### ISSUE TITLE
io.sockets.emit not always received

### ISSUE THREAD

**Issue by btmdave** [socketio/socket.io#1007]
I'm using socket.io v0.9.10 and sometimes emits sent to all connected clients aren't received for whatever reason.  Is there anyway to ensure that a message is always received? I thought that was the default behavior, with volatile being if it's not required, but by default, it seems to be not always ensuring delivery.

Thank you!
Dave

**Comment by dynamodude** [comment]
I have the same problem. Why this issue has been closed?

**Comment by dynamodude** [comment]
I have the same problem
