### ISSUE TITLE
Chain room filters on "clients" and "in" method

### ISSUE THREAD

**Issue by marksyzm** [socketio/socket.io#1052]
The clients method that is used to get all clients or those that belong to a room or namespace seems fundamentally flawed to me... most people that use jQuery and similar libraries expect these things to filter down via a chaining method which is not currently the case. 

So instead of passing an argument to clients, I might prefer to get them from 2-3 sets of rooms i.e.

io.sockets.in('staff').in('room-4').in('threads').emit('notification',data)
var myClients = io.sockets.in('staff').in('room-4').in('threads').clients()

This would allow the user to get a distinct list of clients from a nicely interpretable system, rather than rolling through the difference between 3 sets of rooms. At the moment to do this I have to get all the clients from 'staff', all the clients from 'room-4' and all the clients from 'threads' and then the job is usually to emit to each one. There's probably a better way that I'm missing?

**Comment by JorisD33** [comment]
This feature would be really useful.
