### ISSUE TITLE
Add a way to destroy Namespaces

### ISSUE THREAD

**Issue by hexacyanide** [socketio/socket.io#1069]
I can create namespaces with `io.of('/namespace/);` but I'd like a way to destroy the namespace, server side, so it's not just laying around after I'm done using it.

Aside from that, emitting to a namespace without creating an actual namespace would be nice.

**Comment by gajus** [comment]
@socketio whats the reason this issue got closed?

**Comment by aashidham** [comment]
I want to ask, along with @gajus why this issue was closed.
