### ISSUE TITLE
Massive number of connects/disconnects/reconnects

### ISSUE THREAD

**Issue by plukevdh** [socketio/socket.io#109]
I have a fairly lightly used node client that is seeing a massive number of connections pick up, and then get dropped within 5 seconds. The below shows how many connections are coming in within the same second and the connections being dropped at the same time. Its cycling like this continually and it seems to keep building up. Any ideas why this would be and how to fix it? There should not be that many connections happening that fast. I don't have enough traffic.

2 Dec 14:19:36 - Initializing client with transport "xhr-polling"
2 Dec 14:19:36 - Client 5934382330160588 connected
2 Dec 14:19:36 - Client 9874193754512817 disconnected
2 Dec 14:19:36 - Initializing client with transport "xhr-polling"
2 Dec 14:19:36 - Client 5672581123653799 connected
2 Dec 14:19:36 - Client 108177927788347 disconnected
2 Dec 14:19:36 - Initializing client with transport "xhr-polling"
2 Dec 14:19:36 - Client 8330359337851405 connected
2 Dec 14:19:36 - Initializing client with transport "xhr-polling"
2 Dec 14:19:36 - Client 34990807599388063 connected
2 Dec 14:19:36 - Client 47731158463284373 disconnected
2 Dec 14:19:36 - Client 7410958986729383 disconnected
2 Dec 14:19:36 - Initializing client with transport "xhr-polling"
2 Dec 14:19:36 - Client 8968417742289603 connected
2 Dec 14:19:36 - Client 5835801085922867 disconnected
2 Dec 14:19:36 - Client 5056488991249353 disconnected
2 Dec 14:19:36 - Initializing client with transport "xhr-polling"
2 Dec 14:19:36 - Client 30259388708509505 connected
2 Dec 14:19:36 - Client 5469971175771207 disconnected
2 Dec 14:19:37 - Initializing client with transport "xhr-polling"
2 Dec 14:19:37 - Client 6519975981209427 connected
2 Dec 14:19:37 - Client 21993497852236032 disconnected
2 Dec 14:19:37 - Client 7131864046677947 disconnected
2 Dec 14:19:37 - Initializing client with transport "xhr-polling"
2 Dec 14:19:37 - Client 6924397654365748 connected
2 Dec 14:19:37 - Client 6955256389919668 disconnected
2 Dec 14:19:37 - Client 7434453174937516 disconnected
2 Dec 14:19:37 - Client 5784024992026389 disconnected
2 Dec 14:19:37 - Client 2763416930101812 disconnected
2 Dec 14:19:37 - Client 2166350968182087 disconnected
2 Dec 14:19:37 - Client 7144372051116079 disconnected
2 Dec 14:19:37 - Initializing client with transport "xhr-polling"
2 Dec 14:19:37 - Client 7602915817406029 connected
2 Dec 14:19:37 - Client 9500369024462998 disconnected
2 Dec 14:19:38 - Client 9683964566793293 disconnected
2 Dec 14:19:38 - Client 7162039454560727 disconnected
2 Dec 14:19:38 - Initializing client with transport "xhr-polling"
2 Dec 14:19:38 - Client 3454602954443544 connected
2 Dec 14:19:38 - Initializing client with transport "xhr-polling"
2 Dec 14:19:38 - Client 7020750108640641 connected
2 Dec 14:19:38 - Client 8099637434352189 disconnected
2 Dec 14:19:38 - Client 5114449660759419 disconnected
2 Dec 14:19:38 - Initializing client with transport "xhr-polling"
2 Dec 14:19:38 - Client 09995635529048741 connected
2 Dec 14:19:38 - Client 03352664387784898 disconnected
2 Dec 14:19:38 - Client 6209960258565843 disconnected
2 Dec 14:19:38 - Initializing client with transport "xhr-polling"
2 Dec 14:19:38 - Client 2652831464074552 connected
2 Dec 14:19:38 - Initializing client with transport "xhr-polling"
2 Dec 14:19:38 - Client 9726575431413949 connected
2 Dec 14:19:38 - Client 28504259209148586 disconnected
2 Dec 14:19:38 - Client 7788902383763343 disconnected
2 Dec 14:19:38 - Client 7562073466833681 disconnected
2 Dec 14:19:38 - Initializing client with transport "xhr-polling"
2 Dec 14:19:38 - Client 27854543970897794 connected
2 Dec 14:19:38 - Initializing client with transport "xhr-polling"
2 Dec 14:19:38 - Client 6697496059350669 connected
2 Dec 14:19:38 - Client 21485708048567176 disconnected
2 Dec 14:19:38 - Client 9851685364264995 disconnected
2 Dec 14:19:38 - Client 8138782123569399 disconnected
2 Dec 14:19:38 - Initializing client with transport "xhr-polling"
2 Dec 14:19:38 - Client 7296940605156124 connected

**Comment by xfankit** [comment]
Hello all, 
recently i was facing the same issue. for a quick fix i tried by changing the socket port other than the node port. And as a surprise this issue got resolved. But i want to understand what could be the exact cause of the issue. And how did the port  change resolved the issue. 
Thanks.
