### ISSUE TITLE
callback returning empty object when using Error object

### ISSUE THREAD

**Issue by acc2005** [socketio/socket.io#1111]
I tried passing an Error object in a callback function so I have something like:

socket.on('init', function (data, callback) {
...
  callback(new Error('foo'))
}

However, the client always gets an empty object back as the callback argument. Seems to be only an issue when I use the Error object as passing a String or my own object work fine:

callback('foo')
callback('{message:"foo"}')

On the client side I have

socket.emit('init', {foo:bar}, function(err) {
  console.log(err); // this is always an empty object
})

Any ideas what might be wrong?

**Comment by TehShrike** [comment]
This does not appear to be documented.

Is there any way to do custom serialization?
