### ISSUE TITLE
(node-gyp rebuild 2> builderror.log) || (exit 0)

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io#1126]
```
# npm install socket.io
npm http GET https://registry.npmjs.org/socket.io
npm http 304 https://registry.npmjs.org/socket.io
npm http GET https://registry.npmjs.org/base64id/0.1.0
npm http GET https://registry.npmjs.org/redis/0.7.3
npm http GET https://registry.npmjs.org/socket.io-client/0.9.11
npm http GET https://registry.npmjs.org/policyfile/0.0.4
npm http 304 https://registry.npmjs.org/base64id/0.1.0
npm http 304 https://registry.npmjs.org/redis/0.7.3
npm http 304 https://registry.npmjs.org/policyfile/0.0.4
npm http 304 https://registry.npmjs.org/socket.io-client/0.9.11
npm http GET https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http GET https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http GET https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http 304 https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/zeparser/0.0.5
npm http GET https://registry.npmjs.org/options
npm http GET https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/zeparser/0.0.5
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/tinycolor
npm http 304 https://registry.npmjs.org/commander

> ws@0.4.25 install /root/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

socket.io@0.9.13 node_modules/socket.io
├── base64id@0.1.0
├── policyfile@0.0.4
├── redis@0.7.3
└── socket.io-client@0.9.11 (xmlhttprequest@1.4.2, uglify-js@1.2.5, ws@0.4.25, active-x-obfuscator@0.0.1)
```

**Comment by 3rd-Eden** [comment]
@kaishin Then you should turn off logging while installing modules as npm decides what to show and what not to show.

**Comment by Injac** [comment]
@3rd-Eden  Glad it is not an error. Installed node 0.10.35 on my Galileo and tried to install socket.io as well (and I am a starter, not much experience). That got me confused a bit. But thanks for the clarification.

**Comment by barneycarroll** [comment]
'Not an error' is fair enough and a lot of these logs don't describe any real world problem, but I've got my build executing in Docker like @bcherny – intermittently the Docker boot process goes into an infinite loop immediately after logging the line in the title.

**Comment by barneycarroll** [comment]
FYI in my case it turns out socket.io is just one of several packages whose optional native dependencies crash Docker in certain combinations with other native dependencies being installed concurrently by NPM. So those who are actually suffering from a crash might be looking for [this NPM bug](https://github.com/npm/npm/issues/5400).

**Comment by cavargasp** [comment]
I solved the error in Ubuntu 14.04 with
apt-get install nodejs-legancy

**Comment by danielreisti** [comment]
In my mac, install xcode solved the problem.

**Comment by bfhike** [comment]
on ubuntu 14.04 I needed to create a link in /usr/bin because /usr/bin/env was looking for /usr/bin/node

ln -s /usr/bin/nodejs /usr/bin/node
