### ISSUE TITLE
is there a way to listen for the heartbeat?

### ISSUE THREAD

**Issue by bmatusiak** [socketio/socket.io#1185]
is there a way to listen for the heartbeat event?

i would like to do a `store.session.touch();` during this event

**Comment by ForgeableSum** [comment]
people warned me about socket.io ... why didn't i listen. stuck with no way to listen to pings on the server side. using v. 1.4.5.

**Comment by darrachequesne** [comment]
@ForgeableSum please see the answer [above](https://github.com/socketio/socket.io/issues/1185#issuecomment-46426515)

**Comment by shamun** [comment]
version": "0.9.16" what is the event to catch? is it `socket.on('heartbeat')` or `socket.io.engine.on('heartbeat')` ? anyone aware of it.

**Comment by wong2** [comment]
@shamun it should be the later
