### ISSUE TITLE
Socket.io + SSL + self-signed CA certificate gives error when connecting

### ISSUE THREAD

**Issue by goloroden** [socketio/socket.io#1187]
I am running an https server using a certificate which was created using a self-signed CA certificate.

Now I want to connect Socket.io client to the Socket.io server that is attached to the https server. Unfortunately, I get an error, telling me:

> Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
>     at SecurePair.<anonymous> (tls.js:1271:32)
>     at SecurePair.EventEmitter.emit (events.js:92:17)
>     at SecurePair.maybeInitFinished (tls.js:883:10)
>     at CleartextStream.read [as _read](tls.js:421:15)
>     at CleartextStream.Readable.read (_stream_readable.js:293:10)
>     at EncryptedStream.write [as _write](tls.js:330:25)
>     at doWrite (_stream_writable.js:211:10)
>     at writeOrBuffer (_stream_writable.js:201:5)
>     at EncryptedStream.Writable.write (_stream_writable.js:172:11)
>     at write (_stream_readable.js:547:24)
>     at flow (_stream_readable.js:556:7)

Basically, this error tells me that the certificate could not be verified successfully. This is due to the fact the the according CA certificate is self-signed. When using a https request, I can specify CAs whom I trust.

How can I make Socket.io connect in this case?

PS: I am running Node.js 0.10.0 and Socket.io 0.9.13.

**Comment by dkebler** [comment]
three years later but for any finding this issue like me.  If you need to force client socket to not reject a self-signed server cert you need  `rejectUnauthorized: false`
as in
``` 
const socket = require('socket.io-client')('https://192.168.0.31', { transports: ['websocket'], rejectUnauthorized: false })
```
from https://github.com/socketio/engine.io-client#methods

**Comment by marcortw** [comment]
For security reasons (protection against mitm), you shouldn't use `rejectUnauthorized: false` in any production environment. Instead, the socket.io `ca` option should be used.

If you stumble upon this thread and your socket.io client is a node app, an alternative way is to specify the node environment variable `NODE_EXTRA_CA_CERTS` as documented in https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file

**Comment by outercloudstudio** [comment]
I'm still receiving this problem. I've tried rejectUnauthorized: false and added ca: 'my self signed cert' and withCredentials:true but I still receive the error. Any ideas?

**Comment by darrachequesne** [comment]
@outercloudstudio please check https://socket.io/docs/v4/client-options/#nodejs-specific-options

**Comment by outercloudstudio** [comment]
Just checked the link and I might have an idea that could work. Thanks 👍

**Comment by outercloudstudio** [comment]
After trying what I thought might be the solution it didn't work. A side not after reading some of the options is my client is in the browser and not using node js. My server is. I can't seem to find an example for a self signed certificate that uses the browser as a client.

**Comment by darrachequesne** [comment]
@outercloudstudio oh, OK! In that case, you need to visit the URL of the backend, and allow the connection there:

![image](https://user-images.githubusercontent.com/13031701/149650720-f8c7b119-65d2-43a7-9b23-10e9a60eaeaf.png)

So the self-signed certificate will be trusted by your browser.

**Comment by shulgamalthael** [comment]
Works for me! I used a different domains front/back side.
