### ISSUE TITLE
Does Socket.io working with Phonegap?

### ISSUE THREAD

**Issue by joshbedo** [socketio/socket.io#1195]
I just created an app using Node.js, Express.js, and Socket.io and it works fine even switched hosts over to my ip address for testing on localhost but when I install it with Phonegap it runs but doesn't seem to connect. I also used     io.set('transports', [ 'websocket', 'xhr-polling' ]);

This app is able to be viewed here
https://github.com/joshbedo/chat-app/blob/master/app/server.js

**Comment by MatthewSaxby2** [comment]
Did yhe documentation ever get made. Im working on an multiplayer game and i want the ability for cross platform. Any help is appreciated 🙂
