### ISSUE TITLE
Socket.IO plugin for Cordova

### ISSUE THREAD

**Issue by thebigredgeek** [socketio/socket.io#1204]
Would anyone be interested in developing a Socket.IO plugin for Cordova/Phonegap?  Currently, it defauls to XHR on most Android platforms which is rather slow and defeats the point of using Sockets.  I am interested in building a compatibility layer between phonegap and cordova using java that will enable websockets with socket.io to work on every single android platforms.  And iOS plugin may be a good idea as well.  

There are multiple complaints and articles regarding Socket.IO not working well with PhoneGap due to the XHR fallback.  On my local area network, it takes around 4-5 seconds for my phone to connect to my node server!  That is completely unreasonable!

I think it would be beneficial to provide some sort of plugin or compatibility layer because developers are going to begin switching to other websocket solutions for mobile use.  Socket.IO either needs to use websocket standards and adapt an existing plugin or write a plugin.

Is anyone interested in working on this with me?  I don't think it will take a whole lot of work.  It's mainly just extending the Cordova API and binding those extensions onto the Window Object.  Thanks

**Comment by LanioHe** [comment]
@thebigredgeek that will be more stable than using js version?
