### ISSUE TITLE
Security leak in htmlfile

### ISSUE THREAD

**Issue by tiff** [socketio/socket.io#1251]
We built a basic chat functionality using socket.io (0.9.14).
After some testing we stumbled upon an issue which affects security.
If a user sends a chat message containing `</SCRIPT>` all recipients that are connected via htmlfile will get a javascript error "unterminated string constant". 

This is what the socket.io client is receiving:

``` html
<html><body><script>var _ = function (msg) { parent.s._(msg, document); };</script>
<script>_("1::");</script>
<script>_("5:::{\"args\":[{\"model\":\"messages\",\"payload\":{\"id\":101,\"text\":\"</SCRIPT>\"}}]}");</script>
```

The reason why this breaks is simple:
**Browsers stop parsing inline javascript once they encounter a `</script>` tag.**
(even the github code highlighter does it this way)

With this bug any potential attacker could execute arbitrary javascript on connected clients:

``` javascript
socket.emit("message", "</script><script>alert(document.cookie);</script>")
```

A possible fix would be to escape all forward slahes. So `</script>` becomes `<\/script>`.

**Comment by nasifimtiazohi** [comment]
Hi @rauchg , 

I was trying to locate the 0.9.16 in the release tags but couldn't find it. I find 0.917 after 0.915 in the [release history](https://github.com/socketio/socket.io/releases?after=1.0.0). Sorry to bother but could you help me explaining this? I see the 0.9.16 release in npm versions though.

My interest in this is that I am studying how release logs contain information on security fixes. I see from [here](https://groups.google.com/g/socket_io/c/lk3J-wU9LnU) that 0.9.16 was a security maintenance release. And was trying to figure out if there was a release log associated with this version and if that said anything about the involved security fix or not. 

Through my quick manual search, I also could not locate this vulnerability in Snyk or GitHub advisory database. Was this issue assigned a CVE or reported to any advisory database?

Thanks,
Nasif
