### ISSUE TITLE
Mixed content error with SSL and Vagrant

### ISSUE THREAD

**Issue by ulrichsg** [socketio/socket.io#1299]
I have an app using socket.io along with Express.js for static content. It is running inside a Vagrant box on my development machine.

Now I want to enable HTTPS access. I have created an additional https server for the app which listens on port 443, which my Vagrant box forwards to the host system's port 4443.

Navigating to 'https://localhost:4443' gives me the static content, so the server works fine, but then I get this error:

`Blocked loading mixed active content "http://localhost:4443/socket.io/1/?t=1376058430540"`

The problem, as I understand it, is that socket.io does not realize it is being accessed from a https context. I suspect the port forwarding may be responsible for this. Any idea how to get around it?

**Comment by rendy14s** [comment]
Hallo @ulrichsg sorry for re-open , i got this too.
![socket](https://user-images.githubusercontent.com/10143804/48881189-92093b00-ee46-11e8-943c-0fa647f3d0fb.PNG)
