### ISSUE TITLE
Multiple origins in options

### ISSUE THREAD

**Issue by adammw** [socketio/socket.io#130]
Hi,
Could multiple origins be supported in a later version of Socket.IO-node so we may specify either an array of origins or a comma separated list of origins?

Thanks.

**Comment by vikrantpogula** [comment]
still looking for an update on this

**Comment by LordMajestros** [comment]
The :* is for specifying ports and yes it won't work without it.

**Comment by rakusai** [comment]
@Gut6 FYI, your sample code cause security issues.

`io.set('origins', 'http://domain.com:* http://domain.org:* http://domain.net:* http://domain.gov:*');`

will be processed at here
https://github.com/socketio/socket.io/blob/e0b2cb0c5a9af768a48c43f65643412cc8edc7df/lib/index.js#L87

so `omain.com`, `main.com`,  `ain.com` will be passed.

You must use array instead of string, like this:  
`io.set('origins', ['http://domain.com:*', 'http://domain.org:*', 'http://domain.net:*', 'http://domain.gov:*']);`

**Comment by yuvalkabeli** [comment]
> This won't work in the latest version of `socket.io`.
> 
> You can now pass the array of allowed origins in the io server config like this:
> 
> ```
> const io = require("socket.io")(httpServer, {
>     cors: {
>         origin: ['http://localhost:*', 'http://anotherdomain.com:*'],
>     },
> });
> ```

real good help for me even a year later, thanks!

**Comment by ezraimanuel** [comment]
> > This won't work in the latest version of `socket.io`.
> > You can now pass the array of allowed origins in the io server config like this:
> > ```
> > const io = require("socket.io")(httpServer, {
> >     cors: {
> >         origin: ['http://localhost:*', 'http://anotherdomain.com:*'],
> >     },
> > });
> > ```
> 
> real good help for me even a year later, thanks!

yeppp... the same. many thanks!

**Comment by taffil** [comment]
> This won't work in the latest version of `socket.io`.
> 
> You can now pass the array of allowed origins in the io server config like this:
> 
> ```
> const io = require("socket.io")(httpServer, {
>     cors: {
>         origin: ['http://localhost:*', 'http://anotherdomain.com:*'],
>     },
> });
> ```

This is my code, and wont work on live or dev server
```
const io = require("socket.io")(http, {
    cors: {
        origin: [
            "https://www.domain.com:*",
            "https://www.dev-domain.com:*",
        ],
        methods: ["GET", "POST"],
    },
});
```

**Comment by darrachequesne** [comment]
@taffil this should be:

```js
const io = require("socket.io")(http, {
    cors: {
        origin: [
            "https://www.domain.com",
            "https://www.dev-domain.com",
        ],
        methods: ["GET", "POST"],
    },
});
```

The extra ̀`:*` is not taken in account.

Reference: https://socket.io/docs/v4/server-options/#cors
