### ISSUE TITLE
 websocket cannot work with F5 Networks

### ISSUE THREAD

**Issue by fenfenxu** [socketio/socket.io#1347]
Websocket cannot work when the my program running behind F5 Networks.

First, I'm not sure this is an issue of the socket.io, maybe the configuration of F5 is not correct.

The client can build the ws connection, but message connot be send to the server with the ws connection. After several seconds the ws connection receive close frame.

I debug the ws connection with chrome.

**Comment by john2exonets** [comment]
In F5 BIG-IP v11.4.x and below, you can just test the connection to see if it is a websocket or not using this iRule:

`
when HTTP_REQUEST {
  if { [string tolower [HTTP::header Upgrade]] contains "websocket" } {
    HTTP::disable
    log local0. ">>WebSocket from [IP::client_addr]"
  }
}
`

Add this iRule to an HTTP (port 80) Virtual Server that might get Websocket traffic.  The BIG-IP HTTP Profile in versions before 11.4.1 don't recognize the "Upgrade" from HTTP to TCP, so the WS connection fails without this iRule in place.
