### ISSUE TITLE
How to get client IP address?

### ISSUE THREAD

**Issue by myrtleTree33** [socketio/socket.io#1387]
How do I get a client's IP address?  This does not seem to work: http://stackoverflow.com/questions/6458083/socket-io-get-clients-ip-address

**Comment by lucdetellis** [comment]
None of the things above worked, but I did `console.dir(socket)` and found this:

    io.on('connection', function(socket) {
        var remoteAddress = socket.client.conn.remoteAddress;
        console.log(remoteAddress);
    });

Works for me! (Socket.IO 1.2.1)

**Comment by esquivelgauna** [comment]
socket.handshake.headers.origin

**Comment by bsn0w** [comment]
```js
io.on('connection', function(socket){
  const address = socket.handshake.headers["x-forwarded-for"].split(",")[0];
  console.log(address);
});
```

**Comment by AhCamargo** [comment]
Hi,

I have a problem  between:

Server-socket.io    <---->  Gateway <------>  front-end


how to handshake socket.io server through gateway ?

//My Gateway:

const http = require('http');
const express = require('express')
const httpProxy = require('express-http-proxy')
const app = express()
const cookieParser = require('cookie-parser');
const logger = require('morgan');
const helmet = require('helmet');

const socketServiceProxy = httpProxy('http://localhost:8081');

app.use(logger('dev'));
app.use(helmet());
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());


app.use(function(request, response, next) {
  //response.header("Access-Control-Allow-Origin", "*");
  response.header("Access-Control-Allow-Origin", "http://localhost:3000");
  response.header("Access-Control-Allow-Credentials", true);
  response.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
 });

app.options('/socket', (req, res, next) => {
  socketServiceProxy(req, res, next);

})

const server = http.createServer(app);
const port = 4000;
server.listen(port, () => {
  console.log(`## - API-GATEWAY(Node.JS) - ## Server started on port ${port}!`);
});


//My front:
 const socket = socketIOClient('http://localhost:4000/socket/', {
           
            transports: ['polling-xhr', 'websocket'],
            query: {
              socketId: personId,
            },
          });


//My Backend

https://github.com/AhCamargo/backend-box-transfer/blob/master/app.js

**Comment by radinmoradi** [comment]
در تاریخ جمعه ۱۳ دسامبر ۲۰۱۹،‏ ۲۱:۰۹ André Camargo <notifications@github.com>
نوشت:
