### ISSUE TITLE
Socket connection limit?

### ISSUE THREAD

**Issue by kejyun** [socketio/socket.io#1393]
hi everyone.

There were many connections in state FIN_WAIT2 when my application run about 3 days. #1380  When state FIN_WAIT2 reach some connection limit (I don't know what boundary it is.) And other user will **very difficult to connect socket server**.

``` shell
netstat -anl | grep 10001 | awk '/^tcp/ {t[$NF]++}END{for(state in t){print state, t[state]} }'

FIN_WAIT2 804
LISTEN 1
CLOSE_WAIT 1
TIME_WAIT 31
ESTABLISHED 192
LAST_ACK 1
FIN_WAIT1 4
```

My environment is ubuntu(12.04) , nodejs (v0.10.22) and socket.io (v0.9.16) in AWS EC2 small instance. I never change ubuntu tcp/ip configuration.

**Is that socket problem? Or should I tune tcp/ip configuration??**

thanks.

**Comment by qgicup** [comment]
That's a good insight @kejyun, thanks !
