### ISSUE TITLE
/socket.io/socket.io.js https request aborted (socket.io v0.9.16)

### ISSUE THREAD

**Issue by FruityXXL** [socketio/socket.io#1405]
Hi!

Im running my webserver and the socket.io server (v0.9.16) on different machines and want to initiate a secure connection.
The socket.io server is reachable but does not serve the socket.io.js client file. The https request will be aborted every time.

Server:

var options, app, server, io;

options = {
    key: fs.readFileSync('key.pem'),
    cert: fs.readFileSync('cert.pem'),
    ca: fs.readFileSync('cert.pem'),
    rejectUnauthorized: false
}

app = require('express')();
server = require('https').createServer(options, app);
server.listen(port);
io = require('socket.io').listen(server);

io.set('origins','*');
io.set('transports', [
    'websocket'
    , 'flashsocket'
    , 'htmlfile'
    , 'xhr-polling'
    , 'jsonp-polling'
]);

Client:

<script type="text/javascript" src="https://domain:port/socket.io/socket.io.js"></script>

socket = io.connect(https://domain:port, { secure : true });

Thanks for your support!

**Comment by oganbat** [comment]
is this same error?

![untitled](https://cloud.githubusercontent.com/assets/4508233/7290394/92fde838-e9b0-11e4-9454-dbe12b41beae.png)
