### ISSUE TITLE
"io is not defined"

### ISSUE THREAD

**Issue by TrangNguyen** [socketio/socket.io#1418]
Hi,

I'm trying to integrate the mean stack (linnovate) with socket.io and I got this error " io is not defined". The issue is also referenced here https://github.com/linnovate/mean/issues/272.

```
//server.js
var server = require('http').createServer(app);
var io = require('socket.io').listen(server, {
    'log level': 2
});
io.sockets.on('connection', function(socket) {
    console.log('Client Connected');
}); //<<<<<< 'socket' is defined but never used (linting error)
...
server.listen(port); 
```

```
//public/js/services/socket.js
angular.module('mean.socket').factory('socket', ['$rootScope',  function ($rootScope) {
    var socket = io.connect();
    return {
... // like Brian Ford did
    }
}]);
```

```
// app/views/includes/foot.html which feeds into the index.html
<script type="text/javascript" src="/socket.io/socket.io.js"></script>
<script type="text/javascript" src="/js/services/socket.js"></script>
```

```
// public/js/app.js
angular.module('mean', ['ngCookies', 'ngResource', 'ngRoute', 'ui.bootstrap', 'ui.route', 'mean.system', 'mean.articles', 'mean.socket']);
angular.module('mean.socket', []);
```

This is the error

```
Linting server.js ...ERROR
[L56:C44] W098: 'socket' is defined but never used.
io.sockets.on('connection', function(socket) {
Linting public/js/services/socket.js ...ERROR
[L4:C18] W117: 'io' is not defined.
  var socket = io.connect();
```

I don't know what I am missing. I have no error consoled to the browser, socket.io.js is loaded properly, socket.io starts server side but nothing works. I have tried to give specific url to io.connect(), load socket.io.js from cdn but it doesn't change.  'io is not defined', what does it mean, any help, any hint greatly appreciated.
Trang

**Comment by 01001000M** [comment]
while having your src codes in another path than the root dir then you have to specify the full path so :

instead of <script type="text/javascript" src="/socket.io/socket.io.js"></script>

try : <script type="text/javascript" src="http://[yourDomain]/socket.io/socket.io.js"></script>

**Comment by Anachron** [comment]
You're a bot, no? 

Why do you reply to a 7 year old thread with no meaningful reply whatsoever?

**Comment by at-r00t** [comment]
we can't confirm neither deny ..
