### ISSUE TITLE
Access-Control-Allow-Origin - not possible to host application clients on other hosts

### ISSUE THREAD

**Issue by gcmartijn** [socketio/socket.io#1442]
I don't know if its an issue or a 'feature' but in the old version I can do something like:
io.set('Origin':'*')

The reason to do this is because our application will be hosted on many different hostnames (websites) (origins). And only one server host.

In other words, its not possible to host our application clients on other hosts.

We don't use express or other modules, to keep it as clean as possible.
request_handler = require('./request_handler');

```
            inspect = require('util').inspect;
            app = require('http').createServer(request_handler.handler);
            io = require('socket.io').listen(app,{
                    'pingTimeout':60000,
                    'transports':['xhr-polling','polling', 'websocket', 'flashsocket'],
                    'pingInterval':25000,
                    'allowUpgrades':true,
                    'cookie':'io'
            });
```

app.listen(8090);

The error we get is:
OPTIONS http://**_serverhost**__:8090/socket.io/?EIO=2&transport=polling&sid=DWGmxtENtfqN_h1GAAAA No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://_**clienthost****' is therefore not allowed access. v1.js?c=b3f0c7f6bb763af1be91d9e74eabfeb199dc1f1f:5798
XMLHttpRequest cannot load http://**_serverhost_**_:8090/socket.io/?EIO=2&transport=polling&sid=DWGmxtENtfqN_h1GAAAA. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://**_clienthost****' is therefore not allowed access.
- I removed the original serverhost name and clienthost

**Comment by shades3002** [comment]
yo lo solvente asi: 
1) npm install cors
2) var cors = require('cors');
3)app.use(cors());

**Comment by zardoz** [comment]
Pero esto no es muy seguro, tienes que specificar el domain. En este caso todo esabierto.

This is not very secure, you should specify the domain. In this case everything is open

**Comment by shades3002** [comment]
Claro pero eso lo configura uno de acuerdo a su necesidad https://www.npmjs.com/package/cors aqui aparece como configurar de manera personalizada. Saludos..
