### ISSUE TITLE
Callbacks that are defined on the server and sent to the client do not make it to the client listener. I've included a link to a repository that reproduces the bug in a clean environment.

### ISSUE THREAD

**Issue by BeekeeperAlex** [socketio/socket.io#1444]
I can do callbacks from the client to the server but I can't do callbacks that are defined on the server and sent to the client. The client listener doesn't receive the callback function in its arguments even though it receives all other arguments. The callback function just vanishes.

There is a workaround, but it's not the most elegant.

Instead of:

``` js
// server
socket.emit('someEvent', function () {
    console.log("Callback ran on server...");
});
```

``` js
// client
socket.on('someEvent', function (callback) {
    callback(); // fails because callback is undefined
});
```

You can work around the issue with a second event, like this:

``` js
// server
socket.emit('someEvent');
socket.on('someEventComplete', function () {
    console.log("Complete event ran on server...");
});
```

``` js
// client
socket.on('someEvent', function () {
    socket.emit('someEventComplete');
});
```

The problem with this "workaround" is that it creates a race condition in some situations. For example, if I fire `someEvent` multiple times in a row it's possible that my return calls to `someEventComplete` will be fired out of order and I won't know which ones correspond to the other.

For those of you who want to work around this race condition issue, this should get you started:
1. Generate some kind of unique identifier (combination of socket ID and event ID is probably good).
2. Register a one time event listener that listens for an event with the name of the unique identifier.
3. Send the unique identifier to the client along with any other arguments you need to send.
4. When the client is ready to reply, emit an event using the identifier handed down by the server as the name.

Now you know which replies correspond to which handler invocations. It should work, but it's pretty gross and cumbersome.

---

I can confirm that the reverse (client to server)...

``` js
// client
socket.emit('someEvent', function () {
    console.log('Callback ran on client...');
});
```

``` js
// server
socket.on('someEvent', function (callback) {
    callback();
});
```

...works just as it should. It's only when the callback is defined on the server and sent to the client that it fails.

---

I really want to see this issue fixed so I went the extra mile and created [a project that reproduces the bug](https://github.com/chevex-archived/socketio-bug-1444). To run it:
1. Clone the repsitory.
2. npm install
3. node app.js
4. Go to http://localhost:3000/

You'll see a callback sent to the server and successfully executed. Then you'll see a callback sent to the client, which fails because it is undefined.

**Comment by Nathan1258** [comment]
Well it's been 6 years and still go work around.... https://stackoverflow.com/questions/62934533/is-it-possible-to-do-a-server-side-callback-within-socket-io
