### ISSUE TITLE
Uncaught TypeError: Object #<Namespace> has no method 'clients'

### ISSUE THREAD

**Issue by chriskilding** [socketio/socket.io#1450]
The ability to get all clients in a room with the following calls described in the wiki has been broken:
- `io.sockets.clients('room')`
- `io.of('namespace').clients('room')`

If you run the following test, it will fail when run against the latest git master with the reason "Uncaught TypeError: Object #<Namespace> has no method 'clients'":

```
it('should return the sockets in a room', function(done){
var srv = http();
var sio = io(srv);
var roomId = 'socketsInRoom';

sio.on('connect', function (socket) {
  socket.join(roomId, function () {
    expect(sio.sockets.clients(roomId)).to.contain(socket);
    done();
  });
});

srv.listen(function(){
  client(srv);
});
});
```

Was this functionality removed intentionally, or just accidentally because there was no spec testing for the `clients` function?

**Comment by wamoyo** [comment]
I had this issue too, Thanks Lucas! This blog post should be updated: http://www.html5rocks.com/en/tutorials/webrtc/infrastructure/ Will let them know.
