### ISSUE TITLE
1.0.0 Replacements for socket.set() and socket.get()

### ISSUE THREAD

**Issue by doughsay** [socketio/socket.io#1481]
You used to be able to store arbitrary data along with a socket, using `socket.get(key, callback)` and `socket.set(key, value, callback)`.  How can we do this in 1.0.0?

Just setting random values on the socket seems to work, but doesn't sound safe. e.g. `socket.foo = 'bar'`.

**Comment by lukewendling** [comment]
Any resolution or best practice for replacing old .set() and .get() -> we should instead use a prop directly on client object? Is there a module ( as mentioned above ) that does this more elegantly?
