### ISSUE TITLE
socket.io 1.0.0-pre1 whats the best way to get ip address of client connected

### ISSUE THREAD

**Issue by ziaaddils** [socketio/socket.io#1483]
I've been diving into the "socket" object returned on connection on the server to try and find the ip address of that connected socket with no luck.

how do we find the ip address and port from the socket irrelevant of the transport being used?

**Comment by lucdetellis** [comment]
None of the things above worked, but I did `console.dir(socket)` and found this:

    io.on('connection', function(socket) {
        var remoteAddress = socket.client.conn.remoteAddress;
        console.log(remoteAddress);
    });

Works for me! (Socket.IO 1.2.1)

**Comment by rauchg** [comment]
Thanks @lucdetellis for contributing your findings on the existing issues. Will be helpful to many

**Comment by antraxa** [comment]
I have the same problem with Socket.io 1.3.3  and nothing works to obtain the ip address client.

Any other suggestion, please?
