### ISSUE TITLE
Could not parse the socket's cookie into a sessionID

### ISSUE THREAD

**Issue by kitemao** [socketio/socket.io#1494]
hi,  Just a error, I dont known why

error: Could not load session for socket #zTy6SEkFFgYFcKX5WUEP Could not parse the socket's cookie into a sessionID.
error: TypeError: Cannot call method 'indexOf' of undefined

**Comment by khmereshop** [comment]
In Angularjs , google added a cookie in the page like this _ga=GA1.1.1279493516.1422988925 for Safari browser . I ran to the same issue with socket.io .  I try to pass cookie the server like this 
url?cookie=cookiename . But I still ran to the same issue. I am using the sails js 0.10.5 version. What is the best way to fix this. I can't remove _ga cookie either.

**Comment by aaronjhoffman** [comment]
@khmereshop - did you end up resolving this? I've having the same exact error and not using GA but I use mixpanel in my case....I'm not sure if that's related but would be curious how you resolved? Thanks in advance
