### ISSUE TITLE
1.0.0-pre "Session ID unknown"

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io#1503]
HTTP Response
{"code":1,"message":"Session ID unknown"}

DEBUG=socket.io:*

 socket.io:socket joined room 2d1DHsPAtc1Sspm6AAAE +0ms
  socket.io:server incoming connection with id rwLW7JMBp6E4TyexAAAG +3s
  socket.io:client connecting to namespace / +3s
  socket.io:namespace adding socket to nsp / +3s
  socket.io:socket socket connected - writing packet +3s
  socket.io:socket joining room rwLW7JMBp6E4TyexAAAG +0ms
  socket.io:client writing packet {"type":0,"nsp":"/"} +1ms
  socket.io:client writing packet {"type":2,"data":["news",{"hello":"world"}],"nsp":"/"} +0ms
  socket.io:socket joined room rwLW7JMBp6E4TyexAAAG +1ms
  socket.io:server incoming connection with id 03Izy4YOxaYm5-d-AAAH +1s
  socket.io:client connecting to namespace / +1s
  socket.io:namespace adding socket to nsp / +1s
  socket.io:socket socket connected - writing packet +1s
  socket.io:socket joining room 03Izy4YOxaYm5-d-AAAH +0ms
  socket.io:client writing packet {"type":0,"nsp":"/"} +1ms
  socket.io:client writing packet {"type":2,"data":["news",{"hello":"world"}],"nsp":"/"} +0ms

And socket is disconnected immediately

**Comment by marcochavezf** [comment]
https://devcenter.heroku.com/articles/node-sessions

**Comment by marcelaraujo** [comment]
+1

**Comment by 1j01** [comment]
@gonzalodiaz Thank you for mentioning `transports: ['websocket']`

**Comment by ecdeveloper** [comment]
For those who are having this issue under a amazon ELB, make sure you enable application-controlled session stickiness (http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-sticky-sessions.html). This solved the problem for me.

**Comment by oleksijfomin** [comment]
Guys read this article https://devcenter.heroku.com/articles/node-websockets
In the end you will find *Apps using Socket.io should enable session affinity*
Then proceed to https://devcenter.heroku.com/articles/session-affinity
Then put in Heroku Toolbelt CLI `heroku features:enable http-session-affinity --app APP`
And I'm happy with working socket.io on scaled dynos.

**Comment by web5** [comment]
@p3x-robot  I was fixed by this method

**Comment by two-bit-stdclass** [comment]
I think this https://nodeer.space/questions/the-process-of-extracting-or-breaking-down-the-socketio-handshake-cookie could streamline your process
