### ISSUE TITLE
IMPORTANT, date type broken when response callback is used

### ISSUE THREAD

**Issue by juleq** [socketio/socket.io#1518]
Hello there,

I just figured out that socket.emit (server->client) works fine for the JS date type, but when the response callback functionality is used (client->server->client), socket.io breaks the date by instantiating a new, empty object. Issue seems to be somewhere near deconstructPacket (wild guess).

The problem is definitely at the server-side. I have verified that by inspecting the WebSocket frames.

**What works:**
_Client:_ 

```
socket.emit('dateRequest', params);
socket.on('dateResponse', function responseHandler(response){
    console.log(response); // -----> outputs the correct date
});
```

_Server:_

```
socket.on('dateRequest', function dateRequestHandler(params){
    socket.emit('dateResponse', new Date());
});
```

**What does not work:**
_Client:_

```
socket.emit('dateRequest', params, function responseCallback (response){
    console.log(response); // -----> outputs empty {}
});
```

_Server:_

```
socket.on('dateRequest', function dateRequestHandler(params, callback){
    callback(new Date());
});
```

I was testing my migration from 0.96 to 1.0 pre2 when this occurred.

In JavaScript the date type is represented by the type object but it has no own properties -> it can´t be copied by iterating the keys (which you would normally expect to be a valid approach to copy an object). Maybe this is the cause for this flaw?

**Comment by SilverSeva** [comment]
This issue still persists in v4.5.1. Empty date on callback

**Comment by darrachequesne** [comment]
@SilverSeva I can't reproduce:

Client:

```js
import { io } from "socket.io-client";

const socket = io("http://localhost:3000");

socket.emit("test", new Date(), (res) => {
  console.log(res);
});
```

Server:

```js
import { Server } from "socket.io";

const io = new Server(3000);

io.on("connection", (socket) => {
  socket.on("test", (value, callback) => {
    console.log(val);
    callback(new Date());
  });
});
```

The dates are stringified though, as mentioned in the documentation: https://socket.io/docs/v4/emitting-events/#basic-emit

Could you please check?

**Comment by SilverSeva** [comment]
> @SilverSeva I can't reproduce:
> 
> Client:
> 
> ```js
> import { io } from "socket.io-client";
> 
> const socket = io("http://localhost:3000");
> 
> socket.emit("test", new Date(), (res) => {
>   console.log(res);
> });
> ```
> 
> Server:
> 
> ```js
> import { Server } from "socket.io";
> 
> const io = new Server(3000);
> 
> io.on("connection", (socket) => {
>   socket.on("test", (value, callback) => {
>     console.log(val);
>     callback(new Date());
>   });
> });
> ```
> 
> The dates are stringified though, as mentioned in the documentation: https://socket.io/docs/v4/emitting-events/#basic-emit
> 
> Could you please check?

Hi Damien,

Thanks for the answer.

It seems like the problem is with socket.io-stream

Client:

`
import { io } from 'socket.io-client'
import ss from 'socket.io-stream'

const socket = io("http://localhost:3000");
const stream = ss.createStream()
ss(socket).emit('test', stream, { date: new Date() }, res => {
   console.log(res)
})
`

Server:


`
import { Server } from "socket.io";
 
const io = new Server(3000);
io.on("connection", function(socket){
  const ss = require('socket.io-stream')
  ss(socket).on("test", (stream, data, callback) => {
    console.log(data.date);
    callback(new Date());
  });
`
