### ISSUE TITLE
io configure - socket io v1.X

### ISSUE THREAD

**Issue by dsalcedo** [socketio/socket.io#1542]
What is the example configuration for do this in socket io v1.X.X ?

``` javascript
//this is configuration for socket.io v0.9.X<
io.configure('production', function () {
        io.enable('browser client minification');
        io.enable('browser client etag');
        io.enable('browser client gzip');
        io.set('log level', 1);
        io.set('transports', ['websocket', 'flashsocket', 'htmlfile', 'xhr-polling', 'jsonp-polling']);
    });
```

**Comment by benissimo** [comment]
Referring us to a CDN doesn't answer the question. We may want to continue to host the client library ourselves. The loss of options for minification, etag, gzip is a step backwards.

**Comment by rauchg** [comment]
@benissimo you can trivially serve it with any static files serving middleware, which is bound to do a better job than socket.io at serving it.

**Comment by benissimo** [comment]
Thanks for responding so quickly! :)
I can understand if you prefer to slim down socket.io so as to focus on the core.
I think it would help if the "migrating from 0.9" page listed more of these kinds of gotchas, ie: if you want the client minified, you'll now have to either rely on the CDN or do it yourself.

Also this ticket asked about an equivalent to io.configure(), ie. a way to pass in options based on an environment. Has that been dropped too? The "migrating from 0.9" page mentions that io.set() is gone and says to instead pass options in the server initialization. Reading between the lines, does this mean that io.configure() should be replaced by do-it-yourself contextual setup of the server initialization? (For example if we want to enable different transports in production env as opposed to test, etc.)
