### ISSUE TITLE
Joining same room more then once and clients in a room

### ISSUE THREAD

**Issue by ismarslomic** [socketio/socket.io#1544]
I'm trying to figure out what happens if the clients emits to join the same room more then once, To test and find answer on this I wanted initially to find out how many clients room has after same clients send more then one emit for joining the room, but [Rooms chapter in wik](https://github.com/Automattic/socket.io/wiki/Rooms#clients-in-a-room)i is outdated. When I try to use `io.sockets.clients('room')` I get `Object #<Namespace> has no method 'clients'`.

So I got two questions:
1. what happens if client tries to join same room more then once? Will he get emits for that room for each time he has tried to join?
2. How can I find out which clients are in a room?

Im using socket.io v1.0.2

**Comment by crisu** [comment]
![image](https://github.com/user-attachments/assets/3417a82a-f193-4591-9908-7d3a4f3d40db)
![image](https://github.com/user-attachments/assets/f292baf9-e5e9-4b79-9a01-cf5d5e631e25)
more joins => more clients => more signals
