### ISSUE TITLE
I can't connec to host in v1.0.X

### ISSUE THREAD

**Issue by diegoug** [socketio/socket.io#1556]
Y have a problem in connection versión 1.0 that I dont had in the versión 0.9.X.

I have Django running in http://app.myhost.com and my node server in http://live.myhost.com:8001

Before I could connect me to the socket.io server v0.9.x like:
Client:
io.connect(//live.myhost.com:8001);
server:
io = require('socket.io')(port)
io.set('transports', ['websocket', 'flashsocket', 'htmlfile', 'xhr-polling', 'jsonp-polling']);

but now I have a problem (not taking the live url correctly):
GET http://app.myhost.com:8000/socket.io/?EIO=2&transport=polling&t=1401468282894-1 404 (NOT FOUND)

if I rewrite (io.connect(http://live.myhost.com:8001)) now have a new problem:
XMLHttpRequest cannot load http://live.myhost.com:8001/socket.io/?EIO=2&transport=polling&t=1401468608168-1. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://app.myhost.com' is therefore not allowed access. 

in debug mode to socket.io I have more info:
engine:core intercepting request for path "/socket.io/" +0ms
engine handling "GET" http request "/socket.io/?EIO=2&transport=polling&t=1401470024479-48" +0ms
engine unknown transport "polling" +3ms

**Comment by falafflepotatoe** [comment]
require('socket.io')(somemagicvar)... is undebuggable because you have 20 magic vars.

    socket.foo(x)
    or io.connection((socket) => socket.on('foo', bar)
    or socket(foo)(bar).connection(baz, (x) => socket.on(bar, foo))
?? this is undebuggable and unintelligable to me. humbley, please pick one paradigm.

eio.connect(localhost:8080) // 404 + XCORS error  ... is undebugabble...

thumbs down.

**Comment by falafflepotatoe** [comment]
@neckle using client side: `io.connect('localhost:port')` worked for me.

it should be `ws://url` or name:port

also i had to DL the socket.io.js script from the downloads page cdnjs.com link, the engine-io.js repository script linked is not working.

also client side
    var socket = io(url)
    socket.on('connect', function() { ... })

doesnt work, its too fast. `socket = io(url).on('connect, function(){..})`... works.
