### ISSUE TITLE
where did v0.9.16 go?

### ISSUE THREAD

**Issue by gantaa** [socketio/socket.io#1558]
Karma (https://github.com/karma-runner/karma/blob/master/package.json)

is pointed to the latest 0.9 version.  When 0.9.17 was released, socket.io started disconnecting karma.  I noticed there is no 0.9.16 tag under releases for this repo.  It had to have been there recently because my backed up working version of karma used socket.io v0.9.16

Any ideas?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
