### ISSUE TITLE
docs don't explain how to close a server in 1.0

### ISSUE THREAD

**Issue by jcollum-hcg** [socketio/socket.io#1559]
I'm instantianting a socket like so: 

```
this.socketLib || (this.socketLib = require('socket.io'));
this.socket = this.socketLib.listen(this.port);
```

Elsewhere in the object, I have a close function. I've tried the following to close the socket: 

```
this.socket.close() # TypeError: Object #<Server> has no method 'close'
this.socket.server.close() #  TypeError: Object #<Server> has no method 'close'
this.socket.server.disconnect() #  TypeError: Cannot call method 'disconnect' of undefined
this.socket.disconnect() # TypeError: Object #<Server> has no method 'disconnect'
this.socket.io.engine.close() # TypeError: Cannot read property 'engine' of undefined
```

In 0.9, fairly simple: `this.socket.server.close()`

There are occurrences of `disconnect` in the codebase, but they are for the client it seems: ([link](https://github.com/Automattic/socket.io/search?q=disconnect&ref=cmdform)). Same thing for `close`, basically. Or I'm not seeing it. 

I've debugged and poked around in the objects and not found anything that closes the server. 

How do I close the socket server in the new codebase? I need to shut it down for integration testing (1st test run passes, 2nd run gets `EADDRINUSE` error). I'm trying to write a close function that I can run in my `after` function in mocha. My tests pass if I run them without `--watch`. It's just the multiple successive runs that are failing.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
