### ISSUE TITLE
[Documentation] How to set log level in v1

### ISSUE THREAD

**Issue by Maxwell2022** [socketio/socket.io#1564]
I have an issue with `log level` settings. I use to set it like this:

``` js
io.set('log level', 1);
```

But now the server is returning an warning:

> Option log level is not valid. Please refer to the README.

When I referred to the README I could not find any reference of `log level`.
I've also search in the source of socketio and could not find anything.

What is the equivalent of this option in `v1`?

Cheers, 
Maxime

**Comment by MrShadowGames** [comment]
"We'll document this on the website under /docs/debugging"

This page can't be found. For a newcomer to node.js this is bad documented. Still no idea what specific notation is expected after DEBUG= ...

**Comment by jecompton** [comment]
@MrShadowGames Don't put it in your code. Just use it from the command line. So it would look like:

$ DEBUG=* node chat_ui.js

Where the '$' is the command prompt.

**Comment by phavor** [comment]
I've been having the same issue, I've tried implementing the corrective measures on this page and yet I get the optional warning message ultimately causing my app not to function. How do I really fix this?

**Comment by trinhvinhtruong96** [comment]
The command can only be used with version 1.0. I believe we do not need to set the log level with the higher version. So, I believe you should just delete the set log level instruction.
