### ISSUE TITLE
WebSocket connection failed: WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by a2prn** [socketio/socket.io#1567]
Hi,

I have a nodejs cluster setup at my side. That is, I have multiple nodejs instances clustered in nginx as reverse proxy. Also websockets is reverse proxied by nginx. When I have only 1 nodejs instance and when I am accessing it using nginx, all my client-server socket connection work smoothly. But when I have multiple node instances, it gives me following error-

WebSocket connection to 'wss://192.168.0.10:8085/socket.io/1/websocket/KhOMMm0pGQbrntuI1xnW' failed: WebSocket is closed before the connection is established.

In my server side console I can see that data is coming from one client. And at another client's web console I see "disconnect" message and then above error.

I am stuck because of this error. Can anybody please guide me with why is this error occured when I cluster nodejs instances? What is the solution.

**Comment by mikermcneil** [comment]
Hi @a2prn, sounds like you need to use [socket.io-redis](http://socket.io/docs/using-multiple-nodes/).  In general, this seems like the type of post that would be more well-suited for StackOverflow or the Socket.io Slack channel.  Would you mind closing this issue?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
