### ISSUE TITLE
big trouble with simple socket.io server (v1.0.2), Access-Control-Allow-Origin Problem

### ISSUE THREAD

**Issue by Dream-Work** [socketio/socket.io#1579]
i use a simple socket.io server with following code

``` js
var io         = require('socket.io')(8085);
var socketioRedis = require('socket.io-redis');
io.adapter(socketioRedis({
  socket: '/tmp/redis.sock'
}));
```

and in my chrome console i show this error:
XMLHttpRequest cannot load http://10.100.2.155:8085/socket.io/?EIO=2&transport=polling&t=1401702906178-35&sid=twzS74w7EAEs-nRkAAAA. No 'Access-Control-Allow-Origin' header is present on the requested resource.

How can i solve this big problem ??

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
