### ISSUE TITLE
Error: Cannot find module 'engine.io' - chat example

### ISSUE THREAD

**Issue by pawski** [socketio/socket.io#1581]
I have just cloned socket.io repository and tried to run example (from within socket.io/examples/chat directory) by following instructions in readme file. Unfortunately after running `node .` i get this message:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'engine.io'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pczyzewski/socket.io-master/lib/index.js:9:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

node - v0.10.28

The same thing is happend on osx and freebsd.

I am quite new to node, so it`s possible that i have omitted something.

**Comment by shnigi** [comment]
Could you add to readme that the npm install needs to be run at the root folder first, I was confused too.

**Comment by Williaan** [comment]
This is very simple to solve.
In your examples / chat folder, open the index.js file and change these lines of code.

before
`Var io = require ('../ ..') (server);`

after
`Var io = require ('socket.io') (server);`

And that's it, it's working!

**Comment by PremkumarAgrawal** [comment]
@Williaan Great man its solved

**Comment by pragatiUiDeveloper** [comment]
I am facing same issue...Please help..
npm install output:

C:\Users\pc8\Desktop\socket.io-master\examples\chat>npm inst
socket.io-chat@0.0.0 C:\Users\pc8\Desktop\socket.io-master\e
`-- express@4.13.4
  +-- accepts@1.2.13
  | +-- mime-types@2.1.16
  | | `-- mime-db@1.29.0
  | `-- negotiator@0.5.3
  +-- array-flatten@1.1.1
  +-- content-disposition@0.5.1
  +-- content-type@1.0.2
  +-- cookie@0.1.5
  +-- cookie-signature@1.0.6
  +-- debug@2.2.0
  | `-- ms@0.7.1
  +-- depd@1.1.1
  +-- escape-html@1.0.3
  +-- etag@1.7.0
  +-- finalhandler@0.4.1
  | `-- unpipe@1.0.0
  +-- fresh@0.3.0
  +-- merge-descriptors@1.0.1
  +-- methods@1.1.2
  +-- on-finished@2.3.0
  | `-- ee-first@1.1.1
  +-- parseurl@1.3.1
  +-- path-to-regexp@0.1.7
  +-- proxy-addr@1.0.10
  | +-- forwarded@0.1.0
  | `-- ipaddr.js@1.0.5
  +-- qs@4.0.0
  +-- range-parser@1.0.3
  +-- send@0.13.1
  | +-- destroy@1.0.4
  | +-- http-errors@1.3.1
  | | `-- inherits@2.0.3
  | +-- mime@1.3.4
  | `-- statuses@1.2.1
  +-- serve-static@1.10.3
  | `-- send@0.13.2
  +-- type-is@1.6.15
  | `-- media-typer@0.3.0
  +-- utils-merge@1.0.0
  `-- vary@1.0.1
________________________________________________________
npm start throwing error:


C:\Users\pc8\Desktop\socket.io-master\examples\chat>npm start

> socket.io-chat@0.0.0 start C:\Users\pc8\Desktop\socket.io-master\examples\chat

> node index.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'socket.io'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\pc8\Desktop\socket.io-master\examples\chat\i
ndex.js:5:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! socket.io-chat@0.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the socket.io-chat@0.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the socket.io-chat packag
e,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs socket.io-chat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls socket.io-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\pc8\Desktop\socket.io-master\examples\chat\npm-debug.log

C:\Users\pc8\Desktop\socket.io-master\examples\chat>

**Comment by pragatiUiDeveloper** [comment]
it worked ,
i did following:
C:\Users\pc8\Desktop\socket.io-master\examples\chat>npm install
C:\Users\pc8\Desktop\socket.io-master\examples\chat>npm install socket.io --save
C:\Users\pc8\Desktop\socket.io-master\examples\chat>npm install enjine.io --save
C:\Users\pc8\Desktop\socket.io-master\examples\chat\node_modules\engine.io>npm install
C:\Users\pc8\Desktop\socket.io-master\examples\chat>npm start

**Comment by arkceajin** [comment]
@pragatiUiDeveloper  
Please change 
`npm install enjine.io --save`
to
`npm install engine.io --save`

**Comment by ilovejs** [comment]
var io = require ('socket.io') (server);
> brew install nvm
> nvm install --lts
> node -v      give me 10.7.0
> npm audit fix
> npm install
> npm start

working !!
