### ISSUE TITLE
On-Click A-tag with Href, socket gets disconnected

### ISSUE THREAD

**Issue by harpreetkhalsagtbit** [socketio/socket.io#1585]
I have a project using socket.io. I want to give user some links to download a file as

    <a href="<path>" >Link Name</a>

When I click on link to download file, my **socket** gets disconnected and does not re-connect.
When I use this

    <a href="<path>" target="_blank">Link Name</a>

it works fine. Any reason why this happens or its a bug?

**Comment by ekeren** [comment]
@agoldis && @Kerez FYI

**Comment by harpreetkhalsagtbit** [comment]
@digitalfrost 
Yes you can close this ticket.

This resolved my issue at that time
http://stackoverflow.com/questions/24009218/on-click-a-tag-with-href-socket-gets-disconnected
