### ISSUE TITLE
Problem on Android browser 4.3 when 'desktop view' is checked

### ISSUE THREAD

**Issue by cbmke** [socketio/socket.io#1587]
Socket.io works fine when 'desktop view' is not enabled.
When it is enabled client messages do not reach the server.
(Checked it on Galaxy SIII and Acer A200 tablet)

Interestingly enough the connection seems to be alive even in 'desktop view' mode because the client can receive 'emit' messages from server.

Anyone know anything about this?

**Comment by rase-** [comment]
Are you still having this problem, @cbmke?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
