### ISSUE TITLE
socket.io 1.0 with titanium (appcelerator)

### ISSUE THREAD

**Issue by fadaytak** [socketio/socket.io#1590]
exist a version of socket.io 1.0 to use with titanium (appcelerator) ?

or can we use 0.96 client with 1.0 server ?

cordially

**Comment by DouglasHennrich** [comment]
Any news about this threat?
I reaaaally need socket.io 1.0 on titanium =/

**Comment by WillDent** [comment]
@yuchi did you make any progress on this?  Do you have some code that is partially working and/or that you can share and maybe others can help/contribute?

**Comment by rishikatyal117** [comment]
Any Success ?? Is there Socket.io client for Titanium now ? My Server is on Socket.io 1.4.5.

**Comment by AppWerft** [comment]
Maybe (idea) we looking to Titanium pubnub implemenation. This is done with pure TiJS:
https://github.com/pubnub/javascript/blob/master/titanium/lib/platform.js

**Comment by yagitoshiro** [comment]
I'm working on this and wrote a module. It's working so far. Stay tuned.

**Comment by AppWerft** [comment]
Thanks

**Comment by yagitoshiro** [comment]
@AppWerft By now it supports only iOS and installation process is so complicated. And many functions are left undone, but works.

https://github.com/yagitoshiro/TiSocketIOClient

```javascript
var socket, io;

io = require('ro.toshi.ti.mod.tisocketio');
socket = io.createSocket({
  url: 'http://localhost:9999/'
});

socket.on('connect', function(){
  Ti.API.info('connected');
  socket.emit('fromClient', {message: 'Hello'});
});

socket.on('message', function(e){
  Ti.API.info(e);
});

socket.connect();

$.index.addEventListener('close', function(){
  socket.disconnect();
});
```

**Comment by DouglasHennrich** [comment]
Any news?

**Comment by janvennemann** [comment]
Just in case someone stumbles upon this, there is an official module by now: https://github.com/appcelerator-modules/titanium-socketio
