### ISSUE TITLE
Namespace except method was removed in 1.0.x

### ISSUE THREAD

**Issue by coulix** [socketio/socket.io#1595]
What worked before:

```
io.of('/foo').in(room).except(socketId).emit(event, data);
```

Does not work anymore with 1.0.x, except is unknown.

This fails at well:

```
io.of('/foo').broadcast.to(room).emit(event, data);
//'TypeError: Cannot call method \'to\' of undefined',
```

How can we broadcast from a io.of('/foo').in(room) ?

**Comment by buunguyen** [comment]
+1, really need this functionality. The use case (multi-nodes with Redis adapter) is this:

* A transaction starts with REST API via HTTP and sends socket.id via header
* Within the API controller method, emit to a room, but want to avoid broadcasting to the original sender

If `except()` still exists, I could invoke it with the socket.id transmitted via request header. But in 1.x, I'm not sure how to handle it.

**Comment by bevacqua** [comment]
@buunguyen have you found a workaround for this one?

**Comment by buunguyen** [comment]
@bevacqua yes, I'm monkey-patching socket.io code like this:

```js
  const ns = io(expressServer, {path: '/sio'})

  ns.constructor.prototype.except = function (id) {
    this.excepts = this.excepts || []
    this.excepts.push(id)
    return this
  }

  const _broadcast = ns.adapter.broadcast
  ns.adapter.broadcast = function (packet, opts) {
    if (ns.excepts) opts.except = ns.excepts
    _broadcast.apply(this, arguments)
    delete ns.excepts
  }
}
```

And here's how to consume that code:

```js
const ns = this.io.to(room)
ns.except(socketId) // socketId comes with each HTTP request
ns.emit(event, message)
```

**Comment by bevacqua** [comment]
That'll do for now, thanks

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
