### ISSUE TITLE
Use Redis as session store for Socket.io

### ISSUE THREAD

**Issue by jamesnocentini** [socketio/socket.io#1598]
Looks like the redis store module for sessions is not available anymore
socket.io/lib/stores/redis was removed so this snippet returns module not found

```
var SocketIoRedisStore = require('socket.io/lib/stores/redis'),
    redis              = require('socket.io/node_modules/redis');
...
io.set('store', new SocketIoRedisStore({
  redisPub    : redis.createClient(),
  redisSub    : redis.createClient(),
  redisClient : redis.createClient()
}));
```

And https://github.com/automattic/socket.io-redis works great for events but doesn't store the session id

Is it possible to store sessions in Redis with socket io 1.0 or does it only rely on the server supporting sticky sessions?

**Comment by bpceee** [comment]
@rauchg  Thanks! Passing { transports: ['websocket'] } work fine.  Anything news?

**Comment by knoxcard** [comment]
I am using this Redis/Express session store: https://github.com/tj/connect-redis store

Works with great with socket.io once you share the session between Express and Socket.io
