### ISSUE TITLE
should have a way to cancel ack callback

### ISSUE THREAD

**Issue by msmouse** [socketio/socket.io#1604]
for a slow or malfunctioning server, a client may have too many callbacks left in socket.ack[id].

It'll be good to have

socket.emit('msg', callback, timeout_callback)

or otherwise

id = emit('msg', callback);

then we can do

socket.cancel_callback(id);

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
