### ISSUE TITLE
socket io websocket is closed before the connection is established

### ISSUE THREAD

**Issue by Udhay2k** [socketio/socket.io#1610]
if (cluster.isMaster) {
    for (var i = 0; i < numCPUs; i++) {
     var worker = cluster.fork();
      worker.send('hi there');
    }

```
cluster.on('fork', function(worker) {
  console.log('forked worker : ' + worker.process.pid);
});

cluster.on('listening', function(worker, address) {
  console.log('listening : ' + worker.process.pid);
});

cluster.on('online', function(worker) {
  console.log("Yay, the worker responded after it was forked");
});

cluster.on('exit', function(worker, code, signal) {
  console.log('worker ' + worker.process.pid + ' died');
});
```

  } 
  else {
   server = http.createServer(function(req, res) {
      $controller.handleReq(req, res);
    }).listen(conf.port, conf.host)
    .on('error', function(e) {
      console.log('Could not start server on ' + conf.host + ':' + conf.port);
      throw e;
    })
    .on('listening', function(e) {
      console.log('Server running at http://' + conf.host + ':' + conf.port);
    });

```
_socketServer();
```

  }

var _socketServer = function() {

  io = sio.listen(server);
  io.set('log level', 1);

  io.sockets.on("connection", function (socket) {

---
## contains set of chat methods

 });  
};

The code not working fine  it give error for cluster server but single http server it works  fine no issue with this

can you anyone give me or suggest to cluster server for chat application

I have stuck it for last week

Thanks

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
