### ISSUE TITLE
problem with some browsers

### ISSUE THREAD

**Issue by nasserghiasi** [socketio/socket.io#1611]
I think opera (12) and safari has problem with websocket or socket.io
opera: disconnecting after full load page and connect to socket.io
safari: is slow on websocket

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
