### ISSUE TITLE
sockets cache used for multiplexing not cleaned on socket destroy 

### ISSUE THREAD

**Issue by Zorkin** [socketio/socket.io#1613]
Next time you try and connect to the same server you get a dead socket that never tries to connect. Can not see any code to remove dead sockets from the cache ?

Even if the socket is there and in a good state it ever emits a connect event which trips the app up.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
