### ISSUE TITLE
io.sockets.socket(socketId) is gone?

### ISSUE THREAD

**Issue by victorwoo** [socketio/socket.io#1618]
In the 0.9.x, we can use `io.sockets.socket(socketId)`, but in 1.0.x, it's gone.
How to find a socket by id in 1.0.x?

**Comment by iamwave007** [comment]
shouldn't it be.
io.connected[socket.id]

? without  ".sockets."

**Comment by onclave** [comment]
Hi, I am using version 1.4.4 and none of the above methods work for me. I want to get a reference to a socket using it's `socket.id`.
All the above methods mentioned here does not work.
What I really want to do is get a socket reference of one namespace from another namespace. A tutorial gives the following code snippet, but uses 0.9.x version.

    var self = this;
    //--code--//
    this.namespace_A = io.of("ns_a");
    this.namespace_B = io.of("bs_b");
    //--code--//
    this.namespace_B.on("connection", function(socket){
            //--code--//
            var ns_a_soc = self.namespace_A.sockets[socket.id];
            //--code--//
    });

I need an alternative to this line `var ns_a_soc = self.namespace_A.sockets[socket.id];` for version 1.4.4. Can anyone please help?

**Comment by AljoSt** [comment]
same problem here

**Comment by MasterJames** [comment]
Seems to work fine here.
Maybe you need to socket.join('ns_a"); first?

**Comment by phpmydev** [comment]
Hello!  I am using the latest release (2.0) and can't get io.to(socket.id) to work.  Any news on this?

**Comment by j-f1** [comment]
@phpmydev I’d recommend opening a new issue for that — this one seems to be for a different problem.

**Comment by StefansArya** [comment]
I'm curious if io.to(socket.id).join(roomID) is working too because I can't found in the documentation

**Comment by darrachequesne** [comment]
@StefansArya `io.to(socket.id)` is meant to be used with emit (`io.to(socket.id).emit('event')`, sending a message to that particular socket), it does not return a `Socket` object.

**Comment by StefansArya** [comment]
@darrachequesne Thanks for the explanation, I have learn so many things with nodejs REPL and found that I can do this for the alternative... I'll leave this here if someone have a same problem like me..
`io.sockets.sockets[targetSocketID].join(roomID)`
