### ISSUE TITLE
Missing connections for socket.emit->socket.on, add confirmation?

### ISSUE THREAD

**Issue by recursion1122** [socketio/socket.io#1619]
I noticed sometimes an emit will not be received on the other side (both client->server and server->client). I'm having to add confirmations and resending if not confirmed. I think it might be helpful to include that in the script.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
