### ISSUE TITLE
error in client.js

### ISSUE THREAD

**Issue by karli2000** [socketio/socket.io#1621]
Hi,

i get on our server app this error:

/socket.io/lib/client.js:72
      self.connectBuffer.forEach(self.connect, self);
                         ^
TypeError: Cannot call method 'forEach' of undefined
    at /data/work/node_chat/server/node_modules/socket.io/lib/client.js:72:26
    at /data/work/node_chat/server/node_modules/socket.io/lib/namespace.js:168:17
    at process._tickCallback (node.js:419:13)

the server has around 400 connections, so should not be a problem, any ideas why?

**Comment by rase-** [comment]
@FredyC does this still happen? Any further info?

**Comment by FredyC** [comment]
@rase- Unfortunately I haven't been working on project with socket.io recently, so I cannot verify this.

**Comment by karli2000** [comment]
Sorry, we switched back to the 0,9,x branch which is working perfect for us (100k+ concurrent connections).

**Comment by rase-** [comment]
@FredyC I wrote a test case for reconnection upon server close in #1939. Does that look like at all like the case you had?

**Comment by FredyC** [comment]
@rase- Well are you sure that `srv.close` is equivalent to restarting whole server? Does it proper cleanup of everything. Otherwise it is not like my case. I was literally restarting server with the nodemon, client reconnected and server crashed with that error above.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
