### ISSUE TITLE
[1.0.4] cocos2dx socketIO - Migrating from 0.9 issue

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io#1628]
handshaking issue

I can't find handshake url

0.9 under - http://uri/socket.io/1
1.0.4        - http://uri/socket.io/?EIO=2&transport=polling  <----- ?? 
I just found with packet sniffer

it returns sid and pinginterval timeout with http response code 200 
but return value has binary data beginning of value <--- just right? 

i don't know exactly what this value is correct.

and then I want connect to websocket but can't find any documents for version 1.0.4

where i connect to?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
