### ISSUE TITLE
socket.io 1.0.X  multi process cluster Connection closed before receiving a handshake response socket.io

### ISSUE THREAD

**Issue by udhayakumark** [socketio/socket.io#1637]
Is there any way do the chat server for multi process cluster server.

it gives error
Connection closed before receiving a handshake response socket.io

If i use single process it works perfect, but only when change back to multiprocess this happens.

code:

var express = require('express');
var app = express();
var server = require('http').createServer(app);
var io = require('../..')(server);
var port = process.env.PORT || 3000
  cluster = require('cluster'),
  numCPUs = require('os').cpus().length;

  if (cluster.isMaster) {
    for (var i = 0; i < numCPUs; i++) {
      var worker = cluster.fork();
    }
  } 
  else {
    server.listen(port, function () {
    console.log('Server listening at port %d', port);
    });
  }

// Routing
app.use(express.static(__dirname + '/public'));

please any one give me idea to do the chat server for multiple process cluster server.

Advance thanks.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
