### ISSUE TITLE
iOS indicator keeps on spinning when connect to cross origin.

### ISSUE THREAD

**Issue by yosuke-furukawa** [socketio/socket.io#1640]
I am testing iOS safari can connect to socket.io v1.0 on cross domain.

I can connect socket.io, however, iphone indicator keeps spinning and does not stop.

I wrote the detail information in gist. If you have time, please check that.

[https://gist.github.com/yosuke-furukawa/35b37013c5dcfcb15e52](https://gist.github.com/yosuke-furukawa/35b37013c5dcfcb15e52)

**Comment by yujiosaka** [comment]
@rauchg @yosuke-furukawa 
is it still occurring? i don't see it occur any more with current iOS and socket.io.
Can you confirm that?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
