### ISSUE TITLE
Removing engine.io to support websockets only (merely a howto)

### ISSUE THREAD

**Issue by lassegit** [socketio/socket.io#1649]
It says on the [web site](http://socket.io/blog/introducing-socket-io-1-0/) that you can seamlessly remove engine.io from web socket client if you only want to support web sockets transport protocol. Is there a build without engine.io or a how to?

**Comment by MayhemYDG** [comment]
@rauchg ETA on `socket.io-ws.js`?

**Comment by rauchg** [comment]
1.5

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
