### ISSUE TITLE
为什么服务器隔8小左右会自动断开

### ISSUE THREAD

**Issue by liketo** [socketio/socket.io#1650]
服务端与客户端都是node.js实现
socket.io 版本："version": "0.9.13"
服务端创建代码:
var _io = require('socket.io').listen(listen_port);

客户端创建代码:
var _io = require('socket.io-client').connect(host_port);

隔8小左右会自动断开，请问有人知道怎么解决吗

**Comment by rase-** [comment]
@liketo are you still experiencing this issue with the latest release?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
