### ISSUE TITLE
How do you store data associated to a socket using Socket.io 1.0

### ISSUE THREAD

**Issue by konfiot** [socketio/socket.io#1651]
Hello, I'm trying to migrate from 0.9 to 1.0, and I was using socket.get and socket.set to store data for each client.
As these functions are deprecated with the 1.0, I'm wondering how to store data relative to a specific socket.
Thanks in advance

**Comment by Alex-Nabu** [comment]
@rauchg so info stored on the socket is not available to the client for mutation?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
