### ISSUE TITLE
Add support of msgpack format 

### ISSUE THREAD

**Issue by mrniko** [socketio/socket.io#1652]
I think it will be useful to add support of msgpack and have ability to switch between json and msgpack formats in configuration. http://msgpack.org/

**Comment by rase-** [comment]
i think alternative formats would serve better as plugins. I'd be happy to merge in any hooks needed to make that happen.

Thought, @rauchg?

**Comment by rauchg** [comment]
Agreed on hooks. Pluggable codecs is something we've been meaning to introduce for a while!
As a matter of fact, the current "codec" is highly opinionated in several areas (performance, usage of UTF8 JSON even in binary stream, etc)

**Comment by rauchg** [comment]
It'd be interesting to test the performance of a demo app that shows users cursors on a page in realtime using the default codec and a custom codec that can only receive integer tuples over a binary stream (x,y).

In other words:

```js
io.emit('position', x, y)
```

could be encoded in a very minimal way instead of using JSON.

**Comment by legomind** [comment]
any progress on this? I have msgpack working via monkey-patching - something I would like to avoid.

**Comment by darrachequesne** [comment]
> I'd be happy to merge in any hooks needed to make that happen.

**Comment by darrachequesne** [comment]
Question: aren't most users already using something like `io.emit(<message id>, msgpack.encode({ x: x, y: y }));`?

Reminder for myself:
```js
socket.emit('hello', 'world');
// the resulting socket.io packet object
packet = {
  type: parser.EVENT,
  data: ['hello', 'world'],
  nsp: '/test'
}
// encoded by socket.io-parser
// > 2/test,["hello","world"]

// the resulting engine.io packet object
packet = {
  type: 'message',
  data: '2/test,["hello","world"]'
}
// encoded by engine.io-parser
// > 42/test,["hello","world"]
```

**Comment by legomind** [comment]
@darrachequesne that is the only way to do it right now, but it would be far more convenient if there were a way to preprocess all outgoing and incoming messages automatically.

As far as hooks go, what would you like them named?

I was thinking something like:
## server
```js
const socket = new SocketIO(httpServer, {
  prepareMessage: msgpack.encode,
  unprepareMessage: msgpack.decode,
})
```

## client
```js
const socket = new SocketIO({
  prepareMessage: msgpack.encode,
  unprepareMessage: msgpack.decode,
})
```

**Comment by legomind** [comment]
Or closer to the request in #1946,

## server
```js
const codec = {
  encode: msgpack.encode,
  decode: msgpack.decode,
}
const socket = new SocketIO(httpServer, {
  codec,
})
```

## client
```js
const codec = {
  encode: msgpack.encode,
  decode: msgpack.decode,
}
const socket = new SocketIO({
  codec,
})
```

**Comment by darrachequesne** [comment]
That may make sense too: https://github.com/socketio/socket.io-parser/issues/61

How about the following API:
- `io.registerPacker(<eventName>, function (a, b, c) { return <buffer> })`
- `io.registerUnpacker(<eventName>, function (buffer) { return [a, b, c] })`

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io/pull/2829.
