### ISSUE TITLE
Need ability to arbitrarily emit with callback to a socket client.

### ISSUE THREAD

**Issue by monteslu** [socketio/socket.io#1656]
0.9.x of Socket.io allowed you to get a socket by id and emit to it with a callback such as:

``` javascript
io.sockets.socket(someSocketId).emit('someTopic', data, callback); 
```

With 1.0.x we can only broadcast to the channel/id of a socket.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
