### ISSUE TITLE
Events when rooms are created and deleted automatically.

### ISSUE THREAD

**Issue by mhretab** [socketio/socket.io#1657]
Hi,

I am working on a project where rooms are created  and deleted dynamically and I don't have any way of knowing when a room is created or deleted. it would be nice to have this feature. Now I am counting the number of users on that room when joining and if it is only one then the room is being created..., but that is not efficient and would be nice to have an event like on room creation or deletion.

Thank you in advance!

**Comment by rase-** [comment]
@gpestana rooms are deleted automatically when empty.

@rauchg thoughts on adding the event?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
