### ISSUE TITLE
Connecting 0.9 clients to 1.0 server

### ISSUE THREAD

**Issue by poscar** [socketio/socket.io#1658]
I have deployed clients that are using socket.io 0.9.  I want to migrate my server to 1.0, but the 0.9 clients are not able to connect to the new server.

What would you guys recommend to perform this migration?  Multiple nodes (0.9 & 1.0) with a redis store? Or would it be possible to write a module/extension to support 0.9 clients?

Thanks!

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
