### ISSUE TITLE
Connecting to socket.io forces browsers to clear page cache

### ISSUE THREAD

**Issue by yujiosaka** [socketio/socket.io#1660]
Page cache (bfcache) retains the entire page when go back and forward.
It is important especially for Mobile Safari and Android browser to give smooth UX.

However, connecting to socket.io automatically disables page cache.

I created a sample app and wrote details on it's readme.
https://github.com/yujiosaka/socket.io-cache-example

I wrote workaround to this problem, but is there a better way avoiding this problem?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
