### ISSUE TITLE
Concurrent Users & Scalability

### ISSUE THREAD

**Issue by amarTech** [socketio/socket.io#1664]
We are going to develop Chat App for our Organization.
1. I wanted to know how many concurrent active users socket.io supports.
2. We are looking to scale our App to 100K - 1M concurrent active users. Can we scale to this limit?
3. We are going to use 16 core CPU & 32 GB of RAM.

Please be helpful.

We got stuck at scalability.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
