### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by BenBals** [socketio/socket.io#1665]
I am just calling `ìo.sockets.emit('hey', data);``and it will crash with``RangeError: Maximum call stack size exceeded``. I use it in other places in my app and it works fine. I am not repeating this (checked with console). The logs say the error is in``socket.io/node_modules/has-binary-data/index.js:46``.

I dont know where the problem is. I tried logging `io.sockets` right before using it and it outputs this:

```

{ name: '/',
17:39:37 web.1  |   server:
17:39:37 web.1  |    { nsps: { '/': [Circular] },
17:39:37 web.1  |      _path: '/socket.io',
17:39:37 web.1  |      _serveClient: true,
17:39:37 web.1  |      _adapter: [Function: Adapter],
17:39:37 web.1  |      _origins: '*:*',
17:39:37 web.1  |      sockets: [Circular],
17:39:37 web.1  |      eio:
17:39:37 web.1  |       { clients: [Object],
17:39:37 web.1  |         clientsCount: 2,
17:39:37 web.1  |         pingTimeout: 60000,
17:39:37 web.1  |         pingInterval: 25000,
17:39:37 web.1  |         upgradeTimeout: 10000,
17:39:37 web.1  |         maxHttpBufferSize: 100000000,
17:39:37 web.1  |         transports: [Object],
17:39:37 web.1  |         allowUpgrades: true,
17:39:37 web.1  |         allowRequest: [Function],
17:39:37 web.1  |         cookie: 'io',
17:39:37 web.1  |         ws: [Object],
17:39:37 web.1  |         _events: [Object] },
17:39:37 web.1  |      engine:
17:39:37 web.1  |       { clients: [Object],
17:39:37 web.1  |         clientsCount: 2,
17:39:37 web.1  |         pingTimeout: 60000,
17:39:37 web.1  |         pingInterval: 25000,
17:39:37 web.1  |         upgradeTimeout: 10000,
17:39:37 web.1  |         maxHttpBufferSize: 100000000,
17:39:37 web.1  |         transports: [Object],
17:39:37 web.1  |         allowUpgrades: true,
17:39:37 web.1  |         allowRequest: [Function],
17:39:37 web.1  |         cookie: 'io',
17:39:37 web.1  |         ws: [Object],
17:39:37 web.1  |         _events: [Object] } },
17:39:37 web.1  |   sockets:
17:39:37 web.1  |    [ { nsp: [Circular],
17:39:37 web.1  |        server: [Object],
17:39:37 web.1  |        adapter: [Object],
17:39:37 web.1  |        id: 'RfgXeMgHeP_9SQC5AAAC',
17:39:37 web.1  |        client: [Object],
17:39:37 web.1  |        conn: [Object],
17:39:37 web.1  |        rooms: [Object],
17:39:37 web.1  |        acks: {},
17:39:37 web.1  |        connected: true,
17:39:37 web.1  |        disconnected: false,
17:39:37 web.1  |        handshake: [Object],
17:39:37 web.1  |        _events: [Object] },
17:39:37 web.1  |      { nsp: [Circular],
17:39:37 web.1  |        server: [Object],
17:39:37 web.1  |        adapter: [Object],
17:39:37 web.1  |        id: '7TEjGJjWzxObulClAAAD',
17:39:37 web.1  |        client: [Object],
17:39:37 web.1  |        conn: [Object],
17:39:37 web.1  |        rooms: [Object],
17:39:37 web.1  |        acks: {},
17:39:37 web.1  |        connected: true,
17:39:37 web.1  |        disconnected: false,
17:39:37 web.1  |        handshake: [Object],
17:39:37 web.1  |        _events: [Object] } ],
17:39:37 web.1  |   connected:
17:39:37 web.1  |    { RfgXeMgHeP_9SQC5AAAC:
17:39:37 web.1  |       { nsp: [Circular],
17:39:37 web.1  |         server: [Object],
17:39:37 web.1  |         adapter: [Object],
17:39:37 web.1  |         id: 'RfgXeMgHeP_9SQC5AAAC',
17:39:37 web.1  |         client: [Object],
17:39:37 web.1  |         conn: [Object],
17:39:37 web.1  |         rooms: [Object],
17:39:37 web.1  |         acks: {},
17:39:37 web.1  |         connected: true,
17:39:37 web.1  |         disconnected: false,
17:39:37 web.1  |         handshake: [Object],
17:39:37 web.1  |         _events: [Object] },
17:39:37 web.1  |      '7TEjGJjWzxObulClAAAD':
17:39:37 web.1  |       { nsp: [Circular],
17:39:37 web.1  |         server: [Object],
17:39:37 web.1  |         adapter: [Object],
17:39:37 web.1  |         id: '7TEjGJjWzxObulClAAAD',
17:39:37 web.1  |         client: [Object],
17:39:37 web.1  |         conn: [Object],
17:39:37 web.1  |         rooms: [Object],
17:39:37 web.1  |         acks: {},
17:39:37 web.1  |         connected: true,
17:39:37 web.1  |         disconnected: false,
17:39:37 web.1  |         handshake: [Object],
17:39:37 web.1  |         _events: [Object] } },
17:39:37 web.1  |   fns: [],
17:39:37 web.1  |   ids: 0,
17:39:37 web.1  |   acks: {},
17:39:37 web.1  |   adapter:
17:39:37 web.1  |    { nsp: [Circular],
17:39:37 web.1  |      rooms:
17:39:37 web.1  |       { '5MGPNOdO4th_dOuZAAAA': [],
17:39:37 web.1  |         '64rUhxxp--4Qk1MqAAAB': [],
17:39:37 web.1  |         RfgXeMgHeP_9SQC5AAAC: [Object],
17:39:37 web.1  |         '7TEjGJjWzxObulClAAAD': [Object] },
17:39:37 web.1  |      sids:
17:39:37 web.1  |       { RfgXeMgHeP_9SQC5AAAC: [Object],
17:39:37 web.1  |         '7TEjGJjWzxObulClAAAD': [Object] },
17:39:37 web.1  |      encoder: {} },
17:39:37 web.1  |   _events: { connection: [Function] } }
```

My code is:

`````` JAVASCRIPT

if (game.scoreTeamTwo > game.scoreTeamOne && game.scoreTeamTwo > game.scoreTeamThree && game.scoreTeamTwo > game.scoreTeamFour) {
              game.winner = 2;
              io.sockets.emit('CTFEnd', game);
}

//It´s just looking if team 1 won the game and when it does is emits ````CTFEnd```` and all the other game data
``````

**Comment by arobbins** [comment]
Interestingly enough, I'm getting this same error when attempting to pass my Firebase data to the client side.
```javascript
node_modules/socket.io/node_modules/has-binary-data/index.js:46

for (var key in obj) {
                ^
RangeError: Maximum call stack size exceeded
```

**Comment by KangGwanwoo** [comment]
해결책을 찾습니다...

**Comment by BenBals** [comment]
Sorry, but my Chinese isn't that great. Would you be so kind to translate this into English.

**Comment by rossnorvell** [comment]
Did a Google Translate & it comes out to "Find the Solution..." ... hardly worth responding to. For record, the solution is to not pass such large amount of data via socket.io ... it's a socket which was designed for quick, short responses. Break up your response or send it via ajax. Unsubscribing to this thread.

**Comment by Strat-** [comment]
One thing you could do is just asynchronously iterate the object and its properties, something like:

```javascript
var props = [];
var obj = { a: 1, b:2, c: { d: 3, e: 4 } };

function next_prop(callback){
  if (!props.length){
    setTimeout(callback);
    return;
  }
  var prop = props.shift();
  //do whatever with the prop, call parse_obj on it if it's an object
  setTimeout(next_prop);
}

function parse_obj(obj, callback){
  for (var i in obj){
    props.push(i);
  }
  setTimeout(function(){next_prop(callback);});
}

parse_obj(obj);
```

**Comment by Marks-Chan** [comment]
I just  get  that error too, my code is like: "io.sockets.emit('key', data);"
i try to simply the "data" object and keep it small, and it worked

**Comment by ecasilla** [comment]
+1 would the core team like a async version of of binary checking i can help get that setup

**Comment by smartytwiti** [comment]
I can reproduce the problem by sending the socket object :)

**Comment by xenyou** [comment]
+1 IE11 shows 'out of stack space' in _hasBinary.

**Comment by kevnk** [comment]
This error showed for me when I was trying to send the whole socket object back to the client. All I _really_ needed was `socket.id` so the error disappeared when I sent back a smaller item — in my case, `socket.id` instead of the whole `socket` object

**Comment by LordMajestros** [comment]
This probably happened because you were trying to send an object with circular references resulting in a recursive call that exceeded the stack size.

**Comment by GerbenHofman** [comment]
@LordMajestros That fixed it for me! Thanks

**Comment by LordMajestros** [comment]
@GerbenHofman you're welcome

**Comment by shunjikonishi** [comment]
I faced same error on NodeJS v4.4.4 and socket.io v1.4.5.

In my case, it happens after disconnect event.  
And it happens only when I called `socket.emit` more than 200,000 times.

If the number of call `socket.emit` is around 100,000, this error never happen.

Is this information helps you?

**Comment by emmerich** [comment]
Just to add to @shunjikonishi , I've seen this happen as soon as I have sent **exactly** 100,000 events via io.emit. I have 1 socked connected, so seems like 100,000 is a hard cap. Any more information on this? Is it a limit imposed by SocketIO, by ws or something else?

**Comment by adamreisnz** [comment]
Is there any chance of Socket IO implementing a guard against recursive data being emitted from and failing with this error? A simple detection could prevent this error from happening and emit instead a more meaningful error, like "You may be trying to send circular data". That would make it easier to debug.

**Comment by mtrabelsi** [comment]
@adamreisnz You are welcome to make a PR ;)

**Comment by adamreisnz** [comment]
It always catches me off guard when someone mentions me 5 months after a comment 😆

**Comment by 623059008** [comment]
I met this error too. And that's why I waste two hours to check my whole codes :<.
I think it caused by recursion object like A={B:{C:A}}, and obviously **socket** is a recursion object.
In fact, I guess it happened because in buffer.js, they use a recursion to find the length of data which you want to send. And then get the "maximum call stack size exceeded". If they use JSON.stringify() to get the length, there will be another clearly error about "circular structure". By the way, it has a bad key word to google!

**Comment by dustingraham** [comment]
I just ran into this as well.
 - https://github.com/socketio/socket.io/blob/master/lib/socket.js#L148

`hasBin` will fill the stack with a recursive loop if trying to send an object that has a circular reference.

**Comment by dustingraham** [comment]
Shucks, I see there is a PR that has been open for 2 years that would fix this:
 - https://github.com/darrachequesne/has-binary/pull/3

**Comment by darrachequesne** [comment]
@dustingraham the fix does look great, though I'm not sure about the performance implications.

Also, even if it doesn't throw in the `hasBinary` method anymore, I'm afraid the JSON.stringify method that is called later in the code will still throw an error:

```js
> var a = {};
undefined
> var b = { a: a };
undefined
> a.b = b
{ a: { b: [Circular] } }
> JSON.stringify(a)
Thrown:
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
```

**Comment by darrachequesne** [comment]
For future readers: sending packet with circular references is not supported by default, since the default parser relies on `JSON.stringify()`.

If you have such a use case, you can provide your own parser: https://socket.io/docs/v3/custom-parser/

**Comment by fo-nhan** [comment]
> Xin lỗi, nhưng tiếng Trung của tôi không tốt lắm. Bạn có vui lòng dịch cái này sang tiếng Anh không.

He is Korean

**Comment by GlistenSTAR** [comment]
Hello, How are you?
Currently, I am implementing chat app using socket.io@4.5.1.
![image](https://user-images.githubusercontent.com/75786284/171927323-418b7b13-aba5-48c4-9ee9-7b014ce90235.png)
But I get this error like image.
![image](https://user-images.githubusercontent.com/75786284/171927598-06a9ee86-fb43-4d49-a6ac-91eb404efe97.png)
What is solution and Can you help me, please?
Warm regards

**Comment by 623059008** [comment]
> 

Check if there is a circle json object, because when you emit an event with data which is an object, it will convert the object to string by recursion. If you transfer a circle object, it will cause endless recursion.
