### ISSUE TITLE
Concurrent Connections

### ISSUE THREAD

**Issue by mshafieluru** [socketio/socket.io#1672]
1. I have a app running on port 8080 and socket.io running on 8000. 
2. i am using socket io client in my app running on 8080 to connect to socket io server on 8000
3. The issue is for 'n' number of clients accessing my app, the client is same port 8080, and connection to server is only one.
4. Even the socket identifies using a unique hash, or even i set 'force new connection : true' still parallel connections are not working
5. How to resolve this issue. i am uploading a big file using socket.io
6. is it library issue, i am using version 0.9.16 or do i need to run a pool of socket.io servers with a load balancer infront of them ?
7. Please help

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
