### ISSUE TITLE
Using https with socket.io 1.0.6 and getting an ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by justenPalmer** [socketio/socket.io#1674]
I've been using https with socket.io on version 0.9 and below successfully for years. I went to upgrade to the new 1.0 version and I'm getting an SSL error. Here is the server-side node.js code to start the socket server:

```
var options = {};
options.key = fs.readFileSync('certs/ssh.key');
options.cert = fs.readFileSync('certs/cert.key'); //I've also tried using the property 'certificate' instead of 'cert'
var io = require('socket.io').listen(9091,options);
```

The connection works fine over standard http but https is giving me the error: ERR_SSL_PROTOCOL_ERROR

I know that all certificate file references are good. There seems to be no documentation on how to implement https socket.io connections on version 1.0, so I'm at a loss. Any help is much appreciated.

**Comment by JohnKiller** [comment]
Same issue. Isn't there a way to use SSL without Express? Before 1.0 it was working.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
