### ISSUE TITLE
Send message to multiple clients only once

### ISSUE THREAD

**Issue by kristoff-it** [socketio/socket.io#1684]
Hello, I'm in need of sending the same message to clients belonging to multiple rooms but I don't want to send duplicates in case a client belongs to more than one of the rooms I'm sending the message to.

Making sure I don't send the same message twice can be done by a simple loop over all clients belonging to each room I'm targeting: inside the loop I simply check if I already sent the message to the client (using an hashmap, for example).

The problem with this approach is that the message gets serialized from scratch for every iteration in which `.emit()` is called. 
Is there a way to do one of the following?
- Send a message that has already been serialized. Something like a `.emit_json()` function.
- Use an array as a 'temporary room' to emit to (if emitting to a room performs the serialization only once)

Thanks!

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
