### ISSUE TITLE
Many tests on Windows fail

### ISSUE THREAD

**Issue by fdellabetta** [socketio/socket.io#1686]
@guille The source of most failures is that on Windows you cannot connect to 0.0.0.0 address (
http://msdn.microsoft.com/en-us/library/windows/desktop/ms737625(v=vs.85).aspx "..If the address member of the structure specified by the name parameter is filled with zeros, connect will return the error WSAEADDRNOTAVAIL..." )

In order to prevent that error on Windows you can apply this patch

```
diff --git a/test/socket.io.js b/test/socket.io.js
index b5c23c9..144fe18 100644
--- a/test/socket.io.js
+++ b/test/socket.io.js
@@ -15,7 +15,7 @@ function client(srv, nsp, opts){
   }
   var addr = srv.address();
   if (!addr) addr = srv.listen().address();
-  var url = 'ws://' + addr.address + ':' + addr.port + (nsp || '');
+  var url = 'ws://' + (addr.address === '0.0.0.0' ? 'localhost' : addr.address) + ':' + addr.port + (nsp || '');
   return ioc(url, opts);
 }
```

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
