### ISSUE TITLE
Can't broadcast to room on v1.0.6

### ISSUE THREAD

**Issue by Rewt0r** [socketio/socket.io#1703]
Having a weird issue here, I'm joining clients to a room using `socket.join(room.name);` where `room.name = 'Testing Rooms';` I already have a client connected to this room (2 open browser windows) and afteer issuing the `join` command I issue `io.in(room.name).emit('join', socket.id);` and send an acknowledgement via `fn()` however this doesn't seem to be emitting at all, even when replacing `io.in` with `io.to`.

Debug from server shows the join and sending of the ack packet but nothing for the emit.

```
Sun, 03 Aug 2014 04:53:35 GMT socket.io:socket joining room Testing Room
Sun, 03 Aug 2014 04:53:35 GMT socket.io:socket sending ack [{"id":1,"name":"Testing Room"}]
Sun, 03 Aug 2014 04:53:35 GMT socket.io:socket joined room Testing Room
```

However I've found that `socket.broadcast.to(room.name).emit('join', socket.id);` is working as expected.

**Comment by spikerola** [comment]
@Rewt0r I've tried

```
socket.broadcast.to("my-room").emit("joined", ....);
```

It doesn't work in v1.3.7

**Comment by Rewt0r** [comment]
I've not used socket.io since then (1.0.6), if this still isn't fixed then it shouldn't be shown on the documentation.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
