### ISSUE TITLE
socket.request.connection.remoteAddress is undefined for AJAX node.js clients

### ISSUE THREAD

**Issue by calzoneman** [socketio/socket.io#1737]
Issues such as #1483 and #1387  illustrate that `socket.request.connection.remoteAddress` is not always defined.

In #1387, someone pointed out that a websocket client's IP address is present, but that a client using a `polling` transport (like `socket.io-client` does by default when running in node.js) does **not**  have `remoteAddress` present.

Test case:

server.js

``` js
var io = require('socket.io')(5555);

io.on('connection', function (socket) {
    console.log(socket.request.connection.remoteAddress);
});
```

client1.js (running this should produce `undefined` on the server console output)

``` js
var io = require('socket.io-client')('http://localhost:5555');
```

client2.js (running this should produce the client's IP address on the server console output)

``` js
var io = require('socket.io-client')('http://localhost:5555', { transports: ['websocket'] });
```

Is there any particular reason that there is not a way to retrieve a client's IP address if they are using a node.js client with the AJAX transport?  I would prefer not to require all of my clients to manually override the transport.

**Comment by polkovnikov-ph** [comment]
Can we put somewhere in documentation that address should be accessed via `socket.client.conn.remoteAddress`? It took me an hour to find it, and it's quite a popular thing to be documented.

**Comment by darrachequesne** [comment]
@polkovnikov-ph you can also use `socket.handshake.address` (reference here: https://github.com/socketio/socket.io/blob/master/docs/API.md#sockethandshake)

**Comment by polkovnikov-ph** [comment]
@darrachequesne I ended up forking and patching source code anyway. Figuring out, which of the requests counts as handshake, whether it will be really stored at any moment of operation, what it will be named in the next version of the library, how to put requests through an `Agent`, how to use `socket.io-client` with a cookie and other headers (for either part of handshake, websockets included) and how to get around other bugs that are not closed for 4 years is just way too time consuming.
