### ISSUE TITLE
"Session ID unknown" after handshake on high server load [Socket.io 1.0.6]

### ISSUE THREAD

**Issue by Rundfunk** [socketio/socket.io#1739]
I am running a multi-node server (16 workers running Socket.io 1.0.6; accessed via Nginx, configured as a reverse proxy supporting sticky sessions) for ~ 5k users. While the load of the server is low (2~3 on a 20 core server / 2k users), everyone is able to connect instantly. When the load of the server gets higher (5~6 / 5k users), new users are not able to connect and receive data instantly. In this case, it takes 2~4 handshakes for the users to connect succesfully.

This is what happens (high load):
- User opens the website; receives HTML and JS
- User's browser attempts to initialize a socket.io connection to the server (`io.connect(...)`)
- A handshake request is sent to the server, the server responds with a SID and other information (`{"sid":"f-re6ABU3Si4pmyWADCx","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}`)
- The client initiates a polling-request, including this SID: `GET .../socket.io/?EIO=2&transport=polling&t=1408648886249-1&sid=f-re6ABU3Si4pmyWADCx`
- Instead of sending data, the server responds with 400 Bad Request: `{"code":1,"message":"Session ID unknown"}`
- The client performs a new handshake (`GET .../socket.io/?EIO=2&transport=polling&t=1408648888050-3`, notice the previously received SID is omitted)
- The server responds with new connection data, including a new SID: (`{"sid":"DdRxn2gv6vrtZOBiAEAS","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}`)
- The client performs a new polling request, including the new SID: `GET .../socket.io/?EIO=2&transport=polling&t=1408648888097-4&sid=DdRxn2gv6vrtZOBiAEAS`
- The server responds with the data that is `emit`ted in the worker source code.

Depending on the load of the server, it may happen 1~3 times that the server responds with `"Session ID unknown"` and the client needs to perform a new handshake before data is actually received.

**Comment by Sesshomurai** [comment]
Hi, I am having this same problem with nginx, node and socket.io. There is a way for nginx to use 'sticky' session ids passed along in the HTTP cookie that would solve it, but its part of their commerical offering. I was hoping the socket.io redis would address this by storing the session id in redis and using it from another socket.io-redis enabled node, but it doesn't work. Maybe this is something that could be made to work using the redis adaptor?

**Comment by aPoCoMiLogin** [comment]
@runningskull +1 thats explain a lot.

**Comment by flaviolivolsi** [comment]
I had this problem hosting my project with Heroku when I switched to multiple dynos, I solved enabling the sticky sessions with `heroku features:enable http-session-affinity`.

**Comment by jiffymack** [comment]
Our application hosted in AWS and we have sticky session but still we have issue of Session ID unknown. 

Please let me know if any update on this. 

Socket IO : 1.7.3
Socket IO redis : 5.2.0
Node : 7.10.0

**Comment by ashish101184** [comment]
Our application hosted in AWS and we have sticky session but still we have issue of Session ID unknown. 

Please let me know if any update on this. 

Socket IO : 1.7.3
Socket IO redis : 5.2.0
Node : 7.10.0

**Comment by ashish101184** [comment]
So you think that we I will upgrade socket io and node js will resolve problem?

**Comment by ashish101184** [comment]
I am getting fail in python socket client library where python always use first polling request. So from python client never getting connected. 

So any solution for that?

**Comment by jaykumarthaker** [comment]
**For novice like me**, making just nodejs backend to use `transport` as websocket protocol won't do much. socket.io clients are also required to set with the same configuration. So, in my onion below should work:

in nodejs:
```
  const ioSocket = io('',  {
      transports: ['websocket',  'polling']
    });
```

and in js client:
```
  socket = io.connect(SocketServerRootURL, {
        transports:['websocket', 'polling']
    });
```

`['websocket', 'polling']` will force socket.io to try webscoket as the first protocol for the connection or else fall back to polling (if some clients doesn't support websockets).

**Comment by lmjavascriptprogrammer** [comment]
Thanks @jaykumarthaker it works for my cluster

**Comment by over2000** [comment]
> for me, it was with nginx ssl http2, and it was polling, so the good config is:
> 
> ```js
>  const ioSocket = io('', {
>       // Send auth token on connection, you will need to DI the Auth service above
>       // 'query': 'token=' + Auth.getToken()
>       path: '/socket.io',
>       transports: ['websocket'],
>       secure: true,
>     });
> ```

This fix the problem, with 'polling' my socket make too many requests

**Comment by darrachequesne** [comment]
For future readers:

Please note that using `transports: ['websocket']` disables HTTP long-polling, so there's no fallback if the WebSocket connection cannot be achieved (which might be acceptable or not, depending on your use case).

Reference: https://socket.io/docs/v4/client-options/#transports

@over2000 if HTTP long-polling makes too many requests, then that surely means something is wrong with the setup, like CORS. Please check our troubleshooting guide: https://socket.io/docs/v4/troubleshooting-connection-issues/

**Comment by mzahidriaz** [comment]
Issue mentioned in [Socket.IO Documentation](https://socket.io/docs/v4/using-multiple-nodes/), how to handle in load balanced environment
