### ISSUE TITLE
Common API documentation format for all Node packages

### ISSUE THREAD

**Issue by Kapeli** [socketio/socket.io#1756]
I'm the developer behind [Dash](http://kapeli.com/dash), an API documentation browser.

The current state of node packages is that each package has its own custom format for providing documentation (most in a README). This makes things extremely hard if you want to collect all these docs under one app and also an inconvenience for users, as they have to learn how to reference and navigate each doc format of each package they use.

I've asked the NPM team to promote a doc format that node packages should use in hope that the community would embrace it and they've asked me to contact the maintainers of the most popular packages and get them to agree on a format, and if it gets popular with the community it will get supported by NPM as well. The NPM issue is tracked here: https://github.com/npm/newww/issues/100.

Some questions:
1. Have you considered using an API documentation generator for your node package? I've heard of JSDoc over and over, but I've never seen a node package use it for their docs
2. Do you think it would be better if the APIs of node packages would be documented inside the code (where a doc generator would turn them into actual docs), and the READMEs be used just as a guide?
3. Any thoughts about this issue?

**Comment by Willian-Zhang** [comment]
Sorry for digging out this post, but,
Can I or where can I find socket.io Dash app doc? Am I missing something like an Dash app node.js docset sourse?
