### ISSUE TITLE
Minor issues with Chrome Apps

### ISSUE THREAD

**Issue by sondreb** [socketio/socket.io#1782]
Socket.io will return two exceptions while running under Chrome Apps. These does not seem to stop socket.io from working, but should be fixed to avoid errors and perhaps fix if there is a real issue with the storage. Running socket.io inside a Chrome App returns the following two errors:

**window.localStorage is not available in packaged apps. Use chrome.storage.local instead.**

This is located in the socket.io.js file, this code:

Line 1361:

``` javascript
try {
  if (window.localStorage) debug.enable(localStorage.debug);
} catch(e){}
```

**beforeunload is not available in packaged apps.**

Line 2819:

``` javascript
 } else if (global.addEventListener) {
    global.addEventListener('beforeunload', unloadHandler);
  }
```

As I said, it appears that socket.io continue to run fine even with these errors.

**Comment by JakeChampion** [comment]
It seems that Chrome apps no longer work if calling localStorage. We've worked around this issue by removing the lines mentioned in the above comment.
