### ISSUE TITLE
Load & server client optionnaly

### ISSUE THREAD

**Issue by aenario** [socketio/socket.io#1804]
For users who build their client with browserify or similar tool and find easier to include the correct version of socket.io-client directly, it would be great if socket.io-client was an optional depency and the whole require & serve the client could be disable.

Would you accept a PR which move [these lines](https://github.com/Automattic/socket.io/blob/1b4f6a5324b1f68cba29b511c9365a368cde991d/lib/index.js#L10-L11) 
and the reading of the client into attachServe ?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
