### ISSUE TITLE
Responses appear to be cut off

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io#1807]
So my websocket server (socket.io) is sending JSON data to my clients who connect with their web browsers (e.g. Firefox).

It works fine when I am sending short responses.

However, when I send a "large" JSON response, the response is always 219265 characters long -- it cuts off!!!

Therefore, I am unable to parse the JSON data because it cuts off before the transmission is complete!

What can I do?

I tried to do it on Chrome too - it also cuts off after 219265 characters.

My webserver is running Apache/2.4.7 (Ubuntu 14.04) with proxy_wstunnel mod. The websocket server (socket.io-1.1.0) is listening on port 8002 of the server, and Apache re-directs any websocket requests to 8002. It has been working perfectly for short responses.

**Comment by freeant** [comment]
How to solve this problem? I use socket.io in express, how to setup the maxBuffer? 
Thx.
