### ISSUE TITLE
Not able to get the list of rooms the client is currently in on disconnect event

### ISSUE THREAD

**Issue by salvador-dali** [socketio/socket.io#1814]
I am trying to find the list of rooms a client is currently in on disconnect event (closes the browsers / reloading the page / internet connection was dropped) and based on my [question on SO](http://stackoverflow.com/q/25830415/1090562) it looks like it is not possible.

I find it hard to believe that this is the case (I think this is frequently needed functionality). Can any socket.io guru tell whether this is true or even better how can I achieve this?

**Comment by X-Coder** [comment]
I stumbled accross the same situation.

As suggested one dirty workaround is by overriding the the onclose handler.

But it would also work if socket.io would just something like a "isDisconnecting" event right before the actually cleanup happens. This could be right before the call to this.leaveAll() in the onclose handler happens:
```javascript
Socket.prototype.onclose = function(reason){
...
  this.emit('disconnecting', reason); //<--insert the new event here
  this.leaveAll();
...
  this.emit('disconnect', reason);
});
```
(the exports.events array has to be extended by the new eventname to get this working)

**Comment by derikb** [comment]
+1, this has caused me no end of headaches in my code. It would simplify so much.

**Comment by atomicframeworks** [comment]
Just experienced this.  Would be a nice to have.

**Comment by mattkenefick** [comment]
+1, this is very frustrating

**Comment by fydo23** [comment]
+1

**Comment by EmilTholin** [comment]
+1

**Comment by bodyflex** [comment]
+1

**Comment by shaggybb** [comment]
I have the same problem to solve it. You can develop an in-memory object
where you can save socket.id (or other identifier) with rooms. In
disconnect event you can query this object to know the rooms you have to
leave.

If you are using some DB o NoSQL you can save it for distributed
environments.

Additonally, if rooms list is temporary you can clean it whit controlled
event after disconnecting.

**Comment by bodyflex** [comment]
this is how I went to solve my problem, I simply wanted to display a count of all the users currently in a room:
```
var rooms = [];
io.on('connection', function(socket) {
	var room;
	socket.on('join', function(_room) {
		room = _room;
		socket.join(room);
		if (room in rooms)
			rooms[room]++;
		else
			rooms[room] = 1;
		io.to(room).emit('client joined', { clients: rooms[room] });
	});

	socket.on('disconnect', function() {
		leaveRoom();
	});

	var leaveRoom = function() {
		rooms[room]--;
		io.to(room).emit('client left', { clients: rooms[room] });
		if (rooms[room] === 0)
			delete rooms[room];
	};
});
```
don't know if it's any good though.

**Comment by ouabing** [comment]
+1

**Comment by frostfang** [comment]
plus elebenty, however did find bodyflex's implementation useful

**Comment by Aliance** [comment]
+1

**Comment by abaranovskii** [comment]
+1

**Comment by darrachequesne** [comment]
Hi! I suggested here (https://github.com/socketio/socket.io/issues/2266) adding 'roomJoined' and 'roomLeft' events, would such a solution suit your needs?

```javascript
server.on('roomJoined', function (id, room) {
  console.log('Socket %s has joined room %s', id, room);
});
server.on('roomLeft', function (id, room) {
  console.log('Socket %s has left room %s', id, room);
});
```

**Comment by X-Coder** [comment]
Your suggestion goes a little into a different direction.
I would prefer something like a new "disconnecting" event to handle stuff in one function, when the client is disconnecting. Like in my example I posted https://github.com/socketio/socket.io/issues/1814#issuecomment-73375702.

**Comment by darrachequesne** [comment]
Well, on second thought, your solution seems cleaner to me. Please note that you may have to clone the array `socket.rooms`, in order to prevent any race condition:
```javascript
client.on('disconnecting', function(){
  console.log(client.rooms);
  var clonedRooms = client.rooms.slice();
  setTimeout(function() {
    console.log(client.rooms); // empty array
    console.log(clonedRooms);
  }, 100);
});
```

**Comment by misiek08** [comment]
It's a must have feature to have pre-disconnect event. Handling cleanup is much harder without this.

**Comment by oskbor** [comment]
I am currently overriding the `onclose` handler, would love a solution to this. My override is as simple as emitting the `disconnect` event before leaving the rooms.

**Comment by phutchins** [comment]
I also added a disconnecting event that fires before disconnect and came to submit a PR to find that someone had already submitted a PR with nearly identical code :). +1 for PR #2332 !

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io/pull/2332 :angel:

**Comment by dragosstancu** [comment]
You don't need to add events, you need to store all the connected sockets into an associative array with keys being the socked IDs. Then, on 'disconnect', you retrieve the room for that socket ID.

let sockets={};
let rooms={};

io.on('connection', function(socket) {
    sockets[socket.id]={
        room:<whatever>
    }

    socket.on('disconnect', (reason) => {
            let room=sockets[socket.id].room;
            io.to(room).emit('message', {
                message: 'I'm out!'
            });
    });
}

**Comment by tribeless** [comment]
Hello everyone, how I was able to solve this was like so:

socket.on(disconnecting,()=>{
     const rooms = Object.keys(socket.rooms);
     io.to(rooms[1]).emit("event", "message");
});

Thanks, hope it helps someone

**Comment by ysawyers** [comment]
See the problem with that is even on the disconnecting event; the room I added is removed and the only thing left in the set is the socket.id. Basically useless :/

**Comment by giovanni-bertoncelli** [comment]
I'm trying to use an async function on `disconnecting` event but probably when the async function gets called the `socket.rooms` are already emptied... Is there any way to listen to the event with an async listener?

**Comment by darrachequesne** [comment]
@giovanni-bertoncelli in that case, you will need to create a copy of the `socket.rooms` set:

```js
io.on("connection", (socket) => {
  socket.on("disconnecting", async (reason) => {
    const rooms = new Set(socket.rooms);

    await someLongRunningOperation();

    // socket.rooms will be empty there
    console.log(rooms);
  });
});
```

Added here: https://socket.io/docs/v4/server-api/#event-disconnecting

**Comment by giovanni-bertoncelli** [comment]
Ok thank you very much!!
