### ISSUE TITLE
I use socket.io 1.0 send a webm blob data to client,how to set it on the client side

### ISSUE THREAD

**Issue by haibo32012** [socketio/socket.io#1818]
this is server side:  
fs.readFile('./message.webm',function(err,data) {
      if (err) throw err;
      socket.broadcast.emit('message', {
        video: data
      });
    });

**Comment by sgarbesi** [comment]
@haibo32012 send the video in chunks.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
