### ISSUE TITLE
Namespace#clients does not exist

### ISSUE THREAD

**Issue by Korri** [socketio/socket.io#1819]
I was looking for a way to disconnect all clients in a room (room closes and clients should leave the server) and found this https://github.com/Automattic/socket.io/wiki/Rooms#clients-in-a-room

But when I try I get the error `Object #<Namespace> has no method 'clients'` is the wiki outdated ? I don't see this method anywhere else.

**Comment by jacargentina** [comment]
I think the wiki is not oudated, but VERY updated (with code not yet on any released socket.io version)
I'm beginning with socket.io, and i find there are lots of room for docs to be better/more detailed, etc.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
