### ISSUE TITLE
0.9.16 warn: error raised: Error: accept EMFILE

### ISSUE THREAD

**Issue by tomalex0** [socketio/socket.io#1820]
We were doing a load test in ubuntu server and at one point we were getting

`warn: error raised: Error: accept EMFILE`

Can anybody shed more details on this and what would be the possible fix.

If you want to know more details, please let me know

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
