### ISSUE TITLE
Get the list of all the ids of room across different servers

### ISSUE THREAD

**Issue by StevenRoan** [socketio/socket.io#1830]
I've distributed socket.io processes to multiple servers to scale up my service, and I need to get all the ids of rooms that exist in different servers. 

I know we can get the rooms name in single process by

```
Object.keys(io.sockets.adapter.rooms)
```

but I cannot get the information of the rooms in other server by socket.io it self.

So far, I noticed that there are several related discussions and pull request: 

[Automattic/socket.io#1811](https://github.com/Automattic/socket.io/issues/1811)
[Automattic/socket.io-redis pull#15](https://github.com/Automattic/socket.io-redis/pull/15)

My questions are:
- What I mentioned is correct or not?
- Should socket.io include some inter-server communication mechanism to let user get the information from other server? Or this kind of adapter should be implemented in each customized adapter itself as mentioned in the [Introduction of Sokcet.io 1.0 # Scalability](http://socket.io/blog/introducing-socket-io-1-0/#scalability)

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
