### ISSUE TITLE
Testing: how to wait until message has been sent

### ISSUE THREAD

**Issue by shaunc** [socketio/socket.io#1833]
I understand that callbacks have been disabled on broadcast to rooms... (for performance reasons?). This causes a problem for testing. I want to test that a client properly leaves a room -- and therefore does not receive a given message. What should I wait for to know that the client might not still get a message?

IMHO it should be possible to get a callback at least to know that the message has been sent. 

[NB in testing environment there seem to be many places where its difficult to know if async activity has been completed. listen() also doesn't accept a callback.]

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
