### ISSUE TITLE
Passing cookies during handshake

### ISSUE THREAD

**Issue by ggrav** [socketio/socket.io#1840]
My deployment environment provides sticky connection via a Cookie parameter which is got when the first get request is made to the server. The subsequent request needs to pass the cookie for providing the sticky connection. 

I verified that The cookies are getting passed correctly when running the client in the browser. However, the cookie information is not coming to the server , if I run the client  code as a node.exe process 

Below is my stripped down version of the client code. Any idea on how I can pass the cookie information ?

var io = require("socket.io-client");

var socket = io.connect(http://bubble.trafficmanager.net/, { 'force new connection' : true });

socket.on('connect', function () {
});

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
