### ISSUE TITLE
Mechanism to add a client to a room with only his ID?

### ISSUE THREAD

**Issue by alexcastano** [socketio/socket.io#1851]
I see currently it is possible to send a message to a socket because a default room is created with his ID.

However I don't know if it would be possible to add this socket to a room, to remove from a room or just to disconnect it, of course in multi server environment. Any ideas?

Thank you!

**Comment by hekike** [comment]
Did you find the right solution how to do this in multi-server env?

I really liked @alexcastano 's approach: `io.join(socketId, roomId)`

**Comment by infnada** [comment]
Maybe this can help you https://github.com/socketio/socket.io/issues/2458

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-redis/pull/168.

```js
io.adapter.remoteJoin('<my-id>', 'room1', function (err) {
  if (err) { /* unknown id */ }
  // success
});

io.adapter.remoteLeave('<my-id>', 'room1', function (err) {
  if (err) { /* unknown id */ }
  // success
});
```

**Comment by Assdi** [comment]
can i do this without redis ? @darrachequesne
