### ISSUE TITLE
xhr poll error come out is throwing while use socket.io

### ISSUE THREAD

**Issue by Jeremy-Zheng** [socketio/socket.io#1852]
I wrote a very simple demo about socket.io And I package it by using phonegap. I found there is problem. After I open my app about ten seconds ,the connection will disconnect because of xhr poll error.if I refresh the page in disconnect event the error won't come again. I use 1.2.0 version..here is my code. I already simplify it.

server:

var express = require('express');
var app = express();
var http = require('http').Server(app);
var io = require('socket.io')(http);
var path = require('path');

var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');

app.use(bodyParser.json());
app.use(bodyParser.urlencoded());
app.use(cookieParser());

app.use(express.static(path.join(__dirname, 'public')));

io.sockets.on('connection', function (socket) {

```
console.log("disconnect--"+socket.id+"--"+io.sockets.server.eio.clientsCount);

socket.on('disconnect', function () {
    console.log("disconnect--"+io.sockets.server.eio.clientsCount);
});
```

});

http.listen(80, function () {
    console.log("server statrt");
});

client:

 $(document).ready(function () {

```
            var socket = io("http://192.168.0.106:80");

            socket.on('connect', function () {
                alert("connect");
            });

            socket.on('error', function (data) {
                alert(data);
            });

            socket.on('disconnect', function () {
                alert("disconnect");
            });

            socket.on("reconnect", function () {
                alert("reconnect");
            })

        });
```

**Comment by marin42** [comment]
Same problem here, anyone found a solution?

**Comment by wf123537200** [comment]
Same problem here, anyone found a solution?

**Comment by wanming** [comment]
Same problem, It happend in here ( from the stack ):
node_modules/engine.io-client/lib/transports/polling-xhr.js
(Seems link engine.io problem :(
```javascript
xhr.onreadystatechange = function(){
        if (4 != xhr.readyState) return;
        if (200 == xhr.status || 1223 == xhr.status) {
          self.onLoad();
        } else {
          // make sure the `error` event handler that's user-set
          // does not throw in the same tick and gets caught here
          setTimeout(function(){
            self.onError(xhr.status); // HERE!!
          }, 0);
        }
      };
```

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by malavshah9** [comment]
@darrachequesne  I am facing same issue. We should reopen this issue if possible

**Comment by darrachequesne** [comment]
@malavshah9 please check the troubleshooting page here: https://socket.io/docs/v4/troubleshooting-connection-issues/

If it doesn't fix your issue, please open a new issue with all necessary details. Thanks!
