### ISSUE TITLE
Scaling socket.io on multiple servers and processes

### ISSUE THREAD

**Issue by refaelos** [socketio/socket.io#1853]
Hey all,

I'm using socket.io on multiple servers (several Azure machines) and processes (using cluster).
I found the regular answers that say I should use sticky sessions to make sure connections to an instance of socket.io will continue going to the same process between calls but I don't understand why sticky sessions are a good solution and how to solve this problem:
1. The was to implement sticky sessions is to have one "server" that is used as a kind of a proxy. This slows down the server and can create a load issue on some of the processes. It might take out the edge of having multiple processes.
2. How does sticky sessions solve the issue of having multiple different machines?
3. On earlier versions of socket.io I could set up a redis store that took care of that. Where did it go (and why?)?

Am I right in all my points here or am I completely off track?
Not sure what i'm missing.

Thanks in advance :)
We LOVE socket.io :heart:

**Comment by Hussion** [comment]
@nkzawa can you provide a complete demo of socket.io with cluster ? i really need it, thanks very much ! because this [#1944](https://github.com/Automattic/socket.io/issues/1944)

**Comment by objectiveSee** [comment]
FWIW @Hussion We moved away from using Cluster because you would need RedisAdapeter for multi-instance scaling anyways. Instead, on each instance we create 34 Node processes listening on incrementing ports, then use HAProxy to balance between them.
