### ISSUE TITLE
TypeError on method sendFile

### ISSUE THREAD

**Issue by teodors** [socketio/socket.io#1855]
I was bumping my head around for a good hour not understanding why the chat example didn't work. Turns out you have to use `sendfile()` not `sendFile()` in this part:

```
app.get('/', function(req, res){
    res.sendFile(__dirname + '/html/index.html');
});
```

Or else console and browser will spit out this:

```
TypeError: Object #<ServerResponse> has no method 'sendFile' at Object.handle
...
```

I am using Windows 8.1 64bit.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
