### ISSUE TITLE
howto migrate snippet to 1.2.0?

### ISSUE THREAD

**Issue by vinnitu** [socketio/socket.io#1877]
``` javascript
setInterval(function () {
    io.sockets.clients().forEach(function(socket) {
        var transport = socket.manager.transports[socket.id];
        if (transport && transport.open && new Date - new Date(socket.handshake.time) > 4*60*60*1000) { //more then 4 hours
            transport.error('booted', 'reconnect');
        }
    });
}, 60*1000); //check every minute

```

this code using to force disconnect socket after 4 hours

How to make the same in v1.2.0?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
