### ISSUE TITLE
what is the documentation style of socket.io now?

### ISSUE THREAD

**Issue by benpptung** [socketio/socket.io#1878]
Is there any reference to study how to read Automattic's socket.io javascript documentation style?
Javascript is not a strong-typed language, but it seems the current NEW js documentation style of socket.io "think" it is a typed language, and it is different from other famous javascript projects, e.g. koa, express, mocha, ...etc. 

It's fun to read their documentation, but it is really a pain to read socket.io NEW documentation style. Previously, 0.9 is easy to read, but now... I beg someone to explain where is the documentation style from, so I can know how to use the new socket.io 1.0

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
