### ISSUE TITLE
concurrent 80000 socket.io  cpu 100% for 6 process. this is GC info

### ISSUE THREAD

**Issue by hackeridear** [socketio/socket.io#1881]
- processId:10238---【stats】:{"num_full_gc":71,"num_inc_gc":1415,"heap_compactions":71,"usage_trend":68.5,"estimated_base":241286421,"current_base":286648648,"min":37596536,"max":418197192}
  processId:17778---【stats】:{"num_full_gc":37,"num_inc_gc":11079,"heap_compactions":37,"usage_trend":15.4,"estimated_base":340030568,"current_base":322598600,"min":31301392,"max":502795640}
  processId:10244---【leak】:{"start":"2014-11-21T05:42:50.000Z","end":"2014-11-21T05:43:45.000Z","growth":138244824,"reason":"heap growth over 5 consecutive GCs (55s) - -2147483648 bytes/hr"}
  【stats】:{"num_full_gc":72,"num_inc_gc":3245,"heap_compactions":72,"usage_trend":86,"estimated_base":268137191,"current_base":396121832,"min":25931360,"max":396121832}
  processId:17778---【stats】:{"num_full_gc":38,"num_inc_gc":11645,"heap_compactions":38,"usage_trend":14.7,"estimated_base":339082507,"current_base":330549960,"min":31301392,"max":502795640}
  processId:17821---【stats】:{"num_full_gc":20,"num_inc_gc":364,"heap_compactions":20,"usage_trend":0.5,"estimated_base":181938635,"current_base":181987688,"min":29999184,"max":299418928}
  processId:10244---【stats】:{"num_full_gc":73,"num_inc_gc":3801,"heap_compactions":73,"usage_trend":90.7,"estimated_base":281651478,"current_base":403280064,"min":25931360,"max":403280064}

this is  pm2 runconfig:
"node-args": "--nouse-idle-notification --gc_global --max-old-space-size=2048 --max-new-space-size=1024"

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
