### ISSUE TITLE
IPv6 URLs

### ISSUE THREAD

**Issue by ngn** [socketio/socket.io#1883]
The server part of `socket.io` has no issues with IPv6.  The client, however, fails to handle URLs of the form `http://[some:ipv6::address]:port`.  It treats the substring before the first colon as a hostname.

I noticed that the `browserify`-ed client script, `socket.io.js`, contains two version of the [`parseuri`](https://github.com/get/parseuri) library: 0.0.4 which supports IPv6 and 0.0.2 which doesn't, so this could possibly be a clue.

**Comment by nkzawa** [comment]
Should be supported on 1.4.
