### ISSUE TITLE
How to get all the rooms

### ISSUE THREAD

**Issue by barisusakli** [socketio/socket.io#1884]
#1630 already adds support for `.clients([room], fn);` to grab a list of socket ids in a room. I sent a PR to @FREEZX for adding the method `.roomClients([socketid],fn)` as well to grab a list of rooms the socket id is in.

This was possible in 0.9.x with `io.sockets.manager.roomClients[socket_id]` and it used to work across multiple nodes when used with RedisStore.

It was also possible to get a hash of all the rooms with `io.sockets.manager.rooms` but I don't see this available in 1.x. There is `io.sockets.adapter.rooms` but that doesn't work across nodes as far as I can see.

It is possible to get this data using the above two functions. First get all socket ids in room '' then call roomClients repeatedly to get the rooms and merge those but it means making n calls to roomClients, where as it was as simple as reading the `io.sockets.manager.rooms` object in 0.9.x

**Comment by ronkorving** [comment]
+1 on this one. You can't even make a decent chat system without the ability to list rooms.

**Comment by mike-aungsan** [comment]
(Y)

**Comment by nebkam** [comment]
:+1:

**Comment by vkv7** [comment]
Does anyone have a solution to getting access to the all rooms?

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-redis/pull/168.

```js
io.adapter.allRooms(function (err, rooms) {
  console.log(rooms); // an array containing all rooms (accross every node)
});
```

**Comment by ApplefaceLisa** [comment]
I'm using 2.0.4 and io.adapter.allRooms not work. Any idea?

**Comment by wangdalang** [comment]
no idea, need help...

**Comment by wangdalang** [comment]
i use  io.sockets.adapter.rooms

**Comment by Noitidart** [comment]
@wangdalang can you please show code example and link to docs for that. I can't seem to find it.

**Comment by minhquan1313** [comment]
console.log(`🚀 ~ io.adapter.rooms:`, io.adapter.rooms);
![image](https://github.com/socketio/socket.io/assets/20660062/4eb34435-22e5-46fd-bd83-28e78c6b679b)

**Comment by darrachequesne** [comment]
For future readers:

As noted above, you can have access to the list of rooms on a single server with:

```js
const rooms = io.of("/").adapter.rooms
```

Please note that this Map will contain:

- both public and private rooms (by "private" I mean the room named after each socket.id)
- only the rooms on this single server, in a multi-server setup

There is no native way to list all the rooms across multiple servers, it's up to you to implement it depending on your application logic.
