### ISSUE TITLE
Chat demo doesn't respond well to page zoom

### ISSUE THREAD

**Issue by jay** [socketio/socket.io#1889]
This is in Firefox 31 ESR but I've noticed it in other Firefox versions. If I have page zoom enabled the chat demo doesn't display properly. The easiest way to reproduce is CTRL + and then send some messages. Here's a screenshot:

![capture](https://cloud.githubusercontent.com/assets/965580/5177768/e7382df4-742c-11e4-8bcf-f0254ee6b67f.PNG)

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
