### ISSUE TITLE
Socket.io + SSL cert problem

### ISSUE THREAD

**Issue by mcfdez** [socketio/socket.io#1895]
Hello
I implemented this on my server.js:
var express =   require('express'),
    http =  require('http'),
    https = require("https"),
    server =    http.createServer(app),
    fs = require('fs');

var app = express();

//SSL Keys
var privateKey  = fs.readFileSync('sslcert/server.key');
var certificate = fs.readFileSync('sslcert/server.crt');

//Apply the SSL
var credentials = {key: privateKey, cert: certificate};
var httpsServer = https.createServer(credentials, app);

//Start the connection
//httpsServer.listen(8080, 'localhost');
httpsServer.listen(8080);
console.log("Listening.....");

//Start Scoket.io
var io = require("socket.io").listen(httpsServer, credentials);

When I visit my app I see:

ReferenceError: io is not defined
var socket = io.connect('https://mydomain.com:8080');

Then, if I visit https://mydomain.com:8080/socket.io/socket.io.js I see NOT trusted connection and the tipical button to add an exception. My question is: is a problem with .key and .crt files? Is a problem of socket.io configuration?

Help please!!

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
