### ISSUE TITLE
A severe memory leak with Socket.io 1.2.1 (earlier as well)

### ISSUE THREAD

**Issue by AvnerCohen** [socketio/socket.io#1904]
I have a very simple socket.io server setup. My needs are to be able to communicate between server and client over sockets, but always on a one-to-one mode.
As such I created something simple as this on the client:

``` js
            var socket = io();
            socket.on('connect',function(){
                socket.emit('connected', UserName);
            });
```

And than on the server:

``` js
          io.on('connection', function (socket) {

            socket.on('connected', function (userName) {
               if (userName !== null) {
                 socket.join("RoomFor:"+ userName);
                }
            });
          });
```

So, each user has his own room I can now communicate with, and I can do this using my applicative userName (not socket id).

Now, on the same socket IO server, I also have express listening, with something like this:

``` js
app.get('/notify', function(req, res) {
  var data = querystring.parse(req.url.split('?')[1]);
  var userName = data.clientId;
  io.sockets.to('RoomFor:'+ userName).emit('notice', {event: data.event });
  res.writeHead(returnCode, {'Content-Type': 'text/plain'});
  res.end();
});
```

So, a very simple server side signaling solution.

However, something in this setup is leaking badely, I have created heapdumps and tried to compare the results, but couldn't make out anything out of it.

Any thoughts?

**Comment by rase-** [comment]
There was a room management memory leak fixed in 1.2.0. Which version were you running? Fixed in the latest release?

**Comment by AvnerCohen** [comment]
As the title of the issue suggested, using version 1.2.1.
Same occurred with earlier versions as well.

**Comment by ebuildy** [comment]
Could you post your test process please? Using socket.io a lot and never see any memory leak yet ;-)

**Comment by AvnerCohen** [comment]
I haven't tested it in any way, I just had the code running in production, code was crashing once reaching memory limit. The memory leak is observed in the graph I show above.

I was hoping to try and find the time to build a sample code demonstrating this, but I decided not to spend the time once I saw many similar open cases with no answers, it could be just something we are all doing wrong.

**Comment by 11001** [comment]
I'm also seeing a memory leak with a very similar setup.

~2k concurrent sessions with one room for each user. The server uses version 1.3.3 and I was able to observe the leak in previous versions as well.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
