### ISSUE TITLE
Socket.io with Apache as proxy issue

### ISSUE THREAD

**Issue by mark-veenstra** [socketio/socket.io#1905]
I am trying to get socket.io working with an Apache server as a proxy in front of it. Problem is that I receive the next error on the clients:
`GET http://subdomain.mydomain.com:8100/socket.io/?extra_info=fe4567&EIO=3&transport=polling&t=1416987210079-31 net::ERR_CONNECTION_TIMED_OUT`

I don't understand where the port 8100 comes from? I have configured the client the connect on port 80.

I described my complete setup here: http://stackoverflow.com/questions/27143605/configure-apache-2-4-7-for-proxying-socket-io

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
