### ISSUE TITLE
Socket.io docs need testing documentation

### ISSUE THREAD

**Issue by agconti** [socketio/socket.io#1906]
##### The docs need examples of how to write basic tests so programmers new to the framework can get started with best practices.

Right now, the [Socket.io docs](http://socket.io/docs/logging-and-debugging/) and Wiki don't contain any documentation on how to write unit or integration tests. This coupled with the fact that testing functionality that uses sockets is different than the type of testing many programmers are used to; makes it hard for new programmers to start to test their applications. 

I [created](https://github.com/agconti/socket.io.tests) a basic setup of what one of these examples might look like for testing node.js apps that use socket.io using the [mocha](http://mochajs.org/) and [chai](http://chaijs.com/) testing frameworks.

How can I contribute it?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
