### ISSUE TITLE
When Server Socket emit Buffer to Client, browser Client receive Empty ArrayBuffer

### ISSUE THREAD

**Issue by joeyzhu0422** [socketio/socket.io#1909]
server.js

var express = require('express');
var app = express();
var http = require('http');
var server = http.createServer(app);
var io = require('socket.io')(server);

app.get('/', function(req, res) {
    res.sendfile('test.html');
});

io.on('connection', function(socket) {
    console.log(socket);

```
var buf = new Buffer(1);
buf.writeUInt8(1, 0, 1);

socket.emit("data", buf);
```

});
server.listen(3000);

test.html

var socket = io.connect("http://localhost:3000");
socket.on('data', function(data) {
     console.log(data);
});

In the test.html receive data is empty ArrayBuffer, use nodejs client is ok

**Comment by MertOtrk** [comment]
Up ! Same problem.

**Comment by darrachequesne** [comment]
@MertOtrk oh! that might be because you use **that** browser

![image](https://cloud.githubusercontent.com/assets/13031701/21723068/67567bc6-d42f-11e6-85a1-1654b67bef5f.png)

How in the world are we supposed to fix without a proper way to reproduce? (which browser, which socket.io version?...)

Love :heart:

**Comment by MertOtrk** [comment]
http://stackoverflow.com/questions/41506577/socket-io-buffer-send

Please check problem.

**Comment by MertOtrk** [comment]
Chrome, latest version. Node v.4.4.7 👍

**Comment by darrachequesne** [comment]
I'm afraid I can't reproduce: https://github.com/darrachequesne/socket.io-chat/tree/empty-arraybuffer

```js
  // server
  function sendBuffer(){
    var buf = new Buffer(1);
    buf.writeUInt8(42, 0, 1);

    io.emit("binary", buf);
  }

  setInterval(sendBuffer, 2000);

  // client
  socket.on('binary', function (buf) {
    var view = new DataView(buf);
    console.log('byteLength:', view.byteLength, 'uint8:', view.getUint8());
    // prints "byteLength: 1 uint8: 42"
  })
```

**Comment by MertOtrk** [comment]
Thank you, its worked.
