### ISSUE TITLE
If reload page, socket disconnect event fired after new http request

### ISSUE THREAD

**Issue by klimashkin** [socketio/socket.io#1911]
Using Chrome, If call page reload, socket.on('disconnect') on server fired after new http request arrived to server. It hinders correct session management.
In firefox behavior is predictable - first disconnect current socket, then new http arrives

**Comment by rase-** [comment]
I don't think we could make this guarantee with anything better than the hack you mentioned.

> Can I ask how does this issue make your session management difficult?

I'd also be interested in knowing what are the issues that arise from this behaviour?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
