### ISSUE TITLE
Socket.IO 0.9 discover error

### ISSUE THREAD

**Issue by flashmandv** [socketio/socket.io#1913]
I'm building a mobile game using flash client and socket.io 0.9 server.
My game got popular and I got like ~300 connected clients at any time.
When the server is working for 24 hours, suddenly it starts responding only in ~10% of the cases.
I debugged the flash client and the socket.io library tryes to load as HTTP this url:

http://HOST:PORT/socket.io/1/?time=14187588...

Normally it receives status code 200 with something like: 

Io70X_FFWJFdyCpfp_3w:40:60:websocket,htmlfile,xhr-polling,jsonp-polling,flashsocket

but when the server hands - in 90% of the requests it receives response code 0 and no data, and in the other 10% of the cases receives the correct data and connects successfully.

Any ideas ?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
