### ISSUE TITLE
Callbacks Are Lost and Never Fail On Client Disconnect

### ISSUE THREAD

**Issue by nasserprofessional** [socketio/socket.io#1918]
Problem:
Suppose there's 2 clients that are connected to a server.

Client A ------> server <------- Client B

Client A needs to send a message to (Client B) so it emits a message that has a callback function
The server gets the message finds the socket Id for Client B emits it to Client B with another callback function

Client B is supposed to respond with a response that is then sent to Client A to acknowledge that everything went OK.

If at anytime in between if Client B disconnects or just closes the browser even after it receives the message from the server... just because it didnt say anything back because the connection was lost Client A will never get any response at all. It will be like as if the function didnt have a callback it doesnt get any response even though the Server knows Client B is never going to callback it doesnt return anything to Client A.

Im wondering why are callbacks not marked as failed when the client related to them gets disconnected?

Any ideas on how I can send Receipts to Client A that Client B got the message?

Is there any better way to pass receipts to Client A even if Client B disconnects? or Anyway to atleast return a failed callback on Client B disconnecting?

I was expecting Callbacks on the Server to fail if the Client the server is waiting for a callback from just disconnected or connection was lost or something. I know most callbacks probably happen so fast that we might not know what would happen if they get interrupted. 

Best way to re create the problem:
Make 2 socket.io pages that connect to a socket.io server
Make a button in page 1 that sends a message to page 2 and it displays a javascript alert and returns a message to the server that is then returned to page 1 that the message was delivered successfully.

open both pages in separate tabs and press the send button so it displays the alert on page 2. If you press ok on the alert it will return the message correctly but if you do the same again but instead of clicking on ok if you just close the tab with the alert open... page 1 will never get a failed callback or anything.

This means that if the client just disconnects while performing some operation it was supposed to return a callback after maybe the client was writing something to a local database and was supposed to tell the other client everything went ok this will never happen if the connection drops in between. Client A will never even know it has to retry to send its data or maybe save it somewhere temporary so it can retry again or mark something in a database that Client B can check back for something that happened while it was offline.

**Comment by wedneyyuri** [comment]
@nkzawa Any progress on this issue? 

Related issues: 
 - https://github.com/socketio/socket.io-client-java/issues/309
 - https://github.com/socketio/socket.io-client-java/issues/322

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
