### ISSUE TITLE
Upgrade to websocket to specific server

### ISSUE THREAD

**Issue by joakimrapp** [socketio/socket.io#1923]
I use socket.io in Amazon with a couple of 100.000 simultaneous connections. My problem is that Amazon ELB (load balancer) only seem to support round robin for TCP-connections, which will, during up- and down-scaling render an uneven distribution och websockets.

Is it possible to, when updgrading to websocket, send the client to another host (e.g. a specific server in the cluster, with the least number of connections)?

Thanks for a great project by the way!

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
