### ISSUE TITLE
Socket.io 1.2.1 + nodejs 0.10.32 error 324 ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by flashmandv** [socketio/socket.io#1925]
I'm using nodejs version 0.10.32 and Socket.IO 1.2.1 to build app. When the server is working for couple of hours, at some point it stops accepnting connections and returns error 324 ERR_EMPTY_RESPONSE. The strange thing is that it does not completely stops, but it stops in most cases. After the 5-10th connection attempt - it succees. 

The url that my flash client is loading is this:
http://HOST:PORT/socket.io/?EIO=2&time=1419436839425&transport=polling

I opened another case for socket.io 0.9 version (https://github.com/Automattic/socket.io/issues/1913), but after upgrading - the problem still exists :(
Please help

**Comment by flashmandv** [comment]
It seems the problem happens again. It is not the memory leak that is causing it.
I fixed the memory leak and now after the system is not loaded at all - it happens again.
It seems socket.io can handle only small load of maximum 200 connections, but definitely not thousands...

**Comment by flashmandv** [comment]
here are some more server logs containing errors:

Mon, 05 Jan 2015 17:36:27 GMT engine:socket sending packet "message" (0)
Mon, 05 Jan 2015 17:36:27 GMT engine:socket transport error
Mon, 05 Jan 2015 17:36:27 GMT engine intercepting request for path "/socket.io/"
Mon, 05 Jan 2015 17:36:27 GMT engine handling "GET" http request "/socket.io/?EIO=2&time=1420479386086&transport=polling"
Mon, 05 Jan 2015 17:36:27 GMT engine handshaking client "Nnqkymw3gSEkIoeMABax"
Mon, 05 Jan 2015 17:36:27 GMT engine:socket sending packet "open" ({"sid":"Nnqkymw3gSEkIoeMABax","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000})
Mon, 05 Jan 2015 17:36:27 GMT engine:polling setting request
Mon, 05 Jan 2015 17:36:27 GMT engine:socket flushing buffer to transport



Mon, 05 Jan 2015 17:36:39 GMT engine:socket sending packet "message" (0)
Mon, 05 Jan 2015 17:36:39 GMT engine:socket transport error
Mon, 05 Jan 2015 17:36:39 GMT engine:socket error triggered by discarded transport
Mon, 05 Jan 2015 17:36:39 GMT engine upgrading existing transport
Mon, 05 Jan 2015 17:36:39 GMT engine:socket might upgrade socket transport from "polling" to "websocket"
Mon, 05 Jan 2015 17:36:39 GMT engine intercepting request for path "/socket.io/"
Mon, 05 Jan 2015 17:36:39 GMT engine handling "GET" http request "/socket.io/?EIO=3&transport=polling&t=1420479277863-33&sid=ycn4-IOFOlHkALe1AAJR"
Mon, 05 Jan 2015 17:36:39 GMT engine:ws received "2probe"
Mon, 05 Jan 2015 17:36:39 GMT engine:ws writing "3probe"
Mon, 05 Jan 2015 17:36:39 GMT engine intercepting request for path "/socket.io/"
Mon, 05 Jan 2015 17:36:39 GMT engine handling "GET" http request "/socket.io/?EIO=2&time=1420475918784&transport=polling"
Mon, 05 Jan 2015 17:36:39 GMT engine handshaking client "qE-Y3wfbXRCtixcQABkM"

**Comment by candelachris** [comment]
Hello,

I have EXACTLY the same problem with my chat server. ERR_EMPTY_RESPONSE error as soon as I have a lot of users connected at the same time.

Did you finally find a fix for this ? Or is it a bug in the socket.io library ?

Thanks

**Comment by flashmandv** [comment]
Yes - my fix was to drop the socket.io and use raw TCP socket via: net.createServer(..)
I'm using flash client, so I don't really need to use WebSocket connection.
Thank god I get rid of this peace of $#$@ - it was leaking memory apart from this problem
Good luck
