### ISSUE TITLE
Safari (Mac Only) crashes when using websocket

### ISSUE THREAD

**Issue by pbcomm** [socketio/socket.io#193]
I am using the very basic example listed on the website, not sending or receiving any messages, just connecting. 
Connection is on 127.0.0.1:80
On connect Safari crashes with following:

Process:         Safari [11081]
Path:            /Applications/Safari.app/Contents/MacOS/Safari
Identifier:      com.apple.Safari
Version:         5.0.5 (6533.21.1)
Build Info:      WebBrowser-75332101~1
Code Type:       X86-64 (Native)
Parent Process:  launchd [238]

Date/Time:       2011-04-23 02:40:30.463 -0400
OS Version:      Mac OS X 10.6.7 (10J869)
Report Version:  6

Interval Since Last Report:          140807 sec
Crashes Since Last Report:           20
Per-App Interval Since Last Report:  36857 sec
Per-App Crashes Since Last Report:   16
Anonymous UUID:                      545FB01F-FF2E-4A16-9EFC-A8A538906A53

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000000
Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Thread 0 Crashed:  Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation        0x00007fff87e11c00 CFArrayGetCount + 80
1   com.apple.WebCore               0x00007fff82a3150b WebCore::SocketStreamHandle::chooseProxyFromArray(__CFArray const_) + 43
2   com.apple.WebCore               0x00007fff82cc6088 WebCore::SocketStreamHandle::pacExecutionCallbackMainThread(void_) + 24
3   com.apple.JavaScriptCore        0x00007fff87bf6848 WTF::callOnMainThreadAndWait(void (_)(void_), void_) + 72
4   com.apple.WebCore               0x00007fff82cc5ec0 WebCore::SocketStreamHandle::pacExecutionCallback(void_, __CFArray const_, __CFError_) + 32
5   com.apple.CFNetwork             0x00007fff86cd167c executionContextPerform(void*) + 1079
6   com.apple.CoreFoundation        0x00007fff87e4f401 __CFRunLoopDoSources0 + 1361
7   com.apple.CoreFoundation        0x00007fff87e4d5f9 __CFRunLoopRun + 873
8   com.apple.CoreFoundation        0x00007fff87e4cdbf CFRunLoopRunSpecific + 575
9   com.apple.HIToolbox             0x00007fff830237ee RunCurrentEventLoopInMode + 333
10  com.apple.HIToolbox             0x00007fff83023551 ReceiveNextEventCommon + 148
11  com.apple.HIToolbox             0x00007fff830234ac BlockUntilNextEventMatchingListInMode + 59
12  com.apple.AppKit                0x00007fff80441e64 _DPSNextEvent + 718
13  com.apple.AppKit                0x00007fff804417a9 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 155
14  com.apple.Safari                0x0000000100015ff6 0x100000000 + 90102
15  com.apple.AppKit                0x00007fff8040748b -[NSApplication run] + 395
16  com.apple.AppKit                0x00007fff804001a8 NSApplicationMain + 364
17  com.apple.Safari                0x0000000100009f18 0x100000000 + 40728

**Comment by filipencu** [comment]
The same issue are present in iOS 9.2 with Phonegap/webview implementation.

**Comment by charles-passille-smartnets** [comment]
Still an issue for me. ExpressJS/NodeJS & socket.io

**Comment by dinesh93** [comment]
When Streaming audio through websocket it show an error message **failed: Failed to send WebSocket frame.** in ionic app

**Comment by flav-code** [comment]
Same issue :/
