### ISSUE TITLE
FATAL ERROR: JS Allocation failed - process out of memory

### ISSUE THREAD

**Issue by utan** [socketio/socket.io#1930]
I have that error, Don't know where to start...

My app have very little users and have enough memory .. 
I think someone is sending a payload just like the previous vulnerabilities in socket.io

**Comment by utan** [comment]
ï¿½0{"sid":"TwR5Jw8Ii0LhTnD4AAAC","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}"
Does that makes any sense?

**Comment by utan** [comment]
What happens is socket.io isn't throttled somehow, anyone could emit with a loop and kill server..
Does anyone know any node module to help on this?

Really need your help if anyone, any pointers I being attacked by same guy that manage to find 
https://github.com/Automattic/socket.io/issues/1880

**Comment by rauchg** [comment]
You could add throttling at the proxy level.

**Comment by utan** [comment]
Can u give me an example, all i tried to do is at socket.io level but isnt enough..

Just a pointer or example or Node module that could help.

**Comment by rauchg** [comment]
Can you send us the log output or a test case to reproduce the problem?

**Comment by utan** [comment]
My log is 3 gigs long that was created in 5 minute attacks..

My server has origin set for specific domains , so attacker edited on the fly my client side code and loope'd emit method to overflowed the server.

He used defaul message emit and or a custom I made, if u would I can give u access to my server and u could look at logs.. 

Though the big ones I saved them and deleted from server... 

Let me know if u are intered in reading them..

A test case just loop the in the client to socket.io event like message and u will kill it..
