### ISSUE TITLE
Safari 8 fails on first connection and reconnects

### ISSUE THREAD

**Issue by johanneswuerbach** [socketio/socket.io#1932]
When connecting Safari 8 (from Sauce) to a local server (testem via sauce connect proxy), the initial connection fails and the browser is always reconnected.

The first connection fails to upgrade to use websockets as expected (sauce proxy can't handle websockets), but then downgrading back to polling fails with a 500 error.

https://www.dropbox.com/s/za5qk0pmu69eszk/Screenshot%202015-01-06%2018.59.36.png?dl=0

The unsupported protocol errors are from my test suite and unrelated.

Here is the server-side log (testem):

```
socket.io-parser decoded 2["browser-login","Safari 8.0",null] as {"type":2,"nsp":"/","data":["browser-login","Safari 8.0",null]} +14s
  socket.io:socket got packet {"type":2,"nsp":"/","data":["browser-login","Safari 8.0",null]} +14s
  socket.io:socket emitting event ["browser-login","Safari 8.0",null] +1ms
  socket.io-parser decoded 2["tests-start"] as {"type":2,"nsp":"/","data":["tests-start"]} +1s
  socket.io:socket got packet {"type":2,"nsp":"/","data":["tests-start"]} +1s
  socket.io:socket emitting event ["tests-start"] +1ms
  socket.io:client client close with reason transport close +16s
  socket.io:socket closing socket - reason transport close +1s
  socket.io:client ignoring remove for hZvi-vpQudN1BB9PAAAE +0ms
  socket.io:server incoming connection with id yr8lhRU7KiNYv3EMAAAF +17s
  socket.io:client connecting to namespace / +809ms
  socket.io:namespace adding socket to nsp / +17s
  socket.io:socket socket connected - writing packet +810ms
  socket.io:socket joining room yr8lhRU7KiNYv3EMAAAF +0ms
  socket.io:client writing packet {"type":0,"nsp":"/"} +1ms
  socket.io-parser encoding packet {"type":0,"nsp":"/"} +2s
  socket.io-parser encoded {"type":0,"nsp":"/"} as 0 +0ms
  socket.io:socket joined room yr8lhRU7KiNYv3EMAAAF +0ms
  socket.io:client client close with reason ping timeout +57s
  socket.io:socket closing socket - reason ping timeout +57s
  socket.io:client ignoring remove for RVv-FZRBWigArwU6AAAD +1ms
```

Any ideas how to further debug this issue? Here is my socket.io implementation: https://github.com/airportyh/testem/pull/450
Server: https://github.com/johanneswuerbach/testem/blob/upgraded-socket-and-express/lib/server/index.js
Client: https://github.com/johanneswuerbach/testem/blob/upgraded-socket-and-express/public/testem/testem_client.js

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
