### ISSUE TITLE
Get Array of Socket Objects in Room

### ISSUE THREAD

**Issue by alanjames1987** [socketio/socket.io#1937]
How do I get an array of all the socket objects in a room?

I don't just want the socket id but the full object. This is because I want to run a custom session method I added to each sockets with middleware.

**Comment by wen-bing** [comment]
I've the same problem. However I finally get the all sockets through this way:
```js
var clientStates = io.adapter.rooms[roomId];
var clients = [];
for (var id in clientStates) {
    if (clientStates[id]) {
         var socket = io.connected[id];
         clients.push(socket);
     }
}
```

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
