### ISSUE TITLE
`clients` API

### ISSUE THREAD

**Issue by rauchg** [socketio/socket.io#1945]
- For fetching all client ids in the server locally
- For fetching all client ids from all nodes (`socket.io-redis`: `allClients`)
- Support for getting client ids in a specific room

**Comment by nickguo** [comment]
@rauchg I would like to help out with this ticket! Please let me know if there is anyone else currently looking into it as well. Also, it'd be great to have an overview of what's needed and some resources or pointers to get started with. :)

**Comment by rauchg** [comment]
@nickguo definitely welcome. Ping me on Slack so I can give you specifics

**Comment by kapouer** [comment]
@rauchg could you check https://github.com/Automattic/socket.io/pull/2063 ?
it makes https://github.com/edasarl/socket.io-backlog/commit/91e86de444675f5b36a2a393e5bda52ecda8f1ff less ugly.
It's a bit related to a "getting clients".

**Comment by rauchg** [comment]
Done

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-adapter/pull/24 and https://github.com/socketio/socket.io-redis/pull/109.
