### ISSUE TITLE
Documentation revamp

### ISSUE THREAD

**Issue by rauchg** [socketio/socket.io#1948]
- Complete `README.md` API spec (like engine.io) for both `socket.io` and `socket.io-client`
- Permalink pages for method / properties on website

**Comment by rauchg** [comment]
Also update http://devdocs.io/socketio/

**Comment by axelpale** [comment]
Possible duplicate: #2020 

+1 on documentation improvement. Major issue for Socket.io growth. For example in some cases, precious info can be found from [github.com/Automattic/socket.io](https://github.com/Automattic/socket.io). In some others, from [socket.io/docs/](http://socket.io/docs/) only, such as [volatile messages](http://socket.io/docs/). Furthermore, as pointed out also by previous comments, docs are still insufficient and the behavior has to be digged out elsewhere, like is the situation with [socket.connection](http://stackoverflow.com/a/16518983/638546).

**Comment by alejonext** [comment]
+1 I like! We need a manual.

**Comment by jhohlfeld** [comment]
Yes please! 

plz remember mentioning connecting to a namespace needs the fully qualified url when using a non-standard port on the client:
http://stackoverflow.com/questions/32363060/socketio-namespace-client-connection-refused/34352508#34352508

And the interface of [Socket](http://socket.io/docs/client-api/#socket) is also incomplete. Had to dig out Socket.disconnect from src code.

**Comment by rauchg** [comment]
We're working on this @jhohlfeld. Thanks for taking the time to leave the feedback.
