### ISSUE TITLE
Can't send volatile message to a room

### ISSUE THREAD

**Issue by lucdetellis** [socketio/socket.io#1952]
I can't send a volatile message to a room. I've searched everywhere, but can't find any mention of how to do this. Here is what I've tried:

`io.volatile.to('someroom').emit('hello', data);`
`io.to('someroom').volatile.emit('hellp', data);`

**Comment by gpersons** [comment]
Possibly relevant SO:
http://stackoverflow.com/questions/25265860/socketio-volatile-emit-to-namespace

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
