### ISSUE TITLE
Could the name of 'emit event' be the same as the name of 'on event'?

### ISSUE THREAD

**Issue by 7demo** [socketio/socket.io#1953]
client :

<pre>
$(document).on('keyup',function(e){
    case 68:  //D
            io.emit('draw style keyCode',{"keyCode":e.keyCode,"objId":2});
            break;
});

io.on('draw style keyCode',function(data){
    console.log('get msg client');
})
</pre>

server：

<pre>
socket.on('draw style keyCode',function(data){
        console.log('get msg server');
        socket.broadcast.to(curName).emit('draw style keyCode',data);
 });
</pre>

I want to press 'D',someone could receive the msg in the same room. The name of emit event is the same as the name of on event.  However, it worked sometime and it did not other time(the server can get the msg, the client not).

When it didn`t work, i just changed the name of emit event and the name of on event.
client:

<pre>
io.on('draw style keyCode msg',function(data){
    console.log('get msg client');
})
</pre>

server:

<pre>
socket.on('draw style keyCode',function(data){
        console.log('get msg server');
        socket.broadcast.to(curName).emit('draw style keyCode msg',data);
 });
</pre>

So , the name of emit event can be the same as the name of on event? whick better? 

socket.io:0.9.5 (for some reason,i have to use it)

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
