### ISSUE TITLE
I want to use this make a push

### ISSUE THREAD

**Issue by HappinessMan** [socketio/socket.io#1960]
sometimes use it to send a message to a room ,just like broadcast.And in others, i want to use this send a message to a client,unicast,just like peer to peer.like two people have a chat. How can i take advantage of it. or send a message to a group client identify by user`s id

**Comment by ebuildy** [comment]
I believe this is your application logic. You have to "store" in NodeJS all socket instances, probably something like:

    var socketInstancesByUser = {"user1" : ["SOCKET1", "SOCKET2" ....], "user2" : ...}

And your groups:

    var usersByGroup = {"group1" : ["user1", "user2"]}

(Of course I make it simple, you probably use MongoDB or another DB).

Then do broadcast message to group1:

    usersByGroup["group1"].forEach(function(user)
    {
        socketInstancesByUser[user].forEach(function(socket)
        {
            socket.emit("message.group", "Hello group 1");
        });
    });

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
