### ISSUE TITLE
node.js & heroku issue

### ISSUE THREAD

**Issue by titopuertolara** [socketio/socket.io#1967]
Hi:

i´m trying to run one example into my heroku server but doesn´t work, but with my local nodejs server the example works fine, here´s the code:

/**
- Server.js
- @author : DiganmeGiovanni | https://twitter.com/DiganmeGiovanni
- @Created on: 25 Oct, 2014
  */

/\* Librerias necesarias para la aplicación */
var app  = require('express')();
var http = require('http').Server(app);
var io   = require('socket.io')(http);

/*\* **\* **\* ***
-  Configuramos el sistema de ruteo para las peticiones web
-  de manera que sin importar la ruta que el usuario solicite
-  siempre lo direccionaremos al html del sistema de chat.
  _/
  app.get('_', function(req, res) {
  res.sendFile( __dirname + '/views/chat.html');
  });

/*\* **\* **\* ***
-  Configuramos Socket.IO para estar a la escucha de
-  nuevas conexiones.
  */
  io.on('connection', function(socket) {
  
  console.log('New user connected');
  
  /**
  - Cada nuevo socket debera estar a la escucha
  - del evento 'chat message', el cual se activa
  - cada vez que un usuario envia un mensaje.
  - 
  - @param  msg : Los datos enviados desde el cliente a 
  -               través del socket.
    */
    socket.on('chat message', function(msg) {
    io.emit('chat message', msg);
    });
  
  /**
  - Mostramos en consola cada vez que un usuario
  - se desconecte del sistema.
    */
    socket.on('disconnect', function() {
    console.log('User disconnected');
    });

});

/**
- Iniciamos la aplicación en el puerto 3000
  */
  http.listen(3000, function() {
  console.log('listening on *:3000');
  });

when i upload this on heroku there is an error on my app, and when i put  node index.js the error is the following:
 url´s app: https://floating-shelf-7537.herokuapp.com/

C:\chatto\index.js:10
var io   = require('socket.io')(http);
                               ^
TypeError: object is not a function
    at Object.<anonymous> (C:\chatto\index.js:10:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

thanks for your help

**Comment by ebuildy** [comment]
On your production env, do you see node_modules directory with socket.io library?

**Comment by paradite** [comment]
@titopuertolara is this fixed by now?

**Comment by titopuertolara** [comment]
Yes, actually i changed the code http://www.emb-ideas.com/index.php/blogs/blog-de-tito/41-creando-un-mini-chat-con-node-js?highlight=WyJjaGF0IiwiY2hhdHMiXQ==

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
