### ISSUE TITLE
documentation escaping

### ISSUE THREAD

**Issue by darul75** [socketio/socket.io#1968]
on Sending and receiving events paragraph

**Comment by 1j01** [comment]
See issue on https://github.com/Automattic/socket.io-website/issues/19

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
