### ISSUE TITLE
Use express session in socket.io

### ISSUE THREAD

**Issue by nemanjavuk** [socketio/socket.io#1970]
I'm using express 4.11.1 with socket.io 1.3.2 (other dependencies are express-session 1.10.1, cookie-parser 1.3.3 and body-parser 1.10.2) and was trying to use express session in socket requests. For example, a user logs in into an app, his data are stored in the session and then for each and every one of his requests I use those data. It would be neat because of disconnect-reconnect cycle when socket loses all of its data on reconnection.

I tried something like this but it just doesn't seem to work:

```
var express = require('express'),
    app = express(),
    session = require('express-session'),
    cookieParser = require('cookie-parser'),
    sessionStore = new session.MemoryStore(),
    bodyParser = require('body-parser');
var server = require('http').createServer(app);
var io = require('socket.io')(server);
var port = process.env.PORT || 3000;

var sessionMiddleware = session({
  name: 'sid',
  store: sessionStore, // MemoryStore
  secret: 's3cr37',
  saveUninitialized: true,
  resave: true,
});

io.use(function(socket, next) {
  sessionMiddleware(socket.request, socket.request.res, next);
});

app.use(sessionMiddleware);
app.use(bodyParser.json())

server.listen(port, function() {
  console.log('Server listening at port %d', port);
});

app.post('/login', function(req, res){  
  //just storing the info in session
  req.session.username = req.body.user;
  ...
});

io.on('connection', function(socket) {
  //using socket.request.session.username which doesn't work
  ...
});
```

**Comment by Kiura** [comment]
Have almost the same issue... when I `destroy` session using socket, it wont regenerate and `socket.request.session.username` will fail (`TypeError: Cannot set property 'username' of undefined`).

**Comment by cruzlutor** [comment]
You guys can solve this issue? i have the same problem.

**Comment by Kiura** [comment]
@cruzlutor, as a hack for now I redirect the user on the client side which will regenerate the session

**Comment by MoLow** [comment]
Why not use https://www.npmjs.com/package/express-socket.io-session

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Comment by knoxcard** [comment]
I've been experiencing this issue forever and there is nothing in the documentation about this, i need to get this solved!
