### ISSUE TITLE
Connect event not fired in IE8

### ISSUE THREAD

**Issue by lucaswxp** [socketio/socket.io#1971]
Hey guys.

I can't get socket.io working in IE8.

I'm using version 1.0, it works in modern browser, but in IE8 the alert is never shown and no console errors also:

```javascript
socket = io('server.com', { forceNew: true, reconnection : false});
socket.on('connect', function(){
    alert('yep');
})
```

What could cause this?

**Comment by lucaswxp** [comment]
By the way. I watch the requests made, and no HTTP request is dispatched when in IE either.

**Comment by 01miru** [comment]
New SocketIO supports only modern browsers with websocket support, see http://socket.io/blog/introducing-socket-io-1-0/

**Comment by rase-** [comment]
@01miru we do support older browsers. Every connection starts with long polling and only upgrades to ws if it is available.

Hmm, @lucaswxp have you tried the latest release? Our tests do pass on IE8 just fine. Could you share a full minimal code snippet to try to reproduce this with?

**Comment by 01miru** [comment]
@rase- Oh sorry, my fault, i was thinking about flash ;-)

**Comment by lucaswxp** [comment]
Hey @rase-  Sorry for the long time to reply.

Yes, I have tried the latest version. Here is minimum code:

```html
<script src="/socket.io/socket.io.js"></script>
<script>
$('#redutor-form').submit(function(e){
  e.preventDefault();
  var socket = io('http://server.com:1338', { forceNew: true, reconnection : false });
	socket.on('connection', function(){
		alert('connect');
	})
});
</script>```

Server:
```javascript
var app = require('express')();
var server = require('http').Server(app);
var io = require('socket.io').listen(server);

server.listen(1338, function(){
    console.log('listening at 1338...');
});
io.set('transports', ['websocket', 'polling']);
io.on('connection', function (socket) {
  console.log('connected');
})
```

At first I thought the reason was that socket.io sends the /socket.io/socket.io.js file as `application/javascript` Content-Type,  where IE8 only understands `text/javascript`, but in the end it didn't make any difference when I changed.

Any ideas? No errors are shown, and the alert "connected" doesn't show up either.

**Comment by rase-** [comment]
@lucaswxp did you try `socket.on('connect')` instead of `socket.on('connection')` on the client side?

**Comment by lucaswxp** [comment]
@rase- Yes, I tried both.

**Comment by rase-** [comment]
@lucaswxp I was able to run that in saucelabs with small adaptations:

Client
```
<html>
  <body>
    <script src="/socket.io/socket.io.js"></script>
    <script>
      var socket = io({ port: 1338, forceNew: true, reconnection : false });
        socket.on('connect', function(){
            alert('connect');
        })
    </script>
  </body>
</html>
```

Server
```
var app = require('express')();
var server = require('http').Server(app);
var io = require('socket.io').listen(server);

server.listen(1338, function(){
    console.log('listening at 1338...');
});

app.get('/', function(req, res) {
  res.sendFile(__dirname + '/test.html');
});

io.set('transports', ['websocket', 'polling']);
io.on('connection', function (socket) {
  console.log('connected');
})
```

Could the problem be in the event you're listening to never happening? Do other browsers work fine, other than IE8?

**Comment by lucaswxp** [comment]
@rase- Yes, other browsers work fine. I'll try that snippet and let you know if it works.
