### ISSUE TITLE
fatal error LNK1181: cannot open input file 'kernel32.lib'

### ISSUE THREAD

**Issue by Daniel-Hug** [socketio/socket.io#1984]
```
LINK : fatal error LNK1181: cannot open input file 'kernel32.lib' [D:\Users\Dan
iel\Desktop\repos\Tiny-Finance\node_modules\karma\node_modules\socket.io\node_m
odules\socket.io-client\node_modules\ws\build\bufferutil.vcxproj]
```

![socketioerror](https://cloud.githubusercontent.com/assets/1326984/6069431/12683d1c-ad39-11e4-8f16-cc065319ec9d.png)

**Comment by rase-** [comment]
Even though the native code build fails `ws` has fallbacks in place and the installation was probably still successful. Are you experiencing isssues beyond this error?

**Comment by Daniel-Hug** [comment]
This socket.io installation was ran cause it's a dependancy of [karma](https://github.com/karma-runner/karma) which [I was installing](https://github.com/karma-runner/karma/issues/1303). The karma directory gets created but "karma" is not added to path.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
