### ISSUE TITLE
TypeError: Cannot read property 'base64' of undefined

### ISSUE THREAD

**Issue by utan** [socketio/socket.io#1986]
<code>
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property 'base64' of undefined
    at Decoder.add (/opt/node_server/socket.test/node_modules/socket.io/node_modules/socket.io-parser/index.js:250:29)
</code>

So is not new, but the spammer attacker is back doing bad things.. latest socket.io so @rauchg , if you can find what's going on?

If you need more help let me know.

**Comment by rauchg** [comment]
Are you sure you're using latest socket.io? We `try/catch` the decoder.

**Comment by utan** [comment]
Yes @rauchg , 

1.3.2 / 2015-01-19
==================

 * no change on this release

**Comment by rauchg** [comment]
of server.

**Comment by utan** [comment]
I am sorry I didn't get last you said? Of Server what?

**Comment by rauchg** [comment]
Are both server and client at `1.3.2` ?

**Comment by utan** [comment]
No, 1.3.0 ,

is it because of lower version?
didn't realize you guys upgraded client till now.

**Comment by utan** [comment]
Can you tag the socket.io client that is served from socket.io .. At least me after an upgrade always check the new client version served by socket.io..

**Comment by utan** [comment]
@rauchg , can you confirm that the above error is because A mismatched version of client and socket.io?

So I can undone what I did to mitigate the attacker..?

**Comment by rauchg** [comment]
Client and server are always in sync. The issue you are describing you have been fixed in 1.3.3 of Server: http://socket.io/blog/socket-io-1-3-3/

**Comment by utan** [comment]
@rauchg , thanks for you quick response.. I will upgrade my clients to ver. 1.3.3
