### ISSUE TITLE
Is data is sent in compressed format over websockets ?What if we want to compress data which we want to emit ?

### ISSUE THREAD

**Issue by mindfireon812** [socketio/socket.io#1996]

**Comment by rase-** [comment]
Not in the current release. The next release will be compressing data, see this PR for reference: https://github.com/Automattic/socket.io/pull/1958

Compression will be enabled by default, but can be turned off with `socket.compress(false).emit('ev', data)`.

**Comment by mindfireon812** [comment]
Is this done now,socket.io compressing data ?

**Comment by juzhen21510** [comment]
support now?

**Comment by CoreySwish** [comment]
+1

**Comment by LordMajestros** [comment]
Socket io version 1.3.6 supports compression but it causes memory leaks in the underlying websocket library [ws](https://github.com/websockets/ws) as seen here [#497](https://github.com/websockets/ws/issues/497).
Setting `perMessageDeflate: false` [ws](https://github.com/websockets/ws) in helps.
Hopefully a fix for [ws](https://github.com/websockets/ws) is coming soon and a way to set this from socket.io as well.

**Comment by nkzawa** [comment]
Supported on 1.4.

**Comment by EricBalingit** [comment]
@nkzawa I assume that `socket.compress(false)` indicates that the data will not be inflated at the client.  But I want to send already gzipped data.  Is it possible to do this using `socket.compress(false)`, or some other config, and have it automatically inflated by the browser?
