### ISSUE TITLE
Error event listener for middleware. How?

### ISSUE THREAD

**Issue by yura3d** [socketio/socket.io#1998]
I'm using NodeJS domains to catch any errors in my code. But this strategy doesn't working, when an error occures in socket.io middleware function, and I can't log information about it. (I see the only string "Missing error handler on `socket`." in my console.) How can I add error event listener for middleware?

**Comment by yura3d** [comment]
UP!

**Comment by henkosch** [comment]
+1

I tried adding my own error handler to the socket everywhere, but it doesn't work. My own listener is removed from socket.listeners somehow by the time the error occurs, so it gives the "Missing error handler on `socket`." message.

See this example:
```
io
    .of("/test")
    .use(function (socket, next) {
        socket.on("error", function (error) {
            console.log("custom error 1");
        });
        next();
    })
    .use(function (socket, next) {
        socket.on("error", function (error) {
            console.log("custom error 2");
        });
        non_existent();
        next();
    })
    .on("connect", function (socket) {
        socket.on("error", function (error) {
            console.log("custom error 3");
        });
    });
```

None of the custom error listeners are called.

Output:
```
Missing error handler on `socket`.
ReferenceError: non_existent is not defined
<trace>
```

And when you don't use a namespace, the error is not even catched, but the whole server crashes.

I think error handling in middlewares should be improved.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
