### ISSUE TITLE
"Missing error handler on `socket`" with domains. Why?!

### ISSUE THREAD

**Issue by yura3d** [socketio/socket.io#2007]
Hi! I'm trying to use NodeJS domains to handle errors in socket.io event listeners like this:

``` javascript
socket.on('my event', function (params) {
  var d = require('domain').create();
  d.add(socket);
  d.on('error', function (err) {
    socket.emit('my event', 'error text');
  });
  d.run(function () {
    non_existent_function();
    socket.emit('my event', 'success text');
  });
});
```

In this example, when I'm calling non_existent_function() (or making any other error) inside the domain, I'm getting the next message in the console:

```
Missing error handler on `socket`.
```

And my domain error handler is not called. Why? How can I handle errors in my event handlers inside the event context?

**Comment by MadhaviGiddaluri** [comment]
Please check whether you have added "socket.io" to your application.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
