### ISSUE TITLE
Update the tutorial for Express 4.8.0

### ISSUE THREAD

**Issue by userpixel** [socketio/socket.io#2008]
I followed the tutorial at http://socket.io/get-started/chat/ but the `sendfile()` is now replaced with `sendFile()`: http://expressjs.com/api.html#res.sendFile

So in order for that line to work `res.sendfile('index.html');` needs to change to `res.sendFile(__dirname + '/index.html');`

**Comment by hanifbbz** [comment]
Same issue exists in the code snippets on the home page: http://socket.io/docs/

**Comment by hanifbbz** [comment]
white at it you might want to take a look at all the `&amp;#039;` on that page too.

**Comment by frankcash** [comment]
This should probably be closed, the example uses Express version `4.10.2`

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
