### ISSUE TITLE
Handshake failed {"code":3,"message":"Bad request"}

### ISSUE THREAD

**Issue by bnouyrigat** [socketio/socket.io#2009]
I use Socket.IO in v1.3.2, configuring with transport=['websocket']. 
I have two differents clients: the official client in v1.3.2, and an iOS client (https://github.com/francoisp/socket.IO-objc).
The handshake phase is in success with the official client, but failed with Socket.IO-objc : the HTTP response returned is {"code":3,"message":"Bad request"}.
When I debug the handshake phase, the request of the official client is an UPDATE, while the request of the iOS client is a GET.

What is the expected request to initiate communication?
I would like to successfully communicate with the iOS client, thank you for your answers.

Benoît

**Comment by doronn** [comment]
have you ever found a solution for this? happens to me too with libgdx iOS client.
with client version 0.8.2

**Comment by darrachequesne** [comment]
For future readers: the Socket.IO session always starts with a `GET` request

Documentation: https://github.com/socketio/socket.io-protocol#sample-session
