### ISSUE TITLE
Possible BC break? HTTP/1.1 101 missing

### ISSUE THREAD

**Issue by Padam87** [socketio/socket.io#2015]
Hi,

We are working on a new project, and we are using socket.io 1.3.4 with elephant.io. When emmiting a message using elaphant.io, it throws an exception: https://github.com/Wisembly/elephant.io/blob/master/src/Engine/SocketIO/Version1X.php#L179

I've double cheked, and the 'HTTP/1.1 101' is indeed missing.

I've tried some earlier versions, and 1.3.1 works fine, 1.3.2 is the first problematic release.

**Comment by nkzawa** [comment]
It sounds this is the problem of elephant.io. I think you should create the issue on their repository.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
