### ISSUE TITLE
UTF8 "Invalid Continuation Byte" Problem

### ISSUE THREAD

**Issue by ahmetemir** [socketio/socket.io#2018]
I'm using socket.io 1.3.4 both server and client side.I'm getting this error on IE 6.As I read this utf 8 inconsistency problem (due to engine io) must be resolved at 1.0.6  but it seems it is continuing.

**Comment by anlumo** [comment]
I'm using socket.io 1.3.5 on both client (Chrome) and server, and I'm seeing the same issue as soon as I send non-ASCII characters from the server to the client.

However, it is not 100% consistent, sometimes the messages get through correctly (just by reloading the web page multiple times, no code changes). Maybe that happens 10% of the time.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
