### ISSUE TITLE
Web - Socket.io 1.3.4 cannot connect with port different from 80

### ISSUE THREAD

**Issue by LeoIannacone** [socketio/socket.io#2021]
Hi,

my app is running over localhost:3000, however socket.io cannot connect because it attends to:
```
GET http://localhost/socket.io/?EIO=3&transport=polling&t=1424860900773-6 net::ERR_CONNECTION_REFUSED
```

It seems port is not specified...

(everything is fine with version 1.2.*)

**Comment by jordanpappas** [comment]
you need to tell your client to connect to http://localhost:3000 . It is trying http://localhost, which defaults to port 80.

**Comment by LeoIannacone** [comment]
It does.

```
<script src="/socket.io/socket.io.js"></script>
```

```
var socket = io.connect('/');
```

But then I get:
```
GET http://localhost/socket.io/?EIO=3&transport=polling&t=1425030526780-8
net::ERR_CONNECTION_REFUSED socket.io.js:2919
```

Browser: Version 40.0.2214.111 Ubuntu 15.04 (64-bit)
Nodejs: v0.10.25
