### ISSUE TITLE
Socket descriptor leak

### ISSUE THREAD

**Issue by calzoneman** [socketio/socket.io#2026]
Possibly related to #1775 

Despite an update to `ws` supposedly fixing a file descriptor leak, I am observing a leak of socket file descriptors over time.  I set up a cron script to list `/proc/(pid)/fd` and count the number of sockets, and generated the following graph:

![2015-02-28-201833_1372x778_scrot](https://cloud.githubusercontent.com/assets/385672/6429196/55d187fa-bf88-11e4-86b0-96eb3125347b.png)

The dips in the graph occur during the mornings of EST, when my traffic drops off (due to a large chunk of my userbase being located in the USA).  I also confirmed by checking `/proc/net/tcp` that all of the sockets being leaked are connected to my socket.io port, not some other service.

I am using the v0.10 branch of node on Debian (from the NodeSource repo) with the latest version of socket.io.  I have tried nuking my node_modules folder and the npm cache and reinstalling socket.io to ensure everything is up to date.

Unfortunately I have not been able to reproduce the problem locally.  My best guess is there's some edge case in an error handler that causes the underlying socket to remain open.  Do you have any advice for how to debug this issue?  I've tried various means of destroying test client sockets to trigger ECONNRESET on the server, with no luck in causing extra fds to be leaked (the server has a `clientError` event handler for the HTTP server socket.io is attached to which destroys the socket).  I have tried forcing both the `websocket` and `polling` transports independently and both seem to leak.

**Comment by calzoneman** [comment]
I should note that my `ulimit -n` is set to 4096, which is why the number of descriptors is allowed to grow past 1024.  Once the limit of 4096 is reached, the application encounters `EMFILE`, terminates, and re-launches to start the cycle over again.

**Comment by calzoneman** [comment]
Upon further investigation, the problem is indeed `ws`.  The current version of `engine.io-client` that `socket.io-client` depends on (`1.5.1`) depends on `ws@0.4.31` which is a version of `ws` that is affected by file descriptor leaks.

@rauchg Any ETA on when the npm version will be bumped so this issue can be resolved without having to manually replace dependencies?

**Comment by rauchg** [comment]
Thanks for the research @calzoneman. The `1.4.0` release shall include this fix.

**Comment by calzoneman** [comment]
Referencing the relevant `ws` issue here for posterity: https://github.com/websockets/ws/issues/392

**Comment by calzoneman** [comment]
Thanks for the update.  Do you have a rough idea of when `1.4.0` will be released?  I don't mean to be pushy, I'm just trying to decide whether I want to stick with polling for a little bit until the fix is released, or manually update `ws` in my `node_modules`.

**Comment by rauchg** [comment]
@calzoneman we're still a 1-2 weeks out. For the moment I recommend you override `ws`

**Comment by calzoneman** [comment]
Sounds good.  Thanks again.

**Comment by calzoneman** [comment]
I just realized I made a stupid mistake. I was looking at the dependencies for the client and not the server.

I'm on mobile so I can't check currently, but is the server side of engine.io using an up to date ws?  I have narrowed the problem down to websockets specifically (switched to polling and the leak immediately disappeared)

Calvin

**Comment by rauchg** [comment]
Just bumped server as well

**Comment by calzoneman** [comment]
Update: I've noticed that even if I manually replace `ws` in `node_modules/socket.io/node_modules/engine.io/node_modules/` with the latest version, socket.io still consistently leaks websocket connections.  I've switched back to polling for now.

**Comment by rauchg** [comment]
Interesting. @calzoneman, can you reproduce this with a controlled setting (eg: test script)?

**Comment by calzoneman** [comment]
That's what I've been trying to come up with.  So far my attempts to trigger the leak locally have failed.  I may try one of those network failure simulators to see if that can expose any leaks, or dig into `socket.io-client` to see if I can disrupt some of the internal messages.

**Comment by calzoneman** [comment]
My server seems to be leaking sockets now even with the client set to `transports: ["polling"]`.  So now I'm really confused.  I'm still trying to trigger it locally but I have been unable to do so.

**Comment by nuclearace** [comment]
Is this still a problem?

**Comment by calzoneman** [comment]
It seems to be fixed from my end.  If you look at the graph of open sockets on my server, there's a pretty clear point (the night that I upgraded socket.io to the latest version) where the fd count stabilizes and stops the cycle of increasing and crashing.

![fdcount_graph](https://cloud.githubusercontent.com/assets/385672/10327306/b55e0ab6-6c5a-11e5-962f-89993b8d185b.png)
