### ISSUE TITLE
When browser looses its internet connection ,socket disconnects . When browser again gets internet connection ,socket doesn't connect automatticly,need to refresh browser

### ISSUE THREAD

**Issue by mindfireon812** [socketio/socket.io#2032]

**Comment by KaustubhYK** [comment]
You need to set **reconnect** parameter to true while establishing socket connection.

**Comment by nkzawa** [comment]
How can I reproduce the issue?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
