### ISSUE TITLE
socket.io pass through cookies for sticky session on non-browser clients

### ISSUE THREAD

**Issue by adrai** [socketio/socket.io#2036]
A naive question:
It's possible to set a cookie (i.e the key for the sessionId) during handshake?
PS. I have a non-browser client and need to make it sticky in cloud foundry (gorouter)

**Comment by peteruithoven** [comment]
You could use a url parameter. This also works for non browser clients. We're using a url parameter in combination with HAProxy.

**Comment by adrai** [comment]
I know this works with HAProxy...
Do you know someone having positive experiences with urlParameter in combination with gorouter?



Il giorno 5-mar-2015, alle ore 17:28, Peter Uithoven <notifications@github.com<mailto:notifications@github.com>> ha scritto:


You could use a url parameter. This also works for non browser clients. We're using a url parameter in combination with HAProxy.

-

**Comment by adrai** [comment]
Isn't there an other approach to sticky the connection?

**Comment by adrai** [comment]
Is there a way to say to the node.js client he should take the sessionId cookie received by the server and resend it back in the next request?

**Comment by adrai** [comment]
Something like this could be really helpful: https://gist.github.com/adrai/246d635e8497b41384cf

**Comment by adrai** [comment]
What do you think? @peteruithoven @rauchg

**Comment by adrai** [comment]
@nkzawa the java client could do this too right?

**Comment by nkzawa** [comment]
@adrai yea, but it's because the situation is much simpler than JS client.

There are already a lot of arguments about this.
https://github.com/Automattic/socket.io-client/issues/344
https://github.com/Automattic/socket.io-client/issues/648

**Comment by adrai** [comment]
As I suggested in https://gist.github.com/adrai/246d635e8497b41384cf the xhr setHeader problem is solved. Should I do a pull request? @rauchg Do you have any feedback on my proposal?

@nkzawa Do you already have an example with your java-client library for doing this? Maybe with the help of this? https://github.com/nkzawa/socket.io-client.java/issues/28

**Comment by adrai** [comment]
Please give me some feedback for: https://github.com/adrai/socket.io-scaling https://github.com/Automattic/engine.io-client/pull/379

**Comment by adrai** [comment]
@nkzawa fyi: https://github.com/Automattic/engine.io-client/pull

**Comment by darrachequesne** [comment]
For future readers: you can use the `extraHeaders` option

```js
const socket = io({
  extraHeaders: {
    cookie: "1234"
  }
});
```

Please note that it will only work on Node.js / React native, and not in the browser.

Documentation: https://socket.io/docs/v3/client-initialization/#extraHeaders
