### ISSUE TITLE
socket.emit (client side) loses performance when the browser tab is unfocused

### ISSUE THREAD

**Issue by CreepyCereals** [socketio/socket.io#2037]

**Comment by nkzawa** [comment]
I think this is inevitable. Do you have any expected behaviors or workaround for this?

**Comment by CreepyCereals** [comment]
I've been working around with other WebSocket applications, and [ws](http://localhost/llamadax/) doesn't have this problem (maybe because doesn't use setTimeout()?). 
I'll fork this and see if I can fix this somehow but I'm afraid my js skills are limited :(

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
