### ISSUE TITLE
error Cannot use 'in' operator to search for 'issued' in undefined

### ISSUE THREAD

**Issue by nguyenvansutt** [socketio/socket.io#2038]
This is error: 
TypeError: Cannot use 'in' operator to search for 'issued' in undefined
    at Manager.garbageCollection (/usr/local/src/livechat/node_modules/socket.io/lib/manager.js:1023:21)
    at wrapper [as _onTimeout](timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout](timers.js:112:15)

It dont know when it raise. while using app, the app die, I check log and saw it.
my socket.io version: 0.9.16, mongodb 1.4.7, Iam using cluster and domain in nodejs

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
