### ISSUE TITLE
A Socket IO Client Demo

### ISSUE THREAD

**Issue by scaret** [socketio/socket.io#2041]
Hi,

I built a socket io web client here for my own debugging purpose. Hope anyone like it:

http://scaret.github.io/socket.io-client

It's enlightened by [MQTT Websocket Client](http://www.hivemq.com/demos/websocket-client/)

**Comment by peteruithoven** [comment]
Very nice. 
I also missed this and created something similar: https://github.com/Doodle3D/socket.io-debug-client/

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
