### ISSUE TITLE
website docs sending and recieving events code example improperly encoded

### ISSUE THREAD

**Issue by efx** [socketio/socket.io#2044]
In Firefox 36.0.1 on Linux the example code for http://socket.io/docs/#sending-and-receiving-events is showing up improperly encoded.
```
<code>// note, io.listen(&amp;lt;port&amp;gt;) will create a http server for you
var io = require(&amp;amp;#039;socket.io&amp;amp;#039;)(80);

io.on(&amp;amp;#039;connection&amp;amp;#039;, function (socket) {
  io.emit(&amp;amp;#039;this&amp;amp;#039;, { will: &amp;amp;#039;be received by everyone&amp;amp;#039;});

  socket.on(&amp;amp;#039;private message&amp;amp;#039;, function (from, msg) {
    console.log(&amp;amp;#039;I received a private message by &amp;amp;#039;, from, &amp;amp;#039; saying &amp;amp;#039;, msg);
  });

  socket.on(&amp;amp;#039;disconnect&amp;amp;#039;, function () {
    io.sockets.emit(&amp;amp;#039;user disconnected&amp;amp;#039;);
  });
});</code>
```
![encoding-woes](https://cloud.githubusercontent.com/assets/472721/6554722/2dd96a70-c635-11e4-9e7c-8ae2d0cb6155.png)

**Comment by paradite** [comment]
@efx are you still having this issue? Can't seem to replicate with Ubuntu/Firefox

**Comment by efx** [comment]
let me check later today and I'll close if it is not there.

**Comment by efx** [comment]
![socket-io](https://cloud.githubusercontent.com/assets/472721/12737451/9aa41cdc-c926-11e5-8f10-6e876bddd8c1.png)
Looks good on FF 40 something on Linux mint.
