### ISSUE TITLE
Where is wiki?

### ISSUE THREAD

**Issue by xylophone234** [socketio/socket.io#2046]
Where is wiki?
How do I get all sockets joined in a room?

**Comment by peteruithoven** [comment]
Please check if there aren't issues already opened before you start a new one. 
https://github.com/Automattic/socket.io/issues?q=wiki

**Comment by paradite** [comment]
you can see 
http://stackoverflow.com/questions/6563885/socket-io-how-do-i-get-a-list-of-connected-sockets-clients/24145381#24145381
and 
http://stackoverflow.com/a/24162850/1472186

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
