### ISSUE TITLE
Socket.io shouldn't use ws < 0.7 in any of its depedencies (recursively)

### ISSUE THREAD

**Issue by pjump** [socketio/socket.io#2049]
At least on Linux  with v0.10.25. ws throws nasty errors such as the following:
"
/home/pskocik/.node/lib/node_modules/instant-markdown-d/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:290
  if (mask != null && buf != null) bufferUtil.unmask(buf, mask);
"                                              ^

Socket.io still  depends on these old versions of ws via engine.io-client, which depends on engine.io 1.5.1, which brings dependencies on old ws's.. From my command line:

pskocik@ProBook:~/repos/socket.io (master *=) 
$ find . -name package.json -exec grep '"ws":' {}    \;
    "ws": "0.7.1",
    "ws": "0.4.x"
    "ws": "0.6.5",
pskocik@ProBook:~/repos/socket.io (master *=) 
$ find . -name package.json -exec grep '"ws":' {} -l   \;
./node_modules/engine.io/package.json
./node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/wscat/package.json
./node_modules/socket.io-client/node_modules/engine.io-client/package.json

**Comment by pjump** [comment]
This is actually identical to #1606 . Could we please get this fixed?

**Comment by nkzawa** [comment]
it has already been fixed, thanks.
