### ISSUE TITLE
opts.allowRequest can no longer be custom

### ISSUE THREAD

**Issue by tobalsgithub** [socketio/socket.io#2050]
Before commit 463d7a16a139981f1eead005b388f720be0989bd, it was possible to pass a custom allowRequest function to socket.io. That commit added the `checkRequest` function, and always set `opts.allowRequest = this.checkRequest.bind(this);`, thus overwriting the passed in value. 

https://github.com/Automattic/socket.io/blob/master/lib/index.js#L225

Seems like it should be `opts.allowRequest = opts.allowRequest || this.checkRequest.bind(this);`.

**Comment by TomKaltz** [comment]
+1

**Comment by mahasen** [comment]
:+1:

**Comment by kamote** [comment]
+1
