### ISSUE TITLE
Unix socket as param of listen() method

### ISSUE THREAD

**Issue by alexeevdv** [socketio/socket.io#2052]
net.Server in NodeJS can work with unix domain sockets https://nodejs.org/api/net.html#net_server_listen_path_callback but in socket.io we can use only port number https://github.com/Automattic/socket.io/blob/master/lib/index.js#L197

We need to add ability to pass unix socket into http.Server method or even pass listen param directly to http.Server
`var io = require('socket.io').listen("/var/run/unix.sock");`

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
