### ISSUE TITLE
Chatbot:limit the chat to the Human Bot usage

### ISSUE THREAD

**Issue by airport-transfers** [socketio/socket.io#2055]
How to limit this wonderful chat to make single users to chat only with the server that will answer trough the chatbot?

**Comment by FaizanZahid** [comment]
Yes this is exactly what I am looking for, have you found it?

I want my real human users to connect with the system bot so that the bot entertains them if the other users r not online.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
