### ISSUE TITLE
Usage XHR vs JSONP docs?

### ISSUE THREAD

**Issue by peteruithoven** [socketio/socket.io#2058]
I can't find information on when JSONP is used and when XHR is used.
I checked the readme's from:
- this repository
- engine.io-protocol
- engine.io
- engine.io-client

I think I understand one of these is used when a client is in "polling" mode, but there is little information on why one of these would be selected. 
I understand I can force JSONP using the `forceJSONP` option and I could disable it by setting `jsonp` to false.

**Comment by davidhxy678** [comment]
I want to know

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
