### ISSUE TITLE
Slow binary transfers compared to pure 'ws'

### ISSUE THREAD

**Issue by matthiasg** [socketio/socket.io#2060]
Running the test program as defined here: https://code.google.com/p/chromium/issues/detail?id=441885

I could only get about **388 Mbps** on my machine. When using ws directly in the example with line 83 altered to use perMessageDeflate:false

```
var wsServer = new ws.Server({server: server, perMessageDeflate: false});
```

i get consistently more than **1100 Mbps**.

I tried passing the **perMessageDeflate** parameter to the server and client in the SocketIO part but it did seem to have any effect. 

Anybody any tips ?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
