### ISSUE TITLE
API docs of flags (broadcast, volatile)

### ISSUE THREAD

**Issue by nkzawa** [socketio/socket.io#2061]
There is no doc on the socket.io website and README.
Required for both `Socket` class and `Namespace` class.

**Comment by peteruithoven** [comment]
Also see: https://github.com/Automattic/socket.io/issues/2020

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
