### ISSUE TITLE
Memory leak if clients never accept messages

### ISSUE THREAD

**Issue by alexcroox** [socketio/socket.io#2064]
We've been using a load balancing desktop tool in the office that can establish a connection with socket.io and send a message, but after 50 concurrent connections the app runs out of memory and is killed by the server. I have my suspicions that because the desktop app isn't sending an acknowledgement of the message, socket.io is queuing them up in memory and it quickly falls over (30 seconds or so).

Would this be the case? How can I mitigate these "bad" websocket connections?

**Comment by peteruithoven** [comment]
What do you mean with "acknowledgement of the message"? 
If you mean they don't call the acknowledgement callback, I don't think that shouldn't be a issue. 
Socket.io just keepw [a list of callbacks](https://github.com/Automattic/socket.io-client/blob/master/lib/socket.js#L144) it expects using id's and a reference to the actual callback function. When it receives a acknowledgment message it will [look up the id and call the appropriate callback function](https://github.com/Automattic/socket.io-client/blob/master/lib/socket.js#L300). 

As usual, try to replicate this in a very basic example.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
