### ISSUE TITLE
Closing the server does not clear polling timers

### ISSUE THREAD

**Issue by ChiperSoft** [socketio/socket.io#2069]
If a socket is in the process of upgrading when io.close is called, the server won't exit cleanly until the polling connection pings out.

Here's a test case:

```js

var http       = require('http');
var Server     = require('socket.io');
var Client     = require('socket.io-client');

var server = http.createServer();

var io = Server(server);

io.on('connection', function (socket) {
	console.log('server connection');

	socket.on('disconnect', function () {
		console.log('server disconnected');
		socket.disconnect();
	});
});

server.listen(8080, function () {
	var socket = Client('http://localhost:8080/');
	socket.on('connect', function () {
		console.log('client connected');
		
		console.log('closing');
		io.close();
	});

	socket.on('disconnect', function () {
		console.log('client disconnected');
		socket.close();
	});
});

server.on('close', function () {
	console.log('shutdown');
});
```

The server will output "shutdown", but the process will not exit until the socket times out two minutes later (if debug is setup to show socket.io, you can see the timeout event).  If I delay the close 5 seconds to allow the socket to upgrade, then the process exits cleanly.

The only workaround I can come up with is to force process exit in the server close event. Unfortunately, the reason I made this test case was that my main application never fires the close event.  I can't seem to reproduce that in a test case, but I suspect it might be related to this issue.

**Comment by rauchg** [comment]
+1

**Comment by Dignifiedquire** [comment]
Any updates on this? This is creating a real problem in karma right now, as the the timers stop the process from exiting cleanly at the end. See https://github.com/karma-runner/karma/issues/1788 for details

**Comment by oniono** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

oniono@naver.com 님께 보내신 메일 <Re: [socket.io] Closing the server does not clear polling timers (#2069)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by Dignifiedquire** [comment]
@oniono please stop, otherwise I'll have to report your account for abuse

**Comment by nkzawa** [comment]
:+1: I think it should be fixed asap

**Comment by rauchg** [comment]
+1

**Comment by onlywei** [comment]
+1

**Comment by mightyguava** [comment]
+1

**Comment by maaravi** [comment]
+1

**Comment by marcusmolchany** [comment]
+1

**Comment by ChiperSoft** [comment]
While I'm thankful for the sudden amount of attention this issue is getting, please don't fill up the comments with +1s. All that does is annoy project maintainers.  Explanations of why this bug affects you are much more effective.

**Comment by rauchg** [comment]
We've merged a solution for this and it will shortly be in a release.
