### ISSUE TITLE
doc suggestion: do not use express app.listen() with socket.io

### ISSUE THREAD

**Issue by jldec** [socketio/socket.io#2075]
I ran into this in the process of adding socket.io to an existing express(4) app because i didn't switch the code from `app.listen()` to `server.listen()`.

The symptom is refusal by the server to serve the client library or connect any sockets.

According to http://expressjs.com/4x/api.html#app.listen , "This method is identical to node's http.Server.listen()" - but in reality it creates a new http server leaving the one with socket.io non-operational.

Hopefully this issue will help others to avoid the same trap.

**Comment by asnyder** [comment]
Could you please provide a full example? Been dealing with these changes due to new express, and it's not obvious to me what the "server" would be in this case, especially when trying to pass in custom "use" settings. Thanks.

**Comment by jldec** [comment]
Our original project used regular express boilerplate:
```javascript
var express = require('express');
var app = express();

// ... other code

app.listen(port);
```

the socket.io documentation [here](http://socket.io/docs/#using-with-express-3/4) says
```javascript
var app = require('express')();
var server = require('http').Server(app);
var io = require('socket.io')(server);

server.listen(80);
```

so i fixed the first part of the code in our project, but i didn't change `app.listen()` to `server.listen()` because i thought they were the same, and things kindof worked except socket.io didn't run...

**Comment by TifPun** [comment]
+1

**Comment by jakesee** [comment]
For folks passing by looking for answer to you CORS issue, express.listen() causes "No 'Access-Control-Allow-Origin' header is present on the requested resource." CORSs error, whereas http.listen() does not.

**Comment by darrachequesne** [comment]
This is indeed a common trap... A note was added here: https://socket.io/docs/v3/server-initialization/#With-Express

**Comment by sharafath-ali** [comment]
is there any limitations if we use server created from 

const expressServer = app.listen(4000)

to implement socket.io  server

const io = new Server(expressServer,{    
    cors: [
        'http://localhost:4000'
    ]
})
