### ISSUE TITLE
doc issue: linking to socket.io/docs with #fragment-id pollutes browser history stack (firefox)

### ISSUE THREAD

**Issue by jldec** [socketio/socket.io#2076]
in issue #2075 i linked to the doc using url `http://socket.io/docs/#using-with-express-3/4`
for some reason (i think it may be the slack polling) after clicking on that [link](http://socket.io/docs/#using-with-express-3/4), my firefox history is polluted with alternating calls to
`http://socket.io/docs/##using-with-express-3/4` and  
`http://socket.io/docs/#using-with-express-3/4`  
image below:
![screen shot 2015-04-08 at 09 03 22](https://cloud.githubusercontent.com/assets/849592/7045766/f18f41f0-ddce-11e4-9780-aa080f80f07e.png)

**Comment by nkzawa** [comment]
:+1: 

![socket io-doc](https://cloud.githubusercontent.com/assets/775227/7218745/592c8ac8-e6b9-11e4-9e6d-487d4c18eb7b.gif)

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
