### ISSUE TITLE
send message from php server to nodejs socket.io and node send message top client.?

### ISSUE THREAD

**Issue by cmideal** [socketio/socket.io#2077]
#### send message from node socket.io to server

and php server send message to socket.io and node send message to client .

I dont know this is possiable in socket.io

**Comment by nkzawa** [comment]
see https://github.com/rase-/socket.io-php-emitter

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
