### ISSUE TITLE
Cordova Tutorial Missing Connect Statement

### ISSUE THREAD

**Issue by ilevin350** [socketio/socket.io#2078]
There appears to be an omission in the Cordova tutorial.  The tutorial can be found on the socket.io website under Docs / FAQ.  The missing line is the connect statement:

**var socket = io.connect('http://192.168.0.10:3000');**

Where the IP address is the IP address of the machine hosting the socket.io server.

The whole script tag in the index.html file should look like this.

```
<script type="text/javascript">
  app.initialize();

  document.addEventListener('deviceready', function() {
    var socket = io.connect('http://192.168.0.10:3000');
      socket.on('connect', function() {
        socket.on('chat', function(text) {
        alert(text);
      });
    });
  });
</script>
```

It took me quite a while to figure this one out, so adding it to the tutorial would likely help some people out.

**Comment by venca163** [comment]
+1
(quick link: http://socket.io/socket-io-with-apache-cordova/ )

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
