### ISSUE TITLE
this.sockets.indexOf is O(n) ? is there a reason to not use a hash array instead ?

### ISSUE THREAD

**Issue by kapouer** [socketio/socket.io#2079]
Hi,
when trying to figure out why latest socket.io has CPU load climbing a bit too fast (70% on one core with around 5.000 clients), this was found:
https://github.com/Automattic/socket.io/blob/916872587fd6e0280e9538f712b91d0460bc3a2b/lib/namespace.js#L191
before i try to see if that can be optimized, i'd welcome some advice from the author(s), please.

**Comment by nkzawa** [comment]
I think there is no big reasons for this.

**Comment by kapouer** [comment]
What do you think @manubb ? Feel like doing it ?

**Comment by manubb** [comment]
I'll have a look at it.

**Comment by manubb** [comment]
Hi. I have patched socket.io and socket.io-adapter:
https://github.com/manubb/socket.io/tree/1.3.5-efficient
https://github.com/manubb/socket.io-adapter/tree/0.3.1-efficient

To my understanding, a namespace or a room can have many sockets (10000s) connected to but a Client only have a few sockets (a socket for each namespace it is connected to). Am i right?

**Comment by kapouer** [comment]
ping @nkzawa

**Comment by nkzawa** [comment]
> To my understanding, a namespace or a room can have many sockets (10000s) connected to but a Client only have a few sockets (a socket for each namespace it is connected to). Am i right?

In most cases, this should be correct.

The modifications look almost good to me. Thanks for your effort :smile:

**Comment by manubb** [comment]
I have done your suggested corrections. I did two pull requests, one for socket.io and one for socket.io-adapter. Version number of socket.io-adapter should be updated in both socket.io and socket.io-adapter.

**Comment by kapouer** [comment]
For reference:
https://github.com/Automattic/socket.io/pull/2123
https://github.com/Automattic/socket.io-adapter/pull/29

**Comment by nkzawa** [comment]
Should be fixed now, thanks.
