### ISSUE TITLE
socket.io/socket.io.js is pending too long time.

### ISSUE THREAD

**Issue by ognb** [socketio/socket.io#2084]
![untitled2](https://cloud.githubusercontent.com/assets/4508233/7176190/b6b23f16-e44e-11e4-829e-147d6dbd1b21.png)

**Comment by oganbat** [comment]
sometimes cant include socket.io.js

**Comment by nkzawa** [comment]
How can we reproduce this?

**Comment by oganbat** [comment]
![untitled333](https://cloud.githubusercontent.com/assets/4508233/7223257/008c2d54-e751-11e4-9ebd-726f4590c7e5.png)

**Comment by oganbat** [comment]
server is running while can not include socket.io.js

**Comment by nkzawa** [comment]
I couldn't reproduce this. Can you post your code to somewhere?

**Comment by oganbat** [comment]
var fs = require('fs'),
	options = {
		secureProtocol: 'SSLv23_method',
		secureOptions: require('constants').SSL_OP_NO_SSLv3,
		ca: fs.readFileSync('**********'),
		key: fs.readFileSync('**********'),
		cert: fs.readFileSync('**********'),
		passphrase: '**********'
	},
	app = require('https').createServer(options);
io = require('socket.io').listen(app,{log:false});
app.listen(8001);
var web = require('./module/socket_io_server');
web.io =io;

**Comment by nkzawa** [comment]
Is SSL required to reproduce the issue? Can you simplify the code and remove `require('./module/socket_io_server')` so that I can test it? Thank you for your help.

**Comment by oganbat** [comment]
app = require('https').createServer(options);
io = require('socket.io').listen(app,{log:false});
app.listen(8001);

io.set('transports', ['websocket', 
  'flashsocket', 
  'htmlfile', 
  'xhr-polling', 
  'jsonp-polling', 
  'polling']
);

io.use(function(socket, next)  {
	var handshakeData = socket.request,
		cookie =parseCookies(handshakeData);
	if(!socket.handshake.query || !handshakeData.headers || !handshakeData.headers.cookie)  {
		next(new Error('-Error code:1')); //cookie transmitted
		console.log('cookie transmitted');
		return false;
	}
	if(handshakeData.headers.cookie.search('PHPSESSID') < 0)  {
		next(new Error('-Error code:2'));  //No session id transmitted.
		console.log('No session id transmitted.');
		return false;
	}
	console.log(socket.handshake.query);
	console.log(socket.handshake.query.myHID + " " + socket.handshake.query.comId + " " +cookie['PHPSESSID']);
	if(parseInt(socket.handshake.query.myHID) < 0 && parseInt(socket.handshake.query.comId) > 0 && socket.handshake.query.myHID =='undefined' && socket.handshake.query.comId =='undefined')  {
		next(new Error('-Error code:3'));  //No user id or com id transmitted.
		console.log('No user id or com id transmitted.');
		return false;
	}
	var userId =parseInt(socket.handshake.query.myHID),
		loginId =cookie['PHPSESSID'];
	if(loginId =='' || loginId ==undefined || userId ==undefined)  {
		next(new Error('-Error code:4'));  // No cookie values transmitted
		console.log('No cookie values transmitted');
		return false;
	}

	mysql.query('use cloud');
	qry = "SELECT * FROM `_online_user_i` "+
		  "WHERE `user_id`="+ mysql.escape(userId) +
		  " AND (`login_id`="+ mysql.escape(loginId) +" OR `insight`="+ mysql.escape(loginId) +" OR `mobile`="+ mysql.escape(loginId)+")";
	
	mysql.query(qry, function(err, result, fields)  {
		if(err)  {
			next(new Error('-Error code:5'));  //Query error on loginId checking.
			console.log('Query error on loginId checking.');
			console.log(err);
			return false;
		}
		else  {
			try  {
				if(result.length == 0)  {
					next(new Error('-Error code:6')); // Result is 0 transmitted.
					console.log('Result is 0 transmitted.');
					return false;
				}
				else if(result.length > 1)  {
					next(new Error('-Error code:7'));  // Result is too many transmitted.
					console.log('Result is too many transmitted.');
					return false;
				}
				else  {
					socket.request.loginId =loginId;
					socket.request.result =result[0];
					next();
					console.log('Accept userId:' + result[0].user_id +' time:'+ (new Date).toString());
				}
			}
			catch (e)  {
				next(new Error('-Error code:8'));  // - Syntax error
				console.log('Syntax error.');
				return false;
			}
		}
	});		
});

io.on('connection', function (socket)  {
	console.log("\nsockets length:"+ io.sockets.clients().length);
	console.log("\n");
	var cookie = parseCookies(socket.handshake),
		userId =parseInt(socket.handshake.query.myHID),
		comId =parseInt(socket.handshake.query.comId),
		type =socket.handshake.query.type,
		loginId =cookie['PHPSESSID'];
	console.log("new user login. "+ (new Date).toString()+"\nmyHID:"+ userId +"; comId:"+ comId +"; " +loginId);
	try  {
		console.log("\n");
		socket.loginId =loginId;
		socket.userId =userId;
		socket.comId =comId;
		socket.type =type;

		
		var comRow =getRegisteredCom(socket.comId,socket);


		var sockets =io.sockets.clients(socket.userId);
		
		if(emitTimeouts[socket.userId])  clearTimeout(emitTimeouts[socket.userId]);
		else  {
			qry = "SELECT `id`,`system_name`,`app_name`,`com_id`,`position`,"+
				" (SELECT `status` FROM `_user_status_i` WHERE `user_id`="+ mysql.escape(socket.userId) +" AND `is_active`=1) `status`,"+
				" (SELECT `user_icon` FROM `_user_i` WHERE `user_id`="+ mysql.escape(socket.userId) +") `user_icon`"+
				" FROM `_able_human_i` WHERE `id` = "+ mysql.escape(socket.userId);
			mysql.query('use `cloud`');
			mysql.query(qry, function(err, result, fields)  {
				if(err)  console.log(err);
				else  {
					try  {
						console.log(" result " + result.length);
						if(result.length > 0)  {
							io.sockets.in('com'+ socket.comId).emit('addNewUser', result[0]);
							emitToRecent(socket.userId, result[0], 'addNewUser');
							console.log("\t\t\tconnect emit to other users."+ socket.userId);
						}
					}
					catch (e)  {
						console.log("socket_io_server - addClientList: " + e);
					};
				};
			});
		}
		emitTimeouts[socket.userId] =null;

		socket.join('com'+ socket.comId);
		socket.join(socket.userId);

		// ?????? ??????????? ???????
		if(socket.type =='desktop')  {
			console.log("\t\tDesktop connected "+ socket.userId);
			socket.isDesktop =true;
			if(desktopUsers[socket.userId])  {
				desktopUsers[socket.userId].emit('logout');
			}
			desktopUsers[socket.userId] = socket;
		}
		else if(socket.type =='mobile')  {
			console.log("\t\tmobile connected "+ socket.userId);
			socket.isMobile =true;
			if(mobileUsers[socket.userId])  mobileUsers[socket.userId].emit('logout');
			mobileUsers[socket.userId] = socket;
		}
		else  {
			if(sqlTimeouts[socket.userId])  clearTimeout(sqlTimeouts[socket.userId]);
			sqlTimeouts[socket.userId] =null;
			console.log("\t\tweb connected "+ socket.userId +". now socket length: "+ sockets.length);
			for(var i =0; i< sockets.length; i++)  {
				console.log("\t\t"+sockets[i].loginId  + " = "  + socket.loginId);
				if(sockets[i].isDesktop)  continue;
				if(sockets[i].isMobile)  continue;
				if(sockets[i].loginId != socket.loginId)  {
					sockets[i].emit('logout');
					sockets[i].disconnect();
				};
			};
		};
		console.log("\t\t"+ socket.userId +" is connected, has "+ (sockets.length + 1) +" connection.");
	}
	catch(e)  {
		console.log((new Date).toString() +' - register user error:');
		console.log(e);
	}
});

**Comment by nkzawa** [comment]
@oganbat Please minimize your code. And it looks your socket.io configurations are for socket.io v0.9, see http://socket.io/docs/ for the latest doc.

**Comment by oganbat** [comment]
app = require('https').createServer(options);
io = require('socket.io').listen(app,{log:false});
app.listen(8001);

io.set('transports', ['websocket', 
  'flashsocket', 
  'htmlfile', 
  'xhr-polling', 
  'jsonp-polling', 
  'polling']
);

io.use(function(socket, next)  {
	var handshakeData = socket.request,
		cookie =parseCookies(handshakeData);
	if(!socket.handshake.query || !handshakeData.headers || !handshakeData.headers.cookie)  {
		next(new Error('-Error code:1')); //cookie transmitted
		console.log('cookie transmitted');
		return false;
	}
	if(handshakeData.headers.cookie.search('PHPSESSID') < 0)  {
		next(new Error('-Error code:2'));  //No session id transmitted.
		console.log('No session id transmitted.');
		return false;
	}	
	socket.request.loginId =loginId;
	next();
			
});

io.on('connection', function (socket)  {
	console.log("\nsockets length:"+ io.sockets.clients().length);
	console.log("\n");;
	try  {
		console.log("connection is here");
	}
	catch(e)  {
		console.log((new Date).toString() +' - register user error:');
		console.log(e);
	}
});

**Comment by nkzawa** [comment]
@oganbat I tried to reproduce the issue again using your code but couldn't. Maybe it's the problem of your environment rather than socket.io?

**Comment by oganbat** [comment]
@nkzawa  I'm using on ubuntu server. How many connection able to create on socket.io. Is there any limit?

**Comment by nkzawa** [comment]
There is no specific limit. It depends on your environment.

**Comment by oganbat** [comment]
var fs = require('fs'),
	express = require('express'),
	options = {
		secureProtocol: 'SSLv23_method',
		secureOptions: require('constants').SSL_OP_NO_SSLv3,
		ca: fs.readFileSync('path'),
		key: fs.readFileSync('path'),
		cert: fs.readFileSync('path'),
		passphrase: 'pssword'
	},
	app = express();
server = require('https').Server(options, app);
io = require('socket.io').listen(server);

server.listen(8050);

app.get('/', function (req, res) {
	res.send("server..");
});
io.sockets.on('connection', function (socket)  {
	console.log("\ncalled connection 8050.");
	socket.on('register', function (type)  {
		try  {
			console.log(type +" is connected "+ (new Date).toString() +"\n");
		}
		catch(e)  {
			console.log((new Date).toString() +' - register user error:');
			console.log(e);
		}
	});
	socket.on('send', function (obj)  {
		try  {
			if(socket.type !='able')  return;
			io.sockets.in('client').emit('receive', obj);
		}
		catch(e)  {
			console.log((new Date).toString() +' - register user error:');
			console.log(e);
		}
	});
	socket.on('disconnect', function()  {
		try  {
			var type =socket.type;
			console.log('call disconnect '+ type);
			socket.leave(type);
		}
		catch(e)  {
			console.log('disconnect user error:');
			console.log(e);
		}
	});
});

**Comment by oganbat** [comment]
I dont know what is problem. It is running but sometimes can not include https://host:port/socket.io/socket.io.js

**Comment by nkzawa** [comment]
Closed since we couldn't reproduce the issue. Feel free to reopen when you could have more information.

**Comment by dev-mraj** [comment]
i am getting same issue, sometimes chrome network tab.

i see sid related message came late, even after coming that handshake connect event fire very late.
and sometimes don't even get that sid message and i see only (OPcode -1) in chrome dev tab.

**Comment by darrachequesne** [comment]
@dev-mraj could you please open a new issue with full details, your setup, a way to reproduce?
