### ISSUE TITLE
TransportError

### ISSUE THREAD

**Issue by xZGit** [socketio/socket.io#2089]
Error: parser decode error {type: "TransportError", description: Error: Invalid UTF-8 detected, stack: (...), message: "parser decode error"}
description: Error: Invalid UTF-8 detected
data: "42["user joined",{"user":{"name":"你好 你去哪儿"},"numUsers":2}]"
message: "Invalid UTF-8 detected"
stack: (...)
get stack: function () { [native code] }
set stack: function () { [native code] }
proto: d
message: "parser decode error"
stack: (...)
get stack: function () { [native code] }
set stack: function () { [native code] }
type: "TransportError"
proto: d

As about , when i use socket.io , I always get this error at engine.io version 1.5.1 , but if I use version 1.3.1 ，it works. what is the matter?

**Comment by nkzawa** [comment]
Maybe you use different versions of socket.io on server and client? If so, please try a same one.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
