### ISSUE TITLE
Can not  check socket is connected or not when using socket.io-redis adapter and NginX

### ISSUE THREAD

**Issue by nguyenvansutt** [socketio/socket.io#2090]
I am using socket.io with multiple process (multiple server), socket.io-redis and nginx. I follow this guide: http://socket.io/docs/using-multiple-nodes/

I am trying to do: At a function (server side), I want to query by socketid that this socket is connected or disconnect
I tried io.of('namespace').connected[socketid], it only work for current process.  it mean, if this socket is connected at another process, So I can not check it

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
