### ISSUE TITLE
Get a socket reference in different namespace

### ISSUE THREAD

**Issue by slier81** [socketio/socket.io#2094]
How can i get socket reference in different namespace?
Below code show how it can be done in socket.io v0.9

```
var chatInfra = io.of("/chat_infra").on( 'connection', function( socket ) {
    var comSocket = chatCom.sockets[socket.id]; //<-- this work in socket.io v0.9
    comSocket.join(room.name);
});


var chatCom = io.of("/chat_com").on( 'connection', function( socket ) {
 //code
});
```

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
