### ISSUE TITLE
SecurityError

### ISSUE THREAD

**Issue by chatis** [socketio/socket.io#2096]
After a while, my client side send a SecurityError and it's impossible to connect again to the server... I really don't know how to handler the error or having more information about this problem... 

Is someone has ever had this problem one time ? This is ver annoying

**Comment by chatis** [comment]
I see this is only in windows 8 now... I try to close socket with 

window.onbeforeunload = function()
    {
      socket.emit("disconnect");
	  socket.close(); 
    };

This is working for other version.. but not for windows 8... Do you have any idea ?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
