### ISSUE TITLE
websocket always pending

### ISSUE THREAD

**Issue by chatis** [socketio/socket.io#2097]
the socket.io with protocol websocket is always pending.... this is normal or not ?

Thank you

![capture d ecran 2015-04-26 a 14 48 58](https://cloud.githubusercontent.com/assets/4694026/7337243/6632010c-ec23-11e4-9653-70411b3d024c.png)

**Comment by MDXDave** [comment]
no, it should be "101 Switching Protocols"

**Comment by chatis** [comment]
This is 101 Switching protocols.. but in  Time - Latency, this is writting Pending

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Comment by liudonghua123** [comment]
In my project, the pending status is ok, but non pending status (through a nginx reverse proxy) is problem.
