### ISSUE TITLE
socket-to-socket chat, done!

### ISSUE THREAD

**Issue by xzh-loop** [socketio/socket.io#2099]
Actually, this is not a question. I just want to share my feelings now.
In the beginning, I try `io.sockets.socket(socketid).emit()` and many other codes,

Finally, I found every socket has a [default room](http://socket.io/docs/rooms-and-namespaces/#default-room)
>Each Socket in Socket.IO is identified by a random, unguessable, unique identifier Socket#id. For your convenience, each socket automatically joins a room identified by this id.
This makes it easy to broadcast messages to other sockets:
```javascript
io.on('connection', function(socket){
  socket.on('say to someone', function(id, msg){
    socket.broadcast.to(id).emit('my message', msg);
  });
});

As the socket.id could not be overrided, I stored them with a global object. Like this: `var all = {}`

And then use `all[username] = socket.id;` to store them on `connection` event. So I change the code above:
```javascript
io.on('connection', function(socket){
  socket.on('say to someone', function(id, msg){
    socket.broadcast.to(all[username]).emit('my message', msg);  // id changed
  });
});
```
To be honest, it took a long time for me to solve it.

**Comment by peteruithoven** [comment]
Where is `username` defined in your example?

**Comment by xzh-loop** [comment]
@peteruithoven I did not provide it. But you can define it by yourself. You should know whom you're talking with in the code. Right?

**Comment by aHumanBeing** [comment]
@xzh-loop Thanks.

**Comment by nkzawa** [comment]
@xzh-loop :+1:
