### ISSUE TITLE
Error without Retry

### ISSUE THREAD

**Issue by rossimo** [socketio/socket.io#2100]
I'm currently testing failure recovery for a Node.js app. I've encountered an error that the Javascript Socket.io client isn't recovering from. 

```
WebSocket connection to 'wss://myhost/socket.io/?EIO=3&transport=websocket&sid=7HdN4oe1dTNjjk6PAAAA' failed: Invalid frame header
```

The test case is restarting all my Node.js processes, and watching to see if the websocket reconnects. In most cases, the Socket.io client fully recovers, but when this error appears, all retries stop. Is this a Socket.io error I can listen for, or is this a browser error I'll have to add a new hook for?

I'm using Chrome 42.0.2311.90.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
