### ISSUE TITLE
Emit to an array of rooms

### ISSUE THREAD

**Issue by derikb** [socketio/socket.io#2106]
It would be great if I could pass an array as an argument to .to()/.in() when emitting to rooms.

Right now if I have a variable number of rooms I want to send the same data to, I have to either:
- Emit to each room separately (which seems inefficient if we have the same sockets in some of those rooms)
- ... Build a string of .to(room).to(room) and use eval, which seems like an awful idea but the only other thing I can think of.

**Comment by jordanpappas** [comment]
Sounds like a decent enough request, but would it really be too inefficient to write your own simple broadcast loop?

```javascript
function broadcastTo(rooms, msg) {
  var len = rooms.length;
  for (var i = 0; i < len; i++) {
    socket.broadcast.to(rooms[i]).emit(msg);
  }
}
```

simple example, but this should be fine if you don't have a ton of rooms. Even then, it may be fast enough. Hope this helps

**Comment by derikb** [comment]
By doing it that way (looping over the rooms), if a socket is in more than 1 of the rooms it would get sebt the same message multiple times in a row.

**Comment by dsalcedo** [comment]
Please close this question listed as 'issue'. For questions please use stackoverflow.
Code strong.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
