### ISSUE TITLE
How can I debug/test my socket.io server?

### ISSUE THREAD

**Issue by smuellerus** [socketio/socket.io#2110]
I am looking for a chrome extension, something like Simple WebSocket Client, but for socket.io. I would like to connect to my socket.io server and to send and receive any messages.

**Comment by peteruithoven** [comment]
Maybe you can use one of these:
https://github.com/Automattic/socket.io/issues/2041
https://github.com/Automattic/socket.io/issues/2014

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Comment by amritb** [comment]
http://amritb.github.io/socketio-client-tool/

**Comment by tahsinature** [comment]
> Try [Firecamp](https://chrome.google.com/webstore/detail/firecamp/eajaahbjpnhghjcdaclbkeamlkepinbl)
> 
> ![image](https://user-images.githubusercontent.com/5078921/51088490-60e22280-1786-11e9-83a3-d99807571385.png)

the best tool for socket.io. looking forward...
