### ISSUE TITLE
Going from single mysql-queries to mysql-pool

### ISSUE THREAD

**Issue by AlexioVay** [socketio/socket.io#2113]
I'm trying to switch from single mysql-queries to mysql-pool connection using the node-mysql-module, so users can share one mysql-connection, but I'm not familiar with this at all (also new to nodejs/socket.io).

The following code is what I've tried so far to send data every second to the socket in an array:
http://pastebin.com/dRFzWtEH

But this doesn't send me any data to the WebSocket. Is this approach (code-structure) even correct? 

Previously I used query.on('results') to get data like this:

var selection = "SELECT \* FROM auctions";  
var query = mysql.query(selection), auctions = []; 
query.on('result', function(auction) {
console.log ('id: '+auction.id+' ('+auction.duration+') ');
});

This worked fine showing data with auction.row but how to do this in my mysql pool connection?

Also after some seconds I'm getting an error that release() isn't even defined, but it's listed in the mysql-module documentation. I think my whole logical process is somehow incorrect?
- Should I use connection.end() and .release() at all? Because the
  connection should never end.
- Should I still use setInterval(function () { mysql.query('SELECT 1'); }, 5000); as answered in another StackOverflow question to keep the connection alive here? (nodejs mysql Error: Connection lost The server closed the connection)

(Appreciate any tips or answers to even some of my questions! Better some answers than none, because I experienced that this topic isn't answered much at all.)

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
