### ISSUE TITLE
Better example?

### ISSUE THREAD

**Issue by Xeoncross** [socketio/socket.io#2115]
I was looking at the [chat example](https://github.com/Automattic/socket.io/blob/master/examples%2Fchat%2Findex.js) and it seemed like there where a lot of missing parts if someone actually wanted to use this on a server. I understand that is just a simple demo - but most people need to cover a real-life chat demo more than the most basic chat demo.

Can we expand this?
### Missing features
- No checking to see if the username is already taken
- No support for rooms (or namespaces)
- No checking on message to see if the user has actually given a name yet
- No use of showing get()/set() for session data (just socket.username = ...)
- No rate-limiting
- etc...

**Comment by thelordgabo** [comment]
Agree with that better examples please

**Comment by dsalcedo** [comment]
Please close this question listed as 'issue'. For questions please use stackoverflow.
Code strong.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
