### ISSUE TITLE
Chrome Data Saver will not connect to socket

### ISSUE THREAD

**Issue by lukepolo** [socketio/socket.io#2116]
I was testing out my new site with my mobile phone while noticing it wasn't getting all the auto updates like the rest of my devices. Pluggged up my phone into my laptop enabled debugging, and everything seems ok excpet it would not fire the connect.  

Finally going through the Android Chrome browser there is a setting called "Data savings", once I disabled it would connect. 

Any ideas how to look for this and notify the user ? Or am I just SOL?

**Comment by fermmm** [comment]
Man thanks for reporting this, I was hitting my head against a wall with this problem. The solution seems to be setting SSL in your page, "data savings" seems to be disabled in SSL websites.

**Comment by Haeresis** [comment]
Same problem, all work fine except on Chrome Android only when Data Saver is activated

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
