### ISSUE TITLE
Callback not invoked for socket.join(room,callback) if room already exists in socket.rooms

### ISSUE THREAD

**Issue by rishabhgrg** [socketio/socket.io#2117]
The callback passed to `socket.join(room, callback)` is never invoked if the `room` is already present in `socket.rooms`.
I think the culprit is this `if` [here](https://github.com/Automattic/socket.io/blob/master/lib/socket.js#L226) in `lib/socket.js` which returns without invoking the callback `fn` if it finds `room` in `socket.rooms`.

``` javascript
Socket.prototype.join = function(room, fn){
  //...
  if (~this.rooms.indexOf(room)) return this;
  this.adapter.add(this.id, room, function(err){
    if (err) return fn && fn(err);
    //...
    self.rooms.push(room);
    fn && fn(null);
  });
};
```

Maybe moving it inside the adapter function similar to `Socket.prototype.leave` can be a solution: 

``` javascript
Socket.prototype.join = function(room, fn){
  //.... 
  this.adapter.add(this.id, room, function(err){
    if (err) return fn && fn(err);
    //...
    if (!~this.rooms.indexOf(room)) {
       self.rooms.push(room);
    };
    fn && fn(null);
  });
};
```

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
