### ISSUE TITLE
When user disconnected, TCP link still alive?

### ISSUE THREAD

**Issue by hisune** [socketio/socket.io#2118]
My chat APP only 5 people online, but my server  has 550 TCP link.

>#ss -o state established|grep :3000| wc -l
>550

Why is it so? And what can I do?
Thx everyone.

**Comment by dbackowski** [comment]
See #1910

**Comment by nkzawa** [comment]
Should be fixed in v1.4.x.

**Comment by ricky65** [comment]
This issue with TCP connections not closing is still happening in v1.7.2. Can somebody look into it please.
