### ISSUE TITLE
IE problems

### ISSUE THREAD

**Issue by avenger86** [socketio/socket.io#2126]
It is dont connect to socket.io server that hosted on different domain
![q2kjolriona4mj](https://cloud.githubusercontent.com/assets/701051/7708468/91097e8a-fe5e-11e4-94bd-f93f5c79b983.jpg)
![l213oxktjeqwrx](https://cloud.githubusercontent.com/assets/701051/7708467/9108cbde-fe5e-11e4-9892-d48bcc7458ce.jpg)

all cross origin headers is ok

on server log is:
 socket.io:client client close with reason transport close +2m
  socket.io:server incoming connection with id uph1_EbrJ2A1LxlqAAAF +519ms
  socket.io:client connecting to namespace / +0ms
  socket.io:namespace adding socket to nsp / +0ms
  socket.io:client writing packet {"type":4,"nsp":"/"} +1ms
  socket.io-parser encoding packet {"type":4,"nsp":"/"} +1.6m
  socket.io-parser encoded {"type":4,"nsp":"/"} as 4 +0ms

**Comment by dsalcedo** [comment]
client side and server side socket.io code ?

**Comment by dsalcedo** [comment]
Please close this question listed as 'issue'. For questions please use stackoverflow.
Code strong.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
