### ISSUE TITLE
Socket.io 1.3.5 protocol and Jmeter benchmarking

### ISSUE THREAD

**Issue by laukamp** [socketio/socket.io#2127]
I'm trying to benchmark socket.io 1.3.5 with Jmeter and the following websocket plugin (https://github.com/maciejzaleski/JMeter-WebSocketSampler).

When implementing the socket.io protocol in Jmeter to emulate the same connection steps I see in google dev tools I'm having a 20s delay between some frames. Please, can you give me some advice to get this working properly and remove this delay? Thank you!!
##### Jmeter
1. HTTP REQUEST [GET] socket.io/?EIO=3&transport=polling&t=${timestamp} HTTP
   Server Response:   ÿ0{"sid":"ZqjRE1Sjl5_d5lspAAAD","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}
2. HTTP REQUEST [GET] socket.io/?EIO=3&transport=polling&t=${timestamp}&sid=${sessionid} HTTP
   Server Response: ÿ40
3. WEBSOCKET REQUEST socket.io/?EIO=3&transport=websocket&t=${timestamp}&sid=${sessionid} WS REQUEST DATA: 2probe
   Server Response:  [Message 1] 3probe
4. WEBSOCKET REQUEST socket.io/?EIO=3&transport=websocket&sid=${sessionid} REQUEST DATA: 5 
   Server Response:  [Message 1] 3probe
5. WEBSOCKET REQUEST socket.io/?EIO=3&transport=websocket&sid=${sessionid} REQUEST DATA: 42["auth", "test", "test", "test"]  
   Server Response:  [Message 1] 3probe

---
##### DEBUG=\* node server.js

  engine intercepting request for path "/socket.io/" +0ms
  engine handling "GET" http request "/socket.io/?EIO=3&transport=polling&t=1432340495988" +1ms
  engine handshaking client "oWkewBuyw3c6ZztNAAAA" +3ms
  engine:socket sending packet "open" ({"sid":"oWkewBuyw3c6ZztNAAAA","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}) +1ms
  engine:polling setting request +1ms
  engine:socket flushing buffer to transport +0ms
  engine:polling writing "  �0{"sid":"oWkewBuyw3c6ZztNAAAA","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}" +1ms
  engine:socket executing batch send callback +4ms
  socket.io:server incoming connection with id oWkewBuyw3c6ZztNAAAA +4s
  socket.io:client connecting to namespace / +1ms
  socket.io:namespace adding socket to nsp / +0ms
  socket.io:socket socket connected - writing packet +3ms
  socket.io:socket joining room oWkewBuyw3c6ZztNAAAA +0ms
  socket.io:client writing packet {"type":0,"nsp":"/"} +1ms
  socket.io-parser encoding packet {"type":0,"nsp":"/"} +0ms
  socket.io-parser encoded {"type":0,"nsp":"/"} as 0 +0ms
  engine:socket sending packet "message" (0) +5ms
Conenction recived
  socket.io:socket joined room oWkewBuyw3c6ZztNAAAA +1ms
  engine intercepting request for path "/socket.io/" +2ms
  engine handling "GET" http request "/socket.io/?EIO=3&transport=polling&t=1432340496010&sid=oWkewBuyw3c6ZztNAAAA" +0ms
  engine setting new request for existing client +0ms
  engine:polling setting request +0ms
  engine:socket flushing buffer to transport +0ms
  engine:polling writing "�40" +1ms
  engine:socket executing batch send callback +0ms
  engine upgrading existing transport +14ms
  engine:socket might upgrade socket transport from "polling" to "websocket" +0ms
  engine:ws received "2probe" +2ms
  engine:ws writing "3probe" +1ms
  engine:ws received "5" +3ms
  engine:socket got upgrade packet - upgrading +1ms
  engine:ws received "42["auth", "test", "test", "test"]" **+20s**

**Comment by eib** [comment]
In JMeter, the WebSocket Sampler element has a "Response" timeout property in the "Timeout (milliseconds)" panel. This defaults to 20000. Lowering that means your WS connections close sooner.

Alternatively, there's a "Close connection pattern" in the "WebSocket Response" panel. [Per the manual](https://github.com/maciejzaleski/JMeter-WebSocketSampler/wiki/User-manual#streaming-and-short-lived-connection), this is used when the "Streaming connection" option is enabled. I haven't used it yet, but it looks like "3probe" would be good values for your samplers (numbers 3 and 4).

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
