### ISSUE TITLE
test.chat domain

### ISSUE THREAD

**Issue by nikoloza** [socketio/socket.io#2129]
Hello,

I've got http://test.chat/ domain. But I don't know its use case except some test chat of socket.io maybe.

I can just give you for http://chat.socket.io/ if you want

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
