### ISSUE TITLE
Apache Reverse Proxy Configuration

### ISSUE THREAD

**Issue by numannaufal** [socketio/socket.io#2134]
Dear All,
I have chat application that run on port 3000. Port 80 already used by Apache.
Because security reason, another port than 80 isn't opened so chat application is running
behind reverse proxy that configured in apache. Here is the configuration:

```
ProxyPreserveHost On
ProxyPass /chat http://localhost:3000/
ProxyPassReverse /chat http://localhost:3000/

RewriteEngine on
RewriteCond %{QUERY_STRING} transport=polling
RewriteRule /(.*)$ http://theserver/chat/$1 [P]

ProxyRequests off
ProxyPass /theserver/socket.io/ ws://localhost:3000/socket.io/
ProxyPassReverse /theserver/socket.io/ ws://localhost:3000/socket.io/

```

my chat application is running in url http://theserver/chat
but socket io doesn't work. I have set the parameter like this in client

```
var socket = io("http://theserver/chat");
```

and the error message is like this:

```
GET http://theserver/socket.io/?EIO=3&transport=polling&t=1432814349093-2 404 (Not Found)
...
...
...
```

I am using the latest socket.io version and using apache 2.4.10
I will very grateful for your help.

**Comment by nkzawa** [comment]
Use the `path` option. https://github.com/Automattic/socket.io#serveroptsobject

**Comment by dsalcedo** [comment]
Please close this question listed as 'issue'. For questions please use stackoverflow.
Code strong.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Comment by harirehm** [comment]
I have the exact same problem. @numannaufal,  did you get a chance to resolve it?

Below is how socket is defined in front-end.
`var socket = io("http://theserver/chat");`

I get the following error.

`GET http://theserver/socket.io/?EIO=3&transport=polling&t=... (Not Found)`

But, when I hit `http://theserver/chat/socket.io/?EIO=3&transport=polling&t=...`via browser, I am getting some results. But my app is not hitting through the above URL. Its missing **/chat** in the URL and throwing 404.

**Comment by numannaufal** [comment]
3 years ago...almost forgot, but I had the documentation in my final task. might be help. @harirehm 

`
# /etc/apache2/sites-available/000-default.conf
ProxyPreserveHost On

ProxyPass /socket.io/ws/ ws://localhost:3000/socket.io/ws/
ProxyPassReverse /socket.io/ws/ ws://localhost:3000/socket.io/ws/

ProxyPass /socket.io/ http://localhost:3000/socket.io/
ProxyPassReverse /socket.io/ http://localhost:3000/socket.io/

ProxyPass /chat http://localhost:3000/
ProxyPassReverse /chat http://localhost:3000/

`

**Comment by harirehm** [comment]
Hi @numannaufal, solved the problem by adding a path to the socket variable in the front end. 
[This](https://stackoverflow.com/questions/49591591/socket-io-eio-3-not-found-404) saved me.
