### ISSUE TITLE
Please provide propper browser support documentation

### ISSUE THREAD

**Issue by j-diaz** [socketio/socket.io#2143]
Please provide documentation on which browsers/versions are supported. "Works on every device" does not inspire production use. A simple table will suffice.

**Comment by Mouvedia** [comment]
:+1:

**Comment by TommyLike** [comment]
:+1:

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
