### ISSUE TITLE
I want to chat one to one. What code i changed in example?

### ISSUE THREAD

**Issue by surendrakumar1992** [socketio/socket.io#2144]
Hello,
I want to make app in which client send his/her device id, message and agent id which he want to communicate. Other side agent communicate with device id.
How i can achieve this. Please help

**Comment by anant-singh** [comment]
I have not tried this yet but as much as I understood rooms you can try this.
Under the `add user` event in `index.js`, add the following line: 

```javascript
socket.username = username;
socket.join(username); // Creates a room where this user is the only one in the room.
```
In the client side, in `main.js`, under `sendMessage` make the following change:

```javascript
var recipient = $inputRecipient.val();
socket.emit('new message', {
    message: message,
    recipient: recipientId
});
```

On the server side, now make the following changes in `new message` event:

```javascript
socket.on('new message', function(data) {
    if(!data.recipient){
        socket.broadcast.emit('new message', {
            username: socket.username,
            message: data.message
        });
    else{
        socket.broadcast.to(data.recipient).emit('new message', {
            username: socket.username,
            message: data.message
        });
    }
});
```

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
