### ISSUE TITLE
Does not work with TLS Http2 server object

### ISSUE THREAD

**Issue by peterhanneman** [socketio/socket.io#2145]
Works fine with standard node HTTPS package.  Breaks when started using: https://github.com/molnarg/node-http2

**Comment by willin** [comment]
+1

**Comment by willin** [comment]
How to test with http2?

**Comment by DJCMBear** [comment]
I was also having issues with this, and found a solution to it, depending on your code you have to place the HTTP2 listen call after the socket.io binding code.

My setup currently allows for both HTTP and HTTPS over a single port using express with the ability to force upgrade, HTTP uses HTTP/1.1 and HTTPS uses H2, I have just managed to also implement socket.io to also use a single codebase to cover both HTTP and HTTPS over a single port however like Peter I was unable to use socket.io over the HTTP2 protocol but when changing it to nodes HTTPS package socket.io begins working without any other code changes.

Below is a simple guide to how I got it working `(code not fully functional)`, the second bit of code shows the HTTP and HTTP2 listeners being set after the socket.io package has been bound to each server.

The way I was doing it (works only with nodes http and https packages)
> var ioServer = require( 'socket.io' );
> var io = new ioServer();
> var net = require( 'net' );
> var http = require( 'http' );
> var https = require( 'https' );
>
> net.createServer( netHandler ).listen( [single access port here] );
>
> io.attach( http.createServer( app ).listen( [http proxy port here] ) );
> io.attach( https.createServer( [https cert and key here], app ).listen( [https proxy port here] ) );
>
> io.on( 'connection', handler );

The way to get it working with http2

> var ioServer = require( 'socket.io' );
> var io = new ioServer();
> var net = require( 'net' );
> var http = require( 'http' );
> var https = require( 'http2' );
>
> net.createServer( netHandler ).listen( [single access port here] );
>
> http = http.createServer( app );
> https = https.createServer( [https cert and key here], app );
>
> io.attach( http );
> io.attach( https );
>
> http.listen( [http proxy port here] );
> https.listen( [https proxy port here] );
>
> io.on( 'connection', handler );

Once I made this change both the HTTPS requests and websockets worked over the H2 protocol.

**Comment by efx** [comment]
The HTTP/2 protocol does not support websocket connections. Here is a helpful article to explain in more detail: https://daniel.haxx.se/blog/2016/06/15/no-websockets-over-http2/ (note, he is the author of curl so knows much more than I and many others on networking protocols).

**Comment by darrachequesne** [comment]
For future readers, you need to enable compatibility with HTTP 1.1 clients:

```js
const fs = require("fs");
const httpServer = require("http2").createSecureServer({
  allowHTTP1: true,
  key: fs.readFileSync("/tmp/key.pem"),
  cert: fs.readFileSync("/tmp/cert.pem")
});
const options = { /* ... */ };
const io = require("socket.io")(httpServer, options);

io.on("connection", socket => { /* ... */ });

httpServer.listen(3000);
```

Documentation:
- https://socket.io/docs/v3/server-initialization/#Attached-to-an-existing-HTTP-server
- https://nodejs.org/api/http2.html
