### ISSUE TITLE
package.json dependencies

### ISSUE THREAD

**Issue by Schniz** [socketio/socket.io#2146]
Hey!
I'm having trouble setting up socket.io and its dependencies with [sinopia](https://github.com/rlidwka/sinopia). I use sinopia for in-house NPM in a closed network.

Socket.IO installation depends on github repositories and I'd like to know if you guys thinking about moving towards "regular" npm usage with packages and semvers.

that would be the easiest way to make sure closed network organizations could use socket.io in their in-house apps.

**Comment by shahar3012** [comment]
:+1: 

I have the exact same problem.

**Comment by metamatt** [comment]
The underlying cause is in engine.io, https://github.com/socketio/engine.io-client/issues/358, right?

**Comment by Schniz** [comment]
Seems like it

**Comment by nkzawa** [comment]
Fixed in 1.4.x
