### ISSUE TITLE
How ban one user?

### ISSUE THREAD

**Issue by martec** [socketio/socket.io#2147]
How ban one user using socket.id in 1.0 series?

**Comment by dsalcedo** [comment]
I think you need:
* Databases
* "handshake" or like. (http://socket.io/docs/migrating-from-0-9/)

Any way, this is not a issue can you solve this 'question' in http://stackoverflow.com/
Code strong!

**Comment by martec** [comment]
@dsalcedo 
you making some confusion.
I already has socket.id of user. But in 1.0 not work more socket.manager.onClientDisconnect(socket.id).
So what command i can use in instead?

**Comment by dsalcedo** [comment]
In this part of code exist : 
https://github.com/socketio/socket.io/blob/master/lib/socket.js#L446
```javascript
/**
 * Disconnects this client.
 *
 * @param {Boolean} if `true`, closes the underlying connection
 * @return {Socket} self
 * @api public
 */
Socket.prototype.disconnect = function(close){
  if (!this.connected) return this;
  if (close) {
    this.client.disconnect();
  } else {
    this.packet({ type: parser.DISCONNECT });
    this.onclose('server namespace disconnect');
  }
  return this;
};
```

so, i think (i think) this should be work:
```javascript
/*
* Client side
*/
socket.emit('forceDisconnect');

/*
* Server side
*/
socket.on('forceDisconnect', function(){
    socket.disconnect();
});
```
Code strong!

**Comment by martec** [comment]
@dsalcedo 
i already tried this before you posted here.
not work correctly. if user try connect after disconnect usinbg code above will appear two message in each message that user send.
socket.manager.onClientDisconnect(socket.id) in 0.9 or below work perfect. but 1.0 not.

**Comment by dsalcedo** [comment]
Im reading this post in the blog of Socket.io and found this:
http://socket.io/blog/socket-io-1-2-0/
```javascript
// Client side
var socket = io({ forceNew: true });
socket.once('connect', function() {
  socket.disconnect();
});

socket.once('disconnect', function() {
  socket.once('connect', function() {
    console.log('Connected for the second time!');
  });
  socket.connect();
});
```
Code strong !!

**Comment by martec** [comment]
@dsalcedo 
plz make test here first before post.
already tested all thing you saying...
not work correctly.
what i need is socket.manager.onClientDisconnect(socket.id) in 1.0 series.

**Comment by dsalcedo** [comment]
you're absolutely right, I've made changes and I disconnect the server side
![captura de pantalla 2015-07-29 a las 23 33 59](https://cloud.githubusercontent.com/assets/1441444/8975895/5fdde9da-364a-11e5-9894-294d96348a8c.png)

```javascript
// Server side
io.on('connection', function (socket) {
  console.log('socketID: ',socket.id, ' - connected')

  setTimeout(function() {
    console.log('socketID: ',socket.id,' - disconnect')
   socket.conn.close();
    console.log('socketID: ',this.socket,' - disconnect')
  }, 3000);
});
```

```javascript
// Client side
  var socket = io({
  	reconnection:false
  });

```

**Comment by DannyvanderJagt** [comment]
If you want to prevent someone from connecting to your server you should use `socket.io` middelware.
Middelware is basic stuff in `http` and it in new in `socket.io` 1.0. See [this migration guide](http://socket.io/docs/migrating-from-0-9/#authentication-differences) 

You can use it like this:
```js
// Server side
var io = require('socket.io')(3000);

io.use(function(socket, next){
   // socket contains a list of headers including the clients ip adress etc.
   if(isUserIsAllowed(socket)){  // Check if the user is banned.
         // An empty next() will allow the use to connect.
        next();
   }else{
       // This will send the client and error event and it will prevent the client from connecting to your server.
       next(new Error('You are not allowed on this server!'));
   }  
});
```

If you want to disconnect a client which is already connected you simple use:
```js 
socket.disconnect();
```

The client will get a disconnect event. It will still be able to send events to your server but they will never arrive/be processed by your server side code. And the reconnect attempt from the client will fail because of the middelware.

**I hope this helps.**
*The code is tested and is working here! ;) Let me know if you have any problems!*

**Comment by martec** [comment]
@DannyvanderJagt 
thanks but i need disconnect specific user using socket.id
because of this that i need something like socket.manager.onClientDisconnect(socket.id) in 1.0

**Comment by DannyvanderJagt** [comment]
I think I understand your problem now. 
You want to get a socket by its id and disconnect that socket. I'v read that you already have the socket.id of the socket you want to disconnect.

In order to get a socket by socket.id you can use this:
```js
var io = require('socket.io')(3000);

// Get a socket by id.
var socket = io.to(socket.id);

// Now that you have the socket you can do what ever you want like disconnect it.
socket.disconnect();
```

*Note: The socket can reconnect once it is disconnected. If want to prevent this you can/need to use middelware. See my previous comment. https://github.com/socketio/socket.io/issues/2147#issuecomment-126320131*

**Comment by dsalcedo** [comment]
:+1:

**Comment by martec** [comment]
@DannyvanderJagt 
@dsalcedo 

One of first thing i tried... But not work corectly for me...
has same issue of this user https://github.com/socketio/socket.io/issues/47#issuecomment-17094329

**Comment by dsalcedo** [comment]
...mmm ok, so maybe you are doing wrong code and you need update to SocketIO V1 with the new methods and events; Remember, the upgrade of socketio to stable version is for make better code and practices. If you find the way for do the action that you are searching, share with us :smile: !

**Comment by dsalcedo** [comment]
Please close this question listed as 'issue'. For questions please use stackoverflow.
Code strong.
