### ISSUE TITLE
npm WARN package.json socket.io@1.3.5 No license field.

### ISSUE THREAD

**Issue by 1mihirpandya** [socketio/socket.io#2149]
When I enter "$ npm install" into terminal (Mac OS), I receive this error: "npm WARN package.json socket.io@1.3.5 No license field." What does it mean and how do I fix it?
![screen shot 2015-06-06 at 3 53 45 pm](https://cloud.githubusercontent.com/assets/7907525/8021797/41447314-0c64-11e5-9644-e65de0adc7ee.png)

**Comment by jehmehta** [comment]
Same issue here for a diff repo although but the very same error! please help!

**Comment by jehmehta** [comment]
Hey i resolved it just add:
"license": "ISC"
to the package.json file :)
