### ISSUE TITLE
Socket.io websocket getting stucked after a while

### ISSUE THREAD

**Issue by lucaswxp** [socketio/socket.io#2150]
Hey guys.

I have a weird behavior with my socket.io implementation, it works well a while (30min - 1 hour uptime), but then it seems connections can't be made any further, look at the print screen of what  Network Inspector shows:
![captura de tela 2015-06-11 as 08 43 53](https://cloud.githubusercontent.com/assets/131314/8107388/cf6a2f0c-1016-11e5-8ec2-73dc62661302.png)

The client keeps receiving these "2" and "3" data forever, that I have no idea what it means.

If I restart the webserver, things get back working:
![captura de tela 2015-06-11 as 08 46 43](https://cloud.githubusercontent.com/assets/131314/8107436/2bd36682-1017-11e5-88ef-864ea9ca486b.png)

I'm out of ideas how to debug this, the logs doesn't show anything specific on disconnect, I usually get generic messages like "transport close", "server namespace disconnect" and "client namespace disconnect".

Can anyone please help me debug this further?

**Comment by peteruithoven** [comment]
Not sure how to debug this, but I would check my nginx / haproxy / apache settings, to check if they're ready for socket connections.

**Comment by lucaswxp** [comment]
@peteruithoven I don't think it's a proxy issue, otherwise it wouldn't even work to begin with.

I'm more interested in those "3" and "2" sent from the server...they look like some kind of status code, but I can't figure it out.

**Comment by maxzeroedge** [comment]
Those 2 and 3 look more like requests to me. If you look at the request strings, they conten 2 or 3 at the end. Maybe you do something with the requests, as is seen in your later responses ([42, "percentage", 2] like them.

**Comment by lucaswxp** [comment]
@maxzeroedge I still don't understand. I'm not making those '2' and '3' requests, not directly at least... The `["percentage", 2]` is my json-encoded data, but the "42" inserted in the beginning is inserted by socket.io `42["percentage", 2]`

**Comment by maxzeroedge** [comment]
Then that 42 is probably the size of data transmitted. 4x10 + 2
That makes me wonder, if those 2 and 3 are also sizes of data transmitted, in which situation, it must mean that there is some problen with requests at server. Can you log the requests you get at server to see what happens when such data starts to appear?

**Comment by lucaswxp** [comment]
I don't think it's the size of data. Why 4x10? It's a 17-length string, shouldn't it be 17 bytes then? Since the chars used are within the ascii table, each one should occupy 1 byte only. Also, when the data is bigger, it always sends "42", independently of data size. Hence the why I think it's some kind of status code.

**Comment by lucaswxp** [comment]
About logging the requests,

That is an interesting point, I've tried that in the past. What happens is the client connects to the server, but that's it. It doesn't receive any messages or sends them.

**Comment by lucaswxp** [comment]
I'm closing this, since I don't need it anymore.
