### ISSUE TITLE
Connection rate limiting.

### ISSUE THREAD

**Issue by allthetime** [socketio/socket.io#2151]
I'm running a socket.io driven app that is sometimes viewed through an iframe on a popular blog. I keep track of sessions on the backend so I know which sockets belong to who. Sometimes a client will connect and disconnect and connect repeatedly, hundreds of times at least once a second. 

I'm guessing its someone using an ancient browser of some kind that doesn't understand sockets and doesn't play nice with XHR polling.

My question: is there any standard way within socket.io to detect this type of activity and stop it?

I'm currently keeping an object that counts connection attempts for sessions and then stops them from being able to access the app after a burst of attempts. I'm hoping there's some way to block specific clients outright...

**Comment by zevero** [comment]
Similar here!
I have an app behind a secure login (company policy). For some reason I dont get an upgrade to websockets, so I am left with polling.
Now, if the session is up, socket.io goes wild. It retries connecting multiple times a second with 302 and 304s. Even when doing socket.close(). !!!

At least it should only retry every x seconds...

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
