### ISSUE TITLE
Chat example -- would anyone please update it to use the newest express version?

### ISSUE THREAD

**Issue by agamemnus** [socketio/socket.io#2152]
Thanks...

**Comment by aHumanBeing** [comment]
Would need this as well.  Express generator now creates the http server in /bin/www file and not app.js.  Furthermore, I need the ability to maintain the socket between routes.  How may I accomplish this in a clean way?  Thank you.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
