### ISSUE TITLE
Emitting a message when returning a json stream

### ISSUE THREAD

**Issue by joshterrill** [socketio/socket.io#2157]
Is it possible to emit a message when doing a `res.json({});` call using express? I want to be able to tell when someone visits a route that returns a json stream.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
