### ISSUE TITLE
Why exactly are sticky sessions required for multiple nodes after an upgrade from 0.9x to 1.0?

### ISSUE THREAD

**Issue by matthewhafner** [socketio/socket.io#2158]
The only explanation I have seen is the following: 
Instead of storing and/or replicating data across nodes, Socket.IO is now only concerned with passing events around.

Is there a more detailed explanation to this? What specifically changed?
## My Scenario

nodejs - 0.10.31 and 0.12.4
socket.io - 1.3.5
socket.io-client 1.3.5

Before we upgraded from socket.io 0.9.16 to 1.3.5, socket connections were able to find the server they originated from while behind an AWS load balancer pointing to *.mydomain.com. After the upgrade we  are seeing websocket handshake errors and xhr polling errors. The socket.io advice is to enable sticky sessions and the redis adapter (i was already using the redis adapter). I followed the advice and added an nginx server in front of our application servers.

http://socket.io/blog/introducing-socket-io-1-0/#scalability
http://socket.io/docs/using-multiple-nodes/

The problem comes with autoscaling nginx servers and using sticky sessions. Following nginx architecture advice - http://nginx.com/blog/using-ngnix-amazon-elastic-load-balancer-aws/
I am able to get my app working with multiple application servers (each running socket.io) and route to them with a single nginx instance. As soon as I add a second nginx instance, the load balancer can send the traffic to the second nginx instance, which may send it to a different application server. Then I am back where I started from with the same errors as above.

This all works as long as I have one nginx server as the bottleneck/single point of failure, which does not meet our requirements for autoscaling in case of major traffic spurts.

Does anyone have a solution that will enable the upgrade to socket 1.0 and keep our ability to scale.

Thanks in advance
Matt

**Comment by nappa32** [comment]
Have you come to a solution to this ?

**Comment by shawn-simon** [comment]
+1

**Comment by jnorris441** [comment]
+1

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
