### ISSUE TITLE
Example code uses undocumented API

### ISSUE THREAD

**Issue by cherrydev** [socketio/socket.io#2161]
So, imagine that this is your first time using socket.io and you come to this GitHub repo, read the Readme.md and then read through the example code.  In the example code, the only method that's being used to communicate back with the client is this `socket.broadcast.emit` function, so obviously this is the standard way of sending messages back to the client, right?  So I look the documentation and find absolutely no mention of `broadcast` being any part of `socket`.

Eventually, I learn about `socket.broadcast` from [a StackOverflow](https://stackoverflow.com/questions/10342681/whats-the-difference-between-io-sockets-emit-and-broadcast) question instead.

**Comment by maxzeroedge** [comment]
If you look at the examples on the website and the documentation there, then things arr a lot more clear.

**Comment by cherrydev** [comment]
Yes, I also see it's mentioned in the overview, but not under "Server API" or "Client API".  I just thought that was weird.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
