### ISSUE TITLE
Does it work well in iOS7?

### ISSUE THREAD

**Issue by lbchange** [socketio/socket.io#2164]
we developed an iOS App, which using HTML5 , websocket and nodejs as server. in iOS8, it works well. but in iOS7, we found packet losing issue. the app can't receive the packets from server. Does anybody else suffer this problem?

**Comment by knusprigeswuerstchen** [comment]
Check [this](http://caniuse.com/#feat=websockets)

**Comment by objectiveSee** [comment]
We have been successfully using Socket.IO 1.x on iOS7 since it socket.io 1.0 was released with no packet loss.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
