### ISSUE TITLE
Migrating from 0.9 docs misleading for heartbeat config values

### ISSUE THREAD

**Issue by jabclab** [socketio/socket.io#2165]
In the [migrating from 0.9 docs](http://socket.io/docs/migrating-from-0-9/#configuration-differences) it says:

> `io.set('transports')`, `io.set('heartbeat interval')`, `io.set('heartbeat timeout')`, and `io.set('resource')` are still supported for backwards compatibility.

However, it doesn't mention that in 0.9.x these values were in seconds whereas now milliseconds are used. Therefore if we had the following `io.set('heartbeat timeout', 5)`  in 1.x we would be setting `pingTimeout` to 5ms so the client would only have 5ms to respond with a pong otherwise the server would think it had disconnected.

I guess either:
- Docs are updated to say that the value is now in milliseconds.
- Values are auto converted to milliseconds to allow complete backwards compatibility, e.g.

``` js
var oldSettings = {
  "transports": "transports",
  "destroy buffer size": "maxHttpBufferSize"
};

var oldSettingsSeconds = {
  "heartbeat timeout": "pingTimeout",
  "heartbeat interval": "pingInterval"
};

Server.prototype.set = function (key, val) {
  // ...
  } else if (oldSettings[key] && this.eio[oldSettings[key]]) {
    this.eio[oldSettings[key]] = val;
  } else if (oldSettingsSeconds[key] && this.eio[oldSettingsSeconds[key]]) {
    this.eio[oldSettingsSeconds[key]] = val * 1000;
  }
  // ...
}
```

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
