### ISSUE TITLE
socket.to(roomid) doesn't include the sender himself.

### ISSUE THREAD

**Issue by hatelove85911** [socketio/socket.io#2170]
I'm using version 1.3.5.

My understanding is `socket.broadcast.to(roomid)` is to exclude the sender for being notified.
while `socket.to(roomid)` will include the sender himself. 
But it's not the case in 1.3.5
I think it's a bug

**Comment by tecnogram888** [comment]
Here are my notes on behavior
socket.emit = to selected socket
io.emit() = to all sockets (identical to io.sockets.emit)
io.sockets.emit = to all sockets
socket.broadcast.emit = excludes current socket
io.sockets.in(room).emit = to all sockets in the room including this one if it's in the room
socket.to(room).emit = to all sockets in the room excluding this one
if a bad room is given (undefined) nothing happens: no exceptions/errors/crashes

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
