### ISSUE TITLE
Messages not being sent from client

### ISSUE THREAD

**Issue by iamdriz** [socketio/socket.io#2188]
I have three Node applications that need to talk to each other that contain the following code:

APP 1

```
var io = require('socket.io')();

io.on('connection', function (socket) {
socket.on('comms', function (data) {
    console.log(data);
});
});

io.listen(8004);

setInterval(function(){
    io.emit('comms', {'hello':'world'});
}, 2000);
```

APP 2 (listens for comms from APP 1 and 3)

```
var socket = require('socket.io/node_modules/socket.io-client')('http://localhost:8004');

socket.on('comms', function (data) {
    console.log(data);
});
```

APP 3

```
var socket = require('socket.io/node_modules/socket.io-client')('http://localhost:8004');

setInterval(function(){
    socket.emit('comms', {'goodbye':'world'});
}, 2000);
```

However I only get the comms from APP 1 and not from APP 3 appearing in APP 2.

I do see the comms from APP 3 in APP 1 but not APP 2.

What's the issue? Do I then have to send comms back down from 1 that came from 3 to 2?

**Comment by maxzeroedge** [comment]
There is a space between socket and .emit in app 3

**Comment by iamdriz** [comment]
@maxzeroedge That **was** just a typo I made here.

**Comment by maxzeroedge** [comment]
Try io.sockets.emit or socket.broadcast.emit  in app 1. io.emit will only
emit for the current connection, which may be only to app 3 when app 3 is
sending.

**Comment by iamdriz** [comment]
@maxzeroedge APP 1 emits fine. It's APP 3 that's not emitting!

**Comment by maxzeroedge** [comment]
You realize that the app 3 emits to app 1 (if I am correct in assuming it
is the socket.io server) which emits or rather relays back to app 3 and not
to app 2. In websockets, the server has to act like a relay to transmit
data.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
