### ISSUE TITLE
Detecting socket.io client version

### ISSUE THREAD

**Issue by adriano-di-giovanni** [socketio/socket.io#2190]
Is it possible to detect socket.io client version on incoming requests in order to switch to a Node.js server instance having matching socket.io server version?

Is it possible to do it at nginx level?

Thanks in advance,
Adriano

**Comment by dsalcedo** [comment]
Please close this question listed as 'issue'. For questions please use stackoverflow.
Code strong.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
