### ISSUE TITLE
Flashsocket where to go？

### ISSUE THREAD

**Issue by guhaizhous** [socketio/socket.io#2196]
Why socket.io1.x version did not like 0.9.16/17 flashsocket.js, how fruit project needs to communicate with flash, what to do, how to do?

**Comment by dsalcedo** [comment]
Flash? Really?
(see https://blog.malwarebytes.org/malvertising-2/2015/08/large-malvertising-campaign-takes-on-yahoo/)
Flash not its supported en SocketIO V1+, but you can use Websockets, Polling and another option. Flash isn't secure and spends enough resources (and flash is disabled on OSX computers).
Whatever, the modern browser supports Websockets. 
http://caniuse.com/#search=websockets
Code strong !

**Comment by nkzawa** [comment]
Flash transport is not supported. Please implement it yourself if you really need it, but usually websocket and polling would be enough anyway.

**Comment by fullflash** [comment]
There can be actionscript support for adobe air applications like mobile.
Adobe air have socket client and socketserver built in. 
Using socket.io for adobe air mobile apps would be great.
Adobe air mobile apps is powerfull than hybrid apps running on browsers.
