### ISSUE TITLE
Organize these issues

### ISSUE THREAD

**Issue by apeace** [socketio/socket.io#2197]
The other day I Slacked @rauchg and mentioned I'm interested in helping to clean up the issues on this repo. He expressed interest, so I put together this proposal.

At time of this writing, there are 227 open issues. I think the best way I can contribute to socket.io at this time, is to process these issues and label them. Here is what I'd like to do:

 * Delete all labels, and replace with: Bug, Request, Verified, Cannot Reproduce, Upstream, and Milestone-1.4. There are a lot of labels in the repo, and I think that's contributing to most issues not getting labeled. I'd like to simplify the labels so they are easier to use.
 * Go through each issue and label as Bug or Request.
 * Go through each bug and attempt to reproduce. Mark reproducible bugs as Verified, and the rest as Cannot Reproduce. I'll also mark Upstream bugs, and link them with the appropriate upstream issue (e.g. engine.io issues).
 * Write a small script to automatically close Cannot Reproduce issues if they have not received a comment in the last 30 days. I'll run this periodically, and put it in a gist so that anyone else can use it, too.
 * I won't use the Milestone-1.4 label, but I think the socket.io developers should use it to indicate which Request tickets will go into the 1.4 release.

Hopefully through these few steps, we can get the issues better-organized, close a few which are not valid or no longer relevant, and get a sense for how many current reproducible bugs there are.

I'd love if it the socket.io devs could evaluate this plan and give me feedback. From there, let me know how we can move forward!

**Comment by rauchg** [comment]
This sounds great to me. I like having only a few labels. +1!

**Comment by nkzawa** [comment]
:+1: I will help as much as I can.

**Comment by apeace** [comment]
Thanks guys! I'm awaiting word here or on Slack about how I can start this project :)

I have been browsing the issues already and think it would be appropriate to add two more labels: Question and Need More Information.

There are lots of issues which are people asking questions about their specific application/setup. These would be labeled Question. Some have remarked that these questions should be on StackOverflow instead, and I agree. We can close these, but might as well mark them as Question so we can see which closed tickets were just questions.

There are also some reported "bugs" that don't quite have enough information to act on. For these, I would label them Bug (since the user thinks it's a bug), and Need More Information.

Let me know if these additions sound good, and how I can move forward on this!

**Comment by tabone** [comment]
+1

**Comment by apeace** [comment]
Hey all,

Been almost a month since I created this and got interest from a few of you, including @rauchg. Is there still interest? If you let me know how I can move forward (issue-editing access on the repo?) I can get started this weekend!

**Comment by rauchg** [comment]
Sorry for the delay! Added you to the team

**Comment by apeace** [comment]
Whoop! I'll get started this weekend!
