### ISSUE TITLE
How can socket.io work with pm2 cluster?

### ISSUE THREAD

**Issue by node-rookie** [socketio/socket.io#2200]

**Comment by tabone** [comment]
Take a look at the docs: http://socket.io/docs/using-multiple-nodes/

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Comment by songguangyu** [comment]
when in pm2 cluster , socket.to(room) can not work,what wrong?
i set ip hash but it not work

**Comment by darrachequesne** [comment]
For future readers, please check https://socket.io/docs/v4/pm2/
