### ISSUE TITLE
Change client to server and server to client in socket.io (nodejs)

### ISSUE THREAD

**Issue by geniant** [socketio/socket.io#2201]
Hello,

I know the title is so weird, but my problem is there.

Socket.io offers a big advantages which is establishing connection with clients even if clients are under firewalled local network.

This happens if the server has a public IP, and the clients connect on it. In my case, the server is under a firewalled local network and the client has the public IP.

I thought about making a client in the server and a server in the client to establish a socket connection. Then I reuse the existing (opened) socket connection to connect a server in the client side and a client in the server side.

Any help ?

Thanks

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
