### ISSUE TITLE
Where exaclty is the socket id generated?

### ISSUE THREAD

**Issue by rcc26** [socketio/socket.io#2203]
In which file is the socket hash generated? This is, for example, "AxbahHshHshr2Hdjl"

**Comment by Nibbler999** [comment]
It's actually generated in engine.io - lib/server.js. Look for base64id.

**Comment by rcc26** [comment]
Could you tell me the process tree that takes to that point? I'm trying to add an extra parameter to the handshake function since the user connects

**Comment by ClassicOldSong** [comment]
You can use a public array or class to link to each socket. Such as
```javascript
var socketHub = [];
var i = 0;
io.on('connection', function (socket) {
  socketHub[i] = socket;
  i++;
}
```
then you can use ```socketHub[i]``` to control whatever socket youwant.
