### ISSUE TITLE
When in polling mode, client doesn't receive middleware errors.

### ISSUE THREAD

**Issue by JohnyDays** [socketio/socket.io#2204]
Client tries to connect -> Server middleware calls next(error) -> Client doesn't trigger on('error') and keeps trying to connect.
If we are in websocket mode, this problem doesn't occur

**Comment by darrachequesne** [comment]
Hi! I haven't been able to reproduce the issue with the following code:
```javascript
var cluster = require('cluster'),
  server = require('socket.io')(),
  client = require('socket.io-client');

if (cluster.isMaster) {
  server.listen(8181);
  server.use(function(socket, next){
    console.log('[server] middleware called');
    next(new Error('thou shall not pass'));
  });
  cluster.fork();
} else {
  var socket = client('http://localhost:' + '8181', { 'transports': [ 'polling' ] });
  socket.on('error', function () {
    console.log('[client] error');
  });
  socket.on('connect', function () {
    console.log('[client] connect');
  });
}
// output:
// [server] middleware called
// [client] error
``` 
node@0.12.7 / socket.io@1.3.5 / socket.io-client@1.3.5 (also tested with version 1.3.7)

Are you having this issue in a particular browser?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
