### ISSUE TITLE
change query params

### ISSUE THREAD

**Issue by fabi0w** [socketio/socket.io#2205]
My initial connection is passed the following parameters:

"? profile_id = 2 & mc_g = 0 & uc_g = 0 & lc_g = 0" of

`handshake:
      url: '/socket.io/?profile_id=2&mc_g=0&uc_g=0&lc_g=0&EIO=3&transport=polling
& t = 1439583938299-0 '`

How can I change these parameters with the client already connected?

**Comment by nkzawa** [comment]
You can't change query parameter afterward. If you need to do that, create a new connection or send parameters as an event data.
