### ISSUE TITLE
require('socket.io') takes 2.2 seconds on RaspberryPi

### ISSUE THREAD

**Issue by ceremcem** [socketio/socket.io#2206]
`require('socket.io');` takes 2.2 seconds on RaspberryPi. Why would it be?

Here is the original thread: http://raspberrypi.stackexchange.com/questions/34496/node-js-and-its-require-function-is-too-slow

**Comment by Nibbler999** [comment]
That's normal in my experience.

**Comment by 3rd-Eden** [comment]
Why would it even matter? It only affects start-up time of your application. If connections took 2.2 seconds to establish the would be whole different issue at hand.

**Comment by ceremcem** [comment]
@3rd-Eden It's not the only thing, we are using Hapi.js also and it adds 4 seconds to startup time. Node's own startup time is 0.9 seconds... Total startup time is 7.2 seconds. These all make the system look so slow.  

Anyway, if you say it is normal, then it might be OK.
