### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io#2209]
I picked up an old project using socket.io:

```
  "dependencies": {
    "express": "2.5.x",
    "irc": "0.3.x",
    "socket.io": "0.8.x"
  },
```

I get the error on some users but not all, any fix?

```
   debug - set heartbeat interval for client 21247142871726833819
   warn  - websocket connection invalid
   info  - transport end
```

**Comment by darrachequesne** [comment]
Hi! Could you provide more information about this issue? Is upgrading to a more recent version of Socket.io a possibility for you (0.8 is a bit old)?

**Comment by nkzawa** [comment]
Unfortunately, 0.8 wouldn't be supported.
