### ISSUE TITLE
Cannot found the full list of socket.io configuration parameters 

### ISSUE THREAD

**Issue by xinyuanyu** [socketio/socket.io#2210]
I'm using socket.io@0.9.16 in my project, and now planing to upgrade to newer version. 

According to the migration doc : http://socket.io/docs/migrating-from-0-9/, 
`.set` method is deprecated in new version, and should use the following code to apply configuration: 

```javascript
var socket = require('socket.io')({
  // options go here
});
```
I set `heartbeat timeout` in version 0.9.16, but cannot find any words containing `heartbeat` in new document. Is this configuration deprecated?

BTW, it will be great if we have all available configuration parameters with detail description listed in the doc?

**Comment by Nibbler999** [comment]
For options read https://github.com/socketio/socket.io#serveroptsobject which points you to https://github.com/socketio/engine.io#methods-1

`heartbeat timeout` is now `pingTimeout`

**Comment by xinyuanyu** [comment]
Caught it. Thanks.
