### ISSUE TITLE
Anyone can spam easily by using the exposed io() function

### ISSUE THREAD

**Issue by ClassicOldSong** [socketio/socket.io#2211]
Once linked to the socket anyone can use a simple script to start spamming just by running this in your browser's console:
`for (i=1; i<1000; i++) { io().emit("new message", i.toString());};`

`new message` can be replaced with any event that the server can responce, such as I can easily make the onlinecount to a great number:
![image](https://cloud.githubusercontent.com/assets/10512422/9308574/78895d7e-4537-11e5-8ee2-8412d8e2a73a.png)

I hope you can find a solution to solve this problem.

**Comment by ClassicOldSong** [comment]
Found solution: pass ```io()``` into a closure and then use ```window.io = null;``` to neutralize the global ```io()``` function

**Comment by 3rd-Eden** [comment]
That doesn't solve the problem as you only hide `io` constructor. Everybody can still create thousands of connections using any other library them choose to import or just through the CLI. But this is hardly a Socket.IO issue as you should take care of rate limiting and DDOS protection your self.

**Comment by ClassicOldSong** [comment]
Yeah but the demo chatroom can just use this method to flood.

**Comment by shawn-simon** [comment]
welcome to the internet @ClassicOldSong

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
