### ISSUE TITLE
Request timeout on mobile browser

### ISSUE THREAD

**Issue by adeelsaleem** [socketio/socket.io#2214]
Hi,

I'm getting error when i deployed my web app on heroku server.

2015-08-19T13:16:47.035288+00:00 heroku[router]: at=error code=H12 desc="Request
 timeout" method=GET path="/socket.io/?EIO=3&transport=polling&t=1439990176946-1
3&sid=p_OmBS-9X9JhY6ilAAAC" host=xyz.herokuapp.com request_id=e63cefc2
-7179-41d3-844f-c0548257cf28 fwd="116.58.29.6" dyno=web.1 connect=1ms service=30
001ms status=503 bytes=0

**Comment by adam-back** [comment]
Same on AWS in environment running:
64bit Amazon Linux 2015.03 v1.4.1
Node version 0.12.2

No proxy server and normal EB load balancing.

**Comment by ceemomx** [comment]
save problem in phonegap webapp. no nginx, connect with IP. tested on dev server, everything was OK. time out in product server.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
