### ISSUE TITLE
Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1

### ISSUE THREAD

**Issue by guyuewei** [socketio/socket.io#2215]
## Q:\test_fis3_c\kf5>cnpm install socket.io

> bufferutil@1.1.0 install Q:\test_fis3_c\kf5\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

\
Q:\test_fis3_c\kf5\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\伟\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\bin\node-g
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  bufferutil.cc
..\src\bufferutil.cc(7): fatal error C1083: 无法打开包括文件: “v8.h”: No such file or directory [Q:\test_fis3_c\kf5\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcx
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\伟\AppData\Roaming\npm\node_modules\cnpm\node_modules\pangyp\lib\build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\Users\伟\AppData\Roaming\npm\node_modules\cnpm\node_modules\pangyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd Q:\test_fis3_c\kf5\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok

> utf-8-validate@1.1.0 install Q:\test_fis3_c\kf5\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

Q:\test_fis3_c\kf5\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\伟\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\bin\no
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  validation.cc
..\src\validation.cc(7): fatal error C1083: 无法打开包括文件: “v8.h”: No such file or directory [Q:\test_fis3_c\kf5\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate\build\validation
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\伟\AppData\Roaming\npm\node_modules\cnpm\node_modules\pangyp\lib\build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\Users\伟\AppData\Roaming\npm\node_modules\cnpm\node_modules\pangyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd Q:\test_fis3_c\kf5\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0

> utf-8-validate@1.1.0 install Q:\test_fis3_c\kf5\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

Q:\test_fis3_c\kf5\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\伟\AppData\Roaming\npm\node
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  validation.cc
..\src\validation.cc(7): fatal error C1083: 无法打开包括文件: “v8.h”: No such file or directory [Q:\test_fis3_c\kf5\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_mo
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\伟\AppData\Roaming\npm\node_modules\cnpm\node_modules\pangyp\lib\build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\Users\伟\AppData\Roaming\npm\node_modules\cnpm\node_modules\pangyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd Q:\test_fis3_c\kf5\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0

> bufferutil@1.1.0 install Q:\test_fis3_c\kf5\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

Q:\test_fis3_c\kf5\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\伟\AppData\Roaming\npm\node_mod
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  bufferutil.cc
..\src\bufferutil.cc(7): fatal error C1083: 无法打开包括文件: “v8.h”: No such file or directory [Q:\test_fis3_c\kf5\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_mo
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\伟\AppData\Roaming\npm\node_modules\cnpm\node_modules\pangyp\lib\build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\Users\伟\AppData\Roaming\npm\node_modules\cnpm\node_modules\pangyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd Q:\test_fis3_c\kf5\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0
socket.io@1.3.6 node_modules\socket.io
├── debug@2.1.0 (ms@0.6.2)
├── has-binary-data@0.1.3 (isarray@0.0.1)
├── socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, benchmark@1.0.0, json3@3.2.6)
├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2, socket.io-parser@2.2.2)
├── engine.io@1.5.2 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.2.1, ws@0.7.2)
└── socket.io-client@1.3.6 (to-array@0.1.3, indexof@0.0.1, component-bind@1.0.0, debug@0.7.4, backo2@1.0.2, object-component@0.0.3, component-emitter@1.1.2, has-binary@0.1.6, parseuri@0.0.2, engine.io-client@1.5.2)

**Comment by aireol** [comment]
Could you check what version of python you are using? Thanks!

**Comment by aireol** [comment]
I think this has something to do with the `gyp` module not being able to rebuild a the node module it is trying to rebuild. Sometimes it is just the python version (the recommended is python v2.7).

You can read more about it in (here)[https://www.npmjs.com/package/node-gyp#installation].

**Comment by guyuewei** [comment]
Q:\test_fis3_c\kf5>python
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by zhuqiao** [comment]
Solved?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
