### ISSUE TITLE
How can I implement userlist

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io#2216]
Hi, using the demo chat example, what's the best approach to add a userlist to the right?

**Comment by Swinkid** [comment]
You'd want to ask the user to choose a username when they load the page, when set it sends it to the server then the server emits it to all the connected clients. Each client has an array of some sort to keep track of connected clients then on disconnect emit that x client has disconnected.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
