### ISSUE TITLE
Win Xp IE8 Socket 1.X Not Working!

### ISSUE THREAD

**Issue by man9565** [socketio/socket.io#2224]
Win Xp IE8 Socket 1.X Not Working!

![20150905_222708](https://cloud.githubusercontent.com/assets/10486692/9699423/490921c0-541d-11e5-9c2b-68daabef1f34.png)

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
