### ISSUE TITLE
Callback ack when broadcast message

### ISSUE THREAD

**Issue by whifflevcq** [socketio/socket.io#2226]
When I use broadcast to send message, have a alot of clients does not see message. If I send message to 1 client, I will use callback ack, but socket.io don't support callback when broadcast.
How to know a client does not see message when use broadcast to send message?

Example:
io.to(room).emit('message','hello',function(ping){
//socket.io do not support callback!!!
})

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
