### ISSUE TITLE
Node 4.0 - Segmentation fault: 11

### ISSUE THREAD

**Issue by chadcampbell** [socketio/socket.io#2227]
Hello,

I just updated to Node 4.0. That upgrade breaks my server. I isolated the problem down to these to lines in my main module:

```
var server = require('http').createServer(app);
var sockets = require('socket.io')(server);
```

The second line is what causes the segmentation fault. The first line is included for reference.

**Comment by Mad-Head** [comment]
Hello. Can you show a stack error or problem file?

**Comment by chadcampbell** [comment]
@Mad-Head - Thank you for your response. I was able to fix the error by doing the following:

1. Deleting the "node_modules" directory in the app.
2. Re-running `npm install`.

Once I did that, the server correctly started again.

**Comment by vrunoa** [comment]
:+1:
