### ISSUE TITLE
http://socket.io/get-started/chat/ - clarification needed

### ISSUE THREAD

**Issue by wizofaus** [socketio/socket.io#2229]
I stumbled with the directions on http://socket.io/get-started/chat/ as I missed reading a single /: it says to add the &lt;script> tag before the &lt;/body> but I just read this as adding it before &lt;body> (assuming they meant inside the &lt;head> tag), but while the next few steps work, once you're asked to add the script that attaches the 'submit' event to the form, it no longer works, with no errors or anything to indicate what's wrong. It's probably worth a note to make sure others don't make the same mistake!

**Comment by Benuuu** [comment]
:+1: I made the same mistake, but instead solved it by waiting for the document to be ready.

**Comment by Mad-Head** [comment]
document.addEventListener('load', function() {
    // your logic here...
})

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
