### ISSUE TITLE
Array within object is not emit to browser as Array (fails `instanceof Array`)

### ISSUE THREAD

**Issue by unional** [socketio/socket.io#2234]
This is a long trace from `systemjs` to `karma-systemjs` to `karma` and now to `socket.io`.  According to https://github.com/karma-runner/karma/issues/1578 on `karma`, the issue might come from `socket.io` so I want to bring it up here to your attention.

The issue starts from `systemjs` fail to run on `karma` under certain circumstances. After I trace it down, it comes down to the following:

When `karma-systemjs` reads the `config.js` for `systemjs`, it places the config as an object under `config.client.systemjs`, which, is emit and available on browser after `karma` starts.

Within that config object, it has a section like this:

```
meta: {
  "*": {
    deps: ['jquery', 'moduleB', ...]
  }
}
```

However, on the browser (inside `adapter.js` from `karma-systemjs`):

```
console.log(
  karma.config.systemjs.config.meta['*'].deps,
  karma.config.systemjs.config.meta['*'].deps instanceof Array);
```

produces:

```
LOG: ['jquery', 'moduleB', ...], false
```

`instanceof Array` returns false.

Here are all related issues on each repo:
https://github.com/karma-runner/karma/issues/1578
https://github.com/rolaveric/karma-systemjs/issues/44
https://github.com/systemjs/systemjs/issues/769

**Comment by nkzawa** [comment]
Sorry, could you specify the problem? I'd like to know what kind of problem socket.io actually has.
Do you mean the following doesn't work?

```js
// server
socket.emit('an event', { foo: ['bar'] });

// client
socket.on('an event', function(data) {
  assert(data.foo instanceof Array)?
});
```

And I'd like to make sure that it's not the same issue with `instanceof Array` doesn't work across frames.

http://stackoverflow.com/questions/22289727/difference-between-using-array-isarray-and-instanceof-array

**Comment by unional** [comment]
@nkzawa , seems like it is not iframe issue.

I don't know the exact usage on `karma` that sends the plugin config to the client, but likely is something similar to what you describe.

**Comment by oniono** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

oniono@naver.com 님께 보내신 메일 <Re: [socket.io] Array within object is not emit to browser as Array (fails `instanceof Array`) (#2234)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by unional** [comment]
Per https://github.com/karma-runner/karma/issues/1578#issuecomment-172803831

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
