### ISSUE TITLE
Crash on node.js 4.0 / socket.io 1.3.6 (unexpected disconnect?)

### ISSUE THREAD

**Issue by chisleu** [socketio/socket.io#2236]
Today I got socket.io going great for a simple chat setup. However, if I refresh the screen rapidly, it crashes my node instance. Here is the error:

```
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at ServerResponse.resOnFinish (_http_server.js:473:7)
    at emitNone (events.js:67:13)
    at ServerResponse.emit (events.js:166:7)
    at finish (_http_outgoing.js:526:10)
    at doNTCallback0 (node.js:407:9)
    at process._tickDomainCallback (node.js:377:13)
```

Google has been unhelpful. I'm hoping someone else solved this.

Unfortunately, I also upgraded to node 4.0 today because I am a huge fan of => functions.

It could be related to that, although it only happens when I have the socket.io code loaded. The code I'm using is very simple:

```
var server = http.createServer(app);
var io = require('socket.io')(server);
io.on('connection', function (socket) {
    socket.emit('juxtami.com', { hello: 'world' });
};
server.listen(8888);
```

I'm using express.js 4.13 and followed the information from the website.

I want to stress that it works fine unless I force disconnects by refreshing the client page (causing the JS to disconnect abruptly, I'm guessing.)

I found several comments about similar issues in earlier versions of node. It seems there was a bug fix that kept disconnects from throwing an error, but maybe there was reversion? Or maybe it is just similar?

**Comment by chisleu** [comment]
Update: doesn't seem to break on 0.12.7 so I guess I'll revert. It's a shame because I wrote a good bit of code with arrow functions.

**Comment by lepture** [comment]
Please don't pin your dependencies. Use `^`, `~` etc.

**Comment by ChALkeR** [comment]
@chisleu, did you rebuild all dependencies (including socket.io) after an Node.js upgrade? Native addons compiled for 0.12 won't work with 4.0.0 until you rebuild them.

Atm, when you will try to build socket.io with 4.0.0, you will experience this bug: https://github.com/socketio/socket.io/issues/2228.

**Comment by chisleu** [comment]
I deleted node_modules and did ```npm install```. 
I didn't notice that output. I did find that it worked until I refreshed the browser over and over.

**Comment by kestuxg** [comment]
Same for me. 0.12 was fine just after upgrade to node 4 I started to see these errors.
On separate box I did fresh install of node and all depending modules - same thing.

**Comment by kleinph** [comment]
I can confirm this with node 4.0 and socket.io 1.3.6 on Linux. I also did a clean install of the node modules (deleted node_modules and did a `npm install`).

I also got the same stacktrace:
````
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at ServerResponse.resOnFinish (_http_server.js:473:7)
    at emitNone (events.js:67:13)
    at ServerResponse.emit (events.js:166:7)
    at finish (_http_outgoing.js:526:10)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
````

**Comment by vandernorth** [comment]
@chisleu why dont you use the --harmony flag in node 0.12 to use your arrow functions?

I've got the same error on node 4.1, after removing and reinstalling with npm install the issue still exists but happens later. At first I only needed 2 refreshes of the page, now it takes me about 20 refreshes.

**Comment by chisleu** [comment]
@vandernorth The scope in 0.12's arrow functions isn't lexical. That is the only reason I'm using them. They can keep my prototype function code more simple, if I don't have to set the class' this to something else.

**Comment by pertinax** [comment]
Segmentation fault (core dumped), 
ubuntu 14.04, 
node 4.0.0, 
socket.io 1.3.5

**Comment by laggingreflex** [comment]
[1.3.7 is out](https://github.com/socketio/socket.io/issues/2242#issuecomment-141877333). I think it solves this?

**Comment by youth7** [comment]
same to me , but it happen more frequently while the client is IOS. it  rarely happen on Android

**Comment by chisleu** [comment]
I upgraded to socket.io 1.3.7 and node 4.1.

It now builds without errors and doesn't seem to crash like it did before!!

:+1:

**Comment by pertinax** [comment]
Yep, 1.3.7 is okay

**Comment by vandernorth** [comment]
I've upgraded to 1.3.7 with node 4.1 but after refreshing 4 pages at the same time I still seem to get this error. I'm testing on windows this time, not sure if that makes any difference. I did not see any error in the build/install process.

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at ServerResponse.resOnFinish (_http_server.js:473:7)
    at emitNone (events.js:67:13)
    at ServerResponse.emit (events.js:166:7)
    at finish (_http_outgoing.js:526:10)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)

**Comment by laggingreflex** [comment]
Have you tried deleting all node_modules and doing a fresh install?

**Comment by vandernorth** [comment]
@laggingreflex Yes I did, but I can no longer trace my current issue back to socket.io.
What I'm experiencing now looks more like https://github.com/nodejs/node/issues/2639 
Ill start searching from there, thanks anyway!

**Comment by chisleu** [comment]
Closing as it no longer appears linked to just socket.io

```
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at ServerResponse.resOnFinish (_http_server.js:473:7)
    at emitNone (events.js:67:13)
    at ServerResponse.emit (events.js:166:7)
    at finish (_http_outgoing.js:526:10)
    at doNTCallback0 (node.js:407:9)
    at process._tickDomainCallback (node.js:377:13)
```

**Comment by laggingreflex** [comment]
I actually experienced this again today. It's happened only once so far, whereas before 1.3.7 it was happening on every other socket disconnect.

**Comment by valdorvaldor** [comment]
it happens to me, But I only use express...

**Comment by kazimiras** [comment]
At the same error i updated express to 4.13.3, and it works fine for me
