### ISSUE TITLE
Missing Forward-slash in socket.io URI Request Causes Connection Failure

### ISSUE THREAD

**Issue by kestrelhawk** [socketio/socket.io#2237]
Sometimes, when I connect to a specific page that's performing the above client request, I see a number of `404 Not Found` errors precede by a `301 Moved Permanently` error, and after a random number of attempts (from one to four) as follows: 

    GET http://domain.com/socket.io?EIO=3&transport=polling&t=1441727903280-0 404 (Not Found)
    GET http://domain.com/socket.io?EIO=3&transport=polling&t=1441727905168-1 404 (Not Found)
    Client connected...

The first request I see shows the following information: 

    Request URL:http://domain.com/socket.io/?EIO=3&transport=polling&t=1441728010300-0
    Request Method:GET
    Status Code:301 Moved Permanently

The proceeding requests fail with `404 Not Found` until a success occurs: 

    Request URL:http://domain.com/socket.io/?EIO=3&transport=polling&t=1441728015410-2
    Request Method:GET
    Status Code:200 OK

What's strange here is that the URI specified in the network logs for any failed requests appear as follows: 

**Failed**

    http://domain.com/socket.io?EIO=3&transport=polling

**Success**

    http://domain.com/socket.io/?EIO=3&transport=polling

As you can see, it appears that the client is first attempting to connect to the URI without a trailing forward-slash; however, any concurrent successful connections contain the forward-slash. 

This issue occurs at random, where sometimes it works successfully, most times it fails. It is working on my development environment successfully without issue. 

I've thinned down the issue to a point where I have a simple NodeJS server which a client can connect through with socket.io, as follows: 

**Client**

    <script type="text/javascript">
    $(document).ready(function() {
         // open a socket connection
        var socket = io();
        
        socket.on('connect', function (user) {
            console.log('Client connected...');
        });
    });
    </script>

**Server**

    var server = require('http').createServer();
    var io = require('socket.io')(server);
    var redis = require('redis');
    
    server.listen(8083);
    
    io.on('connection', function (socket) {
      console.log('Client connected successfully...');
      
      // Error reporting
      socket.on('error', function (err) {
        console.log("Socket.IO Error");
        console.log(err.stack);
      });
    
      socket.on('disconnect', function() {
        // redisClient.quit();
        console.log('Client disconnected...');
      });
    });

*Note: I'm currently using `haproxy` which routes requests internally from port 80 to 8081 (HTTP) and 8083 (NodeJS).*

I've tried a lot of steps so far, so any feedback would be greatly appreciated.

**Comment by kestrelhawk** [comment]
Here's a copy of the client-side debug logs: 

    socket.io-client:url parse http://domain.com +0ms
    socket.io.js:1402 socket.io-client new io instance for http://domain.com +0ms
    socket.io.js:1402 socket.io-client:manager readyState closed +0ms
    socket.io.js:1402 socket.io-client:manager opening http://domain.com +1ms
    socket.io.js:3715 engine.io-client:socket creating transport "polling" +0ms
    socket.io.js:3715 engine.io-client:polling polling +1ms
    socket.io.js:3715 engine.io-client:polling-xhr xhr poll +1ms
    socket.io.js:3715 engine.io-client:polling-xhr xhr open GET: http://domain.com/socket.io/?EIO=3&transport=polling&t=1441887162366-0 +0ms
    socket.io.js:3715 engine.io-client:polling-xhr xhr data null +1ms
    socket.io.js:3715 engine.io-client:socket setting transport polling +1ms
    socket.io.js:1402 socket.io-client:manager connect attempt will timeout after 20000 +4ms
    socket.io.js:1402 socket.io-client:manager readyState opening +1ms
    socket.io.js:2919 GET http://domain.com/socket.io?EIO=3&transport=polling&t=1441887162366-0 404 (Not Found)17.Request.create @ socket.io.js:2919Request     @ socket.io.js:284217.XHR.request @ socket.io.js:277317.XHR.doPoll @ socket.io.js:280318.Polling.poll @ socket.io.js:319218.Polling.doOpen @ socket.io.    js:313614.Transport.open @ socket.io.js:231313.Socket.open @ socket.io.js:1743Socket @ socket.io.js:1625Socket @ socket.io.js:15603.Manager.open.Manager.    connect @ socket.io.js:299Manager @ socket.io.js:157Manager @ socket.io.js:127lookup @ socket.io.js:60(anonymous function) @ tests1:114n.Callbacks.j @     jquery.js:3073n.Callbacks.k.fireWith @ jquery.js:3185n.extend.ready @ jquery.js:3391I @ jquery.js:3407
    socket.io.js:3715 engine.io-client:socket socket error {"type":"TransportError","description":404} +418ms
    socket.io.js:1402 socket.io-client:manager connect_error +418ms
    socket.io.js:1402 socket.io-client:manager will wait 671ms before reconnect attempt +0ms
    socket.io.js:3715 engine.io-client:socket socket close with reason: "transport error" +1ms
    socket.io.js:3715 engine.io-client:polling transport not open - deferring close +1ms
    socket.io.js:1402 socket.io-client:manager attempting reconnect +673ms
    socket.io.js:1402 socket.io-client:manager readyState closed +0ms
    socket.io.js:1402 socket.io-client:manager opening http://domain.com +0ms
    socket.io.js:3715 engine.io-client:socket creating transport "polling" +673ms
    socket.io.js:3715 engine.io-client:polling polling +0ms
    socket.io.js:3715 engine.io-client:polling-xhr xhr poll +1ms
    socket.io.js:3715 engine.io-client:polling-xhr xhr open GET: http://domain.com/socket.io/?EIO=3&transport=polling&t=1441887163462-1 +0ms
    socket.io.js:3715 engine.io-client:polling-xhr xhr data null +0ms
    socket.io.js:3715 engine.io-client:socket setting transport polling +1ms
    socket.io.js:1402 socket.io-client:manager connect attempt will timeout after 20000 +4ms
    socket.io.js:2919 GET http://domain.com/socket.io?EIO=3&transport=polling&t=1441887163462-1 404 (Not Found)17.Request.create @ socket.io.js:2919Request     @ socket.io.js:284217.XHR.request @ socket.io.js:277317.XHR.doPoll @ socket.io.js:280318.Polling.poll @ socket.io.js:319218.Polling.doOpen @ socket.io.    js:313614.Transport.open @ socket.io.js:231313.Socket.open @ socket.io.js:1743Socket @ socket.io.js:1625Socket @ socket.io.js:15603.Manager.open.Manager.    connect @ socket.io.js:299(anonymous function) @ socket.io.js:564
    socket.io.js:3715 engine.io-client:socket socket error {"type":"TransportError","description":404} +533ms
    socket.io.js:1402 socket.io-client:manager connect_error +532ms
    socket.io.js:1402 socket.io-client:manager reconnect attempt error +0ms
    socket.io.js:1402 socket.io-client:manager will wait 1592ms before reconnect attempt +0ms
    socket.io.js:3715 engine.io-client:socket socket close with reason: "transport error" +1ms
    socket.io.js:3715 engine.io-client:polling transport not open - deferring close +0ms
    socket.io.js:1402 socket.io-client:manager attempting reconnect +1s
    socket.io.js:1402 socket.io-client:manager readyState closed +0ms
    socket.io.js:1402 socket.io-client:manager opening http://domain.com +0ms
    socket.io.js:3715 engine.io-client:socket creating transport "polling" +2s
    socket.io.js:3715 engine.io-client:polling polling +0ms
    socket.io.js:3715 engine.io-client:polling-xhr xhr poll +0ms
    socket.io.js:3715 engine.io-client:polling-xhr xhr open GET: http://domain.com/socket.io/?EIO=3&transport=polling&t=1441887165592-2 +1ms
    socket.io.js:3715 engine.io-client:polling-xhr xhr data null +0ms
    socket.io.js:3715 engine.io-client:socket setting transport polling +1ms
    socket.io.js:1402 socket.io-client:manager connect attempt will timeout after 20000 +3ms
    socket.io.js:2919 GET http://domain.com/socket.io?EIO=3&transport=polling&t=1441887165592-2 404 (Not Found)17.Request.create @ socket.io.js:2919Request     @ socket.io.js:284217.XHR.request @ socket.io.js:277317.XHR.doPoll @ socket.io.js:280318.Polling.poll @ socket.io.js:319218.Polling.doOpen @ socket.io.    js:313614.Transport.open @ socket.io.js:231313.Socket.open @ socket.io.js:1743Socket @ socket.io.js:1625Socket @ socket.io.js:15603.Manager.open.Manager.    connect @ socket.io.js:299(anonymous function) @ socket.io.js:564
    socket.io.js:3715 engine.io-client:socket socket error {"type":"TransportError","description":404} +539ms
    socket.io.js:1402 socket.io-client:manager connect_error +539ms
    socket.io.js:1402 socket.io-client:manager reconnect attempt error +1ms
    socket.io.js:1402 socket.io-client:manager will wait 3422ms before reconnect attempt +0ms
    socket.io.js:3715 engine.io-client:socket socket close with reason: "transport error" +1ms
    socket.io.js:3715 engine.io-client:polling transport not open - deferring close +0ms
    socket.io.js:1402 socket.io-client:manager attempting reconnect +3s
    socket.io.js:1402 socket.io-client:manager readyState closed +2ms
    socket.io.js:1402 socket.io-client:manager opening http://domain.com +0ms
    socket.io.js:3715 engine.io-client:socket creating transport "polling" +3s
    socket.io.js:3715 engine.io-client:polling polling +0ms
    socket.io.js:3715 engine.io-client:polling-xhr xhr poll +0ms
    socket.io.js:3715 engine.io-client:polling-xhr xhr open GET: http://domain.com/socket.io/?EIO=3&transport=polling&t=1441887169559-3 +1ms
    socket.io.js:3715 engine.io-client:polling-xhr xhr data null +0ms
    socket.io.js:3715 engine.io-client:socket setting transport polling +1ms
    socket.io.js:1402 socket.io-client:manager connect attempt will timeout after 20000 +2ms
    socket.io.js:3715 engine.io-client:polling polling got data ArrayBuffer +452ms
    socket.io.js:3715 engine.io-client:socket socket receive: type "open", data "{"sid":"jvPzwsEhkqqGnhLeAAAB","upgrades":["websocket"]    ,"pingInterval":25000,"pingTimeout":60000}" +2ms
    socket.io.js:3715 engine.io-client:socket socket open +1ms
    socket.io.js:1402 socket.io-client:manager open +455ms
    socket.io.js:1402 socket.io-client:socket transport is open - connecting +0ms
    socket.io.js:1402 socket.io-client:manager reconnect success +1ms
    socket.io.js:3715 engine.io-client:socket starting upgrade probes +1ms
    socket.io.js:3715 engine.io-client:socket probing transport "websocket" +0ms
    socket.io.js:3715 engine.io-client:socket creating transport "websocket" +0ms
    socket.io.js:3715 engine.io-client:polling polling +1ms
    socket.io.js:3715 engine.io-client:polling-xhr xhr poll +1ms
    socket.io.js:3715 engine.io-client:polling-xhr xhr open GET: http://domain.com/socket.io/?EIO=3&transport=polling&t=1441887170018-    4&sid=jvPzwsEhkqqGnhLeAAAB +0ms
    socket.io.js:3715 engine.io-client:polling-xhr xhr data null +0ms
    socket.io.js:3715 engine.io-client:polling polling got data ArrayBuffer +164ms
    socket.io.js:3715 engine.io-client:socket socket receive: type "message", data "0" +1ms
    socket.io.js:1402 socket.io-parser decoded 0 as %j +0ms Object {type: 0, nsp: "/"}
    tests1:118 Client connected...
    socket.io.js:3715 engine.io-client:polling polling +2ms
    socket.io.js:3715 engine.io-client:polling-xhr xhr poll +0ms
    socket.io.js:3715 engine.io-client:polling-xhr xhr open GET: http://domain.com/socket.io/?EIO=3&transport=polling&t=1441887170185-    5&sid=jvPzwsEhkqqGnhLeAAAB +0ms
    socket.io.js:3715 engine.io-client:polling-xhr xhr data null +0ms
    socket.io.js:3715 engine.io-client:socket probe transport "websocket" opened +185ms
    socket.io.js:3715 engine.io-client:socket probe transport "websocket" pong +182ms
    socket.io.js:3715 engine.io-client:socket pausing current transport "polling" +0ms
    socket.io.js:3715 engine.io-client:polling we are currently polling - waiting to pause +0ms
    socket.io.js:3715 engine.io-client:polling polling got data ArrayBuffer +112ms
    socket.io.js:3715 engine.io-client:socket socket receive: type "noop", data "undefined" +1ms
    socket.io.js:3715 engine.io-client:polling pre-pause polling complete +0ms
    socket.io.js:3715 engine.io-client:polling paused +1ms
    socket.io.js:3715 engine.io-client:socket changing transport and sending upgrade packet +0ms
    socket.io.js:3715 engine.io-client:socket setting transport websocket +0ms
    socket.io.js:3715 engine.io-client:socket clearing existing transport polling +0ms
    socket.io.js:3715 engine.io-client:polling ignoring poll - transport state "paused" +1ms
    socket.io.js:3715 engine.io-client:socket writing ping packet - expecting pong within 60000ms +24s
    socket.io.js:3715 engine.io-client:socket flushing 1 packets in socket +1ms
    socket.io.js:3715 engine.io-client:socket socket receive: type "pong", data "undefined" +198ms
    socket.io.js:3715 engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
    socket.io.js:3715 engine.io-client:socket flushing 1 packets in socket +1ms
    socket.io.js:3715 engine.io-client:socket socket receive: type "pong", data "undefined" +222ms

**Comment by kestrelhawk** [comment]
**Resolved**
I attempted to connect to the IP address directly (which I thought I had previously done whilst hosted on a different web server) and found that client connects with the server immediately on the first attempt. I've therefore determined the root cause as being a redirect in my `.htaccess` file, where the naked domain is redirected to the 'www' CNAME which ultimately causes the `301 Moved Permanently` errors.

**Comment by yashmakavana** [comment]
i am also getting the same error.

**Comment by CodeWith-HAMZA** [comment]
const express = require("express");
const http = require("http");
const socketIo = require("socket.io");
const cors = require("cors");
const app = express();
const server = http.createServer(app);

const io = new socketIo.Server(server, { cors: { origin: "*" } });

const PORT = 5000;

const users = ["hamza", "suffiyan", "aisha"];

io.on("connection", (socket) => {
  console.log("User connected:", socket.id);

  socket.on("join", (username) => {
    if (users.includes(username)) {
      socket.join(username);
      console.log(`${username} joined`);
    } else {
      socket.emit("invalidUser");
    }
  });

  socket.on("chat", (data) => {
    const { from, to, message } = data;
    io.to(to).emit("chat", { from, message });
  });

  socket.on("disconnect", () => {
    console.log("User disconnected:", socket.id);
  });
});

server.listen(5000, () => {
  console.log(`Server is running on port ${PORT}`);
});


one solution is, listen the server with http-server not "app.listen" but after even changing this thing, didn't fix even, what should i do, if anyone knows please do tell me!
