### ISSUE TITLE
Does socket.io support sub (custom) protocols?

### ISSUE THREAD

**Issue by lightningtgc** [socketio/socket.io#2240]
```js
var exampleSocket = new WebSocket("ws://www.example.com/socketserver", ["protocolOne", "protocolTwo"]);
```

I want to use the custom protocols like `protocolOne` and `protocolTwo`.

How can I implement in soket,io?

Thank you!

**Comment by nkzawa** [comment]
Unfortunately, we don't support custom protocol.
