### ISSUE TITLE
Bump engine.io

### ISSUE THREAD

**Issue by marcelaraujo** [socketio/socket.io#2242]
Please, bump Engine.io package up to 1.5.3.

The version 1.5.2 breaks on Node 4.0.0.

**Comment by radum** [comment]
+1

**Comment by torvalamo** [comment]
See https://github.com/socketio/socket.io/issues/2245 for a temporary fix for Node 4

**Comment by marcelaraujo** [comment]
@torvalamo Thanks

**Comment by radum** [comment]
This doesn't solve anything if socket.io is a dependency.

**Comment by torvalamo** [comment]
No, for that to be fixed they have to push it npm. Not sure why they haven't.

**Comment by nuclearace** [comment]
@rauchg Can we get an update to npm with the node 4.0.0 fix?

**Comment by maxwerr** [comment]
+1 here too... sufficient for direct dependency on socket.io, but not if through another project (or multiple). Would love to see an npm update.

**Comment by davispuh** [comment]
`npm install socket.io` fails to install with Node 4.0 because specified `bufferutil` doesn't compile for it.

**Comment by lirantal** [comment]
+1

**Comment by douglasduteil** [comment]
+1

**Comment by rauchg** [comment]
1.3.7 is out!
