### ISSUE TITLE
rooms property doesn't return the actual rooms that socket is joined to, please update it to _rooms

### ISSUE THREAD

**Issue by kataras** [socketio/socket.io#2244]
I had project written in javascript, I re-write it in typescript and I was testing it and didn't working, after some hours I see that the definition file doesn't have the _rooms property I used on javascript version of my project, the .rooms didn't working...

https://github.com/nodets/socket.io.users/blob/master/src/lib/User.ts#L141

**Comment by darrachequesne** [comment]
Hi! Please correct me if I'm wrong, but shouldn't you open an issue/pull-request over there https://github.com/borisyankov/DefinitelyTyped instead?

Apart from that, from what I understand of the code [here](https://github.com/socketio/socket.io/blob/master/lib/socket.js), `this.rooms` do actually represent the rooms the socket is in:
```
/**
 * Joins a room.
 *
 * @param {String} room
 * @param {Function} optional, callback
 * @return {Socket} self
 * @api private
 */

Socket.prototype.join = function(room, fn){
  debug('joining room %s', room);
  var self = this;
  if (~this.rooms.indexOf(room)) return this;
  this.adapter.add(this.id, room, function(err){
    if (err) return fn && fn(err);
    debug('joined room %s', room);
    self.rooms.push(room);
    fn && fn(null);
  });
  return this;
};
```
Or have I misunderstood?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
