### ISSUE TITLE
update engine.io version to 1.5.4

### ISSUE THREAD

**Issue by vsharmaGit** [socketio/socket.io#2245]
engine.io-client has resolved a dependency which was retrieving xmlhttprequest from Github. socket.io 1.3.6 relies on engine.io version 1.5.2. please update engine.io version

**Comment by nicofff** [comment]
+1

**Comment by torvalamo** [comment]
It is updated on github, so if you do

    npm install git+https://github.com/socketio/socket.io

you've got it.

However there is one bug, which is that engine.io complains that module `base64id` isn't found. So you need to 

    npm install base64id

separately, and you're good to go. At least I haven't seen anything bad yet apart from that.

**Comment by vsharmaGit** [comment]
unfortunately, we don't have GIT installed in our build environment as well this doesn't solve our issue since socket.io is a dependency for browser-sync and karma.

**Comment by maxwerr** [comment]
+1 if you have a direct dependency on socket.io this is enough, but for everyone else, it means forking your _real_ dependenc(ies) and bumping the socket.io reference... I'd love to see a patch release resolving this.

**Comment by bountyx** [comment]
Very annoying, one way around it that I found was a manageable workaround (regarding maxwerr's point) was to use npm's built-in shrinkwrap command (https://docs.npmjs.com/cli/shrinkwrap). This allows you to bump the version number in your dependant packages without having to fork them. Finally, was able to resolve the issue this way.

**Comment by maxwerr** [comment]
@bountyx that's really smart. great workaround until this passes tests and gets released..

**Comment by jldec** [comment]
appears to be fixed in socket.io v1.3.7

**Comment by mikermcneil** [comment]
@jldec :+1:  @rauchg [published yesterday](https://www.npmjs.com/package/socket.io)

@vsharmaGit I imagine this can be closed :)

**Comment by vsharmaGit** [comment]
Awesome...thanks for the update
