### ISSUE TITLE
[meta] More contributors?

### ISSUE THREAD

**Issue by SEAPUNK** [socketio/socket.io#2252]
Understandably, some of you package owners/main contributors are very busy people, but it gets frustrating for the end user/possible contributor when issues aren't really being looked at and pull requests aren't being reviewed, especially for a popular package.

How about adding some contributors to the repository, so they can work on this repo as well? If yes, are there any prerequisites for becoming one? If no, why not?

**Comment by fourpixels** [comment]
+1

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
