### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by nkt** [socketio/socket.io#2254]
Please publish new release of socket.io due node 4.0 support

**Comment by deployable** [comment]
fyi `nan` has issues in 4.x which `ws` has an optionalDependency on  https://github.com/websockets/bufferutil and https://github.com/websockets/utf-8-validate 

See:
https://github.com/brianmcd/contextify/issues/180 
https://github.com/brianmcd/contextify/pull/181

**Comment by mikermcneil** [comment]
@nkt see https://github.com/socketio/socket.io/issues/2245
