### ISSUE TITLE
Remove event listener attached with io.on

### ISSUE THREAD

**Issue by NoNameProvided** [socketio/socket.io#2257]
``` javascript
let app   = require('http').createServer();
let io      = require('socket.io')(app);

let listener = io.on('connection', callback);

io.removeListener('connection', listener);
```

The code above doesn't work, how can I remove that event listener? Socket.io should not implement the removeListerner method on the base object?

**Comment by Nibbler999** [comment]
Try `io.sockets.removeListener('connection', callback);`

**Comment by torvalamo** [comment]
isn't it `sockets.removeEventListener`?

**Comment by studentIvan** [comment]
So what is correct way to do it?

**Comment by Bogdaan** [comment]
Unfortunately removeListener not works (

**Comment by runn1ng** [comment]
Is there some documentation how to do removing listeners correctly?

**Comment by erperejildo** [comment]
Did you find something @runn1ng ?

**Comment by studentIvan** [comment]
@erperejildo you can use something like this way:
```javascript
// $messenger is socket.io instance
tab.unload = function () {
        if (tab.__events.smbdStopTyping) { 
          $messenger.removeListener('somebody_stop_typing_in_a_deal', tab.__events.smbdStopTyping) 
        }
      };
tab.__events = {};
tab.__events.smbdStopTyping = function (chat, uid) {
        // your callback function here
      };
$messenger.on('somebody_stop_typing_in_a_deal', tab.__events.smbdStopTyping);
```

**Comment by erperejildo** [comment]
Perfect @studentIvan thank you

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
