### ISSUE TITLE
Installation issues (Windows 10)

### ISSUE THREAD

**Issue by DomDale** [socketio/socket.io#2259]
For the last hour or so I have been trying to install socket.io on my Windows 10 PC. I have Python 2.7.10, Visual studio express installed. Keep getting this error but not good at this sorta thing so I cant figure out why. Hope you can help :)

[Error](http://pastebin.com/BmrcQbyN)

**Comment by Saturate** [comment]
I get the same thing. Tried almost everything now, but without any luck.

**Comment by nkzawa** [comment]
These errors are for optional dependencies, so anyway socket.io would work without any problems.

**Comment by fourpixels** [comment]
Socket.IO works even with those errors, but frankly I don't find that pretty nice way to install a package - who knows when things will stop working! +1 from me

**Comment by nkzawa** [comment]
This wouldn't happen on the latest version.
