### ISSUE TITLE
Can debug console time use local time?

### ISSUE THREAD

**Issue by fangrui625** [socketio/socket.io#2260]
Hi, when I using socket.io v1.3.6 debug mode,
I found console log time format is UTC, not local time.
Is any settings can change debug time format?
Or can I using some way to change time format?

```bash
Fri, 25 Sep 2015 02:05:11 GMT socket.io:server initializing namespace /
Fri, 25 Sep 2015 02:05:11 GMT socket.io:server initializing namespace /
Fri, 25 Sep 2015 02:05:11 GMT socket.io:server creating engine.io instance with opts {"path":"/socket.io"}
Fri, 25 Sep 2015 02:05:11 GMT socket.io:server creating engine.io instance with opts {"path":"/socket.io"}
Fri, 25 Sep 2015 02:05:11 GMT socket.io:server attaching client serving req handler
Fri, 25 Sep 2015 02:05:11 GMT socket.io:server attaching client serving req handler

**Comment by darrachequesne** [comment]
Hi @fangrui625 ! Socket.io rely on the following dependency for debugging (as you can see in [package.json](https://github.com/socketio/socket.io/blob/master/package.json)):
```
"dependencies": {
  [...]
  "debug": "2.1.3"
},
```
That is to say this [project](https://github.com/visionmedia/debug), which is using the method  ```new Date().toUTCString()``` to display the date in the logs (as you can see [here](https://github.com/visionmedia/debug/blob/master/node.js)). But I don't think it is currently possible to change this format (this [PR](https://github.com/visionmedia/debug/pull/128) suggests the change to local time with the method ```.toString()```, but has not been merged yet).

++

**Comment by fangrui625** [comment]
OK, I see, Thank you.
