### ISSUE TITLE
How to catch messages sent to closed sockets/rooms?

### ISSUE THREAD

**Issue by Especially** [socketio/socket.io#2261]
I'm using Rase's PHP socket emitter, the `emitter->to(room)->emit()` method, and I'm trying to create a notification system. My problem is that the node server doesn't receive the emission when there isn't a client in the room, looking at the debug console it seems that it'll simply package the message and that's it. How do I make it so that if there's no socket that it'll pass through an alternate channel?
Doing something like:
(!socket){
// Do something if socket doesn't exist
}

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
