### ISSUE TITLE
join and leave events

### ISSUE THREAD

**Issue by jacargentina** [socketio/socket.io#2266]
It seems those events where implemented, but now they dont exist.
They should exists so one is able to easily notify to connected sockets when other client enters/leaves the room.

**Comment by darrachequesne** [comment]
Hi @jacargentina ! I've found no occurence of those events in the code, do you know when they were implemented? Before version 1.0 maybe?

A quick implementation could be:
* https://github.com/socketio/socket.io-adapter/blob/master/index.js
```javascript
Adapter.prototype.add = function(id, room, fn){
  this.sids[id] = this.sids[id] || {};
  this.sids[id][room] = true;
  this.rooms[room] = this.rooms[room] || {};
  this.rooms[room][id] = true;
  + this.emit('event', 'roomJoined', id, room);
  if (fn) process.nextTick(fn.bind(null, null));
};
// same with Adapter.prototype.del and Adapter.prototype.delAll (event 'roomLeft')
```

* https://github.com/socketio/socket.io/blob/master/lib/namespace.js
```javascript
Namespace.prototype.initAdapter = function(){
  this.adapter = new (this.server.adapter())(this);
  + var self = this;
  + this.adapter.on('event', function(){
  +   emit.apply(self, arguments);
  + });
};
```

And then you could just do 
```
server.on('roomJoined', function (id, room) {
  console.log('Socket %s has joined room %s', id, room);
});
``` 
Would it suit your needs?

**Comment by jacargentina** [comment]
Yes, that should work!

**Comment by darrachequesne** [comment]
Anybody else has a thought on this? The thing is, the callbacks on `Socket#join` and `Socket#leave` allow one to catch when a client enters/leaves a room (to notify for example the other clients in the given room) but if a client disconnects, I don't think one is able to access to the rooms where the socket was just before:
```javascript
socket.on('disconnect', function(){
  console.log(this.rooms);
});
// always returns []
```
Am I missing another obvious solution? Else, the PR is ready!

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
