### ISSUE TITLE
gyp ERR! configure error - Phyton required? 

### ISSUE THREAD

**Issue by alvarotrigo** [socketio/socket.io#2272]
I'm getting many errors when following [the documentation provided in socket.io website](http://socket.io/docs/#how-to-use) and execute the following command:

> npm install socket.io

It seems its related with [node gyp](https://github.com/nodejs/node-gyp#installation) and its failing because I [haven't installed Phyton](https://github.com/npm/npm/issues/9563). 

There's nowhere in socket.io docs where the requiere of Phyton is specified. 
It seems to me that Phyton can be required to build it, but... isn't there any way to get socket.io without having to build anything?

Here's the result I'm getting:

> C:\inetpub\wwwroot\tlmNode>npm install --save socket.io
> 
> utf-8-validate@1.2.1 install C:\inetpub\wwwroot\tlmNode\node_modules\socket.io
> \node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild
> 
> C:\inetpub\wwwroot\tlmNode\node_modules\socket.io\node_modules\engine.io\node_mo
> dules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C
> :\Users\trigoa\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\....\node
> _modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
> HON env variable.
> gyp ERR! stack     at failNoPython (C:\Users\trigoa\AppData\Roaming\npm\node_mod
> ules\npm\node_modules\node-gyp\lib\configure.js:103:14)
> gyp ERR! stack     at C:\Users\trigoa\AppData\Roaming\npm\node_modules\npm\node_
> modules\node-gyp\lib\configure.js:64:11
> gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:82:15)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\trigoa\AppDa
> ta\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "
> rebuild"
> gyp ERR! cwd C:\inetpub\wwwroot\tlmNode\node_modules\socket.io\node_modules\engi
> ne.io\node_modules\ws\node_modules\utf-8-validate
> gyp ERR! node -v v4.1.2
> gyp ERR! node-gyp -v v1.0.3
> gyp ERR! not ok
> 
> bufferutil@1.2.1 install C:\inetpub\wwwroot\tlmNode\node_modules\socket.io\nod
> e_modules\engine.io\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild
> 
> C:\inetpub\wwwroot\tlmNode\node_modules\socket.io\node_modules\engine.io\node_mo
> dules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Us
> ers\trigoa\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\....\node_mod
> ules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
> HON env variable.
> gyp ERR! stack     at failNoPython (C:\Users\trigoa\AppData\Roaming\npm\node_mod
> ules\npm\node_modules\node-gyp\lib\configure.js:103:14)
> gyp ERR! stack     at C:\Users\trigoa\AppData\Roaming\npm\node_modules\npm\node_
> modules\node-gyp\lib\configure.js:64:11
> gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:82:15)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\trigoa\AppDa
> ta\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "
> rebuild"
> gyp ERR! cwd C:\inetpub\wwwroot\tlmNode\node_modules\socket.io\node_modules\engi
> ne.io\node_modules\ws\node_modules\bufferutil
> gyp ERR! node -v v4.1.2
> gyp ERR! node-gyp -v v1.0.3
> gyp ERR! not ok
> npm WARN optional dep failed, continuing utf-8-validate@1.2.1
> 
> utf-8-validate@1.2.1 install C:\inetpub\wwwroot\tlmNode\node_modules\socket.io
> \node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\nod
> e_modules\utf-8-validate
> node-gyp rebuild
> 
> C:\inetpub\wwwroot\tlmNode\node_modules\socket.io\node_modules\socket.io-client\
> node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate>if not
>  defined npm_config_node_gyp (node "C:\Users\trigoa\AppData\Roaming\npm\node_mod
> ules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
> )  else (rebuild)
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
> HON env variable.
> gyp ERR! stack     at failNoPython (C:\Users\trigoa\AppData\Roaming\npm\node_mod
> ules\npm\node_modules\node-gyp\lib\configure.js:103:14)
> gyp ERR! stack     at C:\Users\trigoa\AppData\Roaming\npm\node_modules\npm\node_
> modules\node-gyp\lib\configure.js:64:11
> gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:82:15)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\trigoa\AppDa
> ta\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "
> rebuild"
> gyp ERR! cwd C:\inetpub\wwwroot\tlmNode\node_modules\socket.io\node_modules\sock
> et.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-va
> lidate
> gyp ERR! node -v v4.1.2
> gyp ERR! node-gyp -v v1.0.3
> gyp ERR! not ok
> npm WARN optional dep failed, continuing bufferutil@1.2.1
> 
> bufferutil@1.2.1 install C:\inetpub\wwwroot\tlmNode\node_modules\socket.io\nod
> e_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_mo
> dules\bufferutil
> node-gyp rebuild
> 
> C:\inetpub\wwwroot\tlmNode\node_modules\socket.io\node_modules\socket.io-client\
> node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil>if not def
> ined npm_config_node_gyp (node "C:\Users\trigoa\AppData\Roaming\npm\node_modules
> \npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  e
> lse (rebuild)
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
> HON env variable.
> gyp ERR! stack     at failNoPython (C:\Users\trigoa\AppData\Roaming\npm\node_mod
> ules\npm\node_modules\node-gyp\lib\configure.js:103:14)
> gyp ERR! stack     at C:\Users\trigoa\AppData\Roaming\npm\node_modules\npm\node_
> modules\node-gyp\lib\configure.js:64:11
> gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:82:15)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\trigoa\AppDa
> ta\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "
> rebuild"
> gyp ERR! cwd C:\inetpub\wwwroot\tlmNode\node_modules\socket.io\node_modules\sock
> et.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferut
> il
> gyp ERR! node -v v4.1.2
> gyp ERR! node-gyp -v v1.0.3
> gyp ERR! not ok
> npm WARN optional dep failed, continuing utf-8-validate@1.2.1
> npm WARN optional dep failed, continuing bufferutil@1.2.1
> socket.io@1.3.7 node_modules\socket.io
> ├── debug@2.1.0 (ms@0.6.2)
> ├── has-binary-data@0.1.3 (isarray@0.0.1)
> ├── socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2,
>  benchmark@1.0.0, json3@3.2.6)
> ├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2, socket.io-parser@2.
> 2.2)
> ├── engine.io@1.5.4 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.2.2, ws@0.8
> .0)
> └── socket.io-client@1.3.7 (to-array@0.1.3, debug@0.7.4, indexof@0.0.1, componen
> t-bind@1.0.0, backo2@1.0.2, object-component@0.0.3, component-emitter@1.1.2, has
> -binary@0.1.6, parseuri@0.0.2, engine.io-client@1.5.4)
> 
> C:\inetpub\wwwroot\tlmNode>

**Comment by basarat** [comment]
Not that it works fine even despite this error.  [VorlonJS](http://www.vorlonjs.com/) homepage mentions this as well : 

![image](https://cloud.githubusercontent.com/assets/874898/11084235/019b313a-888d-11e5-947c-eeb9756a523f.png)


I searched for an issue to track it ... but this was the only one I could find. Hope we can get a fix :rose:

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
