### ISSUE TITLE
Typos in documentation under Rooms and Namespaces Section

### ISSUE THREAD

**Issue by tgreenidge** [socketio/socket.io#2274]
Please see below for typos found in the docs and my corrections with comments
1. Typo 1: Under subheading 'Custom namespaces'

``` javascript
var nsp = io.of('/my-namespace');
nsp.on('connection', function(socket){
   console.log('someone connected'); // ':' should be ';' at end of line 
});
nsp.emit('hi', 'everyone!');
```
1. Typo 2: Under subheading 'Joining and Leaving'

``` javascript
io.to('some room').emit('some event');  // ':' should be ';' at end of line
```

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
