### ISSUE TITLE
What happens to ack callbacks when they are never called?

### ISSUE THREAD

**Issue by abhi922** [socketio/socket.io#2275]
Hi,

I am using socket.io **node.js** client and my front end is an **android** device.

Due to frequent poor or no network access on mobile devices, I can emit an event and expect an ack, but the ack may never get called because the event was not received by the client.

So, what happens to that ack event, because it will resides in memory and if it is not garbage collected, it might lead to memory leakage.
When do these ack events become eligible for a **GC**?

**Comment by nkzawa** [comment]
Ack event will remain in socket if it was not called, but socket will be GCed when disconnected.

**Comment by abhi922** [comment]
Okay. Got it. Thanx for the reply.
