### ISSUE TITLE
How to secure 'io' cookie

### ISSUE THREAD

**Issue by dglozic** [socketio/socket.io#2276]
I noticed that socket.io (engine.io to be precise) is setting a non-secure session cookie called 'io' on the URL it is invoked. What is the role of this cookie, is it necessary and if so, can it be secured? We force https:// for all locations where socket.io is running, and could easily set this cookie to secure but I cannot find where.

**Comment by Nibbler999** [comment]
It's not used for anything; you can disable it by setting `cookie: false` in the server options.

**Comment by dglozic** [comment]
Best answer ever - thanks!

**Comment by dglozic** [comment]
Closing as resolved - thanks

**Comment by wisniewski94** [comment]
@Nibbler999 Where are these options? Where exactly do I put this setting?

**Comment by darrachequesne** [comment]
@wisniewski94 the options are documented here: https://github.com/socketio/engine.io#methods-1

```js
var io = require('socket.io')();
io.on('connection', function(client){});
io.listen(3000, {
  cookie: false
});
```

**Comment by wisniewski94** [comment]
@darrachequesne thank you very much! Without your help it would be still unclear to me how to use them. It would be good idea to add example to README.md.

**Comment by darrachequesne** [comment]
On a broader note, that cookie may be removed, if it's not used anywhere.

**Comment by tienlx93** [comment]
Hi @darrachequesne , 

Here is my current code.

`var server = http.createServer(app);
var socket = require('socket.io');
var io = socket().listen(server,
    {
        cookie: false
    });`

However, the server still send the cookie io.
Is there a problem of cookie when integrate io with express server?

Thanks.

**Comment by tienlx93** [comment]
One more thing, are there any method for sending the header `Access-Control-Allow-Origin` for web socket request (the `101 Switching Protocols` response)
I have set `io.origins(config.origin)` in init step, however, it only apply for XHR request.

The background is if there is a request that not setting correct Origin header is an vulnerable request, is this correct?

**Comment by darrachequesne** [comment]
@tienlx93 I'm not able to reproduce: https://github.com/darrachequesne/socket.io-fiddle/tree/issues-2276

> The background is if there is a request that not setting correct Origin header is an vulnerable request, is this correct?

The `Access-Control-Allow-Origin` header only applies for cross-domain requests ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Origin)). If you set the allowed origins with `io.origins()`, it should be ok.

**Comment by lkende** [comment]
Thanks for the info.  For reference, another way to set this cookie false:

`var io = require('socket.io')(server, { path:"/some/path", cookie: false });`

**Comment by jquinter** [comment]
> @darrachequesne In socket.io-2.0, is there a way to set this cookie secure and remove it from the query string.

can you please post how to do this in socket.io^2.0?

**Comment by dae721** [comment]
Recently noticed a warning in Chrome console regarding this cookie:
A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`.

In case it helps anyone who searches and ends up here, setting the option `cookie: false` as above seems to have solved the issue for me. I'm no longer getting the warning and the app is working fine without the cookie being set.

**Comment by GuilhermeCouto** [comment]
> Recently noticed a warning in Chrome console regarding this cookie:
> A cookie associated with a cross-site resource at (URL) was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`.
> 
> In case it helps anyone who searches and ends up here, setting the option `cookie: false` as above seems to have solved the issue for me. I'm no longer getting the warning and the app is working fine without the cookie being set.

It doesn't work for me. 

My code: 

```
http.listen(port, {cookie: false}, function(){
  console.log('listening on *:' + port);
});
```

What is wrong?

**Comment by dae721** [comment]
@GuilhermeCouto, I think you need to set the `{cookie: false}` option when initializing the _socket_, not http.listen. The solution provided above that worked for me is the one that uses express:

```
var server = require('http').createServer(express());
var io = require('socket.io')(server, { path:"/some/path", cookie: false });
```

Hope this helps

**Comment by GuilhermeCouto** [comment]
> @GuilhermeCouto, I think you need to set the `{cookie: false}` option when initializing the _socket_, not http.listen. The solution provided above that worked for me is the one that uses express:
> 
> ```
> var server = require('http').createServer(express());
> var io = require('socket.io')(server, { path:"/some/path", cookie: false });
> ```
> 
> Hope this helps

Thank you Doug for the reply. 
Just more one question?
What do I put in path? 
My system works like this: There is a local network that other pcs connect to the local server. 
The internal IP varies for each customer.

**Comment by dae721** [comment]
That snippet was from Ikende's answer above so I'm not entirely sure what the `path` option is referring to, but I don't think you need to specify it. If it helps, here are the relevant snippets of my code (I'm using typescript):

```
import * as express from 'express';
import { createServer, Server } from 'http';
import * as socketIo from 'socket.io';

this.app = express();
this.server = createServer(this.app);
this.io = socketIo(this.server, { cookie: false });
this.server.listen(this.port, () => {
            this.log('Running server on port ' + this.port);
        });
this.io.on('connect', (socket: SocketIO.Socket) => { bunch of code here }
```

**Comment by GuilhermeCouto** [comment]
> , { cookie: false }

It didn't work. =/

What version of socket.io are you using?

**Comment by dae721** [comment]
2.2.0. My memory is kind of fuzzy, but I think I needed to exit Chrome and start a new instance and/or manually remove the cookie via Chrome Dev Tools on the Application page to verify the fix.

**Comment by Kugelschieber** [comment]
Why does it even exist if it's not used?

**Comment by georgerappel** [comment]
For those using http and https servers, with the `io.attach` method, this worked for me:


    io.attach(httpServer, {cookie: false});
    io.attach(httpsServer, {cookie: false});

**Comment by CoDanny** [comment]
As opposed to what other people are saying here, this cookie is useful to provide stickiness in a system with multiple concurrent instances of a socket.io server as explained here in the Haproxy option: https://socket.io/docs/using-multiple-nodes/
