### ISSUE TITLE
Outdated tutorial using depreciated method

### ISSUE THREAD

**Issue by AlesMenzel** [socketio/socket.io#2280]
The warning: http://prntscr.com/8r8j4s

The depreciated method: http://prntscr.com/8r8ix1

**Comment by fourpixels** [comment]
This is a strict express issue, not a Socket.IO one. @nkzawa I think you should remove the label and close the issue.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
