### ISSUE TITLE
Socket IO NodeJS cluster unable to work properly with REDIS as the adapter

### ISSUE THREAD

**Issue by panbhatt** [socketio/socket.io#2281]
Hi Team,
  we are working on socket.io v 1.3.7 both on client side and server side. The server side is based on express JS and we are clustering it via nodeJS cluster module. 
When we are trying with only one instance then we are successfully able to establish the websocket connection (101 switching protocols), however as soon as the nodejs process is started in cluster mode having two or more worker process.. we are unable to set up the websocket connection and everytime the connection is FINISHED with the following error

Browser logs: WebSocket connection to 'wss://IP/socket.io/?EIO=3&transport=websocket&sid=2_mHSDYLUcA8irY_AAAD' failed: Connection closed before receiving a handshake response
engine.io-client:socket probe transport "websocket" failed because of error: Error: websocket error
at WS.Transport.onError
at WebSocket.ws.onerror

as a result of this, it again asks for an session ID and then the same process repeat itself again and again.  
1. https://IP/socket.io/?EIO=3&transport=polling&t=1445291560918-75
2.https://IP/socket.io/?EIO=3&transport=polling&t=1445291560933-76&sid=_rlE_qNItuooMtRlAAAF
3. https://IP/socket.io/?EIO=3&transport=polling&t=1445291777182-32&sid=_rlE_qNItuooMtRlAAAF
4. wss://192.168.191.25:3443/socket.io/?EIO=3&transport=websocket&sid=_rlE_qNItuooMtRlAAAF [ this is the last request is finished instead it should be 101 with switching protocols

Server Logs (only socket.io logs)
socket.io:server incoming connection with id ZOJ_d6iihffB1q_lAAAI +3s
  socket.io:client connecting to namespace / +1ms
  socket.io:namespace adding socket to nsp / +0ms
  socket.io:socket socket connected - writing packet +2ms
  socket.io:socket joining room ZOJ_d6iihffB1q_lAAAI +1ms
  socket.io:client writing packet {"type":0,"nsp":"/"} +0ms
  socket.io-parser encoding packet {"type":0,"nsp":"/"} +7s
  socket.io-parser encoded {"type":0,"nsp":"/"} as 0 +2ms
  socket.io:socket joined room ZOJ_d6iihffB1q_lAAAI +4ms

Here is the code in express (all this is RUN if this is not MASTER): 
 var redisSocket = require('socket.io-redis');

var redis = require('redis');
var sub = redis.createClient(6379, 'localhost',{return_buffers:true});
var pub = redis.createClient(6379, 'localhost',{return_buffers:true});
var client = redis.createClient(6379, 'localhost',{return_buffers:true});

io.adapter(redisSocket({
     pubClient: pub
    , subClient: sub
}));

ios.adapter(redisSocket({
      pubClient: pub
    , subClient: sub
}));

    io.sockets.on('connection', function (socket) {
        sockets.push(socket);
        var connection_index = sockets.length - 1;
        socket.on('disconnect', function (data) {
            sockets[connection_index] = undefined;
        });
    });

    ios.sockets.on('connection', function (socket) {
        sockets.push(socket);
        var connection_index = sockets.length - 1;
        socket.on('disconnect', function (data) {
            sockets[connection_index] = undefined;
        });
    });

    redisPool.getClient(function(client, done) {
        client.on("message", function(channel, message) {
            sockets.forEach(function(socket) {
                if ( socket ) {
                    socket.emit(channel, message);
                }
            });
        });

        client.subscribe("asds");
        client.subscribe("dddd");
    });

Env : UBUNTU 14
Scheduling Policy : RR

Is there is a problem with the module?/ as we have tried several strategies in order to make them work as suggested over stackoverflow and other websites, but none of them is working...

**Comment by barisusakli** [comment]
You need sticky sessions see https://github.com/indutny/sticky-session#reasoning.

**Comment by panbhatt** [comment]
Thanks barisusakli. I will try this, however this looks little hackable kind of approach to me. Socket.io team while designing there adapter must have taken care of this which might be missing from the documentation. ??. Will let you know the results, if this works out.

**Comment by appleton** [comment]
I have a similar issue though in my case I'm load balancing across servers. It seems to me that socket.io could (possibly should) store the handshake session info in redis in this case so that sticky sessions are not required.

**Comment by panbhatt** [comment]
We are also load balancing our app via Haproxy however while setup in the dev env since wehave only one server with 8 cores we face this issue. Let me know, how you have solved the problem..

**Comment by panbhatt** [comment]
@barisusakli -> This sticky session is working fine, as it directly sends the request to the same worker everytime by using the IP. however, i did not see any activity on the REDIS which means the adapter functionality is not being stored. Can you please help to guide me on this.

**Comment by barisusakli** [comment]
socket.io-redis is only used to pass messages to nodes it is not used for the handshake. Try emitting some messages when you have more than 1 node and you used see some activity in redis `MONITOR` command.

**Comment by nkzawa** [comment]
Looks like the issue has been solved. Thanks for your help @barisusakli !

**Comment by jnorris441** [comment]
"socket.io-redis is only used to pass messages to nodes it is not used for the handshake"

I believe the 0.9.x Redis plugin did handle the handshake. Has anyone gotten that to work? Some load balancers  don't have the option for websocket sticky sessions **cough** AWS **cough**
