### ISSUE TITLE
Calling socket.emit('error') on server always throws error

### ISSUE THREAD

**Issue by nick-allen** [socketio/socket.io#2285]
From the server, attempting to call `socket.emit("error", payload);` always throws an error. This occurs whether the connect client socket has an handler for the 'error' event or not.

```
> io = require('socket.io').listen(3000)
### Connect a client ###
> socket = io.sockets.sockets[0]
Socket {
...
}
> socket.emit("error", "Message");
Error: Uncaught, unspecified "error" event. (Message)
    at Socket.emit (events.js:144:17)
    at Socket.emit (<PATH>/socket.io/lib/socket.js:129:10)
    at repl:1:3
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:250:14)
    at REPLServer.runBound [as eval] (domain.js:263:12)
    at REPLServer.<anonymous> (repl.js:393:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
```

**Comment by darrachequesne** [comment]
Hi! I think "error" is a reserved event in socket.io, hence the exception.

From https://github.com/socketio/socket.io/blob/master/lib/socket.js:
```javascript
/**
 * Blacklisted events.
 *
 * @api public
 */

exports.events = [
  'error',
  'connect',
  'disconnect',
  'newListener',
  'removeListener'
];
```

**Comment by nkzawa** [comment]
@darrachequesne is correct.

**Comment by akontsevich** [comment]
Please reopen. What is the workaround here? I had same issue today accidentally sending 'error' message from socket.io-client-cpp to socket.io node.js server. That means any client can crash me server if he wants to. How to avoid this?!

**Comment by akontsevich** [comment]
Added error handler like this:
`socket.on('error', (error) => {});`
Issue is gone. **BTW**, <u>only</u> **cpp** client crashes node.js socket.io server.

**Comment by yalegria** [comment]
I think this is similar, I am getting 'disconnect is  a reserved event name' on this snippet:

```
socket.on('disconnect', function () {
        console.log('user disconnected: ', socket.id);

        // remove this player from our players object
        delete players[socket.id];

        // emit a message to all players to remove this player
        io.emit('disconnect', socket.id);

});
```

**Comment by darrachequesne** [comment]
For future readers:

`error` is no longer a reserved event, here is the complete list in v3/v4:

- connect
- connect_error
- disconnect
- disconnecting
- newListener
- removeListener

Reference: https://socket.io/docs/v4/emit-cheatsheet/#reserved-events
