### ISSUE TITLE
can socket.io   send video or audio in the chat?

### ISSUE THREAD

**Issue by zengfeng1993** [socketio/socket.io#2286]
i hope to send video or audio in chat , but i can't find it in doc ...i find it can send strem in index page ....

**Comment by suitupalex** [comment]
Yes you can, but you'll need to figure out the streaming part yourself. Or you can look at https://www.npmjs.com/package/socket.io-stream and see if it fits your needs.

**Comment by zengfeng1993** [comment]
thank you very much!!!
