### ISSUE TITLE
Socket.io net::ERR_CONNECTION_REFUSED Error

### ISSUE THREAD

**Issue by picacure** [socketio/socket.io#2288]
I lock my pc. and system get sleep. when re-open the page,I found the error

**Comment by nkzawa** [comment]
I think this is no problem if reconnection works fine. Does this occur even after a few reconnection attempts?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
