### ISSUE TITLE
Socket.io website id down, says Bad Gateway

### ISSUE THREAD

**Issue by asifalikhokhar** [socketio/socket.io#2290]
Hi SocketIO team,
http://socket.io.. the site id down and says 

502 Bad Gateway
nginx/1.5.11

Kindly look into the matter why the site went inaccessible.
For your reference I am attaching a snapshot of the screen.

![screen shot 2015-10-29 at 3 57 23 pm](https://cloud.githubusercontent.com/assets/11837568/10816604/cdd44df0-7e55-11e5-8999-57d9c5ff1949.png)

**Comment by kerphi** [comment]
+1

**Comment by w3hacker** [comment]
+2

**Comment by alexbudin** [comment]
+3

**Comment by RoyTimes** [comment]
+4

**Comment by ChadTaljaardt** [comment]
+5

**Comment by reinier-gonzalez** [comment]
yep, it's still down

**Comment by RoyTimes** [comment]
Website is back !!

**Comment by asifalikhokhar** [comment]
Yeah It's back. Thanks Team!

**Comment by nullart** [comment]
but chat.socket.io is down

**Comment by jdc20181** [comment]
Yes but this goes back to 2015, i assume it was never resolved.
