### ISSUE TITLE
Help me : io is not define

### ISSUE THREAD

**Issue by tugnt** [socketio/socket.io#2293]
Hi . I'a try write simple chat app using nodeJs and socket.io but , when i run it , i get error . IO not define 
this is my project https://github.com/tugnt/socket.ioChat
thanks all

**Comment by juniorrojas** [comment]
You're including the wrong socket.io.js file in the client code (public/socket.io/socket.io.js). Try replacing the content of that file with the content of this https://cdn.socket.io/socket.io-1.2.0.js.

**Comment by nkzawa** [comment]
juniorrojas is correct. You can use CDN or the file which served from socket.io server.
