### ISSUE TITLE
Support for Map, Set, WeakMap, and WeakSet.

### ISSUE THREAD

**Issue by suitupalex** [socketio/socket.io#2295]
I ran into this while working on a project today where I was trying to send a `Map` over socket.io. Are there any plans to add support for this and other new (and feasible) native types?

My current workaround is simply doing `Array.from(map)` and sending my map that way, but it could be nice for socket.io to handle it internally. My use case is Node4 server to Node4 server, but Chrome, Firefox, and Opera support these new types. And we might want this ready for when the full spec of ES2015 is finally implemented across the board.

**Comment by nkzawa** [comment]
I think there is no plan for this, but it might be nice to support :+1:

**Comment by MattSPalmer** [comment]
Pretty sure socket.io can only send and receive JSON or binary data. Supporting a JS type that doesn't have a JSON counterpart would be impossible.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
