### ISSUE TITLE
pingTimeout does not work if I use socket.io with express

### ISSUE THREAD

**Issue by qlqllu** [socketio/socket.io#2296]
This is my code snippet:

```
var app = express();
var httpServer = http.createServer(app).listen(3344, function() {

});

var io = require('socket.io')(httpServer, {
    pingTimeout: 3000,
    pingInterval: 1000
  });
  io.of('/slaves').on('connection', function(socket){
    logger.debug('New Slave socket:', socket.id);

    socket.on('disconnect', function () {
      logger.debug('Slave socket disconnect.');
    });
  });
```

When start the server and then start a client, the connection is established. But if I kill the client, the `disconnect` event is not fired in 4 seconds, it's fired after 60 seconds, which is the default value.

**Comment by qlqllu** [comment]
More information:

I use `"socket.io": "1.3.7"` as the server, and use ` "socket.io-client": "1.3.7"` as the client.

**Comment by qlqllu** [comment]
?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
