### ISSUE TITLE
[!help] a mysterious "disconnect" 

### ISSUE THREAD

**Issue by fortyMiles** [socketio/socket.io#2298]
# A mysterious "disconnect"

Hi every one, today, after lunch... really is after lunch. 
My code did not work well.. until now. 
And I checkout my code to a "good" version, but still not work. 

## Here is the question: 
To simplify the problem, I user the code  from socket.io [chat example.](http://socket.io/get-started/chat/)
<img width="1280" alt="screen shot 2015-11-05 at 5 41 53 pm" src="https://cloud.githubusercontent.com/assets/6982171/10964853/8de2d3ee-83e4-11e5-96d7-52c1e383333d.png">

### index.html

```html
<!doctype html>
<html>
    <head>
        <title>Socket.IO chat</title>
        <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { font: 13px Helvetica, Arial; }
            form { background: #000; padding: 3px; position: fixed; bottom: 0; width: 100%; }
            form input { border: 0; padding: 10px; width: 90%; margin-right: .5%; }
            form button { width: 9%; background: rgb(130, 224, 255); border: none; padding: 10px; }
            #messages { list-style-type: none; margin: 0; padding: 0; }
            #messages li { padding: 5px 10px; }
            #messages li:nth-child(odd) { background: #eee; }
        </style>

        <script src="/socket.io/socket.io.js"></script>
        <script src="http://libs.baidu.com/jquery/1.9.0/jquery.js"></script>
        <script>
            var socket = io();
            $('form').submit(function(){
                socket.emit('chat message', $('#m').val());
                $('#m').val('');
                return false;
            });
        </script>
    </head>
    <body>
        <ul id="messages"></ul>
        <form action="">
            <input id="m"  /><button>Send</button>
        </form>
    </body>
</html>
```
```js
var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);

app.get('/', function(req, res){
  res.sendfile('index.html');
});

io.on('connection', function(socket){
    console.log('a user connected');
    socket.on('chat message', function(msg){
        console.log('message: ' + msg);
    });

    socket.on('disconnect', function(){
        console.log('user disconnect');
    });
});

http.listen(3000, function(){
  console.log('listening on *:3000');
});
```

All above, is exactly same as the socket.io 's example, besides the cdn is from baidu.com, because of my location is China. 

#### When I typed something. 

<img width="548" alt="screen shot 2015-11-05 at 5 45 25 pm" src="https://cloud.githubusercontent.com/assets/6982171/10965008/1e538dce-83e5-11e5-8545-0981bca15d6d.png">

#### The server side, did not receive the message, but on the **disconnect** event.

<img width="648" alt="screen shot 2015-11-05 at 5 45 42 pm" src="https://cloud.githubusercontent.com/assets/6982171/10965014/36188f72-83e5-11e5-9b22-54d14de02961.png">

#### However, when I test in web browser's console. 
<img width="545" alt="screen shot 2015-11-05 at 5 48 01 pm" src="https://cloud.githubusercontent.com/assets/6982171/10965055/641e5294-83e5-11e5-8ddf-f5d30757d2bc.png">

#### The socket.io server could receive this message. 

![d546020f-b173-4ad5-99e5-aa9628a5f0e3](https://cloud.githubusercontent.com/assets/6982171/10965144/fca636a8-83e5-11e5-80ee-bc09418e28e2.png)

## References:

1. [Socket io example. ]  http://socket.io/get-started/chat/
2. [My Project code] http://socket.io/get-started/chat/
3. [Problem Demo code] https://github.com/fortyMiles/socket_issus

**Comment by fortyMiles** [comment]
anyone??

**Comment by nkzawa** [comment]
You just have to put these `script` tags on the bottom of `body`.  See https://github.com/rauchg/chat-example/blob/master/index.html.
