### ISSUE TITLE
Issue not passing splashscreen in IOS 

### ISSUE THREAD

**Issue by chaerf** [socketio/socket.io#2299]
hi,
im working on a real time chat with socket.io, ionic and node.js as server... i've successfuly builded and used it with android. but in ios it compiles... but never pass splash screen...

debuging i found that the issue ocurrs only when i run the library from a .run function

ie.:
  .run(function ($ionicPlatform,socket) {
        $ionicPlatform.ready(function() {
            console.log("socket",socket);
        });
    })

what im trying to do is connect the socket when the app starts... from the begining...

with those lines im able to compile in ios, but freezes in splashscreen... it works in android, also in chrome...

apps starts... keep getting feedback from logs, and then it just freezes... no more logs, no nothing.

tried in emulators, ipads, etc... without success... im working with ionic 1.7.7 developing for ios 9.1, 8, tried some of them.

anything to look at? another debugger? work around ? 

Regards.

**Comment by dsalcedo** [comment]
For questions (not issues) use Stackoverflow
url: https://www.google.com.mx/search?espv=2&q=ionic+socket+io+stackoverflow&oq=ionic+socket+io+stackoverflow&gs_l=serp.3...7801.10699.0.10838.14.13.0.0.0.0.192.1238.0j8.8.0....0...1c.1.64.serp..12.2.351.JpKJxLK_324

please , close this 'issue' :cry:
