### ISSUE TITLE
Why is `disconnect` event fired as a first thing right after client connects?

### ISSUE THREAD

**Issue by visualfanatic** [socketio/socket.io#2305]
I am using Node 4.2 and Socket.io 1.3.7, and below is a fragment from a server side code:
```js
var connectCounter = 0;

io.on('connection', function (socket) {
	socket.on('logged', function () { connectCounter++; console.log('connected', connectCounter); });
	socket.on('disconnect', function () { connectCounter--; console.log('disconnected', connectCounter); });
});
```

... and this is a client side code:
```html
<script src="/socket.io/socket.io.js"></script>
<script>
	var socket = io();
	socket.emit('logged');
</script>
```

After server is restarted, the first client connection will result with that in my logs:
```
disconnected -1
connected 0
```

Each new client (a new tab) is just fine, but that first client is my issue. From what I have seen in a chat example, you guys are using a `addedUser` variable (https://github.com/socketio/socket.io/blob/master/examples/chat/index.js#L22), and this is a solution, but for me it feels hacky and would like to know if there is a better way to solve that. Is that all because of the behaviour of a `io` function on the client side? I mean, when used without an `url` argument, it will lookup for an address by itselt and because of that, the first try causes an `disconnect` event. Is that correct?

**Comment by nkzawa** [comment]
This is because `socket.emit('logged');` is not called when client reconnected. Do the following for counting connections.

```js
io.on('connection', function (socket) {
    connectCounter++; console.log('connected', connectCounter);
    socket.on('disconnect', function () { connectCounter--; console.log('disconnected', connectCounter); });
});
```
