### ISSUE TITLE
socket.io only works when connected to the internet

### ISSUE THREAD

**Issue by iamdriz** [socketio/socket.io#2309]
I have the following NodeJS app:
~~~
var io = require('socket.io')();

io.on('connection', function (socket) {
	
    console.log('we\'ve got a client connection');
	
    socket.emit('toClient', { client: 'hello world' });

    socket.on('toServer', function (data) {
        console.log(data);
    });
	
});

io.listen(8004);

var socket = require('socket.io/node_modules/socket.io-client')('http://localhost:8004');

socket.on('connect', function () {
	
	console.log('connected client');
	
	socket.on('toClient', function (data) {
		console.log(data);
		socket.emit('toServer', { server: 'hello world' });
	});

});
~~~

If I run this in my command prompt (on Windows 8) and I'm connected to the internet then I see all of the above console logs fine:

![image](https://cloud.githubusercontent.com/assets/801252/11244054/90369e9a-8e03-11e5-877b-1fdfa3113b1e.png)

But if I try it with my Ethernet cable pulled out then I don't see them!

![image](https://cloud.githubusercontent.com/assets/801252/11244035/748ab0aa-8e03-11e5-9213-f7655bd7d268.png)

Any ideas why? I need sockets to work locally without relying on an internet connection.

I've done some more testing and found that if you are connected to the internet and start the script and then pull the Ethernet cable out, the sockets still work. For example I can set an interval to keep sending messages and I see them.

But if the cable is pulled out before the script is started so I don't have a connection, then they don't work at all. But as soon as the connection returns, it starts working again. So it seems like socket.io doesn't connect properly if no internet is available when they first connect but can then resolve itself when a connection is found. But why is it relying on the internet full stop?

**Comment by dsalcedo** [comment]
in your HTML main page, you have the CDN js of socket.io ?

**Comment by iamdriz** [comment]
This isn't a html page. It's just a Nodejs app (single js file)

**Comment by iamdriz** [comment]
Just done some more testing and found that if you are connected to the internet and start the script and **then** pull the Ethernet cable that the sockets still work. But if they cable is out **before** the script is started then they don't work at all.

**Comment by iamdriz** [comment]
@dsalcedo This isn't a html page. It's just a Nodejs app (single .js file)

This is just an example to show that socket.io doesn't work when offline As I have the same issue in my real application that runs locally and messages don't work when the internet is disconnected.

**Comment by Nibbler999** [comment]
Did you try 127.0.0.1?

**Comment by iamdriz** [comment]
@Nibbler999 From initial testing changing `localhost` to `127.0.0.1` does indeed fix it. But why???

**Comment by Nibbler999** [comment]
Apparently something to do with how DNS works in windows.

https://superuser.com/questions/713491/why-does-localhost-not-work-in-windows-8-1-but-127-0-0-1-does

**Comment by iamdriz** [comment]
@Nibbler999 Forgot to say thanks :)

**Comment by DevChrisDev** [comment]
thanks guys!
