### ISSUE TITLE
socket.join() sometimes (!) does not work

### ISSUE THREAD

**Issue by helios1138** [socketio/socket.io#2311]
I have a system in which a lot of clients are constantly joining and leaving rooms and I see this weird behavior in which I do:
```js
socket.join(someRoom);
```
and them on the next line I have:
```js
console.log(io.of('/').adapter.rooms[someRoom][socket.id])
```
which prints `true` **most of the time**, but sometimes I get `undefined`

in `Socket` class source code I see this line that stops socket from joining the room:
```js
if (~this.rooms.indexOf(room)) return this;
```
So I now I see that problem is that `adapter.rooms` and `socket.rooms` are out of sync for some reason.

Also in the `Adapter.prototype.add()` I see this:
```js
if (fn) process.nextTick(fn.bind(null, null));
```

So apparently `adapter.rooms` and `socket.rooms` are updated in different event loops. Might this be causing the problem?

**Comment by fourpixels** [comment]
I was also checking this today. I have no idea why the `process.nextTick` is used. Any clues?
Anyways, your pull request seems legit to me.
I still don't understand why those rooms are so complicated. There is another issue suggesting simple Object mapping, which is pretty fast compared to Array search / modifications. Might wanna check it.

**Comment by darrachequesne** [comment]
Hi! This issue should be solved now, with the following merged PR:
- https://github.com/socketio/socket.io/pull/2239 (object mapping)
- https://github.com/socketio/socket.io/pull/2325 (trigger callback on already joined room)

(should be released with the forthcoming version)
