### ISSUE TITLE
Improve binary support documentation

### ISSUE THREAD

**Issue by castillobgr** [socketio/socket.io#2313]
Hi! While reading the docs, I noticed a lack in examples regarding binary support, available since v1.0.

**Comment by castillobg** [comment]
Btw, I'd be glad to contribute. :)

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
