### ISSUE TITLE
Get a raw socket frame(or its length) from the socket object

### ISSUE THREAD

**Issue by elssar** [socketio/socket.io#2318]
I am using `sails.js`, which exposes the socket object in each request. Is it possible to get the raw frame data, or its length for the request and the corresponding response.

Sailsjs uses socket.io v1.2.1

**Comment by nkzawa** [comment]
Unfortunately, there is no official or easy way to do that.

**Comment by shamasis** [comment]
+1 this something that is useful when tracing traffic pattern in logs. @rauchg thoughts?

**Comment by shamasis** [comment]
ping

**Comment by rauchg** [comment]
We're about to release `1.4.0`, we'll evaluate this for `1.5.0`

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
