### ISSUE TITLE
Creating a user-socket association map

### ISSUE THREAD

**Issue by vipersec** [socketio/socket.io#2323]
Hi all,

I'm trying to implement a private messaging system using socket.io

In order to associate the users with their sockets, most sites are suggesting this:

    var people = {};

    client.on('connection', function(socket) {

        //join the server
        socket.on('add user', function(user_id) {
	        //create user-socket map
            people[user_id] = socket.id;
        });

    });

But isn't it wrong? The user_id is sent from the client side, so if the user modify it and send another user's id an impersonation will take place. How can someone avoid this?

**Comment by darrachequesne** [comment]
Hi! I'd personally use the socket.id as key here `people[socket.id] = user_id` as you're sure it is unique and not messed-with.

Please note that StackOverflow (for example) would be better (and more responsive) for questions like that (as this is not really an issue :wink:)

**Comment by vipersec** [comment]
ok @darrachequesne thanks!!
