### ISSUE TITLE
Emit object before redirect & Disconnect and reconnect previous con

### ISSUE THREAD

**Issue by ujwaldhakal** [socketio/socket.io#2324]
We would like to see the socket emi possible before redirection by makeing some hooks and delaying connection and same as emiting data. And where as making in built in cache about the con would be better

**Comment by nkzawa** [comment]
sorry, could you explain the issue in another word?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
