### ISSUE TITLE
Node.js package installation hang at loadrequesteddeps

### ISSUE THREAD

**Issue by rainbow1112** [socketio/socket.io#2328]
I had tried installing v4.2.1, v4.2.2 and v5.1 of Node.js

All hang at loadrequesteddeps

any help to install packages?

[![enter image description here](http://i.stack.imgur.com/BJmoB.jpg)](http://i.stack.imgur.com/BJmoB.jpg)

[![enter image description here](http://i.stack.imgur.com/3TVcX.jpg)](http://i.stack.imgur.com/3TVcX.jpg)

**Comment by panwarvikas** [comment]
I am having same issue and stuck at this point , As I have to download cordovea for android development but still waiting for any help.

**Comment by nkzawa** [comment]
Does this still occur on the latest version?

**Comment by Shankar016** [comment]
me too having the same issue, please anyone tell the remedy

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
