### ISSUE TITLE
Enter your email to join the Socket.IO community Slack, But failed

### ISSUE THREAD

**Issue by lian1925** [socketio/socket.io#2329]
I want to join  Socket.IO community Slack , I try to do this
1 . go to http://socket.io/slack/? on browser
2 . input my email  and press enter key , below the tip "Enter your email to join the Socket.IO community Slack server:"
But I can not receive any invited email for a long time (more than one hour). I think that must be something wrong with your web service.

Looking for your reply.

**Comment by makkesk8** [comment]
This has nothing to do with socket.io? As far as I can tell slack is a service independent from socket.io and its on their side.

**Comment by mrmartineau** [comment]
Hi @lian1925, I had the same issue and resolved it by emailing feedback@slack.com. This is what I wrote:

> I recently tried to signup at http://slack.socket.io/ for the socket.io Slack group but I have not received an invite yet. Is it possible that my email address has been caught in a filter somewhere?

Slack support replied within a few minutes. Hope that helps.

**Comment by nkzawa** [comment]
@lian1925 is this still an issue ?

**Comment by joshkpeterson** [comment]
Seeing this issue. There needs to be a 'submit' button and some UI feedback that an email should be on its way.

**Comment by choiRyan** [comment]
I can't get in the slack channel either. I think something's wrong in general, if I open the console (Chrome 54, Win10)  I'm greeted with `Failed to load resource: the server responded with a status of 502 (Bad Gateway)`. If you click on the Slack button in the nav bar you get a 502 Bad Gateway too.

The websocket connection seems to be having issues.

> GET http://slack.socket.io/socket.io/?EIO=3&transport=polling&t=LWYl3O7 
> (index):1 XMLHttpRequest cannot load http://slack.socket.io/socket.io/?EIO=3&transport=polling&t=LWYl3O7. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://socket.io' is therefore not allowed access. The response had HTTP status code 502.

And if I try to fill the form I see:

> OPTIONS http://slack-io.socket.io/invite 
> XMLHttpRequest cannot load http://slack-io.socket.io/invite. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://socket.io' is therefore not allowed access. The response had HTTP status code 405.

**Comment by nakulshah** [comment]
I am facing the same issue. 
1) I went to http://socket.io/slack/ and put in my email, but dont see any submit button
2) I tried to go to http://slack-io.socket.io/invite but that is throwing a 404 not found error
Can someone please help?

**Comment by darrachequesne** [comment]
Until we migrate the website, please use https://rauchg-slackin-wjgcyuptip.now.sh/

**Comment by DukeCannon** [comment]
Related to #2329 and #2753.

**Comment by roychri** [comment]
I tried using https://rauchg-slackin-wjgcyuptip.now.sh/

but the page says "Loading..." and the WebSocket frames in the Developer Tools says:

```
42/states,["state", {error: true}]
```

**Comment by sachanand** [comment]
I am not able to login to the slack channel from the site. when I try to subscribe it says with the link below no response. How to join the channel ?
http://socket.io/slack/

**Comment by MeBNoah** [comment]
same issue here, entered my email here http://socket.io/slack/ but got no invitation email, also tried to use https://rauchg-slackin-wjgcyuptip.now.sh/ but there is only a text in the middle of the page that says loading ... forever

**Comment by ToujouAya** [comment]
same issue here, does anyone have any idea?

**Comment by k0mita** [comment]
Same issues as everyone else. There is no way to submit the typed email address for a slack invitation and the backup site provided above does not load (https://rauchg-slackin-wjgcyuptip.now.sh/ ).

**Comment by georgeedwards** [comment]
Would be great to get an answer to this! @darrachequesne ?

**Comment by darrachequesne** [comment]
Well, it seems the service is not absolutely stable yet. Please use the following: https://slackin-socketio.now.sh/

**Comment by darrachequesne** [comment]
Along with https://socketio-whiteboard.now.sh and https://socketio-chat.now.sh

**Comment by QuantumInformation** [comment]
The link on the open new issue should have the invite link no?
