### ISSUE TITLE
SocketIO server closing all live connections unexpectedly 

### ISSUE THREAD

**Issue by tonyjose009** [socketio/socket.io#2331]
Hi,
After establishing success connections on web clients, when we are sending a socket emit, after  the pingTimeout all connected socket clients are getting disconnected and this happens only after each socket.emit.
 I'm getting _ping timeout_ as error in client side while disconnecting.
socket.on('disconnect', function(err) {
    console.log(" err -", err);
    errorconnection();
    socket.io.reconnect();
});

Please see my socketio config

var io = require('socket.io').listen(httpd, {
    log: true
    , "transports":["polling"],
    "pingInterval":15000,
    "pingTimeout":25000

});

My web and mobile applications were working smoothly, unfortunately I'm getting this error since yesterday on both mobile and web clients.

Please help

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
