### ISSUE TITLE
Socket.io Not available for "graceful" exit

### ISSUE THREAD

**Issue by makkesk8** [socketio/socket.io#2336]
```
process.on('SIGTERM', function () {
   logger.info("About to shutdown");
   io.to("channel").emit("Server going down");
    setTimeout(function() {
       logger.info("shutting down");
       process.exit(0);
    }, 5000);
});
```

As the code explains, **io.to** will never get fired, the **io** object doesn't even return anything either... However it does shutdown after 5 seconds according to logs (logger = [winston](https://github.com/winstonjs/winston)).

Any ideas?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
