### ISSUE TITLE
forced disconnesion from the server doesn't work properly

### ISSUE THREAD

**Issue by matteomartinelli** [socketio/socket.io#2339]
While using

``` javascript
io.sockets.connected[socket_id].disconnect();
```

the client is not successfully disconnected. Moreover, the disconnect event is not fired.
To get you more information, the socket object and io.sockets.connected[socket_id] object seems different (for instance, namespace are not stored in the latter)

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
