### ISSUE TITLE
Default namespace middleware firing

### ISSUE THREAD

**Issue by perrin4869** [socketio/socket.io#2342]
I'm trying to create a server with the default `/` namespace for normal users and the `/admin` namespace for admins, and they both are authenticated in different ways. I wrote two different middlewares for authentication like so:

``` javascript
io.use(normalAuthenicate);
io.of('/admin').use(adminAuthenticate);
```

Now, when connecting from the client I do:

``` javascript
var socket = io('/admin');
```

Unfortunately, the top middleware gets called even though it shouldn't be. It still gets called even if I change it to `io.of('/').use(normalAuthenticate)`. Is there any way to tell socket.io to use only the middlewares for the namespaces requested?

**Comment by darrachequesne** [comment]
Hi! I think a similar issue has already been opened here https://github.com/socketio/socket.io/issues/2124

The middlewares associated with the default namespace '/' are indeed triggered by every request, and there's currently no way to avoid that. A quick "workaround" would be to also use a custom namespace for normal users :cake: 

And yes, the documentation could be clearer on that point :smile:

**Comment by perrin4869** [comment]
I see I was hoping to avoid a new namespace, guess I have quite a bit of code to change now! Thankfully I also have tests to help me through the process :)

Is this done by design? I guess it kinda makes sense to have a namespace with common middleware in case you got some common logic. But definitely this needs documentation

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Comment by perrin4869** [comment]
@darrachequesne I think this issue should still be addressed, preferably by fixing the inconsistencies between the root namespace `/` and custom namespaces as described in #2124 and also my own issue https://github.com/socketio/socket.io-client/issues/975
Maybe this could be added to the list in #2823?
