### ISSUE TITLE
io.nsps['/namespace'].adapter.rooms

### ISSUE THREAD

**Issue by nodejs1208** [socketio/socket.io#2348]
before use socket.join('roomname') , socket already got it's room. (roomname is socket.id)
can i block socket.join(socket.id) ?

i connected 1 socket and socket.join('room1'),
and i  check Object.keys(io.nsps['/namespace'].adapter.rooms).length, 
length is 2 .

 http://imgur.com/KtG4Q1z

**Comment by nkzawa** [comment]
sorry, could you explain the issue In another word?

**Comment by samuel281** [comment]
He's saying that he could see 2 rooms in the io.nsps.adapter.rooms when he joins a room.
I guess one has the room name and another has sid as its name.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
