### ISSUE TITLE
Heartbeat timeout was discovered before the data loss problem

### ISSUE THREAD

**Issue by haozxuan** [socketio/socket.io#2349]
Hi ，I'm confused about socket heartbeat timeout was discovered before the data loss, because when the connection breaks up due to network problems (or that the client crashes) the default heart beat timeout is too long(60s),  so is there any way to solve this problem?

BTW: except receipt for each message do;

socket.io version: 0.9.16
node version: 0.12.7

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
