### ISSUE TITLE
Ghost users after refreshing

### ISSUE THREAD

**Issue by Fusix** [socketio/socket.io#2351]
Hey, I have a problem. If the user refreshes their page very fast my socket.io server has ghost sockets. They are not really connected but their connection wasn't closed. I get duplicate entries except the new socket.id each time. (See this picture: http://puu.sh/lYe92/01da0e4f91.png)

**Comment by nkzawa** [comment]
That wouldn't be inevitable since sometimes there are some delay until server noticed a socket closed.
