### ISSUE TITLE
socket.in('room').emit..  messaging bug

### ISSUE THREAD

**Issue by Akshay-Thakare** [socketio/socket.io#2355]
Messages from users who are not allocated any rooms are being send to user who was allocated a room last.
---------------------------------------------------------------------------------------------------------------------------
I first connected a user 1 to room = 'a'
---------------------------------------------------------------------------------------------------------------------------
<img width="405" alt="1" src="https://cloud.githubusercontent.com/assets/6640346/12000278/68328478-aaf9-11e5-90c3-c3ca05dd182b.png">
---------------------------------------------------------------------------------------------------------------------------
Then i connected another user 2 to room='b'
---------------------------------------------------------------------------------------------------------------------------
<img width="411" alt="2" src="https://cloud.githubusercontent.com/assets/6640346/12000277/68300c20-aaf9-11e5-9e13-119393d4ac45.png">
---------------------------------------------------------------------------------------------------------------------------
For user 3 i did not connect it to any room and just send a message='sdf'
---------------------------------------------------------------------------------------------------------------------------
<img width="406" alt="3" src="https://cloud.githubusercontent.com/assets/6640346/12000279/685e5f6c-aaf9-11e5-9d3c-0619a3bf5a2d.png">
---------------------------------------------------------------------------------------------------------------------------
Now if we look at user 2 we can observe that user 3's message has been send to user 2. The message is not send to user 1. So we can conclude that the bug is that users with no room if they send a message, then their message is send to the last allocated room. I also tried it the other way round i.e. sending message from last allocated room (user 2) to user 3 but that didnt work out. So its a one way problem.

---------------------------------------------------------------------------------------------------------------------------
Here's the server code : index.js
---------------------------------------------------------------------------------------------------------------------------
var app = require('express')();
app.set('port',(process.env.PORT || 3000));

var server = require('http').createServer(app);
server.listen(app.get('port'), function(){
	console.log('listening on *:' + app.get('port'));
});

//Socket.io 
var roome;
var io = require('socket.io')(server);
io.sockets.on('connection', function(socket) {
    console.log('user joined');
    socket.on('join', function(room) {
        socket.join(room);
        roome = room;
        console.log('user joined room ' + room);
    });
    socket.on('disconnect', function() {
        console.log('user disconnected');
    });
    socket.on('chat message',function(msg){
        socket.in(roome).emit('chat message',msg);
        //socket.broadcast(roome).emit('chat message',msg);;
    });
});

---------------------------------------------------------------------------------------------------------------------------
//Client code
---------------------------------------------------------------------------------------------------------------------------
//index.html - snippet

<textarea id="room"></textarea>
<button id="rid">Submit room</button>

<textarea id="message"></textarea>
<button id="mid"></button>

---------------------------------------------------------------------------------------------------------------------------
//client script code
---------------------------------------------------------------------------------------------------------------------------
var room = document.getElementById('room');
var rid = document.getElementById('rid');
var message = document.getElementById('message');
var mid = document.getElementById('mid');

rid.onclick = connectToRoom;
mid.onclick = sendMessage;

var socket = io("http://localhost:3000");
    socket.on('connect',function(){
        console.log('connected to server');
});

function connectToRoom(){
	//Client side does not have the ability to socket.join('room');
	console.log(room.value);
	socket.emit('join',room.value);
}

function sendMessage(){
	console.log(message.value)
	socket.emit('chat message',message.value);
}

socket.on('chat message',function(msg){
	console.log(msg);
});

---------------------------------------------------------------------------------------------------------------------------
Work around
---------------------------------------------------------------------------------------------------------------------------
A simple work around for this would be to check for users who try to send messages without being allocated a room at both client and server side. But its still a bug none the less.

**Comment by nkzawa** [comment]
With `socket.in(roome).emit('chat message',msg);` you are trying to send a message to a room which a user joined last time. It would a problem of your script. Feel free to reopen if I'm missing something.
