### ISSUE TITLE
socket.emit don't have callback

### ISSUE THREAD

**Issue by jackmasa** [socketio/socket.io#2358]
Do I need to check the message has been sent successfully.

**Comment by dsalcedo** [comment]
```javascript
io.sockets.connected //Return {socket_1_id: {}, socket_2_id: {}} . This is the most convenient one, since you can just refer to io.sockets.connected[id] then do common things like emit()
io.sockets.sockets //Returns [{socket_1}, {socket_2}, ....]. Can refer to socket_i.id to distinguish
io.sockets.adapter.sids //Return {socket_1_id: {}, socket_2_id: {}} . Looks similar to the first one but the object is not actually the socket, just the information.

// Not directly helps but still relevant
io.sockets.adapter.rooms //Returns {room_1_id: {}, room_2_id: {}}
io.sockets.server.eio.clients //Return client sockets
io.sockets.server.eio.clientsCount //Return number of connected clients
```
When you have 'client list' you only need verify if the "client id" is connected.
```javascript
if(connected) {
 return {"success" : true} 
}else{ 
 return {"success" : false} 
}
```

**Comment by jackmasa** [comment]
@dsalcedo I have experienced the situation to send the missing data, but socket is connected.

**Comment by dsalcedo** [comment]
can you show the code ?

**Comment by jackmasa** [comment]
@dsalcedo  it's 'ghost' :(

**Comment by dsalcedo** [comment]
Well, i dont know if SocketIO is able to do this in native... but with a little code should be works, open a  Runnable code snippets and invite me to play

**Comment by nkzawa** [comment]
The only way is to use ack.

**Comment by qiulang** [comment]
But accorind to https://socket.io/docs/client-api/#socketemiteventname-args-ack 

ack's signature is not like `function(err, success)` how do I know when ack fails ?
