### ISSUE TITLE
npm install problem

### ISSUE THREAD

**Issue by yunusemreuveyik** [socketio/socket.io#2359]
ı run app and it says listening 3000 but in browser ı am not able to run it.. 

[npm-debug.log.zip](https://github.com/socketio/socket.io/files/73157/npm-debug.log.zip)

**Comment by nkzawa** [comment]
Could you make the problem clear?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
