### ISSUE TITLE
bump for new release?

### ISSUE THREAD

**Issue by japrescott** [socketio/socket.io#2360]
now that most of the trouble with redis2.0 (return-buffer/detect-buffer), msg-pack, socket.io-redis, socket.io-emitter have been resolved, it would be great if we'd see a new version beeing released and bumped on npm.
@rauchg Or are you waiting for more changes to land and then release 1.4?

**Comment by rauchg** [comment]
@japrescott we're waiting on a `ws` release (@3rdEden)

**Comment by darrachequesne** [comment]
@rauchg I think you meant @3rd-Eden :smile:

**Comment by rauchg** [comment]
:+1:

**Comment by awinograd** [comment]
Looks like we may be in luck! 

https://github.com/websockets/ws/commit/753937ff1ddc0938513267b4d6d5139a6ad41746

**Comment by rauchg** [comment]
@awinograd We're working on a minor yet breaking change, the removal of the `browser` field. Ready right after that.

**Comment by japrescott** [comment]
@rauchg awesome! looks like xmas came early this year ;)

**Comment by mikermcneil** [comment]
@rauchg thanks for the update!
