### ISSUE TITLE
Is this module platform-dependent?

### ISSUE THREAD

**Issue by cherryliu** [socketio/socket.io#2361]
It might be a silly question, but when I run npm to install socket.io on windows, it looks for Visual Studio build tools (probably related to node-gyp), but it runs more straight forward on Linux - Will the installed files be the same for both platforms? Thanks!

**Comment by antoniogiordano** [comment]
The compiled binaries will be different for different platforms!

**Comment by cherryliu** [comment]
Thanks you! However, I only saw the .js files being "installed" under node_modules/.../... Are there any other files being deployed?

**Comment by nkzawa** [comment]
socket.io is not platform-dependent. on 1.3.x and earlier, socket.io had dependencies to a few native addons.
