### ISSUE TITLE
Client events for Manager and Socket

### ISSUE THREAD

**Issue by alexandrubau** [socketio/socket.io#2364]
From what it says in the docs, we can find the same events available for Manager and Socket.

Client: [Manager](http://socket.io/docs/client-api/#manager%28url:string,-opts:object%29), [Socket](http://socket.io/docs/client-api/#socket)

> The events above are also emitted on the individual sockets that reconnect that depend on this Manager.

The event called `connect_error` cannot be found in the docs of the Socket. Instead I can see the event `error` listed - which is not available for Manager. Both events describe the same `Fired upon a connection error.`.

So, which one is correct?

**Comment by nkzawa** [comment]
The doc looks wrong. `connect_error` is only for connection. `error` is for more generic errors.

**Comment by alexandrubau** [comment]
@nkzawa thank you for help.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
