### ISSUE TITLE
Http Error 400 on High Load

### ISSUE THREAD

**Issue by EddieOne** [socketio/socket.io#2365]
Hi, When our socket.io servers experience increased load we see increased httpError 400 showing in newrelic. So far we have been unable to track it down. Best guess right now is maybe the origin white list. I'm wondering if someone has experience with this? Maybe there's a configeration change we need or a better way to track the root cause?
![errors](https://cloud.githubusercontent.com/assets/1835156/12053503/114da0c0-aed7-11e5-8ba6-b180d42df47d.png)

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
