### ISSUE TITLE
Tests failing in CI

### ISSUE THREAD

**Issue by MylesBorins** [socketio/socket.io#2367]
Hey All. socket.io is one of the modules we are testing in CI with [canary in the gold mine](http://github.com/nodejs/citgm) the official node.js smoke tester.

We are currently getting a failure in one of your tests

```
  1 failing

  1) socket.io socket should handle very large binary data:
     Error: timeout of 2000ms exceeded
```

https://ci.nodejs.org/job/thealphanerd-smoker/nodes=ubuntu1504-64/9/console

edit: fixed CI link

**Comment by jasperkuperus** [comment]
I'm having the same issue and I don't see anything in the changelog to help me further. Here's some of our output:

```
1) Event integration test, POST /api/event should receive a socket notification when creating a valid event
- Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

The test is quite straightforward (join a room, mark test as done on event) and worked just fine with 1.3.7.

**Comment by jasperkuperus** [comment]
Ok, diving deeper, I found out our problem was related to redis. Events emitted on a socket directly did arrive, but events emitted on a namespace failed. Updating the `socket.io-redis` package to `1.0.0` was the solution for me.

**Comment by nkzawa** [comment]
Thanks for your report. How can we fix the problem? We have already been testing on Node.js 4 and all tests pass. And I wonder why the error message is `Error: timeout of 2000ms exceeded` even though we set longer timeout. https://github.com/socketio/socket.io/blob/master/test/socket.io.js#L1539

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
