### ISSUE TITLE
Docs specify that options are passed through to engine.io but they are not always

### ISSUE THREAD

**Issue by calzoneman** [socketio/socket.io#2372]
From the readme for the `Server()` constructor:

> The same options passed to socket.io are always passed to the engine.io Server that gets created. See engine.io options as reference.

However, this is not always the case.  It seems like the options are only passed through to engine.io when the `opts` object is passed to `Server#attach`, so if one constructs a `Server` that is not attached to anything in the constructor, and then later attaches it to a server and does not pass in the options again, it will not pass through these options to engine.io.

Example:

``` javascript
var ioServer = sio({
    perMessageDeflate: false
});

// ...

ioServer.attach(httpServer);
```

**Comment by nkzawa** [comment]
right, it could be confusing.

**Comment by calzoneman** [comment]
Yeah, ideally socket.io would cache the config and re-use it during calls to `attach()`.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
