### ISSUE TITLE
Reloading page via Ajax causes the client to receive multiple messages.

### ISSUE THREAD

**Issue by danifantom** [socketio/socket.io#2376]
I load the page via Ajax inside a div, this page has the script.js included in it. but when I load more then once I receive the same amount of messages as reload times. Can't seem to find why! Any clues?

**Comment by nkzawa** [comment]
Please describe more details.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
