### ISSUE TITLE
1.4.3 socket.io-client update results in 2 warnings and 2 errors of missing modules

### ISSUE THREAD

**Issue by ADumaine** [socketio/socket.io#2379]
Was running 1.3.7 and used npm to update socket.io-client to 1.4.3.

The app uses just the socket.io-client to connect to a game server(also updated to socket.io 1.4.3).  Developing on windows 7. 

Tried uninstalling via npm and reinstalling.  Did not expect to see warnings and errors from socket.io-client and engine.io-client when starting the app.

Shouldn't the missing modules be part of the npm package?

Warnings:
WARNING in ./~/socket.io-client/~/engine.io-client/~/ws/lib/BufferUtil.js
Module not found: Error: Cannot resolve module 'bufferutil' in C:\Data\captchatheprize.com\dev\gamewww\node_modules\socket.io-client\node_modules\engine.io-clie
nt\node_modules\ws\lib
 @ ./~/socket.io-client/~/engine.io-client/~/ws/lib/BufferUtil.js 10:19-40

WARNING in ./~/socket.io-client/~/engine.io-client/~/ws/lib/Validation.js
Module not found: Error: Cannot resolve module 'utf-8-validate' in C:\Data\captchatheprize.com\dev\gamewww\node_modules\socket.io-client\node_modules\engine.io-
client\node_modules\ws\lib
 @ ./~/socket.io-client/~/engine.io-client/~/ws/lib/Validation.js 10:19-44

Errors:
ERROR in ./~/socket.io-client/~/engine.io-client/~/ws/lib/WebSocketServer.js
Module not found: Error: Cannot resolve module 'tls' in C:\Data\captchatheprize.com\dev\gamewww\node_modules\socket.io-client\node_modules\engine.io-client\node
_modules\ws\lib
 @ ./~/socket.io-client/~/engine.io-client/~/ws/lib/WebSocketServer.js 15:10-24

ERROR in ./~/socket.io-client/~/engine.io-client/~/ws/~/options/lib/options.js
Module not found: Error: Cannot resolve module 'fs' in C:\Data\captchatheprize.com\dev\gamewww\node_modules\socket.io-client\node_modules\engine.io-client\node_
modules\ws\node_modules\options\lib
 @ ./~/socket.io-client/~/engine.io-client/~/ws/~/options/lib/options.js 6:9-22

**Comment by Levino** [comment]
This is a client issue. Post it in client. Or just jump on the band waggon. https://github.com/socketio/socket.io-client/issues/933

**Comment by ADumaine** [comment]
Sorry!  will repost or jump on the client site.   But at least it is here for anyone searching.
