### ISSUE TITLE
socket.io dosn't run in VM "sandboxed-module"

### ISSUE THREAD

**Issue by mStirner** [socketio/socket.io#2381]
Hay, i have a little problem.

I cant use socket.io inside a node js VM.
When i run it i become this error:  "TypeError: Cannot read property 'prototype' of undefined"

/home/marc/NetBeansProjects/Project/node_modules/socket.io-client/node_modules/json3/lib/json3.js:50
    var objectProto = Object.prototype,
                            ^
TypeError: Cannot read property 'prototype' of undefined
    at runInContext (/home/marc/NetBeansProjects/Project/node_modules/socket.io-client/node_modules/json3/lib/json3.js:50:29)

As VM i use the module "sandboxed-module"

**Comment by xerox95** [comment]
I found a "Qucik & Dirty" Solution:

The problem is the "json3" module.
I added in the function "runInContext" (path: json3/lib/json3.js) before: 
```javascript
context || (context = root["Object"]());
exports || (exports = root["Object"]());
```

this line:
```javascript
root = global;
```

final: 
```javascript
root = global;
context || (context = root["Object"]());
exports || (exports = root["Object"]());
```
Now it works, but is this the fine way ?
Or have i problems with the configuration of the vm ?

**Comment by nkzawa** [comment]
This one https://github.com/felixge/node-sandboxed-module ? I'm not familiar with the module that sounds the issue of vm module to me.

**Comment by xerox95** [comment]
Yep., it is the module.
What do the vm wrong ?

**Comment by nkzawa** [comment]
I'm not sure if the vm module is wrong, but I don't think we can do something to solve the problem. Can you create the issue on `node-sandboxed-module` or `json3` instead?

**Comment by xerox95** [comment]
json3 module issues: https://github.com/bestiejs/json3/issues/86
vm module issues: https://github.com/felixge/node-sandboxed-module/issues/55

**Comment by dozoisch** [comment]
I'm hitting exactly the same issue in a WebWorker. Trying to figure out a work around. The issue seems to originate from json3

**Comment by colm-mcqs** [comment]
@dozoisch cheers, looking at a workaround as well but rolling back to 1.3.7 sorted the issue for now.

:+1:

**Comment by chge** [comment]
It's `sandboxed-module` [issue](https://github.com/felixge/node-sandboxed-module/pull/61).

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
