### ISSUE TITLE
socket.io keeps constantly trying to use polling on wrong address

### ISSUE THREAD

**Issue by soend** [socketio/socket.io#2382]
Hei, i am trying to use socket.io with cross domains. For example lets say domains are: https://client.domain.com and https://server.domain.com. My client side code looks like this:
```
socket = io.connect("https://server.domain.com");
socket.on("connect", function () {
    console.log("socketio Connected to server!");
});
socket.emit("test", {"test":"test"});
```
And server side:
```
var fs = require('fs');
var https = require('https');
var express = require('express');
var socketIO = require('socket.io');
var app = express();

// Settings
var serverOptions = {
  key: fs.readFileSync('privkey1.pem'),
  cert: fs.readFileSync('cert1.pem')
};

var serverPort = 443;

// Logic
var server = https.createServer(serverOptions, app);
var io = socketIO(server);

io.on('connection', function(socket) {
  socket.on("test", function(data) {
    console.log(data);
  });
});

server.listen(serverPort, function() {
  console.log('server up and running at %s port', serverPort);
});
```
Everything works, messages get sent back and forth. But some reasone socket.io keeps trying to use polling and on wrong domain. Almost every second i see these request:
```
Request URL:https://client.domain.com/socket.io/?EIO=3&transport=polling&t=1452418594321-145
Request Method:GET
Status Code:302 OK
```
Why is socket.io doing that and how can i turn this off?

EDIT: Whats more interesting is that if i comment out all the code to do with socket.io in client side and only leave in: `<script src="https://server.domain.com/socket.io/socket.io.js"></script>` it still keeps making these HTTP requests.

**Comment by nkzawa** [comment]
do you mean requests get created even without calling `io()`or  `io.connect()`? That sounds really weird. What version do you use? I'll try to reproduce it.

**Comment by soend** [comment]
Yes, i dont have anything related to socket.io in the code and it still start making requests. 
And last thing what i didnt think is important at first is that im running the client code with tampermonkey, here's full example of one simple script i made for testing:
```
// ==UserScript==
// @name         Socketio test
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://client.domain.com/*
// @grant        none
// @require      https://server.domain.com/socket.io/socket.io.js
// ==/UserScript==

// Your code here...
var socket = io.connect("https://server.domain.com");
socket.on("connect", function () {
    console.log("socketio Connected to server!");
});
```

**Comment by nkzawa** [comment]
what version do you use?

**Comment by soend** [comment]
Socket.io version is 1.4.4

**Comment by nkzawa** [comment]
I tried to reproduce, like serving a html from `http://localhost:3001` and connecting to `http://localhost:3000` as socket.io server from 3001. But I couldn't reproduce the issue. The html includes only `<script src="http://localhost:3000/socket.io/socket.io.js"></script>`.

Does that mean it's the issue of `tampermonkey` or something?

**Comment by soend** [comment]
Maybe it has something to do with the server whats hosting the html, because this anomaly only happens with that page. If you interested to try then the address where you should run the tampermonkey script is https://www.ingress.com/ (change the @match to this address).

**Comment by nkzawa** [comment]
It looks ingress.com defines `io` as a function, so `io()` would be called wrongly even if you didn't call it explicitly. This wouldn't be a problem of socket.io.
