### ISSUE TITLE
allow to disable ping logic

### ISSUE THREAD

**Issue by titoBouzout** [socketio/socket.io#2383]
Hi there, 

The ping logic of this library is flawed, it does not work, would be possible to allow to disable it? 

For example.. people get disconnected with reason "ping time-out" after 5 second they sent a message to the server (and other people[including self] receive it) , so clearly you have no idea when the user stopped contacting the server. Can we add a setting to allow disable all the ping logic?

**Comment by nkzawa** [comment]
Unfortunately, there is no way to disable ping/pong. But instead, you'd be able to set a big number for `pingInterval` and `pingTimeout` options for now.

About ping logic, I'd like to know if you have any better ideas.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
