### ISSUE TITLE
net::err_connection_refused

### ISSUE THREAD

**Issue by iw2rmb** [socketio/socket.io#2384]
Hi!

I'm able to catch subj error but I cant' find how to supress socket.io to show this error in console as thrown. Is there a way?

**Comment by nkzawa** [comment]
I think it's how browser (chrome?) works on network error. The library can't change the behavior.
Or do you mean you'd like to establish connections successfully?

**Comment by iw2rmb** [comment]
No, I thought that it could be like when you `catch` an exception browser doesn't put error message to the console.
