### ISSUE TITLE
when client offline, server cannot get any event or callback

### ISSUE THREAD

**Issue by jasoncodingnow** [socketio/socket.io#2398]
when client suddenly offline, the server side cannot get any callback or error. Can anyone tell me if i'm wrong or this is a fatal bug?

**Comment by nkzawa** [comment]
socket.io has a heartbeat mechanism (ping/pong) for detecting dead sockets. Usually, it takes a while to detect them. You can change settings of timeouts by options. Please see https://github.com/socketio/engine.io#methods-1 (`pingTimeout`, `pingInterval`)
