### ISSUE TITLE
Why connect/disconnect and other methods are not listed in Client API docs?

### ISSUE THREAD

**Issue by jsangilve** [socketio/socket.io#2400]
``` javascript
/**
 * Disconnects from all namespaces and closes transport.
 *
 * @api private
 */

Client.prototype.disconnect = function(){
  for (var id in this.sockets) {
    if (this.sockets.hasOwnProperty(id)) {
      this.sockets[id].disconnect();
    }
  }
  this.sockets = {};
  this.close();
};
```

Those API methods are tagged as private. If they shouldn't be used, how could you disconnect a client?

**Comment by nkzawa** [comment]
Please use `Socket#disconnect(true)`. (Sorry, no doc on README)

**Comment by jsangilve** [comment]
Thank you, I'll try to do a PR later.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
