### ISSUE TITLE
socket.io server emitting 2 "on connection" events for single client

### ISSUE THREAD

**Issue by s1riedel** [socketio/socket.io#2406]
I am developing an app using socket.io and socket.io-client for server-to-server pub/sub functionality. For the most part, it is working fine, but whenever the client opens a single connection, the server emits 2 events for the socket.on('connection', function(){}) event listener. The client is receiving messages correctly, and is not getting any duplicate messages, so I am not sure why 2 events are being fired for a single socket connection, and this is making things more difficult in regards to authenticating the URL/host the connection is coming from. Code is below.

Server code:

    var app = require('express')();
    var http = require('http').Server(app);
    var io = require('socket.io')(http);

    app.get('/', function(req, res){
        res.send('Hello world');
    });

    io.on('connection', function(socket){
        console.log('a user connected');
        console.log(socket.client.conn.remoteAddress);
        console.log(socket.handshake.url);

        setInterval(function(){
            console.log('Emit');
            socket.emit('foobar', {some: 'data', here: 'bar'});
        }, 5000);
    });

    http.listen(3010, function(){
        console.log('listening on *:3010');
    });

------------------------------------------------------------------------------------------------------------------------

Client code:

    var io = require('socket.io-client');
    var socket = io('http://localhost:3010?k=foo&p=bar');
    socket.once('connect', function(){});
    socket.once('event', function(data){
        console.log('Got event');
        console.log(data);
    });
    socket.once('foobar', function(data){
        console.log('Got foobar');
        console.log(data);
    });
    socket.once('disconnect', function(){
        console.log('DISCONNECTED')
    });

    io('http://localhost:3010');

**Comment by 3rd-Eden** [comment]
You got 2 io calls in your client code. So you create 2 connections instead of one

Arnout Kazemier

**Comment by s1riedel** [comment]
@3rd-Eden Oh, well duh.. Thanks for pointing that out. That's what I get for copying and pasting!
