### ISSUE TITLE
Is there still update?

### ISSUE THREAD

**Issue by EasonWang01** [socketio/socket.io#2407]
http://socket.io/get-started/whiteboard/ this page is coming soon for one year.

**Comment by paradite** [comment]
maybe you can checkout this, I think it has some issues though: https://github.com/socketio/socket.io/pull/2103

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
