### ISSUE TITLE
Need support on Java client for socket io

### ISSUE THREAD

**Issue by sajeshMUFC** [socketio/socket.io#2411]
I am new to websockets. Please suggest me if Java client for socket io is available.
We need to send push notification from Java App server to angular app using web socket.

**Comment by josephkandi** [comment]
There's a Java client for socket.io, did you have a look at this [Socket.IO Java Client](https://github.com/socketio/socket.io-client-java)

**Comment by nkzawa** [comment]
@josephkandi thanks!

**Comment by sajeshMUFC** [comment]
@josephkandi  Thanks a ton
