### ISSUE TITLE
interval socket.emit

### ISSUE THREAD

**Issue by komarevtsevdn** [socketio/socket.io#2412]
Hi. if i write on console:
for (var i = 0; i < 100000; i++) {
    socket.emit('any_data' , 5);
}
will emit 100000 events on server.
May be socket.io have options, which can flood protect?

**Comment by rmxhaha** [comment]
Why would it need to protect itself ? 
I think this can be resolved with underscore's throttle or something similar ...

**Comment by nkzawa** [comment]
I agree with @rmxhaha. You'd be able to have your own implementations. Feel free to reopen when I'm missing something.
