### ISSUE TITLE
Simulate latency

### ISSUE THREAD

**Issue by rmxhaha** [socketio/socket.io#2413]
Is it possible for emit function to simulate some sort of latency. I can totally do this with setTimeout on every emit but I think it's too messy. I am trying to test unreliable network scenario.

Is there a way to easily hack into socket.io emit ?

**Comment by thebinarypenguin** [comment]
In Google Chrome you can...

1. open the developer tools
2. switch to device mode
3. adjust the network speed

**Comment by rmxhaha** [comment]
Thank you

**Comment by ForgeableSum** [comment]
speed != latency. Just sayin'.

**Comment by oxue** [comment]
I know this has been closed, but I don't think the developer tools actually affects websocket connections.

**Comment by Joe312341** [comment]
It does not

**Comment by oxue** [comment]
By doing setTimeout (especially with random latency) will cause messages to come out of order.
