### ISSUE TITLE
Are "ping" and/or "pong" reserved events?

### ISSUE THREAD

**Issue by thebinarypenguin** [socketio/socket.io#2414]
I have some basic code (see below) that works as expected when the events are named __ding__ and __dong__ but behaves very strangely when the events are named __ping__ and __pong__

When the events are named __ping__ and __pong__
- The server code will log the "connect" and "disconnect" messages, but not the "ping" and "pong" messages
- The client code will log the "ping" message and after a long wait (10+ seconds) will log the "pong" message, and if I keep waiting I'll get more "pong" message each 10+ seconds apart

Server Code

```js
const fs             = require('fs');
const http           = require('http');
const path           = require('path');
const SocketIOServer = require('socket.io');

const app = new http.Server();
app.on('request', (req, res) => {
  
  const index = path.join(__dirname, 'public', 'index.html')

  fs.readFile(index, function (err, data) {
    if (err) {
      res.writeHead(500);
      return res.end('Error loading index.html');
    }

    res.writeHead(200);
    res.end(data);
  });
});
app.listen(3000, 'localhost');

const io = new SocketIOServer(app);


// could also use "connection"
io.on('connect', function (socket) {
  console.log(`${socket.id} "connect"`);

  socket.on('ping', (data) => {
    console.log('Receive "ping"');
    
    io.emit('pong', {});  
    console.log('Send "pong"');  
  });

  socket.on('disconnect', () => {
    console.log(`${socket.id} "disconnect"`);    
  });
});
```
Client Code

```js
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Socket.IO Events</title>
  </head>
  <body>
    <h1>Socket.IO Events</h1>

    <script src="/socket.io/socket.io.js"></script>
    <script>
      const socket = io();

      socket.on('pong', (data) => {
        console.log('Receive "pong"');
      });

      socket.emit('ping', {});
      console.log('Send "ping"');

    </script>
  </body>
</html>

```

I have no idea what is going on here. Also this may be related to #1951

**Comment by neutrino84** [comment]
I'm seeing strange behavior while using 'ping' / 'pong' event names - there does appear to be code in socket.io that does something with ping and pong, I don't have time to investigate further - changed name to 'drip' and 'drop'

**Comment by nkzawa** [comment]
`ping` and `pong` events are used in  socket.io-client. 
please see https://github.com/socketio/socket.io-client#events

**Comment by ajhsu** [comment]
Just trapped by the 'ping' event for few hours.
I think [the official document](http://socket.io/docs/client-api/#socket) may sync up with document on GitHub?

**Comment by basilbeltran** [comment]
what a time waster. We all (including the socket.io team) had the same bad idea.
