### ISSUE TITLE
`send` not documented

### ISSUE THREAD

**Issue by adamreisnz** [socketio/socket.io#2417]
Thought I'd mention that `send` is not documented anywhere in the Client API or Server API documentation. The only mention it gets is in the overview at the bottom, where it says:

> Simply leverage `send` and listen on the `message` event

For a first time socket.io user, this is not very clear. Every method should be properly documented in the API specs.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Comment by adamreisnz** [comment]
This is a documentation issue and doesn't warrant auto closing until the documentation has been updated.

**Comment by darrachequesne** [comment]
Is there something we can improve?

* https://github.com/socketio/socket.io/blob/master/docs/API.md#socketsendargs-ack
* https://github.com/socketio/socket.io-client/blob/master/docs/API.md#socketsendargs-ack

**Comment by adamreisnz** [comment]
I was referring to the documentation on the socket.io website;

http://socket.io/docs/server-api/
No mention of `send` there whatsoever.

http://socket.io/docs/client-api/
This page results in a blank page at the moment, but the only thing it mentioned was the statement from my OP.

Is the online documentation not linked to the docs in the repository?

**Comment by darrachequesne** [comment]
Not yet!
