### ISSUE TITLE
Bug or Intended? References to SocketIO namespaces, channels, etc change meaning if referenced across async method calls

### ISSUE THREAD

**Issue by joospotter** [socketio/socket.io#2418]
I was tripped up for a few hours earlier with regards to how variables referring to Socket IO objects seem to work. 

It seems that if one binds a reference to a namespace or room (for example, "socketIO.of('/users').to('user-123)", this reference switches from being a reference to that particular object to being a reference to the entire SocketIO object if accessed from an async function (e.g., inside a Callback).

Here's an example piece of semi-code approximating what I was doing:

var targetRoom = io.of('/user-feeds').to('user-' + userId);

asyncFunction(parameter, function(error, data)
{
  targetRoom.emit('testEvent', data);
});

In this example, by the "time" targetRoom.emit is called, the targetRoom variable will be a reference to the entire socketIO object, not to the Namespace/Room that it was intended to be referring to. This leads to the unexpected result of sending a server-wide message when the code suggests it will be restricted to a single room.

However, if the targetRoom reference is bound within asyncFunction's scope, it will safely refer to the actual room rather than the entire SocketIO object:

asyncFunction(parameter, function(error, data)
{
  var targetRoom = io.of('/user-feeds').to('user-' + userId);
  targetRoom.emit('testEvent', data);
});

This is kind of unintuitive, as the identical method signatures do not make the problem immediately obvious without debugging the object doing the emit calls to begin with.

Is this a bug, or simply due to the nature of how the of, to, etc. methods return their references?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
