### ISSUE TITLE
what events will be triggered if connetion is lost (e.g. wifi down) between client and server

### ISSUE THREAD

**Issue by chicheongweng** [socketio/socket.io#2421]
I am using javascript websocket io https://github.com/socketio/socket.io

I have been scratching my head about what event will be triggered on the client and server side in case the connection is lost. Let's say the socket io client running on mobile connects to the socket server over wifi, what events will be triggered if the wifi is down? Is it 'error'? I am using version 0.9.16

**Comment by xuezhma** [comment]
Socket.io automatically sends heartbeats to check if a client is active. If the client's WiFi is down, it will keep trying to reconnect. In the meantime, the server will not kill the connection until it reaches a timeout.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
