### ISSUE TITLE
how to keep socket alive in swift 

### ISSUE THREAD

**Issue by KhaledAld** [socketio/socket.io#2423]
how to keep socket-io alive when closed applications in swift 
when applications in background or froeground the socket is still alive 
but  when application is closed the socket is closed

**Comment by ahallora** [comment]
For questions regarding the socket.io swift client please see https://github.com/socketio/socket.io-client-swift 

For background mode support on iOS please see https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html and http://www.raywenderlich.com/92428/background-modes-ios-swift-tutorial

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
