### ISSUE TITLE
Put the site's documentation on github so people can help improve it

### ISSUE THREAD

**Issue by manad777** [socketio/socket.io#2425]
The documentation is the least polished part of socket.io IMO, and would benefit from being editable by the community.

Could you put the documentation on here and accept pull requests like you do for code?

**Comment by mgold** [comment]
+1, for all the work that's gone into the code, the docs are... not great.

**Comment by volumio** [comment]
+1, it's quite obscure and there are lots of not documented functions...

**Comment by Michael77** [comment]
**+1**

**Comment by NoahAndrews** [comment]
+1

**Comment by creole** [comment]
+1

**Comment by ajhsu** [comment]
+1

**Comment by mg1075** [comment]
The documentation is _unbelievably_ cryptic.

Have to love this comment on a [stackoverflow answer](http://stackoverflow.com/questions/10058226/send-response-to-all-clients-except-sender-socket-io) where the commenter touches on the SO answer vs socket.io documentation.

> This is more useful than everything on the socket.io docs combined 

Surely there are experienced socket.io users who could improve the documentation?

Or if that will not be allowed, could the docs be updated to at least offer a collection of external resources with a more friendly look at how to understand and properly use socket.io?

**Comment by llaakso** [comment]
+1

**Comment by volumio** [comment]
As a suggestion, we're using http://daux.io/ , which in combination with travis-CI, results in a very agile and comprehensive documentation platform. 
If the team is interested, I could set it up.
You can see a couple of examples I made for other projects:
http://www.udoo.org/docs/Introduction/Introduction.html
https://volumio.github.io/docs/

**Comment by darrachequesne** [comment]
That should be fixed now, thanks. The source for the website can now be found here: https://github.com/socketio/socket.io-website
