### ISSUE TITLE
Socket.io threw err:fn.bind is not a function

### ISSUE THREAD

**Issue by zyf394** [socketio/socket.io#2428]
why does it happen and how can I fix it ? please help~

err from where:
...\socket.io-adapter\index.js:195
  if (fn) process.nextTick(fn.bind(null, null, sids));

socket.io version:
1.4.5

**Comment by davebaol** [comment]
I got the same error while trying to build the multiroom chat application from the book "Node.js in action"
````
<MY_PATH>\chatrooms\node_modules\socket.io-adapter\index.js:195
  if (fn) process.nextTick(fn.bind(null, null, sids));
                              ^

TypeError: fn.bind is not a function
    at Adapter.clients (<MY_PATH>\chatrooms\node_modules\socket.io-adapter\index.js:195:31)
    at Namespace.clients (<MY_PATH>\chatrooms\node_modules\socket.io\lib\namespace.js:253:16)
    at joinRoom (<MY_PATH>\chatrooms\lib\chat_server.js:71:32)
    at Namespace.<anonymous> (<MY_PATH>\chatrooms\lib\chat_server.js:20:5)
    at emitOne (events.js:90:13)
    at Namespace.emit (events.js:182:7)
    at Namespace.emit (<MY_PATH>\chatrooms\node_modules\socket.io\lib\namespace.js:206:10)
    at <MY_PATH>\chatrooms\node_modules\socket.io\lib\namespace.js:174:14
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
````
The issue appears if you update the dependencies to the latest versions:
````
  "dependencies": {
    "mime": "^1.3.4",
    "socket.io": "^1.4.5"
  }
```` 
while it works if you use the dependencies specified by the book
````
  "dependencies": {
    "socket.io": "~0.9.6",
    "mime": "~1.2.7"
  }
````

BTW, before commenting here, I've read the page [Migration from 0.9](http://socket.io/docs/migrating-from-0-9/#) from the socket.io site but I've not found a solution.

I can upload the simple chat project somewhere if needed (it's very small).

**Comment by CheckMater** [comment]
I checked the example in the book NodeJs in action, and of course it will not work if you use the latest versions of socket.io, you will have the 2 following lines to get it to work:

From:
`var usersInRoom = io.sockets.clients(room);`

To:
`var usersInRoom = io.of('/').in(room).clients;`

and from:
`socket.emit('rooms', io.sockets.manager.rooms);`

to:
`socket.emit('rooms', io.of('/').adapter.rooms);`

Greetings!

**Comment by A-312** [comment]
`.in(room).clients;` is function...

**Comment by A-312** [comment]
Without the [clients prototype](https://github.com/socketio/socket.io/commit/8814825a35e9af6f6b2f110aa3c0574ec7bac11a#diff-bec4836920d745d8a89d6bc6f6c59960R251) of the _commit 8814825a35e9af6f6b2f110aa3c0574ec7bac11a_ we doesn't have this issue.

Maybe : 
```
Namespace.prototype.clients = function(fn){
  if (typeof(fn) == "string") {
    this.adapter.clients(fn);
  } else {
    this.adapter.clients(this.rooms, fn);
  }
  // delete rooms flag for scenario:
  // .in('room').clients() (GH-1978)
  delete this.rooms;
  return this;
};

**Comment by ReactorboY** [comment]
thnx @CheckMater

**Comment by BeginMan** [comment]
thnx @CheckMater

**Comment by EyEder** [comment]
thnx @CheckMater

**Comment by GiovanniCst** [comment]
thnx @CheckMater

**Comment by zyf394** [comment]
thnx @CheckMater

**Comment by Fuhaustin** [comment]
Thanks man @CheckMater

**Comment by tvnhan** [comment]
thanks @CheckMater

**Comment by SailorMoonS** [comment]
thanks @CheckMater

**Comment by singlespider** [comment]
thanks @CheckMater

**Comment by MoHax22rus** [comment]
thanks @CheckMater

**Comment by thangarajks** [comment]
Thanks @CheckMater . But for me simply changing `var usersInRoom = io.of('/').in(room).clients;` didn't worked. As this clients is a function which takes a callback as a param, below snippet worked for me.

```
io.of('/').in(room).clients(function(error,clients){
		var otherUsers = [];
                for(var i in clients){
                        if(socket.id != clients[i]) otherUsers.push(nickNames[clients[i]]);
                }
                var userSummary = 'Users Currently in ' + room + ' are : ' + otherUsers.join(', ') + '.';
                socket.emit('message',{text:userSummary});
	});

```

**Comment by Santosh-Lodhi** [comment]
console.log(io.of('/').in(rooms).clients);

ReferenceError: **rooms is not defined**  :  at findClientsSocket

**Comment by chaoshenr** [comment]
thnx @CheckMater

**Comment by MilkGames** [comment]
thnx @CheckMater

**Comment by JMTK** [comment]
thx @CheckMater

**Comment by ishutrehan** [comment]
thanks @CheckMater
