### ISSUE TITLE
virus socket.io URL:mal

### ISSUE THREAD

**Issue by BlackOnix** [socketio/socket.io#2434]
Hello. Avast mark connect to socketio as a virus
what could it be?
http://prntscr.com/9zq6sc

**Comment by 3rd-Eden** [comment]
Try changing port number to something more common to internet services.

**Comment by BlackOnix** [comment]
I changed ports, it didn't help

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
