### ISSUE TITLE
socket.io-client: Object [object Object] has no method 'close'

### ISSUE THREAD

**Issue by radiofrequency** [socketio/socket.io#2435]
I just upgraded to 1.4.5 on server and client hoping it would fix this problem i've had for awhile but no luck.

Client side unhandled exception seems to be isolated to Chrome 38.0.1025 on Android 4.\* or 5.*.

reproducible here:
https://www.datememe.com/dating/united-states

browserName: Chrome Mobile
browserVersion: 38.0.1025
locale: en
osName: Android 4.2
userAgent: Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 5 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko; googleweblight) Chrome/38.0.1025.166 Mobile Safari/535.19

TypeError Object [object Object] has no method 'close' 
    ../js/socket.io.js:2421:3 d.doClose
    ../js/socket.io.js:1211:28 d.close
    ../js/socket.io.js:745:9 filterUpgrades
    ../js/socket.io.js:748:109 e
    ../js/socket.io.js:749:104 d.g
    ../js/socket.io.js:200:29 d.c
    ../js/socket.io.js:264:19 d.emit
    ../js/socket.io.js:1144:4 d.onClose
    ../js/socket.io.js:1169:15 d.onError
    ../js/socket.io.js:638:24 e.anonymous

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
