### ISSUE TITLE
The request queue

### ISSUE THREAD

**Issue by BlackOnix** [socketio/socket.io#2436]
Is it possible to create some kind of queue of requests to the server?
For example, the user sent 2 request, And the server does not start the second request until the first action does not end

**Comment by xuezhma** [comment]
Put each request under another one's call back functions like matryoshka dolls!

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
