### ISSUE TITLE
Latency Issue in Socket.io

### ISSUE THREAD

**Issue by madhan-vine** [socketio/socket.io#2437]
Hi Team,

I am using socket.io(1.3.2) and node.js((0.12.2) as middleware and Java as backend for real time trading system.

In this I am having delay in emitting the data from client. I have emitted two continuous emit from client first one reaches the server with in 2 ms and other one taking nearly 100- 150 ms to reach the server?

Example:

socket =io.connect('http://' + location.host, {'force new connection' : true,'forceNew': true });

Line1  socket.emit("test","data");--------------------------------------------takes 2ms to write server
Line2  socket.emit ("test","data");--------------------------------------takes 100ms to write server

Is this actually delay in socket.io or something else going on? 

Note: In server side I am just printing the time of each emitted data.

Thanks

**Comment by LordMajestros** [comment]
What do you mean by Java as backend? Is your websocket server implemented in Java?
As to your question, how many clients are connected to your server? Node.js is apparently single threaded so if your server was doing other things between the first and the second emit e.g. garbage collection, etc it could take a while to print out the next emit regardless of when it actually arrived. This only holds if your websocket server is implemented in javascript (node.js)

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
