### ISSUE TITLE
Socket.io Client Wait to do socket.on Function

### ISSUE THREAD

**Issue by gkio** [socketio/socket.io#2438]
hello i am trying to do a scrapping website and i send from client the url to scrap until the function is scrapping and give me an output.json file i want the socket.on from client side to wait how can i do it? and can can i say ok its done the function?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
