### ISSUE TITLE
Socket.leave doesn't work, multiple calls made when logged into new room

### ISSUE THREAD

**Issue by minusthebear** [socketio/socket.io#2440]
I am designing a chat application with an AngularJS front-end and Node.JS back-end. When I connect to a chat room every call gets sent once. Once I leave that chat room and create a new one, I receive two calls. Leave that one and create a third chat room, three calls. Etc, etc, etc.

The problem is I'm not leaving my chat room, and I have no idea why it's like this. This is my code for leaving the chat room.

```
    var rm = socket.room;
    socket.leave(rm);
    console.log("There should be no room");
    console.log(socket.room);
```

This is what I see in my console.

```
    There should be no room
    8f44e442-c444-491b-919b-5e9ba9ac338a
```

I am using Node.JS v5.6.0 and Socket.IO 1.4.5

Could the problem be how I'm joining the room? I'm doing something like this.

```
    var id = uuid.v4();
    socket.room = id;
    socket.join(socket.room);
```

**Comment by xuezhma** [comment]
I had a similar problem with angular and socket.io. Are you using ngRoute? And when you go to a different ng-view and come back to the chat view, you create a deprecate connection? 

Angular reload the controller when you switching views. It doesn't fire disconnect event to socket.io, but fire connect event only. You can disable the reloading by setting reloadOnSearch to false, and update query parameters instead of updating the path. 

If you don't want to disable the reloading.  You can keep a global variable, don't use build in connect event, fire disconnect event every time when a user  is switching views, etc..

The solution I used was to embed the view into a view and styled it to look normal, so it fires disconnect event when I switch views.

**Comment by minusthebear** [comment]
I am using ui-router, but I will try reloadOnSearch and let you know how
that works.

On Fri, Feb 12, 2016 at 3:22 PM, Xuezheng Ma <notifications@github.com>
wrote:

> I had a similar problem with angular and socket.io. Are you using
> ngRoute? And when you go to a different ng-view and come back to the chat
> view, you create a deprecate connection?
>
> Angular reload the controller when you switching views. It doesn't fire
> disconnect event to socket.io, but fire connect event only. You can
> disable the reloading by setting reloadOnSearch to false, and update query
> parameters instead of updating the path.
>
> If you don't want to disable the reloading. You can keep a global
> variable, don't use build in connect event, fire disconnect event every
> time when a user is switching views, etc..
>
> The solution I used was to embed the view into a view and styled it to
> look normal, so it fires disconnect event when I switch views.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/socketio/socket.io/issues/2440#issuecomment-183197620>
> .
>



-- 
Matthew S. Hamann

**Comment by infnada** [comment]
When you do `socket.leave(rm);` you really leave the room but the variable `socket.room` still have the String in it cos `socket.room` is initialized by you and not by socket.io.

> var id = uuid.v4();
> socket.room = id;

If you check the `socket` object with caution you can see all joined rooms for every connected socket.

`socket.room` is a simple String created by you! And `socket.leave` will not delete the content of this variable created by you.

Its like;

```
var id = uuid.v4();
socket.join(id);
socket.leave(id);
console.log(id); //8f44e442-c444-491b-919b-5e9ba9ac338a
```

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
