### ISSUE TITLE
Problem with external/internal port

### ISSUE THREAD

**Issue by YaiEf** [socketio/socket.io#2441]
WebSocketServer.cs line 614: `if (uri == null || uri.Port != _port) {`

This will fail with 400 BadRequest, if the external port does not match the internal port of the server. This can for example happen if you have multiple IPs for the server, so you listen externally on port 443 for multiple IPs with multiple services, and internally they map to different ports.

Suggestion is to either drop the port check or allow a configuration for what the external port is.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
