### ISSUE TITLE
avoid thrown error crashing server?

### ISSUE THREAD

**Issue by artofspeed** [socketio/socket.io#2443]
For some reason, sometimes I encounter the error `Lone surrogate ... is not a scalar value`. And this will make my entire app crash. By checking the detail, this is caused by an internal function in the utf8.js file:

```
    function checkScalarValue(codePoint) {
        if (codePoint >= 0xD800 && codePoint <= 0xDFFF) {
            throw Error(
                'Lone surrogate U+' + codePoint.toString(16).toUpperCase() +
                ' is not a scalar value'
            );
        }
    }
```

Is there a way to catch this error somehow in my client code, to avoid it crashing the whole server? Or else, some naughty boy could send invalid UTF string and keep crashing the server :(

**Comment by manad777** [comment]
Wow, I'd also like to know.

**Comment by darrachequesne** [comment]
Fixed by https://github.com/socketio/engine.io-parser/pull/68, included in socket.io `1.5.0`.
