### ISSUE TITLE
gevent UnicodeError

### ISSUE THREAD

**Issue by IftachSadeh** [socketio/socket.io#2446]
Hello,
(Hope that this is the correct forum to report this bug...)

I'm developing a pyramid app, using gevent 1.1rc3 and gevent-socketio 0.3.6 .
I get the following error:
```
  File "........../python2.7/site-packages/gevent-1.1rc3-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 748, in start_response
    raise UnicodeError("The value must be a native string", header, value)
UnicodeError: ('The value must be a native string', 'Access-Control-Max-Age', 3600)
<Greenlet at 0x7f23bf614b90: _close_when_done(<socket at 0x7f23be97bd90 fileno=[Errno 9] Bad fil, ('127.0.0.1', 60882))> failed with UnicodeError
```

This may be resolved by changing the line
`` ("Access-Control-Max-Age", 3600),`` to ``("Access-Control-Max-Age", '3600'),`` in the two files,
``..../site-packages/gevent_socketio-0.3.6-py2.7.egg/socketio/handler.py `` and
``..../site-packages/gevent_socketio-0.3.6-py2.7.egg/socketio/transports.py``.

Can this UnicodeError be prevented to begin with?
Thank you,

Iftach.

**Comment by IftachSadeh** [comment]
Dear Developers,

There's been no comment on this for a few months...
This is a very easy fix (changing two lines of code, as mentioned in the ticket).  Would it be possible to fix this?

Thanks,

**Comment by nkzawa** [comment]
@IftachSadeh sorry for the delay, but it seems this is the issue of python library? Please report it on their repository https://github.com/abourget/gevent-socketio.
