### ISSUE TITLE
QWebsocket

### ISSUE THREAD

**Issue by Xsmael** [socketio/socket.io#2447]
http://doc.qt.io/qt-5/qtwebsockets-index.html

Why don't you use QWebSocket class since you"re dealing with Qt ?

**Comment by manad777** [comment]
Your post isn't clear at all.

OP appears to be referencing http://socket.io/blog/socket-io-cpp , the C++ client.

I'm a big fan of Qt, but the sio team likely used Websocket++ in order not to have Qt as a dependency. Qt is a very large dependency.

The example application may have a Qt GUI, but many C++ developers won't be using Qt. They could be writing console applications, or one of the other (inferior, admittedly) UI kits.

**Comment by Xsmael** [comment]
Oh yeah you're right! Sorry of the clarity of my post... but you got it.

**Comment by Xsmael** [comment]
Because i was trying to have nodejs socket.io as a server and Qt as a client but it didn't work. I found success only with a different library: "ws"    wich is on nodejs too

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
