### ISSUE TITLE
Unhandled errors in message handlers do not bubble up to the Node process

### ISSUE THREAD

**Issue by manad777** [socketio/socket.io#2449]
(Related issue: first I'd like to re-iterate my request in #2425 to make the doc available in the repo for editing. The documentation on this project is extremely poor, and I want to help. Other people want to help. Let us help. This is the most poorly documented project of this size/popularity I've ever seen. The API has too many bad surprises to have documentation this shallow.)

I saw exceptions printed on the console, but without crashing the Node app like unhandled exceptions usually do. What I get is:

```
[[14:36:13.096]] [ERROR] Missing error handler on `socket`.
[[14:36:13.097]] [ERROR]   TypeError: _.findwhere is not a function
//stacktrace here
```

Of course, I rectified the error, but I was wondering why it didn't fail early and fail hard, like all other exceptions do. I investigated and it seems that if there's an exception in a socket handler, such as socket.on('message'), or an acknowledgement, then sio catches it and prints it to the console, without letting the exception bubble up to Node, who would have otherwise terminated the process.

I think this is a pretty major and surprising behavior, which should be documented. Furthermore, the doc never mentions the "error" socket event that we should be handling.

Here's an example which demonstrates the issue:

server.js:

```
var app = require('express')();
var server = require('http').Server(app);
var io = require('socket.io')(server);
server.listen(3000);

app.get('/', function (req, res) {
    res.sendfile(__dirname + '/index.html');
});

io.on('connect', (socket) => {
    socket.on('rpctest', function (payload, callback) {
        console.log('in rpctest handler');
        doesntexist(); //this will throw a ReferenceError
    });
})
```

index.html:

```
<script src="/socket.io/socket.io.js"></script>
<script>
  var socket = io.connect('http://localhost:3000');

  function doRpcTest() {
      socket.emit('rpctest', function(response) {
         console.log('got response'); 
      });      
  }

  setTimeout(doRpcTest, 2000);
</script>
```

The best solution would be to provide (and document) a configuration option that lets the user decide whether exceptions should be allowed to bubble up. Alternatively, if you're satisfied with the status quo, then the documentation should specify that socket handlers won't let errors bubble up In both cases, the socket reference doc at http://socket.io/docs/server-api/# should include the 'error' event.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
