### ISSUE TITLE
No .clients function for namespaces

### ISSUE THREAD

**Issue by Zunon** [socketio/socket.io#2450]
Hello, I was trying to limit the _number of people_ within a **room** inside a **namespace**, but when I try to get the number of people it throws an error.

``` javascript
io.clients('room').length
```

works but this doesn't

``` javascript
chat = io.of('/chat')
chat.clients('room').length
```

**Comment by Nibbler999** [comment]
`clients` takes a callback not a room name. See the second example at https://github.com/socketio/socket.io#namespaceclientsfnfunction

**Comment by Zunon** [comment]
Ah, I see now, is there a way to get the number of people in a specific room?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
