### ISSUE TITLE
Not compatible with Windows Server 2012 R2

### ISSUE THREAD

**Issue by benpaddlejones** [socketio/socket.io#2452]
Trying to install on Windows Server 2012 R2 64bit, gives error not compatible with OS or architecture?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
