### ISSUE TITLE
event listener fires incrementally

### ISSUE THREAD

**Issue by umair-khanzada** [socketio/socket.io#2454]
when i change state and back to again this state it'll fires incrementally 
here is code: 
socket.on('messageThread:update', function (message) {
      console.log('update');
})
my socket version is: "socket.io": "^1.0.6",

**Comment by umair-khanzada** [comment]
i solve this issue by removeAllListeners.
check for help: http://stackoverflow.com/questions/14389049/improve-this-angularjs-factory-to-use-with-socket-io/35560038#35560038

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
