### ISSUE TITLE
Redis store dev server problem

### ISSUE THREAD

**Issue by stogupd** [socketio/socket.io#2455]
Hello.
I have to work with legacy chat based on socket.io and redis store.
First i need to create dev server (copy of production).
But i cannot force socket.io to use port of dev redis server (6380) instead of default 6379. So i see messages from production chat in dev chat and when i write in dev chat - the message appears in production
The problem is i have one redisClient instance in the chat app:

```
var redis = require("redis");
var clientRedis = redis.createClient({port : 6380});
```

But socket.io creates its own instance (with default port apparently).

I tried to set port of redis store (2 variants)

1)

```
var sio = require('socket.io');
var io = sio.listen(port);
io.set("store", new sio.RedisStore);
```

2)

```
var RedisStore = require('socket.io/lib/stores/redis');
var clientRedis = redis.createClient({port : 6380});
io.set("store", new RedisStore({redisClient : clientRedis}));
```

But it does not work.
Help please!

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
