### ISSUE TITLE
a typing error in example/chat/main.js

### ISSUE THREAD

**Issue by juhongchul** [socketio/socket.io#2461]
function cleanInput (input) {
    return $('<div/>').text(input).text();
  }
is typing error;
the correct typing is
  function cleanInput (input) {
    return $('<div>').text(input).text();
  }
am i right?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
