### ISSUE TITLE
Why `io.close` closing httpServer too?

### ISSUE THREAD

**Issue by aydn** [socketio/socket.io#2462]
Is this really necessary?
`https://github.com/socketio/socket.io/blob/master/lib/index.js#L357`

This causes io server can not be closed when it initialized with http.Server
without closing the "attach"ed http.Server.

Why we need to do something like this:
`https://github.com/socketio/socket.io#serverclose`

**Comment by dsalcedo** [comment]
```javascript
// Server
  socket.disconnect() // ends client socket connection
  io.close(); // Close current server and die :c
```

io.close() not its necessary, there is an example 

CodeStrong!

**Comment by perrin4869** [comment]
+1, got tripped up by this too a while back

**Comment by fourpixels** [comment]
+1, very nasty!

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Comment by Ionaru** [comment]
Given this code:
```ts
import { createServer } from 'http';
import * as SocketIO from 'socket.io';

const httpServer = createServer();

httpServer.listen(3000, () => {

    console.log(httpServer.listening); // true

    // Bind socketIO to the same server.
    const io = SocketIO.listen(httpServer);

    console.log(httpServer.listening); // true

    io.close();

    console.log(httpServer.listening); // false

    httpServer.close((err) => {
        throw err; // Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    });

});
```

This code clearly shows that `io.close()` ALSO closes the http server!
Using socket.io 2.2.0

**Comment by aeb-sia** [comment]
@darrachequesne Just ran into this myself.
I'm running multiple endpoints on the httpServer. Now everytime I close socketio, I also close other active connections. 
It would be nice if this was configurable. So I can shutdown the httpServer myself when all connections are finished. 
My current ugly workaround is to set httpServer to undefined before calling close.
