### ISSUE TITLE
Superfluous require('socket.io-client') in index.js

### ISSUE THREAD

**Issue by salfield** [socketio/socket.io#2463]
It seems that the require('socket.io-client') in index.js is superfluous. However, it causes a problem when trying to load socket.io from jspm. This is because jspm uses the built socket.io-client.js as its "main" and this file cannot be imported outside a browser environment.

If the import can be removed, we'll be a step closer to having socket.io working in jspm.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
