### ISSUE TITLE
io.of(nsp).to(room).emit('test',{testdata: 1}); not being received

### ISSUE THREAD

**Issue by civocr** [socketio/socket.io#2464]
Hey, running 1.4.5 and when I try to emit an event triggered from a REST API call to a room, the connected sockets in the room aren't receiving the event

debug mode shows it's sending as the following
 as undefined/driver/v1 +4ms

My current work around is to find each socket in the room and emit the event to each socket

**Comment by poupougnac** [comment]
Hi, I have the exact same problem here. Namespaces and rooms are just pointless without this ability.

**Comment by dvdliao** [comment]
+1 for this issue

**Comment by darrachequesne** [comment]
Hi! How can we reproduce that issue?

**Comment by aHumanBeing** [comment]
@dvdliao how to do you emit to that particular user? Are you emitting from another namespace?  I'm facing the same situation where the message is not being sent (or received) and there are no errors.

Thanks

**Comment by dvdliao** [comment]
hey @aHumanBeing so on server side, when the client connects to this namespace, you can force the client to join a room with its room id to be the socket id of the client.
doing this will allow you to do `io.of( {namespace} ).to( {socket_id} ).emit( 'test',{testdata: 1} );` again, which is to send a message to a particular user/socket under a namespace

**Comment by aHumanBeing** [comment]
Thanks for the quick response.  Unfortunately, I'm still unable to send / receive any message directly.  Here is my situation:

```
var local = ioServer.of('/local').on('connection', function (socket) {
        socket.join(socket.client.id);
```

User 1 connected to the /local namespace with socket id: /local#RxoKAj8F6VthA8u3AAAF and socket.client.id RxoKAj8F6VthA8u3AAAF
User 2 connected to the /local namespace with socket id: /local#F-fifAIYgVy0RwJYAAAG F-fifAIYgVy0RwJYAAAG

`ioServer.of('/local').to(id).emit('chatMessage', {message: data.message}); `
where id = "F-fifAIYgVy0RwJYAAAG"

Just to confirm, the following clients connected to /local  "F-fifAIYgVy0RwJYAAAG" 0=/local#RxoKAj8F6VthA8u3AAAF, 1=/local#F-fifAIYgVy0RwJYAAAG

**Comment by dvdliao** [comment]
hmm, that should work, want to provide a little more code snippets?

**Comment by aHumanBeing** [comment]
Sure thing.  It is weird because I join other rooms (e.g. '17') in the same namespace and can emit successfully to all clients in that name space. I can't even emit to all connected clients. Anything in particular you wish to see?

**Comment by dvdliao** [comment]
are you trying to emit to a particular user or everyone under a namespace?
my above method is for a particular user, not everyone.
can i see the on connect (you provided this above) and where you are emitting with alittle code context around it, if youre talking about the emit to 1 user under a namespace

**Comment by aHumanBeing** [comment]
I want to do both actually but I'm starting with the 'particular user' scenario.
BTW, I switched from the /local name space to the default namespace to see if that helped (and since all users should be here anyway).  

~ The user connects to the local namespace, and emits  'sendMessage' from the client side. The code grabs the socketid stored in Redis and then emits 'chatMessage' back to the receiver (client side) Here is the code below:

```
var root = ioServer.of('/').on('connection', function (socket) {       
        socket.join(socket.client.id);
    });

var local = ioServer.of('/local').on('connection', function (socket) {

socket.on('sendMessage', function(data){
            winston.log('debug', 'Send message from: ' + socket.request.personCode + ' to: ' + data.receiver + ' message: >' + data.message + '<');

            if (data.receiver && data.receiver !== 'admin' /*&& data.receiver != socket.request.personCode */ && data.message !== undefined && data.message.length > 0){
                //fetch all socket ids's owned by the receiver and emit the message to each one
                repo.getUserSocketId(data.receiver, client)
                    .done(function(sockets) {
                        data.timestamp = moment().format('YYYY-MM-DD hh:mm:ss A').toString();
                        sockets.forEach(function (id) {
                            winston.log('debug', 'sending message to socket:',id);                            
                            ioServer.of('/').to(id).emit('chatMessage', {message: data.message, sender: socket.request.personCode, timestamp: data.timestamp});

                            ioServer.of('/').clients(function(error, clients){
                                if (error) throw error;
                                winston.log('debug', 'clients connected to /', clients); 
                            });
                        });

                    }, function(err) {
                        winston.log('error', err);
                        serverError(err, err);
                    });
            }
        });
    });
```

**Comment by dvdliao** [comment]
so you dont need to join on connecting to the default namespace ('/') as it should do this automatically, when joining the /local namepace, you should do the join `socket.join(socket.client.id);` and when emitting it should be `ioServer.of('/local').to(id).emit('chatMessage', {message: data.message, sender: socket.request.personCode, timestamp: data.timestamp});` this also depends on what your clientside is listening to but this is the correct serverside setup

**Comment by aHumanBeing** [comment]
You're correct about the default. I commented that block out and saw they were still connecting.
I also did as you suggested but it still doesn't work.  Just to make sure I'm not going crazy, I did the following which worked:  ioServer.of('/local').emit.....

Of course, this emitted to all users of that namespace which is not what I want.

**Comment by aHumanBeing** [comment]
According to documentation...

An example to get all clients in namespace's room:

  ```js
  var io = require('socket.io')();
  io.of('/chat').in('general').clients(function(error, clients){
    if (error) throw error;
    console.log(clients); // => [Anw2LatarvGVVXEIAAAD]
  });
  ```

My code (which resulted in nothing):
  ```js
ioServer.of('/').in(id).clients(function(error, clients){
                                if (error) throw error;
                                console.log(clients); // => [Anw2LatarvGVVXEIAAAD]
                            });
  ```

**Comment by aHumanBeing** [comment]
Downgrading to v 1.3.7, the following worked:

```js
socket.broadcast.to(id).emit('chatMessage', {message: data.message, sender: socket.request.personCode, timestamp: data.timestamp});
```

**Comment by llaakso** [comment]
Joining a room is asynchronous, so emitting to a room just after joining it won't work.

**Comment by aHumanBeing** [comment]
@llaakso In my app, there are several namespaces and any user may be connected to one of those namespaces.   What I need is the ability to send a message directly to a user regardless of what namespace they are in.  I thought that by emitting to the id it would always work since by default the user joins the default namespace.  It appears that (from v 1.3.7 above) the broadcast is to the particular namespace the socket is in (/local at the time). For whatever reason, .of(namespace).to(id) isn't working in the newer versions. By the time I start emitting, I may always be in another namespace.

**Comment by aHumanBeing** [comment]
From the client side (just in case):

```js
$(document).ready(function(){
        var socket = io();
if (permissible === true){
          socket = io('/local');
}
socket.on('chatMessage', function (data) {
          // show chat
          addTab(data);
        });
});
```

**Comment by ahmetuludag** [comment]
This may be relevant [https://github.com/socketio/socket.io/issues/2512#issuecomment-216858609](https://github.com/socketio/socket.io/issues/2512#issuecomment-216858609) if you're also using socket.io-redis.

**Comment by aHumanBeing** [comment]
@ahmetuludtag thanks for the info.  This doesn't apply since I'm not using socket.io-redis module.

**Comment by aHumanBeing** [comment]
The only ray of light it seems, is that I must emit a message for each name space (server side) when handling the client event:

```js
var local = ioServer.of('/local').on('connection', function (socket) {
socket.on('sendMessage', function(data){
...
ioServer.of('/index').to(id).emit('chatMessage', {message: data.message, sender: socket.request.personCode, timestamp: data.timestamp});
ioServer.of('/local').to(id).emit('chatMessage', {message: data.message, sender: socket.request.personCode, timestamp: data.timestamp});
ioServer.of('/remote').to(id).emit('chatMessage', {message: data.message, sender: socket.request.personCode, timestamp: data.timestamp});
...
})
})
```
This allows the client to receive the message regardless of which namespace they may be connected to at the time. Not sure why I cannot just use the default namespace only here.

**Comment by dvdliao** [comment]
You will need to make 2 io.connect() one to the default namespace and one to the '/local' namespace to achieve what youre talking about. (if i understand correctly). Dont worry about the socket connections as socketio will handle multiple connections sharing 1 socket automatically.

**Comment by aHumanBeing** [comment]
@dvdliao I'm doing this currently but I still must emit to each namespace as above.  I thought that by joining both and only emitting to the default namespace it would work but it does not.  Nevertheless, I at least have a working solution right now :)

**Comment by civocr** [comment]
I recently upgraded to 1.7.1 and this issue is still active.

`socket.io:client writing packet ["2/monitor/v1,[\"debug\",{\"debug\":{\"data\":true}}]"] +4s
  socket.io-parser encoding packet ["2/monitor/v1,[\"debug\",{\"debug\":{\"data\":true}}]"] +0ms
  socket.io-parser encoded ["2/monitor/v1,[\"debug\",{\"debug\":{\"data\":true}}]"] as undefined/monitor/v1 +0ms
  engine:socket sending packet "message" (undefined/monitor/v1) +4s
`

**Comment by civocr** [comment]
turns out I had an older version of socket.io-redis which was using an old version of socket.io-adapter.

I've updated and it works now
