### ISSUE TITLE
Proposed Feature: Batch join and leave

### ISSUE THREAD

**Issue by nathanpeck** [socketio/socket.io#2466]
Depending on the underlying adapter being used it may be much more efficient to join multiple rooms in one batch operation, rather than joining rooms one a time.

For example if you imagine a Slack like app where each user is in many channels, and each channel has its own socket.io room then on initial connection to the socket.io server you may need to do `socket.join()` for each channel the user is in. If the user is in many channels it would be much more efficient if it was possible to do a batch join operation like `socket.join(['roomOne', 'roomTwo', 'roomThree'])`.

This would be well suited for the redis adapter for example, as the redis [SUBSCRIBE operation](http://redis.io/commands/subscribe) supports multiple channels in one op.

Thoughts? Does anyone else like/need this feature?

I could easily create my own private fork with this simple feature for my own personal usage, but wanted to see if there was more general interest in adding such a feature to the mainline.

**Comment by mrbatista** [comment]
+1

**Comment by infnada** [comment]
+1 my users joins a room for each "friend" to use it as a private chat. 100 friends = 100 socket.join

**Comment by baconface** [comment]
What is wrong with looping through a list of rooms? Unless I am missing something shouldn't the below snippet of code achieve the same thing?
```javascript
var rooms = [ 'roomOne', 'roomTwo', 'roomThree' ];
for (room in rooms) {
    socket.join(rooms[room]);
}
```
or
```javascript
var rooms = [ 'roomOne', 'roomTwo', 'roomThree' ]
for (i = 0; i < rooms.length; i++) {
    socket.join(rooms[i]);
}
```

**Comment by infnada** [comment]
@baconface If you use redis/clusters can be a huge network traffic improvment in some cases

**Comment by nathanpeck** [comment]
@baconface 

This is the time breakdown for a new socket connecting to my socket.io service:

![screen shot 2016-03-04 at 1 20 42 pm](https://cloud.githubusercontent.com/assets/3495674/13536086/f2e81684-e20b-11e5-86b7-c9b51f702142.png)

On average 70% of the time is being spent sending on average 25 different `SUBSCRIBE` commands to the Redis machine. This would be hugely optimized if it sent just one `SUBSCRIBE` command with 25 channels to subscribe to, as it would reduce the network overhead of subscribing to 1/25th of what it is.

**Comment by baconface** [comment]
Gotcha. :+1:

**Comment by NguyenTungs** [comment]
Gotcha. 👍

**Comment by NguyenTungs** [comment]
@nathanpeck !
Hi There!
 I was you said : 
**I could easily create my own private fork with this simple feature for my own personal usage, but wanted to see if there was more general interest in adding such a feature to the mainline.**
 
May you help me? Please give me a idea or a suggestion. I need it for my project.
Thanks a lot.

**Comment by qeqedenq** [comment]
That is a great idea for improvement
+1
