### ISSUE TITLE
ADD SOCKET.IO to Amazon web services: elastic beanstalk

### ISSUE THREAD

**Issue by g666nz** [socketio/socket.io#2469]
Hi,

I'm relatively new to the programing cloud and node.js. Could anybody please give me a step to step guide of exactly how to upload to socket.io code onto the server and have it working so i can connect my android to it for real time data transfer.

Any help will be appreciated. Hope to hear from someone soon

Br

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
