### ISSUE TITLE
Cannot reconnect in namespace after connexion Lost

### ISSUE THREAD

**Issue by GH974** [socketio/socket.io#2474]
Hi,

After connexion in namespace, if connexion lost, socket reconnect in socket normal and not reconnect in namespace.

Can you help me ?
# Thanks

  "name": "socket.io",
#   "version": "1.4.5",

 "express": "~4.13.4",
 "express-session": "~1.13.0",

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
