### ISSUE TITLE
Add the ability to resend/re-emit a message to clients

### ISSUE THREAD

**Issue by kripod** [socketio/socket.io#2478]
Handling the re-connection of users is not as easy as it seems with today's technology. In state-based applications (for instance, turn-based card games), the last message must be resent to each client who gets reconnected.

I would like to make a proposal for resending the last message to its recipient(s): `io.to(currentSocketId).emit(...).resend(newSocketId)`

At first, this may seem like a redundant function. Although, it makes restoring client state much easier.

``` js
// Server code

let users = []; // Array of users, stored by userId as key

// Send a message to a client, and store it as the last message sent to the user
users[i].lastMessageSent = io.to(users[i].socketId).emit(...);

io.on('connection', (socket) => {
  let userId = ...; // Detect the user ID using socketio-jwt

  // Forward the previously sent message to the user's new socket
  users[userId].lastMessageSent.repeat(socket.id);
});
```

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
