### ISSUE TITLE
Client reconnect not working properly

### ISSUE THREAD

**Issue by mjasnikovs** [socketio/socket.io#2481]
```
        this.io.on('reconnect', (num) => {
            this.io.emit('transfer', {func: '/user/sessionstatus', __session__key: this.data.__session__key }, (data) => {
                if (!data) {
                    this.update(false)
                }
                MessageStore.update({type: '', msg: ''})
            })
        })
```

Event "reconnect" is working, but emit never reaches server. It's seems that longer server downtime helps, but it's never works on small updates, like quick restart.

```
var config = {
    reconnection: true, 
    reconnectionDelay: 1000, 
    timeout: 1000, 
    reconnectionDelayMax: 1000, 
    timeout: 1000 
}
```

Any options to debug whats going on? Or, help to ensure, that re-connection actually is done, and can send/receive data.

Maybe, on reconnect i shod destroy current connection and create new?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
