### ISSUE TITLE
Emit is lost

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io#2485]
io.on('connection', function(socket) {
socket.emit('info', callback)
}

Client doesn't receive 'info'. I must ask the server for info from the client, first in order to receive anything, having server code like this:

io.on('connection', function(socket) {
 socket.on('askforinfo', function(msg) {
socket.emit('info', {name: 'Peter Park' })
 });

Obviously this is undesirable. The fact is that "emit" "on connection" is bugged.

**Comment by dsalcedo** [comment]
```javascript
// client
var socket = io();
      socket.emit('info', data);
      socket.on('get_info', function(data) {
         console.log(data)
     }); 


// server
#code
io.on('connection', function(socket) {
   socket.on('info', function (data){
      socket.emit('get_info', data)
   });
});
```

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
