### ISSUE TITLE
Binary streaming

### ISSUE THREAD

**Issue by jimmywarting** [socketio/socket.io#2487]
On your homepage you announce that it's possible to send a binary stream in v1.0
<img width="470" alt="screen shot 2016-03-14 at 10 01 42" src="https://cloud.githubusercontent.com/assets/1148376/13739498/c932aabc-e9cb-11e5-812d-a9a98d9ef77f.png">

For me a stream is something that you can pipe, pause, resume and possible stream right away without getting everything back from the server.

socket.io itself is only cabitable of emiting a binary blob/buffer (not a stream)

I thought that was somewhat misleading since you also need [socket.io-stream](https://github.com/nkzawa/socket.io-stream) to make it possible to send streams

It's more like webrtc where you set `datachannel.binaryType = 'arrayBuffer'` and you are able to send a buffer, not a stream

**Comment by simoneb** [comment]
Indeed this is something I noticed and would be curious to know whether streaming is supported or planned.

**Comment by roccomuso** [comment]
+1

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
