### ISSUE TITLE
Socket.io prepends '/#' to server ids

### ISSUE THREAD

**Issue by FabioAntunes** [socketio/socket.io#2491]
I'm having a weird issue, I have just cloned a repo that was working perfectly fine, but for no aparent reason it isn't anymore.

Basically what's happening is that my socket.io server instance is prepending '/#' to the ids making them different from the client side.

So on the server side I have **/#zG3wncZxZvgRE7LKAAAA** and on the client side I have **zG3wncZxZvgRE7LKAAAA**

Also when the client is receiving a message, it's possible to see on the frames tab this:

    4undefined

This is my app.js and `config.room = fabio1`:

```javascript
    import config from './config';
    import io from './factories/io';
    
    io.on('connection', (socket) => {
      socket.join('dmClient');
      socket.join(config.room);
      console.log('socketId', socket.id);
    });
```

And this is my **/factories/io.js**
```javascript
    import socketIo from 'socket.io';
    const io = socketIo(3000);
    
    export default io;
```
More info:

 - socket.io - 1.4.5
 - node - v4.4.0

**Comment by creole** [comment]
See https://github.com/socketio/socket.io/issues/2475 and https://github.com/socketio/socket.io/issues/2405
