### ISSUE TITLE
can this be used to connect to a Kafka publisher?

### ISSUE THREAD

**Issue by dizzy0ny** [socketio/socket.io#2493]
Right now, we publish and subscribe to Kafka.  Can socket.io be used to implement pub/sub directly through kafka?

**Comment by riaan53** [comment]
I havnt tried it and its a year old but here you go: https://github.com/ghermeto/socket.io-kafka

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
