### ISSUE TITLE
socket.rooms is not an array 

### ISSUE THREAD

**Issue by hstarorg** [socketio/socket.io#2495]
In server code, socket.rooms is not an array ,that is a object.
When I use socket.join('xxx'), socket.rooms can't be set.

I will get rooms with `socket.adapter.rooms`, it's different to [api doc](http://socket.io/docs/server-api/).

**Comment by cloakedninjas** [comment]
Just checkout out a project that hasn't been updated for a few months to find this breaking change

`TypeError: socket.rooms.indexOf is not a function`

Original version was 1.3.7 so it looks like Socket.io should have gone to v2 at some point

**Comment by Jokero** [comment]
@rauchg ping

**Comment by magicdawn** [comment]
`socket.adapter.rooms` is all rooms. haha
`socket.join('xxx')` is a asynchronous, just get `socket.rooms` in the callback ...

**Comment by magicdawn** [comment]
And in the document on socket.io website. it's still 
> `socket.rooms` is an Array

**Comment by hstarorg** [comment]
@magicdawn callback will be called on join room succeed.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
