### ISSUE TITLE
io.emit in while loop

### ISSUE THREAD

**Issue by bkvaiude** [socketio/socket.io#2497]
Need a help to understand the behaviour of socket.io

`while(condtion){`
`//do computation`
`//if condition true`
`//io.emit('update the result on web page', result);//it will get called on particluar condtion`
`}`

but it seems client received all signals on while loop completion.

I am not able to show progress on the web page, as client receiving all signal at same time.

Can someone please explain what is happening?

**Comment by LordMajestros** [comment]
I think some sort of buffering is going on.
Please note  that io.emit will emit the result to all clients and this might take a while.
It's ok if that is what you intend.

**Comment by LordMajestros** [comment]
The emit function probably uses some form of deferred execution like `process.nextTick` to send data.
So your data gets sent before I/O or timer events and after execution of the current script.
Instead of using a while loop try 
```
function computationFunction(){
    //do computation
    //if condition true
    //io.emit('update the result on web page', result)
}
setInterval(computationFunction,5000);//5 seconds
```

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
