### ISSUE TITLE
Socket looses its variables upon connecting different namespace

### ISSUE THREAD

**Issue by ZoeLove** [socketio/socket.io#2498]
I have declared few variables on server to hold information about user as ,

```
// Server script
io.on('connection' , function(socket) {
socket.on('adduser' , function(username) { 
   socket.username = username ;
} ) ;
// This works fine till i connect to different namespace
} ) ;
```

Now if i connect to different namespace , socket.username gets destroyed resulting undefined.

**Comment by darrachequesne** [comment]
Hi! The sockets (of the same client but within different namespaces) are indeed independent from each other.

I guess you could store the username in the underlying `client` (`socket.client`).
