### ISSUE TITLE
file:// null Origin

### ISSUE THREAD

**Issue by lobovkin** [socketio/socket.io#2503]
Hello. This code require 'null:*' or 'null:80' in allow list, it is unclear.
[index.js#L60](https://github.com/socketio/socket.io/blob/master/lib/index.js#L60)

```
// file:// URLs produce a null Origin which can't be authorized via echo-back
  if ('null' == origin || null == origin) origin = '*';
```

My way to do it better:
`
if ('null' == origin || null == origin) return fn(null, true);`

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
