### ISSUE TITLE
io.of(nsp).to(socketId).emit cannot seem to take an Acknowledgement function

### ISSUE THREAD

**Issue by Kay-Zee** [socketio/socket.io#2505]
When I call `io.of(nsp).to(socketId).emit('eventName', data)`, everything works as expected, however, when I add an acknowledgement function:

``` js
io.of(nsp).to(socketId).emit('eventName', data, function() {
  console.log('test');
});
```

does not seem to send the event at all.

``` js
io.of(nsp).connected[socketId].emit('eventName', data, function() {
  console.log('test');
});
```

seems to work just fine though.

**Comment by natelaws** [comment]
`.to()` should be to a room name, not a socketId.

See http://socket.io/docs/server-api/#socket#to(room:string):socket

**Comment by darrachequesne** [comment]
`.to(socketId).emit` does send a message to the room named `socketId` (which is, in that case, the room created for the given socket), but, quoting the [source](https://github.com/socketio/socket.io/blob/master/lib/socket.js#L138):

> Callbacks are not supported when broadcasting :angel:

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
