### ISSUE TITLE
use promise in tests?

### ISSUE THREAD

**Issue by tw0517tw** [socketio/socket.io#2510]
I've seen many these setTimeout functions in tests.

``` js
      setTimeout(function() {
        expect(counter).to.be(1);
        done();
      }, 200);
```

Maybe we could use promise on these scenario to prevent timeout failing on bad performance machine/platform?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
