### ISSUE TITLE
Socket crash RangeError: Invalid string length

### ISSUE THREAD

**Issue by chatcoder** [socketio/socket.io#2511]
socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:434
      strLen += '' + bufferTail[i];
              ^
RangeError: Invalid string length
    at Object.exports.decodePayloadAsBinary 

Any assistance, this is constantly happening now?

**Comment by nkzawa** [comment]
Hi, thanks for your report. Do you know how to reproduce the issue ?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
