### ISSUE TITLE
Console errors: failed: Connection closed before receiving a handshake response

### ISSUE THREAD

**Issue by RTBathula** [socketio/socket.io#2513]
Hi socket.io Team, i am seeing this error in my console,?EIO=3&transport=websocket&sid=Rooo1KswdiFN2ePeAACM' failed: Connection closed before receiving a handshake response

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
