### ISSUE TITLE
Error: got binary data when not reconstructing a packet

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io#2517]
I got this errors when opening page that uses socket.io client on iPhone, specifically iPhone and iPad with iOS < 9. Is there any solution for this?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
