### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by colby-ham** [socketio/socket.io#2522]
There is a spelling mistake on the page http://socket.io/download/ 
Instead of "practical" it says "If you want to learn how to use Socket.IO through **pratical** examples, head to Get Started."

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
