### ISSUE TITLE
io.to(id).emit() sends to wrong socket when disconnected

### ISSUE THREAD

**Issue by llaakso** [socketio/socket.io#2524]
I encountered following case:

io.to(id).emit('message')
id disconnected
message was delivered to another socket

So it seems that if disconnect fires just after calling emit the handling of sockets are inconsistent. (Maybe array index is then out of date?)

**Comment by darrachequesne** [comment]
Hi! Which version of socket.io are you using? Could you provide some code please?

**Comment by llaakso** [comment]
v. 1.4.4

I'm afraid I am not able to provide any code which could do any help. But I'm quite confident that it isn't my code as just after it happened I checked the related users of socket ids. As there was synchronous code where my server logs "send to user x" until io.to().emit that must be correct (socket ids are saved under user). And afaik that is asynchronous call, disconnect event just after emit messed something up.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
