### ISSUE TITLE
Interesting scaling problem with Socket.io and Cluster

### ISSUE THREAD

**Issue by mminchev** [socketio/socket.io#2528]
Hi guys,

We run a Node.js based chat application. Currently, we use the cluster module to create several workers and each of them uses socket.io to accept user connections. We use the Redis store and so far everything scales fine except one thing.

Every time a worker dies/crashes, its state is lost. When a new worker is created it does not know about any sockets that have been created (on other workers) before it has been forked. This is because the Redis store syncs sockets as they arrive but does not syncs the "history".

This is a big problem because users which connect to the new worker cannot send messages to users who have connected to some of the other workers before the creation of the new worker.

How can we solve this problem? How can a new worker get info about all the sockets that were active before its creation?

Btw, we are using socket.io 0.9.17 and Node.js 0.12.7.

As far as I can see, this is a problem also in newer versions of socket.io > 1.0 with the Redis adapter, right?

Thanks!

**Comment by jaider2523** [comment]
Hi @mminchev  i have the same problem when run my app in cluster.... any solution ?

**Comment by mminchev** [comment]
Hi, @jaider2523! 

No, I do not have a real solution yet. The only short term solution is to always restart socket.io instances together, so they have uniform data about sockets. Unfortunately, this is not always possible.

Did you find any solution?

**Comment by MasterJames** [comment]
Can't you store that info in redis? Then it's absorbed or ingested from redis by the new socket fork and new events sent out as needed to notify or confirm available connections.

**Comment by jaider2523** [comment]
@mminchev  Hi!, yes i found one solution for this. 

The solution is redis.  In your file index.js (Example)
Put:

import socketio from 'socket.io'   (es6)
import redis from 'socket.io-redis' (es6) Magic package

const io = socketio(server)

io.adapter(redis({ host: 'localhost', port: 6379 })) // the solution

io.on('connection', (socket) => {
  // Code
])

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
