### ISSUE TITLE
Duplicate events being fired upon server restart

### ISSUE THREAD

**Issue by EduardJS** [socketio/socket.io#2529]
[http://i.imgur.com/TUJr3yf.png](http://i.imgur.com/TUJr3yf.png)

I have 2 clients connected with some debugging and I'm broadcasting two events uppon connection and one on disconnect.

Upon connection:
1 - broadcast to all users ( aside the current one ) the "member_joined" event.
2. broadcast to socket.id ( current user ) the "member_list" event so I can show what users are already online.

Upon disconnect:
1. broadcast to all users aside current one, the `member_left` event so others are aware of it.

Now that I have two clients connected, the events are triggered as many times as the server has been restarted. Look at that image.

My thought was .. to try and disconnect the client from all rooms or something upon server being restarted. Is that possible ?

I see people experiencing the same issue. What am I doing wrong ?

This is my small server code. Works fine but upon server restart, everything gets fired multiple times:

```javascript
var clients = [];

io.on( 'connection', socket => {

	user.getUserData( socket.handshake.userId, account => {

		console.log( 'device connection accepted', account.id, socket.id );
		clients.push( account.id );

		socket.on( 'subscribe', channel => {

			socket.join( channel );

			if ( channel == 'presence' )
			{

				socket.broadcast.to( 'presence' ).emit( 'member_joined', account.id );
				io.to( socket.id ).emit( 'member_list', clients );

			} else
				console.log( account.id, 'subscribed', channel );

		});

		socket.on( 'disconnect', () => {

			clients.splice( clients.indexOf( account.id ), 1 );
			socket.broadcast.to('presence').emit( 'member_left', account.id );

		});

		console.log( clients );

	});

});
```

**Comment by EduardJS** [comment]
Nevermind guys. The issue was because upon server being restarted, the sockets try `reconnecting` therefore the events `this.socket.on( event, this.events[ type ][ event ] )` assigns the method as many times as the `connect` has been triggered ( number of connections lost / server restarts ). Therefore I've added another if which avoids assigning another event with the same name:

```javascript
for ( var event in this.events[ type ] )
	if ( !this.socket._callbacks[ '$' + event ] )
		this.socket.on( event, this.events[ type ][ event ] );
```

**Comment by J6K** [comment]
@EduardJS 

`io.on('connection', (client) => {
  client.removeAllListeners();
  log('client connected');
  const { roomId } = client.handshake.query;
  const room = rooms.findOrCreate(roomId || 'default');
  client.join(room.get('id'));


  each(clientEvents, (handler, event) => {
    if (!client._events || !client._events[event]) {
      client.on(event, handler.bind(null, { io, client, room }));
    }
  });
});`

I've tried controlling the re-attachments of listeners as well as removing listeners but it still sends duplicate events. Is there any other reason for this?
The clientsCount always reflects the correct number of clients too.

**Comment by moustafaart4muslim** [comment]
When I tried doing something like yours, it stopped working for me.

The working for is is to detach event listener before attaching it: 
            socket.off('chat message');
            socket.on('chat message', function(msg){  
            ...
so if the event is attached such like reconnect, it's detached then attached, worked fine for me.
