### ISSUE TITLE
socket.io down

### ISSUE THREAD

**Issue by kennetpostigo** [socketio/socket.io#2531]
Hello,

I attempted going to the socket.io site and it appears to be down. Just opening this to notify in case it is not known.

**Comment by cviebrock** [comment]
I was on yesterday and it was fine.  However, it's down again now (27 Apr 2016 14:40 GMT).

**Comment by weisjohn** [comment]
Down again

**Comment by puradox** [comment]
I can confirm that it is down again, and was up yesterday

**Comment by sneakyfildy** [comment]
Error establishing a database connection for me

**Comment by asifalikhokhar** [comment]
It is down again. 
**Error establishing a database connection**

**Comment by Viral-Inc** [comment]
downnnn

**Comment by yigitsayan** [comment]
**Error establishing a database connection**

**Comment by rhessinger** [comment]
It is very inconsistent on it's up time.  If i refresh enough times it starts working again.

**Comment by Modulus** [comment]
It is still down. Please fix this...
Error establishing a database connection

**Comment by zerkms** [comment]
socketio is not web scale

**Comment by TawabG** [comment]
The website is down once again ( May 6th ) 
"http://socket.io/docs/" -> Error establishing a database connection

**Comment by djaonourside** [comment]
The same problem. The http://socket.io doesn't work (May, 8th)

**Comment by musou1500** [comment]
Hello.
It appears Bad Gateway...
(May, 9th)

**Comment by FoghostCn** [comment]
502 Bad Gateway

**Comment by jaroslav-kubicek** [comment]
same here, is there any update?

**Comment by TropicSapling** [comment]
Error establishing a connection a couple of days ago, now it says 502 Bad gateway :/

**Comment by TropicSapling** [comment]
Website seems to be up again :)
Close issue?

**Comment by JonNode28** [comment]
This needs to be reopened

**Comment by mishaor** [comment]
Today it's returning a 502 error
