### ISSUE TITLE
QUESTION: Change something on browser to something on client

### ISSUE THREAD

**Issue by XtremePlayzCODE** [socketio/socket.io#2535]
Client code:
`var socket = io.connect("ws://127.0.0.1:8080);`
`var count = 10;`
`socket.on("requested", function() {`
`    // Change var on browser to count`
`}`
Browser script code:
`var socket = io.connect("ws://127.0.0.1:8080);`
`socket.emit("requested"), {});`
`$("count").replace("<p>Count: " + (the count from client variable))`

How do I add a variable "count" on the browser script to have the same value as "count" from the client script?

**Comment by darrachequesne** [comment]
Hi! The following should work:
```javascript
// client
socket.emit("requested", function (c) {
  console.log(c);
});
// server
socket.on("requested", function (fn) {
  fn(count);
}
```
