### ISSUE TITLE
Emitting to all and specific clients

### ISSUE THREAD

**Issue by aHumanBeing** [socketio/socket.io#2536]
Hello,

Express app using npm to install modules.  Currently, I'm using socket.io v 1.3.5. I can emit to name spaces but trying to emit to all clients results in no errors and no messages sent.  Also, trying to emit to specific clients is the same behavior.  Should I upgrade to a newer version of socket.io?  If so, which one? I've tried multiple ways to emit messages but wanted to ask after reading some threads from a few months back.

Thank you for you time

**Comment by aHumanBeing** [comment]
#2464

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
