### ISSUE TITLE
Get namespace

### ISSUE THREAD

**Issue by JonattanV** [socketio/socket.io#2537]
Hello, One question is possible to obtain the namespace?

![socket](https://cloud.githubusercontent.com/assets/6434948/15004153/1af6d452-1179-11e6-8e1f-2505970fe03b.png)

**Comment by leemason** [comment]
+1 I really need to know this as well

**Comment by JonattanV** [comment]
+1

**Comment by darrachequesne** [comment]
`socket.nsp.name` should work :angel:

**Comment by JonattanV** [comment]
socket.nsp.name => '/'
