### ISSUE TITLE
socket.io website is down.

### ISSUE THREAD

**Issue by LeonFedotov** [socketio/socket.io#2541]

**Comment by pjaleeuwen** [comment]
I've been trying socket.io several times last week, I can never reach it. 👎

**Comment by matesk8** [comment]
I also can't reach the website.

**Comment by TropicSapling** [comment]
Same here :/

**Comment by Modulus** [comment]
The site is down again! http://socket.io/docs/client-api/
502 Bad Gateway

nginx/1.5.11

What on earth is going on? The client is pondering on leaving socket.io behind, since the site is always down and we cannot access the docs. This simply looks bad guys....

**Comment by darrachequesne** [comment]
A temporary solution :angel: 

http://webcache.googleusercontent.com/search?q=cache:http://socket.io/docs/

**Comment by TropicSapling** [comment]
@darrachequesne Tried that myself too but now it seems website is working again?

**Comment by LeonFedotov** [comment]
Working again.

**Comment by sebringj** [comment]
Well its 2017 and its down again.

**Comment by jakesa** [comment]
I haven't been able to get to it all week. Keep getting ERR_CONNECTION_TIMED_OUT

**Comment by lracicot** [comment]
It have been down for a while now. Can anybody fix this ?

**Comment by venku122** [comment]
I've also been having issues connecting to the site. Last week, I briefly had an issue with the cdn pulling client side code...

**Comment by TheHyphen** [comment]
Someone please fix this. What could be the reason...? Should we wait for it to be live? I'm using Google Cached content right now. Life Saver.

**Comment by EricBalingit** [comment]
#2870

**Comment by ashwiny66** [comment]
its still down ..

**Comment by TropicSapling** [comment]
Not anymore 😄

**Comment by dangreenisrael** [comment]
Down again 😞

**Comment by TropicSapling** [comment]
:disappointed: Why does this keep happening?

**Comment by deisemelo** [comment]
Down again, sad life.

**Comment by justinyanme** [comment]
Down agin🤦‍♂️

**Comment by venku122** [comment]
Is it possible to get the documentation files and run backup web servers? I'd be up for hosting a limited web server to at least provide some access to the docs for people.

**Comment by LeonFedotov** [comment]
A simple gh page with everything is a good idea
-- 
Leon. Everything web.
leonfedotov.com

**Comment by darrachequesne** [comment]
That should be fixed now, thanks. The source for the website can now be found here: https://github.com/socketio/socket.io-website

**Comment by venku122** [comment]
Hosting the website repo here. Let me know if this rehost is ok as a backup.

http://backup.socketio.app.csh.rit.edu/

**Comment by karikalanarun** [comment]
again website is down

**Comment by venku122** [comment]
@karikalanarun http://backup.socketio.app.csh.rit.edu

**Comment by TropicSapling** [comment]
Atleast it says an error this time (502)

**Comment by hellenfc** [comment]
Website down. **502**

**Comment by CzechErface** [comment]
I hope this is not indicative of the quality of socket.io...

**Comment by hamilton-lima** [comment]
![image](https://user-images.githubusercontent.com/2771784/30839236-9598b976-a23e-11e7-8f1b-f504ab7d7fd3.png)
Still down.

**Comment by sathishstar** [comment]
The socket website is down, But there is website of socket **http://backup.socketio.app.csh.rit.edu/**

**Comment by darrachequesne** [comment]
It should be up again, sorry for the inconvenience.

**Comment by adamdry** [comment]
The site is down `503 The deployment is currently unavailable.`

**Comment by TropicSapling** [comment]
Why does this keep happening?

**Comment by darrachequesne** [comment]
The site is hosted on now.sh, which is currently experiencing issues... Status here: https://mobile.twitter.com/zeit_status

**Comment by darrachequesne** [comment]
That should be fixed now, sorry for the inconvenience.

**Comment by tjtarazevits-jstar** [comment]
Backup site is now hosted at http://backup.socketio.a.csh.rit.edu/ 

It should auto-update based on commits to `master`
