### ISSUE TITLE
socket server namespace disconnect(3g to wifi)

### ISSUE THREAD

**Issue by Ivanpaz91** [socketio/socket.io#2542]
Using socket io. but eventually got "server namespace disconnect" reason when disconnect.
From that time, server and client can't send / receive any data.
What should i do.? should i use socket.disconnect() on server side at that time?

**Comment by liuming3** [comment]
ps: sometime i got "client namespace disconnect" reason when disconnect event on server.
What should I do on that case.
current namespace is default.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
