### ISSUE TITLE
Error - "failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1

### ISSUE THREAD

**Issue by tomasvts** [socketio/socket.io#2543]
I'm facing this weird error since last week which is specific to some Windows 10 versions.

Its weird, as this error has arisen in a system which has been working fine since last 3 years (including windows 10 pc).

Error - "failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1 " [ hence cannot connect to server ] 

**Server machine:**
socket.io: "1.3.7"
socket.io-client: "1.3.7"
OS - Windows 10 Home Edition
Browser - Latest Chrome (v50)
Node - v4.4.0

My client connects *directly* to the socketio server to get the socketio client and then upgrades to use a regular websocket connection.

I do know that some people have solved the problem updating nginx. Like this one: http://stackoverflow.com/questions/37063442/websocket-connection-failed-one-or-more-reserved-bits-are-on-reserved1-0-re
But I do not use nginx. I connect directly to the socketio server.

**Comment by sobtiankit** [comment]
Some of our Windows users are facing the same issue. Any ideas?

**Comment by tomasvts** [comment]
First discard the nginx problem. 
If you use nginx, apply this solution http://stackoverflow.com/questions/37063442/websocket-connection-failed-one-or-more-reserved-bits-are-on-reserved1-0-re

**Comment by sobtiankit** [comment]
Thanks @tomasvts. I dont think this is the problem in our case, but will confirm to eliminate.

**Comment by Aur0r** [comment]
Maybe this is not a solution to your problem but you could check the following.

I had also the same problems (Windows 10 and no working websocket connections) and I realised that it didn't matter which websocket implementation was in use. So I search a bit and also found this thread. Then I looked at the recently installed windows updates but none of them were of a type that they could be the cause for this issue.

So I searched again and found this site [Link](https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=0ahUKEwj_7tnSgc7MAhWLuhQKHff1AOMQFgg2MAM&url=http%3A%2F%2Fforum.sc2tv.ru%2Fthreads%2F12116-%25D0%25A7%25D0%25B0%25D1%2582-%25D0%25B1%25D0%25B0%25D0%25B3%25D0%25B8-%25D0%25B8-%25D0%25BF%25D1%2580%25D0%25B5%25D0%25B4%25D0%25BB%25D0%25BE%25D0%25B6%25D0%25B5%25D0%25BD%25D0%25B8%25D1%258F%3Fp%3D2710775&usg=AFQjCNGCvnG-FH1yK_CSJYy0tFT1sAciuA&sig2=d1om4jIbz8kXTGMvhriqpw) which was actually a forum that seems like it is russian or something similar and translated that via google translate. Then I found the issue for me. I use eset nod32 antivirus software and there is also an option for filtering web protocols.
As described in the forum post I deactivated the following setting. Right-click on the tray icon -> advanced settings -> Internet & Email (or Web & Email) -> And then deactivate the checkbox "Check application specific protocols".

Now I know this might not be the ideal solution but at least I know now how to workaround this issue for now.

However I will contact the eset support as soon as I have time to do so.
Hope this helps others as well in the meantime.

**Comment by tomasvts** [comment]
That was it! Thanks so much for sharing with everyone!

Closing this issue now
