### ISSUE TITLE
socket.io on https cannot be connected during Mocha test

### ISSUE THREAD

**Issue by derekshi** [socketio/socket.io#2546]
I am not sure whether it is an issue on socket.io or Mocha. My apps works when socket.io on https. However during test, socket.io on https cannot be connected. 

```
const https = require('https');
const app = require('express')();
const server = https.createServer(OPTIONS, app) //OPTIONS include key and cer for ssl certificates;
const PORT = 8443;
const io = require('socket.io');

describe('Socket', () => {
  const TEST_CHANNEL = 'pusher-client-channel-test';

  const options = {
    transports: ['websocket'],
    forceNew: true,
  };

  before(done => {
    io.listen(server);
    server.listen(PORT, () => {
      console.log(`Pusher server is listening at ${PORT}`);
      done();
    });
  });

  it('can connect clients', (done) => {
    const client = io.connect('https://localhost:8443', options);

    client.on('connect', (data) => {
      console.log(data);
      client.emit('subscribe', TEST_CHANNEL);
    });
  });
});
```

The problem that 'connection' event on server never gets called. However, if I use 'http' instead of 'https' with the same codes, everything works fine. Any ideas?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
