### ISSUE TITLE
Cross Origin Requests for Polling Transport Results in a Bad Request

### ISSUE THREAD

**Issue by brodeuralexis** [socketio/socket.io#2547]
EDIT: Just in case someone was wondering, but when launching the Socket.IO server in local, everything works as expected.

I have been trying to get a Socket.IO server working through a nginx proxy in order make a small chat application for a school assignment, however, the client makes a lot of XHR ending with a 400

![network-requests](https://cloud.githubusercontent.com/assets/11179144/15266231/4797ad42-196c-11e6-8e49-700e25ebfc07.PNG)

Though it seems like Engine.IO is processing them

![console-debug](https://cloud.githubusercontent.com/assets/11179144/15266242/b8a26eaa-196c-11e6-900b-a8da66468fc6.PNG)

My client is running in local and [here](https://gitlab.brodeuralexis.com/brodeuralexis/chat-react/blob/develop/src/modules/backend.js#L14) is where I create the connection, and the code for the server side is available [here](https://github.com/brodeuralexis/socket-io-chat) and deployed at `chat-socket-io.brodeuralexis.com`.

Here is my nginx configuration:

``` nginx
upstream backend {
    server 127.0.0.1:3000;
}

server {
    listen 80;

    access_log /var/log/nginx/chat-socket-io.access.log;
    error_log /var/log/nginx/chat-socket-io.error.log;

    server_name chat-socket-io.brodeuralexis.com;

    large_client_header_buffers 8 32k;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;

        proxy_buffers 8 32k;
        proxy_buffer_size 64k;

        proxy_pass http://backend;
        proxy_redirect off;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
