### ISSUE TITLE
uncaughtException: Error: read ETIMEDOUT

### ISSUE THREAD

**Issue by Foltos2016** [socketio/socket.io#2548]
I have node 4.4.0

but sometimes (1-2-3 days after) get error:

uncaughtException: Error: read ETIMEDOUT\n    at exports._errnoException (util.js:870:11)\n    at TCP.onread (net.js:550:26)

How to fix?

**Comment by zoell** [comment]
Same here.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
