### ISSUE TITLE
How to detect if client is being overrun with messages?

### ISSUE THREAD

**Issue by manad777** [socketio/socket.io#2550]
I have an app where I can send a lot of individual messages every second or so.

If the client is unable to cope with the stream of incoming messages, for example due to a slow network link, is there any way to detect this at the server level? I could then take corrective measures, such as only sending the most critical data.

I looked at the doc and there's no metric like "queued but unsent messages" on the socket that I could track over time to properly address flow problems.

**Comment by wonderdogone** [comment]
Maybe you could attempt to use this to confirm that client received the message
http://socket.io/docs/#sending-and-getting-data-(acknowledgements)

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
