### ISSUE TITLE
Warning if using reserved ping and pong events.

### ISSUE THREAD

**Issue by RainingChain** [socketio/socket.io#2551]
There should be a warning/error message when trying to subscribe to the newly reserved `ping` and `pong` events. 

There is no way to tell the subscription failed other than the fact that the callback is never called.

I've recently migrated to the latest socket.io version and my code wasn't working correctly because of that.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
