### ISSUE TITLE
client-side disconnect is not detected

### ISSUE THREAD

**Issue by iamisti** [socketio/socket.io#2553]
Hi guys,
I'm raising this ticket because it seems another ticket had been closed but the issue didn't get resolved.
Here is the issue, I don't want to write it down here to prevent duplication: https://github.com/socketio/socket.io/issues/635

Can you guys assist and help us fixing the problem?

**Comment by alexcroox** [comment]
Same, if my socket.io server crashes but recovers without properly restarting the process it detects the client has disconnected, but on the client side it still thinks it's connected.

None of the following are triggered:

```
socket.on('disconnect');
socket.on('error');
socket.on('connect_error');
socket.on('connect_timeout');
```

**Comment by lunzhang** [comment]
Are you guys running the socket server locally?

**Comment by lunzhang** [comment]
Are you guys running the socket server locally?

**Comment by alexcroox** [comment]
Yes

**Comment by lunzhang** [comment]
I thought I had the same problem of not being detected but when I tested by setting an interval in the server to emit.  I found that the client side was never disconnected and was still receiving the emits.

**Comment by Hemanshu1belani** [comment]
I'm facing the same issue. Any updates or workaround?

**Comment by ashleymorris2** [comment]
I have the same issue.

**Comment by darrachequesne** [comment]
Could you check if https://github.com/socketio/socket.io/issues/635#issuecomment-266880918 solves your issue?
