### ISSUE TITLE
Should namespace connections really fail here if not previously declared?

### ISSUE THREAD

**Issue by leemason** [socketio/socket.io#2555]
https://github.com/socketio/socket.io/blob/master/lib/client.js#L64

if you take a look here we are enforcing an existing namespace when a client connects, i see the logic, but this does allow for dynamic or "after the fact" namespaces.

for example im using socket.io to work with laravel via redis and namespaces as "channels".

to remove the need to declare the "channel/namespace" in two locations (laravel and socket.io) it would be really nice if this just used `this.server.of(name);` or at least had the option too so if the namespace doesnt exist, it creates it rather than erroring out.

would you accept a pull request for this? either as optional or default behaviour.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
