### ISSUE TITLE
WebSocket connection to failed: Invalid frame header

### ISSUE THREAD

**Issue by littleguga** [socketio/socket.io#2557]
```WebSocket connection to 'ws://10.1.30.58/socket.io/?EIO=3&transport=websocket' failed: Invalid frame header```

server debug:
```
 socket.io:server incoming connection with id 7hnvZ1RkTsCgjyVVAAB- +4ms
 socket.io:client connecting to namespace / +3ms
 socket.io:namespace adding socket to nsp / +1ms
 socket.io:server incoming connection with id gOcFr2YHNcmSF9hqAAB_ +2ms
 socket.io:client connecting to namespace / +2ms
 socket.io:namespace adding socket to nsp / +1ms
 socket.io:namespace next called after client was closed - ignoring socket +74m

 socket.io:namespace next called after client was closed - ignoring socket +2ms

 socket.io:namespace next called after client was closed - ignoring socket +1ms

 socket.io:namespace next called after client was closed - ignoring socket +2ms

 socket.io:namespace next called after client was closed - ignoring socket +2ms

 socket.io:namespace next called after client was closed - ignoring socket +1ms
```

On client side:
`var socket = io({transports: ['websocket']}); //socket.io`

What's wrong?

**Comment by littleguga** [comment]
Server debug:
```
 socket.io:server incoming connection with id 1fX2a9tSW67s86bOAAAd +630ms
 socket.io:client connecting to namespace / +1ms
 socket.io:namespace adding socket to nsp / +1ms
 socket.io:server incoming connection with id ElBX5J56jGg2AL-RAAAe +3ms
 socket.io:client connecting to namespace / +2ms
 socket.io:namespace adding socket to nsp / +1ms
 socket.io:client client close with reason transport close +2ms
 socket.io:client client close with reason transport close +1ms
 socket.io:server incoming connection with id JM1_bp5eVOvNlyC-AAAf +2ms
 socket.io:client connecting to namespace / +2ms
 socket.io:namespace adding socket to nsp / +1ms
 socket.io:server incoming connection with id 5kOM-EtYOCmRrgZ7AAAg +4ms
 socket.io:client connecting to namespace / +2ms
 socket.io:namespace adding socket to nsp / +0ms
 socket.io:namespace next called after client was closed - ignoring socket +4ms

 socket.io:namespace next called after client was closed - ignoring socket +5ms

 socket.io:namespace next called after client was closed - ignoring socket +2ms

 socket.io:namespace next called after client was closed - ignoring socket +1ms
```

**Comment by littleguga** [comment]
On network tab
![image](https://cloud.githubusercontent.com/assets/12018713/15436696/f062a4ea-1ecb-11e6-937c-7a621e05b92d.png)

**Comment by littleguga** [comment]
On client:
![image](https://cloud.githubusercontent.com/assets/12018713/15440666/761c0dd4-1edf-11e6-9d26-281dc01def80.png)

On server:
``` js
var http = require('http'); //http module from node.js
var staticserver = require('node-static'); //http server for serving static files

//Create static serving server from 'client' folder
var file = new staticserver.Server('./client');

server = http.createServer(function (request, response) {
    request.addListener('end', function () {
        //
        // Serve files!
        //
        file.serve(request, response);
    }).resume();

    //Start socket.io server
    startSocket();
}).listen(port);

var options = {
    pingTimeout: 3000,
    pingInterval: 3000,
    transports: ['websocket'],
    allowUpgrades: false,
    upgrade: false,
    cookie: false
};
io = require('socket.io')(server, options);
```

**Comment by littleguga** [comment]
I used `node-static` for serving files, with it socket.io doesn't work. With express or default node(http) it works.

Here an example: https://github.com/littleguga/websocket-test

**Comment by rizkiaditya24** [comment]
@lgg is this issue solved? I have got the same problem

**Comment by lgg** [comment]
@rizkiaditya24 i used express.js instead of node-static

**Comment by rrpatilcse** [comment]
Same issue. Any one have solution for it?
Error:
WebSocket connection to 'ws://192.168.0.160/socket.io/?EIO=3&transport=websocket' failed: Invalid frame header

**Comment by lgg** [comment]
@rrpatilcse what server you are using?
expressjs?

**Comment by zengliangbigdata** [comment]
i used nginx proxy django websoket service.now no way got it！throw "WebSocket connection to failed: Invalid frame header"

**Comment by lgg** [comment]
@zengliangbigdata show your nginx config, i think it could be troubles with proxy_pass

**Comment by MrBandaruk** [comment]
Same issue here.

**Comment by carloverhamme** [comment]
Same issue, I only get the error in the chrome console

**Comment by gNull-ph** [comment]
> Same issue, I only get the error in the chrome console

SAME.. do you find any solution??

**Comment by jclabrand** [comment]
same!! someone tell me what's going on

**Comment by SiddharthTiwari03** [comment]
Hi, I have encountered the same issue.

I am using NodeJS (LTS v12.18.1) with ExpressJS (v4.17.1) and Socket.io (v2.3.0).

Here is my **server.js**

`const express = require('express');

const app = express();

const server = require('http').createServer(app);

const io = require('socket.io')(server);

app.get('/',(req,res) =>{
// do something
});

io.on('connection' ,socket => {
// socket events handling
});

server.listen(3000);`

Has anyone found a solution?

**Comment by whoakashtyagi** [comment]
> Hi, I have encountered the same issue.
> 
> I am using NodeJS (LTS v12.18.1) with ExpressJS (v4.17.1) and Socket.io (v2.3.0).
> 
> Here is my **server.js**
> 
> `const express = require('express');
> 
> const app = express();
> 
> const server = require('http').createServer(app);
> 
> const io = require('socket.io')(server);
> 
> app.get('/',(req,res) =>{
> // do something
> });
> 
> io.on('connection' ,socket => {
> // socket events handling
> });
> 
> server.listen(3000);`
> 
> Has anyone found a solution?

**Comment by whoakashtyagi** [comment]
same issue... please if anybody found solution.. then drop here

**Comment by marcosybarraa** [comment]
Same here

**Comment by pdeivaraj** [comment]
WebSocket connection to 'ws://localhost:5000/socket.io/?EIO=4&transport=websocket&sid=NMbkrqJ9ePqRI5IeAACL' failed: Invalid frame header

**Comment by lgg** [comment]
@marcosybarraa @pdeivaraj @whoakashtyagi

Im not sure, that yours' issues are the same to mine. I was trying to host static web-files with `node-static` and `socket.io`, changing libraries to `express.js` with `socket.io` helped to me. Also, there are some more "up to date" libraries for working with sockets, rather than `socket.io` (which seems a little bit abandoned)

Check this out: 
https://github.com/websockets/ws
https://deepstream.io/
https://github.com/desertbit/glue


Also check this:
https://github.com/facundofarias/awesome-websockets

**Comment by Nabin0433** [comment]
same problem

**Comment by pdeivaraj** [comment]
@lgg thanks for your reference

**Comment by kbinwant31** [comment]
> Hi, I have encountered the same issue.
> 
> I am using NodeJS (LTS v12.18.1) with ExpressJS (v4.17.1) and Socket.io (v2.3.0).
> 
> Here is my **server.js**
> 
> `const express = require('express');
> 
> const app = express();
> 
> const server = require('http').createServer(app);
> 
> const io = require('socket.io')(server);
> 
> app.get('/',(req,res) =>{
> // do something
> });
> 
> io.on('connection' ,socket => {
> // socket events handling
> });
> 
> server.listen(3000);`
> 
> Has anyone found a solution?

Same issue. Has anybody found a solution for this?

**Comment by asheroto** [comment]
Bump

**Comment by chrisdlangton** [comment]
Same issue here also. adding setup for a recent example.

**dependencies**

```json
{
        "express": "^4.17.1",
        "nodemon": "^2.0.12",
        "socket.io": "^4.1.3"
}
```
**src/index.js**
```js
const app = require('express')()
const server = require('http').createServer(app)
const io = require('socket.io')(server)
const fs = require('fs')

app.set('port', process.env.SOCKETS_PORT || 5080)

io.on('connection', socket => {
    socket.on('disconnect', data => {
        console.log(`client disconnect ${data}`)
    })

    socket.on('checkin', uuid => {
        socket.join(uuid)
        console.log(`checkin from ${uuid}`)
    })
})
app.get('/healthcheck', (_, res) => {
    res.status(200).send("ok")
})
server.listen(app.get('port'), () => {
    fs.writeFile('/srv/app/nodemon.pid', process.pid.toString(), err => {
        if (err) throw err
    })
    console.log(`listening on *:${app.get('port')}`)
})
```

Start with `/node_modules/nodemon/bin/nodemon.js -V --no-stdin start` which produces:
```
[nodemon] src/index.js
[nodemon] starting `node start src/index.js`
[nodemon] forking
[nodemon] child pid: 297
[nodemon] files triggering change check: nodemon.pid
listening on *:5080
```

```js
socket = io('wss://localhost', { transports: ['websocket'] })
```

Chrome says
```
Request URL: wss://localhost/socket.io/?EIO=3&transport=websocket
Request Method: GET
Status Code: 101 Switching Protocols
HTTP/1.1 101 Switching Protocols
Server: nginx
Date: Wed, 04 Aug 2021 03:56:36 GMT
Connection: upgrade
Upgrade: websocket
```
and complains in the console with:
```
WebSocket connection to 'wss://localhost/socket.io/?EIO=3&transport=websocket' failed: Invalid frame header
e @ VM415:1
n.doOpen @ socket.io.2.3.0.min.js:8
n.open @ socket.io.2.3.0.min.js:6
n.open @ socket.io.2.3.0.min.js:6
n @ socket.io.2.3.0.min.js:6
n @ socket.io.2.3.0.min.js:6
n.open.n.connect @ socket.io.2.3.0.min.js:6
(anonymous) @ socket.io.2.3.0.min.js:6
```
There was no output on the server-side from nginx or node

About the obvious forward proxy, so that is nginx and the config is fairly simple (joke), TLS via letsencrypt:
```
server {
    listen                  443 ssl;
    listen                  [::]:443 ssl;
    server_name             localhost;
    root                    /srv/app/;
    server_tokens           off;
    client_max_body_size    32M;
    underscores_in_headers  on;

    ssl_certificate /etc/letsencrypt/live/localhost/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/localhost/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        set $test  $request_method; 
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'https://localhost';
            add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
            add_header 'Content-Length' 0;
            return 204;
        }
        if ($request_method = 'GET') {
            add_header 'Access-Control-Allow-Origin' 'https://localhost';
            add_header 'Access-Control-Allow-Credentials' 'tws.trivialsecrue';
        }
        if ($request_uri = '/socket.io/') {
             set $test  "${test}OK"; 
        }
        if ($test != GETOK) { 
            return 404;
            break;
        } 
    }
    location /socket.io/ {
        proxy_cache             off;
        proxy_no_cache          1;
        proxy_cache_bypass      1;
        access_log              on;
        server_tokens           off;
        proxy_pass              http://localhost:5080/socket.io/;
        proxy_http_version      1.1;
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        Connection 'Upgrade';
        proxy_set_header        Host             $host;
        proxy_set_header        X-Real-IP        $remote_addr;
        proxy_set_header        X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto https;
        proxy_pass_header       device_id;
    }
}
```
This configuration is not intended to allow anything otehr than socket.io websockets through, not even the `/healthcheck` from express.js (which is kept there as a test for this example).

I've exhausted all my SO and Github issue searches, this thread seems to be the closest match for my problem and it appears many others have the same issue for several years.

I can only conclude that socket.io is not suitable for secure environments that utilise CORS, this and many other results related to this indicate people try and give up which only results in insecure deployments.

**Comment by mikecann** [comment]
For me the answer was that I was connecting with a client that was version 2 and the server was running version 4. As [per the docs](https://socket.io/docs/v4/client-installation/) I had to enable `allowEIO3` on the server

**Comment by trongkhoa1505** [comment]
> For me the answer was that I was connecting with a client that was version 2 and the server was running version 4. As [per the docs](https://socket.io/docs/v4/client-installation/) I had to enable `allowEIO3` on the server

resolved

**Comment by ShawnWhy** [comment]
https://socket.io/docs/v4/server-options/#alloweio3
this worked for me, which is strange, because  my socket.IO client is version 4

**Comment by TheMixaDev** [comment]
same issue, occured when trying to initialize on server PeerJS and SocketIO, starts fine if PeerJS disabled
