### ISSUE TITLE
Different paht to client file on mac then on linux

### ISSUE THREAD

**Issue by tjirousek** [socketio/socket.io#2558]
Hi. Why does client socket.io file for browser have different path on mac then on linux system. I`ve installed on both of system same version 1.4.6.

**Comment by kdbanman** [comment]
What are the two paths you see?

**Comment by tjirousek** [comment]
Sorry about that. The issue was resolved by updating of npm.

**Comment by tjirousek** [comment]
But I have futher issue with reconnecting on linux. 

I noticed futher issue. When mobile client lost connecting and somebody send emit to room where mobile client was connected, then mobile socket is disconnected immediately without timeout with reason transport close on linux.

the situation above is different for mac system. The socket is disconnected either timeout is gone or immediately if client mobile is reconnected.

Can anybody help what is a reason that this behaviors on same version of node (6.2) and same version of socket (1.4.6) are different?

**Comment by kdbanman** [comment]
> The issue was resolved by updating of npm.

Good!  This issue should probably be closed, then.  I would if I had the power to.

--------------------------------------

The further issue is difficult to replicate.  If it matters to you, you should open a separate issue :)  Please post client and server code that replicates the issue!
