### ISSUE TITLE
Ack callback error

### ISSUE THREAD

**Issue by aquadestructor** [socketio/socket.io#2560]
Is there some issue with passing callback to emit for acknowledgement? Even on trying the exact same code on the official docs, it is throwing me an error, '_callback is not a function_ _missing error handler on socket_

Any suggestions?

`socket.emit('ferret', 'tobi', function (data) {
      console.log(data); // data will be 'woot'
    });
socket.on('ferret', function (name, fn) {
    fn('woot');
  });
`

**Comment by kdbanman** [comment]
In that snippet, which is the client code and which is the server code?  Which version of socket.io and node are you using?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Comment by jituijiaqiezi** [comment]
@aquadestructor can you tell me how you solve the problem?
