### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by codypearce** [socketio/socket.io#2561]
In in the [Sending Volatile Messages](http://socket.io/docs/#sending-volatile-messages) section of the docs: 

"if they _doesn’t_ receive", should be _don't_

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
