### ISSUE TITLE
Errors on event listeners causes disconnects

### ISSUE THREAD

**Issue by cristianocca** [socketio/socket.io#2562]
Hello, given the below code:

```
// socket init ...

socket.on('disconnect', function(){        
    console.log('user disconnected');
});
socket.on('error', function(err, callback){        
    console.log('socket error');
    console.log(err);
});

socket.on('some event', function(data){
    //some unexpected error.
    console.log(x.willRaiseException);
});
```

The uncaught error on the listener will cause the 'error' event to be fired (if you don't handle it, you get an even worse and uncaughtable error), and also fire the disconnect event, leaving the socket connection unusable. However, the disconnect event is never sent to the client, leaving the whole connection on a very bad state where it won't re connect but neither detect an error.

I have looked everywhere and I'm not sure if this is a bug or not, or I am just handling the errors incorrectly.

**Comment by cristianocca** [comment]
Any ideas?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
