### ISSUE TITLE
socket.io client 1.4.6 receives different object to what server 1.4.6 emits

### ISSUE THREAD

**Issue by carpii** [socketio/socket.io#2564]
I am emitting an object from my node (4.4.4) server, using socket.io (1.4.6)
When I pick it up client side (1.4.6), it seems socket.io has somehow added an extra element to the blocks array, as 'undefined'
###### Server code

```
    var obj = { blocks: [{userid:1, username: "User1" }] };
    socket.emit('test_blocks', obj);
```
###### Client code

```
    // logging to console
    client.socket.on('test_blocks', function (data) {
        console.log("%c console.log(data)", "color: red; font-weight: bold; text-decoration: underline");
        console.log(data);

        console.log("%c console.log(JSON.Stringify(data.blocks))", "color: green; font-weight: bold; text-decoration: underline");
        console.log(JSON.stringify(data.blocks));

        console.log("%c console.log(JSON.parse(JSON.Stringify(data.blocks)))", "color: green; font-weight: bold; text-decoration: underline");
        console.log(JSON.parse(JSON.stringify(data.blocks)));
    }
```

The client output  in console (Chrome OSX 50.0.2661.102 (64-bit)) is...

![](http://i.imgur.com/Lb3QY82.jpg)

As you can see, the 'data' object the socket.io handler recieves, seems have an extra 'undefined' element in data.blocks
I cannot see where this is coming from, and it seems the only way to get rid of it is to JSON.stringfy the object, then reparse it via JSON.parse

Any advice appreciated. 

I could work around this by reparsing all socket.io objects via JSON class
But since I am emitting the data myself and I know they are valid, I don't see why this would be necessary. Its surely a bug?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
