### ISSUE TITLE
ngrok clone by socket.io team

### ISSUE THREAD

**Issue by dharness** [socketio/socket.io#2566]
A little while ago, maybe a month, there was a product on Hacker News that was similar to ngrok in that it let you host and deploy node.js applications from the commandline. It said that it was "by the team that brought you socket.io" but I have been completely unable to find it ever since. Does anyone have any insights?

**Comment by pekeler** [comment]
http://zeit.co/now

**Comment by dharness** [comment]
Perfect! Thanks
