### ISSUE TITLE
cleaning up multiple subscribers to the same message

### ISSUE THREAD

**Issue by mark-lester** [socketio/socket.io#2568]
I have multiple listeners to the same message. How do I perform cleanup, i.e stop listening ? 
I am in backbone and have got a nice reactive game going now, thanks indeed.
But things are getting hairy now with dynamic trees listening to parent models and stuff and the only instruction on clean up I can find is removeListener(subject), so no ref to the subscriber, and removeListener is wanted by the police it seems anyway.
How do I clean up ?,

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
