### ISSUE TITLE
cdn.socket.io has an out of date certificate.

### ISSUE THREAD

**Issue by jpwilliams** [socketio/socket.io#2569]
Looks like #2131's happened again!

**Comment by guigusman** [comment]
Yes. Just happened with me. Expired certificate, one year later.

**Comment by EvaLok** [comment]
happening for me too..

**Comment by jagadeshanh** [comment]
Yes the certificate is out of date.
![socket-io-cdn](https://cloud.githubusercontent.com/assets/6314101/15613538/91ffeaee-2451-11e6-8f2a-51d2de577d92.jpg)

**Comment by Javarome** [comment]
Same here :( 
This already happened last year (https://github.com/socketio/socket.io/issues/2131) so this is quite bad for Socket.io CDN credibility.

**Comment by guigusman** [comment]
Yeah, I've switched it to cloudfare meanwhile, just point to your version.
https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.2.0/socket.io.min.js

I'll not return to socket.io's CDN, as it's the second time it's happening

**Comment by krbnr** [comment]
+1

**Comment by chewax** [comment]
+1

**Comment by dh1tw** [comment]
+1
...Certificate expired on the Friday 27.5.2016

**Comment by GuillaumeLeclerc** [comment]
+1

**Comment by LeslieLei** [comment]
plz update certificate ASAP~~~~

**Comment by zengoma** [comment]
+1

**Comment by vincedev** [comment]
+1

**Comment by jpwilliams** [comment]
Looks like this was fixed a while back now.
