### ISSUE TITLE
Error with Site

### ISSUE THREAD

**Issue by EmmaRamirez** [socketio/socket.io#2571]
Sorry if this is the wrong place to post this, but the Socket.io website has an error where when you hover over the slack badge, it shows 'undefined'.
![untitled](https://cloud.githubusercontent.com/assets/4407518/15629281/22920844-24e3-11e6-86d9-5a8ab0da30ec.png)

**Comment by kdbanman** [comment]
Good find!  I believe the correct repo for this issue is here: https://github.com/socketio/socket.io-website/issues

**Comment by kdbanman** [comment]
Actually, it looks like this has already been reported:  https://github.com/socketio/socket.io-website/issues/28

**Comment by EmmaRamirez** [comment]
Ah, okay then. My bad!
