### ISSUE TITLE
Transpiling with webpack doesn't work.

### ISSUE THREAD

**Issue by tyron-j** [socketio/socket.io#2572]
First thing's first:
- node v6.2.0
- webpack v1.13.1
- socket.io v1.4.6

Trying to transpile the following code:
```
import io from 'socket.io';
```

But the following error gets thrown:
```
fs.js:971
  return binding.fstat(fd);
                 ^

Error: EBADF: bad file descriptor, fstat
    at Error (native)
    at Object.fs.fstatSync (fs.js:971:18)
    at tryStatSync (fs.js:456:13)
    at fs.readFileSync (fs.js:504:12)
    at eval (webpack:///../~/socket.io/lib/index.js?:27:20)
```

So I try to fiddle with it by commenting out socket.io/lib/index.js, line 27:20
```
// var clientSource = read(require.resolve('socket.io-client/socket.io.js'), 'utf-8');
```

While also commenting out the following occurrence of `clientSource`.
Afterwards, code transpiles beautifully without any errors.
It seems to me that the issue is with `require.resolve` being incompatible with webpack transpilation.
Any thoughts on how I can fix this issue?
I would love to use some `socket.io` with webpack.

**Comment by kdbanman** [comment]
Are you following any particular guide or documentation?  If so can you link it?

Also, I'm assuming you're building for the client side.  When using browserify with socket.io on my last project, it worked when I required the `socket.io-client` module, which doesn't have all the exclusive-to-node stuff.  Have you tried 

    import io from 'socket.io-client';

instead of 

    import io from 'socket.io';

?

**Comment by tyron-j** [comment]
Actually, I'm building for the server side.
It seems like webpack just isn't good enough for server side building yet.
We decided **not** to build the server using webpack, so socket.io should be working fine.
Thanks for your time!

**Comment by biirus** [comment]
Hi, there!
I have the same issue but do want to use webpack to transpile my server-side code.
Does any solutions exist?

**Comment by tyron-j** [comment]
@biirus actually, it might have something to do with excluding `node_modules` as part of your webpack configuration:

```
var babelLoader = {
    // ...

    exclude : /(node_modules|bower_components)/,

    // ...
};
```

A lot of the `node_modules` don't seem to support ES6... which is why it's probably better to exclude them when transpiling your node code.

**Comment by tyron-j** [comment]
Forgot to mention where that object actually belongs:

```
module.exports = [{
    // ...

    module: {
        loaders: [ babelLoader ]
    },

    // ...
}];

```

^ as part of your `webpack.config.js`.

**Comment by omerts** [comment]
@tyron-j , excluding node_modules from babel-loader doesn't help. Excluding it entirely from the webpack bundle via the `externals` config does help, but it is an unwanted behavior. We would like to have one bundle file including all the dependencies in it.
