### ISSUE TITLE
Retain message order on fallbacks

### ISSUE THREAD

**Issue by drcmda** [socketio/socket.io#2576]
From digging through logs and debugging it looks like message order is only cared for when the webSocket transport is used. This takes away the abstraction that socket.io offers, at least if it lets the network arbitrarily shuffle fallback packages.

I have read about the technical limitations and have some idea why it happens, but now both server and client have to emply hack-arounds that add bulk, collecting timestamps, draining promisechains, etc. things that socket.io should take care of to guarantee that fallbacks give the same results as the prototype transport. 

This would be very appreciated.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
