### ISSUE TITLE
How to set-cookie in the namespace middleware

### ISSUE THREAD

**Issue by magicdawn** [socketio/socket.io#2577]
I guess I can use

``` js
io.sockets.use((socket, next){
  const res = socket.request.res;
  res.headerSent // true
  res.setHeader('set-cookie', ['name=foo', 'age=18']); // error 
})
```

and I also noticed this http://stackoverflow.com/questions/10771337/adding-a-cookie-value-on-socket-io

Do I need to other configurations ?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
