### ISSUE TITLE
ENOENT error when using socket io client with websocket transport only on nodes

### ISSUE THREAD

**Issue by mcavuoti** [socketio/socket.io#2578]
I am trying to stress test my node server and to do this I'm setting up a server on a AWS EC2 instance and running a client from another AWS EC2 instance (both run ubuntu). I just try to bring one connection up but it's failing.

Note that if I try to connect from my local computer to the server with the same exact code it works. So I'm guessing some file socket io might need for the web socket connection is missing or not there?

I'm using only web socket transport. and from the debug I see the following:

socket.io-client:url parse http://ec2-52-39-50-123.us-west-2.compute.amazonaws.com:3000 +0ms
  socket.io-client ignoring socket cache for http://ec2-52-39-50-123.us-west-2.compute.amazonaws.com:3000 +1ms
  socket.io-client:manager readyState closed +1ms
  socket.io-client:manager opening http://ec2-52-39-50-123.us-west-2.compute.amazonaws.com:3000 +0ms
  engine.io-client:socket creating transport "websocket" +0ms
  engine.io-client:socket setting transport websocket +7ms
  socket.io-client:manager connect attempt will timeout after 20000 +0ms
  socket.io-client:manager readyState opening +1ms
  engine.io-client:socket socket error {"description":{"code":"ENOENT","errno":"ENOENT","syscall":"connect","target":{"domain":null,"_events":{},"_maxListeners":10,"_socket":null,"_ultron":null,"_closeReceived":false,"bytesReceived":0,"readyState":0,"supports":{"binary":true},"extensions":{},"_isServer":false,"url":"ws://ec2-52-39-50-123.us-west-2.compute.amazonaws.com:3000/socket.io/?EIO=3&transport=websocket","protocolVersion":13,"binaryType":"buffer"}}} +3ms
  socket.io-client:manager connect_error +0ms
  socket.io-client:manager cleanup +1ms

**Comment by andrew-aladev** [comment]
In `node_modules/ws/lib/WebSocket.js`
```
//requestOptions.agent = agent;
``

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
