### ISSUE TITLE
IP ADDRESS

### ISSUE THREAD

**Issue by ShavidzeT** [socketio/socket.io#2579]
Hi,
I'm working on v0.10.25 of node and v1.4.6 of socket.io.
I want to detect and get client's ip address inside socket connection listener.
Can you suggest me anything?

**Comment by LordMajestros** [comment]
Use 
```
socket.handshake.headers['x-forwarded-for'] || socket.handshake.address
```
The first for if you have a proxy like nginx.

**Comment by ShavidzeT** [comment]
@LordMajestros Thank you too much, works great. :+1:
