### ISSUE TITLE
Missing 1.4.6

### ISSUE THREAD

**Issue by oliversalzburg** [socketio/socket.io#2581]
Version 1.4.6 is not on cdn.socket.io and the website also still lists 1.4.5 as the latest version.

**Comment by rderharo** [comment]
This is still an issue as of 1.4.8...

**Comment by oliversalzburg** [comment]
CDNs are *so* awesome to deliver your content to your customers!

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Comment by oliversalzburg** [comment]
lol @darrachequesne

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
