### ISSUE TITLE
ERR_INSECURE_RESPONSE in chrome.

### ISSUE THREAD

**Issue by hifall** [socketio/socket.io#2582]
Once in a while, I see this ERR_INSECURE_RESPONSE thrown in Chrome's console (desktop version 51 and canary, Mac OS El Capitan). This happens when the browser tries to fetch https://www.mydomain.com:port/socket.io/socket.io.js.

I believe the SSL key/cert/bundles are correctly set up on the server and for node.js, since most of the time, socket.io works pretty well, without throwing the ERR_INSECURE_RESPONSE error. The certificate is issued by Comodo, and uses SHA256. In other words, not a "self-signed" cert.

But once it throws ERR_INSECURE_RESPONSE in the console, it's not recoverable. Simply closing the browser tab is not enough, I'd have to restart the whole browser process on my Mac. After the restart, socket.io comes back and works fine.

I can't provide definite repro steps here, but running socket.io on a unstable network connection (like a 3G network or something like that) will increase the possibility of this issue. In such a network, after being connected/disconnected for multiple times, ERR_INSECURE_RESPONSE might happen.

It seems this should probably be a node.js issue. But could it involve socket.io?

**Comment by tokra100** [comment]
Got the same error with an self-signed certificate.

**Comment by bfwg** [comment]
Same error with an self-signed certificate

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
