### ISSUE TITLE
Documentation example for node.js cluster  Sticky Session (upstream timed out)

### ISSUE THREAD

**Issue by TheColorRed** [socketio/socket.io#2584]
In the websites documentation on using multiple nodes (http://socket.io/docs/using-multiple-nodes/#using-node.js-cluster), the section says to use Sticky Session (https://github.com/indutny/sticky-session). Would it be possible to get an example snippet of code in that section that uses the Sticky Session module?

That part is where I am having issues with soket.io, as my upstream is timing out. Remove the module from the code and socket.io starts working again.

> 2016/06/07 11:46:09 [error] 10052#0: *895 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 127.0.0.1, server: api.chat.com, request: "GET /socket.io/?EIO=3&transport=polling&t=LKhmEM5 HTTP/1.1", upstream: "http://127.0.0.1:3000/socket.io/?EIO=3&transport=polling&t=LKhmEM5", host: "api.chat.com", referrer: "http://local.gamesmart.com/play/gamesmart/tower-of-babel"

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
