### ISSUE TITLE
Network Traffic problem

### ISSUE THREAD

**Issue by lordrepha1980** [socketio/socket.io#2587]
Hello,

I have an IOS app with namespace socket.

`app.appSock = io( app.domain + ":"+app.port+"" + "/app", {
                        forceNew:   true,
                        port: app.port
                    } );`

On the webserver fired the event with:

`app.appSock.of('/app').to( socketId ).emit( "receivedFb" );`

This worked but, all other IOS Clients without the correct socketId, get the event in Networkmonitor. Nothing happend but they get the traffic.

Same problem with rooms.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
