### ISSUE TITLE
how can i get all rooms list in 1.4.6

### ISSUE THREAD

**Issue by young91** [socketio/socket.io#2588]
in 0.9.x version, use `socket.rooms`  i can get array like this

```
 { '': 
     [ 'Xjs42p3Uw-uD43I5Q5h7',
       '_04hiZjuoc5U9SDqQ5h8',
       'HM_vb7iWjIps2YmFQ5h-' ],
    '/testRoom1': [ 'Xjs42p3Uw-uD43I5Q5h7', '_04hiZjuoc5U9SDqQ5h8' ],
    '/testRoom2': [ 'HM_vb7iWjIps2YmFQ5h-' ] }
```

then i can get rooms list `['testRoom1', 'testRoom2', '']` for i want

but in 1.4.6 version `sockets.rooms` dosen't work, i test all the method but only can get like this

```
{ '/#7MQcLvUZNUx6PNzrAAAA': Room { sockets: { '/#7MQcLvUZNUx6PNzrAAAA': true }, length: 1 },
  testRoom1: 
   Room {
     sockets: 
      { '/#7MQcLvUZNUx6PNzrAAAA': true,
        '/#jaF1KVL9QHCR8EsQAAAB': true },
     length: 2 },
  '/#jaF1KVL9QHCR8EsQAAAB': Room { sockets: { '/#jaF1KVL9QHCR8EsQAAAB': true }, length: 1 },
  '/#6eXdDcDrDLurGFhPAAAC': Room { sockets: { '/#6eXdDcDrDLurGFhPAAAC': true }, length: 1 },
  testRoom2: Room { sockets: { '/#6eXdDcDrDLurGFhPAAAC': true }, length: 1 } }
```

i don't wang to foreach this array beacause when a lot clients connected, it's too many keys to foreach. how can i do

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
