### ISSUE TITLE
io.emit causes 4undefined frame

### ISSUE THREAD

**Issue by nitin02** [socketio/socket.io#2590]
The nodejs servers are set up on AWS EC2 instances with Nginx as the primary load balancer. I'm implementing a the concept of "rooms" with socket.io 's redis adapter and found no work around for this issue.

I can see from my chrome's "network" tab in debug mode that, it switches to websocket. In the Frame's  tab of the web socket, I can see all the information sent to and back from the nodejs server. 

Any operation with socket.emit is proper and returns the proper object as 4["actual_content"] frame and is **received** by the client but any operation with io object (all operation done with io) returns a 4undefined frame.

Please note that, there seems to be no code issue as the same setup works perfectly when implemented locally on my machine.

Thank you for your help.

**Comment by MasterJames** [comment]
I'm thinking you should simplify the problem to a code sample you're comfortable with posting.
If you use io.on "connection" it's the handler you pass that can see its argument the socket for emit etc. So it's probably the expected behaviour for io.on to return undefined as a result, no?  
I'm sure you know that so I must not be seeing clearly in this moment.

**Comment by nitin02** [comment]
Simplified, this is what I am doing,

```
var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);

http.listen(3000, function(){
  console.log('listening on *:3000');
});
```

The below code works, I am able send back to the client using the socket object.

```
io.on('connection', function(socket){
  socket.join('news');
  socket.broadcast.emit('update', 'hello world');
// or any type of operation with socket works, for example: socket.emit('news', 'hello world' );
});
```

However, the below causes 4undefined frame.

`io.to('news').emit('update', 'hello world');`

or any type of operation using the io object,

For example:

```
io.sockets.emit('update', 'hello world');
io.emit('update', 'hello world');
```

I've tried using the latest version of socket.io (v1.4.6). Do note that the same code works locally.

**Comment by MasterJames** [comment]
Do you put the to inside the on 'connection' ?
http://socket.io/docs/server-api/#socket#in(room:string):socket

**Comment by MasterJames** [comment]
Does it change if you force long-polling?
`io.set('transports', ['jsonp-polling']);`

or maybe
```
io.configure(function () { 
      io.set("transports", ["xhr-polling"]); 
      io.set("polling duration", 10); 
    });

```

**Comment by MasterJames** [comment]
Well if your on AWS using ELB this might be useful. It might be what's happening whereever you are hosting.
https://www.built.io/blog/2014/11/websockets-on-aws-elb/

**Comment by nitin02** [comment]
Thank you for your exhaustive and wonderful list of solutions and tips.

However, After much search I was able to pin-point the error to the issue below by printing socket.id and socket.client.id,

https://github.com/socketio/socket.io/issues/2405
https://github.com/socketio/socket.io/issues/2491

This seems to be a known consequence of the latest versions of socket.io. This issue is still open (2405) and will be resolved in the next release (**maybe**). They should at least **point** this out somewhere, considering that this a **serious** issue.

So, Manually **degrading** socket.io 1.3.* did the trick. All is working well.

(On a side note, I am still puzzled as to why only operations on socket worked properly **previously** as the above issue should have broken that functionality too. Weird!)

Thank you for your time.
