### ISSUE TITLE
security vulnerability for negotiator

### ISSUE THREAD

**Issue by akoskm** [socketio/socket.io#2591]
A recent nsp check returned the following:

```
┌───────────────┬─────────────────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                            │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Name          │ negotiator                                                      │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Installed     │ 0.4.9                                                           │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ <= 0.6.0                                                        │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Patched       │ >= 0.6.1                                                        │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Path          │ my-project@1.0.2 > socket.io@1.4.6 > engine.io@1.6.9 > accepts… │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/106                          │
└───────────────┴─────────────────────────────────────────────────────────────────┘
```

**Comment by alokrajiv** [comment]
Really puzzling because engine.io changelog ([see link](https://github.com/socketio/engine.io/blob/master/History.md)) clearly shows that, at v1.6.10 dependency of accepts was rose to `"accepts": "1.3.3"`.
This said snyk.io clearly shows the error (see [link](snyk.io)) by saying dependency is to `accepts@1.1.4. But I believe snyk is calculating the dependency wrong!

**Comment by ChisholmKyle** [comment]
I get the same issue from snyk:

    ✗ High severity vulnerability found on negotiator@0.4.9
    - desc: Regular Expression Denial of Service
    - info: https://snyk.io/vuln/npm:negotiator:20160616
    - from: WebAppStart@0.0.1 > socket.io@1.4.8 > engine.io@1.6.11 > accepts@1.1.4 > negotiator@0.4.9
    No direct dependency upgrade can address this issue.
    Run `snyk wizard` to explore remediation options.

The npm registry resolves the `engine.io` version 1.6.11 package from [https://registry.npmjs.org/engine.io/-/engine.io-1.6.11.tgz](https://registry.npmjs.org/engine.io/-/engine.io-1.6.11.tgz). The package.json file in this tarball clearly lists the package `accepts` version 1.1.4 as a dependency.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
