### ISSUE TITLE
Dynamic namespace creation and related events

### ISSUE THREAD

**Issue by drekka** [socketio/socket.io#2593]
Hi guys, I'm working on a project using socket.io in node, and socket.io-swiftclient on iOS devices. I needed to create namespaces dynamically, but socket.io seems to only work with hardcoded namespace names created at compile time. I also needed a callback when a namespace was joined so that I could trigger code. For example, to let other users (sockets) know that someone had joined the namespace.

I initially tried to use rooms but socket.io-swiftclient has no support for rooms at all so I have to abandon the idea. So in effect I'm using namespaces as rooms. 

Anyway, I used the following codes to ad the functionality I needed to socket.io. I've posted it because I'd like to see this functionality added to the core socket.io code and because it might be useful to others.

```
var Client = require('socket.io/lib/client');
var Namespace = require('socket.io/lib/namespace');
var SocketIOServer = require('socket.io');

// Add default server namespace validate function. Override as necessary.
SocketIOServer.prototype.namespaceValid = function(namespace) {
    return true;
}

exports.hackSocketIO = function() {

    // Update the list of events.
    Namespace.events = [
        'namespaceCreated', // New
        'disconnect', // New
        'connect',
        'connection',
        'newListener'
    ];

    // Swizzle to dynamically create namespaces as needed before connecting.
    Client.prototype.originalConnect = Client.prototype.connect;
    Client.prototype.connect = function (namespace) {

        var server = this.server;
        if (!server.nsps[namespace]) {
            if (server.namespaceValid(namespace)) {
                var newNsp = server.of(namespace);
                server.emit('namespaceCreated', newNsp);
            }
        }

        this.originalConnect(namespace);
    };

    // Swizzle namespace remove to emit disconnect calls.
    Namespace.prototype.originalRemove = Namespace.prototype.remove;
    Namespace.prototype.remove = function (socket) {
        if (this.sockets[socket.id]) {
            this.emit('disconnect', socket);
        }
        this.originalRemove(socket);
    };

}
```

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
