### ISSUE TITLE
broadcasting to all clients except sender issue

### ISSUE THREAD

**Issue by jloa** [socketio/socket.io#2594]
I've noticed this weird behavior while broadcasting to other clients using `socket.broadcast.emit()`
Here's the sample code of the problem:

```js
...notifyOtherClients = function(room, e, data, socket)
{
 	// sending to all clients in a room except sender
 	var transport = socket.broadcast.to(room);
 	//
 	setTimeout(function(){
 		// #method1: this works as expected: all clients receive event except the sender
 		socket.broadcast.to(room).emit(e, data);
 		// #method2: this doesn't work though: all clients receive this event. Why?! Bug?
 		transport.emit(e, data);
 		// logs out 'true'
 		console.log(transport === socket.broadcast.to(room));
 	}, 
	1000);
};
...
notifyOtherClients("myRoom", "someEvent", { }, socket);
```

 

What am i missing here? Why #method2 doesn't work as expected.
Thanks.

**Comment by Mad-Head** [comment]
```
var transport = function(e, data) {
    socket.broadcast.to(room);
}
```

**Comment by Mad-Head** [comment]
What's returns from `socket.broadcast.to(room)` ?

**Comment by jloa** [comment]
@Mad-Head  According to docs, returns the same socket instance almost like all other method to keep the chainability.
[http://socket.io/docs/server-api/#socket#to(room:string):socket](url)

The funny thing is that this traces true
```js
console.log(transport === socket.broadcast.to(room));
```

**Comment by darrachequesne** [comment]
Hi! `socket.broadcast` actually add a temporary flag (namely, `broadcast`) which will be used the next time `emit` is called on the `socket`.

The flag is used the first time, and then is deleted, hence the result of your second call.

**Comment by jloa** [comment]
Hi there! Hm... maybe i wasn't clear enough. Let me make it more obvious:

```js
    setTimeout(function(){
        // #method1: this works as expected: all clients receive event except the sender
        socket.broadcast.to(room).emit(e, data);
    }, 
    1000);
```
```js
    setTimeout(function(){
        // #method2: this doesn't work though: all clients receive this event. Why?! Bug?
        transport.emit(e, data);
    }, 
    1000);
```
