### ISSUE TITLE
connect_error { [Error: server error] code: 'parser error' }

### ISSUE THREAD

**Issue by cherisope** [socketio/socket.io#2595]
What's the "connect_error { [Error: server error] code: 'parser error' }" mean? 
The version of socket.io is 1.4.6.

**Comment by blaues0cke** [comment]
Maybe you are using websockets with a proxy that does not support websockets.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
