### ISSUE TITLE
Slack is not working, slack.socket.io is broken

### ISSUE THREAD

**Issue by joskuijpers** [socketio/socket.io#2596]
Hi!
I wanted to seek some in-depth support but the slack is broken, and I can't create an account.

Can this be fixed?

**Comment by joskuijpers** [comment]
It works again

**Comment by mitchellporter** [comment]
This is still broken for me. Can't enter my email address on socket.io/slack/ and slack.socket.io is broken.

**Comment by thedotedge** [comment]
Confirming it to be broken: 
![image](https://cloud.githubusercontent.com/assets/227241/17328252/dd5eb908-58bc-11e6-84c3-f983ab4de4ce.png)
