### ISSUE TITLE
Question: Are disconnect initiated by peer and disconnect caused by network problem handled differently?

### ISSUE THREAD

**Issue by fangqiao** [socketio/socket.io#2597]
Hi I am new to socket io. I am now working on an experiment project with socket io now.

I know socket io has built in automatic reconnect. On my case, I need to handle server initiated disconnect and network connection failure caused disconnect differently.

Is there a way to tell which is which? Are different events emitted? 

Hope to find some answers. Thanks in advance.

**Comment by MasterJames** [comment]
I believe you can call disconnect from the server.
https://github.com/socketio/socket.io/issues/47
Or as you might imagine you can setup to tell a client to call it's disconnect like shown here.
http://www.unknownerror.org/opensource/Automattic/socket.io/q/stackoverflow/5048231/force-client-disconnect-from-server-with-socket-io-and-nodejs

`socket.disconnect();`

is suppose to work.

On the client you can specify how many times to try to reconnect and how often.
http://stackoverflow.com/questions/11632969/how-configure-reconnecting-in-socket-io

```
var socket = io({
        'reconnection': true,
        'reconnectionDelay': 1000,
        'reconnectionDelayMax' : 5000,
        'reconnectionAttempts': 5
    });

```

**Comment by bratberg** [comment]
> socket.disconnect();
> is suppose to work.

You could also try `socket.disconnect(true);` - (closes the connection, not just the namespace)

https://github.com/socketio/socket.io/blob/b754cff2b415a8cbbf0f23c61824bcc69b078430/docs/API.md#socketdisconnectclose

**Comment by darrachequesne** [comment]
For future readers: please see the documentation [here](https://socket.io/docs/v3/client-socket-instance/#disconnect).
