### ISSUE TITLE
Connection transport close.

### ISSUE THREAD

**Issue by tjirousek** [socketio/socket.io#2598]
Hello. I have a problem.

Imagine that I have two client devices. The first is desktop PC with running chrome and second is my Mobile devices.

I have problem with my mobile devices. When my mobile devices is temporary offline and PC emited this devices during this time, there is some weird behavior after reconnecting of my mobile devices. The mobile devices transport is closed immediately and created new one.  There is no timeout for old socket.

Mobile devices and Desktop PC are in same room.

During time when Mobile devices is offline and desktop PC does not emit nothing, then mobile device can reconnect, old socket of mobile devices is closed after timeout so what is good for my needs.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
