### ISSUE TITLE
set a auth listener on the server , but when auth fail, client always try connecting.

### ISSUE THREAD

**Issue by chxiaowu** [socketio/socket.io#2604]
set a auth listener on the server , but when auth fail, client always try connecting.
suppose when auth error, client stop trying.

version : 1.4.5.js

**Comment by MasterJames** [comment]
Are you making a suggestion? 
Like "You should alter the code to suppose..."
Sounds right and good to me. Maybe you would like to submit a PR that solves this problem.
I'm new to socket.io and unsure if that's the next step. Any other devs here have some thoughts to share on this?  It does sound like a bug or possible a feature request.
I'm guessing your code should be able to handle the error on the client side and close the connection.
Are you asking how to do that?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
