### ISSUE TITLE
Socket.io Nodes Not syncing

### ISSUE THREAD

**Issue by rroxysam** [socketio/socket.io#2607]
Hi,

I am sending image from server to client. Its is succesfully visible, but it not syncing to all the nodes.

This is my server code : 

    f```
         s.readFile(__dirname + '/images.jpg', function(err, buf){
                  socket.emit('receiveFile', { image: true, buffer: buf.toString('base64')});
           });
```

And on client side, i used 

```
    socket.on("receiveFile", function(info) {
            if (info.image) {
                  var img = new Image();
                  img.onload = function() {
                  };
                  img.src = 'data:image/jpg;base64,' + info.buffer;
                  ctx.drawImage(img, 0, 0);
            }
      });
```
 
But if i just sent a text message, it appears on all the socket node. So can you please help me out.

**Comment by MasterJames** [comment]
What ctx is is unclear.
Search for some nodejs write image file code like this...
http://stackoverflow.com/questions/20267939/nodejs-write-base64-image-file

**Comment by rroxysam** [comment]
Thanks, but i have solved.
