### ISSUE TITLE
socket.io@1.4.8 has insecure dependency

### ISSUE THREAD

**Issue by mwittig** [socketio/socket.io#2608]
socket.io@1.4.8  --> engine.io@1.6.11 --> ws@1.1.0

Vulnerability: DoS due to excessively large websocket message
https://nodesecurity.io/advisories/120

Related ticket at engine.io
https://github.com/socketio/engine.io/issues/410

engine.io has not been updated yet

**Comment by LordMajestros** [comment]
This should be addressed cc @rauchg

**Comment by auridevil** [comment]
also negotiator has issues (Regular Expression Denial of service) and should be updated to >= 0.6.1

https://nodesecurity.io/advisories/106

**Comment by gtilma** [comment]
bump

**Comment by mroberty8** [comment]
Any news ? @rauchg 
Thx

**Comment by jkomyno** [comment]
+1

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
