### ISSUE TITLE
socket.io io.sockets.adapter.rooms[room] in 3G not working

### ISSUE THREAD

**Issue by joanmooreban** [socketio/socket.io#2609]
I have a really strange issue going on here in a socket.io development.

Everything is working just fine except when from a 3G connection the server does the following:

```
console.log( io.sockets.adapter.rooms['thisroom'] )
```

This line, almost every time, returns a typeof of 'undefined', as if there where not sockets connected in the given 'thisroom' room when there actually are sockets connected to the room.

If the same code is executed from a WIFI connection, under the same circumstances, with the same sockets connected, the above line returns something like:

```
Room { sockets: { '/#wEkHFuAhbCEf1Dw2AAAC': true }, length: 1 }
```

which is correct.

I've tried everything with this as to:

Tried socket.io version 1.3.7 Tried socket.io version 1.4.8 Tried to connect with

```
var socket = io.connect("http://<ip>:8081");
```

Tried to force to websockets transport only with:

```
var socket = io.connect("http://<ip>:8081", {transports: ['websocket']});
```

Tried to use two transports as:

```
var socket = io.connect("http://<ip>:8081", {transports: ['websocket', 'polling']});
```

Nothing worked.

Ideas?

**Comment by MasterJames** [comment]
There's lots on this here's one...
http://stackoverflow.com/questions/5557776/websockets-over-a-3g-connection
Might be interesting to ask your mobile provider how they handle the issue and plan to make the future work properly.

**Comment by Swinkid** [comment]
Interestingly enough, I've tested this over Three and 02 on 4G (Not sure if this will cause any differences) with the tests passing.

Just got my friend to test this over 3G on 02 and the test passed.

Are you using a dongle by any chance? Wondering if this is causing some sort of issue.

**Comment by joanmooreban** [comment]
Well I just managed to make it work under a TLS connection.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
