### ISSUE TITLE
Infinity transmitted as null

### ISSUE THREAD

**Issue by tforgione** [socketio/socket.io#2611]
Hi everyone,

I don't really know if this is expected behaviour but when I try to send `Infinity` from a client to a server, the server receives `null` instead.

MCVE :

``` javascript
// Server side
var socket = require('socket.io');

socket.listen(8000).on('connection', function(socket) {
    socket.on('data', function() {
        socket.emit('ok');
        console.log(arguments);
    });
});
```
``` javascript
// Client side
var socket = require('socket.io-client').connect('http://localhost:8000');

socket.on('ok', function() { socket.disconnect(); });
socket.emit('data', Infinity);
```

**Comment by cheemeng** [comment]
That's because JSON doesn't support Infinity
http://stackoverflow.com/questions/16644597/json-stringify-converting-infinity-to-null

**Comment by tforgione** [comment]
Thanks for the information.

I guess I can close this issue now.


*BTW, nice profile pic @cheemeng*
