### ISSUE TITLE
Exception in Server-Side Event - Disconnect Not Detected

### ISSUE THREAD

**Issue by kaansoral** [socketio/socket.io#2615]
I decided to let clients cause exceptions in server events, otherwise it's almost impossible to cover all exception scenarios - this is all great in practice, exceptions are caught by socket.io, the code is simpler

However, when an exception occurs in the server-side event handler, the client is disconnected, yet the client-side "disconnect" event isn't triggered

I want the client side "disconnect" to trigger whenever the connection is severed

Is it possible to remedy/fix this issue, I'm guessing this is a long-standing issue with ties to #2285

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
