### ISSUE TITLE
Concerns on year old claim of bug/difficency with cluster

### ISSUE THREAD

**Issue by MasterJames** [socketio/socket.io#2616]
I noticed this post ...
https://www.jayway.com/2015/04/13/600k-concurrent-websocket-connections-on-aws-using-node-js/
Claiming socket.io was not up to the task due to some bug with cluster at the time.
I'm wondering if this is still true or needs a dressing etc?
Where can I learn more about cluster on socket.io or relavant examples etc?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
