### ISSUE TITLE
How to assure topic subscription by authentic user only ?

### ISSUE THREAD

**Issue by mkj-git** [socketio/socket.io#2617]
How can I make sure that a given topic "myNotification" will be subscribed by user X only. If any other user try to subscribe  "myNotification" it should be failed.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
