### ISSUE TITLE
Acknowledgement mechanism not documented?

### ISSUE THREAD

**Issue by pmeinhardt** [socketio/socket.io#2618]
Hi, it was only by chance that I stumbled across socket.io's built-in acknowledgement mechanism. I was really surprised that this is not documented in the README.md as I consider this to be a very important and useful feature for building websocket protocols/message exchanges.

I **really** think it should be added to the README.md so other's don't run into the same issue and start rolling their own ack-mechanism. I have not written a socket.io application before, so for some this may be obvious, but I suspect the same could happen to other people who are just starting out and that don't bother to read through the code (which - by the way - is very nicely written).

**Comment by darrachequesne** [comment]
The documentation was added there: https://github.com/socketio/socket.io/blob/master/docs/API.md#socketemiteventname-args-ack

Do not hesitate to complete it if you find that something is missing!

**Comment by pmeinhardt** [comment]
Very nice!
