### ISSUE TITLE
var io = require('../..')(server);

### ISSUE THREAD

**Issue by CyrusDP** [socketio/socket.io#2620]
HI

the examples code is awesome. but i would like to know how is the code "var io = require('../..')(server);" work as i didn't found and folder/file one the file structure.

Thanks.

**Comment by amylittleyang** [comment]
I was wondering how this code works too. Another file I didn't find is ```socket.io.js``` included in index.html.     
``` html
  <script src="/socket.io/socket.io.js"></script> 
```

**Comment by amylittleyang** [comment]
I'm trying to use socket.io swift client to connect to the socket.io server in the example. The URL I used was 
```swift
socket = SocketIOClient(socketURL: NSURL(string: "http://localhost:3000/socket.io")!)
socket!.connect()
socket?.emit("add user", username)
```
An event was emitted by the client but was not received by the server.    
I tried to find how the client in the chat example connects to the server, and in main.js I found ```socket = io()```, which doesn't give any clue to the url either. 
Am I using the correct server url? And exactly how does the client connect to the chat server in the example?

**Comment by Aotik** [comment]
This is according to the repo directory on GitHub. Run `npm install --save socket.io` in your root directory (where you have **package.json** then use `var io = require('socket.io')(server)` instead. 

Or otherwise, download all the socket IO repo and run the example from there.

**Comment by Aotik** [comment]
`<script src="/socket.io/socket.io.js"></script> ` will be automatically available to you when you run your server with `var io = require('socket.io')(server)`

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
