### ISSUE TITLE
Website chat demo not working

### ISSUE THREAD

**Issue by nacholibre** [socketio/socket.io#2622]
So I wanted to check out the demo, but It's not working.

http://chat.socket.io/

`Uncaught ReferenceError: io is not defined`

**Comment by dospunk** [comment]
To add to this, none of the demos are working either

**Comment by jhl0903** [comment]
It's not working for me either. When will this be fixed?

**Comment by albanirneves** [comment]
It's not working for me too

**Comment by jwickens** [comment]
still doesn't work. I just tried on chrome, firefox and safari on a mac (all relatively recent versions.) On chrome I get the following error which seems to be the root cause:
```
GET http://chat.socket.io/socket.io/socket.io.js
net::ERR_INCOMPLETE_CHUNKED_ENCODING
```
looks like a server config error

**Comment by darrachequesne** [comment]
Until we migrate the website, please use https://socketio-chat-dyfwapyfni.now.sh/

**Comment by darrachequesne** [comment]
That should be fixed now, thanks: https://socket.io/demos/chat/
