### ISSUE TITLE
Emit to socket in different node without broadcasting

### ISSUE THREAD

**Issue by sgiachero** [socketio/socket.io#2623]
Using socket.io, socket.io-redis, and socket.io-emitter I am able to emit to specific socket by emitting to the channel named after that socket's id, but this is like broadcasting so I can't send a callback function.
Is there a way to emit to a socket in a different node and send a callback function?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
