### ISSUE TITLE
Request clarification 

### ISSUE THREAD

**Issue by PRDinesh** [socketio/socket.io#2624]
In the chat example index.js file

what does the following line means? and how it works?

var io = require('../..')(server);

**Comment by MasterJames** [comment]
I think it calls the relative path's parent of parent.
Then via the main attribute in the package.json found there it loads lib/index.js so the Server object is loaded.
If no package.json with "main" file is found a default of index.js would load if found.

**Comment by PRDinesh** [comment]
@MasterJames 
Thank you
