### ISSUE TITLE
security vulnerability for ws

### ISSUE THREAD

**Issue by mikewli** [socketio/socket.io#2625]
A recent nsp check returned the following

```
|            | DoS due to excessively large websocket message                  |
|------------|-----------------------------------------------------------------|
| Name       | ws                                                              |
| Installed  | 1.1.0                                                           |
| Vulnerable | <=1.1.0                                                         |
| Patched    | >=1.1.1                                                         |
| Path       | study-kik@1.0.0 > socket.io@1.4.8 > engine.io@1.6.11 > ws@1.1.0 |
| More Info  | https://nodesecurity.io/advisories/120                          |
```

**Comment by gtilma** [comment]
+1, should be trivial to update

**Comment by keverw** [comment]
A security issue open for 10 days? Is this project still maintained? This is concerning.

**Comment by hairyhenderson** [comment]
@keverw - just to be clear, NSP's alert isn't a false positive. engine.io still needs to make a new release, and socket.io also needs to update dependencies

**Comment by keverw** [comment]
@hairyhenderson  Interesting. I was going by what @3rd-Eden wrote which made me think it was a false positive and they fixed it.

**Comment by hairyhenderson** [comment]
@keverw - it was fixed in engine.io's `master`, but there still needs to be a few releases.

**Comment by keverw** [comment]
@hairyhenderson So they fixed it, but never released it? I was unware of that, seems scary being that long.

**Comment by hairyhenderson** [comment]
@keverw yup, basically 😞

**Comment by idanielsteven** [comment]
NSP found these packages need to be moved from/to to fix security vulnerabilties

WS from 1.1.0 to 1.1.1 (patch fix)
Module ws has a known vulnerability: "DoS due to excessively large websocket message"

Negotiator from 0.4.9 to 0.6.1 (patch fix) ISSUE: 
Module negotiator has a known vulnerability: "Regular Expression Denial of Service"

**Comment by darrachequesne** [comment]
Released as:
- engine.io `1.7.0` (https://github.com/socketio/engine.io/releases/tag/1.7.0)
- socket.io `1.5.0` (https://github.com/socketio/socket.io/releases/tag/1.5.0)
