### ISSUE TITLE
How to listen for events globally?

### ISSUE THREAD

**Issue by van-nguyen** [socketio/socket.io#2626]
Hi there, I'm trying to make a global event that can be listened from any connection. A use case would be so that for each connection doesn't need a separate handler. So far the only "global" event is "connection", I want to be able to listen to any event globally. Is this possible?

**Comment by MaffooBristol** [comment]
Yeah this is one that's been discussed a huge amount over many years: https://github.com/socketio/socket.io/issues/434

This is the best solution at the moment imho: https://www.npmjs.com/package/socketio-wildcard

**Comment by van-nguyen** [comment]
Hmm, thanks for the reply, but I don't think it's the same thing I'm after. It is indeed a good feature to have wildcards, but what I'm really after is a many-to-one handler.

e.g.
```js
io.on('login', (data)=> {
  // do login stuff
});
```

instead of
```js
io.on('connection', (socket)=> {
  socket.on('login', (data)=> {
    // do login stuff
  });
});
```

As you can see the current structure creates an overhead of a nested handler.

**Comment by MaffooBristol** [comment]
Ahh. No, as far as I'm aware, connect and disconnect events are very much fundamental to the way client connections work. How could a user login without being connected first, for example? Nothing can be sent outside of the handshake.

**Comment by barraponto** [comment]
If you don't like the nesting, consider `io.use` (http://socket.io/docs/server-api/#namespace#use(fn:function):namespace).
