### ISSUE TITLE
Spam server Socket.IO cycles

### ISSUE THREAD

**Issue by stalkerdenrus** [socketio/socket.io#2627]
Good afternoon. There was a man who spamming my server through a browser console cycle:
for (var i = 0; i < 100000; i++) {
    socket.emit('any_data' , 5);
}

Because of him falling sockets. Is it possible to somehow protect against this server. It can be an example?

**Comment by LordMajestros** [comment]
What I do is I try to determine a reasonable interval between socket emits. I then add a timer to the socket object on the server and disconnect all sockets that exceed that send messages more frequently than that interval.

**Comment by stalkerdenrus** [comment]
**LordMajestros**, could you send sample code this filtering?

**Comment by LordMajestros** [comment]
I added the following check to the onevent function in socket.io/lib/Socket.js
```
Socket.prototype.onevent = function(packet){
  var args = packet.data || [];
  debug('emitting event %j', args);

  if (null != packet.id) {
    debug('attaching ack callback to event');
    args.push(this.ack(packet.id));
  }
  //throttle frequency
  var thisReceiptTime = ((new Date()).getTime());
  if( ( thisReceiptTime - this.lastReceiptTime ) < this.minInterval){
      if(process.env.NODE_ENV == 'development'){
          this.emit('m',JSON.stringify({'msg':'Disconnected, too frequent.'}));
      }
      debug('Disconnected, too frequent.');
      this.disconnect(true);
      return;
  }
```
and added an instance variable to the Socket constructor 
```
function Socket(nsp, client){
  this.nsp = nsp;
  this.server = nsp.server;
  this.adapter = this.nsp.adapter;
  this.id = nsp.name + '::' + client.id;
  this.request = client.request;
  this.client = client;
  this.conn = client.conn;
  this.rooms = {};
  this.acks = {};
  this.connected = true;
  this.disconnected = false;
  this.handshake = this.buildHandshake();
  this.lastReceiptTime=0;//add this
  this.minInterval = 500;//and this
}
```

**Comment by stalkerdenrus** [comment]
**LordMajestros**, Thank you very much. I will try. You save a filtration method?

**Comment by LordMajestros** [comment]
This is most of what I can remember. I switched to uwebsockets since but did something similar.
I put this in the Socket object because otherwise you would have to throttle individual emit messages
like
```
            socket.on('some message',function(message){
                //check last time some message was received
                //allow or disallow
            });
```
but this means you would do this for every possible message emitted and someone spamming your server would just pick one you did not cover.. You should also consider enabling the maxpayload option in the underlying ws server to prevent large messages from causing fails.

**Comment by LordMajestros** [comment]
What do you mean by filtration method?
The disconnection of too frequent clients on all server side sockets regardless of namespace or emit subject there is no selectivity.

**Comment by stalkerdenrus** [comment]
**LordMajestros**, I mean just that. Disable frequent requests (very frequent).
Look, I did like this and like that. It's all? Now like everything is working.

```
function Socket(nsp, client){
  this.nsp = nsp;
  this.server = nsp.server;
  this.adapter = this.nsp.adapter;
  this.id = nsp.name + '#' + client.id;
  this.client = client;
  this.conn = client.conn;
  this.rooms = {};
  this.acks = {};
  this.connected = true;
  this.disconnected = false;
  this.handshake = this.buildHandshake();
  this.lastReceiptTime=0;//add this
  this.minInterval = 500;//and this
}
```

```
Socket.prototype.onevent = function(packet){
  var args = packet.data || [];
  debug('emitting event %j', args);

  if (null != packet.id) {
    debug('attaching ack callback to event');
    args.push(this.ack(packet.id));
  }
  
    //throttle frequency
  var thisReceiptTime = ((new Date()).getTime());
  if( ( thisReceiptTime - this.lastReceiptTime ) < this.minInterval){
      if(process.env.NODE_ENV == 'development'){
          this.emit('m',JSON.stringify({'msg':'Disconnected, too frequent.'}));
      }
      debug('Disconnected, too frequent.');
      this.disconnect(true);// or comment this line and just return
      return;
  } else {
	  emit.apply(this, args);
  }

};
```

**Comment by LordMajestros** [comment]
Yes that's it. It allows a minimum of 500milliseconds between messages. Does the spamming still occur?

**Comment by stalkerdenrus** [comment]
**LordMajestros**, It is not observed. I hope I did the right thing and everything will be fine. And where you change option lastReceiptTime? In my opinion it will always be equal to 0

**Comment by LordMajestros** [comment]
Sorry, it should be in or after the else block
```
    //throttle frequency
  var thisReceiptTime = ((new Date()).getTime());
  if( ( thisReceiptTime - this.lastReceiptTime ) < this.minInterval){
      if(process.env.NODE_ENV == 'development'){
          this.emit('m',JSON.stringify({'msg':'Disconnected, too frequent.'}));
      }
      debug('Disconnected, too frequent.');
      this.disconnect(true);// or comment this line and just return
      return;
  } else {
      this.lastReceiptTime =  thisReceptTime;//add this
      emit.apply(this, args);
  }
```

**Comment by stalkerdenrus** [comment]
**LordMajestros**, thank you ;)

**Comment by LordMajestros** [comment]
You're welcome 👍

**Comment by kittfple** [comment]
What if someone spam connection like this:
for (let i = 0; i < 1000000; i++) {
    io.connect('ws://localhost:9001');
}

As tested result my socket app will down as well, any solution for this?

**Comment by kittfple** [comment]
What if someone spam connection like this:
for (let i = 0; i < 1000000; i++) {
io.connect('ws://localhost:9001');
}

As tested result my socket app will down as well, any solution for this?
