### ISSUE TITLE
Issue with sample chat app

### ISSUE THREAD

**Issue by dmuth** [socketio/socket.io#2629]
While working through the sample at http://socket.io/get-started/chat/ I ran into some problems with jQuery handlers not firing.

I eventually traced it to not having `$(document).ready(...)` around the Javascript code.

e.g.

```
$( document ).ready(function() {
    $('form').submit(...
});
```

My recommendation is that `$(document).ready()` be aded to the source, as this may have tripped up other people as well.

Thanks,

-- Doug

**Comment by KhainTCore** [comment]
Thank you. I was driving myself crazy trying to figure out why it wasn't working.

**Comment by jdiegogonzales** [comment]
Thanks, the same here. 

Btw, you can also add the ` $('form').submit(` thing just before the closing body tag.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
