### ISSUE TITLE
Server not sending data unless it receives data.

### ISSUE THREAD

**Issue by sathibault** [socketio/socket.io#2631]
My server emits data every second, but the packets are buffered in engine:socket and doesn't get flushed until it gets some response from the client.  If the client doesn't emit anything, data is only sent at every ping/pong.  Transport is engine:ws.

My work around is to have the client emit an acknowledgement for every message it gets, which seems to work.

**Comment by haozxuan** [comment]
In nodejs, the tcp protocol use Nagle, and you can try use socket.setNoDelay(true) .

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Comment by sdetweil** [comment]
if using raw socket protocol, then  socket.setNoDelay(true)   doesn't apply
