### ISSUE TITLE
Connecting to new namespaces submits previously used parameters instead of new ones (including code to replicate)

### ISSUE THREAD

**Issue by ClaasM** [socketio/socket.io#2632]
Code to replicate:

Server side:
```
var io = require('socket.io')(server);
io.of('/1').on('connection', function(socket){
  console.log(socket.request._query['test']);
});
io.of('/2').on('connection', function(socket){
  console.log(socket.request._query['test']);
});
io.of('/3').on('connection', function(socket){
  console.log(socket.request._query['test']);
});
```

Client side: 
```
io('/1', {
    query: 'test=1'
});
io('/2', {
    query: 'test=2'
});
io('/3', {
    query: 'test=3'
});
```

Prints:
```
1
1
1
```

Instead of:
```
1
2
3
```

It feels like a bug.
Clarification is appreciated.
Also posted this on SO here: [http://stackoverflow.com/questions/38771302/socket-io-mixing-up-query-parameters-in-different-namespaces](url)

**Comment by Nibbler999** [comment]
That's multiplexing - the underlying connection is shared. To disable multiplexing set the `multiplex: false` option in the client when you connect. That will give you 3 separate connections.

**Comment by ClaasM** [comment]
Thanks a lot!
