### ISSUE TITLE
Issues with Socket.IO (>= 1.0) and Bouncy

### ISSUE THREAD

**Issue by bernardsaucier** [socketio/socket.io#2633]
There seems to be some incompatibilities between Socket.IO and Bouncy : in Chrome and Firefox (not in Edge), my browser tabs hang when I open more than 5.

I know it's caused by the NPM module "Bouncy" because if I remove the code that uses it, everything works fine and there's no limit to how many browser tabs I can open. The other culprit is the new version of Socket.IO (>= 1.0, which I just updated to), because when I downgrade back to v0.9.16 the problem goes away.

Here's some relevant server code :

```
var port = 8502;    
var bouncy = require('bouncy');
var socketio = require('socket.io');
var express = require("express");
var http = require('http');
var app = express();
var server = http.createServer(app);
var io = socketio.listen(server);
server.listen(port);

var serverBouncer = bouncy(function(req, res, bounce) {
    var path = req.url;
    var url = req.headers.host;
    if (typeof url !== "string")
        return;
    var urlArray = url.split('.');
    var bouncePort = port;
    if (!isNaN(urlArray[0]))
        bouncePort = parseInt(urlArray[0]);
    else if (String(urlArray[0]).toLowerCase() === "www" && !isNaN(urlArray[1]))
        bouncePort = parseInt(urlArray[1]);
    bounce(bouncePort);
});
serverBouncer.listen(80);

io.on("connection", function(socket) {
    //Some events...
});
```

Here's some relevant client code :

```
var client = io.connect();
```

I have been stuck trying to solve this problem for the past 3 days, any help is immensely appreciated.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
