### ISSUE TITLE
error in dealing with events 

### ISSUE THREAD

**Issue by engmohammad224** [socketio/socket.io#2635]
I have noticed that when i refresh a page quickly  , 
the following code ignores the 'disconnect' event !!
io.sockets.on('connection',function(socket){
//some code 
socket.on('disconnect', function () {
     //some code 

```
});
```

})

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
