### ISSUE TITLE
Socket IO performance on a simulated Very Bad Network

### ISSUE THREAD

**Issue by bhartsb** [socketio/socket.io#2637]
I'm using socket.io, nodejs, and redis on my server, and socket.io-client-swift in my iOS app to communicate via web sockets.  In the iOS app when I use the Developer tools (accessible from iPhone Settings screen) to simulate "Very Bad Network" I see extremely poor network performance.  That is even sending smallish 40-50KB size data payloads takes many seconds, and the connection is very prone to disconnecting and reconnecting.  I haven't started creating speed and performance type metrics yet to determine what exactly is wrong but it does seem like something is awry.  Given what the Very Bad Network simulation setting are it doesn't seem like it should be as bad as it is.  That is why before embarking on trying to nail down what is wrong I wanted to get some feedback here first.  Very Bad Network simulation settings are:

In bandwidth: 1000 kbps
In packet loss: 10%
In delay: 500 micro secs
Out bandwidth: 1000 kbps
Out packet loss: 10%
Out delay: 500 micro secs
DNS delay: 0

In the past I worked on a project where we made realtime audio streaming work over a connection that had high bandwidth but 80% packet loss.  That is why I'm wondering why my performance is so bad with just 10% packet loss.  But again I haven't yet started to try and isolate the culprit(s).

Input welcome.

**Comment by haozxuan** [comment]
what's your socket.io version?

**Comment by bhartsb** [comment]
socket.io@1.4.6

**Comment by BuGlessRB** [comment]
Socket.IO runs over TCP, TCP cannot deal very well with packetloss >5% situations.
In order to accomodate your 10% loss scenario, you'd need to switch Socket.IO to use a transport that supports UDP instead.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
