### ISSUE TITLE
Compatible with async/await ?

### ISSUE THREAD

**Issue by varHarrie** [socketio/socket.io#2638]
I'm trying to integrate socket.io with koa v2.
Can I pass a async funtion as a event on server side,
just like:
```javascript
socket.on('message', async () => {
  const some1 = await fun1()
  const some2 = await fun2()
  socket.emit('reply', some1, some2)
  ... 
})
```
As I known, the async funtion just a wrapper of promise. 
Is there any implicit problems?

**Comment by ilkkao** [comment]
That works just fine.

**Comment by varHarrie** [comment]
thx a lot : )

**Comment by tommoor** [comment]
For anyone coming via Google, please be aware of this critical issue using `await` and socket.io:

https://github.com/socketio/socket.io/issues/3431
