### ISSUE TITLE
Is it possible to declare a domain-wide global (reusable) client-side instance of socket.io across navigated pages?

### ISSUE THREAD

**Issue by acrolink** [socketio/socket.io#2639]
I am considering implementing socket.io on one of my sites for authenticated users. I need to be able to send personalized messages to the connected authenticated users. My site has many paths and pages. I understand that I can send personalized messages by registering the clients based on unique identifiers via room joining. My question, do I have to register (and re-register) the remote user to his room on each page load he makes at my site? Or is it possible to register him at first [entry] page load and that is it? Thank you.

Question originally posted at:
http://stackoverflow.com/questions/36589799/is-it-possible-to-declare-a-domain-wide-global-client-side-instance-of-socket-io

**Comment by carpii** [comment]
IMO unless you have a single page app, then each page load is going to require the websocket connection to be re-established. 

This means each connection will have a new socket.io identifier, and so any connections established from previous pages will not be valid and eventually timeout.

I get what you're trying to do, but I don't see how its going to work...  unless your socket.io client is loaded from a parent frame which isn't reloaded when your page url changes.

**Comment by MaffooBristol** [comment]
Carpii's right, yeah there's no way of sharing a connection after disconnecting the window. It's not possible either to persist the connection in any browser storage methods, so no, sorry! It's very much designed for single page apps.

There are web workers, but their support is hugely limited so I would recommend strongly against them, at least for the next few years. See here: http://tavendo.com/blog/post/websocket-persistent-connections/

What's wrong with closing an opening a connection anyway? As long as you can send a uid and, preferably, some sort of token, closing and reopening a connection shouldn't be a problem. Whatever auth is running on page load should be tough enough to deal with future page loads hopefully.

Of course you can always help things by caching the user connections into an array/object outside of the socket connection and then refer to that on connect and disconnect events!
