### ISSUE TITLE
In mac os x 10.11.6 can't get the right io.sockets.adapter.rooms[roomid].length 

### ISSUE THREAD

**Issue by chfeizy** [socketio/socket.io#2640]
My version is:
node.js is 6.3.1
"dependencies": {
    "async": "^2.0.1",
    "cluster": "^0.7.7",
    "kue": "^0.11.1",
    "log4js": "^0.6.38",
    "mysql": "^2.11.1",
    "redis": "^2.6.2",
    "socket.io": "^1.4.8",
    "socket.io-redis": "^1.0.0"
  }
In mac os x 10.11.6
io.sockets.adapter.rooms[plaza].length  is 1,
Can't get the right online num,
But in windows7 is right.

**Comment by chfeizy** [comment]
win7 is connect the same process,
So io.sockets.adapter.rooms[roomid].length is get the one process online,
How can get all onlines?

**Comment by MaffooBristol** [comment]
Hello, could you please provide some more details. Same node version on each?

I can't imagine any reason for a difference between OSes otherwise without a bit more info, especially a code sample? Thanks!

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
