### ISSUE TITLE
SLI integrity

### ISSUE THREAD

**Issue by C-Bouthoorn** [socketio/socket.io#2643]
Maybe it's better if you should encourage [SLI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) on your Download page?

At  http://socket.io/download/, use

``` html
<script src="https://cdn.socket.io/socket.io-1.4.5.js" integrity="sha384-mp5QqlF7YJplkggFgto52+zx2bKkCQPFNvJWia1rhnEpwcXieUOcgRoLncV3M4NO" crossorigin="anonymous"></script>
```

instead of

``` html
<script src="https://cdn.socket.io/socket.io-1.4.5.js"></script>
```

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Comment by C-Bouthoorn** [comment]
Well... uhm... the link is still the same on the website?
