### ISSUE TITLE
358 bytes payload takes almost double mobile traffic

### ISSUE THREAD

**Issue by radosi** [socketio/socket.io#2646]
Hello,

I developed node.js server based on socket.io 1.4 and mobile application working absolutely flawless with it. The app send binary array with length around 360 bytes every second. Recently I found that mobile traffic is abnormally high and after sniff the traffic I found this.
![socket io](https://cloud.githubusercontent.com/assets/3874806/17755752/9148e64a-64e4-11e6-8059-242f474ff751.PNG)
As a respond from server I send 1-4 bytes payload as a reply to application.
Whye there are here all 5 packets instead of 2 (for send and reply) and why so many extra data is sent ? (I tried to find some documentation about the protocol nut no luck) Can I configure something in order to remove extra data or I have to migrate to native socket communication between app and server to save mobile data. 

some details : socket server is running on 8080 port, the payload package is in first packet and are masked, the program that I used for screenshot is wireshark.

**Comment by radosi** [comment]
nobody can't help ? 
Can I force socket.io in socket mode not in websocket since I don't use browser in this connection

**Comment by radosi** [comment]
http://tavendo.com/blog/post/dissecting-websocket-overhead/ - this may give me some light on the websocket transport scheme :(

**Comment by darrachequesne** [comment]
Please see https://github.com/socketio/socket.io-parser/issues/61

**Comment by darrachequesne** [comment]
@jannicars since version 2.0.0 you can now provide your own parser:

Please take a look at:
- https://github.com/socketio/socket.io-parser/issues/61
- https://github.com/socketio/socket.io/tree/master/examples/custom-parsers

Related: https://github.com/socketio/socket.io/issues/2938
