### ISSUE TITLE
Community slack channel

### ISSUE THREAD

**Issue by davidpede** [socketio/socket.io#2647]
Hi, is anyone able to send me an invite to the community slack channel? The form here: http://socket.io/slack/ does nothing

**Comment by Hongbo-Miao** [comment]
Same here, can someone invite me too? thanks!
Hongbo.Miao@outlook.com

**Comment by kamakinto** [comment]
Same here. 

everettlrobinson@gmail.com

**Comment by darrachequesne** [comment]
That should be fixed now, thanks => https://slackin-socketio.now.sh/

**Comment by vin-ni** [comment]
the link doesn't work anymore :)

**Comment by FreddieRa** [comment]
I get "Error with deployment" if I try and sign up to the Slack.

**Comment by darrachequesne** [comment]
It should be up again, sorry for the inconvenience.

**Comment by Zorail** [comment]
The link is not working anymore.

**Comment by SomuBhandari** [comment]
The Link to your channel not working anymore, please fix this.

**Comment by SomuBhandari** [comment]
The link to your channel is not working anymore, please see to it and fix it
