### ISSUE TITLE
[https] Connection closed before receiving a handshake respons

### ISSUE THREAD

**Issue by phanthinh** [socketio/socket.io#2648]
Can't find out a solution, I get this error on the browser console: 

> WebSocket connection to 'wss://iosock.dayl.toancauxanh.vn:5432/socket.io/?token=eyJ0eXAiOiJKV1QiLCJh…HA1JyERt24hP2TIa-chetqE&EIO=3&transport=websocket&sid=YAkQDwaVRixIx_b_AAAR' failed: Connection closed before receiving a handshake respons

My code client: 
`io.socket('https://iosock.dayl.toancauxanh.vn:5432', {transports:['polling', 'websocket'], query: 'token=343', secure: true });`

Can you help me?

**Comment by erperejildo** [comment]
Facing same issue.
Change `hpps` instead `http` or IP instead url when you create connection didn't work to me.

**Comment by Lichtjaeger** [comment]
Are you running a cluster (with pm2 for example)?

**Comment by MaffooBristol** [comment]
Clusters could be an issue, as lichtjaeger mentioned, but it could be an issue with the server accepting non ssl outside of its own domain. Is your socket.io code running off the same domain? What happens if you turn ssl off, if that's possible? Or test generic websocket connections over wss:// without involving socket.io and see if that works?

**Comment by phanthinh** [comment]
@Lichtjaeger Yep. I'm using pm2 to running a cluster

**Comment by MaffooBristol** [comment]
http://socket.io/docs/using-multiple-nodes/

**Comment by Lichtjaeger** [comment]
@MaffooBristol that's to little explanation and not all.

@phanthinh if you connect to socket.io a handshake is happening. But you can't guarantee that the response is returned to the same cluster. So you get most times this error. This can be solved with sticky sessions, but they aren't supported by pm2.

Look in the following reference for the workaround: Unitech/pm2#389

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
