### ISSUE TITLE
Socket.io@1.4.8 can't work under IE9 or other browser with low version

### ISSUE THREAD

**Issue by maihaihua** [socketio/socket.io#2650]
It doesn't work while I using IE9 browser while it occurs an Error that Uint8Array is not defined.

**Comment by james-mckinnon** [comment]
I was having this issue as well, after a quick browse I found that IE9 doesn't support Uint8Array. [This polyfill from Mozilla's pdf.js worked for me](http://sharextras.org/jsdoc/extras/trunk/symbols/src/Media%20Preview_source_web_extras_components_preview_pdfjs_compatibility.js.html).

Hope this helps.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
