### ISSUE TITLE
please delete this isuue

### ISSUE THREAD

**Issue by na3er-faraji** [socketio/socket.io#2652]
hi.
The issue is handled for chrome but not for Internet Explorer
 I get this error on the browser console after open 6 or 7 tab for any user:
WebSocket connection to 'ws://46.209.255.190/MabnaERP_Version/signalr/connect?transport=webSockets&clientProtocol=1.5&connectionToken=QiSFHH4jmJgSDrTEbXq%2BaKZHnewSFHuIRuEoR5jMYtyH6%2FXu3ggbyYmI4tv9l99346qdWaxXCvLYVpIApQ895vfu%2FJPJ%2B9LI3HFsbZV0RtazB%2BK5lwWnAx4sivTPzEPB&connectionData=%5B%7B%22name%22%3A%22mabnahub%22%7D%5D&tid=5' failed: Error during WebSocket handshake: Unexpected response code: 400.
Hava any advice?

**Comment by erperejildo** [comment]
Is it fixed for your? I'm facing the same problem
