### ISSUE TITLE
Pattern for repeat emit?

### ISSUE THREAD

**Issue by hifall** [socketio/socket.io#2653]
We are building an app where we emit an critical event and must make sure the event is delivered in order for the app to function properly. If the event is not delivered, we need to repeat emitting until the number of retries have reached a specified upper limit.

What's a good pattern to implement such a function?

Thanks!

**Comment by MaffooBristol** [comment]
How about [async.retry](http://caolan.github.io/async/docs.html#.retry)?

Something like this perhaps (this is off the top of my head and untested btw)...

```javascript
async.retry(10, function (callback, asyncResult) {
  socket.emit('something', function (err, socketResult) {
    if (err) return callback(err);
    callback(null, socketResult);
  });
}, function(err, result) {
    // do something with the result
});
```

**Comment by hifall** [comment]
That seems like a good pattern. Thanks!
