### ISSUE TITLE
I can't join slack team

### ISSUE THREAD

**Issue by SplitX26** [socketio/socket.io#2654]
Hi, I have some troubles for joining your slack team from here http://socket.io/slack/
How can i join your slack  ? 

Thanks

**Comment by marcusnielsen** [comment]
Same issue for me a while back.

**Comment by enzobes** [comment]
And that you could settle it ?

**Comment by aprilsnows** [comment]
"502 Bad Gateway"

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
