### ISSUE TITLE
How to join the same room from different namespaces?

### ISSUE THREAD

**Issue by ColadaFF** [socketio/socket.io#2656]
Hi there,

Is there a way to join the same room to N sockets from different namespaces ?

I mean, I have socket#1 on namespace /queue and socket#2 on namespace /chat, how can I made them both to join a room so I can emit messages to both of them?

**Comment by MaffooBristol** [comment]
Hello! Can you not just use the global/default namespace outside of your custom ones to send those messages across, unless I'm missing some detail here?

**Comment by ColadaFF** [comment]
You mean, like I get an instance of the global like: ```socketIO.sockets.connected[`/#${socket.conn.id}`] ``` and then use it to join a room ?
So socket#1 and socket#2 could get into the same room using the global namespace?

**Comment by MaffooBristol** [comment]
Well, a client can use multiple namespaces simultaneously, but the very nature of namespaces means that they can't talk to one-another. It's why the pattern exists, to separate out. Is it not just easiest to send the messages via a third `/messages` channel, or via the default socket?

```javascript
// Client
var queueSocket = io('/queue');
var defaultSocket = io();
queueSocket.on('queue:receive', addToQueue);
defaultSocket.on('message:receive', doSomethingElse);

// Server
var queueSocket = io.of('/queue');
var defaultSocket = io;
queueSocket.on('connection', function (socket) {
  socket.emit('queue:receive', {data: 'test'});
});
defaultSocket.on('connection', function (socket) {
  socket.emit('message:receive', {data: 'test'});
});
```

If there's a specific use case where you need the communication between namespaces and can't just use separate channels, let me know, perhaps provide some code?

**Comment by ColadaFF** [comment]
Well, the thing is, I have 2 nameSpaces: 
```javascript
const chatSpace = io.of('/chat');
const queueSpace = io.of('/queue');
```

So the queue purpose in for CS(customer support) users to watch whether a new users join the chat nameSpace, a user who joins the chat nameSpace has no CS assigned to chat, the CS must pick the user from the chat nameSpace and create a conversation, in that order of ideas, I have:
```javascript
const currentQueue = [];
const currentWatchers = [];
chatSpace.on('connection', socket => {
    socket.on('queue:add', () => {
        currentQueue.push(socket);
        currentWatchers.forEach(watcher => {
            watcher.emit('queue:newPerson', socket.id);
        });
    });
});

queueSpace.on('connection', socket => {
    currentWatchers.push(socket);
    socket.on('queue:createConversation', function (socketId) {
        const socketForConversation = currentQueue.filter(socketToFilter => socketToFilter.id === socketId)[0];
        const conversationId = generateConversationId();
        [socketForConversation, socket].forEach(socketToCreateConversation => {
            socketToCreateConversation.join(conversationId);
            socketToCreateConversation.emit('messages:newConversation', conversationId);
        });
    });
});
```
The problem being that since they are not in the same namespace, they will be on 2 separate rooms, each on their own namespace, so, chat messages will never get emitter to both of them.

**Comment by rn222cx** [comment]
In version 1.3.7 and bellow you can do like this 

var comSocket = io.of('/your_namespace').connected[socket.id];
comSocket.join(room.name);

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Comment by thoutbha** [comment]
> In version 1.3.7 and bellow you can do like this
> 
> var comSocket = io.of('/your_namespace').connected[socket.id];
> comSocket.join(room.name);
> 
> In newer version
> 
> var comSocket = io.of('/your_namespace').connected['/your_namespace#' +socket.client.id];
> comSocket.join(room.name);

Thanks. This worked for me.
