### ISSUE TITLE
Calling client connect when connected fires no event

### ISSUE THREAD

**Issue by marcusnielsen** [socketio/socket.io#2657]
I'd expect calling connect on a client which is connected already to give any kind of feedback to say that the superfluous connect has been handled. Right now, we get no event, and our app would then get into a blocking pending state waiting for the result.

**Comment by barraponto** [comment]
It is a reserved event name. Now I don't know if the client just aborts sending the event or if the server is picky about this event name.

**Comment by marcusnielsen** [comment]
Code snippet to clarify:
```
const socket = io({reconnection: false, timeout: 5000})
  connectionBehaviors.streams.tryConnect.subscribe(
    function onSubscribe() {
      omyLogger.writeInfo('Socket: manual connect retry.')
      socket.io.connect()
    }
  )
```

We show a screen that blocks the rest of the UI. If the GUI gets into a bad state for some reason, calling tryConnect won't do anything unless you are disconnected.

**Comment by marcusnielsen** [comment]
If we have access to a connection state variable, I can make a stream out of that value and merge with it.

Like `Observable.of(socket.isConnected)`

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
