### ISSUE TITLE
(Service Unavailable) on /admin/#!realtime when start socket.io

### ISSUE THREAD

**Issue by OmarSari** [socketio/socket.io#2658]
I got an error on console: VM26939:2 GET https://localhost/socket.io/1/?t=1472386247234 503 (Service Unavailable)
on /admin/#!realtime when start socket.io.
Notes: 
I use Apache server listens to port 80 AND Nodejs listens to port 8085.

Sincerely

**Comment by darrachequesne** [comment]
Please reopen if needed!
