### ISSUE TITLE
(Service Unavailable) on /admin/#!realtime when start socket.io

### ISSUE THREAD

**Issue by OmarSari** [socketio/socket.io#2659]
I got an error on console: VM26939:2 GET https://localhost/socket.io/1/?t=1472386247234 503 (Service Unavailable)
on /admin/#!realtime when start socket.io.
Notes: 
I use Apache server listens to port 80 AND Nodejs listens to port 8085.
AND I use windows 7 operating system.

Sincerely

**Comment by MaffooBristol** [comment]
Does it work fine afterwards or is it constantly coming up with a 503? Sometimes when the server momentarily disconnects, or sometimes on initial load if it hasn't quite started up properly, you'll get 503s, but then they'll resolve themselves.

Also I think you may have duplicated this in #2658 - could you close one of the issues please?

**Comment by MaffooBristol** [comment]
Also, I've just seen you've posted the same issue here: https://github.com/micwallace/wallacepos/issues/57

I assume that both issues in this repo can be closed then?

**Comment by darrachequesne** [comment]
Please reopen if needed!
