### ISSUE TITLE
Socket.io 0.9.x can't work under Google Chrome but it work under Firefox

### ISSUE THREAD

**Issue by OmarSari** [socketio/socket.io#2660]
I need that socket.io is working under Google Chrome.

**Comment by MaffooBristol** [comment]
In what way is it not working? Does it work with later versions of socket.io? 0.9.x is very old.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
