### ISSUE TITLE
duplicate connection on socket.io. status pending xhr

### ISSUE THREAD

**Issue by paredesivan** [socketio/socket.io#2662]
I have a problem with socket.io client in ionic. iam using it in a cordova android . Sometimes it duplicates the connection or at least I interpret it, and when ocurrs the connection status (pending) appears I can not logging in to the application.

This error happens sometimes. If that does not appear pending status , the application allows me to log correctly.

After a minute I get the pending connection as an error 400 bad request and there if I can login correctly in the application.

(function () {

```
angular.module('starter')
    .service('SocketService', ['socketFactory', SocketService]);


function SocketService(socketFactory) {

    console.log("conectando con el server");
    return socketFactory({

        ioSocket: io.connect('http://54.221.207.114:3001')


    });
}
})();
```

![im](https://cloud.githubusercontent.com/assets/4249625/18067322/cf2c4ed4-6e2b-11e6-97de-96fa18c531ce.png)

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
