### ISSUE TITLE
0.9.17 default version for npm 3.10.7 (minor issue)

### ISSUE THREAD

**Issue by Judahmeek** [socketio/socket.io#2663]
Running `npm install socket.io` results in the 0.9.17 version being downloaded and the base64id error being thrown. Running `npm install socket.io@latest` results in `1.4.8` being installed.

I don't understand this, especially since `npm config ls -l` states that the default tag is `latest`.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
