### ISSUE TITLE
Multiple socket generation

### ISSUE THREAD

**Issue by GeertVanWonterghem** [socketio/socket.io#2668]
Reproduction:
- A working socket connection
- Interrupt the Ethernet connection => There will be reconnection attempts from the client, let’s say 10
- Re-enable the Ethernet connection => 10 socket connections are being made and kept alive in the library, at the server, for the same client

**Comment by jayces** [comment]
I noticed the same concern . If the time between each reconnection reconnection is fast, very quickly we get a lot of open socket for a single customer.
Also if you connect Ethernet is that you spend on a mobile network , it works , but if you return the mobile network in Ethernet, can not connect to the server.

sorry google traduction

**Comment by shahqaan** [comment]
Noticed the same behaviour. I am also able to reproduce it with slow reconnect timeout from client (up to 30s).

**Comment by carpii** [comment]
Can you post the minimum working code to reproduce?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
