### ISSUE TITLE
Api inconsistency for rooms

### ISSUE THREAD

**Issue by rsdrsd** [socketio/socket.io#2669]
When I do:

```
socket.join('room');
socket.to('room').emit('online');
```

the 'online'-event is never received on the client side.

When I do:

```
 socket.join('room');
 io.to('room').emit('online');
```

the 'online'-event is received on the client side.

When I do:

```
socket.join('room', () => {
    socket.to('room').emit('online');
});
```

the 'online'-event is never received on the client side.

The docs state the following:

http://socket.io/docs/server-api/#socket#to(room:string):socket

If I read this the call to:

```
socket.to('room').emit('online');
```

should be emitted to the room.

If I use the call:

```
socket.broadcast.to('room').emit('online');
```

the event should emit to the room except the socket.

Now it looks like that:

```
socket.to('room').emit('online');
```

and

```
io.to('room').emit('online');
```

are different. But what I read from the docs I read that they are the same.

Can someone explain the differences and why behave different?

**Comment by darrachequesne** [comment]
Hi! The behaviour is the following:

```javascript
socket.to('room').emit('online'); // emit to everyone in 'room' but the given socket
socket.broadcast.to('room').emit('online'); // emit to everyone in 'room', including the given socket
io.to('room').emit('online'); // emit to everyone in 'room'
```

**Comment by Smiley43210** [comment]
Can we get this clarified on the docs page please?

**Comment by rsdrsd** [comment]
I always thought that broadcasting to a room was excluding the socket. Now
I read that it is including the socket??  I've read this in some
official docs a long time ago, that broadcasting was always without the
socket. This is why I started using SockJS, because I couldn't get a grasp
of the workings of the commands.

2016-10-31 22:18 GMT+01:00 Smiley43210 <notifications@github.com>:

**Comment by cozzbie** [comment]
@darrachequesne `socket.to('room').emit('online'); // emit to everyone in 'room' but the given socket` doesn't work. Clients in the room do not get the emitted event. I think thats what @rsdrsd is getting at and I am experiencing the same thing.

**Comment by darrachequesne** [comment]
@rsdrsd sorry, my answer was not correct, I edited it. To actually answer your question:

- socket.join is asynchronous:
```js
// WON'T WORK
socket.join('room');
io.to('room').emit('online'); // the socket will not receive the event (but other sockets already in 'room' will)

// OK
socket.join('room', function(){
  io.to('room').emit('online'); // everyone in the room will receive the 'online' event
  socket.to('room').emit('online'); // everyone in the room but the sender will receive the 'online' event
});
```

* The `broadcast` flag is needed when you want to send to anyone in the namespace (but not in a given room):
```js
socket.broadcast.emit('online'); // everyone in the namespace but the sender will receive the 'online' event
```

I added it in the [documentation](https://github.com/socketio/socket.io/blob/master/docs/emit.md).
