### ISSUE TITLE
require('express').createServer() doesn't work

### ISSUE THREAD

**Issue by limabeans** [socketio/socket.io#2670]
I'm using express v4.14.0 and `require('express').createServer()` doesn't work, although it is used in sample code [http://socket.io/docs/#using-with-the-express-framework](here). Am I missing something, or should the docs be updated?

**Comment by MaffooBristol** [comment]
Directly above it are the docs for using Express 3/4 - http://socket.io/docs/#using-with-the-express-framework

The sample code you're using is for old version pre-3

**Comment by MaffooBristol** [comment]
But you are correct that it's a bit confusing in the docs.

**Comment by limabeans** [comment]
Thanks for clarifying
