### ISSUE TITLE
socket.io behind nginx with CORS fails on duplicate header

### ISSUE THREAD

**Issue by r3wt** [socketio/socket.io#2671]
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.website.com/socket.io/?EIO=3&transport=polling&t=LS02RU3. (Reason: CORS header 'Access-Control-Allow-Origin' does not match 'http://website.com, http://website.com').`

We were attempting to handle the headers at nginx, as it can do so much more efficiently than node. however, socket.io is setting the same headers we are trying to set at nginx, and it result in duplicate header, and the above bizarre error message. Please provide option to disable all CORS related headers in socket.io; We can fix the issue by stop setting headers at nginx, but then it is not set for normal api request, so only solution is to add express middleware forcing the headers to be set, which is problematic. we would much rather prefer to disable the header from node entirely and rely on nginx to manage these headers.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
