### ISSUE TITLE
Namespace.prototype.emit performance

### ISSUE THREAD

**Issue by jorgemsrs** [socketio/socket.io#2673]
Hello.

`Namespace.prototype.emit` always checks if the data to emit is binary by calling `hasBin` and passing it to the adapter to broadcast.

Can the `hasBin` check move to the adapter so it can be optimised for the case when we're emitting data for namespaces/rooms with no connected clients?

I can help providing a merge request for this if you see value.

Cheers

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
