### ISSUE TITLE
broken build

### ISSUE THREAD

**Issue by capaj** [socketio/socket.io#2674]
there have been 3 release with a broken build-specifically this test:
https://github.com/capaj/socket.io/blame/master/test/socket.io.js#L1537

is failing. How so?
Why hasn't anyone fixed it yet?

@rauchg @3rd-Eden @dvv @einaros

**Comment by JonasGutermuth** [comment]
same problem. Is there a workaround?
Problem is fsevents:

npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "fsevents"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.7
npm ERR! code EBADPLATFORM
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
npm ERR! Please include the following file with any support request:
npm ERR!     /home/jonas/my-new-project/npm-debug.log
