### ISSUE TITLE
Race condition when using namespaces.

### ISSUE THREAD

**Issue by Alanz2223** [socketio/socket.io#2676]
I am trying to use namespaces on the server in conjuction with a session based authorization scheme. What I am relying on is that a single client will have a single connection no matter how many namespaces they connect to. 

Here is my server

`var Server = require('socket.io');

var session = require('express-session')({
  .... opts
})

var io = new Server(http_server); //http_server is passed in

io.use(function(socket,next){

   session(socket.request, {}, next) //session is express-session

});

var Foo = io.of('/foo');

Foo.on('connection',function(socket){
    socket.request.session.myVar = 'hello world'
});

var Bar = io.of('/bar');

Bar.on('connection',function(socket){
   //need access to socket.request.session.myVar from here.
});`

now in my client

`
var io = require('socket.io-client')

var url1 = 'http://localhost:3000/foo';
var url2 = 'http://localhost:3000/bar'

var opts = {
   transports : ['websocket']
};

var Foo = io(url1,opts)

var Bar = io(url2,opts);

Foo.on('connect',function(){
  //now myVar should be set
});

Bar.on('connect',function(){
   //emit an event that will use myVar
});`

now you can see that a single socket must be used in order to preserve the session across both namespaces. The issue is that sometimes the session function fires once to correctly share the session and sometimes it fires twice for the same client making it have two different sessions.

**Comment by carpii** [comment]
You are asking Foo and Bar to connect, but there is no guarantee they will complete in the same sequence you expect
So the 'connect' event handler for Bar could well fire before Foo.on('connect'    -- in which case myCar will not be set

Add some logging into these event handlers and maybe you will get more insight. You probably want to synchronise this with a Promises library

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
