### ISSUE TITLE
client lost listening when it has more listener at different page

### ISSUE THREAD

**Issue by FLCos** [socketio/socket.io#2679]
Hi, the problem is I have two pages one is main page(172.26.203.71), another is a sub page(172.26.203.71/job/jobDetail). At the both page I add io socket listeners.
when I fresh the sub page,  the listener at main page will lost listening.
Here is part of my page. 

Server:  I use express + io;

```
var express = require('express');
var app = express();
var port = process.env.PORT || 3000;
var handlebars = require('express3-handlebars')
    .create({
        defaultLayout: 'main',
    });
var server = require('http').createServer(app),
    io = require('socket.io')(server);
server.listen(port);
```

Client: at main page(the address is 172.26.203.71),
 I add the listener here: 

```
socket = io('172.26.203.71:3000');
socket.on('my-main-event', function (data) {
    console.log('main page' + data);
});
```

at sub page(the address is 172.26.203.71/job/jobDetail)
I add another listener:
socket = io('172.26.203.71:3000');
socket.on('my-job-event', function (data) {
    console.log('main page' + data);
});
Is there any good idea to solve this problem?

**Comment by MaffooBristol** [comment]
Odd! When you say 'lost listening' do you just mean data's not coming through or is there a disconnect error? Are there any errors coming from the server?

Also is there any reason for specifying the ip rather than using `0.0.0.0`?

**Comment by FLCos** [comment]
yes, for the main page, no data coming. I have to reload the main page again

**Comment by carpii** [comment]
@ FLCos What is a subpage? Do you mean some content which is loaded into the main page via ajax, or embedded in an IFRAME etc? How are you refreshing the subpage?

**Comment by FLCos** [comment]
Hi @carpii , sorry, I make you misunderstand, I mean the main page and sub page are different page. The main page is the home page.

**Comment by carpii** [comment]
Hi @FLOCos 

> when I fresh the sub page, the listener at main page will lost listening.

Do you mean you have the main page open in the browser, at the same time as the subpage, or you just navigate from the main to the sub?

When you establish a socket.io client connection on the main page, and then again on the subpage, both are entirely new socket.io connections. If you want to give the end user the impression of a persistent connection across pages, you will need to develop this into your node server (preserve any state and then send it back to the subpage socket when it connects)
by authenticating

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
