### ISSUE TITLE
socket is disconnnect, but the tcp from client doesn't release

### ISSUE THREAD

**Issue by peizhengxing** [socketio/socket.io#2684]
I use nodejs + express + socket.io(1.3.5version) developed,but the num of tcp continued growth.

**Comment by carpii** [comment]
@peizhengxing  You need to provide much more detail about the problem you are having

Please post some code and instructions which allows your bug report to be reproduced

**Comment by peizhengxing** [comment]
@carpii  My english is just so so,I can't describe much more detail about this problem by english. I just want to know why socket has been disconnected and the server side has listener this event,but I check the linux server and find the tcp is still connected.

**Comment by carpii** [comment]
@peizhengxing ok, but post some code and bash commands which will let people reproduce your issue

I can't see anyone being able to help you without this

**Comment by peizhengxing** [comment]
@carpii  anyway  thanks

**Comment by carpii** [comment]
@peizhengxing can you post your code for onConnect() and onDisconnect()?

**Comment by peizhengxing** [comment]
@carpii  this two function mainly deal with some buisness logic about db data(the db is Mongo). It can effect the socket?

**Comment by carpii** [comment]
@peizhengxing your onConnect() is being called from your socket.io handler, so yes it could in theory be causing an issue. 
Only you has any idea what the code in there is actually doing

You need to pare your code back to something barebones, and then show there is actually a problem in socket.io (and not something your own code is doing)

**Comment by carpii** [comment]
@peizhengxing Hi, please could you close this ticket if you are not having any further issue
