### ISSUE TITLE
socket connects and disconnects 

### ISSUE THREAD

**Issue by aabm00** [socketio/socket.io#2685]
Hi.

I have 2 **Arduino Yun** working as a **client** sending messages every 30 seconds (at 00 and 30 seconds). 
The versions of node and node-serial and socket.io are:

**node                        -->  0.10.33-1
node-serialport       -->  1.4.6-2 
socket.io-client        -->   1.4.8** 

The versions in the **server** are:

**node                        -->  4.4.5
socket.io                  -->  1.4.8**  

The Arduinos are switched off and after 22 seconds or so are reconnected (the interval is 16 to 38 or 46 to 08 seconds). and I wanted to know:

Is this behaviour normal. The normal way wouldn't be the socket to be connected all the time without interruptions?

In which cases a socket can behave switching off and switching on, when sending data regularly?

There some way to maintain the connection alive?

Can be some problem with the versions of the libraries? 
Keep in mind that I can't upgrade the version of the node and node-serialport in the arduinos because it depends of the linux installed) so in case that can be problems with the versions, I'd have to change the socket.io  version.

Thanks

**Comment by carpii** [comment]
You can configure the client socket.io to automatically attempt to reconnect if it loses connection (along with a delay, which is gradually backed off after several attempts).

There's so many variables here. Try adding some event handlers to your client socket.io, so you can log when they are actually 'connecting', 'reconnecting' and 'disconnecting'. 

Without debugging this it will be very difficult to establish if its its even a socket.io issue, or whether its simply your serial connection timing out. 

> Is this behaviour normal. The normal way wouldn't be the socket to be connected all the time without interruptions?

If its using websocket transport, then it would typically remain connected, yes
Check if it IS using websocket, and not other transports like polling.

> In which cases a socket can behave switching off and switching on, when sending data regularly?

If socket.io is no longer connected, it cannot send anything until it first reconnects

> There some way to maintain the connection alive?

You don't need it under normal circumstances. I believe socket.io provides its own heartbeat to keep the websocket connection alive

**Comment by aabm00** [comment]
Thanks for your answer.

I am testing again now, but I think it was a problem with promises  and not with socket.io.

**Comment by aabm00** [comment]
Yes. finally the problem were the promises.

Thanks

**Comment by mucan54** [comment]
how you solved?
