### ISSUE TITLE
(BUG) IPv6 only websocket connection broken when a package size is more than ~4k.

### ISSUE THREAD

**Issue by MariasStory** [socketio/socket.io#2686]
Hi,

I have IPv6 only connection and found a problem that is well reproducible:
1) Open two tabs with the following link https://jsfiddle.net/#&togetherjs=v8drhU8QAP and join.
2) Insert and change short text. It works.
3) Insert or copy big text ~4k. The connection is broken. No farther communication possible.

This does not happen with pure websocket:
1) Open http://jsfiddle.net/EAVvQ/24/
2) Enter big text in the small text field.
3) The data transfer works.

Please fix the bug ASAP.

**Comment by MariasStory** [comment]
Ping. Can someone at least put a label "bug" for this issue?
I really need solution to this problem.

**Comment by carpii** [comment]
@MariasStory the first link you pasted is not working

**Comment by MariasStory** [comment]
Hi @carpii. Ok, I see. It work in my case. Any way, it is just a collaborate option on https://jsfiddle.net/#. You just need to push the collaborate button on the top and you'll get a link that you can open in a new tab. This way you'll have a websocket connection between the two tabs.
There will be communication with a server and this one breaks in my case for data bigger ~4k.

The problem is that this server does not use socket.io. They use websockets. Now I see that there is something fishy with this websockets.

I am continuing to experiment.

The point is that there is a popular internet provider that offers IPv6 only connections and it may be a bigger problem in a long run.

**Comment by carpii** [comment]
> Any way, it is just a collaborate option on https://jsfiddle.net/#

@MariasStory Hmm, ok. It does ask if I want to join the collab session, but even when I say yes it just loads a completely empty fiddle. 

If you have a non-collab jsfiddle link which can demonstrate the same problem, that would be useful. 

Maybe I need to have jsfiddle user account and be logged in for it to work

**Comment by MariasStory** [comment]
Hi all,
It seems that the problem is more with some providers than with socket.io.
I have tested the same so

**Comment by MariasStory** [comment]
Hi all,
It seem more of a problem with some providers not properly handling IPv6 than the socket.io.
I will check details and report findings.

BZW: Does someone else have IPv6 only to test some of the problematic connections?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
