### ISSUE TITLE
Socket.io is sleeping ?

### ISSUE THREAD

**Issue by JosselinTD** [socketio/socket.io#2688]
I have a platform which run for some days, and people come and go, Socket.IO connect and disconnect, everything works fine.
At some point (no more traffic load, no more CPU usage, no network issue), front console and server logs start to display connection issues for everyone :
##### Front

```
Firefox ne peut établir de connexion avec le serveur à l’adresse wss://ai-platform.withthebest.com/socket.io/?EIO=3&transport=websocket&sid=KqGwQai_grRwyoDsAAgL.socket.io.js:4026:31
La connexion avec wss://ai-platform.withthebest.com/socket.io/?EIO=3&transport=websocket&sid=KqGwQai_grRwyoDsAAgL a été interrompue pendant le chargement de la page.
```

(Firefox can't establish a connection with the server at the URL wss and The connection with wss... has been interrupted during page loading for the english version ;) )
##### Back :

```
Sep 23 01:45:35 ideation-aiwtb heroku/router: at=error code=H13 desc="Connection closed without response" method=GET path="/socket.io/?EIO=3&transport=websocket&sid=nDBpyW57c2VXQ1nJAAer" host=ai-platform.withthebest.com request_id=d4b80b5a-0551-4ee9-ba85-8fef8e4f8140 fwd="103.252.203.8" dyno=web.2 connect=0ms service=0ms status=503 bytes=0 
```

If I make an action which use Socket.IO, everything go back to normal and works for the client which made the action. A page refresh, and the issue come back.
- Is it an issue you already have and is induce by a known architecture design ?
- Does someone already have this issue and manage to solve it ?

Thank you ! (and sorry for the poor english, if you need more precision, ask for it ! )

**Comment by carpii** [comment]
When socket.io server appears to have stalled, is your web server still responding?

> If I make an action which use Socket.IO

What action are you taking here, and how are you actually doing it?

**Comment by JosselinTD** [comment]
@carpii :

> When your socket.io server appears to have stalled, is your web server still responding?

Yes !

> Ie, can you request the socket.io client library and it responds ok?

Yes !

> What action are you taking here, and how are you actually doing it?

The server use .emit()

**Comment by carpii** [comment]
@JosselinTD  I'm not familiar with Heroku platform, but from the HTTP 503 error, Im guessing there is some reverse proxy sitting infront of the socket.io server?

Is this something Heroku provides, or some server process you are running (nginxm haproxy etc?). Is this reverse proxy running on the same instance as your socket.io server? 

I'm just trying to understand how your project is architected. 

Are you on a paid plan with Heroku? I notice their free plan does make mention that servers are put to sleep after 30 mins of inactivity.

**Comment by JosselinTD** [comment]
@carpii 

> Im guessing there is some reverse proxy sitting infront of the socket.io server?

We didn't set up a system like that. Heroku is doing some sort of routing work, but I don't find informations about a proxy. If it exist, why is it after a certain time that errors shows-up and not directly at start up ?

> Are you on a paid plan with Heroku? I notice their free plan does make mention that servers are put to sleep after 30 mins of inactivity.

Yep, paid plan.

I join an image of my firefox console network tab. I check the Heroku logs, the erors shows-up after 12 to 15 hours of running server.

![socketio](https://cloud.githubusercontent.com/assets/1528493/18870762/7d20043a-84b2-11e6-92de-80655e7b1486.png)

**Comment by carpii** [comment]
@JosselinTD 

Some of the requests in your firefox log are responding with HTTP 400 (Bad Request), even when polling transport is still being used. 
When you get a 400, are you also seeing corresponding web server log entries for this?

What web server are you using, or are the http requests also served by your node process (ie, express etc?)

Is there any console/error output from your node process during the window where its not responding? (I use pm2 to stream this all to disk). Im wondering if there could be be some unhandled exceptions being thrown by node, which you are not noticing?

Do you have any resource monitoring on the server, tracking memory utilisation, maybe file descriptors? Perhaps its a memory leak in your node process... although that wouldn't explain why it suddenly comes back to life when you trigger an emit from the server.

What node and socket.io versions are you using?

Finally are you able to reproduce this on a dev server, ideally one which is not hosted on Heroku (by automating a similar level of traffic)?

**Comment by JosselinTD** [comment]
@carpii 
We don't currently have a platform with the issue, so I can't answer for now on the web server log entries part.

For the rest :

> What web server are you using, or are the http requests also served by your node process (ie, express etc?)

Http resquests also served by our node process (express)

> Is there any console/error output from your node process during the window where its not responding? (I use pm2 to stream this all to disk). Im wondering if there could be be some unhandled exceptions being thrown by node, which you are not noticing?

We output everything we can. I will investigate for any unhandled exceptions.

> Do you have any resource monitoring on the server, tracking memory utilisation, maybe file descriptors? Perhaps its a memory leak in your node process... although that wouldn't explain why it suddenly comes back to life when you trigger an emit from the server.

We use new relic and the buit-in system of heroku. We don't see any memory leak.

> What node and socket.io versions are you using?

Socket.io : ^1.4.4
Node : 4.2.3

> Finally are you able to reproduce this on a dev server, ideally one which is not hosted on Heroku (by automating a similar level of traffic)?

We never have this issue on local dev computers, but they never stay on enough time. Our online dev server are also heroku ^^ I will see if I can set up the app on a EC2.

**Comment by carpii** [comment]
@JosselinTD not sure what to suggest for this, sorry.

I think if it was me, I would write some client socket.io bots to emulate traffic, and then leave them running against a dev server. 
My hunch is it may be a Heroku issue (based on the wide variety of HTTP status codes you are getting in the response)

If you can reproduce the problem outside of Heroku then this would help narrow it down to either an issue in socket.io, or maybe a wider issue in your node sever. I wrote bots for my project and they have been invaluable in testing and performance tuning, so they wouldn't be a bad thing to have around anyway

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Comment by Chathula** [comment]
i am having same problem.. i am using apache(httpd). did u find a solution for this??
