### ISSUE TITLE
Invalid frame header

### ISSUE THREAD

**Issue by mcdyzg** [socketio/socket.io#2690]
I emit 60 times/s,
then chrome errors like this:

`socket.io.min.js:1 WebSocket connection to 'ws://localhost:3030/socket.io/?EIO=3&transport=websocket&sid=hRKSQOy3Pu_8n0cjAAAH' failed: Invalid frame header`

koa server errors like this:

```
F:\websocket server\walkers\node_modules\.npminstall\ws\0.8.0\ws\lib\Receiver.js
:386
    default: srcBuffer.copy(dstBuffer, dstOffset, 0, length); break;
                       ^

RangeError: out of range index
    at RangeError (native)
    at fastCopy (F:\websocket server\walkers\node_modules\.npminstall\ws\0.8.0\w
s\lib\Receiver.js:386:24)
    at Receiver.add (F:\websocket server\walkers\node_modules\.npminstall\ws\0.8
.0\ws\lib\Receiver.js:86:3)
    at Socket.realHandler (F:\websocket server\walkers\node_modules\.npminstall\
ws\0.8.0\ws\lib\WebSocket.js:800:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
```

how can i deal with it?please

**Comment by carpii** [comment]
@mcdyzg what version of node, socket.io client and socket.io server? 

Are you able to use Chromes Network tab to grab the full trace of the websocket frames it has received? Not sure if the invalid one would appear there, but its worth checking

**Comment by mcdyzg** [comment]
My node version is v6.3.1,socket.io is 1.4.5. As for server, i use koa.io 0.0.3, it seems like useing a 1.3.7 socket.io.
Here is Network tab info:
![qq 20160929181319](https://cloud.githubusercontent.com/assets/14190768/18950035/83ffa692-8670-11e6-8584-2d28e3c1a979.png)
Here is console info:
![qq 20160929181330](https://cloud.githubusercontent.com/assets/14190768/18950054/90f28450-8670-11e6-9ec7-c3fc80dc8cc4.png)
It seems like socket reconnect many times.

when i reduce emit info in per-second,it performs better.

**Comment by carpii** [comment]
@mcdyzg I could not find the 'One or more reserved bits' error anywhere in socket.io code, or even in the unrelated ws npm module

It seems to be something which can be generated by Chrome, or as a result of anti-virus or security suite software
"Eset nod32" security software crops up often, although most of these are from a couple of years ago...

https://github.com/jaspervdj/websockets/issues/83
https://github.com/yesodweb/yesod/issues/823
https://github.com/socketio/socket.io/issues/2543
https://github.com/ZenHubIO/support/issues/720

**Comment by darrachequesne** [comment]
Could you please try with latest version of `socket.io` (which uses ws `1.1.1`)?

**Comment by darrachequesne** [comment]
That should be fixed in latest release, thanks for the heads-up.

**Comment by rrpatilcse** [comment]
I was also facing same issue. Try with `npm install socket.io -save` at client side also. It works for me.
