### ISSUE TITLE
save connected sockets on rooms

### ISSUE THREAD

**Issue by tux-world** [socketio/socket.io#2692]
As far as we know creation of sockets is unique id.when my users create room and invite users to join into that. I cant save and store joined users on rooms.when user joined on room (s)he likes to server store this join and after disconnet and connected again joined automatically to latest joined rooms.how can i store sockets and join automatically users?

I cant find any solution about this ability. Because sockets changed on each connection.

Is any simple solution? Thanks in advance

**Comment by carpii** [comment]
@tux-world 

You would need to write some feature which authenticates the user, then stores the user id and which rooms they want to autojoin
Then write a feature to have the server automatically rejoin them to those rooms.

If you allow anonymous users so they don't have a persistent userid, you may be able to do it using an HTTP session instead, or perhaps by dropping a cookie (in which case be sure to validate the data before taking any action). 

There may already be some npm modules which could help you with this, but I had a quick search and couldn't find any obvious candidates

**Comment by carpii** [comment]
@tux-world Please can you close this ticket if you are not having further problems?
