### ISSUE TITLE
How to improve socket.io's performance in transmission

### ISSUE THREAD

**Issue by lishengze** [socketio/socket.io#2694]
I've tested socket.io's performance in transmission for a few days. I found that it can't supply stable transmission for a large mount of data for a long time. It's bandwith is only 2~2.5 MB/s. The test environment: Cpu Quad-Core AMD Opteron(tm) Processor 2382, 4 cores, 2.6GHz; memory for nodejs: 1.5G. For example, if I emit 10MB data one time, the server will collapse because of lacking in memory. Supplying bigger memory is meanless because it can't  improve the bandwith. It can just supply memory for the data that are waiting to be emitted. So I want to know how to improve socket.io's performance in transmission, my company's project needs at least 20MB/s ~ 30MB/s.

**Comment by BuGlessRB** [comment]
Have you tried using a different Socket.IO implementation serverside?  It's available in a number of languages.

**Comment by carpii** [comment]
@lishengze 

> For example, if I emit 10MB data one time, the server will collapse because of lacking in memory

Do you mean a single packet/emit of 10MB, or 10MB is the total throughput across all your client connections?

If you are wanting to send large packets, there is another Issue active at the moment, with one user suggesting he might try to tackle it by fragmenting and reassembling large payloads...

https://github.com/socketio/socket.io/issues/2666

**Comment by lishengze** [comment]
I sended 10MB data in almost 10thousands packets and my server collapsed. I plan to build a proxy-sever on nodejs by sockeio to connect client with the real sever. The real sever was build by c++. I have already encapsulated the c++ interferce by V8. The client is  a web app on pc and my company also plan to make apps on the ios/Android by h5 , JS. So I have to use build a js proxy-server or I have to encapsulated the c++ interferce for different platforms. And I need 20MB/s ~30MB/s bandwidth at least. Give me some suggestions guys. Or I have to give up the proxy-sever.  @carpii @BuGlessRB

**Comment by carpii** [comment]
@lishengze Personally I would not embark on building a node.js proxy server if you are already having performance issues.

Look into haproxy (or nginx). 
Both can be configured to act as a reverse proxy (frontend) and have support to proxy websockets to your socket.io server

**Comment by BuGlessRB** [comment]
Well, I would not use a proxy server of any kind, I would use a server-side socket.IO implementation not written in JavaScript.

**Comment by lishengze** [comment]
Thanks guys! I think I will give up this proxy-server!
