### ISSUE TITLE
Clean-room Engine.IO and Socket.IO implementation for the Pike programming language

### ISSUE THREAD

**Issue by BuGlessRB** [socketio/socket.io#2695]
I'm proud to announce that I've finished implementing a clean-room version of both Engine.IO and Socket.IO server-side in the [Pike](http://pike.roxen.com) programming language (also on [github](https://github.com/pikelang/Pike)).

I used the specs for reference, reverse engineered the (sadly missing) rest, only glanced at the JavaScript source code rarely to figure out subtle intricacies. Pike supports XHR/JSON/WebSocket, both with and without compression.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
