### ISSUE TITLE
How to get socket instance in koa routes.

### ISSUE THREAD

**Issue by varHarrie** [socketio/socket.io#2696]
``` javascript
const app = require('koa')()
const server = require('http').createServer(app.callback())
const io = require('socket.io')(server)
const Router = require('koa-router')

io.on('connection', function(){ /* … */ })
app.context.io = io

const router = new Router()
// routes
router.get('/someurl', async (ctx) => {
  console.log(ctx.io) // I can get io, but how to get current socket instance
})

app.use(router.routes())
app.use(router.allowedMethods())

server.listen(3000);
```

I can get io, but how to get current socket instance.

**Comment by MaffooBristol** [comment]
The current socket instance is contained within `io.on('connection')`; it's the first parameter. So I *reckon* you'd want to do something like this, but I'm not that well versed in koa:

```javascript
router.get('/someurl', async (ctx) => {
  ctx.io.on('connection', (socket) => console.log(socket));
});
```

**Comment by varHarrie** [comment]
@MaffooBristol Thx for reply, but I think `connection` event will be emitted before I access `/someurl`.

**Comment by MaffooBristol** [comment]
Okay, well if that doesn't work, is there any reason not to wrap the `router.get()` lines inside the main `io.on('connection')` callback?

**Comment by varHarrie** [comment]
@MaffooBristol koa app wiil add the route `/someurl` whenever someone connected, even if it's already exists. It may be undesirable.

**Comment by varHarrie** [comment]
```javascript
router.get('/someurl', async (ctx) => {
  console.log(ctx.io)
  const socket  = ctx.sockets.connected[socketId]  // send the socketId from front end
})
```
It's the best solution that I can find, but still not good enough.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).

**Comment by YikaJ** [comment]
There is a not bright solution. Try to use `events.EventEmitter`, it may works. But it's ugly when you write your code with lots of event callback.

**Comment by saviourdog** [comment]
any progress?
