### ISSUE TITLE
How can I store socket object in Mongodb?

### ISSUE THREAD

**Issue by jimmyzzzzzzz** [socketio/socket.io#2697]
Now I'm running socket server on a single core and saving sockets to an array. I need to save everything to cloud in order to scale later. How can I save the socket object to Mongodb and cast it back to a socket object? I have tried JSON.stringify(socket); I got TypeError: Converting circular structure to JSON. also I searched online but couldn't find any answer to this.

**Comment by carpii** [comment]
You can't serialise sockets like this (at least not in a way that can be unserialised later, and still somehow be a valid connection).

Instead decouple all the user data form the socket, and serialise that instead. 
Then you would authenticate or identify an incoming socket, and tie that to the userdata in mongo

**Comment by darrachequesne** [comment]
In order to scale to multiple nodes, please take a look at [socket.io-redis](https://github.com/socketio/socket.io-redis) or [socket.io-mongodb](https://github.com/losandes/socket.io-mongodb)

**Comment by jimmyzzzzzzz** [comment]
thanks for the replies. Finally I'm using Redis. It works perfectly with socket.io

**Comment by darrachequesne** [comment]
Nice to hear :+1: 

Could you please close the issue?

**Comment by mobility2015** [comment]
Dear jimmy, can you please help this trouble with redis to me? thank you very much

**Comment by itachiRedhair** [comment]
@jimmyzzzzzzz can you explain how are you using 'redis' to store your socket instances. Becuase I don't see 'socket.io-redis' is made for that purpose.

**Comment by RezaErfani67** [comment]
@jimmyzzzzzzz 
can you explain how are you using 'redis' to store your socket instances.
