### ISSUE TITLE
How to handle reconnection on server side?

### ISSUE THREAD

**Issue by overflowz** [socketio/socket.io#2700]
Hi, I'm trying to handle reconnection on server side, but can't find anything in documentation to do so. I'm trying to make MMOG style game, where clients are connecting with a JWT token (which expires in 30 seconds, just to authorize first time and keep working on). Here's the scenario:
1) User connects to socket.io server using `var socket = io.connect('/', { forceNew: false });` to be able to reconnect later.
2) User connects to game, token is decoded via socketio-jwt authorize:

```
server.on('connection',
    ioJwt.authorize({
      secret: config.jwt_secret,
      decodedPropertyName: 'token',
      timeout: 5000 // disconnect after X seconds if not authenticated.
    }))
    .on('authenticated', authenticated);
```

3) On successful authentication, user plays a game, of course.

So let's say, internet connection was interrupted for a few seconds, socket automatically tries to reconnect by default (using forceNew: false). So, I'd like to wait user to reconnect let's say, in 5 seconds, if not then just drop him out. Something like this:

```
var authenticated = function (client) {
  console.log('authenticated', client.token);
  client
    .once('disconnect', function () { this.reconnectTimeout = setTimeout(function() { remove_user_from_game_here(); }, 5000); })
    .once('reconnect', function () { clearTimeout(this.reconnectTimeout); }); // this never gets fired.
};
```

May I ask how can I do such thing?

Regards.

**Comment by carpii** [comment]
''''
var authenticated = function (client) {
''''

Is this server-side code?  'reconnect' is a client-side event only, as far as I know, so the server will never see it. 
The server simply gets a connect event as it did initially.

What is remove_user_from_game_here() actually doing?

To remove users from the game, record a timestamp for the user when the server gets the disconnected event
Then have a server routine which cleans up once it sees they have been disconnected for more than 5 seconds.

Don't take this as gospel though, it's just based on my experience and the (kinda crumby) API docs

**Comment by darrachequesne** [comment]
For future readers: you can generate a session ID on the server-side, and store it in the localStorage on the client-side.

Please see the following example: https://socket.io/get-started/private-messaging-part-2/#Persistent-session-ID
