### ISSUE TITLE
socket.io working on localhost but not on ubutu live server

### ISSUE THREAD

**Issue by themodernpk** [socketio/socket.io#2701]
socket.io working fine on local server but on live ubutu server, it's showing error following error :
`<mywebsite>/socket.io/?EIO=3&transport=polling&t=LUAiPxI 404 (Not Found)`

**Comment by carpii** [comment]
Not a socket.io issue. Check your webserver or frontend proxy config

**Comment by jamiehutber** [comment]
There is a proxy config for socket.io?

**Comment by vadirajkulkarni** [comment]
Same issue.

**Comment by rp21buzz** [comment]
Has any one managed to figure this out.
have been banging my head over this.

**Comment by rp21buzz** [comment]
I Kinda Did fix
unless a path option is specifically configured on client end it ain't working.
const io = io(window.location.origin,{
path:'/'
});

I found the fix here
https://stackoverflow.com/questions/58600810/socket-io-just-not-working-without-any-error

**Comment by darrachequesne** [comment]
For future readers: please see the documentation [here](https://socket.io/docs/v3/troubleshooting-connection-issues/).

Closed due to inactivity, please reopen if needed.
