### ISSUE TITLE
Emit to a specific socket id not working

### ISSUE THREAD

**Issue by TheCrow1213** [socketio/socket.io#2703]
From the docs: `socket.broadcast.to(id).emit('my message', msg);`
http://socket.io/docs/rooms-and-namespaces/#default-room

But, doesn't seem to work. I see the socket-io parser serializing the message, but the outgoing packet is never written. For now I'll maintain my own list of connected sockets.

**Comment by carpii** [comment]
socket.broadcast sends it to all sockets apart from the originating socket

Just use socket.emit to send to that socket

**Comment by TheCrow1213** [comment]
Thanks for the reply @carpii, got it figured out but I appreciate you replying :) I'll close this issue. Thanks!

**Comment by Nassefferjeni** [comment]
@TheCrow1213  what solution did you find ? 
i seem to have the same problem ...

**Comment by darrachequesne** [comment]
@Nassefferjeni please take a look at https://socket.io/docs/emit-cheatsheet/
