### ISSUE TITLE
Problem with Intel XDK on Android Mobile with Socket.io Js Client (Not the Emulator)

### ISSUE THREAD

**Issue by chon9** [socketio/socket.io#2705]
> `:\Users\Alex\Documents\tester\www>node --debug accounting
> Debugger listening on port 5858
>  /#PGoZq8tP68D18UpDAAAA a client connected Wed Oct 05 2016 19:48:33 GMT+0800 (Malay Peninsula Standard Time)
> /#C5hOrMKl_58DGP40AAAB a client connected Wed Oct 05 2016 19:48:38 GMT+0800 (Malay Peninsula Standard Time)
> /#dtoIaEKkBWfHjedIAAAC a client connected Wed Oct 05 2016 19:48:43 GMT+0800 (Malay Peninsula Standard Time)
> /#hDjXP3zrmTA4sAjJAAAD a client connected Wed Oct 05 2016 19:48:46 GMT+0800 (Malay Peninsula Standard Time)
> /#yGMgSLxYmzE8hgX2AAAE a client connected Wed Oct 05 2016 19:48:49 GMT+0800 (Malay Peninsula Standard Time)
> /#CrNInuw1LYGdiWmBAAAF a client connected Wed Oct 05 2016 19:48:54 GMT+0800 (Malay Peninsula Standard Time)
> /#iAZgKePfxuJte0c2AAAG a client connected Wed Oct 05 2016 19:48:59 GMT+0800 (Malay Peninsula Standard Time)
> /#CxkNm3d5GGQBrPgpAAAH a client connected Wed Oct 05 2016 19:49:04 GMT+0800 (Malay Peninsula Standard Time)
> /#-5mnOCGdK37RNjO0AAAI a client connected Wed Oct 05 2016 19:49:09 GMT+0800 (Malay Peninsula Standard Time)
> /#BqKiH3Av9jRtZZn1AAAJ a client connected Wed Oct 05 2016 19:49:14 GMT+0800 (Malay Peninsula Standard Time)
> /#U15i6beXbyGugJe-AAAK a client connected Wed Oct 05 2016 19:49:19 GMT+0800 (Malay Peninsula Standard Time)
> /#hh0XSR1zfHR42s9cAAAL a client connected Wed Oct 05 2016 19:49:24 GMT+0800 (Malay Peninsula Standard Time)
> /#GTGMQXKr9QsYokMWAAAM a client connected Wed Oct 05 2016 19:49:29 GMT+0800 (Malay Peninsula Standard Time)
> /#zMjPaWRXDJW9-VTbAAAN a client connected Wed Oct 05 2016 19:49:35 GMT+0800 (Malay Peninsula Standard Time)
> /#KszEpitUzwcXeLfaAAAO a client connected Wed Oct 05 2016 19:49:40 GMT+0800 (Malay Peninsula Standard Time)
> /#fuHD_UyyZ72ewfNOAAAP a client connected Wed Oct 05 2016 19:49:45 GMT+0800 (Malay Peninsula Standard Time)
> /#SbuBFqcA-cYt-7qQAAAQ a client connected Wed Oct 05 2016 19:49:50 GMT+0800 (Malay Peninsula Standard Time)
> /#9dplSBnE6IJRQ5CBAAAR a client connected Wed Oct 05 2016 19:49:55 GMT+0800 (Malay Peninsula Standard Time)
> /#PGoZq8tP68D18UpDAAAAa client disconnected Wed Oct 05 2016 19:49:58 GMT+0800 (Malay Peninsula Standard Time)
> /#fPd6KV_zbcKfKuS3AAAS a client connected Wed Oct 05 2016 19:50:00 GMT+0800 (Malay Peninsula Standard Time)
> /#C5hOrMKl_58DGP40AAABa client disconnected Wed Oct 05 2016 19:50:03 GMT+0800 (Malay Peninsula Standard Time)
> /#ES5D34fJ1MaXkkm2AAAT a client connected Wed Oct 05 2016 19:50:05 GMT+0800 (Malay Peninsula Standard Time)
> /#dtoIaEKkBWfHjedIAAACa client disconnected Wed Oct 05 2016 19:50:08 GMT+0800 (Malay Peninsula Standard Time)
> /#AxvEvbBrL30J3iV1AAAU a client connected Wed Oct 05 2016 19:50:10 GMT+0800 (Malay Peninsula Standard Time)
> /#yGMgSLxYmzE8hgX2AAAEa client disconnected Wed Oct 05 2016 19:50:14 GMT+0800 (Malay Peninsula Standard Time)`

I am facing problem where the client making mass connections to the server but not a successful one, we tried empty all our codes and left a very normal connection to Socket Io (with latest js client) for testing, yet we are still facing problem where the socket.io successful to connect from all browser, but not cordova apps compiled with Intel Xdk on physical Android devices. When we trying to debug the apps, we found that socket were connected but the readyState still show closed in the physical device.

Method of fixes tried:
Send ping to server and reply pong manually to client
add {'forceNew': true }

Sorry for the bad english.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
