### ISSUE TITLE
how to send a Ack from Server to Client? i use android client,but it is no work

### ISSUE THREAD

**Issue by xnchen1995** [socketio/socket.io#2706]
I use the socket.io-client-java to build a client,but when i emit a new message from Client to Server,not the Ack return. 

here is the socket.io-client-java  official document. i can't follow that i can auto get a callback with Ack when the server received a message? if not,how do
![image](https://cloud.githubusercontent.com/assets/11613388/19116134/01514918-8b47-11e6-880f-9580a30de41a.png)

Android client
```
        mSocket.emit("new message", message, new Ack() {
            @Override
            public void call(Object... args) {
                Toast.makeText(MainActivity.this,"receiver",Toast.LENGTH_LONG).show();        //no work
            }
        });
```

Server

```
  // when the client emits 'new message', this listens and executes
  socket.on('new message', function (data) {
    // we tell the client to execute 'new message'
    socket.broadcast.emit('new message', {
      username: socket.username,
      message: data
    });
  });
```

thanks

**Comment by carpii** [comment]
To send a message to that specific socket, use socket.emit() not socket.broadcast.emit() 

From http://socket.io/docs/

"Broadcasting means sending a message to everyone else except for the socket that starts it."

**Comment by carpii** [comment]
@xnchen1995 Please can you close this ticket if you are not having further problems?
