### ISSUE TITLE
socket.io 1.5.0 backwards incompatible with socket.io-client < 1.5.0

### ISSUE THREAD

**Issue by zivester** [socketio/socket.io#2712]
We just had a breaking application because our server socket.io upgraded before our clients could.
#2422 seems to be the culprit as it strips all query parameters that are not `t`, `EIO` or `transport`.  With our `1.3.*` client, we need the `token` parameter to be parsed as well.

**Comment by Root-Core** [comment]
There might be an related issue. SocketIO-jwt has some serious problems, handling authentication while multiplexing is enabled. ([#95 @ socketio-jwt](https://github.com/auth0/socketio-jwt/issues/95))

It is working, if multiplexing is disabled though.

**Comment by shoerob** [comment]
I'm also seeing this problem. A custom value I'm placing on the query appears to be dropped. Should I not be placing values on the query? I'm reverting to 1.4.8 for now.

**Comment by BlueWinds** [comment]
The reverse appears to be true as well - socket.io.client 1.5.0 appears to also be incompatible with < 1.5.0.

I haven't looked into the precise cause yet, but reverting to 1.4.8 for the client fixed my issue as well.
