### ISSUE TITLE
Accept events from specific room only?

### ISSUE THREAD

**Issue by overflowz** [socketio/socket.io#2713]
So far no response to latest issues. I'd like to know if it's possible to listen some events only from specific channel?

e.g
```
...
client.on('join', function(room) {
  client.join(room);
  client.on('event to be accepted only from this room', function() {
    console.log('got it');
  });
});
```

**Comment by carpii** [comment]
Rooms are used by socket.io server to help manage what subset of sockets you want to send a message to

The socket.io client does not receive any information about the room it was intended for. It just gets the message

If you want the client to respond to certain messages, but only from certain rooms, then you should include some room identifier in the message you broadcast
Then your client can just listens for all occurrences of that message, and once received, can look at the roomid in the packet and decide if it needs to respond to it

**Comment by overflowz** [comment]
Thanks for the reply! I'm already working on that :)
