### ISSUE TITLE
Remote Server CORS. Possible?

### ISSUE THREAD

**Issue by roddh** [socketio/socket.io#2715]
I don't know if this is an issue with socket.io but I have searched all over for this.
I'm building an application where the socket.io server will be hosted in a remote server.
Clients from all possible domains will connect to it, including mobile apps. However, after setting up CORS for Express and the Cross-Origin to "*", I get the following error on Chrome:

A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:8000' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.

I understand the problem with the security problem with wildcards, but what exactly can I do to make any client connect to the server securely? Or is it not possible at all?

Regards

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
