### ISSUE TITLE
Connect to a socketIO server on iOS with SocketRocket failed

### ISSUE THREAD

**Issue by creeveliu** [socketio/socket.io#2716]
I am using this [SocketRocket](https://github.com/facebook/SocketRocket) to connect to a socketIO server, but it always return:

`didFailWithError Error Domain=SRWebSocketErrorDomain Code=2132 "received bad response code from server 502" UserInfo={NSLocalizedDescription=received bad response code from server 502, HTTPResponseStatusCode=502}`

**Comment by carpii** [comment]
According to github, the SocketRocket unit tests are all passing

So I guess first you need to find out what socket.io server version it's actually testing against.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
