### ISSUE TITLE
[Solved] Socket.io gets 400 "bad handshake method" on Firefox, but not Chrome or Safari

### ISSUE THREAD

**Issue by richb-hanover** [socketio/socket.io#2717]
I have a test page (below) that creates a socket.io connection back to the server, then listens for and logs 'time' messages. It works as expected for recent Chrome and Safari on OSX 10.10.5. I'm using Socket.io 1.5.0 for all tests.

With Firefox 49.0.1, each POST request gets a response with `bad handshake method`. There is no `Socket.io connected...` message in the console, and no `time` messages arrive (see image). Other interesting info about the POST is:

```
- Params: EIO:3, t: LUuPeKr, transport:polling
- POST raw data: "1:1"
```

The test page connects back to a create-react-app app (0.6.1) that proxies the request to my own server on localhost:3001. As noted above, this page works as expected with Chrome and Safari. 

I searched Stackexchange/Overflow without results, so I come here. What other info could I provide to debug this?

![image](https://cloud.githubusercontent.com/assets/1094930/19312570/ff8a9c1e-9060-11e6-96d1-fee166615e68.png)

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SOCKET.IO TEST PAGE</title>
</head>
<body>
<h1>Socket.io Test Page</h1>

<script src="/socket.io/socket.io.js"></script>
<script>
    var socket = io();
    socket.on('connect', function(data){
        console.log("Socket.io connected...");
    });

    socket.on('time', function (data) {
        console.log(data);
    });
</script>
</body>
</html>
```

**Comment by carpii** [comment]
When you view similar activity log in Chrome, is it also doing a POST?
What parameters are present in the POST?

Looking at socket.io source, its checking for the existence of a 'sid' query parameter (which I'm guessing is socketid). 
If this is not set, AND its using POST, then it will return a BAD_HANDSHAKE_METHOD error, which is what you're seeing

**Comment by richb-hanover** [comment]
GOOD SLEUTHING!  And thanks for digging into this.

I have verified that both socket.io and socket.io-client in node_modules are version 1.5.0. (I have `1.5.0` in both my client and server package.json files - is there an API to get socket.io to divulge its version to confirm?)

And you're right, in Chrome and Safari (both of which work), there appear to be alternating GET and POST requests *with* `sid=...`:
```
engine.io-client:polling-xhr xhr open POST: http://localhost:3000/socket.io/?EIO=3&transport=polling&t=LVUP-70&sid=l62Bzjgs0ZYkSf3XAAAA +2ms
...
engine.io-client:polling-xhr xhr open GET: http://localhost:3000/socket.io/?EIO=3&transport=polling&t=LVUP-7D&sid=l62Bzjgs0ZYkSf3XAAAA +1ms
```
In Firefox, they alternate as well, but no sid is present in either GET/POST request:
```
engine.io-client:polling-xhr "xhr open POST: http://localhost:3000/socket.io/?EIO=3&transport=polling&t=LVUQXbB" +1ms
...
engine.io-client:polling-xhr "xhr open GET: http://localhost:3000/socket.io/?EIO=3&transport=polling&t=LVUQYXf" +1ms
```
I'm using the default proxy behavior from [create-react-app](https://github.com/facebookincubator/create-react-app) to go to my server code. 

I think you're on to something with the cookies, though:

1) GET Request /test.html (send some garbage cookies with the request __utma, etc.)
2) 200 Response has no new cookies
3) GET request for /socket.io.js
4) 200 Response has the "io" cookie that appears to be a sid
5) GET request for /socket.io has the "io" cookie with params for EIO, t, & transport *but* Firefox does not include a sid parameter
6) 200 response
7) POST request for /socket.io has the "io" cookie with params for EIO, t, & transport *but* Firefox does not include a sid parameter
8) 400 response with "bad handshake method"

What's confusing is that the identical client code (above),  proxy (create-react-app) and server code (below) handle the requests. The server code sets up the socket and then sends out regular 'time' messages. NB: When Firefox loads the page, the console does *not* contain the `Client connected...` message, but Safari or Chrome display it. 

So... Why doesn't Firefox include the `sid=...` parameter? How can I coax it to do so?

```
var io = require('socket.io')(server);                                    // this is the socket.io listener
io.on('connection', (socket) => {                                         // when we get a connection from a client
  const count = Object.keys(io.sockets.connected).length;
  console.log('Client connected. Socket id %s, (%s)', socket.id, count);  // log when they connect

  socket.on('disconnect', function () {                                   // log when they go away
    const count = Object.keys(io.sockets.connected).length;
    console.log('Client disconnected. Socket id %s (%s)', socket.id, count);
  });
});

// Send a message to all connected clients every 10 seconds
// NB It is OK to io.emit() if no clients are connected,
//  The test for connected clients simply minimizes excess log messages
setInterval( () => {
  const count = Object.keys(io.sockets.connected).length;   // get number of clients
  if (count > 0) {                                          // if anyone's connected...
    const msg = `Time is now: ${new Date()}`;               // get the date & time
    // console.log(`Sending to (${count}) clients: ${msg}`);   // log it
    io.emit('time', { text: `${msg}`});                     // and send to all clients
  }
}, 10000);
```

**Comment by richb-hanover** [comment]
@nkzawa  This problem looks a bit like #2391- do you have any insights here? Many thanks.

**Comment by carpii** [comment]
As far as I can tell, the routine which checks for existence of 'sid' parameter, and then rejects it with a bad handshake, ONLY happens when the transport is trying to upgrade get websocket.

I found this in ./node_modules/socket.io/node_modules/engine.io/lib/server.js  (in the verify() function)

> Why doesn't Firefox include the sid=... parameter? How can I coax it to do so?

Not entirely sure :(  But Firefox is working I think, so maybe its a red herring

As far as I can see though, BAD_HANDSHAKE error can only ever occur after or during an upgrade to websocket, and never during polling
We know Firefox supports websockets, but could it be that Firefox is choosing not to upgrade to websocket for some reason? Maybe Safari is trying to upgrade and thats why the error manifests itself.

Admittedly its all a bit vague at the moment, I can't claim I can understand what's going on, but it would be worth checking what transport each browser is using when it *does* work

**Comment by richb-hanover** [comment]
>>Why doesn't Firefox include the sid=... parameter? How can I coax it to do so?

>Not entirely sure :( But Firefox is working I think, so maybe its a red herring

If you mean that (in other circumstances) Firefox works with socket.io, then I agree.
>As far as I can see though, BAD_HANDSHAKE error can only ever occur after or during an upgrade to websocket, and never during polling
>I found this in ./node_modules/socket.io/node_modules/engine.io/lib/server.js (in the verify() function)

>We know Firefox supports websockets, but could it be that Firefox is choosing not to upgrade to websocket for some reason? Maybe Safari is trying to upgrade and thats why the error manifests itself.

... Safari is trying to upgrade...[?]

>Admittedly its all a bit vague at the moment, I can't claim I can understand what's going on, but it would be worth checking what transport each browser is using when it does work

If the parameters are to be believed, `&transport=polling` for all three browsers. Or is there another way to check?

**Comment by carpii** [comment]
> As far as I can see though, BAD_HANDSHAKE error can only ever occur after or during an upgrade to websocket, and never during polling

Sorry, ignore this. I've since realised it's not accurate, and can indeed occur just using polling.

**Comment by richb-hanover** [comment]
I haven't installed fiddler yet, but can reproduce the problem with a much smaller project that I can share. 

Read how to demonstrate the problem at https://github.com/richb-hanover/test-socketio-400/blob/master/test-socketio-400.md Thanks!

**Comment by richb-hanover** [comment]
**Update:** I am able to confirm that this behavior (400 error on the socket.io POST request) occurs with Firefox (newly-installed) on Win10, when connecting to my test server (see previous note).

Chrome on Win10 and Edge on Win10 both work as expected.

**Comment by Nibbler999** [comment]
Thanks for posting the example. This can be fixed by making firefox send the same accept header that chrome does for these requests.

**Comment by darrachequesne** [comment]
@richb-hanover did v1.5.1 solve your issue?

**Comment by richb-hanover** [comment]
I haven't checked. (I patched node_modules/socket.io-client/socket.io.js: that worked to move ahead.) I will check in a day or so, and update the ticket with the results.

**Comment by hifall** [comment]
@richb-hanover, is the issue random?

I remember seeing this a while back, though it was random, and I wasn't able to find a consistent repro.

**Comment by richb-hanover** [comment]
I had a reproducible test case (see my original post) with Firefox (only). @Nibbler999 found and committed a change that forced Firefox to make an explicit request for "*/*". This is in socket.io@1.5.1

I have not confirmed that v1.5.1 works, but a manual patch in my code solved the problem. I got switched to another project, but I still hope to test this in a couple days.

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io-client/pull/508.
