### ISSUE TITLE
Cannot connect on Safari using reverse proxy and SSL

### ISSUE THREAD

**Issue by alexander-daniel** [socketio/socket.io#2718]
Hello there, and thanks for this awesome module! So far its been amazing to use, save for this little issue I've been running into.

For some reason or another, Safari hangs on a polling request, even after the first few go through OK.
### The first 3 are fine here

![screen shot 2016-10-13 at 10 14 42 am](https://cloud.githubusercontent.com/assets/5408720/19352576/49b4a26c-912e-11e6-92e3-5af4bd02b65a.png)
### The last one

![screen shot 2016-10-13 at 10 15 09 am](https://cloud.githubusercontent.com/assets/5408720/19352586/54666d3a-912e-11e6-945d-51f87edb709a.png)

<img width="151" alt="screen shot 2016-10-13 at 10 15 00 am" src="https://cloud.githubusercontent.com/assets/5408720/19352592/5756916e-912e-11e6-950f-e416d5c8119c.png">

Im using a reverse-proxy (nginx) to route all requests made to `/ws/` to hit our websocket server on port `3000`. HTTPS works fine on all other browsers, but Safari just seems to hang and freeze up if I have the console open.
## Client code:

```
const socket = socketIO("https://outro.io", {
        path: "/ws/socket.io",
        reconnectionDelay: 5000
});
```
## nginx conf

```
worker_processes 4;
error_log  /var/log/nginx/error.log  warn;

events { worker_connections 1024; }

http {

  access_log /var/log/nginx/access.log;
  client_max_body_size 200m;

  server {
    listen 443 ssl;

    ssl_certificate /etc/xxx.pem;
    ssl_certificate_key /etc/xxx.pem;
    ssl_trusted_certificate /etc/xxx.pem;

    location / {
      proxy_pass http://outro:5759;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }

    location /ws/ {
      proxy_pass http://outro:3000/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }
  }

  server {
    listen 80;
    return 301 https://$host$request_uri;
  }
}
```

Hopefully someone else has seen this issue and can maybe lend a hand! Appreciate the time!

**Comment by alexander-daniel** [comment]
sample nginx config:

```
worker_processes 4;
error_log  /var/log/nginx/error.log  warn;

events { worker_connections 1024; }

http {

  access_log /var/log/nginx/access.log;
  client_max_body_size 200m;

  server {
    listen 443 ssl;

    ssl_certificate /etc/xxx.pem;
    ssl_certificate_key /etc/xxx.pem;
    ssl_trusted_certificate /etc/xxx.pem;

    location / {
      proxy_pass http://outro:5759;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }

    location /ws/ {
      proxy_pass http://outro:3000/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }
  }

  server {
    listen 80;
    return 301 https://$host$request_uri;
  }
}
```

**Comment by carpii** [comment]
What appears in your nginx logs for this stalled request?

**Comment by dleeq8** [comment]
something like that happened to me before cause some iphone users fail to connect
and fixed by choosing correct ssl key/cert
make sure your:
   ssl_certificate /etc/xxx.pem;
    ssl_certificate_key /etc/xxx.pem;
    ssl_trusted_certificate /etc/xxx.pem;
is pointed to what it says

**Comment by davidolen** [comment]
is your cert self-signed?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
