### ISSUE TITLE
client cannot connect to server when web page changed

### ISSUE THREAD

**Issue by L30Yu** [socketio/socket.io#2725]
Hi, I am new to Node.js and Socket.io. I am trying to create a PC client node.js app to talk with a node.js server.

It works good at the beginning of starting server.js, the client.js could connect to server.

However, If I use a separate browser to access my server, do something like list users, login.....

If I close the client.js manually, and restart client.js again, it cannot connect to server anymore. No error message. 

Does not find any error message.

I create socket on Server.js like this:

```javascript
var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);

app.get('/', function(req, res){
  res.sendfile('index.html');
});

io.on('connection', function(socket){
  console.log('a user connected');
});

http.listen(3000, function(){
  console.log('listening on *:3000');
});
```

separate nodejs app client.js : 

```javascript
let socket = require("socket.io-client")("http://127.0.0.1:3000/");
socket.on('connect', function (data) {
  socket_connect = true;  
});
```

I do not have any socket on html page, so, when I access server by browser, it is just a normal step to open a html page.

![image](https://cloud.githubusercontent.com/assets/12931325/19528409/27c75680-95e9-11e6-9030-f982f5950ca5.png)

**Comment by carpii** [comment]
> console.log('listening on *:3000');
> console.log('a user connected');

Neither of these server logs are appearing in the screenshots you pasted?

Do you have a on.('disconnect') handler in your server code? If so please paste that too.
It needs to be placed inside the connection block, like this...

````
    io.sockets.on('connection', function (socket) {
        socket.onEvent('connecting', function () {
            console.log('connecting');
        });
    
        socket.onEvent('disconnect', function () {
            console.log('disconnected');
        });
    }
''''
