### ISSUE TITLE
If only using websockets transport, are sticky sessions required?

### ISSUE THREAD

**Issue by manast** [socketio/socket.io#2728]
Since there seems to be a lot of discussion and hacky workarounds to get socket.io working in clusterified environments, I am wondering, are sticky sessions really needed when just relying on the websocket transport? If the answer is no, I think we should update the webpage explicitly telling this fact. It may make the life easier to many people, specially nowadays when websockets are for most practical purposes ubiquitous.

**Comment by idibidiart** [comment]
Wow. Maintainers. Bump+

**Comment by darrachequesne** [comment]
For future readers: no, sticky sessions are not required when using WebSocket only, since it relies on a single TCP connection.

Added in the documentation here: https://socket.io/docs/v3/using-multiple-nodes/#Why-is-sticky-session-required
