### ISSUE TITLE
Online examples are not functioning

### ISSUE THREAD

**Issue by AntiAsko** [socketio/socket.io#2736]
_Note_: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)
### You want to:
- [x] report a _bug_
- [ ] request a _feature_
### Current behaviour

While trying to check your online examples I saw that none of them is functional. Whether is a known issue or not I considered a good idea to inform you. The error receiving is:

_XMLHttpRequest cannot load http://slack.socket.io/socket.io/?EIO=3&transport=polling&t=LVuf8-O. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://socket.io' is therefore not allowed access. The response had HTTP status code 502._
### Setup
- OS: Ubuntu 16.04
- browser: chrome
- socket.io version:

**Comment by iongion** [comment]
Had some headaches with the `middleware` for authentication, all the examples say to migrate to this:
```
io.use(function(socket, next) {
  var handshakeData = socket.request;
  next();
});
```
But there I found it to be more like this:
```
io.use(function(socket, next) {
  var handshakeData = socket.handshake;
  next();
});
```

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
