### ISSUE TITLE
Namespace connections not working on remote server

### ISSUE THREAD

**Issue by dolftax** [socketio/socket.io#2738]
```
const http = require('http').createServer()
let io = require('socket.io')(http)

io.on('connection', (socket) => {
// Works
})

global.queueSock = io.of('/queue')

// Connection listener
global.queueSock.on('connection', (socket) => {
// Doesn't work
})
```
- It isn't the issue with client
- It works well and good locally, but doesn't work when hosted on a remote server

Socket.io v1.5.1 // Node v6.9.0

**Comment by tvnhan** [comment]
Hi dolftax,
I have same problems with youwhen i working with new update of socket.io.
COuld you share me how to you solve this problem?
Thank you!

**Comment by dolftax** [comment]
@tvnhan Well, our my case, it was issue with AWS load balancer and nginx config. If you are in the same stack, read upon websocket connection config for nginx and use Application load balancers over elastic.
