### ISSUE TITLE
Option to provide a callback to io.close() to pass to httpServer.close()

### ISSUE THREAD

**Issue by mhmeadows63** [socketio/socket.io#2739]
I can see that `io.close()` calls `httpServer.close()`.

The `httpServer.close()` takes an optional callback that is called once all clients have disconnected.

However, the call to `io.close()` provides no way to supply the callback.

Is it possible to consider changing the following line in `Server.prototype.close` from:
`this.httpServer.close();`
to
`this.httpServer.close.apply(this.httpServer, arguments);`

**Comment by darrachequesne** [comment]
PR is welcome!

I'd suggest making the argument explicit in the code, something like:
``` 
Server.prototype.close = function(fn){
...
  if(this.httpServer){
    this.httpServer.close(fn);
  } else {
    fn && fn(null);
  }
```
What do you think?

**Comment by mhmeadows63** [comment]
Good idea, and well done for spotting the absent httpServer scenario.

I'll try for a PR over the coming week, unless you get to it sooner.

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io/pull/2748
