### ISSUE TITLE
 'Access-Control-Allow-Origin' header when the credentials flag is true.

### ISSUE THREAD

**Issue by ChuntheQhai** [socketio/socket.io#2740]
I am keep getting this issues, I had tried to use add my headers or using cors with domain allow origin. Still getting this error. I am currently using ExpressJS for my server side (localhost:8888) and angular localhost (192.168.2.15:8100). 

This error always happen when my front-end angular tried to connect to localhost:8888 with socket.io :

> XMLHttpRequest cannot load http://localhost:8888/socket.io/?EIO=3&transport=polling&t=LWA2z-G. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://192.168.2.15:8100' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.

Response Header:

> HTTP/1.1 404 Not Found
> X-Powered-By: Express
> Access-Control-Allow-Credentials:false
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Headers: Content-Type
> Access-Control-Allow-Methods: PUT, GET, POST, DELETE, OPTIONS
> X-Content-Type-Options: nosniff
> Content-Type: text/html; charset=utf-8
> Content-Length: 65
> Date: Fri, 28 Oct 2016 06:55:56 GMT
> Connection: keep-alive

Request Header:

> Accept:_/_
> Accept-Encoding:gzip, deflate, sdch
> Accept-Language:en-US,en;q=0.8
> Connection:keep-alive
> Host:localhost:8888
> Origin:http://192.168.2.15:8100
> Referer:http://192.168.2.15:8100/
> User-Agent:Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.23 Mobile Safari/537.36

**Comment by darrachequesne** [comment]
@ChuntheQhai were you able to solve your issue? I think the `404 Not Found` error suggests that the socket.io server cannot be reached.

Related: https://github.com/socketio/socket.io/issues/1979
