### ISSUE TITLE
socket.io is throwing 502 error with using "pm2 --watch option" on server.

### ISSUE THREAD

**Issue by papmodern** [socketio/socket.io#2741]
#### Expected behaviour

Consistent socket.io connection between client and server after using pm2 --watch option.
#### Actual behaviour

Socket.io connection breaks sometimes with 502 (Bad Gateway) errors (Only with using pm2 --watch)
#### Steps to reproduce

Create an expressjs application, consuming socket.io package for managing socket connections.
Start nginx server and create a virtual host to redirect requests to local running application (which is running by pm2 and with --watch option on port 3000)
Now try to calling some functions on server or vice versa.
#### Software versions used

pm2 1.1.3
node 6.5.0
npm 3.10.3
express 4.14.0
socket.io 1.4.8
nginx 1.10.1
centos 7

As I'm not sure the problem is in socket.io, I will add this issue on pm2 project too!

**Comment by songguangyu** [comment]
**environment**
pm2 cluster
**error**
400 
{code: 1, message: "Session ID unknown"}
502
(Opcode -1)

**Comment by darrachequesne** [comment]
For future readers:

Please check the documentation here: https://socket.io/docs/v4/pm2/
