### ISSUE TITLE
Client ack for server-emitted events.

### ISSUE THREAD

**Issue by hifall** [socketio/socket.io#2742]
We use this code to emit events on node.js/socket.io server:

    socketio.sockets.in(room).emit('event', data);

Is it possible for the server to receive a confirmation from the clients?

I know this is possible and common the other way around, i.e., emit an event from client, and get the confirmation from the server. But I can't find any topic on the scenario mentioned above.

If it's not possible, how can I detect server-emitted event delivery errors?

**Comment by darrachequesne** [comment]
AFAIK, there is no built-in acknowledgement when emitting to several clients. I guess you'll have to add your own, to detect delivery errors.

**Comment by darrachequesne** [comment]
Closed, please reopen if needed.
