### ISSUE TITLE
Demo Chat from Main Site doesn't work

### ISSUE THREAD

**Issue by TilliWilli5** [socketio/socket.io#2743]
Address http://socket.io/demos/chat/ 
nor Firefox, nor Chrome cant handle it

![socketiobug](https://cloud.githubusercontent.com/assets/5957294/19971455/ada953b4-a211-11e6-910f-e858e2b68419.png)

This file http://chat.socket.io/socket.io/socket.io.js has bad ending:
...
 if (this.backoff.attempts >= this._reconnectionAttempts) {
    debug('reconnect failed');
    this.backoff.reset();
    this.emitAll('reconnect_failed');
    this.reconnecting = false;
  } else {
    var delay = this.backoff.durati

This is the last line in the file - maybe its the reason

**Comment by mrwillis** [comment]
Same here.

**Comment by tameravci** [comment]
Same

**Comment by JacobSiegel35** [comment]
same yo.

**Comment by chalkers** [comment]
Seems like weplay.io and socket.computer is down too

**Comment by mandazi** [comment]
It is not working for me as well.

**Comment by sulfo** [comment]
Aaaand same here Would be nice to see it up and working again.

**Comment by alexhernandez** [comment]
Any update on this?

**Comment by m1guelpf** [comment]
same here

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
