### ISSUE TITLE
How to get socket's session id in client side.. This is my service in angularjs!

### ISSUE THREAD

**Issue by nischay13may** [socketio/socket.io#2746]
When I am printing the id its showing undefined and when i am printing only Socket object its showing id but I am not able to access it.
`
app.factory('socket',function($rootScope){

	var socket = null;
	return {
		connect: function(){
			socket = io.connect();
			console.log(socket.id);  //If printing console.log(socket) then showing the object with its id
		},
	    on: function (eventName, callback) {
	      socket.on(eventName, function () {  
	        var args = arguments;
	        $rootScope.$apply(function () {
	          callback.apply(socket, args);
	        });
	      });
	    },
	    emit: function (eventName, data, callback) {
	      socket.emit(eventName, data, function () {
	        var args = arguments;
	        $rootScope.$apply(function () {
	          if (callback) {
	            callback.apply(socket, args);
	          }
	        });
	      })
	    }
	  };`

**Comment by darrachequesne** [comment]
`socket.id` should be available once the socket is connected, that is, when the `connect` event is triggered. It may not be the case where you put your `console.log(socket.id);`

**Comment by nischay13may** [comment]
I am not able to access it. console.log(socket.id); shows undefined

**Comment by yitomok** [comment]
@nischay13may What @darrachequesne said is that you should wait for the event `connect` before accessing the `id` field:
```
socket.on('connect', function() {
  console.log(socket.id);
});
```

**Comment by asifvora** [comment]
socket.on('connect',()=> {
  console.log(socket.id);
});
