### ISSUE TITLE
does the number of the connections at the same time is limit？

### ISSUE THREAD

**Issue by cosdy** [socketio/socket.io#2750]
i want to setup a message system which will have ten million or more connections at the same time，does socket.io can support so many connections at the same time? does the socket.io cluster can support the needs?

**Comment by Haocen** [comment]
I believe it is.
But this is a limitation more on your system side, your system/cluster need to be able to handle this many TCP connection at the same time.
Meanwhile node.js and socket.io doesn't seem to impose any limitation intentionlly.

**Comment by danielmeng07** [comment]
I've been trying to get a solid count on the number of connections too. So far, the best I've been able to get out of a single process is 300. Anything higher than that and Socket.io starts dropping connections. 

Node 7.4.0
Socket 1.7.2

**Comment by darrachequesne** [comment]
For future readers: the max number of concurrent connections depends on a lot of factors, please do some performance testing against your own use case.
