### ISSUE TITLE
Websocket handshake error does not auto fallback to polling or other transport 

### ISSUE THREAD

**Issue by Haocen** [socketio/socket.io#2751]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
If websocket is supported by both browser and server but proxy or firewall disallow connection socket.io will stuck on handeshake failure forever, although polling is enabled on both side and would work without any problem.

### Steps to reproduce (if the current behaviour is a bug)
Disallow websocket `ws` and `wss` connection in firewall and test, client will stuck on trying to connect via websocket.
Or do following in server side code:
```
                const io = require('socket.io')(server, { transports: [
			//'websocket', 
			'flashsocket', 
			'htmlfile', 
			'xhr-polling', 
			'jsonp-polling', 
			'polling'
		] });
```

And Client side code:
```
	var socket = io(window.location.protocol + "//" + window.location.hostname.split(":")[0] + ":8443", { path: "/socket.io", transports: [
			'websocket',
			'flashsocket', 
			'htmlfile', 
			'xhr-polling', 
			'jsonp-polling', 
			'polling
		], 
		allowUpgrades: true
	});
```
Theoretically client should fail a few times and switch to any of the `'flashsocket'`, `'htmlfile'`, `'xhr-polling'`, `'jsonp-polling'`, `'polling'` and work just fine.

But instead client keep on trying to connect via websocket.
![image](https://cloud.githubusercontent.com/assets/10842569/21456094/58e76470-c8f3-11e6-98ab-73ee3d145f8a.png)

### Expected behaviour
After timeout or certain number of tries go back to polling or any other possible transport.

### Setup
- OS: Windows Server 2012 R2
- browser: Chrome Version 54.0.2840.71 m (64-bit)
- socket.io version: 1.5.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
Supply options to set limit on upgrade attempts or retries.

This behavior is very annoying since nobody can ensure the internet infrastructure in between can always support websocket while both server and client can do/allow websocket, e.g enterprise firewall and so on.

**Comment by jamiehutber** [comment]
👍

**Comment by darrachequesne** [comment]
How can we reproduce?

With `const io = require('socket.io')(server, { transports: [ 'polling' ] })`, the client does not try to upgrade, since the server responds `{"sid":"iXW8OMaVAH4-Hjt6AAAF","upgrades":[],"pingInterval":25000,"pingTimeout":60000}`.

And if I had the following code at the eHi, I'm unfortunately not able to reproduce.nd of the chat example:

```js
var http = require('http');
var httpProxy = require('http-proxy');

httpProxy.createProxyServer({
  target:'http://localhost:3000',
  ws: false
}).listen(3001, function () {
  console.log('Proxy listening at port 3001');
});
```

The upgrade request seem to be discarded (i.e. the expected behaviour):
![image](https://cloud.githubusercontent.com/assets/13031701/21455534/44cca72e-c921-11e6-8210-03fe2bcfe375.png)

**Comment by Haocen** [comment]
@darrachequesne one can manually set supported transports on the __client__ side:
```
        var socket = io();
	socket = io(window.location.protocol + "//" + window.location.hostname.split(":")[0] + ":8443", { path: "/socket.io", transports: [
			'flashsocket', 
			'htmlfile', 
			'xhr-polling', 
			'jsonp-polling', 
			'polling',
			'websocket'
		], 
		allowUpgrades: true
	});
```

**Comment by darrachequesne** [comment]
In your example, it seems you're calling `io()` twice, isn't it?

Related: http://stackoverflow.com/a/28594964/5138796

**Comment by Haocen** [comment]
Thanks for pointing that out, I changed my code to following:
![image](https://cloud.githubusercontent.com/assets/10842569/21456634/9e24f4e0-c8f7-11e6-91f4-82b1485aabc5.png)
but still no luck:
![image](https://cloud.githubusercontent.com/assets/10842569/21456665/d39e477a-c8f7-11e6-9da7-acaaa2cdd0a3.png)

**Comment by darrachequesne** [comment]
I'm able to reproduce the `Connection closed before...` with https://github.com/darrachequesne/socket.io-chat/tree/ws-upgrade-fail, are you sure there is no duplicate?

**Comment by Haocen** [comment]
@darrachequesne Thanks for pointing that out, I'm afraid that is not the reason.

I make an example with socket.io-chat as well:
https://github.com/Haocen/socket.io-chat/tree/ws-blocked

**Comment by darrachequesne** [comment]
Thanks for the test case! It seems to be related to the order of 'polling' and 'websocket'.

If you replace:
```js
var socket = io({
  transports: [ 'websocket', 'polling' ]
});
```
by:
```js
var socket = io({
  transports: [ 'polling', 'websocket' ]
});
```
It seems to work properly. Can you confirm?

**Comment by Haocen** [comment]
Yes after switching the order the client try upgrade once and fail then fallback to polling.
I think this behavior should be better documented.

**Comment by darrachequesne** [comment]
Well, PR is welcome! Can that issue be closed?

**Comment by Haocen** [comment]
@darrachequesne wait, I'm still not 100% sure the behavior I should expect on the client side.
Do you mean client side is always using the first method in `transports` array as the default fallback?

**Comment by darrachequesne** [comment]
Yes, that's the behaviour described [here](https://github.com/socketio/engine.io#goals):

> The main goal of Engine is ensuring the most reliable realtime communication. Unlike the previous Socket.IO core, it always establishes a long-polling connection first, then tries to upgrade to better transports that are "tested" on the side.

**Comment by Haocen** [comment]
I think it might want to do round-robin in a specific order? Or try a few times before switch to another transportation method? Well, that is another story then.
So the first method in transportations array is the default method, got it.

**Comment by jamiehutber** [comment]
Nice one guys, I will try and look at fixing my problem in a similar way.
