### ISSUE TITLE
socket.io website: dead link on slack button

### ISSUE THREAD

**Issue by positlabs** [socketio/socket.io#2753]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Clicking the slack button on the website leads to http://slack.socket.io/ which gives `502 Bad Gateway`

![screen shot 2016-11-19 at 1 58 47 pm](https://cloud.githubusercontent.com/assets/1918844/20458694/6e9f19dc-ae60-11e6-824a-8038de96e3f9.png)

### Steps to reproduce (if the current behaviour is a bug)

Click the button, or go to http://slack.socket.io/

### Expected behaviour

Link should point to https://socketio.slack.com

### Setup
- OS: OSX
- browser: Chrome
- socket.io version: N/A

**Comment by DukeCannon** [comment]
related to #2773. "https://socket.io/slack" also is viable

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
