### ISSUE TITLE
Best practice for notifications? Send to a lot of messages vs join a lot of rooms?

### ISSUE THREAD

**Issue by dj-hedgehog** [socketio/socket.io#2758]
I'm using socket.io as for my WebApp. It is a marketplace. Users may favourite/buy/sell articles and will therefore be notified from the server when something changes.

Now I've got to make the choices whether a user joins a room for every article he is interested upon login or whether I emit a message for every user individually when something changes.

What is your take on this? Is there a best practice?

**Comment by darrachequesne** [comment]
Hi! That question rather belongs to StackOverflow..

That being said, I don't think there is any best pratice, but the ability to use `io.to(<article-id>).emit()` looks really convenient to me.

**Comment by dj-hedgehog** [comment]
I suspect to get the infamour "close by off-topic" on SO b/c this question may appear to be opinion-based. Let's try it nonetheless: http://stackoverflow.com/questions/40729073/emit-a-lot-of-messages-vs-join-a-lot-of-rooms

Regarding your answer:
While its convenient it also means that upon logging a user I may have to join 100 rooms which doesn't sound so convenient anymore.

**Comment by darrachequesne** [comment]
@dj-hedgehog you mean, performance-wise?

**Comment by dj-hedgehog** [comment]
@darrachequesne Yes, I can imagine that all the subscription may hog quite some memory when the user base becomes large enough. I'm still pretty new to Socket.io but I guess others asked the same question before.

**Comment by darrachequesne** [comment]
Well, it will indeed depend on the number of concurrent clients / subscribed articles / events per second. Some performance testing will be needed, but you'll always be able to scale horizontally (please see https://github.com/socketio/socket.io-redis).

**Comment by dj-hedgehog** [comment]
I just checked it quickly myself with this:

``` 
for (var attr in io.sockets.sockets){
        console.time("sockets");
        for (var i = 0; i < 100; i++) { 
          io.sockets.sockets[attr].join("lala"+i);
        }
        console.log(`room ${attr} length ${Object.keys(io.sockets.sockets[attr].rooms).length}`)
        console.timeEnd("sockets");
 }
```

Joining 100 rooms takes around 11ms on my Ivy Bridge MBPro which is perfectly fine for my use case :)

**Comment by darrachequesne** [comment]
Closed, please reopen if needed.
