### ISSUE TITLE
Send messages securely to specific user logged in on multiple devices

### ISSUE THREAD

**Issue by dj-hedgehog** [socketio/socket.io#2759]
I'm using Socket.io as a notification system for my webapp. Every user receives individual notifications. Right now I use a room based on just the "user-id" so I can join it from multiple devices.

Someone else having physical access to a device at one time could grab this "user id" and join this users room sometime in the future.

While this may seem far fetched is there a good way to prevent these kind of scenarios.

**Comment by darrachequesne** [comment]
Again, that question rather belongs to StackOverflow.

Since joining a room is a server-side action, only client with proper authentication should then be able to join the room <user-id>, right? Or did I misunderstand the question?

**Comment by dj-hedgehog** [comment]
No, you understood it just right but I was a little bit too fast here. You are right, since joining rooms is done on the server side this is not an issue.
Let me ask another question though.

When someone opens my webapp the a WebSocket connection is established with the server (for global messages etc.) However I need to join the rooms after the user is logged in. **How can I access a specific socket without using it via the `connection` event?**

```
io.on('connection', function(socket){
  socket.join('some room');
});
```

**Comment by darrachequesne** [comment]
`io.of('/').sockets[<socketid>]`

_(disclaimer: not a public API)_

**Comment by dj-hedgehog** [comment]
I just deleted my question because I found the solution myself. I asked for a way to access individual Sockets outside of an event.

Thank you @darrachequesne. This works as expected.
