### ISSUE TITLE
how to leave a group with multiple socket ids at a time socket.leave()?

### ISSUE THREAD

**Issue by vasuvanka** [socketio/socket.io#2761]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:
i have a situation that a user can have multiple connections .if user exits from a  group then i have to remove all user socket ids from a room .is there any solution for this ??
* [x] report a *bug*

### Setup
- OS: ubuntu
- browser: chrome
- socket.io version : 1.4.5

**Comment by carpii** [comment]
What is the reason they have multiple connections? 

Presumably you can identify the userid for each socket, so when a socket disconnects, just disconnect all other sockets with that userid.

**Comment by vasuvanka** [comment]
thanks carpii.

but i found solution 

var connectedSockObj = io.sockets.connected[UserSocketId];
if (connectedSockObj)
	connectedSockObj.leave(groupName);
