### ISSUE TITLE
Slack image doesn't load and leads to "502 bad gateway" in README.md on GitHub

### ISSUE THREAD

**Issue by Property404** [socketio/socket.io#2773]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Slack image doesn't load and leads to "502 bad gateway" in README.md on GitHub

### Steps to reproduce (if the current behaviour is a bug)
Chrome on Windows on https://github.com/socketio/socket.io

### Expected behaviour
Slack image does load but does not lead to "502 bad gateway" etc etc

### Setup
- OS: Windows 7
- browser: Chrome 54
- socket.io version: master

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
