### ISSUE TITLE
Memory usage climbs with Socket.io included - memory leak

### ISSUE THREAD

**Issue by moeiscool** [socketio/socket.io#2775]
### You want to:
* [x] report a *bug*

Basic usage of socket.io causes incremental memory usage (about +4mb every second). Even when nothing is transmitting. I have found that if I comment out socket.io my app no longer has this memory issue. Meaning the only thing that causes it is socket.io.

### Current behaviour

Memory will keep climbing if socket.io is in use `(about +4mb every second)`. I am using it to transmit ArrayBuffer data of an image every few seconds (CCTV monitoring). 

If a user connects to watch a stream it will climb faster. Sometimes `10mb per second`. Which makes sense as I am transmitting images over socket.

### Steps to reproduce (if the current behaviour is a bug)

just create a fresh node app with socket.io and watch the ram usage just go up for no reason.

### Expected behaviour

Meant to purge sent data after its done sending (but it doesn't i am guessing)

### Setup
- OS: Ubuntu 16.04 Server, Installed an old Macbook (white) Core 2 Duo.. with i think either 1GB ram or 2GB ram... (the thing is gutless)
- browser: Chrome - `Polling disabled in socket.io.js` (but the issue is not directly the fault of the user, they just connect and get data)
- socket.io version: 1.7.1
- node : v4.2.6
- npm : 3.5.2

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

I have tried `global.gc()` but it returns as an undefined function even with `--expose-gc`. I have read in countless places shouldn't do that anyway so I am hoping there is a way to purge the `old/temp/cached` data from memory. It would be nice to specifically target the data socket.io is leaving in memory.

Perhaps there is an object that i just `delete()`... man that would be nice eh?

**Comment by toothlessG22** [comment]
Hello,

I have been running an express server with socket.io for 3 days straight, and I have had no memory issues. Perhaps something you are doing with stream is causing the memory leak?

Cheers,
toothless

**Comment by darrachequesne** [comment]
Could you please share some code? Is the memory climbing forever (well, until process crashes)?

**Comment by moeiscool** [comment]
im afraid any snippets i provide are going to require more "decoding" :sweat_smile: 

here is one part where i open an ffmpeg and throw jpegs from a camera url into it on interval. while i throw them into ffmpeg i am pushing the frame to any users who happen to connected to that monitor.

```
                            e.args = '-f image2pipe -framerate 1 -vcodec mjpeg -i - -f webm -framerate 1 -q:v 1 '+e.dir+e.filename+'.webm';
                            s.users[e.ke].mon[e.id].spawn = spawn('ffmpeg',e.args.split(' '));
                            e.captureOne=function(f){
                                request({url:e.url,method:'GET',encoding: null},function(er,resp,body){
                                    if(er){++e.error_count;return}
//                                    if(e.error_count>4){s.camera({mode:'stop',id:e.id,ke:e.ke})}
                                    clearTimeout(e.timeOut),e.timeOut=setTimeout(function(){e.error_count=0;},3000)
                                }).on('complete',function(data){
                                    if(s.users[e.ke].mon[e.id].watch&&Object.keys(s.users[e.ke].mon[e.id].watch).length>0){
                                        s.tx({f:'monitor_frame',ke:e.ke,id:e.id,time:s.moment(),frame:data.body,frame_format:'ab'},'MON_'+e.id);
                                    }
                                    setTimeout(function(){e.captureOne()},s.interval);

                                }).on('error',function(er){}).pipe(s.users[e.ke].mon[e.id].spawn.stdin,{end:false})
                            }
                            e.captureOne()
```

**Comment by moeiscool** [comment]
turns out the problem was here.

what is happening ; making a snapshot of a camera url and sending as an ArrayBuffer of socket with the `s.tx()` function mentioned before.

```
            e.url=e.mon.protocol+'://'+e.mon.host+':'+e.mon.port+e.mon.path;
            request({url:e.url,method:'GET',encoding:null},function(err){if(err){return};}).on('complete',function(resp){
                if(resp.body){
                    s.tx({f:'monitor_snapshot',snapshot:resp.body,snapshot_format:'ab',id:e.id},'GRP_'+e.ke)
                }
                }).on('error',function(){s.tx({f:'monitor_snapshot',snapshot:'No Image',snapshot_format:'plc',id:e.id},'GRP_'+e.ke)})
```

I was using this function in succession too quickly. I was probably using it 8 times within the same second.. and after i commented this function out it stopped doing the memory climb.

**Comment by darrachequesne** [comment]
So.. can you close the issue please?
