### ISSUE TITLE
DevTools failed to parse SourceMap socket.io.js.map

### ISSUE THREAD

**Issue by uiteoi** [socketio/socket.io#2777]
### You want to:

* [x] report a *bug*

### Current behaviour

Console displays:
```DevTools failed to parse SourceMap <domain name>/socket.io/socket.io.js.map```

### Steps to reproduce (if the current behaviour is a bug)

in index.html:
```html
<script src="/socket.io/socket.io.js" type="text/javascript"></script>
```

### Expected behaviour

No error message in console and a valid source map returned for origin source files that should also be served.

### Setup
- OS: Windows 7
- browser: Chrome
- socket.io version: 1.7.1

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

This is due to ```"/socket.io/socket.io.js"``` having a source map declaration at its end:
```javascript
//# sourceMappingURL=socket.io.js.map
```

When loading ```"/socket.io/socket.io.js.map"```, the server serves ```"/socket.io/socket.io.js"``` which is not a valid source map, yielding the parse error reported by DevTools.

I have also tried to replace:
```html
<script src="/socket.io/socket.io.js" type="text/javascript"></script>
```
with:

```ht;ml
<script src="/socket.io/socket.io-min.js" type="text/javascript"></script>
```

Which displays in the console:
```GET <domain name>/socket.io/socket.io-min.js 400 (Bad Request)```

Where it should return ```404 (Not Found)``` or much better return the minified version of the socket.io client with a valid source map.

**Comment by darrachequesne** [comment]
Hi! Sourcemap was added in `1.7.0` (https://github.com/socketio/socket.io/commit/0ef55b26d4684abfb54e18567905c22d4bfc83ac).

Could you please make sure you use the latest version?

**Comment by uiteoi** [comment]
After upgrading to v1,7.1 I had not restarted the server, which was still serving version 1.6.0 I had before. So the error in the console is gone after restarting, and the served file is now minified, which was unexpected since I am requesting ```"/socket.io/socket.io.js"```.

Unfortunately, the served minified asset does not contain a ```sourceMappingURL``` specification on its last line so the source map which is now correctly available at ```"/socket.io/socket.io.js.map"``` is not accessible by DevTools and other source mapping tools in the browser.

Attempting to access ```"socket.io/socket.io-min.js"``` still returns ```400 (Bad Request)``` with a content body:
```json
{"code":0,"message":"Transport unknown"}
```

It should most likely return a ```404 (Not Found)``` instead, although this is a separate issue.

**Comment by darrachequesne** [comment]
Hmm, the header `X-SourceMap` [here](https://github.com/socketio/socket.io/blob/master/lib/index.js#L307) should make it work though. Isn't that the case?

**Comment by uiteoi** [comment]
Unfortunately ```X-SourceMap``` does not appear to be supported, at least not in Chrome on Windows.

Also read from [Source Map Revision 3 Proposal](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit):
- The HTTP header should supply the source map URL reference as:
  SourceMap: <url>

  Note: previous revisions of this document recommended a header name of “X-SourceMap”. This is now deprecated; “SourceMap” is now expected.

  The generated code may include a line at the end of the source, with the following form:
  ```javascript
  //# sourceMappingURL=<url>
  ```

My recommandation would be to implement at least the ```sourceMappingURL``` comment line as it is supported everywhere. If you want to add an HTTP header, use at least ``` SourceMap``` and optionally ``` X-SourceMap``` in the short term as the later is deprecated.

Also note, when using an HTTP header, that socket.io does not currently send ```X-SourceMap``` on an HTTP 304 response. The header is only present on an HTTP 200 response. This may be a problem when accessing the page more than once.
