### ISSUE TITLE
Client get disconnected .........

### ISSUE THREAD

**Issue by pratikwebkul** [socketio/socket.io#2778]
HI,
 i working on chat project and using socket.io version(1.7)......
when client is in ideal mode for long time ................... they are disconnected ................ they are not able to get any message .but this issue is not present in socket.io 0.9 version ............. any one please help us .............  
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Setup
- OS:
- browser:
- socket.io version:

**Comment by darrachequesne** [comment]
Hi! Do you have any error in console? Are those issues happening after a specific amount of time, or on a given device/browser?

**Comment by pratikwebkul** [comment]
Hi

i think i got this error
Error: read ECONNRESET
    at exports._errnoException (util.js:1007:11)
    at TCP.onread (net.js:563:26)


Are those issues happening after a specific amount of time

No i don't think so , but when client is not chatting long time ................ socket is dropped and can't able to send chat 

I am using ubuntu-14.04/chrome and firefox

Thanks

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
