### ISSUE TITLE
Connect request without transport fails server

### ISSUE THREAD

**Issue by vostrik** [socketio/socket.io#2779]
Query
`/socket.io/?EIO=3`
fails server

> TypeError: Cannot read property 'prototype' of undefined
> at Server.onWebSocket node_modules\engine.io\lib\server.js:343:12

**Comment by darrachequesne** [comment]
Hi, thanks for the report! Shouldn't it be caught in the [`verify`](https://github.com/socketio/engine.io/blob/master/lib/server.js#L140) method?

Which version are you using, and which options are you passing to the socket.io server?

**Comment by vostrik** [comment]
Our version is 1.5.0, we use default options.

In verify method you use Server.errors.UNKNOWN_TRANSPORT (which eq 0), then in handleUpgrade 
`if (err)` 
which 0 in this case, finally in onWebSocket method 
`if (!transports[req._query.transport].prototype.handlesUpgrades)`
but req._query.transport can be wrong or empty.

**Comment by darrachequesne** [comment]
Hmm.. it should rather be `if (!success)`, right? Like [here](https://github.com/socketio/engine.io/blob/master/lib/server.js#L214).

**Comment by darrachequesne** [comment]
And... this was changed in https://github.com/socketio/engine.io/pull/385.

**Comment by vostrik** [comment]
I use this url (via chrome plugin Smart WebSocket Client)

> wss://127.0.0.1:3000/socket.io/?EIO=3

There is no handleRequest method in my error chain:
![socket](https://cloud.githubusercontent.com/assets/8706396/20927758/053b420a-bbd4-11e6-9686-0438a6b015bc.png)

**Comment by vostrik** [comment]
As I understand it, you need change Server.errors and Server.errorMessages enums 0 to another value.
