### ISSUE TITLE
Web page, slack, documentation - down for long time... [old: Is this project alive?]

### ISSUE THREAD

**Issue by scippio** [socketio/socket.io#2781]
Web page, slack, documentation .. everything is fucked up for long time...

**Comment by Property404** [comment]
It's obviously "alive"  

They just had a new bugfix release

**Comment by Orbyt** [comment]
The title of this issue should be changed, but yes, currently the docs and more seem to be down.

Example: http://socket.io/docs/client-api/

**Comment by Property404** [comment]
As of now, that page works for me

**Comment by CatTail** [comment]
The doc is down, @scippio , maybe changing the title of this issues will be better?

**Comment by csmcanarney** [comment]
> As of now, that page works for me

Unfortunately I see the same issue: The server consistently stops sending after 4094 bytes on `/docs/client-api/`.

**Comment by Orbyt** [comment]
@Property404 Really? The page is blank for me but no errors are in the console.

**Comment by mathieug** [comment]
http://socket.io/docs/client-api is down for me

**Comment by darrachequesne** [comment]
Hi all,

We're going to migrate the site content to github (as soon as I'll find time to do so).

Temporarily, you can access:
- the chat example: https://socketio-chat-dyfwapyfni.now.sh/
- the slack channel: https://rauchg-slackin-wjgcyuptip.now.sh/

**Comment by mathieug** [comment]
@darrachequesne thanks, what about [http://socket.io/docs/client-api/](http://socket.io/docs/client-api/)? Even google has a broken page in cache.

**Comment by tagyoureit** [comment]
The temp slack link isn't working either.  the slack channel: https://rauchg-slackin-wjgcyuptip.now.sh/

Shows 'loading...' but never loads.

**Comment by codegeek1001** [comment]
Few issues I see with website and documentation:

- the link to /docs/client-api (client api link on docs page) does not work. blank html returned

- the menu link for slack channel is incorrectly set as slack.socket.io which doesn't work. However, the correct slack link is socket.io/slack which is correctly shown on the homepage. 

- The whiteboard demo has been pending for a while :) Would love to see it.

**Comment by brokencube** [comment]
And of course, the elephant in the room, that the website is currently advertising v1.4.5 as the latest version, when v1.7.2 is the latest release in the repo...

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
