### ISSUE TITLE
Socket receives custom event after 'disconnect'.

### ISSUE THREAD

**Issue by hifall** [socketio/socket.io#2786]
With the latest 1.7.2 Socket.IO, I have seen a socket receive a custom event even after 'disconnect'. I had assumed that after a socket receives 'disconnect', and before it receives the next 'connect', it can not receive any other event.

Is this behavior correct?

We have relied on this assumption for quite a while -- we set things up upon 'connect' for a socket, and clear things up upon 'disconnect' for that socket. And if a custom event comes in after things are cleared up, it crashes our server.

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Socket receives custom event after 'disconnect'.

### Steps to reproduce (if the current behaviour is a bug)
None so far.

### Expected behaviour
After a socket receives 'disconnect', and before it receives the next 'connect', it can not receive any other event.

### Setup
- OS: Mac OS
- browser: Chrome
- socket.io version: 1.7.2

**Comment by darrachequesne** [comment]
That seems weird. Are you able to reproduce?

Out of curiosity, is there binary data in your message?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
