### ISSUE TITLE
socket io client does not support java web socket server written using spring boot

### ISSUE THREAD

**Issue by nakulshah** [socketio/socket.io#2787]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug* -- socket.io client is not working with java spring boot web socket server
* [ ] request a *feature*

### Current behaviour
I have created a web socket server using spring boot (similar to http://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html) without stomp messaging. My customer is insisting on writing his client using socket.io. 
I tried this on my test bed, socket.io is able to connect, but .send() and .emit() are not coming through to my service

### Steps to reproduce (if the current behaviour is a bug)
Create a web socket server using spring boot and a client using socket io

### Expected behaviour
Socket IO client should be able to work seamlessly with Java web socket service created using spring boot 
[FYI -- this is working A-OK when I use SockJS and native javascript websockets]

### Setup
- OS: Linux & Mac OS X
- browser: chrome
- socket.io version: 1.4.5

**Comment by darrachequesne** [comment]
Hi. I'm afraid that, since socket.io and sockJS do not share the same [protocol](https://github.com/socketio/socket.io-protocol), that won't be possible.
