### ISSUE TITLE
Client API docs is blank on website

### ISSUE THREAD

**Issue by ztrange** [socketio/socket.io#2791]
I've been trying all day to see the client API documentation on socket.io but every time I enter, I only see a blank page:

http://socket.io/docs/client-api/

I tried with chrome and edge and also tried using a web http proxy from netherlands to see if it was a local issue. In all cases I only got a blank page.

**Comment by bigslycat** [comment]
![2016-12-16 14-59-31](https://cloud.githubusercontent.com/assets/1121997/21262074/5efb811e-c3a0-11e6-9405-5814bb17fb52.png)

**Comment by lednhatkhanh** [comment]
Me too, also, the slack link is broken too.

Just came here trying to use socket.io with redux saga...

**Comment by digital-flowers** [comment]
how can we solve this ?! 
anw for now anybody needs the doc he can access it using this way back machine link:
http://web.archive.org/web/20161022042404/http://socket.io/docs/client-api/

**Comment by paralin** [comment]
Totally broken right now, doesn't give a lot of confidence in the codebase if the entire documentation can be down for over 12 days without even an ack from the maintainers!

**Comment by darrachequesne** [comment]
@paralin sadly I have no control over the website, @rauchg has.

The client API documentation can also be found here: https://github.com/socketio/socket.io-client/blob/master/docs/API.md

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
