### ISSUE TITLE
Repo history is corrupt

### ISSUE THREAD

**Issue by taoeffect** [socketio/socket.io#2792]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

```
-> % git clone git@github.com:socketio/socket.io.git
Cloning into 'socket.io'...
remote: Counting objects: 9993, done.
error: object 2fbd0cd08a20661b46345ceac2e421d1efe3fc50: zeroPaddedFilemode: contains zero-padded file modes
fatal: Error in object
fatal: index-pack failed
```

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

git [doesn't check the integrity of its commit log](https://groups.google.com/d/msg/binary-transparency/f-BI4o8HZW0/MDmnWideAgAJ) by default.

This is potentnially dangerous. It means that someone (e.g. GitHub) could mess with the data that's present at a commit and your client would not notice it.

Per the advice in that thread, my git is configured to always verify the integrity of the data, and it seems something isn't quite right in socket.io's commit history.

**Comment by darrachequesne** [comment]
Hi, thanks for the heads-up! Do you know how we can fix that?

**Comment by taoeffect** [comment]
@darrachequesne I'm not sure as I've never had to fix this myself. Just thinking out loud here: if someone has a non-corrupt version of the repo history, you could use that to overwrite the one on github.

You could also ask some of the people in that thread that I link to above what they think, they might be able to help. Or on the git dev list(s).
