### ISSUE TITLE
removeAllListeners is corrupted

### ISSUE THREAD

**Issue by niemoralny** [socketio/socket.io#2794]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
There is no effect when you use removeAllListeners method.

### Steps to reproduce (if the current behaviour is a bug)
Server:
```
socket.on('someEvent', () => {
  console.log('it works!');
  socket.removeAllListeners('someEvent');
});
```

Client:
```
socket.emit('someEvent');
socket.emit('someEvent');
```

Result:
> it works!
> it works!

### Expected behaviour
Second event shouldn't have fired.

### Setup
- socket.io version: 1.7.1, 1.7.2

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
It seems that this error only occured with version 1.7.1 and 1.7.2. Other versions works fine.

**Comment by darrachequesne** [comment]
Could you provide a failing test case please? I am not able to reproduce: https://github.com/darrachequesne/socket.io-fiddle/tree/issue/removeAllListeners

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
