### ISSUE TITLE
on connection event not firing when connecting from nodemcu lua client.

### ISSUE THREAD

**Issue by ibramn** [socketio/socket.io#2795]
I want to connect nodemcu lua socket client to node.js socket server.
**nodemcu lua code:**
`sk = net.createConnection(net.TCP, 0)`
`sk:on("receive", function ( sck,c )`
    `print (c)`
`end)`

`sk:on("connection", function ( sck,c )`
    `print("Connected")`
   ` sk:send("Helloooo...")`
`end)`
`sk:connect(12346,"192.168.1.100")`

**Node.js server code:**
`var express = require('express');`
`var app = express();`
`var server = require('http').Server(app);`
`var io = require('socket.io')(server);`

`io.on('connection', function(socket){`
	`console.log('someone is connected');`
`});`
`server.listen(12346);`

The on connection event in lua client is fired and prints "Connected"  but the on connection in node.js socket server isn't fired.
I tried the lua client with python socket server and worked well !!.
And also tried node.js socket server with javascript socket client and worked well !!.

**Comment by darrachequesne** [comment]
Could you please open an issue in the nodemcu lua client project? Thanks!

**Comment by sigmasoldi3r** [comment]
Is there the issue in NodeMCU Lua client?
