### ISSUE TITLE
Client-API documentation page does not load

### ISSUE THREAD

**Issue by cyphunk** [socketio/socket.io#2798]
``view-source:http://socket.io/docs/client-api/`` shows that the page doesn't get past loading the header before something on the server stops responding. Tested in chrome and firefox on a linux system.

currently this makes it impossibe to access documentation.

**Comment by jfix** [comment]
👍

**Comment by jhuckaby** [comment]
While we're waiting for this to be fixed, here's a working link from the Internet Archive, from Oct 22, 2016:

http://web.archive.org/web/20161022042404/http://socket.io/docs/client-api/

\- Joe

**Comment by ericls** [comment]
There's also a documentation in the github repo.

https://github.com/socketio/socket.io-client/blob/master/docs/API.md

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
