### ISSUE TITLE
http://slack.socket.io returns 502 Bad Gateway

### ISSUE THREAD

**Issue by cyphunk** [socketio/socket.io#2799]
testing on firefox and chrome on a linux system. This slack URL is linked to on the front page of the socket.io site and suggested for obtaining help.

**Comment by jxc876** [comment]
Experiencing the same issue on Mac (Yosemite) w/ Chrome (v55) & Firefox.

**Comment by codegeek1001** [comment]
The link is wrong and few folks already have raised this on another issue. The correct link is at:

http://socket.io/slack/

which ultimately takes you to the actual slack link which is:

https://socketio.slack.com/

**Comment by codegeek1001** [comment]
Apparently, there is a PR for this already but not done yet

https://github.com/socketio/socket.io-website/pull/34

**Comment by jstrother** [comment]
It also looks like new signups aren't permitted.  I'm having issues with the client side and was wanting to get on this slack to ask for help.  I tried to sign-up, but nothing seems to be working.  Any ideas?  Thanks!

**Comment by ThePhantomGamer** [comment]
@darrachequesne the invite link still says `Contact the workspace administrator for an invitation`
