### ISSUE TITLE
socket.io-client module not found

### ISSUE THREAD

**Issue by jstrother** [socketio/socket.io#2801]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
I built a simple task list with this and was able to get it to work a few months ago.  I am going back to build another more robust program, but am getting this error when I try to run webpack 1.13.1:
ERROR in ./socket-listeners/task-listener.js
Module not found: Error: Cannot resolve module 'socket.io-client' in /home/ubuntu/workspace/socket-listeners
 @ ./socket-listeners/task-listener.js 33:9-36

### Steps to reproduce (if the current behaviour is a bug)
I have used both "import io from 'socket.io-client';" and "const io = require('socket.io-client');" and both reproduce the same error.

### Expected behaviour
I was expecting it to find the module on its own. I am able to find it manually in my node_modules folder.

### Setup
- OS: not sure if this counts as I use Cloud 9.  I tried to work it on my local machine using windows 10, but experienced the same result.
- browser: chrome
- socket.io version: 1.4.8

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
I'm hoping this can be fixed relatively quickly as this is going to be a final project so I can graduate.  If anybody has any work-around, please let me know.  Thanks!

**Comment by darrachequesne** [comment]
How did you install the package? Could you share your webpack config?

**Comment by killerspaz** [comment]
The package.json nor bower.json are configured properly, you will have to reference the dist output manually for now.

This broke on us from 1.5 -> 1.7 (although it was never set up correctly to begin with)

**Comment by darrachequesne** [comment]
> The package.json nor bower.json are configured properly

@killerspaz would you know what can be improved / fixed?

**Comment by jstrother** [comment]
Thanks, @killerspaz. That's what did the trick, just had to dig a little deeper into the socket.io module:
`import io from 'socket.io/node_modules/socket.io-client';`

**Comment by killerspaz** [comment]
@darrachequesne sorry, my feedback was actually meant for `socket.io-client`, not this project. Must have gotten switched up somehow. I can create an issue and PR.

@jstrother, you can use just `socket.io-client` to reduce packages if you wanted. It's not really optimal or suggested to dig into a module's dependencies.

**Comment by JonoH** [comment]
As with @killerspaz I only got it to work by referencing `socket.io-client/dist/socket.io`

**Comment by jstrother** [comment]
Thanks, @killerspaz, that worked.  (Sorry for being late responding)

**Comment by vvkrajput** [comment]
error: Error: Unable to resolve module `use-socket.io-client` from `App.js`: use-socket.io-client could not be found within the project.

**Comment by ptc-bink** [comment]
I followed this, but this didn't fix issue :(

**Comment by mukunddubey10000** [comment]
same issue here. 

`Module not found: Can't resolve 'socket.io/node_modules/socket.io-client'`
`  1 | // import { io } from "socket.io-client";`
`  2 | // const { io } = require("socket.io-client")`
`> 3 | import io from 'socket.io/node_modules/socket.io-client';`
