### ISSUE TITLE
socket.rooms lags

### ISSUE THREAD

**Issue by Nerfair** [socketio/socket.io#2804]
If i want to join the room like

    socket.join(room);

and then immediately retrieve all rooms with

    socket.rooms

i won't see just joined room in a room list, i need to wait ~100ms before retrieving.

**Comment by darrachequesne** [comment]
You can use the callback argument ([ref](https://github.com/socketio/socket.io/blob/master/docs/API.md#socketjoinroom-callback)):
```js
socket.join('my-room', function () {
  console.log(socket.rooms);
});
```

**Comment by darrachequesne** [comment]
Closed, please reopen if needed.
