### ISSUE TITLE
When client is reopened, server does not receive buffered sync data from emitBuffered

### ISSUE THREAD

**Issue by gdsimz** [socketio/socket.io#2805]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
When using the client locally offline to add and update data using socket.emit, the app stores buffered requests offline.  If the app/browser isn't closed the emitBuffered requests are processed when device is back online.  If the app/browser is closed and reopened the stored buffer requested are not processed when the device comes back online. The emitBuffer triggers when socket.connect occurs releasing the data, but the server doesn't process any requests submitted.

### Steps to reproduce (if the current behaviour is a bug)
1.  create a page or application with socket.emit requests
2.  create code to store the buffered objects  (from Socket.sendBuffer when offline)
3.  turn network offline
4.  save some buffer requests by processing actions within the page/application
5.  close the app/browser
6.  reopen app/browser
7.  put items back into sendBuffer
    -  socket.sendBuffer.push(item);
8.  call emitBuffered() to send request objects to server
    -  if(socket && socket.connected){socket.emitBuffered();}
no success data response comes back or acknowledged

### Expected behaviour
in the event a browser / application crashes or is closed while device is offline, stored buffered data should be processed by the newer connection that is reopened.

### Setup
- OS: Android/iOS/Windows10
- browser: Chrome/Safari
- socket.io version: 1.4.5

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

js code currently used that works while app/browser isn't closed while offline:

socket.on('disconnect', function() {
                console.log('disconnected');
                setTimeout(function() {
                    if(socket && socket.sendBuffer.length>0){
                        localStorage.sendBuffer = JSON.stringify(socket.sendBuffer);
                    }
                    setInterval( function(){socket.connect();}, 1000);
                }, 1000);
            });

socket.on('connect', function(){
                sendBuffData();
            });
function sendBuffData(){
        //we have to wait for socket.io.reconnect to actually be ready
        setTimeout(function(){
            if(localStorage.sendBuffer){
                var changesBuffer = JSON.parse(localStorage.sendBuffer);
                changesBuffer.forEach(function(item){
                    socket.sendBuffer.push(item);
                    console.log('sending sendBuffer Data:');
                    console.log(item);
                    socket.emitBuffered();
                });
                if(socket && socket.connected){
                    localStorage.removeItem('sendBuffer');
                }
            }
        },20000);
    }

**Comment by darrachequesne** [comment]
How about using the `onbeforeunload` event? Something like:

```js
  var socket = io();

  socket.on('connect', onConnect);

  function onConnect(){
    sendBuffData();
  }

  function sendBuffData(){
    if (!localStorage.sendBuffer){ return; }
    var localSendBuffer = JSON.parse(localStorage.sendBuffer);
    Array.prototype.push.apply(socket.sendBuffer, localSendBuffer);
    socket.emitBuffered();
  }

  window.onbeforeunload = function(){
    if (socket && socket.sendBuffer.length > 0){
      // store in localStorage
      localStorage.sendBuffer = JSON.stringify(socket.sendBuffer);
    }
  };
```

**Comment by darrachequesne** [comment]
@gdsimz can that issue be closed?
