### ISSUE TITLE
socket.io/docs/client-api returns corrupted response

### ISSUE THREAD

**Issue by kootoopas** [socketio/socket.io#2807]
### Current behaviour
Rendering stops at `<script type='text/javascript' src='http://socket.io/wp-includes/js/jque`.

### Steps to reproduce
Go to http://socket.io/docs/client-api/.
(View source.)

### Expected behaviour
Page should render.

**Comment by kootoopas** [comment]
Client docs are [here](https://github.com/socketio/socket.io-client/blob/master/docs/API.md) too btw. 🙂

**Comment by robey** [comment]
this is still happening. it's been broken for so long that google is now caching the broken form. you can find an archived version here:

    https://web.archive.org/web/20161022042404/http://socket.io/docs/client-api/

is this project moribund?

**Comment by rhclayto** [comment]
Who runs the web page, & how can we contact this person?

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
