### ISSUE TITLE
rejoin users solution

### ISSUE THREAD

**Issue by tux-world** [socketio/socket.io#2808]
when user joined on rooms and disconnected from internet, how can i rejoin room users, is any simple solution such as save users joined states? how can i rejoin users after connected on server? socket id created by random id as dynamically, thanks in advance

**Comment by darrachequesne** [comment]
@tux-world I guess you'll need some way to authenticate the connected user, with a token for example.

Also, the rooms joined by a socket are deleted upon disconnection, so you'll have to somehow persist those rooms if you need that feature.

**Comment by tux-world** [comment]
@darrachequesne my solution is create unique user id for each user which registered on system, after request to join on room, i store himself user id on database and joining to room, after connecting again i search himself user id and rejoin automatically on room again

**Comment by darrachequesne** [comment]
@tux-world perfect :+1:

**Comment by tux-world** [comment]
@darrachequesne Thanks to share your knowledge
