### ISSUE TITLE
Socket.io Tutorial "Chat" is broken

### ISSUE THREAD

**Issue by max06** [socketio/socket.io#2809]
* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Following the current tutorial version on the socket.io documentation to build a small chat system doesn't work at all. 

### Steps to reproduce (if the current behaviour is a bug)
The steps beginning with setting up a basic express server are fine, also adding socket.io to that http server and the connection-event is fine.
When it comes to adding the html snippet for the socket.io-client and establishing the connection, it breaks. First of all, the file is not accessible on the express server, so I replaced it with the cdn version. Now it tries to connect, but fails again, probably because it's trying to reach the socket on a different path (socket.io-1.2.0.js:2 GET http://localhost:3000/socket.io/?EIO=3&transport=polling&t=1483818339831-18 404 (Not Found)), the tutorial states that the socket is available on `/`.

Debugging the sockets with 2 different chrome extensions also doesn't work, they are also not able to establish connections to both of these paths.

### Expected behaviour
Tutorials should contain a working example, to allow beginners (like me) to quickly gain experience.

### Setup
- OS: Windows 10
- browser: Chrome
- socket.io version: current/latest

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
Rewriting the tutorial from scratch should help here.

**Comment by darrachequesne** [comment]
Hello! We're talking about that tutorial [here](http://socket.io/get-started/chat/), right?

Apart from the following warning `express deprecated res.sendfile: Use res.sendFile instead index.js:6:7`, it works great for me (:tm:) , could you please provide some more details? Or a sample repo reproducing your issue?

**Comment by max06** [comment]
Hi @darrachequesne 
yes, that's the tutorial I meant. Sorry for being unclear about this.
I can upload my test project to github tomorrow, will report back then here.
Details I've observed so far: Express doesn't seem to expose the /socket.io/*-path after adding the `var io = require('socket.io')(http);`-part from the tutorial. At least I was not able to establish any websocket connection with different tools (chrome extensions) here. Also the `<script>`-tag with the client-js file results in a 404 in my browser. After I replaced the path with a public version available on `https://cdn.socket.io/socket.io-1.2.0.js`, it got loaded in my browser - but again, it wasn't able to connect. Also, the connecting-event didn't fire at any time (no log message in consoles).

**Comment by developius** [comment]
Same for me, except I'm using Express. The `createServer` function of Express has been deprecated, so the example doesn't work.

**Comment by max06** [comment]
@darrachequesne [here](https://github.com/max06/rc-admin) is my example repo... still doesn't work.

**Comment by darrachequesne** [comment]
@max06 I think the issue lies in the `app.listen(3000);`. According to the [reference](http://expressjs.com/fr/api.html#app.listen):

> The app.listen() method returns an http.Server object and (for HTTP) is a convenience method for the following...

```js
// Current (does not work)
var express = require('express');
var app = express();

var server = require('http').createServer(app);
var io = require('socket.io')(server);
// ...
app.listen(3000);

// solution1 (which is what is suggested in the tutorial, if I'm not mistaken)
var express = require('express');
var app = express();

var server = require('http').createServer(app);
var io = require('socket.io')(server);
// ...
server.listen(3000);

// solution2
var express = require('express');
var app = express();

var server = app.listen(3000);
var io = require('socket.io')(server);
```

Also, you should be able to replace `<script src="https://cdn.socket.io/socket.io-1.4.5.js"></script>` with `<script src="/socket.io/socket.io.js"></script>`.

**Comment by max06** [comment]
@darrachequesne 
That's now kind of embarrassing... 
Both of your solutions work. I've just overseen that server variable...
Thank you!

**Comment by darrachequesne** [comment]
You're welcome!
