### ISSUE TITLE
Very minor script issue in "Get Started"

### ISSUE THREAD

**Issue by johngoren** [socketio/socket.io#2821]
I only bring this up because the guide is aimed at all levels of knowledge, and some people may otherwise be stumped...

The Get Started guide recommends putting a <script> before the <body>. This works O.K. until the script begins relying on form HTML elements that haven't loaded yet. Might be worth putting in a $(document).ready to wait for all that stuff to load, or moving the <script> lower on the Index.html. I had to do the former to get my form to load in time before trying to stick a JS handler on it...(on a Mac running Chrome and Node 7.2.1)

**Comment by darrachequesne** [comment]
That should be fixed [here](https://github.com/socketio/chat-example) and [here](https://socket.io/get-started/chat/), thanks!
