### ISSUE TITLE
Truncated chat.socket.io server reply causes corruption

### ISSUE THREAD

**Issue by jay** [socketio/socket.io#2822]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

chat.socket.io is not working in the latest Firefox or Chrome. In Firefox browser console I see `ReferenceError: io is not defined  main.js:26:7`. On review the javascript appeared corrupted due to `http://chat.socket.io/socket.io/socket.io.js `. I reproduced in a web debugging proxy (Fiddler) which reported a protocol violation while retrieving that resource:

X-HTTPPROTOCOL-VIOLATION: [ProtocolViolation] Transfer-Encoding: Chunked response did not terminate with a proper zero-size chunk.

On further review of that data (attached as [4_Response.txt](https://github.com/socketio/socket.io/files/702590/4_Response.txt)) the server reply is truncated which is causing the corruption.

### Steps to reproduce (if the current behaviour is a bug)

You can easily reproduce this with curl or any browser.
curl -vsS -o NUL http://chat.socket.io/socket.io/socket.io.js
curl: (18) transfer closed with outstanding read data remaining

### Expected behaviour

A proper server reply and chat.socket.io functional

### Setup
- OS: Windows 7 x64 Enterprise
- browser: Firefox, Chrome, curl, etc
- socket.io version: unknown

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
