### ISSUE TITLE
wss node https server :ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by swapnil001** [socketio/socket.io#2827]
I have a HTTPS domain "https://example.com". When i make "wss://example.com:3002" connection the ":ERR_CONNECTION_REFUSED" error comes and on server side, node https server restarts.

app.js -

var app = module.exports = express();
var https = require('https');
var fs = require('fs');
var server = https.createServer({ 
    key: fs.readFileSync('/etc/letsencrypt/live/example.com/privkey.pem'),
    cert: fs.readFileSync('/etc/letsencrypt/live/example.com/fullchain.pem'),
    ca: fs.readFileSync('/etc/letsencrypt/live/example.com/chain.pem'),
    requestCert: true,
    rejectUnauthorized: false
 },app);
server.listen(3002); //listen on port 80

var io = require('socket.io').listen(server);
io.set('transports', ['websocket']);
var socketRedis = require('socket.io-redis');
io.adapter(socketRedis({ host: 'xyz', port: 6379 }));

Need urgent help tp connect socket io on https website. Thanks

**Comment by danieluyo** [comment]
```
//Client
var socket = io('https://somedomain.com',{secure: true, port: 100001});

```

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
