### ISSUE TITLE
The client api doc can not be displayed

### ISSUE THREAD

**Issue by Rainmen-xia** [socketio/socket.io#2830]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:
- browser:
- socket.io version:

**Comment by Rainmen-xia** [comment]
![image](https://cloud.githubusercontent.com/assets/5163662/22179756/e5f0c47c-e097-11e6-91af-e0fce1c33b91.png)

**Comment by xJkit** [comment]
Me too!

**Comment by Rainmen-xia** [comment]
why not fixed?

**Comment by bichotll** [comment]
Ping!

**Comment by jamesmanning** [comment]
@Rainmen-xia @bichotll as a temporary workaround, can you use an archived version?  Here's one:

http://web.archive.org/web/20161022042404/http://socket.io/docs/client-api/

**Comment by barryvdh** [comment]
Here is the Github version: https://github.com/socketio/socket.io-client/blob/master/docs/API.md
Also: https://github.com/socketio/socket.io/issues/2823 https://github.com/socketio/socket.io/issues/2807 https://github.com/socketio/socket.io/issues/2791 https://github.com/socketio/socket.io/issues/2781

**Comment by jamesmanning** [comment]
@barryvdh I thought about including that as a 'workaround' link, but I was worried that the master-branch version of the docs might be different than the last published version.   I didn't diff them to check, though, so that might have been a needless worry. 😄

**Comment by barryvdh** [comment]
@jamesmanning Well, it's better then no docs ;)

**Comment by Rainmen-xia** [comment]
thank you!

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.

**Comment by jamesmanning** [comment]
Thanks @darrachequesne ! 👍
