### ISSUE TITLE
broken (truncated) content in http://socket.io/docs/client-api/ prevents seeing any client api documentation

### ISSUE THREAD

**Issue by jamesmanning** [socketio/socket.io#2831]
Looks like the contents of the file got truncated somehow - it stops in the middle of what appears to have been an include for jquery.  I'm guessing it might have been an error/failure during the docs build process and just having it to the build again might be sufficient to fix it?  Just a guess.

http://webcache.googleusercontent.com/search?q=cache:l8azwhnhGvgJ:socket.io/docs/client-api/&num=1&hl=en&gl=us&strip=0&vwsrc=1

In the mean time, users can probably use an archived version like:

http://web.archive.org/web/20161022042404/http://socket.io/docs/client-api/

or the npmjs copy at https://www.npmjs.com/package/socket.io-client

**Comment by barryvdh** [comment]
Here is the Github version: https://github.com/socketio/socket.io-client/blob/master/docs/API.md
Also: #2823 #2830 #2807 #2791 #2781

**Comment by fijiwebdesign** [comment]
Bump! I think this is really important and should be an easy fix.

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
