### ISSUE TITLE
Troubles with the website: http://socket.io/

### ISSUE THREAD

**Issue by Ollemesh** [socketio/socket.io#2834]
Page:   http://socket.io/docs/client-api/   is wrong.
Cannot see anything.

Trying in Chrome, Firefox, under Linux, Mac, Ubuntu.

**Comment by AlexisAnzieu** [comment]
duplicate with #2798 
A cache version can be found there : 
http://web.archive.org/web/20161022042404/http://socket.io/docs/client-api/

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
