### ISSUE TITLE
Bug: Documentation page empty

### ISSUE THREAD

**Issue by tashburn** [socketio/socket.io#2836]
http://socket.io/docs/client-api/ is empty!

**Comment by barryvdh** [comment]
Here is the Github version: https://github.com/socketio/socket.io-client/blob/master/docs/API.md
Also duplicate from : #2823 #2830 #2807 #2791 #2781 #2831 #2834

**Comment by tashburn** [comment]
Thanks

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
