### ISSUE TITLE
Create Server on Mobile Application

### ISSUE THREAD

**Issue by judeallblack** [socketio/socket.io#2837]
I would like to create both client and server sockets on a mobile application.
And use a mobile device to execute the code on the server, so that client mobile device conects to serevr mobile device......and chat occurs through devices connected to the host mobile device.

Is this possible, how?

Please Help

*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:
- browser:
- socket.io version:

**Comment by judeallblack** [comment]
https://github.com/socketio/socket.io/blob/master/examples/chat/

Is the code on the server that id like to run on a mobile device acting as a server to the above code

**Comment by darrachequesne** [comment]
Since the server code is written for a Node.JS backend, I'm afraid that won't be possible (but I may be wrong).

**Comment by judeallblack** [comment]
@darrachequesne  there is a link to a forum about a JX-Core plugin at the below URL

https://www.sitepoint.com/how-to-run-node-js-with-express-on-mobile-devices/

do you think this will have the required node.js backend to run the code?

Because am not certain at this moment

**Comment by judeallblack** [comment]
more information on the JXcore repository is here.

Am abit new to ionic and node.js and Jxcore ........it seems that it has node.js and may work, what do you think @darrachequesne 

https://github.com/jxcore/jxm

**Comment by judeallblack** [comment]
Is there a way the server code can be rewritten so that i can run on a normal phone?

I.e client application ends socket data to server mobile device which has the functionality of the server code at....  
http://chat.socket.io

or https://github.com/socketio/socket.io/blob/master/examples/chat/


please help.

Am reading about JXcore and Express web framework, can they enable the server side code to run on a mobile phone?
