### ISSUE TITLE
Client API documentation did not work

### ISSUE THREAD

**Issue by mjamrozek** [socketio/socket.io#2839]
http://socket.io/docs/client-api/ page is blank

![zrzut ekranu z 2017-01-29 12-29-21](https://cloud.githubusercontent.com/assets/9804061/22403665/e747d5cc-e61e-11e6-93f0-94af4639c4ba.png)

**Comment by StianOvrevage** [comment]
Yes, client docs are blank. And google's cached version is ALSO blank.

Also: Slack link on homepage points to http://slack.socket.io/ which gives a 502 Bad Gateway.

Also: On the Slack invite page: http://socket.io/slack/ . There is a field to enter e-mail address, but no button to actually push to submit the e-mail. Pressing enter does nothing.

**Comment by Swinkid** [comment]
See #2823 , issue explains whats going on.. Also duplicate: #2807 #2791 #2781 #2830 #2831 #2834

You can find the one on github at: https://github.com/socketio/socket.io-client/blob/master/docs/API.md

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
