### ISSUE TITLE
chat.socket.io sample doesn't work (ERR_INCOMPLETE_CHUNKED_ENCODING)

### ISSUE THREAD

**Issue by ripper234** [socketio/socket.io#2840]
### You want to:

* [ ] report a *bug*

### Current behaviour

http://chat.socket.io/ example fails (locally it works, I mean the deployed instance)

GET http://chat.socket.io/socket.io/socket.io.js net::ERR_INCOMPLETE_CHUNKED_ENCODING

```
main.js:26 Uncaught ReferenceError: io is not defined
    at HTMLDocument.<anonymous> (http://chat.socket.io/main.js:26:16)
    at c (https://code.jquery.com/jquery-1.10.2.min.js:4:26036)
    at Object.fireWith [as resolveWith] (https://code.jquery.com/jquery-1.10.2.min.js:4:26840)
    at Function.ready (https://code.jquery.com/jquery-1.10.2.min.js:4:3305)
    at HTMLDocument.q (https://code.jquery.com/jquery-1.10.2.min.js:4:717)
    at <anonymous>:2:297
    at b (<anonymous>:2:142)
    at HTMLDocument.F (eval at exec_fn (:1:108), <anonymous>:45:26)
```

When I try to manually download http://chat.socket.io/socket.io/socket.io.js I get a **partial** file, that sometimes end in 

```
self.open(function(err){
        if (err) {
          debug('reconnect attempt error');
          self.reconnecting = false;
          self.reconnect();
 
```

other times ends with 

```
var toArray = _dereq_('to-array');
var on = _dereq_('./on');
var bind = _dereq_('component-bind');
var debug = _dereq_('debug')('socket.io-client:socket');
v
```

(It ends with `v`).

So the web server serving http://chat.socket.io/socket.io/socket.io.js doesn't serve the entire file, and thus the sample isn't working at all.

### Steps to reproduce (if the current behaviour is a bug)

Try to browse http://chat.socket.io/ from Israel (perhaps try using Fiddler/Charles to simulate a slow network)

Note: I've tried to access this sample and others many times on different dates, it always fails, never worked for me.

### Expected behaviour
Should be able to login to chat sample website.

### Setup
- OS: Windows 10 64 bit
- browser: Chrome stable
- socket.io version: Whatever you have installed

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
