### ISSUE TITLE
Add session documentation to the API on socket.io website

### ISSUE THREAD

**Issue by ripper234** [socketio/socket.io#2841]
The [API docs](http://socket.io/docs/server-api/) do not explain session management - they briefly touch session ids, but do not show how you can store data on the session object as shown in the [chat example](https://github.com/socketio/socket.io/blob/master/examples/chat/index.js).

**Comment by darrachequesne** [comment]
Added in the documentation here: https://socket.io/docs/v3/server-socket-instance/#Additional-attributes
