### ISSUE TITLE
Link the docs on session.io to & from documentation on github

### ISSUE THREAD

**Issue by ripper234** [socketio/socket.io#2842]
From socket.io, one can think that the documentation is only http://socket.io/docs/server-api/ and http://socket.io/docs/client-api/, when in fact the extensive https://github.com/socketio/socket.io/blob/master/docs/API.md exists as well.

If not merge the docs completely, then a link between these two separate doc locations should exist.

**Comment by jessecstewart** [comment]
http://socket.io/docs/client-api/ doesn't seem to be working right now, tested in Chrome and FF

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
