### ISSUE TITLE
Question - How I write the middleware to check data before process

### ISSUE THREAD

**Issue by samuraitruong** [socketio/socket.io#2845]
Hi all, 

My socket is being attack with huge of fake data. I would implement the middleware to check data length of incoming data before allow them upload, or at least drop their connection.  I hope that there is a easier way to do it. 

Could you please link me to the article that will help. Thanks

**Comment by LordMajestros** [comment]
Socket.io uses https://github.com/websockets/ws you could also specify https://github.com/uWebSockets/uWebSockets as the engine behind it. In each of those libraries you can specify a maxpayload option to limit the amount of data that can be received. The connection is dropped if a client exceeds this value

**Comment by LordMajestros** [comment]
You can pass the max payload option to the websocket server instance. See here https://github.com/websockets/ws/blob/master/lib/WebSocketServer.js#L47

**Comment by samuraitruong** [comment]
thanks, I also would allow some clients send big data. the idea is for trusted IP address, I would allow send unlimited data, but for untrusted I only allow send max 10k. I would have a look on those link to see if I can implement it.

**Comment by samuraitruong** [comment]
I have alook in socketio, It using engine.io and has maxHttpBufferSize  but it doesn't seem to work,  since i set it to 100kb, then client still able to send 1mb data .

Deeper in  socket.io option, I saw they actually mention they use ws as @LordMajestros  mentioned above, however, I don't know how to by maxPayload to ws engine inside. 

@LordMajestros  do you have any ideal?

**Comment by Swinkid** [comment]
Probably doesn't help, but with the version 2.0 of Socket.IO, it will use uWebSockets by default.

**Comment by edenprojectde** [comment]
also pretty interested as this is a security leak imo

**Comment by darrachequesne** [comment]
The `maxHttpBufferSize` option should work. Could you provide a failing test case?

> I would allow send unlimited data, but for untrusted I only allow send max 10k.

How about something like:
```js
socket.use(function(packet, next){
  if (Buffer.byteLength(packet) > ...) { next(new Error('too much!')); }
  next();
});
```

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
