### ISSUE TITLE
emitting to a room doesn't work for namespaced clients

### ISSUE THREAD

**Issue by dvv** [socketio/socket.io#285]
## Failing

```
io.of('/foo').on('connection', function(client) {
  client.join('aaa');
  this.in('aaa').emit('goes to noone since packet endpoint is set to "/foo/aaa", instead of "/foo" and room: "aaa"')
})
```
## Working

```
io.of('').on('connection', function(client) {
  client.join('aaa');
  this.in('aaa').emit('goes to aaa members since packet endpoint is set to "aaa"')
})
```

**Comment by selay** [comment]
yes, doesnt work on 1.3.3

**Comment by selay** [comment]
doesnt work on 1.3.6
The following example works fine if no namespace or namespace is set to '/'. If you set namespace like '/mynamepsace'. Won't work. 
socket.join('test room');
console.log(io.sockets.adapter.rooms);

**Comment by Xplouder** [comment]
@missinglink you last reply here was like 2 years ago but anyway, did you find any solution? i just posted  in stackoverflow something related. Please take a look and reply if possible. Ty http://stackoverflow.com/questions/34279278/join-a-namespace-room-from-different-namespace

**Comment by missinglink** [comment]
replied http://stackoverflow.com/questions/34279278/join-a-namespace-room-from-different-namespace/34288957#34288957

**Comment by alirezanasseh** [comment]
Still not solved in 2018! socket.io 2.1.0, why?!

**Comment by roymckenzie** [comment]
I figured it out. Basically, when emitting to namespaced rooms you also need to define the namespace.

`io.of('/chat').in( 'cool room ).emit( 'new message' );`
