### ISSUE TITLE
Disconnect socket server in IE11

### ISSUE THREAD

**Issue by ToujouAya** [socketio/socket.io#2851]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Disconnect socket server in IE11.  I'm not sure it is bug or not and I have't yet tried it on lower IE version.
My application auto disconnect after open the about IE window, The disconnection is not immediately, it will disconnect after ~1 min. 
### Steps to reproduce (if the current behaviour is a bug)
1) Create sample socket application from https://github.com/darrachequesne/socket.io-fiddle
2) Open IE browser 
3) Open about in IE setting
4) Just wait about 1 min
![image](https://cloud.githubusercontent.com/assets/21350606/22634727/a834b138-ec5f-11e6-9c10-e8c4a66e32da.png)

You can reproduce it quickly by setting the pingInterval : 1000 and pingTimeout : 5000

### Setup
- OS: Window 8.1
- browser: IE11
- socket.io version: 1.4

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

P/S
I'm not sure it is bug or not so please help me to confirm. If it is bug please help me how to  fix it. Sorry for my English

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
