### ISSUE TITLE
socket.io CORS for per request

### ISSUE THREAD

**Issue by calidion** [socketio/socket.io#2857]
### You want to:

* [] report a *bug*
* [ X] request a *feature*

### Current behaviour

currently socket.io support universal CORS config.

### Expected behaviour

support per request COR.

### Setup
- OS: all
- browser: all 
- socket.io version: newer

**Comment by darrachequesne** [comment]
May I ask what your use-case is?

**Comment by calidion** [comment]
for ims in PWAs， requests are  none domain specific。 Need to allow all kinds of requests through web.
