### ISSUE TITLE
website broken

### ISSUE THREAD

**Issue by withinboredom** [socketio/socket.io#2859]
Links I've discovered, so far:

- http://socket.io/docs/client-api/
- http://slack.socket.io/

I apologize if this isn't the right issue tracker ...

**Comment by Fingel** [comment]
It's been broken for a while. I've been evaluating this and similar libraries for a while. Decision time is rapidly approaching and I'm pretty sure I'm not going to choose the project that has had broken docs for a month.

**Comment by billouboq** [comment]
@Fingel I understand your choice but the website is not on github so we can't change it, anyway you have plenty of docs in the github repo 

https://github.com/socketio/socket.io/tree/master/docs
https://github.com/socketio/socket.io/tree/master/examples

And also @darrachequesne is doing a really great job on socket IO, see https://github.com/socketio/socket.io/issues/2823

**Comment by pensiero** [comment]
I visited the website 8 days ago and it was already broken.
Who is in charge of taking care the website? It's ridiculous for a popular service like this.

**Comment by billouboq** [comment]
@pensiero you seems to forget that people are creating those services on their free time and for free most of the time.  

> Who is in charge of taking care the website?

see this issue if you want to know more about the current state of socket.io: https://github.com/socketio/socket.io/issues/2823

**Comment by pensiero** [comment]
@billouboq work on free time doesn't justify a bad service.

The maintainers of Socket.io are free to provide bad service to their users, but you should expect critics from dissatisfied users like me.

Thanks for the link to the issue #2823

**Comment by Swinkid** [comment]
At the end of the day, only one person has access to the website. The rest of us do not. So we've tried our best and put the docs in the repo. Take a look at them.

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
