### ISSUE TITLE
read cookies setted after socket.io connection

### ISSUE THREAD

**Issue by webdevsenior** [socketio/socket.io#2860]
Maybe is a stupid question but if i set or update a cookie after client connection i can't get the new values using socket.request.headers.cookie server side without page refresh.

**Client side**
`socket = io();`
`document.cookie="foo=bar";`
`socket.emit('this', { is: 'test'});`

**Server side**
`io.sockets.on('connection', function (socket) {`
    `socket.on('this', function(reqData){` 
        `console.log(socket.handshake.headers); // there is no cookies here!`
    `});`
`}`

If i update an access token cookie using ajax i need to read the updated cookie server side without page refresh but it seems that sochet.io set the cookies only during handshake.

**Comment by krishnaTORQUE** [comment]
any update ?
I am kind of facing same issue
until I refresh the page cookie is not showing on server side

**Comment by darrachequesne** [comment]
For future readers: the `handshake` object indeed contains the headers of the first HTTP requests of the Socket.IO session.

Documentation: https://socket.io/docs/v3/server-socket-instance/#Socket-handshake

You can force the reconnection on the client-side:

```js
if (socket.io.engine) { socket.io.engine.close(); }
```

**Comment by krishnaTORQUE** [comment]
@darrachequesne is correct.
Yes indeed there it is.

If you use encrypted or signed cookie
```javascript
const allCookies = cookie.parse(socket.handshake.headers.cookie);
const signedCookie = signedCookie(allCookies.signedCookie, process.env.COOKIE_SECRET);
```

If you wants to access or facing issue in session data

call this to refresh the data
```javascript
await socket.handshake.session.reload(() => null);
```

**Comment by elbasan** [comment]
@krishnaTORQUE so there's no way to update the cookie after the connection?

**Comment by krishnaTORQUE** [comment]
@elbasan I guess **NO**
web socket make connection through P2P so yes there are some issue for session & cookie.

**Comment by darrachequesne** [comment]
@elbasan if the WebSocket connection is established (which is the most common case), you won't be able to update the cookie without closing and recreating the connection, as the headers are exchanged only at the beginning of the WebSocket connection. So my answer [above](https://github.com/socketio/socket.io/issues/2860#issuecomment-781411803) is still valid:

```js
if (socket.io.engine) { socket.io.engine.close(); }
```

Note: we could maybe create an official `forceReconnect()` method, but the implementation will be exactly this

If you are stuck in HTTP long-polling, you could indeed access the cookie of the subsequent HTTP requests. Is that your use case?

Documentation: https://socket.io/docs/v3/how-it-works/

**Comment by mortsnort** [comment]
I think the issue some people may be having is that the handshake cookie info is always from the last socket session and not the current session.  I was able to solve my problem by using socket.client.id, which provides the session ID of the current cookie.
