### ISSUE TITLE
Socket.io client on server side disconnected after few hours

### ISSUE THREAD

**Issue by samuraitruong** [socketio/socket.io#2861]
Hi everyone,

I am using socket.io on server side to connect to another soscket.io server (both using nodejs + express + socketio) .  the client only connect and listen to get data broadcast from server . it work well for couple hours then stop working while server still work fine. I though client was disconnected after certain time.

can I hook in to  disconnected event and call connect again?  Anyway we can increase alive time for connection?

Thanks

**Comment by darrachequesne** [comment]
The client should try to reconnect by itself (unless configured otherwise). Do you get any `disconnect` event? Any other event? ([reference](https://github.com/socketio/socket.io-client/blob/master/docs/API.md))
