### ISSUE TITLE
Bump engine.io to 2.0.2 to fix vulnerability in websocket

### ISSUE THREAD

**Issue by nahammervold** [socketio/socket.io#2865]
Bump engine.io to 2.0.2 to fix vulnerability in websocket

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
snyk test results in vulnerability 

### Steps to reproduce (if the current behaviour is a bug)
snyk test

### Expected behaviour
no vulnerabilities

### Setup
- OS:
- browser:
- socket.io version:

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
https://github.com/socketio/engine.io/issues/478

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io/pull/2864.
