### ISSUE TITLE
Client docs unacessible

### ISSUE THREAD

**Issue by matso165** [socketio/socket.io#2868]
Client docs have been unacessible for months...
http://socket.io/docs/client-api/

Not sure where to report this

**Comment by yeralin** [comment]
Website is down entirely

**Comment by Swinkid** [comment]
Hey,

Thanks for reporting this.

Docs can be found in the repo: https://github.com/socketio/socket.io/tree/master/docs

**Comment by ekoome** [comment]
The whole site is down.

**Comment by stephan-v** [comment]
Wtf is going on with the website.

**Comment by sandaemc** [comment]
I thought it was just me 👎

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.

**Comment by stephan-v** [comment]
Only took like a month.
