### ISSUE TITLE
http://socket.io website is down

### ISSUE THREAD

**Issue by shivajivarma** [socketio/socket.io#2870]
http://socket.io website is down. Many people on social network are reporting the same.

**Comment by brenc** [comment]
The site has been unreliable for a long time. If anyone is in need of the documentation, I believe it's all here:

https://github.com/socketio/socket.io/blob/master/docs/README.md

**Comment by dhamaniasad** [comment]
Could we get input from some maintainers here? I've faced issues with the site being unreliable before, and this problem is one that should not really exist. 

@rauchg

**Comment by darrachequesne** [comment]
I'm currently working with @rauchg to restore the website, sorry for the inconvenience.

**Comment by leslielamprecht** [comment]
It's still down, thanks @darrachequesne for trying to get it back online ....

**Comment by rauchg** [comment]
I'll have this resolved by next week. Thanks everyone for your patience!

– @rauchg <https://twitter.com/rauchg>

**Comment by Swinkid** [comment]
@rauchg We could possibly host the site via GitHub pages. I wouldn't mind help maintain this.

Alex

**Comment by PC-HUB** [comment]
I'm desperately waiting for the site to get restored...take your time and restore it soon :+1:

**Comment by sdaitzman** [comment]
Everyone can view the website for now at [archive.org](https://web.archive.org/web/20170208024545/http://socket.io/)

**Comment by askdesigners** [comment]
Really?!? Site is down for an entire week?

**Comment by Swinkid** [comment]
@askdesigners I don't see why it matters. Documentation - which is better than the websites version is available within the GitHub repository. This includes examples.

**Comment by MickL** [comment]
The chat tutorial is not available on GitHub. I had to use archive.org too.Am 27.02.2017 11:56 schrieb Alex Noble <notifications@github.com>:@askdesigners I don't see why it matters. Documentation - which is better than the websites version is available within the GitHub repository. This includes examples.

**Comment by cuduy197** [comment]
Still down :(

**Comment by eljefedelrodeodeljefe** [comment]
What is the problem?

**Comment by rauchg** [comment]
I made the necessary changes and it'll soon be back up. We are donating
free hosting from @zeithq so that it never goes offline again.

– @rauchg <https://twitter.com/rauchg>

**Comment by darrachequesne** [comment]
The site should be up again: https://socket.io/

If anyone wants to contribute, the source is here: https://github.com/socketio/socket.io-website/tree/new-website (hosted on now.sh, thanks to @rauchg :+1: )

**Comment by joshkoenig** [comment]
Still down, at least from here. Lots of reports on twitter as well.

Also looks like there's a good bit of code floating around (e.g. slackin) that references the library via CDN, which is also failing now as well.

**Comment by sambengtson** [comment]
Having issues as well accessing CDN.  Specifically, cdn-orig.socket.io

**Comment by imfinethankyou** [comment]
website still not working...

**Comment by domoritz** [comment]
Neither the website, nor the CDN (e.g. https://cdn.socket.io/socket.io-1.4.5.js) are working for me right now. Are they hosted on the same server?

**Comment by askdesigners** [comment]
@Swinkid Well is certainly makes this project look pretty sloppy. If the team of contributors can't be fucked to fix a simple website, how quickly will other bugs in the library get addressed? 

C'mon. While the documentation is in the repo, a lot of new users (like me) are going to come along and nope right out. It makes the status of everything look very suspect.

**Comment by dhamaniasad** [comment]
I have to agree with @askdesigners. This incident does not inspire confidence, and I think I should keep my eye out for needing to switch in the near-future, as this reeks of potential abandonware.

**Comment by sdaitzman** [comment]
I agree with @askdesigners and @dhamaniasad. In a world where it literally takes minutes to get a website up (seconds as a .github.io etc.) it is concerning that such a major project would take this long to get documentation up.

**Comment by arswaw** [comment]
I'm curious as to the specific reason why the website is taking so long to be restored. At the very least, couldn't you place a message that says 'Down for maintenance, please refer to this archive.org link in the meantime'.

It's better than nothing.

**Comment by barryvdh** [comment]
See https://github.com/socketio/socket.io/issues/2823#issuecomment-283951093

>Long story short: the domain is not managed by me anymore, but by
Automattic, and there have been some communication issues that have made
this process a lot more complicated than it should have been.
> I apologize for the service disruption. The CDN should be coming back up
shortly.
> - @rauchg

**Comment by arswaw** [comment]
Well, there you go.

**Comment by sapraaman** [comment]
Still down

**Comment by arswaw** [comment]
Perpetually

**Comment by sdaitzman** [comment]
I can have a mirror up in 30 seconds. Why have the developers not done so? Even if it were a different domain entirely, would be preferable. This project gets brought up at almost every hackathon I go to, and now beginners cannot find the docs???

Developers of the project, I mean you no undue disrespect, but this suggests that it may be time to fork the project and put it under new and open management given its importance to the ecosystem.

**Comment by barryvdh** [comment]
@sdaitzman The docs are right in the repo: https://github.com/socketio/socket.io/tree/master/docs

I think @darrachequesne is very active currently, but he doesn't have control over the domain.

**Comment by MickL** [comment]
The docs are not complete. Tutorial is linking to the website.

What about an alternative domain as a quickfix?

**Comment by arswaw** [comment]
@MickL You can try archive.org for now.

And I agree with @sdaitzman with regards to new management. A project of this importance needs to have full and complete documentation, and a website. A Github repo is not enough.

**Comment by darrachequesne** [comment]
Well, there is one already: https://socketio.now.sh/ (with source here: https://github.com/socketio/socket.io-website/tree/new-website)

I still hope we can restore the old Wordpress website, but that takes waaay longer than expected.

**Comment by Orbyt** [comment]
Why is this even an issue? The site has been down for months. I understand that some of the documentation text is available in the respective repositories, but many of the very useful tutorials and getting started documentation is not.

I have never seen such a popular open source project managed so poorly.

That said, I am not one to carp without offering my assistance or a solution. What can we as a community do to finally resolve this trivial issue? Is it money for hosting? Time?

Who is in charge of the site?

**Comment by arswaw** [comment]
@Orbyt Apparently not the core maintainers. Somebody else manages the domain. I know that @darrachequesne linked a working site. But I don't know who to contact about getting the socket.io domain to temporarily redirect to that site, (or archive.org) while the main site is being repaired.

**Comment by Jabark** [comment]
I believe this can now be closed: https://socket.io/

**Comment by DJCMBear** [comment]
Whoever has access to the source code of the website, update the action attribute for the MailChimp form to https, it is currently using http and causing the https to be labeled as insecure due to mixed content.

**Comment by MickL** [comment]
Is this the latest version of the website? Docs are linking to GitHub. I liked the docs on the website a lot more.
