### ISSUE TITLE
socket.io CDN does not support CORS

### ISSUE THREAD

**Issue by april** [socketio/socket.io#2875]
### You want to:

* [x] request a *feature*

### Current behaviour

Hello there!  This is April from the web security team over at Mozilla.  We had a recent request to contact you to see if you'd be willing to add cross-origin resource sharing (CORS) headers to the socket.io CDN.  This would allow socket.io to be used with [subresource integrity (SRI)](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity).

For CDNs, it simply involves adding this header when you serve a resource:
`Access-Control-Allow-Origin: *`

You can use tools like [srihash](https://www.srihash.org/) to help you determine if it's working or not, and I'd be happy to help you out with any questions you might have.

Some CDNs that already support CORS (and SRI), if you need an example:
https://code.jquery.com/jquery-2.2.4.min.js
https://unpkg.com/react@15/dist/react.min.js

It would be great if the download page could be updated to include the proper integrity/crossorigin hashes automatically, but I can understand how that would add complexity to your build and deployment chain.  Still, with how popular that socket.io is, adding CORS is a great way to improve the security and safety of the internet.

Thank you so much!

**Comment by jamilservicos** [comment]
i like cdnjs.
[https://cdnjs.com/libraries/socket.io](https://cdnjs.com/libraries/socket.io)

without SRI
`<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.7.3/socket.io.min.js"></script>`

with SRI
`<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.7.3/socket.io.min.js" integrity="sha256-WKvqiY0jZHWQZIohYEmr9KUC5rEaYEOFTq+ByllJK8w=" crossorigin="anonymous"></script>`

**Comment by darrachequesne** [comment]
@marumari thanks for contacting us.

Actually I'm not sure the socket.io CDN is still maintained, but I'll try to update the link on the website once it is up again, to point towards cdnjs.com.

**Comment by darrachequesne** [comment]
The CDN now includes the `Access-Control-Allow-Origin: *` header.

The SRI hash has been added here: https://socket.io/docs/v3/client-installation/#From-a-CDN
