### ISSUE TITLE
[Question] - How to client can join two room the same time?

### ISSUE THREAD

**Issue by NguyenTungs** [socketio/socket.io#2877]
Hi everyone!

In my project have a user , that user can in two channel , but i wanna this user can receive notifications for two channel different.

I can ask a question?
**How to Client can join multiple room and receive 2 notifications the same time for different two rooms.**
i just found this code run on server :

On server.js
```javascript
   io.sockets.to( 'channel01' ).to( 'channel02' ).emit('pushInfo', 'Nguyen Son Tung');
```

So why not features :
```javascript
   socket.join( 'channel01' ).join( 'channel02' );
```

Many thanks!

**Comment by darrachequesne** [comment]
Yes, that has already been suggested: https://github.com/socketio/socket.io/issues/2466

PR is welcome!

**Comment by NguyenTungs** [comment]
@darrachequesne 
The first give my love to you :)

It's mean :

``` javascript

socket.join(['roomOne', 'roomTwo', 'roomThree']).

```
I really can do it this way, right?
