### ISSUE TITLE
Demo https://socket.io/get-started/chat/ says "Not Found"

### ISSUE THREAD

**Issue by davestewart** [socketio/socket.io#2882]
I link from the readme:

- https://github.com/socketio/socket.io/blob/master/docs/README.md

To the site:

- https://socket.io/get-started/chat/

And get:

> Not Found

Every few months / years I come back to look at Socket IO, the demos don't seem to run, or are broken.

Is this just bad timing, or something that needs attention long-term?

**Comment by ekoome** [comment]
+1

**Comment by IG-88** [comment]
Wayback Machine has [a copy of it](http://web.archive.org/web/20161018172034/http://socket.io/get-started/chat/) taken some months ago that works. I can say that you were pretty unlucky with timing! 

The demos do actually work how they are supposed to. Just think again, use common sense.

The websites are now down anyways.
