### ISSUE TITLE
cdn.socket.io is down

### ISSUE THREAD

**Issue by bikalay** [socketio/socket.io#2883]
https://cdn.socket.io/socket.io-1.4.5.js

This site can’t provide a secure connection

cdn.socket.io sent an invalid response.

ERR_SSL_PROTOCOL_ERROR

**Comment by kilker12** [comment]
Probably due to the Amazon outage yesterday. Give them some time to bring their services back up.

**Comment by darrachequesne** [comment]
Please use https://cdnjs.com/libraries/socket.io instead.

**Comment by bikalay** [comment]
@darrachequesne. I added package to npm dependency already, but i used cdn in cordova  app,  and publish to stores can take long time. I know it was my fault, but if it possible, please add redirect. Thank you.

**Comment by fedecordova** [comment]
I have the same problem, please turn on the https://cdn.socket.io/socket.io-1.4.5.js please!!!!!!!!!! my app is published with that.

**Comment by fedecordova** [comment]
@darrachequesne  I have the same problem, please turn on the https://cdn.socket.io/socket.io-1.4.5.js please!!!!!!!!!! my app is published with that.

**Comment by barryvdh** [comment]
The alternative is nice. You can also include it from the running socketIO instance (`yourdomain:6001/socket.io/socket.io.js`), but it seems pretty important that the CDN get's fixed.

A lot of sites are still running with the old CDN:
https://github.com/search?q=https%3A%2F%2Fcdn.socket.io%2Fsocket.io-1.4.5.js&type=Code&utf8=%E2%9C%93 (25,885 results)
https://www.google.com/#q=%22https:%2F%2Fcdn.socket.io%22&* (4690 hits)

All sites running will break..

**Comment by sdaitzman** [comment]
#2870

**Comment by tonytran1** [comment]
@fedecordova Looks like it's up now.

**Comment by darrachequesne** [comment]
The CDN should be up again, but please migrate to something like https://cdnjs.com/libraries/socket.io as soon as possible (I have personally no control over the CDN).
