### ISSUE TITLE
Docs Unavailable

### ISSUE THREAD

**Issue by ekoome** [socketio/socket.io#2884]
Getting NOT FOUND when trying to access https://socket.io/get-started/chat/

**Comment by Mercieral** [comment]
Strangely enough, it doesn't work on any of my internet services. But the website works perfectly fine on my phone on 4G...

**Comment by Qiua** [comment]
Which dns are you using? Looks down from here too.

**Comment by Mercieral** [comment]
Any idea how to find that out on iOS?

**Comment by techiechelle** [comment]
I think socket.io is down.
![screen shot 2017-03-02 at 11 35 37 am](https://cloud.githubusercontent.com/assets/2449194/23516848/6722d6e4-ff3c-11e6-8355-3558531336ec.png)

**Comment by RBroden** [comment]
It's been down for a few days, I think. I thought they were just moving everything to NPM and GitHub but there are still lots of links on both that lead to socket.io.

**Comment by ip192** [comment]
How could I read some socket.io docs without [https://socket.io](url)

**Comment by Braden1996** [comment]
The docs are all in [this GitHub repository](https://github.com/socketio/socket.io/tree/master/docs)...

**Comment by sdaitzman** [comment]
#2870

**Comment by rocketspacer** [comment]
@Braden1996 No docs on clustering. Those are references, not really docs

**Comment by vishivish18** [comment]
@ekoome The site is up again 👍

**Comment by ip192** [comment]
However, I found the docs are all here on the github

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
