### ISSUE TITLE
Socket.io doesn't setup namespaces reliably with asyncronous logic

### ISSUE THREAD

**Issue by georgeedwards** [socketio/socket.io#2885]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
My mocha test timeouts on the first run (I believe because the connection event is fired before the namespace has setup). However, if mocha is live-reloaded it reliably passes on all subsequent runs. 

### Steps to reproduce (if the current behaviour is a bug)

https://gist.github.com/georgeedwards/61b9da71056ebcc7260445af3c090221
https://gist.github.com/georgeedwards/5f880225d00c003182c63f7e0e7a1cf2

Add the following two files into a directory and run mocha. 

### Expected behaviour
The test to complete properly on the first run.

### Setup
- OS: Windows 10
- browser: n/a
- socket.io version: 1.7.2

**Comment by darrachequesne** [comment]
Please use stackoverflow for that kind of question.

**Comment by georgeedwards** [comment]
@darrachequesne I am really not sure it is just a question, I have discussed this on Slack and been through the docs thoroughly, The general consensus is that what I am trying to do should work - but doesn't. Hence I opened this...

**Comment by darrachequesne** [comment]
> Add the following two files into a directory and run mocha.

In any case, could you please provide a simple test case showing the issue?
