### ISSUE TITLE
socket.io unavailable

### ISSUE THREAD

**Issue by Diuda** [socketio/socket.io#2887]
The website has been unavailable for over two weeks now. Please look into this and get this running as soon as possible as docs are not available elsewhere.

**Comment by 2b3pro** [comment]
What's going on with the site?

**Comment by Diuda** [comment]
I have no idea the sites seems to be down from about 2 weeks now.

**Comment by Swinkid** [comment]
The documentation is available in the repository. Also, this has been raised before. See #2823

**Comment by Jabark** [comment]
I believe this can now be closed: https://socket.io/

**Comment by Diuda** [comment]
yeah the site is up again
thanks
