### ISSUE TITLE
prevent further connections

### ISSUE THREAD

**Issue by MichaelAlthoff** [socketio/socket.io#2888]
hi community,
if there a way to prevent further connections when the first one established ?
My prob is when the first client submit his info to the server, the server-app is starting and do something.
Maybe a second client try to connect. during the server is running the application, the first client see the idle button, the second client can't connect to the server, till the server-app is finished. the second client submit his data to the server, and the server run again the app with the new parameter.

Can I prevent this behavior.
I would be nice if the server ignored the information for a defined time, and the clients also no longer tries to send him data.

kind regards 

Mike

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
