### ISSUE TITLE
Socket.io Hello World Chat Tutorial is down

### ISSUE THREAD

**Issue by LukeR51** [socketio/socket.io#2893]
https://socket.io/get-started/chat/ is currently down. I assume this has something to do with server crash a few hours ago. Everything else seems to be working properly.

**Comment by JamesWClark** [comment]
The home page links to https://socket.io/get-started and I am getting a 404 Not Found error page.

**Comment by darrachequesne** [comment]
It should be up again, sorry for the inconvenience.
