### ISSUE TITLE
WebSocket Handshake Error appears sometimes on Heroku

### ISSUE THREAD

**Issue by flaurida** [socketio/socket.io#2894]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

Hi Socket.io,
I have a web application (www.pokemania.site) on Heroku that uses a Node.js server and Socket.IO (not using Express at the moment). I am seeing this strange error in production that is not in development, with a message "VM302:35 WebSocket connection to 'ws://www.pokemania.site/socket.io/?EIO=3&transport=websocket&sid=UZTNHUTNkuM5UAS6AAAJ' failed: Error during WebSocket handshake: Unexpected response code: 400". The even stranger thing is that this message only appears sometimes, generally during the day. I don't understand what is going on, though someone suggested it could be because I need to upgrade to hobby. Please let me know what might be going on? If it helps, please feel free to check out the source code on Github (https://github.com/flaurida/pokemania). Thanks and happy Friday!

Sincerely,
Laura

**Comment by flaurida** [comment]
To give more context, the error went away this entire weekend on Heroku, but has come back again this morning. Why might that be happening? I did not change the code in any way between this weekend and now.

**Comment by flaurida** [comment]
It may also have something to do with HTTP vs HTTPS?

**Comment by darrachequesne** [comment]
Hi Laura,

What happen when this error occur? Does the server crash? Do you have any log?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
