### ISSUE TITLE
There doesn't appear to be a way to track room creation/deletion

### ISSUE THREAD

**Issue by vincentwoo** [socketio/socket.io#2897]
### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour

Right now, it appears that rooms are a socket-level construct only. Individual connections appear to know what rooms they're a part of. Adapters like `socket.io-redis` appear to have *just enough* functionality to know how to route messages to all members of a room.

### Expected behaviour

In many applications, `socket.io` will sit on top of a room that represents some potentially costly resource. For instance, in my use case, I want to spin up a docker container to be used by everyone in a room. That means I need to know when to create one and when to delete one when it's no longer being used.

I can try to track room membership on my own, but then I become a central point of failure anyhow.

### Suggestion

In a system like the one `socket.io-redis` suggests, I think it should be possible for all nodes to subscribe to when rooms are created or destroyed, since those changes should be pubbed through redis already.

**Comment by darrachequesne** [comment]
Well, I guess we could emit an event when a room is created:

https://github.com/socketio/socket.io-adapter/blob/1.1.0/index.js#L56
```js
for (var i = 0; i < rooms.length; i++) {
    var room = rooms[i];
    this.sids[id] = this.sids[id] || {};
    this.sids[id][room] = true;
    if (!this.rooms.hasOwnProperty(room)) {
      this.rooms[room] = Room();
      this.emit('create-room', room);
    }
    this.rooms[room].add(id);
}
// and then
io.of('/').adapter.on('create-room', /* */);
```
What do you think?

**Comment by vincentwoo** [comment]
I think that would certainly work for detecting creation, and in the basic `socket.io-adapter` that might be okay. I think the bigger questions are how you would do it in the redis model, as well as detecting deletion. For the basic adapter you could add a corresponding emit here: https://github.com/socketio/socket.io-adapter/blob/c6f7baec3b000bf75ce4b5278ac146dc993a537f/index.js#L81.

**Comment by throwarray** [comment]
Could I suggest join and leave events as well? The current callback approach isn't ideal and I notice a lot of people rolling their own room implementations.

**Comment by darrachequesne** [comment]
For future readers: starting with `socket.io@3.1.0`, the underlying Adapter will emit the following events:

- `create-room` (argument: room)
- `delete-room` (argument: room)
- `join-room` (argument: room, id)
- `leave-room` (argument: room, id)

Example:

```js
io.of("/").adapter.on("create-room", (room) => {
  console.log(`room ${room} was created`);
});

io.of("/").adapter.on("join-room", (room, id) => {
  console.log(`socket ${id} has joined room ${room}`);
});
```

Documentation: https://socket.io/docs/v3/rooms/#Room-events

**Comment by Tsourdox** [comment]
Is there a way to get the correct typescript types for these events?

**Comment by darrachequesne** [comment]
@Tsourdox no, this is not currently possible, but we could add this I guess :+1:
