### ISSUE TITLE
npm install socket.io only installs socket.io@1.0.0, not 1.7.3

### ISSUE THREAD

**Issue by crkellen** [socketio/socket.io#2899]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Using a package.json with the dependency of "socket-io": "^1.7.3", will always error as npm cannot find socket.io version 1.7.3.

1.7.3 must be manually installed by doing 'npm install socket.io@1.7.3'
This prevents installing all dependencies by using 'npm install'

### Steps to reproduce (if the current behaviour is a bug)
Add "socket-io": "^1.7.3", to your dependency list in your package.json and attempt a 'npm install'

### Expected behaviour
'npm install' should grab the latest version (1.7.3) of socket.io

### Setup
- OS: Windows/Node
- socket.io version: 1.7.3

**Comment by dcorns** [comment]
Make sure you are using socket.io and not socketio. The problem you are reporting is exactly what happens when you are using socketio without the dot.

**Comment by crkellen** [comment]
I copy and pasted what was in my package.json. Should it not be 'socket-io'?

**Comment by dcorns** [comment]
It should be socket.io

**Comment by crkellen** [comment]
Odd, I have no idea why it got like that. I don't remember doing a socket-io install or a socketio install.
Thanks!
