### ISSUE TITLE
WS upgrade fails with socket.io Java client 0.8.3

### ISSUE THREAD

**Issue by kramasundar** [socketio/socket.io#2901]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
WC connection upgrade fails with Socket.io java client (0.8.3)

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
Connection is established and data could be exchanged on the WS channel

### Setup
- OS: Windows 7
- browser: -NA-
- socket.io version: nodejs socket.io js - 1.7.3, Java socket.io - 0.8.3

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
nodejs debug log:

`ram@rampc:~$ DEBUG=* node 5gfe/app.js
  socket.io:server initializing namespace / +0ms
  socket.io:server creating http server and binding to 8080 +16ms
  socket.io:server creating engine.io instance with opts {"path":"/socket.io"} +17ms
  socket.io:server attaching client serving req handler +90ms
Server running
  engine intercepting request for path "/socket.io/" +12s
  engine handling "GET" http request "/socket.io/?EIO=3&transport=polling" +1ms
  engine handshaking client "vCLeuL8DUyO5TwVUAAAA" +10ms
  engine:socket sending packet "open" ({"sid":"vCLeuL8DUyO5TwVUAAAA","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}) +5ms
  engine:polling setting request +4ms
  engine:socket flushing buffer to transport +1ms
  engine:polling writing "      �0{"sid":"vCLeuL8DUyO5TwVUAAAA","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}" +11ms
  engine:socket executing batch send callback +21ms
  socket.io:server incoming connection with id vCLeuL8DUyO5TwVUAAAA +1ms
  socket.io:client connecting to namespace / +4ms
  socket.io:namespace adding socket to nsp / +1ms
  socket.io:socket socket connected - writing packet +51ms
  socket.io:socket joining room vCLeuL8DUyO5TwVUAAAA +1ms
  socket.io:client writing packet {"type":0,"nsp":"/"} +12ms
  socket.io-parser encoding packet {"type":0,"nsp":"/"} +0ms
  socket.io-parser encoded {"type":0,"nsp":"/"} as 0 +8ms
  engine:socket sending packet "message" (0) +20ms
  socket.io:socket joined room vCLeuL8DUyO5TwVUAAAA +5ms
  engine intercepting request for path "/socket.io/" +3s
  engine handling "GET" http request "/socket.io/?EIO=3&transport=polling&sid=vCLeuL8DUyO5TwVUAAAA" +1ms
  engine setting new request for existing client +1ms
  engine:polling setting request +0ms
  engine:socket flushing buffer to transport +1ms
  engine:polling writing "�40" +1ms
  engine:socket executing batch send callback +6ms
  engine upgrading existing transport +95ms
  engine:socket might upgrade socket transport from "polling" to "websocket" +1ms
  engine intercepting request for path "/socket.io/" +63ms
  engine handling "POST" http request "/socket.io/?EIO=3&transport=polling&sid=vCLeuL8DUyO5TwVUAAAA" +0ms
  engine setting new request for existing client +1ms
  engine:polling received �420["MeasurementData",{"Time":1490090193899,"Date":"Tue Mar 21 10:56:33 CET 2017"}]" +1ms
  engine:socket packet +2ms
  socket.io-parser decoded 20["MeasurementData",{"Time":1490090193899,"Date":"Tue Mar 21 10:56:33 CET 2017"}] as {"type":2,"nsp":"/","id":0,"data":["MeasurementData",{"Time":1490090193899,"Date":"Tue Mar 21 10:56:33 CET 2017"}]} +3s
  socket.io:socket got packet {"type":2,"nsp":"/","id":0,"data":["MeasurementData",{"Time":1490090193899,"Date":"Tue Mar 21 10:56:33 CET 2017"}]} +3ms
  socket.io:socket emitting event ["MeasurementData",{"Time":1490090193899,"Date":"Tue Mar 21 10:56:33 CET 2017"}] +0ms
  socket.io:socket attaching ack callback to event +0ms
  socket.io:socket dispatching an event ["MeasurementData",{"Time":1490090193899,"Date":"Tue Mar 21 10:56:33 CET 2017"},null] +1ms
MeasurementData: Tue Mar 21 10:56:33 CET 2017: 1490090193899
  engine:socket client did not complete upgrade - closing transport +10s
  engine:ws closing +2ms
`

**Comment by darrachequesne** [comment]
Please open an issue here: https://github.com/socketio/socket.io-client-java
