### ISSUE TITLE
avoid sending event names for multiply times

### ISSUE THREAD

**Issue by nybbs2003** [socketio/socket.io#2902]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour
For binary messages in the same event name, a text message is sent over and over again, which takes up relativly large amount of bandwidth, compared to the size of binary message being sent.

[text msg indicate that next binary msg is of event  named 'a']
[binary msg of event 'a']
[text msg indicate that next binary msg is of event  named 'a']
[binary msg of event 'a']
[text msg indicate that next binary msg is of event  named 'a']
[binary msg of event 'a']
[text msg indicate that next binary msg is of event  named 'a']
[binary msg of event 'a']
[text msg indicate that next binary msg is of event  named 'a']
[binary msg of event 'a']
[text msg indicate that next binary msg is of event  named 'a']
[binary msg of event 'a']
[text msg indicate that next binary msg is of event  named 'a']
[binary msg of event 'a']
[text msg indicate that next binary msg is of event  named 'a']
[binary msg of event 'a']
[text msg indicate that next binary msg is of event  named 'b']
[binary msg of event 'b']

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour

[text msg indicate that next binary msg is of event  named 'a']
[binary msg of event 'a']
[binary msg of event 'a']
[binary msg of event 'a']
[binary msg of event 'a']
[binary msg of event 'a']
[binary msg of event 'a']
[binary msg of event 'a']
[binary msg of event 'a']
[text msg indicate that next binary msg is of event  named 'b']
[binary msg of event 'b']

### Setup
- OS:
- browser:
- socket.io version:

**Comment by darrachequesne** [comment]
Related: https://github.com/socketio/socket.io-parser/issues/61

A solution in the upcoming version will be to use a custom parser, like the one [here](https://github.com/darrachequesne/socket.io-msgpack-parser).

**Comment by darrachequesne** [comment]
@nybbs2003 since version 2.0.0 you can now provide your own parser:

Please take a look at:
- https://github.com/socketio/socket.io-parser/issues/61
- https://github.com/socketio/socket.io/tree/master/examples/custom-parsers
