### ISSUE TITLE
"Invalid namespace" on reconnection (timing issue)

### ISSUE THREAD

**Issue by crsten** [socketio/socket.io#2903]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Client is connected to a namespace.
If the server goes down and the client reconnects immedeatly after the server has come up. The server returns "Invalid namespace" and the client can't properly connect to the correct namespace. The client is however connected to the default ("/") namespace.

If the client waits some seconds before reconnecting to a freshly restarted server, the connection to the namespace works as expected.

### Steps to reproduce (if the current behaviour is a bug)

1. Startup server
2. Let clients connect to a custom namespace
3. Restart server
4. Let clients reconnect (since this bug is affected by connection timing, you will eventually need to retry. The clue is to get server restart and client reconnect as close as possible)
5. If you inspect the frames ("did it with chrome") you should see "Invalid namespace" error

### Setup
- OS: Any (tested on MACOS Sierra & Win 10 & linux)
- browser: Any (tested on firefox / chrome / safari) 
- socket.io version: 1.7.3

### Temporary workaround
We did find a workaround for this bug: 
1. Listen to error event on client
2. Manually disconnect and connect (use a little timeout to avoid too many reconnects)

**Comment by darrachequesne** [comment]
How are you initializing your custom namespace? Are you using the [redis](https://github.com/socketio/socket.io-redis) adapter (so the `initAdapter` method could induce some latency)?

I am able to reproduce the "Invalid namespace" with:
```js
setTimeout(() => io.of('/test', (socket) => {}), 1000);
```

As a workaround, maybe add a delay before the http server actually handles requests?

**Comment by crsten** [comment]
I'am initializing the namespace dynamically at runtime when it's needed. I guess that's where the problem is located. 

As soon as the namespace has been initialized the connection works as it should.
So that's the problem right? 

I can't find anything about namespace initialization in the documentation, could someone point me in the right direction or give an example on how this is done?

**Comment by darrachequesne** [comment]
@crsten sorry for the delay. Yes, if the namespace is not already initialized, the client won't be able to connect. And you create a namespace with `io.of(<your namespace>)`, documented [here](https://github.com/socketio/socket.io/blob/master/docs/API.md#serverofnsp).

**Comment by crsten** [comment]
Thanks for your reply! 
Alright then, problem solved. That means this is no bug, but faulty implementation by me 😄

**Comment by shemul** [comment]
@crsten so how you create namespaces dynamically if you don't know what should be the namespace name ?

**Comment by crsten** [comment]
@shemul `io.of(<your namespace>)` is the way to do it. I ended up doing an inital fetch of all documents from my DB at startup and looped through them and called `io.of(<your namespace>)` for each of them.

**Comment by shemul** [comment]
@crsten okay. thank you. I will do my test.

**Comment by yingnian** [comment]
I also have this problem.
Namespace invalidation occurs on the first connection, but it works when I refresh it.
