### ISSUE TITLE
Socket.io not accessible via domain name.

### ISSUE THREAD

**Issue by Abubakar63** [socketio/socket.io#2909]
I have a socket.io node js application running on server on port 3001. When I access that socket connection via browser **http://ip-address:3001/socket.io/socket.io.js**. It works perfectly fine.

And I have a domain abc.com pointing to that server. 

When I try to access via browser like **https://abc.com:3001/socket.io/socket.io.js** then it doesn't work and connection timed out error comes.

As I am new to nodeJS and socket.io. So please guide me.

**Comment by darrachequesne** [comment]
@Abubakar63 could it be related to the https configuration? Could you provide more details please?

**Comment by Abubakar63** [comment]
Thank you @darrachequesne. I have fixed this issue. :)

**Comment by Mobifyi** [comment]
@Abubakar63 how did you fix this issue please ? We are facing the same issue , did you configure the https ? Help would be greatly appreciated :)

**Comment by Lissy93** [comment]
I have exactly the same issue- if anyones got a fix, or any suggestions, they'd be appreciated

**Comment by Lissy93** [comment]
Found the solution, eventually - posting here in case it helps anyone else in the future.
 
**Socket.io V 2.0 + is not backward compatible**. 
See the [V2.0.0 release notes for details of what you need to change](https://github.com/socketio/socket.io/releases/tag/2.0.0) 

_More details on [my question on SO here](https://stackoverflow.com/questions/48075509/socket-io-failed-websocket-is-closed-before-the-connection-is-established/48078678)_

Hope that helps 😁

**Comment by bilalbaz1** [comment]
If you want to run on version 2.x.x, use version "2.4.1"

``` "socket.io": "^2.4.1" ```

[npm i socket.io@2.4.1](https://www.npmjs.com/package/socket.io/v/2.4.1)
