### ISSUE TITLE
socket.io 's docs for Express 4.x 

### ISSUE THREAD

**Issue by tinyCucumber** [socketio/socket.io#2911]
i used socket in express recently after reading docs of socket.io.But there is one problem , in the docs,it create a server in app.js.And the truth is , for express 4.x,the server will created in 'www' file,if you use socket.io as the docs says,it wont run.

**Comment by nimat-netlinks** [comment]
I can not connect socket.io to express 4.x, any one around can help me ? https://stackoverflow.com/questions/46946465/can-not-connect-socket-io-to-express4

**Comment by darrachequesne** [comment]
Added in the documentation here: https://socket.io/docs/v3/server-initialization/#With-Express
