### ISSUE TITLE
socket.join not working

### ISSUE THREAD

**Issue by lappalj4** [socketio/socket.io#2914]
Repost from SO, but I need answers so here: 

So, my socket.join calls are doing nothing. After calling socket.join, and then listing the rooms the socket is in, the socket is only connected to the room defined by it's id (it's own room). 
```
    function onJoin(room) {
        console.log("Joining room: " + room);
        socket.join(room);
        console.log(socket.id + " now in rooms ", socket.rooms);
    }
```
    
Would print for example: 
```
    > Joining room: 5aba92759b9ffa9fdf579714d6aa125ddb05cb1172611331775e7a69dab37258
    > Q6D4h17DvdOZrbrEAAAC now in rooms  { Q6D4h17DvdOZrbrEAAAC: 'Q6D4h17DvdOZrbrEAAAC' }
```

If it makes a difference, here's how my socket server is being created: 
```
    //app.js
    var app = express();
    var http = require('http');
    var server = http.Server(app);
    var io = require('socket.io')(server);
    var chat = require('./routes/chat/chat')(io);

    //chat.js
    module.exports = function(io) {
      io.sockets.on('connection', function(socket) {
        
        socket.on('join', onJoin);
        ...
    }
```
 

Where's the issue?

- Socket.io v1.7.3

**Comment by darrachequesne** [comment]
The `join` method is asynchronous:

```js
socket.join(room, function () {
  console.log(socket.id + " now in rooms ", socket.rooms);
});
```

**Comment by lappalj4** [comment]
Indeed, thanks for that!

**Comment by hsunami10** [comment]
How would you join a room then immediately emit to that room, including the socket that just joined? Because this isn't working.
`    socket.join("room-" + group_id, () => {
      console.log(socket.rooms);
      io.in("room-" + group_id).emit('receive_message', { is_alert: true, username, joined: true })
    })`

**Comment by mgiraldo** [comment]
for some reason this doesnt work with async/await like so:

````
await socket.join(room);
console.log(socket.id + " now in rooms ", socket.rooms);
````

is this the expected behavior?

**Comment by mneil** [comment]
@mgiraldo it's a callback function, not a returned Promise. It would need to return a promise to be awaited.

**Comment by mgiraldo** [comment]
got it... i ended up not needing the callback because i'm force-leaving all rooms using
```
  Object.keys(client.rooms).forEach(room => {
    client.leave(room);
});
```
then joining the new room... the syntax for promisifying functions is confusing to me so i had to punt on that

**Comment by darrachequesne** [comment]
@hsunami10 the code you provided should be working. Any error thrown?

@mgiraldo @mneil is right, but returning a Promise when no callback is provided is something we could include here I think.

**Comment by chuckdries** [comment]
Could we maybe mention the join callback the rooms and namespaces documentation? The example there makes it seem synchronous. I know it's in the actual API section but it would have saved us a bit of trouble if it were here. https://socket.io/docs/rooms-and-namespaces/

**Comment by OzairP** [comment]
@chuckdries welcome to the world of socket.io documentation
