### ISSUE TITLE
Socket.io is not a realtime implementation of sockets. Evidence attached

### ISSUE THREAD

**Issue by samcv** [socketio/socket.io#2915]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
“In computer science, real-time computing (RTC), or reactive computing describes hardware and software systems subject to a "real-time constraint", for example from event to system response. Real-time programs must guarantee response within specified time constraints, often referred to as "deadlines" .” [Source](https://en.wikipedia.org/wiki/Real-time_computing)

**socket.io does not meet this criteria**

### Steps to reproduce (if the current behaviour is a bug)
* Read definition of realtime computing
* Read socket.io site which says: **"FEATURING THE FASTEST AND MOST RELIABLE REAL-TIME ENGINE"**
* Use socket.io
* See screenshot attached

### Expected behaviour
Expected a real time implementation of sockets. 

### Setup
- OS: linux
- browser: chrome
- socket.io version: all of them

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
**Further evidence by this screenshot**

![screenshot_20170419_153642](https://cloud.githubusercontent.com/assets/20145557/25205167/0832ef02-2516-11e7-84a7-f001fc6fe338.png)

**Comment by alexhultman** [comment]
JS devs often hijack low level programming concepts and put their own overloaded meaning to them:

* Realtime (nothing written in JS is realtime, it has a GC that breaks this guarantee).
* Memory leak (there are no true memory leaks in JS, it has a GC).
* User space (no such thing as kernel space JS).

I think you are overreacting, this is JS, nothing is serious here. It's all based on hype and buzz.

**Comment by dndteam** [comment]
@samcv You must be fun at parties ...

**Comment by jamesshore** [comment]
Please don't waste maintainers' time with this kind of crap. Socket.IO is a tool for real-time web, not real-time computing. Like it or not, language evolves. (And even though it doesn't have to, the term "real-time web" does make sense as an example of soft real-time computing where the time constraint is on the order of 1-10s.)

(not a Socket.IO maintainer)
