### ISSUE TITLE
on didn't work as expected (sometimes)

### ISSUE THREAD

**Issue by Haideralee** [socketio/socket.io#2919]
I am facing the same issue but in my case the problem in `on` section, emit is working fine but the listen is not working as expected.
Ex: 
```
Ctrl 1
       this.SocketIo.socket.on('user:updated', function(data){
            console.log("user:updated in choose place", data)
        });

Ctrl 2

       this.SocketIo.socket.on('user:updated', function(data){
            console.log("user:updated in choose place", data)
        });

        this.SocketIo.socket.emit('acceptedJob', {res});

Server

     socket.on('acceptedJob', (res) => {
            socket.log('acceptedJob');
            socket.emit('user:updated', res);
      });
```
the confusing thing is on running in `Ctrl 2` but not listen in `Ctrl 1` , 

secondly, i am not receiving event all the time. 

i emit the event form server 

Server
``   Socket.emit('user:updated',updatedUser); ``

and on mobile-client i listen this event as 

mobile-client
````
         this.SocketIo.socket.on('user:updated', function(data){
            console.log(data)
        });
````
sometime it gets the event, sometime not. (i am having the socket connection with the server)
I am using meteor-ionic.

**Comment by darrachequesne** [comment]
Answered here: https://github.com/socketio/socket.io-client/issues/700#issuecomment-296400168

Were you able to find the issue?

**Comment by Haideralee** [comment]
@darrachequesne not yet. i am facing some weird behavior. 
sometime i gets the event, within seconds i re-emit the event but unable to listen.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by trupeshv** [comment]
> @darrachequesne not yet. i am facing some weird behavior. sometime i gets the event, within seconds i re-emit the event but unable to listen.

I am facing the same issue.

**Comment by darrachequesne** [comment]
@trupeshv could you please open a new issue with all necessary details?
