### ISSUE TITLE
Socket.leave doesn't work, still receiving event from the old rooms 

### ISSUE THREAD

**Issue by fithwith** [socketio/socket.io#2920]
I'm using 
socket.io version 1.7.2
nodejs version 6.0.0
I'm also using socket.io-redis version 2.0.1

I'm trying to leave a room and subscribe to a new one, but I'm still receiving old events, I checked the content of  socket.adapter.rooms  and when the socket join its added under the room but but when the socket leave the socket is not removed from the room.

**Comment by darrachequesne** [comment]
@fithwith could you provide some code? Also, please be aware that socket.leave is async:

```js
socket.leave('room1');
socket.adapter.rooms; // may still contain room1
// instead
socket.leave('room1', function (err) {
  // ok
});
```

**Comment by fithwith** [comment]
I tried, but the same, and n the browser I'm still receiving events from old rooms.

`
console.log(socket.adapter.rooms);    //display the list of rooms
socket.leave('room');

socket.leave('room', function (err) {
   console.log(err); // display null
   console.log(socket.adapter.rooms);  // display the same list of rooms the specified room is still there
});
`

**Comment by darrachequesne** [comment]
@fithwith oh :goat: ! `socket.adapter.rooms` contains every room created on your server, you are looking for `socket.rooms`, aren't you?

**Comment by fithwith** [comment]
my problem was not from where I can get the rooms, but leaving a room.
but just now I discovered what was the error, it was a stupid mistake from me, I was giving the leave function a wrong room name so that's why it was not working, with the correct one it works perfectly.
sorry for that :)

**Comment by neobie** [comment]
For me, it doesn't work as well.
It seems like leave() cannot take array as param like join() did.
No clear documentation is given.

**Comment by darrachequesne** [comment]
@neobie no, `socket.leave()` does not currently handle passing an array of rooms.

Reference: https://socket.io/docs/v4/server-api/#socketleaveroom
