### ISSUE TITLE
Where to get client side file socket.io.js?

### ISSUE THREAD

**Issue by Globik** [socketio/socket.io#2922]
can't find *Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:
- browser:
- socket.io version:

**Comment by darrachequesne** [comment]
The client file is exposed by the socket.io server at `/socket.io/socket.io.js` (unless configured otherwise).

Else, you can find it on a CDN, like https://cdnjs.com/libraries/socket.io

**Comment by Globik** [comment]
Ah, thank you. I'v found it on cdn. One can close this issue.
