### ISSUE TITLE
socketio sticky session

### ISSUE THREAD

**Issue by l3l4c7-h4t** [socketio/socket.io#2927]
Hi

I have more than +100K Clients and I have to use socketio sticky session for Multiple Process...

**this is my simple server code:**

```js
var sticky = require('socketio-sticky-session');
  
var server = sticky(function() {
  var http = require('http'),
      io = require('socket.io');
 
  var server = http.createServer(function(req, res) {
    
  });
  io.listen(server);
 
  return server;
}).listen(3131, function() {
  console.log('server started on 3131 port');
});
 
server.on( 'connection', function( socket ){
  socket.broadcast.emit('to-client','hi');
});
```

**and this is my Client browser code:**

`$(document).ready(function() {
			var socket = io.connect('http://111.111.111.111:3000');
			socket.on('to-client', function (data) {
				alert("eceived Message");
			});
			 $("#send").click(function(event) {
				socket.emit('to-client', "aaa");
			});
		});`

the client connected to the server successfully, but when the Client clicked on "#send" button, nothing happen ... ( must be shown alert("received Message")

whats problem?

**Comment by gboysko** [comment]
The problem is that clicking on the #send button sends a message to the server, but the server is not responding to it. You should still see the alert box (with `eceived Message`), but that will only occur when the initial connection is established.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
