### ISSUE TITLE
io.sockets.to('room').emit() needed

### ISSUE THREAD

**Issue by jakeg** [socketio/socket.io#293]
You can `io.sockets.emit('foo', 'bar')` to send a send a message to everyone from outside of an individual socket. But what if you want to send a message to everyone in one room only from outside of an individual socket? Something like `io.sockets.to('room').emit('foot', 'bar')`

Use-case would be polling a database for updates and sending them to everyone in one room only. You don't want every single client in that room doing their own database poll.

**Comment by FrancisLeon** [comment]
sweet
