### ISSUE TITLE
doesn't work well on windows

### ISSUE THREAD

**Issue by cherish1260** [socketio/socket.io#2931]
`UnhandledPromiseRe
jectionWarning: Unhandled promise rejection (rejection id: 1178): UnableToResolveError: Unable to resolve module \node_modules\engine.io-client\lib\transports\index.j\lib\xmlhttprequest.js。`

It seems the path is not right.

**Comment by darrachequesne** [comment]
Please provide a complete example reproducing the issue, thanks.
