### ISSUE TITLE
The docs seem to be offline

### ISSUE THREAD

**Issue by pensierinmusica** [socketio/socket.io#2932]
<img width="1920" alt="screenshot" src="https://cloud.githubusercontent.com/assets/3594037/25818434/e2fd31f6-342a-11e7-9a31-b2fc267866cd.png">

**Comment by pensierinmusica** [comment]
@rauchg @darrachequesne any idea what could be causing this? Thx!

**Comment by darrachequesne** [comment]
@pensierinmusica thanks for the heads-up! It seems there was an issue with the platform, but it looks like it is fixed now.
