### ISSUE TITLE
Server lost the message which is sent in client reconnect event handler

### ISSUE THREAD

**Issue by mingc00** [socketio/socket.io#2935]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
We register asynchronous middleware for authentication. After upgrading socket.io from 1.7.4 to 2.0.1, server cannot get the message if client sent it in `reconnect` event handler.

### Steps to reproduce (if the current behaviour is a bug)
Please reference the code: https://github.com/mingc00/socket.io-fiddle

1. Register a asynchronous middleware
2. Startup server
3. Turn off server after client is connected
4. Restart the server
5. Server cannot get the message which is sent in client `reconnect` event handler.

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
In previous version, server should get the message which is sent in client `reconnect` event handler.

### Setup
- OS: Ubuntu 16.04
- browser: Chrome 58
- socket.io version: 2.0.1

**Comment by adrai** [comment]
same issue even if directly emitting a message in the `connect` event handler

**Comment by darrachequesne** [comment]
@mingc00 thanks for the fiddle, I could indeed reproduce.

It seems to be related to https://github.com/socketio/socket.io/pull/2833, the CONNECT packet is sent too soon.

**Comment by adrai** [comment]
same issue as: https://github.com/socketio/socket.io/issues/2866

**Comment by mxq19901028** [comment]
How to ignore the LTS certificate problem?
