### ISSUE TITLE
bufferUtil.unmask undefined error still on socket.io 2.x

### ISSUE THREAD

**Issue by drcmda** [socketio/socket.io#2936]
This bug is haunting us sporadically for at least half a year now, it's never really clear why and there have been issues about that here as well but they got closed. Now as of socket.io 2.x all our Windows customers got it, while it seems to do alright on my Mac. 

![img_10052017_074230_0](https://cloud.githubusercontent.com/assets/2223602/25888526/d5fccbc8-3566-11e7-9bb8-fc883177b609.png)

On the server:

```json
"engines": {
    "node": ">=7.6.0"
  },
"dependencies": {
    "socket.io": "2.0.1",
    "uws": "^0.14.5"
  },
"optionalDependencies": {
    "bufferutil": "2.x.x",
    "utf-8-validate": "2.x.x"
  },
```

```js
this.io = require('socket.io')(this.socket, { wsEngine: 'uws' });
```

On the client

```json
"socket.io-client": "^2.0.1",
```

```js
this.socket = io(url);
```

**Comment by darrachequesne** [comment]
Hmm, `uws` may have issues with Windows. It seems engine.io is using `ws` as a fallback, could you please check your version?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
