### ISSUE TITLE
TypeError: this.adapter.addAll is not a function

### ISSUE THREAD

**Issue by Nerfair** [socketio/socket.io#2937]
After socket.io update from 1.7.4 to 2.0.1 i am getting error

```
0|server   | TypeError: this.adapter.addAll is not a function
0|server   |     at Socket.join (/home/htdocs/socket/server/node_modules/socket.io/lib/socket.js:244:16)
0|server   |     at Socket.onconnect (/home/htdocs/socket/server/node_modules/socket.io/lib/socket.js:299:8)
0|server   |     at /home/htdocs/socket/server/node_modules/socket.io/lib/namespace.js:171:16
0|server   |     at _combinedTickCallback (internal/process/next_tick.js:73:7)
0|server   |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

my package.json is

```
"dependencies": {
    "file-type": "latest",
    "htmlspecialchars": "latest",
    "jsonwebtoken": "latest",
    "mysql": "latest",
    "pmx": "latest",
    "redis": "latest",
    "socket.io": "latest",
    "socket.io-redis": "latest",
    "twemoji": "latest"
  }
```

Found why, i am using [socket.io-redis](https://github.com/socketio/socket.io-redis/blob/master/index.js) as adapter, and it's not having  addAll method.

**Comment by darrachequesne** [comment]
Please use `socket.io-redis` [5.0.0](https://github.com/socketio/socket.io-redis/releases/tag/5.0.0).

**Comment by xzk821649509** [comment]
I also have the same question, does the author solve the problem?

**Comment by ImYasine** [comment]
I had a same issue and i simply degraded my nodev20.x.x and socket io: "^4.7.2",
and also changed in my code from this const io = new Server(server, {
    connectionStateRecovery: {}
});
to that const io = new Server(server);
i hope it helps
