### ISSUE TITLE
Possible remove of placeholder packet

### ISSUE THREAD

**Issue by jannicars** [socketio/socket.io#2938]
### You want to:

* [] report a *bug*
* [x ] request a *feature*

### Current behaviour

We are using socket.io in combination with schemapack and binary data only. When binary is being sent, socket.io is also sending placeholder packets. For what are they needed exactly? Is there a way we can get rid of them? Or at least reducing it's size?

`{_placeholder: true, num: 0}`

![Image of Yaktocat](http://image.prntscr.com/image/f9849dd14cd34621a6370969c75d4fdf.png)

### Setup
- OS: Doesn't matter
- browser: Doesn't matter
- socket.io version: 2.0.1

**Comment by darrachequesne** [comment]
@jannicars since version 2.0.0 you can now provide your own parser:

Please take a look at:
- https://github.com/socketio/socket.io-parser/issues/61
- https://github.com/socketio/socket.io/tree/master/examples/custom-parsers

**Comment by jannicars** [comment]
Thanks, this solved the issue! I wrote an own parser to send binary data without the placeholder.

**Comment by darrachequesne** [comment]
Great :+1:

**Comment by UgurAbasov** [comment]
I tried schemapack parser not working. Still sending this additional data.
