### ISSUE TITLE
Nginx Proxy timeout

### ISSUE THREAD

**Issue by jannicars** [socketio/socket.io#2939]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Nginx randomly logs the following error:
`upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxxxxx, server: xxxxxxxxx, request: "GET /realtime/?EIO=3&transport=polling&t=xxxxxxxx&sid=xxxxxxxx HTTP/1.1", upstream: "http://127.0.0.1:3000/realtime/?EIO=3&transport=polling&t=xxxxxxxx&sid=xxxxxxxx""`

I'm using the same configuration for nginx as on [https://github.com/socketio/socket.io/blob/master/examples/cluster-nginx/nginx/nginx.conf](https://github.com/socketio/socket.io/blob/master/examples/cluster-nginx/nginx/nginx.conf).

### Steps to reproduce

Start a socket.io server behind a nginx proxy, connect with a client and wait.

### Expected behaviour

No errors in nginx error log.

### Setup
- OS: All of them
- browser: All of them
- socket.io version: 2.0.1

**Comment by vickos** [comment]
+1

**Comment by darrachequesne** [comment]
@jannicars hi, I'm not able to reproduce with the example: https://github.com/socketio/socket.io/tree/master/examples/cluster-nginx

Do the requests actually reach the server, before timing out?

**Comment by v0devil** [comment]
Also the same problem

**Comment by Steveb-p** [comment]
I'd like to say I've a similar issue going on my servers for a month now :/ It might be causing me some issues further down the road:
On random occasions, specific users are not able to connect to socket.io at all. They are however perfectly capable of delivering ajax requests to the node server itself (to the main server handler function, which I've setup just before the connection should start). I have logged user communication up until this point.

Only the aforementioned notification about upstream node server not responding is present in logs. What is more, **socket.io server set up without nginx proxy behaves in exactly the same fashion**.

Profiling of the application function calls proved inconclusive: 90% of the time application spends idle. It also only happens to specific users only, and seems to persist (they never do achieve connection, whether they refresh page that tries to establish it or not).

**Comment by dgtlmoon** [comment]
Be sure to set the various `proxy_*_timeout`'s as well as `proxy_set_header Connection "";`

https://stackoverflow.com/questions/24453388/nginx-reverse-proxy-causing-504-gateway-timeout

Does this help? (Note: setting timeouts is not the solution but it should be set anyway)

**Comment by MarkAdell** [comment]
@Steveb-p
I'm currently experimenting the same issue, have you figured out what's wrong?

**Comment by Steveb-p** [comment]
@MarkAdell unfortunately no. I haven't been using socket.io too much recently, however my application that does use it currently is "stable" (I don't have reports about clients not being able to connect).

I don't remember if I've changed the nginx configuration :/

**Comment by jannicars** [comment]
Hello all,

Sorry for not replying to this for a long time. I'm still experiencing this issue with the latest socket.io version. Also I'm experiencing the exact same issue like @Steveb-p described. Some users randomly can't connect to my socket.io instance at all. With literally no error in my logs. I asked them to try another browser and then it worked for them again. This happened so far to Edge and Chrome users. So it's not specific to a browser. But switching the browser helps "fixing" the issue. However, I never encountered this issue myself.

**Comment by darrachequesne** [comment]
For future readers, please see the documentation [here](https://socket.io/docs/v3/using-multiple-nodes/#NginX-configuration).

Closed due to inactivity, please reopen if needed.
