### ISSUE TITLE
Emitting to rooms fails sometimes after server restarts

### ISSUE THREAD

**Issue by MyMomSaysIAmSpecial** [socketio/socket.io#2941]
### Current behaviour

We have two users, A and B, who chats in a room, if server restarts and users are rejoined to their rooms, sometimes (sometimes!) one (randomly) of users can stop receiving messages to his room despite he joined it.

The fact what user is joined the room is checked with `socket.rooms` before sending a message.

Here is visual representation 

![Image of chatlog](http://i.imgur.com/qTO4x6k.png)

Here we see user A and user B sending each other simple plaint text messages, and at certain moment user at left, stops to receive messages to room he is in, and receives only messages emitted to global scope

From server side sending is as simple as that

```
io.emit('test', message + ' single');
io.to('testroom').emit('chat_message', message + ' room');
```
This situation is not "systematic", you can have this case after first restart, or have not after 15. Who will stop receive messages is not clear too, it can be user A, user B, or both (both case is much more rare)

It doesn't matter server is running as cluster or single instance, and situation is same on 2.0.1 socket version and 1.7.4, socket.io-redis used as adapter, his version doesn't matter too.

Also what i forgot to mention, what this problem exists only if you "connecting" to socket.io via reconnect, if you just reload your page just after server restart everything is perfect

### Steps to reproduce

Just restart socket.io server while user chats

_p.s. i ll try to make a fork of fiddle later_

**Comment by Nerfair** [comment]
### Status update

Tried on clean fork with minimum logic, and on my production server, preliminarily it's because i am calling `redisClient.flushall();` on `SIGINT` like this (_redis used for cache, and i need to clean it after restart_):

```
process.on('SIGINT', function () {
    redisClient.flushall();
    process.exit();
});
```

i ll continue investigating this problem, but looks like it is.

**Comment by Nerfair** [comment]
Preliminary reason is redis flushing on `SIGINT`.
I am using same instance of redis for `socket.io-redis` adapter and for storing chat application cache, and i am flushing it on server restart like this

```
process.on('SIGINT', function () {
    redisClient.flushdb();
    process.exit();
});
```

I made exactly 200 server restarts, and in 100% cases situation wasn't repeated when flushing was commented out, the only thing what bothers me in all this, is why this happens with flushdb (at first it was flushall).

I init redis like this

```
const redis = require('redis');
const redisClient = redis.createClient(
    {
        host: '127.0.0.1',
        port: 6379,
        password: 'password'
    }
);
```

and using it with `socket.io-redis` adapter like this

```
io.adapter(
    require('socket.io-redis')(
        {
            pubClient: redis.createClient(
                {
                    host: '127.0.0.1',
                    port: 6379,
                    password: 'password'
                }
            ),
            subClient: redis.createClient(
                {
                    host: '127.0.0.1',
                    port: 6379,
                    password: 'password'
                }
            )
        }
    )
);
```

so logically flushdb should not have been affected adapter databases, but it does.
Tomorrow i ll test with separate redis instances and maybe with another redis package

Sadly i couldn't reproduce this situation on fiddle fork, probably project is too small and there is lack of redis based logic (my production application relies on redis heavily)

**Comment by wisniewski94** [comment]
I don't think this problem is related to database or any other module at all. I think problem is in socket.io. In my app when users are in room A chatting and server restarts, their socket.id gets messed up in some way. Socket A, can send and receive messages while socket B can send (only to server, not to other users) but cannot receive messages.

In fact there are multiple problems related to reconnection and socket.id. 

These bugs do not appear when before reconnection everyone closes tab or browser.

**Comment by jflebeau** [comment]
@MyMomSaysIAmSpecial how do you manage the case where your server die without a SIGINT ?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
