### ISSUE TITLE
0.9.18 potentially broken legacy apps

### ISSUE THREAD

**Issue by LeoK80** [socketio/socket.io#2942]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Application with Socket-io doesn't start and logs error.

### Steps to reproduce (if the current behaviour is a bug)
build an old nodejs project that utilises socket-io and try run it.
 
**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
startup and run the app with socket-io

### Setup
- OS: linux ubuntu LTS 14.04
- browser: -
- socket.io version: 0.9.18

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
We're having a legacy app based on an older nodejs and socketio version that won't start due to Eventemitter not being there.
package.json ->
nodejs version 0.10.x
socket-io version 0.9.x

ERR /stub_app/node_modules/socket.io/lib/socket.js:339
ERR Socket.prototype.$emit = EventEmitter.prototype.emit;
ERR                                                ^
ERR TypeError: Cannot read property 'emit' of undefined
ERR     at Object.<anonymous> (/stub_app/node_modules/socket.io/lib/socket.js:339:48)
ERR     at Module._compile (module.js:456:26)
ERR     at Object.Module._extensions..js (module.js:474:10)
ERR     at Module.load (module.js:356:32)
ERR     at Function.Module._load (module.js:312:12)
ERR     at Module.require (module.js:364:17)
ERR     at require (module.js:380:17)
ERR     at Object.<anonymous> (/stub_app/node_modules/socket.io/lib/manager.js:20:14)
ERR     at Module._compile (module.js:456:26)
ERR     at Object.Module._extensions..js (module.js:474:10)

We're currently 'fixing' this by adjusting the socket-io version back to 0.9.17 in our package.json, just thought you should be aware for anyone using outdated legacy nodejs apps that it affects more than just Nodejs 7.x  apps.

**Comment by darrachequesne** [comment]
Well, it has been broken by https://github.com/socketio/socket.io/commit/9ad1fd2771d641d17601ac7817c93dd63f3eec63 (https://github.com/socketio/socket.io/pull/2790). I guess we should use `require('events').EventEmitter` instead (https://github.com/nodejs/node/blob/v7.10.0/lib/events.js#L16).

**Comment by heyZeus** [comment]
Seeing a similar error with node version `v0.10.35` legacy application.

```
.../node_modules/lineman/node_modules/testem/node_modules/socket.io/lib/socket.js:339
Socket.prototype.$emit = EventEmitter.prototype.emit;
                                               ^
TypeError: Cannot read property 'emit' of undefined
    at Object.<anonymous> (.../node_modules/lineman/node_modules/testem/node_modules/socket.io/lib/socket.js:339:48)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (.../node_modules/lineman/node_modules/testem/node_modules/socket.io/lib/manager.js:20:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by arvindsure** [comment]
HI @darrachequesne I could see the similar issue which reported by @LeoK80 @heyZeus .

Can you help us to provide the fix for it, Also let us know if there is any work around for this issue.

we are using the versions in our application.
 
node: v0.10.32 (npm v1.4.28)

**Error Log:**

`/src/node_modules/express.io/node_modules/socket.io/lib/socket.js:339
Socket.prototype.$emit = EventEmitter.prototype.emit;
                                               ^
TypeError: Cannot read property 'emit' of undefined
    at Object.<anonymous> (/src/node_modules/express.io/node_modules/socket.io/lib/socket.js:339:48)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/src/node_modules/express.io/node_modules/socket.io/lib/manager.js:20:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
15 May 20:37:04 - [nodemon] app crashed - waiting for file changes before starting...
^C15 May 20:37:14 - [nodemon] exiting`


We are having the prod deployment over the weekend, due to this we couldn't able to access the application, we will really appreciate your help on this.

Regards,
Aravind Sure

**Comment by heyZeus** [comment]
I just locked down version `"socket.io": "0.9.17"` and that worked around the issue in version `0.9.18`.

**Comment by darrachequesne** [comment]
Should be fixed by e4d61b1be65ac3313a85da111a46777aa8d4aae3 (released as `0.9.18`)

**Comment by arvindsure** [comment]
@darrachequesne thanks for the quick fix, i have verified the change and it looks great.

regards,
Aravind Sure

**Comment by LeoK80** [comment]
thanks for the quick action!
