### ISSUE TITLE
When did 2.0 happen?

### ISSUE THREAD

**Issue by franciscop** [socketio/socket.io#2946]
## You want to:

* [ ] report a *bug*
* [x] request a *feature*

When did 2.0 happen? Is it stable? I cannot see neither in the homepage nor in the repository information about breaking changes or transition paths. What broke that was warrant a major bump?

I am also invested on 1.0 as I'm preparing to release [`server`](https://serverjs.io/) which relies on socket.io so I'd love to know these changes in the same way that there was a transition guide from 0.9 to 1.x. If there are no breaking changes I think the homepage or repo would be a good place to say so for people who worry (like myself).

PS, I really love socket.io, great work!

**Comment by darrachequesne** [comment]
Please check https://github.com/socketio/socket.io/releases/tag/2.0.0

**Comment by franciscop** [comment]
Ah I searched and found the History as well, but I mean that some sort of public announcement would also be nice in either the homepage, documentation or Github's README

**Comment by darrachequesne** [comment]
Well, I'm open to suggestions!

What has already been done:
- an update to the [homepage](https://socket.io/)
- a [blog post](https://socket.io/blog/socket-io-2-0-0/)
- a [release note](https://github.com/socketio/socket.io/releases/tag/2.0.0)
- and a twitter [post](https://twitter.com/darrachequesne/status/861835308496715776)

**Comment by tagyoureit** [comment]
Hi, is there anything that needs to happen in order to upgrade 1.x to 2.0?  I haven't seen any notes on upgrading other than 0.9.  Is it just drop/replace?

**Comment by darrachequesne** [comment]
@tagyoureit besides upgrading your nodejs if you are still running 0.10/0.12 versions, I don't see anything particular to do.

**Comment by drcmda** [comment]
@darrachequesne is uws in there by default meaning we don't have to track it or add it somewhere? And is it still recommended to add bufferutils + utf8-validate? And at which versions, 2.x.x, or latest?
