### ISSUE TITLE
2.0.1 socket.io/examples/chat : Why the chat/package.json has no socket.io dependency ? Chat Demo from socket.io-master

### ISSUE THREAD

**Issue by christalk** [socketio/socket.io#2950]
Hello,

I'm not talking about "Get Started: Chat application"  
but about the socket.io-master example Chat Demo 2.0.1 in socket.io/examples/chat 

I dowloaded all https://github.com/socketio/socket.io, and ran the all commands.about "chat example"
$ cd socket.io             (socket.io-master)
$ npm install
$ cd examples/chat
$ npm install
$ npm start

And the chat example works.

I would like to know why the file : 
socket.io-master\examples\chat\package.json 
has no socket.io dependency ?

There is no even socket.io's module  reference in the directory
socket.io-master\examples\chat\node_module

But I can see three references, in the directory socket.io-master/node_modules  
                socket.io-adapter
                socket.io-client
                socket.io-parser

But I don't know ho it works. There is something with the parents directories.

See : if I try to copy the chat directory in another place, it doesn't work.
Error: Cannot find module '../..'

Chris

**Comment by darrachequesne** [comment]
The chat example indeed depends on the parent package.

In order to make it autonomous, you'll have to change to line [here](https://github.com/socketio/socket.io/blob/master/examples/chat/index.js#L5) to `var io = require('socket.io')(server);` (and add `socket.io` as dependency, as you suggested).

**Comment by christalk** [comment]
Thank you for your reply.
I did indeed see that there was this reference per directory path.

It's strange that we can replace the module name ('socket.io') by a simple path ('../ ..') without naeme.
I mean, without making any reference to the module soket.io, only in writing '../..' and not,  by example with '../../socket.io'

I think that if we modify the example, to make it autonomous, we will have to renew the command "npm install" to be able to include the necessary socket.io modules, in the local directory named examples/chat/node_modules

**Comment by darrachequesne** [comment]
> It's strange that we can replace the module name ('socket.io') by a simple path ('../ ..')

Documentation here: https://nodejs.org/docs/latest/api/modules.html#modules_all_together

> we will have to renew the command "npm install"

Yep that's right!

**Comment by christalk** [comment]
Great
Thank you.

**Comment by darrachequesne** [comment]
You're welcome!
