### ISSUE TITLE
webpack-build-server example doesn't work with 2.0

### ISSUE THREAD

**Issue by haschu** [socketio/socket.io#2951]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behavior
Since version 2.0 the [webpack-build-server example](https://github.com/socketio/socket.io/tree/master/examples/webpack-build-server) doesn't work anymore. Instead, the following error will be thrown: `ERROR in ./~/socket.io/lib/index.js
Module build failed: Error: tried to statically call undefined as a function`

The example works fine for 1.7.4 though.

### Steps to reproduce (if the current behaviour is a bug)
Go into the `example/webpack-build-server` directory and change the version to >= 2.0 in `package.json`, then follow the instructions. 
What I figured out is, that if you remove `transform-loader` from `webpack.config.js`, the error is similar to #2943.

**Comment by darrachequesne** [comment]
I updated the example, could you please check it? It seems the client serving was the issue, it can be disabled with `serveClient: false`.

**Comment by haschu** [comment]
Thanks @darrachequesne, this works now!
