### ISSUE TITLE
Broken changes in ie8

### ISSUE THREAD

**Issue by tormozz48** [socketio/socket.io#2952]
Hello.

As you know socket.io is a dependency of [karma](https://github.com/karma-runner/karma) test unit framework.

And I come here from some issue with unit-test on my project.
I found a [commit](https://github.com/socketio/socket.io/commit/3c98130f15a912307a7362e7dda38c4670b30042)
in socket.io package  that breaks work in ie8 browser

Here you can see row of code that has broken changes:
```js
clientSource = read(require.resolve('socket.io-client/dist/socket.io.min.js'), 'utf-8')
```
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

IE8 browser does not launch from karma test unit framework

### Expected behaviour

IE8 browser should work properly as other browsers

### Setup
- OS: windows
- browser: ie8
- socket.io version: 1.7.0 and higher (1.6.0 and lower is working fine)

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

My version is that minified code from `socket.io-client` dependency does not properly supported by ie8 browser and it fails.

**Comment by tormozz48** [comment]
I will close it due to https://github.com/socketio/socket.io-client/issues/1063

**Comment by darrachequesne** [comment]
@tormozz48 it should be fixed in 2.x version (related to uglifyJS and `screw_ie8` option)

Related: https://github.com/socketio/socket.io-client/pull/1042
