### ISSUE TITLE
single socket connection for multipurposes

### ISSUE THREAD

**Issue by zishanj** [socketio/socket.io#2953]
I am using socket in mobile app with different namespaces for chat, slide sharing which is used by 1000 of students. Is it safe to use single socket server for chat and slide? I mean will there be any chances of overloading which will degrade the performance of either receiving chat messages or slide shares?

**Comment by darrachequesne** [comment]
As usual, there are lots of parameters to take into account, the number of messages per second, the size of the payloads sent, the hardware, the quality of the network, among (lots of) others...

But high availability usually means multiple endpoints, to handle node failures.
