### ISSUE TITLE
Need latest Typescript definitions files for Socket.io client version?

### ISSUE THREAD

**Issue by rubinchyk** [socketio/socket.io#2954]
Need folder with typescript definitions. Latest typescript definition 1.4.29, but now 2.x.x

### Steps to reproduce (if the current behaviour is a bug)
Try to search typescript definitions

### Expected behaviour
After npm install, need folder typescript, when user can get latest *.d.ts files.

**Comment by haschu** [comment]
I'm also up for this, but this belongs to the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped). There is already a related [issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16619) which you can upvote.

**Comment by darrachequesne** [comment]
As pointed out by @haschu, please open an issue in the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository.

Related: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16619
