### ISSUE TITLE
Is socket.io 2.0 compatible with java client? (Android)

### ISSUE THREAD

**Issue by andresetiawan95** [socketio/socket.io#2955]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

ask compatibility

### Setup
- OS: Android
- browser:
- socket.io version: 2.0.1

I'm upgrading socket.io from 1.7.x to 2.0.x on my server side.
Is 2.0.x version fully compatible with java client right now? Because i'm using socket io for my android apps.

Thanks for the response.

**Comment by darrachequesne** [comment]
It seems it's not compatible yet: https://github.com/socketio/socket.io-client-java/issues/421

**Comment by andresetiawan95** [comment]
thanks!
reverted back to 1.7.4, while waiting on java client to fully support 2.0.x.
I've tested in my android app when I was using 2.0.x. Seems like working. Socket is connected, no issues. But well, reverting back is quite wise option right now :)

**Comment by darrachequesne** [comment]
@andrea11 there was an issue in 1.x version, where a packet could be utf8-encoded twice, I think most client implementations currently try to decode the packet twice (while catching any error in the 2nd decoding) as a workaround.

Related: https://github.com/socketio/engine.io-parser/pull/81

**Comment by csoni111** [comment]
I am facing a similar kind of bug. I have mentioned it here [socketio/socket.io-client-java/430](https://github.com/socketio/socket.io-client-java/issues/430).

**Comment by nkzawa** [comment]
Just released the new version which supports socket.io 2.0 🎉

**Comment by csoni111** [comment]
Thanks @nkzawa for the update
