### ISSUE TITLE
Create documentation on how to upgrade an application to socket.io 2.0.0

### ISSUE THREAD

**Issue by TysonAndre** [socketio/socket.io#2957]
### You want to:

request documentation

### Current behaviour

There is currently no explanation or tutorial of steps to upgrade an application (e.g. mobile app using socket.io) in the following places (or their links):

- https://socket.io/blog/socket-io-2-0-0/#
- https://github.com/socketio/socket.io/releases/tag/2.0.0
- https://socket.io/docs/# (There is a page for "Migrating from 0.9", but not "Migrating from 1.x")

### Expected behaviour

Create documentation in https://socket.io/docs/# , link to it from blog posts and release notes

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

Based on the UTF-8 comment in the changelog, I assume it's incompatible (i.e. 2.0 client won't work with 1.x, nor will 1.x client work with 2.0). **Is that correct?**

A similar question was asked in https://github.com/socketio/socket.io/issues/2946#issuecomment-302847169

Sorry if this already exists, I didn't see any similar issues after a quick search.

**Comment by niallel** [comment]
I agree, I understand there is an issue with unicode, but it would be really useful to know in what situations this will cause failures.

I'm using it with Cordova in an app, so I can't just upgrade the server as many clients will be on 1.x.
However I did a test with the client on 2.0.3 and the server on 1.7.4 and all worked.

Are there examples of what would work and what wouldn't. For example if I'm just using very basic ascii characters will it all work?

**Comment by niallel** [comment]
I've spent the day testing with my apps setup.
Everything has worked, 1.4.5 <--> 2.0.3 (client and server both ways).

When I read the notes for the utf encoding problem I see that it only mentions if you are using polling.
So I imagine if you are using web sockets then it works fine (seems to).
With the other issue #1058, it mentions if you are using the non-default namespace.
So again I imagine if you are using the default namespace it works fine (again seems to).

Would someone be able to confirm if there are any other reasons why there would be problems.

**Comment by jwalton** [comment]
Good comments here: https://github.com/socketio/socket.io/issues/3007#issuecomment-336791836
