### ISSUE TITLE
No compatible version found: socket.io-client@2.0.2

### ISSUE THREAD

**Issue by vishnuchittamuru** [socketio/socket.io#2958]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce 

npm install socket.io

Produces error - 
```
No compatible version found: socket.io-client@~2.0.2
It was specified as a dependency of 'socket.io'
```
But the npm registry for socket.io-client shows the latest version is 2.0.2

**Comment by darrachequesne** [comment]
@vishnuchittamuru I am not able to reproduce. Are you using a custom registry? Which version of `npm` are you using?

**Comment by vishnuchittamuru** [comment]
It was due to a custom registry! Thank You!
