### ISSUE TITLE
socket io  websocket call getting high response time on heroku

### ISSUE THREAD

**Issue by jitchavan** [socketio/socket.io#2959]
We are facing WebSocket handshaking issue with node server on heroku.

> heroku router - - at=info method=GET path="/socket.io/?transport=websocket&sid=jvFOp8W0nyrtZc1eAAA-" host=api.herokuapp.com request_id=e345bd1-1a05-467c-a462-43b18d345d9 fwd="" dyno=web.1 connect=0ms service=39526ms status=101 bytes=129 protocol=https

All websocket call responses always get with a high response time. 
our current setup is
node v5.5.0
socket.io v1.7.3

our client library is https://github.com/socketio/socket.io-client-swift.
we have tried to upgrade socket io to 2.0.1 latest but same issue is there.

**Comment by darrachequesne** [comment]
@jitchavan isn't it because the TCP connection is kept open?

**Comment by jitchavan** [comment]
Not sure on this. can you please explain more on this. below is our socket integration code.

```
'use strict';
var socketio = require('socket.io');
var common = require('./common');
var chat = require('./chat');
module.exports.listen = function(app) {

    var io = socketio.listen(app)
    var numUsers = 0;

    io.on('connection', function(socket) {
        var addedUser = false;

       // when the user disconnects.. perform this
        socket.on('disconnect', function() {
          console.log(">>>disconnect");
        });

        // when the client emits 'newuser', we broadcast it to others
        socket.on('newuser', function() {
            socket.broadcast.emit('newuser', {
                uuid: socket.uuid
            });
        });

        // when the client emits 'userupdate', we broadcast it to others
        socket.on('userupdate', function() {
            socket.broadcast.emit('userupdate', {
                uuid: socket.uuid
            });
        });

        socket.on('subscribe', function(data) {
            socket.join(data.roomId);
            //after join send pending messages from db (if exist) to userId
            chat.sendMessages(data, socket);
        });

        socket.on('unsubscribe', function(room) {
            socket.leave(room);
        });

        socket.on('send', function(data, callback) {
                socket.broadcast.to(data.roomId).emit('message', data);
        });
       
    });

    return io;
};


```

**Comment by darrachequesne** [comment]
What I meant is that Websocket transport (in your log: `/socket.io/?transport=websocket`) rely on an underlying TCP connection which is kept open during the session. So that could explain your log (the `service=39526ms` part).

Are you able to send events?

**Comment by jitchavan** [comment]
It returns websocket call with 101 protocol transfer but then continue with polling calls only. please refer below image. 

![issue_screenshot](https://user-images.githubusercontent.com/12793102/27030521-39bbc096-4f8a-11e7-905c-317cd46a4879.png)

any chance how we can trace/log tcp connections in heroku?

**Comment by darrachequesne** [comment]
Again, I think the "High response time" is due to the Websocket keeping the underlying TCP connection open. For more details please see https://en.wikipedia.org/wiki/WebSocket and https://tools.ietf.org/html/rfc6455.

**Comment by bitflower** [comment]
Having the same issue.

@darrachequesne this might be cause and nature of sockets, yes. Bit what is the sokution?

**Comment by alessandrocapra** [comment]
Also interested in this, having the same problem with a multiplayer game hosted on Heroku where the data is sent through SocketIO.

**Comment by bitflower** [comment]
Hey guys, the solution is simple (at least in my case): I'm using the add on "LogEntries" and the - by default - alert us with "high response time" mails for requests taking longer than 5s. Therefore just disable this LogEntries rule and you're done. Question is: What if you use other transports in your app like REST and the time out .....

Heroku Support gave me a simliar solution:

"
Hey Matthias,

You can disable this alert if you wish, or I can do it for you? This triggers when service is above 5000ms.

Regards,
"

**Comment by alessandrocapra** [comment]
@bitflower more than just an annoying alert, the problem for me is that the response time between the client (Arduino in my case) and the server is sometimes around half a second, which is quite noticeable in a game. So I would like to know if it's because of Heroku being kinda slow or it's something in my setup that can be improved.

**Comment by darrachequesne** [comment]
@alessandrocapra is the Websocket connection actually established? Or does it keep polling?

It seems Heroku should work properly with Socket.IO : https://devcenter.heroku.com/articles/node-websockets#option-2-socket-io

**Comment by sameernafdey** [comment]
@alessandrocapra Sorry but I don't get it. I see the same problem on my app. Except that my log shows transport=polling with high service times. I did try that add-on named logentries but disabling the email alert doesn't sound like a solution to me. Can you elaborate on your solution please. Thanks.

**Comment by tyh835** [comment]
using `service>5000 AND status != 101` as the Pattern rule for LogEntries seem to work

**Comment by darrachequesne** [comment]
For future readers: the high response time is expected because the WebSocket connection (and the underlying TCP connection) is kept open for the duration of the session.

Documentation: https://socket.io/docs/v3/how-it-works/
