### ISSUE TITLE
Problem with emit to specific room

### ISSUE THREAD

**Issue by amitrev** [socketio/socket.io#2965]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [ ] report a *bug*
* [ ] request a *feature*

### Current behaviour

I use nodejs for server and angular4 for cleint. 

Server code:
```
app.io = require('socket.io')();
...
app.io.on('connection', function (socket) {
  socket.on('join', function(data) {
    socket.join(data.ch);
  });
});
```
Client code:
```
this.io.emit('join', {ch: 'channel#2'});
this.io.emit('join', {ch: "event#180"});
....

this.zone.run(() => {
 this.io.on('newMessage', (data) => {                
  console.log(data);
  ...
 });
});
```

If I use `req.app.io.in('event#180').emit('newMessage', message)` noting happened, but If I use `req.app.io.emit('newMessage', newMsg)` everythig works fine.

My question is how to emit message from nodejs to all users in specific room? What this code not working?

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS: Kubuntu 16.04
- browser: Firefox, Chromium
- socket.io version: 2.0.1

**Comment by nkCoding** [comment]
I ran into this issue too. On the server side, `emit()` after `to()` is not working. (`io.emit()` works as expected.)

- socket.io 2.0.2 and 2.0.3
- node 8.1
- using a node client written with socket.io-client module for testing

**Comment by darrachequesne** [comment]
@amitrev I'm not able to reproduce (fiddle: https://github.com/darrachequesne/socket.io-fiddle/tree/issues-2965). Did you find anything?

**Comment by kinsi55** [comment]
@darrachequesne i seem to be getting the same problem currently and have no idea whats up. Socket.io 2.0.3, node LTS, chrome. Doing socket.emit works fine, doing io.to(someRoom).emit just doesnt emit anything.

```
console.log(ioSock.sockets.adapter.rooms); //room is listed
console.log(ioSock.sockets.adapter.rooms[someVar]); //room is found

ioSock.to(someVar).emit("someMessage"); //No error, no message emitted
```

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
