### ISSUE TITLE
Problem after updating from 2.0.2 to 2.0.3 with middleware

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io#2971]
This error occurred the first time after updating from 2.0.2 to 2.0.3 - I really can't figure it out right now. 

```
/data/project/app/node_modules/on-headers/index.js:25
	throw new TypeError('argument res is required')
	^

TypeError: argument res is required
	at onHeaders (/data/project/app/node_modules/on-headers/index.js:25:11)
	at session (/data/project/app/node_modules/express-session/index.js:219:5)
	at Array.<anonymous> (/data/project/app/modules/webserver.js:41:5)
	at run (/data/project/app/node_modules/socket.io/lib/namespace.js:123:11)
	at Namespace.run (/data/project/app/node_modules/socket.io/lib/namespace.js:135:3)
	at Namespace.add (/data/project/app/node_modules/socket.io/lib/namespace.js:163:8)
	at Client.connect (/data/project/app/node_modules/socket.io/lib/client.js:76:20)
	at Server.onconnection (/data/project/app/node_modules/socket.io/lib/index.js:398:10)
	at emitOne (events.js:115:13)
	at Server.emit (events.js:210:7)
error: Forever detected script exited with code: 1
error: Script restart attempt #63
```

```
const session = require('express-session');
[..]
const httpsServer = https.createServer(credentials, app).listen(config.server.port);
const io = require('socket.io')(httpsServer);

var sessionMiddleware = session({
    store: new RedisStore({}),
    secret: 'MYSECRET',
    resave: false,
    saveUninitialized: true
});

io.use(function (socket, next) {
    sessionMiddleware(socket.request, socket.request.res, next); //(/data/project/app/modules/webserver.js:41:5)
});
```

**Comment by darrachequesne** [comment]
@Gindu as usual, could you please provide a way to reproduce?

Fiddle here: https://github.com/darrachequesne/socket.io-fiddle/commits/issues-2971

**Comment by Gindu** [comment]
Only happening once (3hours after updating to 2.0.3 on live site) - reverting directly to 2.0.2.

On dev site i can't even reproduce it. So it will be hard to do this in a fiddle.

As of the error the "socket.request.res" was probably undefined/null ? 

```
io.use(function (socket, next) {
    console.log("#1: " + socket.request);
    console.log("#2: " + socket.request.res);

    if(!socket.request.res) {
        console.log("#3: it happend again!");
        return next();
   }

    sessionMiddleware(socket.request, socket.request.res, next);
});
```

would this work without crashing the live site?

**Comment by ashnamuh** [comment]
I have the same issue

**Comment by ToddAlvord** [comment]
I found that this works.
`sessionMiddleware( socket.request, {}, next );`   
  
You will have access to your session via `socket.request.session`. The res part is used to notify the session handler to check if it should save the session data or not after a request has completed. I never could get session data to save automatically with socket.io, even in v1. If you need to make changes to your session in a socket.io connection you can use `socket.request.session.save()`. Basically remove the res part as it wasn't being used anyways by socket.io. At least not in a way that seems to have any affect.

**Comment by Gindu** [comment]
I found the issue for the crash. On polling socket.request.res is find. On Websocket it's undefined.

I have already swapped to  express-socket.io-session module. This working without any issue

**Comment by evancarter-iex** [comment]
@darrachequesne Any possibility on getting a fix on this? We are seeing the same issue

**Comment by jsieler** [comment]
2.0.4 same issue.

**Comment by knoxcard** [comment]
@ToddAlvord - Todd, you're a lifesaver for that one!

**Comment by akontsevich** [comment]
Thanks, @ghost! Will try to revert to `express-socket.io-session` module as well. `sessionMiddleware` worked fine for me
```
io.use(function(socket, next) {
    sessionMiddleware(socket.request, socket.request.res, next);
});
```
with web `socket.io-client` <=> `socket.io` node.js server until I added `socket.io-client-cpp` application to the chain - crashed on `socket.io-client-cpp` connection with above error:
> TypeError:  argument res is required

**Comment by dimified** [comment]
Thanks! Works for me.

**Comment by darrachequesne** [comment]
For future readers, the documentation was added here: https://socket.io/docs/v3/middlewares/#Compatibility-with-Express-middleware
