### ISSUE TITLE
A socket cannot emit to itself

### ISSUE THREAD

**Issue by anestv** [socketio/socket.io#2972]
### You want to:
* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Emits sent using `socket.to(socket.id).emit( ... )` are not sent.

I have pasted the output of running the fiddle with `DEGUG=*`
```
connect XtxCnJ-60yZ9gMZKAAAA                                                                                                                                                                                   
  socket.io-parser encoding packet {"type":2,"data":["hello","world"],"nsp":"/"} +7s                                                                                                                           
  socket.io-parser encoded {"type":2,"data":["hello","world"],"nsp":"/"} as 2["hello","world"] +0ms                                                                                                            
  socket.io:client writing packet {"type":2,"data":["hello","user XtxCnJ-60yZ9gMZKAAAA"],"nsp":"/"} +10ms                                                                                                      
  socket.io-parser encoding packet {"type":2,"data":["hello","user XtxCnJ-60yZ9gMZKAAAA"],"nsp":"/"} +2ms                                                                                                      
  socket.io-parser encoded {"type":2,"data":["hello","user XtxCnJ-60yZ9gMZKAAAA"],"nsp":"/"} as 2["hello","user XtxCnJ-60yZ9gMZKAAAA"] +0ms                                                                    
  engine:socket sending packet "message" (2["hello","user XtxCnJ-60yZ9gMZKAAAA"]) +35ms                                                                                                                        
```

### Steps to reproduce (if the current behaviour is a bug)
See the following [fiddle](https://github.com/anestv/socket.io-fiddle/commit/7fb7ccd341f2426a729b8e462340064117b05754)

Basically all you do is `socket.to(socket.id).emit('hello', 'world');`

### Expected behaviour
It should emit to the current socket.

### Setup
- socket.io version: 2.0.3

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
I think what causes this bug is [line 171](https://github.com/socketio/socket.io/blob/2.0.3/lib/socket.js#L171) at socket.js. A solution would be to not add the socket's id to the `except` array when the only recipient is that socket.

Also, using `io.to(socket.id).emit('hello', 'world');` works as expected and does not cause this bug.

**Comment by darrachequesne** [comment]
@anestv yep, that's expected: `socket.to(<room>).emit('hello', 'world');` is meant to send to anyone in the `room` but the sender, so in that particular case the message is not sent.

You can simply use `socket.emit('hello', 'world');`

**Comment by anestv** [comment]
Yes, but that would emit to everyone. I want to send it only to that socket.

**Comment by darrachequesne** [comment]
I think you're confusing `io.emit`, which broadcasts to everyone in the namespace, and `socket.emit`, which only sends to the given socket. Or am I missing something?

Please see https://github.com/socketio/socket.io/blob/master/docs/emit.md.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by JefferyHus** [comment]
`socket.emit` does not work at all with me it keeps crashing and the error is not even clear:

```bash
events.js:142
      throw err;
      ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (The link is not correct please ma
ke sure to use the correct link sent to you.)
    at Socket.emit (events.js:140:19)
    at Socket.emit (C:\wamp64\www\instacraft\telemedicine\node_modules\socket.io
\lib\socket.js:141:10)
    at Socket.<anonymous> (C:\wamp64\www\instacraft\telemedicine\server.js:30:11
)
    at Socket.emit (events.js:159:13)
    at C:\wamp64\www\instacraft\telemedicine\node_modules\socket.io\lib\socket.j
s:527:12
    at process._tickCallback (internal/process/next_tick.js:150:11)
```
