### ISSUE TITLE
can`t disconnect client from namespace.

### ISSUE THREAD

**Issue by box3x4** [socketio/socket.io#2974]
Hi! I have an app with lots of different namespaces that represents different chats. But when a client disconnects and goes back to the namespace, it's like the client has multiple connection to the namespace.  I tried with socket.disconnect(true), but nothing happened. If you guys need some code, just let me know so I can provide. My app is based on the example provided in this github page.
![2017-06-14-151324_1360x768_scrot](https://user-images.githubusercontent.com/11823051/27147681-0dc27fb2-5114-11e7-9cb1-dac15378e21c.png)

**Comment by darrachequesne** [comment]
@box3x4 yes, we will need some code :+1: (or a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue).

**Comment by box3x4** [comment]
this is the same code thats on the chat demo. the only difference is the namespace part, which i'm calling on my app.js file, and it's working fine.

i tried to put the _socket.disconnect(true)_ in a lot of parts, but none worked.

the server part: http://piratepad.net/1gaUFEon4v

the client part: http://piratepad.net/wT2UNmKrTy

the namespace split part on the client is working fine too. the problem is that i cant disconnect

**Comment by box3x4** [comment]
i managed to fix this problem. the problem was not the front-end neither the websocket. the problem was that the listeners from previous websocket connections were remaining active, so 1 websocket was firing multiple events. i fixed this by using
`socket.removeAllListeners()`
on the server-side (handler.js).
