### ISSUE TITLE
Socket disconnect race condition leads to orphaned HTTP connections and stop() callback not running

### ISSUE THREAD

**Issue by jamesshore** [socketio/socket.io#2975]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

When connecting to a Socket.IO server, if the server is shut down using `httpServer.stop()` (not `ioServer.stop()`) immediately after connecting and disconnecting a Socket.IO connection, Socket.IO doesn't close all of its connections. The `httpServer.stop()` callback never fires.

Order of operations:

1. Client initiates connection to server.
2. Client disconnects connection. Socket IO creates several HTTP connections to cause the Socket.IO connection to be closed.
3. Server `disconnect` event fires.
4. Server immediately runs `httpServer.close()`.
5. **Race condition** Socket.IO never cleans up the HTTP connections it created in step 2. The `httpServer.close()` callback doesn't run.
6. Eventually, the orphaned connections time out and the callback is executed.

There are two workarounds for this issue:

* Adding a timeout after step 3, before running `httpServer.close()` gives Socket.IO enough time to clean up its connections. 
* Running Socket.IO's `close()` rather than the `http` package's `close()` causes Socket.IO to clean up its connections. This is the best workaround.

### Steps to reproduce (if the current behaviour is a bug)

Run the following Node.js code:

```javascript
(function() {
	"use strict";

	var clientIo = require("socket.io-client");
	var http = require("http");
	var io = require("socket.io");

	var httpServer;
	var ioServer;

	var PORT = 5020;

	startServer(function() {
		console.log("SERVER STARTED");

		var connections = {};
		logAndTrackServerConnections(connections);
		logHttpConnections();

		var serverSocket;
		ioServer.once("connect", function(socket) {
			console.log("** stored server socket", socket.id);
			serverSocket = socket;
		});

		console.log("** connecting client");
		var client = clientIo("http://localhost:" + PORT);
		logClientConnections(client);

		client.once("connect", function() {
			console.log("** disconnecting client");
			client.once("disconnect", function() {
				console.log("** waiting for server to disconnect");
				serverSocket.once("disconnect", function() {

					// console.log("** waiting to stop server");    // uncommenting this timeout prevents hang
					// setTimeout(function() {
						stopServer(function() {
							console.log("** end of test, Node.js should now exit")
						});
					// }, 500);
				});
			});
			client.disconnect();
		});
	});

	function logAndTrackServerConnections(connections) {
		ioServer.on("connect", function(socket) {
			var key = socket.id;
			console.log("SERVER CONNECTED", key);
			connections[key] = socket;
			socket.on("disconnect", function() {
				console.log("SERVER DISCONNECTED", key);
				delete connections[key];
			});
		});
	}

	function logHttpConnections() {
		httpServer.on('connection', function(socket) {
			var id = socket.remoteAddress + ':' + socket.remotePort;
			console.log("HTTP CONNECT", id);
			socket.on("close", function() {
				console.log("HTTP DISCONNECT", id);
			});
		});
	}

	function logClientConnections(socket) {
		var id;
		socket.on("connect", function() {
			id = socket.id;
			console.log("CLIENT CONNECTED", id);
		});
		socket.on("disconnect", function() {
			console.log("CLIENT DISCONNECTED", id);
		});
	}

	function startServer(callback) {
		console.log("** starting server");
		httpServer = http.createServer();
		ioServer = io(httpServer);
		httpServer.listen(PORT, callback);
	};

	function stopServer(callback) {
		console.log("** stopping server");

		httpServer.close(function() {   // using ioServer.close() instead of httpServer.close() prevents hang
			console.log("SERVER CLOSED");
			callback();
		});
	};

}());
```

Example output:
```
** starting server
SERVER STARTED
** connecting client
HTTP CONNECT ::ffff:127.0.0.1:57798
SERVER CONNECTED uvnZrgajc8_W1X5QAAAA
** stored server socket uvnZrgajc8_W1X5QAAAA
HTTP DISCONNECT ::ffff:127.0.0.1:57798
CLIENT CONNECTED uvnZrgajc8_W1X5QAAAA
** disconnecting client
CLIENT DISCONNECTED uvnZrgajc8_W1X5QAAAA
** waiting for server to disconnect
HTTP CONNECT ::ffff:127.0.0.1:57799
HTTP CONNECT ::ffff:127.0.0.1:57800
HTTP CONNECT ::ffff:127.0.0.1:57801
SERVER DISCONNECTED uvnZrgajc8_W1X5QAAAA
** stopping server
HTTP DISCONNECT ::ffff:127.0.0.1:57800
HTTP DISCONNECT ::ffff:127.0.0.1:57799
~~~ (long delay) ~~~
SERVER CLOSED
** end of test, Node.js should now exit
HTTP DISCONNECT ::ffff:127.0.0.1:57801
```

### Expected behaviour

`httpServer.stop()` should work the same as `ioServer.stop()`. Specifically, the connections should be cleaned up and the callback called immediately, with no delay.

### Setup
- OS: MacOS 10.11.6
- browser: n/a
- Node.js: v7.10.0
- socket.io version: 2.0.1

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

Although this is arguably a misuse of Socket.IO--specifically, the code should run `ioServer.stop()`, not `httpServer.stop()`--the fact that it works when a timeout is added means that there is probably some sort of race condition in the current Socket.IO code that handles HTTP server shutdown.

**Comment by darrachequesne** [comment]
For future readers: `io.close()` is definitely the best way to stop a Socket.IO server and close all existing connections.

I've updated the documentation here: https://socket.io/docs/v4/server-api/#serverclosecallback
