### ISSUE TITLE
Objects passed to emit are not serialized / deserialized

### ISSUE THREAD

**Issue by leobudima** [socketio/socket.io#2980]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

If I call .emit() with an object payload, I previously (with pre 2.0.0), received it properly as an object on the receiving end. 

Now, seems like due to use of splice at: namespace.js, line 215, which only makes a shallow copy of the arguments, I don't receive the objects properly any more. Example below.

### Steps to reproduce (if the current behaviour is a bug)

`
emit('partner', {
			verb: 'created',
			id: doc._id,
			data: { 
                              propertyA: 'something',
                              propertyB: 'somethingElse'
                       }
		}
`

What I get on the receiving end is 

`data: [ 'partner', [Object] ],...`

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour

For socket.io to serialize / deserialize data as needed, without needing to do it manually when sending and receiving. Maybe I'm missing something? Thanks!

### Setup
- socket.io version: 2.0.3

**Comment by oeduardoal** [comment]
Sure

**Comment by leobudima** [comment]
Issue seems to be in socket.io-redis...
