### ISSUE TITLE
Can Socket.io client connect  WSS Server?

### ISSUE THREAD

**Issue by Elliot9** [socketio/socket.io#2981]
My Question is can i use socket.io build a winsform  and connect wss server 
like "WSS://123.456:8551"?

**Comment by LordMajestros** [comment]
Although socket.io supports websockets internally as one of several transports, Socket.io clients cannot directly connect to a web socket server. Socket.io clients can only connect to a socket.io server.

**Comment by Elliot9** [comment]
thanks for  response -@LordMajestros 
i been search for long time ,and i found this one [EngineIoClientDotNet](https://github.com/Quobject/EngineIoClientDotNet)
but i not sure it's work,cos i don't know how to build the Server,...Anyway ,.thanks again

**Comment by sirudog** [comment]
I guess by "Server" you mean the test server from the project. (https://github.com/Quobject/EngineIoClientDotNet/tree/master/TestServer) It is written in javascript (node.js), so to run it, you have to install node.js, then just type: 
`node server.js`

**Comment by Elliot9** [comment]
thanks for response- @sirudog 
You've got a big help.
and it's work
