### ISSUE TITLE
Remote address (IP) is always undefined

### ISSUE THREAD

**Issue by kirick13** [socketio/socket.io#2982]
After upgrading socket.io from 1.x.x to 2.0.3 I can't get client's IP address — it's always `undefined`.

Test environment:
Ubuntu 14.04.5 LTS
Node.js 8.1.2
Socket.io 2.0.3

Server:
```js
require('socket.io')(8888).on('connection', socket => {
    console.log('socket.client.conn.remoteAddress', socket.client.conn.remoteAddress);
    console.log('socket.request.connection.remoteAddress', socket.request.connection.remoteAddress);
    console.log('socket.handshake.address', socket.handshake.address);
});
```

Client:
```html
<script src="http://192.168.13.13:8888/socket.io/socket.io.js"></script>
<script>
    var socket = io('http://192.168.13.13:8888', { transports: [ 'websocket' ] });
    socket.on('connect', function(){
        console.log('connected');
    });
</script>
```

Aaaaand it's gone.
```
daniil@ubuntu:/var/srv/node-test# node server.js
socket.client.conn.remoteAddress undefined
socket.request.connection.remoteAddress undefined
socket.handshake.address undefined
```

When I remove `{ transports: [ 'websocket' ] }` from client's code, I got this:
```
socket.client.conn.remoteAddress ::ffff:192.168.13.12
socket.request.connection.remoteAddress ::ffff:192.168.13.12
socket.handshake.address ::ffff:192.168.13.12
```

Socket.io 1.7.4 works fine. Socket.io >=2.0.1 is not.

**Comment by ashleybrener** [comment]
@kirick13 I am experiencing the exact same behavior with { transports: [ 'websocket' ] }

**Comment by xPaw** [comment]
We also experience this issue on 2.x and are unable to upgrade for now.

https://github.com/thelounge/lounge/pull/1143
https://travis-ci.org/thelounge/lounge/builds/241839980

**Comment by burstpay** [comment]
Was this fixed? As i'm having the same issue.

**Comment by unknown0perator** [comment]
@burstpay https://stackoverflow.com/a/45925740/2976093

**Comment by Serveurperso** [comment]
Same probleme here, always undefined... major issue !

**Comment by darrachequesne** [comment]
Could you please try with engine.io [v3.1.3](https://github.com/socketio/engine.io/releases/tag/3.1.3)?

**Comment by xPaw** [comment]
@darrachequesne How do you access that `remoteAddress` in context of socket.io itself? `socket.remoteAddress` is undefined in `connect` callback.

**Comment by darrachequesne** [comment]
@xPaw it should be `socket.handshake.address` ([ref](https://github.com/socketio/socket.io/blob/master/docs/API.md#sockethandshake))

**Comment by Serveurperso** [comment]
Sorry, what is the proper way to upgrade my engine.io dependency from 3.1.0 to 3.1.3 ?
(I use socket.io 2.0.3)

**Comment by Serveurperso** [comment]
I installed engine.io inside my own project and it's clean:)
npm install engine.io

Now "socket.handshake.address" work but I get IPv6 header buggy inside my code. I must parse the string.
::ffff:127.0.0.

**Comment by polkovnikov-ph** [comment]
@Serveurperso You can also turn off IPv6 if you `http.listen(port, '0.0.0.0')`. This way your server won't be IPv6-compatible, but also you will have remote addresses in IPv4 format.

**Comment by bsn0w** [comment]
```js
io.on('connection', function(socket){
  const address = socket.handshake.headers["x-forwarded-for"].split(",")[0];
  console.log(address);
});
```

**Comment by funnel20** [comment]
> @Serveurperso You can also turn off IPv6 if you `http.listen(port, '0.0.0.0')`. This way your server won't be IPv6-compatible, but also you will have remote addresses in IPv4 format. Given the fact you were going to convert IPv6 address to IPv4, IPv6 connectivity shouldn't be an issue for you.

@polkovnikov-ph Thanks for this great solution. Is this option somewhere documented?

**Comment by polkovnikov-ph** [comment]
It was a long time ago, but I'm pretty sure I just made a google search with something like "http listen force ipv4" and opened [first link](https://stackoverflow.com/questions/47797322/node-js-server-only-listening-on-ipv6) that lead to stackoverflow.

The issue is not actually related to Node.js. It's [platform-specific](https://github.com/nodejs/node/issues/9390) socket behavior. Listening on `::` meta-address might  or might not listen also on `0.0.0.0`.

**Comment by funnel20** [comment]
Thanks for your prompt response.

**Comment by panpansh** [comment]
```js
if (socket.handshake.address.lastIndexOf(':') > -1) {
    socket.this_is_a_demo = {
        ipv4: socket.handshake.address.slice(socket.handshake.address.lastIndexOf(':') + 1, socket.handshake.address.length),
        ipv6: socket.handshake.address.slice(0, socket.handshake.address.lastIndexOf(':'))
    }
} else {
    socket.this_is_a_demo = {
        ipv4: socket.handshake.address
    }
}
console.log(socket.this_is_a_demo.ipv4);
```
