### ISSUE TITLE
Why you gays still use ES3-ES5?

### ISSUE THREAD

**Issue by maicss** [socketio/socket.io#2983]
This module is faced node server, right?

It's like node from `0.11` turns use ES6

**Comment by maicss** [comment]
And many many `==`, why not `===`?

**Comment by joannesalfa** [comment]
== it's used to compare between same number and same string that returns true, otherwise using === returns false due to identical data type.

**Comment by maicss** [comment]
@joannesalfa I know that, but why should we need this?

**Comment by jakehamilton** [comment]
@maicss, this is a massive project used in countless places. A rewrite to update syntax would be incredibly costly.

**Comment by darrachequesne** [comment]
@maicss but if you want to contribute, I'll be happy to merge your pull request!

**Comment by maicss** [comment]
@darrachequesne Thanks, but I'm a greener. I want to know why you use ES standards, and as you can see, my English is very bad...Thanks again.
