### ISSUE TITLE
cleanInput function in the chat example

### ISSUE THREAD

**Issue by VincentGau** [socketio/socket.io#2986]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
the cleanInput() function is not working as expected;

```
  // Prevents input from having injected markup
  function cleanInput (input) {
    return $('<div/>').text(input).text();
  }
```
Suppose the input string to be "&lt;a&gt;whatever&lt;/a&gt;", the function returns exactly the same string "&lt;a&gt;whatever&lt;/a&gt;",  Shouldn't it return "whatever" if the purpose it to prevent injected markup? Should it return `$('<div/>').html(input).text()`?

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:
- browser:
- socket.io version:

**Comment by darrachequesne** [comment]
Good catch! Could you please open a pull request?
