### ISSUE TITLE
Socket io doesn't work over 3g, 4g, LTE connection on phonegap

### ISSUE THREAD

**Issue by JairLomas93** [socketio/socket.io#2990]
Hi, I make a chat app using socket io with phonegap, my issue appear when I use the app over 3g, 4g or LTE the socket io doesn't connect but if I connect over wifi works perfectly!, anyone has the same issue?, Thanks community!

**Comment by Twois** [comment]
Are you build your app and installed or just served via webpack? In the second case webpack is't abble to serve js files when you use other than wifi, because you have to be on the same network.

**Comment by JairLomas93** [comment]
Hi Twois, I build my app and installed on android and ios device.

**Comment by bfjfm2** [comment]
@JairLomas93  I am having the unstable issue in 4g and it is working fine only in wifi.

**Comment by Entrecampos** [comment]
I am using ionic to android and I have noticed that disconnect and connects with another socket.io every second ... So is impossible to do socket.on(....) because the socket already changed...

Any suggestions?

**Comment by A-Tokyo** [comment]
We are facing the same issue with react-native.

We also noticed that's it doesn't work on CERTAIN providers. For example it works with Verizon but not T-Mobile

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by A-Tokyo** [comment]
Still happening :/

**Comment by A-Tokyo** [comment]
update: Still happening with v4

**Comment by Goran7777** [comment]
I must set some notification on screens bellow 700px like "Turn off 3G/4G and turn on WI-FI for mobiles".

**Comment by A-Tokyo** [comment]
update: not working on `T-Mobile US` but working on `Vodafone DE`.

**Comment by Goran7777** [comment]
Actually it works,i somehow fix that today,there is no issues anymore with socket.io && mobiles.
