### ISSUE TITLE
Leaving connected room from client

### ISSUE THREAD

**Issue by Nerfair** [socketio/socket.io#2991]
Using socket.io client version [2.0.3](https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.3/socket.io.slim.js), and trying to call

```
socket.leave(room);
```

**from client**, i am getting error `Uncaught TypeError: socket.leave is not a function`, but `socket.join(room)` works like a charm

**Comment by TK-999** [comment]
According to [the documentation](https://socket.io/docs/rooms-and-namespaces/), rooms and namespaces should be managed by the socket.io server, not the client.
