### ISSUE TITLE
1.3.5 socket.io client can be abused to flood socket.io 2.0.3 server

### ISSUE THREAD

**Issue by TK-999** [socketio/socket.io#2993]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
When a socket.io 1.3.5 client is trying to connect to a socket.io 2.0.3 server, the client will endlessly send a large volume of requests in a short time without any form of throttling. While 1.3.5 clients are not compatible with 2.0.3 servers, this problem can still arise if a client still has the old version in their browser cache, or if a client is connected to the server when the server is updated and does not reload the page. It can also be abused for DoS - someone can simply run a 1.3.5 client from their web console and flood the server with a huge amount of requests.

**Note:** 1.3.7 clients still have this issue, 1.4.0 clients do not.
### Steps to reproduce (if the current behaviour is a bug)
A self-contained example with instructions is provided in my [fork](https://github.com/TK-999/socket.io-fiddle) of socket.io-fiddle.

### Expected behaviour
2.0.3 server should properly handle <1.4.0 clients by satisfying their connection requirements so that the server is not flooded.

If the decision is to not fix this problem, please, provide mitigation.
### Setup
- OS: macOS
- browser: Chrome
- socket.io version: 1.3.5 client + 2.0.3 server

**Comment by darrachequesne** [comment]
There is indeed a parsing error with < 1.4.x clients, which prevents them from connecting properly, I'm not sure whether that can be fixed.

You should be able to throttle the connections (or messages) by using a middleware:
```js
io.use((socket, next) => {
  // throttle per ip address for example
});

socket.use((packet, next) => {
  // or per message
});
```

[Reference](https://github.com/socketio/socket.io/blob/master/docs/API.md#namespaceusefn)
