### ISSUE TITLE
Support question - get ephemeral port

### ISSUE THREAD

**Issue by ORESoftware** [socketio/socket.io#2995]
I am looking for a way to start the socket.io server with an ephemeral port. After starting the server, I need to pass the discovered ephemeral port to the socket.io clients.

How can I get an ephemeral port with socket.io server?

thanks!

**Comment by Nibbler999** [comment]
```javascript
var server = require('http').createServer();

server.on('listening', function () {
    console.log('Listening on port', this.address().port);
});

server.listen(0);

var io = require('socket.io')(server);
```

**Comment by the1mills** [comment]
Thanks a ton! That should do nicely.

**Comment by darrachequesne** [comment]
For future readers: please see the documentation [here](https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback).
