### ISSUE TITLE
Ionic iOS Client doesn't receive any messages from socket.io server

### ISSUE THREAD

**Issue by wiadev** [socketio/socket.io#2997]
I've built the ionic v1 app with socket.io.
I have release for both of iOS and Android.
on Android, I received messages from the server correctly but on iOS, it 's not receiving any messages from the server.

It worked an month ago but not working all of sudden.

Can anyone help me?
Thanks

Ionic version: 2.2.3
Cordova: 6.2.0
AngularJS v1.4.14
angular-socket-io v0.7.0

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by adam-enzy** [comment]
Could we re-open this? We are seeing the same issues and it's been tough to track down a good answer
