### ISSUE TITLE
socket.io is crashing over https

### ISSUE THREAD

**Issue by dx9s** [socketio/socket.io#2999]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

```
node: ../src/util-inl.h:196: TypeName* node::Unwrap(v8::Local<v8::Object>) [with TypeName = node::TLSWrap]: Assertion `(object->InternalFieldCount()) > (0)' failed.
Aborted
```

### Steps to reproduce (if the current behaviour is a bug)

I have forked the code here:

https://github.com/dx9s/socket.io-fiddle/tree/issue-2999

**make sure to checkout branch issue-2999**

### Expected behaviour

expect it not to crash like when server is running over http. Instead it crashes with the error listed above.

### Setup
- OS: Distributor ID: Ubuntu
Description: Ubuntu 16.04.2 LTS
Release: 16.04
Codename: xenial
- browser: Firefox 54.0
- socket.io version: 2.0.3

**Comment by dx9s** [comment]
arg.. OS:
lsb_release -a
LSB Version:	security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

**Comment by dx9s** [comment]
This also might be a problem in node .. version I am using is:
$ node --version
v4.2.6
 there probably is a new version. I will try it next.

**Comment by dx9s** [comment]
Updated to latest version of nodejs from nodesource:
$ $ node --version
v8.1.3
 and problem in my fork of socket.io-fiddle seems to work without crashing .. tried my code and solved it. Sorry for the hassle. Hopefully others will find this and learn to update node first!

**Comment by regimantas** [comment]
Same problem to me :(
my version was v4.2.6
after upgrade to v4.2.6
Start Working normal :)
Just Update nodejs :)

**Comment by dx9s** [comment]
@regimantas: Yeah, I figured updated the reference code project (which I have a commit pending now for over a month) that includes testing everything (SSL use - see https://github.com/dx9s/socket.io-fiddle/tree/issue-2999 ) would be a good "reference" update to help avoid people like you and me having same problem.

It boils down to is a problem with the Libraries (socket.io, etc.) or a problem with the runtime (nodejs), hence the reference code SSL addition.

**Comment by darrachequesne** [comment]
SSL example merged here: https://github.com/darrachequesne/socket.io-fiddle/tree/ssl-example (courtesy of @dx9s, thanks!)
