### ISSUE TITLE
io.sockets.emit caused memory leak

### ISSUE THREAD

**Issue by shipunyc** [socketio/socket.io#3000]
io.on('connection', (socket) => {

  setInterval(()=>{
    var someData = generateData();
    io.sockets.emit('data', someData);
  }, 100)

});

The above code will cause memory leak in a few hours (with a few clients connected). I saw a long chain of WriteReq in the heap snapshot.

I believe nodejs cached the WriteReq if the emit was blocked. Because I setInterval to repeat, the chain becomes longer and longer, and eventually crashed the program.

**Comment by owenbonescoregaming** [comment]
Tried using
```javascript
delete this;
```
?

**Comment by ADumaine** [comment]
Not sure I can help but would like to understand the use case. 

setInterval is not repeating.  A new setInterval is being created for each socket that connects so you have multiple timers. That does not seem like it would scale well.

You may want to consider creating one timer that generates the data then emits to all sockets.

**Comment by shipunyc** [comment]
@ADumaine  Thanks. Now I understand how socket.io works better. I think I should move the setInterval out of the scope.
