### ISSUE TITLE
session ID unknown

### ISSUE THREAD

**Issue by CHparis** [socketio/socket.io#3002]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:liunx
- browser:
- socket.io version:2.0.3

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

I am use swift version, use socket.io 2.+,But it often happens 【session id unknown】,socket.io server use Multi process and nginx distribute.

**Comment by wanming** [comment]
Try to use NGINX load balance ip_hash

**Comment by darrachequesne** [comment]
For future readers: please see the documentation [here](https://socket.io/docs/v3/using-multiple-nodes/).
