### ISSUE TITLE
"code":1,"message":"Session ID unknown" - 400 (Bad Request)

### ISSUE THREAD

**Issue by pinkladywithcoco** [socketio/socket.io#3009]
I'm running a single Socket.io server ( 2.0.3 ) .

In the client side i'm trying to allow only **polling** mode.

```
io.connect(url, {
   "transports": ['polling']
})
```
The problem is that polling fails and throws:

`"code":1,"message":"Session ID unknown" `response. And the client get disconnected.

i have tried to place **node-http-proxy** server in front of the socket.io server. So the client connect to node-http-proxy server. This solved the problem, but i don't understand why...

Can someone please explain why this is happening and how to fix it ???

**Comment by pinkladywithcoco** [comment]
THIS HAPPENS ONLY ON **MAC**. TESTED ON **WINDOWS** IT DO NOT HAPPEN THERE...

**Comment by vtellier** [comment]
I run into this issue as well, my server is executed in docker containers behind a load balancer. I assume this happens because the request polling request do not arrive in the same container everytime.

**Comment by zwhGithub** [comment]
How to solve？

**Comment by eduardobc88** [comment]
I had the same problem and my solution was change 'polling' by 'websocket':
`transports: ['websocket']`
of course this only has support for browser with websocket compatibility but you can use both:
`transports: ['polling', 'websocket']`
it's work but you will have same issue for 'polling' connection

**Comment by darrachequesne** [comment]
For future readers: please see the documentation [here](https://socket.io/docs/v3/using-multiple-nodes/).
