### ISSUE TITLE
compress string message in socket.io made me confused

### ISSUE THREAD

**Issue by Rainmen-xia** [socketio/socket.io#3010]
I tried to compressed a long tring when communicate in websocket. but I found it failed .
the compress plugin is pako;

`
        var i = 0;
        var message = [];

        for(;i<1000;i++){
               message.push({
                    tempx: parseInt(Math.random()*100),
                    tempy: parseInt(Math.random()*100),
                    openid: 'fjbdsaf'+parseInt(Math.random()*100)+'sfnj21321312',
                    buff: parseInt(Math.random()*100)
                })
        }

        var string = JSON.stringify(message);

         string     = pako.deflate(string,{to:'string'});

       client.emit('message',string);
`

after compressed ,the length of the string  decreased 90%;
but when I send it by websocket ,the bandwith of network  increased 10%;
I think you have much more knowledgethan me about websocket，can you help me analysis the reason？
thanks a lot！

**Comment by Rainmen-xia** [comment]
hello author？

**Comment by Rainmen-xia** [comment]
any one can help me？

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
