### ISSUE TITLE
Multiple connection with the same ip and port

### ISSUE THREAD

**Issue by joingood** [socketio/socket.io#3012]
### You want to:

* [ ] communication

### Current behaviour

It does not allow me to have connections with ws with the same ip and port, if it connects but when the new connection is connected, the other stops communicating.

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour

I want to open the app in several windows in google with no communication problems

### Setup
- OS: windows
- browser: google
- socket.io version: ^1.7.1

**Comment by madivad** [comment]
The listening port is only used once and that is by the socket.io server. It listens to clients connecting from any source that has thruput to it. Any other tabs, windows or browsers will in fact use their own randomised ports to attempt to connect to (assuming you're using) `http://localhost:3000`. If you're using any other device, it would be `http://{ip-address}:3000`.

If you're trying to run multiple servers on the same IP address with the same port number that will fail, you should get a SocketException (guessing: Socket in use or unavailable, something like that). Just confirm that you're not trying to start several servers as opposed to clients. 

I'm very new to socket.io and have only downloaded it and given it a run today. I had several tabs of chrome, a chromium, Firefox and iOS device all connected for asynchronous communications.

**Comment by joingood** [comment]
If I am connecting so http: // {ip-address}: 3000,i investigated but the connection ws has that problem, that if you open another tab, you lose the communication, not the connection but the communication.

**Comment by madivad** [comment]
I'm not sure about your distinction between connection and communication. You're going to need to provide further information like how you're running it, what versions you have installed, what OS, what browser etc. 

I've just run it again just now and made a screencast, I'll upload it when I get back home. I'd encourage you to do the same and show where you're having the problem and or demonstrate how to reproduce it.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by MaheshGawhane11** [comment]
Anyone got the solution for this issue. I am facing same issue. When one client is communicating and second client is started communication then the first client lose the communication. I want both to talk at a time with server.
