### ISSUE TITLE
[BUG] Server.close() should clear memory

### ISSUE THREAD

**Issue by patrickml** [socketio/socket.io#3015]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
If you close a server it is not clearing the listeners. We can see this is true within the source. https://github.com/socketio/socket.io/blob/master/lib/index.js#L430

This means that if you re-add listeners before starting the server again they are then registered twice and will perform actions twice or as many times as the server is restarted.

### Steps to reproduce (if the current behaviour is a bug)
1. Create a socket.io instance
2. Register .on(connection)
3. Register message listener within .on(connection)
4. call socket.close();
5. Register .on(connection), again
6. reattach to http server
7. emit a message

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
