### ISSUE TITLE
IPv4 and IPv6 clients

### ISSUE THREAD

**Issue by pinkladywithcoco** [socketio/socket.io#3016]
Hi

My home network where my Socket.io server is runing support only **IPv4**.

If **IPv6** client connect to the url of my **IPv4** server... will he be able to connect???

if not what should i do??

**Comment by asbachb** [comment]
That's no question about socket.io it's about ip protocol. You can not access ipv4 with ipv6. The ipv6 client needs a gateway which does NAT64 or something like this or you need to provide a ipv6 server.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
