### ISSUE TITLE
socket.disconnect() in socket.io-client is async but it doesn't have a callback function

### ISSUE THREAD

**Issue by Aweather** [socketio/socket.io#3018]
### You want to:

* [x] request a *feature*

### Current behaviour
If I call "io.disconnect()" from the client's side, the function defined in io.on('disconnect', () => {}) is triggered immediately, and I couldn't find a way to test server behavior (integration test) in jest when a client disconnects.

I was hoping to do something like:
```
test('Connect client 1', (done) => {
    expect(stats.usersOnline).toBe(0);
    console.log(stats);
    client1 = new socketioclient(url);
    client1.on('connect', () => {
      expect(stats.usersOnline).toBe(1);
      console.log(stats);
      done();
    });
  });

```
 ```
 test('Disconnect client 1', (done) => {
    expect(stats.usersOnline).toBe(1);
    client1.on('disconnect', () => {
      expect(stats.usersOnline).toBe(0);
      console.log(stats);
      done();
    });
    client1.disconnect();    
  });

```
Is there any reason this is async but without a ack function?

**Comment by Mathspy** [comment]
Had to deal with the same yesterday actually

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
