### ISSUE TITLE
commit tags misused, or some other problem with History.md?

### ISSUE THREAD

**Issue by sam-github** [socketio/socket.io#3021]
I'm trying to figure out what the breaking changes are in 2.x, but the History isn't helping.

Changelog for https://github.com/socketio/socket.io/blob/master/History.md#200--2017-05-09 shows no semver-major commits, they are all marked `[fix]` (semver-patch) `[feat]` (semver-minor), or other book-keeping categories, so 2.0.0 should be 1.8.0 according to my reading of the History.md.

Why did it go to 2.x? Is one of the commits mislabelled?

**Comment by attritionorg** [comment]
And now the History.md is gone completely...
