### ISSUE TITLE
Why not support standard client api?

### ISSUE THREAD

**Issue by lifubang** [socketio/socket.io#3022]
stackoverflow: https://stackoverflow.com/questions/45433580/why-not-support-standard-client-api 

### I want to:
* [x] report a *bug*

### Current behaviour
```js
<script type="text/javascript">
var socket = new WebSocket('wss://ws.acmcoder.com:3333'); 

socket.onopen = function(event) { 
  socket.send('I am the client and I\'m listening!'); 

  socket.onmessage = function(event) { 
    console.log('Client received a message',event); 
  }; 

  socket.onclose = function(event) { 
    console.log('Client notified socket has closed',event); 
  }; 

  //socket.close() 
};
</script>
```
it displays:  (Opcode -1)
By the way, If run the web socket server with Workman, It works.

### Setup
- OS: Windows 10
- browser: chrome
- socket.io version: 2.0.3

**Comment by darrachequesne** [comment]
Socket.IO is not a WebSocket server. Please see [ws](https://github.com/websockets/ws) instead.

**Comment by lifubang** [comment]
@darrachequesne 
But Socket.IO also provide WebSocket Server. I have found the succussful wss address when the client use socket.io library. But this address can't connet by other client library.
wss://ws.acmcoder.com:3333/socket.io/?EIO=3&transport=websocket&sid=e_M_bEN6KH8mfw9vAAAA
