### ISSUE TITLE
Version 0.9.19 logs deprecation warning "(node:19140) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead."

### ISSUE THREAD

**Issue by HolgerFrank** [socketio/socket.io#3023]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Node.js logs "(node:19140) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead."

### Expected behaviour

No deprecation warning

### Setup
- OS: Windows 10
- browser: node.js
- socket.io version: 0.9.19

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

The deprecation warning is caused by policyfile version 0.0.4. 
There is already a policyfile version 0.0.5 which does not use process.EventEmitter.
Please update the dependency in package.json

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
