### ISSUE TITLE
socket.io-connect not connecting in iphone,tab 

### ISSUE THREAD

**Issue by santoshkumar611** [socketio/socket.io#3027]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS: ios 10.33
- browser: safari
- socket.io version: 2.03

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

we are developing web applications using socket.io. our site working in desktop browsers, Android mobiles but not working in iphone , Tab

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
