### ISSUE TITLE
Socket.io not accessible via domain name

### ISSUE THREAD

**Issue by catalynn21** [socketio/socket.io#3028]
I have a socket.io node js application running on server on port 3001. When I access that socket connection via browser http://ip-adress:3000/socket.io/?EIO=3&transport=polling&t=1502735738006-0 It works perfectly fine.
I have a VPS on vultr with Ubuntu 14.04 x64
And I have a domain jackpotrolldice.com pointing to that server.

When I try to access via browser like  http://jackpotrolldice.com:3000/socket.io/?EIO=3&transport=polling&t=1502735738006-0  then it doesn't work and connection timed out error comes.

As I am new to nodeJS and socket.io. So please guide & help me!Thank you in advance!

**Comment by Jnesselr** [comment]
It looks like port 3000 isn't actually open through your firewall. It looks like you have several ports open, but that isn't one of them. My suggestion is to hide all of this behind an nginx configuration. So reverse proxy https://jackpotrolldice.com/socket.io to 127.0.0.1:3000/socket.io.

**Comment by Lissy93** [comment]
Another potential cause, which gave me a similar issue was upgrading to socket.io V 2.0.0, which isn't backward compatible See the [V2.0.0 release notes for details of what you need to change](https://github.com/socketio/socket.io/releases/tag/2.0.0) 

Should this issue be closed now, as it seems to be sorted?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
