### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 500

### ISSUE THREAD

**Issue by ForsakenHarmony** [socketio/socket.io#3030]
Trying to get socket.io to connect through websockets ( server is behind traefik )

I'm always getting the error in the title

on the server I get  `engine unknown transport "undefined"`

client ver: 2.0.3
server ver: 2.0.3

**Comment by darrachequesne** [comment]
@ForsakenHarmony are the query parameters properly proxied by traefik? I mean, the requests should look like `/socket.io?transport=polling&sid=...`.

**Comment by ForsakenHarmony** [comment]
polling works

**Comment by BeigeHacker** [comment]
Hi, did you manage to resolve your issue? I'm experiencing the same thing

**Comment by ForsakenHarmony** [comment]
I think I just ignored it because polling worked

**Comment by darrachequesne** [comment]
Documentation for Traefik added here: https://socket.io/docs/v3/using-multiple-nodes/#Traefik
