### ISSUE TITLE
receive overwrote result when same events emit concurrently

### ISSUE THREAD

**Issue by mindori** [socketio/socket.io#3034]
### You want to:
* [x] report a *bug*
### Setup
- OS: centos 7
- socket.io version: 1.7.3
- socket.io-client version: 1.7.4
- Node.js version: 6.11.2
### IN DETAIL
When I emit same events almost concurrently(e.g. 5 times), I receive overwrote event result. Why does this happen? My codes are here. 
```
[Client]
// used socket.io-client
function foo(var1, var2) { // foo was multiple times called by external code(at almost same time)
    console.log('send var1:', var1);
    console.log('send var2:', var2);
    socket.emit('foo', var1, var2);
    socket.once('bar', (result1, result2, result3, result4, result5) => {
        console.log('recv result3:', result3);
        console.log('recv result4:', result4);
    });
}

[Server]
// used socket.io
socket.once('foo', (var1, var2) => { // * important: called once!
    let result1, result2, result3, result4, result5;
    result3 = var1;
    result4 = var2;
    ...
    console.log('result3:', result3);
    console.log('result4:', result4);
    socket.emit('bar', result1, result2, result3, result4, result5);
});
```
### Expected behaviour
[Server Log]
// 1st emit
result3: 1
result4: 2

[Client Log]
// send 1st emit
send var1: 1
send var2: 2
// send 2nd emit
send var1: 3
send var2: 4
// send 3rd emit
send var1: 5
send var2: 6
// send 4th emit
send var1: 7
send var2: 8
// received after 1st emit
recv result3: 1,
recv result4: 2

### Current behaviour
[Server Log]
// 1st emit
result3: 1
result4: 2

[Client Log]
// send 1st emit
send var1: 1
send var2: 2
// send 2nd emit
send var1: 3
send var2: 4
// send 3rd emit
send var1: 5
send var2: 6
// send 4th emit
send var1: 7
send var2: 8
// received after 1st emit
recv result3: 1
recv result4: 2
**// received after 2nd emit(BUG. server emit to client only one time)**
recv result3: 1
recv result4: 2
**// received after 3rd emit(BUG. server emit to client only one time)**
recv result3: 1
recv result4: 2
**// received after 4th emit(BUG. server emit to client only one time)**
recv result3: 1
recv result4: 2

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
