### ISSUE TITLE
Unhandled rejection Error: Integer is unsafe

### ISSUE THREAD

**Issue by whoisstan** [socketio/socket.io#3035]
Sometimes I am getting the error 'Unhandled rejection Error: Integer is unsafe' when sending JSON data via socket.io 2.0. Here is an example of sending a tweet object that causes such an rejection error.

Example Code:
https://gist.github.com/whoisstan/dcba1471094b984514c436fd395364e2

I am using those packages on node 6.11.2:

 -   "redis": "^2.8.0",
 -   "socket.io": "~2.0",
 -   "socket.io-redis": "^5.1.0",

Is the JSON payload simply too big? If yes, how do go about constraining the payload?

**Comment by darrachequesne** [comment]
I think that's because integers in Javascript are "safe" up to `2^53 - 1`:

```bash
$ node
> 899068272867328000 === 899068272867328001
true
> 899068272867328000 === 899068272867328002
true
> 899068272867328000 === 899068272867328064
true
> 899068272867328000 === 899068272867328065
false
```

And there's a check [here](https://github.com/darrachequesne/notepack/blob/2.1.1/lib/encode.js#L101) in the msgpack implementation.

Note: `msgpack-lite` seems to truncate the value:
```bash
$ node
> const msgpack = require('msgpack-lite');
undefined
> msgpack.decode(msgpack.encode(899068272867328064));
899068272867328000
```

**Comment by whoisstan** [comment]
yes, i understand that the number is bigger then "safe" int, but it's still a totally legal number that i can use in javascript and apply operations to.

`> 899068272867328002222220 + 899068272867328002222220
1.798136545734656e+24`

actually the value is retrieved from a twitter API payload, parsed and saved/retrieved into mongo without hickups or truncations.

at the end of the day i like to avoid having to parse and adjust all the data that we are retrieving to not breach max int. is there a way to plugin a less opinionated encoder but still use socket2?

**Comment by darrachequesne** [comment]
Closed by https://github.com/darrachequesne/notepack/pull/15.
