### ISSUE TITLE
Socket io sends a lot of requests

### ISSUE THREAD

**Issue by xahon** [socketio/socket.io#3040]
### You want to:

* [ ] request a *feature*
* [x] report a *bug*

### Current behaviour
Socket io sends lots of request

### Steps to reproduce (if the current behaviour is a bug)
1. clone https://github.com/socketio/chat-example
2. change socket io version in package json to the latest
3. npm install

### Expected behaviour
Socket io doesn't send a lot of requests like in version 1.7.3

### Setup
- OS: Ubuntu 16.04
- browser: Chrome latest
- socket.io version: 2.0.3 (1.7.3 works well)

**Comment by liujing0628** [comment]
i had the same problem

**Comment by xahon** [comment]
I've fixed that but don't remember what i did

**Comment by darrachequesne** [comment]
I think the chat example rely on an old version (1.2.0) of the `socket.io-client` (https://github.com/socketio/chat-example/blob/master/index.html#L22), which is not able to connect properly with newer versions of the server. In fact, it seems to happen with every version below 1.4.x. Could you please update your client version?

**Comment by xahon** [comment]
Yes, i remember. I just installed old socket.io version

**Comment by darrachequesne** [comment]
@xahon thanks for the detail! I think this issue can be closed, please reopen if needed.
