### ISSUE TITLE
How to SET MAX MESSAGE SIZE?

### ISSUE THREAD

**Issue by MegaUITeam** [socketio/socket.io#3041]
* [x] request a *feature*

- OS: all
- browser: all
- socket.io version: last

I want to limit the size of the request from the user so that he can not send me gigabytes of data

**Comment by darrachequesne** [comment]
You're looking for the [maxHttpBufferSize](https://github.com/socketio/engine.io#methods-1) option.

**Comment by MegaUITeam** [comment]
@darrachequesne wat if i use custom https server (for ssl support) ?

```coffeescript
httpsServer = https.createServer(
	cert              : config.SSL_CERT
	key               : config.SSL_KEY
	requestCert       : yes
	rejectUnauthorized: yes
).listen(config.PORT)

@io = new SocketIo(httpsServer)
```

where do I send the `maxHttpBufferSize` option?
