### ISSUE TITLE
it always auto disconnect from server(use php swoole)

### ISSUE THREAD

**Issue by QiiSyhx** [socketio/socket.io#3043]
i had read the document, but i can't find the answer, so i write this question for need help;

*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [ ] report a *bug*
* [ ] request a *feature*
* [x] need help

### Current behaviour
auto disconnect from server

### Steps to reproduce (if the current behaviour is a bug)
client code:
`var socket = io('127.0.0.1:9502', {
    transports: ['websocket'],
});

socket.connect();
socket.on('connect', function(){
    socket.send('Hello, i am HMM');
    console.log('Connected to server');
});
`
server code: 

`$ws = new swoole_websocket_server('0.0.0.0', 9502);
  
  $ws->on('open', function(swoole_websocket_server $server, $request) {
        echo "Open\n";
          $server->push($request->fd, "hello, welcome\n");
   });     
  
  $ws->on('message', function($server, $request) {
        echo "Message: {$request->data}\n";
         $server->push($request->fd, "server:{$request->data}");
 });     
 
 $ws->on('close', function($server, $fd) {
         echo "client-{$fd} is closed\n";
 });     
  
 $ws->start();
`
step1: run server
php server.php
step2: run client
open the html page on the browser;
step3: get infomation from server
Open
client-1 is closed
Open
client-2 is closed
Open
client-3 is closed
Open
client-4 is closed
Open
client-5 is closed
Open
client-6 is closed
...
**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
keep alive

### Setup
- OS: ubuntu 16.4 (64-bit)
- browser: firefox 54.0
- socket.io version: v2.0.3

**Comment by darrachequesne** [comment]
Hi! I don't know the Swoole project, is it supposed to be compatible with the socket.io client?

**Comment by QiiSyhx** [comment]
Thanks. If i use the native websocket, it's work!
`var socket = new WebSocket('ws://localhost:9502');
socket.send('Hello');`
I will receive a message from terminal: Message: Hello
And i don't know socketio how to work. i will check it agin.

**Comment by Qanah** [comment]
@QiiSyhx I have same issue can you help me if you have fix that

**Comment by arabnewscms** [comment]
hi pro 
it very easy 
in your php server 
`$ws = new swoole_websocket_server('127.0.0.1', 8080);
`
$ws->on('open', function(swoole_websocket_server $server, $request) {
echo "Open\n";
$server->push($request->fd,"hello", "hello, welcome\n");
});
`
in front end :) 
 `
 var socket = io.connect('ws://127.0.0.1:8080',{transports: ['websocket']});
socket.on('hello',function(data){
console.log(data); //
});
`
read the documentation on swoole website 
to get more benefits 
https://www.swoole.co.uk
if you have any error i am here  <3

**Comment by darrachequesne** [comment]
Hi! From what I understand, [Swoole](https://github.com/swoole/swoole-docs/blob/master/modules/swoole-websocket-server/introduction.md) provides a Websocket server implementation in PHP. That's why the `socket.io-client` library is not able to connect.

I edited the documentation [here](https://socket.io/docs/#What-Socket-IO-is-not), hopefully it is more clear now! I think we can close the issue.

Note: wrapping your code between ticks (\`\`\`js \<code\> \`\`\`) will make it far more readable :cake:
