### ISSUE TITLE
Centralised session info to remove dependency of stickiness!

### ISSUE THREAD

**Issue by royalpinto** [socketio/socket.io#3044]
### You want to:

* [x] report a *bug/enhancement*

### Current behaviour
When node clusters are used, it is required to maintain stickiness explicitly even though shared adapter is used `socket.io-redis`. When client sends multiple requests, if subsequent requests doesn't go to the same node worker where initial request was made, socket.io throws an error: *Session ID unknown*. How about caching this session information in a centralised place (May be in a `redis` adapter itself) and make it work from any worker ?

Currently there are implementations available to make connections go to the same worker based of Client's IP Address hashing. But these have to be managed explicitly and also might not help load balancing when users share common IP address. (Ex: An internal app being used within a same network).

**Comment by darrachequesne** [comment]
Hi! As a matter of fact, it was handled by the library in < 1.x versions, but that led to some synchronization issues, hence the current implementation.

Recently, I implemented a proxy based on the `http-proxy` module, which stores the associations between client and worker in Redis, but unfortunately I haven't been able to test it in _real_ conditions yet: https://github.com/darrachequesne/socket.io-proxy

**Comment by royalpinto** [comment]
@darrachequesne Would it work with node workers (clustering) sharing the same PORT ?

It would have been great if `socket-io` internally handles session management between multiple workers within a same process. That way, explicitly **user doesn't have to manage multiple PORT**s (one for each node process. When scaling number of workers based on number of CPUs available, it will be painful otherwise) and also doesn't need a proxy layer to maintain the stickiness.

**Comment by darrachequesne** [comment]
No, it won't work with workers sharing the same port.

Though I think the principle used in https://github.com/darrachequesne/socket.io-proxy (routing based on the socket id) could be used to improve the https://github.com/indutny/sticky-session module.

**Comment by royalpinto** [comment]
@darrachequesne interesting, I will play around with this. Thanks

**Comment by johnmela** [comment]
I am also working through this problem and would prefer not to use sticky sessions. I am curious to know what the synchronization issues were pre 1.0.x that led to the deprecation of shared  session support?

**Comment by darrachequesne** [comment]
There was a lot of conversations around that subject:
- https://github.com/socketio/engine.io/issues/261
- https://github.com/socketio/engine.io/pull/416
- https://github.com/socketio/socket.io/issues/2231
- https://github.com/socketio/socket.io/issues/1942

I wasn't on the project when the support for cluster was removed, so I don't remember where those synchronisation issues came from (either implementation or architecture)..

**Comment by darrachequesne** [comment]
For future readers:

We have added some explanation here: https://socket.io/docs/v4/using-multiple-nodes/#Why-is-sticky-session-required

Within a Node.js [cluster](https://nodejs.org/api/cluster.html), you can now use the cluster adapter and the `@socket.io/sticky` package:

```js
const cluster = require("cluster");
const http = require("http");
const { Server } = require("socket.io");
const numCPUs = require("os").cpus().length;
const { setupMaster, setupWorker } = require("@socket.io/sticky");
const { createAdapter, setupPrimary } = require("@socket.io/cluster-adapter");

if (cluster.isMaster) {
  console.log(`Master ${process.pid} is running`);

  const httpServer = http.createServer();

  // setup sticky sessions
  setupMaster(httpServer, {
    loadBalancingMethod: "least-connection",
  });

  // setup connections between the workers
  setupPrimary();

  // needed for packets containing buffers (you can ignore it if you only send plaintext objects)
  // Node.js < 16.0.0
  cluster.setupMaster({
    serialization: "advanced",
  });
  // Node.js > 16.0.0
  // cluster.setupPrimary({
  //   serialization: "advanced",
  // });

  httpServer.listen(3000);

  for (let i = 0; i < numCPUs; i++) {
    cluster.fork();
  }

  cluster.on("exit", (worker) => {
    console.log(`Worker ${worker.process.pid} died`);
    cluster.fork();
  });
} else {
  console.log(`Worker ${process.pid} started`);

  const httpServer = http.createServer();
  const io = new Server(httpServer);

  // use the cluster adapter
  io.adapter(createAdapter());

  // setup connection with the primary process
  setupWorker(io);

  io.on("connection", (socket) => {
    /* ... */
  });
}
```

Documentation:

- https://socket.io/docs/v4/using-multiple-nodes/#Using-Node-js-Cluster
- https://socket.io/docs/v4/cluster-adapter/

Please reopen if needed.
