### ISSUE TITLE
Connection error in https for socket.io

### ISSUE THREAD

**Issue by catalynn21** [socketio/socket.io#3045]
I have this script running well in http but the problem appears in https when in google chrome appears "Error 525 SSL handshake failed" generated by cloudflare. Thank you in advance!

`//socket
var connections=0;
var app = require('express')();
var https = require('https').Server(app);
var io = require('socket.io')(https);
io.on('connection', function(socket){

    connections=connections+1;
 //   myconsolelog('[socket] a user connected. total connections: '+connections);
    //

    socket.emit('handshake',1);
    socket.emit('online',connections);

    request(steamstatusurl+'?pw='+accesspassword, function(error, response, body) {
        //myconsolelog('steamstatus: '+body);
        io.emit('steamstatus',body);
    });
    request(contentcreatorsurl+'?pw='+accesspassword, function(error, response, body) {
        //myconsolelog('steamstatus: '+body);
        io.emit('cc',body);
    });

    socket.on('disconnect', function(){

        connections=connections-1;
//        myconsolelog('[socket] user disconnected total connections: '+connections);
        socket.emit('online',connections);

    });

});
//

//sock
https.listen(2096, function(){
  myconsolelog("\r\n\r\n"+'[socket] Listening on *:2096');
});`

**Comment by derbaser** [comment]
Same problem. Have you solved it?

**Comment by derbaser** [comment]
Same problem. Have you solved it?

**Comment by darrachequesne** [comment]
For future readers: please see the documentation [here](https://socket.io/docs/v3/server-initialization/#With-an-HTTPS-server).
