### ISSUE TITLE
Server webpack bundling issue

### ISSUE THREAD

**Issue by IhostVlad** [socketio/socket.io#3046]
### Current behaviour
Socket.io server-side part contains following line: https://github.com/socketio/socket.io/blob/master/lib/index.js#L110 , which implies load some library part at runtime.
Such behaviour causes problems in bundling server side by webpack, because `socket.io-client` library is not required directly by `require` operation, and that's why does not compile into bundle.

### Steps to reproduce (if the current behaviour is a bug)
Bundle server side/backend project by webpack in `node` mode and try to get one independent bundled distributed file, like for client/frontend side

### Expected behaviour
Socket.io server-side part should perform require dependent entities in compile-time by using default `require`/`import` mechanism, or provide already bundled version of library for webpack usage

### Setup
- OS: Linux 4.4.0-62-generic SMP x86_64 GNU/Linux / Ubuntu 16.04.1 LTS
- socket.io version: 2.0.3

**Comment by IhostVlad** [comment]
Solved this way: instruct the SocketIO server to disable serving the client and serve it "manually". At https://socket.io/docs/server-api/##server set `serveClient` to `false`

**Comment by darrachequesne** [comment]
Thanks for the follow-up! If anyone else is interested, there is an example with webpack [here](https://github.com/socketio/socket.io/tree/master/examples/webpack-build-server).
