### ISSUE TITLE
How to reduce emit delay with MANY concurrent connections?

### ISSUE THREAD

**Issue by MickL** [socketio/socket.io#3047]
Im running a 4-core Amazon EC2 instance(m3.xlarge) with 200.000 concurrent connections with no ressouce problems(each core at 10-20%, memory at 2/14GB). Anyway if i emit a message to all the user connected first on a cpu-core gets it within milliseconds but the last connected user gets it with a delay of 1-3 seconds and each CPU core goes up to 100% for 1-2 seconds. I noticed this problem even at "only" 50k concurrent users.

How to reduce the delay?

I tried changing redis-adapter to mongo-adapter with no difference.

Im using this code to get sticky sessions on multiple cpu cores:

https://github.com/elad/node-cluster-socket.io

The test was very simple: The clients do just connect and do nothing more. The server only listens for a message and emits to all.

**Comment by perjerz** [comment]
@MickL Did you solve this problem?

**Comment by MickL** [comment]
I think it is just normal: If you do an array operation on 200.000 items it will take a while. The solution is to put less people per core. Also I would use node cluster anymore. Instead just spawn one app per core and let Nginx handle sticky sessions.
