### ISSUE TITLE
how to using send message to array rooms

### ISSUE THREAD

**Issue by thandonguocmo2020** [socketio/socket.io#3048]
my rooms :

var rooms =  [ObjectId1,ObjectId2,...n ObjectId); // 10 item

 socket.join(rooms);

how to send it looks so

socket.to(rooms).emit("send-notitication", data)

my help !

**Comment by darrachequesne** [comment]
This feature was implemented by https://github.com/socketio/socket.io/commit/085d1de9df909651de8b313cc6f9f253374b702e and included in `socket.io@4.0.0`.

Syntax:

```js
io.to(["room1", "room2", "room3"]).emit(/* ... */);

socket.to(["room1", "room2", "room3"]).emit(/* ... */);
```

Documentation: https://socket.io/docs/v3/migrating-from-3-x-to-4-0/#Allow-to-pass-an-arrow-to-io-to
