### ISSUE TITLE
Unable to parse python dictionaries. 

### ISSUE THREAD

**Issue by piyushdivyankar1994** [socketio/socket.io#3050]
I have a server to which i connect using websockets. The server sends me python dictionaries. The python dictionaries often contain `numpy.nan` entries. When this happens none of the functions(events) I have written on my client, that are triggered using this dictionaries as input get executed. One example would be following. 
```
socket.on('response', function(msg) {
                //var result = JSON.parse(msg.replace(/\bnan\b/g, "null"));
                console.log('New message')
                console.log(msg);
            });
```
The server sends an event called `response` and along with it comes a python dict. But this function doesn't get triggered when the dict contains `nan`. However when dict passes `None` then it works fine.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
