### ISSUE TITLE
Facebook Beta

### ISSUE THREAD

**Issue by Stingertough** [socketio/socket.io#3051]
When attempting to log into Facebook Beta for Windows 10 am met with the following error message: 

The operation couldn't be completed. AsyncSocketException: error:24064064:random number generator: SSLEAY_RAND_BYTES:PRNG not seeded, type = SSL error

Has anyone come across this issue besides what was reported for Karma? 

![capture](https://user-images.githubusercontent.com/20640031/30322827-b2f7f946-97b2-11e7-9878-c88219666780.PNG)

**Comment by darrachequesne** [comment]
Is this related to socket.io?

**Comment by Stingertough** [comment]
It is not sir.

**Comment by ForsakenHarmony** [comment]
Then this is not the place
