### ISSUE TITLE
I have created https server on node server and after that i am not able to get the socket.io.js here is my code:

### ISSUE THREAD

**Issue by brij-mohan** [socketio/socket.io#3052]
var fs = require('fs');
var server = require('https');
var express = require('express');
var app = express();

// This is needed if the app is run on heroku:

var port = process.env.PORT || 8181;
//var port = process.env.HTTPS_PORT || 8181;

// Initialize a new socket.io object. It is bound to
// the express app, which allows them to coexist.
httpsServer = server.createServer({
key: fs.readFileSync('my.agentmx.com.key'),
cert: fs.readFileSync('my.agentmx.com.crt'),
ca: fs.readFileSync('my.agentmx.com.ca-bundle')
}, app).listen(port);

//var io = require('socket.io').listen(app.listen(port));

var io = require('socket.io')(httpsServer);
// Require the configuration and the routes files, and pass
// the app and io as arguments to the returned functions.

require('./config')(app, io);
require('./routes')(app, io);

var url = require('url');

console.log('Your application is running on port: ' + port);

**Comment by psabharwal123** [comment]
this is not a socket,io issue, maybe ask on stackoverflow

**Comment by brij-mohan** [comment]
Thanks for message @psabharwal123. I resolved this issue.
