### ISSUE TITLE
Would love some JWT authentication support

### ISSUE THREAD

**Issue by mmc41** [socketio/socket.io#3053]
### You want to:

* [] report a *bug*
* [x ] request a *feature*

### Current behaviour

Currently, there seem to be no support for token authentication when using socket.io. I could find various npm packages with some extensions but they are either not maintained or use query strings which are not secure. There are some articles like for instance [this](http://wmyers.github.io/technical/nodejs/Simple-JWT-auth-for-SocketIO/) which outlines how to impl. token authentication but it is rather complex at requires 2 round trips. Would really like a simple solution for this build-in.

**Comment by darrachequesne** [comment]
How about using the `extraHeaders` option? Something like:
```js
const client = io({
  transportOptions: {
    polling: {
      extraHeaders: {
        'Authorization': 'Bearer abc'
      }
    }
  }
});

// server-side
const io = require('socket.io')();

// middleware
io.use((socket, next) => {
  let header = socket.handshake.headers['authorization'];
  if (isValidJwt(header)) {
    return next();
  }
  return next(new Error('authentication error'));
});
```

**Comment by mmc41** [comment]
@darrachequesne Thanks. Great suggestion (much better than the examples I could find online). Much appreciated!

**Comment by mmc41** [comment]
@darrachequesne I tried you suggestion and it seems to work but after reading the docs I am unsure if it is a solid solutions because of the statement below.

> This only works if polling transport is enabled (which is the default). Custom headers will not be appended when using websocket as the transport. This happens because the WebSocket handshake does not honor custom headers.

I have enabled default transports enabled but I am unsure of the security implications regarding the upgrade from pooling to websockets ?

**Comment by brenc** [comment]
Yep you hit the same thing I did. I use a form of [this method](https://facundoolano.wordpress.com/2014/10/11/better-authentication-for-socket-io-no-query-strings/). I've updated the main example and made it more complete using `node-jsonwebtoken` directly (which I find better than using middleware):

```javascript
io.on('connection', function (socket) {
  socket.authenticated = false
  
  socket.on('authenticate', function (data) {
    const token = data.token

    // Verify the token.
    jwt.verify(token, 'secretOrPublicKey', function (err, decoded) {
      let message

      if (err) {
        // err.message will be something like 'jwt malformed' or 'jwt expired'
        // so you'll want to check that and maybe do something else here
        // depending on the error message. For example, if I get a 'jwt
        // expired' or 'jwt malformed' error, I send that to the client to
        // give it a chance to obtain a fresh token.
        if (err.message === 'jwt expired' || err.message === 'jwt malformed') {
          message = err.message
        } else {
          message = 'access denied'
        }

        socket.emit('unauthorized', {
          message: message
        })

        // Don't disconnect the client. This gives them time to obtain a fresh
        // token. If they fail to do so, then disconnect timer will eventually
        // disconnect them.

        return
      }

      // You'll probably want to log the username or ID here instead. I don't
      // use socket.id at all myself.
      console.log(`authenticated socket ID "${socket.id}"`)

      // I don't recommend adding data to the socket object directly. This is
      // just here for brevity. I made a User class that wraps the socket
      // object, for example.
      socket.authenticated = true
      socket.decodedToken = decoded
    })
  })

  setTimeout(function () {
    // If the connection hasn't been authenticated in a period of time,
    // disconnect it.
    if (!socket.authenticated) {
      // You'll probably want to log the username or ID here instead.
      console.log(`socket ID "${socket.id}" failed to authenticate, ` +
        `disconnecting`)

      socket.emit('unauthorized', {
        message: 'failed to authenticate'
      })

      socket.disconnect()
    }
  }, 5000)
})
```

The other thing you'll want to watch out for is clients can send any event they want. This means an authorized user could use your server for something it wasn't designed to do (their own chat client for example).

I use [socketio-wildcard](https://github.com/hden/socketio-wildcard) to inspect each packet coming in to make sure I'm receiving authorized events. You could just put in a basic middleware function to do this as well. Example using `socketio-wildcard`:

```javascript
io.on('connection', function (socket) {
  socket.on('*', function (packet) {
    const eventName = packet[0]
    if (eventName !== 'allowedEventName') {
       socket.emit('unauthorized')
       socket.disconnect()
    }
  })
})

This pretty much covers authentication and authorization with JWTs as far as I know (as long as you have the JWT stuff set up correctly). Hope this helps!

**Comment by ForsakenHarmony** [comment]
feathers authenticates the socket session with an initial request, which might not be what you want, just thought I'd note it

**Comment by darrachequesne** [comment]
@mmc41 what that means is that the following would not work:

```js
const client = io({
  transports: [ 'websocket' ], // <-- the default being [ 'polling', 'websocket' ]
  transportOptions: {
    polling: {
      extraHeaders: {
        'Authorization': 'Bearer abc'
      }
    }
  }
});
```

**Comment by zishanj** [comment]
@darrachequesne I have tried your middleware solution to authorize the `socket.io-client-java` client but it does not return the Error to Java client :

```
io.use((socket, next) => {
  let header = socket.handshake.headers['authorization'];
  if (isValidJwt(header)) {
    return next();
  }
  return next(new Error('authentication error'));
});
```

**Comment by muhammadnasr** [comment]
@darrachequesne will using long polling like this example:
const client = io({
  transportOptions: {
    polling: {
      extraHeaders: {
        'Authorization': 'Bearer abc'
      }
    }
  }
});

 will never use web sockets after that or it will upgrade to web socket once handshaking is done?

**Comment by darrachequesne** [comment]
@muhammadnasr it will try to upgrade to Websocket if possible.

@zishanj please open an issue in the [socket.io-client-java](https://github.com/socketio/socket.io-client-java) repository.

**Comment by darrachequesne** [comment]
@muhammadnasr it seems Swift client has ([documentation](https://nuclearace.github.io/Socket.IO-Client-Swift/Enums/SocketIOClientOption.html)), but Java hasn't yet: https://github.com/socketio/socket.io-client-java/issues/520
