### ISSUE TITLE
Can't capture port errors

### ISSUE THREAD

**Issue by adamreisnz** [socketio/socket.io#3055]
I may be missing something obvious, but I've tried all variations of `on('error')` and wrapping the code in try/catch blocks, all to no avail.

How to capture errors that originate from:

```js
this.io = new Server(this.port);
```

When I try to run two instances in parallel, obviously I get a port in use error, but I can't capture/handle it. No matter what I do, it keeps crashing with:

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 
```

How can I capture these errors and handle them gracefully?

**Comment by darrachequesne** [comment]
For future readers:

For this use case, please create your own HTTP server:

```js
const httpServer = require("http").createServer();
const options = { /* ... */ };
const io = require("socket.io")(httpServer, options);

io.on("connection", socket => { /* ... */ });

httpServer.on("error", (e) => {
  if (e.code === 'EADDRINUSE') {
    // ...
  }
});

httpServer.listen(3000);
```

Documentation: https://socket.io/docs/v3/server-initialization/#With-an-HTTP-server
