### ISSUE TITLE
Question - how can in socket.use make call to an acknowledge function

### ISSUE THREAD

**Issue by juan77** [socketio/socket.io#3058]
Sorry, but I can't find any help related to my question in stackoverflow.

when the client emit with an ack function, I would like to intercept using socket.use() and if apropiate can respond to the ack function of the client.

```javascript
client.emit('myMessage', { myData: 1 }, function(err, message) {
  console.log(message); // -> should be { msg: 'server response' }
});
```

```javascript
socket.use(function(packet, next) {
  ack = ... // some way to retrieve ack function
  ack(null, { msg: 'server response' });
}
```

Is there any way to do it?
thx in advance.

**Comment by Nibbler999** [comment]
`ack` is the last element in the `packet` array.

**Comment by juan77** [comment]
Great!! worked like a charm!
thx @Nibbler999 !
