### ISSUE TITLE
NSP security waring from socket.io dependency

### ISSUE THREAD

**Issue by jornki** [socketio/socket.io#3061]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
* `socket.io@2.0.3 > socket.io-client@2.0.3 > engine.io-client@3.1.1 > parsejson@0.0.3`
* The version of `parsejson` shipped with socket.io 2.0.3 can leave the solution open to a DDoS attack
* https://nodesecurity.io/advisories/528
* ~https://nodesecurity.io/advisories/531~

### Steps to reproduce (if the current behaviour is a bug)
* Add socket.io 2.0.3 to a node project
* Run [nsp](https://nodesecurity.io/) against the project

### Expected behaviour
* Deps in socket.io should not contain vulnerable dependencies

### Setup
- OS: Linux/Unix
- browser: ..
- socket.io version: 2.0.3

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io-client/pull/580. Thanks for the heads-up!
