### ISSUE TITLE
Socket connection issue while using namespace middleware with iOS Swift

### ISSUE THREAD

**Issue by vishvas-prajapati** [socketio/socket.io#3063]
The connection is established successfully with iOS Client without using namespace middleware.
`var nsp = io.of('/test');
nsp.on('connection', function(socket) {
});`

But when I use below middleware code, the connection could not be established with iOS Client. It works with web and Android client.

`var nsp = io.of('/test');`

`// middleware
nsp.use(function (socket, next) {
// 
}); `

`nsp.on('connection', function(socket) {
});`

**Comment by darrachequesne** [comment]
Hi! Could you please open an issue in the iOS Client repository: https://github.com/socketio/socket.io-client-swift?

Thanks!
