### ISSUE TITLE
"featuring the fastest and most reliable real-time engine"

### ISSUE THREAD

**Issue by neolectron** [socketio/socket.io#3064]
Hi,
"featuring the fastest and most reliable real-time engine"
found in the frontpage, its the headline of the lib apparently now.

Can you provide benchmark for this ?

I have a doubt on this one.
Where can I find your benchmark justifying this sentence?

thanks.

**Comment by darrachequesne** [comment]
As of version 2.0, we now rely on `uws` as the default websocket engine, please see [here](https://github.com/uNetworking/uWebSockets) for the benchmarks.

**Comment by thetutlage** [comment]
@darrachequesne Those will be `uws` benchmarks and not socket.io right?

**Comment by marcj** [comment]
So any proof for that claim yet? I'm sure you guys did some benchmarks before you decided to put that claim in the first headline of the site.

**Comment by darrachequesne** [comment]
We've removed the phrase from the homepage, as I didn't find any evidence for this claim. I agree that we'll need to provide some benchmark results for this.
