### ISSUE TITLE
Hanlde socket.io inTCP loadbalancer 

### ISSUE THREAD

**Issue by chaturanga836** [socketio/socket.io#3065]
i have two server, which use tcp load-balance to handle request.  i use socke.io-redis  for socket adapter
the problem is when client handshake with server it response 400 ( unknown session i ) error.
then i looking for sticky session solution. but server admin said it cannot apply, cuz tcp loadbalacer.
is there a way to handle this issue.?

**Comment by darrachequesne** [comment]
For future readers: the TCP loadbalancer should be able to provide sticky session based on the IP address of the client.

Documentation: https://socket.io/docs/v3/using-multiple-nodes/
