### ISSUE TITLE
Not recieving pong

### ISSUE THREAD

**Issue by shivankappster** [socketio/socket.io#3068]
socket.on("connect") { data, ack in
            print("connection~!~!~!")
            self.getChatMessage { (messages) in
                debugPrint("messageDictionary %@",messages)
            }
        }
        socket.onAny {event in
            print(event.event)
        }
        
        socket.on("ping") {data, ack in
            print(self.socket.status)
            self.socket.emit("pong")
        }
        
        socket.on("message") { data in
            print("client received message")
        }
        
        socket.on("pong") {data in
            print("client received pong")
        }
        
        socket.connect()

        switch socket.status {
        case .connected:
            debugPrint("----connected")
        case .disconnected:
            debugPrint("----disconnected")
        case .connecting:
            debugPrint("----connecting")
        case .notConnected:
            debugPrint("----notConnected")
        }

**Comment by darrachequesne** [comment]
`ping` and `pong` are reserved event names, please do not use them in your code.

Please see the [docs](https://github.com/socketio/socket.io/blob/master/docs/emit.md) for the full list.
