### ISSUE TITLE
Socket connection in IE 11

### ISSUE THREAD

**Issue by huytran0605** [socketio/socket.io#3069]
Currently i'm using SocketIo to make chat application. 
It doesn't have any problem in Chrome. 
But in **IE 11**, after few minute, i can't use socket to emit event. It seems socket connection is disconnected.

I searched and found any issue about timeout of tcp/socket in IE 11. But still can't found solution.

I only use websocket for socket.io, prevent them use long-polling. The config socket in client side like below:
```
import socket from 'socket.io-client';

socket('/test', { transports: ['websocket'], upgrade: false });
```
Server i'm using express and socket redis
```
import socketio from 'socket.io';
import socketioRedis from 'socket.io-redis';


const ioRedis = socketioRedis('redis://localhost:6379');
const io = socketio(server, {
  adapter: ioRedis,
  transports: ['websocket'],
});
```

**Comment by darrachequesne** [comment]
Could you enable the debug logs (with `localStorage.debug='socket*'`)? Does it happen when you have several tabs open?

**Comment by dev-mraj** [comment]
![image](https://user-images.githubusercontent.com/2859624/42922589-f90c3728-8b3e-11e8-9cca-667704eeb404.png)

this is happening again and again

**Comment by darrachequesne** [comment]
It seems the socket is unable to connect. What happens if you enable `polling` transport? Does it succeed to connect?

Could you please include engine.io's logs with `localStorage.debug="socket*,engine*"`?

**Comment by dev-mraj** [comment]
that is now started working but that particular time everytime it was getting timeout..while in all other browers was working..

may be something server side is fishy

**Comment by dev-mraj** [comment]
also let me know how can i get exact reason for disconnect. because we are getting too much random disconnect while internet is working fine, even when client have high speed internet.

how to debug that issue?

**Comment by dev-mraj** [comment]
any update?

**Comment by Shangxq** [comment]
![image](https://user-images.githubusercontent.com/21060863/64468070-8a572080-d152-11e9-9682-d70a5ad1f9ec.png)
when I refresh 6 times in IE 11

**Comment by Shangxq** [comment]
add this code it was working fine
`                window.addEventListener("beforeunload", function (event) {
                    try{
                       xxxxx.io.engine.transport.doClose();
                        xxx.io.engine.transport.ws = undefined;
                    }catch (err){
                        logger('ie refresh error', err);
                    }
                });
`

**Comment by Shangxq** [comment]
`javascript                window.addEventListener("beforeunload", function (event) {
                    try{
                        _this.socket.io.engine.transport.doClose();
                        _this.socket.io.engine.transport.ws = undefined;
                    }catch (err){
                        logger('ie 刷新报错', err);
                    }
                });`

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io-client/commit/ed48b5dc3407e5ded45072606b3bb0eafa49c01f, included in [`socket.io-client@3.1.2`](https://github.com/socketio/socket.io-client/releases/tag/3.1.2).
