### ISSUE TITLE
Bump debug dependency to 3.1.0

### ISSUE THREAD

**Issue by roccomuso** [socketio/socket.io#3070]
`Regular Expression Denial of Service` Affecting `debug <= 3.1.0`.

Because of this, it prevents all the modules using express and `nsp check` to pass the security checks.

Bump also the `socket.io-client` dependency after having merged this: https://github.com/socketio/socket.io-client/issues/1160

**Comment by darrachequesne** [comment]
Hi! Does it also apply to version `2.6.8` of debug? Because running `nsp check` on the project currently gives me `No known vulnerabilities found`.

**Comment by roccomuso** [comment]
`2.6.8` is also fine.

**Comment by YasharF** [comment]
https://github.com/socketio/socket.io/pull/3099

**Comment by pmbanugo** [comment]
Looking forward to having the PR merged so I can upgrade my services.

**Comment by daraghking** [comment]
If I created a PR similar to [#3099](https://github.com/socketio/socket.io/pull/3099) for the 1.7 branch would it be considered for merging?

**Comment by darrachequesne** [comment]
Fixed by https://github.com/socketio/socket.io/commit/52b09609db04e8691ba9307009e54dd528929a86 (included in `socket.io@2.1.0`).
