### ISSUE TITLE
why socket.emit is not working after socket connection timeout in ios?

### ISSUE THREAD

**Issue by binita12345** [socketio/socket.io#3072]
i am facing issue with socket, when i click on my logout button after some times, socket api is not call from backend (node.js).

    i am using following code on frontend ionic:

    $rootScope.socket.emit('userlogout', JSON.stringify(userinfo));
            console.log("user logout" + JSON.stringify(userinfo));

            $rootScope.socket.on('userout', function(user) {
               console.log("user out details" + user);
               // $scope.islogin = true;
               $scope.removelogoutuser(user);
               // $state.go('login');
            });

and using on backend(node.js):

    socket.on('userlogout',function(userdetails) {
        var userinfo=JSON.parse(userdetails);
        console.log("userinfo...." +JSON.stringify(userinfo));
        // var options = { new: true };
        myUser.find({
              'username': userinfo.username
          }, function(err, result) {
            myUser.update({
                'username': userinfo.username
            }, {
                $set:{
                    isLogin: false
                },
            }, {
                upsert: true
            }, function(err, data) {
                console.log('errrr: ',err);
                console.log('data: ',data);

                if (err) {
                    console.log("err...." +JSON.stringify(err));
                } else {
                    console.log("data...." +JSON.stringify(data));
                }
            }); 
        });
        
         io.sockets.in(userinfo.roomname).emit('userout',userdetails);
      })

      socket.on('logoutme',function(userdetails,callback){
          var userinfo=JSON.parse(userdetails);
          console.log("user disconnected "+ userinfo.roomname);
          callback('error', 'message');
          socket.leave(userinfo.roomname);
      })

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
