### ISSUE TITLE
socket.io 2.0.3 client side js error

### ISSUE THREAD

**Issue by yeukfei02** [socketio/socket.io#3073]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
I use yarn to install socket.io and express
In client side js:
```
<script>
var socket = io.connect(windows.location.host);
</script>
```
or 
```
<script>
var socket = io.connect(windows.location.href);
</script>
```

client side console error: 
``net::ERR_ADDRESS_UNREACHABLE`` 
or
``400 (Bad Request)``

### Expected behaviour

no error in console

### Setup
- OS: mac
- browser: chrome
- socket.io version: 2.0.3

**Comment by darrachequesne** [comment]
Hi! How are you initializing your server, and how are you importing the client script (is it served by the server itself)?

**Comment by yeukfei02** [comment]
try to use version 1.3.x
without error
thanks.
