### ISSUE TITLE
Connecting to unsupported path

### ISSUE THREAD

**Issue by ScottFreeCode** [socketio/socket.io#3075]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

If I attempt to connect to the wrong path, nothing happens.

### Steps to reproduce (if the current behaviour is a bug)

```js
const Server = require("http").Server
const socketIO = require("socket.io")
const makeClient = require("socket.io-client")

new Promise((resolve, reject) => {
	const server = new Server()
	server.on("error", reject)
	socketIO(server, { path: "/some/path" })
	server.listen(8080)
	const client = makeClient("http://localhost:8080", { path: "/other/path" })
	client.on("connect", () => {
		client.disconnect()
		server.close(error => {
			if (error) {
				reject(error)
			} else {
				resolve(error)
			}
		})
	})
	client.on("error", reject)
})
	.then(console.log, console.error)
```

### Expected behaviour

I'm not certain is this is 100% correct or if I'm just missing the right way to watch for this problem, but I'd expect an error to be emitted on the client if the path doesn't exist/match.

### Setup
- OS: Mac or Windows
- browser: NodeJS Socket.io client
- socket.io version: 2.0.3

**Comment by darrachequesne** [comment]
For future readers: the "connect_error" event is emitted by the Socket instance upon connection error.

Documentation: https://socket.io/docs/v3/client-socket-instance/#connect-error
