### ISSUE TITLE
IE11 websocket disconnection delay from within iframe

### ISSUE THREAD

**Issue by manufacturist** [socketio/socket.io#3077]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
When deleting an iframe, the 'disconnect' event will not be triggered immediately for 'io connections' which use the 'websocket' transport only from within that iframe.

### Steps to reproduce (if the current behaviour is a bug)
./index.js:
```javascript
var express = require('express');
var app = express();
var server = require('http').createServer(app);
var io = require('socket.io')(server);

app.use(express.static('public'));

io.on('connection', function(client){
  console.log(Date.now(), 'Connected');
  client.on('event', function(data){});
  client.on('disconnect', function(){
    console.log(Date.now(), 'Disconnected');
  });
});

server.listen(3000);
```

./public/index.html:
```html
<html>
	<body>
		<button id="cls">Remove iframe</button>
		<iframe id="ifr" src="/iframe.html"></iframe>
		<script>
			var btn = document.getElementById('cls');
			btn.addEventListener('click', function(){
				var ifr = document.getElementById("ifr");
				ifr.parentNode.removeChild(ifr);
			});
		</script>
	</body>
</html>
```

./public/iframe.html:
```html
<html>
	<body>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.3/socket.io.js"></script>
		<script>
			var socket = io.connect("ws://localhost:3000", {
				transports: ['websocket']
			});
		</script>
	</body>
</html>
```
First, install the socket.io and express packages, then run 'node .' or 'node index.js'.
Now go to localhost:3000 via IE11 and press the 'Remove iframe' button.

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
When deleting an iframe, any websocket connection within it should disconnect / close / self-destroy and trigger the 'disconnect' event on the backend quickly (less than 2 seconds).

### Setup
- OS: Windows 10
- browser: Internet Explorer 11.608.15063
- socket.io version: 2.0.3 (latest on npm)

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
I've tried disconnecting the WS manually on the window.unload event but it doesn't work. Also, if the transport is not specified (client), the disconnect event will get triggered in only a few seconds (1-4[s]).

Here's the generated fiddler log for IE11 when closing the iframe:
```
10:14:52:8288 WSSession46.WebSocket'WebSocket #46'
MessageID:	Client.7
MessageType:	Text
PayloadString:	41/ws,
Masking:	6D-96-23-31

10:14:52:8293 WSSession46.WebSocket'WebSocket #46'
MessageID:	Server.8
MessageType:	Close
PayloadString:	
Masking:	<none>

// the message below is a fiddler error
10:14:52:8298 [WebSocket #46] Read from Server returned error: 0
10:14:52:8298 WSSession46.WebSocket'WebSocket #46'
MessageID:	Client.9
MessageType:	Close
PayloadString:	
Masking:	52-D3-AB-3F

// the message below is a fiddler error
10:14:52:8303 [WebSocket #46] Read from Client failed... Object reference not set to an instance of an object.
10:14:58:8246 WSSession25.WebSocket'WebSocket #25'
MessageID:	Server.59
MessageType:	Close
PayloadString:	
Masking:	<none>
```
The 'disconnect' event is triggered at ~10:14:58 and the iframe was closed at ~10:14:52 (there were scenarios where the 'disconnect' would trigger after ~40 seconds).

Here's the generated fiddler log for Chrome (latest) when closing the iframe:
```
10:18:48:6693 WSSession99.WebSocket'WebSocket #99'
MessageID:	Client.4
MessageType:	Text
PayloadString:	21�O/�/-�,K��/)N-*K-�/����t

10:18:48:6698 WSSession99.WebSocket'WebSocket #99'
MessageID:	Server.5
MessageType:	Close
PayloadString:	
Masking:	<none>

// the 2 messages below are fiddler errors
10:18:48:6698 [WebSocket #99] Read from Server returned error: 0 
10:18:48:6703 [WebSocket #99] Read from Client failed... Object reference not set to an instance of an object.
10:18:48:6828 WSSession79.WebSocket'WebSocket #79'
MessageID:	Client.28
MessageType:	Close
PayloadString:	03-E9
Masking:	60-9A-9A-4C
```
The 'disconnect' event is triggered at ~10:18:48:6828 and the iframe was closed at ~10:18:48:6693.

**Comment by manufacturist** [comment]
Update:

The 'close' event does get triggered properly when using the 'ws' package and the WebSocket JS object and manually closing the client websocket in the 'onunload' event.

If the WebSocket is not closed manually, the 'close' event will trigger in somewhere between ~0 and 3 seconds.

I'm guessing that it might be an issue with the Socket.io protocol (or the 'WebSocket' implementation used) and the way it handles the 'closing' messages from IE11.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
