### ISSUE TITLE
The fn.bind() not a function

### ISSUE THREAD

**Issue by Daxong** [socketio/socket.io#3079]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
new request server and then it will break out! and tips: fn.bind() not a function in node_modules/socket.io-adapter/index.js:210:31

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:macOS high Sierra 10.13.1 Beta (17B25c)
- browser:chrome Version 61.0.3163.100 (Official Build) (64-bit) and Safari Version 11.0.1 (13604.3.1)
- socket.io version:4.2.0

**Comment by darrachequesne** [comment]
@Daxong are you calling the `clients` method? with which parameters? The `fn` argument at this [line](https://github.com/socketio/socket.io-adapter/blob/1.1.1/index.js#L210) seems invalid.

Reference: https://github.com/socketio/socket.io/blob/master/docs/API.md#namespaceclientscallback

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
