### ISSUE TITLE
Not getting actual socket id on disconnection.

### ISSUE THREAD

**Issue by royaldevdevbrat** [socketio/socket.io#3080]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

var allClients = [];
io.sockets.on('connection', function(socket) {
   allClients.push(socket.id);

   socket.on('disconnect', function() {
      console.log('Got disconnect!');

      var i = allClients.indexOf(socket.id);
      allClients.splice(i, 1);
   });
});

### You want to:
I want to remove disconnected socket client based on its id but it's not coming actual id.
* [x] report a *bug*

### Current behavior
It is giving last connected socket id instead of socket id which is disconnected.

### Steps to reproduce (if the current behavior is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behavior
It should give actual socket id which is disconnected.

### Setup
- OS:
- browser:
- socket.io version:

**Comment by darrachequesne** [comment]
Hi! Any particular reason you are not using a `Set` here?

Note: you can add "```js" ... "`` `" around your code so that it will be more readable

**Comment by royaldevdevbrat** [comment]
No, I have tried with setting resource as well, I am getting the same problem.

**Comment by darrachequesne** [comment]
I'm not sure to understand what you are trying to achieve. What I meant was:
```js
let allClients = new Set();

io.sockets.on('connection', function(socket) {
  allClients.add(socket.id);

  socket.on('disconnect', function() {
    console.log('Got disconnect!');

    allClients.delete(socket.id);
  });
});
```

**Comment by taufiqGit** [comment]
thanks bro @darrachequesne
