### ISSUE TITLE
Closing adapter connection

### ISSUE THREAD

**Issue by sorokinsh** [socketio/socket.io#3081]
Hello! I use my own implementation of adapter for `socket.io` based on `rabbitmq`. The problem is that when `socket.io` server becomes disconnected, `rabbitmq` connection stays alive and it's hard to close it. Is it possible to add `close` method to "abstract" adapter and call this method when server `close` method is called?

**Comment by darrachequesne** [comment]
How about listening to the `close` event ([ref](https://nodejs.org/api/net.html#net_event_close)) emitted by the server? Would that work for you?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
