### ISSUE TITLE
socket.io Chat example iis host 404 error

### ISSUE THREAD

**Issue by canaktepe** [socketio/socket.io#3084]
I want to host this example on IIS. However, the http: //localhost/socket.io path gives a 404 not found error.

**Comment by canaktepe** [comment]
[https://pasteboard.co/GOK4o07.png](url)

`<script src="/socket.io/socket.io.js"></script>`

That's the javascript path. but it always gives a 404 error.

**Comment by zelongc** [comment]
Sam problem here

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
