### ISSUE TITLE
Error after adding Cloudflare DDOS protection and Cloudflare signed SSL certificate

### ISSUE THREAD

**Issue by KnottyCord** [socketio/socket.io#3085]
### You want to:

* [x] report a *bug*

### Current behaviour

When I got on my site and look in the Google Dev Console I see this error:
Failed to load https://www.csgofullcasino.com:8443/socket.io/?EIO=3&transport=polling&t=LyJQ9P1: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.csgofullcasino.com' is therefore not allowed access. The response had HTTP status code 521.

### Setup
- OS: Windows 10
- Server OS: Ubuntu 17
- browser: Google Chrome
- socket.io version: 1.4.5

**Comment by brenc** [comment]
This isn't related to `socket.io` but it's a pretty simple fix. Google CORS.

**Comment by KnottyCord** [comment]
@brenc Where to I change that the "Google CORD"?

**Comment by KnottyCord** [comment]
@brenc And I get this error: socket.io-1.4.5.js:934 GET https://www.csgofullcasino.com:8443/socket.io/?EIO=3&transport=polling&t=LyL_V-R net::ERR_ABORTED

**Comment by brenc** [comment]
You have to reconfigure your web server:

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

https://github.com/expressjs/cors

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
