### ISSUE TITLE
Gets multiple events call back from angular end

### ISSUE THREAD

**Issue by NilendraSarathchandra** [socketio/socket.io#3086]
(X) *****************First Scenario*****************
We have a web application and we are using socket.io as middleware . There is a angular end and there are api from .net. and its a chat application, when a user sends a message it calls for the socket server and from socket server we call to the api and we send the message to the particular socket. but when we send the message to the client the client event gets called multiple times(not every time but sometimes) from angular end but the message, we have only send once from server(we set a logger to confirm this from server end). We have azure linux server. We are pooling socket ids from user ids as rooms. Though we removed rooms and added a manual array to pool sockets ids from user ids issue still exists. Working fine on android and ios devices.

*******************Second scenario***************
when we disconnect internet connection and reconnect the connection gets connect to the server and we send a message after that it does sends the message to other end, but if we are sending messages from other end, messages are not coming to this end, from loggers in server it shows that messages are sent. to the particular socket ids.

### Setup
- socket.io version: V2.0.3
- node 6.11.4

**Comment by darrachequesne** [comment]
Hi! It sounds like your listeners ("`client.on()`") are registered multiple times (or not at all, on the second scenario). Could you check please, or provide some code?

**Comment by NilendraSarathchandra** [comment]
@darrachequesne  your assistance is highly appreciated here is our angular code,

angular.module('xxx.services').factory('socketIOService', ['$rootScope', '$cookies', '$timeout', 'UtilitiesServices', function ($rootScope, $cookies, $timeout, UtilitiesServices) {
  var socket
  return {
    on: function (eventName, callback) {
      if (socket !== undefined) {
        socket.on(eventName, callback)
      }
    },
    emit: function (eventName, data) {
      if (socket !== undefined) {
        socket.emit(eventName, data)
      }
    },
    connect: function (callback) {
      if (socket === undefined) {
        socket = io.connect(UtilitiesServices.socketServerURL, {
          forceNew: true
        })
        var tokenData = {}
        tokenData.AuthToken = $cookies.get('token_Hire')
        tokenData.UserType = 2
        socket.emit('AuthorizationToken', tokenData)
      }

      socket.on('MessageReceived', function (data) {
        $rootScope.$broadcast('newMessageReceived', data)
      })

      // exception found
      socket.on('Exception', function (data) {
        console.log('Exception HIRE')
        console.log(data)
      })
    },
    // reconnect connection
    reconnect: function () {
      if (!socket.connected) {
        socket = io.connect(UtilitiesServices.socketServerURL, {
          forceNew: true
        })
        var tokenData = {}
        tokenData.AuthToken = $cookies.get('token_Hire')
        tokenData.UserType = 2
        socket.emit('AuthorizationToken', tokenData)
      }
    },
    // disconnect socket
    disconnect: function () {
      if (socket.connected) {
        socket.close()
      }
    },
    getConnectionStatus: function () {
      if (socket) {
        return socket.connected
      } else {
        return socket
      }
    },
    removeListener: function (name) {
      socket.removeListener(name)
    }
  }
}])

**Comment by darrachequesne** [comment]
I don't know how the service is used, but the `reconnect` part seems wrong, since reconnection is already handled by the client, and here you're creating a new connection. Also, if you're calling `connect` twice, you'll have two handlers for `MessageReceived`  and `Exception` events.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
