### ISSUE TITLE
how to persist the socket.io connection

### ISSUE THREAD

**Issue by rdy23x** [socketio/socket.io#3088]
i want to persist the socket.io connection between my server and my clients
please can you help me

**Comment by darrachequesne** [comment]
May I ask what you do mean by `persist`? Could you give us more details about what you are trying to achieve please?

**Comment by johnjspiteri** [comment]
A good example would be to save the socket id once the user is connected to the server, and delete the socket reference once the user disconnects. 

You can also clear the sockets when the user connects if you have issues with the disconnection save.

Here is an example using MongoDB.

```
io.on('connection', function(socket){
	var user_id = '';
        // Update socket id on connection
	socket.on('join', function(data){
                // Pass in the user's id
		user_id = data._id;

		// Save socket.id on load
		console.log('connected socket:', socket.id);

		User.findById(user_id, function(err, user) {
			if(err) return err;
                        // Clear the sockets here
			user.sockets = [];
			user.sockets.push(socket.id);
			user.save(function(err, user) {
				if(err) console.log(err);
				console.log('sockets after connecting:', user.sockets);
			});
		});
	});
});
```

**Comment by darrachequesne** [comment]
For future readers: please see the example [here](http://localhost:4000/get-started/private-messaging-part-2/#Persistent-session-ID).

**Comment by Gbahdeyboh** [comment]
@darrachequesne the example leads to a localhost

**Comment by alkiskal** [comment]
https://socket.io/get-started/private-messaging-part-2/

I guess this is the link that @darrachequesne meant to post
