### ISSUE TITLE
How to disconnect the connected user in socket.io

### ISSUE THREAD

**Issue by DurgaPrasadGavara** [socketio/socket.io#3090]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:
- browser:
- socket.io version:

**Comment by darrachequesne** [comment]
Documentation: [`socket.disconnect()`](https://socket.io/docs/v3/server-api/#socket-disconnect-close)
