### ISSUE TITLE
YOUR WEBSITE IS DOWN

### ISSUE THREAD

**Issue by KyleWMiller** [socketio/socket.io#3091]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

connect to your website

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

I can't connect do to a 503 error

### Steps to reproduce (if the current behaviour is a bug)

try to visit your own website

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour

the docs to come up

### Setup
- OS: Sierra OSx
- browser: chrome
- socket.io version: 2.0.3

**Comment by darrachequesne** [comment]
Our provider experienced an outage yesterday (https://zeit-status.co/), it should be fixed now. Sorry for the inconvenience!
