### ISSUE TITLE
In chat example is there only one `addedUser` variable?

### ISSUE THREAD

**Issue by teremyx** [socketio/socket.io#3092]
I tried to understand the chat example and I have a question concerning the `addedUser` variable. 
If 2 clients connect, client1 and client2. And client2's "add user" event is received before that of client1. Then `addedUser` is set to `true` because of the `add user` event for client2. Then when `add user` of client1 is received, the function returns, because `addedUser` is already set to `true`. 

There is only one `addedUser` variable, right? Or is one created for every client/connection? 

[https://github.com/socketio/socket.io/blob/master/examples/chat/index.js](url)

**Comment by darrachequesne** [comment]
An `addedUser` variable is created for each connection:
```js
io.on('connection', function (socket) {
  var addedUser = false;
  ...
```

**Comment by teremyx** [comment]
Thank you, that answers my question. So it's reasonable to save connection specific data inside that block? I know socket has an username attribute, but it would also work if I save the username in a var `username` inside that block ( next to `addedUser` ), right?

**Comment by darrachequesne** [comment]
@teremyx yes, you should be able to use an `username` variable in the `function (socket) {}` scope.

**Comment by teremyx** [comment]
Thanks again for the clarification.
