### ISSUE TITLE
When I install the app it gives me an error message saying "Failed To Connect" Even when I have connected to the network

### ISSUE THREAD

**Issue by paulabhishek** [socketio/socket.io#3094]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [x] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:
- browser:
- socket.io version:

**Comment by 1998abhishekpaul** [comment]
someone help!

**Comment by darrachequesne** [comment]
For future readers: please see https://socket.io/docs/v3/troubleshooting-connection-issues/
