### ISSUE TITLE
Socket still fires event after disconnect

### ISSUE THREAD

**Issue by wagenaartje** [socketio/socket.io#3095]
### You want to:

* [x] report a *bug*

### Current behaviour
I'm sending certain tasks to connected clients (all using Chrome), the clients then send back the result of the task. Of course, all tasks need to be completed and thus a task should be sent to another client when the first client disconnects.

So this is what is happening:

- SERVER sends task to CLIENT
- CLIENT disconnects (fires `socket.on('disconnect', ...)`)
- SERVER removes CLIENT from the task's client list and appoints task to new CLIENT2
- CLIENT sends a message with task results (fires `socket.on('completion', ...)`)

I have no idea how this is even possible. I have spent literally days trying to understand why the server would freeze and I just discovered this by doing the following:

```js
  socket.on('completion', function (data) {
    console.log('Completing task...', socket.connected); // logs 'false'
    // do something
  });
```

### Steps to reproduce (if the current behaviour is a bug)

I can't really give 'steps'. All I can say is that i'm sending tasks to the client that are finished within a second, and i'm sending 1000s of them sequentially. I should also mention that each client has X sockets doing tasks, one for every CPU core.

### Expected behaviour
Should not fire an event when disconnected.

### Setup
- OS: Windows 10
- browser: Chrome
- socket.io version: latest

**Comment by xPaw** [comment]
I believe I found out why this happens.

If I'm reading the code right, it emits normal events in `process.nextTick` in `ondecoded` and then in `dispatch`, but it appears that `onclose` would be emitted instantly, so it can be 2 ticks behind?

Could any of the developers confirm that this is what is happening?

**Comment by darrachequesne** [comment]
For future readers: this was (finally) fixed by https://github.com/socketio/socket.io/commit/494c64e44f645cbd24c645f1186d203789e84af0 and included in [`socket.io@3.1.2`](https://github.com/socketio/socket.io/releases/tag/3.1.2).
