### ISSUE TITLE
How can we check if socket is already joined a room ?

### ISSUE THREAD

**Issue by soravmobi** [socketio/socket.io#3096]
Hi,
I am creating unique room while Group calling, i want to know if same socket already connected or joined in other rooms, i mean want to filter socket id in all rooms, please let me know if there is any method to check socket id in all created rooms ?

**Comment by KristjanTammekivi** [comment]
`io.on('connection', function(socket){
  socket.join('room1');
  console.log(socket.rooms); // contains an object with all of the roomnames as keys and values
})`

**Comment by rraallvv** [comment]
For me the log shows the same output before and after the call to join a room, any idea why is that the case?

```
console.log(socket.rooms);
socket.join("mychannel");
console.log(socket.rooms);
```

**Comment by darrachequesne** [comment]
Documentation: https://socket.io/docs/v3/server-socket-instance/#Socket-rooms

**Comment by mominrazashahid** [comment]
> For me the log shows the same output before and after the call to join a room, i.e. the room "mychannel" doesn't show up in `socket.rooms`, any idea why is that the case?
> 
> ```
> console.log(socket.rooms);
> socket.join("mychannel");
> console.log(socket.rooms);
> ```

same for me
