### ISSUE TITLE
socketio does not maintain websocket transport

### ISSUE THREAD

**Issue by hungtp** [socketio/socket.io#3097]
Hi,
In my socketio app, I set my transport to websocket only (on both server & client side). However, when I capture my app traffic by wireshark, it only use websocket for a short time then it is switched to tcp protocol.

One more thing, it seems packet sent from client side is encoded but the packet sent from server side is not, all my data was exposed in plain text. Do I need to do something with parser on server side to be able to encode packet? (I'm using default parser of socketio)

## Environment
* Server: Nodejs
* Framework: Express 4.15.2
* Socket.io version: 2.0.3

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
