### ISSUE TITLE
socketio: emit inside EventEmitter handler 

### ISSUE THREAD

**Issue by YouneLL** [socketio/socket.io#3098]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

I have web socket server and http server, and I want to tell socketio server to emit an event to user only if an event was emitted using EventEmitter Class, the problem is when I open 2 tabs in browser I noticed that the event was sent to all users (broadcasting)

### Steps to reproduce (if the current behaviour is a bug)

server.js:

    const server = require('http').createServer(handler)
        , io = require('socket.io')(server)
        , url = require('url')
        , fs = require('fs')
        , EventEmitter = require('events')
        , emitter = new EventEmitter();

    server.listen(3000);

    function handler(req, res) {

        var route = url.parse(req.url).pathname;

        if (route === '/') {
            var stream = fs.createReadStream(__dirname + '/index.html');
            stream.pipe(res);
        } else if (route === '/testSocket') {
            var stream = fs.createReadStream(__dirname + '/test.html');
            stream.pipe(res);
            // emit event after 5s, the handler is inside socketio server
            setTimeout( function() {
                emitter.emit('fromEmitterToSocketServer', 'Msg');
            }, 5000);
        } else {
            res.writeHead(404, {"Content-Type": "text/plain"});
            res.end('404');
        }

    }

    io.on('connection', function (socket) {
    
        // handle event and then send data to the user
        emitter.on('fromEmitterToSocketServer', function(data) {

            // here I noticed that socketio emit the event to all users
            socket.emit('fromSocketServerToClient', data); 

        });
        
    });

index.html:

    <!doctype html>
	<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Index</title>
	</head>

	<body>

		<h1>Index</h1>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.3/socket.io.js"></script>
		<script>

			var socket = io('//localhost:3000');

			socket.on('fromSocketServerToClient', function (data) {
				console.log(data);
			});

		</script>
		
	</body>

	</html>

test.html:

    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Test socketIO</title>
    </head>

    <body>

        <h1>Test socketIO</h1>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.3/socket.io.js"></script>
        <script>

            var socket = io('//localhost:3000');

            socket.on('fromSocketServerToClient', function (data) {
                console.log(data);
            });

        </script>
    </body>
    </html>

launch server `node server.js` and then open two tabs and go to http://localhost:3000 and http://localhost:3000/testSocket after 5s socketio will emit event to testSocket page and log the data, but also on index page which is not the default behavior.

### Expected behaviour

socketio server should emit the event to testSocket page only

### Setup
- OS: win7
- browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)
- socket.io version: 2.0.4

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
