### ISSUE TITLE
uWS support is a bit broken on Windows

### ISSUE THREAD

**Issue by luffs** [socketio/socket.io#3100]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Only in Windows when using uWs:
Huge delay between websocket data is parsed, and event is emitted to server event listeners, when more than one client is connected.

### Steps to reproduce

1. Make a server, listen to "test" event. Start with env DEBUG=socket.io*
2. Open a browser, emit "test" event to server; everything is fine.
3. Open same page in another tab. You should now have 2 connected clients.
4. Emit "test" event in browser from the console. There is now a huge delay until the event listener in step 1 is fired.
5. Emit event twice, socket.emit('test', {}); socket.emit('test', {}); and the first event fires directly, and there is a huge delay on the second one.
5. Close the second browser tab and emit some events again. The delay is gone.

### Expected behaviour

Event emitter should fire within 1-2ms.

### Setup
- OS: Windows 10 x64
- browser: tested in both Chrome and Firefox
- socket.io version: 2.0.4

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

  socket.io:server initializing namespace / +0ms
  socket.io-parser encoding packet {"type":0,"nsp":"/"} +3ms
  socket.io-parser encoded {"type":0,"nsp":"/"} as 0 +0ms
  socket.io:server creating engine.io instance with opts {"path":"/socket.io","initialPacket":["0"]} +1ms
  socket.io:server attaching client serving req handler +5ms
  socket.io:server incoming connection with id uLSPqVnrkgVklbmJAAAA +1s
  socket.io:client connecting to namespace / +2ms
  socket.io:namespace adding socket to nsp / +0ms
  socket.io:socket socket connected - writing packet +4ms
  socket.io:socket joining room uLSPqVnrkgVklbmJAAAA +1ms
  socket.io:socket packet already sent in initial handshake +1ms
**user connected** <-- FIRST CLIENT CONNECTED
  socket.io:socket joined room uLSPqVnrkgVklbmJAAAA +3ms
  socket.io-parser decoded 2["test",{}] as {"type":2,"nsp":"/","data":["test",{}]} +4s
  socket.io:socket got packet {"type":2,"nsp":"/","data":["test",{}]} **+1ms**
  socket.io:socket emitting event ["test",{}] +0ms
  socket.io:socket dispatching an event ["test",{}] +0ms
test {}
  socket.io:server incoming connection with id QfIEBNCsI5InQCrgAAAB +15s
  socket.io:client connecting to namespace / +0ms
  socket.io:namespace adding socket to nsp / +0ms
  socket.io:socket socket connected - writing packet +1ms
  socket.io:socket joining room QfIEBNCsI5InQCrgAAAB +0ms
  socket.io:socket packet already sent in initial handshake +0ms
**user connected** <--- ANOTHER CLIENT CONNECTED 
  socket.io:socket joined room QfIEBNCsI5InQCrgAAAB +1ms
  socket.io-parser decoded 2["test",{}] as {"type":2,"nsp":"/","data":["test",{}]} +5s
  socket.io:socket got packet {"type":2,"nsp":"/","data":["test",{}]} **+20s <--- THIS IS THE PROBLEM, 20sec delay!**
  socket.io:socket emitting event ["test",{}] +1ms
  socket.io:socket dispatching an event ["test",{}] +0ms
test {}
  socket.io:client client close with reason transport close +7s
  **socket.io:socket closing socket - reason transport close +1ms**  <--- DISCONNECTED ONE CLIENT
  socket.io-parser decoded 2["test",{}] as {"type":2,"nsp":"/","data":["test",{}]} +5s
  socket.io:socket got packet {"type":2,"nsp":"/","data":["test",{}]} **+1ms**
  socket.io:socket emitting event ["test",{}] +0ms
  socket.io:socket dispatching an event ["test",{}] +0ms
test {}

A workaround is to change the wsEngine to ws in the options:
`const io = require('socket.io')(httpServer, { wsEngine: 'ws' });`

**Comment by afterx** [comment]
I seem to be having the same issue on windows 7 latest chrome.  Updating my krama timeout made it run, but extremely slow.
```
06 11 2017 07:30:**23**.179:INFO [launcher]: Starting browser ChromeHeadless
06 11 2017 07:30:**32**.444:WARN [karma]: No captured browser, open http://localhost:9876/
06 11 2017 07:30:43.738:INFO [HeadlessChrome 0.0.0 (Windows 7 0.0.0)]: Connected on socket 
```

**Comment by Hughp135** [comment]
I'm getting this too! It's been driving me crazy.

Windows 10. Happens in either chrome or firefox. Does not occur on my macbook.

Basically, with 2 clients connected, some emits are basically ignored until some other code gets triggered on the server. If nothing gets triggered, it can be delayed for several seconds before a reply is received. Here is an example:

With only 1 client connected:

```
client emits 1
server replies 1
client emits 2
server replies 2
```

with 2 clients connected:

```
client emits 1
client emits 2
server replies 1
client emits 3
server replies 2
...
server replies 3
```

I've noticed that setting a random interval function on the server can trigger the emits to be triggered as soon as the interval ticks. E.g. if you add this code randomly anywhere on the server, it will pick up any emits ever 50 ms and send the reply immediately. 

```
setInterval(()=> {
    console.log('tick');
  }, 50)
```

**Comment by ulikus** [comment]
Same applies to socket,io.

**Comment by navelencia** [comment]
I get the exact same behavior. Would be nice to have a fix with uws.

**Comment by igabesz** [comment]
I confirm this issue. I see the same behavior in Win 10 -- but it works correctly in the Linux subsystem of Win 10. (Same codebase, just reinstalled node_modules.) The fix from @Hughp135 fix works for me too:

```js
	if (/^win/.test(process.platform)) {
		console.warn('Starting uws bug-hack interval under Windows');
		setInterval(() => {}, 50);
	}
```

**Comment by jsieler** [comment]
Same happens to me on Windows 7 machine, where is working well on Debian (with same code).

**Comment by zz1985summer** [comment]
Thank you so much,this issue confued me serval days,finally got your tips!!thank you !

**Comment by darrachequesne** [comment]
For future readers: `ws` was reverted as the default WebSocket server implementation in `socket.io@2.1.0`.

Documentation: https://socket.io/docs/v3/server-installation/#Other-WebSocket-server-implementations
