### ISSUE TITLE
socket error {"type":"TransportError","description":0}

### ISSUE THREAD

**Issue by sajaddp** [socketio/socket.io#3102]
* [x] report a *bug*

Hello,
We encountered this error several times:
`net::ERR_EMPTY_RESPONSE`
After debugging, we get this error code:
`socket error {"type":"TransportError","description":0}`
We tried to get help by asking a question in stackoverflow, but they rejected it.

What this error relates to?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
