### ISSUE TITLE
Using socket.io with koa2

### ISSUE THREAD

**Issue by Nahasean94** [socketio/socket.io#3107]
Does anyone have a comprehensive guide for how to use socket.io with koa2? 
Below are some of the things it should teach:
1 Broadcast a message to connected users when someone connects or disconnects
2. Add support for nicknames
3. Don’t send the same message to the user that sent it himself. Instead, append the message directly as soon as he presses enter.
4. Add “{user} is typing” functionality
5. Show who’s online
6. Add private messaging

**Comment by johnjspiteri** [comment]
@Nahasean94, you will have much better luck getting help if you break apart these requests... you will get answers individually, usually with other points of view that you can research and develop further.
