### ISSUE TITLE
This dependency was not found:  * fs in ./node_modules/socket.io/lib/index.js

### ISSUE THREAD

**Issue by zhuhaoming2** [socketio/socket.io#3112]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:
- browser:
- socket.io version:

**Comment by Dwood15** [comment]
Are you using webpack?

In your Webpack Config, add: node: { fs: 'empty' }.

**Comment by thelonecabbage** [comment]
npm i fs@0.0.2

**Comment by darrachequesne** [comment]
Hi! Is there something we can fix? Could you provide more context please?

**Comment by Dwood15** [comment]
@darrachequesne anything you can do to make it so when running webpack, we don't need  node: { fs: 'empty' } ?

**Comment by darrachequesne** [comment]
@Dwood15 it seems `{ fs: 'empty' }` was not needed in our webpack [example](https://github.com/socketio/socket.io/tree/master/examples/webpack-build-server), could you please check?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
