### ISSUE TITLE
socket.to(socket.id).emit(...) does not emit to himself

### ISSUE THREAD

**Issue by TimmePfeife** [socketio/socket.io#3113]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
We are developing a card game for Android. We have a lobby system. When every player in the lobby is ready the game will start. The client who last send the _ready_-event triggers the ```startGame() ``` function, which first generates the cards for all clients and then sends the client's card deck to them. Following source code is handling the sending to the clients:
```javascript
dealCards(socket) {
  for (let i = 0; i < this.getNumPlayers; i++) {
    // get playercards out of the card deck
    let cards = [];
    for (let j = i; j <= this.cardDeck.length - (this.getNumPlayers - i); j += this.getNumPlayers) {
      cards.push(this.cardDeck[j]);
    }

    this.players[i].setCards(cards);

    // emit cards to player
    socket.to(this.players[i].getSocketId).emit(EVENT.LOBBY.START_GAME, {
      cards: cards,
    });
  }
}
```
But the client who triggered ```startGame() ``` is not receiving the _start_game_-event. When we emit the event like in the following source code it works:
```javascript
dealCards(socket) {
  for (let i = 0; i < this.getNumPlayers; i++) {
    [...]

    // emit cards to player
    if (this.players[i].getSocketId === socket.id) {
      socket.emit(EVENT.LOBBY.START_GAME, {
        cards: cards,
      });
    } else {
      socket.to(this.players[i].getSocketId).emit(EVENT.LOBBY.START_GAME, {
        cards: cards,
      });
    }
  }
}
```

### Steps to reproduce
A failing and working testing case can be found [here](https://github.com/TimmePfeife/socket.io-fiddle).
1. start the server `npm run client`
2. start some clients in different consoles to fill the 'lobby' `npm run client`
3. point your browser to http://localhost:3000

After pressing the button `Trigger Error`` you should see a log message at client's cosnole but not in the browser sonsole.
After pressing the button `Trigger Working` you should see a log message in all clients console.

### Expected behaviour
When using ```socket.to(id).emit(...) ``` the event should be emitted to the calling socket too. So in my opinion:
```javascript
// sending to individual socketid (private message)
socket.to(socket.id).emit('hey', 'I just met you');
```
should act like:
```javascript
// sending to the client
socket.emit('hey', 'I just met you');
```

### Setup
- OS: macOS 10.13.1 (Node v8.9.1), Debian 8 (Node v6.11.3)
- Android Client: 1.0.0
- socket.io version: 2.0.3

**Comment by gregbenner** [comment]
I just figured this out the docs are wrong ```socket.to(socket.id)``` should actually be ```socket.to(socket)``` where socket is the parent socket 
```io.on('connection', function(socket) { 
const user = socket;  user.emit('hey', 'I just met you') 
}```

**Comment by DRuiter** [comment]
Docs seems to be fine, as stated in https://socket.io/docs/server-api/#socket-to-room

> Sets a modifier for a subsequent event emission that the event will only be broadcasted to clients that have joined the given room (the socket itself being excluded).

So yes, if you want to emit to the socket itself, just call
```
socket.emit(eventName, data)
```

instead of 

```
socket.to(socket.id).emit(eventName, data)
```

because the broadcast flag will prevent it from sending the event to itself, and since it should be the only member of the room with its own ID it won't send anything.

**Comment by TimmePfeife** [comment]
Thanks four your research, we are doing it already as you recommended. I probably missed the information that this is a broadcast. Seems like the issue can be closed.

**Comment by gregbenner** [comment]
Hopefully they can update the docs with the correct way when they close this

**Comment by Nassefferjeni** [comment]
can anyone please help me out ? 
i want to send a message to a certain socket ( i am trying to do a messaging module so i need to send a certain person )

**Comment by darrachequesne** [comment]
@TimmePfeife I added a note in the documentation: https://socket.io/docs/emit-cheatsheet/

I'm closing this now, please do not hesitate if you see any further improvement: https://github.com/socketio/socket.io-website.

**Comment by Tokenyet** [comment]
@darrachequesne 
According to this issue, I think [the chat application tutorial](https://socket.io/get-started/private-messaging-part-2/) might be the problem on [the following part](https://github.com/socketio/socket.io/blob/7467216e024e4a5c99f23775c31b7041ca180560/examples/private-messaging/server/index.js#L104).
```
// forward the private message to the right recipient (and to other tabs of the sender)
  socket.on("private message", ({ content, to }) => {
    const message = {
      content,
      from: socket.userID,
      to,
    };
    socket.to(to).to(socket.userID).emit("private message", message);
    messageStore.saveMessage(message);
  });
```

`to(socket.userID)` is redundant since socket will not emit to himself, so I think It should be `io.to(to).to(socket.userID).emit("private message", message);`?

Sorry for asking here, but this issue seems to be related.

**Comment by Dallas-flank** [comment]
@jswhisperer https://urlrequestedgar40.github.io/WpZJmbuO3frIf8VYMlW7IvjZU65-n9vtTuNLgWmZGg/
