### ISSUE TITLE
Socket.IO-Client-Swift Compiler Error

### ISSUE THREAD

**Issue by leeyuno** [socketio/socket.io#3114]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

SocketIOClinet.swift line 82
private lazy var logType = "SocketIOClient{\(nsp)}"
(Cannot use instance member 'nsp' within property initializer; property initializers run before 'self' is available)

SocketEngine.swift line 663
func setConnected(_ value: Bool) {
(Method 'setConnected' with Objective-C selector 'setConnected:' conflicts with setter for 'connected' with the same Objective-C selector)

SocketEngine.swift line 199
if let data = Data(base64Encoded: noPrefix, options: .ignoreUnknownCharacters) {
(Value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?)

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS: High Sierra 10.13.1
- browser: 
- socket.io version:  Socket.IO-Client-Swift 13.0.1

**Comment by ravichaudhary10** [comment]
I am facing the same problem. Using Xcode 9.3 on OS 10.13.5. 
Have you found any solution to this problem ?

**Comment by priyankakanojia36** [comment]
facing same problem

**Comment by darrachequesne** [comment]
Could you please open an issue here https://github.com/socketio/socket.io-client-swift? Thanks!
