### ISSUE TITLE
socket.on arguments non consistent

### ISSUE THREAD

**Issue by legraina** [socketio/socket.io#3115]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
When handling emit and emitWithAck on the server side, there is some issue to retrieve the arguments correctly. The arguments of the callback of socket.on(k, function(data, callback)) are not consistent.

1- client sends: socket.emit(k);
server receives: data = undefined and nothing for callback

2- client sends: socket.emit(k, data);
server receives: data = data and callback=undefined

3- client sends: socket.emitWithAck(k);
server receives: data = [Func] and nothing for callback

### Expected behaviour

I think it makes more sense to have in 3- data = undefined and callback=[Func]

### Setup
- OS:
- browser: Chrome
- socket.io version: 2.0.1 (client and server)

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

What I've done on my side to fix that:

if (typeof data === 'function') {
      callback = data;
      data = null;
}

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by e-lwanga** [comment]
This bug disturbs me too, for some reason the callback is inconsistent. I would suggest that it always be the second argument. As an addition to the bug above when the client calls socket.emitWithAck(eventName, [someData,someData,someData], callback); the server will receive socket.on(eventName, (arg1,arg2,arg3,callback)=>{}); this makes the method more inconsistent
