### ISSUE TITLE
[x 2.0.3 ,the client  close when your server to send chinese sentence,]

### ISSUE THREAD

**Issue by wuteng606** [socketio/socket.io#3117]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:
- browser:
- socket.io version:

**Comment by wuteng606** [comment]
in 2.0.3 ,the client will be closed when your server send a chinese sentence.   the error is transport close

**Comment by gooddaddy** [comment]
@wuteng606 
me too（i use socket.io 2.0.4）

**Comment by Chopinsky** [comment]
I couldn't reproduce this issue, I'm using express 4.16.2 and socket.io 2.0.4, and messages containing Chinese characters can be sent to/from the express server.

**Comment by gooddaddy** [comment]
@Chopinsky 
I'm using express 4.16.2 and socket.io 2.0.4 too,and I did it like this 
`io.of("/webPush").connected[socketId].emit('scanLogin',"一发中文就断网，啥玩意啊");`
then the error is transport close.
if I use `io.of("/webPush").connected[socketId].emit('scanLogin',"111");`
it work well

**Comment by gooddaddy** [comment]
@Chopinsky 
I konw why，maybe it was that I use  “browser-sync” in debug-environment。“browser-sync” use socket.io(version 1.6.0)。I work well in release-environment。

**Comment by deanshub** [comment]
checkout #3126

**Comment by awtmeng** [comment]
@gooddaddy
According to your configuration, it doesn't take effect

**Comment by darrachequesne** [comment]
For future readers: I think that's because the version of the client and the server did not match (v1 and v2 were indeed incompatible).
