### ISSUE TITLE
Connection between server and android app not working over wifi

### ISSUE THREAD

**Issue by Saturnyn** [socketio/socket.io#3119]
Hi,

I have the following setup:
- a ionic 2 app running in android
- a nodejs server running on a local device (raspberry pi)

My local device creates a wifi hotspot, the android device connects to this wifi network and can talk to the server via socket.io.

Everything works fine except in the following scenario:
- the raspberry is not connected to the internet
- the android device is connected to the cellular network
In that case, the android device will not be able to connect to the server, it looks like it is looking on the wrong network interface.

This doesn't seem to be a bug inside socket.io but an issue with android giving priority to the network havng an access to the internet. (There is the same problem with plain http request and there is a lib that fixes it in that particular scenario: https://github.com/CanTireInnovations/cordova-plugin-httpOverWifi.
However, since it does affect socket.io)
Has anyone else encountered this problem already ?
Is there a workaround that I could try ?

Thanks

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by bonnebulle** [comment]
Exactly same here
Am doing a wifi hotspot on my pc (not intetnrt connected)
Works fine with an Android wifi hotspot
I checked Firewall ports, ip. Mybe Cors.
Any clue ? Thanks
