### ISSUE TITLE
Access-Control-Allow-Origin set to * despite setting origins

### ISSUE THREAD

**Issue by matewilk** [socketio/socket.io#3122]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Despite setting up origins to `xxxx.yyyy.zzz.www:3000` in the `socket.io` listener and the exact same address in the `socket.io-client` connect method the `Access-Control-Allow-Origin` is set to `*` when starting the app. It happens only with `GET` requests.

### Steps to reproduce (if the current behaviour is a bug)
Start server side `socket.io` with the following params:
```
exports.start = (server) => {
    io = exports.socketio.socketio.listen(server, {
        origins: 'https://xxxx.yyyy.zzz.www:3000'
        rejectUnauthorized: false,
        wsEngine: 'ws',
        transports: ['websocket', 'polling']
    });
    exports.connect();
};
```

Start client side `socket.io-client` with the following params:
```
let socket = socketIoClient.io.connect(
        'https://xxxx.yyyy.zzz.www:3000',
        { 
            secure: true, 
            rejectUnauthorized: false
        });
```

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
When inspecting the headers of the `socket.io` communication I expect the `Access-Control-Allow-Origin` header to be set to `https://xxxx.yyyy.zzz.www:3000`

### Current behaviour
The `Access-Control-Allow-Origin` header is set to `*` for `GET` requests
<img width="1068" alt="screen shot 2017-11-21 at 16 37 19" src="https://user-images.githubusercontent.com/6328360/33127497-98c61c5a-cf80-11e7-997a-6d3e63e6d0f4.png">
Please ignore the fact on the above screen that it shows `localhost` it happens on the production server too, but because of the security, I had to post the response without revealing the ip address (thank you)  

### Setup
- OS: Mac, Linux
- browser: Chrome
- socket.io version: 2.0.4

**Comment by barisusakli** [comment]
I think the culprit is in engine.io https://github.com/socketio/engine.io/search?utf8=%E2%9C%93&q=Access-Control-Allow-Origin

There are two places where the header is set to '*' if `req.headers.origin` is not set.

If `req.headers.origin` is set then the header is set to that value without respecing the `io.origins()` setting.

**Comment by FabianElsmer** [comment]
This is fixed in Engine.IO v4: [https://github.com/socketio/engine.io/issues/569](url)

Is there a rough schedule when we can expect SocketIO to use Engine.IO v4?
I'm guessing there are some breaking changes that are currently being updated in SocketIO?

**Comment by darrachequesne** [comment]
@FabianElsmer there are a few additional changes that we'd like to include in Socket.IO v3, but I think we'll have a release candidate by next week.

**Comment by darrachequesne** [comment]
Here you are: [3.0.0-rc1](https://github.com/socketio/socket.io/releases/tag/3.0.0-rc1)

The new syntax:

```js
new Server(3000, {
  cors: {
    origin: "https://example.com",
    methods: ["GET", "POST"],
    allowedHeaders: ["content-type"]
  }
});
```

instead of:

```js
new Server(3000, {
  origins: ["https://example.com"]
});
```

Feedback is welcome!

**Comment by phffmn** [comment]
since origin is not an array anymore, how can this be used with several domains?

**Comment by darrachequesne** [comment]
@phffmn you can provide an array too:

```js
new Server(3000, {
  cors: {
    origin: ["https://example.com", "https://dev.example.com"],
    methods: ["GET", "POST"],
    allowedHeaders: ["content-type"]
  }
});
```

In fact, all options are forwarded to the `cors` module. Reference:  https://www.npmjs.com/package/cors#configuration-options

I think this issue can now be closed.
