### ISSUE TITLE
socket 2.03 raises error400 when I use some accents or unicode chars.

### ISSUE THREAD

**Issue by yarekc** [socketio/socket.io#3123]
Hello
 I migrated from socket.io 1.45 to 2.03 (latest)
I use that client side: 

`socket.emit('enterRoom', myUser); `

if I use in some myUser properties some **UTF8** chars, **I will get a 400 BAD REQUEST error**

ex:

```
myUser.someting="héllo" // genarates a 400 error  
myUser.something = "hello" // works fine and everything works fine in socket.io 1.45 as well
```

Any idea ?

**Comment by Chopinsky** [comment]
Seems related to #3117. Though I couldn't reproduce the mentioned issue using 2.0.4, so this newer version may worth a try.

**Comment by darrachequesne** [comment]
For future readers: I think that's because the version of the client and the server did not match (v1 and v2 were indeed incompatible).
