### ISSUE TITLE
Socket hangs (no messages can be sent) after "RangeError: Invalid string length"

### ISSUE THREAD

**Issue by assaf-xm** [socketio/socket.io#3125]
Working with node v8.7.0
Socket io: 2.0.4
Socket-io-parser: 3.1.2

When **responding** to a message with a large object that serialized to a string larger than ~300MB, we get the exception:
_2017-11-24T04:04:06.732Z - error:  RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at encodeAsString (.../node_modules/socket.io-parser/index.js:173:17)
    at Encoder.encode (.../node_modules/socket.io-parser/index.js:137:20)
    at Manager.packet (.../node_modules/socket.io-client/lib/manager.js:421:18)
    at Socket.packet (.../node_modules/socket.io-client/lib/socket.js:173:11)
    at .../node_modules/socket.io-client/lib/socket.js:292:10
    at then (.../app/runner.js:111:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)_

While getting an error for this is ok (we don't really want these kind of messages to be sent), it gets the entire communication to hang. No more messages can be sent!!!

In order to reproduce you should respond to a message with a very large object (> 300MB) that will get to the **JSON.stringify** inside **encodeAsString** (socket.io-parser/index.js) and throw an exception.

PS: any other exception inside the JSON.stringify will hang the channel as well (for example other serialization errors).

Expected behavior: Catch these exceptions and return a proper error message, keeping the channel active.

Thanks,
Assaf

**Comment by paul-bell** [comment]
Hello,

I write both to second @assaf-xm's original post and to inquire concerning the status of  this issue.

I've hit the very same error. In my case the message was ~270MB long. While I agree with @chopinsky's "chunking" comment in #3135, it should not happen that the socket is no longer usable. 

So, yeah, the error is fine, but after catching it via try/catch, I should be able to continue communicating over the socket.

Thanks.

-Paul

**Comment by Renari** [comment]
I'm encountering this issue when sending a ~30mb base64 string.

**Comment by radinmoradi** [comment]
در تاریخ جمعه ۲۱ فوریهٔ ۲۰۲۰،‏ ۸:۵۰ Arie Miller <notifications@github.com>
نوشت:

**Comment by Renari** [comment]
https://github.com/zeit/pkg/issues/681

Tracked down the source of my issue it actually wasn't anything to do with socket.io.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by ankitkumaragarwal** [comment]
> [vercel/pkg#681](https://github.com/vercel/pkg/issues/681)
> 
> Tracked down the source of my issue it actually wasn't anything to do with socket.io.

Hi  could you advise where did you find the issue

**Comment by Renari** [comment]
> > [vercel/pkg#681](https://github.com/vercel/pkg/issues/681)
> > Tracked down the source of my issue it actually wasn't anything to do with socket.io.
> 
> Hi could you advise where did you find the issue, as we are facing a similar issue

I linked to it.

**Comment by ankitkumaragarwal** [comment]
> 

Hi didnt understand when you mentioned that you linked to it?

**Comment by Renari** [comment]
The original message has a link to the issue on the pkg repo that was causing my problem.
