### ISSUE TITLE
data strings changes over socket

### ISSUE THREAD

**Issue by yotamgever** [socketio/socket.io#3126]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
when emitting an object as data and within it using a string of ```≥``` (or the unicode ```\u2265```) it turns it to the string letter ```e``` and ```≤``` trurns to ```d```

### Steps to reproduce (if the current behaviour is a bug)
client side
```
channel.emit('data', {data:'≥'});
```
server side
```
socket.on('data',({data:bla})=>{
console.log(bla); // prints 'e'
});
```

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
that the data will stay the same consistently

### Setup
- OS: Windows
- browser: Chrome 62
- socket.io version: 1.7.2

**Comment by deanshub** [comment]
This happens only when the socket hasn't upgraded (first use) over xhr,
after it upgrades to websocket all data is sent correctly

**Comment by deanshub** [comment]
see #451 and #572

**Comment by darrachequesne** [comment]
There was an issue regarding utf8 parsing in version 1.x, could you please try with version 2.x ?

Related:
- https://github.com/socketio/socket.io/releases/tag/2.0.0
- https://github.com/socketio/engine.io-parser/pull/81

**Comment by deanshub** [comment]
tried it with 2.0.4, still happens...
fixed it with encoding and decoding the data with this code:
client side
```
function strencode( data ) {
	return encodeURIComponent( escape( JSON.stringify( data ) ) );
}
```
server side
```
function strdecode( data ) {
	return JSON.parse( unescape( decodeURIComponent( data ) ) );
}
```

**Comment by yotamgever** [comment]
Yeah that's seems to be working. Thanks!

**Comment by darrachequesne** [comment]
For future readers: I think that's because the version of the client and the server did not match (v1 and v2 were indeed incompatible).
