### ISSUE TITLE
problem with multiple io.attach on v2.0.*

### ISSUE THREAD

**Issue by chatziko** [socketio/socket.io#3127]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Attaching two servers and a middleware fails when an Error is passed to the middleware callback.
```
io.attach(server1, opt)
io.attach(server2, opt)
io.use((socket, next) => next(new Error('foo')))
```
Clients connect succesfully to one of the servers instead of getting an error.

The problem only appears with socket.io 2.0.*.

**Workaround**: The problem dissapears if
 * either `io.use` happens **before** both `io.attach`'s
 * or `io.use` happens **in-between** `io.attach` and `opt = null`

### Steps to reproduce (if the current behaviour is a bug)

I attach ([multi-attach-bug.zip](https://github.com/socketio/socket.io/files/1518521/multi-attach-bug.zip)) both a minimal server/client reproducing the issue, and a mocha test that tries all 6 combinations of `io.use` position with/without `opt`.

```
  ✓ before,    no opts (136ms)
  ✓ inbetween, no opts
  1) after,     no opts
  ✓ before,    with opts
  2) inbetween, with opts
  3) after,     with opts

  3 passing (226ms)
  3 failing
```

### Expected behaviour

Only the error event should be called when Error is passed to the middleware function.

### Setup
- OS: Ubuntu 17.10
- browser: -
- socket.io version: 2.0.*

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
