### ISSUE TITLE
One entry point for all events

### ISSUE THREAD

**Issue by FriOne** [socketio/socket.io#3128]
### You want to:

* [    ] report a *bug*
* [ x ] request a *feature*

### Current behaviour
io.on('event', (message) => {...stuff})

### Expected behaviour
io.on((eventName, message) => {...stuff})

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
It would be nice to have this, I'm trying to make server with `inversify`. What i want to is to create decorators for message controllers to handle incoming messages by name. But since socket.io doesn't have one entry point for events, I should to make many event listeners.

I guess it may be done with `socket.use(fn)` but it is a little bit hacky.

**Comment by darrachequesne** [comment]
What's wrong with using `socket.use`? Else, would [socketio-wildcard](https://www.npmjs.com/package/socketio-wildcard) suit your needs?

**Comment by FriOne** [comment]
Yeah, thanks
