### ISSUE TITLE
Can't connect to server after several hours

### ISSUE THREAD

**Issue by minotaurrr** [socketio/socket.io#3132]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
On Chrome - getting ERR_CONNECTION_REFUSED
Tried curling but getting - curl: (7) Failed to connect to localhost port 8095: Connection refused

### Steps to reproduce (if the current behaviour is a bug)
When I first start the server it's fine, clients can connect and get talk to the server.
I would disconnect all clients for about 5-6 hours then try to connect again but nothing can connect, looks like the server just shuts down automatically.

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
Expect the server to be running forever..

### Setup
- OS: Ubuntu
- browser: Chrome
- socket.io version: 2

**Comment by darrachequesne** [comment]
Do you get any error on the server part? Is the process still running?

**Comment by minotaurrr** [comment]
Sorry for not updating - there was an issue with the server, closing it
