### ISSUE TITLE
connect with wrong addr but successfully, and strange behavior occurs

### ISSUE THREAD

**Issue by zyf0330** [socketio/socket.io#3133]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
console print this
`server: new connection`
So client connects successfully with wrong addr, but it cannot receive emit event from server.

### Steps to reproduce (if the current behaviour is a bug)
```
const io = require('socket.io')
const ioC = require('socket.io-client')

const server = io(3001)
server.on('connection', (socket)=>{
	console.log('server: new connection')
	socket.emit('hello', 'world')
})
setTimeout(() => {
	const client = ioC('http://localhost:3001\'')
	client.open()
client.on('connect', ()=>{
	console.log('client: connect')
	client.on('hello', (data) => {
		console.log('client: receive hello ' + data)
		data
	})
})
}, 100)

```
**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS: Linux Ubuntu 17.10
- browser: nodejs
- socket.io version: newest

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
