### ISSUE TITLE
Disconnect event is not fired if socket disconnects before middleware is finished

### ISSUE THREAD

**Issue by calzoneman** [socketio/socket.io#3134]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

It's possible this is intended behavior, in which case it would be nice if the documentation explained this clearly.

### Current behaviour

If a `disconnect` listener is bound on a socket from middleware, the callback is not fired if the socket disconnects before the middleware completes.

My use case for this is along the lines of:

```
io.use((socket, next) => {
    const foo = allocSomeResource(socket);
    socket.once('disconnect', () => free(foo));
    authorize(socket, next);
})
```

Where `authorize` is a call that completes asynchronously

### Steps to reproduce (if the current behaviour is a bug)

`server;js`:

```js

const express = require('express');
const app = express();
const server = require('http').createServer(app);
const io = require('socket.io')(server);
const port = process.env.PORT || 3000;

app.use(express.static(__dirname + '/public'));

io.on('connect', onConnect);
io.use(function (socket, next) {
    console.log('waiting for ' + socket.id);
    setTimeout(next, 1000);
});
server.listen(port, () => console.log('server listening on port ' + port));

function onConnect(socket){
  console.log('connect ' + socket.id);

  socket.on('disconnect', () => console.log('disconnect ' + socket.id));
}
```

`client.js`

```js

const socket = require('socket.io-client')('http://localhost:3000');

socket.on('connect', onConnect);

function onConnect(){
  console.log('connect ' + socket.id);
}

setTimeout(() => socket.disconnect(), 500);
```

### Expected behaviour

`disconnect` event is fired when the socket is closed **OR** the documentation clearly states whether/which events are supported during the middleware phase.

### Setup
- OS: Linux
- browser: N/A, reproduced with node.js client
- socket.io version: `socket.io@2.0.4`

**Comment by hrdwdmrbl** [comment]
Can someone confirm this bug? It's almost a year old now...

**Comment by vicrazumov7** [comment]
Yes, we can

**Comment by TobiasWehrum** [comment]
I have a very similar bug and I assume it might be the same one. If a client disconnects in the middleware phase, the following things will happen:
- ```socket.connected``` will forever stay "true" for that socket.
- The ```io.on("connect")``` event will never be called for that socket.
- The ```socket.on("disconnect")``` event will never be called for that socket.

**Comment by deman714** [comment]
Have the same issue. I just quickly hit F5 on my chat page, and the number of clients is growing.
Code I tested:
let clients = {};
io.on('connection', socket => {
  socket.on('disconnect', () => {
    logger.info('disconnected id:', socket.id);
    delete clients[socket.id];
  });
});

**Comment by deman714** [comment]
Found workaround - to disconnect all clients by interval.
Server side:
```
setInterval(() => {
  const socket_ids = Object.keys(clients);
  socket_ids.forEach(socket_id => {
    // sometimes socket_id is not found in connected, but it's not all of the bugged sockets
    // that's why we disconnect all
    if (!(socket_id in io.sockets.connected)) {
      delete clients[socket_id];
      return;
    }
    io.sockets.connected[socket_id].disconnect();
  });
}, 86400000); // once a day
```
Client side:
```
socket.on('disconnect', () => {
  if(socket.io.connecting.indexOf(socket) === -1){
    socket.connect();
  } else { // fires if you call "socket.disconnect(true)" on server
    socket.disconnect();
  }
});
```

**Comment by TobiasWehrum** [comment]
My "workaround" was to not use middleware.

If you have to use middleware, I'd instead have the client send a custom "I am alive" message in a regular interval. If a client hasn't done that for a bit, disconnect it. Feels a bit more solid than just disconnecting everyone once a day.

**Comment by deman714** [comment]
@TobiasWehrum thank you for idea. I tried to use ping function:
```
socket.conn.on('packet', packet => {
  if (packet.type === 'ping' && socket.id in clients) {
    clients[socket.id].seen = Math.trunc(Date.now() / 1000);
  }
});
```
But I noticed that's actually overkill, because socket.io disconnects all of the not pingable clients itself. And others left are not found in connected, so my workaround is:
```
setInterval(() => {
  const socket_ids = Object.keys(clients);
  socket_ids.forEach(socket_id => {
    if (!(socket_id in io.sockets.connected)) {
      delete clients[socket_id];
    }
  });
}, 3600000);
```

**Comment by TroyDota** [comment]
how is this still a thing?

**Comment by darrachequesne** [comment]
For future readers: we have added a note here: https://socket.io/docs/v4/middlewares/#Registering-a-middleware

> the Socket instance is not actually connected when the middleware gets executed

```js
// server-side
io.use((socket, next) => {
  setTimeout(() => {
    // next is called after the client disconnection
    next();
  }, 1000);

  socket.on("disconnect", () => {
    // not triggered
  });
});

io.on("connection", (socket) => {
  // not triggered
});

// client-side
const socket = io();
setTimeout(() => {
  socket.disconnect();
}, 500);
```

**Comment by TobiasWehrum** [comment]
@darrachequesne If this is desired behaviour and not a bug, what would be the proper way to initialize something in a middleware that needs to be cleaned on disconnect? (See "My use case for this is along the lines of:" in the opening post.)

And does `socket.connected` still stay forever stay true if a client disconnects in the middleware phase, or is that fixed?

**Comment by darrachequesne** [comment]
@TobiasWehrum can't you just init this something in the `connection` handler?

```js
io.on("connection", (socket) => {
  const foo = allocSomeResource(socket);
  socket.once("disconnect", () => free(foo));
});
```

> And does socket.connected still stay forever stay true if a client disconnects in the middleware phase, or is that fixed?

I'm wondering if it would make more sense to set `connected` to true [here](https://github.com/socketio/socket.io/blob/6f2a50b9327fb5da6a1fb04ed436e156c042f470/lib/socket.ts#L337) (once the middleware is completed) instead of [here](https://github.com/socketio/socket.io/blob/6f2a50b9327fb5da6a1fb04ed436e156c042f470/lib/socket.ts#L161). What is your opinion?

**Comment by TobiasWehrum** [comment]
> @TobiasWehrum can't you just init this something in the `connection` handler?
> 
> ```js
> io.on("connection", (socket) => {
>   const foo = allocSomeResource(socket);
>   socket.once("disconnect", () => free(foo));
> });
> ```

Hmm. Yeah, you can - that's what I did earlier too when I had that problem. I think I just haven't understood properly what middlewares are for in socket.io. You are using them mainly as connection gatekeepers, I guess?

> 
> > And does socket.connected still stay forever stay true if a client disconnects in the middleware phase, or is that fixed?
> 
> I'm wondering if it would make more sense to set `connected` to true [here](https://github.com/socketio/socket.io/blob/6f2a50b9327fb5da6a1fb04ed436e156c042f470/lib/socket.ts#L337) (once the middleware is completed) instead of [here](https://github.com/socketio/socket.io/blob/6f2a50b9327fb5da6a1fb04ed436e156c042f470/lib/socket.ts#L161). What is your opinion?

Since you say "the Socket instance is not actually connected when the middleware gets executed" - absolutely, that makes more sense.

I think my earlier problems mainly came from my misunderstanding of middlewares. I used them to set up things (e.g. to keep a list of connected sockets bound to around), so it was pretty annoying to me that I suddenly had sockets that were not connected (because another middleware rejected them), never had `disconnect` called and forever had `connected=true`.

All these things are solved if I see them as gatekeepers instead and do my set up stuff in `io.on("connection")`.

**Comment by gurupras** [comment]
What are the implications if a middleware is performing asynchronous work to determine whether to allow the socket to connect or not? Should this logic be moved from `io.use((socket, next))` into `io.on('connection', socket => { ... })` as well? And regardless, do we need some kind of lock to ensure that `disconnect` event and initialization are mutually exclusive?

For example, consider the following code where I'm fetching information about the user, creating a `User` object that abstracts away some logging, methods, etc:
```js
io.on('connection', async socket => {
  // The following code was originally in io.use(). It has been moved here
  socket.on('disconnect', () => {
    socket.user && socket.user.disconnect() // Does some logging, cleanup, etc
  })
  try {
    const [userID, userInfo] = await getUserInfoFromToken(socket.handshake.query.token)
    const user = socket.user = new User(userID, socketID, userInfo)
    await user.bindSocket(socket)
    await user.joinRoom(userID) // This internally performs socket.join()
  } catch (e) {
    // Something went wrong. Just disconnect
    socket.user && socket.user.disconnect()
    socket.close()
  }
})
```
If `disconnect` could occur at any point, I have two choices:
  1. Litter the above code with checks as to whether the socket has disconnected after each async operation so as to not try to  do things like, say, `user.joinRoom(userID)` after the socket has disconnected.
  2. Use some kind of 'lock' to ensure that even if the socket disconnected in the middle of initialization, the `disconnect` event is handled only after initialization is complete.

Is there something simpler? Am I misunderstanding something?
