### ISSUE TITLE
Message size limit for socket.io 

### ISSUE THREAD

**Issue by techwizardg** [socketio/socket.io#3135]
We have a socket.io server that supports websockets as transport. Would like to know the message size limit for socket.io (i.e. as per documentation maxHttpBufferSize is only for polling and not for websockets). We send huge data over websocket from client to server to perform some operations on it. It takes a lot of time for response as i assume it is coming over multiple chunks and what is the default value on the message size limit for socket.io when transport is websockets.

**Comment by Chopinsky** [comment]
As raised in issue #3125, if a message is larger than 300MB, socket parser will crash on creating the JSON object to be sent. It would be better to break your traffic into smaller trunks and send them separately.

**Comment by darrachequesne** [comment]
For future readers: there are two parameters to take in account when sending big files:

- [`maxHttpBufferSize`](https://socket.io/docs/v3/server-initialization/#maxHttpBufferSize), which defaults to 1MB and applies to **both** the HTTP long-polling and WebSocket connections
- [`pingTimeout`](https://socket.io/docs/v3/server-initialization/#pingTimeout), which default to 5s, which is a bit low when uploading big files (if the client is uploading something while receiving a PING from the server, it may not have the time to send a PONG back)
