### ISSUE TITLE
Room Clients

### ISSUE THREAD

**Issue by marcus-sa** [socketio/socket.io#3137]
### Current behaviour
`fn.bind is not a function[2] at Adapter.clients`

### Expected behaviour
Return all clients in a specific room.

### Setup
- OS: Xubuntu 16.04
- browser: Mozilla Firefox
- socket.io version: latest

### Details
I'm running into an issue regarding getting all clients associated with a room. I feel like there lacks a lot of documentation, and all Stackoverflow answers are outdated.
Back in v1 you could do this to retrieve the clients: `io.sockets.clients(roomId)`
So how is that done now?

**Comment by LukasDeB** [comment]
You can get all clients's socket Id in a room by doing `io.sockets.adapter.rooms[roomId]`

**Comment by marcus-sa** [comment]
Thanks a lot!

**Comment by JonathanLee-LX** [comment]
Thanks!!
