### ISSUE TITLE
Socket emit with ack function

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io#3138]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
I can't make an emit with ack function. I would like to send information from client to server, and then, a server will need to reply. Can you help me how to make that, please? Is that appropriate way, if so, how to make it work? Because now it doesn't!

### Steps to reproduce (if the current behaviour is a bug)
Server
```
const electron = require('electron');
const {app, BrowserWindow} = electron;

app.on('ready', () => {
  let win = new BrowserWindow({width:800, height: 600})
  win.loadURL(`file://${__dirname}/index.html`)
  win.webContents.openDevTools()
})

var server = require('http').createServer();
var io = require('socket.io')(server);

io.on('connection', function(client){
  console.log('Socket connection established');

  io.on("signIn", (bid, text) => {
      domain('Root!');

  });
});
```
Client
```
var socket = io.connect('http://localhost:3000');
socket.on('connect', function() {
  console.log('Client connected');

  socket.emit('signIn', 'coffee', (data) => {
    console.log(data); // data will be 'Pizza'
  });


});
```

server.listen(3000);

### Setup
- OS: Windows 10
- browser: Chrome
- socket.io version: latest

**Comment by AngelMunoz** [comment]
Hey just passing by

I think you should replace this line
```js
 >>>> io.on("signIn", (bid, text) => {
```
for this one
```js
 >>>> client.on("signIn", (bid, text) => {
```
in your server example, just like you did in your client example

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
