### ISSUE TITLE
socket.io 2.0.4 Client/Server Question

### ISSUE THREAD

**Issue by rayj00** [socketio/socket.io#3142]
I am totally new to nodejs and pretty much new to JS. I have been pulling my hair out trying to figure out how to count number of connected clients.  This is simple client webpage to js server.

I have tried numerous examples but the all seem to throw errors.

Can someone just point me to a simple client/server javascript code example of counting connected clients? Please?  Pretty please?

I am using socket.io 2.0.4

I would highly appreciate it!

Ray

**Comment by CruizK** [comment]
From my experience there is no built in socket counter, the solution i am currently employing is this,
```javascript
//Express Setup
const express = require('express');
const app = express();
const server = require('http').Server(app);
const io = require('socket.io')(server);

const port = process.env.PORT || 8080;

//The variable that we store the users in
var CONNECTED_USERS = 0;

//Everytime a user connects, increment CONNECTED_USERS by 1
io.on('connection', (socket) => {
  CONNECTED_USERS++
  console.log(CONNECTED_USERS);
  
  //On disconnect, decrement CONNECTED_USERS by 1
  socket.on('disconnect', () => {
    CONNECTED_USERS--;
    console.log(CONNECTED_USERS);
  })
})

server.listen(port, () => {
  console.log('Server started on port ' + port);
})
```

**Comment by darrachequesne** [comment]
@rayj00 Please note that @CruizK's answer is valid when you are using only one Socket.IO server.

You can also use `Object.keys(io.sockets.sockets).length`.

**Comment by darrachequesne** [comment]
For future readers: https://socket.io/docs/v3/server-instance/#Server-engine
