### ISSUE TITLE
Server cannot receives Uint8Array from client, it only receives a plain Object

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [socketio/socket.io#3143]
### You want to:
* [x] report a *bug*
* [ ] request a *feature*
### Current behaviour
Server cannot receives Uint8Array from client, it only receives a plain Object.
### Steps to reproduce (if the current behaviour is a bug)
Client side:
```javascript
let binary = new Uint8Array(5);
binary.fill(12);
socket.emit('binary', binary);
```
Server side:
```javascript
socket.on('binary', (binaryData) => {
   console.log(binaryData);
});
```
Result of console.log on Server side:
```javascript
{ '0': 12,
  '1': 12,
  '2': 12,
  '3': 12,
  '4': 12,
  '5': 12 }
```
### Expected behaviour
Server side receives a Buffer, an ArrayBuffer, or Uint8Array.

### Setup
- OS: Windows 10
- browser: Google Chrome and Mozilla Firefox, Nodejs v8.9.1
- socket.io version: 2.0.4

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
I don't know if this is a bug or not.
Edit: Reason to do this: to save bandwidth.

**Comment by byrgazov** [comment]
```javascript
let binary = new Uint8Array(5);
binary.fill(12);
let buffer = binary.buffer.slice(binary.byteOffset, binary.byteOffset + binary.byteLength);
socket.emit('binary', buffer);
```

**Comment by darrachequesne** [comment]
This was fixed by https://github.com/socketio/socket.io-parser/commit/88225783f7bcbfd874d9b61449da4a25965a79c8, included in `socket.io-parser@3.1.3` & `socket.io@2.0.4`.

**Comment by cdauth** [comment]
I ended up here while searching whether/how it is possible to send `Uint8Array`s over Socket.IO. For anyone coming here for the same issue, be informed that you _can_ send an `Uint8Array` over a Socket.IO socket, but it will arrive as an `ArrayBuffer`. To convert it back, you have to wrap it by doing `new Uint8Array(arrayBuffer)`.
