### ISSUE TITLE
Cannot Connect To Server from mobile

### ISSUE THREAD

**Issue by jamalabo1** [socketio/socket.io#3144]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS: Android / IOS
- browser: Google Chrome / Android Browser / IOS Browser
- socket.io version: 2.0.4

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

cannot connect to server from mobile! 

var server = io.connect(server_url);
server.on('connect', ()=> {
    alert('connected'); 
});

**Comment by tsinglemon** [comment]
I have encountered the same problem. Have you solved it？thank！

**Comment by jamalabo1** [comment]
> I have encountered the same problem. Have you solved it？thank！

hello, this was a while ago, I don't have the source code at the moment, but as far as I remember it was HTTP/https problem, 
try to connect with https on.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
