### ISSUE TITLE
serializable in JSON

### ISSUE THREAD

**Issue by voanhcuoc** [socketio/socket.io#3146]
### You want to:

* [ ] report a *bug*
* [ ] request a *feature*
* [x] report missing docs

### Current content

https://socket.io/docs/client-api#socket-emit-eventname-args-ack

> Emits an event to the socket identified by the string name. Any other parameters can be included. All _serializable datastructures_ are supported, including Buffer.

### Expected content

> Emits an event to the socket identified by the string name. Any other parameters can be included. All _datastructures that are serializable in JSON_ are supported, including Buffer.

### Explanation

I'm sure the docs mean serializable in JSON through `JSON.stringify`.
But it should be clarified. I can't find any definition of _serializable_ in your docs or the ECMA Script spec.

**Comment by fenderOne** [comment]
Yes, I was wondering the same.
It would be good give us an example of something we can't do, for instance:

```
navigator.geolocation.getCurrentPosition(
  function (position) {    // Success function
    socket.emit('createLocationMessage', position)
  },
  function () {   // Error handler
      alert('Unable to fetch location')
  }
)
```
Why can´t "position" be used on the socket.emit data parameter?

**Comment by fenderOne** [comment]
Well, I don't know if socket.io use JSON.stringify for serialization but we know something about engine.io

> **engine.io** is the implementation of transport-based cross-browser/cross-device bi-directional communication layer for Socket.IO: 
[socket --> methods --> send ]
 1.- Sends a message, performing message = **toString**(arguments[0]) unless sending binary data, which is sent as is.
 2.- Parameters: String | Buffer | ArrayBuffer | ArrayBufferView: **a string or any object implementing toString()**, with outgoing data, or a Buffer or ArrayBuffer with binary data. Also any ArrayBufferView can be sent as is.

**Comment by darrachequesne** [comment]
For future readers: please see the documentation [here](https://socket.io/docs/v3/custom-parser/#The-default-parser)
