### ISSUE TITLE
Client socket.connected returns true after failed upgrade

### ISSUE THREAD

**Issue by NeekSandhu** [socketio/socket.io#3147]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

`connected` prop on client's `Socket`  object will still return `true` after failed http `upgrade`

![Socket.io stale information](https://i.imgur.com/3QIiiM8.png)

### Steps to reproduce (if the current behaviour is a bug)

```javascript
// server.js

var app = require('express')();
var server = require('http').Server(app);

// This is actually required in my use case and not just a "test case"
server.on('upgrade', function (req, socket) {
    if(!isClientAuthorized(req)) {
        socket.end('HTTP/1.1 403 FORBIDDEN','ascii');
        socket.destroy();
    }
});

var io = require('socket.io')(server);

server.listen(1234);

io.on('connection', function (socket) {
  // This event is also emitted, despite failed upgrade
  console.log('connected');
});
```

### Expected behaviour
`connected` should reflect a truly connected and interactive state

### Setup
- OS: `Windows 10 Pro 64`
- browser: `Google Chrome 63.0.3239.84`
- socket.io version: `2.0.4`

#### Thought
If `connected` cannot be changed for legacy or other reason(s). How about `sock.interactive` or `sock.ready` prop?

**Comment by darrachequesne** [comment]
The `connected` property does not mean the Websocket connection was successfully established, since Socket.IO use long-polling as fallback. Please see https://github.com/socketio/engine.io#goals for details.
