### ISSUE TITLE
Regarding upgrading engine.io version in dependency

### ISSUE THREAD

**Issue by chetandhembre** [socketio/socket.io#3149]
### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour
currently socket.io (2.0.4) uses engine.io (~3.1.0). 

### Expected behaviour
engine.io's new release available with security fixes (https://github.com/socketio/engine.io/releases/tag/3.1.4). 

Can you guys please upgrade engine.io dependency?

**Comment by darrachequesne** [comment]
I think `~3.1.0` should already install `3.1.4` version: https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1. Am I missing something?

**Comment by chetandhembre** [comment]
yeah
closing this issue.
