### ISSUE TITLE
http://socket.io returning Server Error: 5xx

### ISSUE THREAD

**Issue by Ewan-Keith** [socketio/socket.io#3150]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

The http://socket.io/ website is returning a server error. Trying to access it via https suffers a SSL_PROTOCOL_ERROR.

**Comment by darrachequesne** [comment]
Hi! Sadly, our hosting provider is experiencing some outage: https://twitter.com/zeit_status

**Comment by Ewan-Keith** [comment]
Looks like the host issues are resolved, closing issue.
