### ISSUE TITLE
Update dependencies to resolve critical vulnerabilities

### ISSUE THREAD

**Issue by hansemannn** [socketio/socket.io#3151]
### I want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
The dependencies of this (great!) module are outdated. `nsp` reports a critical DoS vulnerability in the `ws` sub-dependency of the `engine.io` core dependency. Full message:

```
┌────────────┬────────────────────────────────────────────────────────────────────┐
│            │ Denial of Service                                                  │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Name       │ ws                                                                 │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ CVSS       │ 7.5 (High)                                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Installed  │ 2.3.1                                                              │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Vulnerable │ <1.1.5 || >=2.0.0 <3.3.1                                           │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Patched    │ >= 1.1.5 <2.0.0 || >=3.3.1                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Path       │ my-node-package > socket.io@2.0.4 > engine.io@3.1.3 >              │
│            │ ws@2.3.1                                                           │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ More Info  │ https://nodesecurity.io/advisories/550                             │
└────────────┴────────────────────────────────────────────────────────────────────┘
```
There is already a patch in `ws` and `engine.io`, so only this one needs to be updated as well. It's a blocker for many pre-production apps, so any roadmap or workaround (probably manually patching it) would be appreciated. Thanks!

### Setup
- OS: macOS
- browser: Chrome (63.0.3239.84)
- socket.io version: 2.0.4

**Comment by darrachequesne** [comment]
Hi! Version [3.1.4](https://github.com/socketio/engine.io/releases/tag/3.1.4) of engine.io should include the fix for the DoS vulnerability, could you please check?

**Comment by hansemannn** [comment]
It does, but unfortunately this pod doesn‘t use the updated version so far.

**Comment by darrachequesne** [comment]
Soooo... is there something we could do?

**Comment by hansemannn** [comment]
Updating https://github.com/socketio/socket.io/blob/master/package.json#L28 to 3.1.4, confirm it passes all internal tests, release a new socket.io version would be a good start :)

**Comment by darrachequesne** [comment]
I may be missing something, but wouldn't running `npm update` solve your issue? Since we rely on engine.io `~3.1.0`.

**Comment by hansemannn** [comment]
It does, but I'd rather trust an official release confirming the fix and compatibility, as it's too critical right now. Has this this confirmed already? Then we should be fine!

**Comment by JeFawk** [comment]
This is still an issue 

  High            Regular Expression Denial of Service

  Package         parsejson

  Patched in      No patch available

  Dependency of   socketio

  Path            socketio > socket.io > socket.io-client > engine.io-client >
                  parsejson

  More info       https://npmjs.com/advisories/528
