### ISSUE TITLE
Ack never called for socket.emit when socket is reconnecting.

### ISSUE THREAD

**Issue by hifall** [socketio/socket.io#3152]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Ack is never called for socket.emit, when a socket is disconnected.

### Steps to reproduce (if the current behaviour is a bug)
1 create a socket, and connect it to the server;
2 disconnect the network (WIFI or LAN), and keep it so that the socket is disconnected (websocket error is seen in browser console);
3 connect the network now; then IMMEDIATELY call socket.emit with an ack, while the network, and socket are still trying to connect;
4 the ack is NEVER called, causing the entire application to freeze.

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
The ack should be called, after socket is reconnected.

### Setup
- OS: macOS Sierra 10.12
- browser: Opera 49, Firefox 57, Safari 10, and Chrome Canary.
- socket.io version: 1.7.2

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
