### ISSUE TITLE
Socket.io heroic CORS issue

### ISSUE THREAD

**Issue by Muneem** [socketio/socket.io#3159]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)
I have created sockets on expresses and it is working perfect in localhost. When I deploy sockets to heroku then I am getting error. I have tried all possible options which I could find in google. 

I am getting this error
The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'

I have also tried to include my domain in cars but no luck. I always get this error

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Socket.io not working in heroku. its always using polling instead of webs sockets.

### Steps to reproduce (if the current behaviour is a bug)
Deploy app o heroic. Try to make socket connection from another web app. You will phase this issue

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:
- browser:
- socket.io version:

**Comment by darrachequesne** [comment]
For future readers: please see the documentation [here](https://socket.io/docs/v3/handling-cors/).
