### ISSUE TITLE
Please help me，Errors have been unresolved

### ISSUE THREAD

**Issue by xCrazylei** [socketio/socket.io#3161]
Socket.io local operation has been no problem, But has been an error on the server.
Will come out in a while Error:This socket is closed.
Seemingly simple question but I can't find the answer.

img:
![_034](https://user-images.githubusercontent.com/25242674/34924208-fb912646-f9dc-11e7-8dad-b9acaa71537f.png)

Please

### Setup
- OS:Ubuntu 16.0.4
- browser:
- socket.io version:2.0.4

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
