### ISSUE TITLE
socket server will block the options request when set extraHeaders on client

### ISSUE THREAD

**Issue by hstarorg** [socketio/socket.io#3162]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*

### Current behaviour

When socket client want to connect to cross domain server with custom header, the options request will be blocked.

The reason is that `engine-io/server.js` not process the options request. [https://github.com/socketio/engine.io/blob/master/lib/server.js#L216-L235](https://github.com/socketio/engine.io/blob/master/lib/server.js#L216-L235)

The client code like this:

```js
// client.js (local address: http://localhost:7411)
io('http://localhost:7410', {
  transportOptions: {
    polling: {
      extraHeaders: {
        'x-clientid': 'abc'
      }
    }
  }
});
```

When I modify the engion.io server.js code like this:
```js
Server.prototype.handleRequest = function(req, res) {
  debug('handling "%s" http request "%s"', req.method, req.url);
  this.prepare(req);
  req.res = res;
  var self = this;
  if (req.method === 'OPTIONS') {
    res.setHeader('Access-Control-Allow-Origin', 'http://localhost:7411');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, x-clientid');
    res.setHeader('Access-Control-Allow-Credentials', true);
    return res.end();
  }
  this.verify(req, false, function(err, success) {
    if (!success) {
      sendErrorMessage(req, res, err);
      return;
    }

    if (req._query.sid) {
      debug('setting new request for existing client');
      self.clients[req._query.sid].transport.onRequest(req);
    } else {
      self.handshake(req._query.transport, req);
    }
  });
};
```
The question will be fixed.

**Comment by hstarorg** [comment]
I find an option can resolve it.

```js
const handlePreflightRequest = (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', req.headers.origin);
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, x-fc-token');
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.end();
};

const io = require('socket.io')(
  server,
  Object.assign({ handlePreflightRequest },config.socketOpt)
);
```

**Comment by Cheyenne55** [comment]
Man, this is sooo saving what you gave here.
Nowhere in the docs this is found but without that it is just impossible to add custom headers.
What the hell... :(

**Comment by hstarorg** [comment]
Stackoverflow is so slow in my environment(some times also has any errors).

**Comment by hstarorg** [comment]
I think you can commit this question to stackoverflow. Thank you.
