### ISSUE TITLE
the socket connects to the server for three times requests

### ISSUE THREAD

**Issue by yonghualuo** [socketio/socket.io#3163]
![1516701177120](https://user-images.githubusercontent.com/13300593/35269328-a507eed2-0066-11e8-8dad-08b62a9b9e7c.jpg)

Why dose the successful connection is established after two times other requests?

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://github.com/socketio/socket.io-protocol#sample-session
