### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found) socket.io.js

### ISSUE THREAD

**Issue by JskMohit** [socketio/socket.io#3172]
Hi All,

I am bit new to NodeJS and have created a sample application and publish it on local in IIS using IISNode. However, my code is working locally but not using IIS. As it gives me the following error:

Failed to load resource: the server responded with a status of 404 (Not Found)  socket.io.js
This refers to that it unable to locate socket.io.js file.

Below is my entire code which is working perfectly fine locally:
`
ChatApp.js file:

var app = require('express')();
var server = require('http').createServer(app);
var io = require('socket.io')(server);

app.get('/', function(req, res) {
   res.sendfile('ChatAppIndex.html', {"root": __dirname});
});

users = [];
io.on('connection', function(socket) {
   console.log('New user connected');
   socket.on('setUsername', function(data) {
      console.log(data +" - Index of userName is: "+ users.indexOf(data));
      
      if(users.indexOf(data) > -1) {
        console.log('userExists event emitted');
        socket.emit('userExists', data+ ' username is taken ! Try another one.');
      }
      else
      {
        users.push(data);
          socket.emit('userSet', {username: data});
      }

    
   });
   
   socket.on('msg', function(data) {
      //Send message to everyone
      io.sockets.emit('newmsg', data);
   });

});

app.listen(process.env.PORT); 
/*server.listen(3000, function() {
   console.log('listening on localhost

:3000');
});*/

ChatAppIndex.html:

<!DOCTYPE html>
<html>
   <head>
      <title>Hello world</title>
   </head>
   
   <script src = "socket.io/socket.io.js"></script>  //Error coming at this point. 
   <script>
      var socket = io();
      function setUsername() {
         socket.emit('setUsername', document.getElementById('name').value);
      };

      
      var user;
      socket.on('userExists', function(data) {
         document.getElementById('error-container').innerHTML = data;
      });
      
      socket.on('userSet', function(data) {
         user = data.username;
         document.body.innerHTML = '<input type = "text" id = "message">\
         <button type = "button" name = "button" onclick = "sendMessage()">Send</button>\
         <div id = "message-container"></div>';
      });
      function sendMessage() {
         var msg = document.getElementById('message').value;
         if(msg) {
            socket.emit('msg', {message: msg, user: user});
         }
      }
      socket.on('newmsg', function(data) {
         if(user) {
            document.getElementById('message-container').innerHTML += '<div><b>' + 
               data.user + '</b>: ' + data.message + '</div>'
         }
      })
   </script>
   <body>
      <div id = "error-container"></div>
      <input id = "name" type = "text" name = "name" value = "" placeholder = "Enter your name!">
      <button type = "button" name = "button" onclick = "setUsername()">Let me chat! </button>
   </body>
</html>

Code has been attached in txt file for reference
[JS&Index filecode.txt](https://github.com/socketio/socket.io/files/1702628/JS.Index.filecode.txt)
.

I have almost wasted 2 days in getting this issue fixed. Kindly help and as I would be very thankful for same.

Regards,
Mohit

**Comment by cwrx777** [comment]
try socket.io 1.3.7

**Comment by kjr247** [comment]
@I-GitHub Did you get your issue resolved?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
