### ISSUE TITLE
dynamically display data from server to client

### ISSUE THREAD

**Issue by saisrinivas047** [socketio/socket.io#3174]
hi all 
I am trying to send chunks of text data to the client using socket.emit(....). note that socket .emit is inside a loop so chunks of data is dynamically sent to the client. but in the client I am unable to display the data one by one...the data is getting displayed only after collecting the whole data from the server. is there a way to display data one by one sent from the server. ..that is whenever one chunk of data is sent to the client it should display or store it individually ..... instead for me it is displaying only after receiving all the data.

CLIENT CODE:
socket.on('message', function (data) {
             $('#transcript').append($('<p>').text(data));
           });

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
