### ISSUE TITLE
Sequelize + SocketIO + Mocha query getting randomly blocked

### ISSUE THREAD

**Issue by jessykalycia** [socketio/socket.io#3176]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

When developing tests with mocha + socketio + sequelize, _sometimes_ a sequelize query is being blocked until another packet comes to the server (the first query). The socketio code is connected to the REST API, but the REST API itself never blocks the code while querying - this is only happening on the SocketIO server. What's more - the same query is being executed on a non-connected part to the REST API, meaning this is basically a query with SocketIO only.

### Steps to reproduce (if the current behaviour is a bug)

```js
socket.use(async (packet, next) => {
	socket.log(packet);
	> let session = await Sessions.findOne({where: {session_key: socket.session}});
	if (session.session_available) return next();
	next(new Error("Session unavailable"));
	socket.disconnect(true);
	next();
});
```
The session query will trigger a block 1/100 of the time (on average). If the code gets removed, another query will get blocked - the first one that would be queried.

### Expected behaviour

Find the value (without blocking until another packet comes) and resume the function/code.

### Setup
- OS: Windows 7
- browser: none (using socket.io-client 2.0.4 with mocha)
- socket.io version: 2.0.4

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
