### ISSUE TITLE
why socket.io is better then native websockets

### ISSUE THREAD

**Issue by asif876** [socketio/socket.io#3177]
these days almost all browsers support `websockets` 

why `socket.io` is better?

why all popular websites use `socket.io` ?

where `websockets` do not work and `socket.io` works ?

**Comment by jfriend00** [comment]
Eleven items that socket.io has that webSockets do not is described here: https://stackoverflow.com/questions/38546496/moving-from-socket-io-to-raw-websockets/38546537#38546537.  Among them, auto-reconnect, rooms, middleware architecture, fallback for older browers, message based data format, etc...

**Comment by darrachequesne** [comment]
Documentation added here: https://socket.io/docs/v3/#Features
