### ISSUE TITLE
"delete this.server.eio.initialPacket"   This program leads to the failure of the socket.io-client-swift handshake   

### ISSUE THREAD

**Issue by AKM36** [socketio/socket.io#3184]
Namespace.prototype.use = function (fn) {
  if (this.server.eio) {
    debug('removing initial packet');
    delete this.server.eio.initialPacket;
  }
  this.fns.push(fn);
  return this;
};

**Comment by AKM36** [comment]
Socket.prototype.onOpen = function () {
  this.readyState = 'open';

  // sends an `open` packet
  this.transport.sid = this.id;
  this.sendPacket('open', JSON.stringify({
    sid: this.id,
    upgrades: this.getAvailableUpgrades(),
    pingInterval: this.server.pingInterval,
    pingTimeout: this.server.pingTimeout
  }));

  if (this.server.initialPacket) {
    this.sendPacket('message', this.server.initialPacket);
  }

**Comment by AKM36** [comment]
if (false) {
    debug('removing initial packet');
    delete this.server.eio.initialPacket;
  }
This can be a successful handshake

**Comment by AKM36** [comment]
"this.sendPacket('message', this.server.initialPacket)"  The above causes this sentence not to be executed

**Comment by darrachequesne** [comment]
For future readers: the `initialPacket` is not used in Socket.IO v3 anymore, it was used in Socket.IO v2 to include the Socket.IO CONNECT packet in the Engine.IO handshake (but only when there was no registered middleware).

Documentation: https://github.com/socketio/socket.io-protocol/tree/v4#sample-session
