### ISSUE TITLE
io.origins() does not take an array of strings 

### ISSUE THREAD

**Issue by stnwk** [socketio/socket.io#3190]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
In the documentation it states, that `io.origins()` takes an array of strings/origins (see example https://socket.io/docs/server-api/#server-origins-value), when in fact it does not. It only works when providing a string instead of an array.

### Steps to reproduce (if the current behaviour is a bug)
Setting 
```jsx
io.origins(['http://localhost:3000'])
```
and then connecting from `localhost:3000` does not work.

It only works when setting `io.origins('http://localhost:3000')`

### Setup
- OS: macOS High Sierra 10.13.3
- browser: Chrome 64.0.3282.186
- socket.io version: 2.0.4

**Comment by darrachequesne** [comment]
I think protocol shouldn't be included:

```js
io.origins(['localhost:3000', 'localhost:3001']);
// or
io.origins('localhost:3000');
```

**Comment by stnwk** [comment]
Works with protocol when provided as a string, does not when provided in an array 😄

But thanks for clarification!

**Comment by darrachequesne** [comment]
I think it's implemented as an `indexOf`, hence the funky behaviour.

I'll add a note in the documentation.

**Comment by ranetpgit** [comment]
I just ran into the same issue - an array with the protocol in the URL, eg `io.origins([https://subdomain.domain.ee:*])` doesn't work, while `io.origins([subdomain.domain.ee:*])` works. 

Whilst the example in the [documentation ](https://socket.io/docs/server-api/#server-origins-value  ) includes `https://` in the array example: `io.origins(['https://foo.example.com:443']);` .

Looking at this [commit](https://github.com/socketio/socket.io/commit/1f1d64bab61a273712a199591a3f76210d8c0959), it seems that the docs were changed to include that example, yet it still happened to me?


I was using `[https://subdomain.domain.ee:*]` as the URL, which didn't work, nor did it with `http://` (although in my case it should be only accessible via `https://` anyway). Once I removed the protocol, it started working. 

I thought I'd report this here just in case. Was I possibly missing something?
