### ISSUE TITLE
'io' is not defined

### ISSUE THREAD

**Issue by Logabe** [socketio/socket.io#3193]
### Current behaviour
Game.js running up until a certain point.
[](url)
### Expected behaviour
A green square should appear on the canvas.

### Setup
- OS: CloudReady
- browser: Chromnium
- socket.io version: 1.7.3

[Page](project-wrecked.glitch.me)
[Project](https://glitch.com/edit/#!/project-wrecked)

**Comment by Logabe** [comment]
Not helpful.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
