### ISSUE TITLE
Socket.io event handlers are not being executed when debugging with node --inspect --debug-brk

### ISSUE THREAD

**Issue by KerimG** [socketio/socket.io#3194]
I hope this is the right place for this issue. If not, I'd appreciate being redirected.

### Current behaviour

Debugging with node --inspect currently impossible, because custom events' handlers like

```javascript
socket.on("clientMessage", writeToFile);
```
do not get executed when inspecting. Handlers are executed just fine when not running in "node --inspect --debug-brk mode".

### Steps to reproduce

Run following code with "node --inspect --debug-brk", connect via Chrome Dev Tools (or VS Code or whatever) and set a breakpoint at second console.log then let execution continue. 

```javascript
var io = require("socket.io").listen(1337);

io.sockets.on("connect", defineSocketEvents);

function defineSocketEvents(socket) {
  console.log("defining event handlers");
  socket.on("clientMessage", writeToFile);

}

function writeToFile(data) {
   console.log(data);
}
```

run following code in second instance: 

```javascript
var io = require("socket.io-client");

var socket = io.connect("http://127.0.0.1:1337");
socket.emit("clientMessage", ["banana", "apple"]);

```

Server prints "defining event handlers" but never executes "writeToFile" function.

### Expected behaviour

When client emits "clientMessage" event, execution should halt at "console.log(data)".

### Setup
- OS: Windows 10
- browser: Chrome
- socket.io version: 2.0.4
- node version: 6.9.4

**Comment by darrachequesne** [comment]
I get a `[DEP0062] DeprecationWarning: 'node --inspect --debug-brk' is deprecated. Please use 'node --inspect-brk' instead.`, could this be linked?
