### ISSUE TITLE
clustering socket.io, the messages arrived late

### ISSUE THREAD

**Issue by enviel** [socketio/socket.io#3196]
i tried to cluster socket.io server, everything seems working as expected, the message got sent to clients even if they are on another node, except the messages is very late.

if i only send 1 message from client to server and broadcasted the message, the message will arrive at other clients around 5++ seconds later sometimes a bit faster but still longer than 1 second.

but if i sent 1 message and then send another one close in time both message will arrive the same time, but the next message or 3rd message will stuck or late again except if i send another or 4th message.

my server code

```javascript
const cluster = require('cluster');
const os = require('os');

const PORT = 3000;

if (cluster.isMaster) {
    for (var i = 0; i < os.cpus().length; i++) {
        cluster.fork();
    }

    cluster.on('exit', function(worker, code, signal) {
        console.log('Worker ' + worker.id + ' died, respawning..');
        cluster.fork();
    });
}

if (cluster.isWorker) {

    const io = require('socket.io')({
        pingInterval: 5000,
        pingTimeout: 10000,
        transports: ['websocket']
    });

    io.adapter(require('socket.io-redis')({
        host: 'localhost',
        port: 6379
    }));

    io.listen(PORT);

    console.log("Worker "+cluster.worker.id+" started, listening on port "+PORT);

    io.on('connection', function(socket) {
        console.log("Incoming connection on worker " + cluster.worker.id);
        console.log("<"+socket.id+"> ["+socket.handshake.address+"]");

        socket.on('join', function(data){
            let roomName = data["roomName"];

            socket.join(roomName);
            socket.roomName = roomName;

            io.to(roomName).emit('newChat', {
                chatSender: socket.id,
                chatText: "someone joined"
            });

            console.log("<"+socket.id+"> ["+socket.handshake.address+"] joined "+roomName);
        });

        socket.on('sendChat', function(data){
            let chatText = data["chatText"];

            io.to(socket.roomName).emit('newChat', {
                chatSender: socket.id,
                chatText: chatText
            });

            console.log("new message from "+socket.id);
        });

        socket.on('disconnect', function(reason){
            console.log("<"+socket.id+"> ["+socket.handshake.address+"] disconnected from worker "+cluster.worker.id+", reason: "+reason+".");
        });
    });
}
```

i'm using http://amritb.github.io/socketio-client-tool/ and https://github.com/fpanettieri/unity-socket.io-DEPRECATED for the client, both having the same problem.

socket.io version: 2.0.4

socket.io-redis version: 5.2.0

**Comment by darrachequesne** [comment]
Could you please try with
```js
const io = require('socket.io')({
    pingInterval: 5000,
    pingTimeout: 10000,
    transports: ['websocket'],
    wsEngine: 'ws'
});
```
There are reports of issues with `uws`.

**Comment by enviel** [comment]
> Could you please try with
> 
> const io = require('socket.io')({
>     pingInterval: 5000,
>     pingTimeout: 10000,
>     transports: ['websocket'],
>     wsEngine: 'ws'
> });
> There are reports of issues with uws.

no difference

**Comment by allicanseenow** [comment]
I am having the same delay. Cannot explain why.

**Comment by jastmicro** [comment]
Same problem here

**Comment by matth-c3** [comment]
Hello @ShujiaWu , 

Did you find a solution at the problem ? 

thanks

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by digz6666** [comment]
I'm having same problem as if I use redis cluster on socket-io.

With redis cluster messages are late, with single redis server messages arriving instantly.
