### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by didlie** [socketio/socket.io#3200]
C:\xampp\htdocs>npm install socket.io --save
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Isaac\AppData\Roaming\npm-cache\_logs\2018-03-13T10_58_44_793Z-debug.log

C:\xampp\htdocs>

**Comment by vdanielpop** [comment]
The first result on google shows you the error. Give it a try, mate.

**Comment by imachug** [comment]
Install git first: https://git-scm.com/
