### ISSUE TITLE
My discovery about the bug with Socket.rooms and how I found the current socket.rooms

### ISSUE THREAD

**Issue by allicanseenow** [socketio/socket.io#3201]
### Bug description

Hi,

I am an enthusiast in Socket.io. At the moment, I would like to report a bug in version 2.x of socket.io, where the main impacted factor is **rooms** (which used to be io.sockets.rooms) but got changed in version 2.x. It is not deprecated and you can still access it, however through a very long chain of javascript object properties.

This error happens when I'm using a namespace.

I've dug into the socket source code and found a problem here. If you have installed node modules via npm (or yarn), you can find the file in **./node_modules/socket.io/lib/socket.js**. In the function **join**

```js
Socket.prototype.join = function(rooms, fn){
  ...
  var self = this;
  ...
  this.adapter.addAll(this.id, rooms, function(err){
  rooms.forEach(function (room) {
    console.log('each room in rooms----------', room);
    self.rooms[room] = room;  
    }
    console.log('This socket after setting rooms--------', self.adapter); // (****)
    ...
  });
  return this;
```

> Note: All of the console.log() I mention are added by me.

If you take notice, in this function, we are adding each element of the **rooms** array to **self.rooms**. However, this is not the **socket.rooms** that we expect but a very different room. I'll explain how we actually reach this **room** later.

Assume, in a real-life scenario, I want a socket to join after it has connected. Taking a look at the '**onconnect** function in the **socket.js** file, which is always fired before the **join** function. Here is the code for the **onconnect** function:

```js
Socket.prototype.onconnect = function(){
  ...
  console.log('in onconnect funtion', this.id); 
  this.join(this.id);
  ...
};
```

Here is where the problem arises. When we connect, we actually "join" **this.id**, thus making **this.id** become an unexpected room. From the console.log (****) that I added to the function **join**, you can see inside the property **rooms**:

```
rooms: 
     { '/namespace_name#x9Je6cweXBB5fp4eAAAB': Room { sockets: [Object], length: 1 },
     '/namespace_name#pMr_xrIEM2lSc182AAAC': Room { sockets: [Object], length: 1 },
     '/namespace_name#BscQZyK_gFrIL_2-AAAD': Room { sockets: [Object], length: 1 },
     '/namespace_name#C5WH4nJo_73ZVvGDAAAE': Room { sockets: [Object], length: 1 },
     room_name: Room { sockets: [Object], length: 1 } },
```
> **room_name** is the name of the room that I used for **socket.join("room_name")**

You can see that I have a lot of extra, unexpected rooms that are automatically added when my socket connects. 

---

### How to find the current rooms

Assume you use a namespace

```js
console.log('Room list that contains connected rooms', util.inspect(io.sockets.in('namespace_name').adapter.nsp.server.nsps['/namespace_name'].adapter.rooms, {showHidden: false, depth: 2, colors: true, }));
```
---
### Ps

I have discovered this problem when I tried to find a list of all available connected rooms with socket.io. In versions before 1.0, we could do it with socket.rooms and we would have an array of room_name. However, in this 2.0 function, I cannot find any effective method that wouldn't require a lot of steps to actually find a list of different rooms that have been connected. Can you give my a way to fetch all room names in the version 2.x (**socket.rooms** will not work)? 

And should there be a way to filter rooms so that no duplication is made if there are many sockets connecting to the same room?

**Tl,dr:** **Onconnect** function in socket library adds redundant rooms to the room list by using the function **join**, and the **rooms**, which used to be found in **socket.rooms**, can be found in a different place.

**Comment by spietrek87** [comment]
I think these are the rooms mentioned in the documentation:
[https://socket.io/docs/rooms-and-namespaces/#default-room](url)

**Comment by allicanseenow** [comment]
Thanks. However, this has destroyed the purpose of making rooms though. In my opinion, room should only be defined when a user has a socket "join" a room. Or there should be a separate way to get the list of rooms that I make myself. Before, it existed in **socket.rooms** but it no longer does in this version.

**Comment by spietrek87** [comment]
Atleast you can access the adapter easier with
`io.of('/').adapter.rooms` or `io.of('<your_namespace>').adapter.rooms`

Or leave the room by `socket.leave(socket.id)` after the client joins your indended room, but im not sure if that will break something. (Of course the "Default Room" functionalty will no longer work)

**Comment by YoginAlex** [comment]
Hi!
It looks like my problem.

Simple code.
server.js
```
const app = express();
const socketServer = new http.Server(app);
const io = socketIo(socketServer);

io.on('connection', (socket: SocketIO.Socket) => {
  console.log('connection');
  console.log('socket.rooms', socket.rooms);

  socket.on('joinGame', ({ gameId: room, playerName }: IJoinGame) => {
    socket.join(room);
    console.log('socket joinGame');
    console.log('adapter.rooms', io.of('/').adapter.rooms);
    console.log('socket.rooms', socket.rooms);
  }
}
```

And debug from console:
```
socket.io:socket emitting event ["joinGame",{"gameId":"26687578e3b74e0fab046e290a27d484","playerName":"player"}] +0ms
socket.io:socket dispatching an event ["joinGame",{"gameId":"26687578e3b74e0fab046e290a27d484","playerName":"player"}] +0ms
  socket.io:socket joining room 26687578e3b74e0fab046e290a27d484 +1ms

socket joinGame

adapter.rooms { yEewU8y2Xx4lT5N4AAAB: Room { sockets: { yEewU8y2Xx4lT5N4AAAB: true }, length: 1 },
  '16GKD7PtquJo7vVcAAAC': Room { sockets: { '16GKD7PtquJo7vVcAAAC': true }, length: 1 },
  '26687578e3b74e0fab046e290a27d484': Room { sockets: { '16GKD7PtquJo7vVcAAAC': true }, length: 1 } }

socket.rooms { '16GKD7PtquJo7vVcAAAC': '16GKD7PtquJo7vVcAAAC' }
```

Why `console.log('socket.rooms', socket.rooms);` show me a very strange room ID?
I did `socket.join('26687578e3b74e0fab046e290a27d484');` and result is `socket.rooms { '16GKD7PtquJo7vVcAAAC': '16GKD7PtquJo7vVcAAAC' }`.

Then I did `socket.in(room).emit('update', updatedGame);` equal `socket.in('26687578e3b74e0fab046e290a27d484').emit('update', updatedGame);`

And client catch nothing :(

Where is my mistake?

**Comment by NicholasEwing-SB** [comment]
Has this been resolved yet? I don't understand why having a client connect to a namespace creates a "room" of the user in that namespace.

@allicanseenow :
> ```
> rooms: 
>      { '/namespace_name#x9Je6cweXBB5fp4eAAAB': Room { sockets: [Object], length: 1 },
>      '/namespace_name#pMr_xrIEM2lSc182AAAC': Room { sockets: [Object], length: 1 },
>      '/namespace_name#BscQZyK_gFrIL_2-AAAD': Room { sockets: [Object], length: 1 },
>      '/namespace_name#C5WH4nJo_73ZVvGDAAAE': Room { sockets: [Object], length: 1 },
>      room_name: Room { sockets: [Object], length: 1 } },
> room_name is the name of the room that I used for socket.join("room_name")
> 
> You can see that I have a lot of extra, unexpected rooms that are automatically added when my socket connects.
> ```

The [socket.io documentation](https://socket.io/docs/rooms-and-namespaces/) clearly states: 

> Within each namespace, you can also define arbitrary channels that sockets can join and leave.

My understanding is that namespaces _contain_ rooms, but are not rooms themselves. Like a one-to-many relationship. 

Rooms aren't appearing under namespaces correctly either, which seems to contradict the documentation and what @spietrek87 mentioned about referencing the adapter.

In a app I'm working on, when a client joins a namespace called `/project` they automatically enter a room named after the project ID they're viewing. Several of these projects exist such as "Project A" / "Project B" / etc.

When a client on Project A joins the namespace, this should create a room named "Project A" underneath the namespace of `/project`.

Here's a code snippet:

server.js
```
const io = socket(server);

io.of('/project').on('connection', client => {
  client.on('join project', projId => {
    client.join(projId, () => {
      console.log(io.nsps['/project'].rooms); // returns an empty array
    });
  });
});
```

someReactComponent.js
```
componentDidMount() {
    this.socket = io('/project');
    this.socket.emit('join project', "Project A");
}
```

Inside server.js, `console.log(io.nsps['/project'].rooms)` should return `["Project A"]`, but contains `[]` instead.

Upon checking the adapter for the `/project` namespace by console.logging `io.nsps['/project'].adapter.rooms`, there are two rooms. 

One is correctly named 'Project A' while another unexpected room is '/project#GUyI-6I3ktZusTJsAAAA''.

It appears the second room should NOT be appearing as @allicanseenow stated.

```
    { 'Project A':
    Room {
      sockets: { '/project#GUyI-6I3ktZusTJsAAAA': true },
      length: 1 
    },
   '/project#GUyI-6I3ktZusTJsAAAA':
    Room {
      sockets: { '/project#GUyI-6I3ktZusTJsAAAA': true },
      length: 1 } 
    }
```

I'd love to see this bug fixed, otherwise it prevents the room / namespace distinction from existing and prevents this package from being useful.

If I'm just understanding socket.io incorrectly, please let me know. Thanks in advance!

**Comment by szarkowicz** [comment]
I am experiencing the same issue with Rooms array in the Namespace not getting updating when joining a room.  Socket.io version 2.2.0

When I create a namespace 
// Create Admin Namespace
const adminNSP = io.of('/admin-device-mgmt');

Then have a socket join the room in the namespace
adminNSP.on('connection', (socket) =>
{
  socket.join('room-name-1);
  console.log(adminNSP.rooms); // LENGTH is 0 
});

The only way to get list of rooms is by using one of the following but it also has the sockets in the list which does not seem correct at all.

 console.log(Object.keys(adminNSP.adapter.rooms));
 console.log(io.of('/admin-device-mgmt').adapter.rooms);

<img width="593" alt="Screen Shot 2019-07-23 at 11 56 10 AM" src="https://user-images.githubusercontent.com/9085693/61731372-ef8cb900-ad40-11e9-9d48-539404a6809d.png">

Looping over the array you would not know if its a room id vs a socket id. 

Something this basic as getting a list of rooms in a namespace seems like its broken in the latest version of socket.io

**Comment by darrachequesne** [comment]
For future readers: as of Socket.IO v3, the `socket.rooms` attribute is basically a reference to the underlying adapter, which stores the relationships between Socket IDs and rooms.

Documentation: https://socket.io/docs/v3/rooms/#Implementation-details

Source:
- https://github.com/socketio/socket.io/blob/3.1.1/lib/socket.ts#L610-L612
- https://github.com/socketio/socket.io-adapter/blob/2.1.0/lib/index.ts#L195-L197
