### ISSUE TITLE
cache messages to be sent after device goes online

### ISSUE THREAD

**Issue by monajafi** [socketio/socket.io#3202]
How should I send the messages to client after he goes online which I was trying to send but he was offline and unable to receive
Socket.io is working well while there is a connection between server and client. but I want to simulate FCM in my own server using Socket.io
any help is appreciated

**Comment by darrachequesne** [comment]
For future readers: on the server-side, the packets sent to a given client are not saved when this client is disconnected. You'll need to store them in your application, and deliver them upon reconnection.

Please see the example here: https://socket.io/get-started/private-messaging-part-3/
