### ISSUE TITLE
socket.disconnect is not a function

### ISSUE THREAD

**Issue by idibidiart** [socketio/socket.io#3207]
on server, inside the io.socket.on('connection', callback):

if I call 
socket.disconnect(true)
             ^

TypeError: socket.disconnect is not a function

socket.disconnect is in the Server API docs. What is the problem? Using 2.0.4

**Comment by idibidiart** [comment]
I searched the codebase for  a 'disconnect' method on server side and there is none, so the docs must be out of date.

Does this mean that once client disconnects (via .disconnect which does exist on client (https://github.com/socketio/socket.io/blob/c0c79f019e7138194e438339f8192705957c8ec3/lib/client.js#L114) ) then socket.io cleans up properly on server? i.e. closes the underlying socket connection and removes event handlers etc? 

It's not clear at all from the docs.

**Comment by sayhicoelho** [comment]
have tried socket.disconnect(true), it doesn't catch an 'not a function' error but it doesn't works. the client remains connected! :(

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
