### ISSUE TITLE
Relationship to Node is unclear in documentation.

### ISSUE THREAD

**Issue by caaker** [socketio/socket.io#3210]
I don't know the correct forum for addressing this concern. So please point me in the right direction if this is not.

If my understanding is correct, Socket.IO  requires that you pass it in a reference to the server as such or similar.

`const io = require('socket.io')(server);
`

If I understand correctly there is no Node server code in the socket.io repo.

Hence I would like to modify the documentation from:

> Socket.IO enables real-time bidirectional event-based communication. It consists in:
> a Node.js server (this repository)
> a Javascript client library for the browser (or a Node.js client)

to

> Socket.IO enables real-time, bidirectional, event-based communication. It consists of 2 parts:
> a Socket.IO server contained in this repository.
> a Socket.IO client which is a dependency in this library's package.json file

or similar.

If that change is acceptable please accept this pull request here:

https://github.com/socketio/socket.io/pull/3205

Thank you!

**Comment by darrachequesne** [comment]
Actually, passing an http server is not required, since a new one will be created by default:
```js
const io = require('socket.io')();
```
But providing your own gives you a more fine-grained control.

Regarding this part:
> a Socket.IO client which is a dependency in this library's package.json file

I think the fact that the client can be executed in both the browser and a NodeJS runtime is lost, isn't it?

Else, looks good to me :+1:

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
