### ISSUE TITLE
io.on("connection") method is too big,how can i use routes

### ISSUE THREAD

**Issue by myname9** [socketio/socket.io#3211]
i use socket.io,i could write more ‘on event’ in my project ,such as
```
io.on('connection', function(socket){
	socket.on('event1', res=>{...});
	socket.on('event2', res=>{...});
	socket.on('event3', res=>{...});
	socket.on('event4', res=>{...});
	...
});
```
i want to use like routes,create a routes folder  which can save more ‘on event’  file

**Comment by darrachequesne** [comment]
Added in the documentation here: https://socket.io/docs/v3/server-application-structure/
