### ISSUE TITLE
Version with engine.io 3.2.0

### ISSUE THREAD

**Issue by johanneswuerbach** [socketio/socket.io#3213]
For testem https://github.com/testem/testem we prefer to provide users an experience without any native dependencies due to how npm reports compile/install failures.

I happily saw that the optional usw dependency was removed in https://github.com/socketio/engine.io/pull/550 and would love to see a socket.io release including https://github.com/socketio/socket.io/commit/b1941d5dfe3d2530bb0f0391088d3c8765ae9695 so we can finally upgrade our socket.io version again :-)

Any chance to get a new release including said commit?

❤️ thanks for the great work 👍 

//cc @stefanpenner

**Comment by darrachequesne** [comment]
And "voilà"! https://github.com/socketio/socket.io/releases/tag/2.1.0

**Comment by johanneswuerbach** [comment]
Perfect, thank you :bow:
