### ISSUE TITLE
client in chrom browser not work but in firefox and ie is OK

### ISSUE THREAD

**Issue by 191302041** [socketio/socket.io#3215]
client code very simple as follows:

	var socket =  io.connect('http://localhost:9092/orderSpeech');
	

	socket.on('connect', function() {
		alert("Connected!");
		socket.emit('eventJoinRoom', '{"shopId":"1"}'); // abcd = shopId;
		output('<span class="connect-msg">Client has connected to the server!</span>');
	});
it does not work.

the net work record as follows:
image
it could not establish websocket connection.

why?

**Comment by kotAPI** [comment]
Could you be more descriptive? The image you've attached seems to be broken

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
