### ISSUE TITLE
Fail to load resource with CodeIgniter

### ISSUE THREAD

**Issue by JakeCube** [socketio/socket.io#3216]
### Setup
- OS: Windows
- browser: Chrome
- socket.io version: 2.1.0

Hi, i'm trying to include the tutorial from web socket into my codeIgniter project.
But when i'm implement exact the same way i got the error "Fail to load resource: ... socket.io.js"

But if i try to access socket.io.js with this "localhost:3000/socket.io/socket.io.js" URL it was able to access.

Since codeigniter will only run url like this "localhost/ci_test/chat", is there any way to overcome this issue?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
