### ISSUE TITLE
Broadcast to local instance only when using the redis-adapter

### ISSUE THREAD

**Issue by sleimanx2** [socketio/socket.io#3217]
it's possible to add the local flag when emitting to a room

```js
 // sending to all clients on this node (when using multiple nodes)
 io.to(channel).local
     .emit(message.event, channel, message.data)
```

however, when broadcasting from a socket instance it's not possible to add a local flag is there any way to achieve the same behavior?

```js
// this wont work
socket.broadcast.to(channel).local
      .emit(message.event, channel, message.data);
```
thank you

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io/pull/3219
