### ISSUE TITLE
Question : How to get socket object from socket.on() events ?

### ISSUE THREAD

**Issue by ExDomino** [socketio/socket.io#3218]
Hello,

My question is simple: in my code I have for exampe socket.on("message"), so if I receive the event "message" from a client, I will do something. But how to get the client's socket object? I would like to emit something in return but "socket is not defined". How to reply to this client? The socket object is not transmitter with the event so I don't know how to identify the emiter. This is a problem! The event "disconnect" has this variable but not the other events.

Thank you in advance!

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
