### ISSUE TITLE
BUG: Emitting to specific socket IDs - won't emit to itself

### ISSUE THREAD

**Issue by peppies** [socketio/socket.io#3220]
Greetings,

I noticed a bug today, trying to do something simple, took a few hours to realize it was a bug. Let's say a user has multiple tabs open in their browser, and then they turn their "Away" status to "Online":

Client side: 
```js
socket.emit('update.online.status', userid);
```
Server side:
```js
socket.on('update.online.status', function(userid) {
  client.smembers('sockets:'+userid, function(err, reply) { // redis: array of user's socket ids (multiple browser tabs)
    reply.forEach(function(sockid) { // loop through all of the user's sockets
      socket.to(sockid).emit('test', 'test');
    });
  });
});
```

The server emits a "test" response back to all of the sockets (browser tabs) except the originating socket (tab). In my script, the "Online" status gets updated in all of the user's browser tabs - except the one tab where they actually set their online status (and fires off the socket emission to the server).

The only solution would be to use socket.emit('test', 'test') if the originating socket == sockid. That additional logic on the server side should not be necessary and should work using socket.to(sockid).emit. Therefore this is a bug.

Thanks
Kind regards
Ryan

Edit by @darrachequesne: style

**Comment by peppies** [comment]
Unfortunately, I cannot edit the post, but I am using Socket.io version 2.0.3

**Comment by blackfish-wu** [comment]
I have the same question while run this code:
`socket.to(socket.id).emit('hey');`
Could anybody tell us how to emit a private message to the socket itself ?

**Comment by darrachequesne** [comment]
According to the [documentation](https://socket.io/docs/emit-cheatsheet/), `socket.to(sockid).emit('test', 'test');` emits to all clients in `sockid` room except the sender itself, I think that's why it fails for the tab associated with the given `socket`.

Two solutions:
- use `io.to(sockid).emit('test', 'test');` instead
- make each socket join the `userid` room, and then use `io.to(userid).emit('test', 'test');`

@blackfish-wu `socket.emit('hey');` should be enough

**Comment by peppies** [comment]
According to the [documentation] (https://socket.io/docs/emit-cheatsheet/), it also says:

```
// sending to individual socketid (private message)
  socket.to(<socketid>).emit('hey', 'I just met you');
```

This is confusing, it is assumed that this command will send a message to any specific socketid. Maybe update the cheatsheet to use "io.to" instead of "socket.to" in this instance. Had the same confusion with a different part of developing my private messaging script the other day until I again realized I had to remember this issue.

However, darrachequesne's solution of using ```io.to(sockid).emit('test', 'test');``` does work as expected and I will probably just use this. However:

**Question for darrachequesne**

If there is a very large number of socket connections, is there a performance difference for using "io.to" vs "socket.to" when emitting to individual socket ids?

**Comment by darrachequesne** [comment]
@peppies you're absolutely right, thanks for the explanation! I updated the documentation in https://github.com/socketio/socket.io/pull/3232.

Regarding the performance, both methods actually call the same code:

https://github.com/socketio/socket.io/blob/master/lib/namespace.js#L234-L237

```js
this.adapter.broadcast(packet, {
  rooms: rooms,
  flags: flags
});
```

https://github.com/socketio/socket.io/blob/master/lib/socket.js#L170-L173

```js
this.adapter.broadcast(packet, {
  except: [this.id],
  rooms: rooms,
  flags: flags
});
```

**Comment by 592da** [comment]
@darrachequesne ack not working when emitting to specific socket. ex:
```ts
io.to(client).emit(MESSAGE_TYPE, data, function(
            error,
            resposne
          ) {
            console.log({ error, resposne });
          });
```

when sending with ack function, message not sent.
when sending without ack, message sent.

how to solve it?
thee use case is to send a message from server to specific client id, with ack function.

Thank you.
