### ISSUE TITLE
UUID as room doesn't work while md5 hash is fine

### ISSUE THREAD

**Issue by mygnu** [socketio/socket.io#3222]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)
```javascript
//server with redis adapter
socket.on('join_chat', function(chatId) {
    console.error('join_chat', chatId);
    // console.error(io.sockets.adapter.rooms);
    socket.join(chatId);
    // console.error(io.sockets.adapter.rooms);
  });

//client 
socket.emit('join_chat', id); // if id is uuid it dosen't work
```
if id is UUID (ideal as chat table in the db has id UUID v4) it doesn't work but if i hash the id with md5 and use hash as chat id it works fine.
maybe related to  #1703 
### Expected behaviour
client should connect and communicate through UUID room name 

### Setup
- OS: Linux
- browser: Firefox 60-beta
- socket.io version: 2.1.0

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by AasishP** [comment]
> ### You want to:
> * [x]  report a _bug_
> * [ ]  request a _feature_
> 
> ### Current behaviour
> ### Steps to reproduce (if the current behaviour is a bug)
> ```js
> //server with redis adapter
> socket.on('join_chat', function(chatId) {
>     console.error('join_chat', chatId);
>     // console.error(io.sockets.adapter.rooms);
>     socket.join(chatId);
>     // console.error(io.sockets.adapter.rooms);
>   });
> 
> //client 
> socket.emit('join_chat', id); // if id is uuid it dosen't work 
> ```
> 
> if id is UUID (ideal as chat table in the db has id UUID v4) it doesn't work but if i hash the id with md5 and use hash as chat id it works fine. maybe related to #1703
> 
> ### Expected behaviour
> client should connect and communicate through UUID room name
> 
> ### Setup
> * OS: Windows 10
> * browser: Chrome 97.0.4692.99
> * socket.io version: 4.1.2

**Comment by darrachequesne** [comment]
@AasishP I'm not sure the ObjectId is serializable. Could you please try calling `toString()` on it?

Reference: https://docs.mongodb.com/manual/reference/method/ObjectId.toString/

Regarding the initial issue, I wasn't able to reproduce: https://codesandbox.io/s/happy-bohr-627u5
