### ISSUE TITLE
New error 'Access-Control-Allow-Origin' header has a value 'null' that is not equal...after chrome update version

### ISSUE THREAD

**Issue by aseolin** [socketio/socket.io#3223]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
When trying to connect on a localhost web app after Chrome update, I got this message:
The 'Access-Control-Allow-Origin' header has a value 'null' that is not equal to the supplied origin. Origin 'null' is therefore not allowed access.

This was not happened on previous versions of chrome. On version 61 I can connect normally. On version 65 I get that error. On firefox 59 everything is ok too.

### Setup
- OS: Windows 7 64
- browser: Chrome 65, Chrome 62, Firefox 59
- socket.io version:

**Comment by darrachequesne** [comment]
For future readers: please see https://socket.io/docs/v3/handling-cors/
