### ISSUE TITLE
400 error when in a slow connection and the whole hung

### ISSUE THREAD

**Issue by qiulang** [socketio/socket.io#3224]
I have asked help at StackOverflow  [how to debug 400 error](https://stackoverflow.com/questions/49799415/how-do-i-debug-socket-io-client-api-400-error)

But I feel it is more like a bug.
### You want to:

* [x] report a *bug*

### Current behaviour

I use socket.io 2.0.3, only the basic stuff like

    <script src="/socket.io/socket.io.js"></script>
    <script>
      const socket = io();
    </script>

Normally it works fine but sometimes I got 400 error like following. The problem is easier to trigger when I got a slow connection 

<img width="1274" alt="socket" src="https://user-images.githubusercontent.com/516243/38717889-355eff36-3f1c-11e8-982f-5e4721e72800.png">

My second question is when I got 400 error the page just hung, it almost like in a blocking single thread situation. I had thought with socket.io callback model, that won't happen. So how do I fix it?

### Steps to reproduce (if the current behaviour is a bug)

I find when I get a slow connection it is easier to trigger. 

### Expected behaviour

Even socket.io is busy in reconnecting, it should not hang the whole page.

### Setup
- OS macOS 10.13:
- browser chrome65/safari 11 both happened:
- socket.io version 2.0.3:

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

I use socket.io with vue.js. Not sure if that is a factor.

**Comment by Techytt** [comment]
We are facing same issue in my localhost in window system with chrome browser,

**Comment by AngelLiang** [comment]
It seems lost 'sid'(session id) which can find it in the 'get' method response cookie.

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socket.io/docs/v3/troubleshooting-connection-issues/#In-the-browser
