### ISSUE TITLE
maintain  the same socket connection on browser refresh

### ISSUE THREAD

**Issue by rohan-new** [socketio/socket.io#3225]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:
- browser:
- socket.io version:

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
Each time i refresh the web browser page, a new socket connection is made and the old socket connection is destroyed. Is there any way to maintain the old socket connection on browser refresh?

**Comment by darrachequesne** [comment]
For future readers: please see the example [here](https://socket.io/get-started/private-messaging-part-2/#Persistent-session-ID).
