### ISSUE TITLE
Clients count in room

### ISSUE THREAD

**Issue by Jhordan92** [socketio/socket.io#3230]
Hi, if I'm writting this in the wrong place, please tell me.

I'm trying to practice WebRTC using the book
Real Time Communication with WebRTC

And I'm stuck in the use of signaling channels.
I'm using socket.io version 2.x and the way in which the book tells you to ask for the clients count connected in one room is
**var numClients = io.sockets.clients(channel).length;**
But this throws an error, so I looked for other methods

This one always return one client
**io.of('/').in(channel).clients(function(error,clients){
numClients=clients.length;
});**
and so did this
**var numClients = io.of('/').in(channel).clients.length;**

I would appreciate any help or guide, I tried the socket.io documentation and didn't found anything on the matter

**Comment by darrachequesne** [comment]
For future readers:

Please use the [`allSockets()`](https://socket.io/docs/v3/server-api/#namespace-allSockets) method:

```js
// all sockets in the main namespace
const ids = await io.allSockets();

// all sockets in the main namespace and in the "user:1234" room
const ids = await io.in("user:1234").allSockets();

// all sockets in the "chat" namespace
const ids = await io.of("/chat").allSockets();

// all sockets in the "chat" namespace and in the "general" room
const ids = await io.of("/chat").in("general").allSockets();
```

Note: this will also work with multiple Socket.IO servers, if the [Redis adapter](https://socket.io/docs/v3/using-multiple-nodes/#Passing-events-between-nodes) is used.

**Comment by robertbunch** [comment]
darrachequesne comment is a welcome find and exactly right for v3, but [noted in v4 docs](https://socket.io/docs/v4/server-api/#serversocketsjoinrooms) allSockets() will be removed in the next major release. In v4 and beyond, use [fetchSockets()](https://socket.io/docs/v4/server-api/#namespacefetchsockets). Note that allSockets returns a promise (make sure to add async to your callback!), so the implementation would be:

// Count of all sockets in / namespace
const sockets = await (io.of('/').fetchSockets()) // returns an array of all sockets
const socketCount = sockets.length;

// Count of all sockets in /chat namespace, general room
const sockets = await (io.of('/chat').in('general').fetchSockets()) // returns an array of all sockets
const socketCount = sockets.length;

**Comment by timbo-tj** [comment]
Is there a more efficient way to do this that doesn't (assumedly) pull down all of the 'data's from all of the sockets across all of the Socket IO servers? For 'noisy' rooms (ie global chat) we'd like to just be able to check how many people are in a room across all nodes - just a number.

**Comment by darrachequesne** [comment]
@timbo-tj yes, you can use the `serverSideEmit` method to gather the count across your cluster:

```js
function localCount(room) {
  return io.of("/").adapter.rooms.get(room)?.size || 0;
}

async function totalCount(room) {
  const remoteCounts = await io.serverSideEmitWithAck("count", room);

  return remoteCounts.reduce((total, count) => total + count, localCount(room));
}

io.on("count", (room, cb) => {
  cb(localCount(room));
});

const value = await totalCount("my-room");
```

Reference: https://socket.io/docs/v4/server-instance/#serversideemit

**Comment by darrachequesne** [comment]
Added in the documentation there: https://socket.io/how-to/count-connected-clients

**Comment by timbo-tj** [comment]
Extremely thorough, thank you so much, and fantastic work 🫡
