### ISSUE TITLE
Socket.io Server answers sometimes with 404 to client

### ISSUE THREAD

**Issue by GermanBluefox** [socketio/socket.io#3231]
### Current behavior
I have a very strange behavior: 
- http (https not tested)
- express 4.16.3
- socket.io 2.1.0
- node.js 8.11
- npm 5.8.0
- Windows x64

There is a web server with express and socket.io. With one connection works everything perfect.

If second connection from other IP will come, so the socket.io server answers with HTTP that "document not found". It is not happen, if only one connection is there. Only when second connection from other IP (important) is established, so the first connection cannot connect after the page is reloaded.

Someone answers to client with HTTP on web socket.

### Installation
Socket.io is connected after express.

#### Server code:
```
var app = express();
app.disable('x-powered-by');
var server = require('http').createServer(app);
var socketio = require('socket.io');
server.listen(8082);   //<-- first the http server starts
var io = socketio.listen(server); // <-- then connect socket.io to that
io .on('connection', socket => {
    // communicate
});


app.use('/', (req,res) => {
       // serve some stuff
       res.send('HTML PAGES');
});
```
#### Client code:
```
var socket = io.connect("https://localhost:8082", {
                query:                          'key=nokey',
                'reconnection limit':           10000,
                'max reconnection attempts':    Infinity,
                reconnection:                false,
                upgrade:                        false,
                rememberUpgrade:       true,
                transports:                     ['websocket']
            });
socket .on('connect', function () {
      socket.emit('name', 'vis.0');
      socket.emit('authenticate',  function () {});
});
```

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
Socket.io debug

```  
engine:socket flushing buffer to transport +1ms
  engine:ws writing "0{"sid":"AoQ0D_7BqjVz2ePeAAAD","upgrades":[],"pingInterval":25000,"pingTimeout":5000}" +10s
  engine:socket sending packet "message" (0) +1ms
  engine:transport setting request +10s
  socket.io:server incoming connection with id AoQ0D_7BqjVz2ePeAAAD +10s
  socket.io:client connecting to namespace / +10s
  socket.io:namespace adding socket to nsp / +10s
  engine:socket flushing buffer to transport +1ms
  engine:ws writing "40" +3ms
  socket.io:socket socket connected - writing packet +10s
  socket.io:socket joining room AoQ0D_7BqjVz2ePeAAAD +0ms
  socket.io:socket packet already sent in initial handshake +1ms
 Connected system.user.admin from ::ffff:192.168.0.22
  socket.io:socket joined room AoQ0D_7BqjVz2ePeAAAD +1ms
[HPM] Upgrading to WebSocket
  engine:ws received "42["name","vis.0"]" +7ms
  engine:socket packet +8ms
  socket.io-parser decoded 2["name","vis.0"] as {"type":2,"nsp":"/","data":["name","vis.0"]} +10s
  socket.io:socket got packet {"type":2,"nsp":"/","data":["name","vis.0"]} +6ms
  socket.io:socket emitting event ["name","vis.0"] +0ms
  socket.io:socket dispatching an event ["name","vis.0"] +0ms
  engine:socket transport error +14ms
  engine:ws closing +14ms
  socket.io:client client close with reason transport error +24ms
  socket.io:socket closing socket - reason transport error +14ms
``` 

Wireshark: 
![image](https://user-images.githubusercontent.com/4582016/39330513-2d6c8b50-49a2-11e8-9244-589de7ad56ba.png)

![image](https://user-images.githubusercontent.com/4582016/39331509-12c0da24-49a5-11e8-8334-0c937505f3ef.png)

![image](https://user-images.githubusercontent.com/4582016/39331519-19d866ec-49a5-11e8-8571-a1e7fbfe4922.png)

**Comment by Apollon77** [comment]
Experienced such an effect too ...

**Comment by GermanBluefox** [comment]
I think it has something to do with this issue: https://github.com/websockets/ws/issues/1000

> The main problem is that we are using several WebSocket servers with different paths but the same express server instance. This was working fine with ws 1.x. **Now the first WebSocket server closes the connection if the path would match the path of the registered second WebSocket server.** This is a crucial feature because we extend express to allow ws routes which register a WebSocket server using the route's path.

How can I solve it? I need 2 simultaneous connections from one client. (main window and iframe window)

**Comment by GermanBluefox** [comment]
If I will use socket.io 1.7.2 => engine.io 2.0.2 => ws 1.1.2 could it help?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
