### ISSUE TITLE
routing in express with socket data.

### ISSUE THREAD

**Issue by vettorazi** [socketio/socket.io#3241]
Hey guys, i am trying to acess data of socket.id outside of io.on() function...
with io.on('connection') i counted every each user logged in my app and putted in an array, but i want to send different pages according to the socket.id that each user have.

How can i achieve this?

`[...]
var row_of_users=[];//my array of users.
var visits=0;//just a count of users logged in.

io.on('connection', function(socket){
var user=socket.id;
visits++;
row_of_users.push(user);
console.log(row_of_users);
[...]

outside of the function i have my express function:

app.get('/', function(req, res){
  if(row_of_users==0){
  res.sendFile(__dirname+'/index.html');
}else if(row_of_users<0){
  res.sendFile(__dirname+'/wait-your-time.html');
}

`

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
