### ISSUE TITLE
socket.io connection closed before receiveing handshake 

### ISSUE THREAD

**Issue by nara1988** [socketio/socket.io#3244]
client side c++ code（cocos2dx）
#include "HelloWorldScene.h"

USING_NS_CC;
using namespace  cocos2d::network;

Scene* HelloWorld::createScene()
{
	// 'scene' is an autorelease object
	auto scene = Scene::create();

	// 'layer' is an autorelease object
	auto layer = HelloWorld::create();

	// add layer as a child to scene
	scene->addChild(layer);

	// return the scene
	return scene;
}

// on "init" you need to initialize your instance
bool HelloWorld::init()
{
	//////////////////////////////
	// 1. super init first
	if ( !Layer::init() )
	{
		return false;
	}

	Size visibleSize = Director::getInstance()->getVisibleSize();
	Vec2 origin = Director::getInstance()->getVisibleOrigin();

	auto pItmLabel1 = Label::createWithBMFont("fonts/fnt8.fnt", "Send Message");
	auto pItmMenu1 = MenuItemLabel::create(pItmLabel1, CC_CALLBACK_1(HelloWorld::menuSendMsgCallback, this));

	Menu* mn = Menu::create(pItmMenu1, NULL);
	mn->alignItemsVertically();
	this->addChild(mn);

	/////////////////////////////
	// 3. add your codes below...

	// add a label shows "Hello World"
	// create and initialize a label
	label = Label::createWithTTF("Hello World", "fonts/Marker Felt.ttf", 12); 

	// position the label on the center of the screen
	label->setPosition(Vec2(origin.x + visibleSize.width/2,
		origin.y + visibleSize.height - label->getContentSize().height));

	// add the label as a child to this layer
	this->addChild(label, 1);
	//_sioClient=Cocos2dExt::NativeCodeLauncher::connectToSocketIO("192.168.207.145", 3000);
	_sioClient = SocketIO::connect("ws://192.168.207.145:3000", *this);
	//	_sioClient = SocketIO::connect("http://192.168.207.145:3000", *this);

	if (_sioClient != NULL) _sioClient->emit("callServerEvent", "{\"message\":\"Hello Server.\"}");
	_sioClient->setTag("Client1");
	//注册服务器端事件
	_sioClient->on("callClientEvent", CC_CALLBACK_2(HelloWorld::callClientEvent, this));

	return true;
}

void HelloWorld::menuSendMsgCallback(Ref* pSender)
{
	//向服务器发出消息
	if(_sioClient != NULL) _sioClient->send("Hello Socket.IO!");
	//触发服务器callServerEvent事件
	if(_sioClient != NULL) _sioClient->emit("callServerEvent","{\"message\":\"Hello Server.\"}");
}

//委托协议方法
void HelloWorld::onConnect(SIOClient* client)
{
	log("HelloWorld::onConnect called");
	__String* s = __String::createWithFormat("%s connected!",client->getTag());
	label->setString(s->getCString());
}

void HelloWorld::onMessage(SIOClient* client, const std::string& data)
{
	log("HelloWorld::onMessage received: %s", data.c_str());
	__String* s = __String::createWithFormat("%s  received message.",client->getTag());
	label->setString(s->getCString());
}

void HelloWorld::onClose(SIOClient* client)
{
	log("HelloWorld::onClose called");
	__String* s = __String::createWithFormat("%s closed!",client->getTag());
	label->setString(s->getCString());

	if(client == _sioClient) {	
		_sioClient = nullptr;
	}
}

void HelloWorld::onError(SIOClient* client, const std::string& data)
{
	log("HelloWorld::onError received: %s", data.c_str());
	__String* s = __String::createWithFormat("%s   received error .",client->getTag());
	label->setString(s->getCString());

}

void HelloWorld::callClientEvent(SIOClient *client, const std::string& data) {
	log("HelloWorld::callClientEvent received: %s", data.c_str());
	__String* s = __String::createWithFormat("%s Server CallBack",client->getTag());
	label->setString(s->getCString());
}

the error：
cocos2d: fullPathForFilename: No file found at /cc_2x2_white_image. Possible missing file.
In the constructor of HttpClient!
HelloWorld::onError received: Client not yet connected
cocos2d: QuadCommand: resizing index size from [-1] to [2560]
“cocos2dx_networking.exe”(Win32): 已加载“C:\Windows\SysWOW64\secur32.dll”。无法查找或打开 PDB 文件。
“cocos2dx_networking.exe”(Win32): 已加载“C:\Windows\SysWOW64\mswsock.dll”。无法查找或打开 PDB 文件。
“cocos2dx_networking.exe”(Win32): 已加载“C:\Windows\SysWOW64\wship6.dll”。无法查找或打开 PDB 文件。
“cocos2dx_networking.exe”(Win32): 已加载“C:\Windows\SysWOW64\WSHTCPIP.DLL”。无法查找或打开 PDB 文件。
D/WebSocket.cpp (415): WebSocket thread start, helper instance: 05117E58

D/WebSocket.cpp (167): NOTICE: Initial logging level 911

D/WebSocket.cpp (167): NOTICE: Libwebsockets version: 2.1.0 desktop-8c9aqu5\cocosengine@DESKTOP-8C9AQU5-v3.4-141-gcddc296

D/WebSocket.cpp (167): NOTICE: IPV6 not compiled in

D/WebSocket.cpp (167): NOTICE: libev support not compiled in

D/WebSocket.cpp (167): NOTICE: libuv support not compiled in

D/WebSocket.cpp (167): NOTICE:  Threads: 1 each 30000 fds

D/WebSocket.cpp (167): NOTICE:  Compiled with OpenSSL support

D/WebSocket.cpp (167): NOTICE:  mem: per-conn:          392 bytes + protocol rx buf

D/WebSocket.cpp (873): scheme: ws, host: 192.168.207.145, port: 3000, path: /socket.io/1/websocket/96

D/WebSocket.cpp (167): NOTICE: Creating Vhost 'default' port -1, 1 protocols, IPv6 off

“cocos2dx_networking.exe”(Win32): 已加载“C:\Windows\SysWOW64\cryptsp.dll”。无法查找或打开 PDB 文件。
“cocos2dx_networking.exe”(Win32): 已加载“C:\Windows\SysWOW64\rsaenh.dll”。无法查找或打开 PDB 文件。
D/WebSocket.cpp (167): NOTICE: lws_protocol_init

D/WebSocket.cpp (1322): WebSocket (04FE0E20) Unhandled websocket event: 32

D/WebSocket.cpp (1322): WebSocket (04FE0E20) Unhandled websocket event: 29

D/WebSocket.cpp (1322): WebSocket (04FE0E20) Unhandled websocket event: 24

D/WebSocket.cpp (1197): WebSocket (04FE0E20) onConnectionError, state: 0 ...

D/WebSocket.cpp (1226): WebSocket (04FE0E20) onConnectionClosed, state: 2 ...

D/WebSocket.cpp (1256): onConnectionClosed, WebSocket (04FE0E20) is closing by server.

D/WebSocket.cpp (1279): WebSocket (04FE0E20) onConnectionClosed DONE!

D/WebSocket.cpp (1322): WebSocket (04FE0E20) Unhandled websocket event: 45

D/WebSocket.cpp (1322): WebSocket (04FE0E20) Unhandled websocket event: 33

D/WebSocket.cpp (1226): WebSocket (04FE0E20) onConnectionClosed, state: 3 ...

Websocket error received: 1
HelloWorld::onClose called
D/WebSocket.cpp (545): In the destructor of WebSocket (04FE0E20)

D/WebSocket.cpp (565): before join ws thread

D/WebSocket.cpp (167): NOTICE: lws_context_destroy

D/WebSocket.cpp (425): WebSocket thread exit, helper instance: 05117E58

线程 0xe94 已退出，返回值为 0 (0x0)。
D/WebSocket.cpp (567): after join ws thread

**Comment by nara1988** [comment]
why this happen？？

**Comment by nara1988** [comment]
the server side socket.io version is 2.1.0

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
