### ISSUE TITLE
Client doesnt connect. Only keeps on reconnecting

### ISSUE THREAD

**Issue by lanzosuarez** [socketio/socket.io#3245]
My socket setup is perfectly works when used in a local server. 
But this issue happens when it was deployed to prod server with a linux OS.

It doesn't connect and just keeps on reconnecting.

![image](https://user-images.githubusercontent.com/18522203/39933193-d54e542e-5574-11e8-91a4-e1999826ab09.png)

CLIENT

![image](https://user-images.githubusercontent.com/18522203/39933366-596489e0-5575-11e8-8ae3-f8629b23fc09.png)

SERVER

![image](https://user-images.githubusercontent.com/18522203/39933242-fdc12cec-5574-11e8-9952-676383c84dbe.png)

**Comment by bryanmcleod** [comment]
Are you using the same version client & server?

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socket.io/docs/v3/troubleshooting-connection-issues/#In-the-browser
