### ISSUE TITLE
span "... is typing" doesnt dissapear after user sent his message

### ISSUE THREAD

**Issue by abdulart** [socketio/socket.io#3247]
Hello,

I installed socket io both on linux server and macos localhost and the problem is still the same:
When user sent his message span "user_name is typing" doesnt dissapear and moreover all this messages stay in chat. Pls help

**Comment by darrachequesne** [comment]
Could you please provide a way to reproduce the issue? Thanks.

**Comment by abdulart** [comment]
sure, its http://renatavogue.com:3000/

**Comment by Code-Craver** [comment]
https://mikichat.glitch.me/

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
