### ISSUE TITLE
why socket.io cannot process connection from client written C lang.

### ISSUE THREAD

**Issue by hyunsooda** [socketio/socket.io#3248]
Hello, I am korean student.
my C client can connect to node server(see picture) but, node server cannot process connection from client
How can my C client connect to node server?

**Node.js code.**
`
io.on('connection', function(socket){
  	if(ids.indexOf(socket.id) === -1)
  		ids.push(socket.id);`

  	console.log(`${socket.id} : connect`);

  	socket.on('disconnect', () => { // clojure
  		console.log(socket.id);
  	})

  	socket.ondata = data => {
  		console.log(data);
  	}
  	console.log(socket.handshake.headers.host)
`});`

`http.listen(3000, function(){
  console.log('listening on *:3000');
});
`

**C code**

![proof2](https://user-images.githubusercontent.com/12508269/40179306-fa93bc8e-5a1e-11e8-9018-75ef57266ba3.PNG)

**Output**

![proof1](https://user-images.githubusercontent.com/12508269/40179322-03e86096-5a1f-11e8-86c1-ced412d3c3e6.PNG)

As you can check the output, my C client well connect to server. But, below picture is showed ignoring connection.
![proof3](https://user-images.githubusercontent.com/12508269/40179331-0b2f04e0-5a1f-11e8-9df9-367785c7d946.PNG)

**Comment by darrachequesne** [comment]
For future readers: please note that Socket.IO is not a websocket server implementation

Documentation: https://socket.io/docs/v3/#What-Socket-IO-is-not
