### ISSUE TITLE
Communication failed after project deployment

### ISSUE THREAD

**Issue by shoukailiang** [socketio/socket.io#3258]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

 Everything was fine with Windows 10, the communication was fine, and when I ported the project to ubuntu for deployment, the project was able to communicate at first and then not for a few minutes

![image](https://user-images.githubusercontent.com/24668909/40530707-6a3316a8-602c-11e8-826f-8a0147c8180d.png)

### Setup
- OS: ubuntu 16.04 
- browser: chrome 
- socket.io version: 2.0.4

**Comment by abelduran1** [comment]
Could be a CORS problem. Try this: 

app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});

**Comment by shoukailiang** [comment]
@abelduran1 thanks,but it doesn't work

**Comment by shoukailiang** [comment]
@abelduran1 The port of my node is also 9999 and should not be cross-domain

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
