### ISSUE TITLE
SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by F0x1** [socketio/socket.io#3260]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
C:\Users\Fox\Desktop\Project\node_modules\socket.io\lib\index.js:179
  const run = () => {
               ^

SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Fox\Desktop\Project\app.js:14:10)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS: Windows
- browser: Chrome
- socket.io version: 2.1.1

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

**Comment by sp00m** [comment]
Looks like your environment does not support ES6. Which Node version are you running? Make sure you use an up-to-date version.

**Comment by chenhongwu** [comment]
year

At 2018-05-30 19:16:19, "Christophe Maillard" <notifications@github.com> wrote:


Looks like your environment does not support ES6. Which Node version are you running? Make sure you use an up-to-date version.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
