### ISSUE TITLE
Socket IO client run in Node.JS does not connect to server

### ISSUE THREAD

**Issue by Darker** [socketio/socket.io#3261]
### You want to:

* [x] report a *bug*

### Current behaviour

Socket IO client does not connect to socket IO server when running in Node.JS environment

### Steps to reproduce (if the current behaviour is a bug)

I wrote a simple test case. 
```
    const socketioclient = require("socket.io-client");
    const io = require("socket.io");
    
    const server = io.listen(process.env.PORT);
    
    server.on("connection", (client) => {
        console.log("[SERVER] Client connected!");
        client.emit("chat", "Bye!");
        client.on("bye", () => {
            console.log("[SERVER] Client goodbye'd us.");
            client.disconnect();
        })
    });
    
    const client = socketioclient("localhost:" + process.env.PORT);
    client.once("connect", () => {
        console.log("[CLIENT] Connected to remote server, identificating.")
        this.sendIdentification();
    });
    client.on("chat", (msg) => {
        console.log("[CLIENT] Server sends message:", msg);
        if (msg.toLowerCase().indexOf("bye") != -1) {
            client.emit("bye");
        }
    });
    client.on("disconnected", () => {
        console.log("[CLIENT] Disconnected.");
    })
    client.on("error", () => {
        console.error("[CLIENT] Socket IO connection error.")
    });
```
If you run it, nothing happens. Client does not connect to the server at all.

### Expected behaviour

Client should connect to server the same way it works in the browser.

### Setup

- socket.io version: 2.1.1

**Comment by lionstuff** [comment]
> const client = socketioclient("localhost:" + process.env.PORT);

May be you need try to change uri for client connection from `localhost:` to `http://localhost:`

**Comment by doexclusive** [comment]
Any updates? this issue still presents in version 2.3.0

**Comment by darrachequesne** [comment]
As pointed out by @lionstuff, you need to add the protocol in the URL:

```js
const client = socketioclient("http://localhost:" + process.env.PORT);
```

There is a bug in the code [here](https://github.com/socketio/socket.io-client/blob/master/lib/url.js#L43) though, as `loc = false` in Node.js.
