### ISSUE TITLE
Documentation: server.attach(port[, options]) poorly documented, the rest of Server docs as well

### ISSUE THREAD

**Issue by Darker** [socketio/socket.io#3263]
### Type
Documentation problem.
### Steps to reproduce
Read the docs.
### Expected result
Knowing what the function does, especially where will the created server be exposed.
### Actual result
Knowledge did not increase at all after reading the docs.

# Detailed description:

At the moment, docs say:

> ```server.attach(port[, options])```
> 
>  - port (Number) the port to listen on
>  - options (Object)
> 
> Attaches the `Server` to an engine.io instance on a new http.Server with the supplied `options` (optionally).

First, I am not a native speaker and the sentence does not even make sense to me. "Attaches the `Server`" - what server? Also, wasn't the `server` (lowercase `s`) used before for `http.Server` instance, not the socket io instance? "engine.io instance on a new `http.Server`" - Now I'm totally lost, is `Server` attached to socket io, which is on `http.Server` instance?

I reached to the docs because the method being documented does not do *anything* at all on my machine. The port does not even open, I checked. So I was hoping to get at least three coherent simple English sentences about the method, how to use it and what to avoid. 

Can the documentation be updated? And why is that being done, could a decision be done on the variable names in the docs?

![Really bad, mmkay?](https://i.stack.imgur.com/wjSM2.png)

This is bad, mmkay?

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
