### ISSUE TITLE
how to destroy a client object after disconnected

### ISSUE THREAD

**Issue by liu602348184** [socketio/socket.io#3264]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour
i want to destroy a socket object but i can not found a way to do it just like ```socket.destroy()```

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS: Ubuntu16.04
- browser: Chrome
- socket.io version: 2.1.1

**Comment by darrachequesne** [comment]
For future readers: there is nothing to clean up upon disconnection, the socket object will simply be garbage collected.

Please reopen if needed.
