### ISSUE TITLE
Option to disconnect a client by default on the server when connecting to "Invalid Namespace"

### ISSUE THREAD

**Issue by ricxsar** [socketio/socket.io#3265]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:
Disconnect a client by default on the server when connecting to "Invalid Namespace"
* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour
the client is not disconnected when an error: "Invalid Namespace" occurred.

### Steps to reproduce (if the current behaviour is a bug)
1. Create a basic socket.io application.
2. Connect to the server with a namespace.
```
var socket = io.connect("/namespace-test");

socket.on("error", function(e){
      console.error(e);           // Invalid Namespace
})
```
**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
the client will be disconnected when an error: "Invalid Namespace" occurred when the option is `disconnect by default`.

### Implications
We have an emitter outside of the `socket.io server` ie. `socket.io-emitter server`. On the `socket.io server`, we setup an authentication. On the `socket.io-emitter server`, it broadcast some data to many namespaces. The `socket.io-emitter server` don't have any knowledge on authentication.

We would like the client to authenticate first before it receives data from the `socket.io-emitter server`. The problem is we cannot force disconnect a client connected on `Invalid Namespace` so we cannot enforce an authentication to it. Also the client receives data from `socket.io-emitter server` which is we don't want to.

### Flow
1. When the client try to connect to an `Invalid Namespace`, it is force to disconnect.
2. The server then add authentication handlers on that namespace.
         Since the server attached event handlers on that namespace, the client will not receive `Invalid Namespace` error anymore.
3. When the client retry to connect, it is then ask an authentication details.

### Setup
- OS: ANY
- browser: ANY
- socket.io version: 2.0.1

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socket.io/docs/v3/middlewares/
