### ISSUE TITLE
Socket leaking or not receiving events all users

### ISSUE THREAD

**Issue by soravgarg123** [socketio/socket.io#3267]
I had developed a iOS gaming real time application using swift language and I am using Node.Js and Socket.io server technologies, and we have large traffic more now approx 10K users comes at a time, and we are using NGINX web server with upstream feature with multiple ports to manage load balancing, right now we are sending messages to all online 10K users at a time, but 40% users receiving socket event remaining 60% not receiving, so i want to know is my NGINX configuration configured successfully or not ? it`s working with multiple ports or not ? I had attached my ng inx configuration file also /etc/nginx/nginx.conf (path).

Please let me know, why all users are not receiving socket event (message) ?

https://i.stack.imgur.com/oLYlU.png

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
