### ISSUE TITLE
Socket.io Error on server

### ISSUE THREAD

**Issue by iarafat** [socketio/socket.io#3271]
I was posting my question on StackOverflow (https://stackoverflow.com/questions/50757568) and also slack (https://socketio.slack.com/archives/C02AS4S1H/p1528454299000030).

### Setup
- OS: Xubnuntu
- browser: Chrome
- socket.io version: ^2.0.4

### Other information
I am tried to use socket io on the live server and I got this error.

> polling-xhr.js:264 GET http://sub.domain.com:3000/socket.io/?EIO=3&transport=polling&t=MFUVMS5 net::ERR_TIMED_OUT

But on my local server, the files worked perfectly.

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socket.io/docs/v3/troubleshooting-connection-issues/
