### ISSUE TITLE
A lot of connections

### ISSUE THREAD

**Issue by d4rckh** [socketio/socket.io#3272]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Server Side

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS: Windows 10 PRO
- browser: Chrome
- socket.io version: Latest

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

Code:
```js
var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);
var port = process.env.PORT || 3000;

app.get('/', function(req, res){
  res.sendFile(__dirname + '/index.html');
});

io.on('connection', function(socket){
  console.log('connected')
  socket.on('chat message', function(msg){
    io.emit('chat message', msg);
  });
});

http.listen(port, function(){
  console.log('listening on *:' + port);
});
```

When I run that, and I go to localhost:3000 port, it spams in console: `connected`

http://prntscr.com/jsheg4

**Comment by LoganDark** [comment]
You haven't posted your `index.html`, which is most likely the cause for the issue. Nobody can confirm it either way though without the `index.html`.

**Comment by Andre221** [comment]
The client-side? The client-side is..... good... I mean,,, .... yea. is good

**Comment by LoganDark** [comment]
???

Can you post it here?

**Comment by Andre221** [comment]
It's the same as in the chatapp-example repository @LoganDark

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
