### ISSUE TITLE
JS Socket Object Chaining

### ISSUE THREAD

**Issue by knoxcard** [socketio/socket.io#3274]
instead of doing....
```
socket.handshake.save()
socket.handshake.reload(err => {
})
```

i want to do this...
```
socket.handshake.save().reload(err => {
})

```
**Is this possible or in the workings?**

If not, I'd like to contribute when the proverbial "when I find the time" allows for it.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
