### ISSUE TITLE
Callback from user A to user B

### ISSUE THREAD

**Issue by IamNotHuman** [socketio/socket.io#3275]
Is there a way to do a callback that passes throw the server to another user?

**Comment by IamNotHuman** [comment]
For example:
```
// client A
this.socket.emit('call client b', room, (callback)=>{
    if(callback)
        console.log(true);
    else
        console.log(false);
});

// server

socket.on('call client b', function(room, callback1) {
    socket.to(room).emit('call client b', (callback2)=>{
        if(callback2)
           callback1(true);
        else
           callback1(false);
    });
});

// client B

socket.on('call client b', function(callback) {
     callback(true);
});
```

**Comment by Twois** [comment]
You can emit to client B from the server

//server
`io.to(socketIdOfClientB).emit('keyOfClientBListener', {
    "success": true,
    "msg": "have some fun"
});`

//Client side
`
socket.on('keyOfClientBListener', (data) => {
    //do something
});`

**Comment by bharathnallamothu** [comment]
@Twois i have 5 rooms on server let say "A", "B","C","D","E" 
**server side**
i.e `io.on('connection', (socket) => {
  console.log('New user connected');
   socket.on('disconnect', () => {
    console.log('User was disconnected');
  });
});
//function that create rooms
function connectSocket(data) {

  io.emit(data.device_id, data);
  console.log('room',data.device_id, 'created');

  // socket.broadcast.emit('newMessage', {
  //   from: message.from,
  //   text: message.text,
  //   createdAt: new Date().getTime()
  // });

}
// **room creation call**
connectSocket("A")

**client side**
var socket = io(<url>);
 socket.on('connect', function () {
			console.log('Connected to server');
		  });
		  socket.on(<roomname>, function (message) {
			console.log(message);
		  });
`
**problem**
i want to switch room **A** to **B** 
before switch i want to close all connections?

**Comment by LoganDark** [comment]
@bharathnallamothu excuse me, why did you mention me? I have nothing to do with this.

**Comment by bharathnallamothu** [comment]
@LoganDark  i thought you are good at socket io if not ignore ... :(

**Comment by LoganDark** [comment]
Sorry, I'm not very experienced with socket.io. I don't use it very much. Please don't mention me for trivial reasons. Additionally, if you'd like help, please try explaining your issue a little better. What's a "switch", for example? I may not be able to help, but others might if you give them something to work off of.

**Comment by darrachequesne** [comment]
@bharathnallamothu please open a new issue (note: you can wrap your code example within \`\`\`js `<your code>` \`\`\`, so that it is easier to read)

@IamNotHuman to answer your question, no there is currently no way to use acknowledgements between two clients, it only works between the client and the server.

**Comment by darrachequesne** [comment]
Merged into https://github.com/socketio/socket.io/issues/1811
