### ISSUE TITLE
Unable to send notification to particular user in socket.io io.to().emit() method

### ISSUE THREAD

**Issue by sudoshreyas** [socketio/socket.io#3276]
I am trying to send notification to the user when he/she gets a friend request.The problem I am facing is the server is sending the data but it is not able to be shown on the front end.

Here is the server side code

`module.exports=function(io) {

 io.on('connection',(socket)=>{
    socket.on('joinRequest',(myRequest,callback)=>{
       socket.join(myRequest.sender);
       callback();
    });
 socket.on('friendRequest',(friend,callback)=>{
      io.to(friend.receiver).emit('newFriendRequest',{
        from:friend.sender,
        to:friend.receiver
      });
      console.log('new friend request sent');
      callback();
    });
  });
}`

Here is the code on the client side
`socket.on('newFriendRequest',function(friend){
  console.log('heyy got you');
  console.log(friend);
});`

If in this server side  code  io.to(friend.receiver).emit('newFriendRequest',{ if i change it to friend.sender then it shows the output in the browser console but it is not going to show for friend.receiver

**Comment by Nishchit14** [comment]
Can you please share good fiddle or gist?

**Comment by darrachequesne** [comment]
For future readers:

Please see the example here: https://socket.io/get-started/private-messaging-part-1/
