### ISSUE TITLE
Is there a socket.IO server in JAVA?

### ISSUE THREAD

**Issue by bfang711** [socketio/socket.io#3278]
I only see socket.io-client JAVA, which I assume similar to socket.io-client (in Javascript), meaning it is for client only.  Our server side is written in JAVA, so I would like to know if there is a socket.io server in JAVA.

thanks

**Comment by picklespy** [comment]
You can try netty-socketio : https://github.com/mrniko/netty-socketio

**Comment by chengwubin** [comment]
> You can try netty-socketio : https://github.com/mrniko/netty-socketio

But it use 4 - year - old socket.io client and does not support newer versions

**Comment by picklespy** [comment]
It works for us with a 2.0.x client. Give it a try.

**Comment by darrachequesne** [comment]
You can also take a look at: https://github.com/trinopoty/socket.io-server-java
