### ISSUE TITLE
Fail over server

### ISSUE THREAD

**Issue by KenDodman** [socketio/socket.io#3279]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [] report a *bug*
* [X] request a *feature*

### Current behaviour
socket = io('http://'192.168.0.1':3002',{reconnectionAttempts:5});
socket.on('reconnect_failed', () => {
  console.log("reconnect_failed");
  socket = io('http://192.168.0.2:3002',{reconnectionAttempts:5});
}

This trys to connect to the backup, but it looses all events attached to origonal socket

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
Connect to backup server, retain all events attached to socket

### Setup
- OS: 
- browser:
- socket.io version:

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

Looking to connect to a backup server is primary server fails

**Comment by darrachequesne** [comment]
For future readers:

You can update the URI on the manager instance:

```js
socket.io.on("reconnect_failed", () => {
  socket.io.uri = "http://192.168.0.2:3002";
  socket.connect();
});
```

Not sure if we should make it an official API though. Please reopen if needed.
