### ISSUE TITLE
Socket client does not emit message in room.

### ISSUE THREAD

**Issue by HardikGlib** [socketio/socket.io#3281]
I am Trying to send message from one client to other.
One client is nodeJS client and second is AngularJS frontend client.
Here is my code:
Server Code:
`
function createConnection() {
    console.log("creating");
    io.sockets.on('connection', socketHandler);
    // io.on('disconnect', socketHandler);
}

createConnection();

function socketHandler(socket) {
    if(socket.connected) {
        console.log("Connection Successful with id: " + socket.id + " ...OK");
        socket.join('bot');
        socket.on('chat message', function(message) {
            console.log("Client Message >>> " + message.msg);
            // socket.emit('chat message', {user: message.user, msg: message.msg});
            // io.emit('chat message', {user: message.user, msg: message.msg});
        });

        socket.on('disconnect', function() {
            console.log("Connection Disconnected with id: " + socket.id + " ...OK");
            socket.leave('bot');
        });
    }
}
`

Client Code One NodeJS:
`
let io = require('socket.io-client');
let socket = io("http://192.168.1.30:3000");

function sendEventTrigger(ref, users, mesg) {
    if(socket.disconnected) {
        connectSocketServer();
        setTimeout(function() {
            // socket.emit(ref,{user: users, msg: mesg});
            console.log(socket.connected);
            socket.to('bot').emit(ref,{user: users, msg: mesg});
        }, 5000);
    } else {
        // socket.emit(ref,{user: users, msg: mesg});
        socket.to('bot').emit(ref,{user: users, msg: mesg});
    }
}

function connectSocketServer() {
    socket.on('connect', function() {
        console.log(" Watcher Connected with Socket Server");
    });
}

sendEventTrigger("chat message", "ravt", "You are Fool!!!");
`

### Current behaviour
On client side socket.emit() function works perfectly, but when i run socket.to().emit(), it fires error: "TypeError: socket.to is not a function"

### Steps to reproduce (if the current behaviour is a bug)
You can run both server and client side code and check it yourself, this might be not a bug. or You have not provided this functionality. 

### Setup
- OS: Ubuntu 16.04
- browser: chrome
- socket.io version: 2.1.1

**Comment by darrachequesne** [comment]
For future readers: broadcasting is a server-only concept.

Relation documentation:

- https://socket.io/docs/v3/broadcasting-events/
- https://socket.io/docs/v3/rooms/
- https://socket.io/get-started/private-messaging-part-1/
