### ISSUE TITLE
Socket reconnection problem when we switch internet/wifi connection

### ISSUE THREAD

**Issue by arpansac** [socketio/socket.io#3283]
Switching the wifi connection while using socket.io on a chat engine based on node breaks the connection, no errors shown on the new connection.

However, when I connect back to the same wifi, all the pending messages get delivered.

Is this normal or I'm missing something from the protocols. Please help!

**Comment by darrachequesne** [comment]
For future readers: the messages are indeed buffered until reconnection.

Documentation: https://socket.io/docs/v3/client-offline-behavior/#Buffered-events
