### ISSUE TITLE
Upgrade is often delayed when using Safari browser on Android.

### ISSUE THREAD

**Issue by picklespy** [socketio/socket.io#3284]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
When using Safari browser on Android, the Upgrade packet gets delayed many a times (not consistent), and eventually gets sent when the PING packet is sent. So, if the server is configured to send a welcome message onConnect, the message reaches the browser with a delay, which is not good UX.

### Steps to reproduce (if the current behaviour is a bug)
Open this chat in Safari on Android : https://app.engati.com/static/standalone/bot.html?bot_key=f943f0294af3437b
You will see the lag 90% of the time.
Check out the Charles proxy screenshot attached.

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
The Upgrade packet should not get delayed, and the client should get connected immediately.

### Setup
- OS: Android
- browser: Safari
- socket.io version: 2.1.1

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
<img width="1425" alt="screen shot 2018-06-29 at 15 38 50" src="https://user-images.githubusercontent.com/40716491/42125178-21dccb0e-7c8f-11e8-881c-6df028e9b08a.png">

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
