### ISSUE TITLE
Mobile (iOS) browsers can't handle 'unauthorized' ssl connection

### ISSUE THREAD

**Issue by kuehn-sba** [socketio/socket.io#3288]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Using socketio-client on a mobile device (iPad) for a https connection without a ssl certificate (
this address is set as 'allowed' inside browser) and using following options:

`{
                rejectUnauthorized: false, 
                secure: true
 }`

...leads to following error and falls back to polling:
_WebSocket network error: The operation could not be completed. (OSStatus-Fehler -9807.)_

### Expected behaviour
Connection via ws-engine by socketio-client, which is working succesfully for none-mobile browsers on Mac/Win OS.

### Setup
- OS: iOS 11
- browser: Safari Mobile
- socket.io version: 2.1.1

**Comment by darrachequesne** [comment]
For future readers: `rejectUnauthorized` is a Node.js-only option, it cannot be used in the browser.

Documentation: https://socket.io/docs/v3/client-initialization/#Node-js-specific-options
