### ISSUE TITLE
website is broken

### ISSUE THREAD

**Issue by AmoseKang** [socketio/socket.io#3289]
https://socket.io/ is broken.
It shows HTTPS  unsecured fault in Chrome.
After choosing proceed anyway, it returns 403 error.
plz fix it.

**Comment by darrachequesne** [comment]
Looking into this, sorry for the inconvenience..

**Comment by MickL** [comment]
Seems to be fixed, isn't it?

**Comment by darrachequesne** [comment]
Yep, sorry for the inconvenience. Closing now.
