### ISSUE TITLE
Allow frame loss on images streaming

### ISSUE THREAD

**Issue by abouroubi** [socketio/socket.io#3290]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [] report a *bug*
* [ ] request a *feature*

### Current behaviour
I use Socket.io for Android to send base64 encoded images from an Android device to a Node.js Socket.IO app. 
When the bandwidth is high enough everything works fine, but when the device has a bad network connectivity, the image are sent with a delay, that can be up to 10mn.

Is there a way to drop some frames, when connectivity isn't good ? My goal is to have less delay even if I loose data.

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS: 
- browser:
- socket.io version:

**Comment by darrachequesne** [comment]
For future readers: please see https://socket.io/docs/v3/emitting-events/#Volatile-events
