### ISSUE TITLE
Cannot remove typing text

### ISSUE THREAD

**Issue by beratetik** [socketio/socket.io#3291]
https://github.com/socketio/socket.io/blob/e0b2cb0c5a9af768a48c43f65643412cc8edc7df/examples/chat/public/main.js#L111

getTypingMessages function doesn't return typing elements. So it should be fixed like this:

    getTypingMessages(data).prevObject.fadeOut(() => {
      $(this).remove();
    });

**Comment by Dian8** [comment]
I've explored this issue too and found the following code works:

```
  // Gets the 'X is typing' messages of a user
  const getTypingMessages = (data) => {
    return $('.message.typing').filter(function(i) {
      return $(this).data('username') === data.username;
    });
  }
```

Does anybody know why '=>' syntax does not work here?

**Comment by darrachequesne** [comment]
@Dian8 it's because the scope of `this` is different when using `() => {}` or `function(){}`

@beratetik it should be fixed by https://github.com/socketio/socket.io/commit/7e35f901b8b60605b6cde94467033921ab582fc5
