### ISSUE TITLE
Weird room behaviour 

### ISSUE THREAD

**Issue by vanaart** [socketio/socket.io#3292]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behavior

When I join a room on the first connection, the messages don't come to the client. But when I reload the page it works. And if I place the join command outside the connection event, it works.

### Steps to reproduce (if the current behavior is a bug)
```
//Client side
// This works like a charm
socket.emit("join", uuid);

//Doesnt work
socket.on("connection", function () {
    socket.emit("join", uuid);
});
```

### Expected behavior
That I can join a room on the first connection. And that the message comes to the client

### Setup
- OS: Windows 10 Pro 64bit
- browser:  Google Chrome - 67.0.3396.99
- socket.io version:  2.1.1

**Comment by Leftier** [comment]
Im using version 1.4.5 try:

Client side:

```
var uuid= "#asd";

socket.on('connect', function() {
   socket.emit('join', uuid);
});
```


Server side:
```
io.sockets.on('connection', function(socket) {
    
    socket.on('join', function(uuid) {
        socket.join(uuid);
    });
});
```

**Comment by devwork-g** [comment]
@vanaart your code should be 
```
socket.on("**connect**", function () {
    socket.emit("join", uuid);
});
```
This will work.

**Comment by darrachequesne** [comment]
Documentation: https://socket.io/docs/v3/client-socket-instance/#Events
