### ISSUE TITLE
socketio cpp client still alive ?

### ISSUE THREAD

**Issue by Nelson-numerical-software** [socketio/socket.io#3294]
Short issue, is this project still alive ?
Currently, it seems that there is no more support for open tickets.

**Comment by robreuss** [comment]
Discouraging.

**Comment by darrachequesne** [comment]
It seems the main maintainer has no time to dedicate to the project currently... Is there anyone willing to help triaging issues and PR?

**Comment by Nelson-numerical-software** [comment]
Thanks to @darrachequesne to maintain this project used by many others.
