### ISSUE TITLE
Events being fire twice using SSL

### ISSUE THREAD

**Issue by arapocket** [socketio/socket.io#3296]
I am using node and express. I had everything working fine using HTTP. Now using HTTPS it seems all events are being fired twice.

## Relevant code:

In my **app.js**

```
  var server = https.createServer(options, app).listen(443, function () {
  });
```

```
var io = require('socket.io')(server);

io.on('connection', function (socket) {
someFunction(socket);
});
```

## What's Happening:
I am kind of lost as to what's happening but i'll try to explain it as best I can. Keep in mind that everything I describe here works perfectly using an http connection. Here are the only changes i've made:

1. Passing https server to var io = require('socket.io')(server) instead of http server

That's it!

I have a socket server started from my node app, and I also create connections from a desktop client, and a mobile application.

**Mobile Application**
Connecting to the socket, I see that io.on('connection') is fired a single time, however, all events emitted from the mobile application are fired twice.

**Desktop Application**
When I open the page that uses sockets, I see io.on('connection') is called twice.

_Tried on both 2.0.4 and 2.1.1_

**Comment by arapocket** [comment]
Something else seems to be the issue, closing for now.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
