### ISSUE TITLE
WebSocket connection to 'ws://localhost:3000/socket.io/?EIO=3&transport=websocket&sid=eVRYx4v_wA8UImsNAACo' failed: WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by parammca** [socketio/socket.io#3297]
Why my site goes slow when I opened it more than two tabs. With corresponding getting the above error. I am using Node Express for Backend and ReactJS for Frontend. 

Client Side:

        import React, { Component } from "react";
        import axios from 'axios';
        import $ from "jquery";
        import io from 'socket.io-client';
        import DatePicker from 'react-datepicker';
        import moment from 'moment';
        import {
                BrowserRouter as Router,
                Route,
                Link,
                Switch,
                Redirect,
                withRouter
        } from "react-router-dom";
 
     import 'react-datepicker/dist/react-datepicker.css';
     var formurlencoded = require('form-urlencoded');
     const socket = io('http://localhost:3001');
     class Abc extends Component {
          constructor(props) {
               super(props);
          }
          componentDidMount() {
               var user = localStorage.getItem("loggedInUser");
               socket.emit('set-user', user);
               user = JSON.parse(user);
              console.log(user);
          }
     }

The above code I used for client side which is in ReactJs.

Backend Code: 

     var express = require('express')
         , validate = require('express-validation')
         , bodyParser = require('body-parser')
           app     = express();

     var path    = require("path");
     var mysql   = require("mysql");
     var http    = require('http').Server(app);
     var io      = require('socket.io')(http);
     var bs = require("black-scholes");
     var greeks = require("greeks");
     var md5 = require('md5');
     var jwt = require('jwt-express');
     var config = require('./config');

     var router  = express.Router();
     var MySQLEvents = require('mysql-events');
     var dsn = {
        host:     config.dbconfig.host,
        user:     config.dbconfig.user,
        password: config.dbconfig.password,
     };
     var mysqlEventWatcher = MySQLEvents(dsn);

     io.on('connection',function(socket){
            console.log('We have user connected !');
           socket.on('set-user', function(user) {
            socket.user = user;
       });
     });

It's my Backend Code, So why it displayes  " WebSocket connection to 'ws://localhost:3000/socket.io/?EIO=3&transport=websocket&sid=eVRYx4v_wA8UImsNAACo' failed: WebSocket is closed before the connection is established.  "  and  " POST http://localhost:3000/socket.io/?EIO=3&transport=polling&t=MJC55jG&sid=X4-5-TB3lcJABYHeAACm 400 (Bad Request) "

I'm facing the above issue at Client End. 
Even when I opened our site in 2 or multiple tabs, then our site goes too slow.  
Why our site goes slow ?

OS: Windows 7
socket.io version: ^2.0.4
Browser: Google Chrome and Mozilla

**Comment by Frostai** [comment]
Hi, this is also happening to me on version 2.1.1, I narrowed it down to special characters. If I remove them from the data if works as expected, in my case not even same versions helped solve it.

**Comment by hequanb** [comment]
same for me on version 2.0.4

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socket.io/docs/v3/troubleshooting-connection-issues/
