### ISSUE TITLE
any .net support?

### ISSUE THREAD

**Issue by guftall** [socketio/socket.io#3303]
Is there any .net support for socket io client? i searched stackoverflow but seems those projects doesn't maintained by you.
I need socket io client in my c# project.

**Comment by darrachequesne** [comment]
There are indeed a few clients which are maintained by the community, please take a look at https://github.com/Quobject/SocketIoClientDotNet.

**Comment by darrachequesne** [comment]
For future readers:

There is a more active .Net client project: https://github.com/doghappy/socket.io-client-csharp

**Comment by RobotJohns** [comment]
Is there any csharp  server?
not supper .net server?
