### ISSUE TITLE
XHR poll error on high arrival rate or x number of connections

### ISSUE THREAD

**Issue by jeroendk** [socketio/socket.io#3304]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Sockek.io starts throwing XHR poll errors when number of connections are above a certain number or when the arrival rate is to high. It wont give an error on all requests but on some. CPU and memory are far from 100%. 

### Steps to reproduce (if the current behaviour is a bug) 
1. Server script

     `/*Accept  connections in nodejs*/
    io.on('connection', function (socket) { 
    });`

2. test script
https://gist.github.com/redism/11283852 
Running a test with arrival rate of 50 and total of 2500 connections.

### Expected behaviour
All sockets connect without a problem until CPU or memory becomes a problem.

### Setup
- OS: Node(linux) Docker container running on windows host (2 CPU, 4gb ram)
- browser: Chrome
- socket.io version: 2.1.1

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

Until 1900 connections almost each connection gets established but after this number the XHR poll error grows exponential.

No high CPU or Memory values for the docker containers.

The XHR poll error in detail:

    Error: xhr poll error
    at XHR.Transport.onError (D:\xxx\xxx\api\node_modules\engine.io- 
    client\lib\transport.js:64:13)
    at Request.<anonymous> (D:\xxx\xxx\api\node_modules\engine.io- 
    client\lib\transports\polling-xhr.js:128:10)
    at Request.Emitter.emit (D:\xxx\xxx\api\node_modules\component-emitter\index.js:133:20)
    at Request.onError (D:\xxx\xxx\api\node_modules\engine.io-client\lib\transports\polling- 
    xhr.js:309:8)
    at Timeout._onTimeout (D:\xxx\xxx\api\node_modules\engine.io- 
    client\lib\transports\polling-xhr.js:256:18)
    at ontimeout (timers.js:475:11) 
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) type: 'TransportError', description: 503

**Comment by lokk3d** [comment]
I'm getting the same problem with 8000 connections on my pc and at least 370 connections on my server. Any solution for this?

**Comment by lokk3d** [comment]
After so much research i've found a solution to this (on my production server). I've incremented the worker_connections parameter on my  config of nginx: 
https://www.nginx.com/blog/tuning-nginx/#:~:text=worker_connections%20%E2%80%93%20The%20maximum%20number%20of,to%20support%20a%20larger%20number.

**Comment by darrachequesne** [comment]
For future readers, I think the author did reach the maximum number of open files.

I've added some documentation about this here: https://socket.io/docs/v4/performance-tuning/#At-the-OS-level
