### ISSUE TITLE
Data loss : While emit data with 1 sec time interval then after sometimes getting some data loss. 

### ISSUE THREAD

**Issue by s-hari** [socketio/socket.io#3305]
Description
I am trying to send continuous stream with 1sec time interval, from flask server, but it stops updating over the UI after some time(i.e complete 180000) is never reached in the UI. I don't understand why. Please help
   
` from flask_socketio import SocketIO
from flask import Flask, render_template
from flask_socketio import send, emit
import time

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

breakLoop = False

@socketio.on('sendStream')
def message(arg1):
    global breakLoop
    breakLoop = True
    i=0
    maxI = 180000
    time.sleep(0.500)
    breakLoop = False
    emit('TSDetails',str(maxI))
    # data = {"count": i};
    # i += 1
    # i i<50:
    #     emit('myStream',str(data))
    #     print('message ', data)
    # else: print "limit crossed"
    while i<maxI:
        if breakLoop == True: break;
        time.sleep(1)
        i+=1000
        data = {"count":i};
        emit('myStream', str(data))

        print('message ', data)
if __name__ == '__main__':
    socketio.run(app,host= '0.0.0.0', port=5000)`

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
