### ISSUE TITLE
Handshake returns 403 Forbidden when Referrer not set/sent

### ISSUE THREAD

**Issue by julianlam** [socketio/socket.io#3306]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Socket.io connections do not establish due to a 403 Forbidden Response during the handshake (I think). Two separate clients have [tracked this down to a user setting `sendRefererHeader`](http://kb.mozillazine.org/Network.http.sendRefererHeader) to a more restrictive value (default 2, user set to 1)

### Steps to reproduce (if the current behaviour is a bug)
Set `sendRefererHeader` to `1` via Firefox `about:config`, access a site with socket.io

### Expected behaviour
Connect as normal, but instead, 403 Forbidden returned

### Setup
- OS: Windows and Linux
- browser: Mozilla Firefox
- socket.io version: 2.1.1

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

**Request Headers**
```
GET /socket.io/?EIO=3&transport=polling&t=MKLfI37 HTTP/1.1
Host: forum.netgate.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Cookie: express.sid=s%3A91BbV7Dk7MrLF1UuwmKpZBdbEMyY48i4.%2Bv9SLGedoIWzT6Y%2F5NGaFrC1pA34zjUkjAA75fBDg5c; io=otEvC_6E0NlVP1ExAJ8Z
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

**Response**
`{"code":4,"message":"Forbidden"}`

**Response Headers**
```
HTTP/2.0 403 Forbidden
server: nginx
date: Tue, 07 Aug 2018 18:27:31 GMT
content-type: application/json
X-Firefox-Spdy: h2
```

**Comment by beblaawy** [comment]
@julianlam I have been suffering from this issue, have you got any solution to this issue ?

**Comment by julianlam** [comment]
@beblaawy not yet, no. The only workaround so far is to not set that particular option in Firefox.

**Comment by beblaawy** [comment]
@julianlam but I get the same error with Chrome as well.

**Comment by darrachequesne** [comment]
This should be fixed in Socket.IO v3, as the `origins` method was removed.

Documentation: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#CORS-handling
