### ISSUE TITLE
Connection event fires three times per client

### ISSUE THREAD

**Issue by michaelb-01** [socketio/socket.io#3307]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
The connection (and disconnect) event fires three times every time a client connects (or disconnects). I'm trying to track which users are currently online and match their 'user' data if they are logged in and the user is stored in localStorage. However this isn't working since i'm getting three socket IDs for every connection (its hard to explain i'll put code below)

### Steps to reproduce (if the current behaviour is a bug)
I'm doing the following:

```
  let activeUsers = [];
  let numUsers = 0;

  io.on('connection', (socket) => {
    const clientId = socket.id;
    // Log whenever a user connects
    console.log('User connected');
    let found = 0;

    for (let i = 0; i < activeUsers.length; i++) {
      if (clientId == activeUsers[i].clientId) {
        found = 1;
      }
    }

    if (found == 0) {
      activeUsers.push({
        clientId:clientId,
        user:null
      });
    }

    numUsers++;
    io.emit('numUsers',numUsers);

    console.log(activeUsers);

    // Log whenever a user disconnects
    socket.on('disconnect', () => {
      console.log('User disconnected');

      numUsers--;
      io.emit('numUsers',numUsers);

      for (let i = 0; i < activeUsers.length; i++) {
        if (activeUsers[i].clientId == clientId) {
          activeUsers = activeUsers.splice(i,1);
          break;
        }
      }

      console.log(activeUsers);
    });

    // login
    socket.on('userLoggedIn', function(user) {
      console.log('USER LOGGED IN!!');
      console.log(user);

      for (let i = 0; i < activeUsers.length; i++) {
        if (activeUsers[i].clientId == clientId) {
          activeUsers[i].user = user;
          console.log(activeUsers);
          return;
        }
      }
    })

...
```

This prints an array of 3 client IDs in the console and numUsers shows 3 too.

### Expected behaviour
One connection message per client and one disconnect message per client.

### Setup
- OS: macOS 10.13.6
- browser: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
- socket.io version:     "socket.io": "^2.1.1", "socket.io-client": "^2.1.1"

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
I'm using Angular 6.0.0 and running nodemon, I had read that nodemon could cause issues but I tried without it and I get the same results. I start the server with `npm run web`:

    "web": "concurrently --kill-others \"npm run tsc\" \"npm run client\" \"npm run server\"",
    "client": "ng serve --aot --proxy-config proxy.conf.json",
    "server": "concurrently \"tsc -p server --watch\" \"nodemon index.js\"",

**Comment by darrachequesne** [comment]
For future readers:

Please see the example here: https://socket.io/get-started/private-messaging-part-1/
