### ISSUE TITLE
WebSocket is already in CLOSING or CLOSED state.

### ISSUE THREAD

**Issue by chfeizy** [socketio/socket.io#3308]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

![image](https://user-images.githubusercontent.com/6427629/44080120-a8066e58-9fdd-11e8-8e6f-bf543bb33bd6.png)
After a while, it will reconnect

chrome 68.0.3440.106

**Comment by chfeizy** [comment]
engine:socket packet +25s
  engine:socket got ping +0ms
  engine:socket sending packet "pong" (undefined) +0ms
  engine:socket flushing buffer to transport +0ms
  engine:ws writing "3" +0ms
  engine:ws closing +5s
  socket.io:client client close with reason ping timeout +1m
  socket.io:socket closing socket - reason ping timeout +1m

**Comment by chfeizy** [comment]
set pingTimeout: 60000 solve

**Comment by crobinson42** [comment]
This is related to #3259 and the _work around_ is changing `pingTimeout` on the server - appears to be an issue with Chrome
