### ISSUE TITLE
JSON.Parse in a listener makes the whole event cancel?

### ISSUE THREAD

**Issue by exapsy** [socketio/socket.io#3312]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
So, I've debugged some events of mine that weren't invoked for some reason.
I found out that having this line was the actual bug in my code ... stangely
```javascript
socket.on('eventName', (info) => {
  const infoToJson = JSON.parse(info) // When removed the event gets invoked
  socket.emit('eventName2', 'Message Sent only when JSON Parse not in the event');
}
```
I can't find a reason why though.

### Steps to reproduce (if the current behaviour is a bug)
At least the way it works to me, is just having an `event` on a `custom namespace` which runs a `JSON.parse(obj)`

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
To run fluently even with a `JSON.Parse(obj)`

### Setup
- OS: Ubuntu
- browser: socket-io-tester
- socket.io version: v9.6.1

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
