### ISSUE TITLE
When emitting large data, I receive same amount of data

### ISSUE THREAD

**Issue by abouroubi** [socketio/socket.io#3314]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Hello,

I'm using Socket.io on an Android application to send blobs to server.
When I start the app on android studio and start profiling the network usage, I noticed that the upload and the download sizes are the same, multiple MB/s.
It's normal for the upload, I'm sending lot of data, but I don't understand why I have that much download, as I'm not supposed to receive anything.

Is it the normal behavior of socket.io ? Is there any config I can use to stop the download ?

Thanks.

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

Not receive that much data.

### Setup
- OS:
- browser:
- socket.io version:

**Comment by darrachequesne** [comment]
Which tool are you using for profiling the network usage? Does it support websocket properly?

Also, does it happen with the JS client or only with the java client?

**Comment by abouroubi** [comment]
I'm using the Android profiler.
I think it supports web sockets, because when I stop sending packets with socket.io, the bandwidth goes to 0.
I don't have a JS client, only sending data with Android Client.

So from your answer I guess it's not the normal behavior ?

**Comment by mallik3230** [comment]
@darrachequesne 
Hi
i have problem with socket io v2.1.1

getting error like this ' Error : Websocket error ' on some devices mobiles and desktop

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
