### ISSUE TITLE
Cannot receive Buffer in NodeJS server/client

### ISSUE THREAD

**Issue by jacargentina** [socketio/socket.io#3316]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Emitting a `Buffer` is not working, the client is not receiving anything.

### Steps to reproduce

- `git clone https://github.com/jacargentina/socket-test`
- `cd socket-test`
- `npm install`
- `npm run test-fail`

Also can do `npm run test-pass` which is exactly the same but emitting a string, which simply works!

### Expected behaviour

Should just work

### Setup
- OS: macOS/Linux
- socket.io version: 2.1.1

**Comment by jacargentina** [comment]
@darrachequesne could u look at this please?

**Comment by darrachequesne** [comment]
@jacargentina thanks for providing a way to reproduce, that really helps :+1: 

That looks reaaaaaally weird, I'm not able to reproduce within the fiddle: https://github.com/socketio/socket.io-fiddle/tree/issues-3316

```
// server-side
  socket:test starting server +0ms
  socket:test connection +4s /hub#VduhqmBscd9Z3sMsAAAA
  socket:test data response +6ms <Buffer 68 69 21>
// client-side
  socket:test starting client +0ms
  socket:test connected +73ms
  socket:test data +0ms <Buffer 68 65 6c 6c 6f 20 79 6f 75 21>
```

Hmm... could it be related to `jest`?

**Comment by jacargentina** [comment]
@darrachequesne you're right with jest, replacing with mocha just works! At least i can go on with mocha, while jest team fixes this.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
