### ISSUE TITLE
Client still waiting for server responde for life!

### ISSUE THREAD

**Issue by ghadeerraad** [socketio/socket.io#3317]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

I cannot get the server's responses!! the client still waiting for it without a result!

### Steps to reproduce (if the current behaviour is a bug)

I tried to do many methods to fix this issue but it may be a bug !
> server.js
`var express = require('express');`
`var app = express().use(express.static(__dirname + '/'));`
`var server = require('http').createServer(app);`
`var io = require('socket.io')(server);`
`io.on('connection', function(){ console.log('connected!'); });`
`server.listen(3000);`

### Expected behaviour

I should get the "connected!" message in CMD after visiting the webpage but there is not!

### Setup
- OS: WIndows 7 64bit
- browser: Chrome
- socket.io version: 2.1.1

### Notes
- The server is working well without any problems.
- Chrome's console has no alerts,warnings, info or errors.
- node command still running without error.
- Socket.io client version is the same as the server (2.1.1).

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
