### ISSUE TITLE
Error is thrown out when Nodejs ups to 10.x

### ISSUE THREAD

**Issue by Maledong** [socketio/socket.io#3319]
* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

For Nodejs 8.x and 9.x (with uws = 8.x) works properly.

For Nodejs 10.x + uws (>= 8.x <= 9.x)： it throws an error saying "Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'".

For Nodejs 10.x + uws (>=10.x)：cannot find module 'uws'.

### Steps to reproduce (if the current behaviour is a bug)

Just assign 'uws' to `wsEngine`, each time I'll remove all the imports by directly removing node_modules and install them by running `npm i`. Then my `uws` is installed in the mode of dev-dependencies.

### Expected behaviour

Works properly like Node 8 or 9.

### Setup
- OS: Windows 8.1 (SP1), Linux (x64
- browser: N/A
- socket.io version: 2.0.4

### Other Info
I found `uws` is deprecated now, so in the main page of Socket.IO SHOULD'T SUPPORT THAT any more (See https://socket.io/docs/server-api/ part). And maybe there's something code to be changed with, or change to a new lib something like `uws`.

See the DUPLICATED `uws`: https://www.npmjs.com/package/uws, the version is changing TOO RAPIDLY, not so stable.

**Comment by Maledong** [comment]
Any other solutions or replacer lib? /cc：@darrachequesne

**Comment by Maledong** [comment]
Red: engine.io has referred uws, which is totally deprecated now：https://github.com/socketio/engine.io/blob/6a16ea119280a02029618544d44eb515f7f2d076/lib/server.js#L107

**Comment by Andrews54757** [comment]
@Maledong UWS has been deprecated because the owner wanted to make a hefty personal statement. There is nothing wrong with the code, but he has decided to go out of his way to publish an EMPTY package just to break about everything on the internet. What a f**ing do*chebag.

https://www.reddit.com/r/node/comments/91kgte/uws_has_been_deprecated/

**Comment by Maledong** [comment]
@Andrews54757：I see, however I'm not sure whether you've noticed that **since Nodejs 10.x, the uws cannot be used and there'll be runtime error...** This is a serious problem, and we have to use Node v8, 9, if we wanna keep this uws or when the author fixed that.... Try to think what will we do if we're running on Nodejs 10.x or later versions in the future according to this senario?!

What's more, the version is changing too rapidly, which looks unstable:( 

>What a f**ing do*chebag.

Ah ha haha……

**Comment by Maledong** [comment]
@Andrews54757: Many thanks, it's because I'm using ^10.x.y. So it will be automatically upgraded to 10.148.2. But I'll have a try and feedback to you :)

Thanks first!

**Comment by Maledong** [comment]
This is the problem I've been meeting with, I'm not sure whether you've seen this?
![image](https://user-images.githubusercontent.com/40081831/45583615-34adb680-b8f8-11e8-9f9e-d49d54574a9d.png)

Nodejs：8.12.0，10.10.0

**Comment by Maledong** [comment]
In my test, it seems ONLY 10.148.0 works on me without any other configs, leave it here for others if they need help :)

Thank you for your help again @Andrews54757 , It's YOU that have minded and tipped me to have a try of different kinds of versions!
