### ISSUE TITLE
[Possibly security relevant] accessing emits in rooms you're not joined

### ISSUE THREAD

**Issue by SeanDylanGoff** [socketio/socket.io#3322]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*
If an evil client is able to trigger an exception inside a io.to(room).emit() call (such as accessing a non existing property inside the arguments to emit) they can receive messages of subsequent emits to rooms they are not part of!

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

https://github.com/SeanDylanGoff/socketio_bugreport

### Expected behaviour

After 10 seconds, as soon as Alice starts triggering exceptions on the server, she will get Bob's emits even though she shouldn't. When Alice stops triggering exceptions (after another 10 seconds), she stops getting the messages.

*What is expected?*

### Setup
- OS: Detected with Linux server, osx/win client. reporoduced on osx
- browser:
- socket.io version: default via NPM fresh install

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

EDIT:
I could track the problem down further: it seems that when calling
io.to('room_a');
a subsequent
io.to('room_b').emit('response', 'secret');
gets emitted to room_b as well as room_a.
While calling io.to('room_a') is nonsensical, it *can* happen, when dealing with errors inside the call... simplified example: https://github.com/SeanDylanGoff/socketio_bugreport/tree/furthertests

**Comment by darrachequesne** [comment]
Duplicate of https://github.com/socketio/socket.io/issues/3431
