### ISSUE TITLE
Debug from chrome devtools

### ISSUE THREAD

**Issue by ashish101184** [socketio/socket.io#3326]
Hello Team,

I want to debug scoket IO server. 

I can see logs while doing debug = * pm2 start system.js & pm2 logs. 

But while inspecting my application from chrom-devtools using 'about:inspect' and add my_server:7000 and console does not show me logs regarding socket.io. 

Please suggest if I am doing something wrong.

Thanks
Ashish

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
