### ISSUE TITLE
does not work on some android device browsers socket io v2.1.1

### ISSUE THREAD

**Issue by mallik3230** [socketio/socket.io#3328]
socket io v2.1.1 does not connect on some android device browsers
getting error like this 'xhr-polling error '

user agent details of android devices browsers

Mozilla/5.0 (Linux; Android 7.0; SM-J730GM Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Mobile Safari/537.36
Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) CriOS/68.0.3440.83 Mobile/15G77 Safari/604.1
mozilla/5.0 (linux; android 5.1.1; a37f build/lmy47v) applewebkit/537.36 (khtml, like gecko) chrome/43.0.2357.93 mobile safari/537.36
mozilla/5.0 (windows nt 6.1; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/68.0.3440.106 safari/537.36
Mozilla/5.0 (Linux; Android 5.1; ELUGA_I2 Build/LMY47D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 7.0; en-US; Lenovo K33a42 Build/NRD90N) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 UCBrowser/12.9.0.1141 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 6.0.1; en-US; Le X821 Build/FGXOSOP5801910121S) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 UCBrowser/12.8.0.1120 Mobile Safari/537.36
Mozilla/5.0 (BB10; Touch) AppleWebKit/537.35+ (KHTML, like Gecko) Version/10.2.1.3412 Mobile Safari/537.35+
mozilla/5.0 (linux; android 7.0; sm-g570f build/nrd90m) applewebkit/537.36 (khtml, like gecko) chrome/65.0.3325.109 mobile safari/537.36
Mozilla/5.0 (Linux; Android 8.0.0; SAMSUNG SM-J810G Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/7.0 Chrome/59.0.3071.125 Mobile Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/537.86.7

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
