### ISSUE TITLE
Why isn't there documentation for handlePreflightRequest?

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io#3334]
It's not documented as an option here: https://github.com/socketio/socket.io/blob/master/docs/API.md#new-serverhttpserver-options

Even though this works: https://github.com/socketio/socket.io-client/issues/1140#issuecomment-325958737

**Comment by siddhant1** [comment]
Should i work on this one?

**Comment by 5ebastianMeier** [comment]
Another problem is that this solution works perfectly, but breaks in an TypeScript environment because the typings in the package `@types/socket.io` also don't contain the option.

**Comment by NoniHunter** [comment]
Already documented here [https://github.com/socketio/engine.io#methods-1](url) as part of Engine.IO.

**Comment by EO2875** [comment]
Yeah, this isn't a part of Socket.IO but of Express JS

**Comment by darrachequesne** [comment]
Documentation for v2: https://socket.io/docs/v2/handling-cors/

Documentation for v3: https://socket.io/docs/v3/handling-cors/
