### ISSUE TITLE
Website SSL errror 

### ISSUE THREAD

**Issue by xeewi** [socketio/socket.io#3336]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

[Socket.io](http://socket.io) website certificate verification failed on firefox. 
I can't access to the documentation :/ 
![image](https://user-images.githubusercontent.com/18403647/46011410-097c5180-c0c6-11e8-8418-dc5950d8aa43.png)

### Steps to reproduce (if the current behaviour is a bug)

Just connect on [Socket.io](http://socket.io).

### Expected behaviour

Be able to go on the website.

### Setup
- OS: Ubuntu 18.04.1
- browser: Firefox
- socket.io version: Meh.

**Comment by darrachequesne** [comment]
It seems the platform where the website is hosted has encountered some issues yesterday. It should be fixed now, sorry for the inconvenience.
