### ISSUE TITLE
socket. handshake.address return ::ffff:127.0.0.1

### ISSUE THREAD

**Issue by yqsailor** [socketio/socket.io#3337]
I want get the client ip, but socket. handshake.address return ::ffff:127.0.0.1,what should i do?

**Comment by darrachequesne** [comment]
You should be able to force the server to listen to IPv4 addresses:
```js
const server = require('http').createServer();
const io = require('socket.io')(server);
io.on('connection', (socket) => {
  // ...
});
server.listen(3000, '0.0.0.0');
```

**Comment by LaKing** [comment]
You may have a proxy on your system, so you may need to check the x-forwarded-for headers in socket.handshake ...
