### ISSUE TITLE
Add a way to add headers on handshake (Feature)

### ISSUE THREAD

**Issue by claudioc** [socketio/socket.io#334]
I think it should be a good idea to give the options to add headers to the handshake (client side, of course). If my web application (not served by node/express) is on another host (different domain) than the socket.io server endpoint, I'll not be able to transparently receive cookie. So, I need to inject information in the HTTP headers for the sake of authentication.

**Comment by nomi-ramzan** [comment]
Hi is there any way to set headers like `headers:{Authorization:"Bearer token"}` ?
