### ISSUE TITLE
Minor styling problem on the landing page.

### ISSUE THREAD

**Issue by jukefr** [socketio/socket.io#3343]
On the landing page the you show a code example and the result.
Here is what it looks like on my screen (15" macbook on Vivaldi)
![Imgur](https://i.imgur.com/enWJIam.png)
Here is the fix
![Imgur](https://i.imgur.com/sre7A7C.png)
And here is after the fix
![Imgur](https://i.imgur.com/xOOB062.png)

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
