### ISSUE TITLE
passing `undefined` as a 3rd param to `socket.emit` causes `callback` to be null on BE

### ISSUE THREAD

**Issue by MaxYari** [socketio/socket.io#3345]
Hello there!

### I want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

If you do `socket.emit("foo",function(data){this is a callback},undefined);`
note 3rd param = `undefined`, apparently if you do this  then `callback` (2nd param) will be `null` on backend, without `undefined` - it's a function, as expected. 
Potential case for this to happend - if you have a wrapper doing something like `socket.emit(msg,param1,param2)`, issue becomes not so easy to spot (my case).

### Steps to reproduce (if the current behaviour is a bug)

Frontend: `socket.emit("foo",function(data){console.log("I'm never invoked")},undefined);`
Backend: `socket.on(‘foo’, (callback) => {console.log(callback)}); //callback == null`

### Expected behaviour

`undefined` should be treated as absence of parameter and shouldn't cause other parameter to nulllify for some reason.

### Setup
- OS: Windows 10 (FE)
- browser: latest Chrome
- socket.io version: latest afaik, can ask BE dev if critical

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
