### ISSUE TITLE
CDN Down

### ISSUE THREAD

**Issue by osterman** [socketio/socket.io#3347]
## what
* https://cdn.socket.io/ is offline
* http://www.isitdownrightnow.com/cdn.socket.io.html

![image](https://user-images.githubusercontent.com/52489/46718099-fd90a380-cc1e-11e8-94e8-f94e0f180363.png)

**Comment by osterman** [comment]
Hrmm... https://cdn.socket.io/socket.io-1.4.4.js doesn't work (used in every slackin service). https://cdn.socket.io/socket.io-1.6.0.js works.

**Comment by darrachequesne** [comment]
We're looking into this. Sorry for the inconvenience..

**Comment by darrachequesne** [comment]
It should be fixed now, I think the issue can be closed.
