### ISSUE TITLE
What's the difference between socket.io-client and socket.io

### ISSUE THREAD

**Issue by codepandy** [socketio/socket.io#3348]
I think the client used on the client.
but this demo:
https://github.com/socketio/chat-example/blob/master/index.html

this is not socket.io-client? why?

when use the client , and when use the socket.io？

**Comment by LordMajestros** [comment]
Socket.io-client is provided in the node.js implementation for testing on node.js. This script https://cdn.socket.io/socket.io-1.2.0.js is used on the browser side and only provides a client connection to a socket.io server. the line
```
var socket = io();
```
returns a client connection to a socket.io server.

**Comment by codepandy** [comment]
Should I use the https://cdn.socket.io/socket.io-1.2.0.js when I use the react development?

**Comment by shahinghasemi** [comment]
So How it is used on the server-side (node.js)? I see many examples that `socket.io-client` is used on the server-side. I want to know the usage that when should it be used on the server-side?

**Comment by darrachequesne** [comment]
For future readers:

The `socket.io` package contains the Socket.IO server, and the `socket.io-client` package contains the Socket.IO client.

@shahinghasemi the client can totally be used on the server side (in Node.js) to establish a connection to a Socket.IO server. It might not be the most performant way to establish a connection between two servers, but it should not require to open a new port on the firewall as it works on the classic HTTP ports (80/443).
