### ISSUE TITLE
internalOnClose code change from 2.0.3  to 2.1.1

### ISSUE THREAD

**Issue by yayuntian** [socketio/socket.io#3351]
```
this.socket.conn.transport.socket.internalOnClose = (code, reason) => {
            this.closeCode = code;
            if (onCloseFunction) {
                onCloseFunction(code, reason);
            }
        };
```

After upgrading to the 2.1.1 version, refresh the chrome browser and receive the status code of 1000.
but in 2.0.3 version status code return 1001.

Forced to refresh the browser or close, it should be abnormally disconnected instead of the normal.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
