### ISSUE TITLE
Orphan socket connections on disconnect and connect in the same tick

### ISSUE THREAD

**Issue by stevestevensonneds** [socketio/socket.io#3354]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

`socket.disconnect()` then followed by `socket.connect()` can result in 1 connection being closed and another 2 connections opened. Leaving one of the connection orphaned.

### Steps to reproduce (if the current behaviour is a bug)

```
  var socket = io();
  setInterval(() => {
    socket.disconnect();
    socket.connect();
  }, 1000);
```

### Expected behaviour

Only one connection is opened.

### Setup
- OS: Linux
- browser: Chrome v70
- socket.io version: 2.1.1 Latest

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

Waiting at least one tick to connect will not cause the issue;

```
  var socket = io();
  setInterval(() => {
    socket.disconnect();
    // for demo only
    setTimeout(() => socket.connect(), 20);
  }, 1000);
```

**Comment by darrachequesne** [comment]
For future readers:

This should be fixed by https://github.com/socketio/socket.io-client/commit/99c2cb8421361487ed7c876edd8670bb69a5c5b5, included in `socket.io-client@4.4.0`.
