### ISSUE TITLE
Something wrong while using socket.io with nginx to Load Balancing.

### ISSUE THREAD

**Issue by hequanb** [socketio/socket.io#3356]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*While using nginx ,socket.io and nodeJs to build a multiple nodes socket.io chatting room, A server's connection becomes unstable and reconnecting frequently while B server's socket.io connections go well .*

### Setup
- socket.io version: 2.0.4
- nginx version: 1.13.8
- socket.io.redis: 5.2.0

### socket.io server setup
`const io = require('socket.io')(httpServer);
io.adapter(soRedis({
  host: serverConfig.redis.host, 
  port: serverConfig.redis.port, 
  requestsTimeout: 10000,
  password: serverConfig.redis.password,
}));`

### nginx setup
`#user  nobody;
worker_processes  8;
worker_cpu_affinity 00000001 00000010 00000100 00001000 00010000 00100000 01000000 10000000;
worker_rlimit_nofile 102400;

events {
    worker_connections  102400;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
	
	proxy_cache_path /data/nginx/proxy_cache_dir levels=1:2 keys_zone=cache_one:1024m inactive=1d max_size=20g;

    #自定义日志格式
	log_format  main  '\nsource:$remote_addr - $remote_user --- url:$request_uri\n serverIp:$upstream_addr\n aid:$COOKIE_aid\n'
    access_log  logs/access.log  main;	
	
    sendfile        on;
    tcp_nopush     on;

    #压缩
    gzip  on;
    gzip_comp_level 4;
	gzip_buffers 4 16k;
	gzip_min_length 1k;
	gzip_types text/plain application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
	gzip_vary on;
	gzip_disable "MSIE [1-6]\.";	
	
    server {
        listen       80;
        server_name  www.xxx.net;
		
		proxy_cache cache_one;
        root /data/nginx/proxy_cache_dir;
		
        access_log  logs/host.access.log  main;
		
        #所有请求负载均衡
        location / {
            # other
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_pass http://serversocket;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            #proxy_redirect off
        }
    }

     #解决socket双机问题
	upstream serversocket{
		#hash $COOKIE_aid;
		ip_hash;
		server server1:3000 max_fails=3 fail_timeout=30s;
		server server2:3000 max_fails=3 fail_timeout=30s;
	}

}`

### nginx error-logs
`upstream prematurely closed connection while reading response header from upstream`

**Comment by hequanb** [comment]
Problem still exists, however, everything goes well while I use only one nodeJs server

**Comment by hequanb** [comment]
The problem still exists, and the server side report a 'disconnect' event which says that 'transport error' and nothing more.
No idea why that requests hit the same server (socket.io server) but the server side failed to response.

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socket.io/docs/v3/reverse-proxy/#NginX
