### ISSUE TITLE
Socket IO Hangs browser on MAC and Mobile browsers

### ISSUE THREAD

**Issue by nategurian** [socketio/socket.io#3362]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

On my windows machine, I am able to load my application and use it as intended. When I published the app to heroku, I noticed socket.io is not connecting on mobile browsers or Safari. So I cloned my repo and installed it on my MAC for testing, and I cant even get the application to load locally. The site basically hangs and never loads and I dont get any errors in the console. 

I do get this though:
<img width="746" alt="screen shot 2018-10-22 at 8 46 58 pm" src="https://user-images.githubusercontent.com/24398108/47756395-4238b900-dc78-11e8-824d-c686e958376f.png">

### Expected behaviour

Be able to load the site locally for testing.

### Setup
- OS: MAC 10.13.3
- browser: Safari 10
- socket.io version: 2.1.1

https://supportchatdev.herokuapp.com is my published app on Heroku

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
