### ISSUE TITLE
socket.io doesn't work at all, not even the example(ws works)

### ISSUE THREAD

**Issue by IAmJustAHuman** [socketio/socket.io#3364]
### You want to:

* [x] report a *bug*

### Current behaviour

It just doesn't even fucking work(Connection refused)

### Steps to reproduce (if the current behaviour is a bug)

1. Clone example or use the code from the docs

### Expected behaviour

The client should connect to the server.

### Setup
- OS: Windows & Linux
- browser: Chrome & Firefox
- socket.io version: 2.1.1

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

The ws module works wonderful but it misses some needed feautures that socket.io has. Socket.io doesn't work on TWO browsers & TWO computers. I just wasted 3h of my life, please get your fu** example to work.

**Comment by IAmJustAHuman** [comment]
Sorry for the outrage but i have limited time and this cost me much...

**Comment by X-NicON** [comment]
?

```
<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.1.1/socket.io.js"></script>
 
<textarea id="msg-txt" rows="10" style="width:100%;"></textarea>
<button id="send">send</button>
 
<script>
var socket = io('ws://<DOMAIN>:<PORT>');
socket.on('connect', function() {
    console.log('connect success');
});

socket.on('message', function(msg) {
    console.log(msg);
});
 
socket.on('disconnect', function(status) {
    console.log(status);

    if (status === 'io server disconnect') {
        socket.close();
        // reconnect manually
        socket.connect();
    }
});

$('#send').on('click', function(){
    socket.send($('#msg-txt').val());
    console.log($('#msg-txt').val());
});
</script>
```

**Comment by Nishchit14** [comment]
Try [Firecamp](https://chrome.google.com/webstore/detail/firecamp/eajaahbjpnhghjcdaclbkeamlkepinbl)  to debug it, It would save your time to test about socket connection. It's working or not.

![image](https://user-images.githubusercontent.com/5078921/51088490-60e22280-1786-11e9-83a3-d99807571385.png)
