### ISSUE TITLE
Help me with socket.io

### ISSUE THREAD

**Issue by marccasco** [socketio/socket.io#3365]
I have a nodejs server, with socket.io connection with my clients.
The problem I have, is that when my clients close the page, the socket detects the disconnection perfectly, but still keeps running the functions that that socket runs when it is connected.

I need to know how to stop that socket without affecting the other active sockets.

Thank you.

**Comment by X-NicON** [comment]
?

```
io.on('connect', (wsocket) => {

    wsocket.on('disconnect', (reason) => {
        if (reason === 'io client disconnect') {
           wsocket.disconnect();
        }
    });

});
```

**Comment by marccasco** [comment]
> ?
> 
> ```
> io.on('connect', (wsocket) => {
> 
>     wsocket.on('disconnect', (reason) => {
>         if (reason === 'io client disconnect') {
>            wsocket.disconnect();
>         }
>     });
> 
> });
> ```

I already have that function, and yes, it is detected when the client's page is closed.
But the functions of the node that were activated when the client opened the page, continue running when the page closes.
For example, if you put in when the client opens the page of the socket a loop of ++, and showing a number of the loop, when the client closes the page, it continues adding numbers even though it should not.

**Comment by X-NicON** [comment]
then the problem is not sockets.

may be check client is connected? on loop

if ( io.sockets.connected[wsocket.id] )

**Comment by marccasco** [comment]
> then the problem is not sockets.
> 
> may be check client is connected? on loop
> 
> // connectId - saved user socket id = from wsocket.id
> if ( io.sockets.connected[connectId] )

It is true that you can check, but I call other functions that within those functions have their own loops, and those loops are those that do not stop even when you have closed the page.
Any ideas?
Thank you

**Comment by Nishchit14** [comment]
Try [Firecamp](https://chrome.google.com/webstore/detail/firecamp/eajaahbjpnhghjcdaclbkeamlkepinbl) for testing

![image](https://user-images.githubusercontent.com/5078921/51088490-60e22280-1786-11e9-83a3-d99807571385.png)

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
