### ISSUE TITLE
How to listen the event of ping in server side?

### ISSUE THREAD

**Issue by yqsailor** [socketio/socket.io#3367]
I want listen all event of the client in server side? for example, I want listen the event of ping, what should i do?

thanks for first

**Comment by RosenTomov** [comment]
You have to listen on yourSocket.conn instead:

```
socket.conn.on('packet', packet => {
	if (packet.type === 'ping') {
		console.log(`Received ping from client}`);
	}
});

socket.conn.on('packetCreate', packet => {
	if (packet.type === 'pong') {
		console.log(`Sending pong to client.`);
	}
});
```

https://socket.io/docs/server-api/#socket-conn

**Comment by shlomisas** [comment]
> You have to listen on yourSocket.conn instead:
> 
> ```
> socket.conn.on('packet', packet => {
> 	if (packet.type === 'ping') {
> 		console.log(`Received ping from client}`);
> 	}
> });
> 
> socket.conn.on('packetCreate', packet => {
> 	if (packet.type === 'pong') {
> 		console.log(`Sending pong to client.`);
> 	}
> });
> ```
> 
> https://socket.io/docs/server-api/#socket-conn

looks like it's the opposite, I'm getting only `pong` to the `packet` event callback. using SocketIO 3.

**Comment by RosenTomov** [comment]
It got reversed in v3
https://socket.io/blog/engine-io-4-release/#Heartbeat-mechanism-reversal
https://socket.io/docs/v3/migrating-from-2-x-to-3-0#No-more-%E2%80%9Cpong%E2%80%9D-event-for-retrieving-latency

**Comment by shlomisas** [comment]
it's totally not clear from the 2-to-3 migration link you sent (which i actually read before answering here), also their example:

```
socket.on("ping", (cb) => {
    if (typeof cb === "function")
        cb();
});
```

not even working.

I found that this serves me well:

```
socket.conn.on('packet', async (packet) => {
    try {
        if (packet && packet.type === 'pong') {
            doSmtg();
        }
    } catch(e) {
        logger.error(e);
    }
});
```
