### ISSUE TITLE
Document the handling of errors in middleware

### ISSUE THREAD

**Issue by murrayju** [socketio/socket.io#3371]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

The documentation is seriously lacking around error handling in middleware functions.

The [client documentation for the error event](https://socket.io/docs/client-api/#Event-%E2%80%98error%E2%80%99) states that you should expect to receive an `object`. However, if you write your middleware as suggested in the [server documentation for `use()`](https://socket.io/docs/server-api/#socket-use-fn):

```
io.on('connection', (socket) => {
  socket.use((packet, next) => {
    if (packet.doge === true) return next();
    next(new Error('Not a doge error'));
  });
});
```

On the client side you receive a `string` (containing the error's message 'not a doge error'), *not* an `object`.

After nearly giving up on passing additional data, I discovered [this stackoverflow post](https://stackoverflow.com/a/38117590/866224), which describes a magical `err.data` property. If this is set, then that object is sent to the client (*instead* of the message string).

```
io.on('connection', (socket) => {
  socket.use((packet, next) => {
    if (packet.doge === true) return next();
    const err = new Error('This string is not used at all');
    err.data = {
      message: 'Not a doge error',
      isADoge: false,
    };    
    next(err);
  });
});
```

This behavior should be documented.

### Steps to reproduce (if the current behaviour is a bug)

Look at https://socket.io/docs/server-api/#socket-use-fn and https://socket.io/docs/client-api/#Event-%E2%80%98error%E2%80%99

### Expected behaviour

The documentation describes the behavior above.

### Setup
- OS: n/a
- browser: n/a
- socket.io version: current

**Comment by murrayju** [comment]
I did some additional testing, and found that it isn't necessary to use an `Error` instance at all. Any object with a `data` property will have the same result (`data` is serialized and sent to the client).

```
io.on('connection', (socket) => {
  socket.use((packet, next) => {
    if (packet.doge === true) return next();
    next({ data: {
      message: 'Not a doge error',
      isADoge: false,
    }});    
  });
});
```

Is equivalent to the second code block in the issue description.

**Comment by darrachequesne** [comment]
Documentation added here: https://socket.io/docs/v3/middlewares/#Handling-middleware-error
