### ISSUE TITLE
How to delete the useless rooms?

### ISSUE THREAD

**Issue by yqsailor** [socketio/socket.io#3374]
When the room is abandoned, I want to delete it.What should i do?

thanks for first

**Comment by johnmanko** [comment]
Stackoverflow might have your answer.  Generally, github should be reserved for bugs/enhancements; Stackoverflow/Slack are great places for support.

**Comment by Prateek327** [comment]
What are you using in your backend ?

**Comment by darrachequesne** [comment]
For future readers: the rooms are cleaned up when all Socket instance have left it.

The source code can be found here: https://github.com/socketio/socket.io-adapter

Please reopen if needed.
