### ISSUE TITLE
What is the standard socket.io library that should be used in react-native project ?

### ISSUE THREAD

**Issue by ronastlelobo** [socketio/socket.io#3375]
Socket.io official website doesn't show me documentation for react-native. I search for multiple libraries, but most of them looked unreliable.

Link of a standard library used will be helpful.

Thank you

**Comment by johnmanko** [comment]
https://stackoverflow.com/questions/tagged/socket.io

**Comment by darrachequesne** [comment]
For future readers:

Please see the example here: https://github.com/socketio/socket.io/tree/master/examples/react-native
