### ISSUE TITLE
Socket.io disconnect after long http request

### ISSUE THREAD

**Issue by karProgrammer** [socketio/socket.io#3376]
I use socket.io with express server, when I start an http request that take about 20 sec the connection is disconnected then reconnected again. How can I solve this problem?

**Comment by johnmanko** [comment]
Stackoverflow is a betting place to ask support questions: https://stackoverflow.com/questions/tagged/socket.io

**Comment by lucidwater** [comment]
同样的问题

**Comment by hequanb** [comment]
I use nginx to load balance with ip_hash, and the request did goes to the right server with reverse-proxy.
however,  some request will fail to get a response from socket.io server.
And the error logs of nginx is 'upstream prematurely closed connection while reading response header from upstream',
same question.

**Comment by Nishchit14** [comment]
@karProgrammer Is it still happening? 

You can test it in [Firecamp](https://chrome.google.com/webstore/detail/firecamp-a-campsite-for-d/eajaahbjpnhghjcdaclbkeamlkepinbl), let me know if still facing the issue.

**Comment by roy2651** [comment]
is this solved?

**Comment by darrachequesne** [comment]
@karProgrammer what do you mean by:

> when I start an http request that take about 20 sec

Is this a `socket.emit()`? Or a plain HTTP request to the Express part of your application?

**Comment by darrachequesne** [comment]
For future readers: you can increase the value of the `pingTimeout` option (defaults to 20s now).

I've added a note here: https://socket.io/docs/v4/troubleshooting-connection-issues/#you-are-trying-to-send-a-huge-payload
