### ISSUE TITLE
what is the problem between socket.io and node-webkit

### ISSUE THREAD

**Issue by fakirpic** [socketio/socket.io#3377]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

hi i am just created a very small module

```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
function sockettest(domain)
{
	
return new Promise(function(resolve, reject) {
conn=require('socket.io-client')('https://ws.'+domain.replace('www.').replace('m.'),{
  forceNode:true,
  transports: ['websocket'],
  extraHeaders: {
	  'Origin': 'https://www.'+domain.replace('www.').replace('m.')
  }
});

conn.on('connect',  function(socket){
conn.emit('query', {"body":{"siteId":"9","source":1,"lang":"tr"},"action":"site.session","frontEndId":0,"token":null});
conn.on('response', function(data){

	if(data && data.body)
	{
		resolve(data.body);
	}
	
	if(data && data.body && data.body.error)
	{
		reject(data.body);
	}
});

});


  setTimeout(function(){
conn.close();
  console.log("sure bitti");
   reject("timeout");
  },40000);

});
}

module.exports = function (domain) {     
return sockettest(domain).then(function(result) {	
return result;
})
.catch((e) => {
return e;
});
};
```

when i test it from console
```
x=require("./test.js");
x("x.com").then(function(result){console.log(result);}).catch((e)=>{x.console.log(e);});
```

everything works well! but when i try to do same thing on nwjs.

it just stays at pending all the never can connect . why this bug happens when i call it from somewhere it supports also node-webkit.?
### Steps to reproduce (if the current behaviour is a bug)

just try to connect with these config from nwjs

require('socket.io-client')('https://test.com',{
  forceNode:true,
  transports: ['websocket'],
  extraHeaders: {
	  'Origin': 'https://www.test.com'
  }
});

### Expected behaviour

*What is expected?*

### Setup
- OS: win10
- browser: chromium
- socket.io version: latest

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

something happens to socket.io-client when it thinks it runs under windows and i force by forcenode option

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
