### ISSUE TITLE
Room not retained on restarts and reconnects

### ISSUE THREAD

**Issue by germansokolov13** [socketio/socket.io#3382]
### I want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

After server restart the client does successfully reconnect but does not rejoin the room

### Steps to reproduce
Here is the client code:
```js
var socket = io('http://localhost:3000');
setInterval(() => {
  socket.emit('message', 'I emit');
}, 5000);
socket.on('onMessage', (message) => {
  console.log(message);
});
socket.emit('enterRoom');
```

Here is the server code:
```js
var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);

io.on('connection', (socket) => {
  console.log('a user connected');

  socket.on('enterRoom', () => {
    socket.join('someRoom');
  });

  socket.on('message', (message) => {
    io.in('someRoom').emit('onMessage', 'This message was sant: ' + message);
  });
});

http.listen(3000, () => {
  console.log('listening on *:3000');
});
```

1) Run the server
2) Open the client code in an html-file in browser. At this point "This message was sant: I emit" appears in the console every 5 seconds.
3) Restart the server (Ctrl+C, run again).

### Expected behaviour

After restart I should still see these messages in the console. But I don't. This is because the client does not rejoin the room `someRoom`.

### Setup
- OS: Ubuntu 18.04 LTS
- Browser: Chrome Version 70.0.3538.77 (Official Build) (64-bit)
- socket.io version: 2.2.0

### Possible workaround

If I add this code to the client to rejoin the room on reconnect then it works fine:
```js
socket.on('reconnect', () => {
  socket.emit('enterRoom');
});
```
But I couldn't find any info that I should do this in docs. So I assumed I don't need to do anything on reconnects because Socket.io manages them. Without this workaround the system does work but is not robust. This issue was very tricky to solve. I think that either Socket.io should be able to maintain the room or at least there should be some kind of a guide on how to properly manage reconnects in real world programs.

**Comment by boolee** [comment]
I juess,it will take much resource if when restart the node to keep and handle those connected sessions.so,the best way to design is rejoin both side by your self to keep them relation.Any better explain?

**Comment by darrachequesne** [comment]
For future readers:

Please see the example here: https://socket.io/get-started/private-messaging-part-1/
