### ISSUE TITLE
For stress testing purposes against an AWS ALB, how can I enable cookies from a nodejs client?

### ISSUE THREAD

**Issue by sean256** [socketio/socket.io#3383]
I have a few instances in AWS running behind an Application load balancer. It works fine from a client like Chrome or Safari.

However I want to slam it using nodejs. The only problem is that it fails the handshake due to the sticky-session cookie not working.

Is there a way I can use socket.io-client in nodejs and have it maintain a cookie store?

**Comment by darrachequesne** [comment]
For future readers: the HTTP client we are using ([xmlhttprequest-ssl](https://github.com/mjwwit/node-XMLHttpRequest)) does not currently allow to store cookie.

There is a fork with a cookie jar: https://github.com/rse/node-xmlhttprequest-cookie

You should be able to do it manually though:

```js
const socket = require("socket.io-client")("https://my-domain.com");
const cookieModule = require("cookie");

const COOKIE_NAME = "AWSALB";

socket.io.on("open", () => {
  socket.io.engine.transport.on("pollComplete", () => {
    const request = socket.io.engine.transport.pollXhr.xhr;
    const cookieHeader = request.getResponseHeader("set-cookie");
    if (!cookieHeader) {
      return;
    }
    cookieHeader.forEach(cookieString => {
      if (cookieString.includes(`${COOKIE_NAME}=`)) {
        const cookie = cookieModule.parse(cookieString);
        socket.io.opts.extraHeaders = {
          cookie: `${COOKIE_NAME}=${cookie[COOKIE_NAME]}`
        }
      }
    });
  });
});
```

Another workaround is to disable HTTP long-polling, and only connect with WebSocket.

Please reopen if needed.

**Comment by Overdrive141** [comment]
I am in a similar boat. I have a socket io server hosted on multiple EC2 instances connected to an ALB (all using same redis container). I lose stickyness eventhough I have enabled stickyness in my Target Group.

Here are my configuration:

```
export const ioServer = new Server(server, {
  cors: {
    origin: [process.env.APP_SERVER, 'capacitor://localhost'],
    credentials: true,
    preflightContinue: true,
  },
});

  app.set('trust proxy', true);
  sessionMiddleware = session({
    store: sessionStore,
    secret: sessionSecret,
    resave: true,
    saveUninitialized: true,
    name: sessionCookieName,
    proxy: true,
    cookie: {
      secure: true,
      sameSite: 'none',
    }
  });

  ioServer.engine.use(sessionMiddleware);
  ioServer.engine.use(passport.initialize());
  ioServer.engine.use(passport.session());


logger.debug(`[users:join] userid: ${socket.request.user.userid}`);
```

And the client: 

```
    const socket = io(apiServer + namespace, { withCredentials: true, transports: ["websocket"]  });
    return socket;
```
This configuration works on my beta ec2 instance which is directly connected to ec2's public IP as well as locally but not when behind the ALB.

**Comment by darrachequesne** [comment]
@Overdrive141 that's weird, with `transports: ["websocket"]` you shouldn't even need it (since WebSocket does not require sticky sessions). Did you find a solution?
