### ISSUE TITLE
Socket.io & Nodejs Not WOrking Over https ?

### ISSUE THREAD

**Issue by Mahmoud-Italy** [socketio/socket.io#3386]
i have Code working fine with socket.io & node.js over http
but i need get over it over HTTPS

Last Error : net::ERR_CERT_AUTHORITY_INVALID
something wrong with certificates were i find , need find right one on server
i'm using Server CentOs 6 & Cpanel WHM

Server.js
======
<pre>
// Dependencies
const fs = require('fs');
const https = require('https');
const express = require('express');
const app = express();

// Certificate from server
// const privateKey = fs.readFileSync('/etc/ssl/private/ftpd-rsa-key.pem', 'utf8');
// const certificate = fs.readFileSync('/etc/ssl/private/ftpd-rsa.pem', 'utf8');
// const ca = fs.readFileSync('/etc/ssl/private/ftpd-ca.pem', 'utf8');

// Certificate were created from openssl command
const pkey = fs.readFileSync('ssl/key.pem', 'utf8');
const pcert = fs.readFileSync('ssl/cert.pem', 'utf8')
const pca = fs.readFileSync('ssl/csr.pem', 'utf8');

const credentials = {
	key: pkey,
	cert: pcert,
	ca: pca
};

app.use((req, res) => {
	res.send('Hello there !');
});

const httpsServer = https.createServer(credentials, app);

httpsServer.listen(3530, () => {
	console.log('HTTPS Server running on port 3530');
});
</pre>

Clients JS
=======
<pre>
var socket = io.connect("https://domainName.com:3530", { secure: true, reconnect: true, rejectUnauthorized : false });
</pre>

**Comment by hash3liZer** [comment]
Did you manage to solve this?

**Comment by ismardantas** [comment]
How to solve this?

**Comment by Mahmoud-Italy** [comment]
Yeah 
1. you've to generate your own SSL keys from Cpanel then put them into new folder like example public

2.then call them from ur code
const pkey = fs.readFileSync('public/key.pem', 'utf8');
const pcert = fs.readFileSync('public/cert.pem', 'utf8')
const pca = fs.readFileSync('public/csr.pem', 'utf8');
