### ISSUE TITLE
Request for variable event names

### ISSUE THREAD

**Issue by johnmorsey007** [socketio/socket.io#3389]
I was hoping to use variable event names similar to how server side routing works.  The syntax would look like this:

```
socket.on(variable_event, data => {
    io.emit(variable_event, data);
  });
```

Is this available yet ( I could not find it in the docs ), if so can someone provide a link to the appropriate documentation?

If it is not available can it be added as a feature ?  I would be happy to write it.

**Comment by JeremieTouze** [comment]
I agree, it would be very convenient. I don't know much yet about socket.io, does anyone know what is the appropriate strategy to achieve the same goal with the currently existing tools ?

**Comment by darrachequesne** [comment]
For future readers: this was implemented in Socket.IO v3

Syntax:

```js
socket.onAny((eventName, ...args) => {
  io.emit(eventName, ...args);
});
```

Please see the documentation here: https://socket.io/docs/v3/listening-to-events/#Catch-all-listeners
