### ISSUE TITLE
Strange behavior on server restart.

### ISSUE THREAD

**Issue by broburns** [socketio/socket.io#3392]
Anytime i restart the server, no events are fired on the server. I have both a local web page and a second node script that are supposed to connect, If i restart the server and then refresh the webpage or restart the second node script then nothing happens on the server, the connection event is fired from the clients however but not on the server, the only way to get them to connect is by visiting the socket address in the browser. Strangely after i visit the socket address in the browser, i am to refresh the web page and restart the second node script and everything connects, but all events are then subsequently fired twice when sent from the webpage. The only way i was able to fix the dupes is by setting the client-side socket options to:
`{
reconnectionAttempts:0
}`

I still have no idea as to what is causing the the server to not connect unless i visit the socket address in the browser. I've been chasing this problem for a while now, any help would be appreciated.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
