### ISSUE TITLE
memory leak with require("socket.io")(http)

### ISSUE THREAD

**Issue by CODY-RAY** [socketio/socket.io#3393]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

I had a memory leak that would lock up the server and not let any communication happen. with
```
var http = require('http').Server(app);
var io = require("socket.io")(http)
```
changed it to 
```
var io = require("socket.io").listen(http, {
  'log level': 3
});
```
and it works with no issue

### Steps to reproduce (if the current behaviour is a bug)
var http = require('http').Server(app);
var io = require("socket.io")(http)

### Expected behaviour
That 
```
var io = require("socket.io")(http)
```
not to freeze the process.
### Setup
- OS: macos
- browser: chrome
- socket.io version: 2.2.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
it was just undefined behavior that I didn't expect

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
