### ISSUE TITLE
WebSocket connection error 301

### ISSUE THREAD

**Issue by shrinivasmani** [socketio/socket.io#3394]
Hi 
I am getting the error mention bellow 

WebSocket connection to 'wss://api.etokenmarket.com/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 301

![websocket](https://user-images.githubusercontent.com/34855216/50555702-e03b1500-0cf5-11e9-8b96-c00f60009296.png)

Thanks for any help will be greatly appreciated

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
