### ISSUE TITLE
Error while accessing io object in router file, if does routing in another file.

### ISSUE THREAD

**Issue by rajatlnweb** [socketio/socket.io#3395]
I have two files, one is server.js and another is router.js. I am making connection with server on server.js and i imported router.js inside the server.js. But now i want to implement socket.io in my node js app. But i am getting error while accessing io object.

Please have a look at [this](https://stackoverflow.com/questions/53994185/how-to-use-socket-io-across-diffrent-routes-in-node-js) question.

**Comment by cptrodgers** [comment]
I used to answer your question.
In short: 

```nodejs
// socket.js
var http = require('http')
var socket_io = require('socket.io')

export function init_socket(app) {
    const server = http.Server(app)
    const io = socket_io(server, { path: 'your-path-want-for-socket-io' }) // default: /socket.io/
}
```

```nodejs
import {init_socket} from 'socket.js'
init_socket(app)
```

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by sbn111** [comment]
Am facing the same issue. is there any way to use socket.io more than one module in nodejs

**Comment by darrachequesne** [comment]
@sbn111 hi! Please check: https://socket.io/docs/v4/server-application-structure/
