### ISSUE TITLE
Socket IO is not connected wen using android Pie/android 9

### ISSUE THREAD

**Issue by mohamadfaris92** [socketio/socket.io#3397]
I have issue where android 9 is not connecting to my socket io. Please help

**Comment by moinkhan-in** [comment]
same issue ..
It's working below Pie ...

**Comment by h091237557** [comment]
u could open the socket.io server Debug model. and it will show some information. and upload on here. we can help u check what happen.

```
DEBUG=* node xxx.js
```

**Comment by arem94** [comment]
i set below code in my android manifest project and it work fine for me 

>android:usesCleartextTraffic="true"

**Comment by theromie** [comment]
@arem94 Not working in my case when setting 

> android:usesCleartextTraffic="true"

**Comment by berksafran** [comment]
> i set below code in my android manifest project and it work fine for me
> 
> > android:usesCleartextTraffic="true"

Exactly where did you put it?

**Comment by arem94** [comment]
you must add this code in application tag
like below
`<Application
      .
      .
       android:usesCleartextTraffic="true">
. 
.
.
<Application/>
`

**Comment by berksafran** [comment]
> you must add this code in application tag
> like below
> `<Application . . android:usesCleartextTraffic="true"> . . . <Application/> `

This problem is cause that Android emulator doesn't see "localhost" url. You need to put your local IP. (for macOS, you can learn yours by writing `ifconfig`). I solved it with way.

**Comment by r-bayat** [comment]
i used android:usesCleartextTraffic="true" but again not connecting on android 9.
everything is ok on my other device with android 8

**Comment by Jaquedeveloper** [comment]
Same here. If I build my App with SDK 27 it works flawlessly. If I build it using sdk 28 it does not connect. Now Play Store only accepts apps and apps updades with build sdk 28... Any fixes for this? Already tried clearfix... no success

**Comment by aonurozcan** [comment]
> > you must add this code in application tag
> > like below
> > `<Application . . android:usesCleartextTraffic="true"> . . . <Application/> `
> 
> This problem is cause that Android emulator doesn't see "localhost" url. You need to put your local IP. (for macOS, you can learn yours by writing `ifconfig`). I solved it with way.

It works! Thank you. I didn't even put android:usesCleartextTraffic="true" setting to manifest.xml.

**Comment by berksafran** [comment]
> > > you must add this code in application tag
> > > like below
> > > `<Application . . android:usesCleartextTraffic="true"> . . . <Application/> `
> > 
> > 
> > This problem is cause that Android emulator doesn't see "localhost" url. You need to put your local IP. (for macOS, you can learn yours by writing `ifconfig`). I solved it with way.
> 
> It works! Thank you. I didn't even put android:usesCleartextTraffic="true" setting to manifest.xml.

You're welcome.

**Comment by climbican** [comment]
Adding usesCleartextTraffic worked for me.  Thanks!!

**Comment by darrachequesne** [comment]
It seems the `usesCleartextTraffic` attribute now defaults to `false` starting from SDK 28 ([ref](https://developer.android.com/guide/topics/manifest/application-element)).

A few solutions are mentioned here: https://stackoverflow.com/a/50834600.

Let's close this, as I don't think we can do much here.
