### ISSUE TITLE
namespace.clients() returns sockets from other namespaces

### ISSUE THREAD

**Issue by AnyhowStep** [socketio/socket.io#3399]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

```js
server.on('connection', function (socket) {
    socket.join("roomA", function () {
        console.log("roomA joined");
        //roomB does not exist!
        socket.in("roomB").clients(function (err, clients) {
            //clients has socket.id in it! But it isn't in roomB!
            console.log(err, clients);
        })
    });
});
```

### Expected behaviour

`clients` in the callback should be an empty array since nothing has joined `roomB`.

### Setup
- OS: Ubuntu 16.04.2 LTS
- socket.io version: 1.7.4

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

I feel like I just don't understand how rooms/namespaces work. Maybe this is the intended behaviour.
I just want to know if `roomA` or `roomB` is empty, at any given point of time.

I've tried `Namespace.sockets` and `Namespace.connected` but they also behave the same as `Namespace.clients()` in that they return *ALL* socket ids and not the socket ids I added to the room.

-----

For now, in desperation, I'm using a separate counter to determine if a room is empty or not. User joins, increment, user leaves, decrement.

**Comment by ralphpig** [comment]
`Socket.prototype.clients` doesn't exist, only `Namespace.prototype.clients`. 
So `socket.in(..).clients(..)` isn't valid.

What you need is `NAMESPACE.in("roomB").clients(..)`.
Where `NAMESPACE` is:
- `server` (root namespace `'/'`)
- `server.of(..)`

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
