### ISSUE TITLE
A socket-io client can open many connections to server and cause unexpected results.

### ISSUE THREAD

**Issue by EltonZhong** [socketio/socket.io#3402]
### You want to:
* [x] report a *bug*

### Current behaviour
A socket-io client can open many connections to server.

*What is actually happening?*
There are many connected socket connections stored in server, pointing to only one socket-io client.

### Steps to reproduce (if the current behaviour is a bug)
Client:
```js
const io = require('socket.io-client');

const client = io('http://localhost:3333');

let i = 0;
let j = 0;
client.on('connect', () => {
    console.log(`${i++} connect! ' + ${client.id}`);
});

client.on('disconnect', () => {
    console.log(`${j} disconnect! '`);
    console.log(`Remains ${i - j} connections`);
    j ++;
});

setInterval(() => {
    console.log(client.id + '\tdisconnect')
    client.disconnect();
}, 1000)

setInterval(() => {
    client.connect();
}, 1000)

```

and server:
```js
const Koa = require('koa');
const pretty = require('pretty-format');
const app = new Koa();
const http = require('http').createServer(app.callback());
const io = require('socket.io')(http);

const port = 3333;

http.listen(port, function () {
    console.log(`listening on *:${port}`);
});
app.use(async (context) => {
    console.log('resp!')
})

const se = new Set();
let i = 0;
let j = 0;
io.on('connection', (socket) => {
    console.log('Sockets still alive:');
    console.log(Object.keys(io.sockets.sockets).length);
    se.add(socket);
    console.log(se.size);
    console.log(pretty(socket.id));
    console.log(socket.id + 'One socket connected:' + i++)

    socket.on('disconnect', () => {
        console.log(socket.id + 'One socket disconnect:' + j++)
        console.log(`There are ${i - j} sockets alive.`)
    });

    socket.use((pack, next) => {
        next();
        socket.emit('do', "d")
    });
    socket.on('hello2', (_, fn) => { fn('Response from server: world22222'); })
    socket.emit('do', "d")
});

```

It gives log below:
```
Sockets still alive:
9
306
"k91YdFHe1y7zGWoYAAEx"
k91YdFHe1y7zGWoYAAExOne socket connected:305
AZftkWSyFP2APCnqAAEwOne socket disconnect:297
There are 8 sockets alive.
k91YdFHe1y7zGWoYAAExOne socket disconnect:298
There are 7 sockets alive.
```

### Expected behaviour
There should be only one socket alive:
`Object.keys(io.sockets.sockets).length;` should be 1, but actually, when I use same socket-io client and disconnect, connect many times, many socket-io connections stay alive.

*What is expected?*
`Object.keys(io.sockets.sockets).length;` should be 1

### Setup
- OS: mac OS
- socket.io version: ^2.2.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
I don't know the much about the mechanism behind the socket-io. But I do think it's different from what I expect.

**Comment by requireSol** [comment]
If you reload page very fast in a row on safari Iphone same issue happens to me. Slowly but save the sockets dropping after a big delay. Maby i missing something still try to fix it.

**Comment by darrachequesne** [comment]
For future readers:

If the client is still in HTTP long-polling mode and the connection is severed, the server will not be able to detect the disconnection right away. The connection will be closed once the heartbeat fails, after `pingTimeout + pingInterval` seconds (which defaults to 45s in latest release).

This could also be a symptom of the `socket.disconnect().connect()` bug, which was fixed in `socket.io-client@4.4.0`: https://github.com/socketio/socket.io-client/commit/99c2cb8421361487ed7c876edd8670bb69a5c5b5

Please reopen if needed.
