### ISSUE TITLE
socket connection status

### ISSUE THREAD

**Issue by gevhambarzumyan93** [socketio/socket.io#3403]
how can I get socket connection status to avoid "socket is already disconnected" issue 
in react-js, I need to disconnect on componentWillUnmount(), but because it's already disconnected it's crushing a page,
Is there any method to get connection status

**Comment by ikalisz** [comment]
There are 2 options.
On your server side you can use
`socket.on('disconnect', () => {
    //Put a console.log or something here to alert you the socket has been disconnected.
}`
or I'm pretty sure you can use something like this also, on your front end set up a set interval that will emit and check the status
front end:
`setInterval(() => {
   socket.emit('check connect')
}`
on your back end:

`
socket.on('check connect', () => {
    socket.emit('check', socket.connected())
}
`

socket.connected returns true or false depending on if the socket is connected or not, you can use this in state or something other and change based on what it returns. Try those out.

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socket.io/docs/v3/client-socket-instance/#Socket-connected
