### ISSUE TITLE
Is there a way to attach a data in every emit?

### ISSUE THREAD

**Issue by lai32290** [socketio/socket.io#3404]
I would like to be able know which socket belongs to which user, because I'm creating rooms based user id, like:

```
socket.join(`user ${userId`});
```

But I don't want to have to send the user id in every event as parameter.

Is there a way to attach that information to be send in every emit?

**Comment by mehmoodak** [comment]
If you use `passport` for authentication then there is a package `passport.socketio` that can add the authenticated user with each request automatically and you can access that with `req.user`.

**Comment by darrachequesne** [comment]
For future readers: there is no way to attach data to each emit.

You can attach an attribute to the Socket instance, as long as you do not overwrite an existing one:

```js
socket.userId = "1234";
// later...
socket.broadcast.emit("hello", socket.userId);
```

Documentation: https://socket.io/docs/v3/server-socket-instance/#Additional-attributes
