### ISSUE TITLE
Include Client application domain cookie in request header of Socket connection

### ISSUE THREAD

**Issue by HegdeSach** [socketio/socket.io#3406]
In my application once the user is successfully authenticated, client side browser is set with proper cookie value (JWT Token).
How can I send that cookie as Request header during Socket Connection process so that server side code should be able to identify the sender of connection request.

Any configuration available in Socket IO so that browser picks the cookie available and include it in request header like below,
![image](https://user-images.githubusercontent.com/21358983/52657064-cc521800-2f1d-11e9-8328-085400f7204a.png)

**Comment by JayEdver** [comment]
I have the same problem with you.Could you tell me how did you solve it because I saw you have closed the issue ?

**Comment by JayEdver** [comment]
@HegdeSach I have the same problem with you.Could you tell me how did you solve it because I saw you have closed the issue ?
