### ISSUE TITLE
Random disconnections on server and client

### ISSUE THREAD

**Issue by dakairus** [socketio/socket.io#3407]
Hi Guys, I'm currently implementing a socket io server were I only want to make use of the "websocket" transport. Lately I updated my socket io version to the latest and found a problem trying to use this protocol.

**What happens?**
socket io on the client or server side randomly disconnects or doesn't even connect.

**Workaround**
Currently using the polling transport, but is not the desired behaviour

**Possible solution**
I read a issue in the socket io client (https://github.com/socketio/socket.io-client/issues/1268) where updating the engine io dependency to 3.3.2 solve the connection issue and actually it worked, but still got some random disconnections, even with good networking status. I grabbed a local copy of socket io for server side and also updated the dependency for engine io and the issue seems to go away.

Any chance of get the engine io dependency updated in next release?

**Comment by LynX39** [comment]
Hi, we have any update for this ticket? Thanks

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
