### ISSUE TITLE
How to send message like whatsapp, telgram, viber or imo just between two person?

### ISSUE THREAD

**Issue by muhammadwfa** [socketio/socket.io#3408]
Hi, I want to create a messenger app like whatsapp,
1. First I need to make a list of people connected to my messenger app.
2. I want to message to one of the person which existed on the list, so I click on its name on the list.
3. Now I want to chat with him.

Here I dont want message gets broadcast to all people.

So please show me the best secure way.

I've done some like below code.
I am just created a room only between two person
this works well.
but problem is when two person for the first time and the same time click each other to go messaging there two diffrent rooms gets create.
if they click each other from the list for the first time in different time then it works well.

(async () => {

    try {
    
        const r1 = await AsyncStorage.getItem(userphone + "u-uuuuuuuu-u" + mynumber);
        const r2 = await AsyncStorage.getItem(mynumber + "u-uuuuuuuu-u" + userphone);
    
        if (r1 !== null || r2 !== null) {
            if (r1 !== null) {
                this.socket.emit("joiningroom", { room: r1 });
                if (this._isMounted) {
                    this.setState({ room: r1 });
                }
            } else {
                this.socket.emit("joiningroom", { room: r2 });
                if (this._isMounted) {
                    this.setState({ room: r2 });
                }
            }
    
        } else {
    
            var ref1 = db.collection('chatrooms').doc(userphone + "u-uuuuuuuu-u" + mynumber);
            var ref2 = db.collection('chatrooms').doc(mynumber + "u-uuuuuuuu-u" + userphone);
    
            const doc1 = await ref1.get();
            const doc2 = await ref2.get();
    
            if (doc1.exists || doc2.exists) {
    
                if (doc1.exists) {
                    const room = doc1.data().mbaliotaq;
                    this.socket.emit("joiningroom", { room });
                    if (this._isMounted) {
                        this.setState({ room });
                    }
                    await AsyncStorage.setItem(userphone + "u-uuuuuuuu-u" + mynumber, room);
                } else {
                    const room = doc2.data().mbaliotaq;
                    this.socket.emit("joiningroom", { room });
                    if (this._isMounted) {
                        this.setState({ room });
                    }
                    await AsyncStorage.setItem(mynumber + "u-uuuuuuuu-u" + userphone, room);
                }
    
            } else {
    
                const id = userphone + "u-uuuuuuuu-u" + mynumber;
                const room = "mmm" + userphone + "r-rrrrrrrrr-r" + mynumber + "mmm";
    
                db.collection('chatrooms').doc(id).set({
                    mbaliotaq: room
                }).then(() => {
                    this.socket.emit("joiningroom", { room });
                    if (this._isMounted) {
                        this.setState({ room });
                    }
                }).catch(err => {
                    console.log(err);
                });
            }
        }
    
    } catch (e) {
        console.log(`Error in async ${e}`);
    }

})();

**I need a bettter way and a secure way than my solution.**

**Comment by Vitalii2103** [comment]
I am not an expert but I think they using p2p connection.
Or try something like this: [dat://](https://datproject.org/)

**Comment by johnmanko** [comment]
Consider asking on Slack (https://slackin-socketio.now.sh) or StackOverflow.  This is generally meant for issues with socketio that should be fixed by the developers. Your queation is more of usage, and you'll get a better response on those sites I listed above.

**Comment by muhammadwfa** [comment]
@Vitalii2103 thank you I'll check.
@johnmanko thank you, I asked before in stackoverflow, there were not one to answer.

**Comment by hafiz013** [comment]
hi i also want to do things same like yours. do you have full code?

**Comment by darrachequesne** [comment]
For future readers:

Please see the example here: https://socket.io/get-started/private-messaging-part-1/
