### ISSUE TITLE
Server im. on ('connection', async (socket) has been receiving client connections.

### ISSUE THREAD

**Issue by huangwz** [socketio/socket.io#3409]
Hello:

The socket. IO I use is the latest version of 2.2.0. Android is used by client and node JS is used by server.

The current situation is that after the client has established contact with the server, the client has two threads calling disconnect (). The phenomenon on the server side is that the client is always connected in.

1. The code for calling disconnect () at the same time by two threads on the Java side is as follows:

New Thread (new Runnable (){

@Override

Public void run (){

MSocket. disconnect ();

}

}.Start ();

// It's the same as the code above.

New Thread (new Runnable (){

@Override

Public void run (){

MSocket. disconnect ();

}

}.Start ();

MSocket defines a static change: private static Socket mSocket;

2. The code on the nodejs side is as follows:

(async () = > +

Im.on ('connection', async (socket) = >{

Log4js. debug ("--connection-");

}

} ()

From the point of view of the log, it prints "connection-" countless times, and has been printing.

What's the reason? Can't multithreading be used?

你好:
我使用的socket.io是最新的2.2.0版本。客户端使用的android,服务端使用是nodejs。
目前情况是这样的，客户端与服务端已经建立联系后，客户端有两个线程同时调用disconnect()。服务端的现象是客户端一直在连接进来。

1.java端两个线程同时调用disconnect()的代码如下：
 new Thread(new Runnable() {
        @Override
        public void run() {
            mSocket.disconnect();
        }
}).start();
//与上面那段代码是一样的
new Thread(new Runnable() {
    @Override
    public void run() {
        mSocket.disconnect();
    }
}).start();

其中mSocket定义的是一个static变更： private static Socket mSocket;

2.nodejs端的代码如下：
(async()=>{
	im.on('connection', async (socket) => {
		 log4js.debug("--connection-");
	 })
})()

从日志来看，打印了无数次 "--connection-"，而且是一直在打印。
请问下是原因导致的呢? 不能用多线程来操作么？

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
