### ISSUE TITLE
emit during connection lost, automatically re-emit?

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io#3414]
Hey there,
I am developing a chat app in nodeJS and ReactJS.

Server:

```js
socket.on("new message", data => {
  console.log(data);
})
```
Client:

```js
const message = {content: "hello"}
socket.emit("new message", message);
```
However when the client has a connection problem and then gets back online, it sometimes resends the previous emit and sometimes it doesn't. Can anyone tell me why this is happening randomly?

**Or generally asked: When a client drops his connection for a quick time, what happens with the emitted messages during that time? Does it get re-emitted, and if yes, how?**

**Comment by andredoering** [comment]
can anyone help me here? :)

**Comment by boolee** [comment]
I have same doubt with you,any suggestion to make sure no message will not miss?

**Comment by andredoering** [comment]
In fact no. No one could help me with it yet. I observed that the messages get send really randomly when you emitted them during a connection lost. sometimes a few get re-send sometimes none, sometimes all. I will most likely not use socket.io anymore because of that issue. I am developing a chat app and it is unacceptable to have this random behavior. What you can do (I don't know your use case) you can give the message a unique id and check if this id already exists and then deny it, to avoid duplicates.

**Comment by knightchim** [comment]
> In fact no. No one could help me with it yet. I observed that the messages get send really randomly when you emitted them during a connection lost. sometimes a few get re-send sometimes none, sometimes all. I will most likely not use socket.io anymore because of that issue. I am developing a chat app and it is unacceptable to have this random behavior. What you can do (I don't know your use case) you can give the message a unique id and check if this id already exists and then deny it, to avoid duplicates.

Finally,agree with you,in my oppon,ws will not help you consider how to send a message for sure,every thing we need do it in ourself way,like recode all messages in redis(thats my salution),then set a setinterval act from backend emit to client like every 10 secoends,then comfrim one emit bact to delete cache.

but,I just facing a slow reconnect,it cant be accpted by me,I am confused how to reconnect faster,it takes more than 15s.

**Comment by dinceremre** [comment]
sometimes this leads to a message bomb in my app.

**Comment by darrachequesne** [comment]
For future readers:

By default, the messages are buffered until reconnection.

There are two possible solutions:

- check if the socket is connected before sending the packet:

```js
if (socket.connected) {
  socket.emit("new message", "123");
} else {
  // handle the case
}
```

- or, use the `volatile` flag (available in version `> 3.0.0`). In that case, the packet is discarded if the socket is not connected:

```js
socket.volatile.emit("new message", "123");
```

Documention here: https://socket.io/docs/v3/emitting-events/#Volatile-events

Regarding the randomness, that sounds weird, I will see if I can reproduce.

**Comment by dinceremre** [comment]
> For future readers:
> 
> By default, the messages are buffered until reconnection.
> 
> There are two possible solutions:
> 
> * check if the socket is connected before sending the packet:
> 
> ```js
> if (socket.connected) {
>   socket.emit("new message", "123");
> } else {
>   // handle the case
> }
> ```
> 
> * or, use the `volatile` flag (available in version `> 3.0.0`). In that case, the packet is discarded if the socket is not connected:
> 
> ```js
> socket.volatile.emit("new message", "123");
> ```
> 
> Documention here: https://socket.io/docs/v3/emitting-events/#Volatile-events
> 
> Regarding the randomness, that sounds weird, I will see if I can reproduce.
thanks for the swift response.
can you please explain how does the server behave when it comes to **socket.broadcast.to(roomId)**? 
can we attach volatility to broadcast emits?

**Comment by darrachequesne** [comment]
For future readers:

> can you please explain how does the server behave when it comes to socket.broadcast.to(roomId)?

The packets are not buffered on the server side, if the client is not currently connected it will not receive the packet.

I've added a note here to make it clearer: https://socket.io/docs/v4/broadcasting-events/#to-all-connected-clients

> can we attach volatility to broadcast emits?

Yes!

```js
io.volatile.emit(/* ... */);
```

Please reopen if needed.

**Comment by ericwangqing** [comment]
For a chat app, only buffering on client side is not enough, since a receiver will miss all packets sent in its disconnect/reconnect process.  The app should cache/persist all messages in that period and resend them to the reconnected receiver.

**Comment by khacnha** [comment]
this doc: https://socket.io/docs/v4/connection-state-recovery may help for this case to further upgrade.
