### ISSUE TITLE
How to dissconnect another client through a different client?

### ISSUE THREAD

**Issue by Helixable** [socketio/socket.io#3418]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [ ] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

*What is expected?*

### Setup
- OS:
- browser:
- socket.io version:

**Comment by Helixable** [comment]
I'm making a simple multiplayer tag game: https://repl.it/@Helixable/Multiplayer-Tag-v10
I want to make admins be able to kick other players. How do I do this?

**Comment by boolee** [comment]
records every palyers socket.id in local db,like redis in one room,then just emit to those players offline socket.to(player1.socket.id).to(player2.socket.id).emit('offline')

**Comment by darrachequesne** [comment]
For future readers: this was implemented in https://github.com/socketio/socket.io/commit/b25495c069031674da08e19aed68922c7c7a0e28 and included in `socket.io@4.0.0`

Syntax:

```js
// make all Socket instances disconnect
io.disconnectSockets();

// make all Socket instances of the "admin" namespace in the "room1" room disconnect
io.of("/admin").in("room1").disconnectSockets();
```

Documentation: https://socket.io/docs/v3/migrating-from-3-x-to-4-0/#Additional-utility-methods
