### ISSUE TITLE
Amazing Script! Congrats!!!

### ISSUE THREAD

**Issue by inglesuniversal** [socketio/socket.io#3419]
Can anybody point me in the right direction?

I am trying to find a sample code using Socket.io where I can control an html5 audio or video player hosted online, from my mobile device (iPhone / iPad / Android phone or tablet) within the same wifi network ONLY.

Any help or link is greatly appreciated!

**Comment by killia15** [comment]
I don't have any script in particular but perhaps a [WebRTC Data Channel](https://www.html5rocks.com/en/tutorials/webrtc/datachannels/) may be a better solution. You could use something like PeerJS to avoid the trouble with initiating the connection and use your public IP. Then on the site, you can use event listeners and control the player.

**Comment by inglesuniversal** [comment]
Nice! Thanks for the tip, and if it works, I'll let you know the outcome.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
