### ISSUE TITLE
error connecting client to server

### ISSUE THREAD

**Issue by Kiranprajapati2719** [socketio/socket.io#3420]
* [x] report a *bug* 

### Current behaviour

polling-xhr.js:269 GET http://localhost:8080/socket.io/?EIO=3&transport=polling&t=McRhcgV net::ERR_CONNECTION_REFUSED
c.create @ polling-xhr.js:269
c @ polling-xhr.js:163
l.request @ polling-xhr.js:89
l.doPoll @ polling-xhr.js:123
c.poll @ polling.js:123
c.doOpen @ polling.js:69
i.open @ transport.js:78
c.open @ socket.js:238
c @ socket.js:116
c @ socket.js:32
d.open.d.connect @ manager.js:231
(anonymous) @ manager.js:533
setTimeout (async)
d.reconnect @ manager.js:526
(anonymous) @ manager.js:537
(anonymous) @ manager.js:251
r.emit @ index.js:130
c.onError @ socket.js:660
(anonymous) @ socket.js:265
r.emit @ index.js:130
i.onError @ transport.js:65
(anonymous) @ polling-xhr.js:129
r.emit @ index.js:130
c.onError @ polling-xhr.js:315
(anonymous) @ polling-xhr.js:262
setTimeout (async)
hasXDR.t.onreadystatechange @ polling-xhr.js:261
XMLHttpRequest.send (async)
c.create @ polling-xhr.js:269
c @ polling-xhr.js:163
l.request @ polling-xhr.js:89
l.doPoll @ polling-xhr.js:123
c.poll @ polling.js:123
c.doOpen @ polling.js:69
i.open @ transport.js:78
c.open @ socket.js:238
c @ socket.js:116
c @ socket.js:32
d.open.d.connect @ manager.js:231
(anonymous) @ manager.js:533
setTimeout (async)
d.reconnect @ manager.js:526
(anonymous) @ manager.js:537
(anonymous) @ manager.js:251
r.emit @ index.js:130
c.onError @ socket.js:660
(anonymous) @ socket.js:265
r.emit @ index.js:130
i.onError @ transport.js:65
(anonymous) @ polling-xhr.js:129
r.emit @ index.js:130
c.onError @ polling-xhr.js:315
(anonymous) @ polling-xhr.js:262
setTimeout (async)
hasXDR.t.onreadystatechange @ polling-xhr.js:261
XMLHttpRequest.send (async)
c.create @ polling-xhr.js:269
c @ polling-xhr.js:163
l.request @ polling-xhr.js:89
l.doPoll @ polling-xhr.js:123
c.poll @ polling.js:123
c.doOpen @ polling.js:69
i.open @ transport.js:78
c.open @ socket.js:238
c @ socket.js:116
c @ socket.js:32
d.open.d.connect @ manager.js:231
(anonymous) @ manager.js:533
setTimeout (async)
d.reconnect @ manager.js:526
d.maybeReconnectOnOpen @ manager.js:215
(anonymous) @ manager.js:254
r.emit @ index.js:130
c.onError @ socket.js:660
(anonymous) @ socket.js:265
r.emit @ index.js:130
i.onError @ transport.js:65
(anonymous) @ polling-xhr.js:129
r.emit @ index.js:130
c.onError @ polling-xhr.js:315
(anonymous) @ polling-xhr.js:262
setTimeout (async)
hasXDR.t.onreadystatechange @ polling-xhr.js:261
XMLHttpRequest.send (async)
c.create @ polling-xhr.js:269
c @ polling-xhr.js:163
l.request @ polling-xhr.js:89
l.doPoll @ polling-xhr.js:123
c.poll @ polling.js:123
c.doOpen @ polling.js:69
i.open @ transport.js:78
c.open @ socket.js:238
c @ socket.js:116
c @ socket.js:32
d.open.d.connect @ manager.js:231
d @ manager.js:76
d @ manager.js:41
u @ index.js:56
72 @ PeerConnection.js:7
f @ (index):1
35 @ btn.svg:1
f @ (index):1
a @ (index):1
e @ (index):1
(anonymous) @ main.f198de26.chunk.js:1
 
### Expected behaviour

Connect to server

### Setup
- OS: windows 8.1
- browser: chrome 72
- socket.io version: 2.2

**Comment by ShooterArk** [comment]
I am also facing the same issue :/ .. it was working perfectly fine and after few months now suddenly I am getting this error when client called me and told me that the client is not connecting to the server :/ ..

I am using socket.io 2.1.1. A possible solution might be to update it to 3.0, Any advise ?
Thanks

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socket.io/docs/v3/troubleshooting-connection-issues/

**Comment by iBVerma** [comment]
GET http://localhost:3001/socket/?EIO=3&transport=polling&t=OccOHRS net::ERR_CONNECTION_REFUSED
Request.create @ polling-xhr.js:268
Request @ polling-xhr.js:170
XHR.request @ polling-xhr.js:96
XHR.doPoll @ polling-xhr.js:126
Polling.poll @ polling.js:118
Polling.doOpen @ polling.js:63
Transport.open @ transport.js:84
Socket.open @ socket.js:250
Socket @ socket.js:122
Socket @ socket.js:28
Manager.open.Manager.connect @ manager.js:226
(anonymous) @ manager.js:544
setTimeout (async)
Manager.reconnect @ manager.js:534
(anonymous) @ manager.js:548
(anonymous) @ manager.js:247
Emitter.emit @ index.js:145
Socket.onError @ socket.js:690
(anonymous) @ socket.js:281
Emitter.emit @ index.js:145
Transport.onError @ transport.js:71
(anonymous) @ polling-xhr.js:132
Emitter.emit @ index.js:145
Request.onError @ polling-xhr.js:314
(anonymous) @ polling-xhr.js:261
setTimeout (async)
xhr.onreadystatechange @ polling-xhr.js:260
XMLHttpRequest.send (async)
Request.create @ polling-xhr.js:268
Request @ polling-xhr.js:170
XHR.request @ polling-xhr.js:96
XHR.doPoll @ polling-xhr.js:126
Polling.poll @ polling.js:118
Polling.doOpen @ polling.js:63
Transport.open @ transport.js:84
Socket.open @ socket.js:250
Socket @ socket.js:122
Socket @ socket.js:28
Manager.open.Manager.connect @ manager.js:226
(anonymous) @ manager.js:544
setTimeout (async)
Manager.reconnect @ manager.js:534
(anonymous) @ manager.js:548
(anonymous) @ manager.js:247
Emitter.emit @ index.js:145
Socket.onError @ socket.js:690
(anonymous) @ socket.js:281
Emitter.emit @ index.js:145
Transport.onError @ transport.js:71
(anonymous) @ polling-xhr.js:132
Emitter.emit @ index.js:145
Request.onError @ polling-xhr.js:314
(anonymous) @ polling-xhr.js:261
setTimeout (async)
xhr.onreadystatechange @ polling-xhr.js:260
XMLHttpRequest.send (async)
Request.create @ polling-xhr.js:268
Request @ polling-xhr.js:170
XHR.request @ polling-xhr.js:96
XHR.doPoll @ polling-xhr.js:126
Polling.poll @ polling.js:118
Polling.doOpen @ polling.js:63
Transport.open @ transport.js:84
Socket.open @ socket.js:250
Socket @ socket.js:122
Socket @ socket.js:28
Manager.open.Manager.connect @ manager.js:226
(anonymous) @ manager.js:544
setTimeout (async)
Manager.reconnect @ manager.js:534
(anonymous) @ manager.js:548
(anonymous) @ manager.js:247
Emitter.emit @ index.js:145
Socket.onError @ socket.js:690
(anonymous) @ socket.js:281
Emitter.emit @ index.js:145
Transport.onError @ transport.js:71
(anonymous) @ polling-xhr.js:132
Emitter.emit @ index.js:145
Request.onError @ polling-xhr.js:314
(anonymous) @ polling-xhr.js:261
setTimeout (async)
xhr.onreadystatechange @ polling-xhr.js:260
XMLHttpRequest.send (async)
Request.create @ polling-xhr.js:268
Request @ polling-xhr.js:170
XHR.request @ polling-xhr.js:96
XHR.doPoll @ polling-xhr.js:126
Polling.poll @ polling.js:118
Polling.doOpen @ polling.js:63
Transport.open @ transport.js:84
Socket.open @ socket.js:250
Socket @ socket.js:122
Socket @ socket.js:28
Manager.open.Manager.connect @ manager.js:226
(anonymous) @ manager.js:544
setTimeout (async)
Manager.reconnect @ manager.js:534
(anonymous) @ manager.js:548
(anonymous) @ manager.js:247
Emitter.emit @ index.js:145
Socket.onError @ socket.js:690
(anonymous) @ socket.js:281
Emitter.emit @ index.js:145
Transport.onError @ transport.js:71
(anonymous) @ polling-xhr.js:132
Emitter.emit @ index.js:145
Request.onError @ polling-xhr.js:314
(anonymous) @ polling-xhr.js:261
setTimeout (async)
xhr.onreadystatechange @ polling-xhr.js:260
XMLHttpRequest.send (async)
Request.create @ polling-xhr.js:268
Request @ polling-xhr.js:170
XHR.request @ polling-xhr.js:96
XHR.doPoll @ polling-xhr.js:126
Polling.poll @ polling.js:118
Polling.doOpen @ polling.js:63
Transport.open @ transport.js:84
Socket.open @ socket.js:250
Socket @ socket.js:122
Socket @ socket.js:28
Manager.open.Manager.connect @ manager.js:226
(anonymous) @ manager.js:544
setTimeout (async)
Manager.reconnect @ manager.js:534
(anonymous) @ manager.js:548
(anonymous) @ manager.js:247
Emitter.emit @ index.js:145
Socket.onError @ socket.js:690
(anonymous) @ socket.js:281
Emitter.emit @ index.js:145
Transport.onError @ transport.js:71
(anonymous) @ polling-xhr.js:132
Emitter.emit @ index.js:145
Request.onError @ polling-xhr.js:314
(anonymous) @ polling-xhr.js:261
setTimeout (async)
xhr.onreadystatechange @ polling-xhr.js:260
XMLHttpRequest.send (async)
Request.create @ polling-xhr.js:268
Request @ polling-xhr.js:170
XHR.request @ polling-xhr.js:96
XHR.doPoll @ polling-xhr.js:126
Polling.poll @ polling.js:118
Polling.doOpen @ polling.js:63
Transport.open @ transport.js:84
Socket.open @ socket.js:250
Socket @ socket.js:122
Socket @ socket.js:28
Manager.open.Manager.connect @ manager.js:226
(anonymous) @ manager.js:544
setTimeout (async)
Manager.reconnect @ manager.js:534
(anonymous) @ manager.js:548
(anonymous) @ manager.js:247
Emitter.emit @ index.js:145
Socket.onError @ socket.js:690
(anonymous) @ socket.js:281
Emitter.emit @ index.js:145
Transport.onError @ transport.js:71
(anonymous) @ polling-xhr.js:132
Emitter.emit @ index.js:145
Request.onError @ polling-xhr.js:314
(anonymous) @ polling-xhr.js:261
setTimeout (async)
xhr.onreadystatechange @ polling-xhr.js:260
XMLHttpRequest.send (async)
Request.create @ polling-xhr.js:268
Request @ polling-xhr.js:170
XHR.request @ polling-xhr.js:96
XHR.doPoll @ polling-xhr.js:126
Polling.poll @ polling.js:118
Polling.doOpen @ polling.js:63
Transport.open @ transport.js:84
Socket.open @ socket.js:250
Socket @ socket.js:122
Socket @ socket.js:28
Manager.open.Manager.connect @ manager.js:226
(anonymous) @ manager.js:544
setTimeout (async)
Manager.reconnect @ manager.js:534
(anonymous) @ manager.js:548
(anonymous) @ manager.js:247
Emitter.emit @ index.js:145
Socket.onError @ socket.js:690
(anonymous) @ socket.js:281
Emitter.emit @ index.js:145
Transport.onError @ transport.js:71
(anonymous) @ polling-xhr.js:132
Emitter.emit @ index.js:145
Request.onError @ polling-xhr.js:314
(anonymous) @ polling-xhr.js:261
setTimeout (async)
xhr.onreadystatechange @ polling-xhr.js:260
XMLHttpRequest.send (async)
Request.create @ polling-xhr.js:268
Request @ polling-xhr.js:170
XHR.request @ polling-xhr.js:96
XHR.doPoll @ polling-xhr.js:126
Polling.poll @ polling.js:118
Polling.doOpen @ polling.js:63
Transport.open @ transport.js:84
Socket.open @ socket.js:250
Socket @ socket.js:122
Socket @ socket.js:28
Manager.open.Manager.connect @ manager.js:226
(anonymous) @ manager.js:544
setTimeout (async)
Manager.reconnect @ manager.js:534
(anonymous) @ manager.js:548
(anonymous) @ manager.js:247
Emitter.emit @ index.js:145
Socket.onError @ socket.js:690
(anonymous) @ socket.js:281
Emitter.emit @ index.js:145
Transport.onError @ transport.js:71
(anonymous) @ polling-xhr.js:132
Emitter.emit @ index.js:145
Request.onError @ polling-xhr.js:314
(anonymous) @ polling-xhr.js:261
setTimeout (async)
xhr.onreadystatechange @ polling-xhr.js:260
XMLHttpRequest.send (async)
Request.create @ polling-xhr.js:268
Request @ polling-xhr.js:170
XHR.request @ polling-xhr.js:96
XHR.doPoll @ polling-xhr.js:126
Polling.poll @ polling.js:118
Polling.doOpen @ polling.js:63
Transport.open @ transport.js:84
Socket.open @ socket.js:250
Socket @ socket.js:122
Socket @ socket.js:28
Manager.open.Manager.connect @ manager.js:226
(anonymous) @ manager.js:544
setTimeout (async)
Manager.reconnect @ manager.js:534
(anonymous) @ manager.js:548
(anonymous) @ manager.js:247
Emitter.emit @ index.js:145
Socket.onError @ socket.js:690
(anonymous) @ socket.js:281
Emitter.emit @ index.js:145
Transport.onError @ transport.js:71
(anonymous) @ polling-xhr.js:132
Emitter.emit @ index.js:145
Request.onError @ polling-xhr.js:314
(anonymous) @ polling-xhr.js:261
setTimeout (async)
xhr.onreadystatechange @ polling-xhr.js:260
XMLHttpRequest.send (async)
Request.create @ polling-xhr.js:268
Request @ polling-xhr.js:170
XHR.request @ polling-xhr.js:96
XHR.doPoll @ polling-xhr.js:126
Polling.poll @ polling.js:118
Polling.doOpen @ polling.js:63
Transport.open @ transport.js:84
Socket.open @ socket.js:250
Socket @ socket.js:122
Socket @ socket.js:28
Manager.open.Manager.connect @ manager.js:226
(anonymous) @ manager.js:544
setTimeout (async)
Manager.reconnect @ manager.js:534
(anonymous) @ manager.js:548
(anonymous) @ manager.js:247
Emitter.emit @ index.js:145
Socket.onError @ socket.js:690
(anonymous) @ socket.js:281
Emitter.emit @ index.js:145
Transport.onError @ transport.js:71
(anonymous) @ polling-xhr.js:132
Emitter.emit @ index.js:145
Request.onError @ polling-xhr.js:314
(anonymous) @ polling-xhr.js:261
setTimeout (async)
xhr.onreadystatechange @ polling-xhr.js:260
XMLHttpRequest.send (async)
Request.create @ polling-xhr.js:268
Request @ polling-xhr.js:170
XHR.request @ polling-xhr.js:96
XHR.doPoll @ polling-xhr.js:126
Polling.poll @ polling.js:118
Polling.doOpen @ polling.js:63
Transport.open @ transport.js:84
Socket.open @ socket.js:250
Socket @ socket.js:122
Socket @ socket.js:28
Manager.open.Manager.connect @ manager.js:226
(anonymous) @ manager.js:544
setTimeout (async)
Manager.reconnect @ manager.js:534
(anonymous) @ manager.js:548
(anonymous) @ manager.js:247
Emitter.emit @ index.js:145
Socket.onError @ socket.js:690
(anonymous) @ socket.js:281
Emitter.emit @ index.js:145
Transport.onError @ transport.js:71
(anonymous) @ polling-xhr.js:132
Emitter.emit @ index.js:145
Request.onError @ polling-xhr.js:314
(anonymous) @ polling-xhr.js:261
setTimeout (async)
xhr.onreadystatechange @ polling-xhr.js:260


error caught, anyway to fix this?

**Comment by iBVerma** [comment]
const express = require('express');
const app = express();
const server = require('http').createServer(app);
const ioUtils = require('./utils/io');

const io = require("socket.io")(server,{ cors:{ 
	origin:"http://localhost:8080",
	methods: ["GET","POST"], 
	credentials: true, 
	allowEIO3: true }, 
	transport: ["websocket"],
	rejectUnauthorized: false
});

const PORT = process.env.PORT || 3005;

// app.get('/', (req, res, next) => {
// 	console.log("Running");
// 	res.send("Hello");
// 	// res.send({ message: 'Hello World' });
// });

ioUtils.setupIO(io);

server.listen(PORT, () => console.log(`Server started on port: ${PORT}`));



this is my server side code


ioUtils file:

const Rooms = require('./Rooms');
const {
	generateServerMessage,
	generateUserMessage,
} = require('../utils/message');

exports.setupIO = (io) => {
	console.log("HEEERE");
	io.on('connection', (socket) => {
		console.log("next");
		console.log(socket.id);
		console.log(`User connected: ${socket.id}`);

		socket.on('join', (data) => {
			console.log('joining user', data);
			const { roomId, name, userId, videoId } = data;
			console.log(`User ${name} just joined in room ${roomId}`);

			socket.join(roomId);
			Rooms.addRoom(roomId, videoId);
			Rooms.addUser(roomId, name, userId); // data.userId = socket.id
			// Rooms.showInfo();

			// emit to all except the joined user
			socket.broadcast.to(roomId).emit(
				'newMessage',
				generateServerMessage('userJoin', {
					roomId,
					name,
					userId,
				})
			);

			// tell everyone in the room to update their userlist
			io.to(roomId).emit('updateUserList', Rooms.getUserList(roomId));

			// if the user joined existing room, tell him about the playing video
			if (!videoId) {
				const room = Rooms.getRoom(roomId);
				socket.emit(
					'newMessage',
					generateServerMessage('changeVideo', {
						videoId: room.videoId,
					})
				);
			}
		});

		socket.on('createMessage', (message) => {
			const user = Rooms.getUser(socket.id);

			if (user) {
				io.to(user.roomId).emit(
					'newMessage',
					generateUserMessage(user.name, user.id, message)
				);
				console.log('new message received', message);
			}
		});

		socket.on('videoStateChange', (data) => {
			const user = Rooms.getUser(socket.id);
			console.log('videoStateChange trigerred', data);
			// tell others to update the videoState
			socket.broadcast.to(user.roomId).emit(
				'newMessage',
				generateServerMessage('updateVideoState', {
					type: data.type,
					...data.payload,
					user: {
						name: user.name,
						id: socket.id,
					},
				})
			);
		});

		socket.on('changeVideo', (data) => {
			const { videoId } = data;
			const user = Rooms.getUser(socket.id);
			io.to(user.roomId).emit(
				'newMessage',
				generateServerMessage('updateVideoId', { videoId, user })
			);
			Rooms.setVideoId(user.roomId, videoId);
		});

		socket.on('disconnect', () => {
			console.log('User disconnected');
			const user = Rooms.removeUser(socket.id);
			// Rooms.showInfo();
			console.log(`${user.name} has left`);

			io.to(user.roomId).emit(
				'newMessage',
				generateServerMessage('userLeft', {
					name: user.name,
					userId: user.id,
					roomId: user.roomId,
				})
			);

			// tell everyone in the room to update their userlist
			io.to(user.roomId).emit(
				'updateUserList',
				Rooms.getUserList(user.roomId)
			);
		});
	});
};


frontend code:
import io from "socket.io-client";

export const createConnection = (name, roomId = null, videoId = null) => {
	// create the socket connection with socket server
	console.log(name);
	console.log(videoId);
	console.log("Socket");
	return new Promise((resolve) => {
		const socket = io("http://localhost:3001", { path: '/socket' });
		socket.on('connect', () => {
			socket.emit('join', {
				roomId: roomId || socket.id,
				name,
				userId: socket.id,
				videoId,
			});
			resolve(socket);
		});
	});
};
