### ISSUE TITLE
Found some doubt on ping timeout

### ISSUE THREAD

**Issue by boolee** [socketio/socket.io#3421]
I test suddenly disconnect my local network,then recove immediately. before reconnet, first connection not really disconnect yet.just found the socket ping timeout. at thus time, client still can recvice emit from server,nut cant emit back to server again. Anybody has met same situation?

Any idears about how to avoid it?

**Comment by irfancnk** [comment]
I have the same problem in my application. I have a ReactJS  web application using socket.io to communicate with my NodeJS server, after a random time (I could not reproduce the error everytime) socket.io calls the disconnect callback with 'ping timeout' as a reason. However, I can still send commands to my server from React app even the socket.io did not call the 'connect' event again. Right now I have just increased the ping timeout value to 10000000 and did not encounter with the same error. But still waiting for the solution.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
