### ISSUE TITLE
Socket io not receive to client

### ISSUE THREAD

**Issue by ducga1998** [socketio/socket.io#3426]
Hello everybody, I am have problem when send socket to client => server, it can socket and receive other user but not receive to seft

**Comment by abbasalim** [comment]
i have this problem also;

**Comment by ducga1998** [comment]
@achesser  i am read document, it's said the same thing but i am  try but not success : ((, it only receive to other user

**Comment by h091237557** [comment]
Would u mind show your code for there ?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
