### ISSUE TITLE
Old listeners listen when disconnected

### ISSUE THREAD

**Issue by TGamingStudio** [socketio/socket.io#3433]
### I want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

After client disconnects and connects again the old listener still works with new socket id

### Setup
- NPM
- Browser: Mozila in Winows
- socket.io version: 2.2.0
- Express + express- session

```
app.get("/test", (req, res) => {
 res.render("test")
 io.on("connection", function(socket){
   console.log("new connection: " + socket.id)
   console.log(io.sockets.sockets)
 })
})
```
![picture](https://user-images.githubusercontent.com/45291673/56591640-60f58800-65e9-11e9-855c-a247cd8827d4.png)

As you can see first connection is there once, 
second connection appears twice but in io.sockets is only once the new one
with every connection new connection dupes (old listener stays with new id)

**Comment by Un-knownCoder** [comment]
I have a similar problem: Whenever I request something from the server (not at the first time), it sends me more responses than expected.....

See: https://github.com/socketio/socket.io/issues/3435#issue-437989735
