### ISSUE TITLE
Client connect event not triggered after manual close and open

### ISSUE THREAD

**Issue by bdeweygit** [socketio/socket.io#3436]
### I want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

The client side `connect` event is not fired after the client manually closes and then immediately manually reopens the connection.

### Steps to reproduce (if the current behaviour is a bug)

Forked [fiddle](https://github.com/Benjamin-Dewey/socket.io-fiddle). Start the server, run the Node.js client, and see for yourself.
```
const socket = require('socket.io-client')('http://localhost:3000', {
  autoConnect: false,
  reconnection: false,
});

const openThenCloseOnConnect = (recursions) => {
  console.log('---START FUNCTION CALL---');
  socket.once('connect', () => {
    console.log('- connected socket', recursions);
    console.log('- closing socket', recursions);
    socket.close();
    console.log('---END FUNCTION CALL---');
    if (recursions > 0) openThenCloseOnConnect(recursions - 1)
  });
  console.log('- opening socket', recursions);
  socket.open();
};


openThenCloseOnConnect(1);
```

### Expected behaviour

I expect the output to be...
```
---START FUNCTION CALL---
- opening socket 1
- connected socket 1
- closing socket 1
---END FUNCTION CALL---
---START FUNCTION CALL---
- opening socket 0
- connected socket 0
- closing socket 0
---END FUNCTION CALL---
```
and sometimes it is, but usually it only gets as far as...
```
---START FUNCTION CALL---
- opening socket 1
- connected socket 1
- closing socket 1
---END FUNCTION CALL---
---START FUNCTION CALL---
- opening socket 0
```
and then it hangs because the `connect` event needed to continue is never triggered

### Setup
- OS: MacOS 10.14.4
- browser: I'm not using the browser, I'm using the Node.js client
- socket.io version: latest

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
The bug only ever occurs if the closing and reopening of the connection is done without delay. If instead the connection is reopened after a 500ms timeout, everything works as it should.

**Comment by darrachequesne** [comment]
For future readers:

This was fixed by https://github.com/socketio/socket.io-client/commit/99c2cb8421361487ed7c876edd8670bb69a5c5b5, included in `socket.io-client@4.4.0`.
