### ISSUE TITLE
set cookie through middleware

### ISSUE THREAD

**Issue by fithwith** [socketio/socket.io#3437]
Thank you guys for supporting socketio, there is no doubt that this is an awesome module that is making the life of many persons better but unfortunately there is an issue that many people suffered from for years.
basically we want to set a cookie from socketio.
the background of this is:
there few modules available to share session cookies from express and socketio, basically all of them are able to update the session once its updated from express, which not a huge accomplishment since its simply writing the cookie in the brower then socketio get that cookie in the header, but where every module fails to do is to update the cookie once its changed from a socketio event.

many people come up with the conclusion that socketio is not handling this properly and went back to a crappy solution kind of sending the client and event to add the cookie from client side using javascript, some others choose to refresh the page in order to let express update the cookie. 

here an example of code:

`
var clientSessions = require('client-sessions');
var sesmid=clientSessions({
  cookieName: 'session',
  secret: '123', 
  duration: 24 * 60 * 60 * 1000,
  activeDuration: 1000 * 60 * 5,
  cookie: {
    httpOnly: false
  }
});
app.use(sesmid);
iolib.use(function(socket, next) {
    sesmid(socket.request, socket.request.res, next);
});`

most of the online dicussion about the subject come up to the same conclusion that this line "sesmid(socket.request, socket.request.res, next);" especially socket.request.res is doing nothing.

I was debugging about the issue for the whole day and I found that the socketio is not even writing the cookie in  the response header.

 here some link of modules and discussion :
https://github.com/expressjs/session/issues/208
https://github.com/mozilla/node-client-sessions
https://github.com/expressjs/cookie-session
https://github.com/oskosk/express-socket.io-session
https://stackoverflow.com/questions/25532692/how-to-share-sessions-with-socket-io-1-x-and-express-4-x
https://stackoverflow.com/questions/10771337/adding-a-cookie-value-on-socket-io

from another side using this module "https://github.com/expressjs/cookie-session"  when I try to save the session through socket  I'm getting :
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
here is the code 

`
socket.request.session.aa=55;
socket.request.session.save();
`

**Comment by darrachequesne** [comment]
For future readers:

Please see an example for maintaining a persistent session: http://localhost:4000/get-started/private-messaging-part-2/

**Comment by saheedt** [comment]
> For future readers:
> 
> Please see an example for maintaining a persistent session: http://localhost:4000/get-started/private-messaging-part-2/

Hey @darrachequesne , I know this has been a while but the link to the sample app here is pointing to a localhost, can you help update it?

**Comment by darrachequesne** [comment]
@saheedt you are absolutely right, here is the right link: https://socket.io/get-started/private-messaging-part-2/

You can also check:

- how to deal with cookies: https://socket.io/how-to/deal-with-cookies
- how to use with express-session: https://socket.io/how-to/use-with-express-session

**Comment by saheedt** [comment]
Thanks a great deal for the extremely swift response @darrachequesne

**Comment by DrKlonk** [comment]
Hi @darrachequesne, I cannot get the value of a cookie set in the initial_headers function to get set before the _first_ connect() call.

```js
import { randomUUID } from 'crypto';
import { serialize, parse } from 'cookie';

io.engine.on('initial_headers', (headers, request) => {
  headers['set-cookie'] = serialize('sessionId', randomUUID(), {
      sameSite: 'strict',
      path: '/',
      maxAge: 86400
    });
})
...
io.on('connection', (socket) => {
  console.log(socket.request.headers.cookie, socket.handshake.headers.cookie) // prints undefined undefined on the first connect
})
```

When I refresh the frontend the cookie is set and it logs `sessionId=6528604c-a990-4d3e-b4f7-8cc1af2dec1c`. Is it possible to have this work on the first time connect() is called from the client?
