### ISSUE TITLE
Inside socket io on function, code is being skipped for some reason

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io#3439]
Somehow the code I'm writing inside the function that is called when socket io receives an event from the client, is being skipped. 
socket.on('event', function)

Now inside function(data, callback){
Line 1
await function()
callback()
}

Line 1 gets executed but the function at line 2 doesn't even get called. the callback is sent immediately after skipping it. Please help. What am I doing wrong here? Has it happened to you before? 
Thanks.

**Comment by bolthorn91** [comment]
It looks like you need to "promisify" your async functions if you want to wait them to execute. Maybe this could help you.

https://medium.freecodecamp.org/how-to-make-a-promise-out-of-a-callback-function-in-javascript-d8ec35d1f981

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
