### ISSUE TITLE
Socket IO hangs up with HTTPS

### ISSUE THREAD

**Issue by D19cannon** [socketio/socket.io#3441]
### You want to:
Hi guys,  

I have been trying to to solve this socket problem for the last 8h. For some reason when it is on my local system over http there is not a single issue. However, the moment I uploaded it on the dev and tried to setup a secure connection over https with all the SSL certificates etc the connection suddenly 'hangs up'. Also, made sure that all the requests are going to the right domain, ip-address and port.

I have been searching and trying many solutions, but none of them unfortunately worked for me...

The server initialises and mongodb as well. It also did ran a few of my timer-loops, but not they're all dead.

Any ideas or suggestions?

### Current behaviour

Localhost over an http connection with the server Socket IO works normally, however, the moment some SSL is needed over https it "hangs up".

### Steps to reproduce (if the current behaviour is a bug)

```javascript
const fs = require('fs');
const express = require("express");
const mongoose = require("mongoose");
const bodyParser = require("body-parser");
const cors = require("cors");

const options = {
  key: fs.readFileSync('privkey.pem'),
  cert: fs.readFileSync('cert.pem'),
  ca: fs.readFileSync('chain.pem'),
  rejectUnauthorized : false,
  secure: true,
  reconnect: true,
  ciphers: 'ECDHE-RSA-AES128-GCM-SHA256:!RC4',
  transport: ['polling']
};

const app = express();
const httpsServer = require("https").createServer(options, app);
const io = require("socket.io")(httpsServer);

// some ip address
httpsServer.listen(8000, '1.1.1.1', function () {
  console.log("Server running on port: 8000");
});

io.on("connection", client => {
  console.log('success');
}
```

### Setup
versions:
Node: 12.1.0 (also tried /w 10.6.0)
socket.io: 2.1.1
socket.io-client: 2.1.1

server:
Nginx

### Error messages
Browser console error:  net::ERR_EMPTY_RESPONSE

Server error:
UnhandledPromiseRejectionWarning: Error: socket hang up
    at createHangUpError (_http_client.js:335:17)
    at Socket.socketOnEnd (_http_client.js:436:23)
    at Socket.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)
(node:1691) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)

**Comment by XOR-LIFE** [comment]
@D19cannon  it might be late, idk if you solved the problem or not.

I don't have much knowledge of node but I have in Nginx. and as you said that you are using nginx then I think you are also using it as a reverse proxy for your node app, then you only let nginx handle the SSL thing and let node do what it does.

see my tutorial https://github.com/XOR-LIFE/node-production

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
