### ISSUE TITLE
unable to access other module data when using Window.websocket with socket.io.

### ISSUE THREAD

**Issue by ksabariraj** [socketio/socket.io#3442]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*

When I am using socket.io-client/WS node client, I'm able to access the bot list (local variable in bot module) by using " bot.getList();". But, When I am using the default browser WebSocket "window.WebSocket || window.MozWebSocket" to connect socket.io, always I am getting bot list as empty on 'onMessage' event. I can't able to access any stored local variable data.

`const bot = require('../bots')
var io = require('socket.io').listen(http);
var redis = require('socket.io-redis');
io.adapter(redis({ host: 'localhost', port: 6379 }));
io.on('connection', function (socket) {
        // console.log("socket", socket);
        socket.on('message', (data) => {
            if(data.action == 'history') {
                gotMessage();
            } else {
                bot.getList();
            }
        });
});`

### Steps to reproduce (if the current behaviour is a bug)

Connect Socket.io server with inbuilt browser WebSocket and try to access local data from some module, inside 'onMessage' event.

### Expected behaviour

*What is expected?*

Should able to access the local variable data.

### Setup
- OS: Mac
- browser: All
- socket.io version: 2.2.0

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
