### ISSUE TITLE
Help me : About socket

### ISSUE THREAD

**Issue by dubini** [socketio/socket.io#3445]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:
I am a student who is new to socket communication. I do not have a sense of what to do and I would like to ask you a few questions. I want to use socket communication in raspberry pi 3, what is the default setting? And basically what do you need to know? We are configuring the server with nodejs. I would be grateful if you could answer the question.

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour

*What is actually happening?*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

*What is expected?*

### Setup
- OS: linux (raspberry pi)
- browser: chrome
- socket.io version:

**Comment by ikalisz** [comment]
I don't use Linux but I have used sockets with Node.js and would love to try and help.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
