### ISSUE TITLE
Flaky test: listen EADDRINUSE: address already in use :::54024

### ISSUE THREAD

**Issue by BridgeAR** [socketio/socket.io#3447]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Running the test suite frequently runs into an `listen EADDRINUSE: address already in use :::54024` error. That prevents the library to be properly tested in [CITGM](https://github.com/nodejs/citgm). We had the tests marked as flaky but running them as such does not help much. Thus, it would be great if this could be looked at and fixed.

See e.g., https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1855/nodes=rhel72-s390x/testReport/junit/(root)/citgm/socket_io_v2_2_0/

### Steps to reproduce (if the current behaviour is a bug)

Run the test frequently.

### Expected behaviour

The tests all pass.

### Setup
- OS: Multiple (Linux / Windows)
- socket.io version: v2.2.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

   1 failing
   1) socket.io handshake should allow request when using an array of origins:
      Uncaught Error: listen EADDRINUSE: address already in use :::54024
       at Server.setupListenHandle [as _listen2] (net.js:1226:14)
       at listenInCluster (net.js:1274:12)
       at Server.listen (net.js:1362:7)
       at Server.listen.Server.attach (lib/index.js:64:524)
       at Context.<anonymous> (test/socket.io.js:361:55)
       at processImmediate (internal/timers.js:439:21)

**Comment by darrachequesne** [comment]
Fixed by https://github.com/socketio/socket.io/commit/7a74b66872d53f00eac0d80b1869d06a1ebe2f1d.

**Comment by Psoffie009** [comment]
> ### You want to:
> * [x]  report a _bug_
> * [ ]  request a _feature_
> 
> ### Current behaviour
> Running the test suite frequently runs into an `listen EADDRINUSE: address already in use :::54024` error. That prevents the library to be properly tested in [CITGM](https://github.com/nodejs/citgm). We had the tests marked as flaky but running them as such does not help much. Thus, it would be great if this could be looked at and fixed.
> 
> See e.g., https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1855/nodes=rhel72-s390x/testReport/junit/(root)/citgm/socket_io_v2_2_0/
> 
> ### Steps to reproduce (if the current behaviour is a bug)
> Run the test frequently.
> 
> ### Expected behaviour
> The tests all pass.
> 
> ### Setup
> * OS: Multiple (Linux / Windows)
> * socket.io version: v2.2.0
> 
> ### Other information (e.g. stacktraces, related issues, suggestions how to fix)
> 1 failing
> 
> 1. socket.io handshake should allow request when using an array of origins:
>    Uncaught Error: listen EADDRINUSE: address already in use :::54024
>    at Server.setupListenHandle [as _listen2] (net.js:1226:14)
>    at listenInCluster (net.js:1274:12)
>    at Server.listen (net.js:1362:7)
>    at Server.listen.Server.attach (lib/index.js:64:524)
>    at Context. (test/socket.io.js:361:55)
>    at processImmediate (internal/timers.js:439:21)
