### ISSUE TITLE
When calling `socket.to(roomId).emit`, the current socket won't receive this event even it has joined the room.

### ISSUE THREAD

**Issue by zhaoyao91** [socketio/socket.io#3449]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*

I am compare the two apis:

`socket.to(roomId).emit(...)` vs `socket.broadcast.to(roomId).emit(...)`

By now, even if the the sender socket is in the target room, both apis won't send this event to it (or it doesn't want to receive the event?).

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

```
const logger = console;

io.of("/test-room").on("connect", socket => {
  const sid = socket.id;

  logger.info("client connected", { sid });

  socket.on("c.join-room", ({ roomId }, ack) => {
    logger.info("client join room [", { sid, roomId });
    socket.join(roomId, () => {
      logger.info("client join room ]", { sid, roomId });
      ack();
    });
  });

  socket.on("c.leave-room", ({ roomId }, ack) => {
    logger.info("client leave room [", { sid, roomId });
    socket.leave(roomId, () => {
      logger.info("client leave room ]", { sid, roomId });
      ack();
    });
  });

  socket.on("c.message", ({ roomId, message }) => {
    logger.info("client sent message", { sid, roomId, message });

    socket.to(roomId).emit("s.message", message);
    // socket.broadcast.to(roomId).emit("s.message", message);
  });

  socket.on("disconnect", reason => {
    logger.info("client disconnected", { sid, reason });
  });
});
```

### Expected behaviour

*What is expected?*

With `socket.to(roomId).emit(...)`, the socket itself, if it joined the room, will receive this event. But with `socket.broadcast.to(roomId).emit(...)`, it won't receive the event.

### Setup
- OS: mac 10.14.5
- browser: chrome 74.0.3729.169
- socket.io version: 2.2.0

**Comment by GustavoMorais** [comment]
to send for everyone on room and the sender, just use:
`io.in("roomid").emit("...");`

**Comment by ralphpig** [comment]
This is documented behavior: https://socket.io/docs/server-api/#socket-to-room.

`socket.<broadcast?>.to(roomId).emit(...)` doesn't and shouldn't emit to `socket`.

However I think there's some ambiguity as to what is supposed to be the difference between:
- `socket.to(roomId).emit(...)`
- `socket.broadcast.to(roomId).emit(...)`

**Comment by ralphpig** [comment]
@GustavoMorais 

You **must** include the Namespace that the socket is connected through.

```js 
io.of(...).in(roomId).emit("..."); 
```
or 
```js
let nsp = io.of(..);
nsp.in(roomId).emit("...");
```

**Comment by GustavoMorais** [comment]
@ralphpig it's not necessary include the namespace if your application design use default namespace "/" for everything, you can check this on _emit cheatsheet_

```
// sending to all clients in 'game' room, including sender
io.in('game').emit('big-announcement', 'the game will start soon');
```

https://socket.io/docs/emit-cheatsheet/

**Comment by ralphpig** [comment]
@GustavoMorais 

Right, but in this example they use a namespace of `test-room`.

Also I said 
> ... Namespace that the socket is connected through

So if the socket is _connected through_ the default namespace, then `io.in(..)` is fine, but if it's not then you **must** include a namespace.

I was including that point only because if the socket is in `test-room`, then just `io.emit(..)` will not work.

**Comment by berksafran** [comment]
I have same issue. When i emit a variable from server to a room, the current socket didn't receive any message. 
I'm using this method:
```
// sending to all clients in 'game' room, including sender
io.in('game').emit('big-announcement', 'the game will start soon');

```

**Comment by CroquetMickael** [comment]
Same issue as @berksafran, emitting a message with  
```javascript
 io.in("game").emit("big-announcement", "the game will start soon");```

It's not working but with :
```javascript
socket.nsp.in(roomName).emit("big-announcement", "the game will start soon");
```

It works like a charm

**Comment by darrachequesne** [comment]
For future readers:

`socket.to(roomId).emit(...)` and `socket.broadcast.to(roomId).emit(...)` are equal (the event will be emitted to everyone in the room excluding the given `socket`).

The `broadcast` flag can be omitted in the 2nd expression, it is only useful when no room is used (`socket.broadcast.emit(...)`, which means broadcasting to everyone excluding the given `socket`).

I have updated the documentation:

- broadcasting to all: https://socket.io/docs/v3/broadcasting-events/
- broadcasting to room: https://socket.io/docs/v3/rooms/
- cheatsheet: https://socket.io/docs/v3/emit-cheatsheet/
