### ISSUE TITLE
Same event emitting multiple times in socket.io-client reactjs

### ISSUE THREAD

**Issue by rajatlnweb** [socketio/socket.io#3453]

**Comment by ikalisz** [comment]
Can you give more details like examples of your code? Are you using hooks or class based React components?

**Comment by rajatlnweb** [comment]
I am using class based components. When I click on send message button, Then I fire an event and listen that event on server side and from server side I fire another event which I listen on frontend. I put my event listen code in componentDidMount. You can refer to below link to understand about the question more:

https://stackoverflow.com/questions/56430669/same-event-emitting-multiple-times-in-socket-io-client-reactjs

**Comment by ikalisz** [comment]
Instead of method chaining your socket client side, try just invoking it on the componentDidMount. It might be creating a lot of sockets. I would first try this before changing anything, add a console.log on your back end.
`
io.on('connection',function(socket){
    console.log('a user has connected') <-- Add this line
    socket.on('send_message',function(data){
        io.emit('msg',data);
    })
})
`

If you see multiple users are connected then change your front end to
`
var socketIOClient = require('socket.io-client') <--- Removed Method Chain

sendMessageClicked(e) {
    e.preventDefault();
    let message = this.state.originalMessage;

    var data = {
        message: message,
        time: Date.now()
    }

    socketIOClient.emit('send_message',data);
}

componentDidMount() {
    socketIOClient = socketIOClient('http://localhost:4001') <-- Add this first
    or if the above doesn't work try
    socketIOClient('http://localhost:4001') <-- try this line second
    socketIOClient.on('msg',function(result){
        let messageHtml = 'messages working!';
        let messageBox = document.getElementById('messageBox');

        if (messageBox ) {
            messageBox.appendChild(messageHtml);
        }
    })
}

render(){
    return(
        <div>
            <form onSubmit={this.sendMessageClicked}>
                <textarea onChange={this.handleMessageChange} name="originalMessage" value={this.state.originalMessage}></textarea>
                <input type="submit" value="" />
            </form>
        </div>
    );
}
`

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by Muhammadsheraz492** [comment]
please reopen this issues

**Comment by Abhikumar98** [comment]
> Instead of method chaining your socket client side, try just invoking it on the componentDidMount. It might be creating a lot of sockets. I would first try this before changing anything, add a console.log on your back end. `io.on('connection',function(socket){ console.log('a user has connected') <-- Add this line socket.on('send_message',function(data){ io.emit('msg',data); }) })`
> 
> If you see multiple users are connected then change your front end to `var socketIOClient = require('socket.io-client') <--- Removed Method Chain` `componentDidMount() { socketIOClient = socketIOClient('http://localhost:4001') <-- Add this first or if the above doesn't work try socketIOClient('http://localhost:4001') <-- try this line second //Other code below`
> 
> Edit: Sorry I'm new to formatting github Messages.

Agreed with you.
Rewriting it in formatted manner to be able to grasp in a glance.

Putting `sockets.on` outside creates more connections on every re-render.

```
const sockets = io( ... )

useEffect(() => {
	socket.on("connect", () => console.log("connected")); // only 1 connection established

	return () => socket.off('disconnect', () => { ... })
}, []);

```

**Comment by Localstack-alluring** [comment]
@Muhammadsheraz492 https://lnkr.fun/115fc5a
