### ISSUE TITLE
Duplicate ping timeout disconnect events get fired

### ISSUE THREAD

**Issue by betimer** [socketio/socket.io#3454]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

When clients gets disconnect events, sometimes duplicate events get fired.

FYI. the screenshot and we can see they are fired at the exact millisecond. 

![image](https://user-images.githubusercontent.com/8111748/59075479-18352c80-8914-11e9-830a-d7d5738a0052.png)

**Comment by sarameie** [comment]
I get the same problem, which makes counting clients very annoying

**Comment by darrachequesne** [comment]
This should be fixed in latest releases, please reopen if needed.
