### ISSUE TITLE
socket.io is not working correctly with React js Node.js and Express.js for multiple tabs

### ISSUE THREAD

**Issue by usamamashkoor** [socketio/socket.io#3457]
I am trying to integrate the socket.io with React.js I am running socket.io on server with Express.js back end.

The problem is this I am on homepage and when order is placed from homepage then i am showing that order in the Orders page of React but the problem is it sometimes shows the order but it sometimes does not shows the order and if i open multiple tabs on different browsers then on some tabs in some browsers the order does not show mean the socket connection does not work some time but in all of the cases when ever a order is created from home page then the emit from the socket.io from home page is showing in the Node.js Express.js back end.

Please note I am using clustering module on the express.js

Here is how i am creating the socket.io connection.

`socket = io('http://localhost:5000',{ reconnect: true ,transports: ['websocket']});`

Here is my homepage react component from where i am placing the order.

`socket.emit("putKitchenOrder", Order);`

Here is my second component on which i want to show the order which is placed in real time using socket.io 

```
componentWillUnmount(){
   socket.off("kitchen-channel:orderPlacedFromPos");
}
componentDidMount() {
    socket.on("kitchen-channel:orderPlacedFromPos",  (order) => {
        console.log('order in orderPlacedFromPos');
        console.log(order);
        alert('order in orderPlacedFromPos')

    });
}
```

Here is my Node.js and Express.js code
```
io.on("connection", socket => {
  socket.on("putKitchenOrder", order => {
    // this console.log is always showing in the node.js console window when ever a new order is placed from the homepage component but the second page is not getting the following emit "kitchen-channel:orderPlacedFromPos" sometime.
    console.log('putKitchenOrder order');
    io.emit("kitchen-channel:orderPlacedFromPos",order);

  });
});
```

The console.log('putKitchenOrder order'); is always showing in the node.js console window when ever a new order is placed from the homepage component but the second page is not getting the following emit "kitchen-channel:orderPlacedFromPos" sometime.

**Comment by Sourav-98** [comment]
Could you please share the entire ReactJS code and the NodeJS server code, for better analysis?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
