### ISSUE TITLE
Socket IO 2.2.0 server stops receiving incoming emits randomly and silently

### ISSUE THREAD

**Issue by kaansoral** [socketio/socket.io#3459]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*Socket IO 2.2.0 server stops receiving incoming messages randomly and silently*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: I was using Socket IO 2.1.1 for a long time, recently switched to Google Cloud VM's, and started experiencing this issue, I develop a game, right after the switch, servers randomly stopped receiving incoming emit's some hours after they were started

### Expected behaviour

*Reverted back to Socket IO 2.1.1 - it's been 2 days, no issues ever since on Google Cloud, it was either Google Cloud's network or Socket IO 2.2.0 - I believe it's Socket IO 2.2.0 now*

### Setup
- OS: Ubuntu 18.04 LTS on Google Cloud
- socket.io version: 2.2.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

Completely silent, no errors, server continues receiving regular HTTP requests

*So it's a very bizarre issue, did anything change in 2.2.0 that could cause this? I can't really reproduce or debug it anymore, since every time it happens, a gameworld dies*

**Comment by Ericxgao** [comment]
I am also having similar issues, but only with specific browsers. Desktop chrome and desktop firefox fail for me, while Safari, Edge, Mobile Chrome, and Mobile Safari still work. Do you have browser specific failures as well?

**Comment by kaansoral** [comment]
I couldn't test too deeply, Chrome was unable to connect, however, the server logged frequent connects/disconnects, so I assumed maybe a non-websocket client was able to connect only to fail later on etc.

**Comment by chevett** [comment]
this looks like the same issue as https://github.com/socketio/socket.io/issues/3461

**Comment by devflexpro** [comment]
exactly the same problem here

socket.io 2.2.0
macOS 10.13.6
no specific browsers

**Comment by marksalpeter** [comment]
I think I might be experiencing the same problem as well. @kaansoral, did you stop receiving all incoming emits from a client or were just a few missing?

**Comment by kaansoral** [comment]
All of them, seems fixed now tho, for a while I manually patched it, I guess the fix got into regular releases later on

**Comment by marksalpeter** [comment]
Interesting, it looks like the 2.3.0 release is the only one after 2.2.0 
and the changes seem very minor. Are you sure you're not still using a 
manual patch you made?

**Comment by kaansoral** [comment]
Just checked a live server, seems to use socket.io 2.1.1 - So it seems my solution was to just revert to 2.1.1 for the time being, apologies for the confusion, there was another issue that needed a manual change, I thought this was that issue

**Comment by marksalpeter** [comment]
Super informative. Thanks, I'll do the same 🙏

**Comment by ikerya** [comment]
> Just checked a live server, seems to use socket.io 2.1.1 - So it seems my solution was to just revert to 2.1.1 for the time being, apologies for the confusion, there was another issue that needed a manual change, I thought this was that issue

Could you give a few words about your issue? It may help others

**Comment by kaansoral** [comment]
Issue is simple, solution/cause is unknown (to us), lack of attention/fix is perplexing

**Comment by darrachequesne** [comment]
OK, let's dig into this...

- Socket.IO 2.2.0 includes Engine.IO [~3.3.1](https://github.com/socketio/socket.io/blob/2.2.0/package.json#L28)
- Socket.IO 2.1.1 includes Engine.IO [~3.2.0](https://github.com/socketio/socket.io/blob/2.1.1/package.json#L28)

The diff is here: [3.2.0...3.3.1](https://github.com/socketio/engine.io/compare/3.2.0...3.3.1)

The only thing that I think could explain the different behavior is the Websocket server:
- Engine.IO 3.3.2 includes ws [~6.1.0](https://github.com/socketio/engine.io/blob/3.3.2/package.json#L32)
- Engine.IO 3.2.1 includes ws [~3.3.1](https://github.com/socketio/engine.io/blob/3.2.1/package.json#L32)

The diff is huge, I think it was more or less a complete rewrite: [3.3.1...6.1.2](https://github.com/websockets/ws/compare/3.3.1..6.1.2)

But I didn't find anything in the release notes: https://github.com/websockets/ws/releases

Are you able to reproduce with Socket.IO 2.3.0? (which includes ws 7.x.x)

**Comment by darrachequesne** [comment]
I'm not sure what happens exactly. Are users able to connect at all? Is the underlying WebSocket server unresponsive? Could you please provide a heapdump, in case that's related to a memory leak? Thanks!

**Comment by kaansoral** [comment]
Sorry for the lack of a reply, I was busy with stuff other than work, currently I will (within 2 weeks) deploy one server with the latest version of Socket.io and see if the issue is still there

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
