### ISSUE TITLE
socket.io web site menu broken on iPad

### ISSUE THREAD

**Issue by tohagan** [socketio/socket.io#3466]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*

For Safari / iPad ...
1. In Landscape orientation... “Learn” and “Resources” menu options on socket.io web site don’t respond when tapped.
2. In Portrait orientation the Menu disappears!

In Chrome on my iPad, the menu options work (drop down appears) in Landscape, menu is hidden in Portrait orientation.

Not tested on iPhone 

### Expected behaviour

Should appear and be navigable.  

### Setup
- OS: iOS / iPad Air model MD789X/A 
- browser: Safari

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
