### ISSUE TITLE
fs on client in docs

### ISSUE THREAD

**Issue by kjr247** [socketio/socket.io#3468]
**Note**: 

### You want to:

* [x] report a *bug* _in the docs_
https://socket.io/docs/client-api/#With-a-self-signed-certificate

### Current behaviour
In the docs it says 
``` javascript
client-sideconst 
socket = io({  
    // option 1  
    ca: fs.readFileSync('server-cert.pem')
});
--
```

*What is actually happening?*
`socketioTestLab.js:32 Uncaught ReferenceError: fs is not defined`

### Steps to reproduce (if the current behaviour is a bug)
Try accessing fs in the client js in a browser... it's a node thing browsers don't know what this is.

**Note**: Open any browser and in the console type fs and see that browsers don't understand it. Docs need to be updated.

### Expected behaviour

*What is expected?* Yes... what is expected here? It should do something other than error and break the page.

### Setup
- OS: any
- browser: any
- socket.io version: any

**Comment by Jopchumba** [comment]
Please clarify the question because I am trying to get the context 
Thanks

**Comment by Edeph** [comment]
@kjr247 is reporting a problem with documentation. It's node.js code that cannot run in browsers. What question are you referring to anyway @Jopchumba ?

**Comment by darrachequesne** [comment]
Documentation: https://socket.io/docs/v3/client-initialization/#Node-js-specific-options
