### ISSUE TITLE
No callback on socket.open()

### ISSUE THREAD

**Issue by prographo** [socketio/socket.io#3470]
According to the documentation here: https://socket.io/docs/client-api/#manageropencallback

The callback should be called in the event the connection fails. It is not.

```
const io = require('socket.io-client')
const socket = io( "rubbish", {rejectUnauthorized: false, autoConnect: false, timeout: 2000, reconnectionAttempts: 1} )
socket.open( function() { console.log("Hello") } )
```

**Comment by prographo** [comment]
It is also not called on success... the callback is simply not called.

**Comment by prographo** [comment]
I've got what I wanted by doing the following:

```
socket.on('connect', () => { 
  console.log("socket.id: "+socket.id)
})

socket.on('connect_error', () => {
  console.log("connect error")
})

socket.open( () => { console.log("NEVER HERE") } )
```

Some examples in the documentation wouldn't go amiss.

**Comment by darrachequesne** [comment]
For future readers:

`socket.open()` (or `socket.connect()`) does not accept a callback argument.

The manager does though:

```js
const io = require('socket.io-client');

const socket = io("https://mydomain.com", {
  autoConnect: false
});

const manager = socket.io;

manager.open((err) => {
  // ...
});
```

I've added an example in the documentation: https://socket.io/docs/v4/client-api/#manageropencallback
