### ISSUE TITLE
Static ID that will save after user disconnects.

### ISSUE THREAD

**Issue by PixelNinja132** [socketio/socket.io#3472]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current problem

*What is actually happening?*
trying to ban users with socket.ip but sometimes changes

### Steps to reproduce (if the current behaviour is a bug)

upon joining, if a user has a banned ip, it will disconnect them

### Expected behaviour

*What is expected?*
a static id for each user that is created when they first join, this is also useful to see if it is a new user

### Setup
- OS: Windows
- browser: Chrome
- socket.io version: 2

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

just add a static ID like socket.id but maybe socket.staticID

**Comment by darrachequesne** [comment]
For future readers:

For this use case, you can simply use a cookie:

```js
io.engine.on("initial_headers", (headers, req) => {
  const cookies = cookie.parse(req.headers.cookie || "");
  if (!cookies["mycookie"]) {
    headers["Set-Cookie"] = cookie.serialize("mycookie", "random value");
  }
});
```
