### ISSUE TITLE
Namespace connection causes second WS connection

### ISSUE THREAD

**Issue by CycoPH** [socketio/socket.io#3476]
### Short info
Namespace connections are supposed to be multiplexed on top of normal connections (using a single TCP/IP connection). This works until you loose connection to the server.  At reconnect two connections are established.

### Current behaviour
socket.io opens a second TCP/IP connection when reconnecting on a Namespace.
The default behaviour is that a Namespace connection is multiplexed on top of a base socket.io connection.  In the attached example you can see the server logging this behaviour:
```
new ws YYmsRZT2fsmZYNuAAAAB
asking to join
new NS ws /info#YYmsRZT2fsmZYNuAAAAB
```
and the client this
```
connected to server with YYmsRZT2fsmZYNuAAAAB
sending out join request
received join
connected to server/info with /info#YYmsRZT2fsmZYNuAAAAB
```

All perfect.  We are using a single TCP/IP connection.
Now restart the server and the client will reconnect giving these logs:
Server:
```
new ws TdvIBazUsVKVYP-4AAAA
asking to join
new ws j3OU8fxeGC-NWctBAAAB
new NS ws /info#j3OU8fxeGC-NWctBAAAB
```

Client:
```
GET http://localhost:2222/socket.io/?EIO=3&transport=polling&t=MoEjEDs 
connected to server with TdvIBazUsVKVYP-4AAAA
sending out join request
received join
connected to server/info with /info#j3OU8fxeGC-NWctBAAAB
```

What we see here is the base connection has been re-established as `TdvIBazUsVKVYP-4AAAA` but the namespace connection has opened a second connection `j3OU8fxeGC-NWctBAAAB`

Don't think this is the correct behaviour, it should still communicate on the base connection.

### Steps to reproduce (if the current behaviour is a bug)
Here is the test case [fiddle](https://github.com/CycoPH/socket.io-fiddle)

### Expected behaviour

I would expect the namespace connection to be multiplexed over the new connection and not to open another WS connection

### Setup
- OS: win10
- browser: Chrome 76
- socket.io version: 2.2.0

**Comment by darrachequesne** [comment]
For future readers: the misunderstanding here comes from the fact that the `connect` event is emitted both for the connection and the reconnection, so:

```js
socket.on('connect', () => {
  console.log("connected to server with", socket.id);
  console.log("sending out join request");
  // sent for each connection and reconnection!
  socket.emit('join');
});

socket.on('join', () => {
  console.log("received join");
  // a new connection is created upon each reconnection (the first time, the same low-level connection
  // is reused, but the following create a new manager every time)
  infoSocket = io(socketUrl + 'info');
  infoSocket.on('connect', () => {
    console.log("connected to server/info with", infoSocket.id);
  });
  
  infoSocket.on('disconnect', () => {
    console.log("disconnected from server/info", infoSocket.id);
    infoSocket.disconnect();
  });
});
```

The documentation should be clearer now: https://socket.io/docs/v4/client-socket-instance/#connect
