### ISSUE TITLE
Cors error resolved but got 404 not found

### ISSUE THREAD

**Issue by amits505** [socketio/socket.io#3479]
Hi 
I have created a simple socket app and was getting cors error. I used the **cors** package to remove the cors error. But now I'm getting. https://chat.collegewrk.com/socket.io/?EIO=3&transport=polling&t=Mop5QD2 404 (Not Found)
Please help.

**Comment by jonathangaldino** [comment]
Same thing.

(SERVER) Morgan log: GET /socket.io/?EIO=3&transport=polling&t=Msu3mq_ 404 149 - 0.253 ms

**Comment by jonathangaldino** [comment]
I found that I was starting http server and not express server.

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socket.io/docs/v3/troubleshooting-connection-issues/
