### ISSUE TITLE
express not await events socket.io

### ISSUE THREAD

**Issue by maikjr** [socketio/socket.io#3483]
Hello.

I don't know why but my express is not waiting for socket events.
I'm using:
Centos 6 + nginx + nodejs + pm2
-----
const server = require('http').Server(app);
const io = require('socket.io')(server, { rememberTransport: false, transports: ['websocket'] });

let userConnected;

io.sockets.on('connection', (socket) => {
   userConnected = socket.id;
});

EXPRESS 
app.use((req, res, next) => {
  req.io = io;
  console.log(userConnected); <- return empty
  console.log(io.sockets.adapter.rooms); <- return empty
  
  return next();
});

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
