### ISSUE TITLE
Repeated connection and disconnection

### ISSUE THREAD

**Issue by ysk2014** [socketio/socket.io#3484]
![image](https://user-images.githubusercontent.com/8800042/64272973-009d2c80-cf73-11e9-81e5-7181fbf3b1ed.png)

**Comment by berksafran** [comment]
Same issue.

**Comment by adobnikar** [comment]
Same issue.

**Comment by adobnikar** [comment]
This helped: https://stackoverflow.com/questions/41924713/node-js-socket-io-page-refresh-multiple-connections

**Comment by ysk2014** [comment]
Thanks

**Comment by adobnikar** [comment]
After further retries, I figured out that this issue was caused by using incompatible server and client versions of the scoket.io library. So before restricting the communication to only websockets it is good to check the versions of the server and client libraries.
