### ISSUE TITLE
How to improve socket.io's performance in transmission?

### ISSUE THREAD

**Issue by wikipac** [socketio/socket.io#3488]
Hi,
I need to send 30-40 MB of data per second. But I was only got 4MB.
I want to know how to improve socket.io's performance in transmission.

Server.js

`var http = require("http"),
    io = require("socket.io")(http, { 
      wsEngine: "ws", 
      serveClient:false, 
      pingTimeout: 60000,
      pingInterval: 25000,
      upgradeTimeout: 10000,
      maxHttpBufferSize: 100000000,
      allowUpgrades: true, 
      transports:"websocket" });

var server = http.createServer(function(req, res){ 
  res.writeHead(200,{ "Content-Type": "text/html" }); 
  res.end("Hello Socket!");
});

server.listen(10030);
var socket = io.listen(server);

io.on("connection", function(client){ 
	
    client.on("message",function(event){ 
    console.log("Received message from client!",event);
    client.send(testData);

  });
  
	client.on("disconnect",function(){
		console.log("Server has disconnected");
	});

});`

Client.html

`<script>
var socket = io("http://localhost:10030");
    socket.connect(); 
    socket.on("connect",function() {
        console.log("Client has connected to the server!");
    });

    socket.on("message",function(data) {
        console.log(data);
        sendMessageToServer("Hi Server ! ");
    });
</script>`

Socket.io version : 2.2.0
NodeJS version: 10.16.3

**Comment by darrachequesne** [comment]
For future readers: the transmission speed depends most frequently on the size of the pipe.

If you think Socket.IO is a bottleneck, there are two potential solutions:

- use another WebSocket server implementation, like [eiows](https://github.com/mmdevries/eiows)

```js
const io = require("socket.io")(httpServer, {
  wsEngine: require("eiows").Server
});
```

Reference: https://socket.io/docs/v4/server-installation/#Other-WebSocket-server-implementations

- use a custom parser, like [socket.io-msgpack-parser](https://github.com/socketio/socket.io-msgpack-parser)

```js
const { Server } = require("socket.io");
const parser = require("socket.io-msgpack-parser");

const io = new Server(httpServer, {
  parser
});
```

Reference: https://socket.io/docs/v4/custom-parser/#The-msgpack-parser
