### ISSUE TITLE
Namespace as a Function Doesn't Do Anything

### ISSUE THREAD

**Issue by aronduby** [socketio/socket.io#3489]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

When attempting to use a dynamic [namespace as a function as outlined in the docs](https://socket.io/docs/server-api/#server-of-nsp), it ignores what is passed through to next and just uses the original string.

### Steps to reproduce (if the current behaviour is a bug)

https://github.com/aronduby/socket.io-fiddle

- make the server's `of` method call next with a specific namespace value
- open index and index2
- see that despite overriding the ns in the `of` `next` function the sockets are still namespaced to main and main2

### Expected behaviour

*What is expected?*
They would be connected to the namespace supplied by the of function

### Setup
- OS: windows, node 8.16.1
- browser: chrome
- socket.io version: 2.2.0

**Comment by dehypnosis** [comment]
I figured out what is the next function in Server.of resolver function.
```js
(err, allow) => {
      if (err || !allow) {
        run();
      } else {
        fn(this.parentNsps.get(nextFn.value).createChild(name));
      }
    }
```

As you can see, it seems that 2nd parameter of next function just accept boolean type value.
So, Server.of resolver function just dynamically determine that the given namespace derived from URI can be open or cannot be....

Also i had misunderstood this feature like you, and also hope a feature to resolve a socket to a specific namespace not just original URI for the purpose of reuse of existing namespace.

**Comment by darrachequesne** [comment]
For future readers:

The documentation about dynamic namespaces has been updated, and will hopefully be clearer: https://socket.io/docs/v4/namespaces/#dynamic-namespaces

Please reopen if needed.
