### ISSUE TITLE
Recommend 'good first issue' for newcomers.

### ISSUE THREAD

**Issue by SunflowerPKU** [socketio/socket.io#3490]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour

*What is actually happening?*
No issue recommended to newcomers.
### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

*What is expected?*
Nowadays, many popular projects are using tags such as 'good first issues' to attract newcomers. I suggest labeling ceratin issues for newcomers to help them contribute successfully.
### Setup
- OS:
- browser:
- socket.io version:

**Comment by darrachequesne** [comment]
Here we are: https://github.com/socketio/socket.io/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
