### ISSUE TITLE
Unexpected behavior of origins

### ISSUE THREAD

**Issue by xiaoyaozi5566** [socketio/socket.io#3491]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*
I setup socket io on the server side and wanted to use the `origins` feature to restrict the allowed clients. The origins I use was

`['https://mywebsite:*']`

but the socket io connection from mywebsite got rejected. After a closer look into the library, I found the line causing it https://github.com/socketio/socket.io/blob/9c1e73c752aec63f48b511330a506d037783d897/lib/index.js#L84 
Basically, when the protocol (https or http) is specified, the origins check requires the specific port to be specified as well. 

While I understand `443` is for `https` and `80` is for `http` by standard, syntactically speaking, `https://mywebsite:*` should pass `https://mywebsite:443`, so I would consider the current behavior as a bug. Please correct me if I was wrong.

### Steps to reproduce (if the current behaviour is a bug)

Setup a socket io server with origins `['https://mywebsite:*']` and send the request to the server from mywebsite.

### Expected behaviour

*What is expected?*
Explained above, I think `['https://mywebsite:*']` should allow `https://mywebsite:443` to pass. Same for `http` case.

### Setup
- OS:
- browser:
- socket.io version:

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

Add another condition
`~this._origins.indexOf(parts.protocol + '//' + parts.hostname + ':*') ||`
to https://github.com/socketio/socket.io/blob/9c1e73c752aec63f48b511330a506d037783d897/lib/index.js#L84

**Comment by darrachequesne** [comment]
For future readers: the behavior of the `origins` method was indeed quite surprising. It was remove in Socket.IO v3.

Related: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#CORS-handling
