### ISSUE TITLE
"Emit" leaks memory when using acknowledgement callback.

### ISSUE THREAD

**Issue by Erbolking** [socketio/socket.io#3494]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

When emitting message with **acknowledgement** callback, it starts leaking the memory.

### Steps to reproduce (if the current behaviour is a bug)

```js
// this will leak the memory ( with acknowledgements callback)
client.socket.emit('some_event', payload, (data) => {});

// this works fine
client.socket.emit('some_event', payload);
```

### Expected behaviour

it shouldn't leak the memory

### Setup
- OS: macOS High Sierra
- browser: Google Chrome 77.0.3865.90 (Official Build) (64-bit)
- socket.io version: ^2.0.4

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
To clearly see that it's leaking the memory please perform several thousand emits.

**Comment by Chopinsky** [comment]
Could have 2 causes: 

1. The socket is in the `broadcast` mode, where an error will be thrown and cause memory leak, though you should be able to see error messages in your server's console. 
2. The ACK packet is never received (i.e. the client/server not handling the connections correctly), in which case the callback are registered but never invoked (meaning they will stick around forever, until an ACK is received), hence causing the leak. 

I think case #2 is probably the actual cause of the problem you see.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
