### ISSUE TITLE
Incorrect query object when connection to different namespace

### ISSUE THREAD

**Issue by sebamarynissen** [socketio/socket.io#3495]
### Current behaviour

*What is actually happening?*

When one connects to a different namespace with multiplexing **enabled** such as
```js
let one = io.connect('/one', {
  'force new connection': false,
  query: { param: 'one' }
});

let two = io.connect('/two', {
  'force new connection': false,
  query: { param: 'two' }
});
```
the updated query is not parsed correctly on the server. The server side code
```js
let one = io.of('one').on('connection', socket => {
  let { query } = socket.handshake;
  console.log('one', query.param, query.param === 'one');
});
let two = io.of('two').on('connection', socket => {
  let { query } = socket.handshake;
  console.log('two', query.param, query.param === 'two');
});
```
logs
```
one one true
two one false
```
When multiplexing is explicitly disabled by setting 
```js
{ 'force new connection': true }
```
the server logs
```
one one true
two two true
```
as expected.

### Steps to reproduce

Fork https://github.com/sebamarynissen/socket.io-fiddle. Run `npm start`, open up a browser and go to `http://localhost:3000`.

### Expected behaviour

The query object should be the same, regardless of whether multiplexing is enabled or not.

### Setup
- OS: Windows 10
- browser: Chrome 
- socket.io version: 2.3.0

### Other information

When I open up the WS network tab in Chrome devtools, it logs that
```
40/two?param=two
```
is sent to the server, so it seems that at least the client sends the correct query to the server. Hence I guess that this is a server related issue.

**Comment by sebamarynissen** [comment]
I have found the cause of the bug, it is located in socket.js:
```js
Socket.prototype.buildHandshake = function(query){
  var self = this;
  function buildQuery(){
    var requestQuery = url.parse(self.request.url, true).query;
    //if socket-specific query exist, replace query strings in requestQuery
    // The order of query & requestQuery should be swapped! The general
    // `requestQuery` currently overrides socket-specific `query`, but this
    // should be the other way around.
    // return Object.assign({}, query, requestQuery);

    // It should be:
    return Object.assign({}, requestQuery, query);
  }
  return {
    // ...
    query: buildQuery()
  };
};
```

I'm going to file a PR for this.

**Comment by sebamarynissen** [comment]
For people having this issue as well, until #3496 is accepted and published on npm, you can fix it by including the following in your server code:
```js
const url = require('url');
const Socket = require('socket.io/lib/socket');
Socket.prototype.buildHandshake = function(query) {
	let self = this;
	function buildQuery() {
		let requestQuery = url.parse(self.request.url, true).query;
		return Object.assign({}, requestQuery, query);
	}
	return {
		headers: this.request.headers,
		time: (new Date) + '',
		address: this.conn.remoteAddress,
		xdomain: !!this.request.headers.origin,
		secure: !!this.request.connection.encrypted,
		issued: +(new Date),
		url: this.request.url,
		query: buildQuery()
	};
};
```
I can confirm that this fixed my issue which led me to discover this bug.

**Comment by darrachequesne** [comment]
Fixed by https://github.com/socketio/socket.io/commit/d33a619905a4905c153d4fec337c74da5b533a9e (included in `socket.io@2.4.0`).

Please note that this does not apply to Socket.IO v3, since the `query` option has been updated (more information [here](https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#Add-a-clear-distinction-between-the-Manager-query-option-and-the-Socket-query-option)).
