### ISSUE TITLE
I have translated the socket.io Chinese document

### ISSUE THREAD

**Issue by veaba** [socketio/socket.io#3497]
Let the Socket.io document support i18n.

> Meaning is as follows（Translated by Google）：

Hello，everyone：

I have translated the socket.io Chinese document 

Because I couldn't find the relevant Chinese documents, I tried to translate them into socket.io API documents in my native language. Three months ago, I finished the translation.

At first, I was just for the convenience of personal inquiry.

I originally only used it for my convenience. Recently I noticed that there are developers [star] and fork the [project] (https://github.com/veaba/socket.io-docs), although very few, but some users need This one.

So, I summon up my courage to ask, does the socket.io community need such a contribution of a Chinese document?

If you need it, please take it away and let it lower the threshold for developers to use Socket.IO.

I love socket. IO, which is one of the best open source projects.

Tips：This document is not perfect

Repo：https://github.com/veaba/socket.io-docs

--------------------------

（上面是英文是Google翻译的，(⊙o⊙)…）

我已经翻译完成socket.IO 中文文档。

因为找不到相关的中文文档，我尝试翻译为自己母语的socket.io API文档，三个月前，我已完成翻译。

我起初只是为了方便本人使用，最近我注意到有开发者在star 和 fork这个[项目](https://github.com/veaba/socket.io-docs)，虽然很少，但有部分用户需要这个。

所以，我鼓起勇气问下，socket.io 社区需要这样的一份socket.io中文文档的贡献吗？

如果有需要的话，请拿走，让它降低更多的开发者使用Socket.IO的门槛

我爱Socket.io，它是最棒的开源项目之一。

仓库地址：https://github.com/veaba/socket.io-docs

Tips：这个起初是个人小仓库，未能通过严格的翻译方式完成，期待专业的开发者参与完成。

**Comment by darrachequesne** [comment]
A bit late to the party, but thanks a lot for your awesome work on this :+1: 

For future readers:

I've started to translate the website to french, so if anyone has the time to translate it to another language, I'll be happy to merge it.

Documentation: https://docusaurus.io/docs/i18n/tutorial
Source: https://github.com/socketio/socket.io-website
