### ISSUE TITLE
Error running socket.io on nodeJS live server

### ISSUE THREAD

**Issue by marshalsoft** [socketio/socket.io#3498]
*The following error log was located*:
App 1021896 output: this.id = nsp.name !== '/' ? nsp.name + '#' + client.id : client.id;
App 1021896 output: ^
App 1021896 output:
App 1021896 output: TypeError: Cannot read property 'id' of undefined
App 1021896 output: at Socket (/home/mars/chats/node_modules/socket.io/lib/socket.js:64:55)
App 1021896 output: at Object. (/home/mars/chats/main.ts:9:43)
App 1021896 output: at Module._compile (module.js:577:32)
App 1021896 output: at Object.Module._extensions..js (module.js:586:10)
App 1021896 output: at Module.load (module.js:494:32)
App 1021896 output: at tryModuleLoad (module.js:453:12)
App 1021896 output: at Function.Module._load (module.js:445:3)
App 1021896 output: at Module.require (module.js:504:17)
App 1021896 output: at Module.require (/opt/passenger-5.3.7-4.el6.cloudlinux/src/helper-scripts/node-loader.js:80:25)
App 1021896 output: at require (internal/module.js:20:19)
[ E 2019-10-19 10:46:04.8393 936530/T4j age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/mars/chats: The application process exited prematurely.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
