### ISSUE TITLE
Cannot set headers after they are sent to the client, WITH MINIIFY REPRODUCE CODE

### ISSUE THREAD

**Issue by xieranmaya** [socketio/socket.io#3501]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*

### Steps to reproduce (if the current behaviour is a bug)
run this code on node:
everything is the newest version until today
```
var app = require('express')();
var http = require('http').createServer();
var io = require('socket.io')(http);
http.on('request', app)

app.get('/', function(req, res){

});

io.on('connection', function(socket){
  console.log('a user connected');
});

http.listen(3008, function(){
  console.log('listening on *:3000');
});
```
open http://localhost:3008/socket.io/socket.io.js in browser
node console will log 'Cannot set headers after they are sent to the client' error

**but if you SWITCH the line 3 and line 4, the error will not be shown and EVERYTHING IS OK.**

**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

should not throw the error

*What is expected?*

### Setup
- OS:
- browser:
- socket.io version:

**Comment by darrachequesne** [comment]
For future readers:

Please check https://socket.io/docs/v4/server-initialization/#with-express
