### ISSUE TITLE
Transport error io.socket.engineio.client.EngineIOException: xhr poll error

### ISSUE THREAD

**Issue by sid9890** [socketio/socket.io#3502]
iam trying to connect with android mobile some mobiles do proper connection but some gives this error
Transport error io.socket.engineio.client.EngineIOException: xhr poll error

**Comment by sid9890** [comment]
Add this line in manifest file 
<Application . . android:usesCleartextTraffic="true"> . . . <Application/>

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
