### ISSUE TITLE
get socket object by socket id

### ISSUE THREAD

**Issue by nh916** [socketio/socket.io#3504]
can we please implement a way to grab socket object easily by socket id. that would be very useful and would keep a lot of coding and slowing of a backend system than looping through every socket. thank you!

**Comment by Dj-jom2x** [comment]
its there you just had to read the docs.. scoket[socketid].yourObjHere...

**Comment by darrachequesne** [comment]
For future readers:

You can use the `fetchSockets` method:

```js
const sockets = await io.in(theSocketId).fetchSockets();
```

Please note that this function also works with multiple Socket.IO servers, hence the `await` operator.

Reference: https://socket.io/docs/v4/server-api/#server-fetchSockets
