### ISSUE TITLE
Get decompressed message size when perMessageDeflate is true

### ISSUE THREAD

**Issue by ChrisCAdsk** [socketio/socket.io#3505]
### I want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour

When `perMessageDeflate` is set to true on a socket.io server there's no way to get the total uncompressed byte size of received messages. If it's false, i.e. data is sent uncompressed, we can get total bytes transferred directly using `socket.conn.transport.socket.bytesReceived`.

There shouldn't be any reason why we can't get the uncompressed total bytes, this value is available during the zlib inflate process.
Total uncompressed transferred bytes are very useful when measuring throughput without having to do extra computation on the received socket message, for example:
```
socket.on('emit', (data, ackFunction) {
  const sizeOfData = JSON.stringify(data).length;
});
```
Measurements like these add CPU and memory overhead to servers.

**Comment by darrachequesne** [comment]
For future readers:

As far as I understand there is currently no way to do so, but we might be able to add a hook here: https://github.com/websockets/ws/blob/c82b08737fbe142dd910fc7e429399e23b95c6d6/lib/receiver.js#L450
