### ISSUE TITLE
"during WebSocket handshake: Unexpected response code: 200" with nginx location path match

### ISSUE THREAD

**Issue by qiulang** [socketio/socket.io#3508]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Nginx problem:
When I use `location / { ... }` it works well but if I use sub-path match, e.g. `location /admin { ... }` it stops working:

```
location /admin {
    alias   ...;
    index  index.html index.htm;
    try_files $uri $uri/ @websocket;
}

location @websocket {
    proxy_pass http://127.0.0.1:3000; 
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}

//change the socket.io code as well

//client code
socket = io({ transports: ['websocket'], path: '/admin' })
//server code
var io = require('socket.io')(http,{path: '/admin'})  //Actually I tried with or without path parameter

```

I got 200OK but "Error during WebSocket handshake: Unexpected response code: 200"

### Steps to reproduce (if the current behaviour is a bug)
Nginx location set subpath instead of just "/"

### Setup
- OS:  macOS 10.14
- browser:  78
- socket.io version: 2.3

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socket.io/docs/v3/reverse-proxy/#NginX
