### ISSUE TITLE
400 Handshake Error With Application Load Balancer AWS (Flask App)

### ISSUE THREAD

**Issue by ecda909** [socketio/socket.io#3510]
Getting a 400 handshake error on POST requests to my Flask app running socket.io, but I've added in the configs for NGINX according to docs and posts I read online. I'm using an Application Load Balancer in AWS and have set a :80 Target Group and a :443 listener which forwards to the Target Group. I have also added a rule for the route /socket.io to forward request to the target group on :80. I'm also using a Route53 domain name and enforcing SSL everything works fine except the socket. 

NGINX conf file:

`server {

    listen [::]:80;
    listen 80;

    server_name <domain_name>;
    access_log  /var/log/nginx/access.log;

    location / {
        proxy_pass http://127.0.0.1:8000;
        include proxy_params;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://127.0.0.1:8000;
    }
}`

And js file connection for socket.io:
`var socket = io();
  socket.on('connect', () => {
        console.log(socket.connected); // true
        });
`
Connection returns true.

**Comment by superway117** [comment]
what is the status of this issue? i have also encountered this problem

**Comment by superway117** [comment]
```
const client = io('https://io.yourhost.com', {  // WARNING: in that case, there is no fallback to long-polling  transports: [ 'websocket' ] // or [ 'websocket', 'polling' ], which is the same thing})
```
do we need the above code to fix  this problem?

**Comment by darrachequesne** [comment]
For future readers:

Please check https://socket.io/docs/v4/troubleshooting-connection-issues/

Please reopen if needed.
