### ISSUE TITLE
Question: Support and development golang implementation socket.io and go-engine.io

### ISSUE THREAD

**Issue by sshaplygin** [socketio/socket.io#3511]
Hi, everyone!
Do you wanna support and development implementation socket.io and engine.io in pure golang.
Link to [go-socket.io](https://github.com/googollee/go-socket.io) and link to [go-engine.io](https://github.com/googollee/go-engine.io)

**Comment by gzq0616** [comment]
yes, i want

**Comment by darrachequesne** [comment]
See https://github.com/socketio/socket.io/issues/3242
