### ISSUE TITLE
Unable to disconnect socket into ionic application.

### ISSUE THREAD

**Issue by krunal9421** [socketio/socket.io#3513]
I am not able to socket disconnect into ionic application. I have socket.on into the constructor of common page in providers. I want to disconnect socket into a function on the same file from where application logout is called.

But I am unable to disconnect the socket. I am multiple socket.on('event') on multiple emit into application.
Can anyone help me out?

Screenshot of code for reference:
https://i.stack.imgur.com/wrIEv.png

**Comment by radinmoradi** [comment]
Z6823

**Comment by krunal9421** [comment]
@radinmoradi  any update for me?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
