### ISSUE TITLE
socketio Upgrade header in post handshake requests blocked by Google Loadbalancers

### ISSUE THREAD

**Issue by ccjon** [socketio/socket.io#3515]
Google engineers told me that the reason our socketio connections were not working with the Google LoadBalancers is that the first request after protocol change contains an Upgrade http header which is not forwarded downstream. The docs specifically callout such requests as not handled. I don't know why... perhaps so that the LB can handled all the protocol switching:
https://cloud.google.com/load-balancing/docs/https/
"The load balancer blocks the request if any of the following are true: ...
...
The request contains an Upgrade header and the Upgrade header is not used to enable WebSocket connections.
....

This is a big issue for me since it means I have to create an alternative route for websocket traffic via apache which is a lot more maintenance.

Is there a good reason to have the Upgrade header in post handshake calls?

_Originally posted by @ccjon in https://github.com/socketio/socket.io/issues/3424#issuecomment-553151282_

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
