### ISSUE TITLE
socket io client side not working on host

### ISSUE THREAD

**Issue by mohamedale** [socketio/socket.io#3517]
I am using seocket io & elephant io & php
this code worked completely on localhost and no problem here, but when i upload this code to my hosting everything worked except (client side) it show message in a client file in console "polling-xhr.js:264 GET http://test.twodir.com:1337/socket.io/?EIO=3&transport=polling&t=Mv_kbSV net::ERR_CONNECTION_TIMED_OUT"
**server.js**
![image](https://user-images.githubusercontent.com/13859990/69078377-6f513880-0a40-11ea-8f95-3197f18932bf.png)

**elephant io**
![image](https://user-images.githubusercontent.com/13859990/69078632-ec7cad80-0a40-11ea-8329-ed35b27a295a.png)

**client.php**
![image](https://user-images.githubusercontent.com/13859990/69078676-08804f00-0a41-11ea-89ab-24e1cf207e33.png)

**terminal show message that received from elephant io**
![image](https://user-images.githubusercontent.com/13859990/69078731-29e13b00-0a41-11ea-8267-2d496e9df0c9.png)

**error on client side in console**
![image](https://user-images.githubusercontent.com/13859990/69078754-39f91a80-0a41-11ea-98e1-826a7ce9d6bf.png)

**Comment by dev-newton** [comment]
Good day, im having this same issue, how did u resolve it

**Comment by mohamedale** [comment]
This problem is because I tried to run Node JS on **shared hosting** and Node JS run only with (VPS hosting Cloud hosting or dedicated server). This is what Godaddy support told me... you can buy vps or dedicated server OR get free vps from amazon for one year .. After this Node JS should work without problems if there is no problem with the code

**Comment by darrachequesne** [comment]
For future readers:

Please check https://socket.io/docs/v4/troubleshooting-connection-issues/
