### ISSUE TITLE
How to get all socket ids in multiple processes？

### ISSUE THREAD

**Issue by jwentao** [socketio/socket.io#3522]
when use `socket.to('socketId').emit('an event', { some: 'data' })`,
I want to make sure this socketId is available,  use `connected` or `adapter.rooms` can only get socketIds in current process.
thanks.

**Comment by betterTry** [comment]
You may need a MQ like kafka or Pub/Sub system.

**Comment by darrachequesne** [comment]
For future readers: you can use the `allSockets()` method:

```js
// all sockets in the main namespace
const ids = await io.allSockets();

// all sockets in the main namespace and in the "user:1234" room
const ids = await io.in("user:1234").allSockets();

// all sockets in the "chat" namespace
const ids = await io.of("/chat").allSockets();

// all sockets in the "chat" namespace and in the "general" room
const ids = await io.of("/chat").in("general").allSockets();
```

Documentation: https://socket.io/docs/v3/server-api/#namespace-allSockets
