### ISSUE TITLE
namespace.emit can't be received in linux 

### ISSUE THREAD

**Issue by zy-zero** [socketio/socket.io#3523]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*

Now I use the socket io to send message:
![image](https://user-images.githubusercontent.com/23359848/69837565-66efcd80-128a-11ea-85eb-251a373edc5a.png)
![image](https://user-images.githubusercontent.com/23359848/69837582-825ad880-128a-11ea-86f9-7a09efa1221c.png)
It can be work in windows, and node js is 8.x, but can not work on linex.

client can receive message if server work in windows. but can not receive if server work in linux.

### Setup
- browser: chrome 78.0.3904.108
- socket.io version: 2.3.0

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
