### ISSUE TITLE
multitabs re-connection fail on firefox

### ISSUE THREAD

**Issue by Preciel** [socketio/socket.io#3525]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Multitabs re-connection on firefox fail when server restart if more than 8 tabs.
Clients re-connects, but can't emit and are disconnected by server aftar a few seconds

### Steps to reproduce (if the current behaviour is a bug)

1) Run node server
2) Connect 8+ tabs with firefox
3) Stop node server and restart after a few seconds

### Expected behaviour

All clients from multitabs reconnects successfully

### Setup

- OS: Windows 10
- browser: Firefox 71, Firefox 72 (Dev edition)
- socket.io version: 2.3.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

[Partial fix]:
Close socket on `connect_error` and try to reconnect later.
While some will fail in the process, more clients will be able to reconnect after some time
```javascript
socket.on("connect_error", function(error) {
    socket.close();
    setTimeout(function() {
        socket.open();
    }, Math.random() * (10000 - 5000) + 5000);
})
```

**Comment by radinmoradi** [comment]
در تاریخ جمعه ۶ دسامبر ۲۰۱۹،‏ ۲۲:۵۲ Preciel <notifications@github.com> نوشت:

**Comment by darrachequesne** [comment]
For future readers:

I could indeed reproduce the odd behavior: for some tabs, the socket reconnects right after the disconnection, for others, the first reconnection attempt fails after 20s (the connection delay), and then succeeds. And in some rare cases, the socket is stuck in HTTP long-polling.

I don't think this is something we can fix though, so I guess we can close this. Please reopen if needed.
