### ISSUE TITLE
client not connected w/o any errors

### ISSUE THREAD

**Issue by salkat** [socketio/socket.io#3526]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*

server:
```
var https = require('https');

var ssl_options = {
    key: fs.readFileSync('privkey.pem'),
    cert: fs.readFileSync('cert.pem'),
    requestCert: false,
    rejectUnauthorized: true
}
var httpsServer = https.createServer(ssl_options, app);
httpsServer.listen(port, onListening);
const io = require('socket.io')(httpsServer);
io.on('connection', (socket) => {
    console.log ('client connected');
}
```
It works ok.

Client 1: SPA in browser
```
import * as io from "socket.io-client";
socket = io(`wss://${server}:${port}`, { transports: ["websocket"] });
socket.on("connect", event => {
        console.log ('connected');
}

```
It works ok too

Client 2: node.js application on the same server
```
const io = require('socket.io-client');
socket = io.connect(`wss://localhost:${port}`, { transports: ["websocket"], reconnect: true });
socket.open();
socket.on ('connect', onSocketConnected);
socket.on ('error', onSocketError);
socket.on ('connect_error', onSocketError);
socket.on ('connect_timeout', onSocketError);
socket.on ('reconnect', onSocketError);
socket.on ('reconnecting', onSocketError);
socket.on ('reconnect_attempt', onSocketError);
socket.on ('reconnect_error', onSocketError);
socket.on ('reconnect_failed', onSocketError);

const onSocketConnected = (event) => {
    common.log ('socket connected', event);
}

const onSocketError = (event) => {
    common.log ('socket error', event);
}
```

### Steps to reproduce (if the current behaviour is a bug)

No connections. No errors. Just nothing happens. Server does not show any connection attempts

I've tried `https `instead of `wss `with no difference. With or without `transports: ["websocket"]` again with difference. Ip instead of localhost with no difference

### Expected behaviour

Connection or error

### Setup
- OS: Debian 9
- browser: node.js
- socket.io version: latest

**Comment by eltharynd** [comment]
I'm pretty sure it's because you're using `wss://` instead of `https://`...

I might be mistaken but if i understand socket-io correctly it uses http(s) to estabilish a connection even if it thenswitches to ws(s) so it's trying to communicate with the wrong protocol

**Comment by darrachequesne** [comment]
For future readers: I think this is due to the SSL certificate, you need to add it on the client-side:

```js
const fs = require("fs");
const socket = require("socket.io-client")("https://example.com", {
  ca: fs.readFileSync("./cert.pem")
});
```

Documentation: https://socket.io/docs/v3/client-initialization/#Node-js-specific-options

@eltharynd you can use either `wss` or `https`

Documentation: https://socket.io/docs/v3/client-initialization/#From-a-different-domain
