### ISSUE TITLE
Can't emit undefined and null values to socket client (stripped by parser).

### ISSUE THREAD

**Issue by wizzfizz94** [socketio/socket.io#3527]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

[See here](https://stackoverflow.com/questions/57722814/how-to-emit-undefined-null-value-to-client-with-socket-io)

I'm not sure if this is a bug or a design decision but its limits the ability to dynamically process null/undefined properties. eg:
```
// in browser
socket.on("Data", function (data) {
 for (var key in data) {
  if (data[key] == null) {
   unset(key); 
  }
 }
});
```

**Comment by darrachequesne** [comment]
For future readers: this is an expected behavior, as the default parser uses `JSON.stringify()` to marshall the payload.

Source: https://github.com/socketio/socket.io-parser/blob/4.0.4/lib/index.ts#L87-L89

As a workaround, you can provide your own parser: https://socket.io/docs/v3/custom-parser/
