### ISSUE TITLE
React SPA + Express Socket.on() not work

### ISSUE THREAD

**Issue by IDONTSUDO** [socketio/socket.io#3531]
### You want to:

* [x] report a *bug*

### Current behaviour

The socket is connecting. And does not reproduce events. And to be more precise, it only reproduces the trip event.

*What is actually happening?*

I expect logging when connecting. But the socket just plugs in. And after that, it does not go about other events at all.
### Steps to reproduce (if the current behaviour is a bug)
I am ready to throw the code. Or you can copy my repository. To make sure his ability is not working.

### Expected behaviour
I expect socket.on () events to be visible to the server.
### Setup
Ubuntu 18.04

- chrome last version:
- socket.io version:
 "socket.io-client": "^2.3.0",
 "socket.io": "^2.3.0",

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
If you ask, I can throw stacktraces.

**Comment by manosriram** [comment]
Can you post that code piece ?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
