### ISSUE TITLE
NodeJs does not exit on server closed during 'connection' event, if middleware is present

### ISSUE THREAD

**Issue by BAKFR** [socketio/socket.io#3535]
# You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

When using a middleware and closing the server during a 'connection' event, the server does not close immediately. The 'close' event is emitted, but the nodejs process exits only after a timeout of a few minutes.

This behavior only appear when both conditions are set:
- a middleware has been set using `socket.use()`.
- the server is closed during a `connection` event, or shortly after.
  During my tests, using `server.close()` on a setTimeout of 10ms triggers the bug, but a setTimeout of 500ms does not.

### Steps to reproduce

Running the following scripts at the same time (server.js then client.js)

`client.js`
```js
let WsClient = require('socket.io-client').Manager;

let client = new WsClient('http://localhost:9999', {autoConnect: false});
client.on('close', () => console.log('client event: close'));

client.connect(err => {
  if (err) {
    console.log('error', err);
    process.exit(1);
  }
  console.log('client has been connected');
  client.close();
});
```

`server.js`
```js
let server = require('socket.io')();
server.use((socket, next) => next());

server.on('connection', () => console.log('server event: connection'));
server.on('close', () => console.log('server event: close'));
server.listen(9999);

console.log('Wait for connection ...');
server.once('connection', () => {
  console.log('client has been connected');
  console.log('will close server now ...');
  server.close(() => {
    console.log('server closed!');
  });
});
```

The server.js result is:
```
Wait for connection ...
server event: connection
client has been connected
will close server now ...
server closed!
```
Then, the script wait a few minutes before exiting.

### Expected behaviour

NodeJs should exit instantly after the "server closed!" message.

### Setup
- OS: Linux
- NodeJs: v12.14.1
- Socket.io: 2.3.0
- Socket.io-client: 2.3.0

**Comment by darrachequesne** [comment]
That should be fixed in latest version, please reopen if needed.
