### ISSUE TITLE
question about Socket.id and status (关于状态)

### ISSUE THREAD

**Issue by bln7** [socketio/socket.io#3536]
1. How do I get a user's online status? (怎么获取一个用户的在线状态？)
2. How to get whether a message is sent successfully? (怎么获取一条信息是否发送成功？)

**Comment by darrachequesne** [comment]
For future readers:

1. you can use the `socket.connected` attribute: https://socket.io/docs/v3/client-socket-instance/#Socket-connected
2. you can use acknowledgements: https://socket.io/docs/v3/emitting-events/#Acknowledgements
