### ISSUE TITLE
Initial Browser Load - Not Including IO cookie

### ISSUE THREAD

**Issue by james-ingold** [socketio/socket.io#3544]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Testing in BrowserStack and locally. On the first browser load, the io cookie is not available in the socket handshake or request. This happens in IE11, Chrome 79, Firefox 71, and Safari 13
```
io.on('connection', socket => {
    console.log(`socket handshake is ${JSON.stringify(socket.handshake.headers)}`)
    console.log(`socket request is ${JSON.stringify(socket.request.headers)}`)
```

io cookie not available in headers
`   { headers:
      { host: 'localhost:50000',
        origin: 'http://localhost:8000',
        connection: 'keep-alive',
        accept: '*/*',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15',
        'accept-language': 'en-us',
        referer: 'http://localhost:8000/',
        'accept-encoding': 'gzip, deflate' },`

Reload the site: 
io cookie available in headers
`   { headers:
      { host: 'localhost:50000',
        origin: 'http://localhost:8000',
        cookie: 'io=Zbpbc_eg8SWntiXaAAAA',
        connection: 'keep-alive',
        accept: '*/*',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15',
        'accept-language': 'en-us',
        referer: 'http://localhost:8000/',
        'accept-encoding': 'gzip, deflate' },`

### Steps to reproduce (if the current behaviour is a bug)

Safari v13.0.4-locally
Pull down this example repo => https://github.com/devjin0617/nodejs-socket.io-chat-example.git
Close Safari
Open Safari
Add a line on the server connection to log out the headers as seen above
Go to localhost:8000
Cookie header will not be available 
Reload the page
Cookie header will be available

### Expected behaviour

Cookie header should be available on the first load of a new browser session

### Setup
- OS: macOS
- browser: Safari 13.0.4
- socket.io version: 2.3.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

Poking around in the socket.io code, if I listen for the headers event, it looks like Set-Cookie is on there
```
io.use((socket, next) => {
    socket.conn.transport.once('headers', (headers) => {
      console.log(headers)
      next()
    })
  })
```

```
{ 'Content-Type': 'text/plain; charset=UTF-8',
  'Content-Length': 3,
  'Access-Control-Allow-Origin': '*',
  'X-XSS-Protection': '0',
  'Set-Cookie': 'io=eOCIZrWR52q0WAy7AAAA; Path=/' }
```

But no cookie in headers 
`socket handshake is {"accept":"*/*","accept-language":"en-US","accept-encoding":"gzip, deflate","user
-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko","host":"localhost:8000","connection":"keep-alive"}`

**Comment by gotheer** [comment]
In the first load of the browser, socket.io just upgrades the connection from HTTP to Websocket when it's possible.

**Comment by darrachequesne** [comment]
For future readers: this is an expected behavior, as the `headers` value contains the headers of the initial request (when the "io" cookie is not set yet).

Documentation: https://socket.io/docs/v3/server-socket-instance/#Socket-handshake

Please reopen if needed.
