### ISSUE TITLE
Overriding generateId

### ISSUE THREAD

**Issue by hqntrt** [socketio/socket.io#3545]
Using socketio over cdn, and setting it up as
`let socket = io();

socket.io.engine.generateId = () => {
    return "something...";
}`

id that has been generated shows up in client side but it doesn't match with the server side. Any suggestions?

**Comment by darrachequesne** [comment]
For future readers: the `generateId` method is found on the server-side.

```js
const uuid = require("uuid");

io.engine.generateId = (req) => {
  return uuid.v4(); // must be unique across all Socket.IO servers
}
```

Documentation: https://socket.io/docs/v3/server-instance/#Server-engine
