### ISSUE TITLE
React native sometimes no data transmission problem

### ISSUE THREAD

**Issue by mertbuldur** [socketio/socket.io#3547]
In my react native project, sometimes the link is not transmitted and does not fall to app.js
i am using this code 
`const socket = io.connect(SOCKET_URL, {
    'reconnection': true,
    'reconnectionDelay': 500,
    'reconnectionAttempts': Infinity,
    transports: ['websocket']

});`
and than 
`  componentDidMount = async () => {
socket.on('call_receiver', (data)=>{
console.log(data);
}
}
`

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
