### ISSUE TITLE
Official events from server when client is joined to a room.

### ISSUE THREAD

**Issue by Milad** [socketio/socket.io#3548]
### You want to:

* [] report a *bug*
* [x] request a *feature*

### Current behaviour

Nothing

### Expected behaviour

Emit an event from server when client is joined to a room.

**Comment by Edeph** [comment]
You can do this yourself by broadcasting this when a user joins a room `socket.to('myRoom').emit('user joined', "User Milad joined the room!");`

You can use [this cheatsheet](https://socket.io/docs/emit-cheatsheet/) to see other interactions that you can do with the room.
