### ISSUE TITLE
how to broadcast a message to ALL connected clients

### ISSUE THREAD

**Issue by mariomuja** [socketio/socket.io#3551]
Hi, 
when something happens in the server app, an event shall be broadcasted to all clients. 

How can this be achieved?

The example at 

https://socket.io/docs/#Broadcasting-messages

comes with the sentence 

"Broadcasting means sending a message to everyone else **except for the socket that starts it**."

How can I send a message to **ALL** connected clients, when something happens in the server application?

Thanks for your help,
Mario

**Comment by firelort** [comment]
Hi Mario,

not sure if it helps, but socket.io provided this cheatsheet: https://socket.io/docs/emit-cheatsheet/
I guess "io.emit('event', 'an event sent to all connected clients');" would be perfectly fine.

Kind regards,
Robert

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socket.io/docs/v3/broadcasting-events/
