### ISSUE TITLE
Memory leak - sockets listeners never getting released

### ISSUE THREAD

**Issue by eltharynd** [socketio/socket.io#3553]
### You want to:

* report a *bug* (possibly)

### Current behaviour

If you follow the [documentation](https://socket.io/get-started/chat) sockets never get released..

If you try conencting a bunch of clients the heap usage climbs... when they disconnect it doesn't go down (actually increases slightly)

Calling Garbace collector manually clears some of the heap but not all...

### Steps to reproduce (if the current behaviour is a bug)

Follow the [documentation ](https://socket.io/get-started/chat)and add an interval which lists the heap usage and some way to call a garbage collector like this
`setInterval(() => {
    var heapUsed = process.memoryUsage().heapUsed;
    console.log(heapUsed / 1024 / 1024)
}, 2000)`

`        this.app.get('/_ah/garbage_collection', async(req, res) => {
            var heapUsed = process.memoryUsage().heapUsed;
            let before = 'GC --- Program is using ' + heapUsed + ' bytes of Heap before garbage collection.'
            global.gc()
            heapUsed = process.memoryUsage().heapUsed;
            let after = 'GC --- Program is using ' + heapUsed + ' bytes of Heap after garbage collection.'
            console.log(before);
            console.log(after);
            res.send({before: before, after: after})
        })`

### Expected behaviour

when a client disconnects memory is released from heap

### Setup
- socket.io version: ^2.3.0

used with express on a basic config

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

I fixed it like this but a under the hood implementation could be implemented
`socket.on('disconnect', (data) => {
                socket.removeAllListeners()
            })`

Unless there's a reason for that

After almost 24 hours of live cluster running i can confirm the memory usage is finally stable with the above line.
If you don't consider this a bug it would still be nice to have it included in the docs...

Also beware, if you found "my" fix somewhere else it was actually slightly different `socket.on('disconnect', (socket) => {})`
socket instead of data but the lsitener is assigned inside the socket handler so the lamba parameter is not the socket itself but the usual data you get with events (in this case just a string saying 'conenction closed' or something... so if you try to address socket.removeAllListeners() it obviusly won't work

**Comment by ArmanNisch** [comment]
Hi @eltharynd I can confirm the behaviour you describe. Implementing your "fix" on a 1:1 basis however did not fix my issue. Do I need to pass `data` in as an argument? and if yes, what exactly does data represent?

**Comment by eltharynd** [comment]
data is just an info string on my case.. the problem with having socket is that it overrides the scope of socket itself so instead of removing all listeners from the socket it tried to remove them from the string

**Comment by rhpijnacker** [comment]
Same problem here.
Tried to unsubscribe by iterating over the event names, then over the listeners per event name. Even though after that it says there are no more listeners, when I connect again I see the callback being invoked 2 times, increasing every time I reconnect.

**Comment by darrachequesne** [comment]
For future readers:

I was not able to reproduce the issue.

Node version: `v16.13.1`
Socket.IO version: `v4.4.1`

I used the scripts from https://github.com/socketio/socket.io-benchmarks, here is the graph with 10 000 clients:

![Screenshot from 2022-03-31 23-36-43](https://user-images.githubusercontent.com/13031701/161155715-68f13a91-c337-4169-b6bc-4448d2e3c15c.png)

Please reopen if needed.
