### ISSUE TITLE
Served socket.io client does not find client installed in own node_modules

### ISSUE THREAD

**Issue by Apollon77** [socketio/socket.io#3555]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Sometimes other socket.io-client files are served, pot. very old and so incompatible versions.

### Steps to reproduce (if the current behaviour is a bug)

When it happens that e.g. an other version of socket.io-client is installed in the "root" node_modues and so the socket.io dependencies are installed in it own node_modules the current code logic in https://github.com/socketio/socket.io/blob/master/lib/index.js#L109 will not be able to find it because it only searches "to the top".
It will never find a client installed in node-modules/socket.io/node_modules/socket.io-client/... when there is a client package existing in npm structure „more above“

### Expected behaviour

Find the correct version, so start searching on it's own node_modules. I woud completely switch to use requirer.resolve

### Setup
- OS: irrelevant
- browser: multipe/irrelevant
- socket.io version: 2.3.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

Idea for fix: see "Steps to reproduce". 

I could also provide a PR if it has a chance to be adopted.

**Comment by darrachequesne** [comment]
For future readers: this was fixed by https://github.com/socketio/socket.io/commit/7603da71a535481e3fc60e38b013abf78516d322, included in `socket.io@3.0.0`.
