### ISSUE TITLE
How to run socket more time

### ISSUE THREAD

**Issue by Filz0** [socketio/socket.io#3556]
Hi,
I have an issue with my server program in Android Studio(Java). I'm trying to open a socket and send a message to the client.The first time is fine but when the main thread run the connection thread another time, the connection is established but i cant send message more. Now i've searched this problem and i think that the problem is the TCP port because i can't reuse it but i have to wait some minutes....What do you think? i did not try this solution because i want to be sure.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
