### ISSUE TITLE
The RSS memory increase and never released when heapUsed/heapTotal does not

### ISSUE THREAD

**Issue by AlePurga** [socketio/socket.io#3558]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*In linux, with [simple-socket.txt](https://github.com/socketio/socket.io/files/4263231/simple-socket.txt) application, I noticed that RSS memory is growing during client connection and never decrease once the clients are disconnected also if heapUsed/heapTotal is released normally.*

*In windows server all is working fine.*

*There is something that I'm done wrongly?*

### Expected behaviour

*The RSS memory returns to initial values*

### Steps to reproduce (if the current behaviour is a bug)

1. Run the application
2. Connect 2500 client
3. Disconnect them

### Setup
- OS: Red Hat Enterprise Linux Server release 6.9 (Santiago)
- client: Jmeter 
- socket.io version: 2.3.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
Excerpt of memory usage during 2500 client connection and disconnection
RSS: 37.46 MB; Heap Used: 13.45 MB; Heap Total: 18.18 MB; Externa: 13.82 MB;
RSS: 43 MB; Heap Used: 12.56 MB; Heap Total: 20.14 MB; Externa: 25.37 MB;
RSS: 49.99 MB; Heap Used: 14.08 MB; Heap Total: 21.14 MB; Externa: 36.93 MB;
RSS: 57.28 MB; Heap Used: 16.73 MB; Heap Total: 25.64 MB; Externa: 48.49 MB;
RSS: 66.02 MB; Heap Used: 17.09 MB; Heap Total: 35.64 MB; Externa: 60.03 MB;
RSS: 73.07 MB; Heap Used: 19.63 MB; Heap Total: 35.64 MB; Externa: 71.71 MB;
RSS: 80.44 MB; Heap Used: 19.58 MB; Heap Total: 38.64 MB; Externa: 83.26 MB;
RSS: 88.3 MB; Heap Used: 21.72 MB; Heap Total: 39.64 MB; Externa: 94.82 MB;
RSS: 95.8 MB; Heap Used: 23.64 MB; Heap Total: 57.14 MB; Externa: 106.38 MB;
RSS: 104.22 MB; Heap Used: 25.36 MB; Heap Total: 58.64 MB; Externa: 117.94 MB;
RSS: 111.16 MB; Heap Used: 27.22 MB; Heap Total: 60.14 MB; Externa: 129.61 MB;
RSS: 119.64 MB; Heap Used: 26.36 MB; Heap Total: 63.64 MB; Externa: 141.15 MB;
RSS: 127.21 MB; Heap Used: 29.13 MB; Heap Total: 65.14 MB; Externa: 152.72 MB;
RSS: 134.76 MB; Heap Used: 34.79 MB; Heap Total: 65.14 MB; Externa: 164.31 MB;
RSS: 131.12 MB; Heap Used: 30.98 MB; Heap Total: 38.64 MB; Externa: 175.83 MB;
RSS: 140.84 MB; Heap Used: 32.46 MB; Heap Total: 45.14 MB; Externa: 187.51 MB;
RSS: 150.52 MB; Heap Used: 33.57 MB; Heap Total: 54.64 MB; Externa: 199.08 MB;
RSS: 158.61 MB; Heap Used: 39.79 MB; Heap Total: 54.64 MB; Externa: 210.68 MB;
RSS: 165.04 MB; Heap Used: 40.09 MB; Heap Total: 56.64 MB; Externa: 222.23 MB;
RSS: 175.37 MB; Heap Used: 42.46 MB; Heap Total: 57.14 MB; Externa: 233.8 MB;
RSS: 183.31 MB; Heap Used: 39.42 MB; Heap Total: 75.14 MB; Externa: 245.38 MB;
RSS: 190.82 MB; Heap Used: 46.36 MB; Heap Total: 75.14 MB; Externa: 257.05 MB;
RSS: 204.41 MB; Heap Used: 41.86 MB; Heap Total: 79.14 MB; Externa: 268.58 MB;
RSS: 210.61 MB; Heap Used: 44.58 MB; Heap Total: 79.64 MB; Externa: 277.93 MB;
RSS: 210.66 MB; Heap Used: 48.79 MB; Heap Total: 79.64 MB; Externa: 277.96 MB;
RSS: 189.12 MB; Heap Used: 43.87 MB; Heap Total: 51.64 MB; Externa: 277.94 MB;
RSS: 192.56 MB; Heap Used: 44.75 MB; Heap Total: 52.64 MB; Externa: 277.95 MB;
RSS: 194.53 MB; Heap Used: 47.87 MB; Heap Total: 57.14 MB; Externa: 277.98 MB;
RSS: 195.45 MB; Heap Used: 46.51 MB; Heap Total: 58.64 MB; Externa: 277.97 MB;
RSS: 195.45 MB; Heap Used: 46.52 MB; Heap Total: 58.64 MB; Externa: 277.97 MB;
RSS: 195.45 MB; Heap Used: 46.52 MB; Heap Total: 58.64 MB; Externa: 277.97 MB;
RSS: 200.1 MB; Heap Used: 51.28 MB; Heap Total: 58.64 MB; Externa: 0.62 MB;
RSS: 155.34 MB; Heap Used: 9.45 MB; Heap Total: 15.14 MB; Externa: 0.08 MB;
RSS: 155.36 MB; Heap Used: 9.41 MB; Heap Total: 14.64 MB; Externa: 0.08 MB;
RSS: 163.45 MB; Heap Used: 9.41 MB; Heap Total: 14.64 MB; Externa: 0.08 MB;
RSS: 163.45 MB; Heap Used: 9.41 MB; Heap Total: 14.64 MB; Externa: 0.08 MB;
RSS: 169.35 MB; Heap Used: 9.42 MB; Heap Total: 14.64 MB; Externa: 0.08 MB;
RSS: 169.35 MB; Heap Used: 9.42 MB; Heap Total: 14.64 MB; Externa: 0.08 MB;

I tried also to analyze the dump, but it shows only information about the heap so I cannot know which objects are still in RSS memory.

**Comment by eltharynd** [comment]
ehi.. not a fix but a workaround https://github.com/socketio/socket.io/issues/3553

**Comment by AlePurga** [comment]
Already tried, but doesn't solve. The usage of heap has been improved, but the RSS don't want to go down

**Comment by eltharynd** [comment]
Yeah i just checked and you are right I'm also experiencing this.. i just havn't noticed because the effect is small enough not to make my backend go nuts

**Comment by radinmoradi** [comment]
در تاریخ پنجشنبه ۲۷ فوریهٔ ۲۰۲۰،‏ ۲۱:۴۸ Alessio Purgatori <
notifications@github.com> نوشت:

**Comment by alin1771** [comment]
I have the same issue and I am not using socket.io at all but its engine directly. The 'ws' library.
It keeps a lot of Socket objects as active handles.
process._getActiveHandles()
I am currently using websocket, it also has a memory leak but increase a bit slower

**Comment by RosenTomov** [comment]
Try the following:
- Set "perMessageDeflate: false" in the socket options (will be off by default in socket.io v3.0);
- Install jemalloc (memory allocator) and add LD_PRELOAD env. variable for your app 
`LD_PRELOAD=/usr/lib/libjemalloc.so` (path might be different);


Here's how I install jemalloc for AWS:
```
{
  "schemaVersion": "2.2",
  "description": "Install jemalloc",
  "mainSteps": [
    {
      "action": "aws:runShellScript",
      "name": "example",
      "inputs": {
        "runCommand": [
          "rm -rf jemalloc-5.2.1*",
          "wget https://github.com/jemalloc/jemalloc/releases/download/5.2.1/jemalloc-5.2.1.tar.bz2",
          "bunzip2 jemalloc-5.2.1.tar.bz2",
          "tar xvf jemalloc-5.2.1.tar",
          "cd jemalloc-5.2.1",
          "./configure --prefix=/usr > o.cf 2> e.cf",
          "make -j4 > o.m 2> e.m",
          "sudo make install",
          "sudo find / -name \"*jemalloc*\""
        ]
      }
    }
  ]
}
```

Last command is used to easily find the path.
Depending on your distro, your package manager might have access to the newest version (5.2.1).

**Comment by darrachequesne** [comment]
For future readers:

I was not able to reproduce the issue.

Node version: `v16.13.1`
Socket.IO version: `v4.4.1`

I used the scripts from https://github.com/socketio/socket.io-benchmarks, here is the graph with 10 000 clients:

![Screenshot from 2022-03-31 23-36-43](https://user-images.githubusercontent.com/13031701/161155715-68f13a91-c337-4169-b6bc-4448d2e3c15c.png)

Please reopen if needed.

**Comment by sheerryy** [comment]
@darrachequesne Here is a minimal code example to reproduce memory leaks in `socket.io: v4.7.4` and `Node: v18.17.1`. 

```js
const express = require('express');
const http = require('http');
const { Server } = require("socket.io");

const app = express();
const server = http.createServer(app);
const io = new Server(server, {transports: ['websocket']});

const fee = io.of(`memory-leak`)

server.listen(3000, () => {
    console.log((new Date()), 'listening on *:3000');
});

fee.use((socket, next) => {
    console.log((new Date()), 'Socket connected!', { id: socket.id })
    next()
})

fee.on('connection', (socket) => {
    socket.on('disconnect', (reason) => {
        console.log((new Date()), 'Socket Disconnected!', { id: socket.id, reason })
    })

    socket.on('test', () => {
        console.log((new Date()), `Event by ${socket.id}`)
        try {
            for (let i = 0; i < 100000; i++) {
                socket.emit('leaks', { ping: 'pong' })
            }
        } catch (error) {
            socket.disconnect(true)
        }
    })
})

setInterval(function(){
    logMemory();
}, 10000);

function logMemory() {
    var memory = process.memoryUsage();
    console.log((new Date()), 'RSS ',memory.rss, ', Heap Used ', memory.heapUsed, ' Heap Total ', memory.heapTotal);
}
```

Logs
```logs
2024-03-07T20:01:40.406Z listening on *:3000
2024-03-07T20:01:50.408Z RSS  61718528 , Heap Used  10491376  Heap Total  12713984
2024-03-07T20:02:00.408Z RSS  61964288 , Heap Used  10530232  Heap Total  12713984
2024-03-07T20:02:04.134Z Socket connected! { id: 'UnTlJVTg9c2HxNURAAAB' }
2024-03-07T20:02:10.409Z RSS  62341120 , Heap Used  10944016  Heap Total  12713984
2024-03-07T20:02:15.789Z Event by UnTlJVTg9c2HxNURAAAB
2024-03-07T20:02:20.409Z RSS  234930176 , Heap Used  134080096  Heap Total  165953536
2024-03-07T20:02:28.806Z Socket Disconnected! { id: 'UnTlJVTg9c2HxNURAAAB', reason: 'client namespace disconnect' }
2024-03-07T20:02:30.411Z RSS  81657856 , Heap Used  10837688  Heap Total  13238272
2024-03-07T20:02:40.411Z RSS  81690624 , Heap Used  10859304  Heap Total  13238272
2024-03-07T20:02:50.411Z RSS  81707008 , Heap Used  10875264  Heap Total  13238272
2024-03-07T20:03:00.411Z RSS  81723392 , Heap Used  10891120  Heap Total  13238272

```

I was able to reproduce the issue consistently. If you encounter any problems, try sending multiple events and closing the socket before the emit loop. The server clears the memory in about 15 minutes.

**Comment by darrachequesne** [comment]
@sheerryy 

> The server clears the memory in about 15 minutes.

If that's the case, then this is not a leak. The OS is free to reclaim the memory when it deems it necessary.

**Comment by sheerryy** [comment]
> If that's the case, then this is not a leak. The OS is free to reclaim the memory when it deems it necessary.

There is still some small memory that is never claimed.

**Comment by darrachequesne** [comment]
@sheerryy were you able to pinpoint the issue? Could you please provide a heapdump, in order to identify the leaking objects?
