### ISSUE TITLE
The 'Getting Started' on socket.io website doesn't work with latest version

### ISSUE THREAD

**Issue by achuthrajula** [socketio/socket.io#3559]
### You want to:

* [x] report a *bug*

*What is actually happening?*
Basic implementation of socket doesn't work with socket 2.0

### Steps to reproduce (if the current behaviour is a bug)
Follow the 'Get Started' section on https://socket.io/get-started/chat/ with latest version of socket

**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

*What is expected?*
Fix the latest version work as in 'Get Started'

### Setup
- OS: Manjaro Linux
- browser: Firefox Developer Edition
- socket.io version: "^2.3.0"

**Comment by kenklin** [comment]
I encountered this as well.  If you use devtools, you'll see it spinning with ...
```
?EIO=3&transport=polling
```

I searched and found https://github.com/miguelgrinberg/Flask-SocketIO/issues/219 which is marked as closed.

To resolve, I forced index.html to use websockets by passing this [option](https://socket.io/docs/client-api/#With-websocket-transport-only) to io() ...
```
const options = {transports: ["websocket"]};
var socket = io(options);
```

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
