### ISSUE TITLE
Not able to receive data from server on io.emit

### ISSUE THREAD

**Issue by vijhhh2** [socketio/socket.io#3561]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Not able to receive data from the socket server only in the browsers.
When I create a simple js file, connect to the socket serve and run the js file the data from the server getting logged. 

### Steps to reproduce (if the current behaviour is a bug)
create a socket io server create an emit event in the server.
In client (Angular 9) connect to socket server and listen to the event
### Expected behaviour
Whenever socket server emits data client (Angular 9) should receive it.

### Setup
- OS: Wnidows 10
- browser: chrome, edge
- socket.io-client version: 2.3.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
The worst thing is I am not getting any errors at all

**Comment by kinshuksri25** [comment]
Hi, I am getting the same issue, were you able to resolve yours??

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
