### ISSUE TITLE
Room isn't recreated after one user leaves and rejoins inmediately.

### ISSUE THREAD

**Issue by AoDev** [socketio/socket.io#3562]
### You want to:

* [x] report a *bug*

### Current behaviour

I have users joining rooms that are dynamically created. Each user can only be in one room at a time. The way that socketio works, as far as I understand is: 
- that a room is created once the first member (socket) joins. 
- a room is deleted once it's empty. (The last member leaves).

I have an issue where it's possible that there is a single user in a room and this user quickly asks to leave and rejoin the same room. What happens is that the room is deleted automatically because it becomes empty, but then, the room isn't recreated once the user joins again. (see code)

```js
    socket.on('viewRoom', (roomId) => {
      // User is allowed to be only in one room at a time
      // viewingRoomId tracks the current user room
      socket.leave('room-' + session.viewingRoomId)
      session.viewingRoomId = roomId
      socket.join('room-' + roomId)
    })
```
My guess is that it looks like the room deletion happens after the room creation in this case and so the room isn't recreated and the socket is never added to the new room. Maybe it is async?

Now, I have solved this issue with a small code change:

```js
    socket.on('viewRoom', (roomId) => {
      if (session.viewingRoomId !== roomId) { // <----
        socket.leave('room-' + session.viewingRoomId)
        session.viewingRoomId = roomId
        socket.join('room-' + roomId)
      }
    })
```

**But**: I still think there is an unexpected behaviour or bug here.

I log the existing rooms with this code:
`console.log(Object.keys(this.io.sockets.adapter.rooms).map((key) => key))`

And I can see how the room exists when user joins and then disappear once it tries to join it again.

### Expected behaviour

In the case where there is a single socket in a room and it leaves and rejoins immediately, the end result should be that the room still exists and the socket is in it.

### Setup
- OS: **local: OSX | Production: Heroku NodeJS v12.13.0 (LTS)** 
- browser: **tested in Brave | Firefox** (probably not relevant)
- socket.io version: `"socket.io": "2.3.0"`

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

I haven't dived into socketio code but maybe check if room deletion is asynchronous? That would explain this issue.

**Comment by bnol** [comment]
I think it's because `socket.join` and `socket.leave` are asynchronous functions, so you must provide a callback to make sure they're executed in order.
ref: https://socket.io/docs/rooms-and-namespaces/#Joining-and-leaving
```
socket.leave('room-' + session.viewingRoomId, () => {
  // Left room
  session.viewingRoomId = roomId
  socket.join('room-' + roomId)
});
```

**Comment by AoDev** [comment]
@bnol Thanks for confirming they are asynchronous. It's true that the code you showed should work because I have the particular situation where it's a "switch" between two rooms. But people don't necessarily have this case. I still think this is unwanted behaviour.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
