### ISSUE TITLE
Socket.io sends broken stream

### ISSUE THREAD

**Issue by ycatbink0t** [socketio/socket.io#3563]
#3557 # You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*
Data sended by socket.io to socket.io-client is broken.
![image](https://user-images.githubusercontent.com/50693692/76311854-801d0700-62da-11ea-9883-14ba456331ee.png)
Headers: 
![image](https://user-images.githubusercontent.com/50693692/76311892-90cd7d00-62da-11ea-852d-ac301bac5ecf.png)

server code:  `socket.emit('method_call_client', {data: 'connected'});`

I use nginx and proxy request to node.js
config:
        location /socket.io {
                proxy_pass https://127.0.0.1:8090;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header X-Real-IP  $remote_addr;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header X-Forwarded-Proto https;
        }

### Expected behaviour

*What is expected?* Normal data, not broken stream.

### Setup
- OS: Linux
- browser: Chrome
- socket.io version: 2.3.0 - server and client

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

I have found only one similar problem in internet with no suggetion how to fix it.
Link: https://forum.magicmirror.builders/topic/1024/mmm-wunderlist-invalid-namespace-error/4

**Comment by ycatbink0t** [comment]
Solved.
The problem was domain update on client.
Before update it was `https://domain.com`
After update: `https://domain/com/api`
As a result io.client tried to enter namespace 'api'. But I haven't register it.

**Comment by radinmoradi** [comment]
س
