### ISSUE TITLE
socket.io connection event is getting called twice

### ISSUE THREAD

**Issue by Irantwomiles** [socketio/socket.io#3566]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*

On the server side, the connection event is getting called twice when a user joins

### Steps to reproduce (if the current behaviour is a bug)

Just call the connection event on the server and open a new connection, it should create two sockets with different socket id's

**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

*What is expected?*

### Setup
- OS: Windows 10
- browser: Chrome
- socket.io version: 2.3.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
```

const UUID = require('uuidjs');
const express = require('express');
const cors = require('cors');
const app = express();
app.use(cors());
const http = require('http').createServer(app);
const io = require('socket.io').listen(http);

const users = [];
const drawings = [];

const draw = {
    x: 0,
    y: 0,
    color: "",
    room : ""
}

const user = {
    id: "",
    name: "",
    room: "",
    loaded: false
}

app.get('/', function (req, res) {
    res.sendFile(__dirname + '/index.html');
});

app.get('/draw.js', function (req, res) {
    res.sendFile(__dirname + '/draw.js');
});

app.get('/main.js', function (req, res) {
    res.sendFile(__dirname + '/main.js');
});

io.on("connection", (socket) => {

    console.log("connect", socket.id);

    socket.on("disconnect", () => {
       
    })

    io.to(socket.id).emit("login", {
        id: socket.id,
        drawings: drawings
    })

    socket.on("add-user", (data) => {
        var u = Object.create(user);
        u.id = data.id;
        u.name = data.name;
        u.room = data.room;
        u.loaded = true;

        console.log(u.id);

        users.push(u);

        socket.join(u.room);

        io.to(u.id).emit("add-user", u); //emits data back to the user with that id
        io.to(u.room).emit("testing-room", {
            message: `Welcome to ${u.name} to room ${u.room}`
        })
    });

    socket.on("draw", (data) => {
        var d = Object.create(draw);
        d.x = data.x;
        d.y = data.y;
        d.color = data.color;

        drawings.push(d);

        var u = getUserById(socket.id);

        console.log(u);

        socket.to(u.room).emit("draw", {
            x: data.x,
            y: data.y,
            color: data.color
        });
        
    })

});


function getUserById(id) {
    for(var i = 0; i < users.length; i++) {
        console.log("loop", users[i].id, id);
        if(users[i].id == id) {
            return users[i];
        }
    }
}

http.listen(4000, () => console.log("Server running"));
```

**Comment by Irantwomiles** [comment]
this is the most relevant bit of code:
```

io.on("connection", (socket) => {
    console.log("connect", socket.id); // this gets called twice even though only one client gets started.
});

```

**Comment by Irantwomiles** [comment]
This was not a server side issue, but a client one.

I was accidentally connection to the server twice, hence the two connection events. I fixed it by creating a global socket variable that my other files use now.

**Comment by barrars** [comment]
Can you share the code that you used to make that global socket on the client please?
