### ISSUE TITLE
Feature: disconnect all sockets of a room.

### ISSUE THREAD

**Issue by royalpinto** [socketio/socket.io#3570]
### Feature request:
I would like to request a feature to disconnect all sockets of a given room.

### Use case:
A logged-in user has multiple connections to the server (and are also connected to different node processes). Upon user logout or session expiry, I would like to disconnect all the client connections of that user session. So, I have created a unique room for each user session id and joined all the connections to that room. So I can simply disconnect all the clients connected to that room (i.e to that session).

Expecting something like this:
```sh
io.in('room-name').disconnect(true)
```

This is missing as of now in the lib. Also, it should send signals over the adaptor to other processes to disconnect from all the other processes too.

Any suggestions? If it's a good approach, I can create a PR for it.

**Comment by darrachequesne** [comment]
For future readers: this was implemented in https://github.com/socketio/socket.io/commit/b25495c069031674da08e19aed68922c7c7a0e28 and included in `socket.io@4.0.0`

Syntax:

```js
// make all Socket instances disconnect
io.disconnectSockets();

// make all Socket instances of the "admin" namespace in the "room1" room disconnect
io.of("/admin").in("room1").disconnectSockets();
```

Documentation: https://socket.io/docs/v3/migrating-from-3-x-to-4-0/#Additional-utility-methods
