### ISSUE TITLE
A cookie associated with a cross-site resource was set without the same site..

### ISSUE THREAD

**Issue by jasonhoo95** [socketio/socket.io#3571]
When I try setting cookies to false in socketio the application load balancer url return me the above title warning... how can i remove that warning.. but when i try with the aws ip address it didnt return me the warning that is very weird..

THIS IS MY CODE..
**const io = require('socket.io')(server, {
  // path: '/socket.io',
  serveClient: true,
  transportOptions: {
    polling: {
      extraHeaders: {
        'Set-Cookie': 'HttpOnly;Secure;SameSite=Strict'
      }
    }
  },
  pingInterval: 40000,
  pingTimeout: 25000,
  upgradeTimeout: 21000, // default value is 10000ms, try changing it to 20k or more
  agent: false,
  cookie: false,
  rejectUnauthorized: false,
  reconnectionDelay: 1000,
  reconnectionDelayMax: 5000
});**

**Comment by jeyraj** [comment]
Same issue... Any solution?

**Comment by darrachequesne** [comment]
This should be fixed now in `socket.io@2.4.0` (https://github.com/socketio/engine.io/commit/19cc58264a06dca47ed401fbaca32dcdb80a903b) and `socket.io@3.0.0` and above (https://github.com/socketio/engine.io/commit/a374471d06e3681a769766a1d068898182f9305f)
