### ISSUE TITLE
Add consistent asynchronous behavior to socket.join()

### ISSUE THREAD

**Issue by sauravhiremath** [socketio/socket.io#3574]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

The client joining the room, using `socket.join()`, behaves synchronously when `(!room.length)` and asynchronously if the prior condition is not satisfied.

### Steps to reproduce (if the current behaviour is a bug)

`socket.join()`

### Expected behaviour

The `socket.join()` function should have a consistent asynchronous behavior so that the user can promisify/callback/async-await the function if required.

### Setup
- OS: Manjaro 19.0 (Kyria) 
- browser: Chromium Version 80.0.3987.163 (Official Build) snap (64-bit)
- socket.io version: 2.3.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

Use `process.nextTick()`

**Comment by darrachequesne** [comment]
For future readers: this is fixed in Socket.IO v3, as there is no "rooms" attribute on the Socket instance anymore (only a reference to the underlying adapter).

Source: https://github.com/socketio/socket.io/blob/3.1.1/lib/socket.ts#L256-L263
