### ISSUE TITLE
http/2 Support

### ISSUE THREAD

**Issue by Justsnoopy30** [socketio/socket.io#3576]
I cannot get http/2 to work with websockets on https://github.com/hypercubemc-github/HyperChat (https://hyperchat.cf).
Changing (options is https options) in Server.js:
`var app = require('https').createServer(options, server);`
`var io = require('socket.io')(app);`
 to 
`var app = require('http2').createSecureServer(options, server);`
`var io = require('socket.io')(app);` 
results in this on the client side: 
`index.js:83 WebSocket connection to 'wss://hyperchat.cf/socket.io/?EIO=3&transport=websocket&sid=Vp41O-2WIjtf5ZUkAAAA' failed: Error during WebSocket handshake: Unexpected response code: 403`

**Comment by Justsnoopy30** [comment]
@socketio

**Comment by Justsnoopy30** [comment]
@darrachequesne

**Comment by darrachequesne** [comment]
Documentation added here: https://socket.io/docs/v3/server-initialization/#With-an-HTTP-2-server
