### ISSUE TITLE
WebSocket handshake 400, can not work on Windows 10

### ISSUE THREAD

**Issue by nuznee** [socketio/socket.io#3579]
I can't use Websocket on windown 10 + Chrome 81.
[Not working from Windows] http://prnt.sc/s2cyi1

But I can use Websocket on Macbook Pro OS with Chrome 81.
[Work from OS] https://prnt.sc/s2cvsu 

My Nginx Config
location / {
proxy_pass http://localhost:8080;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Host $host;
}
===============
I need help fixing problems
===============

### Setup ###
- OS: Windows 10 Pro
- browser: Chrome 81.0.4044.113 
- socket.io version: 2.3.0

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
