### ISSUE TITLE
writeBuffer memory leak

### ISSUE THREAD

**Issue by Fabbok1x** [socketio/socket.io#3582]
Hello,
the writeBuffer of client.js does currently leak in a continuous stream.
Even after the client has disconnected the writeBuffer is not cleared.
This issue could've been culprit of leaks that have been reported previously.

### You want to:

* [x] report a *bug*
* [x] request a *feature*

### Current behaviour

Currently the writeBuffer will indefinitely grow in size for a continous stream.
The writeBuffer is not cleared upon disconnect.

### Steps to reproduce (if the current behaviour is a bug)

Can eventually provide upon request. 

### Expected behaviour

The writeBuffer should be cleared. Especially if a connection ended/died.
Additionally Client.prototype.onclose should clear the writeBuffer of the connection of the client.

### Setup
- OS: Linux
- socket.io version: 2.2.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

A fix that worked in my case was adding:
```
  if(this.conn.writeBuffer.length > 0) {
    this.conn.writeBuffer = [];
  }
```
below the writeToEngine function (L: 173 in client.js)
and in the onclose function.

Ultimately resulting in:
```
Client.prototype.onclose = function(reason){
  debug('client close with reason %s', reason);

  // ignore a potential subsequent `close` event
  this.destroy();

  // `nsps` and `sockets` are cleaned up seamlessly

 
  if(this.conn.writeBuffer.length > 0) {
    this.conn.writeBuffer = [];
  }

  for (var id in this.sockets) {
    if (this.sockets.hasOwnProperty(id)) {
      this.sockets[id].onclose(reason);
    }
  }
  this.sockets = {};

  this.decoder.destroy(); // clean up decoder
};

```
and
```
Client.prototype.packet = function(packet, opts){
  opts = opts || {};
  var self = this;

  // this writes to the actual connection
  function writeToEngine(encodedPackets) {
    if (opts.volatile && !self.conn.transport.writable) return;
    for (var i = 0; i < encodedPackets.length; i++) {
      self.conn.write(encodedPackets[i], { compress: opts.compress });
    }
  }
 
  if(self.conn.writeBuffer.length > 1) {
    self.conn.writeBuffer = [];
  }

  if ('open' == this.conn.readyState) {
    debug('writing packet %j', packet);
    if (!opts.preEncoded) { // not broadcasting, need to encode
      this.encoder.encode(packet, writeToEngine); // encode, then write results to engine
    } else { // a broadcast pre-encodes a packet
      writeToEngine(packet);
    }
  } else {
    debug('ignoring packet write %j', packet);
  }
};
```

I am not yet aware of negative side effects of this fix.Still researching. 
However this fix does certainly fix a severe memory leak of socket.io.

**Comment by darrachequesne** [comment]
For future readers:

I wasn't able to reproduce. The `writeBuffer` should be properly garbage collected after the disconnection.

Please reopen if needed.
