### ISSUE TITLE
I am getting  read ECONNRESET error

### ISSUE THREAD

**Issue by niroshana1234** [socketio/socket.io#3590]
I am getting the below error every 5 min. But still, the application socket connection is working. Can you tell how can I get rid of this error?

Error: Redis connection to 192.168.10.12:6379   failed - read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)

Below is the code

var server = require('http').Server(app);
var io = require('socket.io')(server);
var redis = require('socket.io-redis');
io.adapter(redis( {host: "192.168.10.12", port: 6379}));

**Comment by darrachequesne** [comment]
For future readers:

It should be fixed by https://github.com/socketio/socket.io-redis-adapter/commit/8e5c84f7edcda85a6f7e36c04ebd74152c1cade1.
