### ISSUE TITLE
Intellisense not working in VS Code, even though the browser seems to work with the code

### ISSUE THREAD

**Issue by OSG-Proj** [socketio/socket.io#3591]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*
When I try doing es6 module import on the browser using import io from 'socket.io-client'
For some reason it comes from a typescript definition file and the browser says the module is not found. I am trying to get intellisense working for socket.io itself but none of the code inside socket.io.js in socket.io-client/dist/ is showing up on intellisense
### Steps to reproduce (if the current behaviour is a bug)
Remake socket.io-client into a es6 module format by using the export syntax.
**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

*What is expected?*
For socket.io.js to automatically load intellisense
### Setup
- OS: Windows 10
- browser: Chrome and all others
- socket.io version: 2.3.0

**Comment by ShubhamVerma1811** [comment]
Facing the same issue.

**Comment by OSG-Proj** [comment]
I found out why a long while ago anyway, thats because the code that is embedded into the browser is actually a bundled version of all the modules in the lib folder of the socket.io-client, so basically, you just need to import them as a module and use webpack. The intellisense actually comes from a ts declaration file but webpack can let you import modules from the node_modules folder as the name of the folder in node_modules and even though the module uses module.exports, you can still use the es6 import method for some reason

**Comment by darrachequesne** [comment]
Is this fixed in v3.0.0?

**Comment by ShubhamVerma1811** [comment]
> 
> 
> I found out why a long while ago anyway, thats because the code that is embedded into the browser is actually a bundled version of all the modules in the lib folder of the socket.io-client, so basically, you just need to import them as a module and use webpack. The intellisense actually comes from a ts declaration file but webpack can let you import modules from the node_modules folder as the name of the folder in node_modules and even though the module uses module.exports, you can still use the es6 import method for some reason

I am using express with node, so "import" won't work for me.
Any other way to achieve that?
