### ISSUE TITLE
Error During handshake: Error 4040

### ISSUE THREAD

**Issue by lanceliamll** [socketio/socket.io#3598]
Console keeps saying 
```websocket.js:120 WebSocket connection to 'ws://localhost:5000/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 404```

Server Side
```
io.on("connection", (socket) => {
  console.log("New connection joined");

  socket.on("disconnect", () => console.log("User disconnected"));
})
```

Client Side
  ```useEffect(() => {
    socket = io("http://localhost:5000", { transports: ['websocket'] });
  }, [])```

this should work fine right ?

- OS: Windows 10
- browser: Google Chrome
- socket.io version: 2.3.0

**Comment by PDROJACK** [comment]
Is your socket port correct?

**Comment by hmagrahi** [comment]
It's because socket.io add a / at the end this caused this bug :/

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
