### ISSUE TITLE
Socket IO does not work with nip.io addresses

### ISSUE THREAD

**Issue by averri** [socketio/socket.io#3599]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

SocketIO does not connect to endpoints using nip.io addresses.

### Steps to reproduce (if the current behaviour is a bug)

Configure the client to connect to the server using the nip.io address:

```javascript
const io = require('socket.io-client')
const socketOut = io.connect('http://192.168.68.105.nip.io:4000')
```

### Expected behaviour

The SocketIO client should connect normally, as the nip.io is a valid internet address.

*What is expected?*

SocketIO should connect to the server.

### Setup
- OS: Ubuntu 18.04
- browser: Chrome 80
- socket.io version: 2.3.0 (client)

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

Error when connecting to the server:
![image](https://user-images.githubusercontent.com/1898447/82117784-86ac7c80-976a-11ea-8a16-6657dd8d7893.png)

The server is online and accessible normally via HTTP:
![image](https://user-images.githubusercontent.com/1898447/82117833-dd19bb00-976a-11ea-9498-bd017146865d.png)

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
