### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by ariesclark** [socketio/socket.io#3600]
* [x] request a *feature*

will there be official support for https://deno.land?

**Comment by WaseemRakab** [comment]
https://github.com/garronej/denoify
please take a look into this.

**Comment by suchislife801** [comment]
What does that have to do with the question rubybb asked?

**Comment by lupodevelop** [comment]
Any news about this feature?

**Comment by darrachequesne** [comment]
Does anybody know what is needed for supporting deno?

**Comment by crowlKats** [comment]
Deno for client uses the web WebSocket API, whereas for server you could look at how it is done in https://deno.land/std@0.73.0/ws/mod.ts

**Comment by al6x** [comment]
Any update, does socket.io works with deno?

**Comment by Chris2011** [comment]
You ca try to use: http://esm.sh/socketio but I had a talk in the discord chan of deno and it seems that the node modules needs to be converted. I also wanted to use ws with deno but they don't have support for a socks proxy. So trying the package that I mentioned, wait for official support or helping by make the underlying network stuff of node compatible :).

**Comment by KnorpelSenf** [comment]
There's a pretty good tool called [`deno2node`](https://github.com/fromdeno/deno2node). It lets you write Deno modules in TS and then it can compile them to JS, just like `tsc` compiles TS to JS. Using it in a few dozen projects without problems. If there are things that work differently on both platforms (such as maybe sockets) you can provide two different source files for this part of the library. That way, you can basically provide the same module for both runtimes, and a tiny bit under the hood can vary.

Plan of attack would be:
1. Port the code to Deno (sounds like more effort than it is, basically just adjust import statements)
2. Along the way, extract Node-specific code into a Node-specific file
3. Provide the Deno equivalent for this file
4. Swap out `tsc` with `deno2node`
5. Probably some config is broken, but otherwise you are done now.

Would be awesome to have Deno support!

**Comment by crowlKats** [comment]
As a simpler alternative to the above mentioned solution, there is the official (experimental!) deno tool [`dnt`](https://github.com/denoland/dnt/), which allows you to create Node.js packages from deno ones

**Comment by crowlKats** [comment]
What i forgot to mention above with my comment: that isnt a perfect solution. Deno does provide a `--compat` flag which allows one to use node packages, or one can use https://esm.sh/. these are more robust solutions, and are more recommended over using `dnt` (in the end, they are completely different things, and have different goals, for the case of socket.io, i would actually rather recommend one of the former solutions, not `dnt`).

**Comment by KnorpelSenf** [comment]
I have tried `dnt` a lot and it forces you to completely change the project structure to become a Deno project. `dnt` is the right tool if you have a Deno project, and you want to create a new `npm` package from it. The other way around does not work well. I tried to provide feedback to the Deno team about this, but they deem this kind of compatibility out of scope. We are supposed to write custom build scripts which copy around all files for `dnt` to work, so I concluded that it is the wrong tool for when you already have an existing npm package and you want to have the least disruption.

In contrast, deno2node is literally meant to replace `tsc`, so it just fits in. Naturally, this comes at the cost that you now are responsible for the usual yada-yada with the Node config, so again, for fresh projects `dnt` is probably best.

But either way, I do agree that the compat mode would probably work, too, and it may be the easiest of all suggested solutions. Although it will of course not be as nice as having native Deno support.

**Comment by darrachequesne** [comment]
Hello everyone!

I'm happy to announce that we have published a Socket.IO server implementation for Deno :rocket: 

Usage:

```ts
import { serve } from "https://deno.land/std@0.150.0/http/server.ts";
import { Server } from "https://deno.land/x/socket_io@0.1.0/mod.ts";

const io = new Server();

io.on("connection", (socket) => {
  console.log(`socket ${socket.id} connected`);

  socket.emit("hello", "world");

  socket.on("disconnect", (reason) => {
    console.log(`socket ${socket.id} disconnected due to ${reason}`);
  });
});

await serve(io.handler(), {
  port: 3000,
});
```

Link: https://deno.land/x/socket_io@0.1.0
Source: https://github.com/socketio/socket.io-deno

Feedback is welcome!

**Comment by webdev3301** [comment]
Welcome to the future, Socket.io devs. I just can't wait to stop finding Node examples online forever.
