### ISSUE TITLE
Will there be a update for the new uWebSockets?

### ISSUE THREAD

**Issue by Spejik** [socketio/socket.io#3601]
### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behavior

*What is actually happening?*

When I tried to use the original uws package, I got a compilation error. When I used the new [uWebSockets](https://github.com/uNetworking/uWebSockets.js), some of the methods were missing.

### Expected behavior

*What is expected?*

### Setup
- OS: Windows 10
- browser: -
- socket.io version: latest

### Other information (e.g. stack traces, related issues, suggestions on how to fix)

I'm not using socket.io for a web app, I'm creating a game in ue4 with the [ue4-client](https://github.com/getnamo/socketio-client-ue4).
I was just thinking if you guys could implement it somehow? So that it works with the new uWebSockets? I found that the UDP protocol which uWebSockets uses is much better for games than TCP, so that'd be great.
Thanks for your time

**Comment by dkMorlok** [comment]
uws is dead, you can use alternative https://www.npmjs.com/package/eiows

**Comment by darrachequesne** [comment]
>  I found that the UDP protocol which uWebSockets uses is much better for games than TCP

I'm not sure uWebSockets uses UDP under the hood. More info here: https://gafferongames.com/post/why_cant_i_send_udp_packets_from_a_browser/

The [uWebSockets.js](https://github.com/uNetworking/uWebSockets.js) package does not implement the API of  [ws](https://github.com/websockets/ws), so it can't be used as is. A wrapper could be added though.

As noted by @dkMorlok, a fork of the original `uws` package is available:

```js
// $ npm install eiows
const io = require('socket.io')(3000, {
  wsEngine: 'eiows'
});
```

Source here: https://github.com/mmdevries/eiows
