### ISSUE TITLE
Websocket transport stop working after some time

### ISSUE THREAD

**Issue by David-Good-Enough** [socketio/socket.io#3602]
### You want to:

* [x] report a *bug*

### Current behaviour

After running socket io on a nodejs for a while (from a few hours to a few days), the server just stop serving the websocket transport and only XHR still works as a valid transport.

### Steps to reproduce (if the current behaviour is a bug)

That's the problem, i can't reproduce it myself, it happens after a while running. No errors is thrown from the server or on the client, the client just try to connect every few seconds but nothing happens.

You can test it out yourself on my website, i created a version of the client with only "websocket" as the used transport and the bug is currently on :

Link removed

Open the network tab and check under WS.

If i restart the server everything works fine with this transport again until a few hours/days pass.

Nothing in the logs and i have this issue since 2 years now (since socket io ^2.2.0 at least).

Also, i tried to limit the transport to "websocket" on the server side but it just blocked all my clients when the bug came live again after a few days

### Expected behaviour

Websocket transport still working after running for a while

### Setup
- OS: Debian 9
- browser: Chrome
- socket.io version: "socket.io": last

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

Related issue : [3461](https://github.com/socketio/socket.io/issues/3461)

**Comment by pixelplace-io** [comment]
Hi this is AlmosYT.
I'm pretty sure you are not the owner of that website.

**Comment by roy2651** [comment]
Hello is this issues  solved?

**Comment by David-Good-Enough** [comment]
it is since i updated socket io.

**Comment by darrachequesne** [comment]
Without a proper way to reproduce, that will indeed be hard to debug the issue... Let's continue this discussion in https://github.com/socketio/socket.io/issues/3461
