### ISSUE TITLE
Set variable on socket connection

### ISSUE THREAD

**Issue by Bdoom** [socketio/socket.io#3603]
Is it possible to set a variable on a socket connection to be permanently there?

For example:
`io.on('connection', client => {
client.lobby_id = "sadjasdhjkas";
});
`

I want client.id to be there until it disconnects obviously. Would this mean that the variable lobby_id will always be there for that client socket connection, and could i access it in any events?

**Comment by darrachequesne** [comment]
Yes indeed. As long as you don't overwrite a property of the socket object (ref [here](https://socket.io/docs/server-api/#Socket)), it should work.

**Comment by darrachequesne** [comment]
Documentation: https://socket.io/docs/v3/server-socket-instance/#Additional-attributes
