### ISSUE TITLE
Socket.io typescript error

### ISSUE THREAD

**Issue by mrfambo** [socketio/socket.io#3605]
I am using Lerna for monorepo setup, It was working all perfect till i tried testing yarn workspaces. When i switched back to lerna, i have this very weird problem. 

<img width="1343" alt="Screenshot 2020-05-31 at 4 53 02 PM" src="https://user-images.githubusercontent.com/16781300/83351633-33881b80-a35f-11ea-95e2-cf3171b9a5ac.png">

I tried everything. Cleaning project and installing deps again but nothing is working what so ever.

I am using 

`"socket.io": "^2.3.0"`
`"@types/socket.io": "^2.1.8"`
`"typescript": "^3.8.3"`
`"ts-node": "^8.8.1",`

**Comment by mrfambo** [comment]
<img width="476" alt="Screenshot 2020-05-31 at 4 56 37 PM" src="https://user-images.githubusercontent.com/16781300/83351695-b315ea80-a35f-11ea-9a45-f49ca3f52db0.png">
This is how i am passing http server to constructor of Sockets Class

**Comment by mrfambo** [comment]
### WHAT IS  THIS???
After spending around 8 hours, i ran build to see if production build works and it gave an error. I wonder whats wrong with "flashsocket". I removed flashsocket and its working fine now !!!
Pretty confusing !!!
```
src/Sockets/index.ts:15:21 - error TS2769: No overload matches this call.
  Overload 1 of 4, '(srv: any, opts?: ServerOptions | undefined): Server', gave the following error.
    Type '"flashsocket"' is not assignable to type 'Transport'.
  Overload 2 of 4, '(port: string | number, opts?: ServerOptions | undefined): Server', gave the following error.
    Argument of type 'Server' is not assignable to parameter of type 'string | number'.
      Type 'Server' is not assignable to type 'number'.

15     this.SocketIO = socket_io(http, { transports: ['websocket', 'polling', 'flashsocket'], path: '/aw' })
```

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socket.io/docs/v3/server-initialization/#transports
