### ISSUE TITLE
Firefox 77.0.1 (Ubuntu 18.04) is blocking /socket.io/socket.io.js due to MIME type

### ISSUE THREAD

**Issue by kosson** [socketio/socket.io#3608]
It seems that with the new version of Firefox, the application using socket.io is not loading the script în the client:
`The resource from “http://localhost:8080/socket.io/socket.io.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)`.

To fix it, I have installed `socket.io-client` with bower and loaded accordingly. Works like a charm.

It seems that the solution adopted here https://github.com/socketio/socket.io/blob/210e6887327e6afed4761940fae405b8e784e8e1/lib/index.js#L28 doesn't apply anymore for the evolving browsers; `content-type` needs to be set as well?!

**Comment by kosson** [comment]
After investigations, it seems only this version is afflicted. Firefox Developer is ok. Chrome is fine, only this version of Firefox

**Comment by machineghost** [comment]
Happens with Firefox 78.0.2 also.
