### ISSUE TITLE
How check if the user is at a certain address ?

### ISSUE THREAD

**Issue by brunobrante** [socketio/socket.io#3609]
I want to check if the user is at a certain address, every time he changes location, and if he is at that address he receives a reply confirming if he is or not. But the problem is that for every 10m that it moves (or the minimum distance that I determine), I would have to make a request to my database. 

Every time the user moves at 10m, I issue my server with his location and it searches the database if this location is close to the location that i want him to be notified of, and the server returns a response warning if the user is in the location or not (sending an issue to that specific user by the server.)

I thought of another way too, that when making the first request to the server, the server brings to the front-end all the locations that are close to that user (I can limit the distance by the radius, since I use latitude and longitude). Then I always check if the user is inside the site through the front-end and not through the back-end, only 1 query will be made. If this user exceeds the distance limit that I had defined, he sends a new request to the server to get new data. I also don't know if this is the best scenario, since the client has to check it all the time.

I would like to know, what is the best way to do it, in terms of performance, traffic and cost ?! The advantages and disadvantages of each one, and possible alternatives for this case.

The scenario described above is similar to the UBER application, as it shows the driver in real time moving around the map, but I believe that in uber, it would be the driver sending the socket.io emission directly to the application user. How can I proceed in this scenario?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
