### ISSUE TITLE
Protocol specification for current version?

### ISSUE THREAD

**Issue by basickarl** [socketio/socket.io#3611]
I read this: https://github.com/socketio/socket.io-protocol

It's for version 1 though, is there a protocol specification which is general for this for the current socket io version?

**Comment by adrianschubek** [comment]
Take a look at https://github.com/socketio/engine.io-protocol#difference-between-v3-and-v4

**Comment by darrachequesne** [comment]
The documentation is now up-to-date: https://github.com/socketio/socket.io-protocol
