### ISSUE TITLE
Delay after 3rd request with socket.io

### ISSUE THREAD

**Issue by samuk190** [socketio/socket.io#3613]
When I send message it works and after the 3rd try.. it keeps getting more and more delays.
Strange because 1,2,3 message is instant... 

Server
```
io.on('connection', socket => {
  socket.on('loadMessages', async () => {
    Message.findAll({
      where: { isGroup: true },
      attributes: [['id', '_id'], 'text', ['created_at', 'createdAt']],
      order: [['created_at', 'DESC']],
      include: [
        {
          model: User,
          as: 'user',
          attributes: [['id', '_id'], 'name', 'provider'],
          include: [
            {
              model: File,
              as: 'avatar',
              attributes: ['id', 'path', 'url'],
            },
          ],
        },
      ],
    }).then(chat => {
      io.sockets.emit('loadMessages', chat);
    });
```

React-native
```
   socket.on('loadMessages', (msg) => {
      const newArray = msg.map((message) => ({
        _id: message._id,
        createdAt: message.createdAt,
        text: message.text,
        user: {
          _id: message.user._id,
          name: message.user.name,
          avatar: message.user.avatar.url,
        },
      }));
      setMessages(newArray);
    });

    return () => {
      socket.close();
    };
  }, [socket]);

  const _onSend = async (message = []) => {
    console.log(message);
    const newMessages = await GiftedChat.append(messages, message);
    // socket.on('newMessageAll', () => {
    //   setMessages([messages, ...message]);
    // });
    // console.log(newMessages);

    socket.emit('newMessage', newMessages);
    socket.emit('loadMessages');
    // socket.emit('newMessageAll');
  };
```

**Comment by darrachequesne** [comment]
@samuk190 Hi! Were you able to fix your issue? Could you please explain for future readers?

**Comment by samuk190** [comment]
> @samuk190 Hi! Were you able to fix your issue? Could you please explain for future readers?

Yes! First need use an outdated socketio client version. 
I'm using: "socket.io-client": "2.1.1",

(newer versions are too buggy, idk why, hope you can see in the future)

--> import socket io outside any react component (it doesnt work as expected if you try to useRef or something like other people recommended. It should be loaded once(the instance) only.
CLIENT 
socket.js (services/socket.js)
```
const socketConnect = (token_arg) => {
  if (!token_arg) {
    return;
  }
  const socketConnection = io('http://192.168.0.40:3333', {
    transports: ['websocket'],
    query: {token: token_arg},
  });

  return socketConnection;
};

export default socketConnect;
```
I did this because I'm verifying if user is authenticated with jwt token in my server. 

Now in your MainPage(screen) 
import socketConnect from '~/services/socket';
let socket;
(REACT HOOK ABOVE)
const ChatPrivate = ({isFocused, navigation}) => {
  const token = useSelector((state) => state.auth.token); //getting token state from redux.
  useMemo(() => {
    socket = socketConnect(token);
  }, [token]);
//use memo is needed to run once only, and it will update token when needed


useEffect(() => {
    // socket.on('newMessageAll', onReceiveMessage);

    socket.on('loadMessagesPrivate', loadMessagesPrivate);

    return () => {
      socket.off();
      socket.close();
    };
  }, []);

All listeners .on should be in useEffect (also its mandatory to close and off when you exit the screen, otherwise it will keep creating more and more instances.



 const _onSend = async (message = []) => {
    const newMessages = await GiftedChat.append(messages, message);
    socket.on('newMessagePrivate', (newMessages) => {
      setMessages(newMessages);
    });

    socket.emit('newMessagePrivate', newMessages, id);
  };

Your "newMessage" Listener should be in the _send function that will be triggered when you send something. 
You emit so all other users receive the newMessage

Server side! 

const io = require('socket.io')(server, {
  transports: ['polling', 'websocket'],
  serveClient: false,
  // below are engine.IO options
  pingInterval: 10000,
  pingTimeout: 5000,
  cookie: false,
});

io.use(function(socket, next) {
  if (socket.handshake.query && socket.handshake.query.token) {
    jwt.verify(socket.handshake.query.token, 'rakk9912x', function(
      err,
      decoded
    ) {
      if (err) return next(new Error('Authentication error'));
      socket.decoded = decoded;
      next();
    });
  } else {
    next(new Error('Authentication error'));
  }
});
server.listen(3333);
```

io.on('connection', socket => {
  // console.log(socket.handshake);
  // console.log('connected');
  // console.log(socket.id);

  socket.on('loadRequests', async () => {
    if (socket.decoded.id) {
      const user = await User.findOne({
        where: { id: socket.decoded.id, provider: true },
      });
      // verifica se é prestador de serviço
      if (user) {
        if (socket.decoded.id)
          await Request.findAll({
            // raw: true,
            // where: { [Op.not]: [{ user_id: req.userId }] },
            order: [['created_at', 'DESC']],
            limit: 25,
            attributes: ['id', 'lat', 'lon', 'type', 'read', 'created_at'],
            include: [
              {
                model: User,
                as: 'user',
                attributes: [
                  'id',
                  'name',
                  'street',
                  'streetnumber',
                  'phonenumber',
                ],
                include: [
                  {
                    model: File,
                    as: 'avatar',
                    attributes: ['id', 'path', 'url'],
                  },
                ],
              },
            ],
          }).then(request => {
            io.sockets.emit('loadRequests', request);
          });
      }
    }
  });

  socket.on('loadRequestsNew', async msg => {
    if (socket.decoded.id) {
      const user = await User.findOne({
        where: { id: socket.decoded.id, provider: true },
      });

      if (user) {
        if (socket.decoded.id)
          await Request.findByPk(msg, {
            // raw: true,
            // where: { [Op.not]: [{ user_id: req.userId }] },

            attributes: ['id', 'lat', 'lon', 'type', 'read', 'created_at'],
            include: [
              {
                model: User,
                as: 'user',
                attributes: [
                  'id',
                  'name',
                  'street',
                  'streetnumber',
                  'phonenumber',
                ],
                include: [
                  {
                    model: File,
                    as: 'avatar',
                    attributes: ['id', 'path', 'url'],
                  },
                ],
              },
            ],
          }).then(request => {
            // socket.broadcast.emit('newMessageAll', msg[0])
            // console.log(request);
            io.sockets.emit('loadRequestsNew', request);
            // console.log(socket.decoded.id);
          });
      }
    }
  });

  socket.on('loadMessages', () => {
    Message.findAll({
      where: { isGroup: true },
      attributes: [['id', '_id'], 'text', ['created_at', 'createdAt']],
      order: [['created_at', 'DESC']],
      include: [
        {
          model: User,
          as: 'user',
          attributes: [['id', '_id'], 'name', 'provider'],
          include: [
            {
              model: File,
              as: 'avatar',
              attributes: ['id', 'path', 'url'],
            },
          ],
        },
      ],
    }).then(chat => {
      socket.emit('loadMessages', chat);
    });
  });


```

It's working fine now withoutt any issues and I can use polling.

**Comment by darrachequesne** [comment]
> newer versions are too buggy, idk why, hope you can see in the future

Do you have any pointers? Any particular issue?

I added an example with React here: https://github.com/socketio/socket.io/tree/master/examples/create-react-app-example

**Comment by samuk190** [comment]
> > newer versions are too buggy, idk why, hope you can see in the future
> 
> Do you have any pointers? Any particular issue?
> 
> I added an example with React here: https://github.com/socketio/socket.io/tree/master/examples/create-react-app-example

xhr point warning 

and if you do "ForceNode" it will get delay to process the request, I'm not sure if latest version still have the issue but I don't  figure out now ;) 
btw other people had the same issue on the past too.

**Comment by samuk190** [comment]
does the socket client reconnect automatically? in your example you set "disconnected and connected" but there's no reconnection. I did socket.connect if is disconnected.

**Comment by darrachequesne** [comment]
@samuk190 `{ forceNode: true }` will use the WebSocket implementation provided by the [ws](https://github.com/websockets/ws) package, and not use the [one](https://reactnative.dev/docs/network#websocket-support) provided by the React Native platform. That may explain the additional delay.

And yes, the client reconnects automatically, as usual. You can test it by killing the server.

**Comment by samuk190** [comment]
> @samuk190 `{ forceNode: true }` will use the WebSocket implementation provided by the [ws](https://github.com/websockets/ws) package, and not use the [one](https://reactnative.dev/docs/network#websocket-support) provided by the React Native platform. That may explain the additional delay.
> 
> And yes, the client reconnects automatically, as usual. You can test it by killing the server.

how to check if its reconnecting and if it reconnected. 

In theory to update data I need check if its reconnecting and after reconnected call the emit

**Comment by darrachequesne** [comment]
@samuk190 please take a look at https://socket.io/docs/client-connection-lifecycle/

**Comment by samuk190** [comment]
@darrachequesne  Wow thanks! Nice drawing btw!
