### ISSUE TITLE
Why does socket object lose custom attributes on disconnect event?

### ISSUE THREAD

**Issue by ognjenandric99** [socketio/socket.io#3614]
Stackoveflow question : https://stackoverflow.com/questions/62491222/socket-io-why-does-socket-object-lose-custom-attributes-on-disconnect-event

On every new socket object(new connection) I set up custom attribute to socket object like this :

```js
io.on('connection', function(socket){
   socket.username = "some-custom-username";
   console.log(socket.id); //Output : unique ID from socket object
   console.log(socket.username); //Output : some-custom-username


   socket.on('disconnect',function(reason){
      console.log(socket.id); //Output : Same unique ID like earlier
      console.log(socket.username); //Output : undefined
   });
}
```
(edited for clarity)

Can anyone explain why does this happen?

It is same object, the id attribute stays the same but every custom attribute gets deleted on disconnect event therefore I am unable to easily detect which user has disconnected.

**Comment by ockenden** [comment]
The great thing about socket.io is that it's sooo easy to get into. The horrible thing about socket.io is that it's so simple that it's assumed you will just figure it out... I'm still figuring it out, but I have made some assumptions that make sense to me, and seem to work with my app. I can't say for sure, but here's how I look at things and it may help you.

My understanding is that you have to think about the `socket.id` as a virtual space you're assigned - it exists before you connect and when you do it's now yours for the duration of the session (no exceptions). This space is known as a 'socket'. When you connect, you can pass params and assign those params to the socket which will be your 'virtual space' where your params are stored which is identified by that spaces id (`socket.id`). You cannot reserve that id for a particular user.

When you disconnect from the socket, that id is still there only now it's available for someone else to use. Meaning, the parameters you assigned to it are now gone as the next user will need to assign their parameters to it.

**Comment by darrachequesne** [comment]
Hi! That's weird, the example you provided seems to work:

```
$ node server.js 
server listening on port 3000
NjWvTAgR2VK93QktAAAA
some-custom-username
NjWvTAgR2VK93QktAAAA
some-custom-username
paPErT35M2WlG3tLAAAB
some-custom-username
paPErT35M2WlG3tLAAAB
some-custom-username
^C
```

You can test it with https://github.com/socketio/socket.io-fiddle

As long as you don't overwrite any existing property of the `socket` object (like [rooms](https://socket.io/docs/server-api/#socket-rooms) or [handshake](https://socket.io/docs/server-api/#socket-handshake) for example), you should be able to attach anything to it.

**Comment by ognjenandric99** [comment]
@darrachequesne ,
Your server does not attach custom attributes to an socket object like I did in my example.
On connection attach a custom attribute like socket.ultraHighUniqueAttribute = "UNIQUE ATTRIBUTE";
On disconnect event, that socket.ultraHighUniqueAttribute will become undefined.

**Comment by darrachequesne** [comment]
My bad, I should have provided a complete example: https://github.com/socketio/socket.io-fiddle/tree/issue-3614

```
$ node server.js 
server listening on port 3000
connect h8jlZdWONy3bV_lIAAAA
connect [UNIQUE ATTRIBUTE for socket h8jlZdWONy3bV_lIAAAA (very unique)]
disconnect h8jlZdWONy3bV_lIAAAA
disconnect [UNIQUE ATTRIBUTE for socket h8jlZdWONy3bV_lIAAAA (very unique)]
```

Am I missing something?

**Comment by ognjenandric99** [comment]
No you are not. Your code is working, which means the problem is in my original socket server.
Thank you for helping out :)

**Comment by darrachequesne** [comment]
You're welcome!
