### ISSUE TITLE
How to do a server side emit ?

### ISSUE THREAD

**Issue by tudislei** [socketio/socket.io#3622]
I want to use the emit event in the express router, 
so I am trying to pass a global.io.

But the problem is , even if I add this code

io.emit('join','Tudis')

in the server.js , I can't see any response output,

(I expected there should be 'someone joined :Tudis' right after compiling?)
please enlighten me , thank you so much.

-----the code of server.js---------

```
const express = require('express')
const socketio=require('socket.io')
const http=require('http')

const serverPORT=5000

const app = express();
const server = http.createServer(app)
const io=socketio(server)

io.on('connection',(socket)=>{   
  socket.on('join',(name)=>{
    console.log('someone joined :' + name)
  }) 
})

global.io=io
const router=require('./router')
app.use(router)

io.emit('join','Tudis')

server.listen(serverPORT,
  ()=> console.log('server is up at : '+serverPORT)
  )
```

**Comment by tudislei** [comment]
//client.js
var io = require('socket.io-client');
var socket = io.connect('http://localhost:3000', {reconnect: true});
socket.emit('CH01', 'me', 'test msg');

**Comment by darrachequesne** [comment]
Hi! You can find the various way of emitting an event here: https://socket.io/docs/emit-cheatsheet/
