### ISSUE TITLE
Cannot use eiows websocket implementation in a typesafe environment

### ISSUE THREAD

**Issue by pooyakn** [socketio/socket.io#3627]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*
I cannot use "eiows" websocket package in a typesafe environment (aka typescript) as the [document](https://socket.io/docs/server-installation/#Other-WebSocket-server-implementations) explains.

Actual Error: Type '"eiows"' is not assignable to type "ws" | "uws".

### Steps to reproduce (if the current behaviour is a bug)
```const io = SocketIO(httpServer, { wsEngine: "eiows" })```
the above code doesn't transpile.

**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

*What is expected?*
It should let me pass "eiows" for wsEngine option.

### Setup
- OS: macOS Catalina
- browser: Chrome
- socket.io version: 2.3.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
Type '"eiows"' is not assignable to type "ws" | "uws".

**Comment by darrachequesne** [comment]
For future readers:

This should be fixed now, please check https://socket.io/docs/v4/server-options/#wsengine
