### ISSUE TITLE
socket.io Websockets are Slow

### ISSUE THREAD

**Issue by kevr** [socketio/socket.io#3628]
Disclaimer: Not a bug report or feature request.

Using a socket.io server and client to have a websocket conversation. When sending out a message on the server, it takes a long time to reach the destination (well over 500ms). First question I have: is there a specific reason for this delay? Secondly: Is there any way I can tell socket.io to use a quicker delivery mechanism?

I have a suspicion that `flask-socketio` depends on the event system in `eventlet` or `gevent`, which is probably what takes so long when delivering a message. This is just a guess so far, though.

Thanks for your time!

**Comment by darrachequesne** [comment]
For future readers:

This might be fixed now in latest releases. A delay of 500ms seems indeed huge, even if the client is stuck in HTTP long-polling.

Please reopen if needed.
