### ISSUE TITLE
Send message to all sockets except some when running on multiple nodes

### ISSUE THREAD

**Issue by sebamarynissen** [socketio/socket.io#3629]
### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour

When running on multiple nodes with [socket.io-redis](https://github.com/socketio/socket.io-redis) there is no way to emit a message to all sockets in a namespace except a specific socket **if the socket you want to omit is not on that node**.

Currently you can only do
```js
socket.broadcast.to('room').emit('hi', 'all');
```
which won't work on multiple nodes because the socket is not available to all nodes.

### Expected behaviour

It would be nice to have a way to broadcast to all sockets except a specific one a node that *does not* contain the socket we want to omit. I therefore propose to add a method `.except(id)` that can be used as
```js
io.to('room').except('id').emit('hi', 'all');
```

### Setup
- OS: any
- browser: any
- socket.io version: any

### Implementation

I would be happy to file a PR for this if this functionality would be accepted. The implementation could looke like this:
```js
// In namespace.js
function Namespace(server, name){
  this.name = name;
  this.server = server;
  this.sockets = {};
  this.connected = {};
  this.fns = [];
  this.ids = 0;
  this.rooms = [];
  this.flags = {};
  this.omit = [];
  this.initAdapter();
}

Namespace.prototype.except = function(id){
  this.omit.push(id);
  return this;
};

Namespace.prototype.emit = function(ev){

  // ...

  var rooms = this.rooms.slice(0);
  var flags = Object.assign({}, this.flags);
  var except = this.omit.slice(0);

  // reset flags
  this.rooms = [];
  this.flags = {};
  this.omit = [];

  this.adapter.broadcast(packet, {
    rooms: rooms,
    flags: flags,
    except: except
  });

  return this;
};
```

As far as I know this works with [socket.io-redis](https://github.com/socketio/socket.io-redis) out of the box. See also https://github.com/socketio/socket.io-emitter/issues/87 for a similar feature for [socket.io-emitter](https://github.com/socketio/socket.io-emitter).

**Comment by darrachequesne** [comment]
This was implemented in https://github.com/socketio/socket.io/commit/7de2e87e888d849eb2dfc5e362af4c9e86044701 and included in `socket.io@4.0.0`.

Example:

```js
io.except("room1").emit(/* ... */); // to all clients except the ones in "room1"
io.to("room2").except("room3").emit(/* ... */); // to all clients in "room2" except the ones in "room3"

socket.broadcast.except("room1").emit(/* ... */); // to all clients except the ones in "room1" and the sender
socket.except("room1").emit(/* ... */); // same as above
socket.to("room4").except("room5").emit(/* ... */); // to all clients in "room4" except the ones in "room5" and the sender
```

Documentation: https://socket.io/docs/v3/migrating-from-3-x-to-4-0/#Allow-excluding-specific-rooms-when-broadcasting

**Comment by sebamarynissen** [comment]
Thanks for merging and thanks for the mention in the documentation! 😄
