### ISSUE TITLE
response header customization

### ISSUE THREAD

**Issue by FlorianAgsten** [socketio/socket.io#3630]
### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour

The socket.io-implementation is removing every listener on the requests and therefore any kind of adjustment on the headers  (e.g. from the surrounding express-server) is not possible.
If it is necessary to add a header to the socket.io-calls (e.g. 'X-Content-Type-Options'), a manipulation of the used socket.io-lib is inevitable.

### Expected behaviour

It should be possible to add/adjust headers to the socket.io-server, which are used for all the responses created by the socket.io-server.

### Setup
- OS: Ubuntu
- browser: Chrome, Firefox
- socket.io version: 2.3.0

**Comment by darrachequesne** [comment]
This was implemented in `socket.io@4.1.0`:

```js
io.engine.on("initial_headers", (headers, req) => {
  headers["test"] = "123";
  headers["set-cookie"] = "mycookie=456";
});

io.engine.on("headers", (headers, req) => {
  headers["test"] = "789";
});
```

Reference:
- https://socket.io/blog/socket-io-4-1-0/#Add-a-way-to-customize-the-response-headers
- https://socket.io/docs/v4/server-instance/#Server-engine

Thanks for the suggestion :+1:

**Comment by thernstig** [comment]
@darrachequesne shouldn't https://socket.io/blog/socket-io-4-1-0/#emit-an-event-when-a-namespace-is-created be added to https://socket.io/docs/v4/middlewares/? As the examples there only shows how to add middleware to the [main namespace](https://socket.io/docs/v4/namespaces/#main-namespace).

But I would say one of the most important/common scenarios for middlewares is to add security middleware such as https://github.com/helmetjs/helmet. That should always be added to all namespaces, not just the main namespace.

Could https://socket.io/docs/v4/middlewares/ be updated to reflect this?
