### ISSUE TITLE
Websocket is throwing Error 400 while connecting to AWS Elastic Beanstalk 

### ISSUE THREAD

**Issue by jagadeesh93** [socketio/socket.io#3632]
`WebSocket connection to 'wss://myaws_elasticbeanstalk.com/socket.io/?auth=auth_token&Ids=xxx&EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 400`
### I want to:

* [x] report a *bug*

### Current behaviour

I set up a basic socket io client and server . what it does is to query my db in every one minute and give all latest documents. when i run it on my local machine it is working fine. Everything is working as expected . Local machine in the sense a remote development machine on AWS. 
When i pushed the code to our production server which is on amazon elastic beanstalk it is giving me the error . 

`WebSocket connection to 'wss://myaws_elasticbeanstalk.com/socket.io/?auth=auth_token&Ids=xxx&EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 400`

if i remove `transports: ['websocket']`, form my `socket-io client` it is working but when i check the network it is making infinite requests to server 
When i add it again it throws a 400 error 

### Expected behaviour

Proper socket connection to prod environment which is on AWS EB

### Setup
- OS : LInux
- browser: Chrome
- socket.io version:2.3.0

**Comment by playvici** [comment]
What was solve?

**Comment by Awais6** [comment]
How you resolve this issue?
