### ISSUE TITLE
Socket io not working on Shared hosting sub domain

### ISSUE THREAD

**Issue by sidpauhal** [socketio/socket.io#3633]
I have simple socket io chat app setup which is working fine locally but when I upload to my shared hosting it is not working
Socket io client is not getting connected.

I have setup node app on sub domain in a separate directory like this
subdomain.domain.com/nodeapp/

node is working properly as I can access the page from browser but socket io is not getting connected to my server
getting error ERR_CONNECTION_TIMED_OUT

My package.json dependencies

"dependencies": {
    "express": "^4.17.1",
    "mysql2": "^2.1.0",
    "pug": "^3.0.0",
    "socket.io": "^2.3.0"
}

My app.js entry file

```
const express = require('express');
const app = express();
const server = require('http').createServer(app);
server.listen();
const io = require('socket.io')(server);

app.use(express.json());
app.use(express.urlencoded());

app.set('view engine', 'pug');
app.set('views', './views');

let users = [];
app.get('/capi', function(req, res){
	let page_options = {
		title: 'Welcome',
		message: 'Welcome to pug view'
	};
	res.render('index', page_options);
});

io.on('connection', (socket) => {
	console.log('a user connected');
	socket.on('join', (room)=>{
		console.log('user joined room: '+ room);
		socket.room = room;
		socket.join(room);
		socket.to(room).emit('room_alert', 'User has joined the room.');
	})

	socket.on('chat_message', (msg) => {
		console.log('Got new message: ' + msg);
		io.in(socket.room).emit('chat_message', msg);
	});

	socket.on('disconnect', () => {
		console.log('user disconnected');
		socket.to(socket.room).emit('room_alert', 'User has leaved the room.');
		socket.leave(socket.room);
	});
});

```

On Frontend
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.js"></script>
var socket = io(window.location.origin, {path: '/nodeapp/'})
console.log(socket.connected);  ////getting false here
socket.emit('join', room);
```

Please help

**Comment by darrachequesne** [comment]
I think that's because the `path` does not match between the server and the client:

```js
const io = require('socket.io')(server, {
  path: '/nodeapp/'
});
```

Documentation here: https://socket.io/docs/client-api/#With-custom-path

**Comment by sidpauhal** [comment]
@darrachequesne hey 
I have changed my code to 

```
const io = require('socket.io')(server, {
  path: '/nodeapp/'
});
```
and I am now getting this error
{"code":0,"message":"Transport unknown"}
before it was working fine

My main domain is subdomain.domain.com which is a wordpress website

My node app is here
subdomain.domain.com/nodeapp/ which was working fine

the main issue is with socket which is not getting connected with my frontend

on the frontend I am getting false for connection and 500 error
subdomain.domain.com/nodeapp/?EIO=3&transport=polling&t=NHU72ch

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
