### ISSUE TITLE
wss 'wss://~/sockjs-node/824/hvdylsoy/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by jjkim0816** [socketio/socket.io#3634]
### You want to:

Where is the problem, and how to fix this error?

### Current behaviour
- server architecture
  network : browser <-> proxy <-> node.js web server(vue.js, yarn)
  https : browser <-> proxy
  http  : proxy <-> node.js web server(vue.js, yarn)

I commanded "yarn dev &" and requested https://~ on Chrome.
Print errors ERR_SSL_PROTOCOL_ERROR, rror during WebSocket handshake: Unexpected response code: 400

### Expected behaviour

*What is expected?*

### Setup
- OS:
- browser:
- socket.io version:

**Comment by darrachequesne** [comment]
> wss://~/sockjs-node/824/hvdylsoy/websocket

Are you using a Socket.IO client, or a Sockjs one?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
