### ISSUE TITLE
After yarn vue-cli-service build --modern, why it is not listened web server

### ISSUE THREAD

**Issue by jjkim0816** [socketio/socket.io#3635]
### You want to:

I want to listen web server after yarn build

### Current behaviour

yarn vue-cli-service build --modern, and netstat nap | grep node, but not run node.

### Expected behaviour

I don't know why not run node, after yarn build.
yarn build is success but not run node.

### Setup
- OS:
- browser:
- socket.io version:

**Comment by darrachequesne** [comment]
I'm not sure I understand the issue. Is this related to Socket.IO?

**Comment by jjkim0816** [comment]
> I'm not sure I understand the issue. Is this related to Socket.IO?

Yes Socket.IO

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
