### ISSUE TITLE
UDP sockets?

### ISSUE THREAD

**Issue by gweinstock** [socketio/socket.io#3636]
Does socket.io support UDP sockets?

**Comment by darrachequesne** [comment]
Are you referring to https://developer.chrome.com/apps/sockets_udp? In that case, no Socket.IO does not currently support it.

**Comment by gweinstock** [comment]
Yes, thank you.

**Comment by darrachequesne** [comment]
Closed in favor of https://github.com/socketio/socket.io/issues/3769

**Comment by darrachequesne** [comment]
For future readers:

WebTransport is now supported: https://github.com/socketio/socket.io/releases/tag/4.7.0

See also: https://socket.io/get-started/webtransport
