### ISSUE TITLE
CORS returns 400

### ISSUE THREAD

**Issue by ldilshan** [socketio/socket.io#3637]
Hi,
Following issue identified in the socket server after tested with **BURPSUITE professional.**

https:/url/chat-app.io/

 Response headers with not allowed origin=>

HTTP/1.1 400 Bad request
Content-Type: application/json
connection: close
Acceess-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://example.com
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Expires: 0,
Pragma: no-cache
Strict-Transport-Security: max-age = 31536000,; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode = block
Content-Length: 40

{"code": 0,"message": Transport Unknown"}

Issue detail: The application implements an HTML5 cross-origin resource sharing (CORS) policy for this request that allows access from any domain.

The application allowed access from the requested origin https://example.com

Since the Vary: Origin header was not present in the response, reverse proxies and intermediate servers may cache it. This may enable an attacker to carry out cache poisoning attacks. 

Above include the issue in detail according to DAST report. 

I have enabled CORS in the application like this,

**io.origins((origin, callback) => {
  if (origin !== 'https://foo.example.com') {
    return callback('origin not allowed', false);
  }
  callback(null, true);
});**

Is this an issue or how should i handle the 400 bad request in the application?

**Comment by darrachequesne** [comment]
`Transport Unknown` means the `transport` query param is missing from the HTTP request, which will never happen if you use a proper Socket.IO client (in any language).

This check is done before the origin validation, hence the result you're seeing. If you include `?transport=polling` in your HTTP request, you should get a proper HTTP 403 for your CORS request.

To conclude, it looks like a false positive.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
