### ISSUE TITLE
Client-side disconnect gets fired when leaving page in Firefox but not in Chrome

### ISSUE THREAD

**Issue by Tilogorn** [socketio/socket.io#3639]
### I want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

The `socket.on('disconnect')` event on the **client-side** gets fired, when you leave the page in Firefox. Does not happen in Chrome.

I show an error modal when the socket looses its connection because I assume the server went down (not a rare scenario on an embedded device).

Navigating different pages, each with their own `var socket = io();` and  `socket.on('disconnect')` methods leads to unwanted flickering of error modals because the browser assumes for a split second that the server went down until the new page gets loaded.

### Steps to reproduce (if the current behaviour is a bug)

See my fiddle fork: https://github.com/Tilogorn/socket.io-fiddle
I just added a second page and a link to it.

Open **Chrome** and navigate to index.html, open the console, check option "persist logs", then click on the link. Nothing special will appear:

![Bildschirmfoto vom 2020-09-01 16-00-19](https://user-images.githubusercontent.com/7524854/91860928-8a5a0580-ec6c-11ea-8793-386d7c48fad7.png)

Now do the same in **Firefox**. You will see the `console.log` statement of the disconnect listener.

![Bildschirmfoto vom 2020-09-01 15-59-38](https://user-images.githubusercontent.com/7524854/91860916-84fcbb00-ec6c-11ea-913c-9599d4b0d2a1.png)

### Expected behaviour

Silently leaving the page. Or having a possibility to detect that the user and not the server closed the connection so no need to show an error modal. `reason` is `transport close` in both ways.

### Setup
- OS: Linux Mint 19.3
- browser: Firefox 80.0 (observed), Chrome 84 (not observable)
- socket.io version: socket.io@2.3.0

**Comment by darrachequesne** [comment]
@Tilogorn I could indeed reproduce, thanks a lot for the example.

It seems the WebSocket instance emits an `onclose` event when switching page in Firefox, but not in Chrome. Not sure why though...

**Comment by Tilogorn** [comment]
I thought it's more of a timing thing. Like both browsers emit the `onclose` event, but Firefox does it so fast that it even triggers listeners on the "old" page (or the other way round: chrome loads the new page so fast that old listeners are not existant in RAM  anymore).

Not sure if this is fixable by socket.io though... I'm sure you don't want to have code like `if (firefox) { setTimeout(function() {socket.fire('disconnect')}, 200) }` in your code :wink:

**Comment by PorshnievN-IX** [comment]
Hello, are there any updates on this bug?

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/engine.io-client/commit/ed48b5dc3407e5ded45072606b3bb0eafa49c01f, included in [`socket.io-client@3.1.2`](https://github.com/socketio/socket.io-client/releases/tag/3.1.2).
