### ISSUE TITLE
socket.io c++ client, SSL

### ISSUE THREAD

**Issue by gweinstock** [socketio/socket.io#3641]
Hi,

I am currently using this socket.io c++ client: https://socket.io/blog/socket-io-cpp/. However, it looks like the project hasn't been maintained since 2015.

It works well, and there is a tls (ssl) c++ library build target, but I am not sure if it is actually using ssl or simply defaulting to http? I am not passing any ssl certicates to the client, so I am not 100% that it is actually using https to connect to the socket.io server. I am passing an https url to the client, and the socket.io server is listening on the https port, so it appears to be working, but is there a way I can confirm this?

I am also posting this to the GitHub for that project, but if anyone has any input, it would be greatly appreciated.

Thanks,
Gabe

**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

*What is expected?*

### Setup
- OS:
- browser:
- socket.io version:

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
