### ISSUE TITLE
Socket.io Not Loading Client Side: Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io#3642]
Hi. I am trying to have POST data update a clients DOM. Socket.io seems to be loading on the server-side, but when I open up the page it throws an error: `GET https://zoomrollcall.herokuapp.com/socket.io/socket.io.js net::ERR_ABORTED 404 (Not Found)`. Is there a reason why it cannot get the socket.io library? 

View the code [here](https://github.com/joeymalvinni/ZoomRollCall), and the live example is [here](https://zoomrollcall.herokuapp.com/)

Thanks!

**Comment by Hexafair** [comment]
i got the same problem please help me to sort out this issue

**Comment by darrachequesne** [comment]
The URL you provided seems to work now.

The only possible explanation that I see is that the Socket.IO server(s) is/are not listening, hence the HTTP 404 response (or if you used the option `serveClient: false`, obviously).

**Comment by hmassareli** [comment]
Same problem, there are a lot of people facing this problem in the web
