### ISSUE TITLE
Bundling full bundle for node server fails in runtime

### ISSUE THREAD

**Issue by msimic** [socketio/socket.io#3643]
There is a problem when using webpack to create a bundle with socket.io.
I want to build the server so I do:

`D:\Source\mudslinger-0.2.8>npx webpack --config webpack.config.js
Hash: bdaf47dbddec47b53a54
Version: webpack 4.44.1
Time: 560ms
Built at: 2020-09-09 2:49:04
  Asset      Size  Chunks             Chunk Names
main.js  1.38 MiB    main  [emitted]  main
Entrypoint main = main.js
[./configServer.js] 632 bytes {main} [built]
[./dist/server/app.js] 6.59 KiB {main} [built]
[./dist/shared/ioevent.js] 1.28 KiB {main} [built]
[./node_modules/engine.io/lib sync recursive] ./node_modules/engine.io/lib sync 160 bytes {main} [built]
[./node_modules/socket.io/lib sync recursive] ./node_modules/socket.io/lib sync 160 bytes {main} [built]
[events] external "events" 42 bytes {main} [built]
[fs] external "fs" 42 bytes {main} [built]
[http] external "http" 42 bytes {main} [built]
[net] external "net" 42 bytes {main} [built]
[path] external "path" 42 bytes {main} [built]
[querystring] external "querystring" 42 bytes {main} [built]
[readline] external "readline" 42 bytes {main} [built]
[tty] external "tty" 42 bytes {main} [built]
[url] external "url" 42 bytes {main} [built]
[util] external "util" 42 bytes {main} [built]
    + 173 hidden modules

WARNING in ./node_modules/socket.io/lib/index.js 113:11-32
Critical dependency: the request of a dependency is an expression
 @ ./dist/server/app.js

WARNING in ./node_modules/engine.io/lib/server.js 106:58-80
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/engine.io/lib/engine.io.js
 @ ./node_modules/socket.io/lib/index.js
 @ ./dist/server/app.js`

Behaviour:

It finishes with the warning.
However when launching in node:

`C:\inetpub\wwwroot>node server/main.js
{
  useHttpServer: false,
  serverPort: 8088,
  targetHost: '192.168.8.164',
  targetPort: 4000,
  clientTest: false
}
webpack:///./node_modules/socket.io/lib_sync?:4
        throw e;
        ^

Error: Cannot find module 'socket.io-client/dist/socket.io.js'
    at Function.webpackEmptyContext [as resolve] (webpack:///./node_modules/socket.io/lib_sync?:2:10)
    at resolvePath (webpack:///./node_modules/socket.io/lib/index.js?:113:99)
    at Server.serveClient (webpack:///./node_modules/socket.io/lib/index.js?:116:25)
    at new Server (webpack:///./node_modules/socket.io/lib/index.js?:53:8)
    at Server (webpack:///./node_modules/socket.io/lib/index.js?:44:41)
    at eval (webpack:///./dist/server/app.js?:32:10)
    at Object../dist/server/app.js (C:\inetpub\wwwroot\server\main.js:108:1)
    at __webpack_require__ (C:\inetpub\wwwroot\server\main.js:20:30)
    at C:\inetpub\wwwroot\server\main.js:84:18
    at Object.<anonymous> (C:\inetpub\wwwroot\server\main.js:87:10) {
  code: 'MODULE_NOT_FOUND'
}`

Steps to reproduce:

- Use socket.io in a server.
- bundle with webpack
- run the bundled js with Node
- it cannot launch

Expected behaviour

If the socket.io-client is really required it should be require()d as a normal require, not as an expression, which fails on the server if bundled this way.

Setup
- OS: WIn10
- browser: Chrome
- socket.io version: 2.3.0

**Comment by darrachequesne** [comment]
Hi! Please take a look at the example here: https://github.com/socketio/socket.io/tree/master/examples/webpack-build-server

**Comment by msimic** [comment]
> Hi! Please take a look at the example here: https://github.com/socketio/socket.io/tree/master/examples/webpack-build-server

That works but the client js cannot be served.

**Comment by yoni333** [comment]
look at [stackoverflow ](https://stackoverflow.com/questions/51914186/cannot-find-module-socket-io-client-dist-socket-io-js-when-starting-
express-ap)   they have solution to fix it

**Comment by darrachequesne** [comment]
For future readers, please check the new documentation here: https://socket.io/docs/v4/server-with-bundlers/#Webpack-5
