### ISSUE TITLE
cdn.socket.io is down

### ISSUE THREAD

**Issue by MrOnlineCoder** [socketio/socket.io#3645]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Some of my sites use cdn.socket.io for loading socket.io on client side. The site seems to be down. 

Example: [https://cdn.socket.io/socket.io-1.4.5.js](https://cdn.socket.io/socket.io-1.4.5.js)

Received response: 
```

The deployment could not be found on Vercel.

DEPLOYMENT_NOT_FOUND
```

### Steps to reproduce (if the current behaviour is a bug)

Open cdn.socket.io

### Expected behaviour

Functional CDN

**Comment by darrachequesne** [comment]
@MrOnlineCoder the CDN should now be restored, sorry for the inconvenience.

**Comment by MrOnlineCoder** [comment]
Yes, now everything is fine, thanks!
