### ISSUE TITLE
<Noob Alert> Question: I want to send a file like(PDF, txt, dox) over the websocket connection? How can I do that?

### ISSUE THREAD

**Issue by Ahzam-Lathiya** [socketio/socket.io#3646]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

*What is expected?*

### Setup
- OS:
- browser:
- socket.io version:

**Comment by shash7** [comment]
You can base64 encode and pass it to the client. But this is generally not recommended.
A better way is to pass the url of the file(assuming you're storing it in a filesystem) and the client will read from the url.

**Comment by darrachequesne** [comment]
You can simply emit the files on the client-side:

```html
<input type="file" onchange="handleFiles(this.files)">

<script>
  function uploadFiles(files) {
    socket.emit("files", files);
  }
</script>
```

On the server-side:

```js
io.on('connection', socket => {
  socket.on('files', (files) => {
    // a list of Buffer objects containing the content of the files
  });
})
```
