### ISSUE TITLE
socket.id is the same in two different sessions on localhost

### ISSUE THREAD

**Issue by Pedroxam** [socketio/socket.io#3651]
Should the socket.id be different in the two session in localhost ?

for example in normal chrome tab and private tab, this two tab must have deffrent socket id ?

Let me be clear about this, following code must send test to 1 user, but test can send in all sockets. like io.emit.

```
io.on('connection', function(socket){
    socket.on('test', function(data){
           socket.emit('test');
    });
});
```

**Comment by darrachequesne** [comment]
Yes, the `socket.id` is unique per connection.

**Comment by Pedroxam** [comment]
> Yes, the `socket.id` is unique per connection.

Yes, but in the localhost the socket.id is the same. anyway, i was able to solve this problem with replace socket.id with my users id.
