### ISSUE TITLE
socket.io fastify.js docker timed out

### ISSUE THREAD

**Issue by arsaphone** [socketio/socket.io#3653]
hi everyone

we tried to make socket.io with fastify.js and deploying on docker but get timedout when check on socket.io client tool

here's my app.js

```
const fastify = require('fastify');
const isDocker = require('is-docker');
const { APP_PORT } = require('./environment');
const app = fastify({
  bodyLimit: 1048576 * 2,
  logger: { prettyPrint: true }
});

//Init the modules
global.fastifyApp = app
require('./modules').init(app)


// Run the server!
const start = async () => {
  try {
    if (isDocker()) {
        await app.listen(APP_PORT,'0.0.0.0')
    }else{
        await app.listen(APP_PORT)
        global.fasifyApp = app
    }
    app.log.info(`server listening on ${app.server.address().port}`)
    } catch (err) {
      app.log.error(err)
        process.exit(1)
    }
}
start()

```

and my dockerfile

```
FROM node:12-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash git tzdata vim nano

ENV TZ Asia/Jakarta
    
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install

COPY . .

# ENV APP_SETTINGS_FILE_PATH '/usr/src/app/config/appSettings.json'

EXPOSE 4004
CMD ["node", "./src/app.js"]

```

this is my .env
```
// in your .env
NODE_ENV=production
/* API INFO */
TIME_ZONE=
APP_PORT=4004

//Firebase
FIREBASE_API_URL=https://fcm.googleapis.com/v1/project/project_name
FIREBASE_API_KEY=apikey123
FIREBASE_DB_URL=firebasedb

//Database
REDIS_DB_URL=CONTAINER_NAME
REDIS_DB_PORT=4005
MONGO_DB_URL=CONTAINER_NAME
MONGO_DB_PORT=27017
MONGO_DB_USER=
MONGO_DB_PASSWORD=
MONGO_DB_NAME=kulego
MONGO_DB_WITH_USERNAME_AND_PASSWORD=false
```

when i tried to use docker on my pc, it worked perfectly and socket.io client tool can connect to it.

but when i deploy the image on docker production i can reach 123.123.123:4004/ on web  but timed out when i use socket.io client tool

anyone has idea?

**EXPECTED BEHAVIOR**

I want my socket.io work perfectly on production with docker.
thanks.

**Comment by darrachequesne** [comment]
Are you able to reach the Socket.IO server? What does `curl -X GET '<url>/socket.io/?transport=polling'` return?

**Comment by arsaphone** [comment]
> Are you able to reach the Socket.IO server? What does `curl -X GET '<url>/socket.io/?transport=polling'` return?

it does says 404 not found and i see the container log and it got a hit.

**Comment by darrachequesne** [comment]
I don't see any mention of `socket.io` in the code you provided. Could you please provide a complete example? You can fork the example [here](https://github.com/socketio/socket.io-fiddle) if you want, that would be easier for us to help you.
