### ISSUE TITLE
code ENOSELF

### ISSUE THREAD

**Issue by matheuscamarques** [socketio/socket.io#3655]
`C:\Users\Matheus C. Marques\Desktop\tilemap-master\p5_js\ws>npm install socket.io`

npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "socket.io" under a package
npm ERR! also called "socket.io". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Matheus C. Marques\AppData\Roaming\npm-cache\_logs\2020-10-02T14_59_31_938Z-debug.log

**Comment by darrachequesne** [comment]
So... did you name your project the same as the dependency you're installing? (in the package.json file)

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
