### ISSUE TITLE
Can emit  in a room exclude particular socket id ? not sender.

### ISSUE THREAD

**Issue by redchallengers** [socketio/socket.io#3657]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/engine.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [x] request a *feature*

### Setup
- OS:
- browser:
- engine.io version:

**Comment by darrachequesne** [comment]
Migrated from the Engine.IO repository.

No, it's not currently possible, but it shouldn't be that hard to implement. Could you please explain your use case?

**Comment by darrachequesne** [comment]
This was implemented in https://github.com/socketio/socket.io/commit/7de2e87e888d849eb2dfc5e362af4c9e86044701 and included in `socket.io@4.0.0`.

Example:

```js
io.except("room1").emit(/* ... */); // to all clients except the ones in "room1"
io.to("room2").except("room3").emit(/* ... */); // to all clients in "room2" except the ones in "room3"

socket.broadcast.except("room1").emit(/* ... */); // to all clients except the ones in "room1" and the sender
socket.except("room1").emit(/* ... */); // same as above
socket.to("room4").except("room5").emit(/* ... */); // to all clients in "room4" except the ones in "room5" and the sender
```

Documentation: https://socket.io/docs/v3/migrating-from-3-x-to-4-0/#Allow-excluding-specific-rooms-when-broadcasting

**Comment by pluiz-briteris** [comment]
> Migrated from the Engine.IO repository.
> 
> No, it's not currently possible, but it shouldn't be that hard to implement. Could you please explain your use case?

Hey, do you have any ideas on how to implement this? I have a use case for this, and would like to hear your thoughts.

**Comment by darrachequesne** [comment]
@pluiz-briteris this has been implemented in version 4.0.0, please see my answer [above](https://github.com/socketio/socket.io/issues/3657#issuecomment-796788236).

**Comment by pluiz-briteris** [comment]
> @pluiz-briteris this has been implemented in version 4.0.0, please see my answer [above](https://github.com/socketio/socket.io/issues/3657#issuecomment-796788236).

I may be mistaken, by isn't that for excluding a room? The original question says excluding a particular socket by id.

E.g. I use the underlying server to emit but exclude a given socket of a given room, by this socket id.

Or is this happening somehow in one of the examples you shared?

**Comment by darrachequesne** [comment]
Sorry, I wasn't clear enough! The socket id can be used as a room:

```js
io.except(socketId).emit("some event");
```

Which is equivalent to:

```js
socket.broadcast.emit("some event"); // if you have access to the socket object
```

Similarly, in a particular room:

```js
io.to("some room").except(socketId).emit("some event");
```

**Comment by pluiz-briteris** [comment]
Thank you for that! It probably cover my use case.

Do we have an example like this one in the docs? If not, it would be nice, happy to contribute if needed.

**Comment by darrachequesne** [comment]
@pluiz-briteris actually, we try to discourage users to use the socket ID in their application, since it's an ephemeral identifier which is lost upon reconnection. Instead you should rather use a session ID or a user ID for this use case.

**Comment by pluiz-briteris** [comment]
> @pluiz-briteris actually, we try to discourage users to use the socket ID in their application, since it's an ephemeral identifier which is lost upon reconnection. Instead you should rather use a session ID or a user ID for this use case.

In my use case specifically, this won't be an issue, due to that I think it's worth having this mentioned (with the reconnection point), because other than this issue, I would never figure out that this is possible and this helps me a lot with what I need to do...
