### ISSUE TITLE
Relaxed version of socket.io-client

### ISSUE THREAD

**Issue by daveisfera** [socketio/socket.io#3658]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Specific version of `socket.io-client` is used

### Steps to reproduce (if the current behaviour is a bug)
Install `socket.io`

### Expected behaviour
[Recent point release of `socket.io-client`](https://github.com/socketio/socket.io-client/releases/tag/2.3.1) could be used

### Setup
- OS: macOS 10.15.6
- browser: Safari 14.0
- socket.io version: 2.3.0

**Comment by darrachequesne** [comment]
That should be fixed in latest version, please reopen if needed.
