### ISSUE TITLE
Website Meta Tags are wrong

### ISSUE THREAD

**Issue by vooxal** [socketio/socket.io#3668]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*
The meta tags for discord (and others. I haven't tested yet) look like this
![image](https://user-images.githubusercontent.com/58456527/97222774-16c80680-178c-11eb-9e8b-d30ceeedca47.png)

### Steps to reproduce (if the current behaviour is a bug)
go on discord and send the socket.io website

### Expected behaviour
Not to say casinotopp.net for the image

### Setup
- OS: Windows
- browser: Chromium

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
Change meta tags for website

**Comment by darrachequesne** [comment]
That should be fixed now, thanks for the heads-up :+1:
