### ISSUE TITLE
Pass handshake query parameter as event

### ISSUE THREAD

**Issue by sergiodelossantosjr** [socketio/socket.io#3669]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to: I want to pass value from handshake query parameter to event

* [x] report a *bug*
* [x] request a *feature*

### Current behaviour

*What is actually happening?*
Event doesn't execute if the value is from handshake query parameter

Code: 
            var **_myCustomEvent** = socket.handshake.query.**myCustomEvent**;

            socket.on(_myCustomEvent, function(msg) {

              console.log(msg);

            });

### Expected behaviour

*What is expected?*
To receive message from **_myCustomEvent** event

### Setup
- OS: Windows 10
- browser: Chrome
- socket.io version: socket.io 2.3.0

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
