### ISSUE TITLE
unexpected response when trying to connect to server hosted by node js when using socket-io python. This is new in version 3.0.0

### ISSUE THREAD

**Issue by bribrah** [socketio/socket.io#3675]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

When trying to establish connection from [python-socketio](https://github.com/miguelgrinberg/python-socketio) I get the following error: Unexpected response. If I downgrade back to 2.3.0 this error goes away.

### Steps to reproduce (if the current behaviour is a bug)

Use version 3.0.0 of socket io and the latest version of python-socketio and try to establish a connection from client(python)-server(node)

### Expected behaviour

Connection to be established

### Setup
- OS:Windows
- browser:
- socket.io version:3.0.0

**Comment by darrachequesne** [comment]
I don't think the python client has been upgraded to be compatible with Socket.IO v3 (which was released yesterday) yet.

**Comment by darrachequesne** [comment]
This should be fixed now: https://python-socketio.readthedocs.io/en/latest/intro.html#version-compatibility

Please reopen if needed.
