### ISSUE TITLE
This project sucks because of CORS

### ISSUE THREAD

**Issue by zim32** [socketio/socket.io#3681]
Two hours of trying different copy pasted solutions to fix CORS problem. No luck. GL HF

**Comment by vittse** [comment]
To get socket.io running with cors for example in a typescript project all you need to add is the following:
`
import { Server } from 'socket.io'
const io = new Server({
	cors: {
		origin: 'http://localhost:9000'
	}
})
`

**Comment by vittse** [comment]
To get socket.io running with cors for example in a typescript project all you need to add is the following:

```typescript
import { Server } from 'socket.io'

const io = new Server({
	cors: {
		origin: 'http://localhost:9000'
	}
})
```

**Comment by vittse** [comment]
To get socket.io running with cors all you need to add is the following:

```typescript
import { Server } from 'socket.io'

const io = new Server({
	cors: {
		origin: <YOUR_REQUESTING_URL>
	}
})
```

**Comment by zim32** [comment]
I am not using typescript. I use plain vanilla JS. Trying this example from official docs

```
const io = require('socket.io')(3000, {
    path: '/test',
    serveClient: false,
    // below are engine.IO options
    pingInterval: 10000,
    pingTimeout: 5000,
    cookie: false
});

io.origins(['https://foo.example.com:443']);
```

I have error **TypeError: io.origins is not a function**

I event can not figure out how to init serer side of this great library

**Comment by zim32** [comment]
And there is no **cors** field in options object in docs

**Comment by vittse** [comment]
Which version of socket.io are you using? 
The official docs are outdated at the moment.

**Comment by zim32** [comment]
I am using latest npm-installabe version 
"socket.io": "^3.0.0"

Never ignore docs. This is the first think developers see. It must be updated and reflect latest changes in your lib, because a lot of hours of developers are spend to fogire out wtf is going on and why it is not working

cors: { origins: [...] } helps me. Thanks

**Comment by vittse** [comment]
If you're using the latest version 3.0.0 you only need to adjust your configuration to the following:
```javascript
const io = require('socket.io')(3000, {
    path: '/test',
    serveClient: false,
    pingInterval: 10000,
    pingTimeout: 5000,
    cookie: false,
    // add this part and it will work
    cors: {
        origin: 'https://foo.example.com:443'
    }
});
```
