### ISSUE TITLE
Bad handshake method

### ISSUE THREAD

**Issue by ulziibadrakh-p** [socketio/socket.io#3687]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Response
{"code":2,"message":"Bad handshake method"}

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

*What is expected?*

### Setup
- OS: win 10
- browser: All
- socket.io 3.0.1:

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
Request header
```
POST /socket.io/?EIO=3&transport=polling&t=NMmz-eh HTTP/1.1
Host: localhost:3000
Connection: keep-alive
Content-Length: 3
Accept: */*
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36 Edg/86.0.622.63
Content-type: text/plain;charset=UTF-8
Origin: http://localhost
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```

Response header
```
HTTP/1.1 400 Bad Request
Access-Control-Allow-Origin: http://localhost
Vary: Origin
Access-Control-Allow-Credentials: true
Content-Type: application/json
Date: Tue, 10 Nov 2020 07:03:58 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked
```

Response
{"code":2,"message":"Bad handshake method"}

**Comment by ulziibadrakh-p** [comment]
it was my mistake diffrent client version

**Comment by HDVinnie** [comment]
@ulziibadrakh-p what was the issue as I just updated and am now receiving the same issue you described.

```diff
devDependencies:
- socket.io 2.3.0
+ socket.io 3.0.1
- socket.io-client 2.3.1
+ socket.io-client 3.0.1
```

**Comment by ulziibadrakh-p** [comment]
I was using old client version. Maybe you should check CORS.

**Comment by milleniait** [comment]
I want to sell my project, the beats token BTS.

Support
WhatsApp: +231778665904

**Comment by EO2875** [comment]
I had the same problem. It's fine if you update the client socket.  : )
