### ISSUE TITLE
io.sockets.sockets deprecated - get all sockets in v3.

### ISSUE THREAD

**Issue by llaakso** [socketio/socket.io#3688]
It seems that `io.sockets.sockets` is deprecated in v3 and following does not work anymore:

```
socket.userId = id;

// Later
for (let s in io.sockets.sockets) {
	let socket = io.sockets.sockets[s];
	if (socket.userId === ...) {
		socket.emit(f, ...params);
	}
}

```

Tried also following (https://socket.io/docs/server-api/#namespace-clients-callback)...

```
io.clients((error, clients) => {
	if (error) throw error;
	console.log(clients);
});
```

But:

`Uncaught TypeError: io.clients is not a function
`

Also `io.engine.clients` does not seem to expose client's socket object, so if that's the only way, I'd need to make custom client-id to userId table and try to keep it in sync, which feels bad idea. And if it really is, how it should be used exactly?

```
socket.on('v3test', function() {
	console.log(socket.id);
	for (let s in io.engine.clients) {
		let socket2 = io.engine.clients[s];
		console.log(socket2.id);
	}
});

```
In localhost with 1 client you'd expect 2 identical ids, but:

```
a9C3bHfHsfoA1aPJAAAB
FrOECbewjLGBnAzFAAAA

```
Please advice how to go through all connected clients in v3?

(and to clarify, the room approach is not viable in this case as the exact recipients are checked case-by-case)

**Comment by skgith1** [comment]
var allSockets = io.of('/').sockets;

socket.userId = id;

// Later
for (let s of allSockets) {
	let socket = s;
	if (socket.userId === ...) {
		socket.emit(f, ...params);
	}
}

**Comment by llaakso** [comment]
@skgith1, that does not work

`TypeError: socket.emit is not a function`

...but after digging that for awhile, following works:

```
for (let s of io.of('/').sockets) {
	let socket = s[1];
	socket.emit(...);
}
```

It doesn't feel like intended way of doing it though...

**Comment by darrachequesne** [comment]
Yes, the `sockets` attribute is now a Map instead of a plain object. I added additional code examples here: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#Namespace-connected-is-renamed-to-Namespace-sockets-and-is-now-a-Map

@llaakso your example above is good, you can even simplify it to:

```js
for (const [_, socket] of io.of("/").sockets) {
  socket.emit(...);
}
```

**Comment by RosenTomov** [comment]
@llaakso I think you'll have to iterate through all namespaces

For example, getting the total number of sockets:
```
let socketSum = 0;

socketInstance._nsps.forEach((namespace) => {
   socketSum += namespace.sockets.size;
  // iterate namespace.sockets or do something else
});
```

**Comment by oshihirii** [comment]
I'm having to do a major refactor on multiple package implementations after a hiatus from a project.  

I used to have:

```js
io.clients((error, clients) => {
    if (error) throw error;
    console.log("io.clients list is currently:");
    console.log(clients);
    // this returns an array of socket id strings eg:
    // [6em3d4TJP8Et9EMNAAAA, G5p55dHhGgUnLUctAAAB]
});
```

within:

```js
io.on('connection', (socket) => {
//...
}); 
```

In order to use `await` (per [the examples here](https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#namespaceclients-is-renamed-to-namespaceallsockets-and-now-returns-a-promise)):
```js
const ids = await io.allSockets();
console.log("io.allSockets() is currently:");
console.log(ids); 
```

The containing function needs to be `async`.  

It is allowed to make `io.on('connection', (socket) => {` an async function?

**Comment by darrachequesne** [comment]
> It is allowed to make `io.on('connection', (socket) => {` an async function?

Yes, totally :+1:
