### ISSUE TITLE
typescript for version 3 

### ISSUE THREAD

**Issue by rafakwolf** [socketio/socket.io#3689]
After installing version 3.0.1 of socket.io and client I'm facing that error when TS compiling

![image](https://user-images.githubusercontent.com/2060578/98691063-642ba280-234c-11eb-8269-9d05807d2b10.png)

The first one I think it's an incompatibility with the socket Redis adapter. But the other two seems like some problem with the typescript type definitions.

**Comment by darrachequesne** [comment]
Are you sure you are using `socket.io@3.0.1` and not `socket.io@3.0.0`? Those errors should be fixed in `3.0.1` (by https://github.com/socketio/socket.io/commit/50671d984a81535a6a15c704546ca7465e2ea295).

Could you please check? Thanks!
