### ISSUE TITLE
[Suggestion] Playground

### ISSUE THREAD

**Issue by matiaslopezd** [socketio/socket.io#3691]
I created a codesandbox, like a playground to test socketio server-side and socketio client side.

I want to suggest add to any parts of the documentation.

This is the [codesandbox](https://codesandbox.io/s/socketio-playground-p3vn9).

**Comment by darrachequesne** [comment]
Thanks! We've published a simplified version of your playground:

- https://replit.com/@socketio/socketio-minimal-example
- https://stackblitz.com/edit/socketio-base?file=index.js
- https://codesandbox.io/s/socket-io-minimal-example-k3h2l
