### ISSUE TITLE
io.on connect vs. connection in v3?

### ISSUE THREAD

**Issue by hyperknot** [socketio/socket.io#3692]
In v3, half the documentation pages and half the examples have `io.on("connect, ...)`, while the other half has `io.on("connection", ...)`

Which one is right?

**Comment by joshkpeterson** [comment]
They're synonymous, if you look at the docs entry for the connect event it says right below that connection is a synonym.

**Comment by hyperknot** [comment]
Thanks, it's indeed there. Still, it got two of us confused on Slack, so a replace-all in docs and example would be definitely a nice thing in the future.

**Comment by darrachequesne** [comment]
@hyperknot you are right, that is indeed confusing, sorry for that. I've updated all code examples to use "connection" (though both work).
