### ISSUE TITLE
Documentation v3.x: Misleading CDN version for client

### ISSUE THREAD

**Issue by fevernova90** [socketio/socket.io#3693]
I've found a little misleading information in the v3.x documentation, hopefully we can fix it but no rush.

In v3.x documentation here : [https://socket.io/docs/v3/client-installation/](https://socket.io/docs/v3/client-installation/)

At the CDN section, it should display the link to the 3.x client SDK instead of v2.3.0, this lead to compatibility issue when coupled with v3.x backend.

![image](https://user-images.githubusercontent.com/34376497/98940005-44030b80-2525-11eb-935c-30835dd9f407.png)

**Comment by darrachequesne** [comment]
Good catch, thanks! I've updated the links.

**Comment by fevernova90** [comment]
@darrachequesne thank you for the fast response!
