### ISSUE TITLE
[Documentation] typo in the announcement

### ISSUE THREAD

**Issue by WebReflection** [socketio/socket.io#3695]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

The channel should be the same or nothing would be notified.

### Steps to reproduce (if the current behaviour is a bug)

The current [release announcement](https://socket.io/blog/socket-io-3-release/) shows this example:
```js
socket.emit("updateitem", "1", { name: "updated" }, (response) => {
  console.log(response.status); // ok
});
```

But then it shows how to listen and react to `"updateitem"` via a different channel:

```js
socket.on("update item", ...);
```

### Expected behaviour

I believe that page should use ether `"update item"` or `"updateitem"` for both `emit` and `on(...)`

### Setup
- OS:
- browser:
- socket.io version:

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

I was going to file an MR right away but the docs in here points at the site and it wasn't clear to me how to file an issue regarding that site.

👋

**Comment by darrachequesne** [comment]
Good catch! For the pull request, you should find a link at the bottom of the page:

![link](https://user-images.githubusercontent.com/13031701/99318363-da0d9d80-2867-11eb-88fa-6a82e4a01ae8.png)

Pointing towards the [socket.io-website](https://github.com/socketio/socket.io-website) repository. Thanks!
