### ISSUE TITLE
Adapter rooms is protected (v3)

### ISSUE THREAD

**Issue by yanush** [socketio/socket.io#3697]
Why should adapter.rooms be protected?
Is there another way of getting a list of rooms from the adapter?
I'm using multiple instances connected through a redis adapter

**Comment by ejose19** [comment]
I stumbled on this as well, if this is really intended then what's the proper solution to retrieve all rooms? Same use case as @yanush (redis adapter)
For now I'm using ```// @ts-expect-error``` on that exact line as a workaround.

**Comment by darrachequesne** [comment]
Both `rooms` and `sids` are protected, because I think this is more an implementation detail than a public API.

But your comment suggests that an official API might be needed. Could you please detail your use case?

**Comment by yanush** [comment]
I want to get a list of rooms for all my servers in my dashboard through the redis adapter

**Comment by darrachequesne** [comment]
The redis adapter exposes an `allRooms()` method: https://github.com/socketio/socket.io-redis/#redisadapterallrooms

But it is not well documented... I'll see what I can do.

**Comment by corime** [comment]
Another use case for `rooms` (which is not possible with `allRooms()`) is getting additional information for the room (like the list of members).

Or is there any other possiblity to fetch this kind of information?

**Comment by darrachequesne** [comment]
I did not find any no real argument against this, so... those fields are now public: https://github.com/socketio/socket.io-adapter/commit/313c5a9fb60d913cd3a866001d67516399d8ee2f

Included in `socket.io-adapter@2.1.0` / `socket.io@3.1.0`.
