### ISSUE TITLE
Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by duczz** [socketio/socket.io#3705]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*

### Steps to reproduce (if the current behaviour is a bug)

Run this Code `<script src="https://widgets.coingecko.com/coingecko-coin-price-static-headline-widget.js"></script> <coingecko-coin-price-static-headline-widget coin-ids="bitcoin" currency="eur" locale="de" background-color="#ffffff"></coingecko-coin-price-static-headline-widget>`

![image](https://user-images.githubusercontent.com/25475385/100138908-fa081700-2e8e-11eb-800a-2a5c2ecb45c5.png)

### Expected behaviour

*What is expected?*

### Setup
- OS: Raspberry
- browser: Chrome
- socket.io version: 3.0.14 (iobroker)

**Comment by darrachequesne** [comment]
The error seems to indicate that `cable.coingecko.com` is not a valid domain.

```
$ dig +short cable.coingecko.com
# nothing
```

I'm closing this as I don't think this is directly related to Socket.IO.
