### ISSUE TITLE
Updating Prettier causes many files to become invalid

### ISSUE THREAD

**Issue by Download** [socketio/socket.io#3712]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

When updating Prettier, it starts to report that many files are invalid.
This might be caused by Prettier changing it's mind about some rule default values?

### Steps to reproduce (if the current behaviour is a bug)

* Git clone this project
* `npm install`
* `npm outdated`
* Update all dependencies except for mocha and prettier
* `npm run format:check`
* Observe: prettier has no complaints
* `npm uninstall --save-dev prettier && npm install --save-dev prettier`
* `npm run format:check`
* Observe: Prettier complains aboit a bunch of files

```sh
C:\ws\socketio>npm outdated
Package   Current  Wanted  Latest  Location
mocha       3.5.3   3.5.3   8.2.1  socket.io
prettier   1.19.1  1.19.1   2.2.0  socket.io

C:\ws\socketio>npm uninstall --save-dev prettier && npm install --save-dev prettier
removed 1 package and audited 326 packages in 1.548s

21 packages are looking for funding
  run `npm fund` for details

found 3 vulnerabilities (2 low, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
+ prettier@2.2.0
added 1 package from 1 contributor and audited 327 packages in 2.27s

21 packages are looking for funding
  run `npm fund` for details

found 3 vulnerabilities (2 low, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\ws\socketio>npm run format:check

> socket.io@3.0.3 format:check C:\ws\socketio
> prettier --check "lib/**/*.ts" "test/**/*.ts"

Checking formatting...
[warn] lib\client.ts
[warn] lib\index.ts
[warn] lib\namespace.ts
[warn] lib\parent-namespace.ts
[warn] lib\socket.ts
[warn] test\socket.io.ts
[warn] test\support\util.ts
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
```

**Comment by Prashoon123** [comment]
@Download I think so this is a problem with prettier because I have also seen Prettier remove some of the brackets or etc many times. I don't think so this is a problem with socketio.

**Comment by Download** [comment]
I'm pretty sure it's not a problem with socket.io 👍 
But when trying to upgrade Prettier to address #3709, I ran into this. I am assuming Prettier changed some defaults between releases causing this. I have made [a PR](https://github.com/socketio/socket.io/pull/3711) that updates all dependencies except for Prettier and Mocha and I am hoping to get some feedback on this item so I can also upgrade Prettier.

I can easily make the changes Prettier wants by running `npm run format:fix`, but it changes all source files. I think (not a Prettier expert) we can also maybe change/add some settings for Prettier so it accepts the current code without changes. In any way we have to choose: either change to adopt new Prettier convention (and change all files to reflect this), or change Prettier settings so we can keep the files as they are now without Prettier complaining. Please let me know what is the desired way forward.

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io/commit/d1bfe40dbbf416dfed2c668df56d4dcbbbe2de6b.

**Comment by Prashoon123** [comment]
> I'm pretty sure it's not a problem with socket.io 👍
> But when trying to upgrade Prettier to address #3709, I ran into this. I am assuming Prettier changed some defaults between releases causing this. I have made [a PR](https://github.com/socketio/socket.io/pull/3711) that updates all dependencies except for Prettier and Mocha and I am hoping to get some feedback on this item so I can also upgrade Prettier.
> 
> I can easily make the changes Prettier wants by running `npm run format:fix`, but it changes all source files. I think (not a Prettier expert) we can also maybe change/add some settings for Prettier so it accepts the current code without changes. In any way we have to choose: either change to adopt new Prettier convention (and change all files to reflect this), or change Prettier settings so we can keep the files as they are now without Prettier complaining. Please let me know what is the desired way forward.

I get your point @Download!! I don't exactly know what is the issue so I don't think so I can help you with this. Sorry, I hope you are able to fix the issue in the future!!
