### ISSUE TITLE
Cannot use socket.io-client in Gatsby since it already includes a different version

### ISSUE THREAD

**Issue by idosius** [socketio/socket.io#3713]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

I'm developing a website using Gatsby 2.24.50. One of the requirements is to establish a Web Socket connection to a server. I've tried using socket.io version 3.0.3 both on the client and the server, but the web socket failed to connect.

After some investigation, I realized that Gatsby already includes socket.io-client version 2.3.0. Even though I installed + imported the latest socket.io-client 3.0.3, it seemed to be ignored. I downgraded the socket.io running on my server to 2.3.0, and low and behold, everything was working.

Not sure if this is just a Gatsby issue, but it looks like running two different versions of socket.io-client in the same environment is not possible. 

### Steps to reproduce (if the current behaviour is a bug)

1. Create a demo socket.io (version 3.0.3) server on some port
1. Install + run Gatsby 2.24.50 in development mode
1. In Gatsby, install socket.io-client in version 3.0.3
1. In a Gatsby component or page, try to establish a web socket connection to the above server via socket.io-client - the connection will fail
1. Downgrade socket.io on the above server to version 2.3.0 and restart the server
1. Try to establish the web socket connection again - it will succeed
1. You can even remove the socket.io-client import in Gatsby, it will still work

### Expected behaviour

The expected behavior is that it should be possible to use any socket.io-client version in Gatsby.

### Setup
- OS: Mac
- browser: Chrome
- socket.io version: 3.0.3

**Comment by darrachequesne** [comment]
From what you describe, it seems to be an issue with Gatsby. 

Could you please open an issue in their repository https://github.com/gatsbyjs/gatsby? Thanks!
