### ISSUE TITLE
How to update query params on a Socket.io connection?

### ISSUE THREAD

**Issue by PeterTucker** [socketio/socket.io#3715]
Does anyone know if it's possible to update query params without disconnecting/reconnecting? Also if reconnecting is the only way to update query params, is there an elegant way besides socket.disconnect(), followed by socket.connect(); ?

```
socket.io.opts.query = {
          session_id: sessID,
          access_token: _data.access_token,
};
socket.disconnect();
socket.connect();
```

**Comment by ayushgupta11** [comment]
Hello @PeterTucker , you can use 
```js
socket.socket.connect()
```
Once you've initialized socket connection using `io.connect()`.

**Comment by darrachequesne** [comment]
Hi!

You can update the query parameters of the current (low-level) connection:

```js
// Socket.IO v2
socket.io.engine.transport.query.count++;
// Socket.IO v3
socket.io.engine.opts.query.count++;
```

If you are connected with HTTP long-polling, the query params should be updated for the next HTTP request.
If you are connected with WebSocket, nothing will happen (as the WebSocket connection is kept open).

You can also update the query parameters of the Manager, though they will be taken in account for the next low-level connection:

```js
socket.io.opts.query = {
  session_id: sessID,
  access_token: _data.access_token,
};
```

As you noticed, you can force the reconnection with:

```js
// only works if you have only one socket (no multiplexing)
socket.disconnect().connect();

// or close the underlying connection
socket.io.engine.close();
```

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
