### ISSUE TITLE
io.allSockets() causes UnhandledPromiseRejectionWarning: Error: timeout reached

### ISSUE THREAD

**Issue by hamitsaka** [socketio/socket.io#3717]
Hi there,

socket.io@3.0.3
socket-io-redis@6.0.1

When I try to get a list of all active sockets with:
const ids = await io.allSockets();

I get the following error:
(node:20818) UnhandledPromiseRejectionWarning: Error: timeout reached while waiting for sockets response
    at Timeout._onTimeout (/var/app/node_modules/socket.io-redis/dist/index.js:286:28)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:20818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
Please note that there are only a few clients connected to my dev environment, so it is trying to deal with too much data that could really result in timing out.

Anyone else experiencing the same issue?

Thanks
H

**Comment by momakes2** [comment]
@hamitsaka This error happens when one of your server socket.io nodes isn't answering. 
When you use socket.io-redis, it asks every server node connected to it for reporting their connected sockets, and if one of them doesn't answer (eg. node process failed, etc) it times out.

**Comment by hamitsaka** [comment]
Hi @momakes2 

Thank you for your reply.

For this particular int, there is only one instance of socket.io server running for me and this is what makes it really weird.

Is there a way to get the list of socket.io servers that the system think there is a connection to?

Thanks
Hamit

**Comment by momakes2** [comment]
Try terminating any "node" process from Task Manager on Windows or Activity Monitor on Mac. Maybe you've run the server twice by mistake.

**Comment by hamitsaka** [comment]
There was another socket.io server with a previous version (v2.x) running on the same server and connected to the same Redis server and that was what caused the issue.

Stopping the other socket.io servers with v2.x and flushing the redis database have fixed the issue.
