### ISSUE TITLE
Improperly sanitized objects causes disconnect

### ISSUE THREAD

**Issue by llaakso** [socketio/socket.io#3723]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Disconnect if client tries to send certain kind of objects.

### Steps to reproduce (if the current behaviour is a bug)

```
var el = document.createElement('input');
el.type = 'file';
el.addEventListener('change', crashTest, false);
$(el).trigger('click');

function crashTest(evt) {
    var file = evt.target.files[0];
    console.log('crashTest');
    socket.emit(file);
    // disconnect
}
```

### Expected behaviour

The data would be properly sanitized so there would not be disconnect.

### Setup
- OS: Win10
- browser: Chrome 87
- socket.io version: 3.0.1

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

Probably socket.io versions 2.* as well.

**Comment by llaakso** [comment]
First I thought this problem is related to referencing some special objects such as file reader. But I was able to reproduce this also by sending coded image data over socket:

```
var r = new FileReader();
r.onload = function (evt) {
	var packet = '';
	var array = new Uint8Array(evt.target.result);
	for (var i = 0, len = array.length; i < len; i++) {
		packet+= String.fromCharCode(array[i]);
	}
}
socket.emit('sendFile', packet);
r.readAsArrayBuffer(file.slice(start, end));
```

The particular image caused the disconnect, however, when adjusting the packet size, the problem went away, suggesting there is "reserved string" (like multiple consecutive null characters) which causes the disconnect.

Following packet terminates the connection every time: 

[socketio-disconnect-packet.txt](https://github.com/socketio/socket.io/files/5697122/socketio-disconnect-packet.txt)

**Comment by llaakso** [comment]
Turns out this was due packet size was too big.

I'd suggest to reject sending such packet and throw an error.

**Comment by bang88** [comment]
@llaakso Did you solve the problem ? I have the same problem today when a send an image about 2MB and the socket disconnected. I send it via base64 string..

**Comment by llaakso** [comment]
`maxHttpBufferSize` can be configured at server side (defaults to 1MB), but sending big packets is problematic (can cause ping timeout) so I just send image files in small chunks (see hidden comment).

**Comment by bang88** [comment]
Thank you.
