### ISSUE TITLE
How to test if socket.io is in the PROCESS of connecting in 3.0?

### ISSUE THREAD

**Issue by Delfond** [socketio/socket.io#3724]
I am trying to test whether socket.io is in the PROCESS of connecting in socket io 3.0.

In 2.0, I did this:

```
if ((soio.disconnected === true) && soio.io.connecting.length === 0)) {
  // socket is in the process of connecting
}
```

But in 3.0, "soio.io.connecting" does not exist.

I have several things that try to connect to socket.io at once, but I want the first one to try to connect and return the socket, while the others wait until it is available.

**Comment by darrachequesne** [comment]
For future readers:

You can use the `active` property of the socket:

```js
const isReconnecting = !socket.connected && socket.active;
```
