### ISSUE TITLE
Can't import/require Socket class. returns 'undefined'

### ISSUE THREAD

**Issue by dmaker3000** [socketio/socket.io#3726]
Version 3:
const {Socket} = require('socket.io')   //according to index.d.ts declaration
console.log(Socket) //=>undefined!

Version 2 (for reference):
const Socket = require('socket.io/lib/socket')   //ok. /lib/socket no longer exists in version 3

**Comment by NicolaiLassen** [comment]
I'm facing the same problem with the client library.

**Comment by darrachequesne** [comment]
Hi! I could indeed reproduce.

Out of curiosity, why do you need a direct reference to the Socket class?

**Comment by dmaker3000** [comment]
> Hi! I could indeed reproduce.
> 
> Out of curiosity, why do you need a direct reference to the Socket class?

For extending the socket class methods :)

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io/commit/d65b6ee84c8e91deb61c3c1385eb19afa196a909, included in `socket.io@4.0.2`.

Thanks for the report :+1:
