### ISSUE TITLE
Where is ip address?

### ISSUE THREAD

**Issue by xeroxstar** [socketio/socket.io#3735]
How to get ip address? I am using socket.io 3.0.4 and none of these works:

`socket.handshake.headers["x-forwarded-for"] `
`socket.request.connection.remoteAddress`
`socket.handshake.address`

the only one that works is `socket.request.connection.remoteAddress` but it returns ::1.

**Comment by fliespl** [comment]
@xeroxstar By default socket.io binds to both ipv6 & ipv4 addresses. Make sure to use specific one. In your case it returns ::1 which is localhost equivalent in ipv6.

You can start it with forcing ipv4 address as follows.
```
const socketIO = require('socket.io');
const server = require('http').createServer().listen(3000, '127.0.0.1');
var io = socketIO(server);
```

Then you can use: `socket.handshake.address`.
