### ISSUE TITLE
Supports NATS

### ISSUE THREAD

**Issue by MickL** [socketio/socket.io#3736]
Great work on socket.io 3.0, love that it is on TypeScript now ! :) This might not be the best place to ask for, but I cant think of another place to do so:

It would be great if socket.io would support NATS with both socket.io-adapter (like `socket.io-redis`) and socket.io-emitter. 

Additionally `socket.io-emitter` projects might be renamed to `socket.io-redis-emitter`, `socket.io-php-redis-emitter`, `socket.io-go-redis-emitter`, etc. since they are tight to Redis

**Comment by darrachequesne** [comment]
That would be great indeed!

At a quick glance, I don't think there would be much work to update both https://github.com/efmr/socket.io-nats and https://github.com/efmr/socket.io-nats-emitter to support Socket.IO v2 and v3.

> Additionally socket.io-emitter projects might be renamed to socket.io-redis-emitter

:+1:

**Comment by MickL** [comment]
Made issues to rename

socket.io-emitter -> socket.io-redis-adapter:
https://github.com/socketio/socket.io-emitter/issues/94

socket.io-redis -> socket.io-adapter-redis:
https://github.com/socketio/socket.io-redis/issues/389

**Comment by MickL** [comment]
Started working on the NATS adapter here: https://github.com/MickL/socket.io-nats-adapter
