### ISSUE TITLE
Force room name to be String type (v3)

### ISSUE THREAD

**Issue by pokedexter** [socketio/socket.io#3743]
Maybe because the room changed to Map, it can get Number type as room name. As I have been using room names with numbers, it has been a hassle for me to parse them into strings.

The document states that room names are String type, so I think it should automatically parse name into strings.

**Comment by darrachequesne** [comment]
That's indeed a case that isn't currently covered I think.

Well, actually, it should work even with numbers as room name, doesn't it? Is there a case where it fails?

**Comment by pokedexter** [comment]
It does work with numbers, but that's not the problem. For example, a client inside room 3 can't get messages emitted to room "3", because they are considered as different rooms.

**Comment by mding5692** [comment]
Yep had the same problem with this was storing socket keys that turned to be both numbers and strings so had same issue and thought rooms weren't connecting, fixed it when looked through this thread

**Comment by darrachequesne** [comment]
Actually, I'm not sure I'm understanding the issue here. Are you using something like this:

```js
socket.join(42);

io.to("42").emit(/* ... */);
```

In that case, we should indeed add this in the list of breaking changes for v3.

**Comment by pokedexter** [comment]
That is indeed what I have been using for my project before v3.

**Comment by mding5692** [comment]
> Actually, I'm not sure I'm understanding the issue here. Are you using something like this:
> 
> ```js
> socket.join(42);
> 
> io.to("42").emit(/* ... */);
> ```
> 
> In that case, we should indeed add this in the list of breaking changes for v3.

Same here, was working in v2 and then broke in v3 and spent hours figuring it out until I saw this github issue

**Comment by darrachequesne** [comment]
I've added it in the list of breaking changes: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#Room-names-are-not-coerced-to-string-anymore

Thanks for the heads-up on this :+1:
