### ISSUE TITLE
emit title cannot be number in v3

### ISSUE THREAD

**Issue by AitorG** [socketio/socket.io#3752]
Seems like emit function throws an error if you send number as message title instead of string. 

```
socket.emit(1, 'message') // throws error
socket.emit('1', 'message') // it's ok
```

In v2, I had a enumerable object which says what kind of packet I'm sending, something like this:

```
module.exports = Object.freeze({
  ERROR: 0,
  TRY_LOGIN: 1,
  LOGIN_SUCCESS: 2,
  GAME_READY: 3,
})
```

And then, I do something like socket.emit(Protocol.TRY_LOGIN, [array, with, info])

Now, server returns an error if TRY_LOGIN is not a string, seems like a workaround is to send '1' instead of 1.

I would like to use numbers as package title like we could do in v2.

**Comment by darrachequesne** [comment]
You are right, that makes sense, even though it does not match the [EventEmitter.emit()](https://nodejs.org/api/events.html#events_emitter_emit_eventname_args) signature (string only).

Support for integers as event names was restored by https://github.com/socketio/socket.io-parser/commit/1c220ddbf45ea4b44bc8dbf6f9ae245f672ba1b9 and included in `socket.io-client@3.1.0` / `socket.io@3.1.0`.
