### ISSUE TITLE
Can not allowed all origins or Specific origins Cors Policy. 

### ISSUE THREAD

**Issue by mahiraltinkaya** [socketio/socket.io#3755]
**Cors Policy can't allowed all origin or specific origin **

The configurations made according to V3.0.5 are shared below. Server connection is denied due to CORS policy. Different configurations have been tried like below.

"Access to XMLHttpRequest at 'http://localhost:9091/socket.io/?EIO=3&transport=polling&t=NS0JxCX' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
"
**To Reproduce**

Please fill the following code example:

Socket.IO server version: `3.0.5`

*Server*

```js
var cors = require("cors");
require("dotenv").config({ path: ".env" });
const port = 9091;
const app = require('express')();
app.use(cors());
const http = require("http").createServer(app);  
const io = require("socket.io")(http, {
  origins: ["*"],

  // optional, useful for custom headers
  handlePreflightRequest: (req, res) => {
    res.writeHead(200, {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET,POST",
      "Access-Control-Allow-Headers": "my-custom-header",
      "Access-Control-Allow-Credentials": true
    });
    res.end();
  }
});
io.on("connection", (socket) => {
  console.log('/************************')
  socket.emit('banner_ads',JSON.stringify({title:'Ahmet Reklam Yayını',status:true}))
});


/* listen port also  tried app */

  http.listen(port, () => {
    console.log(`working on ${port}`);
  });


```

Socket.IO client version: vue-socket.io `3.0.10`

*Client*

```js
import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";

Vue.config.productionTip = false;
import VueSocketIO from "vue-socket.io";

Vue.use(
  new VueSocketIO({
    debug: true,
    connection: "http://localhost:9091",
    vuex: {
      store,
      actionPrefix: "SOCKET_",
      mutationPrefix: "SOCKET_",
    },
  })
);
new Vue({
  router,
  store,
  render: (h) => h(App),
}).$mount("#app");

```

**Expected behavior**

**Platform:**
 - Device: Notebook
 - 
 - OS: [Windows 10]
![image](https://user-images.githubusercontent.com/25014707/104575435-2149bc00-5668-11eb-8034-6f1485e6ca94.png)

**Comment by darrachequesne** [comment]
It seems you are using the configuration for Socket.IO v2. Please check https://socket.io/docs/v3/handling-cors/

**Comment by mahiraltinkaya** [comment]
> It seems you are using the configuration for Socket.IO v2. Please check https://socket.io/docs/v3/handling-cors/

Hello my friend;

I checked and changed socket io integration with v3 cnf. Already i need only import socket.io with httpServer and allowing 
cors policy like below code as i understand it. Also tried origin configration with port integration. Client packages vue-socket.io and  nuxt-socket-io tried both all of them. But doesn't work socket connection.


const io = require("socket.io")(httpServer, {  cors: {    origin: "https://localhost",    methods: ["GET", "POST"]  }});
--

**Comment by darrachequesne** [comment]
Both `vue-socket.io` and `nuxt-socket-io` rely on `socket.io-client@2`:

- https://github.com/richardeschloss/nuxt-socket-io/blob/84f82b60a7c5de75acef2518658f0b883d7aae21/package.json#L55
- https://github.com/MetinSeylan/Vue-Socket.io/blob/2f63eebb70a36f462cc8fe688ab9b6185ab294bf/package.json#L32

So I think you need to:

- enable support for v2 clients (introduced in [socket.io@3.1.0](https://github.com/socketio/socket.io/releases/3.1.0))
- add the CORS configuration

```js
const io = require("socket.io")(httpServer, {
  allowEIO3: true,
  cors: {
    origin: "http://localhost:8080", // from the screenshot you provided
    methods: ["GET", "POST"]
  }
});
```

**Comment by mahiraltinkaya** [comment]
> Both `vue-socket.io` and `nuxt-socket-io` rely on `socket.io-client@2`:
> 
> * https://github.com/richardeschloss/nuxt-socket-io/blob/84f82b60a7c5de75acef2518658f0b883d7aae21/package.json#L55
> * https://github.com/MetinSeylan/Vue-Socket.io/blob/2f63eebb70a36f462cc8fe688ab9b6185ab294bf/package.json#L32
> 
> So I think you need to:
> 
> * enable support for v2 clients (introduced in [socket.io@3.1.0](https://github.com/socketio/socket.io/releases/3.1.0))
> * add the CORS configuration
> 
> ```js
> const io = require("socket.io")(httpServer, {
>   allowEIO3: true,
>   cors: {
>     origin: "http://localhost:8080", // from the screenshot you provided
>     methods: ["GET", "POST"]
>   }
> });
> ```


Thanks my friend, it is very clear for me now.

**Comment by Jeggery** [comment]
I use socket.io in the front end,  The back-end technology is unknown, but I just want to use the front-end. If it contains cross domain, what's the point of using socket.io .  Using the native websocket, it does not contain cross domain. Isn't websocket more advantageous?

**Comment by darrachequesne** [comment]
@Jeggery Socket.IO uses WebSocket under the hood, but with a fallback to HTTP long-polling which is indeed subject to cross domain security. The configuration to enable cross domain is quite straighforward though: https://socket.io/docs/v4/handling-cors/

See also: https://socket.io/docs/v4/#how-does-that-work
