### ISSUE TITLE
CDN deployed 3.1.0 may be sending wrong EIO version

### ISSUE THREAD

**Issue by aathan** [socketio/socket.io#3766]
**Describe the bug**
When specifying https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.1.0/socket.io.js script tag for this library, it appears the query string reports EIO version 3 (instead of version 4)

**To Reproduce**

Could the CDN packaged 3.1.0 be using the wrong underlying engine.io-parser package?

(See https://github.com/miguelgrinberg/python-socketio/issues/578)

**Comment by darrachequesne** [comment]
Hi! I'm not able to reproduce:

![screenshot](https://user-images.githubusercontent.com/13031701/105472997-def23180-5c9c-11eb-8022-863337e627c2.png)

Could you please check?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
