### ISSUE TITLE
cdn.socket.io: Could not load content for https://cdn.socket.io/socket.io.min.js.map

### ISSUE THREAD

**Issue by AlexLibs** [socketio/socket.io#3768]
**Describe the bug**
I'm using https://cdn.socket.io/socket.io-3.0.5.min.js from your cdn and I get this error (in the browser console):
DevTools failed to load SourceMap: Could not load content for https://cdn.socket.io/socket.io.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**To Reproduce**

Please fill the following code example:
Try to use on any html page:
`<script src="https://cdn.socket.io/socket.io-3.0.5.min.js"></script>`
And you'll get this error (in the browser console):
DevTools failed to load SourceMap: Could not load content for https://cdn.socket.io/socket.io.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

This source isn't available (one can try to open https://cdn.socket.io/socket.io.min.js.map in a browser to see it)

Here is a demo:
https://jsfiddle.net/xt1r84uf/

Socket.IO server version: `3.0.5`

**Comment by darrachequesne** [comment]
You are absolutely right :+1: 

We have updated the format of the URL on the CDN: https://cdn.socket.io/3.0.5/socket.io.min.js

Thanks for the heads-up!

**Comment by durekhan** [comment]
im facing this error DevTools failed to load source map: Could not load content for https://cdn.socket.io/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
while adding <script
    src="https://cdn.socket.io/socket.io-3.0.5.js"
  ></script>
on my html page

**Comment by darrachequesne** [comment]
@durekhan please try with https://cdn.socket.io/3.0.5/socket.io.min.js
