### ISSUE TITLE
QUIC support

### ISSUE THREAD

**Issue by dzcpy** [socketio/socket.io#3769]
It would be super awesome if socket.io can use QUIC as one of its transport layers.

**Comment by darrachequesne** [comment]
That would be awesome indeed :+1: 

Related:

- https://github.com/nodejs/node/pull/32379
- https://nodejs.org/api/quic.html

**Comment by darrachequesne** [comment]
Bad news:

- the experimental support for QUIC was removed from Node.js: https://github.com/nodejs/node/pull/37067

Good news:

- QUIC has been approved as RFC-9000: https://datatracker.ietf.org/doc/rfc9000/
- a new implementation is being worked on: https://github.com/nodejs/node/pull/38233

**Comment by reececomo** [comment]
@darrachequesne just checking in — any new developments on the node support side (two years later)?

**Comment by darrachequesne** [comment]
@reececomo it's coming: https://github.com/socketio/engine.io/releases/tag/6.5.0

We'll use the `@fails-components/webtransport` package for now, until support lands on Node.js: https://github.com/nodejs/node/pull/44325

**Comment by darrachequesne** [comment]
WebTransport is now supported: https://github.com/socketio/socket.io/releases/tag/4.7.0

We'll add a guide to test it with a self-signed certificate in local environments (soon).

**Comment by reececomo** [comment]
Nice one @darrachequesne!

**Comment by darrachequesne** [comment]
The guide: https://socket.io/get-started/webtransport

Any feedback is welcome!

**Comment by reececomo** [comment]
That is awesome, great job!

Currently we're using [geckos.io (WebRTC datachannel)](https://github.com/geckosio/geckos.io#readme), and interested to see if QUIC/webtransport offers any performance improvement/reduces packet overhead.

**Comment by frabera** [comment]
> WebTransport is now supported: https://github.com/socketio/socket.io/releases/tag/4.7.0
> 
> We'll add a guide to test it with a self-signed certificate in local environments (soon).

Awesome! Is it possible/planned to use datagrams instead of streams?

**Comment by reececomo** [comment]
* https://caniuse.com/webtransport
* https://caniuse.com/?search=quic (HTTP/3)

Interestingly Desktop Safari and a handful of mobile browsers say they support QUIC (HTTP/3) but not Webtransport. Not fully across the particulars here, we'll continue with WebRTC data channels in the meantime.

**Comment by frank-dspeed** [comment]
@reececomo i find it importent to point that out i also go at present for everything with webrtc directly i ship only the inital html
