### ISSUE TITLE
Handshake Headers's Typing should by "any" instead of "object" (v3.1.0)

### ISSUE THREAD

**Issue by Julien-Marcou** [socketio/socket.io#3770]
## Description

When retrieving the cookie property from the socket's handshake headers, typescript's typing is giving the error `Property 'cookie' does not exist on type 'object'`.

## To reproduce

Socket.IO server version: `3.1.0`

*Server*

```ts
import { Server } from 'socket.io';

const io = new Server(3000, {});

io.on('connection', (socket) => {
  // Property 'cookie' does not exist on type 'object'
  console.log(socket.handshake.headers.cookie);

  // Ok
  console.log((socket.handshake.headers as any).cookie);
});
```

## Expected behavior
We should be able to retrieve the cookie property without casting the headers to any.

A better typing could be `Record<string, any>`.

**Comment by andrejleitner** [comment]
The same goes for query attribute (`socket.handshake.query`) I think.

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io/commit/4f2e9a716d9835b550c8fd9a9b429ebf069c2895 (included in `socket.io@3.1.1`).

Thanks for reporting the issue!
