### ISSUE TITLE
Server socket.emit(...) returns TRUE instead of Socket

### ISSUE THREAD

**Issue by Sunvas** [socketio/socket.io#3779]
**To Reproduce**
Server code:
```
io.of("room").on('connection', socket=>{
   console.log( socket.emit("action") ); //Logs true, expected Socket

    socket.emit("action1").emit("action2"); //Failed: socket.emit(...).emit is not a function
});
```

**Comment by darrachequesne** [comment]
Yes, you are right, this `emit` chain is not possible since https://github.com/socketio/socket.io/commit/50671d984a81535a6a15c704546ca7465e2ea295

Is that something you relied on in Socket.IO v2?

**Comment by Sunvas** [comment]
> Is that something you relied on in Socket.IO v2?
Well, yes.

Also in [documentation](https://socket.io/docs/v3/server-api/#socket-emit-eventName-…args-ack), it is clearly said that the `emit` method returns Socket.

**Comment by darrachequesne** [comment]
I've added it to the list of breaking changes in v3: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#emit-chains-are-not-possible-anymore

The documentation of the `emit()` method has been updated too: https://socket.io/docs/v3/server-api/#socket-emit-eventName-%E2%80%A6args-ack

Thanks for the heads-up on this :+1:
