### ISSUE TITLE
SyntaxError: Unexpected identifier handshake 

### ISSUE THREAD

**Issue by RobinLouisSchmidt** [socketio/socket.io#3780]
**Describetion**
I just started a new Project and set up a fresh nodeJs server, installed express and socket.io. No Problem so far, but after i wrote the basic starting code (should not be important here), and started the node js app, the following error occurred:

/var/www/node_modules/engine.io/lib/server.js:231
  async handshake(transportName, req) {
        ^^^^^^^^^
SyntaxError: Unexpected identifier

**To Reproduce**

Please fill the following code example:

Socket.IO server version: 3.1.0

*Server*

```js
const app = require('express')();
const http = require('http').Server(app);
const io = require('socket.io')(http);

app.get('/', function (req, res) {
    res.sendfile('index.html');
});

//Whenever someone connects this gets executed
io.on('connection', function (socket) {
    console.log('A user connected');

    //Whenever someone disconnects this piece of code executed
    socket.on('disconnect', function () {
        console.log('A user disconnected');
    });
});

http.listen(3000, function () {
    console.log('listening on *:3000');
});
```

**Expected behavior**
no error 

**Platform:**
 - Device: [Google Cloud VM]
 - OS: [Debian 9.13]

**Comment by darrachequesne** [comment]
Which version of Node.js are you using? At least Node.js 10 is needed: https://socket.io/docs/v3/server-installation/

See also: https://github.com/nodejs/Release

**Comment by RobinLouisSchmidt** [comment]
yeha, that was the problem, google told it was up to date, but it was very old. Thanks for the fast reply.
