### ISSUE TITLE
Allow Regex Values In CORS Configuration

### ISSUE THREAD

**Issue by n6rayan** [socketio/socket.io#3782]
**Is your feature request related to a problem? Please describe.**
Since the introduction of CORS, we are having some issues with our various environments. We currently have PR environments i.e. envs that spin up when creating PR's via GitHub. The environment URL's will vary every time e.g. https://domain-1234.co.uk or https://domain-5678.co.uk.

**Describe the solution you'd like**
This could be fixed by allowing a regex value in the array of accepted origins just like the [CORS NPM package](https://www.npmjs.com/package/cors#configuration-options)

**Comment by darrachequesne** [comment]
For Socket.IO v3: we are actually relying on the `cors` package, so all options are supported:

```js
const io = require("socket.io")(httpServer, {
  cors: {
    origin: /example\.com$/,
    methods: ["GET", "POST"]
  }
});
```

Documentation here: https://socket.io/docs/v3/handling-cors/

For Socket.IO v2: you can provide a function to the `origins` method:

```js
io.origins((origin, callback) => { callback(null, /example\.com$/.test(origin)) });
```

**Comment by n6rayan** [comment]
Hi @darrachequesne - Thank you for the information, we have now upgraded to `v3.1.0` and all is working as expected. I will close this off. Thanks again! 👍
