### ISSUE TITLE
Invalid namespace for socket v2 connecting to server v3

### ISSUE THREAD

**Issue by RonnieRocket147** [socketio/socket.io#3791]
**Describe the bug**
After upgrading the server to v3.1.0 and using the ```allowEIO3: true``` option the client socket v2.2.0 cannot connect to the indicated namespace anymore. 

```
  socket.io:server creating engine.io instance with opts {"allowEIO3":true,"cors":{"credentials":true,"methods":["GET","POST"],"origin":["https://localhost:4200","http://10.0.2.2:4200"],"transports":["websocket","polling"]},"path":"/socket.io"} +0ms
  socket.io:server initializing namespace /frontend +0ms
  socket.io:client connecting to namespace / +0ms
  engine:ws received "40/frontend?sessionId=2053f60c072e0749d141112ddc851e00942785d7&revision=develop," +1ms
  socket.io-parser decoded 0/frontend?sessionId=2053f60c072e0749d141112ddc851e00942785d7&revision=develop, as {"type":0,"nsp":"/frontend?sessionId=2053f60c072e0749d141112ddc851e00942785d7&revision=develop"} +3ms
  socket.io:client creation of namespace /frontend?sessionId=2053f60c072e0749d141112ddc851e00942785d7&revision=develop was denied +3ms
  socket.io:client writing packet {"type":4,"nsp":"/frontend?sessionId=2053f60c072e0749d141112ddc851e00942785d7&revision=develop","data":{"message":"Invalid namespace"}} +0ms
```

The client connects to the URL `https://localhost:3700/frontend?sessionId=2053f60c072e0749d141112ddc851e00942785d7&revision=develop`

When the query parameters are removed the connection to `/frontend` succeeds.

Server v2.2.0 was working fine with the query parameters.

Any thoughts?

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io/commit/6f4bd7f8e7c41a075a8014565330a77c38b03a8d (included in `socket.io@3.1.1`).

Thanks for reporting the issue!
