### ISSUE TITLE
How to satisfy `Server.adapter()` with `typeof Adapter`?

### ISSUE THREAD

**Issue by MickL** [socketio/socket.io#3796]
**Describe the bug**
I am not sure if this is just a question or the typings are not correct, but it seems impossible for me to satisfy the `Server.adapter()` function which is defined as:

```
adapter(v: typeof Adapter): Server;
```

I tried:

```
createAdapter(): Adapter {}
createAdapter(): typeof Adapter {}
createAdapter(): ReturnType<Adapter> {}
createAdapter(): ReturnType<typeof Adapter> {}
```

Looking at [socket.ioredis](https://github.com/socketio/socket.io-redis/blob/72fe98ed948acc0f86c4f86c7636befdf8720c24/lib/index.ts#L70) it just has no return type / returns any :/

**Comment by ironicbrew** [comment]
I think you may be importing Adapter from the wrong place, imported it improperly or it may be incorrectly declared wherever you are importing it from.

The exact type errors you are getting would be helpful here along with a more complete snippet/repo I could use to reproduce this error.

I figure this is the jist of what you are trying to accomplish except with your own custom Adapter class? The below throws no type issues on my end

```
import { Server } from "socket.io";
import {Adapter} from "socket.io-adapter";

function createAdapter(): typeof Adapter {
    return Adapter;
}

new Server(3333).adapter(createAdapter())
```

**Comment by darrachequesne** [comment]
@MickL I think you are right, the typings are not correct.

The `adapter` argument should be a function the takes a namespace and returns an Adapter instance. Example:

- the in-memory adapter: https://github.com/socketio/socket.io-adapter/blob/2.1.0/lib/index.ts#L30-L33
- the redis adapter: https://github.com/socketio/socket.io-redis/blob/6.0.1/lib/index.ts#L82-L84

**Comment by grubstarstar** [comment]
Isn't the problem that the types are using `typeof Adapter` instead of just using `Adapter` as it's already a type as it's a class.

e.g. If it change it to this:

```
adapter(): Adapter | undefined;
adapter(v: Adapter): this;
adapter(v?: Adapter): Adapter | undefined | this;
```

**Comment by darrachequesne** [comment]
@grubstarstar the adapter function does not take a Adapter instance, but a function that takes a namespace and returns an Adapter instance (there is one Adapter instance per namespace, created [here](https://github.com/socketio/socket.io/blob/3.1.1/lib/namespace.ts#L58-L60)), so I don't think this would work.

I guess we should rather have something like `type AdapterConstructor = typeof Adapter | ((nsp: Namespace) => Adapter);`, to match the current implementation, but the Typescript compiler does not agree.

**Comment by MickL** [comment]
IMO the existing adapters should have a return type. Then they would run in the same problem as I did or solve my question.

Currently they dont have any return type thats why they throw no error:
https://github.com/socketio/socket.io-redis/blob/4dae265a740129b0d86f16418319b902a0648a3c/lib/index.ts#L70

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io/commit/891b1870e92d1ec38910f03bb839817e2d6be65a.

Please reopen if needed.
