### ISSUE TITLE
socket.io > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

### ISSUE THREAD

**Issue by raphael10-collab** [socketio/socket.io#3803]
Installing ipfs : 

`warning ipfs > ipfs-core > libp2p-webrtc-star > socket.io > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-
    severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. 
    (https://github.com/visionmedia/debug/issues/797)`

- O.S. : Ubuntu 18.04 Desktop
- node: v14.5.0

**Comment by darrachequesne** [comment]
This is already fixed I think:

- https://github.com/socketio/socket.io-parser/commit/7c380d38ebdd7fa3984aff34bea3eac94f8c3089 (`socket.io-parser@4.0.3`)
- https://github.com/socketio/socket.io/commit/230cd19164edf294d12cea04876d4e8bb3c93547 (`socket.io@3.0.5`).
