### ISSUE TITLE
When emit 1268096 characters, the socket is disconnected

### ISSUE THREAD

**Issue by einsqing** [socketio/socket.io#3817]
When emit 1268096 characters, the socket is disconnected！2.x is ok

server 3.1.1
client 3.1.1

**Comment by einsqing** [comment]
This issue has been resolved

**Comment by darrachequesne** [comment]
Thanks for the update.

For future readers, the default value of [`maxHttpBufferSize`](https://socket.io/docs/v3/server-initialization/#maxHttpBufferSize) is 1e6 (1Mb). You need to increase it if you need to send bigger payloads:

```js
const io = require("socket.io")(httpServer, {
  maxHttpBufferSize: 1e8
});
```

**Comment by llaakso** [comment]
I can see many others struggling with this. I'd add client logic to reject too big emits. It is not viable that each developer adds test to each possible emit containing possible too big payload.
