### ISSUE TITLE
Provide access to the connection error reason

### ISSUE THREAD

**Issue by andrejleitner** [socketio/socket.io#3819]
I was looking into a way to detect connection errors on server side (e.g. for logging purposes). The only way it can be done seems to be attaching custom `request` listener to the underlying http server. Check for response status code and in the case of `400` rediscover the reason (bad transport, bad method, unknown session ID) manually. It would be nice to have it accessible programmatically somehow in the process running a `socket.io` server.

**Comment by darrachequesne** [comment]
The Engine.IO server could indeed emit an event when such errors occur.

The error codes can be found here: https://github.com/socketio/engine.io/blob/master/lib/server.js#L108

Would you have time to implement it?

**Comment by andrejleitner** [comment]
Closed by release of v4.1.0.
