### ISSUE TITLE
Socket.io client can't send WebSocket message

### ISSUE THREAD

**Issue by zydjohnHotmail** [socketio/socket.io#3825]
**Describe the bug**
Socket.io client can't send WebSocket message

**To Reproduce**
Please fill the following code example:

Socket.IO server version: `x.y.z`
Sever: C# WebSocket server, it works, it can accept different types of websocket clients
*Server*

Socket.IO client version: `3.1.2`

*Client* (On Node.js version 15.10.0 on Windows 10)

```
const io = require("socket.io-client");
const socket = io('ws://localhost:8888/', { transports: ['websocket'] });
socket.on('connect', () => {
  console.log('connected!');
});
socket.emit('Hello');
socket.on("disconnect", () => {
  console.log("disconnect");
});
```

**Expected behavior**
expected to show 'connected' message and send 'Hello' message to WebSocket C# server, but on C# WebSocket server only shows A new session connected. 

**Platform:**
 - Device: PC
 - OS: Windows 10

**Additional context**
On C# WebSocket server only shows A new session connected, but not the 'Hello' message received.

**Comment by darrachequesne** [comment]
Please see the documentation here: https://socket.io/docs/v3/#What-Socket-IO-is-not
