### ISSUE TITLE
Client isnt receiving message

### ISSUE THREAD

**Issue by merttyilmaz** [socketio/socket.io#3841]
**Describe the bug**
The data is lost outside of socket.on method in the client(gps, msg.speed). I can see the data in the client socket.on() by console logging in it but outside of that method all information is lost.

**To Reproduce**

Please fill the following code example:

Socket.IO server version: `4.0.0`

*Server*

```js
const gps=json.gpsData;


const app = require('express')();
const http = require('http').Server(app);
const io = require('socket.io')(http, {
  cors: {
    origin: '*',
  }
});

let index=0;

io.on('connection', socket => {

  interval = setInterval(() => {
    socket.emit("con",gps[index])
    index++
    if(index==774){
    clearInterval(interval);
   }
}, 5000);
})

http.listen(4000, function() {
  console.log('listening on port 4000')
})
```

Socket.IO client version: `4.0.0`

*Client*

```js
import { io } from "socket.io-client";

let gps=0;
  const socket = io("http://localhost:4000")
  socket.on("con", (msg) => {
    // console.log(msg.speed)
    gps=msg.speed
      
  });
  
  console.log(gps);
'''

**Expected behavior**
I'm expecting client to see the log of the msg data.

**Platform:**
 - Device: PC
 - OS: Windows 10

**Additional context**
Add any other context about the problem here.
![image](https://user-images.githubusercontent.com/38688568/111403804-b3a92300-86de-11eb-8ab7-4027020f888b.png)

The 0's in the picture in line 17 are console.log(gps); but the datas in line 12 come when i remove the comment from console.log(msg.speed).. I have commented the part in the code above FYI.

**Comment by mkadirtan** [comment]
@merttyilmaz this is the expected behavior.
`socket.on("con", ...)` event is fired at a future time.
you can better understand the code execution with this:
```javascript
import { io } from "socket.io-client";

let gps=0;

console.time('time') // 0
  const socket = io("http://localhost:4000")
  socket.on("con", (msg) => {
    console.timeLog('time', { gps }); // 300 ms
    gps=msg.speed
  });
  
console.timeLog('time', {gps}); // 150 ms
console.timeEnd('time');
```

as you can see, your console.log executes even before event happens. Therefore gps variable is still 0. I highly suggest you to read about event loop in javascript, nodejs.

**Comment by merttyilmaz** [comment]
Yeah thanks for the help. I have another question though. The data thats being sent over from the server is always out of order, i restart the client and the server and its not related to that. I get null errors constantly sometimes after the console logs after 50.
After some logs i keep getting this error:
WebSocket connection to 'ws://localhost:4000/socket.io/?EIO=4&transport=websocket&sid=JZWX3Esyb_4NqQ_3AANo' failed: 

Appreciate any help.



SERVER

const gps=json.gpsData;


const app = require('express')();
const http = require('http').Server(app);
const io = require('socket.io')(http, {
  cors: {
    origin: '*',
  }
});

let index=0;

io.on('connection', socket => {

  interval = setInterval(() => {
    socket.emit("con",gps[index])
    index++
    if(index==774){
    clearInterval(interval);
   }
}, 10000);
})

http.listen(4000, function() {
  console.log('listening on port 4000')
})

CLİENT

 const socket = io("http://localhost:4000")
  const [settings, setSettings] = useState(false)

  useEffect(() => {
   try {

     socket.on("con", (data) => {
       setSettings(data)
     })
   } catch (error) {
     console.log(error)
   }
 }, [settings])
  console.log(settings)
