### ISSUE TITLE
Emit returns a weird type so union types no longer compile

### ISSUE THREAD

**Issue by solomon23** [socketio/socket.io#3844]
**Describe the bug**
this used to compile in typescript but won't in 4.0

`(channel ? io.to(channel) : io).emit("stuff", message);`

https://github.com/socketio/socket.io/pull/3843

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io/commit/1a72ae4fe27a14cf60916f991a2c94da91d9e54a. Thanks.
