### ISSUE TITLE
[feature] add a way to register middlewares for all namespaces

### ISSUE THREAD

**Issue by darrachequesne** [socketio/socket.io#3851]
**Is your feature request related to a problem? Please describe.**

Since Socket.IO v3, it is not mandatory anymore for the client to connect to the main namespace.

Registering a global middleware which applies to all namespace is thus a bit messier:

```js
const of = io.of;
io.of = (...args) => {
  const nsp = of.call(io, ...args);
  nsp.use(yourMiddleware);
  return nsp;
}
```

**Describe the solution you'd like**

```js
io.<name of the method>(yourMiddleware); // register a middleware which will be attached to each namespace
```

**Describe alternatives you've considered**

Registering a global middleware is possible for dynamic namespaces:

```js
const parentNamespace = io.of(/^\/dynamic-\d+$/);

parentNamespace.use(yourMiddleware); // attached to all child namespaces
```

**Additional context**

Related: https://github.com/socketio/socket.io/discussions/3842

**Comment by stephaneeybert** [comment]
I also wanted to register a root main middlewaredid would fire up its handler for all namespaces.

I was trying to have the middleware:
```
io.use((socket, handler) => {
});
```
called up on a connection to:
```
server.io.of('/elearning').on('connection', function(socket) {
});
```
but the middleware handler would not fire up.

I also tried:
```
io.of('/').use((socket, handler) => {
});
```
but that also did not fire up.

Then I tried with a regex and that again did not fire up.

Only when I changed it to the same namespace is in the connection:
```
io.of('/elearning').use((socket, handler) => {
});
```
did it fire up.

But then I would need to have one same middleware for each and every namespace.

**Comment by sean256** [comment]
I'm glad I found this, I honestly thought `io.use` was bugged. `v2` supported a global middleware and it was awesome.

**Comment by thernstig** [comment]
@darrachequesne the examples inhttps://socket.io/how-to/register-a-global-middleware show:

```js
const myGlobalMiddleware = (socket, next) => {
  next();
}

io.use(myGlobalMiddleware);
io.of("/my-custom-namespace").use(myGlobalMiddleware);
```

But `io.use` is not documented anywhere herehttps://socket.io/docs/v4/server-api/

Is it the `io.use(myGlobalMiddleware)` that adds the middleware to _all namespaces_? Then why is `io.of("/my-custom-namespace").use(myGlobalMiddleware);` also needed?
