### ISSUE TITLE
Website says "socket.io 3.0 is here" but the latest version is 4

### ISSUE THREAD

**Issue by rmcloughlin** [socketio/socket.io#3861]
The website (https://socket.io/) says "SOCKET.IO 3.0 IS HERE" in big letters but the latest version is 4.0.0 (https://github.com/socketio/socket.io/releases).

**Comment by darrachequesne** [comment]
@rmcloughlin you are right, thanks for the heads-up! I think this headline is less useful now, we'll have to update it :+1:

**Comment by KaSakee** [comment]
I think 3.0 is when the break changes begin so it might make sense to let it be 3.0 I guess

**Comment by darrachequesne** [comment]
This should be resolved now. Thanks!
