### ISSUE TITLE
socket.join() saving the room id string inside the single quote

### ISSUE THREAD

**Issue by coderrajput** [socketio/socket.io#3862]
**Describe the bug**
socket.join("user2p8jdlr6klqzapxe") is getting saved as Set { 'zaRHHC5hTDBjaHnFAAAF', ' "user2p8jdlr6klqzapxe" ' }. Here its getting wrapped inside single quote

**To Reproduce**

io.on("connection", (socket) => {
    const id= socket.handshake.query.id;

    socket.join(id);
    console.log(socket.rooms);
        socket.on('receive',({id1,msg})=>{
          console.log('`${id1}`');
            console.log(id1);
            io.to(id1).emit('ok',msg);
            // io.sockets.in('"user2p8jdlr6klqzapxe"').emit('message', 'what is going on, party people?');
            //
            // socket.broadcast.to('"user2p8jdlr6klqzapxe"').emit('rec-mesg','hello ladies');

        });

  });

**Expected behavior**
Set { 'aNv5s7_nhQoAbhvXAAAB', 'user2p8jdk9eklqybe3r ' }

**Actual behaviour**
Set { 'aNv5s7_nhQoAbhvXAAAB', ' "user2p8jdk9eklqybe3r" ' }

**Platform**
 - ubuntu 18.04 
 
![image](https://user-images.githubusercontent.com/56526264/112930807-993c6400-9138-11eb-9518-94922d02f779.png)

**Comment by darrachequesne** [comment]
Hi! I'm not able to reproduce: https://github.com/socketio/socket.io-fiddle/tree/issues/socket.io/3862

Could you please check?

**Comment by coderrajput** [comment]
Thanks @darrachequesne  for replying. Now i am not getting the error after updating my node to 14.
