### ISSUE TITLE
Error connecting Sockets TypeError: v.replace is not a function

### ISSUE THREAD

**Issue by vishal-dev-ilz** [socketio/socket.io#3879]
var io = require('socket.io').(3000).

Its working fine for version v2 socket for v3 and v4 are throwing this error

**Comment by darrachequesne** [comment]
I am not able to reproduce. Could you please provide a complete example?

The `replace` method is used here:
- https://github.com/socketio/socket.io/blob/1faa7e3aea1414ec814aa935021356e8ed2b054c/lib/index.ts#L309
- https://github.com/socketio/socket.io/blob/1faa7e3aea1414ec814aa935021356e8ed2b054c/lib/index.ts#L311

**Comment by oleksii-lyhun** [comment]
@vishal-dev-ilz I also had issue with socket connection! I also got same issue like you with v.replace is not a function.
This code working for me
```
const server = new Hapi.Server({
  port: config.get('api.port') || 3000,
  debug: { request: ['error', 'uncaught'] },
  query: {
    parser: (query) => Qs.parse(query),
  },
})

const io = require('socket.io')(server.listener)

```
Hope it will help you!

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
