### ISSUE TITLE
io.of('/').adapter.rooms returns an empty set

### ISSUE THREAD

**Issue by lucassardois** [socketio/socket.io#3884]
**Describe the bug**
The line `io.of('/').adapter.rooms` returns an empty set even if rooms with clients exists. 

**To Reproduce**

Socket.IO server version: `4.0.1`

*Server*

```js
import { Server } from "socket.io";

const io = new Server(3000, {});

io.of("/").adapter.on("create-room", (room) => {
  console.log(`room ${room} created`)

  setInterval(() => {
    update()
  }, 5000)

  const update = () => {
    console.log(`update room ${room}`)
    console.log(`clients: ${JSON.stringify(io.of('/').adapter.rooms)}`)
  }
})

io.of("/").adapter.on("join-room", (room, id) => {
   console.log(`[${id}] has joined room: ${room}`)
})

io.on('connection', (socket) => {
  console.log(`socket connected with id: ${socket.id}`)
  socket.join('general')
})
```

Socket.IO client version: `4.0.1`

*Client*

```js
import { io } from "socket.io-client";

const socket = io("ws://localhost:3000/", {});

socket.on("connect", () => {
  console.log(`connect ${socket.id}`);
});

socket.on("disconnect", () => {
  console.log("disconnect");
});
```

**Expected behavior**
I expect `io.of('/').adapter.rooms` to returns a set of created rooms instead of an empty Set.

**Platform:**
 - Device: Thinkpad T480
 - OS: Linux Mint 20

**Additional context**
The `update` function declared in the room creation seems to be called twice: once for the room and once for the connected socket.

**Comment by darrachequesne** [comment]
Hi! That's because `io.of('/').adapter.rooms` is an ES6 [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map), which is converted to `{}` by the `JSON.stringify()` method. You can check it with:

```js
const update = () => {
  console.log(`update room ${room}`)
  console.log(`clients: ${io.of('/').adapter.rooms}`) // prints "clients: [object Map]"
}
```

The `update` method is called twice because the Socket instance also joins the room of its own ID (`socket.join(socket.id)`).

Documentation: https://socket.io/docs/v4/rooms/#Implementation-details

**Comment by lucassardois** [comment]
Thanks for the answer.

Is it possible to know if the room was created for the socket private message feature or if it was created because a socket joined it for the first time? Or do I have to implement this logic myself?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
