### ISSUE TITLE
Deprecate @types/socket.io

### ISSUE THREAD

**Issue by memark** [socketio/socket.io#3900]
**Is your feature request related to a problem? Please describe.**
When using version 3+ of Socket.io the `@types/socket.io` should not be any used anymore. This is only briefly mentioned in the upgrade guide and easy to miss. Missing it causes all kinds of strange compilation problems.

**Describe the solution you'd like**
Deprecate the typings so that a warning is shown on `npm install`.

**Describe alternatives you've considered**

**Additional context**
A guiding example could be the way it's done for 
https://www.npmjs.com/package/@types/classnames
which upon installation gives
>warning @types/classnames@2.3.1: This is a stub types definition. classnames provides its own type definitions, so you do not need this installed.

**Comment by darrachequesne** [comment]
That's a good idea! I think we can copy the PR here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52274

@memark would you have time to do it?

**Comment by memark** [comment]
@darrachequesne Sure thing, I'll send a PR shortly.

**Comment by memark** [comment]
Looking at the list in DT, does this apply to all of these packages? @darrachequesne 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/CODEOWNERS#L6723

![image](https://user-images.githubusercontent.com/318504/116874542-c7bacc80-ac19-11eb-99d0-41c12a9ca97d.png)

**Comment by darrachequesne** [comment]
This applies to:

- `socket.io` (https://github.com/socketio/socket.io)
- `socket.io-client` (https://github.com/socketio/socket.io-client)
- `socket.io-emitter` (now named `@socket.io/redis-emitter`, https://github.com/socketio/socket.io-redis-emitter)
- `socket.io-parser` (https://github.com/socketio/socket.io-parser)
- `socket.io-redis` (https://github.com/socketio/socket.io-redis)

The other packages are maintained by the community.

**Comment by memark** [comment]
FYI
I'm still working on this PR over at DT. I've run into a ton of trouble (mostly because of other packages depending on socket.io), but I'm working with the maintainers to solve it.

**Comment by memark** [comment]
Solved by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52719

**Comment by darrachequesne** [comment]
Great!

```
$ npm i @types/socket.io
npm WARN deprecated @types/socket.io@3.0.2: This is a stub types definition. socket.io provides its own type definitions, so you do not need this installed.
```

@memark thanks a lot :+1:

**Comment by Ahnert1** [comment]
@darrachequesne Sorry for the noobie question, but does this mean that I cannot strongly type my Typescript Express server which uses the `socket.io` npm package?

**Comment by memark** [comment]
@Ahnert1 It means that with recent versions of `socket.io` the strong types are built-in and requires no additional packages.

**Comment by Ahnert1** [comment]
@memark ahh yes, I was using an older version of `socket.io`. Thank you!
