### ISSUE TITLE
Socket events getting too much time to fire

### ISSUE THREAD

**Issue by PonnarV** [socketio/socket.io#3907]
I am using socket.io for my chat app.  When above users connect to the chat at the same time, it's getting even slower such that, it looks like, it's almost freezed.  I have used socket.emit()

Am I getting it wrong? Should I use some other way for emitting?

And receive message after 5 Mins

**Comment by darrachequesne** [comment]
That sounds weird. Are you sending a lot of data?

Could you please provide some code to reproduce? You can fork the example [here](https://github.com/socketio/socket.io-fiddle).
