### ISSUE TITLE
Dependency security alert

### ISSUE THREAD

**Issue by umonaca** [socketio/socket.io#3908]
I am receiving a Dependabot alert in my project with the following information:
```
The latest possible version that can be installed is 1.5.5 because of the following conflicting dependency:
socket.io@2.4.1 requires xmlhttprequest-ssl@~1.5.4 via a transitive dependency on engine.io-client@3.5.0
The earliest fixed version is 1.6.2.
```

Screenshot:
![image](https://user-images.githubusercontent.com/53662960/117270330-17baae80-ae27-11eb-8d0f-9bff15bed626.png)

I am using socket.io@2.4.1. I don't think it is feasible to upgrade my socket.io package to 3.x, so I am writing to ask if there will be an upgrade in socket.io 2.x to fix this problem.  
I am not sure whether I should report this issue to socket.io repository or engine.io, so I just put it here.

**Comment by darrachequesne** [comment]
Hi! This should be fixed now, as we have released `engine.io-client@3.5.2` which now points to `xmlhttprequest-ssl@~1.6.2`.

Reference: https://github.com/socketio/engine.io-client/releases/tag/3.5.2
