### ISSUE TITLE
Socket Level Middleware not working

### ISSUE THREAD

**Issue by Inoshy** [socketio/socket.io#3912]
**Bug Description**
Socket Level Middleware not working

**To Reproduce**
As from the docs, I copied code sample for [socket level middleware](https://socket.io/docs/v4/server-socket-instance/#Socket-middlewares).

Socket.IO server version: `4.0.1`

*Server*

```js
import { Server } from "socket.io";

const io = new Server(3000, {});

io.on("connection", (socket) => {
  console.log(`connect ${socket.id}`);

  socket.use(([event, ...args], next) => {
    console.log('middleware here') // doesn't log anything
    return next(new Error('unauthorized event')) // trying to abort the connection
  })

  socket.on('error', err => {
    if (err && err.message === 'unauthorized event') {
      console.log('here') // doesn't log anything
      socket.disconnect()
    }
  })

});
```

Socket.IO client version: `4.0.1`

*Client*

```js
import { io } from "socket.io-client";

const socket = io('/');

const socket = io('/')

socket.onAny((eventName, ...args) => {
  console.log('here') //doesn't log anything
});

socket.on('connect', () => {
  console.log(socket) //logs the socket
})

```

**Comment by darrachequesne** [comment]
Hi! The middleware should be called when a packet is received.

Did you try to add a `socket.emit("test");` on the client side?

**Comment by Inoshy** [comment]
> Hi! The middleware should be called when a packet is received.
> 
> Did you try to add a `socket.emit("test");` on the client side?

Thanks for the clarification!
