### ISSUE TITLE
Volatile not working from server to client with binary data

### ISSUE THREAD

**Issue by sergmister** [socketio/socket.io#3919]
**Describe the bug**
Sending a volatile event from the client (Chrome) to Node with binary data works fine. Sending a volatile event from Node to the client with binary data does not work. Sending binary data without volatile works, sending non binary data with volatile works.

**To Reproduce**

Socket.IO server version: `4.1.1`

*Server*

```js
import { createServer } from "http";
import { Server, Socket } from "socket.io";

const httpServer = createServer({});

const io = new Server(httpServer, {
  cors: {
    origin: "http://localhost:8080",
    methods: ["GET", "POST"],
  },
});

io.on("connection", (socket) => {
  socket.on("some event", (data) => {
    console.log(data);
  });

  setTimeout(() => {
    socket.volatile.emit("some event", "hello");
    // socket.volatile.emit("some event", new ArrayBuffer(10));
  }, 1000);
});

httpServer.listen(3000);
```

Socket.IO client version: `4.1.1`

*Client*

```js
import { io } from "socket.io-client";

this.socket = io("http://localhost:3000");

    this.socket.on("some event", (data) => {
      console.log(data);
    });

    setTimeout(() => {
      this.socket.volatile.emit("some event", new ArrayBuffer(10));
    }, 1000);
```

works fine, changing the server code:

```js
  setTimeout(() => {
    // socket.volatile.emit("some event", "hello");
    socket.volatile.emit("some event", new ArrayBuffer(10));
  }, 1000);
```

and the client receives nothing

**Expected behavior**
The client receives the binary data.

**Platform:**
 - OS: Linux 5.10
 - Node 15.14.0

**Comment by BrendanAnnable** [comment]
I can confirm this bug, and just encountered it when upgrading from socket.io v2 to v4.

It appears to send non-binary data just fine, and it will even send the non-binary parts _of the same message_ just fine, including binary placeholder objects. But the binary packets which correspond to those placeholder objects appear to be never sent.

**Comment by lemonad** [comment]
I also ran into this problem when trying to use `volatile`. I'm using socket.io version 4.2.0.

**Comment by darrachequesne** [comment]
I could indeed reproduce the issue. We will publish a fix as soon as possible.

**Comment by brako** [comment]
Thanks, the problem occurs when we send volatile data directly with the server (working fine with the socket )
```
setInterval(() => {
    io.volatile.emit("test", Buffer.from([1,2,3]));
  }, 1000);
```
You won't receive the data with the client.

**Comment by darrachequesne** [comment]
@brako _zut_, you are right. This should be finally fixed by https://github.com/socketio/socket.io-adapter/commit/88eee5948aba94f999405239025f29c754a002e2, included in `socket.io-adapter@2.3.3` (which should be included by latest `socket.io` by transitivity).

I added a test case [here](https://github.com/socketio/socket.io/commit/2da82103d22b69a8684b5831517a89e722bf090b), to prevent any regression in the future.

Please reopen if needed.
