### ISSUE TITLE
Unhandled Runtime Error Error: unknown packet type NaN

### ISSUE THREAD

**Issue by Him-2C** [socketio/socket.io#3927]
**Describe the bug**
How to fix this 

```
Unhandled Runtime Error
Error: unknown packet type NaN
```

Socket.IO server version: `4.1.0`
Socket.IO client version: `4.1.0`

*Client*

![image](https://user-images.githubusercontent.com/30730045/118397254-52b9af00-b67d-11eb-8d15-1f069f7055d3.png)

**Comment by CallMeGhosty** [comment]
Hello! Could you provide the code you are using?

**Comment by Him-2C** [comment]
@CallMeGhosty duplicate [3922](https://github.com/socketio/socket.io/issues/3922)

**Comment by darrachequesne** [comment]
This should be fixed in `socket.io@4.1.2`. Could you please check?

**Comment by Him-2C** [comment]
@darrachequesne Work! thank you.
