### ISSUE TITLE
Unable to emit or trigger an event to a room id.

### ISSUE THREAD

**Issue by sk-santhosh** [socketio/socket.io#3935]
**Problem**
Unable to emit or trigger an event to a room id.

Link: [https://codesandbox.io/s/socket-io-room-event-not-emitting-1ozu7](https://codesandbox.io/s/socket-io-room-event-not-emitting-1ozu7)

**Code**

Socket.IO server version: `4.1.1`

*Server*

```js
var app = require("http").createServer();

process.env.DEBUG = "*";

const customParser = require("socket.io-msgpack-parser");

var io = require("socket.io")(app, {
  parser: customParser,
});

io.listen(3000);

io.of("custom_namespace").on("connection", (socket) => {
  console.log("Connected");
  socket.on("join_room", () => {
    console.log("Join Room");

    // Working Fine
    socket.emit("direct_event");

    socket.join("ROOM_12345");

    setInterval(() => {
      console.log("Room Event");

      // *********** Problem ************
      // Event not emiting
      io.to("ROOM_12345").emit("room_event");
    }, 1000);
  });
});
```

Socket.IO client version: `4.1.1`

*Client*

```js
var _io = io("/custom_namespace", {
      parser: require("socket.io-msgpack-parser"),
});

_io.on("connect", () => {
      console.log("connected");
      _io.emit("join_room");
 });

_io.on("direct_event", () => {
      console.log("direct_event");
});

_io.on("room_event", () => {
      console.log("room_event");
});
```

Reference Image:

![Screenshot from 2021-05-19 09-53-34](https://user-images.githubusercontent.com/69190150/118756330-4bb2bc80-b888-11eb-94d5-620a1e5214da.png)

**Comment by Benedicht** [comment]
Joining to add some details.

`io.to("ROOM_12345").emit("room_event");` uses socket.io-adapter's [broadcast](https://github.com/socketio/socket.io-adapter/blob/03bda43550a798ac21c9d7be73b71d23df1a1c1e/lib/index.ts#L138-L141) and sets the `wsPreEncoded` field:
```javascript
    const firstPacketOpts = {
      wsPreEncoded: "4" + encodedPackets[0], // "4" being the "message" packet type in Engine.IO
      ...packetOpts
    };
```

However, `wsPreEncoded` is used **only** in the [websocket transport](https://github.com/socketio/engine.io/blob/8c9bd9262f1c664722194c8c321cba947cf0bf54/lib/transports/websocket.js#L96-L100):
```javascript
    if (packet.options && typeof packet.options.wsPreEncoded === "string") {
      send(packet.options.wsPreEncoded);
    } else {
      this.parser.encodePacket(packet, this.supportsBinary, send);
    }
```

If the client is upgrading or can't upgrade to the websocket transport at all, no events using `wsPreEncoded ` going to be sent over.


### Another problem 
is that the Buffer produced by the socket.io-msgpack-parser becomes a string (`"4" + encodedPackets[0]`). This string is sent through a websocket text frame, but its data might not be a valid utf-8 text while the [websocket specification](https://datatracker.ietf.org/doc/html/rfc6455#section-5.6) requires that it must be a valid one:

>    Text

      The "Payload data" is text data encoded as UTF-8.  Note that a
      particular text frame might include a partial UTF-8 sequence;
      however, the whole message MUST contain valid UTF-8.

**Comment by sk-santhosh** [comment]
This release `socketio/socket.io-adapter@2.3.1` works for me 

Reference: https://github.com/socketio/socket.io-adapter/pull/70

thank you @yuhj86
