### ISSUE TITLE
Can 4.1.0 please be pushed to NPM

### ISSUE THREAD

**Issue by willoughby** [socketio/socket.io#3936]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by darrachequesne** [comment]
Hmm, it's already on NPM: https://www.npmjs.com/package/socket.io/v/4.1.0

Am I missing something?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
