### ISSUE TITLE
socket.to('').emit() doesn't work for all the clients in the room

### ISSUE THREAD

**Issue by 2006aman-github** [socketio/socket.io#3949]
**Describe the bug**
I am building an online multiplayer chess game and I am using socket to update the pieces position in real time. I have rooms with 2 people allowed and the roomId is the socket id of the user who joins a newly created room i.e. the default room generated by socket.io as any new connection occurs. when I try to broadcast an event in any room the broadcast works successfully when I make it from the socket id which is not the Id of the room. But when I try to do it from the socket id which is same as the id of room i.e generated by default I am not able to broadcast to other socket id aka player. Please help me out I am so stuck and let  me tell you that I am using react as a front end

**To Reproduce**

server code here >>> Only one file
`const express = require("express");
const app = express();
const http = require("http");
const cors = require("cors");
const socketio = require("socket.io");
const server = http.createServer(app);
const io = socketio(server, {
  cors: {
    origin: "*",
    methods: ["GET", "POST"],
  },
});
const { v4: uuidv4 } = require("uuid");

// middlewares here...
app.use(cors());

app.get("/", (req, res) => {
  res.send("hey dude this is home page");
});
let rooms = [];
let players = {};

io.on("connection", (socket) => {
  console.log("New Conection");
  // check if rooms available for player to join
  let roomId = socket.id;
  rooms = io.sockets.adapter.rooms;
  let newlyCreatedRoom = true;
  for (const [key, value] of rooms.entries()) {
    if (io.sockets.adapter.rooms.get(key).size === 1) {
      roomId = key;
      socket.join(key);
      players[socket.id] = {
        roomId,
        color: "black",
      };
      io.sockets.adapter.rooms.get(key).size !== 1 &&
        (newlyCreatedRoom = false);
      console.log("now rooms are", io.sockets.adapter.rooms);
      socket.broadcast.emit("opponent-connected", `opponent connected`);
      // adding a new player to existing room and will always have black color who joins next
      // message to welcome the newly connected client
      break;
    }
  }

  newlyCreatedRoom
    ? socket.emit("server-connection-message", {
        message: "hey client",
        roomId,
        color: "black",
      })
    : socket.emit("server-connection-message", {
        message: "hey client",
        roomId,
        color: "white",
      });

  // when a player joins the match
  socket.on("player-joined-verify", (name) => {
    players[socket.id] = { name, id: socket.id, roomId };
    socket.broadcast.emit("opponent-connected", `opponent name is: ${name}`);
  });

  // when a player moves his piece
  socket.on("piece-moved", (data) => {
    socket.to(players[socket.id].roomId).emit("opponent-piece-moved", data);

    console.log("piece moved by", socket.id, players[socket.id].roomId);
  });

  // when player leaves the room
  socket.on("disconnect", () => {
    console.log("Client disconnected");
  });
});
const PORT = 8000 || process.env.PORT;
server.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});`

React code here i.e front-end
this snippet is from App.js in a useEffect.
`  useEffect(() => {
    const playerName = window.prompt("Please Enter Your Name: ");

    // setting a random color
    dispatch({
      type: globalReducerActions.handlePlayerColor,
      payload: {
        playerName,
      },
    });
    // socket io connection logic..
    (async () => {
      try {
        // const result = await fetch("http://localhost:8000");
        socket.on("server-connection-message", (data) => {
          console.log(data);
          dispatch({
            type: globalReducerActions.handlePlayerColor,
            payload: {
              myColor: data?.color,
            },
          });
        });
        socket.emit("player-joined-verify", playerName);
        socket.on("opponent-connected", (data) => {
          console.log(data);
        });
        socket.on("opponent-piece-moved", (data) => {
          console.log("the opponent moved: ", data);
          
        });
      } catch (err) {
        console.log(err);
      }
    })();
  }, []);`

Please fill the following code example:

Socket.IO server version: `x.y.z`

*Server*

```js
import { Server } from "socket.io";

const io = new Server(3000, {});

io.on("connection", (socket) => {
  console.log(`connect ${socket.id}`);

  socket.on("disconnect", () => {
    console.log(`disconnect ${socket.id}`);
  });
});
```

client emission of event here
`const emitPieceMovement = (data) => {
  socket.emit("piece-moved", data);
  console.log("emmited piece movement");
};`

Socket.IO client version: `^4.1.2`

*Client*

```js
import { io } from "socket.io-client";

const socket = io("ws://localhost:3000/", {});

socket.on("connect", () => {
  console.log(`connect ${socket.id}`);
});

socket.on("disconnect", () => {
  console.log("disconnect");
});
```

**Expected behavior**

**Platform:**
 - Device: [e.g. Samsung S8]
 - OS: [e.g. Android 9.2]

**Additional context**
https://www.loom.com/share/39c2debfa131422493d1957b65733dee``

**Comment by darrachequesne** [comment]
Hi! That's quite a long example! Could you please reduce your issue to the most basic example (by forking the example [here](https://github.com/socketio/socket.io-fiddle)), so we can help you?

**Comment by 2006aman-github** [comment]
> Hi! That's quite a long example! Could you please reduce your issue to the most basic example (by forking the example [here](https://github.com/socketio/socket.io-fiddle)), so we can help you?

Well I actually got the issue solved somehow magically

**Comment by vvv201214** [comment]
how you solved this issue ?
