### ISSUE TITLE
io.("/")..adapter.on("delete-room", (room) => { }) give me both socket id and room name

### ISSUE THREAD

**Issue by soarying** [socketio/socket.io#3952]
**Describe the bug**
according to the document on socket io web site https://socket.io/docs/v3/rooms/.
the event delete-room (argument: room) will only return room.
that is why I am doing this:

io.("/").adapter.on("delete-room", (room) => {
		console.log(room);
	});

**Expected behavior**
I should only get the room name instead of it return socket userID and room name
**Platform:**
win 10
**Additional context**

**Comment by darrachequesne** [comment]
Hi! This behavior is expected. The socket ID is actually used as a room name, which allows to do private messaging:

```js
io.to(theSocketId).emit("hello");
```

So the "delete-room" event will include the socket ID.

```js
io.on("connection", (socket) => {
  socket.join("room1");
  socket.disconnect();
});

io.of("/").adapter.on("delete-room", (room) => {
  console.log(room); // called twice, the first time with "room1" and the second with the socket ID
});
```

**Comment by soarying** [comment]
thank you for replying to me.
Is there any way I can only have a room name instead of giving me Id and room name?

**Comment by darrachequesne** [comment]
You should be able to check if the `room` argument is a socket ID with:

```js
io.of("/").adapter.on("delete-room", (room) => {
  const isSid = io.of("/").sockets.has(room);
  if (!sid) {
    // room is an actual room
  }
});
```

**Comment by soarying** [comment]
Thank you so much!!
