### ISSUE TITLE
Upgrade engine.io to newest version to remove ws audit failure

### ISSUE THREAD

**Issue by Jakesterwars** [socketio/socket.io#3959]
I've been getting an audit failure for socket.io relating to engine.io and would like to request this upgrade here as well since the dependabot handled the upgrade there.

https://www.npmjs.com/advisories/1748 for reference.

**Comment by darrachequesne** [comment]
Which version is impacted? Doesn't `npm audit fix` actually fix the issue?

**Comment by Jakesterwars** [comment]
Yeah I ended up regenerating my yarn lock file and it went away. Just a bad sha then from my old lock.
