### ISSUE TITLE
Why does "polling" fail for some users (but not all)?

### ISSUE THREAD

**Issue by saeho** [socketio/socket.io#3965]
I just finished debugging a handful of users (about 50%) who could not connect to the socket io server after I upgraded to v4.

After much debugging I found out that the default transports option ["polling", "websocket"] does not work for all users because "polling" fails for them. I was only able to fix it by manually setting it to ["websocket"] or ["websocket","polliing"]

2 Questions:

1. If "polling" fails, then "websocket" should have been attempted, but it wasn't attempted, why? (Is this a bug?)

2. What causes "polling" to fail for some but not all users?

**Comment by darrachequesne** [comment]
That sounds really weird indeed.

Was there any error in the console? Maybe related to CORS? Or is it only related to a given browser/OS configuration?

HTTP long-polling is more or less taken for granted in the current implementation, but if the connection fails there's no fallback to websocket. The related code is here: https://github.com/socketio/engine.io-client/blob/52847fd958f8efa090542f40c9d190f02b5b0561/lib/socket.js#L185-L192

**Comment by saeho** [comment]
There was no error in the console, other than a 400 error (from the server) in front-end. Which I couldn't see because I didn't experience this error, so I had to get the user to screenshot it to me.

I don't think it's CORS, because switching from default (["polling","websocket"]) to ["websocket"] or ["websocket","polling"] works.

I don't think it's browser either, because for many users who experienced this problem (roughly 50%), they couldn't access both the app AND also the website. Thereby leading me to believe it's something to do with... the ISP? 

>  if the connection fails there's no fallback to websocket

I swear, I read somewhere in the website documentation that transports DO fallback... If it doesn't fallback, then why does it accept an array...?

Lastly, given how I found multiple questions/problems about transports not working (and some of them, the solution was to use ["websocket"]), I think the default should change to ["websocket","polling"] and not ["polling","websocket"]...

**Comment by darrachequesne** [comment]
> There was no error in the console, other than a 400 error (from the server) in front-end.

An HTTP 400 error could mean that sticky sessions are not enabled. Which would explain why switching to WebSocket only would fix the issue.

You can check https://socket.io/docs/v4/troubleshooting-connection-issues/

You could also listen to the `connection_error` event on the server-side:

```js
io.engine.on("connection_error", (err) => {
  console.log(err.req);	     // the request object
  console.log(err.code);     // the error code, for example 1
  console.log(err.message);  // the error message, for example "Session ID unknown"
  console.log(err.context);  // some additional error context
});
```

> I don't think it's CORS, because switching from default (["polling","websocket"]) to ["websocket"] or ["websocket","polling"] works.

WebSocket connections are not impacted by CORS, so I think it could be explained by CORS, but it does not result in HTTP 400 errors (only some errors in the browser console).

> I don't think it's browser either, because for many users who experienced this problem (roughly 50%), they couldn't access both the app AND also the website.

Would you have access to the user agents? That could maybe help us for the investigation.

> Lastly, given how I found multiple questions/problems about transports not working (and some of them, the solution was to use ["websocket"]), I think the default should change to ["websocket","polling"] and not ["polling","websocket"]...

Fair question. The biggest problem with `polling` is that you must enable sticky session when scaling to multiple nodes and correctly configure CORS, hence all the related issues.

**Comment by saeho** [comment]
You are right, I just read your troubleshoot guide in detail and found exactly the problem.

I was having trouble getting {withCredentials: true} to work and just gave that up without reading in detail for speed.

My apologies and thank you for the help.

**Comment by saeho** [comment]
@darrachequesne I have one last question. How can I set up the CORS for a mobile app where there is no domain to match?

**Comment by darrachequesne** [comment]
@saeho "mobile app" is quite vague these days. Native app? React native? Cordova?...

**Comment by saeho** [comment]
React Native, thanks for the help, I'm aware this may be better question for StackOverflow, you're too generous.
