### ISSUE TITLE
Socket connects and disconnects multiple times for a same user 

### ISSUE THREAD

**Issue by ghirihari** [socketio/socket.io#3975]
### When the socket get created, same client gets connected and disconnected to the server multiple times.
**Server Side Log**
![image](https://user-images.githubusercontent.com/33194095/121990228-0b792800-cdbb-11eb-974f-1a83e71c6fbc.png)

**Client Side Log**
![image](https://user-images.githubusercontent.com/33194095/121990307-2d72aa80-cdbb-11eb-94e6-b3094274068a.png)

**Server code**
```
const httpServer = require("http").createServer();
const io = require("socket.io")(httpServer);

io.on("connection", (socket) => {
  console.log("Connected",socket.id)
});

httpServer.listen(3030);

```
**Client Code**
```
    import React from 'react';
    import { io } from "socket.io-client";
    
    class Room extends React.Component{
      componentDidMount = () =>{
        const socket = io("http://localhost:3030/");
      }
      render(){
        return (
          <div className="room">
            <div className="container-fluid">
              <label className="subHeading">The Notorious mma</label>
            </div>
          </div>
        );
      }
    }
    export default Room;

```

**Comment by 1337-ishaan** [comment]
try replacing your socket declaration to 

`const socket = io(URL, { autoConnect: false });`

This will basically not force a user to keep on connecting

**Comment by darrachequesne** [comment]
@ghirihari I see two possible explanations:

- either several Room components are created
- or the file gets hot module reloaded but the previous connection is not properly closed

Could that explain your issue?

**Comment by diptenbhut** [comment]
It seems you're calling Room component at multiple places in App file.
to avoid socket duplication issue.
You need to create a separate class file which handles socket connection/ disconnection and event handles.

**Comment by 1337-ishaan** [comment]
@ghirihari pls check out this repo, for reference 

[private-chat-react](https://github.com/1337-ishaan/chat-react)

**Comment by Ging123** [comment]
> autoConnect: false

DUDE THANK U, U SAVE MY ASS

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by k-wilmeth** [comment]
I am having similar issues

I have a react client that creates multiple socket connections because during a process, a page is visited multiple times causing a second socket to be opened on the second page load. I disconnect from the first connection when the component unmounts but I still see log messages indicating 2 different sockets are receiving the same messages from the node server

Any help would be much appreciated! 🙏 

React code
```js

const socketRef = useRef(null);
const [complete, setComplete] = useState(false);

/* Connect to socket ONE time only */
useEffect(() => {
  socketRef.current = io.connect(BACKEND_URL);
  console.log('connected to socket');

  return () => {
    console.log('disconnecting from socket');
    socketRef.current.disconnect();
  };
}, [])

useEffect(() => {
    if (socketRef.current) {
      // Handle incoming messages from custom socket event "socket_data"
      socketRef.current.on('socket_data', body => {
        if (body?.status === 'COMPLETED') {
          console.log('Updating Progress as COMPLETED!');
          updateProgressBar(body);
          setComplete(true);
        } else {
          /* When I un-comment this line, the messages from node-server come in very slowly because of multiple socket connections */
          //updateProgressBar(body);
        }
      });

      socketRef.current.on('connect_error', err => {
        console.log(`connect_error due to ${err.message}`);
      });

      socketRef.current.on('error', err => {
        console.log(`Socket error due to ${err.message}`);
      });
    }

  }
}, [downloads?.length]);

/* Close socket when process completes */
useEffect(() => {
  if (complete) {
    console.log('Process complete! disconnecting socket...');
    socketRef?.current?.disconnect();
  }
}, [complete]);
```

Node server code:
```js
let ioInstance;

module.exports = function(server) {
  const io = require("socket.io")(server, {
    cors: {
      origin: "http://localhost:9000",
      methods: ["GET", "POST"]
    }
  });

  // When a new client connects to the server
  io.on("connection", socket => {
    console.log("New Client Connected", socket.id);

    // Handle outgoing messages from custom socket event "socket_data"
    const socketEventName = "socket_data";
    socket.once(socketEventName, function(data) {
      io.sockets.emit("chat", data);
    });

    socket.on("disconnect", () => {
      console.log("Client disconnected");
    });

    socket.on("connect_error", (err) => {
      console.log(`connect_error due to ${err.message}`);
    });

  });

  ioInstance = io;
  return io;
};

module.exports.getIO = () => {
  if (!ioInstance) {
    throw new Error(
      "Must call module constructor function before you can get the IO instance"
    );
  }
  return ioInstance;
};
```

**Comment by Lakshay-art** [comment]
> try replacing your socket declaration to
> 
> `const socket = io(URL, { autoConnect: false });`
> 
> This will basically not force a user to keep on connecting

just connect while emitting and receiving an event, it will prevent extra calls

**Comment by Isidro1234** [comment]
> It seems you're calling Room component at multiple places in App file. to avoid socket duplication issue. You need to create a separate class file which handles socket connection/ disconnection and event handles.

underrated comment. Thanks, broh. you solved my problem
