### ISSUE TITLE
What happens to the queued packets when socket is reconnected? Is there even a queue for packets?

### ISSUE THREAD

**Issue by tomruk** [socketio/socket.io#3978]
I asked a question [here](https://github.com/socketio/socket.io/discussions/3971) but didn't get an answer. So i'm opening an issue.

By the way, i'm asking for socket.io-client.

As you can see [here](https://github.com/socketio/socket.io-client/blob/master/lib/socket.ts#L204) and [here](https://github.com/socketio/socket.io-client/blob/master/lib/manager.ts#L683), when a packet needs to be sent, the packet is encoded and sent directly with Engine.IO socket.

Is there a queue for packets in case packet never gets sent? What happens when a packet send fails?

**Comment by darrachequesne** [comment]
Let's continue the discussion [here](https://github.com/socketio/socket.io/discussions/3971), if you will. Thanks!
