### ISSUE TITLE
Socket io dosen't detect always disconnect

### ISSUE THREAD

**Issue by fadihanna123** [socketio/socket.io#4006]
**Disconnecting dosen't work always**
When Socket io disconnecting except Mongodb database to remove online user but it dosen't work sometimes. Record in mongodb database stay sometimes especiellay if user closed the browser for long time.
Socket.IO server version: `4.1.2`

Server side:
```js
import { Server, Socket } from "socket.io";
import "./config";

import { MsgModel } from "./models";
import { JoinListModel } from "./models";
import { callUserTypes } from "./typings";

const io = new Server(5000, {
  cors: {
    origin: ["http://localhost:3000"],
    credentials: true,
  },
});

io.on("connect_error", (err: any) => {
  console.log(`connect_error due to ${err.message}`);
});

io.on("connection", async (socket: Socket) => {
  console.log(`✅ Client ${socket.id} has connected!`);

  socket.emit("me", socket.id);


  socket.on("Join", async (data: any) => {
    const findIt =
      (await JoinListModel.find({ nickName: data.nickName })).length > 0;
    if (findIt) {
      socket.emit("loginMsg", "Danger");
    } else {
      const JoinList = new JoinListModel();
      JoinList.id = socket.id;
      JoinList.nickName = data.nickName;
      JoinList.joinedDatenTime = new Date();
      await JoinList.save();
      const onlineListData = await JoinListModel.find({});
      io.sockets.emit("OnlineList", onlineListData);
      socket.emit("loginMsg", "Success");
    }

    console.log(`${data.nickName} is joined!`);
  });

  socket.on("disconnect", async () => {
    await JoinListModel.deleteOne({ id: socket.id });
    console.log(`🚫 Client ${socket.id} has disconnected`);
    const onlineListData = await JoinListModel.find({});
    io.sockets.emit("OnlineList", onlineListData);
  });
});
```
Client:
```js    
const [socket, setSocket] = useState<Socket | null>(null);

  useEffect(() => {
   const socket = io("http://localhost:5000");
   setSocket(socket);
},[]);
```
Please help? Why socket io dosen't detect that?

EDIT: edited by me (@darrachequesne) for clarity

**Comment by darrachequesne** [comment]
Hi! Unfortunately I wasn't able to reproduce.

If I understand correctly the code you provided, a given username must be unique. What happens if the user reloads the page or open a new tab?

See also: https://socket.io/get-started/private-messaging-part-1/

**Comment by fadihanna123** [comment]
If i don't close the tab or if i shutdown computer without closing tab or window. It will not disconnect socket io. There are any way to check if user left after some time?

**Comment by darrachequesne** [comment]
> If i don't close the tab or if i shutdown computer without closing tab or window. It will not disconnect socket io.

I don't think this is possible. The disconnection will either be detected when the TCP connection is closed, or when the client fails to send the heartbeat.

Are you able to reproduce the issue?

**Comment by fadihanna123** [comment]
I tried to reload page or close the tab but sometimes it ignore removing online user from database it means that socket io doesn't detect disconnecting always of some reason. Can you help me, please?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
