### ISSUE TITLE
server v4 disconnects ios client 16 with no namespace joined yet, but v2 server works

### ISSUE THREAD

**Issue by datacosmos** [socketio/socket.io#4007]
Hi there,

I am trying to upgrade socket io to 4.1.2:
  "dependencies": {
    "cookies": "^0.7.0",
    "express": "^4.17.1",
    "hashmap": "^2.3.0",
    "socket.io": "^4.1.2",
    "winston": "^2.4.0"
  }

I am creating the server as follows:

```
const express = require('express')
var app = express();
var http = require('http').createServer(app);
var io = require('socket.io')(http, {
        cors: {
                origin: "*:*",
                methods: ["GET", "POST"]
        },
        transports: ["websocket","xhr-polling","polling"],
        allowEIO3: true // allows socket 2 clients to connect
});
var Cookies = require( "cookies" );
var sockets = {};
var domainSockets = {};
const https = require('https');

app.use( express.json() );

```

When I am connection with Socket IO 16.0.1 Swift Client (forcing websocket transport), I get the following log messages and the client is not able to establish a connection:

>  engine handshaking client "7jYxIcD2QkCuvEaHAAAA" +0ms
>   socket.io:server incoming connection with id 7jYxIcD2QkCuvEaHAAAA +1m
> 
> 
>   socket.io:client no namespace joined yet, close the client +0ms
>   socket.io:client forcing transport close +1ms
>   socket.io:client client close with reason forced close +1ms
>   socket.io:client client close with reason forced server close +1ms
>   engine handshaking client "sUPaEgxhqOQxciouAAAB" +45s
>   socket.io:server incoming connection with id sUPaEgxhqOQxciouAAAB +45s

With socket.io Version 2 the same client Code works without any issues:

> 
>   engine handshaking client "P3A8GDfXXNwTbj7HAAAB" +30s
>   socket.io:server incoming connection with id P3A8GDfXXNwTbj7HAAAB +30s
>   socket.io:client connecting to namespace / +165ms
>   socket.io:namespace adding socket to nsp / +30s
>   socket.io:socket socket connected - writing packet +166ms

It seems that if a client (electron) is polling first, the v4 Server establishes also a connection. But the websocket transport forcing ios client is not able to connect.

The connection is via an apache proxy (for both versions), switching protocols etc. works.
Any ideas what is wrong here?

TIA

**Comment by darrachequesne** [comment]
Hi I'm not able to reproduce: https://github.com/socketio/socket.io-swift-fiddle

Could you please check?

**Comment by datacosmos** [comment]
Thank you very much @darrachequesne !
This fiddle was perfectly helpful - with that  I was able to systematically hunt the problem down. 
On my iOS client I connected (only) with   socketManager.connect() and that worked fine with socket.io server v2. 

However this seems to have changed from v2 to v4 and now it works only when I connect the client with SocketIOClient.connect() - so was there an API change?

**Comment by darrachequesne** [comment]
I think I understand what is happening here:

In v2, the socket instance for the `/` namespace was implicitly connected: https://github.com/socketio/socket.io-client-swift/blob/d031afdbc4aaf87c3b84cbec04bfaa7666e1fa0a/Source/SocketIO/Manager/SocketManager.swift#L354-L356

In v4, this implicit connection was removed (the socket instance must send a CONNECT packet first), and the `manager.connect()` method filters out the inactive socket instances: https://github.com/socketio/socket.io-client-swift/blob/d031afdbc4aaf87c3b84cbec04bfaa7666e1fa0a/Source/SocketIO/Manager/SocketManager.swift#L358-L364

And the socket instance is inactive if you don't call `socket.connect()`: https://github.com/socketio/socket.io-client-swift/blob/d031afdbc4aaf87c3b84cbec04bfaa7666e1fa0a/Source/SocketIO/Client/SocketIOClient.swift#L72

Hence your issue. Does that make sense?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
