### ISSUE TITLE
Expose io state

### ISSUE THREAD

**Issue by andrejleitner** [socketio/socket.io#4013]
Just an idea, would it make sense to expose (properly typed) `socket.io._readyState`?
There should be 3 possible values: `'closed' | 'opening' | 'open'`.

**Comment by darrachequesne** [comment]
That's a good question! For the record, it was simply called `readyState` in Socket.IO [v2](https://github.com/socketio/socket.io-client/blob/de2ccff492b37b0fb83124f83c7614d413588037/lib/manager.js#L59).

I'm not against making it public though. Do you have a specific use case for this?
