### ISSUE TITLE
Blocking Cross origin requests through cors 

### ISSUE THREAD

**Issue by abhijatyatewari** [socketio/socket.io#4014]
**Is your feature request related to a problem? Please describe.**
CORS object only allows to handle CORS requests but should also allow to block them

**Describe the solution you'd like**
Pass a whitelist of hosts to CORS object to be only allowed to request for web-socket connection.  

**Describe alternatives you've considered**
provide a flag to stop all CORS requests

**Comment by darrachequesne** [comment]
Hi! For this use case, you can use the `allowRequest` option:

```js
const io = require("socket.io")(httpServer, {
  allowRequest: (req, callback) => {
    const noOriginHeader = req.headers.origin === undefined;
    callback(null, noOriginHeader);
  }
});
```

I've added it here: https://socket.io/docs/v4/handling-cors/

**Comment by abhijatyatewari** [comment]
This works with whitelist , but is not able to block CORs by default without providing whitelist.

**Comment by darrachequesne** [comment]
> but is not able to block CORs by default without providing whitelist.

I'm not sure to understand. This is what I get with the `allowRequest` option above:

```
curl "http://localhost:3000/socket.io/?EIO=4&transport=polling" -v
< HTTP/1.1 200 OK

curl -H "origin: example.com" "http://localhost:3000/socket.io/?EIO=4&transport=polling" -v
< HTTP/1.1 403 Forbidden
```

Am I missing something?

**Comment by abhijatyatewari** [comment]
In request from  web Browser client Origin Header is sent anyway regardless its coming from same server or not and thus all requests fail. but requests from same server needs to be allowed by default.
