### ISSUE TITLE
Connect to server without query parameters

### ISSUE THREAD

**Issue by vbaptistella** [socketio/socket.io#4017]
I am currently working on a project that is already in production using socket.io, and it needs to migrate to a gateway that blocks any type of query string and rejects the connection.

I could only find information about adding more parameters on the docs, but is there a way to make socket.io work without (or remove) the default query parameters (EIO, transport and t)?

**Comment by darrachequesne** [comment]
No, there is currently no way to do this.

> it needs to migrate to a gateway that blocks any type of query string

That's... interesting. Why is that?
