### ISSUE TITLE
set a cookie using socket.io

### ISSUE THREAD

**Issue by destramic** [socketio/socket.io#4025]
how can i please set a cookie inside socket.io please? ive read the manuel and have has a googled but nothing of much substance has been found.

` socket.on('test', function(){
    	// var cookies = cookie.parse(socket.handshake.headers.cookie);  
    	console.log('cookies ', cookies );
});`

thank you

**Comment by darrachequesne** [comment]
Hi! You can set a cookie at the beginning of the Socket.IO session:

```js
const cookie = require("cookie");

io.engine.on("initial_headers", (headers) => {
  const mycookie = cookie.serialize("mycookie", "1234", {
    sameSite: true
  });
  headers["set-cookie"] = mycookie;
});

io.on("connection", (socket) => {
  const cookies = cookie.parse(socket.handshake.headers.cookie);
  console.log(cookies.mycookie); // prints "1234"
});
```

Please note that this is not possible once the Socket.IO session is initialized, as cookies cannot be sent anymore when the WebSocket session is established.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
