### ISSUE TITLE
Disconnected sockets are never removed from memory

### ISSUE THREAD

**Issue by Novivy** [socketio/socket.io#4028]
**Describe the bug**
When a socket is disconnected, the server doesn't remove it from the memory.

**To Reproduce**

See https://github.com/socketio/socket.io/issues/2427#issuecomment-882599567

**Expected behavior**
Disconnected socket shouldn't be kept in memory forever

**Platform:**
v4.1.3

**Additional context**

**Comment by darrachequesne** [comment]
For future readers:

I was not able to reproduce the issue.

Node version: `v16.13.1`
Socket.IO version: `v4.4.1`

I used the scripts from https://github.com/socketio/socket.io-benchmarks, here is the graph with 10 000 clients:

![Screenshot from 2022-03-31 23-36-43](https://user-images.githubusercontent.com/13031701/161155715-68f13a91-c337-4169-b6bc-4448d2e3c15c.png)

Please reopen if needed.
