### ISSUE TITLE
Stop socket.io complaining in the browser when the server is down

### ISSUE THREAD

**Issue by draeder** [socketio/socket.io#4032]
**Is your feature request related to a problem? Please describe.**
When the socket.io server is down, the following is logged repeatedly in the browser.

```js
polling-xhr.js:206 GET http://localhost:3000/socket.io/?EIO=4&transport=polling&t=NhdlRB- net::ERR_CONNECTION_REFUSED
```

When a browser experiences this for a long time it causes excessive use of system resources by the browser.

**Describe the solution you'd like**
Suppress this error. 

It should be handled by `io.on('error', err =>{})` and up to the developer to handle.

**Describe alternatives you've considered**
I haven't found any way around this error. It's built into socket.io / one of its dependencies.

**Additional context**
N/A

**Comment by draeder** [comment]
This actually looks like it's a bug. 

Line 206 of polling-xhr.js has `xhr.send(this.data)` which should be in its own try/catch block. If the server is down it should emit an error.

**Comment by darrachequesne** [comment]
Hi! Are you referring to the browser logs in the console?

- Chrome:

![Screenshot from 2021-07-28 08-55-41](https://user-images.githubusercontent.com/13031701/127277949-9cd2d7cd-2811-438d-b2ca-2e6291a3521b.png)

- Firefox:

![Screenshot from 2021-07-28 08-56-12](https://user-images.githubusercontent.com/13031701/127277957-027666e7-4235-40d1-ab08-2d41dc5ed694.png)

In that case, there is nothing we can do on our side, but you should be able to hide those logs from the console (there's a "Hide network" option on Chrome).

Related: https://socket.io/docs/v4/logging-and-debugging/#Error-logs-in-the-browser-console

**Comment by draeder** [comment]
Do you know which dependency polling-xhr.js is from? I can open an issue in that repo if so. 

Either way, I'm using this as a workaround:

```js
   socket.io.on("reconnect_error", (error) => {
     socket.disconnect()
   })
```

**Comment by darrachequesne** [comment]
The `polling-xhr` file comes from the `engine.io-client` repository: https://github.com/socketio/engine.io-client/blob/master/lib/transports/polling-xhr.js

You can disable automatic reconnection:

```js
const socket = io({
  reconnection: false // defaults to true
});
```

Documentation: https://socket.io/docs/v4/client-initialization/#reconnection

Or limit the number of reconnection attempts:

```js
const socket = io({
  reconnectionAttempts: 5 // defaults to Infinity
});
```

Documentation: https://socket.io/docs/v4/client-initialization/#reconnectionAttempts

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
