### ISSUE TITLE
Send reason for connection to server

### ISSUE THREAD

**Issue by gillerby** [socketio/socket.io#4033]
**Is your feature request related to a problem? Please describe.**
When a socket connects to the server, e.g., for a chat application, I do not know out of the box if this is a reconnect or a new connection. 
If it is a reconnect, I'd like to add the user to his previous room, while a new user would get a new one, etc etc.

**Describe the solution you'd like**
Ideally somehow the reason for connection would be available in the 'connection' block.
e.g., by quering socket.connReason

```
io.on("connection", (socket) => {
  // ...
});
```

**Comment by darrachequesne** [comment]
For future readers:

Please check https://socket.io/docs/v4/connection-state-recovery
