### ISSUE TITLE
getting an undefined error when connecting to socket.io-server

### ISSUE THREAD

**Issue by samleurs247** [socketio/socket.io#4038]
I have the following (simple) socket.io-servercode:
````
const express = require("express");
const app = express();
const http = require("http");
const server = http.createServer(app);
const io = require("socket.io")(server);

io.on("connection", (socket) => {
  console.log("New client connected");
  socket.on("disconnect", () => {
    console.log("Client disconnected");
  });
});

server.listen(4000, () => console.log('Server running...'));
````

I cannot connect to this server at all. When testing with a React-frontend, or with a websocket tester extension in chrome, I get the following error:
<img width="1013" alt="Schermafbeelding 2021-08-03 om 19 13 40" src="https://user-images.githubusercontent.com/58610521/128057883-08d06170-8b02-40a0-9791-710c519a0d37.png">
As you can see, there is no specific error why it fails.

I'm using a macbook pro running macOS big sur. I'm testing with chrome and safari, both don't work.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by darrachequesne** [comment]
Note: Socket.IO is not a WebSocket server, so you won't be able to connect from a plain WebSocket client.

See also: https://socket.io/docs/v4/#what-socketio-is-not
