### ISSUE TITLE
WebSocket connection to failed: Invalid frame header

### ISSUE THREAD

**Issue by chrisdlangton** [socketio/socket.io#4039]
Opening a new one for visibility

Same issue here also. adding setup for a recent example.

**dependencies**

```json
{
        "express": "^4.17.1",
        "nodemon": "^2.0.12",
        "socket.io": "^4.1.3"
}
```
**src/index.js**
```js
const app = require('express')()
const server = require('http').createServer(app)
const io = require('socket.io')(server)
const fs = require('fs')

app.set('port', process.env.SOCKETS_PORT || 5080)

io.on('connection', socket => {
    socket.on('disconnect', data => {
        console.log(`client disconnect ${data}`)
    })

    socket.on('checkin', uuid => {
        socket.join(uuid)
        console.log(`checkin from ${uuid}`)
    })
})
app.get('/healthcheck', (_, res) => {
    res.status(200).send("ok")
})
server.listen(app.get('port'), () => {
    fs.writeFile('/srv/app/nodemon.pid', process.pid.toString(), err => {
        if (err) throw err
    })
    console.log(`listening on *:${app.get('port')}`)
})
```

Start with `/node_modules/nodemon/bin/nodemon.js -V --no-stdin start` which produces:
```
[nodemon] src/index.js
[nodemon] starting `node start src/index.js`
[nodemon] forking
[nodemon] child pid: 297
[nodemon] files triggering change check: nodemon.pid
listening on *:5080
```

```js
socket = io('wss://localhost', { transports: ['websocket'] })
```

Chrome says
```
Request URL: wss://localhost/socket.io/?EIO=3&transport=websocket
Request Method: GET
Status Code: 101 Switching Protocols
HTTP/1.1 101 Switching Protocols
Server: nginx
Date: Wed, 04 Aug 2021 03:56:36 GMT
Connection: upgrade
Upgrade: websocket
```
and complains in the console with:
```
WebSocket connection to 'wss://localhost/socket.io/?EIO=3&transport=websocket' failed: Invalid frame header
e @ VM415:1
n.doOpen @ socket.io.2.3.0.min.js:8
n.open @ socket.io.2.3.0.min.js:6
n.open @ socket.io.2.3.0.min.js:6
n @ socket.io.2.3.0.min.js:6
n @ socket.io.2.3.0.min.js:6
n.open.n.connect @ socket.io.2.3.0.min.js:6
(anonymous) @ socket.io.2.3.0.min.js:6
```
There was no output on the server-side from nginx or node

About the obvious forward proxy, so that is nginx and the config is fairly simple (joke), TLS via letsencrypt:
```
server {
    listen                  443 ssl;
    listen                  [::]:443 ssl;
    server_name             localhost;
    root                    /srv/app/;
    server_tokens           off;
    client_max_body_size    32M;
    underscores_in_headers  on;

    ssl_certificate /etc/letsencrypt/live/localhost/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/localhost/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        set $test  $request_method; 
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'https://localhost';
            add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
            add_header 'Content-Length' 0;
            return 204;
        }
        if ($request_method = 'GET') {
            add_header 'Access-Control-Allow-Origin' 'https://localhost';
            add_header 'Access-Control-Allow-Credentials' 'tws.trivialsecrue';
        }
        if ($request_uri = '/socket.io/') {
             set $test  "${test}OK"; 
        }
        if ($test != GETOK) { 
            return 404;
            break;
        } 
    }
    location /socket.io/ {
        proxy_cache             off;
        proxy_no_cache          1;
        proxy_cache_bypass      1;
        access_log              on;
        server_tokens           off;
        proxy_pass              http://localhost:5080/socket.io/;
        proxy_http_version      1.1;
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        Connection 'Upgrade';
        proxy_set_header        Host             $host;
        proxy_set_header        X-Real-IP        $remote_addr;
        proxy_set_header        X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto https;
        proxy_pass_header       device_id;
    }
}
```
This configuration is not intended to allow anything otehr than socket.io websockets through, not even the `/healthcheck` from express.js (which is kept there as a test for this example).

I've exhausted all my SO and Github issue searches, this thread seems to be the closest match for my problem and it appears many others have the same issue for several years.

I can only conclude that socket.io is not suitable for secure environments that utilise CORS, this and many other results related to this indicate people try and give up which only results in insecure deployments.

_Originally posted by @chrisdlangton in https://github.com/socketio/socket.io/issues/2557#issuecomment-892345563_

**Comment by chrisdlangton** [comment]
The server and client `socket.io` versions were not matching.
The client was referencing `2.3.0` and the server was installing `4.1.3` as shown above.
Matching the socket.io version solved this problem for me.

**Comment by HakzTV** [comment]
Hey, sorry but i tried your solution but it doesn't work. It still gives me 
"WebSocket connection to 'ws://localhost:3000/socket.io/?EIO=4&transport=websocket&sid=u4pdcuZeebUYcuCKAAAG' failed: Invalid frame header"

**Comment by chrisdlangton** [comment]
> Hey, sorry but i tried your solution but it doesn't work. It still gives me "WebSocket connection to 'ws://localhost:3000/socket.io/?EIO=4&transport=websocket&sid=u4pdcuZeebUYcuCKAAAG' failed: Invalid frame header" Could you please assist me?

You should open an Issue with your own troubleshooting and debugging as you will be having a new/different issue than this issue

**Comment by Olamide9949** [comment]
I have a similar issue with Websocket connection when I try to use simple-peer for peer connection.
Is there a fix for this?

**Comment by Pitrouflette** [comment]
@Olamide9949 yes, same situation here... I was wondering if you had solved your issue and could clue me what to do !

**Comment by chrisdlangton** [comment]
All those thumbs down people don't understand what a closed issue means, so let me be blunt.

You're looking for assistance and you're asking for it and only I get the notification because the issue is closed the maintainers and others who might help never see your question

So, I reiterate, open a ticket for help

**Comment by Godwin9911** [comment]
This worked for me, I made them the same version number,  the "socket.io-client": "^4.5.0", and  "socket.io": "^4.5.0",
