### ISSUE TITLE
server disconnects when sending big data, server -> client

### ISSUE THREAD

**Issue by luckyyyyy** [socketio/socket.io#4041]
**Describe the bug**
There is a problem with nodejs client.
chrome has no problem.

The server was disconnected when it sent a large amount of data.
The nodeJS client has a problem, the same code in Chrome has no problem.

**To Reproduce**
```js
const sio = require('socket.io-client');
const { Server } = require('socket.io');
const http = require('http');

const buf = [];
for (let index = 0; index < 6; index++) {
  buf.push(Buffer.from('1'.repeat(1 << 26)));
}
const buff = Buffer.concat(buf);

console.log(buff.length / 1024 / 1024);

const server = new Server(http.createServer(), {
  cors: {
    origin: '*',
    methods: ['GET', 'POST'],
  },
  maxHttpBufferSize: Infinity,
});

server.on('connect', (client) => {
  console.log('server send data');
  client.on('data', (data) => {
    console.log('size:', data.data.length / 1024 / 1024);
    client.emit('data', data);
  });
});

server.on('disconnect', (data) => {
  console.log('client disconnected');
});

server.listen(8005);

const client = sio('ws://localhost:8005', {
  transports: ['websocket'],
});

client.on('connect', () => {
  console.log('connect server');
  client.emit('data', {
    data: buff,
  });
});

client.on('disconnect', (data) => {
  console.log('server disconnected');
});

client.on('data', (data) => {
  console.log('callback', 'size:', data.data.length / 1024 / 1024);
});

```

**Platform:**
 - Device: macOS
 - OS: 11.5.1

    "socket.io": "^4.1.3",
    "socket.io-client": "^4.1.3",

![image](https://user-images.githubusercontent.com/9210430/128455232-d4d269e0-2914-48f2-bc9e-22fa8d2a503c.png)

![image](https://user-images.githubusercontent.com/9210430/128455262-9d714545-803e-4965-abeb-cf39cc957a85.png)

**Comment by saddamhussainthotlipallishaik** [comment]
same issue from my side also.. whenever I sent 60-70KB image it will go ..but whenever I sent more than(900KB and more) it, the connection is disconnecting...

**Comment by GlebStepenko** [comment]
In my case it helped me to change the maxPayload parameter on the server side.

**Comment by darrachequesne** [comment]
For future readers:

Please increase the `maxHttpBufferSize` value, which defaults to 1 MB.

Reference: https://socket.io/docs/v4/server-options/#maxhttpbuffersize

See also: https://socket.io/docs/v4/troubleshooting-connection-issues/#you-are-trying-to-send-a-huge-payload
