### ISSUE TITLE
How to set multiple origins for cors?

### ISSUE THREAD

**Issue by Mrbeyond** [socketio/socket.io#4048]
How to set multiple origin for the socket cors and why is version 3 and 4 not working in Flutter (socket.io-client)?
 
**Describe the solution you'd like**
I need help with setting multiple origins in version 3 or 4.
The current instance on the official page is like:
 cors: {
    origin: "https://example.com",
    methods: ["GET", "POST"]
  }

I need something like :
 cors: {
    origin: ["https://main.com", "https://admin.main.com"],
    or 
    origin: "https://main.com , https://admin.main.com",

    methods: ["GET", "POST"]
  }

Also how to I set origin for android apps like flutter app socket.io-client?

Please I really need help with this ASAP.

**Comment by darrachequesne** [comment]
Hi! You can totally pass an array of origins:

```js
const io = require("socket.io")(httpServer, {
  cors: {
    origin: ["https://main.com", "https://admin.main.com"],
    methods: ["GET", "POST"]
  }
});
```

Reference: https://github.com/expressjs/cors#configuration-options

**Comment by darrachequesne** [comment]
I updated the documentation here: https://socket.io/docs/v4/server-options/#cors
