### ISSUE TITLE
Version diff warning

### ISSUE THREAD

**Issue by ReArno** [socketio/socket.io#4051]
**Is your feature request related to a problem? Please describe.**
Last time I had a problem. When I start developing a service, which uses the socket io on the client and on the server-side. The problem was when the server and the client were on a different package version after an update in the package.json. And after this, the client doesn't connect to the server, and in this case, we don't have an error.

**Describe the solution you'd like**
I would like a more clear error, for example in the handshake request, the server can validate the client socket version, and can throw an error if the difference is too big.

**Comment by darrachequesne** [comment]
For future readers:

The server now replies with `{"code":5,"message":"Unsupported protocol version"}` (HTTP 400) if the version of the client is too low.

Similarly, a v3/v4 client will emit a "connect_error" if it reaches a v2 server: https://github.com/socketio/socket.io-client/blob/781d753a626d01e675056a2ff4e27f5dd599564f/lib/socket.ts#L668-L673

Please reopen if needed.
