### ISSUE TITLE
Event acknowledgements - no callback is provided

### ISSUE THREAD

**Issue by silverbucket** [socketio/socket.io#4057]
**Describe the bug**
Regardless if I add a callback on the client side and expect one on the server side, none show up in the parameters of an event callback as described here: https://socket.io/docs/v4/emitting-events/#Acknowledgements

**To Reproduce**

Socket.IO server version: `4.1.3`

*Server*

I've tried both using `...args` notation, and explicitly expecting `(msg, cb)` neither of which make a difference.

```js
import { Server } from "socket.io";

const io = new Server(3000, {});

io.on("connection", (socket) => {
  console.log(`connect ${socket.id}`);

  socket.on("disconnect", () => {
    console.log(`disconnect ${socket.id}`);
  });

  socket.on('message', (...args) => { 
    console.log(args);  // [ 'foobar' ]
  });  
});
```

Socket.IO client version: `4.1.3`

*Client*

```js
import { io } from "socket.io-client";

const socket = io("ws://localhost:3000/", {});

socket.on("connect", () => {
  console.log(`connect ${socket.id}`);

  socket.emit('message', 'foobar', (data) => { console.log('Event receipt acknowledged'); });
});

socket.on("disconnect", () => {
  console.log("disconnect");
});
```

**Expected behavior**

A callback should be provided on the server side to confirm acknowledgement/completion of the event, as described in the docs.

**Platform:**
 - Device: macos
 - OS: macos 10.15.7

**Comment by silverbucket** [comment]
Can I get some feedback as to whether this is, in fact, a bug or if there's something incorrect/incomplete in the documentation?

**Comment by darrachequesne** [comment]
Hi! I can't reproduce the issue: https://github.com/socketio/socket.io-fiddle/tree/issues/socket.io/4057

Could you please check?

**Comment by silverbucket** [comment]
Thank you @darrachequesne for taking the time to try to reproduce, you are correct that it all seems to work fine in the example. I believe the error may be with some injected javascript that might be intercepting events and processing some middlewares. So I'll close this as not a socket.io error.
