### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by SudoDios** [socketio/socket.io#4061]
Please add dark mode for socket IO site.
Thanks

**Comment by darrachequesne** [comment]
That's indeed a great idea :+1:

Let's add this to the to-do list for the rework of the website.

**Comment by SudoDios** [comment]
Is it good 👌.

**Comment by darrachequesne** [comment]
Done! https://socket.io/docs/v4/

**Comment by SudoDios** [comment]
👍👌
