### ISSUE TITLE
Duplicate `sendBuffer = []` 

### ISSUE THREAD

**Issue by shitpoet** [socketio/socket.io#4063]
For some reason `sendBuffer` is declared twice in `Socket` constructor of client script:

https://github.com/socketio/socket.io/blob/310f8557a794bb94291cf8d5ef5f31d8258a3338/client-dist/socket.io.js#L859-L868

As do `acks`, `ids`, and `flags`.

Not a big issue by itself, but can be a sign of some problem.

**Comment by darrachequesne** [comment]
Fixed by https://github.com/socketio/socket.io-client/commit/f3acddf9972abbe6832dd19bbbd13bcd2396fd65.
