### ISSUE TITLE
Problem closeOnBeforeunload

### ISSUE THREAD

**Issue by Madriix** [socketio/socket.io#4065]
**Describe the bug**
Customer parameter closeOnBeforeunload by default it is true, should be false

**To Reproduce**

Please fill the following code example:

Socket.IO server and client version: `4.1.3`

Read my post here https://github.com/socketio/socket.io/issues/4040#issuecomment-907566798

We would have to do a tutorial, for example a space "_Optimize socket.io 4.x to behave like socket.io 2.x_" and put the parameters like closeOnBeforeunload to false instead of true, and other things.

**Platform:**
 - Device: Firefox 91.0.2
 - OS: Windows 7 (x64)

**Comment by darrachequesne** [comment]
For future readers:

The `closeOnBeforeunload` option now defaults to `false`, which makes more sense.

Reference: https://socket.io/docs/v4/client-options/#closeonbeforeunload
