### ISSUE TITLE
Blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Socket IO(v4)

### ISSUE THREAD

**Issue by ALWISHARIFF** [socketio/socket.io#4069]
**Describe the bug**
I have a MERN stack app that is currently working perfectly on localhost on my PC but when I prepare for deployment I am RECEIVING AN ERROR 
```Access to XMLHttpRequest at 'http://localhost:3000/socket.io/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmM3YzUyNzI4MWM0NDQwNDdiM2IwZCIsImlhdCI6MTYzMDQzNTkyNSwiZXhwIjoyNTc3MTYzOTI1fQ.LJfFtnThV31y2P9YJOndskKxrC0dYTNDVy7ncgBRPGc&EIO=4&transport=polling&t=NkTZfRS' from origin 'http://209.97.149.47' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.```
This Error is from the console window when browse the website i hosted on digital ocean .Below are the Project config and the server configs NGINX.
MY Project Structure:
>backened(Node(express))
>frontend(React)

socket IO Initialization:
```
const express = require("express");
const app = express();
const http = require("http");
const server = http.createServer(app);
const cors = require("cors")
const asyncHandler = require("express-async-handler");
const io = require("socket.io")(server,{cors:{origin:"http://209.97.149.47",methods:["GET","POST"],credentials:true,allowedHeaders:["Access-Control-Allow-Origin:209.97.149.47"]}});
server.listen(5000, () => {
    console.log(`listening on *:${5000}`);
});
```
The Package.json Frontend React Project file I declared a proxy to the backened .of "proxy":"127.0.0.1/5000";
When I deploy I get a cors error below are deployment details 
>NGINX CONFIG FILE DEFAULT:
```
server {
server_name 209.97.149.47;
    add_header 'Access-Control-Allow-Origin' 'http://209.97.149.47';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
    location / {
        proxy_pass http://localhost:3000; #whatever port your app runs on
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

        location /socket.io/ {
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $host;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $host;
          proxy_pass http://localhost:3000;
   }
}
```

**To Reproduce**

I am unable to setup cors on the server it may be a bug

Socket.IO server version: `4.1.3`

*Server*

```js


const express = require("express");
const app = express();
const http = require("http");
const server = http.createServer(app);
const cors = require("cors")
app.use(cors())
const asyncHandler = require("express-async-handler");
const io = require("socket.io")(server,{cors:{origin:"http://209.97.149.47",methods:["GET","POST"],credentials:true,allowedHeaders:["Access-Control-Allow-Origin:209.97.149.47"]}});
server.listen(5000, () => {
    console.log(`listening on *:${5000}`);
});
```

Socket.IO client version: `4.1.3`

*Client*

```js
import { io } from "socket.io-client";

var socket = io("http://localhost:3000", {
        reconnection: true,
        reconnectionDelay: 500,
        reconnectionAttempts: 10,
      });
socket.on("connect", () => {
  console.log(`connect ${socket.id}`);
});

socket.on("disconnect", () => {
  console.log("disconnect");
});
```

**Expected behavior**
I am able to use the http routes the proxy is working great to the backened but the problem is when socket.io client connects to client the server looks like its not accepting my cors configs,My other api routes are working very fine only socket io isnt connecting!!!.Thanks

**Platform:**
 - Device: LENOVO THINKPAD
 - OS: WINDOWS 10

**Additional context**
Great package !!!

**Comment by ALWISHARIFF** [comment]
When i perform a curl request to the adress below i get a successful response,.
```
curl "http://localhost:3000/socket.io/?EIO=4&transport=polling"
```
{"sid":"QLi4LRkXJeWybJH8AAAA","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":20000}

**Comment by darrachequesne** [comment]
Hi! At first sight your configuration looks good to me.

> When i perform a curl request to the adress below i get a successful response,.

This means that you are able to actually reach the Socket.IO server though. Does the `Access-Control-Allow-Origin` header appear in:

```
curl "http://localhost:3000/socket.io/?EIO=4&transport=polling" -v -H "origin: http://209.97.149.47"
```

**Comment by ALWISHARIFF** [comment]
I solved the issue the issue was when connecting from the frontend since i added a proxy in the package.json file the socket-io client automatically adds the adress when instantiated
Wrong
```

 io('http://localhost:3000')

```
>No need to add the link because there is a proxy already

Correct
```
Io()
Thanks you can correct that in the codebase looks like a small bug
