### ISSUE TITLE
Memory leak: Disconnected socket stays in memory

### ISSUE THREAD

**Issue by thejh** [socketio/socket.io#407]
Hello,
the following code leaks ca. 100KB (very roughly) of ram each time I press "reload" in the browser to reload the page and reconnect:

```
var lightnode = require('lightnode');
var http = require('http');

var fileServer = new lightnode.FileServer('/home/jann/gitty/node-assertvanish/');

var server = http.createServer(function(req, res) {
  fileServer.receiveRequest(req, res);
});

server.listen(8080, '0.0.0.0');
var io = require('socket.io').listen(server);

process.on('uncaughtException', function (err) {

        console.log('Exception: ' + err);

});

io.sockets.on('connection', function (socket) {

  socket.on('disconnect', function() {
    console.log("client gone");
  });

});
```

[Modified version of the code for generating a memory backtrace](https://gist.github.com/1099993)
[Debug output of socket.io and a shortened memory backtrace](https://raw.github.com/gist/1099978/90b41816940094fdd67fe636b414f36c657539a5/gistfile1.txt) (I filtered everything out that had an indentation level >12 and shortened the lines to 150 characters because gist didn't want to accept a 710K big file and because it's easier to read this way.)

As you can see, the socket is still referenced by the disconnect handler which in turn is referenced by the socket. It's not the reason of the leak. Therefore, what leaks is `namespace.sockets.2644789511415902503`. The namespace is also referenced by the second socket (which is alive) and the Manager, and because the namespace still has the dead socket in its `sockets` object, the dead socket stays in memory.

**Comment by iamwave007** [comment]
Is this issue still existing? What is the fix?
