### ISSUE TITLE
Support SocketIO Typed Events in an Array

### ISSUE THREAD

**Issue by rfox12** [socketio/socket.io#4079]
@MaximeKjaer: on behalf of Typescript users... thank you for including typed events!

Before coming to v4.2, I had my own method for typing that I used for messages / events.  I suspect I'm not alone here... many of us Typescript adopters have frameworks that think of "handlers" more generically.  In my case I put the "handle" that should be used when emitting inside the message object itself as a property.  This has been working well for me.

As I'm migrating over, I'm finding a rejection by Typescript that I don't understand.  Sorry for all of the code, but I wanted to include a reproducible example: 

```
import { Server as SocketIOServer, Socket } from 'socket.io';

interface ClientToServerEvent {
  noArg: () => void;
  basicEmit: (a: number, b: string, c: number[]) => void;
}

interface ServerToClientEvent {
  fromServer: (msg: StuffFromServer) => void;
  moreFromServer: (msg: MoreStuffFromServer) => void;
}

interface ServerToClientMessageBase {
  version?: string;
  handle: keyof ServerToClientEvent;
}

interface StuffFromServer extends ServerToClientMessageBase {
    handle: 'fromServer';
    myString: string;
    myBool: boolean;
}

interface MoreStuffFromServer extends ServerToClientMessageBase {
    handle: 'moreFromServer';
    myNum: number;
}

type ServerMessage = StuffFromServer | MoreStuffFromServer;


const io = new SocketIOServer<ClientToServerEvent, ServerToClientEvent>()
io.on('connection', (socket: Socket<ClientToServerEvent, ServerToClientEvent>) => {

    const stuffOne: StuffFromServer = { handle:'fromServer', myString: 'hello', myBool: true };

    const stuffTwo: MoreStuffFromServer = { handle:'moreFromServer', myNum: 42 };

    const stuffThree: ServerMessage = stuffOne;

    const manyStuffs: ServerMessage[] = [stuffOne, stuffTwo, stuffThree];

    const manyStuffs2: (StuffFromServer | MoreStuffFromServer)[] = [stuffOne, stuffTwo, stuffThree];

    //OK
    socket.emit('fromServer', { handle:'fromServer', myString: 'hello', myBool: true })
    //OK
    socket.emit(stuffOne.handle, stuffOne);
    //OK
    socket.emit(stuffTwo.handle, stuffTwo);
    //OK
    socket.emit(stuffThree.handle, stuffThree);
    
    manyStuffs.forEach((stuff) => {
        //NOT OK
        socket.emit(stuff.handle, stuff);
    });

    manyStuffs2.forEach((stuff) => {
        //NOT OK
        socket.emit(stuff.handle, stuff);
    });
});
```
If it works, there is a Typescript playground link [here](https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBaEEeBkGgAb1AxB+ehxDGExHgsHikFQAEkAPJMsgs-gcrk80AAX1xbEQoAA5IJOdzUAEKPB5QBuSnbH7JHooADC0AoqNQOHgQpZAFE9Gi6YoSkMKmRmPlQAAKACUoAAvAA+UA6eAUbjakrSNnqa2IeTuj0Md2cdiIaQ-fjSd2CVCUTjMfiwJMptNkADaAF0fQGgyGw4pJTqFGR9XUrT8LcbTdtbWbQA6SslZW2yPHEII3YyCUiAGJD5k-KuB4Oh8OgRA0yCzpDD0fj90AWQ3xCnyS3iGHi5rK-rjb1BsZ87IHZNZv3+iBzEgACE2Sh+0GfjkeBOAAfizHNRlXBweHcd1uUMVJh2fLtUB7bZtQbRQMibFsUGPdgZznYUfghVYFB4dlH2Q193wYT8f0EP9HRKUBoO4WCFUHbdHy1ZiSkQPBj1zCds2E1d+LwL94HgaB3RBGSPE4DDb2be9DycfDCO44icTWcjuEonTqO2N9BA-b9fz7PjWJcDj5XXJwz2HXiWLXPAADkUyLVMfmUxRUBaB8dNM8y-UnAjTyIllQAAH1AdSSBPJzH21YIEE4bMRAwX1BkgCRGWVHkBWHAAeTszQtYc0NQUUqPgcruztVB-W9LD4ACYCPXldLOEgWBUHVTh5X4D0lXFVB3TFFUypfbZKsfaraqM+rZtQpr-Uvf8SjGlUAkgWNUC6rjzx4-gGTY2D5WO5z+AEoTRndeVsGgaANVuyTpNktAyHYFBJS9YJXJUdLMuzCL+V6sLztsyB8iuqKfmGtzPMQd0ABZ3vuvNHue16kYEqSZPdHNfqlcT0Qy44Twh2Hwq0k6dKhmyYNh+HtJZfHBIg7GFVxt63MJr6Sb+1LXJBqmIpwCR4API8koRnEcuhlm4YczcFc5lH0YAJjJwGWPF64TxwTBskmx8QrolAcrBpEadFg3gMyxAzC5iKCiCllLc-CswtLW3khpuxjel4PJdNyBIHLB2ShAfkAGlrJ2nk9oO0bqd6gILsgMO7d6r1ybjxPXOT1V9vkdPJelrOYdz5IpfgAvrKLpPCrLtOA5N7Ia5Zuuu8jpvXOsl3ODdpFBACZIaWtHpMA9SukU26ygeAdz+RwUAE+XljS9TiuA579ic6NiLB5Y-6MKboA).

This code is producing a ts error inside the forEach loop for both `manyStuffs` and `manyStuffs2`.  For `manyStuffs` its showing:
```
Argument of type '[ServerMessage]' is not assignable to parameter of type '[msg: StuffFromServer] | [msg: MoreStuffFromServer]'.
  Type '[ServerMessage]' is not assignable to type '[msg: MoreStuffFromServer]'.
    Type 'ServerMessage' is not assignable to type 'MoreStuffFromServer'.
      Property 'myNum' is missing in type 'StuffFromServer' but required in type 'MoreStuffFromServer'.(2345)
```
So tried an equivalent definition with `manyStuffs2` and ran into the same message:
```
Argument of type '[StuffFromServer | MoreStuffFromServer]' is not assignable to parameter of type '[msg: StuffFromServer] | [msg: MoreStuffFromServer]'.
  Type '[StuffFromServer | MoreStuffFromServer]' is not assignable to type '[msg: MoreStuffFromServer]'.
    Type 'StuffFromServer | MoreStuffFromServer' is not assignable to type 'MoreStuffFromServer'.
      Type 'StuffFromServer' is not assignable to type 'MoreStuffFromServer'.(2345)
```
It's perplexing to me... it's nearly the same type except that **msg:** has creeped into the definition that SocketIO wants.  

Is there a path to do what I want without radically changing my message objects?  Thanks for reading.

**Comment by rfox12** [comment]
I gather that the new [`Parameters<Type>`](https://www.typescriptlang.org/docs/handbook/utility-types.html#parameterstype) feature of typescript was used to create a tuple?  Someone better than me at typescript should able to figure out how to structure the arguments in socketio

**Comment by darrachequesne** [comment]
Hi! Thanks for the detailed example.

I don't think this is related to Socket.IO though. The TypeScript compiler is not able to understand the type of `stuff` in the loop, but it works with:

```ts
manyStuffs2.forEach((stuff) => {
  if (stuff.handle === "fromServer") {
    socket.emit(stuff.handle, stuff);
  } else {
    socket.emit(stuff.handle, stuff);
  }
});
```

You can also update the `ServerToClientEvent` interface:

```ts
interface ServerToClientEvent {
    fromServer: (msg: ServerToClientMessageBase) => void; // instead of StuffFromServer
    moreFromServer: (msg: ServerToClientMessageBase) => void; // instead of MoreStuffFromServer
}
```

See also: https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions

**Comment by rfox12** [comment]
Thank you for your response!  Your first example surprised me but makes sense now... if you exhaustively go through every type then typescript can affirm a specific type, and it seems to work.  But of course the whole point of having a collection of items that follow a more general interface is so that I don't need to go through every type...

Your second example essentially removes type checking... not a great option.

What I can't really wrap my head around is why `stuffThree` works fine--it's a union type and the `emit` works just fine.  Perhaps there is some behind-the-scenes optimization allowing ts to determine that it's actually an instance of `StuffFromServer`.  I suppose the static introspection could be doing that.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
