### ISSUE TITLE
socket.emit not sending to all clients 

### ISSUE THREAD

**Issue by yoursweater** [socketio/socket.io#4080]
Socket.io seems to be getting confused with its socket connections, preventing me from using `socket.emit` to send a message to all connected clients. Instead, it sends to just one out of the two (I only allow two connections).

```
const app = require('express')()
const http = require('http').createServer(app)
const constants = require('./constants')
const draft = require('./game/draft')
const io = require('socket.io')(http, {
    cors: {
        origin: "http://localhost:3000  ",
        methods: ["GET", "POST"]
      }
})

// auth middleware
io.use((socket, next) => {
    const username = socket.handshake.auth.username;
    if (!username) {
        return next(new Error("invalid username"));
    }
    socket.username = username;
    next();
});

io.on('connection', function (socket) {
    if (io.engine.clientsCount > constants.CONNECTION_LIMIT) {
        socket.emit('err', { message: 'reach the limit of connections' })
        socket.disconnect()
        console.log('Disconnected...')
        return
    }

    socket.broadcast.emit("user connected", {
        userID: socket.id,
        username: socket.username,
    });
    const users = [];
    for (let [id, socket] of io.of("/").sockets) {
      users.push({
        userID: id,
        username: socket.username,
      });
    }
    socket.emit("users", users);

     if (users.length === 2) {
         socket.emit('START_GAME', { message: 'both players have joined the lobby' })
    }
})
```

The expected behavior is for the above START_GAME message to go to both connected clients. What happens is that it only goes to one. I can actually send it to the other if I combine socket.emit with socket.broadcast.emit.

Seems like a genuine bug. Picture below:

[pic of problem](https://imgur.com/2Y7xQDU)

**Comment by rfox12** [comment]
To me this looks like a "bug" in the Socket IO documentation.  The [broadcasting events page](https://socket.io/docs/v4/broadcasting-events/) is very misleading.  

1) **socket.emit() always sends information to a single socket.**  It doesn't "broadcast" at all.  To say that every socket will get the message is _technically_ correct.. in the code example each socket will get the message exactly once--when connected.  But it goes against the spirit of what people who click on "broadcast" are trying to achieve... sending a message to everyone.

2) In the "To all connected clients except the sender" diagram, there should be arrows from the top socket to the second and third sockets.  It would be helpful if the sockets and clients were named.  

@yoursweater From what I can tell the "correct" way to emit to everyone would be, as you say, to use both socket.emit and socket.broadcast.emit (or create a room to broadcast to).

**Comment by rfox12** [comment]
Probably what people are looking for would be here: https://socket.io/docs/v4/server-api/#server-sockets

```
io.sockets.emit("hi", "everyone");
// is equivalent to
io.of("/").emit("hi", "everyone");
```

**Comment by yoursweater** [comment]
Wowwww @rfox12 thank you!  That is incredibly unclear in the docs and the tutorial!

**Comment by darrachequesne** [comment]
Hi! Thanks for the feedback. I have updated the diagrams, could you please check if that's clearer? Thanks in advance :+1:

**Comment by rfox12** [comment]
@darrachequesne I love the new updates!  One small suggestion, which is I think a point of major confusion... why does your broadcast example have to be wrapped inside the "connection" callback?  
 
I guess what I'm proposing is that instead of this:
```javascript
io.on("connection", (socket) => {  
  io.emit("hello", "world");
});
```
We should just put this:
```javascript
io.emit("hello", "world");
```

**Comment by darrachequesne** [comment]
@rfox12 that's a good question... I guess that's linked to the example below:

```js
io.on("connection", (socket) => {
  socket.broadcast.emit("hello", "world");
});
```

So the reader knows where the `socket` comes from. But we could totally remove the wrapper in the other examples. What do you think?

**Comment by rfox12** [comment]
Yep I would remove it in the general example of broadcast to everyone... IMO the socket reference isn't necessary and promotes confusion.

**Comment by darrachequesne** [comment]
Here we go! https://github.com/socketio/socket.io-website/commit/2d13db7ed3c83aa5c1d4fc1d5ca6afc1ef2b189e
