### ISSUE TITLE
> ### You want to:

### ISSUE THREAD

**Issue by Psoffie009** [socketio/socket.io#4088]
> ### You want to:
> * [x]  report a _bug_
> * [x]  request a _feature_
> 
> ### Current behaviour
> Running the test suite frequently runs into an `listen EADDRINUSE: address already in use :::54024` error. That prevents the library to be properly tested in [CITGM](https://github.com/nodejs/citgm). We had the tests marked as flaky but running them as such does not help much. Thus, it would be great if this could be looked at and fixed.
> 
> See e.g., https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1855/nodes=rhel72-s390x/testReport/junit/(root)/citgm/socket_io_v2_2_0/
> 
> ### Steps to reproduce (if the current behaviour is a bug)
> Run the test frequently.
> 
> ### Expected behaviour
> The tests all pass.
> 
> ### Setup
> * OS: Multiple (Linux / Windows)
> * socket.io version: v2.2.0
> 
> ### Other information (e.g. stacktraces, related issues, suggestions how to fix)
> 1 failing
> 
> 1. socket.io handshake should allow request when using an array of origins:
>    Uncaught Error: listen EADDRINUSE: address already in use :::54024
>    at Server.setupListenHandle [as _listen2] (net.js:1226:14)
>    at listenInCluster (net.js:1274:12)
>    at Server.listen (net.js:1362:7)
>    at Server.listen.Server.attach (lib/index.js:64:524)
>    at Context. (test/socket.io.js:361:55)
>    at processImmediate (internal/timers.js:439:21)

_Originally posted by @Psoffie009 in https://github.com/socketio/socket.io/issues/3447#issuecomment-920484949_

**Comment by Psoffie009** [comment]
> > ### You want to:
> > 
> > * [x]   report a _bug_
> > * [x]   request a _feature_
> > 
> > ### Current behaviour
> > Running the test suite frequently runs into an `listen EADDRINUSE: address already in use :::54024` error. That prevents the library to be properly tested in [CITGM](https://github.com/nodejs/citgm). We had the tests marked as flaky but running them as such does not help much. Thus, it would be great if this could be looked at and fixed.
> > See e.g., https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1855/nodes=rhel72-s390x/testReport/junit/(root)/citgm/socket_io_v2_2_0/
> > ### Steps to reproduce (if the current behaviour is a bug)
> > Run the test frequently.
> > ### Expected behaviour
> > The tests all pass.
> > ### Setup
> > 
> > * OS: Multiple (Linux / Windows)
> > * socket.io version: v2.2.0
> > 
> > ### Other information (e.g. stacktraces, related issues, suggestions how to fix)
> > 1 failing
> > 
> > 1. socket.io handshake should allow request when using an array of origins:
> >    Uncaught Error: listen EADDRINUSE: address already in use :::54024
> >    at Server.setupListenHandle [as _listen2] (net.js:1226:14)
> >    at listenInCluster (net.js:1274:12)
> >    at Server.listen (net.js:1362:7)
> >    at Server.listen.Server.attach (lib/index.js:64:524)
> >    at Context. (test/socket.io.js:361:55)
> >    at processImmediate (internal/timers.js:439:21)
> 
> _Originally posted by @Psoffie009 in [#3447 (comment)](https://github.com/socketio/socket.io/issues/3447#issuecomment-920484949)_

**Comment by darrachequesne** [comment]
Bad script? :eyes:
