### ISSUE TITLE
To emit from client to server side for HTML element tag

### ISSUE THREAD

**Issue by lucakim27** [socketio/socket.io#4095]
**Describe the bug**
i was trying to emit the HTML element tag that has "id" and everything inside to the server side but it only shows the curly bracket in the server side as i print it out on console.

Browser console
![Screen Shot 2021-09-16 at 10 21 12 PM](https://user-images.githubusercontent.com/63194988/133629220-add4db50-47bf-4cf3-bab8-3d9e503fc385.png)

Terminal console
![Screen Shot 2021-09-16 at 10 20 58 PM](https://user-images.githubusercontent.com/63194988/133629165-6353ff00-c092-4835-97a2-cbde75160557.png)

**To Reproduce**

Please fill the following code example:

Socket.IO server version: `4.2.0`

*Server*

```js
import { Server } from "socket.io";

const io = new Server(3000, {});

io.on("connection", (socket) => {

  // the room list HTML DOM here
  socket.on('listDOM', dom => {
    console.log(dom)
    socket.emit('receiveDOM', dom)
  })

});
```

Socket.IO client version: `4.2.0`

*Client*

```js
import { io } from "socket.io-client";

const socket = io("ws://localhost:3000/", {});

socket.on('joinRoomList', ({roomTitle, username, room}) => {

  // create a div tag which will be a child appending to the form
  var div = document.createElement("div")
  div.appendChild(document.createTextNode(roomTitle + " by " + username))
  div.setAttribute("id", roomTitle)
  div.addEventListener('click', function (event) { window.location = 'http://localhost:3000/room.html?room=' + room + "&username=" + username + "&roomname=" + roomTitle })
  
  console.log(div)

  // send the form HTML DOM to server
  socket.emit('listDOM', div)
})

// The form HTML DOM from server
socket.on('receiveDOM', dom => {

  console.log(dom)

}) 
```

**Expected behavior**
- i expect the "dom" in console, server side to be same as the console, client side like the first picture i put above.

**Platform:**
 - Device: MacBook pro 2017 15inch 
 - OS: macOS BigSur

**Additional context**

**Comment by darrachequesne** [comment]
Hi! The `<div>` element is not serializable, I think you should be able to do what you want with:

```js
socket.emit('listDOM', div.outerHTML);
```
