### ISSUE TITLE
v2-sockets cannot connect to Socket.io 4.3.0 with allowEIO3 enabled.

### ISSUE THREAD

**Issue by spasma** [socketio/socket.io#4120]
**Describe the bug**
Version 4.3.0 breaks `allowEIO3` support. I know the package is not officially released yet, but I accidentally updated tot 4.3.0 due to my package file with `socket.io": "^4.2.0"`.

I saw that allowEIO3 was removed from the EngineOptions-interface in https://github.com/socketio/socket.io/compare/4.2.0...4.3.0#diff-d5a4b3a0309f2337144861084c1014523cced561eb722cb9684c63f5e41e0567L119, maybe that's related to this issue.

**To Reproduce**
Connect to a server with a 2.0-client, with `allowEIO3` on `true` while having version 4.3.0 installed. 

**Expected behavior**
I expect to successfully connect to a 4.3.0-server with `allowEIO3` on.

**Comment by darrachequesne** [comment]
Hi! I cannot reproduce: https://github.com/socketio/socket.io-fiddle/tree/issues/socket.io/4120

Could you please check?

The `allowEIO3` option is still supported, it was only moved to the `engine.io` repository: https://github.com/socketio/engine.io/blob/fe5d97fc3d7a26d34bce786a97962fae3d7ce17f/lib/server.ts#L113
