### ISSUE TITLE
v4.3.0 breaks testem

### ISSUE THREAD

**Issue by chriskrycho** [socketio/socket.io#4121]
**Describe the bug**
As of the v4.3.0 release, testem (and therefore all CI runs which use it, so this will shortly be hitting the whole Ember.js community and any others as they upgrade *or* for runs which check against "drifted dependencies") is failing with the following error:

```
io.connect is not a function
```

Inspecting `io` shows that it is in fact the `lookup` function ([dist][l]).

[l]: https://github.com/socketio/socket.io/blob/95810aa62d2113db5cc052c857e808fb9b0d5518/client-dist/socket.io.js#L4137-L4169

<img width="398" alt="Screen Shot 2021-10-14 at 16 31 05" src="https://user-images.githubusercontent.com/2403023/137404376-3955d24c-a086-4e56-add5-10a491934817.png">

**To Reproduce**

Unfortunately, this is a bit involved, and I don't have a good minimal reproduction yet. I will add one later. For now, I will link directly to the relevant bits of testem's source.

Socket.IO server version: `4.3.0`

*Server*

- [importing][i] `socket.io` as `const socketIO = require('socket.io');
- [using][u] the imported value as a function

[i]: https://github.com/testem/testem/blob/0b1d56be7b9486995f0131de8f7539707e804b98/lib/server/index.js#L13
[u]: https://github.com/testem/testem/blob/0b1d56be7b9486995f0131de8f7539707e804b98/lib/server/index.js#L131

Socket.IO client version: `x.y.z`

*Client*

- [accessing `/socket.io/socket.io.js` via `<script>` tag][g]
- [attempting to use `io.connect` with `io` as a global][gu]

[g]: https://github.com/testem/testem/blob/0b1d56be7b9486995f0131de8f7539707e804b98/public/testem/connection.html#L4-L5
[gu]: https://github.com/testem/testem/blob/0b1d56be7b9486995f0131de8f7539707e804b98/public/testem/testem_connection.js#L178

**Expected behavior**
Given 4.3.0 was a patch release, `testem`'s previous usage should continue to work without issue.

**Platform:**
 - Device: Mac or Linux
 - OS: Ubuntu latest, macOS 11.6, etc.

**Additional context**
I strongly suspect (but haven't yet been able to prove) that this is related to either the `engine.io` bump, serving ESM, or the intersection of the two.

**Comment by chriskrycho** [comment]
Confirmed: the output from webpack on v4.2.0 included `exports.connect = lookup`, [here](https://github.com/socketio/socket.io-client/blob/4.2.0/dist/socket.io.js#L194), which meant that users could call `io.connect` previously; the Rollup output does *not* have a top-level value of `connect` defined anywhere on the result of the `factory()` call Rollup generates.

**Comment by chriskrycho** [comment]
Not webpack's fault—a little further digging back into the change shows what happened: changing from `modules.exports` to a standard ES named export ([here](https://github.com/socketio/socket.io-client/compare/4.2.0...4.3.0#diff-d5a4b3a0309f2337144861084c1014523cced561eb722cb9684c63f5e41e0567L94) and [here](https://github.com/socketio/socket.io-client/compare/4.2.0...4.3.0#diff-d5a4b3a0309f2337144861084c1014523cced561eb722cb9684c63f5e41e0567R94) respectively) resulted in different compiled output, because you *also* switched to doing a single default export [here](https://github.com/socketio/socket.io-client/compare/4.2.0...4.3.0#diff-e78f7a7cd5aa9e29ff4dc37d5304813609fe765f66363c8a675d0bcbfbb0bd3eR1-R3) rather than re-exporting all the values as a namespace. For equivalent semantics to what you had previously, the contents of `lib/browser-entrypoint.ts` should be:

```ts
export * as io from './index.js';
```

I'm happy to open a PR to that effect tomorrow!

**Comment by chriskrycho** [comment]
I've pushed an update to the PR which manually recreates the namespace in the source module, while preserving the nice new ES module exports.

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-client/commit/8737d0ae6fb362455015e6dd435010c36d023663, which was included in [̀socket.io-client@4.3.1](https://github.com/socketio/socket.io-client/releases/tag/4.3.1).

**Comment by chriskrycho** [comment]
@SergeAstapov yeah, you're correct—given the re-bundling pattern used `socket.io` itself also needs a release. @darrachequesne, mind cutting that on Monday? Thanks!

**Comment by burritoIand** [comment]
@chriskrycho assuming ember-cli will need to cut a release once testem updates as well? (currently broken in latest 3.28)

**Comment by chriskrycho** [comment]
Shouldn't. The CI breakage is just from the Ember CI defaults of including a run which lets all dependencies resolve to their latest legal version (using `--no-lockfile`), precisely so we catch issues like this early. Once the release is out, all of the CI jobs should start passing again.

If you're seeing the  CI builds fail from this issue (as I have on `ember-modifier`), it's almost certainly because of a cache issue which is causing other runs to inherit the bad version even though per the lock file they shouldn't. That should also get fixed (via the same bad cache behavior!) once `socket.io` cuts 4.3.1. I'm going to poke at the CI config a bit on Monday and see if there's something we need to tweak for the GH Actions defaults to make sure that part doesn't become a problem again in the future.
