### ISSUE TITLE
v4.3.0 breaks client-side api for socket.hasListeners() (Typescript bug)

### ISSUE THREAD

**Issue by rfox12** [socketio/socket.io#4123]
Now in client-side code, this call
```javascript
const eventName = 'myEvent';
socket.hasListeners(eventName)
```
Will fail with this typescript error:

**Argument of type 'string' is not assignable to parameter of type 'ReservedOrUserEventNames<SocketReservedEvents, ServerToClientEvent>'.ts(2345)**

And this is not easily fixable.  `SocketReservedEvents` is not exported. `ReservedOrUserEventNames` is buried.

**Comment by darrachequesne** [comment]
Hi! I cannot reproduce the behavior you are describing: https://github.com/socketio/socket.io-fiddle/tree/issues/socket.io%2F4123

Could you please check?
