### ISSUE TITLE
Socket IO 4.3 Breaks HTTPS Support

### ISSUE THREAD

**Issue by Striar-Yunis** [socketio/socket.io#4124]
**Describe the bug**
4.2 -> 4.3 added this if statement check: https://github.com/socketio/socket.io/blob/95810aa62d2113db5cc052c857e808fb9b0d5518/lib/index.ts#L159
That check means that servers made with the https module won't be bound:

**To Reproduce**
Socket.IO server version: `4.3.0`

*Server*

```js
const { readFileSync } = require("fs");
const { createServer } = require("https");
const { Server } = require("socket.io");

const httpServer = createServer({
  key: readFileSync("/path/to/my/key.pem"),
  cert: readFileSync("/path/to/my/cert.pem")
});

const io = new Server(httpServer, { /* options */ });

io.on("connection", (socket) => {
  // ...
});

httpServer.listen(3000);
```
^ From https://socket.io/docs/v4/server-initialization/#with-an-https-server

**Expected behavior**
The https server should be attached. It isn't. You can see this by modifying the following in the `/dist/index.js`
```js
console.log('look for this 1');
if (srv instanceof http.Server || typeof srv === "number") {
    console.log('look for this 2');
    this.attach(srv);
}
```

**Comment by HexaField** [comment]
This also breaks feathers/socketio. I cannot see why this check is necessary, I have created a PR that reverts it.
