### ISSUE TITLE
Error: Unexpected server response: 101 (Postman result)

### ISSUE THREAD

**Issue by zoobibackups** [socketio/socket.io#4125]
The client doesn't make connection with (soctet.io) server, it works on localhost but didn't work when deployed on cpanel.

Server code: 
```
const express = require('express');
const app = express()
const http = require('http').createServer(app);
const io = require('socket.io')(http, {'pingInterval': 10000, 'pingTimeout': 10000});
const bodyParser = require('body-parser');
const port = 3000 // i tried a rage of ports but non of them works

app.use(bodyParser.urlencoded({extended:true}));
app.use(bodyParser.json({extended: true,limit: '50mb'}));

io.on('connection', (socket) => {
    console.log(socket.id)
    io.emit('message', "hi");
});

app.get("/", (req, res) => {
    res.send("Get method called")
})

app.post("/", (req, res) => {
    res.send("Post method called")
})

http.listen(port, () => console.log("Listening on port: ",port))
```

Deployed server response:

![Screenshot (9)_LI](https://user-images.githubusercontent.com/78194973/137577651-937bce2c-6420-4af8-8ecb-7f2a2c299c07.jpg)

LocalHost response:
 
![Screenshot (7)](https://user-images.githubusercontent.com/78194973/137577664-eaef6320-c6c3-4ae2-9dee-ecdfa5ad18f2.png)

I have tried multiple ports but no response from server.

And this event never triggers (no callbacks on error)
```
socket.on("connect_error", (err) => {
  console.log(err)  
});
```

I need help on this???

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
