### ISSUE TITLE
feature request: middleware for emitted events

### ISSUE THREAD

**Issue by naseemkullah** [socketio/socket.io#4139]
**Is your feature request related to a problem? Please describe.**
I'd like to perform some logic for every emitted event  (log them).

**Describe the solution you'd like**
An option to perform some logic within emit, after the event is emitted but just before emit returns true.

**Describe alternatives you've considered**
overriding emit as per https://stackoverflow.com/questions/8832414/overriding-socket-ios-emit-and-on

**Comment by darrachequesne** [comment]
Implemented in version [4.5.0](https://github.com/socketio/socket.io/releases/tag/4.5.0):

```js
socket.onAnyOutgoing((event, ...args) => {
  console.log(event);
});
```
