### ISSUE TITLE
Issue where clients can send messages to room without joining room

### ISSUE THREAD

**Issue by elmcapp** [socketio/socket.io#4149]
**Describe the bug**
Lets say that we have 3 devices. If a button is press to send a message then no device will receive the message. This is expected. However lets say that device 1 press button to join room. At that point its connect and if button is press to send message the data is passed. This is also expected. The problem is that once device 1 has joined the room, device 2 and device 3 can also send message however they have not joined the room. Even though they have not joined they can send a message and receive messages. It's like they don't have to join they can send the message as long as a room is created. I think this is a bug. We should only be able to send messages if we have joined the room or is it that if a device sends a message to a created room it automatically joins. 

**To Reproduce**
server.js

// join room
    socket.on("join", (roomName, data) => {
      socket.join(roomName);
      console.log("user has join", { roomName, socket: socket.id });
    });

    // send message
    socket.on("send_message", (roomName, sender, data) => {
      io.in(roomName).emit("new_message", { sender, data });

      console.log(
        "receive a message here but need to be in joined to see it",
        roomName
      );
    });
-------------------------
my client.js

 mySocket.on('new_message', data => {
      console.log('here is the data from room', data);
    });

 <Button
          style={{margin: 10}}
          title="join abc room"
          onPress={() => mySocket.emit('join', 'abc')}
        />

        <Button
          title="Send a message abc" //roomName, sender, data
          style={{margin: 10}}
          onPress={() =>
            mySocket.emit(
              'send_message',
              'abc',
              firebase.auth().currentUser.uid,
              'hello',
            )
          }
        />

Socket.IO server version: `x.y.z`
"socket.io": "^4.2.0"

```js
import { Server } from "socket.io";
const sockets = require("./socket.io");
const io = new Server(3000, {});

io.on("connection", (socket) => {
  console.log(`connect ${socket.id}`);

  socket.on("disconnect", () => {
    console.log(`disconnect ${socket.id}`);
  });
});
```

Socket.IO client version: `x.y.z`
"socket.io-client": "^4.2.0"

```js
import { io } from "socket.io-client";

const socket = io("ws://localhost:3000/", {});

socket.on("connect", () => {
  console.log(`connect ${socket.id}`);
});

socket.on("disconnect", () => {
  console.log("disconnect");
});
```

**Expected behavior**
Looking for when I join a room that only devices that are in that room to receive messages. All other devices must join room by press the join button and not be able to receive messages when they just press button without joining room

**Platform:**
 - Device: [iPhone 11]
 - OS: [iOS]

**Additional context**
I have attached a video of the issue

https://user-images.githubusercontent.com/64275658/139394331-d555b535-6e88-4256-8b76-932ce5f26f34.mp4

**Comment by sebamarynissen** [comment]
I think you're confusing rooms with [namespaces](https://socket.io/docs/v4/namespaces/). The behaviour you're describing is the expected behaviour for rooms: you don't need to be in a room to be able to send messages to it. Rooms are used to group sockets - for example when a user is connected at the same time on multiple devices, you can do things like
```js
io.to(uid).emit('message', `Hello, user ${uid}!`);
```

**Comment by elmcapp** [comment]
> I think you're confusing rooms with [namespaces](https://socket.io/docs/v4/namespaces/). The behaviour you're describing is the expected behaviour for rooms: you don't need to be in a room to be able to send messages to it. Rooms are used to group sockets - for example when a user is connected at the same time on multiple devices, you can do things like
> 
> ```js
> io.to(uid).emit('message', `Hello, user ${uid}!`);
> ```

Thank you for explaining.
