### ISSUE TITLE
websocket The path is automatically added /

### ISSUE THREAD

**Issue by Jeggery** [socketio/socket.io#4153]
As shown in the figure below
![websocke1](https://user-images.githubusercontent.com/39072827/139831070-2ffc9b2d-94cb-47ae-829c-afd9745c3ebc.png)
![webso2](https://user-images.githubusercontent.com/39072827/139831148-9d9d6a01-4cbe-418c-ba47-3d0bd3d7bfc2.png)
)
Automatically added / caused connection path error in suffix

**Comment by Jeggery** [comment]
![websocke1](https://user-images.githubusercontent.com/39072827/139831280-af904368-d88d-46ec-b642-a5193121b11e.png)

**Comment by darrachequesne** [comment]
Yes, this is the expected behavior. You need to use the same path on the server side:

```js
const io = new Server({
  path: "/ajaxchattest"
});
```

Reference: https://socket.io/docs/v4/server-options/#path

Or it there a proxy in between?

**Comment by Jeggery** [comment]
Does the server also have to use the socket.io framework？The Java language used in our back-end is not clear whether it is socket.io. The native New websocket can be used normally. Is socket.io-client a bug?

**Comment by darrachequesne** [comment]
> Does the server also have to use the socket.io framework？

Yes. Please see here: https://socket.io/docs/v4/#what-socketio-is-not

**Comment by Jeggery** [comment]
> Yes. Please see here: https://socket.io/docs/v4/#what-socketio-is-not
Thank you. I see

**Comment by Jeggery** [comment]
> 是的。请看这里：[https](https://socket.io/docs/v4/#what-socketio-is-not) : [//socket.io/docs/v4/#what-socketio-is-not](https://socket.io/docs/v4/#what-socketio-is-not)

Thank you. I see
