### ISSUE TITLE
Typescript: Namespace engine.io has no e ported member 'ServerAttachOptions'.

### ISSUE THREAD

**Issue by cesco69** [socketio/socket.io#4156]
**Describe the bug**

I have update socket.io to

```
    "socket.io": "^4.3.1",
    "socket.io-client": "^4.3.2",
    "socket.io-redis": "^6.1.1",
```

now typescript show this error

```
node_modules/@types/socket.io/index.d.ts:458:44 - error TS2694: Namespace '"/node_modules/engine.io/build/engine.io"' has no exported member 'ServerAttachOptions'.

58     interface ServerOptions extends engine.ServerAttachOptions {
                                              ~~~~~~~~~~~~~~~~~~~
```

**Comment by dholmes2409** [comment]
How did you resolve this issue?

**Comment by alisomay** [comment]
+ 1

**Comment by darrachequesne** [comment]
Hi! Unfortunatly I wasn't able to reproduce, the `ServerAttachOptions` interface is exported [here](https://github.com/socketio/engine.io/blob/master/lib/engine.io.ts#L7) since `engine.io@6.0.0`.

Could it be caused by the import of `@types/engine.io` (which is now useless)?
