### ISSUE TITLE
Older clients stop working with 4.3.0

### ISSUE THREAD

**Issue by Nibbler999** [socketio/socket.io#4158]
**Describe the bug**
Old clients get disconnected with "parse error" as the reason

**To Reproduce**

Socket.IO server version: `4.3.1`

*Server*

```js
import { Server } from "socket.io";

const io = new Server(3000, {
    allowEIO3: true,
    cors: {
        origin: ['null'],
        credentials: true
    }
});

io.on("connection", (socket) => {

  console.log(`connect ${socket.id}`);

  socket.on("data", (data) => {
      console.log(data);
  });

  socket.on("disconnect", (reason) => {
      console.log(`disconnect ${socket.id} - ${reason}`);
  });
});

```

Socket.IO client version: `2.3.1`

*Client*

```js
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://cdn.socket.io/socket.io-2.3.1.js"></script>
</head>
<body>
<script>

const socket = io("http://localhost:3000/", { transports: ['polling'] });

socket.on("connect", () => {
    console.log(`connect ${socket.id}`);
    socket.emit('data', "Hello!");
    socket.emit('data', new Uint8Array([1,2,3]).buffer);
});

socket.on("disconnect", () => {
    console.log("disconnect");
});

</script>
</body>

</html>

```

**Expected behavior**
Server gets the message "Hello!" and the binary message 1,2,3

**Platform:**
Browser

**Additional context**
Old client protocol
Polling transport
Multiple messages in one packet, at least one of which is binary
Server version 4.2.0 works ok

**Comment by darrachequesne** [comment]
I could indeed reproduce. This should be fixed in `engine.io@6.0.1` (https://github.com/socketio/engine.io/commit/3f42262fd27a77a7383cdbb44ede7c6211a9782b), sorry for that.
