### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::5000

### ISSUE THREAD

**Issue by fadihanna123** [socketio/socket.io#4160]
**Describe the bug**
After upgrading to version 4.3.2, terminal throws always this error:
Error: listen EADDRINUSE: address already in use :::PORT

Socket.IO server version: `4.3.2`

Socket.IO client version: `4.3.2`

When i changed port it worked again.
**Platform:**
 - Device: Apple Macbook Pro
 - OS: MacOS Monterey version 12.0.1

**Comment by fadihanna123** [comment]
Problem solved. All ports was closed after downgraded hehh.

**Comment by darrachequesne** [comment]
@fadihanna123 this error suggests this port is already used by another process, could you please check? This does not seems related to Socket.IO.

**Comment by fadihanna123** [comment]
I already tried 5000 and 7000 and it is always throws error that is already in use. I tested already port 4000 in two computers and it was same result.

**Comment by fadihanna123** [comment]
When i changed to 8080 it worked. It never happends with me in past with Socket io using port 4000.

**Comment by outranker** [comment]
MacOS Monterey has some new features that uses ports 5000 and 7000. I think port 5000 is used by a feature called AirPlay Receiver. If you want to use that port for your own needs then you should disable that from _System Preferences_.
Same can said for port 7000 but i'm not sure what new feature of MacOS uses that for

**Comment by darrachequesne** [comment]
I'm closing this issue, as I don't think this is related to Socket.IO. Please reopen if needed.
