### ISSUE TITLE
Upgrading to v3 increases redis connections due to redis-adapter behavior change

### ISSUE THREAD

**Issue by yuan-jiang** [socketio/socket.io#4167]
This is a suggestion for improving the documentation or the [migration guide](https://socket.io/docs/v4/migrating-from-2-x-to-3-0/).

The background: recently I've been trying to upgrade our socket-io backend from v2 to v3 with the following changes:
```diff
-   "socket.io": "2.3.0",
-   "socket.io-emitter": "3.1.1",
-   "socket.io-redis": "5.4.0" ,
+   "socket.io": "3.1.2",
+   "socket.io-emitter": "3.2.0",
+   "socket.io-redis": "6.0.1",
```
our service is a kind of marketing tool with socket-io clients embedded to many public sites which are connecting to our socket-io servers, and for each site a namespace is used. In our code we attached adapter with the default setup as:
```js
this.io.adapter(redisAdapter({ host: config.redis_adapter.host, port: config.redis_adapter.port }));
```
However, an issue was observed that a huge amount of redis connections were created after the change was deployed to production. After digging into the source code of `socket.io-redis`, I found the root cause was because of a behavior change in adapter initialization for namespaces: 
For socket.io v2.x and its corresponding redis-adapter 5.x, from [here](https://github.com/socketio/socket.io-redis-adapter/blob/5.4.0/index.js#L65-L101) we can see when redis options are passed instead of `pubClient/subClient` during adapter attaching, a pair of redis clients are created and `shared` by all the [namespaces](https://github.com/socketio/socket.io/blob/2.3.0/lib/namespace.js#L91-L93): 
```js
Namespace.prototype.initAdapter = function(){
  this.adapter = new (this.server.adapter())(this);
};
```
But for socket.io v3.x and its corresponding redis-adapter 6.0.x, we can see from [here](https://github.com/socketio/socket.io-redis-adapter/blob/6.0.1/lib/index.ts#L72-L112), a new pair of `pubClient/subClient` is created for each namespace. 

For our specific use case, this behavior change has a big issue for example: if we have 5000 namespaces (sites) with each creating 2 connections to our redis, and we're running 20 instances for socket io servers, which would require `5000 * 2 * 20 = 200_000` redis connections, which was why redis blowed up the moment we tried deployment (until I read the code and knew this behavior change). Of course the solution/workaround is simple: just manually create redis clients and pass the `pubClient` and `subClient` to the `createAdapter` interface when attaching adapter to sio. 

It would be nice if this kind of behavior change is documented for example in the [`server.adapter([value])`](https://socket.io/docs/v3/server-api/#serveradaptervalue) by saying something like if the use cases use many namespaces, be aware that passing redis options to adapter would create 2 redis connections for each namespace and to avoid issue from too many redis connections, you must create redis clients and pass the `pubClient` and `subClient` by yourself.

**Comment by darrachequesne** [comment]
You are right, thanks for the detailed analysis :+1: 

Actually, this is exactly the issue that we have fixed in v7: the library will no longer create Redis clients on behalf of the user.

Before:

```js
const redisAdapter = require("socket.io-redis");

io.adapter(redisAdapter({ host: "localhost", port: 6379 }));
```

After:

```js
const { createClient } = require("redis");
const { createAdapter } = require("@socket.io/redis-adapter");

const pubClient = createClient({ host: "localhost", port: 6379 });
const subClient = pubClient.duplicate();

io.adapter(createAdapter(pubClient, subClient));
```

Please see the release note here: https://github.com/socketio/socket.io-redis-adapter/releases/tag/7.0.0

I added a note in the documentation as well: https://socket.io/docs/v4/redis-adapter/#migrating-from-socketio-redis
