### ISSUE TITLE
io.fetchSockets() return 0

### ISSUE THREAD

**Issue by nachpav** [socketio/socket.io#4183]
**Describe the bug**
If namespaces are used, then the method returns an empty array, although there are connections. It works correctly only if you specify io.of ('/somename')

Socket.IO server version: `4.4.0`

*Server*

```js
    const sockets = await io.of('/test').fetchSockets()
    const allSockets = await io.fetchSockets()
    console.log(sockets.length, allSockets.length)
```

**Ubuntu 20.04:**

**Comment by darrachequesne** [comment]
Yes, that is the expected behavior. Please see the documentation here: https://socket.io/docs/v4/server-api/#namespacefetchsockets

**Comment by nachpav** [comment]
but the documentation says that the request returns all instances? Or does it mean all instances of the space by default? Is it possible to somehow get all connections regardless of the namespace?
// return all Socket instances
const sockets = await io.fetchSockets();

**Comment by darrachequesne** [comment]
@nachpav you are right, the documentation is a bit misleading, it only returns the socket instances in the main namespace.

There is currently no built-in way to fetch all connections of all namespaces, you can either call `fetchSockets()` several times or use the `serverSideEmit` method:

```js
io.serverSideEmit("fetchAll", (err, responses) => {
  // ...
});

io.on("fetchAll", (cb) => {
  const sockets = [];
  const addSocket = (socket) => {
    sockets.push({
      id: socket.id,
      handshake: socket.handshake
    });
  }

  io.of("/").sockets.forEach(addSocket);
  io.of("/nsp1").sockets.forEach(addSocket);
  io.of("/nsp2").sockets.forEach(addSocket);

  cb(sockets);
});
```

Reference: https://socket.io/docs/v4/server-api/#namespaceserversideemiteventname-args

**Comment by nachpav** [comment]
Ok, thank you!
