### ISSUE TITLE
Socket.io Connection Closes instantly

### ISSUE THREAD

**Issue by denny99** [socketio/socket.io#4226]
**Describe the bug**

My Scenario is the following:

I have an angular app which is built with capacitor to run as native ios app.

When connection with socket.io the connection closes directly after the contact with the server. 
The server itself is reachable and sends the initial connection message. CORS is enabled too.

After Switching to polling instead of websockets, i could dive deeper into the problem.
After the connection Socket.io receives the data `6\u001e1`. This will be interpreted as an error package and close the connection.

I've already killed angular and just connected plain with socket.io but still the same error.
I have no idea why this package will be received...

**To Reproduce**

Socket.IO server version: `4.4.0`
Socket.IO client version: `4.4.0`
Capactitor: `3.3.0`
**Expected behavior**

**Platform:**
 - Device: Any apple device
 - OS: ios 15.2

**Additional context**

**Comment by denny99** [comment]
```
  socket.io:server incoming connection with id PgIG7kDqYVd5kerEAADN +2m
  socket.io-parser decoded 0/script, as {"type":0,"nsp":"/script"} +28s
  socket.io:client connecting to namespace /script +2m
  socket.io:namespace adding socket to nsp /script +2m
  socket.io:client client close with reason forced close +1ms

```

Here are some logs from the backend. It just force closes the connection...

**Comment by denny99** [comment]
![image](https://user-images.githubusercontent.com/1826849/147068978-c4ab11c6-dcef-4f52-8195-e98243549d5a.png)

And here the Network log from the websocket transport.
I'm running out of ideas what the issue is

**Comment by denny99** [comment]
ok. i'm an idiot. We are using cookie based authentication and i just had to enable `withCredentials` ...

**Comment by JolianGof** [comment]
> ![image](https://user-images.githubusercontent.com/1826849/147068978-c4ab11c6-dcef-4f52-8195-e98243549d5a.png)
> 
> And here the Network log from the websocket transport. I'm running out of ideas what the issue is

Hey man can i know how did u change the packets to be like 40/script

@denny99

**Comment by denny99** [comment]
40 means namespace join. As far as I remember. 

And script is the name of the namespace

**Comment by JolianGof** [comment]
it's sending the number 40 instead of 42/rs when the connection is opened. This discrepancy is causing the connection to close with a "Connection closed: 1000" error.

To ensure the connection remains stable, it's crucial that the client sends "42/rs" as intended. Could you  provide guidance on how we can correct this behavior?

**Comment by JolianGof** [comment]
> 40 means namespace join. As far as I remember.
> 
> And script is the name of the namespace

it's sending the number 40 instead of 42/rs when the connection is opened. This discrepancy is causing the connection to close with a "Connection closed: 1000" error.

To ensure the connection remains stable, it's crucial that the client sends "42/rs" as intended. Could you provide guidance on how we can correct this behavior?

@denny99

**Comment by denny99** [comment]
Well. I did not alter socket.io in any way. It did send 40 on its own. 

By my issue here with the unexpected close was related due to the fact, that the server required the auth cookie or otherwise it rejected the keep alive and the socket terminated
