### ISSUE TITLE
`SocketData` type is not passed down to the `Namespace`

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [socketio/socket.io#4229]
`SocketData` type is not passed down to the `Namespace` when we do `io.of()`.
That results in `socket.data` being `any` type:

Example: 
```ts
const io = new Server<{},{},{},{ username: string }>()

io.on('connection', socket => {
   socket.data /// { username?: string }
})

io.of('/nps').on('connection', socket => {
   socket.data /// any
})
```

Source code:
https://github.com/socketio/socket.io/blob/51784d0305fda6695af9e325fd14edbabae4c5f4/lib/index.ts#L577-L582

Should be:
```ts
of(...): Namespace<ListenEvents, EmitEvents, ServerSideEvents, SocketData>;
```

**Comment by OrkhanAlikhanov** [comment]
Also it would be nice to have `RemoteSocket.data` type safe. Right now it [defaults to `any`](https://github.com/socketio/socket.io/blob/51784d0305fda6695af9e325fd14edbabae4c5f4/lib/broadcast-operator.ts#L266)

Something like this:
```ts
myNamespace.fetchSockets<IExpectedSocketData>()
```

**Comment by darrachequesne** [comment]
@OrkhanAlikhanov that's a great idea! Would you have the time to open a pull request?

**Comment by OrkhanAlikhanov** [comment]
@darrachequesne When making `RemoteSocket.data` type safe, should `BroadcastOperator<EmitEvents>` also change to `BroadcastOperator<EmitEvents, SocketData>`? I ask because `BroadcastOperator.fetchSockets` is the method that returns `RemoteSocket`.

There are 2 options:
1. Make `BroadcastOperator` like `BroadcastOperator<EmitEvents, SocketData = any>`.
2. Only update `fetchSockets` method signature:
```ts
//from
fetchSockets(): Promise<RemoteSocket<EmitEvents>[]>
// to
fetchSockets<SocketData = any>(): Promise<RemoteSocket<EmitEvents, SocketData>[]>
```
