### ISSUE TITLE
TypeError: this.adapter.fetchSockets is not a function

### ISSUE THREAD

**Issue by SStoliarchuk** [socketio/socket.io#4235]
**Describe the bug**

when accessing the function fetchSockets on a namespace retrieved with a regex it throws an error:

command:
`io.of(/regex/).fetchSockets()`

error:
```
TypeError: this.adapter.fetchSockets is not a function
    at BroadcastOperator.fetchSockets (/node_modules/socket.io/dist/broadcast-operator.js:134:14)
    at ParentNamespace.fetchSockets (/node_modules/socket.io/dist/namespace.js:262:73)
```

Note: the function actually exists, it's just internally it's probably not bound properly?
if I do `typeof io.of(/regex/).fetchSockets === 'function'` it is true

**To Reproduce**
Use a regex instead of a string in the of() command
`io.of(<regex>).fetchSockets();`

with string it works fin
`io.of(<string>).fetchSockets();`

Socket.IO server version: `4.4.0`

*Server*
any server configuration

Socket.IO client version: `4.4.0`

*Client*
any client configuration

**Expected behavior**
It should return the array of sockets

**Platform:**
 - OS: Ubuntu
 - Chrome

**Additional context**

**Comment by darrachequesne** [comment]
I could indeed reproduce, thanks. I'm not sure how it should work though, because the `io.of(/regex/)` returns a parent namespace: https://github.com/socketio/socket.io/blob/master/lib/parent-namespace.ts

With a single Socket.IO server, we could loop over the `children` attribute and call `fetchSockets()` for each one of them.

It is a bit trickier with multiple Socket.IO servers, as `/namespace1` may exist on node1 but not `/namespace2`, while in the meantime `/namespace2` may exist on node2 but not `/namespace1`.

What do you think?

**Comment by SStoliarchuk** [comment]
I'm not familiar with how multiple Socket.IO instances behave, if they're all connected between them would it be possible to aggregate all the namespaces that matches the regex?

If it's not possible then I think if the return value is not reliable, this functionality should be removed
i.e. when doing 
`io.of(<regex>).fetchSockets()` 
an error should be thrown saying:
`Impossibile to use fetchSockets() on RegExp namespaces, please use maybeFetchSockets()`

And then there would be a `maybeFetchSockets()` function that works as described by you where it returns *probably* the correct sockets.

**Comment by darrachequesne** [comment]
That makes sense. Calling `fetchSockets()` on a parent namespace (that is, which was created with a regex) will now throw an error: https://github.com/socketio/socket.io/commit/3bf5d92735e8b57c00a57836211027ebb8eb3eae

As a workaround, you can use the `serverSideEmit()` method with an acknowledgement.

Reference: https://socket.io/docs/v4/server-api/#namespaceserversideemiteventname-args

**Comment by mattch** [comment]
Can you elaborate on how to get a list of sockets when using regex?

Using this:
`io.of(/^\/namespace.*$/).on("connection", fn); `

these don't work:
```
await io.fetchSockets();                                           // always empty
await io.of(/^\/namespace.*$/).fetchSockets();    // throws error as described above
```
