### ISSUE TITLE
[Documentation] Enabling debug logs in socket.io server

### ISSUE THREAD

**Issue by itzmanish** [socketio/socket.io#4236]
Hi, 
Is there any way to debug socket issue by getting debug logs of socket.io?

Also The documentation doesn't tell much about the transport error. So someone please tell me what causes this `transport error` and more information about this disconnect reason.

Thanks.

**Comment by darrachequesne** [comment]
Hi! You can enable the debug logs by setting the DEBUG env variable:

```
DEBUG=socket.io* node my-server.js
```

Reference: https://socket.io/docs/v4/logging-and-debugging/

The `transport error` disconnections comes when the connection between the client and the server gets closed, for example if the server gets shut down, or when the client closes its browser tab.

Reference: https://socket.io/docs/v4/server-socket-instance/#disconnect

**Comment by itzmanish** [comment]
Thanks @darrachequesne .
So when client closes browser at that time `transport close` reason comes with disconnect event. 
My server doesn't gets restart and I am sure about it. 

So what happened was there were 5 clients and all of them got closed at the same time with `transport error` reason and then got reconnected very next second.

No server crash or anything like that I got on logs.

Can it be due to RAM or CPU spikes?

**Comment by darrachequesne** [comment]
> Can it be due to RAM or CPU spikes?

I don't think so. If the server gets overloaded, you would see some `ping timeout` errors, not `transport close`.

Sounds like something (proxy, firewall, ...) between the server and your clients killed the TCP connections. Does it happen regularly?

**Comment by itzmanish** [comment]
So, I found out that the proxy disconnected the socket. But still I want to know the exact set of scenarios which generates `transport error` reason on disconnection.
I enabled debug with `socket.io* ` but I get lots of data that is not useful. So can I change the level of socket logs? If yes how can I achieve that?

**Comment by darrachequesne** [comment]
> So can I change the level of socket logs? If yes how can I achieve that?

You can't. You can specify the scope, like `socket.io:socket`, but not sure if that's what you are looking for.

The `transport error` comes from the Engine.IO layer, you can find the code [here](https://github.com/socketio/engine.io/blob/b04967b52eb1574cfaa6e24bdf164096322be96a/lib/socket.ts#L173). It can be triggered in several places, like [here](https://github.com/socketio/engine.io/blob/b04967b52eb1574cfaa6e24bdf164096322be96a/lib/transports/polling.ts#L88-L90) or [here](https://github.com/socketio/engine.io/blob/b04967b52eb1574cfaa6e24bdf164096322be96a/lib/transports/websocket.ts#L25).

**Comment by itzmanish** [comment]
Thanks @darrachequesne . [Here](https://github.com/socketio/engine.io/blob/b04967b52eb1574cfaa6e24bdf164096322be96a/lib/socket.ts#L173) I can see it passes an err object with the message `transport error`, so if I enable `engineio` logs then I will be able to see the err object right?

If yes, then this will be super helpful. If no then how do I know actual underlying error?

> You can't. You can specify the scope, like socket.io:socket, but not sure if that's what you are looking for.

Ok. If we make it like this `DEBUG=socket.io:socket:info` and change the logging code for getting level from this, then we can also set the log levels. I think a PR will be good for this. I will try to do as soon as possible.

**Comment by renehu** [comment]
Use below to log info about socket:
$ DEBUG=socket* node YOUR_FILE

Use below to log all info:
$ DEBUG=* node YOUR_FILE

**Comment by ngustavo** [comment]
`DEBUG=*` is not working on 4.5.1 
In my case it shows Playwright logs but not socketio server logs.
