### ISSUE TITLE
Kotlin multiplatform support

### ISSUE THREAD

**Issue by bigoloo** [socketio/socket.io#4240]
Hi All, 
Do you have any plan to support Kotlin multiplatform in SocketIO?

**Comment by darrachequesne** [comment]
Hi! Please check https://github.com/icerockdev/moko-socket-io

I've added it in the client list there: https://socket.io/docs/v4/

**Comment by Piasy** [comment]
Hi all, recently I created a pure Kotlin KMP implementation of SocketIO client, which is based on Ktor, so it's not just a wrapper for native implementation, and it supports almost all platforms that KMP supports.

Feel free to check it out: https://github.com/HackWebRTC/kmp-socketio
