### ISSUE TITLE
@socket.io/admin-ui does not work for m1 macs

### ISSUE THREAD

**Issue by itka0526** [socketio/socket.io#4241]
I think its trying to install bcrypt from github but the download does not exist

log from debug.log:
344 info run bcrypt@5.0.1 install node_modules/bcrypt node-pre-gyp install --fallback-to-build
345 info run bcrypt@5.0.1 install { code: 1, signal: null }
346 timing reify:rollback:createSparse Completed in 36ms
347 timing reify:rollback:retireShallow Completed in 0ms
348 timing command:install Completed in 9624ms
349 verbose stack Error: command failed
349 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
349 verbose stack     at ChildProcess.emit (node:events:390:28)
349 verbose stack     at maybeClose (node:internal/child_process:1064:16)
349 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
350 verbose pkgid bcrypt@5.0.1
351 verbose cwd /Users/itgelt/Desktop/coding/project_9 multichatapp/server
352 verbose Darwin 20.6.0
353 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "@socket.io/admin-ui"
354 verbose node v16.13.1
355 verbose npm  v8.1.2
356 error code 1
357 error path /Users/itgelt/Desktop/coding/project_9 multichatapp/server/node_modules/bcrypt
358 error command failed
359 error command sh -c node-pre-gyp install --fallback-to-build
360 error CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
360 error   LIBTOOL-STATIC Release/nothing.a
360 error   CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
360 error Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/itgelt/Desktop/coding/project_9 multichatapp/server/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/itgelt/Desktop/coding/project_9 multichatapp/server/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
361 error node-pre-gyp info it worked if it ends with ok
361 error node-pre-gyp info using node-pre-gyp@1.0.8
361 error node-pre-gyp info using node@16.13.1 | darwin | arm64
361 error node-pre-gyp info check checked for "/Users/itgelt/Desktop/coding/project_9 multichatapp/server/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" (not found)
361 error node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-darwin-arm64-unknown.tar.gz
361 error node-pre-gyp ERR! install response status 404 Not Found on https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-darwin-arm64-unknown.tar.gz
361 error node-pre-gyp WARN Pre-built binaries not installable for bcrypt@5.0.1 and node@16.13.1 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
361 error node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-darwin-arm64-unknown.tar.gz
361 error gyp info it worked if it ends with ok
361 error gyp info using node-gyp@8.3.0
361 error gyp info using node@16.13.1 | darwin | arm64
361 error gyp info ok
361 error gyp info it worked if it ends with ok
361 error gyp info using node-gyp@8.3.0

platform: macbook m1 air

**Comment by darrachequesne** [comment]
Hi! The `unknown` in  `bcrypt_lib-v5.0.1-napi-v3-darwin-arm64-unknown.tar.gz` seems suspicious, could you please open an issue there: https://github.com/kelektiv/node.bcrypt.js?

**Comment by itka0526** [comment]
Ok

**Comment by itka0526** [comment]
Should i remove this issue?

**Comment by darrachequesne** [comment]
@itka0526 you can keep it open until it is fixed upstream, in case someone else bumps on the same issue.

**Comment by md-seb** [comment]
@itka0526 try `npm rebuild bcrypt`

**Comment by darrachequesne** [comment]
It seems m1 macs are supported but there is a restriction in the project path:

> Users on Apple M1 Macs are supported but need to make sure that there are no spaces or special escapable characters in your entire project path

From https://github.com/kelektiv/node.bcrypt.js/pull/909

Please reopen if needed.
