### ISSUE TITLE
[Doc] The Readme badges "Dependency Status" and "devDependency Status" are failing

### ISSUE THREAD

**Issue by fmagaldea** [socketio/socket.io#4242]
**Describe the bug**
Some `Readme.md` badges are failing: "Dependency Status" and "devDependency Status".

**To Reproduce**

Just go to https://github.com/socketio/socket.io
<img width="1059" alt="socket-io-failing-icons" src="https://user-images.githubusercontent.com/6692252/148687029-98a93962-626d-4d59-bbc3-c820a3cb5363.png">

**Expected behavior**
Fix the failing domain (https://david-dm.org/) or just drop these icons if they are obsolete?

**Platform:**
 - Tested with Chrome 97 on Mac OS X

**Comment by darrachequesne** [comment]
Hi! I removed the badges. Thanks for the heads-up!

Related: https://github.com/alanshaw/david/issues/179
