### ISSUE TITLE
Proxy request errors with connection reset (ECONNRESET)

### ISSUE THREAD

**Issue by zachjonesnoel** [socketio/socket.io#4247]
**Describe the bug**
Whenever connecting to the proxy server, the websocket goes to 
`[HPM] Upgrading to WebSocket`
and then returns a proxy error.
**To Reproduce**

Please fill the following code example:

Socket.IO client version: `^4.4.1`

*Client*

```js
import { io } from "socket.io-client";
       this.socket = io({
        path: "/ssh/socket.io",
        transports: [ "websocket"],
        upgrade: false
      });

      this.socket.on("data", (data) => {
        this.term.write(data);
      });

      this.term.onData((data) => {
        this.socket.emit("data", data);
      });

      this.socket.on("connect", () => {
        this.socket.emit("geometry", this.term.cols, this.term.rows);
      });
      this.socket.on("error", (err) => {
        alert(err);
        // console.error('err', `Error: ${err}`)
        this.close();
      });
      this.socket.on("disconnect", (err) => {
        console.error("err", `WEBSOCKET SERVER DISCONNECTED: ${err}`);
        this.socket.io.reconnection(false);
        // countdown.classList.remove('active')
      });

```

**Expected behavior**
The connect should be successful and exchange messages

**Platform:**
- VueJS project
- Web socket server connected over a public IP.

**Additional context**
![image](https://user-images.githubusercontent.com/12515425/149090041-59818ef9-459b-4af1-909d-c9d76e9e04ed.png)

**Comment by darrachequesne** [comment]
It seems you are trying to reach a WebSocket server, is that the case? The Socket.IO client can only connect to a Socket.IO server, not a plain WebSocket server.

See also: https://socket.io/docs/v4/troubleshooting-connection-issues/#you-are-trying-to-reach-a-plain-websocket-server

**Comment by zachjonesnoel** [comment]
Yes, I'm trying to connect to a WS server. `upgrade: false` after removing it, the connection was established. From your response, I understand that if the server is not using Socket.IO, the connection shouldn't be established.

**Comment by darrachequesne** [comment]
@zachjonesnoel yes, exactly :+1:  The Socket.IO client is not a WebSocket client (though it uses a WebSocket connection under the hood).

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
