### ISSUE TITLE
Suddenly my client will not get a connection from server.

### ISSUE THREAD

**Issue by ohabash** [socketio/socket.io#4252]
I have an app (client && server on separate HEROKU servers)... Its been working perfectly for years. Now all the sudden the connection is intermittent. in v4 the error is 400 in v2 the error is cors... Ive tried almost every cors configuration i can think of.

It looks like the client connect and disconnects several times. sometimes the connection sticks but most of the time it disconnects before the frontend can join a room

It works perfectly with almost any configuration on localhost at all times

### **Client ==> "socket.io-client": "^4.4.1",**
```
this.socket = io(environment.backend, {
      withCredentials: true,
      extraHeaders: { dash: "abcd" },
    });
```
### **Server ==> "socket.io": "^4.4.1",**
```
this.io = new Server(server, {cors: { 
          origin: env.frontend_url, 
          allowedHeaders: ["dash"],
          credentials: true
        }});
```

often after a confirmed connection there is the following error
>websocket.js:54 WebSocket connection to 'wss://fornida-api.herokuapp.com/socket.io/?EIO=4&transport=websocket&sid=j64x9KB6m87VHUM4AAAJ' failed:

**Comment by darrachequesne** [comment]
Hi! You can't have both `origin: '*'` with `credentials: true`. This will trigger a CORS error:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘.../socket.io/?EIO=4&transport=polling&t=NvQfU77’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’)
```

You need to either give a specific origin, or remove the credentials. Please note that setting `withCredentials: true` is not needed for the `extraHeaders` to work (it's useful for the cookies though).

Reference:

- https://socket.io/docs/v4/client-options/#withcredentials
- https://socket.io/docs/v4/handling-cors/

**Comment by ohabash** [comment]
@darrachequesne sorry for the confusion.  I also replaced the star for the exact client url. With the same results. Also its worth considering that the frontend does connect sometime just more often than not disconnects before it is fully established.

**Comment by darrachequesne** [comment]
If it's an HTTP 400 error, it sounds like a "Session ID unknown" error, when some requests reach a different Socket.IO server in a multiple servers setup. Are sticky sessions enabled?

See also: https://socket.io/docs/v4/troubleshooting-connection-issues/

**Comment by ohabash** [comment]
@darrachequesne yes! thank you for this tip. I have not figured out how to do sticky sessions yet. But i know what you said is correct because when I turned off scaling in heroku (only one instance now) — The connection was instant and reliable. Thank you for sharing this info!

**Comment by darrachequesne** [comment]
@ohabash for the Heroku platform, you can check: https://devcenter.heroku.com/articles/session-affinity

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
