### ISSUE TITLE
Websocket connection failed (polling works), version 4.4.1

### ISSUE THREAD

**Issue by lucasscheuvens** [socketio/socket.io#4253]
**Describe the bug**
A websocket connection can't seem to be established. Polling however works fine. I want to serve socket.io over the same port as an http server. I'm not using any proxies, this is all localhost.
I get this error:
![image](https://user-images.githubusercontent.com/25504259/149766032-e519e96f-3d99-45cf-9a08-f58bbefb162f.png)
In the Network tab, I get "Finished" for the websocket connection.
![image](https://user-images.githubusercontent.com/25504259/149766245-367d8d22-51d4-45fd-99c4-77eb2898c77f.png)

**To Reproduce**

Socket.IO server version: `4.4.1`

*Server*

```js
(async function() {
  'use strict';
  
  // environment variables
  const PORT          = 8888
  
  // npm packages
  const express       = require('express')
  const app           = express()
  const server        = require('http').createServer(app)
  const io            = require('socket.io')(server)
  const { expressCspHeader, INLINE, SELF } = require('express-csp-header')
  
  io.attach(server)

  app.use(expressCspHeader({
    directives: {
      'default-src': [SELF],
      'script-src': [SELF, INLINE, 'https://cdnjs.cloudflare.com'],
      'connect-src': [SELF],
    }
  }))

  // serve static files in the 'public' directory
  app.use('/', express.static(__dirname + '/public'))
  
  // socket.io functions
  io.on('connection', function (socket) {
    console.log("Somebody connected via socket.io")
  })
  
  // start listening
  server.listen(PORT, () => {
    console.log(`Listening on port ${PORT} (HTTP + SOCKET.IO) ...`)
  }) 
  
})()

```

Socket.IO client version: `4.4.1`

*Client*

```js
let socket = io(window.location.host)

socket.on('connect_error', (err) => {
  console.log(`connect_error due to ${err.message}`)
})

socket.on('connect', function() {
  console.log('Connected to socket.io server')
}) 
```

**Expected behavior**
I expect the websocket connection to be established and preferred over long polling. 

**Platform:**
 - Device: MacBook Pro 2021 M1
 - OS: macOS 12.1 (Monterey)

**Comment by darrachequesne** [comment]
Hi! I think I've found the culprit, the HTTP server is attached twice:

```
// 1st
const io = require('socket.io')(server);

// 2nd
io.attach(server)
```

You need to remove one of them.

**Comment by lucasscheuvens** [comment]
🤦 Thank you for your reply. Can't believe I missed this...
I'm happy to buy you a coffee if you give me your Paypal address.
Best,
Lucas

**Comment by darrachequesne** [comment]
Yay :tada:

Sure, here it is: https://paypal.me/darrachequesne

Have a great day!
