### ISSUE TITLE
Socket IO disconnect more devices,

### ISSUE THREAD

**Issue by buiminhduc1995** [socketio/socket.io#4257]
Hi. I have 1 case get list user online. One user login 2 devices. Then logout in 1 devices, that user is offline. Is there any way to fix it?

**Comment by darrachequesne** [comment]
Hi! If I understand correctly your use case, you can use the `disconnectSockets` method:

```js
io.on("connection", (socket) => {

  socket.on("logout", () => {
    socket.in("theuserid").disconnectSockets();
  });

});
```

It will close every connection for the given user ID.

Reference: https://socket.io/docs/v4/server-api/#namespacedisconnectsocketsclose

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
