### ISSUE TITLE
Error: function model(doc, fields, skipId) { - when trying to io.to('some socket id').emit('key', val)

### ISSUE THREAD

**Issue by SashaShtal** [socketio/socket.io#4261]
**Describe the bug**
Getting error when trying to _io.to('some socket id').emit('key', val)_

It causes only when using socket.io in pm2 cluster with 2+ threads. 

Error: function model(doc, fields, skipId) {
0|server  |       model.hooks.execPreSync('createModel', doc);
0|server  |       if (!(this insta...<omitted>... } could not be cloned.
0|server  |     at writeChannelMessage (node:internal/child_process/serialization:82:9)
0|server  |     at process.target._send (node:internal/child_process:819:17)
0|server  |     at process.target.send (node:internal/child_process:719:19)
0|server  |     at process.send (/root/.nvm/versions/node/v16.13.0/lib/node_modules/@socket.io/pm2/lib/ProcessContainer.js:51:21)
0|server  |     at ClusterAdapter.publish (/home/server/workspace/web/dev/node_modules/@socket.io/cluster-adapter/dist/index.js:189:17)
0|server  |     at ClusterAdapter.broadcast (/home/server/workspace/web/dev/node_modules/@socket.io/cluster-adapter/dist/index.js:215:18)
0|server  |     at BroadcastOperator.emit (/home/server/workspace/web/dev/node_modules/socket.io/dist/broadcast-operator.js:109:22)
0|server  |     at /home/server/workspace/web/dev/app/discord/2auth.js:65:27
0|server  |     at runMicrotasks (<anonymous>)
0|server  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**To Reproduce**

Socket.IO server version: `4.1.3`

*Server*

```js
const {
  createServer
} = require("http");

const {
  Server
} = require("socket.io");

const {
  createAdapter
} = require("@socket.io/cluster-adapter");

const {
  setupWorker
} = require("@socket.io/sticky");
const cluster = require("cluster");

const httpServer = createServer(app); //app - express
var io = new Server(httpServer);

io.adapter(createAdapter());
setupWorker(io);

io.on("connection", (socket) => {

  socket.on('codeActivated', (data) => {
    require(`./app/module/2auth.js`)(data, io);
  })

});
```

*module*

```js
...some data gathering from db...
io.to(data.user_id).emit('auth', result)
//data.user_id - is a valid socket room (created in another file)
```

**Expected behavior**
Emiting event.

**Platform:**
 - OS: Ubuntu 20 LTS

**Comment by darrachequesne** [comment]
Hi! It seems the `result` object is not serializable. What kind of object is this?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
