### ISSUE TITLE
Room ID variable types matter

### ISSUE THREAD

**Issue by LithianCoth** [socketio/socket.io#4265]
**Describe the bug**
Room ID variable types matter

io.in(4)
io.in("4")
io.in('4')

These are all different room ids

So I am having to do RoomID+'' to correctly send data to clients in the room.

**To Reproduce**

When pulling a room ID from a database, it's being used as a single quote string.

Doing .toString() makes it a double quote string

Join a user to a room with a single quote string, then send a message to the room using a double quote string RoomID

Using NodeJs with the mysql library
Socket.IO server version: 4+

**Comment by darrachequesne** [comment]
You are right, room 4 (number) and room "4" (string) are different.

That being said, single or double quotes should not matter, could you please provide a reproducible test case?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
