### ISSUE TITLE
Switching internet connection from wifi to mobile data

### ISSUE THREAD

**Issue by sagarbhatt4** [socketio/socket.io#4268]
### Discussed in https://github.com/socketio/socket.io/discussions/4266

<div type='discussions-op-text'>

<sup>Originally posted by **sagarbhatt4** February  2, 2022</sup>
How can I continue to establish my socket while changing my internet connection?
Because currently, I am changing internet connection sockets are disconnected with throwing a "Transport Error" message.</div>

**Comment by darrachequesne** [comment]
The socket should reconnect over mobile network, isn't that the case?

What I mean is that the connection status of the socket is linked to the underlying TCP connection. If the TCP connection is interrupted, the socket will disconnect and reconnect right away, that's expected.

See also: https://socket.io/docs/v4/troubleshooting-connection-issues/

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
