### ISSUE TITLE
when reconnecting, disconnect event is triggered after connect event

### ISSUE THREAD

**Issue by shenX-2021** [socketio/socket.io#4273]
**Describe the bug**
after establishing connect, cut down network of client side for 5~8 seconds, and then recover network, you will see the server log like that: 
<img width="323" alt="disconnect" src="https://user-images.githubusercontent.com/35101675/153155539-6a5b7539-3f3e-453a-961b-bded868ff49f.png">

This is not the effect I expect, disconnect event should be triggered before next connect. How to achieve the effect I want?

**To Reproduce**

https://github.com/shenX-2021/socket.io-connect-demo

Socket.IO server version: `4.4.1`

Socket.IO client version: `4.4.1`

**Expected behavior**
disconnect event is triggered before next connect

**Platform:**
 - Device: Mackbook Pro
 - OS: Monterey 12.1

**Comment by darrachequesne** [comment]
Yes, that is the expected behavior, since the server acknowledges the disconnection of the first socket when the heartbeat fails.

Could you please explain your use case?

**Comment by shenX-2021** [comment]
I want to keep the socket.id in cache when user connected, and drop the cache when user disconnected. But in this mechanism, it will drop the cache of new connect.

**Comment by darrachequesne** [comment]
In that case, you should be able to check the number of socket instances linked to the user upon disconnection:

```js
io.on("connection", (socket) => {
  const userId = computeUserId(socket);

  socket.join(userId);

  socket.on("disconnect", async () => {
    const sockets = await io.in(userId).fetchSockets();
    if (socket.length === 0) {
      // no more active connections, drop the cache
    }
  });
});
```

Reference: https://socket.io/docs/v4/server-api/#serverfetchsockets

**Comment by shenX-2021** [comment]
thanks for response.
if `computeUserId` function is async function, this is not worked.
So i just do something in this mechanism.

**Comment by darrachequesne** [comment]
@shenX-2021 oh, in that case, you just need to add an `async` keyword:

```js
io.on("connection", async (socket) => {
  const userId = await computeUserId(socket);

  socket.join(userId);

  socket.on("disconnect", async () => {
    const sockets = await io.in(userId).fetchSockets();
    if (socket.length === 0) {
      // no more active connections, drop the cache
    }
  });
});
```

Please reopen if needed.
