### ISSUE TITLE
Web Client is not connecting to socket.

### ISSUE THREAD

**Issue by OguzhanUmutlu** [socketio/socket.io#4280]
**Describe the bug**
Web client is not connecting to socket.

**To Reproduce**

Socket.IO server version: `4.4.1`

*Server*

```js
const express = require("express");
const expressApp = express();
const server = require("http").createServer(expressApp);
const io = new (require("socket.io")).Server(server);
io.on("connection", async socket => {
    console.log("test");
});
server.listen(80);
```

Socket.IO client version: `4.4.1`

*Client*

```html
<script src="./node_modules/socket.io/client-dist/socket.io.js"></script>
<script>
    const socket = io();
</script>
```

**Expected behavior**
It should send the "test" message to server console.

**Platform:**
 - OS: Windows

**Additional context**
-

**Comment by darrachequesne** [comment]
Hi! Do you get any error in your browser console? Is the server reachable?

Please check https://socket.io/docs/v4/troubleshooting-connection-issues/

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
