### ISSUE TITLE
Add data as "sidecar" to heartbeat events

### ISSUE THREAD

**Issue by fzyzcjy** [socketio/socket.io#4282]
I need to have some sidecar data that is sent along the heartbeat events. (Why I do this: Without doing this, I need to send those data as one single event, and it will cost much more resources for the server). However, it seems that currently the heartbeat cannot be customized, neither can I add some sidecar data to it.

Thanks for any suggestions!

**Comment by darrachequesne** [comment]
Yes, you are right, you cannot currently customize the heartbeat packet.

I'm not sure that's a good idea though, as it would deviate from the current protocol and break existing clients.

> it will cost much more resources for the server

Could you please give some additional details? WebSocket connections are quite powerful for sending chunks of data.

**Comment by fzyzcjy** [comment]
> Could you please give some additional details? WebSocket connections are quite powerful for sending chunks of data.

Send/receive messages of websocket needs CPU, memory, logging, monitoring, etc for the server. So if I can combine two messages into one, then the cost can be less.

**Comment by darrachequesne** [comment]
I don't think we will implement this. Thanks!
