### ISSUE TITLE
Client script won't server to iOS 14 device

### ISSUE THREAD

**Issue by noyearzero** [socketio/socket.io#4290]
I have an iPhone X (the only apple device I have for testing).  It has iOS 14.4.  When trying to serve the client script to it (from socket.io server), it gets a 404 error.  If I serve the client script manually from another server it loads fine but won't connect to the socket server.  My setup fully works on Windows and Android devices.  So it seems like it's somehow detecting that something won't work with that device, but I'm not sure what.  As far as I can tell it should be supported.  

Not too long ago I upgraded from socket.IO v2 to v4.  I'm not sure, but I _think_ that it was working when on v2.  Either way, I didn't change much in the config.  I'm curious if there are any known issues, or "gotchyas" I'm not aware of.  Thanks.

**Comment by darrachequesne** [comment]
For future readers:

We were not able to reproduce the issue. Please reopen if needed.
