### ISSUE TITLE
Return 413 when request payload is bigger than `maxHttpBufferSize`.

### ISSUE THREAD

**Issue by maxfliri** [socketio/socket.io#4293]
With polling transport, if the client sends a request with a payload bigger than `maxHttpBufferSize`, the server returns a response with status 502 Bad Gateway. It should instead return 413 Payload Too Large.

**Comment by darrachequesne** [comment]
You are absolutely right! I have updated the HTTP status: https://github.com/socketio/engine.io/commit/e24b27b8efaf621af372f44b7c0ece3d801c603e
