### ISSUE TITLE
socket.io adapter with nats.io as message system

### ISSUE THREAD

**Issue by distrue** [socketio/socket.io#4294]
It take a while then expected, but finally finish to implement full specification of socket.io adapter!
It's released in https://github.com/distrue/socket.io-nats-adapter/releases/tag/v0.2.0,
and soon benchmark is updated on the repository.

Especially I'm interested in comparing performance between `socket.io-redis` and `socket.io-nats-adapter`. When good performance is obtained, considering to apply adapter on enterprise level on [channel.io](https://channel.io/en) service.

It would be glad to share implementation through the socket.io community and receive opinions to improve it. Can I share this contribution on socket.io adaptar section?

### Discussed in https://github.com/socketio/socket.io/discussions/4216

<div type='discussions-op-text'>

<sup>Originally posted by **distrue** December 16, 2021</sup>
Thanks for such a nice project `socket.io`! Recently I have built socket project with socket.io and [socket.io-redis-adapter](https://github.com/socketio/socket.io-redis-adapter). 

And I have reached to an limitation of building high-availability messaging system since redis single machine is bottleneck of the architecture. I considered redis-cluster to get rid of the problem, but it was unsuccessful to meet my requirement (1) easily auto-scalable and (2) well maintained messaging system client. In the midst of these concerns, I found [NATS.io](https://nats.io/) to alternate redis. 

Now I am building socket.io-adapter using NATS.io as messaging service. 
- repo: https://github.com/distrue/socket.io-nats-adapter
- npm: https://www.npmjs.com/package/socket.io-nats-adapter

The project probably be finished within this month, and I want to share the result with the community. Is there a process for sharing project to socket.io community? </div>

**Comment by darrachequesne** [comment]
Hi! I've added the adapter in the list there: https://socket.io/docs/v4/adapter/

Thanks a lot for your work on this :+1:
