### ISSUE TITLE
Websocket client not connecting to the NodeJS socket.io server with EIO v4

### ISSUE THREAD

**Issue by hrishibawane** [socketio/socket.io#4300]
### Discussed in https://github.com/socketio/socket.io/discussions/4299

<div type='discussions-op-text'>

<sup>Originally posted by **hrishibawane** February 27, 2022</sup>
I have a basic socket.io server (version 4.4.1) to which I am trying to connect with a C++ websocket client. 
If I use ```?EIO=3&transport=websocket``` as query parameters in the URL, the connection is successful and the ```io.on("connection")``` event is triggered on the server.
However, if I use ```?EIO=4&transport=websocket```, the connection does get successful but the ```io.on("connection")``` event is not triggered on server.

I have even tried from Postman client using Raw Websocket client too. It shows the same behaviours with EIO=3 and EIO=4.
I understand that socket.io has additional handling over raw websocket connection, but when connecting with EIO=3 in the URL, there
 are no issues seen. I also understand that after v2, the breaking change was the reversal of Ping/Pong messages. However, that part comes later in the socket life cycle. This issue I am facing is concerning the point of connection at which different behaviours are seen with Engine.io versions.

Any pointers on what extra needs to be done on the client or server side to resolve this?
</div>

**Comment by hrishibawane** [comment]
I have figured out the requirement for this to work as mentioned in the discussion.
However, I feel that this must be documented in engine.io and socket.io documentation.
Request to add the same.

**Comment by darrachequesne** [comment]
Hi! You can find more details about the Engine.IO & Socket.IO protocols there:

- https://github.com/socketio/engine.io-protocol
- https://github.com/socketio/socket.io-protocol
