### ISSUE TITLE
Send message to one connected client

### ISSUE THREAD

**Issue by lukeer** [socketio/socket.io#4310]
Hi forum,

I created this some minutes ago but it seems to have disappeared. Trying again:

There's an application ("the backend") using python flask socket.io. Multiple browsers ("the frontends") may connect to this application at the same time. One of the use cases requires that the backend sends a message to one of the frontends and to only this one frontend.

To distinguish one frontend from another, we use SocketIO.send() and its concept of "room"s.
```
            socketSendMethod(
                data = {
                    "ToolId" : self._toolId,
                    "ToolType" : self.ToolType.name,
                    "Value" : measurement
                },
                room = oneSession.Id
```
The room here is a session id that is generated and sent to the frontend upon user login. The frontend then stores this id in a cookie. It then triggers an event handler which uses the session id (called "room") as argument to join_room():
```
@socketio.on("join")
def join(message):
    join_room(int(message["room"]))
```
The join_room() method doesn't work outside of event handlers.

So we have a session id, have it stored in the backend and get its value as a cookie every time the frontend calls some route
```
@app.route("/", methods=["GET"]
def routeRoot():
    return(render_template("index.html"))
```
This way, so I thought, we could specify exactly which frontend to send a message to. But the message gets transferred to all the connected frontends, just like without mentioning the room in SocketIO.send() at all.

Digging into the problem, I found that send() doesn't know a "room" parameter. It uses "to" instead. But after fixing this, none of the connected clients gets the message. Digging deeper, I stumbled over BaseManager.emit() which is called some steps into the stack and checks if (this one is new) namespace exists in its self.rooms list, which is empty.

My question is: What should I do to populate the rooms list?

[Update]
There seems to be an issue with the
```
@socketio.on("join")
def join(message):
    join_room(int(message["room"]))
```
method. It doesn't get called. Except for seldom occurrences when it does. Not getting called is something I would suppose to have influence on the list of known rooms and therefore on my problem.

What can go wrong (mabe even on the frontend side?) so that an event like the one above doesn't get called? How can we fix this?

**Comment by darrachequesne** [comment]
Hi! You should be able to specify the room in the emit method:

```python
@sio.event
def my_message(sid, data):
    sio.emit('my reply', data, room='chat_users', skip_sid=sid)
```

Doesn't it work properly?

Reference: https://python-socketio.readthedocs.io/en/latest/server.html#emitting-events

**Comment by lukeer** [comment]
First of all, thank you [darrachequesne](https://github.com/darrachequesne). I don't know if one detail is relevant: My call to send() (or emit()) is triggered on the server side and therefore doesn't have an event handler context.

I can specify the room in SocketIO.send(), too. The argument is called **to** and is copied to **room** in SocketIO.emit(), which is called by **send()**. My problem is somewhere else: a few calls further down the stack, in **BaseManager.emit()**, a list of rooms is checked to contain our **namespace**. Of cause, we can use namespace if it fits better than **to** or **room**. But the list of rooms is empty and the method returns without sending anything.

I assume that the list of rooms is populated using **SocketIO.join_room()**. We have an event handler and an event for no other reason than to call this method because it doesn't work outside of event handlers. And that handler does not get called reliably.

So the question is: What can go wrong in client or server that makes event handler get called only sporadically?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
