### ISSUE TITLE
Socket will disconnect when client emit file to server in v4.4.1

### ISSUE THREAD

**Issue by liuxinqiong** [socketio/socket.io#4311]
**Describe the bug**
Socket will disconnect when client emit file to server in 4.4.1. The disconnect reason is "transport close".

After some tests, I found that it works fine in v2.3.1.

**To Reproduce**
Socket.IO server version: `4.4.1`

*Server*

```js
const { createServer } = require('http');
const { Server } = require('socket.io');

const httpServer = createServer();
const io = new Server(httpServer, {
  /* options */
  cors: {
    origin: '*',
  },
});

io.on('connection', (socket) => {
  console.log('connected');
  // ...
  socket.on('parse', (...args) => {
    console.log(args);
  });
});

httpServer.listen(4600);
```

Socket.IO client version: `4.4.1`

*Client*

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <input type="file" onchange="handleFile(event)" />
    <script src="https://cdn.socket.io/4.4.1/socket.io.min.js"></script>
    <script>
      var socket = io('http://localhost:4600/');
      function handleFile(e) {
        socket.emit('parse', e.target.files[0]);
        // socket.emit('parse', { a: 1 });
      }

      socket.on('disconnect', (reason) => {
        console.log(reason);
      });
    </script>
  </body>
</html>

```

**Expected behavior**
Server gets the binary message.

**Platform:**
Browser

**Additional context**

**Comment by darrachequesne** [comment]
Hi! I think you need to increase the `maxHttpBufferSize` value, which default to 1MB.

Reference: https://socket.io/docs/v4/server-options/#maxhttpbuffersize

**Comment by liuxinqiong** [comment]
> Hi! I think you need to increase the `maxHttpBufferSize` value, which default to 1MB.
> 
> Reference: https://socket.io/docs/v4/server-options/#maxhttpbuffersize

Thanks for your reply. your are right indeed.

The `maxHttpBufferSize` default value is 10e7 in v2.x, and now is 1e6 in v4.x. That's why it works fine in v2.x.
