### ISSUE TITLE
Should be Able to use module js

### ISSUE THREAD

**Issue by sayamkeshri** [socketio/socket.io#4316]
This socket.io is amazing. I am so happy to use this thing up in my projects but when it comes to modern applications then it is not that good. What I want is it should be able to use new version of node.js (experimental).

for example I cannot import the socket.io like this:
`import io form 'socket.io'`

**Describe the solution you'd like**
I know that it is not possible to make socket.io for common js  as well as for module js
So, I want a new version which is capable of module js and another version for common js

**Please! if possible that would be my humble request.** Lastly I was, I am, And I will be respecting all the grateful efforts of the developers of Socket
.io

**Comment by darrachequesne** [comment]
Hi! Thanks for the kind words :heart: 

You can totally use the ES module syntax:

```js
import { Server } from "socket.io";

const io = new Server({ /* options */ });

io.on("connection", (socket) => {
  // ...
});

io.listen(3000);
```

Reference: https://socket.io/docs/v4/server-initialization/
