### ISSUE TITLE
Not Working for Promise

### ISSUE THREAD

**Issue by sayamkeshri** [socketio/socket.io#4317]
Sir, I have been using socket.io for a long time. Recently I discovered a bug in it. And able to know why it's happening.
the thing is when we use promise like this:
```
socket.emit('someEvent', new Promise((resolve, reject)=>{
  resolve('something')
})
```
It do not works

The reason is when we pass objects in socket.emit function it converts object into string and when we reseve it, it again convers it into a object
As we know node js is not able to convert promises into strings so, this bug is created

I am sorry If it was me doing wrong. Anyway I solved it by making a custom `MyPromise` class.

**Comment by darrachequesne** [comment]
Hi! You can't pass a promise in the arguments array, but the following should work:

```js
const promise = new Promise((resolve) => {
  socket.emit('someEvent', resolve);
});

promise.then((result) => {
  
});

// or with async/await
const result = await promise;
```

See also: https://github.com/socketio/socket.io/issues/4175

**Comment by sayamkeshri** [comment]
Thank you, Sir!
And Sorry

**Comment by 98rahul** [comment]
> Hi! You can't pass a promise in the arguments array, but the following should work:
> 
> ```js
> const promise = new Promise((resolve) => {
>   socket.emit('someEvent', resolve);
> });
> 
> promise.then((result) => {
>   
> });
> 
> // or with async/await
> const result = await promise;
> ```
> 
> See also: #4175

`do{
const promise = new Promise((resolve,reject)=>{
 socket.emit("updateDB", fData, function(response){                  
  resolve(response)
  });	
   })
promise.then((res)=>{
  console.log('response',res)
                 if(res.success){
                              c++;
                }else{
         console.log('in-else')
                                                //do nothing
                                            }
                                        })}while(conditions);`


i just play around these lines of code to implement the socket in promise 
but it emits indefinitely.. that makes dev-tools memory full(it's obvious)

could you suggest what add/edit to these codes to make socket emit event in loop  batch/step-wise manner.

**Comment by darrachequesne** [comment]
@98rahul I'm not sure to understand your use case, could you please provide an example based on https://github.com/socketio/socket.io-fiddle? Thanks!

**Comment by darrachequesne** [comment]
@98rahul I'm not sure to understand your use case, could you please provide an example based on https://github.com/socketio/socket.io-fiddle? Thanks!

**Comment by darrachequesne** [comment]
@98rahul were you able to find a solution?

It seems you are not waiting for the completion of your promise:

```js
do {
  const promise = new Promise((resolve, reject) => {
    socket.emit("updateDB", fData, function (response) {
      resolve(response)
    });
  })
  
  promise.then((res) => {
    console.log('response', res)
    if (res.success) {
      c++; // do some updates in fData as fData has dependent variable on c
    } else {
      console.log('in-else') //do nothing
    }
  })
  
  await promise;
} while(c < 5);
```

Could you please check?

**Comment by 98rahul** [comment]
> @98rahul were you able to find a solution?
> 
> It seems you are not waiting for the completion of your promise:
> 
> ```js
> do {
>   const promise = new Promise((resolve, reject) => {
>     socket.emit("updateDB", fData, function (response) {
>       resolve(response)
>     });
>   })
>   
>   promise.then((res) => {
>     console.log('response', res)
>     if (res.success) {
>       c++; // do some updates in fData as fData has dependent variable on c
>     } else {
>       console.log('in-else') //do nothing
>     }
>   })
>   
>   await promise;
> } while(c < 5);
> ```
> 
> Could you please check?

@darrachequesne thanks it also worked! but i did something different with addition on more asynshronous way..

`do {
  const promise = new Promise(async (resolve, reject) => {
    await socket.emit("updateDB", fData, function (response) {
      resolve(response)
    });
  })
  
  promise.then((res) => {
    console.log('response', res)
    if (res.success) {
      c++; // do some updates in fData as fData has dependent variable on c
    } else {
      console.log('in-else') //do nothing
    }
  })
} while(c < 5)`
