### ISSUE TITLE
Error when running npm install for angular-client in basic-crud-application example

### ISSUE THREAD

**Issue by djd6797** [socketio/socket.io#4325]
**Describe the bug**
The following error occurs when trying to work through the tutorial at https://socket.io/get-started/basic-crud-application/

<img width="530" alt="image" src="https://user-images.githubusercontent.com/77515007/160476075-8f0cf32f-21d3-4a53-9961-709ddda34b9c.png">

**To Reproduce**

`git clone https://github.com/socketio/socket.io.git`
`cd socket.io/examples/basic-crud-application/`
`cd angular-client`
`npm install`

Observe error.

**Comment by darrachequesne** [comment]
Hi! I can't reproduce. Which version of npm are you using?

```
$ npm i

added 1469 packages, and audited 1470 packages in 37s

$ npm ls jasmine-core
angular-todomvc@0.0.0 /git/socket.io/examples/basic-crud-application/angular-client
├── jasmine-core@3.6.0
├─┬ karma-jasmine-html-reporter@1.5.4
│ └── jasmine-core@3.6.0 deduped
├─┬ karma-jasmine@4.0.1
│ └── jasmine-core@3.6.0 deduped
└─┬ protractor@7.0.0
  └─┬ jasmine@2.8.0
    └── jasmine-core@2.8.0
```

**Comment by djd6797** [comment]
Thanks for reaching out! I was using v8.4.0, but even updating to 8.6.0 still caused the error. I was able to resolve the issue from your screenshot though. I reverted the package of karma-jasmine-html-reporter to 1.5.4 instead of 1.7.0 and everything works fine now. 

Seems like replacing
`"karma-jasmine-html-reporter": "^1.5.0",`
with
`"karma-jasmine-html-reporter": "1.5.x",`

in the package.json file should resolve the problem. Thanks!

**Comment by darrachequesne** [comment]
@djd6797 OK, I think I found the culprit: https://github.com/dfederm/karma-jasmine-html-reporter/issues/54

I've updated the `package.json` file accordingly: https://github.com/socketio/socket.io/commit/9f758689f65f7770d974bcd17f8f0aab0fb84146

Thanks for the heads-up :+1:
