### ISSUE TITLE
Erro de Websocket

### ISSUE THREAD

**Issue by Guilhermealves20101999** [socketio/socket.io#4326]
Estou com esse erro dentro da minha aplicação do Socket.io, alguem sabe o motivo e como consigo resolver a mesma?

websocket.js:87 WebSocket connection to 'wss://aapi.dominio.com.br/socket.io/?EIO=4&transport=websocket&sid=bdEUxdbJhx8MVYr9AASe' failed:

**Comment by darrachequesne** [comment]
Hi! Did you check the troubleshooting section: https://socket.io/docs/v4/troubleshooting-connection-issues/

**Comment by rodriguesabner** [comment]
Cara, tem que melhorar essa questão aí. 

Da algum erro no console?
Qual versão do socket vc tá usando no front e no servidor?
A rota tá certa?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
