### ISSUE TITLE
Not able to proxy https requests using nginx

### ISSUE THREAD

**Issue by hitesh-kumar-mck** [socketio/socket.io#4337]
**Describe the bug**
We are trying to connect to our socket server via nginx reverse proxy. It is working fine when done using docker-compose on http but doesn't work when tried over https. 

**client(http) -> server(http)   -- `Working`
client(http) -> server(https)   -- `Not working`
client(https) -> server(https)   -- `Not working`**

**To Reproduce**

Socket.IO server version: `4.4.1`

*Server*

```js
const http = require("http")
const io = require("socket.io")(http).of("/mybot-ws");

io.on("connection", (socket) => {
  console.log(`connect ${socket.id}`);

  socket.on("disconnect", () => {
    console.log(`disconnect ${socket.id}`);
  });
});
```

*Nginx*
```
location /path1/path2/path3/ {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_pass https://abc.com/socket.io/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```

Socket.IO client version: `4.4.1`

*Client*

```js
import { io } from "socket.io-client";
  
const socket = io("/mybot-ws", { path: "/path1/path2/path3", transports: ['websocket'] });

socket.on("connect", () => {
  console.log(`connect ${socket.id}`);
});

socket.on("disconnect", () => {
  console.log("disconnect");
});
```

**Expected behavior**
Client and server should be able to connect in the current setup with nginx as a reverse proxy for socket.io

**Comment by darrachequesne** [comment]
Hi! A few questions:

- is the SSL connection terminated by nginx? Or is it terminated by the upstream server?
- are you using a self-signed certificate?
- do you see any error in the nginx logs?

Could you please provide a complete example reproducing the issue? You can start from [this](https://github.com/socketio/socket.io-fiddle/tree/nginx)).

**Comment by hitesh-kumar-mck** [comment]
1. We are unsure where is the connection being terminated. We are able to log http/https requests at our backend service but not socket.io requests. Neither did I find any way to check if socket requests are even arriving at the backend in the failing case.
2. We tried using self-signed certificate at localhost on our backend nodejs server and we were able to connect. However, when we point nginx to a remote https backend, it does not work.
3. Yes here are the nginx logs when pointed to remote https service.
`[debug] 25#25: *5 http upstream request: "/socket.io/?EIO=4&transport=websocket"`
`[debug] 25#25: *5 http upstream process upgraded, fu:1`
`[debug] 25#25: *5 recv: eof:0, avail:-1`
`[debug] 25#25: *5 recv: fd:13 3 of 4096`
`[debug] 25#25: *5 send: fd:12 3 of 3`
`[debug] 25#25: *5 event timer del: 13: 255503050`
`[debug] 25#25: *5 event timer add: 13: 60000:255528064`

I have pushed the changes [here](https://github.com/hitesh-kumar-mck/socket.io-fiddle/tree/issue/%234337)
Here, in the nginx conf, if we try to `proxy_pass` socket.io requests to a remote https server, it stops working.

**Comment by darrachequesne** [comment]
I think there are a few problems in your example:

- the `path` should match on both sides

```diff
// server.js
- const io = new Server(httpsServer, {}).of("/knowbot-ws");
+ const io = new Server(httpsServer, { path: "/path/path/path" }).of("/knowbot-ws");
```

Reference: https://socket.io/docs/v4/server-options/#path

- the namespace must match too (but that's surely a typo)

```diff
// main.js
- const socket = io("/myBot-ws", { path: "/path/path/path" });
+const socket = io("/knowbot-ws", { path: "/path/path/path" });
```

- the path is not needed in the `proxy_pass` directive

```diff
// nginx.conf
location /path/path/path/ {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
-      proxy_pass https://app:3000/socket.io/;
+      proxy_pass https://app:3000;
```

Also, if you set `proxy_ssl_verify on` in your Nginx configuration (off by default), you'll need to provide the certificate in the `proxy_ssl_trusted_certificate` option.

Reference: https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ssl_verify

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
