### ISSUE TITLE
Callback with Custom EventMaps is Type Error

### ISSUE THREAD

**Issue by RobertFischer** [socketio/socket.io#4348]
**Describe the bug**
When I specify my own `ListenEvents` and `EmitEvents` types, using a callback on one of the events is an error.

**To Reproduce**

```
import { Socket,Server } from "socket.io";
import type { EventsMap } from "socket.io/dist/typed-events";
import { createServer } from "http";

type ClientInitiatedEventsMap = EventsMap & {}

type ServerInitiatedEventsMap = EventsMap & {
	ping: () => void;
}

const httpServer = createServer();

const io:Server<ClientInitiatedEventsMap,ServerInitiatedEventsMap>
	= new Server(
		httpServer, 
		{ cors: { origin: "*" } }
	);

io.on("connection", (socket) => {
	// Next line is an error: "Expected 1 arguments, but got 2."
	socket.emit("ping", (callback) => {});  
});
```

Socket.IO server version: `4.4.1`

**Expected behavior**
I should be able to pass a callback to `emit` in order to get an acknowledgement.  Either that, or I would expect there to be a type that I could use in my custom events map in order to get that effect.

**Comment by RobertFischer** [comment]
Note that removing the custom `EventMap` implementations (ie: by doing just an un-annotated `new Socket` call) sidesteps the problem, but at the cost of having `any` types all over the place, which pretty much undermines TypeScript's ability to be useful for me.

**Comment by darrachequesne** [comment]
Hi! You should be able to type the acknowledgement method with:

```ts
type ServerInitiatedEventsMap = EventsMap & {
	ping: (callback: (value: string) => void) => void;
}
```

Reference: https://socket.io/docs/v4/typescript/

**Comment by RobertFischer** [comment]
Oh, okay -- so I need to explicitly specify when a callback is allowed/expected.  That makes sense -- I had assumed you always had the choice for a callback, no matter what the type is.  But I have no justification for that assumption.
