### ISSUE TITLE
socket disconnect event is throwing same reason for browser reload and machine sleep in mac

### ISSUE THREAD

**Issue by ManojkumarV** [socketio/socket.io#4350]
Is it possible to have different reasons for browser reload and machine sleep so that we can have different handling for both the scenarios. 

socket.io version: 3.0.0
socket.io-client version: 3.0.0

**Comment by darrachequesne** [comment]
Hi! In both cases, the WebSocket connection gets closed, so I don't think we can do much on our side.

You could use the `pagehide` event: https://developer.mozilla.org/en-US/docs/Web/API/Window/pagehide_event

Though I'm not sure you will be able to differentiate browser reload from machine sleep.

Please reopen if needed!
