### ISSUE TITLE
socket.volatile.emit encounter typescript error `Property 'volatile' does not exist on type 'RemoteSocket<ServerToClientEvents, any>'`

### ISSUE THREAD

**Issue by lilong7676** [socketio/socket.io#4358]
**Describe the bug**
```javascript
io.in('foo')
    .fetchSockets()
    .then(sockets => {
      sockets.forEach(socket => {
        socket.volatile.emit('hello', 'world'); // Property 'volatile' does not exist on type 'RemoteSocket<ServerToClientEvents, any>'
      });
    });Ï

```

**To Reproduce**

Please fill the following code example:

Socket.IO server version: `4.5.0`

*Server*

```js
import { Server } from "socket.io";

const io = new Server(3000, {});

io.on("connection", (socket) => {
  console.log(`connect ${socket.id}`);

  socket.on("disconnect", () => {
    console.log(`disconnect ${socket.id}`);
  });
});

io.in('foo')
    .fetchSockets()
    .then(sockets => {
      sockets.forEach(socket => {
        socket.volatile.emit('hello', 'world'); // Property 'volatile' does not exist on type 'RemoteSocket<ServerToClientEvents, any>
      });
    });
```

Socket.IO client version: `4.5.0`

*Client*

```js
import { io } from "socket.io-client";

const socket = io("ws://localhost:3000/", {});

socket.on("connect", () => {
  console.log(`connect ${socket.id}`);
});

socket.on("disconnect", () => {
  console.log("disconnect");
});
```

**Expected behavior**
socket.volatile.emit() working;

**Platform:**
 - OS: [MacOS bigsur]

**Additional context**

**Comment by lilong7676** [comment]
That's all I can do for now:
```typescript
(sock as unknown as Socket).volatile.emit('hello', 'world')
```

**Comment by darrachequesne** [comment]
Hi! Please note that:

```js
io.in('foo')
    .fetchSockets()
    .then(sockets => {
      sockets.forEach(socket => {
        socket.volatile.emit('hello', 'world'); // Property 'volatile' does not exist on type 'RemoteSocket<ServerToClientEvents, any>
      });
    });
```

can be rewritten into:

```js
io.volatile.in('foo').emit('hello', 'world');
```

which is much more efficient.

That being said, I guess we could add the various event modifier like `volatile` or `timeout`, but I'm afraid that would encourage users to use `fetchSockets() + emit() to one` instead of `emit() to many`. What do you think?

**Comment by lilong7676** [comment]
You are right, I did not read the document carefully.

**Comment by keyiis** [comment]
@darrachequesne If add `volatile` and `timeout` to `RemoteSocket<DefaultEventsMap, any>`, it should not cause the problem you said.

> Hi! Please note that:
> 
> ```js
> io.in('foo')
>     .fetchSockets()
>     .then(sockets => {
>       sockets.forEach(socket => {
>         socket.volatile.emit('hello', 'world'); // Property 'volatile' does not exist on type 'RemoteSocket<ServerToClientEvents, any>
>       });
>     });
> ```
> 
> can be rewritten into:
> 
> ```js
> io.volatile.in('foo').emit('hello', 'world');
> ```
> 
> which is much more efficient.
> 
> That being said, I guess we could add the various event modifier like `volatile` or `timeout`, but I'm afraid that would encourage users to use `fetchSockets() + emit() to one` instead of `emit() to many`. What do you think?
