### ISSUE TITLE
`BroadcastOperator.fetchSockets()` ignores flags

### ISSUE THREAD

**Issue by schw4rzlicht** [socketio/socket.io#4359]
**Describe the bug**

When using `BroadcastOperator.fetchSockets()`, flags that were set before (e.g. with `io.local.fetchSockets()` → sets `local: true` flag) are ignored.

This leads to all sockets across all nodes being returned for example instead of only the local ones.

I suspect this code to be responsible:

https://github.com/socketio/socket.io/blob/8ecfcba5c14cff079c59ccc32e6e5150b17b4a56/lib/broadcast-operator.ts#L262-L265

**To Reproduce**

Socket.IO server version: `4.4.1`

*Server*

see https://github.com/fan711/socket-server

Socket.IO client version: `4.4.1`

*Client*

see https://github.com/fan711/socket-client

**Expected behavior**

Previously set flags on `BroadcastOperator` should be respected. I'd suggest following change but I am not sure about any implications this might have, thus opening this as an issue instead of a PR:

```diff
      .fetchSockets({
        rooms: this.rooms,
        except: this.exceptRooms,
+       flags: this.flags,
      })
```

**Additional context**

Initially suspected https://github.com/socketio/socket.io-redis-adapter and opened https://github.com/socketio/socket.io-redis-adapter/issues/454 but I am happy to close that one if this one here is confirmed.

/cc @fan711

**Comment by derikb** [comment]
Would I think, save us some crazy extra redis usage if this could get released (please, thank you). Our pubsub traffic went a bit crazy when we updated to 4 and I think this is at least one of the causes. (Thanks for noticing this @schw4rzlicht and thanks for fixing it @darrachequesne )

**Comment by darrachequesne** [comment]
Letseee go: https://github.com/socketio/socket.io/releases/tag/4.5.1
