### ISSUE TITLE
is socket.onAnyOutgoing() executed when use io.emit() ?

### ISSUE THREAD

**Issue by HsinHeng** [socketio/socket.io#4375]
**Is your feature request related to a problem? Please describe.**
It's seem to not catch outgoing emitted event in socket.onAnyOutgoing() when i use io.emit()

**Describe the solution you'd like**
A extend utils liks io.onAnyOutgoing() for io.emit() ?

**Describe alternatives you've considered**
nothing.

**Comment by darrachequesne** [comment]
Yes it should be caught when broadcasting:

```js
io.on("connection", (socket) => {

  socket.onAnyOutgoing((event) => {
    console.log("onAnyOutgoing", event);
  });

  io.emit("hello");

});
```

Could you please check?

**Comment by HsinHeng** [comment]
> ```js
> socket.onAnyOutgoing((event) => {
>     console.log("onAnyOutgoing", event);
>   });
> ```

Sorry, It's my mistake.
Thank for your reply.
