### ISSUE TITLE
upgrade engine.io dependency for v2.4.1 to avoid vulnerability issue

### ISSUE THREAD

**Issue by gengshenghong** [socketio/socket.io#4377]
**Is your feature request related to a problem? Please describe.**
When using socketio v2.x version, there is a vulnerability issue (when using npm audit) as below (related to engine.io version):
[vulnerability](https://github.com/advisories/GHSA-j4f2-536g-r55m)

As socketio v2.x and v3.x/v4.x compatibility issue, it is sometimes not easy to upgrade to v3.x/v4.x version for some old apps.

**Describe the solution you'd like**
Is it possible to upgrade the dependency of engine.io to 4.0.0 above? I am not sure if engine.io is compatible to upgrade. If it is, could you please upgrade and release v2.4.2 version?

Thanks,
Shenghong

**Comment by darrachequesne** [comment]
Here we go:

- https://github.com/socketio/engine.io/releases/tag/3.6.0
- https://github.com/socketio/socket.io/releases/tag/2.5.0

The vulnerability warning should disappear once https://github.com/github/advisory-database/pull/446 is merged.

**Comment by darrachequesne** [comment]
And _voilà_!

```
$ npm i socket.io@2

added 39 packages, and audited 40 packages in 3s

found 0 vulnerabilities
```
