### ISSUE TITLE
"Unsupported protocol version" error response using commonJS

### ISSUE THREAD

**Issue by alilland** [socketio/socket.io#4381]
this is all on localhost, I have two user interfaces and one backend API, one user interface is React.js based and the other one is an old Angularjs page, both the React.js and backend API are able to talk successfully between eachother, React.js uses ES modules, and Angularjs uses commonJS

both user interfaces are using `socket.io-client ^4.5.0 (4.5.1)`
backend API is using `socket.io ^4.5.0 (4.5.1)`
nodeJS version is v16.15.0
MacOS - Monterey 12.3.1

this example works in my React app
```javascript
import io from 'socket.io-client'

const socket = io(process.env.NOTIFICATION_API, {
  auth: {
    token: '<token>'
  }
})
```
this example does NOT work in my Angularjs app, it returns HTTP 400 response errors
```javascript
const { io } = require('socket.io-client')

const socket = io(process.env.NOTIFICATION_API, {
  auth: {
    token: '<token>'
  }
})
```
error response:
```
General
Request URL: http://localhost:8888/socket.io/?EIO=3&transport=polling&t=O3tZbkp
Request Method: GET
Status Code: 400 Bad Request
Remote Address: [::1]:8888
Referrer Policy: strict-origin-when-cross-origin

Response Headers
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json
Date: Tue, 24 May 2022 19:32:23 GMT
Keep-Alive: timeout=5
Transfer-Encoding: chunked

Response Body
{
  "code": 5,
  "message": "Unsupported protocol version"
}
```

the API is not reporting any error responses

**Comment by alilland** [comment]
just resolved it with `allowEIO3`, but is there a way to make my commonJS connection us EIO4?

**Comment by darrachequesne** [comment]
The `EIO=3` query parameter suggests the client is in version 2.x, which would explain the "Unsupported protocol version" issue. Could you please check?

**Comment by darrachequesne** [comment]
Thanks for the update :+1:
