### ISSUE TITLE
TypeError: this.pingIntervalTimer.refresh is not a function

### ISSUE THREAD

**Issue by tavro** [socketio/socket.io#4390]
**Describe the bug**
There seems to be some dependency-issues:

/app/node_modules/browser-sync/node_modules/engine.io/build/socket.js:109
                 this.pingIntervalTimer.refresh();
                                        ^
TypeError: this.pingIntervalTimer.refresh is not a function
     at Socket.onPacket (/app/node_modules/browser-sync/node_modules/engine.io/build/socket.js:109:40)

[...]

**To Reproduce**
Socket.IO server version: `2.0.3`
Socket.IO client version: `1.4.8`
Node version: `8.9.3`
NPM version: `5.5.1`

**Platform:**
OS: Ubuntu

**Additional context**
Running in a docker container.
Added to a project based on open source project openstf/stf, so the dependencies looks alike.

**Comment by darrachequesne** [comment]
Hi! I think you need to upgrade your Node.js version, as `timer.refresh()` was added in Node.js 10.x: https://nodejs.org/api/timers.html#timeoutrefresh

Reference: https://socket.io/docs/v4/server-installation/#prerequisites

**Comment by tavro** [comment]
I tried installing that version of node as well as the newest one, but that did not fix it.

I wonder if this could be related to the Ubuntu-version... I installed the latest version yesterday

**Comment by darrachequesne** [comment]
@tavro I'm out of ideas then. Have you found the culprit?

**Comment by tavro** [comment]
> @tavro I'm out of ideas then. Have you found the culprit?

I have no idea, it's super weird. It seems to work perfectly after downgrading from Ubuntu 22.04 to 20.04.

**Comment by peedikuubik** [comment]
I, too, had this issue after running _npm install_ on an old project (Gulp, browsersync etc). Sort of solved it by copy-pasting the _node_modules_ folder from another project (which had the same _package.json_ content).

**Comment by beckbailey** [comment]
Also, having this issue.

**Comment by darrachequesne** [comment]
@beckbailey could you make sure you have Node.js >= 10.2.0 installed?

@peedikuubik I'm not sure copying the node_modules folder is a great idea :angel:

I'm closing this, as I don't think there is much more we can do...

**Comment by abhijeetknayak** [comment]
I had the same issue and installing Node.js >= 10.2.0 worked for me. Thanks!

**Comment by DanaStefanoska** [comment]
I just started to receive this problem on our Ubuntu Server ran in AWS EC2 instance.

Operating System: Ubuntu 18.04.2 LTS
Node: v16.20.0
Npm: 8.19.4
Socket.io: ^4.6.1
Socket.io-client: ^4.6.1

Additional info:
This error started to occur once we updated the node version on the server, it was 12.19.0 before. I tried also with node version 16.14.2 but we get the same error. The error occurs every ~30s and it crashes the whole instance of our server.
Also, removing node_modules and reinstalling them didn't help.

**Comment by darrachequesne** [comment]
@DanaStefanoska hi! Could you please make sure you have Node.js >= 10.2.0 installed?

**Comment by DanaStefanoska** [comment]
@darrachequesne hi! As mentioned above I have node 16.20.0, also tried with node 16.14.2

**Comment by DanaStefanoska** [comment]
@darrachequesne the problem was indeed the version. When I do node --version it's version 16.20.0, like mentioned above, but I tried to console.log process.version in my server code and it get's back with version 8.10.0 hence the error that we receive.

I wanted to write this comment in case anyone else has the same issue as us. We are currently looking for a fix for the wrong node version running.

**Comment by avaoffiziell** [comment]
> @darrachequesne the problem was indeed the version. When I do node --version it's version 16.20.0, like mentioned above, but I tried to console.log process.version in my server code and it get's back with version 8.10.0 hence the error that we receive.
> 
> I wanted to write this comment in case anyone else has the same issue as us. We are currently looking for a fix for the wrong node version running.

I have same Problem, it says v8.17.0. Did you found a fix?

**Comment by avaoffiziell** [comment]
In docker-compose.yml:

```
services:
  node:
    image: "node:20"
```
    
And then run: docker-compose up --build

Now my process version is latest and everything works!!
