### ISSUE TITLE
Error: Debug Failure. outdated ts.resolveTypeReferenceDirectives signature. 

### ISSUE THREAD

**Issue by sparshrestha** [socketio/socket.io#4409]
**Describe the bug**
```
ts.Debug.assert(typeof` typeReferenceDirectiveName === "string", "Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.");
```
**To Reproduce**
```
cd examples/basic-crud-application/server
npm install
npm start
```

Socket.IO server version: `4.5.1`

*Server*

```
  "devDependencies": {
    "@types/chai": "^4.2.16",
    "@types/mocha": "^8.2.3",
    "@types/uuid": "^8.3.0",
    "chai": "^4.3.4",
    "mocha": "^10.0.0",
    "nyc": "^15.1.0",
    "socket.io-client": "^4.0.1",
    "ts-node": "^9.1.1",
    "typescript": "^4.2.4"
  }
```

**Expected behavior**
Server for the Basic CRUD Socket.IO example should be running without DEBUG Errors.

**Quick Fix**
`resolveTypeReferenceDirectives` is outdated. Removing `^` in server's `package.json` prevents `npm install` to fetch latest typescript version and thus works fine running the server side code. #4408

**Comment by darrachequesne** [comment]
Hi! This should be fixed by https://github.com/socketio/socket.io/commit/19b225b0c8a093d7f54ccf1b9d3765bc8f463a65.

Thanks for the heads-up :heart:
