### ISSUE TITLE
TypeError: process.nextTick is not a function

### ISSUE THREAD

**Issue by ItzArty** [socketio/socket.io#4412]
Socket.IO server version: 4.5.1

Code:
```
const sio = require("socket.io");
const clientIO = sio(69, { cors: { origin: "*", methods: [ "GET", "POST" ], credentials: true } })
```

Error:
```
D:\...\node_modules\ws\lib\websocket-server.js:181
        process.nextTick(emitClose, this);
                ^

TypeError: process.nextTick is not a function
```

**Comment by darrachequesne** [comment]
Hi! That's weird, which version of Node.js are you using?

Reference: https://nodejs.org/api/process.html#processnexttickcallback-args

**Comment by ItzArty** [comment]
I managed to fix the issue, it turns out, that for some reason, when I defined `this.process` inside a function block, it replaced the global process variable as well, but the function blocks process was defined properly, I have no idea, why this is the case, but its settled, sorry for the annoyance.

**Comment by darrachequesne** [comment]
@ItzArty great, thanks for the update :+1:
