### ISSUE TITLE
Uncaught Error: unknown packet type NaN

### ISSUE THREAD

**Issue by startpimp** [socketio/socket.io#4417]
![image](https://user-images.githubusercontent.com/41271417/177482524-f7ff1558-ef42-455f-98c0-ae3c2d31ddd1.png)
I'm currently getting this error on socket.io@4.5.1.

I don't know why I am getting this problem, but here is the code I use. There's nothing more from the client-side code, and this is where I'm getting the error : 

```js
const WS = io();

function heartbeat() {
  clearTimeout(this.pingTimeout);
  this.pingTimeout = setTimeout(() => {
    this.terminate();
  }, 10000 + 1000);
}


WS.on("open", heartbeat);
WS.on("ping", () => {
	heartbeat();
	WS.emit("pong")
});
WS.on("close", () => {
	clearTimeout(this.pingTimeout);
});
```

**Expected behavior**
Just a ping control on each client to prevent a bad navigator clising or something else, to disconnect the user in the database.

**Platform:**
 - OS: Windows 10

**Comment by dhenson02** [comment]
I'm not seeing it in Ubuntu x64 (server and client) with Node 14 and Chrome 103, but someone on my team has seen it (on Windows server and client).

Out of curiosity what Node and Chrome versions are you running @startpimp?  And are you connecting directly to Node from the client or using HAProxy, nginx, etc. in between?

**Comment by startpimp** [comment]
I'm using node v16.14.2 and I'm currently running my client on Opera GX, but I can't find its version ; I don't know where it is.

By the way, I'm not using a proxy or something between my server and my client. They are both running on the same machine, in localhost

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-client/commit/c5970231699aa47b00c4a617af4239d0fa90fa53, included in [`socket.io-client@4.5.2`](https://github.com/socketio/socket.io-client/releases/tag/4.5.2).

Thanks for the report :+1:
