### ISSUE TITLE
Compatibility with MyPy

### ISSUE THREAD

**Issue by rustam-ashurov-mcx** [socketio/socket.io#4432]
MyPy fails to analyze typings from socket.io throwing errors like:

`Skipping analyzing "socketio": module is installed, but missing library stubs or py.typed marker`

Could we add py.typed file in the root folder of socket.io distribution package, it would be great to have type checking

**Comment by darrachequesne** [comment]
Hi! Could you please open an issue in the repository of the Python implementation? Thanks!

Link: https://github.com/miguelgrinberg/python-socketio
