### ISSUE TITLE
Typescript error using http2 server

### ISSUE THREAD

**Issue by Jayce53** [socketio/socket.io#4434]
**Describe the bug**
The socket.io Server constructor types do not include Http2SecureServer so there's a type error when instantiating a Server as per the documentation HTTP/2 example.

**To Reproduce**

Socket.IO server version: `4.5.1`

*Server*
Example directly from [documentation](https://socket.io/docs/v4/server-initialization/#with-an-http2-server) 

Example in [Typescript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzlApgQwCYDFgBsUDKAngHYDGcAvnAGZQQhwBENAzkwNwBQoksicMqjQxCKMgFdUBFFABusqrXqMmACxgwwAJk49w0eEhnzF1Og2asIZANYoYAOmAQ9XMhBKt4GrSYVQcAC8gsKiMpLSsgEAFAhccHBouLgQAO4AEgAqWQAKAIwAXHAwUBIoADQJcPZExcLYeISkZDFMAPRgImrtMBDtIETttY5gKCBMAJRViWSyMPXojfjE5G2d3b39g+1zsKPjU1yUk9zunt5wLsFwJChpcP6yMb5gT1AVAu0AVHAQYDAXF44N92lRTlweBBHJ42h4SHcyIDPExPjFrHYHJNggA+RDVdpgxzE44Qrivd6OXDAbwoEgxADMAAYWacgA)

**Expected behavior**
No typescript errors

**Comment by williamd5** [comment]
I believe I have the same error in #4494 as well

**Comment by darrachequesne** [comment]
Fixed by https://github.com/socketio/socket.io/commit/d3d0a2d5beaff51fd145f810bcaf6914213f8a06, included in [4.5.3](https://github.com/socketio/socket.io/releases/tag/4.5.3). Thanks :+1:
