### ISSUE TITLE
'Transport close' in production mode

### ISSUE THREAD

**Issue by npodexp5** [socketio/socket.io#4446]
**The bug**
I am creating a tool using `NextJS` and I am getting a disconnect(`transport close`) at a random time, it reconnects right away, but it bothers some tasks

I've tried various settings, like changing the pingInterval, pingTimeout. But no matter what I seem to do, the problem never goes away.

**This problem doesn't happen in localhost**, it only happens when I send my server to Google Cloud, Railway.app or Digitalocean

Socket.IO server version: `"socket.io": "4.5.1"`

*Server*

```js
import { Server } from "socket.io";

const io = new Server(3000, {});

io.on("connection", (socket) => {
  console.log(`connect ${socket.id}`);

  socket.on("disconnect", () => {
    console.log(`disconnect ${socket.id}`);
  });
});
```

Socket.IO client version: `"socket.io-client": "4.5.1",`

*Client*

```js
import { io } from "socket.io-client";

const socket = io("ws://localhost:3000/", {});

socket.on("connect", () => {
  console.log(`connect ${socket.id}`);
});

socket.on("disconnect", () => {
  console.log("disconnect");
});
```

 - Windows - Chrome

**Comment by darrachequesne** [comment]
For future readers:

> First and foremost, please note that disconnections are common and expected, even on a stable Internet connection:
>
> - anything between the user and the Socket.IO server may encounter a temporary failure or be restarted
> - the server itself may be killed as part of an autoscaling policy
> - the user may lose connection or switch from WiFi to 4G, in case of a mobile browser
> - the browser itself may freeze an inactive tab

Reference: https://socket.io/docs/v4/troubleshooting-connection-issues/#problem-the-socket-gets-disconnected

That being said, you can enable connection state recovery to restore the state of the client after a temporary disconnection.

See: https://socket.io/docs/v4/connection-state-recovery
