### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by leviluo** [socketio/socket.io#4451]
socket.io version:^4.5.1

memory keep increasing and no reduce, it seems that every connection will never be released，unconnected socket will stay in memory will never be released

this is my main socket.io code:
[chat.js.zip](https://github.com/socketio/socket.io/files/9332503/chat.js.zip)

this is dump file socket.io server at start:
[1660347155092.heapsnapshot.zip](https://github.com/socketio/socket.io/files/9332499/1660347155092.heapsnapshot.zip)

this is dump file socket.io server after about 12 hours:
[1660434926431.heapsnapshot.zip](https://github.com/socketio/socket.io/files/9332500/1660434926431.heapsnapshot.zip)

nodejs log
<img width="1218" alt="截屏2022-08-15 14 18 34" src="https://user-images.githubusercontent.com/19730473/184586081-253596c6-0607-46ea-b60d-53f2cc8110fd.png">
![屏幕截图 2022-09-12 074103](https://user-images.githubusercontent.com/19730473/189553871-5da8a1aa-b19a-423e-9581-3b4a699470f9.png)

nodejs exists a lot of unrecyler connection，actually socket server has at most 50 connections at one time,but memory show 1000+connections.
<img width="860" alt="截屏2022-08-22 15 53 23" src="https://user-images.githubusercontent.com/19730473/185868889-564fdc16-c218-46db-8042-6e56f8998542.png">

<img width="954" alt="截屏2022-08-17 20 10 06" src="https://user-images.githubusercontent.com/19730473/185115287-6d10ad3d-82ed-4567-bc7a-c31897c52ee2.png">

this is memory record at start:
{
  gc_ts: 1660435083534346,
  gcScavengeCount: 6,
  gcScavengeTime: 35094684,
  gcMarkSweepCompactCount: 1,
  gcMarkSweepCompactTime: 11370196,
  gcIncrementalMarkingCount: 2,
  gcIncrementalMarkingTime: 779792,
  gcProcessWeakCallbacksCount: 1,
  gcProcessWeakCallbacksTime: 229,
  total_heap_size: 109916160,
  total_heap_size_executable: 2359296,
  total_physical_size: 109668288,
  total_available_size: 2089975504,
  used_heap_size: 82783856,
  heap_size_limit: 2197815296,
  malloced_memory: 1065032,
  peak_malloced_memory: 3763256,
  gc_time: 11370196
}

this is memory record after about 12 hours:
{
  gc_ts: 1660434978708896,
  gcScavengeCount: 8330,
  gcScavengeTime: 6094003772,
  gcMarkSweepCompactCount: 68,
  gcMarkSweepCompactTime: 1072605909,
  gcIncrementalMarkingCount: 132,
  gcIncrementalMarkingTime: 61912948,
  gcProcessWeakCallbacksCount: 2,
  gcProcessWeakCallbacksTime: 4448,
  total_heap_size: 114634752,
  total_heap_size_executable: 5767168,
  total_physical_size: 113205152,
  total_available_size: 2085620912,
  used_heap_size: 109306480,
  heap_size_limit: 2197815296,
  malloced_memory: 4210760,
  peak_malloced_memory: 4870952,
  gc_time: 36112984
}

**Comment by dhenson02** [comment]
unrelated but you've got some overlapping variable names.  probably would help to organize and refactor a bit.

**Comment by lafkpages** [comment]
I also got a memory leak in a Socket.IO game.

**Comment by jiouiuw** [comment]
I download the `chat.js.zip`, oh my god, so many leak possible change in the code...

**Comment by leviluo** [comment]
> I download the `chat.js.zip`, oh my god, so many leak possible change in the code...

please tell me many leak possible code ? thanks a lot

**Comment by jiouiuw** [comment]
try 4.5.2

**Comment by jiouiuw** [comment]
Another suggest, if you write node.js, typescript is a good choice, strong type.

**Comment by jiouiuw** [comment]
@leviluo your js code is messy

**Comment by leviluo** [comment]
> Another suggest, if you write node.js, typescript is a good choice, strong type.

thanks a lot，i have try 4.5.2，but it still memory leak, in next day i will try typescript.

**Comment by darrachequesne** [comment]
I'm going to close this, as the memory leaks does not seem to come from Socket.IO itself. Please reopen if needed.

**Comment by Aaryan7631** [comment]
csss
