### ISSUE TITLE
CORS still blocked after implementing CORS handling (Behind a proxy server)

### ISSUE THREAD

**Issue by aryawpratama** [socketio/socket.io#4453]
**Describe the bug**
CORS still block my request after implementing CORS Handling form the documentation

**To Reproduce**

Please fill the following code example:

Socket.IO server version: `4.5.1`

*Server*

![image](https://user-images.githubusercontent.com/75900371/185312621-8b6026ee-02ca-429c-9f58-cd41830020ed.png)

Even tough I change the `"*"` in origin to my origin request it doesn't affect anything, it seems like this: 

![image](https://user-images.githubusercontent.com/75900371/185314185-31e8a8b3-ff32-44f4-9dec-b7374415cc74.png)

Socket.IO client version: `4.5.1`

*Client*

I'm using Vue but I prefer to init the socket manually

![image](https://user-images.githubusercontent.com/75900371/185310638-a44bed91-0052-44c6-a186-92b1caa4add4.png)

The CORS Error log

![image](https://user-images.githubusercontent.com/75900371/185310893-bd452f07-62e2-4f90-8285-74d521e71f8a.png)

I'm using ngrok instead of my VPS for development, but it happened in my VPS too

Thank you in advance!

**Comment by darrachequesne** [comment]
Hi!

Did you find a solution? At first sight, I'd say that the client is not able to reach the Socket.IO server, hence the missing headers. Could you please check?

Reference: https://socket.io/docs/v4/handling-cors/

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by lautiamkok** [comment]
I am having this issue with version 4.6. It was working fine. Now not working at all. No idea why..

**Comment by lautiamkok** [comment]
@darrachequesne it seems that CORS issue has gone after adding a CORS middleware to my server app which is a Koa app, running on `http://localhost:5000`.

But now I have this new issue - I get a 404 for the URL below:

http://localhost:5000/socket.io/?EIO=4&transport=polling&t=OPAk3hO

Why is it calling that URL?

A screenshot of my screen:

![Screenshot_20230213_202703](https://user-images.githubusercontent.com/427931/218457809-750043be-df49-4378-9ea6-c1ea478e2a08.png)

**Comment by lautiamkok** [comment]
The code on client page that is calling the server:

// ./pages/users.vue
import io from 'socket.io-client'
const socket = io('http://localhost:5000/')

**Comment by darrachequesne** [comment]
It seems the client is not able to reach the Socket.IO server. How are you initializing the server?

Reference: https://socket.io/docs/v4/server-initialization/#with-koa

**Comment by lautiamkok** [comment]
@darrachequesne here is code:

```
import Koa from 'koa'
import { koaBody } from 'koa-body'
import serve from 'koa-static'
import cors from '@koa/cors'

import http from 'http'
import { Server } from 'socket.io'

const app = new Koa()

app.use(cors())
app.use(koaBody({
  multipart: true,
  parsedMethods: ['POST', 'PUT', 'PATCH', 'GET', 'HEAD', 'DELETE']
}))
app.use(serve('.'))
app.use(serve('./static/fixtures'))

const server = http.createServer(app.callback())
const io = new Server(server, {
  cors: {
    origin: 'http://localhost:3000'
  }
})

io.sockets.on('connection', socket => {
  //...
})
```

Have I missed anything?

**Comment by lautiamkok** [comment]
Oh! I know why:

`export const viteNodeApp = app`

I am using Vite and [vite-plugin-node](https://github.com/axe-me/vite-plugin-node) on top of my Koa app.

But I don't know how to integrate them properly. So I have to build the Koa app and run the built app so `httpServer.listen(port, host)` can be triggered. So, that means I can't run socket.IO on development.

Do you have any idea how to use socket.IO with Vite and `vite-plugin-node`?

**Comment by singhmona1** [comment]
hi, I am getting the same issue
