### ISSUE TITLE
Is it possible to provide typescript types outside of io.on("connection")?

### ISSUE THREAD

**Issue by Rec0iL99** [socketio/socket.io#4455]
### Discussed in https://github.com/socketio/socket.io/discussions/4454

<div type='discussions-op-text'>

<sup>Originally posted by **Rec0iL99** August 23, 2022</sup>
I want to pass my typescript types outside of the `io.on("connection")` event. Is this possible to do?

This is how my setup looks like:

```ts
// types for socket.io
export interface ServerToClientEvents {
  RCV_MSG: (data: {
    fromUserId: number;
    type: string;
    message: string;
    toTeam: boolean;
  }) => void;
  get_room_after_connect: (room: Room) => void;
}
```

```ts
// index.ts where I initialize my socket.io server
const io = new Server<ServerToClientEvents>(server, {
    cors: {
      origin: [
        process.env.CORS_ORIGIN,
        process.env.SOCKET_ADMIN_DASHBOARD_ORIGIN,
      ],
      credentials: true,
    },
});

io.on("connection", async (socket) => {
   // here I'm able to access the type for get_room_after_connect from ServerToClientEvents interface
   socket.emit("get_room_after_connect", room!);
   // this is a custom function I created where I have various functions which will emit something using socket.io to client once the logic finishes
   // I'm passing the socket object to handleUserEvents which will then distribute it to the various functions
   // the problem I'm facing is that I'm not able to access my types defined in ServerToClientEvents interface in handleUserEvents when I emit something to the client from there
   handleUserEvents({ socket, io, redis, currentUserId });
});
  
```

Please let me know if I'm doing something wrong or Socket.io does not support this functionality.

Note: please do read my comments in code to understand the code snippets better

Thanks</div>

**Comment by darrachequesne** [comment]
Hi!

Did you find a solution? You could forward the types to the `handleUserEvents` method:

```js
function handleUserEvents({ socket: Socket<ServerToClientEvents, ClientToServerEvents>, ... }) {
  // ...
}
```

What do you think?

**Comment by Rec0iL99** [comment]
> Hi!
> 
> Did you find a solution? You could forward the types to the `handleUserEvents` method:
> 
> ```js
> function handleUserEvents({ socket: Socket<ServerToClientEvents, ClientToServerEvents>, ... }) {
>   // ...
> }
> ```
> 
> What do you think?

@darrachequesne I did not think about this approach.

Thanks a lot, it works by sending ServerToClientEvents as generic to Socket type.
