### ISSUE TITLE
Is the version of Releases and tags written wrong? Why is the update still lower?

### ISSUE THREAD

**Issue by git136975643** [socketio/socket.io#4464]
Version from 4 to 2

**Comment by darrachequesne** [comment]
Hi! The latest version is indeed [2.5.0](https://github.com/socketio/socket.io/releases/tag/2.5.0), which is a release of the 2.x branch with bug fixes reported from the main branch.

But the "actual" latest version is [4.5.1](https://github.com/socketio/socket.io/releases/tag/4.5.1):

```
$ npm info socket.io

socket.io@4.5.1 | MIT | deps: 6 | versions: 143

[...]

dist-tags:
beta: 3.0.0-rc4   latest: 4.5.1     v2-latest: 2.5.0
```

Does that make sense?

**Comment by darrachequesne** [comment]
Latest release is now 4.5.2: https://github.com/socketio/socket.io/releases/tag/4.5.2

Please reopen if needed.
