### ISSUE TITLE
fetchSockets with redis errors with circular structure

### ISSUE THREAD

**Issue by lockphase** [socketio/socket.io#4484]
**Describe the bug**
I have an express server running behind a nginx reverse proxy with pm2 and redis. My client connects via websocket transport. When I open 2 browser connections, each connection will be handled by different pm2 processes. Upon connection, server side will perform a fetchSockets and display the socket.id. Then ```socket.data.socket = socket;``` is assigned for said socket. Everything works for the first connection but on the second connection, the process crashes. The crashing is simply cos for repro purposes, I did not add error handling. The error message is:
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
// 1st browser connection here
0|app  | QKlnOavk82-Xsld5AAAB connected
0|app  | 1 socket
// 2nd browser connection here
0|app  | TypeError: Converting circular structure to JSON
0|app  |     --> starting at object with constructor 'Namespace'
0|app  |     |     property 'server' -> object with constructor 'Server'
0|app  |     --- property 'sockets' closes the circle
0|app  |     at JSON.stringify (<anonymous>)
0|app  |     at RedisAdapter.onrequest (/redacted/node_modules/@socket.io/redis-adapter/dist/index.js:254:33)
0|app  |     at runMicrotasks (<anonymous>)
0|app  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
1|app  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
1|app  | Error: timeout reached while waiting for fetchSockets response
1|app  |     at Timeout._onTimeout (/redacted/node_modules/@socket.io/redis-adapter/dist/index.js:712:28)
1|app  |     at listOnTimeout (node:internal/timers:559:17)
1|app  |     at processTimers (node:internal/timers:502:7)
```

**To Reproduce**
Socket.IO server version: `4.5.1`

*Server*

```js
io.sockets.on('connection',async (socket) => {
    let sockets = await io.fetchSockets();
    console.log(socket.id+ " connected");
    console.log(sockets.length+ " socket");
    socket.data.socket = socket;
})
```

Socket.IO client version: grabbed from /socket.io/socket.io.js via
```<script> type="text/javascript" src="/socket.io/socket.io.js"></script>```

*Client*

```js
this.socket = io({
    transports: ["websocket"]
});
```

**Expected behavior**
If I comment out ```socket.data.socket = socket;```, everything works fine.
```
0|app  | -5NJZYVjuW4QdcpiAAAB connected
0|app  | 1 socket
1|app  | _q0CbG6mx6xmGQj1AAAB connected
1|app  | 2 socket
```

**Platform:**
 - Device: Chrome and firefox browsers
 - OS: Amazon Linux

**Additional context**
I am passing the socket into data object for use in other parts of the code where the socket is used for comms downstream.

**Comment by darrachequesne** [comment]
Hi! Yes, the `socket` object does indeed contain circular references and `socket.data.socket = socket;` will throw an exception.

Could you please explain your use case when you call `socket.data.socket = socket;`?

**Comment by lockphase** [comment]
I have a game object in socket.data. I'm trying to access my game object cross-process. If I call ```fetchSockets``` with ```socket.data = game``` in plain form, it works fine. However, my game object contains reference to corresponding socket and is used for downstream comms. Calling ```fetchSockets``` on process 0 to access ```game``` object in process 1 fails.
```
socket.data = game;
game.socket = socket;
```

**Comment by tientp-floware** [comment]
Hi @lockphase your mean want to use socket objects in gross instances?
Example: 
Instance 1:  
`socket.data.socket = socket;` // socket 1
Instance 2: 
`console.log(socket.data.socket)` // you expected it's should be socket 1

You wanna like that?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
