### ISSUE TITLE
Multiple handlers for one event

### ISSUE THREAD

**Issue by AnvarAka1** [socketio/socket.io#4505]
### Discussed in https://github.com/socketio/socket.io/discussions/4504

<div type='discussions-op-text'>

<sup>Originally posted by **AnvarAka1** October 26, 2022</sup>
Hello.
I have used socket.io and it worked fine on the client side, until I stuck with one "bug", I guess. 
Following example is very simplified, but the idea is the same.

In one component I use:

```
socket.on('some_event', () => {
  console.log('first event')
})
```

In another component I use:

```
socket.on('some_event', () => {
  console.log('second event')
})
```

So, I do not get any of that event, but there is also socket.any((event) => console.log(event)) and it gives me proper event name.

Interestingly enough, there is also new connection established after event is registered, but with the same socketId.
That I know because of:
```
socket.on('connect', () => {
  console.log('connected')
})
```
I do not know what is the problem here. Maybe, there is not way in socket.io to use multiple handlers for one event. I didn't find any examples on that topic.
</div>

**Comment by jromerooo2** [comment]
what  Frontend framework are you using?
If it is something like Vue, have you tried to use a mixin?

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socket.io/how-to/use-with-vue
