### ISSUE TITLE
WebpackLicensePlugin: Could not find license info for socket.io-client@4.5.3

### ISSUE THREAD

**Issue by fbeqirllari** [socketio/socket.io#4526]
const WebpackLicensePlugin = require('webpack-license-plugin');
WebpackLicensePlugin: Could not find license info for socket.io-client@4.4.0

Socket.IO client version: `4.5.3`

**Comment by darrachequesne** [comment]
Hi! I wasn't able to reproduce, the license is there: https://www.npmjs.com/package/socket.io-client/v/4.4.0?activeTab=explore

Does it work with a more recent version?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
