### ISSUE TITLE
engine.io-6.2.0 vulnerability

### ISSUE THREAD

**Issue by brampurnot** [socketio/socket.io#4531]
Hello,

we are using socket.io version 4.5.3. We are regularly scanning our source code using mend and today a vulnerability was discovered in the engine.io package: 
A specially crafted HTTP request can trigger an uncaught exception on the Engine.IO server, thus killing the Node.js process. This impacts all the users of the engine.io package, including those who uses depending packages like socket.io. There is no known workaround except upgrading to a safe version. There are patches for this issue released in versions 3.6.1 and 6.2.1.

Bram

**Comment by darrachequesne** [comment]
Here we go! https://github.com/socketio/socket.io/releases/tag/4.5.4
