### ISSUE TITLE
`socket.io` `Socket` class lacks covariance on generic `ListenEvents` and `EmitEvents` types

### ISSUE THREAD

**Issue by jsamr** [socketio/socket.io#4541]
**Describe the bug**

`socket.io` and `socket.io-client` `Socket` classes are not covariant on either `ListenEvents` or  `EmitEvents`. Its typings are too lax, causing TS to allow variable substitutions that should be forbidden. This bug _does not_ happen for `socket.io-client` `Socket` instance.

**To Reproduce**

It's a type-only bug. Easy to reproduce

### With socket.io, expectation fails

_This is a reproduction for `EmitEvents`, it's trivial to reproduce it for `ListenEvents`_

Socket.IO version: `4.5.4`

```ts
import { Socket as ServerSocket } from "socket.io";

type EmptyRecord = Record<never, never>;
type Foo = { foo: string };
type Bar = { bar: string };
type FooEvents = {
  event: (arg: Foo) => void;
};
type BarEvents = {
  event: (arg: Bar) => void;
};

declare const foo: FooEvents;

// @ts-expect-error - BarEvents is not a base type for FooEvents
const fooBis: FooEvents = foo satisfies BarEvents;

// EXPECTATION FAILS WITH socket.io

type ServerSocketEmitFoo = ServerSocket<EmptyRecord, FooEvents, EmptyRecord, never>;
type ServerSocketEmitBar = ServerSocket<EmptyRecord, BarEvents, EmptyRecord, never>;

declare const socketFoo: ServerSocket<EmptyRecord, FooEvents, EmptyRecord, never>;

// @ts-expect-error - ServerSocketEmitBar should not be a base type for ServerSocketEmitFoo
const socketFooBis: ServerSocketEmitFoo = socketFoo satisfies ServerSocketEmitBar
```

[See reproduction in TypeScript playground](https://www.typescriptlang.org/play?ts=4.9.3#code/PTAEAEGcBcCcEsDG0Bco4FcCmBYAUPALYAOA9rNKAN6gDKpiA1lpQIaR1awBuX9TLUAF9QAM1ilCoAESQGzaADp4paQG58+aAE9iWUAFESOgEpZE5ACagAvKDMXYlgDwA7LL1gAaUO88A+DTwdPVAAMVJSW2oxSLQYBFcAc2EgkP0AIVZYaJoAI2z4uHhk1K1dfQjSA15XaA47KnxQUA8sOrQACmyktCqASlt-UG5SeEsgoTSK0CzYGvb63ObW2tRQbthe2ezBm2HR8cmg-EtzABts-QtXGFjSPsiFusgTvBAIeoBaLAAPPWQP1gEhyXx28zWHHgHFcpDYoAKkH06ViOSqz3q+Bud1EkQy0Me1Uh0VxUUgrGg0NE8CwHDmGNemneYAMAA0AAoGADCABUAII8gCSAHkAHLhPmCgAytFAAHVBTyABKgOQCJQqJko2hcTz8BRGeDQKrRHU8PjyFjOIzEUzmKw+dGQnw2u2OSw+PxcQLlUJmvWW6CG6BzU26i3q63GbQOB3ghku6OxpyetqwH14U4XK6gbGUNUKKpof0RhRR20x+0p8JPZ2GJNVj2+NMZ-AfcDfP4A6BAkGgMEl2D6ljB0OQAAWpAw52ssMoeX0rAR7GRM1xOUHw6DhCNVSxpFu+cDVXxkGL4aHgeDJrsBZYJvJlMg1NpnHNl-Vo+yQA).

### With socket.io-client, expectation ~succeeds~ fails

Socket.IO client version: `4.5.4`

This code compiles fine:

```ts
import { Socket as ClientSocket } from "socket.io-client";

type EmptyRecord = Record<never, never>;
type Foo = { foo: string };
type Bar = { bar: string };
type FooEvents = {
  event: (arg: Foo) => void;
};
type BarEvents = {
  event: (arg: Bar) => void;
};

declare const foo: FooEvents;

// @ts-expect-error - BarEvents is not a base type for FooEvents 
const fooBis: FooEvents = foo satisfies BarEvents;

// EXPECTATION SUCCEEDS WITH socket.io-client

type ClientSocketEmitFoo = ClientSocket<EmptyRecord, FooEvents>;
type ClientSocketEmitBar = ClientSocket<EmptyRecord, BarEvents>;

declare const clientSocketFoo: ClientSocket<EmptyRecord, FooEvents>;

// @ts-expect-error - ClientSocketEmitBar is not a base type for ClientSocketEmitFoo
const clientSocketFooBis: ClientSocketEmitFoo = socketFoo satisfies ClientSocketEmitBar
```

[See reproduction in TypeScript playground](https://www.typescriptlang.org/play?ts=4.9.3#code/PTAEAEGcBcCcEsDG0Bco4FcCmBYAUPALYAOA9rNKAN6gDKpiA1lpQIaSgDCANvFgHbR6TFqAC+oAGaxShUACJIDZtAB08UgFpEvAdHkBufPmgBPYllABREmYBKWROQAmoALygHT2M4A8-LAA3LFgAGlAA4NgAPiM8MwtQADFSUndqKVS0GAR+AHNxOITLACFWWHSaACNy7Lh4fMKTc0sU0itgwQ4PKnxQUCC9NAAKcry0NoBKd2jQQNJ4ZzixIpbQMtgOvW7qPoHO1FBR2HH18um3WfnF5bj8Z0ducssnfhhM0gnUra67vBAINBIJosAAPCzIEGwGQVTRnTYHDjwDj8UhsUA1SCWYqZCptH5A0D4V7vSSpErIr7tRHpMlpSCsaDIyR8DgbAmQP4AqwADQAClZOAAVACCQoAkgB5AByyRF4oAMrRQAB1cVCgASoCUIjUGm0ukExniax4fEEwhUNng0Da6TNektLF8NmI9kcLnC+MRsWaiQdFuULGt0A29sNQiD0BdtlMXk98I5vrw90ez1AJMoOpUbTQAcjupjbrjHp8Xu+Pq5YHAQJB4Mc0ChMNAcPzTugIbDyIiaNArAx7GxazJFTbUZDbWJpDelB05oLOfJlK4EfbE9S6WzLDtDKZkBZWA4Y91nfKQA).

**Expected behavior**

`socket.io` and `socket.io-client` `Socket` classes should be [covariant](https://dmitripavlutin.com/typescript-covariance-contravariance/) on `EmitListeners`. 

**Additional context**

I suggest implementing typings tests with [`expect-type` library](https://github.com/mmkal/expect-type).

ERRATA: Initially, I concluded that the issue only existed on `socket.io` because of a typo in the client example. Props to @darrachequesne for pointing out my mistake.

**Comment by darrachequesne** [comment]
Hi! Thanks for the detailed report :+1: 

Would you have the time to open a pull request with all necessary changes? Thanks!

**Comment by jsamr** [comment]
@darrachequesne Happy to give it a try when I find time!

**Comment by darrachequesne** [comment]
@jsamr in your client example, I think there is a typo, it should be `clientSocketFoo satisfies ClientSocketEmitBar` instead of `socketFoo satisfies ClientSocketEmitBar`.

So it seems both the client and the server show the same behavior.

**Comment by jsamr** [comment]
@darrachequesne Appreciate the feedback; I corrected the original post and updated the repro link.

**Comment by darrachequesne** [comment]
That should be fixed in latest version, please reopen if needed.
