### ISSUE TITLE
Error occurred when use uWebSocket.

### ISSUE THREAD

**Issue by ChoSeoHwan** [socketio/socket.io#4542]
**Describe the bug**

Error occurred when use uWebSocket.

It runs successfully, but when trying to establish a connection I get the error below.

```
TypeError: websocket.subscribe is not a function
    at subscribe (C:\Projects\ext-service\.yarn\__virtual__\socket.io-virtual-75b1662c1f\0\cache\socket.io-npm-4.5.4-888fc15f6d-b5456d361b.zip\node_modules\socket.io\dist\uws.js:87:19)
    at Adapter.socket_io_adapter_1.Adapter.addAll (C:\Projects\ext-service\.yarn\__virtual__\socket.io-virtual-75b1662c1f\0\cache\socket.io-npm-4.5.4-888fc15f6d-b5456d361b.zip\node_modules\socket.io\dist\uws.js:22:13)
    at Socket.join (C:\Projects\ext-service\.yarn\__virtual__\socket.io-virtual-75b1662c1f\0\cache\socket.io-npm-4.5.4-888fc15f6d-b5456d361b.zip\node_modules\socket.io\dist\socket.js:298:29)
    at Socket._onconnect (C:\Projects\ext-service\.yarn\__virtual__\socket.io-virtual-75b1662c1f\0\cache\socket.io-npm-4.5.4-888fc15f6d-b5456d361b.zip\node_modules\socket.io\dist\socket.js:338:14)
    at C:\Projects\ext-service\.yarn\__virtual__\socket.io-virtual-75b1662c1f\0\cache\socket.io-npm-4.5.4-888fc15f6d-b5456d361b.zip\node_modules\socket.io\dist\namespace.js:229:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**To Reproduce**

*Server*

```typescript

import { Server } from "socket.io";
import { App } from "uWebSockets.js";

(async () => {
    const io = new Server(80);
    io.attachApp(App());

    io.on('connection', (socket) => {
        console.log('connection');
    });
})();
```

Socket.IO server version: `^4.5.4`
uWebsocket.js version : `uNetworking/uWebSockets.js#v20.15.0`

**Expected behavior**

Should work normally with uWebsocket.

**Platform:**
 - OS: windows 10

**Additional context**

**Comment by darrachequesne** [comment]
I wasn't able to reproduce. Does it work with an older version of uWebsocket?

@frederic117 which OS are you using? Windows 10 too?

**Comment by frederic117** [comment]
i just try with the last version uNetworking/uWebSockets.js#v20.15.0
i'm on windows11
thanks for your quick reply :)

**Comment by gabrielfullview** [comment]
Same error here on a MacBook Pro with M1 Pro processor.

socket.io `^4.5.4`
uWebsocket.js `uNetworking/uWebSockets.js#v20.15.0`

**Comment by gabrielfullview** [comment]
Fixed this problem on my side.

Since I already had an app running socket.io with a HTTP server, I was using this app to migrate to µWebSockets. There were two problems:
1. I was still passing the HTTP server to the socket.io server constructor and the HTTP server was still listening on the main port – that's why the socket had no `subscribe` method.
2. I forgot to actually trigger the listen on the µWebSockets app. 🤦🏼‍♂️ 

Hope it helps. ✨

**Comment by gabrielgrijincu** [comment]
Same error here on a MacBook Pro with M1 Pro processor.

socket.io ^4.5.4
uWebsocket.js uNetworking/uWebSockets.js#v20.15.0

**Comment by gabrielgrijincu** [comment]
Fixed this problem on my side.

Since I already had an app running socket.io with a HTTP server, I was using this app to migrate to µWebSockets. There were two problems:
1. I was still passing the HTTP server to the socket.io server constructor and the HTTP server was still listening on the main port – that's why the socket had no subscribe method.
2. I forgot to actually trigger the listen on the µWebSockets app. 🤦🏼‍♂️

Hope it helps. ✨

**Comment by darrachequesne** [comment]
For future readers: the code above was invalid, it's the uWebSocket server that must listen to incoming connections:

```js
const io = new Server();
const app = App();

io.attachApp(app);
app.listen(80);
```

Reference: https://socket.io/docs/v4/server-initialization/#with-uwebsocketsjs

Please reopen if needed.

**Comment by daveteu** [comment]
> For future readers: the code above was invalid, it's the uWebSocket server that must listen to incoming connections:
> 
> ```js
> const io = new Server();
> const app = App();
> 
> io.attachApp(app);
> app.listen(80);
> ```
> 
> Reference: https://socket.io/docs/v4/server-initialization/#with-uwebsocketsjs
> 
> Please reopen if needed.

I followed the instructions as in your link as well as https://socket.io/docs/v4/server-installation/#usage-with-uwebsockets but when it's not working. 

When using the folllowing uwebsocket version
```
npm install uWebSockets.js@uNetworking/uWebSockets.js#v20.4.0
```
The error return is 

> [1] Error: This version of µWS is not compatible with your Node.js build:
> [1] 
> [1] Error: Cannot find module './uws_darwin_x64_115.node'


If I were to use the latest version of uwebsocket 20.32.0 the suggested codes does not work.

For example in the following line, Token is always `false` and the server is not listening.

```
const app = App();

const io = new Server({
  cors: {
    origin: 'http://localhost:3000',
    methods: ['GET', 'POST'],
  },
});

io.attachApp(app);

app.listen(port, (token: boolean) => {
  console.log('Token: ', token);
  console.log(`Listening on http://${host}:${port}`);
});

```

**Comment by xwiz** [comment]
> Fixed this problem on my side.
> 
> Since I already had an app running socket.io with a HTTP server, I was using this app to migrate to µWebSockets. There were two problems:
> 
> 1. I was still passing the HTTP server to the socket.io server constructor and the HTTP server was still listening on the main port – that's why the socket had no subscribe method.
> 2. I forgot to actually trigger the listen on the µWebSockets app. 🤦🏼‍♂️
> 
> Hope it helps. ✨

So you separated the http server or you were able to use uws as the http server?
