### ISSUE TITLE
pages apart from index.html dont connect to socket .io

### ISSUE THREAD

**Issue by acnologia000** [socketio/socket.io#4545]
### Discussed in https://github.com/socketio/socket.io/discussions/4544

<div type='discussions-op-text'>

<sup>Originally posted by **acnologia000** December  6, 2022</sup>
i was mixing and matching few example in docs
when i tried accessing socket.io through pages other then index.html 
it just logs errors in console 

WebSocket connection to 'ws://localhost:4000/socket.io/?EIO=4&transport=websocket&sid=Xr6J7yHGyTYv75bzAAA6' failed: WebSocket is closed before the connection is established

sources that i am working with are at 
https://github.com/acnologia000/sockchat</div>

**Comment by darrachequesne** [comment]
Let's continue the discussion here: https://github.com/socketio/socket.io/discussions/4544
