### ISSUE TITLE
[Bug] user can still emit to room even if server kick user from room

### ISSUE THREAD

**Issue by elmcapp** [socketio/socket.io#4550]
If I create a room and the server remote user from the room using the socket id the user can still emit message to the room 

````
io.in(socketId).socketsLeave(roomId);
````

After running this code I notice that the user can still emit to the room

**Comment by darrachequesne** [comment]
Hi! There is no constraint about who can emit in a particular room. Any constraint should be applied in your own application, not at the Socket.IO level.

**Comment by elmcapp** [comment]
Can you explain what rooms are for. I figured that being in a room a user that has not joined the room would not be able to emit to it. 

Currently If I have user A in room named "Welcome Room" if user B emits a message to that room without using socket.join("Welcome Room") the message that user B emit will not be received. This Is what I am expecting and that part works correctly. Once user B joins the room current I can get all of the emitted messages from user B.

My  problem is that once I run the server side function to make user B leave the room ```io.in(socketId).socketsLeave(roomId)``` they can still emit to the room "Welcome Room". 
The only way to stop them from emitting is if I disconnect them from the socket using ``` io.in(socketId).disconnectSockets(true)```

User B is not the user calling ```io.in(socketId).socketsLeave(roomId)```. I have an admin client that calls that function using the socket id of user B

**Comment by darrachequesne** [comment]
Basically, rooms can be seen as subscription channels: the client receive the packet if it has subscribed to the given channel.

**Comment by elmcapp** [comment]
So is there a way for the server to unsubscribe a client? Let's say that the server will unsubscribe a client under a created rule, If the client break the rule then the server can kick them from that room. I figure we could kick that client by using ```io.in(socketId).socketsLeave("roomName")```  I believe I understand what you are saying but again if I use ```io.in(socketId).socketsLeave(roomId)``` It does not make that target client leave the room they can still send messages to the room. It's as if they are still joined. I am able to make the client if it calls the function itself but if the server calls this it's never kicked from the room. Basically its as if I have no way to kick a client from the room unless the server disconnects its socket
