### ISSUE TITLE
Is there any update about trailing slash after path for socket.io-client 4.5.4 ?

### ISSUE THREAD

**Issue by Chameza25964** [socketio/socket.io#4554]
My team face the problem about trailing slash is placed after the base path for socket server. and they could not use query parameter for the socket server. Will there be any update for an option to remove trailing slash socket.io-client ?

**Comment by darrachequesne** [comment]
Hi! This will be fixed in the next release: https://github.com/socketio/engine.io-client/commit/21a6e1219add92157c5442537d24fbe1129a50f5

**Comment by Chameza25964** [comment]
Thank you so much! I'll tell my team about this issue and wait for the next release.
