### ISSUE TITLE
Expose DisconnectReason as part of public API

### ISSUE THREAD

**Issue by nathanjcochran** [socketio/socket.io#4556]
**Is your feature request related to a problem? Please describe.**

When you define a listener function for the socket [disconnect event](https://socket.io/docs/v4/server-api/#event-disconnect) in-line, TypeScript correctly infers the type of the `reason` argument to be [DisconnectReason](https://github.com/socketio/socket.io/blob/3b7ced7af7e0a2a66392577f94af1ee5ed190ab1/lib/socket.ts#L28-L40):

```typescript
socket.on('disconnect', (reason) => {
  // Type of  'reason' is 'DisconnectReason'
  console.log(`reason: ${reason}`);
});
```

However, I want to create a listener function for the `socket.on('disconnect')` event ahead of time (so that I can later call [removeListener](https://socket.io/docs/v4/server-api/#socketremovelistenereventname-listener) to remove it). But when I do that, the compiler cannot infer that the type of `reason` is `DisconnectReason`:

```typescript
const listener = (reason) => {
  // Type of 'reason' is 'any'
  console.log(`reason: ${reason}`);
};
socket.on('disconnect', listener);

// Later...
socket.removeListener('disconnect', listener);
```

I can import `DisconnectReason` from `socket.io/dist/socket` and create my listener with `reason: DisconnectReason`, but it would be ideal if `DisconnectReason` was exposed as part of the public API, so that I could import it from `socket.io` directly.

**Describe the solution you'd like**

I would like to be able to import `DisconnectReason` from `socket.io` directly, instead of from `socket.io/dist/socket`, like so:

```typescript
import { DisconnectReason } from 'socket.io';
```

**Describe alternatives you've considered**

I considered trying to determine the type of the listener function via some clever TypeScript, like so:

```typescript
const listener: Parameters<typeof socket.on<'disconnect'>>[1] = (reason) => {
  // Type of 'reason' is 'DisconnectReason'
  console.log(`reason: ${reason}`);
};
```

That _kind of_ worked, but I was running into eslint/prettier errors about the syntax, and I don't actually think it's more readable/clear than just using `DisconnectReason` directly:

```typescript
const listener = (reason: DisconnectReason) => {
  // Type of 'reason' is 'DisconnectReason'
  console.log(`reason: ${reason}`);
};
```

Thanks!

**Comment by apudiu** [comment]
Please also expose `DisconnectDescription` in the same way. [Here](https://github.com/socketio/socket.io/discussions/5221) I've started a discussion on this.
