### ISSUE TITLE
Certbot SSL working on application but socket not connecting

### ISSUE THREAD

**Issue by gauravsunstone** [socketio/socket.io#4563]
I am using a node express application which is already running on https using certbot certificate on nginx server
When i am trying to implement socket connection in the same application i have to pass a certificate in it otherwise it won't work

Here 2 questions coming to my mind

1. Why i need a certificate to pass while starting up the application as i have already done https using certbot and nginx
2. If really needed to start via ssl then i am using a self signed certificate which is also not working

```
const options = {
  key: fs.readFileSync(path.join(__dirname, "../cert/key.pem")),
  cert: fs.readFileSync(path.join(__dirname, "../cert/cert.pem")),
  rejectUnauthorized: false
}
```

This is the configuration i am using to create a server with this line

```
const app = express()
const server = https.createServer(options, app)
io = new Server<ServerToClientEvents, SocketData, ClientToServerEvents, InterServerEvents>(server,  {
        pingInterval: 2000,
})
```

both the things are not working as of now, is there anything else we need to do for connecting sockets in the same nodejs application which is already on https

**Comment by darrachequesne** [comment]
Hi! Hmm, no, it should be sufficient. How are you initializing the client?

**Comment by gauravsunstone** [comment]
My client is a angular application for which i am using `socket.io-client` npm package

`import {io} from 'socket.io-client';`

and below is the code i am using to establish socket connection

```
    this.socketUrl = 'https://domain.com:3004';
    this.socket = io(this.socketUrl, {transports: ['websocket'], query: this.apiHeader});
    this.socket.on('connect', function () {
      console.log('connected!');
    });
    this.socket.on('disconnect', function (reason) {
      console.log('disconnected!', reason);
    });

```

**Comment by darrachequesne** [comment]
I think you need to include the certificate on the client side:

```js
this.socket = io(this.socketUrl, {
  transports: ['websocket'],
  query: this.apiHeader,
  ca: readFileSync("../cert/cert.pem")
});
```

Reference: https://socket.io/docs/v4/client-options/#nodejs-specific-options

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by gauravsunstone** [comment]
I have tried your way and many more but the moment i use self signed certificate i am getting connect_error "websocket error"

**Comment by darrachequesne** [comment]
@gauravsunstone sorry to hear that. Could you please check the example [there](https://github.com/socketio/socket.io-fiddle/tree/ssl-example)?

**Comment by gauravsunstone** [comment]
I did some research on it as i can see the sample application is using node both sides on client as well as on server
In my case i am using angular on client side in which readfilesync is not an options
Can you suggest something to connect with self signed certificate from angular application

Also, please open the issue i am unable to do that

**Comment by liangyuanpeng** [comment]
I'm also need to running the client with TLS and it's not working for me, need someone can provide the help,Thanks!

here is my React code:

```javascript
    Promise.all([
      fetch("https://smartoilets.net/files/user1.crt"),
      fetch("https://smartoilets.net/files/user1.key"),
      fetch("https://smartoilets.net/files/ca.crt"),
    ]).then(async (res) => {
      const crt = await res[0].text();
      const key = await res[1].text();
      const ca = await res[2].text();

      console.log(crt)
      const deviceId2 = "asd"
      const transports: string[] = ["websocket"];

      io(configuration.socketio, {
        query: { deviceId2 },
        cert: crt,
        key: key,
        ca: ca,
        transports: transports
      });
```

There are my self sign cert files, always can not get the cert with Request of `/socket.io/?deviceId2=asd&EIO=3&transport=websocket`


here is the log:

```shell
"GET /socket.io/?deviceId2=asd&EIO=3&transport=websocket HTTP/1.1" 400 639 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "cert:" "-"
```

@darrachequesne @gauravsunstone 
Remind me if i missed something,Thanks!
