### ISSUE TITLE
acknowledgements are empty if not using timeout

### ISSUE THREAD

**Issue by elmcremotebridge** [socketio/socket.io#4577]
I am using socket.io v4.5.4. I am trying to use acknowledgements but I am getting an empty array when I do not use the timeout

// Results are blank
````
io.to("room123").emit("hello", "world", (err, responses) => {
  console.log(responses)
});

````

If I apply the time out I get the results as expected
````
io.to("room123").timeout(5000).emit("hello", "world", (err, responses) => {
   console.log(responses)
});
````

On the client end 
````
socket.on( 'hello', data, callback) => {
        
        callback({status: 2000});
 })
````

**Comment by darrachequesne** [comment]
Yes, you are right, the `timeout()` is mandatory. I guess we could add an option to set a default timeout, or throw if the timeout is not provided, what do you think?

Reference: https://socket.io/docs/v4/broadcasting-events/#with-acknowledgements

**Comment by elmcremotebridge** [comment]
Yes. I think your recommendations would be great. I also think a better ideal would be to allow users the ability to use ``` await``` ``` async``` this way we can wait for the results and maybe throw if results are not received in "x" amount of seconds

**Comment by elmcremotebridge** [comment]
@darrachequesne Please add an option to use ```await```.  have an option where if callback is null before the timeout reach it will simply just wait on the first result

**Comment by LeoDog896** [comment]
> or throw if the timeout is not provided, what do you think?
Probably restrict this in TypeScript as well to give compile errors.

**Comment by elmcremotebridge** [comment]
@darrachequesne @LeoDog896  I think the best method would be as follows


1. have a method where the server will await for the first response it receive. we can use await so that it waits as long as it takes for a response but will timeout after x seconds. 
This way we don't have to wait 5 seconds for the event to be triggered and in the event we are only emitting to 1 client we can ensure we get a response. 

2. have a method with a default time out this way we can wait for all response

**Comment by darrachequesne** [comment]
Update: the `emitWithAck()` method was added in version 4.6.0:

```js
try {
  const responses = await io.timeout(10000).emitWithAck("some-event");
  console.log(responses); // one response per client
} catch (e) {
  // some clients did not acknowledge the event in the given delay
}
```

Reference:
- server: https://socket.io/docs/v4/server-api/#serveremitwithackeventname-args
- client: https://socket.io/docs/v4/client-api/#socketemitwithackeventname-args
