### ISSUE TITLE
socketio.exceptions.BadNamespaceError / is not a connected namespace

### ISSUE THREAD

**Issue by nouser000** [socketio/socket.io#4579]
When i stop sending message for a few minutes it returns me:
**socketio.exceptions.BadNamespaceError / is not a connected namespace**

Socket.IO server version: `4.5.3`

*Server js*

```js
const fs = require('fs');
const { createServer } = require("https");
const { Server } = require("socket.io");

const httpServer = createServer({
    key: fs.readFileSync("/priv.key"),
    cert: fs.readFileSync("/cert.crt")
});


const options = {
   cors: {
        origin: "*"
    }
};

const io = new Server(httpServer, options);
io.on("connection", function (socket) {
    socket.on("debug", function (data) {
        console.log("RECEIVE: "+data.msg);
    });
});

 
httpServer.listen(3001, function () {
    console.log("StARTED ");
});

```

Socket.IO client version: `5.7.2`

*Client python*

```python
sio = socketio.Client(logger=False,ssl_verify=False,reconnection=True)
sio.connect('https://domain.url:3001' ,transports="polling")
sio.emit('debug', {'room': 'hi','msg':'Hi mate'}) #works
sio.sleep(5)
sio.emit('debug', {'room': 'hi','msg':'Hi again'}) #works again

... other task around 5 minutes ...

sio.emit('debug', {'room': 'hi','msg':'Tasks finish'}) #error
```

**Expected behavior**
Send message at the end of tasks after 5-10 minutes

**Platform:**
 - OS: [Ubuntu 22.04.1 LTS]
 
**Additional context**
I read [#1485](https://github.com/miguelgrinberg/Flask-SocketIO/issues/1485) but i got no results

**Comment by nouser000** [comment]
I did tests that reduce the execution time of other tasks and they still give me the same error

`
File "/usr/local/lib/python3.10/dist-packages/socketio/client.py", line 393, in emit
    raise exceptions.BadNamespaceError(
socketio.exceptions.BadNamespaceError: / is not a connected namespace.
`

**Comment by darrachequesne** [comment]
Could you please open an issue in the [Python repository](https://github.com/miguelgrinberg/python-socketio)? Thanks!
