### ISSUE TITLE
add php version

### ISSUE THREAD

**Issue by zsnakeee** [socketio/socket.io#4582]
its will better if provide **php package version**, i hope you do it

**Comment by darrachequesne** [comment]
PHP is not really meant for handling WebSocket connections.

You can check the server implementations in other languages:

- JavaScript (Deno): https://github.com/socketio/socket.io-deno
- Java: https://github.com/mrniko/netty-socketio
- Java: https://github.com/trinopoty/socket.io-server-java
- Python: https://github.com/miguelgrinberg/python-socketio
- Golang: https://github.com/googollee/go-socket.io

See also: https://stackoverflow.com/questions/14512182/how-to-create-websockets-server-in-php
