### ISSUE TITLE
Event listeners are taking a long time to fire. 

### ISSUE THREAD

**Issue by elmcapp** [socketio/socket.io#4597]
I am noticing a up to 5 second lag or delay transmitting data from one client and that data being received to the other clients. 
I am using the lates version of socket.io "socket.io-client": "^4.5.4". Not sure if this is a bug or not. Please see below my experience.

sequence 1
We have 2 clients 
1. Client 1 emits to the server (on button press)
2. server broadcast to room and sends data to client 2
3. Client 2 does not receive this data for up to 5 seconds (the listener for client 2 may take up to 5 seconds to fire)

sequence 2
1. In client 1 I use setInterval to send an emit every 5 seconds to the server and to client 2.
While continuing to do number 1:
2. Client 1 emits to the server (on button press)
3. server broadcast to room and sends data to client 2. 
4. Client 2 received the data almost instantly. (the listeners for client 2 fires almost instantly )

It's as if I have to continue to send data from the clients to the server every 5 minutes. Without doing so when a new event is triggered there will be a delay on all event listeners.

**Comment by darrachequesne** [comment]
Hi! That sounds weird indeed.

Are you able to reproduce reliably? Which platform/OS? Does that happen on mobile?

**Comment by elmcremotebridge** [comment]
Yes I am able to reproduce reliably. I tried on Railway.app as well as on my localhost. I have only test on iOS.

**Comment by elmcremotebridge** [comment]
This week I will post up some time logs. it will show the time a button was press on client a and the time the service received it as well as the time client b received..  I also post logs in the same way but with traffic being sent ever x seconds so that you can see the delay if this would help

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
