### ISSUE TITLE
Count of connected clients/sockets

### ISSUE THREAD

**Issue by denisu** [socketio/socket.io#463]
Hi,

I am using `io.sockets.clients().length` to get the count of all currently connected clients, but after some time this number is way to high, many disconnected clients are still present in this array.

Below an image of `io.sockets.clients().length`, plotted every 5 minutes for 24 hours. Once the count reached over ~2k, i restarted the server, about 200 to 300 clients reconnected, which is the correct count.

![Connected Clients](http://static.allmystery.de/upics/rQNGeo_allmystery_node-day.png)

Is this the wrong way to get the count of all connected clients? I also tried to count the connects and disconnects manually, but after one day there were more disconnects than connects, the count was negative.

Related: https://github.com/LearnBoost/socket.io/issues/349

**Comment by GuyChabra** [comment]
+1
