### ISSUE TITLE
Docs: Typo in documentation to use with React hooks.

### ISSUE THREAD

**Issue by Swastikyadav** [socketio/socket.io#4637]
**Typo in documentation to use with React hooks.**
[How to use with React hooks](https://socket.io/how-to/use-with-react-hooks)

The above documentation code snippet have a typo.

In the snippet sendPing function socket emits to "ping", but in the useEffect it is listening to "pong" instead of "ping".

Attachment for reference:
![image](https://user-images.githubusercontent.com/44374494/220701388-7a1823a1-cffa-4ee5-8d71-d14411dba68d.png)

**Comment by darrachequesne** [comment]
@Swastikyadav hi, thanks for opening this.

I don't think this is a typo, the client sends `ping` events and receives `pong` events from the server. But maybe this example is not clear enough/could be improved? Do you have any suggestion?

**Comment by Swastikyadav** [comment]
@darrachequesne, Thanks for responding and clarification.

I think adding a small snippet of server side will make this example better and easier to understand.

Suggested server side code snippet:

```js
io.on("connection", (socket) => {
  console.log("A user connected");

  // Receives "ping" event from client
  socket.on("ping", () => {
    console.log("ping");

    // Sends "pong" event to client
    io.emit("pong", color);
  });
});
```

Thank You!

**Comment by darrachequesne** [comment]
Hi! We have updated the React guide: https://socket.io/how-to/use-with-react

I think this can be closed now, please reopen if needed.
