### ISSUE TITLE
Update data of RemoteSocket

### ISSUE THREAD

**Issue by NguyenVanCong1902** [socketio/socket.io#4641]
I have a chat server based on SocketIO as 3rd party ChatServer
I'm using socket v4.5.4 with @socket.io/redis-adapter@8.1.0 to implement multiple nodes

After authentication, I saved directly userData to **socket** like this:
socket.data.userData = 
{
    "nickName": "Nguyễn Văn Công",
    "customerID": "123456789",
    "avatar": "https://static.vecteezy.com/system/resources/thumbnails/009/734/564/small/default-avatar-profile-icon-of-social-media-user-vector.jpg",
    "secureString": "961b6dd3ede3cb8ecbaacbd68de040cd78eb2ed5889130cceb4c49268ea4d506"
}

![image](https://user-images.githubusercontent.com/87685455/221506089-a5a29ca4-5f39-4eb1-b8ec-d659ed0c9a86.png)

I can **io.fetchSockets()** to get all sockets (includes RemoteSockets). I tried to change data.userData by 
socket.data.userData = 
{
    "nickName": "Nguyễn Văn Công2 - NEW NAME",
    "customerID": "123456789",
    "avatar": "https://static.vecteezy.com/system/resources/thumbnails/009/734/564/small/default-avatar-profile-icon-of-social-media-user-vector.jpg",
    "secureString": "61be55a8e2f6b4e172338bddf184d6dbee29c98853e0a0485ecee7f27b9af0b4"
}

_**But RemoteSocket userData was not updated.**_

**Describe the solution you'd like**
Is there anyway to update param data in RemoteSocket
or
please let it can update data of RemoteSocket from any node

**Describe alternatives you've considered**
I could use Redis to store userData but everytime user send a message, i must open a http request to Redis server to get userData instead of **socket.data.userData**. It's a little uncomfortable and reduce performance.

Thanks in advance 🥰🥰

**Comment by darrachequesne** [comment]
Hi! For this use case, you will need to use the `serverSideEmit()` method:

```js
io.serverSideEmit("updateUserData", customerId, userData);
```

And on the receiving side:

```js
io.on("updateUserData", async (customerId, userData) => {
  // provided that `socket.join(customerId);` was called before
  // note that the "local" flag is used, to only fetch the sockets on this server
  const sockets = await io.local.in(customerId).fetchSockets();

  sockets.forEach(socket => {
    Object.keys(userData).forEach(key => {
      socket.data.userData[key] = userData[key];
    });
  });
});
```

Reference: https://socket.io/docs/v4/server-instance/#serversideemit

**Comment by NguyenVanCong1902** [comment]
> 

awesome!!!! great function. Tyvm 😘😘😘
