### ISSUE TITLE
Typings issue with `io.engine.use` 

### ISSUE THREAD

**Issue by fastndead** [socketio/socket.io#4644]
**Describe the bug**
In the [How to use with `express-session`](https://socket.io/how-to/use-with-express-session) part of the docs, there's an example for `4.6.0+` version of the library, that suggests to use express middleware with `io.engine.use`, but typings seem to be off. `io.engine.use` accepts `Middleware` type, but `express-session` middleware type is `RequestHandler`. Both are middleware handlers but the request types diverge. It leads to this issue:
<img width="902" alt="image" src="https://user-images.githubusercontent.com/33729448/221967886-623d6703-4643-4b34-b200-9c0d81fb721c.png">
 

**To Reproduce**
Socket.IO server version: `4.6.0`

*Server*

```ts
import session from "express-session";

const sessionMiddleware = session({
  secret: "changeit",
  resave: false,
  saveUninitialized: false
});

io.engine.use(sessionMiddleware);
```

**Expected behavior**
No TS errors. Types are compatible

**Platform:**
 - Device: MacBook
 - OS: MacOS

**Comment by darrachequesne** [comment]
For future readers:

This should be fixed by https://github.com/socketio/engine.io/commit/014195118535669af0ad3bde38a76601dafa4d81, included in `engine.io@6.4.2` (and in Socket.IO v4.6.x).
