### ISSUE TITLE
Private messaging to socket Id doesn't work 

### ISSUE THREAD

**Issue by brynbeaudry** [socketio/socket.io#4646]
**Describe the bug**
Private messaging to socket Id doesn't work as described in all documentation
"socket.io-client": "^4.6.1",

**To Reproduce**

Verify to that socket.id for the client and the server are the same for this particular connection
Send a private message
Notice that the private message doesn't reach the client 
Notice that a broadcast to everyone does in fact work

*Server*

```js
// Update client with nearby users, excluding the current user
        const nearbyUsers = await repos['user'].search().where('location').inRadius(
            circle => circle.origin({ longitude: data.location.lng, latitude: data.location.lat }).radius(300).feet)
            .and('socketId').not.eq(socket.id).return.all() // This is actually successful

        if (nearbyUsers.length) {
            socket.to(socket.id).emit('READ_NEARBY_USERS', nearbyUsers); // DOESN'T WORK, trying to send back to client
            socket.emit('READ_NEARBY_USERS', nearbyUsers); // WORKS FINE, but sends to everyone
        }
```

Socket.IO client version: `^4.6.1`

*Client*

```js
if (!this.socket?.connected) return;
      this.socket.on('READ_NEARBY_USERS', (data) =>{ // WORKS WHEN NOT SENDING TO PARTICULAR CLIENT
        console.log(this.socket!.id)
        console.log(data)
        this.nearbyUsersSubject.next(data);
      });
```

**Expected behavior**

There is an expectation that private messaging by default socket id room joining, when the socket.id displayed ion the server and client are the same, that private messaging to socket id will work. This is an expectation set by all of the documentation materials

**Platform:**
 - Device: Intel MacBook Pro
 - OS: MacOs 13.1 (22C65)
- "socket.io": "^4.6.1",
- ts-node : ts-node -v
v10.9.1
- node : which node
v16.19.0/bin/node

running as 'ts-node -r tsconfig-paths/register ./src/server.ts'

**Comment by brynbeaudry** [comment]
I think that the 'except rooms' set is also getting populated in emit(ev, ...args) {

**Comment by brynbeaudry** [comment]
Looking through o code, it seems you can't have a socket message itself with io.to(socket.id).emit()

**Comment by brynbeaudry** [comment]
So for context, I was firing another event back (READ_NEARBY_USERS(): object[]) to just the client that initiated a WRITE_USER_LOCATION(data): void event, inside of the function on the server that handles write user location.

Ihe 'except rooms' set is getting populated in emit(ev, ...args)
Looking through the code, 'except rooms' set is getting populated in emit(ev, ...args) with he socket id. This means that socket.io prevents the socket from messaging itself with io.to(socket.id).emit() by design. 

The proper solution to the case provided is to use a callback to directly send data back to the socket client after emiting from the client, instead of being able to expect another event. 

This should be stressed in the documentation that io.to(socket.id).emit() from the server doesn't work for the self client. Private message to self is not allowed by the library. Even joining the client to a room based on userId doesn't work because it gets associated with that socket.

**Comment by darrachequesne** [comment]
Hi! `socket.to().emit(...)` broadcast to everyone but the `socket` itself.

```js
// won't work (means: "send to <socket.id> room but ignore <socket.id> room")
socket.to(socket.id).emit('READ_NEARBY_USERS', nearbyUsers);

// send to the particular socket
socket.emit('READ_NEARBY_USERS', nearbyUsers);

// send to the particular socket
io.to(socket.id).emit('READ_NEARBY_USERS', nearbyUsers);
```

`socket.to("sample-room").emit(...)` is equivalent to `io.to([socket.id, "sample-room"]).emit(...)`

References:

- https://socket.io/docs/v4/broadcasting-events/#to-all-connected-clients-except-the-sender
- https://socket.io/docs/v4/emit-cheatsheet/

> Private message to self is NOT allowed by the library

What made you think that? I'd like to improve the documentation if it's not clear enough.

**Comment by Dass7** [comment]
[click here](https://www.mysourcebook.com/2023/04/private-messaging-to-socket-id-does-not-work-in-socket.io.html)-to read this post

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
