### ISSUE TITLE
When using Redis-Adpter, broadcasting a message to one person will notify all redis nodes, causing a waste of redis bandwidth

### ISSUE THREAD

**Issue by myYang2016** [socketio/socket.io#4647]
When using Redis-adapter ,broadcasting a message to one person will notify all Redis nodes, causing a waste of Redis bandwidth

Save the node where the receiver resides to redis, and get the node where the corresponding receiver resides when broadcasting, so that only one redis node can be notified.

**Comment by myYang2016** [comment]
> 
Or broadcast to a channel with only one or two people in it, but multiple redis nodes are notified

**Comment by myYang2016** [comment]
I used io.local to solve the problem myself

**Comment by myYang2016** [comment]
[
![Uploading socketEmitter.png…]()
](url)

**Comment by darrachequesne** [comment]
That's an interesting idea, thanks for opening this :+1: 

Actually it was implemented like that in previous releases: https://github.com/socketio/socket.io-redis-adapter/issues/102

**Comment by myYang2016** [comment]
> That's an interesting idea, thanks for opening this 👍
> 
> Actually it was implemented like that in previous releases: [socketio/socket.io-redis-adapter#102](https://github.com/socketio/socket.io-redis-adapter/issues/102)

Yes, previously you were worried that subscribing to channels would result in too many subscriptions to redis. My solution above only needs to subscribe to one process-related event per process and can solve the problem of too many subscriptions.

**Comment by myYang2016** [comment]
> > That's an interesting idea, thanks for opening this 👍
> > Actually it was implemented like that in previous releases: [socketio/socket.io-redis-adapter#102](https://github.com/socketio/socket.io-redis-adapter/issues/102)
> 
> Yes, previously you were worried that subscribing to channels would result in too many subscriptions to redis. My solution above only needs to subscribe to one process-related event per process and can solve the problem of too many subscriptions.
