### ISSUE TITLE
Client.disconnect() to force a client to disconnect

### ISSUE THREAD

**Issue by steadicat** [socketio/socket.io#47]
It would be great to have a disconnect() method on Client instances. This is useful to implement mechanisms such as IRC's kick/ban. Basically there needs to be a way to get rid of abusers.

**Comment by SiddharthArtoon** [comment]
try {
			IO.Options opts = new IO.Options();
			opts.forceNew = true;
			opts.timeout = -1;
			socket1 = IO.socket(c.ip, opts);
			socket1.on("res", getdataListener);
			socket1.connect();
		 			socket1.on(com.github.nkzawa.socketio.client.Socket.EVENT_CONNECT,
					new Emitter.Listener() {

						@Override
						public void call(Object... args) {

							Logger.print("CONNECTED...............");

							Message msg = new Message();
							msg.what = ResponseCodes.CreateQueueResp;
							Login.handler.sendMessage(msg);

							activity.runOnUiThread(new Runnable() {

								@Override
								public void run() {
									// TODO Auto-generated method stub
									
									startChecking();
									startIdleChecking();
									
								}
								
							});	
						}
						
					})
					.on(com.github.nkzawa.socketio.client.Socket.EVENT_RECONNECT,
							new Emitter.Listener() {

								@Override
								public void call(Object... arg0) {

									 
									System.out
											.println("............... EVENT_RECONNECT");

									// TODO Auto-generated method stub

								}
							})
					.on(com.github.nkzawa.socketio.client.Socket.EVENT_CONNECT_ERROR,
							new Emitter.Listener() {

								@Override
								public void call(Object... args) {

									System.out
											.println("............... EVENT_CONNECT_ERROR");

								}

							})
					.on(com.github.nkzawa.socketio.client.Socket.EVENT_CONNECT_TIMEOUT,
							new Emitter.Listener() {

								@Override
								public void call(Object... args) {

									System.out
											.println("............... EVENT_CONNECT_TIMEOUT");

								}

								// this is the emit from the server
							})

					.on(Socket.EVENT_ERROR, new Emitter.Listener() {

						@Override
						public void call(Object... args) {

							System.out
									.println("......................... EVENT_ERROR");

						}

						// this is the emit from the server

					})
					.on(com.github.nkzawa.socketio.client.Socket.EVENT_DISCONNECT,
							new Emitter.Listener() {

								@Override
								public void call(Object... args) {

									Logger.print(".............EVENT_DISCONNECT");

									
									if (!open) {

										//server_message = getResources().getString(R.string.It_seems_that);

										
										server_message="It seems that connection to server have been Lost.Please reconnect!"; 
										
										ServerError error = new ServerError(activity, server_message);

										
									}
									
								}

							});

		} catch (Exception e) {

			e.printStackTrace();

		}

**Comment by DurgaPrasadGavara** [comment]
My function app triggered repeatedly when device gets the message. Every time my function app socket connection opened.How to close the opened connection forcibly.
Here is the my logic:
'use strict';
var _test = require('socket.io-client');
var socket = _test.connect('http://XXXXXXXXXX.net/'); 
exports.handler = function (event,context) {
  var ResultMessage = JSON.stringify(event.message,null,2);
          if(!socket.connected)
		 {
        socket.emit('add user', '1542');
		 }
        socket.emit('new message',"[" + ResultMessage + "]");

  }; 
Thanks, 
In advance.

**Comment by thusinh1969** [comment]
11 years...passed :) This is till an issue, can not kick client out or simply tell them to disconnect !

Steve
