### ISSUE TITLE
Socket.io/pm2 version update

### ISSUE THREAD

**Issue by matvejs16** [socketio/socket.io#4702]
I can't make any PR/Issue in socket.io/pm2 so that's why I make it here.
Can you please update pm2 version socket.io/pm2 to 5.3.0 (Published 2 months ago)

Changelog 5.3.0
* fix: replace non-working condition that blocks flush from clearing the logs

* fix: ESM script loader

**Comment by darrachequesne** [comment]
Done: https://www.npmjs.com/package/@socket.io/pm2/v/5.3.0

Thanks for the heads-up :+1:
