### ISSUE TITLE
"socket.io": "4.6.1": this.sockets.set is not a function

### ISSUE THREAD

**Issue by hktalent** [socketio/socket.io#4705]
I don't know what the reason is, I only know that the lower version is normal, but after upgrading to the latest version, an error was reported

"socket.io": "4.6.1",
<img width="627" alt="image" src="https://user-images.githubusercontent.com/18223385/235764766-a897748f-1921-4b37-82a1-9ffce4b28b53.png">

```
/app/node_modules/socket.io/dist/namespace.js:259
        this.sockets.set(socket.id, socket);
                     ^
TypeError: this.sockets.set is not a function
    at Namespace._doConnect (/app/node_modules/socket.io/dist/namespace.js:259:22)
    at /app/node_modules/socket.io/dist/namespace.js:231:22
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

client code
```
s1 = s1.replace("https://","wss://")
signaling_socket = io(s1 + "/pChat");
```

**Comment by darrachequesne** [comment]
Hi! I was not able to reproduce the issue, could you please provide your server code that triggers this issue? You can fork the example here: https://github.com/socketio/socket.io-fiddle

Thanks!
