### ISSUE TITLE
The fetchSockets of redis-adapter received inaccurate data. redis-adapter is created multiple times

### ISSUE THREAD

**Issue by huanshiwushuang** [socketio/socket.io#4707]
**Describe the bug**
During my use of redis-adapter, the adapter is initialized twice

**To Reproduce**

Socket.IO server version: `4.6.1`

**first init**
1. Server init，call of('/')
![image](https://user-images.githubusercontent.com/18592659/236593595-3612619b-bfec-45d3-8033-c3ca1a8cd252.png)
2. new namespace
![image](https://user-images.githubusercontent.com/18592659/236593653-853bec95-a50f-4eb3-bb09-31c7bd2ebb20.png)
3. init
![image](https://user-images.githubusercontent.com/18592659/236593740-611906fd-4832-488d-ae6a-205b28ff1de4.png)

**second init**
1. io.adapter
![image](https://user-images.githubusercontent.com/18592659/236594026-43e58df5-fd8c-4961-b93a-8f6319ac6c38.png)

**description**
1. I suspect, that repeated creation of redis-adapters causes repeated subscriptions and publications of socket.io-request#/# and socket.io-response#/# channels, which causes errors with io.fetchSockets .
Because the Promise of fetchSockets depends on the number of subscribers. It is possible to receive more responses, resulting in incomplete data for Promise.resolve.
This is the problem I'm having while using socket.io and fetchSockets with the midwayjs framework.

![image](https://user-images.githubusercontent.com/18592659/236593933-5074a972-8ba8-4203-a012-e81d7d1d18cf.png)

**Platform:**
 - Device: Lenovo R720
 - OS: windows 18363.1556

**Comment by darrachequesne** [comment]
Hi! This could happen in the following case:

```js
import { Server } from 'socket.io';
import { createClient } from 'redis';
import { createAdapter } from '@socket.io/redis-adapter';

const pubClient = createClient();
const subClient = pubClient.duplicate();

await Promise.all([pubClient.connect(), subClient.connect()]);

const theRedisAdapter = createAdapter(pubClient, subClient);

const io = new Server({
  adapter: theRedisAdapter // 1st time
});

io.adapter(theRedisAdapter); // 2nd time
```

Could you please check?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
