### ISSUE TITLE
(node:2666) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 upgrade listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by tejHackerDEV** [socketio/socket.io#4708]
**Describe the bug**
We are using [namespaces](https://socket.io/docs/v4/namespaces/) concept in our production app, where our executive can connect upto 14 different namespaces at one go from one single application. Below is the screenshot of network tab that looks at the time of connection for single executive.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59303486/236641787-09281f1a-e6a7-46e0-82cc-4cea16f0f24d.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59303486/236641818-4ca8132b-3e1e-4156-8c7c-d9de12f8a032.png">

So when ever this happens i am getting an warning in the console saying `(node:2666) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 upgrade listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit`. I looked over stack-overflow about this & I found that we can set maxListeners to 0, which i tried but still the warning gets printed to the console.

```js
// Disable MaxListenersExceededWarning
server.setMaxListeners(0);
io.setMaxListeners(0);
io.sockets.setMaxListeners(0);
```

And i think due to this in our production server which is deployed on the AWS on a powerful machine sometimes hit the CPU utlilization 100% causing the server downtime & everytime we need to restart the server manually to make it work again.

Socket.IO server version: `^4.5.0`

**Comment by tejHackerDEV** [comment]
Below is the output i get by running the server locally with the `NODE_OPTIONS='--es-module-specifier-resolution=node --trace-warnings'`
```
(node:5869) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 upgrade listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:601:17)
    at Socket.addListener (node:events:619:10)
    at Namespace.<anonymous> (/Users/name/Desktop/node_chat_server/node_modules/@socket.io/admin-ui/dist/index.js:264:21)
    at Namespace.emit (node:events:539:35)
    at Namespace.emitReserved (/Users/name/Desktop/node_chat_server/node_modules/socket.io/dist/typed-events.js:56:22)
    at /Users/name/Desktop/node_chat_server/node_modules/socket.io/dist/namespace.js:141:26
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by darrachequesne** [comment]
Hi! I wasn't able to reproduce the issue: https://github.com/socketio/socket.io-fiddle/tree/issues/socket.io/4708

Could you please check that you are not registering the same event listener multiple times?

**Comment by Santosl2** [comment]
Did you manage to solve? I believe i can help you!

I had the same problem.. I noticed that my namespace was in wrong location. 

I had put it inside the socket.on('connection'), like in the example below:

```typescript
io.on('connection', (socket) => {
... EVENTS 

 io.of('/').adapter.on('join-room', (room, id) => {
    console.log(`socket ${id} has joined room ${room}`);
  });

  io.of('/').adapter.on('leave-room', (room, id) => {
    console.log(`socket ${id} has leave room ${room}`);
  });
})
```
note that i had put namespace inside io event 


But the correct was:

```typescript
io.on('connection', (socket) => {
 ... EVENTS 
})

io.of('/').adapter.on('join-room', (room, id) => {
    console.log(`socket ${id} has joined room ${room}`);
  });

  io.of('/').adapter.on('leave-room', (room, id) => {
    console.log(`socket ${id} has leave room ${room}`);
  });
```

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
