### ISSUE TITLE
Authorize/filter event data on a per-socket basis before sending

### ISSUE THREAD

**Issue by uncaught** [socketio/socket.io#4709]
**Is your feature request related to a problem? Please describe.**
This is the scenario:
- A webserver emits a websocket event including some sensitive and some non-sensitive data
- Not all connected sockets should see the sensitive data
- The socket data contains information about whether that socket is allowed to see the sensitive data or not
- The permissions allowing access to this data is too complex to use rooms for it

**Describe the solution you'd like**
- It would be perfect to be able to filter and modify events before they are sent to the client.
- For performance reason this should happen at the server node, which actually holds the socket, and not at the emitter
- This should be registered as some form of callback (hook/middleware/listener)
- Possibly I could even block the event entirely from being passed through

This is an example on how this could look in a middleware like fashion, hiding the salary in an event that informs clients about a new user:

```ts
import {omit} from 'lodash';
import {Socket} from 'socket.io';

type PacketData = [string, ...any]; //the thing you have in `packet.data` in broadcast-operator.ts#emit

type UserCreated = ['userCreated', {name: string; salary?: number; team: string}];

const isUserCreated = (data: PacketData): data is UserCreated => data[0] === 'userCreated';

function filterUserCreated(socket: Socket, data: UserCreated): UserCreated {
  if (socket.data.permissions[data[1].team].canViewSalary) {
    return data;
  }
  return [data[0], omit(data[1], 'salary')];
}

io.useEventFilter((socket: Socket, data: DeepReadonly<PacketData>, next: (data: PacketData) => void) => {
  if (isUserCreated(data)) {
    next(filterUserCreated(socket, data));
  } else {
    next(data);
  }
});
```

This is just a demonstration about how the permission is determined by the sent data. Our actual permission mapping is quite extensive, so having rooms for every constellation is not possible.

I have tried to get closer to the socket.io implementation with the `PacketData` in the example. From what I have understood in the source code, this hook would go right into the `apply` of the [socket.io-adapter/lib/index.ts#broadcast method](https://github.com/socketio/socket.io-adapter/blob/28f60b880ad04ff4b48ade0cd529f1970643604f/lib/index.ts#L172).

Obviously you had to re-encode the packet if the data changed and I'm not totally sure if the types are all correct here:

```ts
  public broadcast(packet: any, opts: BroadcastOptions): void {
    const flags = opts.flags || {};
    const packetOpts = {
      preEncoded: true,
      volatile: flags.volatile,
      compress: flags.compress,
    };

    packet.nsp = this.nsp.name;
    const encodedPackets = this._encode(packet, packetOpts);

    this.apply(opts, (socket) => {
      useEventFilter(socket, packet.data, (nextData) => {
        let packetToSend = packet;
        let encodedPacketsToSend = encodedPackets;
        
        if (nextData !== packet.data) {
          packetToSend = {type: packet.type, data: nextData};
          encodedPacketsToSend = this._encode(packetToSend, packetOpts);
        }
        
        if (typeof socket.notifyOutgoingListeners === "function") {
          socket.notifyOutgoingListeners(packetToSend);
        }
  
        socket.client.writeToEngine(encodedPacketsToSend, packetOpts);
      });
    });
  }
```

**Describe alternatives you've considered**
I've drawn up an alternative approach using the tools at hand and this is basically what this would look like. You have to filter all sockets before emitting:

```ts
async function emitUserCreated(user: { name: string; salary?: number; team: string }) {
  const sockets = await io.fetchSockets();
  sockets.forEach((socket) => {
    if (socket.data.permissions[user.team].canViewSalary) {
      socket.emit('userCreated', user);
    } else {
      socket.emit('userCreated', omit(user, 'salary'));
    }
  });
}
```

However this is not performant especially in a multi-node setup with a redis adapter because you first have to wait for all the nodes to give you all the connected sockets and then emit them one by one, which will send single messages back to the individual nodes where the sockets are connected. Furthermore the emitter should not be the one with this load.

**Additional context**
Our webserver uses PHP and we would like to use the redis emitter at some point. Currently we only send an HTTP request to one socket.io node, which listens to HTTP on a separate port and then emits the HTTP request to the requested recipients (rooms).

The socket data comes from a signed json web token, so the stored permissions are trustworthy.

**Comment by darrachequesne** [comment]
Hi! I think the easiest way to implement this in a multi-node setup is with the `serverSideEmit()` method:

```js
// on a Socket.IO node, or with the redis emitter
io.serverSideEmit("user-created", user);

// on each Socket.IO node
io.on("user-created", (user) => {
  const sockets = io.of("/").sockets; // equivalent of await io.local.fetchSockets()

  sockets.forEach((socket) => {
    if (socket.data.permissions[user.team].canViewSalary) {
      socket.emit('userCreated', user);
    } else {
      socket.emit('userCreated', omit(user, 'salary'));
    }
  });
});
```

Reference: https://socket.io/docs/v4/server-api/#serverserversideemiteventname-args

**Comment by uncaught** [comment]
Thanks for your reply! Looks like this is what I need and that should keep the load on each node.

Is there any downside of using `await io.local.fetchSockets()` instead of `io.of("/").sockets`? Because I need to use rooms, too, and the `.of()` doesn't seem to be on the `BroadcastOperator` class. So it'd be `await io.to(...).local.fetchSockets()` for me.

And if I understand the `serverSideEmit` correctly, it just emits to _other_ servers, not the current one, right? So in principle if I want to emit something to all from one external call, I'd have to do basically:

```js
async function emitFooLocally(data) {
  const sockets = await io.to(...).local.fetchSockets();
  sockets.forEach((socket) => socket.emit('foo', data));
}

/** gets called externally when foo happened **/
export function onFoo(data) {
  io.serverSideEmit('foo-server-side', data); //to other servers in the cluster
  emitFooLocally(data);
}

io.on('foo-server-side', emitFooLocally);
```

**Comment by uncaught** [comment]
Tried it, works like a charm, thanks.
