### ISSUE TITLE
Memory leak by sending messages

### ISSUE THREAD

**Issue by apostx** [socketio/socket.io#4710]
**Describe the bug**
I experienced some memory leaking on server side after seding bigger messages to the client.

**To Reproduce**
1. Start the server
2. Check te logged memory data and wait until it get normalized.
    (in my case it was: { rss: 44904448, heapTotal: 7811072, heapUsed: 4983760 })
3. Start the client and wait for a few seconds (~20)
4. Close the client.
5. Check te logged memory data and wait until it get normalized.
    (in my case it was: { rss: 50757632, heapTotal: 8335360, heapUsed: 5339448 })
6. You will see the new normalized values are way bigger than before the client were running.

Socket.IO server version: 4.6.1

*Server*

```js
const http = require("http");
const socketIo = require("socket.io");

const server = http.createServer();
const io = socketIo(server, {
    connectionStateRecovery: {
        maxDisconnectionDuration: 0,
        skipMiddlewares: true,
        perMessageDeflate: false,
    }
});

setInterval(() => {
    gc();
    const {rss, heapTotal, heapUsed} = process.memoryUsage();
    console.log({rss, heapTotal, heapUsed});
}, 3000);

io.on('connection', (socket) => {
    console.log(`A user has connected (recovered: ${socket.recovered})`);

    if (socket.recovered) {
        return;
    }

    const timer = sendData(socket);

    socket.on('message', (data) => {
        console.log(`Received message from ${socket.id}: ${data}`);
        socket.emit('message', `Server received: ${data}`);
    });

    socket.on('disconnect', () => {
        socket.disconnect(true);
        clearInterval(timer);
        console.log(`User ${socket.id} has disconnected`);
    });
});

server.listen(3000, () => {
    console.log('Server listening on port 3000');
});

function sendData(socket) {
    let index = 0;
    return setInterval(() => {
        socket.emit('msg', 'x'.repeat(1*1024));
    }, 10);
}

```

Socket.IO client version: 4.6.1

*Client*

```js
const { io } = require('socket.io-client');

const socket = io('ws://localhost:3000', {
    transports: ['websocket'],
    forceNew: true,
});

socket.on('msg', (data) => {
    console.log(data.length);
});

process.once('SIGINT', () => {
    socket.close();
    process.exit();
});

```

**Expected behavior**
The used heap should be reduced to the original value after the client disconnected

**Platform:**
 - Device: Docker
 - OS: node:14-alpine

**Additional context**
(BTW only running the empty server I also experienced a slow growing in the memory usage)

**Comment by darrachequesne** [comment]
Hi! When connection state recovery is enabled, messages are temporarily stored, which could explain the memory usage. With the in-memory adapter, the expired messages are cleaned up once per minute: https://github.com/socketio/socket.io-adapter/blob/28f60b880ad04ff4b48ade0cd529f1970643604f/lib/index.ts#L418-L433

Could you try disabling this feature?

> BTW only running the empty server I also experienced a slow growing in the memory usage

Could you please provide a working example reproducing the issue? Thanks!

See also: https://socket.io/docs/v4/memory-usage/

**Comment by apostx** [comment]
Hey, 
thank you for the suggestion.
In the end I just looked into the memory usage by the inspector and could see the extra memory was taken natively by the nodejs.
(It was a little bit unexpected)
Closing the issue and sorry about the false alarm.
