### ISSUE TITLE
security: vulnerability reported in `engine.io@6.4.1`

### ISSUE THREAD

**Issue by vince-fugnitto** [socketio/socket.io#4711]
**Describe the bug**

There is a [security vulnerability](https://github.com/advisories/GHSA-q9mw-68c2-j6m5) reported in `engine.io@6.4.1` which `socket.io` declares in it's dependencies:

https://github.com/socketio/socket.io/blob/3d44aae381af38349fdb808d510d9f47a0c2507e/package.json#L52

_npm audit output_:

```
$ npm audit
# npm audit report

cookiejar  <2.1.4
Severity: moderate
cookiejar Regular Expression Denial of Service via Cookie.parse function - https://github.com/advisories/GHSA-h452-7996-h45h
fix available via `npm audit fix`
node_modules/cookiejar

engine.io  5.1.0 - 6.4.1
Severity: high
engine.io Uncaught Exception vulnerability - https://github.com/advisories/GHSA-q9mw-68c2-j6m5
fix available via `npm audit fix`
node_modules/engine.io

2 vulnerabilities (1 moderate, 1 high)

To address all issues, run:
  npm audit fix
```

**To Reproduce**

1. clone the repository
2. perform `npm audit`

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io/commit/12b0de4f524083c31b613ce33e4fd9f8d313f434. Thanks for the heads-up :+1:

**Comment by vince-fugnitto** [comment]
@darrachequesne thanks for the quick fix! When can we expect a new release?
