### ISSUE TITLE
Cross Domain Socket.IO not working as expected

### ISSUE THREAD

**Issue by devashish-gopalani-cognoai** [socketio/socket.io#4720]
**Describe the bug**
I have got a load balancer (AWS ALB) behind which two EC2 instances of Socket.IO are running. I have enabled sticky sessions too. The problem which I am facing is that when I start a socket connection from a domain (say xyz.com) to my Socket.IO setup (say socketio-mydomain.com) I am getting the following error in the console on the client side:

```
POST https://socketio-mydomain.com/websocket/?roomKey=4205ac9f-a6e8-495a-a6cd-2224638576b6&EIO=4&transport=polling&t=OX8oqUE&sid=iYBx5_oOsPP7g52vAAHP 400
```

On the backend, I am getting the error of Session ID unknown.
AWS ALB is sending back it's cookies in the response of the first GET request for maintaining sticky sessions. It is send it in the Set-Cookie header. Both AWSALB and AWSALBCORS are being sent. Despite of this I am still getting the above mentioned error.

**To Reproduce**

Please fill the following code example:

Socket.IO server version: `4.6.0`

*Server*

```js
const { Server } = require("socket.io");

const io = new Server(3000, {
  path: "/websocket/",
  adapter: createAdapter(redisClient),
  cors: {
    origin: "*",
    credentials: true,
  },
  serveClient: false,
});

```

**Please note:** Even if I specify the domains in the origin, it still gives the same error.

Socket.IO client version: `4.4.1`

*Client*

For the client side, I am using the normal JavaScript implementation from the cdn of socket.io.

```js
window.SOCKET_INSTANCE = io(`https://socketio-mydomain.com/cobrowse?roomKey=${session_id}`, {
    path: "/websocket/",
    withCredentials: true
});

window.SOCKET_INSTANCE.on('connect', () => {
    console.log('connected to server');

    window.SOCKET_INSTANCE.on('disconnect', () => {
      
    });
});
```

**Expected behavior**
The expectation is that the connection get established even when we are requesting from cross domain.

**Platform:**
 - Desktop (running Ubuntu 22.04): Google Chrome browser - Version 113.0.5672.92 (Official Build) (64-bit)

**Comment by darrachequesne** [comment]
Hi! You can't use `origin: "*"` when setting `credentials: true`.

You should see an error like this in the browser console:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘.../socket.io/?EIO=4&transport=polling&t=NvQfU77’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’)

You need to either provide a list of domains (recommended solution) or use the following method:

```js
const io = new Server(httpServer, {
  cors: {
    origin: (_req, callback) => {
      callback(null, true);
    },
    credentials: true
  }
});
```

Please note that in that case, like with `origin: "*"` or `origin: true`, you are basically disabling the security provided by Cross-Origin Resource Sharing (CORS), as any domain will be able to reach your server. Please use with caution.

Reference: https://socket.io/docs/v4/server-options/#cors

**Comment by devashish-gopalani-cognoai** [comment]
@darrachequesne I have tried both the solutions (specified a list of the domains and also used the provided method) which you have suggested but I am still getting the same error. Is there anything else that I should be looking at?

**Comment by darrachequesne** [comment]
> Even if I specify the domains in the origin, it still gives the same error.

Sorry, I didn't read thoroughly...

I will try to reproduce the issue on AWS, I will get back to you.

**Comment by devashish-gopalani-cognoai** [comment]
That would be really helpful! Thanks @darrachequesne! 

PS: I enabled duration based stickiness. If you need any more details, please do let me know!

**Comment by devashish-gopalani-cognoai** [comment]
Hey @darrachequesne, were you able to check regarding this?

**Comment by devashish-gopalani-cognoai** [comment]
Hey @darrachequesne, any luck on this?

**Comment by darrachequesne** [comment]
So, I created two EC2 instances:

![Screenshot from 2023-06-02 10-50-37](https://github.com/socketio/socket.io/assets/13031701/7004874a-ca65-4654-bb8c-1843c1389267)

A target group:

![Screenshot from 2023-06-02 10-50-51](https://github.com/socketio/socket.io/assets/13031701/71df18d3-4ca6-4df8-a0f5-115e54694fe7)

With duration-based stickiness:

![Screenshot from 2023-06-02 10-50-58](https://github.com/socketio/socket.io/assets/13031701/0e1efbeb-19c6-4342-b834-4f3e8a1d1ffe)

Then an ALB:

![Screenshot from 2023-06-02 10-51-22](https://github.com/socketio/socket.io/assets/13031701/1fd5a30a-ac0d-400d-b744-4c65e6fb3d43)

My server is based on the example [here](https://github.com/socketio/socket.io-echo-server), with:

```js
const io = new Server({
  allowEIO3,
  pingInterval: 3000,
  cors: {
    // could also have used origin: ["localhost:3000"]
    origin: (_req, callback) => {
      callback(null, true);
    },
    credentials: true
  }
});
```

And the client:

```js
const socket = io("http://alb01-xxxx.eu-west-3.elb.amazonaws.com", {
  transports: ["polling"],
  withCredentials: true
});
```

And I don't get any 400 errors:

![Screenshot from 2023-06-02 10-51-41](https://github.com/socketio/socket.io/assets/13031701/4686019a-d01a-4cb4-ac13-866c8780b24d)

You can see that the `AWSALB` cookie is included in all requests.

Note: the `pingInterval: 3000` and `transports: ["polling"]` options are not mandatory here, it's just to check if the stickiness is working properly.

**Comment by devashish-gopalani-cognoai** [comment]
@darrachequesne is this working on cross domain? For the setup I have done, if I am establishing a connection via the same domain as the one on which I have setup my Socket.IO server then things work as expected. As soon as I try to establish a connection from a different domain I get the 400 error code.

**Comment by darrachequesne** [comment]
Yes, I'm connecting from `http://localhost:3000` to `https://alb-....amazonaws.com`. You can see the `Access-Control...` headers in the screenshot above.

**Comment by devashish-gopalani-cognoai** [comment]
@darrachequesne thanks, I will check this once at my end and then get back to you!

**Comment by devashish-gopalani-cognoai** [comment]
Closing this issue for now. I'll reopen it if I find any issues.
