### ISSUE TITLE
Add method were we can emit and listen to server 

### ISSUE THREAD

**Issue by elmcapp** [socketio/socket.io#4724]
I am using socket.io with express to create a tunnel server something like localtunnel.me I am in the need to be able to emit messages from the server and be able to listen to the emitted data in the same server. I was thinking of using io.addListener but it does not do anything. 

Goal:
The server can for example``` io.addListener``` or. ``` io.on("in_server", console.log) ``` 
The server can ```io.emit("in_server", "data here")```
when the emit happen in the server the server can also listen. 

By doing something like this I would be able to use the data outside the:
```
io.on("connection", (socket) => {})
```

**Comment by vitaly-t** [comment]
What is the point of using sockets for communicating data inside one process? 😕

**Comment by Shekharcodess** [comment]
To achieve your goal of emitting messages from the server and being able to listen to those emitted messages within the same server using Socket.IO and Express. You have to set up the Socket.IO server within your Express server

**Comment by elmcapp** [comment]
> To achieve your goal of emitting messages from the server and being able to listen to those emitted messages within the same server using Socket.IO and Express. You have to set up the Socket.IO server within your Express server

Can you show an example below is some what that I am trying to do however I know it's not right. I am new to this. 

````
import EventEmitter from "events";
import express from "express";
import http from "http";
import { Server } from "socket.io";

const app = express();
const emitter = new EventEmitter();

// socket
const server = http.createServer(app);
const io = new Server(server, {
  cors: {
    origin: "*",
  },
});

app.set(express.urlencoded({ extended: false }));

app.set(express.json());

// browser page
app.get("/", (req, res) => {
  const url = req.url;

  // emit to the remote host
  io.to(socketId).emit("host", url);

  // Send response back to client
  emitter.addListener("response", (data) => {
    res.send(data);
  });
});

// socket connection
io.on("connection", (socket) => {
  //Listen to to remote host 
  socket.on("remote_response", (data) => {
    emitter.emit("response", data);
  });
});

server.listen(9800, () => {
  console.log("server is running");
});
````

**Comment by Shekharcodess** [comment]
> > To achieve your goal of emitting messages from the server and being able to listen to those emitted messages within the same server using Socket.IO and Express. You have to set up the Socket.IO server within your Express server
> 
> Can you show an example below is some what that I am trying to do however I know it's not right. I am new to this.
> 
> ```
> import EventEmitter from "events";
> import express from "express";
> import http from "http";
> import { Server } from "socket.io";
> 
> const app = express();
> const emitter = new EventEmitter();
> 
> // socket
> const server = http.createServer(app);
> const io = new Server(server, {
>   cors: {
>     origin: "*",
>   },
> });
> 
> app.set(express.urlencoded({ extended: false }));
> 
> app.set(express.json());
> 
> // browser page
> app.get("/", (req, res) => {
>   const url = req.url;
> 
>   // emit to the remote host
>   io.to(socketId).emit("host", url);
> 
>   // Send response back to client
>   emitter.addListener("response", (data) => {
>     res.send(data);
>   });
> });
> 
> // socket connection
> io.on("connection", (socket) => {
>   //Listen to to remote host 
>   socket.on("remote_response", (data) => {
>     emitter.emit("response", data);
>   });
> });
> 
> server.listen(9800, () => {
>   console.log("server is running");
> });
> ```

You can try adding this modification to your code and I think it should work.
import EventEmitter from "events";
import express from "express";
import http from "http";
import { Server } from "socket.io";

const app = express();
const emitter = new EventEmitter();

// socket
const server = http.createServer(app);
const io = new Server(server, {
  cors: {
    origin: "*",
  },
});

app.set(express.urlencoded({ extended: false }));
app.set(express.json());

// Listen to "in_server" event on the server
io.on("in_server", (data) => {
  console.log("Received 'in_server' event:", data);
});

// browser page
app.get("/", (req, res) => {
  const url = req.url;

  // Emit "in_server" event from the server
  io.emit("in_server", "data here");

  // Send response back to client
  emitter.addListener("response", (data) => {
    res.send(data);
  });
});

// socket connection
io.on("connection", (socket) => {
  // Listen to "remote_response" event from remote host
  socket.on("remote_response", (data) => {
    emitter.emit("response", data);
  });
});

server.listen(9800, () => {
  console.log("server is running");
});
Let me know if it does work

**Comment by Shekharcodess** [comment]
``import EventEmitter from "events";
import express from "express";
import http from "http";
import { Server } from "socket.io";

const app = express();
const emitter = new EventEmitter();

// socket
const server = http.createServer(app);
const io = new Server(server, {
  cors: {
    origin: "*",
  },
});

app.set(express.urlencoded({ extended: false }));
app.set(express.json());

// Listen to "in_server" event on the server
io.on("in_server", (data) => {
  console.log("Received 'in_server' event:", data);
});

// browser page
app.get("/", (req, res) => {
  const url = req.url;

  // Emit "in_server" event from the server
  io.emit("in_server", "data here");

  // Send response back to client
  emitter.addListener("response", (data) => {
    res.send(data);
  });
});

// socket connection
io.on("connection", (socket) => {
  // Listen to "remote_response" event from remote host
  socket.on("remote_response", (data) => {
    emitter.emit("response", data);
  });
});

server.listen(9800, () => {
  console.log("server is running");
});

**Comment by Shekharcodess** [comment]
You can try adding these modifications to your code.

> import EventEmitter from "events";
import express from "express";
import http from "http";
import { Server } from "socket.io";

const app = express();
const emitter = new EventEmitter();

// socket
const server = http.createServer(app);
const io = new Server(server, {
  cors: {
    origin: "*",
  },
});

app.set(express.urlencoded({ extended: false }));
app.set(express.json());

// Listen to "in_server" event on the server
io.on("in_server", (data) => {
  console.log("Received 'in_server' event:", data);
});

// browser page
app.get("/", (req, res) => {
  const url = req.url;

  // Emit "in_server" event from the server
  io.emit("in_server", "data here");

  // Send response back to client
  emitter.addListener("response", (data) => {
    res.send(data);
  });
});

// socket connection
io.on("connection", (socket) => {
  // Listen to "remote_response" event from remote host
  socket.on("remote_response", (data) => {
    emitter.emit("response", data);
  });
});

server.listen(9800, () => {
  console.log("server is running");
});


Let me know if it works

**Comment by Shekharcodess** [comment]
> > To achieve your goal of emitting messages from the server and being able to listen to those emitted messages within the same server using Socket.IO and Express. You have to set up the Socket.IO server within your Express server
> 
> Can you show an example below is some what that I am trying to do however I know it's not right. I am new to this.
> 
> ```
> import EventEmitter from "events";
> import express from "express";
> import http from "http";
> import { Server } from "socket.io";
> 
> const app = express();
> const emitter = new EventEmitter();
> 
> // socket
> const server = http.createServer(app);
> const io = new Server(server, {
>   cors: {
>     origin: "*",
>   },
> });
> 
> app.set(express.urlencoded({ extended: false }));
> 
> app.set(express.json());
> 
> // browser page
> app.get("/", (req, res) => {
>   const url = req.url;
> 
>   // emit to the remote host
>   io.to(socketId).emit("host", url);
> 
>   // Send response back to client
>   emitter.addListener("response", (data) => {
>     res.send(data);
>   });
> });
> 
> // socket connection
> io.on("connection", (socket) => {
>   //Listen to to remote host 
>   socket.on("remote_response", (data) => {
>     emitter.emit("response", data);
>   });
> });
> 
> server.listen(9800, () => {
>   console.log("server is running");
> });
> ```

You can try adding these modifications to your code.

import EventEmitter from "events";
import express from "express";
import http from "http";
import { Server } from "socket.io";

const app = express();
const emitter = new EventEmitter();

// socket
const server = http.createServer(app);
const io = new Server(server, {
  cors: {
    origin: "*",
  },
});

app.set(express.urlencoded({ extended: false }));
app.set(express.json());

// Listen to "in_server" event on the server
io.on("in_server", (data) => {
  console.log("Received 'in_server' event:", data);
});

// browser page
app.get("/", (req, res) => {
  const url = req.url;

  // Emit "in_server" event from the server
  io.emit("in_server", "data here");

  // Send response back to client
  emitter.addListener("response", (data) => {
    res.send(data);
  });
});

// socket connection
io.on("connection", (socket) => {
  // Listen to "remote_response" event from remote host
  socket.on("remote_response", (data) => {
    emitter.emit("response", data);
  });
});

server.listen(9800, () => {
  console.log("server is running");
});

**Comment by elmcapp** [comment]
I found a solution that will allow to emit and listen to the emits from anywhere regardless of being in ```io.on("connection" ,socket)``` callback. 

I am able to emit and listen to server emits using 
````
// Listen to "in_server" event on the server
io.engine.on("in_server", (data) => {
  console.log("Received 'in_server' event:", data);
});

io.engine.emit("in_server", "hey there");
````

Although I am not sure what ```io.engine``` do

**Comment by Shekharcodess** [comment]
@elmcapp basically in Socket.IO, `io.engine` property provides access to the underlying Engine.IO instance. Engine.IO is the low-level transport layer that powers Socket.IO and handles the real-time communication between the server and the client.

**Comment by elmcapp** [comment]
Yes it's working with custom events. I created an event called in_server and another event called server-event and its working

**Comment by darrachequesne** [comment]
I think this can be closed now. Please reopen if needed.
