### ISSUE TITLE
ESM distributable client is missing non-minified version

### ISSUE THREAD

**Issue by FossPrime** [socketio/socket.io#4731]
**Describe the bug**
There is no debuggable ESM distributable... making debugging extremely difficult in some situations... like StackBlitz, where WS inspector and source map file loader in DevTools won't work as they are provided by a service worker. Bundling it ourselves with a service worker doesn't solve the problem... we need an ESM debuggle package hosted somewhere. we cannot load ...?module due to node dependencies in package.json (ws and xml).

**To Reproduce**

Please fill the following code example:

Socket.IO client version: `4.6.2`

*Client*

```js
import io from 'https://unpkg.com/socket.io-client@4.6.2/dist/socket.io.esm.js';
```

**Expected behavior**
Load as normal, with debug logging calls.

**Platform:**
 - Device: Yes
 - OS: Yes

**Additional context**
Chrome has a bug where DevTools can't load file based source maps from a service worker. Easy fix is to just point to unpackage... but there is no ESM option.

https://bugs.chromium.org/p/chromium/issues/detail?id=1206431#c13

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-client/commit/781d753a626d01e675056a2ff4e27f5dd599564f, included in version [4.7.0](https://github.com/socketio/socket.io-client/releases/tag/4.7.0).

Please reopen if needed.
