### ISSUE TITLE
Error with socket.io in Tor Browser

### ISSUE THREAD

**Issue by CaribbeanLobster** [socketio/socket.io#4732]
Hello  :wave:

I'm have problems with socket on websites via NodeBB community software, when use Tor Browser or Brave browser in Tor mode. Are there variants to fix this error? Thank you!

`https://example.com/socket.io/?_csrf=a0b3a582192eba97a69c6a4a7e2e19ecc7107e1a8e99beb47fa6cad2e5504d6b30dc41a11834fad9fec64d82c27ef623caf7c88b4b86d9b7941237e0e54e4816&EIO=4&transport=polling&t=OXxzfT5&sid=-vh36HQZkceH8ClfAAbL`

**Tor Browser**
<img width="996" alt="1" src="https://github.com/socketio/socket.io/assets/135332870/d779ed94-4e99-44de-bf25-8fa4501bb34d">

**Brave**

<img width="1199" alt="2" src="https://github.com/socketio/socket.io/assets/135332870/bd3eb4c3-2576-4202-ad0a-e4e5c426a8a8">

**To Reproduce**

NodeBB: `https://github.com/NodeBB/NodeBB` or website `https://try.nodebb.org`, `https://community.nodebb.org` for the test from tor browsers.
Tor Browser: `https://www.torproject.org/download/`
Brave Browser: `https://brave.com/ru/download/`
Ubuntu: `18.04`
Socket.IO version: `4.6.1`

```
"socket.io": "4.6.1",
"socket.io-client": "4.6.1",
"@socket.io/redis-adapter": "8.2.0",
```

More: https://github.com/NodeBB/NodeBB/blob/6aae88d5dd48d46d5943f94bd5226224b37d07f4/install/package.json#L132

**Platform:**
 - Device: `PC`
 - OS: `Windows/MacOS`
 - Browser: `Tor Browser` (standart security level + noscript trust), `Brave` (tor window + disable shield)

**Comment by darrachequesne** [comment]
Please check https://github.com/NodeBB/NodeBB/issues/6286
