### ISSUE TITLE
Connection State Recovery

### ISSUE THREAD

**Issue by ianShoenberger** [socketio/socket.io#4733]
I have followed the steps outlined in https://socket.io/docs/v4/connection-state-recovery, but not sure the state recovery is actually working. Using 4.60 for both server and client.

When I force the socket to disconnect by doing the 'socket.io.engine.close()' from the client (as suggested in the docs) I do see the server and client both responding to the 'connection' event afterwards, but in both sides the socket.recovered boolean is always false.

What's worse, is that any future events I emit from the server aren't received by the client.

Can you confirm that calling close() on the engine from the client should force a recovery state that also continues to allow communication between the frontend and backend?

**Comment by darrachequesne** [comment]
Hi! I wasn't able to reproduce the issue: https://github.com/socketio/socket.io-fiddle/tree/connection-state-recovery

Could you please check?

**Comment by ianShoenberger** [comment]
that's correct,

@darrachequesne after running your branch, I do see everything working as intended, _but_, when I increase the setTimeout in the server code to only emit 'foo' every 20s then the 'recovered' property is always false in both client and server, and the client never receives the event or data.

Perhaps the socket event listening would continue to work after other types of disconnects?
But when doing socket.io.engine.close() it does not.

**Comment by darrachequesne** [comment]
@dklmuc you are right, the server needs to send at least one packet to initialize the offset on the client side. This should indeed be mentioned in the documentation.

@ianShoenberger I could indeed reproduce. I guess we could include the last offset in the handshake payload sent to the client, so the recovery would work even without that first packet.

**Comment by maggo** [comment]
> you are right, the server needs to send at least one packet to initialize the offset on the client side. This should indeed be mentioned in the documentation.

This caused us 2 hours of debugging. Yes, please update the docs…

**Comment by darrachequesne** [comment]
Added a note here: https://socket.io/docs/v4/connection-state-recovery#how-it-works-under-the-hood

I'm not sure about adding the offset in the handshake, since that would require another round trip to the database.

Please reopen if needed.
