### ISSUE TITLE
Double connect

### ISSUE THREAD

**Issue by Gorokhov** [socketio/socket.io#474]
somehow double connect happens to clients(meaning all the handlers are called twice), could not reproduce the situation on my own, but keep receiving bug reports, the behavior is exactly the same if you call socket.socket.connect() on already connected socket.(tested on websocket and flashsocket)

**Comment by leventmenekse** [comment]
I might reproduce it. I am using socket.io 1.3.5 and express 4.12.4. 

My express app sits on 127.0.0.1:3000 and i open up my browser and type that ip address and socket.io opens only one websocket.

I have a domain such as abc.com and i forward it to 127.0.0.1. I open abc.com on my browser and in index.html file there is the line;

```javascript
<script>
        var socket = io('http://localhost:3000/mysql');

        socket.on('processlist', function (data){
            console.log(data);
        });
</script>
```

this opens 2 websockets. 

I haven't tried nginx with proxy yet. I will let you know as soon as i try.

![screen shot 2015-05-29 at 23 53 29](https://cloud.githubusercontent.com/assets/1311988/7892539/fd721e22-065d-11e5-9c07-4eedbac1810d.png)

**Comment by bbcollinsworth** [comment]
Still encountering this issue. For me it happened on server restart -- I was attaching my socket.on('message') event handlers when initial connection event from server fired, and if the server restarted while the client was open that event fired multiple times (more time the longer the client had been waiting for server restart).

My fix for now has been to 'debounce' the socket event attaching so it only happens on the first server connect, like so: 

````
client.socketEventsAttached = false;

socket.on('connect',function(){
     if (!client.socketEventsAttached){
          attachSocketEvents();
     }
});
````

You can also put your message event listeners outside of the the socket.on('connect') listener as @gdiz suggested. I've just had some issues there with socket events firing before the server or client are ready for them.

**Comment by jyywhw** [comment]
@bbcollinsworth  what's the client object?

**Comment by exppro** [comment]
Still encountering this issue with fresh socketio and basic example.

**Comment by brandonraphael** [comment]
I'm still encountering this issue as following the basic example.

**Comment by darrachequesne** [comment]
@brandonraphael could you please provide an example reproducing your issue (based on https://github.com/darrachequesne/socket.io-fiddle for example) and open a new issue?

**Comment by rd67** [comment]
Any update this is still happening and creating problems in the app

These are the logs - 
0|Api Server  | Connected!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  DKap3hUYFSpKBRr7AFgc 4351 2018-12-26 10:58:25
0|Api Server  | Connected!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  VS98DBFVTNF6ifzmAFgd 4351 2018-12-26 10:58:25

4351 is the user id and the number of connections is also not static like 2 in the case for user 4351.
Another log shows 6 connections at the same time for the same user.

Also, have checked these two socket ids on the server and they are showing valid. But the frontend is only able to listen to one of them which is always the first socket id.

Any help would be really great.
Thanks in advance.

**Comment by Gibigbig** [comment]
> I'm still encountering this issue as per following the basic example.
> 
> **EDIT:** I found a fix, although I'm not sure its exactly proper. Essentially all it requires is using
> 
> ```
> io.once('connection', ...)
> ```
> instead of
> 
> ```
> io.on('connection', ...)
> ```

thank you for this

**Comment by rd67** [comment]
The issue got resolved after changing the version used on the client end. Another fix would be to use rooms instead of single socket id. Found out that every socket id is itself a room only part that was to be changed was of the new connection code of putting every socket id in user room. 
Consider a user slug is User1 then a room was created User1 and every new socket connection via slug User1 was put inside the room User1.

**Comment by SimonVuong** [comment]
Was having the same problem and it was driving me crazy. Was definitely NOT re-registering event listeners on client either. In my setup, I have a nodejs server hosting the socketio endpoint and I also have another nodejs server acting as my socketio client. The trick was to connect client side with websocket transport and use the `forceNode`. Ex

```
// client side
const socket = io('<url>', {
  transports: ['websocket'],
  forceNode: true,
});
```

**Comment by michael-lynch** [comment]
I believe I'm having this same issue. I'm building a chat room and when someone joins the room, I emit a "<User> has joined the room" message to the room.

Everything works great, but if I leave the room and then enter it a second time, the intro message is emitted _twice_. If I leave the room again and re-enter it a third time, the intro message is emitted three times, and so on. Every _reconnection_ to the _same_ room results in a duplicate intro message. However, if I enter a _different_ room, I only see the intro message once.

Using `io.once('connection', ...)` didn't work for me. In fact, all of my events stopped working.

Using the "debounce" method didn't work either. Again, none of my events even registered.

Lastly, using `forceNode: true` option client side didn't work either.

I am using `2.2.0` on both the server and client. Is there anything I'm missing?

**Comment by swr7der** [comment]
Having the same issue on V2.3.0.

On the server crash, each of the events is being received by the client n+1 times.

All the methods defined above ain't working. Tried `forceNew` with true and false, tried `reconnecting` with true and false but nothing seems working.

Is there any fix to this issue? Or is there any specific restart logic that we need to follow? 

Using Mac and Chrome

**Comment by swr7der** [comment]
> I believe I'm having this same issue. I'm building a chat room and when someone joins the room, I emit a " has joined the room" message to the room.
> 
> Everything works great, but if I leave the room and then enter it a second time, the intro message is emitted _twice_. If I leave the room again and re-enter it a third time, the intro message is emitted three times, and so on. Every _reconnection_ to the _same_ room results in a duplicate intro message. However, if I enter a _different_ room, I only see the intro message once.
> 
> Using `io.once('connection', ...)` didn't work for me. In fact, all of my events stopped working.
> 
> Using the "debounce" method didn't work either. Again, none of my events even registered.
> 
> Lastly, using `forceNode: true` option client side didn't work either.
> 
> I am using `2.2.0` on both the server and client. Is there anything I'm missing?

I was wondering about the same issue, but ultimately, telling the client to connect only `once` helped.

Here's my config for the client:
```
var socket = io.connect("http://localhost:3000/test", 
            { upgrade: false, transports: ['websocket'], reconnection: true, forceNew: false});
socket.once('connect', socketConn => {
            socket.on('message', data => {
                console.log(data);
            })
        }) 
```
The client will just be registered `once` for `connect` event, thus any other event inside it would be registered once. Now if the server will crash, the client will just try to reconnect to it and won't try to create a new connection. As soon as it gets the response from the server, it will start processing the messages. 

So `io.once` need to be set on the client-side, not on the server side.

**Comment by qiulang** [comment]
I am using client 2.1 version. I find it is very easy trigger it. Every time my node server restarts (e.g. using nodemon) client always trigger several reconnect event then connect even.

**Comment by swr7der** [comment]
> I am using client 2.1 version. I find it is very easy trigger it in my dev env. Every time my node server restarts (e.g. using nodemon) client always trigger several reconnect event then connect even. But I can't figure out the root cause

I was having the same issue that too using nodemon itself. but ultimately, telling the client to connect only `once` helped.
 Try the code from my reply just above. It helped me and every time server restarts, clients are getting new connections.

**Comment by ohabash** [comment]
My problem was simple

I had the same client-side app open on 2 tabs. oops

**Comment by joseph4tw** [comment]
I had the same issue as well. However, for me, I mistakenly put my client-side handlers inside the `socket.on('connection', cb)` callback function.

Here's a snippet to demonstrate:

**client.js (in node.js)**

```js
const client = require('socket.io-client');
const socket = client('my_endpoint', {
  transports: [ 'websockets' ]
});

socket.on('connect', () => {
  console.log('connected');
  socket.on('myEvent', (message) => {
    console.log(`message: ${message}`);
  });
});
```

When a disconnect and reconnect happened, it would call `socket.on('connect', cb)` again, and the `myEvent` handler would register a second handler of the same name. So when the server emitted `myEvent` again, I would have two console logs of the same message.

To resolve, I had to put my other handlers outside the `connect` handler.

```js
const client = require('socket.io-client');
const socket = client('my_endpoint', {
  transports: [ 'websockets' ]
});

socket.on('connect', () => {
  console.log('connected');
});

socket.on('myEvent', (message) => {
  console.log(`message: ${message}`);
});
```

I think my confusion came from how the docs show the server-side putting `socket.on` events inside the `connect` event. That's on me for not reading the docs more carefully, but I figured I'd put this here in case someone else makes the same mistake.

Also, even though I saw this issue in node.js specifically, I'm sure this would be a problem in the browser as well.

**Comment by constantant** [comment]
So the thing is that the `connect` event is emitted before the `connected` property is set to `true`.
As work around you can write something like that:
```ts
          const waitForConnect = (socket: Socket, cb: () => void) => {
            setTimeout(() => {
              if (socket.connected) {
                cb();
              } else {
                waitForConnect(cb);
              }
            }, 100);
          };
```

**Comment by darrachequesne** [comment]
> So the thing is that the connect event is emitted before the connected property is set to true.

I don't think this is true: https://github.com/socketio/socket.io-client/blob/0536fccfc29b58ccc7bbf7e6103877134ac6ec5b/lib/socket.ts#L785-L787

Could you please provide some additional details?

**Comment by constantant** [comment]
@darrachequesne 
What should I see there? 

1. The bug appears while creating `Socket` from `Manager` with `auth`. 
2. Yes, `connected` is true on the `connect` event but at this moment the bug already happened while authorisation
