### ISSUE TITLE
Cannot Received Socket Manager EVENT_PING On Android Library

### ISSUE THREAD

**Issue by YovanggaAnandhika** [socketio/socket.io#4743]
**Describe the bug**
Cannot Received Event socket manager "ping" on Android

**To Reproduce**

Socket.IO server Run On Nodejs version: `4.5.2`

*Server*

```js
import { Server } from "socket.io";

const io = new Server(3000, {});

io.on("connection", (socket) => {
  console.log(`connect ${socket.id}`);

  socket.on("disconnect", () => {
    console.log(`disconnect ${socket.id}`);
  });
});
```

Socket.IO client version: `2.1.0` Android library

*Client*

```kotlin
Socket.io().on(EVENT_PING) {
    Log.d(LOGGER PACKET, "ping")
}
```

**Expected behavior**
The Socket Io Client Run On Service Class and Foreground Service. with Wakelock Particial 

**Platform:**
 - Device: [e.g. Samsung M23]
 - OS: [e.g. Android 13, API 33]
 
 **gradle module**
```gradle
    implementation ('io.socket:socket.io-client:2.1.0') {
           exclude group: 'org.json', module: 'json'
     }
```

**Additional context**
Socket IO Client run successfully. but no Received Ping Like Nodejs Client on ping Event

**Comment by darrachequesne** [comment]
Closed in favor of https://github.com/socketio/socket.io-client-java/issues/734.
