### ISSUE TITLE
Extra data set in client socket not set/present in socket received by server (typescript)

### ISSUE THREAD

**Issue by GeneralPancakeMSTR** [socketio/socket.io#4760]
**Describe the bug**
Extra data set in a client socket (e.g. by [extending the client socket interface](https://stackoverflow.com/questions/48058924/saving-more-data-on-socket-io-object-in-typescript),  is not set or otherwise present in the socket received by the server on connection. 

**To Reproduce**

Socket.IO server version: `4.7.1`

*Server*

```ts
import express, {Request, Response} from 'express'; 
import path from 'path'; 

import * as http from 'http'; 
import {Server} from 'socket.io'; 

const app = express();
app.use(express.static(path.join(__dirname,'../dist')));

const hostname = '0.0.0.0';
const port = 5000;
const server = http.createServer(app); 

const io = new Server(server); 

io.on('connection',(socket) => {
    console.log(socket); 
    console.log(socket.id); 
    console.log(socket.data); 
});

function index(req:Request,res:Response):void {
    res.sendFile(path.join(__dirname,'index.html'));
};

app.get('/',index); 

server.listen(port, () => {
    console.log(`[server]: Server is running at http://*:${port}`);
});
```

Socket.IO client version: `4.7.1`

*Client*

```ts
import io, {Socket} from 'socket.io-client'; 

interface DataSocket extends Socket {
    custom_parameter:string 
}; 

const socket = <DataSocket>io();
socket.custom_parameter = 'Arbitrary Value'; 
console.log(socket); 
```

**Expected behavior**
The line `console.log(socket.data); `  in the server code prints `{custom_parameter: Arbitrary Value}` to the command line. 

Instead, this line prints `{}` to the command line. 

**Platform:**
 - Device: Dell workstation 
 - OS: 
 ```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

**Additional context**
This worked up until a few days ago. I don't know what I changed, other than trying to set custom data in sockets that are part of custom namespaces (which also doesn't work).

**Comment by darrachequesne** [comment]
Hi!

The `data` attribute only exists on the server side, not on the client side.

Reference: https://socket.io/docs/v4/server-api/#socketdata

You can pass any data in the `auth` object:

```ts
import io, {Socket} from 'socket.io-client'; 

interface DataSocket extends Socket {
    custom_parameter:string 
}; 

const socket = <DataSocket>io({
  auth: {
    custom_parameter: 'Arbitrary Value'
  }
});
console.log(socket); 
```

It will then be found in the handshake on the server side:

```js
io.on('connection',(socket) => {
    console.log(socket.handshake.auth); 
});
```

Reference: https://socket.io/docs/v4/client-options/#auth

**Comment by GeneralPancakeMSTR** [comment]
Very strange. I could swear that I was able to set this data client-side and then retrieve it server-side at one point. But good to know about the auth object.

**Comment by darrachequesne** [comment]
Thanks for the update :+1:

I think this can be closed now. Have a great day!
