### ISSUE TITLE
error: socket hang up

### ISSUE THREAD

**Issue by m-salman-afzal** [socketio/socket.io#4766]
**Describe the bug**
Unable to connect to socket

**To Reproduce**

Socket.IO server version: `4.7.1`

*Server*

```ts
/* eslint-disable no-console */
import {createServer} from "http";
import {Server} from "socket.io";

const httpServer = createServer();

const webSocket = (httpServer) => {
    const io = new Server(httpServer);

    io.on("connection", (socket) => {
        console.info("New client connected");

        socket.on("message", (data) => {
            console.info("Received message:", data);

            io.emit("message", data);
        });

        socket.on("disconnect", () => {
            console.info("Client disconnected");
        });
    });
};

webSocket(httpServer);

httpServer.listen(3000, "0.0.0.0", () => {
    console.info("Server listening on port 3000");
});
```

*Client*
Connecting from postman or wscat just for connection confirmation using ws://127.0.0.1:3000
Following are handshake details:
```
Request URL: http://127.0.0.1:3000/
Request Method: GET
Request Headers
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: sEs99c/d7DIMuvDn36WyCg==
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Host: 127.0.0.1:3000
```

**Expected behavior**
Should Connect

**Platform:**
 - Device: [NA]
 - OS: [WSL2 under Windows 11]

**Additional context**
I've tried it on simple Ubuntu and also with windows firewall disabled. Still not working

**Comment by darrachequesne** [comment]
Hi! You need to provide a handler for `/`, the Socket.IO server only respond to requests starting with `/socket.io/`:

```js
const httpServer = createServer((req, res) => {
  res.writeHead(404).end();
});
```

**Comment by m-salman-afzal** [comment]
tried but still same error.

**Comment by m-salman-afzal** [comment]
It looks like socket.io needs its own client for handshake and to establish a connection which is absent from postman. After doing it with socket.io-client, it worked.

**Comment by darrachequesne** [comment]
@m-salman-afzal postman now has native support for Socket.IO, please check https://learning.postman.com/docs/sending-requests/websocket/websocket/
