### ISSUE TITLE
Documentation: closeOnBeforeUnload

### ISSUE THREAD

**Issue by christopherreay** [socketio/socket.io#4770]
**Describe the bug**
description of operation of function is unclear
https://socket.io/docs/v4/client-options/#closeonbeforeunload

**To Reproduce**
Read docs for the function

**Expected behavior**
Describing things only in terms of negatives leaves the developer unsure of what actually *is* happening.

With `closeOnBeforeUnload` set to `false`
* **Firefox** will cause a `disconnect` event to be emitted by the Socket instance when the user reloads the page
  * **Chrome** or **Safari** will not.
* **Chrome** and **Safari** will cause a `close` event to be emitted by the Socket instance

With `closeOnBeforeUnload` set to `true`
* **all browsers** will have the same behavior (no `disconnect` event when reloading the page)
* **all browsers** will cause a `close` event to be emitted by the Socket instance
* ***Beware*** this might cause result in undetermined behaviour if you use the `beforeunload` independently in your application code.

**Platform:**
n/a
**Additional context**

**Comment by darrachequesne** [comment]
Hi! I have updated the documentation for the `closeOnBeforeUnload` option: https://socket.io/docs/v4/client-options/#closeonbeforeunload

Could you please check if that's clearer now?

**Comment by christopherreay** [comment]
Hey,

thank you for taking the time to respond :)

I think it is clearer, yes. To my mind it is still written in double
negatives, and would be clearer if it explained exactly what events are
emitted when.

tyty

Christopher Reay (they / them)


Be prepared to have your predictions come true

**Comment by darrachequesne** [comment]
@christopherreay thanks for your feedback :pray:

I've added a screenshot for both cases. I think we can now close this, please reopen if needed.
