### ISSUE TITLE
Setting up Socket.io server with Node.js Clusters (per docs) leave some requests hanging

### ISSUE THREAD

**Issue by radanjovic** [socketio/socket.io#4786]
**Describe the bug**
We are creating a project that uses Node.js (express + mongoose + typescript) and sockets to set up a backend infrastructure. We choose to use Socket.io for this,  and, since we need multi-thread approach to server multiple concurrent requests, we chose the Cluster module and sat it up the way described in your docs. However, we encounter a problem when sending HTTP requests to server. Some request go through without a problem (mostly the ones from Thunder Client (VS Code extension for sending request similar to Postman)), but some are left hanging until timeout expires. The weird part is that the request reaches the server, enters some middlewares, but never reaches the controller. And the even weirder thing is that the last middleware in which it enters and doesn't exit (as it seems) is the CORS middleware, and this is regardless which cors we use - the package (with or without custom options) or our own custom middleware with headers...

**To Reproduce**
Node Version: 18.17.0
Package Manager: yarn 1.22.19
Additional packages installed:
    "@socket.io/cluster-adapter": "^0.2.2",
    "@socket.io/sticky": "^1.0.3",

**When it usually happens**
From what we saw, some requests will go through super easy - and this is mostly after the client component is mounted on the screen (we use React), and regardless of the number of requests. But if we then wait a few seconds (we usually count to 10) - then requests start to fail - same config, same endpoint, everything is the same - it just won't execute till the end of specified timeout! And sometimes, none of the requests will go through at all !!!

**How do we know it's because of socket.io and not cors or something else**
When we commented out all the socket.io related code and left pure Node.js clusters (in the code bellow - first file (index.ts)) our REST API works as it should !!!

Please fill the following code example:

Socket.IO server version: `4.7.1`

*Server*

**This is the not working version! When we comment out everything from socket.io and in else (for workers) we listen for requests and not on master (the way normal Node.js clusters would work) - this approach works just fine all the time and all the requests go through!!!**

```ts
import { initEnvAndGlobals } from './config';
initEnvAndGlobals(process.argv.find(str => str.indexOf('--local-env') !== -1) ? (__dirname + '/.env') : undefined);

import cluster from 'node:cluster';
import { createServer } from 'node:http';
import { Server } from 'socket.io'
import { availableParallelism } from 'node:os';
import { blueColorInConsole, redColorInConsole } from './helpers/nodeConsole';
import app from './app';
import { initMongoDbConnection, initRedisConnection } from './db';
import { setupMaster, setupWorker } from '@socket.io/sticky';
import { createAdapter, setupPrimary } from '@socket.io/cluster-adapter';

let numCPUs = availableParallelism();
// numCPUs = 6;

initMongoDbConnection(() => initRedisConnection(() => {
    if (cluster.isPrimary) {
        console.log(blueColorInConsole, `Primary process ${process.pid} is starting...`);

        const httpServer = createServer();

        setupMaster(httpServer, {
            loadBalancingMethod: 'least-connection'
        });

        setupPrimary();

        // ? Remove later
        cluster.setupPrimary({
            serialization: 'advanced'
        });

        httpServer.listen(ENV.port);
        console.log(blueColorInConsole, `Curoflow API is listening on port: ${ENV.port}`);

        for (let i = 0; i < numCPUs; i++) cluster.fork();

        cluster.on('exit', (worker, code, signal) => {
            console.log(redColorInConsole, `Worker ${worker.process.pid} has died with code: ${code} and signal: ${signal}. Spawning another worker ...`);
            cluster.fork();
        });
    } else {
        console.log(blueColorInConsole, `Worker process ${process.pid} is starting...`);
        const httpServer = createServer(app);
        const io = new Server(httpServer, {
            allowRequest: (req, cb) => {
                if (req?.headers) cb(null, true); // TODO add headers protection
            },
            cors: {
                origin: '*',
                methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD']
            }
        });

        io.adapter(createAdapter());

        setupWorker(io);

        io.on('connection', (socket) => {
            console.log(blueColorInConsole, `New client with id ${socket.id} connected on worker: ${process.pid}.`);

            socket.on('disconnect', async () => {
                console.log(redColorInConsole, `Client with id ${socket.id} disconnected from worker: ${process.pid}`);
            });
        });
    }
}))
```

*And this is app.ts for reference*
```ts
import express from 'express';
import cors from 'cors';
import compression from 'compression';
import helmet from 'helmet';

import { addErrorAndDoneMethodsToExpressResponseObject } from './middlewares/utils/expressResponseMethods';
import { expressErrorHandler } from './middlewares/utils/expressErrorHandler';
// import { securityMiddleware } from './middlewares/utils/securityMiddleware';

import TestingRouter from './routes/testingRouter';
// import credentialsMiddleware from './middlewares/utils/credentialsMiddleware';

const app = express();

app.disable('x-powered-by');
app.use((_, _2, next) => {
    console.log('ENTERED SERVER'); // SHOWN
    next();
})
// CORS
// app.use(credentialsMiddleware);
app.use(cors());
app.use((_, _2, next) => {
    console.log('AFTER CORS'); // NOT SHOWN
    next();
})
// app.use(cors({
//     origin(origin, cb) {
//         if (!origin || origin === ENV.frontendUrl) return cb(null, true);
//         return cb(new Error('Not allowed by CORS'));
//     },
// }));

// Add res.error and res.done methods
app.use(addErrorAndDoneMethodsToExpressResponseObject);

// Ensure secret and origin custom headers are passed
// app.use(securityMiddleware);

app.use(compression());
app.use(express.json({ limit: '256mb' }));
app.use(express.urlencoded({ extended: true }));
app.use(helmet());

// API routes
app.use('/testing', TestingRouter);

// Handle errors in APIs
// Error handler must come after all other API routes! Do not place API routes under it!
app.use(expressErrorHandler);

export default app;
```

Socket.IO client version: `4.7.1`

*Client*

```ts
import { io } from 'socket.io-client';
import { API_ENDPOINT } from "./constants";

const socket = io(API_ENDPOINT);
socket.on('connect', () => {
  console.log('socket connected');
  socket.io.engine.on('upgrade', () => {
    console.log('socket conn upgraded!')
  });
  socket.io.engine.on('upgradeError', () => {
    console.log('socket conn upgrade ERROR!')
  });
})
```

**Expected behavior**
Sending HTTP request to server should reach controller once all the middlewares are passed - which is not the case here!

**Platform:**
 - Device: PC
 - OS: Windows 11 (with WSL for Redis)

**Additional context**
In another project we used similar setup (but with lower versions) and it worked just fine (since then this project was transferred to another dev team at our company, we don't know if it's still working), but we'll try to lower the versions here too and will write back if something changed).

**Comment by radanjovic** [comment]
Yup, downgrading socket.io to 4.5.1, @socket.io/sticky to 1.0.1, and @socket.io/cluster-adapter to 0.2.0 seems to have worked! I don't know which of these packages caused the troubles, but maybe you can check up what in the code of the newer versions could have prevented server from completing requests

**Comment by darrachequesne** [comment]
Hi! I'm digging into this. It looks like an issue with `@socket.io/sticky`.

**Comment by darrachequesne** [comment]
This should be fixed in `@socket.io/sticky@1.0.4`, could you please check?

**Comment by radanjovic** [comment]
> This should be fixed in `@socket.io/sticky@1.0.4`, could you please check?

Will try out as soon as I'm back at the office, probably later this week, or next week :)

**Comment by radanjovic** [comment]
Seems to be working fine now, will up the versions and keep testing as we develop, and should some problems arise we'll write to You, but for now, seems to be working fine :D
