### ISSUE TITLE
Type is not assignable to type Partial<ServerOptions>

### ISSUE THREAD

**Issue by johan-daniel** [socketio/socket.io#4800]
As the title implies it's happening when trying to initialize a ServerOptions object in TS.
I'm getting the following error 

```
Type '{ maxHttpBufferSize: number; cors: { origin: string; }; }' is not assignable to type 'Partial<ServerOptions>'.
  Object literal may only specify known properties, and 'maxHttpBufferSize' does not exist in type 'Partial<ServerOptions>'
```

Which I do not understand as I checked the definition files and it indeed exists.
I have the following code

Socket.io version 4.7.2
```js
import express from 'express';
import type * as http from 'http';
import { Server, type ServerOptions } from 'socket.io';

const app:Application = express();
const server:http.Server = app.listen(process.env.BACKEND_PORT);

const io_options: any = {
    maxHttpBufferSize: 1e8,
    cors: { origin: `http://127.0.0.1/${process.env.FRONTEND_PORT}`}
}

export const io:Server = new Server(server, io_options);
```

If I remove the "maxHttpBufferSize" attribute in the options I get the same error but with cors instead.

**Comment by faradaytrs** [comment]
I have the same problem, it happens when i switch to moduleResolution: bundler in my project, probably something wrong with exports field in package.json

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/engine.io/commit/c6bf8c0f571aad7a5917f43860c8c3d74a9b429b, included in `engine.io@6.5.3`.

Please reopen if needed.
