### ISSUE TITLE
Contributing to Open Source is something I am not familiar with, and I need a code of conduct or a CONTRIBUTING Readme with specifics.

### ISSUE THREAD

**Issue by darkb0ts** [socketio/socket.io#4814]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by darrachequesne** [comment]
We have added a contributing guide here: https://github.com/socketio/socket.io/blob/main/CONTRIBUTING.md

Please ping me if something is missing/not clear enough.

Have a great day!
