### ISSUE TITLE
'cors' does not exist in type 'Partial<ServerOptions>' (Reopening #4727)

### ISSUE THREAD

**Issue by jauco** [socketio/socket.io#4815]
**Describe the bug**
I want to add a cors option when constructing a new SocketIO server, but Typescript won't let me do that.

**To Reproduce**

Please fill the following code example:

Socket.IO server version: `4.7.2`

*Server*

```js
import { Server } from "socket.io";

const io = new Server(3000, {
    cors: {
      origin: "http://localhost:5173",
      methods: ["GET", "POST"]
    }
});
```

As copied from https://socket.io/docs/v3/handling-cors/#configuration

**Expected behavior**
No typescript error, and the client being able to connect

**Actual behavior**

The client can connect fine (previous edit where I thought it couldn't was due to me typing https instead of http in the origin url)

But typescript reports:
```
src/server/server.ts:4:3 - error TS2769: No overload matches this call.
  Overload 1 of 3, '(srv?: number | import("http").Server<...> | import("https").Server<...> | Http2SecureServer | undefined, opts?: Partial<...> | undefined): Server<...>', gave the following error.
    Argument of type '{ cors: { origin: string; methods: string[]; }; }' is not assignable to parameter of type 'Partial<ServerOptions>'.
      Object literal may only specify known properties, and 'cors' does not exist in type 'Partial<ServerOptions>'.
  Overload 2 of 3, '(srv: number | import("http").Server<...> | import("https").Server<...> | Http2SecureServer | Partial<...> | undefined, opts?: Partial<...> | undefined): Server<...>', gave the following error.
    Argument of type '{ cors: { origin: string; methods: string[]; }; }' is not assignable to parameter of type 'Partial<ServerOptions>'.
      Object literal may only specify known properties, and 'cors' does not exist in type 'Partial<ServerOptions>'.

4   cors: {
    ~~~~
```

**Additional context**
The reproduction attempt from #4727 at https://github.com/socketio/socket.io-fiddle/tree/typescript doesn't pass the cors option

**Comment by InanisOmnia** [comment]
I am having the same issue, with `cors` and similarly with `pingTimeout` and `pingInterval`

It appears to be a typings error

**Comment by darrachequesne** [comment]
Hi! I wasn't able to reproduce the issue: https://github.com/socketio/socket.io-fiddle/tree/issues/socket.io/4815

Could you please check?

**Comment by jauco** [comment]
Thanks for the repro. 

It is caused by adding `"moduleResolution": "bundler"` to the tsconfig. That causes the `import type { ServerOptions as EngineOptions, AttachOptions, BaseServer } from "engine.io";` to go to wrapper.mjs instead of engine.io.d.ts

given that it is config from my bundler I should be able to drop it for the server side code? But I'd need to read up on moduleresolution in typescript.

**Comment by darrachequesne** [comment]
Thanks, I was able to reproduce the issue.

I think this should be fixed by https://github.com/socketio/engine.io/commit/c6bf8c0f571aad7a5917f43860c8c3d74a9b429b, which is not released yet. I'll keep you updated.

> oh well, typescript and node... sigh... maybe I'll try deno again.

Yeah... :smile:

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/engine.io/commit/c6bf8c0f571aad7a5917f43860c8c3d74a9b429b, included in `engine.io@6.5.3`.

Please reopen if needed.
