### ISSUE TITLE
Memory leak issue on production.

### ISSUE THREAD

**Issue by prasann004** [socketio/socket.io#4822]
### Discussed in https://github.com/socketio/socket.io/discussions/4821

<div type='discussions-op-text'>

<sup>Originally posted by **prasann004** September  9, 2023</sup>
This is my server code. I have been facing memory leaks in production.
"socket.io": "2.2.0",
"socket.io-redis": "^5.2.0". 
I am relatively new to socket.io. Any suggestions get rid of this memory leak.

<img width="879" alt="SocketServer" src="https://github.com/socketio/socket.io/assets/47444136/e9bc6ed5-dbcf-470f-b1ba-5283dcaba7df">
<img width="1297" alt="CPU MemoryUtilisation" src="https://github.com/socketio/socket.io/assets/47444136/d7eb58e8-6848-4b3f-825b-47353a7f8baf">
</div>

**Comment by darrachequesne** [comment]
Let's continue the discussion here: https://github.com/socketio/socket.io/discussions/4821
