### ISSUE TITLE
ERR_QUIC_PROTOCOL_ERROR.QUIC_TLS_CERTIFICATE_UNKNOWN (TLS handshake failure (ENCRYPTION_HANDSHAKE) 46: certificate unknown).

### ISSUE THREAD

**Issue by JatosDetking** [socketio/socket.io#4832]
When I ran the server locally there was no problem. But after the deployment of ec2 it appeared and it no longer connects to web transport.

Failed to establish a connection to https://kldfglkdshgkdhfsk/socket.io/: net::ERR_QUIC_PROTOCOL_ERROR.QUIC_TLS_CERTIFICATE_UNKNOWN (TLS handshake failure (ENCRYPTION_HANDSHAKE) 46: certificate unknown).

I start my browser with this command
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --origin-to-force-quic-on=https://kldfglkdshgkdhfsk/ --ignore-certificate-errors-spki-list=rifgjkerwiogi9u0jfiojwod=

I have generated the certificates with
openssl req -new -x509 -nodes
-out cert.pem
-keyout key.pem
-newkey ec
-pkeyopt ec_paramgen_curve:prime256v1
-subj '/CN=0.0.0.0'
-days 14

**Comment by darrachequesne** [comment]
Let's continue the discussion here: https://github.com/socketio/socket.io/discussions/4831
