### ISSUE TITLE
TS2305: Module '"engine.io"' has no exported member 'BaseServer'.

### ISSUE THREAD

**Issue by chrisborecki** [socketio/socket.io#4840]
**Describe the bug**

Compilation error:

node_modules/socket.io/dist/index.d.ts:7:62 - error TS2305: Module '"engine.io"' has no exported member 'BaseServer'.

7 import type { ServerOptions as EngineOptions, AttachOptions, BaseServer } from "engine.io";
                                                               ~~~~~~~~~~

Found 1 error in node_modules/socket.io/dist/index.d.ts:7




**To Reproduce**

package.json:
    "type": "module",
    "devDependencies": {
        "@types/engine.io": "^3.1.8",
    },
    "dependencies": {
        "socket.io": "^4.7.2"
    }

tsconfig.json:

    "compilerOptions": {
      "target": "ESNext",
      "module": "ESNext",
      "moduleResolution": "Bundler",
     "esModuleInterop": true


**Expected behavior**
Compile successfull

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/engine.io/commit/c6bf8c0f571aad7a5917f43860c8c3d74a9b429b, included in `engine.io@6.5.3`.

Could you please try by upgrading `engine.io` and removing `@types/engine.io` (which are not needed since the `engine.io` already provides its own types)?
