### ISSUE TITLE
Responses should have Cache-Control header to avoid being cached by public Caches / CDNs

### ISSUE THREAD

**Issue by Frank683** [socketio/socket.io#4842]
**Describe the bug**

Our web application is running on Microsoft Azure App Service and is published through Azure Frontdoor which is a CDN which 
caches all responses to GET requestes which are deemed as "cacheable".

https://learn.microsoft.com/en-us/azure/frontdoor/front-door-caching?pivots=front-door-standard-premium#cache-expiration

![image](https://github.com/socketio/socket.io/assets/14088575/4e5aa986-2e5f-4d10-8cae-8c691b1976ee)

The server response to the a client's first request which returns the sid to be used for all subsequent requests does not have Cache-Control headers and so the reponse gets cached by Frontdoor CDN which will result in other users receiving this cached response instead of a "fresh" one. 

![image](https://github.com/socketio/socket.io/assets/14088575/92e5c123-6ec8-4079-af18-edb35f351a43)

The subsequent request uses the session ID from the cached response which probably belonged to another user and might not be valid anymore:

![image](https://github.com/socketio/socket.io/assets/14088575/26f80ac2-7afc-40b4-8374-e57d29192bab)

**To Reproduce**

Socket.IO server version: `4.4.1`

*Server*

```js
  let server = http.createServer(app);
  let socketio = SocketIO(server);

  // General server listening
  server.listen(config.server.port, function () {
      logger.info('Express server listening on port ' + server.address().port);
  });

  socketio.on('connection', function (socket) {
        logger.debug('Client with SocketId [%s] connected ...', socket.id);
  });
```

Socket.IO client version: `4.4.1`

*Client*

```js
initSocket: function (oController) {
        if (!this.oSocket) {
          this.oSocket = io();

          this.oSocket.on('myevent', function (oData) {
            var oReceived = JSON.parse(oData);

            // Do something with the data....
        }
      },
```

**Expected behavior**
Every response should have http header

Cache-Control: no-store, no-cache

**Platform:**
 - Device: PC
 - OS: Windows 10

**Additional context**

**Comment by darrachequesne** [comment]
Hi! That's weird, the `t` query parameter is added exactly for this purpose, to prevent any cache from happening.

Are you using the "Ignore Query String" mode?

> In this mode, Azure Front Door passes the query strings from the client to the origin on the first request and caches the asset. Future requests for the asset that are served from the Front Door environment ignore the query strings until the cached asset expires.

**Comment by darrachequesne** [comment]
Done! Implemented in https://github.com/socketio/engine.io/commit/9545b44b3cccc1e2ff51c126d0d759571e22b3a6 and included in `engine.io@6.5.3`.
