### ISSUE TITLE
Remove node-redis from documentation

### ISSUE THREAD

**Issue by nwalters512** [socketio/socket.io#4845]
My team runs multiple servers and uses https://github.com/socketio/socket.io-redis-adapter to ensure messages can be delivered to all clients, no matter which server they're actually connected to. Recently, we got reports from users that updates were *not* in fact being delivered successfully to clients. After a solid day of debugging, we discovered that our Redis clients were unexpectedly disconnecting from the Redis server. We use [`node-redis`](https://github.com/redis/node-redis) as our Redis client, and by default it should reconnect to the Redis server. It was in fact reconnecting, but after reconnecting, it failed to re-establish the subscription.

This appears to be a well-documented problem with `node-redis` specifically:

- https://github.com/redis/node-redis/issues/2155
- https://github.com/redis/node-redis/issues/1252

Other folks have moved off `node-redis` to [`ioredis`](https://github.com/redis/ioredis) because of this (see https://github.com/mastodon/mastodon/issues/25157). `ioredis` [explicitly documents](https://github.com/redis/ioredis#auto-reconnect) that they restore subscriptions after reconnecting:

> When reconnected, the client will auto subscribe to channels that the previous connection subscribed to.

Given that socket.io's Redis adapter relies almost exclusively on pub/sub capabilities of Redis clients, I'd like to propose that `socket.io` remove `node-redis` from its documentation in favor of recommending just `ioredis`. At the very least, a warning about this issue with `node-redis` should be added.

For reference, here's where this is currently documented: https://socket.io/docs/v4/redis-adapter/.

Perhaps I should have filed this in https://github.com/socketio/socket.io-website. Let me know if that's the case and I can move the issue there.

**Comment by darrachequesne** [comment]
Hi! Thanks for the heads-up :+1: 

I've added a note in the documentation: https://socket.io/docs/v4/redis-adapter/#with-the-redis-package
