### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by zbw-zbw** [socketio/socket.io#4848]
**Describe the bug**

var socketio = require("socket.io");

<img width="897" alt="image" src="https://github.com/socketio/socket.io/assets/64134946/d3881921-f833-4444-a1ef-96df01055eaf">

**Platform:**
 - Device: Mac
 - OS: M1

**Additional context**

**Comment by darrachequesne** [comment]
Hi! May I ask which version of `socket.io` you are using? The `lib/store.js` file did exist in version [0.9.x](https://github.com/socketio/socket.io/tree/0.9.x/lib), but this is a reaaaally old release.

**Comment by zbw-zbw** [comment]
> Hi! May I ask which version of `socket.io` you are using? The `lib/store.js` file did exist in version [0.9.x](https://github.com/socketio/socket.io/tree/0.9.x/lib), but this is a reaaaally old release.

0.9.6

**Comment by zbw-zbw** [comment]
> Any reason you are using this release (released in 2013)? The 0.9.x branch is no longer active nor supported.

demo from a nodejs book, maybe i should update the latest version？

**Comment by darrachequesne** [comment]
Yes, using the latest version is recommended :+1: 

Please ping me if you run into any error.

**Comment by zbw-zbw** [comment]
> Yes, using the latest version is recommended 👍
> 
> Please ping me if you run into any error.

ok, thanks.
