### ISSUE TITLE
io.connect is connecting too many times

### ISSUE THREAD

**Issue by lahin31** [socketio/socket.io#4849]
**Describe the bug**
I am creating a socket connection with socket.io version 4.6.1, I am not using any frontend (just added the cors attribute) but I start my server I am seeing count value is incrementing by 1 around 30 times. 

*Server*

```js
import { Server } from "socket.io";

const server = require("http").createServer(app);

connectToSocket(server);

const connectToSocket = (server) => {
  const io = new Server(server, {
    cors: {
      origin: [
        "http://localhost:5173",
        "http://localhost:3000",
      ],
      methods: ["GET", "POST"],
    },
    reconnection: false, // Disable reconnection
    reconnectionAttempts: 0, // Do not attempt any reconnections
  });
  let count = 0;
  io.on("connect", (socket) => {
    count++;
    console.log(count);
  })
})
```

**Expected behavior**
Since I am not connecting to frontend, the count value shouldn't be that much.

**Platform:**
 - Node: 16.19

**Comment by darrachequesne** [comment]
Hi! That's weird, are you sure you don't have any client connected? You can log the HTTP headers with:

```js
// "connect" is a deprecated alias of "connection"
io.on("connection", (socket) => {
  count++;
  console.log(socket.request.headers);
});
```

**Comment by lahin31** [comment]
Is that coming from cache or something? since my client server is off. I am not doing anything in `socket.on("disconnect", () => {})`

<img width="721" alt="Screenshot 2023-10-11 at 9 19 21 PM" src="https://github.com/socketio/socket.io/assets/12637865/e8b21276-0dae-4d41-b133-4320f922fff3">

**Comment by darrachequesne** [comment]
Hmm... it seems you have a client running somewhere. Were you able to find the culprit?

**Comment by lahin31** [comment]
Yes if I use 
```
socket.on("disconnect", () => {
  socket.leave(socket.id);
});
```
I see one client connected which is expected, but i am seeing this object couple of time

<img width="967" alt="Screenshot 2023-10-14 at 12 03 31 AM" src="https://github.com/socketio/socket.io/assets/12637865/a24f2701-3291-4bb2-a0bb-21cf64706471">

**Comment by lahin31** [comment]
host is 4000 every time. strange isn't it?

**Comment by darrachequesne** [comment]
Do you decrease the `count` upon disconnection? Something like this:

```js
io.on("connection", (socket) => {
  count++;
  socket.on("disconnect, () => {
    count--;
  });
});
```

Anyway, I don't think there is something to fix here. Please reopen if needed.
