### ISSUE TITLE
Cannot gracefully shut down when using uWebSockets.js

### ISSUE THREAD

**Issue by ksa-real** [socketio/socket.io#4852]
**Describe the bug**
I'd like to implement graceful shutdown of the server. Below there are two snippets: one that uses express and one using uWebSockets.js. The first one closes gracefully, the second one doesn't, as if something is holding node's event queue. Packages like `why-is-node-running` or `wtfnode` report nothing. The ask is to figure out if socket.io doesn't do uWebSockets App instance shutdown correctly. Another option is that the issue is in uWebockets.js itself. 

**To Reproduce**

Please fill the following code example:

Socket.IO server version: `4.7.2`. Same for previous versions.
NodeJS: 16.20.2, 20.8.1

*Server*

File `test-express.js`:
```js
import { Server } from 'socket.io';
import express from 'express';
import http from 'http';
import { setTimeout as setAsyncTimeout } from 'timers/promises';

const port = 3001;

const test = async () => {
  const app = http.Server(express());
  const io = new Server(app, {
      transports: ['websocket'],
      maxHttpBufferSize: 10 * 1024 * 1024,
      allowEIO3: true,
    });
  app.listen(port, listenSocket => {
    if (listenSocket) {
      console.log(`SocketIO server is listening on port ${port}`);
    } else {
      console.error(`Port ${port} is already in use`);
    }
  });

  await setAsyncTimeout(1000);

  // Shutdown
  io.close(err => {
    console.log('Server closed');
  });
}

void test();
```
Run `npx babel-node test-express.js`
The process exits as expected.

File `test-uws.js`:
```js
import { Server } from 'socket.io';
import { App } from 'uWebSockets.js';
import { setTimeout as setAsyncTimeout } from 'timers/promises';

const port = 3001;

const test = async () => {
  const app = new App();
  const io = new Server({
      transports: ['websocket'],
      maxHttpBufferSize: 10 * 1024 * 1024,
      allowEIO3: true,
    });
  io.attachApp(app);
  app.listen(port, listenSocket => {
    if (listenSocket) {
      console.log(`SocketIO server is listening on port ${port}`);
    } else {
      console.error(`Port ${port} is already in use`);
    }
  });

  await setAsyncTimeout(1000);

  // Shutdown
  io.close(err => {
    console.log('Server closed');
  });
}

void test();
```
Run `npx babel-node test-uws.js`

The process doesn't exit until Ctrl-C is pressed.

**Expected behavior**
The app should exit right after printing `Server closed`

**Platform:**
 - Server
 - OS: Any: Linux/MacOS

**Additional context**

**Comment by darrachequesne** [comment]
Hi! You need to use the `us_listen_socket_close()` method:

```js
import { App, us_listen_socket_close } from "uWebSockets.js";

const app = App();

app.listen(0, (listenSocket) => {
  // ...

  us_listen_socket_close(listenSocket);
});
```

This is what we use in our tests here: https://github.com/socketio/socket.io/blob/9a2a83fdd42faa840d4f11fd223349e5d8e4d52c/test/uws.ts#L63

Please reopen if needed.
