### ISSUE TITLE
Incorrect Types for Client Initialisation

### ISSUE THREAD

**Issue by piet-maier** [socketio/socket.io#4873]
### Description

Initialising the socket.io client with an URL string or `undefined` depending on the environment (as in the [Vue Example](https://socket.io/how-to/use-with-vue) in the documentation) produces the following type error: "No overload matches this call."

It is possible to either pass a string or undefined in separate calls, but not a value that has the type `string | undefined` in one call.

### Reproduction

**Client Version:** `4.7.2`

```js
import { io } from "socket.io-client";

const socket = io(import.meta.env.PROD ? undefined : "ws://localhost:3000/");
```

### Expected Behaviour

There should not be a type error since the argument can be of either type, and the code works as expected.

**Comment by darrachequesne** [comment]
I could indeed reproduce the issue, I'm digging into this.

**Comment by darrachequesne** [comment]
For future readers:

This should be fixed in latest version (`socket.io-client@4.8.0`).
