### ISSUE TITLE
socket.id can be undefined according to the docs, but cannot according to the type

### ISSUE THREAD

**Issue by KleaTech** [socketio/socket.io#4884]
**Describe the bug**
`socket.id` can be undefined according to the documentation (until connect event is triggered). But the `Socket` type does not mark it as possibly undefined.

**To Reproduce**
Check the documentation:
![image](https://github.com/socketio/socket.io/assets/24510869/edbf7644-38ce-492f-8a1b-ad40341d9f82)
Check the code:
https://github.com/socketio/socket.io/blob/8c9ebc30e5452ff9381af5d79f547394fa55633c/lib/socket.ts#L192
And:
https://github.com/socketio/socket.io-adapter/blob/28f60b880ad04ff4b48ade0cd529f1970643604f/lib/index.ts#L10

Socket.IO client version: `4.7.2`

**Expected behavior**
Either the Socket or SocketId type should allow undefined values or the documentation should be clarified.

**Comment by darrachequesne** [comment]
The `id` attribute on the client side is now typed as `string | undefined`: https://github.com/socketio/socket.io-client/commit/f9c16f226512fc8a8df461e3a07e392720462165

On the server side, it cannot be `undefined`: https://github.com/socketio/socket.io/blob/6ab2509d529d438e25b6c3a701444aa6585fa153/lib/socket.ts#L192

Thanks for the heads-up! :+1:
