### ISSUE TITLE
Cannot read properties of undefined (reading 'use')

### ISSUE THREAD

**Issue by ziyaDev** [socketio/socket.io#4887]
**Describe the bug**
im trying to using express-session on socket.io (nestjs) so find in the docs  [How to use with express-session](https://socket.io/how-to/use-with-express-session), there's an example that suggests to use express middleware with io.engine.use, i get this err
![Screenshot from 2023-11-30 19-22-07](https://github.com/socketio/socket.io/assets/125736719/22c98df7-95ae-4519-9cfd-a256938a340d)

**Server:**
```typescript

@WebSocketGateway({
  cors: {
    credentials: true,
    origin: [ '*'']
  },
})
export class MessagesGateway implements OnGatewayConnection  , OnGatewayDisconnect {
  @WebSocketServer() io: Server = new Server({
    cookie:true
  })
  constructor(private readonly messagesService: MessagesService) {     
    this.io.engine.use(expressSession)
  }
```
**epxress-session middlware:**

```typescript
 const expressSession  =   session({
      name: envServer.SESSION_NAME,
      secret: envServer.SESSION_SECRET,
      resave: true,
      unset: 'destroy',
      saveUninitialized: false,
      cookie: {
        secure: process.env.NODE_ENV === 'production',
        httpOnly: false, 
        sameSite: 'strict',
        maxAge: ms('120 days'),
      },
      store: redisStore,
    })
```
No Typescript issues.

**Platform:**

- Device: lenovo thinkBook i5 --10gen
-  OS: KaliLinux

**Comment by darrachequesne** [comment]
`io.engine.use()` was added in `engine.io@6.4.0` and `socket.io@4.6.0`.

Could you please check your `socket.io` version?

Reference: https://socket.io/docs/v4/server-api/#engineusemiddleware

**Comment by ziyaDev** [comment]
> `io.engine.use()` was added in `engine.io@6.4.0` and `socket.io@4.6.0`.
> 
> Could you please check your `socket.io` version?
> 
> Reference: https://socket.io/docs/v4/server-api/#engineusemiddleware

Thank you, I wasn't use the right version yeah
