### ISSUE TITLE
Connection State Recovery does not work until receiving a message

### ISSUE THREAD

**Issue by rikuson** [socketio/socket.io#4888]
**Describe the bug**

socket.io-client sends `offset` when it reconnects based on `lastOffset` .

https://github.com/socketio/socket.io-client/blob/b3f0cab1a0dc101a8aa6a23dc779758019b38a23/lib/socket.ts#L618

`lastOffset` is set when the client receives message.

https://github.com/socketio/socket.io-client/blob/b3f0cab1a0dc101a8aa6a23dc779758019b38a23/lib/socket.ts#L732

If the client has not received message, `offset` is undefined.

socket.io does type-check for `offset` if it's string or not before triggering `this.adapter.restoreSession` .

https://github.com/socketio/socket.io/blob/8c9ebc30e5452ff9381af5d79f547394fa55633c/lib/namespace.ts#L370

Then Connection State Recovery fails.

**To Reproduce**

[This](https://github.com/rikuson/socket.io-k8s-example/tree/21136242000b95966fbf452ff1310365d07439e1) white-board example saves color state on server.

https://github.com/socketio/socket.io/assets/11563968/f272c6d2-9e51-4b9c-912b-1507bf3cb7b6

1. Client A joins the room
2. Client A update color and save state
3. Client B joins the room
4. Client B update color and save state
5. Client A sends messages by rendering on canvas
6. Do rolling-update

Then Connection State Recovery fails on Client A side, and gets back to initial color.
Client B is successfully recovered and keeps color.

**Expected behavior**

Then Connection State Recovery succeed on Client A side, and keeps color.

**Additional context**

Workaround for this issue is sending any message on connection like [this](https://github.com/rikuson/socket.io-k8s-example/blob/f8517c7bbf3e2d163cc2bbc40a353c5090559bfc/backend/index.js#L20).

**Comment by palash018** [comment]
can you demonstrate what happens with multiple clients?

**Comment by darrachequesne** [comment]
Yes, the client must indeed receive at least one message for the connection state recovery to succeed.

This was implemented like this so we don't have to query the underlying database to fetch the last offset upon connection.

**Comment by christopherreay** [comment]
Because for zoomed out view of socket.io, where it may be running over a large cluster of reddis or mongo or whatever, the cost of a database lookup is a poor choice.

> Why don't you query to fetch the last offset?
The obvious answer to this seems to be "why dont you just send a message to the client on connecting"

**Comment by rikuson** [comment]
Thanks, I understood.
