### ISSUE TITLE
[Bug] Delay with retries config

### ISSUE THREAD

**Issue by anhnhoktvn** [socketio/socket.io#4897]
**Describe the bug**
it seems that code run synchronize  with retries config.
with the below code, the console log first line then wait some seconds and log 2nd line

**To Reproduce**

Please fill the following code example:

Socket.IO server version: `x.y.z`

*Server*

```js
const express = require('express')
const app = express()
const server = require('http').createServer(app)
const io = require('socket.io')(server)
const port = process.env.PORT || 3004

app.use(express.static(__dirname + '/public'))

io.on('connect', onConnect)
server.listen(port, () => console.log('server listening on port ' + port))

function onConnect(socket) {
  console.log('connect ' + socket.id)

  socket.on('disconnect', () => console.log('disconnect ' + socket.id))
  socket.on('echoSleep', (data, callback) => {
    setTimeout(() => {
      callback(data)
    }, 1000)
  })
}

```

Socket.IO client version: `x.y.z`
    "socket.io": "^4.7.2",
    "socket.io-client": "^4.7.2",
    
*Client*

```js
const socket = require('socket.io-client')('http://localhost:3004', {
  retries: 10, // <-- comment or remove to see the difference
})
;(function () {
  socket.on('connect', onConnect)

  async function onConnect() {
    console.log('connect ' + socket.id)
    let ok
    ;(async function () {
      let ok = await socket.emitWithAck('echoSleep', Date.now())
      console.log(ok)
    })()
    ;(async function () {
      let ok = await socket.emitWithAck('echoSleep', Date.now())
      console.log(ok)
    })()
  }
})()
```

**Expected behavior**
run async

**Platform:**
Nodejs 
**Additional context**

**Comment by darrachequesne** [comment]
Hi! Yes, it's expected. When retries are enabled, the client will wait for the acknowledgement of an event before sending the next (in order to ensure the event order), hence the delay.

**Comment by anhnhoktvn** [comment]
I think it should be mention in document. Will save some time to figure out this.
 A better way is make it async with a uid/uuid (just my thinking)...
