### ISSUE TITLE
Socket authentication seems to be bypassed when using ws client.

### ISSUE THREAD

**Issue by prabhat24** [socketio/socket.io#4899]
**Describe the bug**
I have implemented socket.io authentication using middleware described https://socket.io/docs/v4/middlewares/.  Authentication middleware works properly for my socket.io server, ensuring that proper credentials are required for authentication only when using socket.io client library. However, when using a different WebSocket client, specifically the ws library or a WebSocket client in Postman, authentication appears to be bypassed, and connections are established without the expected credential validation.

**To Reproduce**
Socket.IO server version: `4.7.2`

*Server*

```js
const express = require("express");
const cookieParser = require('cookie-parser')
const { Server } = require("socket.io");
const helmet = require("helmet");
const {createAdapter} = require("@socket.io/redis-adapter");
const {createRedisClient} = require("./controllers/redisClient");
const {corsConfig } = require("./controllers/serverMiddlewares");

// authWrapper

function authWrapper(redisClient){
    async function authMiddleware(socket, next){
        let success = false
        try{
            await authenticate(socket, redisClient)
            success = true
        }
        catch (error){
            console.error('Authentication failed:', error.message);

            success = false
            next(error)
        }
        if (success){
            next()
        }
    }
    return authMiddleware
}

async function authenticate(socket, redisClient){
    throw new Error("Please login to continue")
}

(async() => {
    const redisClient = await createRedisClient()
    const subClient = redisClient.duplicate()
    const app = express();
    app.use(cookieParser())
    const server = require("http").createServer(app);
    let socketPath = "/socket.io"
    let applicationPort = process.env.APP_PORT
    console.log("CUSTOM SOCKET PATH ", socketPath)
    
    const io = new Server(server, {
      cors: corsConfig,
      transports: ["websocket"],
      path: socketPath
    });
    app.use(express.json());
    io.adapter(createAdapter(redisClient, subClient));
    const authMiddleware = authWrapper(redisClient)
    io.of("/").use(authMiddleware)

    io.on("connect", async (socket) => {
    
        socket.on("msg", data => {
            console.log(`${socket.id} sent message`, data)
        });
    })
    server.listen(applicationPort, () => {
        console.log("Server listening on port ", applicationPort);
    });
})()

```
*Client*
on client side I am using postman's ws client to hit my server also can be replicated using the node.js script below. Node js script shows connection was established.

```
const WebSocket = require('ws');
const ws = new WebSocket('ws://localhost:8000/socket.io/?EIO=4&transport=websocket');
ws.on('open', () => {
    console.log('Connected to WebSocket server');
  
    // Sending a message to the server after connection
    // ws.send('Hello, server!');
  });
```

**Expected behavior**
No WebSocket client should be able to establish a connection with the Socket.IO server unless it undergoes proper authentication, and it must not bypass any authentication middleware.

**Platform:**
Though I feel this is device independent. Adding details just for additional context.
 - Device: device Mac book pro 13-inch, 2018
 - OS: mac os ventura 13.4 (22F66)

**Comment by darrachequesne** [comment]
Hi! That's because the Socket.IO middlewares are not applied during the WebSocket upgrade, but later.

Starting with version `4.6.0`, you can now use low-level middlewares:

```js
io.engine.use((req, res, next) => {
  // do something

  next();
});
```

Which will prevent the WebSocket connection if the middleware fails (but you don't have access to the `auth` attribute, only request headers).

Reference: https://socket.io/docs/v4/server-api/#engineusemiddleware

**Comment by darrachequesne** [comment]
I think this can be closed now. Please reopen if needed.

Reference: https://socket.io/docs/v4/middlewares/#compatibility-with-express-middleware

**Comment by ebwood** [comment]
> Hi! That's because the Socket.IO middlewares are not applied during the WebSocket upgrade, but later.
> 
> Starting with version `4.6.0`, you can now use low-level middlewares:
> 
> ```js
> io.engine.use((req, res, next) => {
>   // do something
> 
>   next();
> });
> ```
> 
> Which will prevent the WebSocket connection if the middleware fails (but you don't have access to the `auth` attribute, only request headers).
> 
> Reference: [socket.io/docs/v4/server-api/#engineusemiddleware](https://socket.io/docs/v4/server-api/#engineusemiddleware)

@darrachequesne Then how to get error additional details with io.engine.use middleware? 
``` js
// server
io.engine.use((req, res, next) => {
  const error = new Error('auth error');
  error.data = { content: 'no token'};
  next(error);
});

// client
socket.on('connect_error', (err) => {
	console.log(err.data);
});
```
the output of err.data is undefined.
