### ISSUE TITLE
jwt authentication needed

### ISSUE THREAD

**Issue by abhanan369** [socketio/socket.io#4910]
really need jwt authentication example, and show how express request can pass auth token to socket

**Comment by darrachequesne** [comment]
Hi! You mean, with [passport-jwt](https://www.passportjs.org/packages/passport-jwt/) for example?

**Comment by abhanan369** [comment]
Yes, that would help alot

**Comment by darrachequesne** [comment]
I've added an example here: https://github.com/socketio/socket.io/tree/main/examples/passport-jwt-example

@abhanan369 could you please check if everything is clear enough?

**Comment by abhanan369** [comment]
Thank you @darrachequesne, this helps alot. ✌️

**Comment by darrachequesne** [comment]
Awesome, thanks for the feedback.

I've added the example here: https://socket.io/how-to/use-with-jwt
