### ISSUE TITLE
Sending one message more than one time after network disconnections and reconnects.

### ISSUE THREAD

**Issue by alishkaahmadov** [socketio/socket.io#4919]
**Describe the bug**
When my network gone and it reconnected after second, socket.io disconnects all my users(sockets) and reconnects them with new id back. But it send 1 message twice when this happens. I checked in my terminal and everything ok with sockets so there's only 1 socket remaining after reconnection.

I am using Node js as a backend and Nuxt Js for the frontend.

Socket.IO server version: `^4.7.2`

Socket.IO client version: `^4.7.2`

**Comment by darrachequesne** [comment]
Hi!

Usually, this means you are registering the event listeners in the `connect` handler:

```js
socket.on("connect", () => {
  socket.on("data", () => { /* ... */ });
});
```

It should instead be:

```js
socket.on("connect", () => {
  // ...
});

socket.on("data", () => { /* ... */ });
```

Could you please check?

**Comment by alishkaahmadov** [comment]
Hello, thanks for your answer! Here's a little part of my code, you are right I am using events in connection, but I am getting socket in `io.of("/join-room").on('connection', (**socket**)` this section. How can I access socket outside then?

```
io.of("/join-room").on('connection', (socket) => {
    console.log('A client has connected', socket.id);
    
      socket.on('leave-room', async ({roomId}) => {
            ...
      })
      // and so on
});
```

**Comment by alishkaahmadov** [comment]
Hello, thanks for your answer. Yeah you're right, I declared my events inside my connection. But when I removed them outside it didn't work. In my case point was keeping my emits on connection (because I authorize my clients on backend) and removing listening events outside. It worked for me :)
