### ISSUE TITLE
If the server's upstream bandwidth is used up, it will generate a large number of pingTimeoutTimers, which in turn will cause memory leaks

### ISSUE THREAD

**Issue by introspection3** [socketio/socket.io#4937]
**Describe the bug**
If the server's upstream bandwidth is used up, it will generate a large number of pingTimeoutTimers, which in turn will cause memory leaks

**To Reproduce**

If the server's upstream bandwidth is used up, it will generate a large number of pingTimeoutTimers,

Socket.IO server version: 4.5
 
![image](https://github.com/socketio/socket.io/assets/12368358/d226aff5-3a82-4ecb-8216-6f895b8b3ee3)

**Expected behavior**
work

**Platform:** debian
 - Device: [e.g. Samsung S8]
 - OS: [e.g. Android 9.2] debian

**Additional context**

**Comment by darrachequesne** [comment]
When the bandwidth is used up, I think that the heartbeat mechanism will fail and the connections will be closed with the reason "ping timeout", and then everything should be properly garbage collected. Isn't that what you are experiencing?

Reference: https://nodejs.org/en/guides/diagnostics/memory/

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
