### ISSUE TITLE
🐛 Error in serving socket.io.min.js

### ISSUE THREAD

**Issue by RutvikChandla** [socketio/socket.io#4946]
**Describe the bug**
https://github.com/socketio/socket.io/blob/e36062ca2df0b1a4adcf986bafc3fd92675d3896/lib/index.ts#L625-L643

While serving assets and encoding is 'br' there is a race condition, seeing code we are piping 2 times. Should be only 1 time
```js
        readStream.pipe(createBrotliCompress()).pipe(res);
        pipeline(readStream, createBrotliCompress(), res, onError);
```

below is the error I'm getting below error when serving /socket.io.min.js
```
error Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.<anonymous> (node:internal/streams/pipeline:352:14)
    at ServerResponse.emit (node:events:525:35)
    at ServerResponse.emit (node:domain:489:12)
    at emitCloseNT (node:_http_server:961:10)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
```

**To Reproduce**

When browser uses `br` as accept encoding to download files added in <script src=""> 
Getting the above error.

**Expected behavior**

**Platform:**
 - Device: [e.g. Samsung S8]
 - OS: [e.g. Android 9.2]

**Comment by darrachequesne** [comment]
Good catch, thanks!

This should be fixed by https://github.com/socketio/socket.io/commit/e426f3e8e1bfea5720c32d30a3663303200ee6ad.
