### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by zhuizhubf** [socketio/socket.io#4949]
**Describe the bug**
new vite ts project
browser-external:path:9  Module "path" has been externalized for browser compatibility. Cannot access "path.extname" in client code.
Uncaught ReferenceError: Buffer is not defined

**To Reproduce**

package.json
```
  "dependencies": {
    "socket.io": "^4.7.4",
    "vue": "^3.2.41"
  },
```
import { createServer } from "http";
import { Server } from "socket.io";

const httpServer = createServer();
const io = new Server(httpServer, {
  cors: {
    origin: "https://example.com"
  }
});

**Comment by jokester** [comment]
`Buffer` should be available in node.js. Could it be the case that, you were trying to run socket.io *server* code in browser?

**Comment by zhuizhubf** [comment]
Okay, I understand
