### ISSUE TITLE
emitWithAck does not throw on disconnect

### ISSUE THREAD

**Issue by jd1378** [socketio/socket.io#4964]
**Describe the bug**
Take the following steps:
- put browser into offline mode
- use `emitWithAck` to send a message immediately
- expect `emitWithAck` to throw on disconnect, but it does not 
- put browser into online mode and reconnect. 
- `emitWithAck` still not resolving.

**To Reproduce**

Socket.IO client and server version: `4.7.4`

I used the socket.io chat example to make a reproduction repo: 
https://github.com/jd1378/socketio-emit-ack-bug

**Expected behavior**

I expect the `emitWithAck` to throw once the socket is disconnected. OR, I expect `emitWithAck` to retry the request, as it's not volatile.

**Platform:** 
 - Windows 10, Edge browser

**Additional context**

What's even better than the expected behavior? a new option to control the behavior.

what I really want is to be able to detect the failure of my requests and throw, much like how a fetch request would throw if connection fails. and I don't want to retry the request automatically when it's thrown.

**Comment by darrachequesne** [comment]
I could indeed reproduce, thanks for the test case. I'm digging into this.

Related: https://github.com/socketio/socket.io-client/issues/1546

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-client/commit/34cbfbb532ae333f4dd034138e8f87cb80a8e382, included in version [4.7.5](https://github.com/socketio/socket.io-client/releases/tag/4.7.5).

@jd1378 could you please check?

**Comment by wilywork** [comment]
hi @darrachequesne , this line is really necessary? 
https://github.com/socketio/socket.io-client/commit/34cbfbb532ae333f4dd034138e8f87cb80a8e382#diff-f0e64910289a49966c99ceadaa5637404e3439ec0812a4bdb7003fe1e5a33d1cR693

If there is an active ack regardless of whether it has a timeout or not, it should be rejected, correct?

**Comment by darrachequesne** [comment]
@wilywork hi! Yes, I think this is necessary, as the callback does not expect an Error argument:

```js
socket.emit("hello", (returnValue) => {
  // 'returnValue' would be an Error object, which is unexpected
});
```

What do you think?
