### ISSUE TITLE
Connection recovery doesn't work

### ISSUE THREAD

**Issue by DEgITx** [socketio/socket.io#4968]
**Describe the bug**
I've trying recovery feature from 4.6.x. (Both client and server 4.7.4 version). But seems it's doesn't work.

**Communication log**
I see in log:
  socket.io:socket closing socket - reason transport close +17s
  **socket.io:socket connection state recovery is enabled for sid zytzW7DNegRiL-66AAAB +0ms**

I see that state saved for recovery. But no reconnection happens, socket.recovered = false and messages missed anyway.

But during reconnection I see:
  engine handshaking client "fVbuYx7fom17T3a2AAAD" +0ms
  engine:socket readyState updated from opening to open +22s
  engine:socket sending packet "open" ({"sid":"fVbuYx7fom17T3a2AAAD","upgrades":["websocket"],"pingInterval":25000,"pingTimeout"
:20000,"maxPayload":52428800}) +0ms
...
  engine setting new request for existing client +0ms
  engine:polling received "40{"pid":"WoNvf_UeVOpy0UOpAAAC"}" +6ms

**To Reproduce**

Socket.IO server version: `4.7.4`
Socket.IO client version: `4.7.4`

1. Create socket.io server with connectionStateRecovery: {}
2. Establish connection
3. Use Chrome network throttling - set offline for page to 10 sec on client side
4. send message on server side while disconnected
5. reestablish connection with Chrome network throttling - connection established with socket.recovered = false. No recovery happend. No missed messages sended from server side to client.

**Expected**
1. socket.recovered must be true, connection recoveried, missed events must be sended.

Recovery must triggered

*Server*

```js
const io = new Server(server, { 
    maxHttpBufferSize: 50 * 1024 * 1024,
    connectionStateRecovery: {
        maxDisconnectionDuration: 2 * 60 * 1000
    }
});
```

Socket.IO client version: `x.y.z`

*Client*

```js
const socket = io();
```

**Platform:**
 - Device: Chrome 122, nodejs 20

**Additional:**
Is client must send something like with offset header ?
40{"pid":"YHcX2sdAF1z452-HAAAW","offset":"MzUPkW0"}

I don't see anything like this in the server log.

instead of this I see
engine:polling received "40{"pid":"WoNvf_UeVOpy0UOpAAAC"}" +6ms

**Comment by DEgITx** [comment]
I found out the reason, the reason on client side that 

_lastOffset is null by default until it resive first message message with emitEvent()

but in case no messages haven't received yet  _lastOffset is set to null, and by logic on server side connection will not recover without offset. 

I think this must be fixed otherwise if first message(s) sended during dissconnected state recovery will not trigger and messages will be lost, until than it can simply overcome with

```
io.on('connection', (socket) => {
    // force init _lastOffset on client side
    socket.emit('dummy', {});
});
``

**Comment by darrachequesne** [comment]
Hi! The server indeed needs to send at least one packet, in order to initialize the offset on the client side. The last offset is not fetched upon connection, in order to reduce the load on the underlying database.

Reference: https://socket.io/docs/v4/connection-state-recovery#how-it-works-under-the-hood
