### ISSUE TITLE
this.children is undefined for ParentBroadcastAdapter broadcast

### ISSUE THREAD

**Issue by charliegracie** [socketio/socket.io#4985]
I am getting an error in my application after moving up to version `4.7.5`. When I run with previous versions, including `4.7.4`, everything works properly. The error I receive is:
```
node_modules/socket.io/dist/parent-namespace.js:88
        this.children.forEach((nsp) => {
                      ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at ParentBroadcastAdapter.broadcast (node_modules/socket.io/dist/parent-namespace.js:88:23)
    at BroadcastOperator.emit (node_modules/socket.io/dist/broadcast-operator.js:169:26)
    at Socket.<anonymous> (server.js:60:33)
    at Socket.emit (node:events:520:28)
    at Socket.emitReserved (node_modules/socket.io/dist/typed-events.js:56:22)
    at Socket._onclose (node_modules/socket.io/dist/socket.js:547:14)
    at Client.onclose (node_modules/socket.io/dist/client.js:247:20)
    at Socket.emit (node:events:532:35)
    at Socket.onClose (node_modules/engine.io/build/socket.js:304:18)
    at Object.onceWrapper (node:events:639:28)
```

When the following code was added in [PR 4950](https://github.com/socketio/socket.io/pull/4950) it appears that the code forgot to store or copy the `children` parameter.
https://github.com/socketio/socket.io/blob/b0568b20c13017d09c6565905a5c4cfa8d19ee2b/lib/parent-namespace.ts#L121

I think the code should be modified something like:
```
class ParentBroadcastAdapter extends Adapter {
  private readonly children: Set<
    Namespace<ListenEvents, EmitEvents, ServerSideEvents, SocketData>
  > ;
  constructor(parentNsp: any, private readonly children: Set<Namespace>) {
    super(parentNsp);

     this.children = children;
  }

  broadcast(packet: any, opts: BroadcastOptions) {
    this.children.forEach((nsp) => {
      nsp.adapter.broadcast(packet, opts);
    });
  }
}
```

**Comment by darrachequesne** [comment]
Hi! That's weird, the `children` attribute should be initialized with the `readonly` tag:

https://github.com/socketio/socket.io/blob/b0568b20c13017d09c6565905a5c4cfa8d19ee2b/lib/parent-namespace.ts#L116-L118

In `dist/parent-namespace.js`:

```js
class ParentBroadcastAdapter extends socket_io_adapter_1.Adapter {
    constructor(parentNsp, children) {
        super(parentNsp);
        this.children = children;
    }
    broadcast(packet, opts) {
        this.children.forEach((nsp) => {
            nsp.adapter.broadcast(packet, opts);
        });
    }
}
```

So I'm not sure how `this.children` can be undefined there... Thoughts?

**Comment by peterjuras** [comment]
Hi,
I'm experiencing the same issue. I'm using https://github.com/socketio/socket.io-redis-streams-adapter maybe that is the source of the issue?

**Comment by gkt5015** [comment]
Hi, is there an update on this?

I believe the issue here is that `this.children` isn't declared yet when `super` is called in the `ParentNamespace` class. The constructor of `Namespace` will call `_initAdapter` of the subclass with the undefined value. Prior to the change, `this.children` was enclosed in the function so it wasn't an issue.

Perhaps one way to change this would be:
```ts
class ParentBroadcastAdapter extends socket_io_adapter_1.Adapter {
    constructor(parentNsp) {
        super(parentNsp);
        this.parentNsp = parentNsp;
    }
    broadcast(packet, opts) {
        this.parentNsp.children.forEach((nsp) => {
            nsp.adapter.broadcast(packet, opts);
        });
    }
}
```

**Comment by Hippopop** [comment]
Hi! I am using the latest version of the package. And I am facing this exact same issue!
I'm not sure why that's happening and how to resolve it?!?

```
/Volumes/Development/NodeJs/Personal/full-stack-chat-app/chat-server/node_modules/socket.io/dist/parent-namespace.js:88
        this.children.forEach((nsp) => {
                      ^
TypeError: Cannot read properties of undefined (reading 'forEach')
    at ParentBroadcastAdapter.broadcast (/Volumes/Development/NodeJs/Personal/full-stack-chat-app/chat-server/node_modules/socket.io/dist/parent-namespace.js:88:23)
    at BroadcastOperator.emit (/Volumes/Development/NodeJs/Personal/full-stack-chat-app/chat-server/node_modules/socket.io/dist/broadcast-operator.js:169:26)
    at Namespace.<anonymous> (/Volumes/Development/NodeJs/Personal/full-stack-chat-app/chat-server/src/socket_io/chat_process/chat_process.ts:35:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by darrachequesne** [comment]
@Hippopop I don't think the fix has been released yet. Let me check.

**Comment by Hippopop** [comment]
@darrachequesne Yeah, I think that's the case. But I've been trying to to use the package/library directly from the GitHub. And use the #main brunch. Sadly that's not working either. 
```
npm error Cannot read properties of undefined (reading 'spec')
npm error A complete log of this run can be found in: ...
```

Is there anything I can do here?!? I'm a bit new with `Node.Js` and `npm`.
