### ISSUE TITLE
Simplify Socket.Io Docs by Removing `createServer`

### ISSUE THREAD

**Issue by priyankarpal** [socketio/socket.io#5003]
In the Socket.IO documentation, consider removing references to `createServer()` and adding the use of `app.listen()` for server setup. This adjustment would streamline the documentation and make it more accessible, particularly for users who are new to Socket.IO and Express

### Before 
```js
import express from 'express';
import { createServer } from 'node:http';

const app = express();
const server = createServer(app);

app.get('/', (req, res) => {
  res.send('<h1>Hello world</h1>');
});

server.listen(3000, () => {
  console.log('server running at http://localhost:3000');
});
```

### After
```js
import express from 'express';

const app = express();

app.get('/', (req, res) => {
  res.send('<h1>Hello world</h1>');
});

app.listen(3000, () => {
  console.log('server running at http://localhost:3000');
});


```

**Comment by darrachequesne** [comment]
Hi! I'm not sure that this is a good idea, as the current way indicates that the Node.js HTTP server can be shared between Socket.IO and Express:

Current version (explicit):

```js
import express from 'express';
import { createServer } from 'node:http';
import { io } from 'socket.io';

const app = express();
const httpServer = createServer(app);

app.get('/', (req, res) => {
  res.send('<h1>Hello world</h1>');
});

httpServer.listen(3000, () => {
  console.log('server running at http://localhost:3000');
});

const io = new Server(httpServer);
```

Suggested version (implicit):

```js
import express from 'express';
import { io } from 'socket.io';

const app = express();

app.get('/', (req, res) => {
  res.send('<h1>Hello world</h1>');
});

const httpServer = app.listen(3000, () => {
  console.log('server running at http://localhost:3000');
});

const io = new Server(httpServer);
```

There is also the risk that people mix the two:

```js
import express from 'express';
import { createServer } from 'node:http';
import { io } from 'socket.io';

const app = express();
const httpServer = createServer(app);

app.get('/', (req, res) => {
  res.send('<h1>Hello world</h1>');
});

aop.listen(3000, () => {
  console.log('server running at http://localhost:3000');
});

const io = new Server(httpServer);
```

Which does not work because `app.listen()` creates another HTTP server.

Does that make sense?

**Comment by menderptl14** [comment]
import express from 'express';
import { createServer } from 'node:http';
import { io } from 'socket.io';

const app = express();
const httpServer = createServer(app);
const PORT = 3000;

app.get('/', (req, res) => {
  res.send('<h1>Hello GIT</h1>');
});

httpServer.listen(PORT, () => {
  console.log('server running at http://localhost:${PORT');
});

const io = new Server(httpServer);

**Comment by darrachequesne** [comment]
I think this can be closed now. Please reopen if needed.
