### ISSUE TITLE
Issue #5049 didn't fix ws for socket.io-adapter

### ISSUE THREAD

**Issue by miszczu-drako** [socketio/socket.io#5051]
npm audit --audit-level=high --package-lock-only --omit=dev --omit=optional

npm audit report
ws 8.0.0 - 8.17.0
Severity: high
ws affected by a DoS when handling a request with many HTTP headers - https://github.com/advisories/GHSA-3h5v-q93c-6h6q
fix available via npm audit fix --force
Will install socket.io@4.5.4, which is a breaking change
node_modules/socket.io-adapter/node_modules/ws
socket.io-adapter >=2.5.2
Depends on vulnerable versions of ws
node_modules/socket.io-adapter
socket.io >=4.6.0-alpha1
Depends on vulnerable versions of socket.io-adapter
node_modules/socket.io

3 high severity vulnerabilities

**Comment by sordu** [comment]
`npm update socket.io-adapter`
and
`npm update engine.io`

bumps `ws` in both and resolves the CVE on my local machine

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-adapter/commit/93fe19019e1c0b82a41a15bd86acbac10634c60b, included in `socket.io-adapter@2.5.5`.

@miszczu-drako could you please check?

**Comment by miszczu-drako** [comment]
yes, no more vulnerabilities found. Thanks a lot for a quick response!
