### ISSUE TITLE
socket.io + Angular SSR  = ping timeout

### ISSUE THREAD

**Issue by Talb2005** [socketio/socket.io#5061]
**Describe the bug**

When using socket.io in an Angular project with Server Side Rendering enabled, the socket disconnects after 70 seconds (with default pingTimeout and pingInterval values).
Setting lower pingTimeout and pingInterval values will trigger the disconnects after a shorter time period. 
This issue **does not occur on socket.io version 4.3.2**, but it does occur in version 4.4.0 and above. 

**To Reproduce**

1. Clone the [Minimal Reproducible Example](https://github.com/Talb2005/angular-ssr-socket.io-issue)
2. Run npm install to install the dependencies. 
3. Run `npm run build:dev` to build the project in development mode.  
4. Run `npm run serve:ssr:dev` to serve the project in development mode.
5. Navigate to http://localhost:3000/ and open the developers console. 
6. Observe that "Socket disconnected after X seconds. Reason: ping timeout" is logged every `pingTimeout + (pingInterval * 2)`

**Expected behavior**
The socket should stay connected continuously.

**Platform:**
 - Device: macOS (but I believe this doesn't matter). 
 - OS: macOS Sonoma 14.5 (but I believe this doesn't matter). 

**Additional context**
- If instead of the latest socket.io version (4.7.5) I install socket.io version 4.3.2 this issue doesn't occur. The socket stays connected as expected. 
- The issue does occur in socket.io versions 4.4.0 and above. 
- If I connect to a different socket.io server, which isn't part of the Angular SSR project, the issue doesn't occur.

**Comment by Talb2005** [comment]
I'm closing this issue, since it appears to be caused by a bug in Angular's zone.js, which will be fixed in https://github.com/angular/angular/pull/56852.

**Comment by darrachequesne** [comment]
@Talb2005 thanks a lot for the detailed analysis :+1:

It seems the issue you linked to was closed, does it solve the problem?

For reference, the `timeout.refresh()` method was added in [this commit](https://github.com/socketio/engine.io/commit/37474c7e67be7c5f25f9ca2d4ea99f3a256bd2de), included in `engine.io@6.1.0` and `socket.io@4.1.0`.

**Comment by Talb2005** [comment]
@darrachequesne my pleasure :) 
Yes I've closed the issue because it isn't really a socket.io bug, rather a bug in zone.js which is a part of Angular. 
The bug was fixed in the latest release of zone.js (0.14.8), thus fixing the ping timeout issue.
