### ISSUE TITLE
Pulls in @types/node

### ISSUE THREAD

**Issue by laino** [socketio/socket.io#5065]
In ``build/esm/index.d.ts`` and ``build/cjs/index.d.ts`` the following line is emitted:

```ts
/// <reference types="node" />
```

This will cause any (in-)direct import to pull in node types, polluting the global namespace.

To illustrate why this is an issue:

```ts
import { Socket } from 'socket.io-client';

//  error TS2322: Type 'Timeout' is not assignable to type 'number'.
const timeout: number = setTimeout(() => {}, 0);
```

The issue was introduced with version ``5.2.2`` and this commit: https://github.com/socketio/engine.io-parser/commit/0305b4a7a597e0f070ce8ea17106121f9ab369bc

The last good version is ``5.2.1``.

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io/commit/f9cb983ab7050c0a1630cfc97eb30f2dd807186b, included in `engine.io-parser@5.2.3`.

 @laino could you please check?

**Comment by laino** [comment]
It's fixed. Thanks!
