### ISSUE TITLE
Error with uWebSockets.js: uWS.HttpResponse must not be accessed after uWS.HttpResponse.onAborted callback

### ISSUE THREAD

**Issue by eighthlucky** [socketio/socket.io#5066]
**Describe the bug**
When running `socket.io` and `uNetworking/uWebSockets.js`, we sometimes get this error:

```
Error: uWS.HttpResponse must not be accessed after uWS.HttpResponse.onAborted callback, or after a successful response. See documentation for uWS.HttpResponse and consult the user manual.
```

It happens rarely (~10 times in last 30 days). We've recently come up with a way to replicate it locally, although I'm not sure if it's the same cause as on production.

**To Reproduce**

Engine.IO server version: `6.6.0`
Engine.IO client version: `6.5.4`

```js
import { Server } from 'socket.io';
import { connect } from 'socket.io-client';
import { App as createApp } from 'uWebSockets.js';

const PORT = 3000;
const SERVER_URL = `http://localhost:${PORT}`;

// Initialize socket.io server with uWebSockets app
const server = new Server({ serveClient: false });
const app = createApp();
server.attachApp(app);

// Listen and wait for it to be ready
await new Promise((r) => app.listen(PORT, r));

// Create a new socket.io client and wait for it to connect
const socket = connect(SERVER_URL);
await new Promise((r) => socket.once('connect', r));

// Mimic a new socket.io client connection with an already connected session ID
// Engine.io will close the connection, but will incorrectly attempt to upgrade it afterwards
// See https://github.com/socketio/engine.io/blob/6.6.0/lib/userver.ts#L213
try {
  new WebSocket(
    `ws://localhost:3000/socket.io/?EIO=4&transport=websocket&sid=${socket.io.engine.id}`,
  );
} catch {}

// Exit when there is no error
setTimeout(() => process.exit(0), 2_000);
```

**Note**: The above snippet will require Node 22 to run.

**Expected behavior**
I expect it to exit normally after the 2s timeout.

**Actual behavior**
It crashes with the error message mentioned above.

**Platform:**
 - Device: MacBook Pro 2019
 - OS: Ventura
 - Node versions: 20.13.1, 20.15.0, 22.3.0

**Additional context**

* I have a branch that replicates the issue: https://github.com/eighthlucky/npm-bug-replication/tree/engine.io-uWS.HttpResponse
  - It also has a patch which seems to fix the issue on my end
* We can also replicate this in the browser by trying to open a duplicate WebSocket connection via the console (similar to the above approach)
  - Just copy+paste the WebSocket URL from the browser's network inspector

**Comment by darrachequesne** [comment]
For future readers:

This should be fixed by https://github.com/socketio/socket.io/commit/d5095fe98c3976673c19f433c0114d06dbd8de1b, included in `engine.io@6.6.1` and `socket.io@4.8.0`.

**Comment by eighthlucky** [comment]
Thanks!
