### ISSUE TITLE
Why engine.io never try the second transport

### ISSUE THREAD

**Issue by SijieDingEsna** [socketio/socket.io#5090]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/engine.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
I have a socket.io server which apply socket.io + express and it only supports websocket. If transports is set as ['polling', 'websocket'] in client side, engine.io-client always try polling infinity and never try websocket. 
* [ ] request a *feature*

### Expected behaviour
Once the socket.io server side return status 400 and the payload is {"code":0,"message":"Transport unknown"}. The client side should be smart enough to try the second protocol. Because your document suggestion is polling is at first and the default transports is ['polling', 'websocket']. So I think under such transport setting of client, engine.io-client should be tolerable enough to handle such condition.

### Setup
- OS:
- browser:
- engine.io version:

**Comment by darrachequesne** [comment]
For future readers:

The `tryAllTransports` option makes the client test each transport:

```js
import { io } from "socket.io-client";

const socket = io({
  tryAllTransports: true
});
```

Reference: https://socket.io/docs/v4/client-options/#tryalltransports

Implemented in https://github.com/socketio/engine.io-client/commit/579b243e89ac7dc58233f9844ef70817364ecf52, included in `engine.io-client@6.6.0` and `socket.io-client@4.8.0`.
