### ISSUE TITLE
questions about the source-code

### ISSUE THREAD

**Issue by david-fong** [socketio/socket.io#5106]
Background: I'm preparing a PR to add more typing information now that the repo is written in typescript (🎉). I was wondering if you can explain some things for me.

- Why does the manager check for whether `this.backoff` is undefined sometimes? Are there actually times when it is not defined?
- can the `serveClient` option for the manager ever be the empty string? If it should never be the empty string, we can use `??` instead of `||` when defaulting the option.
- why use component-bind package instead of javascript's native [`Function.prototype.bind`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind)? Isn't it okay to do `this.ondata.bind(this)` (which is the same as `Manager.prototype.ondata.bind(this)`) instead of `bind(this, "ondata")`? One advantage of using native bind is that typescript will check that the types make sense.
- Would these fields 
![image](https://user-images.githubusercontent.com/42986768/101275919-55bf8380-375e-11eb-9fdb-e3fa2ac6a938.png) ever need to be used outside of the Socket class? Would it be a good and safe idea to completely prevent code outside of the Socket class from accessing those fields? If so, we could use [JavaScript private fields](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#ecmascript-private-fields). But... this would be a breaking change, since any dependent packages accessing those fields would no longer be able to use them.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
