### ISSUE TITLE
Won't switch to polling transport when Websocket transport failed

### ISSUE THREAD

**Issue by hassansin** [socketio/socket.io#5122]
**Describe the bug**
I'm trying to connect with `websocket` transport first and if it fails I was hoping socketio would switch to long-polling. But for some reason, it keeps reconnecting with `websocket` transport and never switches to polling. 

![image](https://github.com/socketio/socket.io-client/assets/4618044/07921dac-1779-4acd-9947-a3baa793da67)

**To Reproduce**

Socket.IO server version: `4.7.2`

*Server*

```js
const { Server } = require("socket.io");
const express = require("express");
const http = require("http");

const server = http.createServer(express());
const io = new Server({
	transports: ["polling", "websocket"],
});
io.on("connection", socket => {
	console.log("New Connection");
});

io.attach(server);
server.listen(3000);
```

Socket.IO client version: `4.7.2`

*Client*

```js
import { io } from "socket.io-client";
const socket = io({
    transports: ["websocket", "polling"],
});
socket.on("connect_error", err => {
    console.log("connect_error", err);
})
```

**Expected behavior**
Was expecting the transport would switch to long-polling when websocket isn't available.

**Platform:**
 - Device: Firefox 120
 - OS: Windows 10

**Additional context**
I disabled websocket by blocking websocket calls using the Firefox request blocking feature. Can be disabled using [this TamperMonkey script](https://greasyfork.org/en/scripts/421454-disable-websockets) as well.

**Comment by darrachequesne** [comment]
For future readers:

The `tryAllTransports` option let the client test all transports instead of just the first one:

```js
import { io } from "socket.io-client";

const socket = io({
  tryAllTransports: true
});
```

Reference: https://socket.io/docs/v4/client-options/#transports

Implemented in https://github.com/socketio/engine.io-client/commit/579b243e89ac7dc58233f9844ef70817364ecf52, included in `engine.io-client@6.6.0` and `socket.io-client@4.8.0`.
