### ISSUE TITLE
Minor: Event handler of 'offline' event must be added on the initial evaluation of worker script on Service Worker

### ISSUE THREAD

**Issue by wanfahmi11** [socketio/socket.io#5125]
**Describe the bug**
Getting a warning when including socket.io client to service worker:

![image](https://github.com/socketio/socket.io-client/assets/44287448/be632196-1f77-4676-82b4-6a894441fc91)

Event handler of 'offline' event must be added on the initial evaluation of worker script on Service Worker

**To Reproduce**

Socket.IO server version: `4.7.4`

*Server*

```js
import { Server } from "socket.io";

const io = new Server(3000, {});

io.on("connection", (socket) => {
  console.log(`connect ${socket.id}`);

  socket.on("disconnect", () => {
    console.log(`disconnect ${socket.id}`);
  });
});
```

Socket.IO client version: `4.7.4`

*Client*

```js
import { io } from "socket.io-client";

const socket = io("ws://localhost:3000/", {});

socket.on("connect", () => {
  console.log(`connect ${socket.id}`);
});

socket.on("disconnect", () => {
  console.log("disconnect");
});
```

**Expected behavior**
Probably can skip adding "offline" event listener for service worker, since it's already skipped it for offline, I don't see any harm skipping it for service worker.

**Platform:**
 - Device: [e.g. Samsung S8]
 - OS: [e.g. Android 9.2]

**Additional context**
I would like to contribute myself but I can't find the exact line to modify. I can find the codes in dist/socket.io.js but I'm not sure if that's the right file.

**Comment by FMaz008** [comment]
Is there a milestone for this fix? I just installed socket.io (current version being 4.7.5) and I'm encountering this very same warning.

**Comment by darrachequesne** [comment]
@FMaz008 out of curiosity, could you please explain your use case? Why use a ServiceWorker and not a SharedWorker?

**Comment by FMaz008** [comment]
> @FMaz008 out of curiosity, could you please explain your use case? Why use a ServiceWorker and not a SharedWorker?

Honestly everything works fine with the Service Worker coupled with an Alarm. That and I had never heard of a Shared Worker before today. So it seems I'm just outdated a bit on my knowledge here.

(Not to side track the conversation, but I tried implementing a SharedWorker, but I keep getting a security error. But even assuming I could sort out this problem, it would be a major refactor of the existing code if it worked.)

**Comment by darrachequesne** [comment]
For future readers:

This should be fixed by https://github.com/socketio/socket.io/commit/8a2f5a3da0addb386e7a0f4970e1a9696b82797e, included in `engine.io-client@6.6.1` and `socket.io-client@4.8.0`.
