### ISSUE TITLE
Inherited `ws` package bump for socket-io.client

### ISSUE THREAD

**Issue by benkeen** [socketio/socket.io#5131]
I see `engine.io-client` has had its `ws` version bumped to 8.17.1 to patch a DoS vulnerability in that library. `socket-io.client` still references the older version of `engine.io-client`. Could we get that package bumped to the latest version? It's not picking up the new minor version due to using "~".

Thanks!

**Comment by darrachequesne** [comment]
Hi!

`socket.io-client@4.7.5` depends on `engine.io-client@~6.5.2`, which should install `engine.io-client@6.5.4` and thus `ws@8.17.1`. Isn't that the case for you?

**Comment by benkeen** [comment]
Apologies, you're right! We're still getting `engine.io-client@6.5.3` in our deps, curious. This is on our end. :) 

Really appreciate the help.
