### ISSUE TITLE
The footer link to roadmap is wrong

### ISSUE THREAD

**Issue by gelzinn** [socketio/socket.io#5141]
**Describe the bug**

![image](https://github.com/user-attachments/assets/4540d6d8-9a9b-49c2-bee9-286ff75a910b)

**To Reproduce**

Open [socket.io](https://socket.io/) website and scroll to footer.

**Image**

![image](https://github.com/user-attachments/assets/ae8379b1-d995-4d1b-865e-57a3dba2de83)

`https://github.com/socketio/socket.io/projects/3` -> `https://github.com/orgs/socketio/projects/3`

**Comment by darrachequesne** [comment]
Good catch, thanks! The link on the website has been updated: https://github.com/socketio/socket.io-website/commit/58eadf0fd77148a3b56a92eb7b37059b62233831
