### ISSUE TITLE
"io is not defined" after adding import/export

### ISSUE THREAD

**Issue by hmathers** [socketio/socket.io#5155]
Hello,

I've been working with two different projects that are structured mostly the same, but there's an error happening with socket (v4.7.5) in one that isn't happening in the other

Project A throws no errors, it has a main.js file, a server.js file, and a client.js file; main exports some stuff to server and client, and client doesn't export anything but it does define `const socket = io({path:"/path/to/socket.io"})`

Project B has a main.js file and a server.js file and until a few days ago there was no need for the client.js file. The main file in this case is the one that has `const socket = io({path:"/path/to/socket.io"})` which works fine, but when I try to export something from main to server I start getting "ReferenceError: io is not defined" as soon as I add the line `import * as main from "./main.js"` in server (not when I add "export" in main)

Client side, both index.html files mostly just do this:
```
<script defer src="/path/to/socket.io/socket.io.min.js"></script>
<script defer src="main.js" type="module"></script>
<!-- <script defer src="client.js" type="module"></script> -->
```

And the server files start like this:
```
import express from "express"
import http from "node:http"
import {Server} from "socket.io"
// import * as main from "./main.js"
const app = express(), httpServer = http.createServer(app),
io = new Server(httpServer,{path:"/to/socket.io"})
```

**Comment by jokester** [comment]
> as soon as I add the line `import * as main` from "./main.js" in server (not when I add "export" in main)

sorry I'm confused. isn't `main.js` meant to be imported from another client script?

**Comment by hmathers** [comment]
> > as soon as I add the line `import * as main` from "./main.js" in server (not when I add "export" in main)
> 
> sorry I'm confused. isn't `main.js` meant to be imported from another client script?

Is that where I'm going wrong? I don't have that much experience with JS, would the idea be that exporting something from main and creating the client io() in it as well is just something we're not supposed to do? Importing main to the client script would be the solution like you said but I just didn't see any reason for the error since it's not like I'm exporting the socket variable

**Comment by jokester** [comment]
can't really grasp what you have at hand. do you happen to have a reproduction repo?

**Comment by hmathers** [comment]
Here's the simplest I can make it, with three one-line files:

main.js:
`const socket = io()`

server.js:
`import * as main from "./main.js"`
(remove this or declare socket in another file to fix the error)

package.json:
`{"dependencies": {"socket.io": ""}, "type": "module"}`

run npm i
run node server.js
"ReferenceError: io is not defined"

I was convinced this was a problem with socket because I thought that was the only difference between my two projects, but I tried commenting the offending line out and it gave me another error saying that document is also not defined which the first project doesn't reference in main either. So my lack of experience with ES6 is really showing here I guess (I converted from CommonJS only recently)? Sorry for the off-topic issue

**Comment by semiharslanait** [comment]
The issue you're facing stems from trying to use client-side code (io(), which is part of the Socket.io client library) in a server-side context. The io object is not available on the server side, which is why you're getting the "ReferenceError: io is not defined" error.

To resolve this, you need to separate your client-side and server-side code properly.
