### ISSUE TITLE
issues Connecting to Socket.IO on Nginx Server via Postman

### ISSUE THREAD

**Issue by yassineMessaoud9** [socketio/socket.io#5159]
Hello everyone,

I'm new to Nginx and I'm trying to connect to a Socket.IO endpoint via Postman. My Node.js project is deployed on an Nginx server. When I attempt to connect to my endpoint at https://octoc-api.dev.ip-label.io/api, I encounter the following error:

Could not connect to https://octoc-api.dev.ip-label.io/api
18:54:02
Error: Invalid namespace
Handshake Details
Request URL: https://octoc-api.dev.ip-label.io/socket.io/?EIO=4&transport=websocket
Request Method: GET
Request Headers
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: hel82z6Ibahidpqk60XpyQ==
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Host: octoc-api.dev.ip-label.io,
However, when I try connecting to https://octoc-api.dev.ip-label.io, the connection succeeds, but it doesn't match with my Express project folder structure.

Here is my Nginx configuration file:

server {
    listen 80;
    server_name octoc-api.dev.ip-label.io;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name octoc-api.dev.ip-label.io;

    ssl_certificate /etc/ssl/certs/ekara.crt;
    ssl_certificate_key /etc/ssl/private/ekara.key;

    location /api {
        rewrite ^/api(.*)$ $1 break;
        proxy_pass http://localhost:3002;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /socket.io/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;

        proxy_pass http://localhost:3002;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
My server.js file is as follows:

const express = require('express');
const { createServer } = require('http');
const { Server } = require('socket.io');

const app = express();
const http = createServer(app);
const io = new Server(http, {
    cors: {
        origin: '*',
        credentials: true,
    },
});

initSocketCommunication(io);
global.io = io;

http.listen(3002, () => {
    console.log('Server is listening on port 3002');
});
And my socket.js file:

export default function initSocketCommunication(io) {
    io.on('connection', (socket) => {
        console.log('Client Connected.', socket.id);

        socket.emit('hello', { message: 'Hello from server!' });

        socket.on('disconnect', (reason) => {
            console.log('Client Disconnected.', reason);
            socket.broadcast.emit('user_leave', reason);
        });

        socket.on('send_noc_room', async (data) => {
            try {
                await CreateNocRoom2({ body: data, params: { id: data.creator } }, {}, io);
                console.log('NOC room created and data sent!');
            } catch (err) {
                console.error('Error in send_noc_room:', err);
            }
        });

        socket.on('send_troubleShooting_invitation', async function (data) {
            try {
                console.log(data);
                await SetInvitedParties(data.troubleshooting_id, data.invited);

                data.invited.forEach((userID) => {
                    io.emit(`get_invitation/${userID}`, {
                        tr_id: data.troubleshooting_id,
                        senderID: data.senderID,
                        message: data.message,
                        senderName: data.senderName,
                    });

                    console.log(`Invitation emitted to user: ${userID}`);
                });
            } catch (error) {
                console.error(`Failed to emit 'get_invitation': ${error}`);
            }
        });
    });
}
Can someone help me understand how to configure Nginx and my Node.js project correctly so that I can connect to https://octoc-api.dev.ip-label.io/api using Socket.IO via Postman?

Any guidance or suggestions would be greatly appreciated.

Thank you!

**Comment by av-waseem** [comment]
hi yassine i have the same issue how did you fix this issue i have nginx socket namespace is like this /socket/ 
and i want to https://domain/socket/vc or im events

**Comment by yassineMessaoud9** [comment]
I have added /api as the namespace in the backend connection.

**Comment by av-waseem** [comment]
api is working fine on port 8000 but socket not working on 8080 when it's deploy locally it's working
