### ISSUE TITLE
Webtransport is not defined in typing

### ISSUE THREAD

**Issue by jtapeg** [socketio/socket.io#5161]
I'm using the latest version of socket.io

![image](https://github.com/user-attachments/assets/da958591-1520-4037-a589-60dfb167308b)

**Comment by TXWSLYF** [comment]
It seems that socket.io@4.7.5 depends on engine.io version ~6.5.2. 
<img width="938" alt="image" src="https://github.com/user-attachments/assets/a6ae58c6-b219-4a69-b575-40dd1a4a1359">
However, the highest version in the 6.5.x range is 6.5.5, and this version of Type Transport does not include webtransport.
<img width="1166" alt="image" src="https://github.com/user-attachments/assets/4a820bd6-c4fb-44b5-a9f0-ee324e471b32">

Maybe just upgrading the socket.io dependency version for engine.io from ~6.5.2 to ~6.6.0 can solve this problem.

**Comment by jtapeg** [comment]
The problem is that socket.io imports its own engine.io so there is no point in installing it manually.

![image](https://github.com/user-attachments/assets/258f3712-2dc7-47f9-9041-8d6dd69fc000)

**Comment by TXWSLYF** [comment]
yes, the socket.io itself need to update the version of engine.io

**Comment by darrachequesne** [comment]
For future readers:

The `webtransport` value was added in https://github.com/socketio/socket.io/commit/c310b7b6b66236f312f017583a67f81389fa5d72, included in `engine.io@6.6.0` and `socket.io@4.8.0`.
