### ISSUE TITLE
When a send a big data to server, I can't get 413 error by listen ‘disconnect’ event

### ISSUE THREAD

**Issue by shuntian** [socketio/socket.io#5177]
socket.io: 4.6.1
socket.io-client: 4.6.1

**Comment by darrachequesne** [comment]
Hi! You can use the second argument of the `disconnect` event:

```js
socket.on("disconnect", (reason, details) => {
  console.log(reason); // "transport error"

  // in that case, details is an error object
  console.log(details.message); "xhr post error"
  console.log(details.description); // 413 (the HTTP status of the response)

  // details.context refers to the XMLHttpRequest object
  console.log(details.context.status); // 413
  console.log(details.context.responseText); // ""
});
```

**Comment by darrachequesne** [comment]
I think this can be closed now. Please reopen if needed.

**Comment by shuntian** [comment]
Tanks for your answer, but when i listen 'disconnect' event, i only get detail message is 
![image](https://github.com/user-attachments/assets/4f37a032-0f30-4c88-a7f9-3b9c12b467b8)

Only listen 'error' message can get the 413 error, But need to reconnect several times to get the corresponding error。
![image](https://github.com/user-attachments/assets/95330088-efec-41c2-ad70-8cd3a8468c4c)
