### ISSUE TITLE
Specify transport type or autocompletion.

### ISSUE THREAD

**Issue by nayounsang** [socketio/socket.io#5187]
**Is your feature request related to a problem? Please describe.**
```
import { io } from "socket.io-client";
    const newSocket = io(process.env.HELLO, {
      withCredentials: true,
      transports: [], // something...
    });
```

**Describe the solution you'd like**
I was able to specify specific transports.
I think it would be more convenient if it was auto-completed.

**Describe alternatives you've considered**
A different type instead of string[]
**Additional context**

**Comment by darrachequesne** [comment]
For future readers:

This should be fixed by https://github.com/socketio/socket.io/commit/b5ccfd4838b901c7c4efd1e5e07a0bd083620619, included in `engine.io-client@6.6.1` and `socket.io-client@4.8.0`.
