### ISSUE TITLE
vuln: cookie package

### ISSUE THREAD

**Issue by k725** [socketio/socket.io#5206]
before version 0.7.0 `cookie` package has vuln (https://github.com/advisories/GHSA-pxg6-pf52-xh8x).
https://github.com/socketio/socket.io/blob/d0fc72042068e7eaef448941add617f05e1ec236/packages/engine.io/package.json#L39

**Comment by GustavPS** [comment]
Anyone looking at this? Our `audit` fails because of the cookie dependency.

**Comment by darrachequesne** [comment]
`cookie` has been bumped to version `~0.7.2` in https://github.com/socketio/socket.io/commit/88efd446f137007c3706908643510f589040b4dc, released in `engine.io@6.6.2`.

**Comment by GustavPS** [comment]
Will there be a new socket.io release with the new engine.io dependency anytime soon?
