### ISSUE TITLE
socket.io client not receiving

### ISSUE THREAD

**Issue by parindam** [socketio/socket.io#521]
I am using socket.io in nodejs and I am able to send data from client to server. But when I emit from server, the client does not seem to be receiving this... What am i missing ?

server:

socket = io.listen(app);
socket.sockets.on('connection', function(client){ 
client.on('something-from-client', function(msg){
           console.log(msg);
       //do something.
       client.emit('some-result',{"total":docs.length});
   });
});
client:

var socket = io.connect('http://localhost:9999');
socket.on('some-result', function(data){
    console.log('received from server', data);
});
socket.emit("something-from-client",  {"lat":lat, "lng":lng});

NB: I also posted the same message in stackoverflow. If I get my answer there, I'll post it here.

**Comment by parthmern** [comment]
how did you solve it i am also facing similar
