### ISSUE TITLE
cookie package dependency vulnerability that was fixed in version cookie@0.7.0 but socket.io use cookie@0.4.1

### ISSUE THREAD

**Issue by daeteck** [socketio/socket.io#5222]
**Impact**
The cookie name could be used to set other fields of the cookie, resulting in an unexpected cookie value. For example, serialize("userName=<script>alert('XSS3')</script>; Max-Age=2592000; a", value) would result in "userName=<script>alert('XSS3')</script>; Max-Age=2592000; a=test", setting userName cookie to <script> and ignoring value.

A similar escape can be used for path and domain, which could be abused to alter other fields of the cookie.

**Patches**
Upgrade to 0.7.0, which updates the validation for name, path, and domain.

**Workarounds**
Avoid passing untrusted or arbitrary values for these fields, ensure they are set by the application instead of user input.

**References**
https://github.com/jshttp/cookie/pull/167

**Comment by darrachequesne** [comment]
Done in https://github.com/socketio/socket.io/commit/88efd446f137007c3706908643510f589040b4dc, included in `engine.io@6.6.2` (and `socket.io@4.8.x`).

Thanks for the heads-up :+1:
