### ISSUE TITLE
 share the same socket.io channel among browser tabs

### ISSUE THREAD

**Issue by soleiljy** [socketio/socket.io#597]
Hi,

It could be a dumb question, but i would like to get some help.

Let's suppose a browser opened with 100 tabs. In the current socket.io implementation, i think each tab would make its own connection with the server, and therefore 100 different socket.io channels would be generated.

Question: Is there any way to share the same socket.io channel among browser tabs which use the same (domain) cookie?

thanks in advance

**Comment by tankerkiller125** [comment]
https://www.npmjs.com/package/socketio-shared-webworker is a fork of socket.io that does exactly what is wanted here. Using the webworker it is able to have multiple tabs that can communicate between one another.
