### ISSUE TITLE
websocket error in https (websocket network error)

### ISSUE THREAD

**Issue by gitawego** [socketio/socket.io#606]
I'm constantly getting this error in safari while using websocket mode in https:

WebSocket network error: The operation couldn\U2019t be completed. (OSStatus error -2146762495.)

I'm using safari 5.1.1 with socket.io 0.8.5 and nodejs 0.4.12 in Ubuntu 11.10

any idea ?

thanks in advance.

**Comment by nishantpandya** [comment]
Hi guys, I am facing same issues. I have to try to run the kurento room demo over Safari (Version 5.1.7) but getting the same error. Could anyone have any solution or suggestion?
