### ISSUE TITLE
client-side disconnect is not detected

### ISSUE THREAD

**Issue by domino14** [socketio/socket.io#635]
```
var socketio = io.connect(socketServer, 
                {rememberTransport: false, 
                'reconnect': true,
                'reconnection delay': 500,
                'max reconnection attempts': 10,
                'secure': true});

socketio.on('disconnect', function() {
    alert('client socketio disconnect!')
});
```

The alert shows up if I take down the Node server, but not if I turn off my wireless, or close my laptop and re-open it later. The connection is lost though. Is there a better way to detect disconnect on the client side? This is with the WebSockets transport.

**Comment by sthang** [comment]
We are having this same issue on 1.3.6 version of socket.io. The node server in our case is not getting the disconnect event from client when wireless is shut off or laptop is closed.

**Comment by blented** [comment]
+1

**Comment by protozoo** [comment]
I am experiencing this same issue, using version 1.4.3. Why is the issue closed?
Thanks

**Comment by iamisti** [comment]
Please re-open this ticket, since it's not yet fixed!

**Comment by probil** [comment]
Have the same issue. Could be reproduced in chrome without actual internet disconnection. Just open `Developer tools` -> `Network tab` -> Choose `offline` from selectbox.

**Comment by aeolusheath** [comment]
any news that can work?

**Comment by kandebonfim** [comment]
Saaaame issue!

**Comment by kandebonfim** [comment]
Please reopen this, It's not fixed!

**Comment by mercior** [comment]
Agreed - this is still a problem for me also

**Comment by mbf5923** [comment]
hi
i use this solution and fine for me
var io = require('socket.io')(http, {'pingInterval': 2000, 'pingTimeout': 5000});
http://stackoverflow.com/a/31787022/2818627

**Comment by inceptivetech** [comment]
Hi,
Still not found a good solution for this issue. I turned off my wifi connection set browser mode to offline still disconnect event of socket.io was not raised. was it due to local connection?

Regards,
Suhas

**Comment by ashleymorris2** [comment]
+1

**Comment by hifall** [comment]
Same issue. This issue needs to be fixed.

**Comment by loint** [comment]
+1

**Comment by radavel** [comment]
I have the same issue, event disconnect client-side not detected

**Comment by darrachequesne** [comment]
- Did anyone try to debug with `localStorage.debug='*'`?
- Does it happen only with websocket transport?
- Which version of socket.io are you using?

**Comment by darrachequesne** [comment]
I just tested with the chat example (socket.io `1.7.2` ; chrome ; linux):

![image](https://cloud.githubusercontent.com/assets/13031701/21161636/a49e1b5a-c189-11e6-9881-95ce3e99a314.png)

Websocket gets established:
23:09:37.709 => ping
23:09:37.934 => pong (server response)
23:10:02.938 => ping
23:10:03.169 => pong
**I switch off the WIFI**
23:10:28.171 => ping
**wait for 60s** => timeout => `disconnect` gets fired

25s being the default value for `pingInterval`, 60s for `pingTimeout` ([ref](https://github.com/socketio/engine.io#methods-1))

Can anyone confirm/infirm that behaviour?

Also, if the server gets killed, I think that the disconnect event will be fired immediately since the underlying TCP connection will be closed.

**Comment by creole** [comment]
I can confirm this behavior: disconnect gets fired on both server and client if a network cable is unplugged. However, there is also the case where the client gets disconnected from the server without any events being fired. The below screenshots are from a client that is no longer emitting to the server. No disconnect events have been fired (either on the client or on the server). Note that the client still seems to be receiving pongs from the server:

![socketio](https://cloud.githubusercontent.com/assets/6288734/21688085/d3fd7d0c-d36b-11e6-88b5-f251c8dadf44.png)

![socketio2](https://cloud.githubusercontent.com/assets/6288734/21688090/d8a84986-d36b-11e6-8de9-b592f4553369.png)

![socketio3](https://cloud.githubusercontent.com/assets/6288734/21688093/dcba8f52-d36b-11e6-896a-ac2282d0bbb5.png)

**Comment by darrachequesne** [comment]
> there is also the case where the client gets disconnected from the server without any events being fired

Hmm, I don't understand, how do you know the client gets disconnected then?

**Comment by creole** [comment]
Yeah, "disconnected" is probably not the right wording. The issue is that the client stops emitting to the server, although it is still receiving pongs from it. In the last screenshot I posted, socket.emit should have been called in between the ping pong events, but somehow it hasn't.

**Comment by darrachequesne** [comment]
So, if I understand correctly, the socket is still emitting pings/getting pongs, but `socket.emit()` gets discarded?

Can you reproduce easily? Is it linked to a given browser?

Ref: https://github.com/socketio/socket.io-client/blob/1.7.2/lib/socket.js#L155
```js
  if (this.connected) {
    this.packet(packet);
  } else {
    this.sendBuffer.push(packet);
  }
```
But the only way the `connected` flag is set to `false` is [here](https://github.com/socketio/socket.io-client/blob/1.7.2/lib/socket.js#L204):
```js
Socket.prototype.onclose = function (reason) {
  debug('close (%s)', reason);
  this.connected = false;
  this.disconnected = true;
  delete this.id;
  this.emit('disconnect', reason);
};
```
So it shouldn't be discarded here, since you didn't get the `disconnect` event. Else, if we look in [engine.io-client](https://github.com/socketio/engine.io-client/blob/1.8.2/lib/socket.js#L605):
```js
Socket.prototype.sendPacket = function (type, data, options, fn) {
  //...
  if ('closing' === this.readyState || 'closed' === this.readyState) {
    return;
  }
```
The `readyState` flag is updated [here](https://github.com/socketio/engine.io-client/blob/1.8.2/lib/socket.js#L631).

**Comment by creole** [comment]
> So, if I understand correctly, the socket is still emitting pings/getting pongs, but socket.emit() gets discarded?

Yes, that's it. Will try to find a way to reproduce.

**Comment by creole** [comment]
@darrachequesne Turns out my own code was blocking calls to socket.emit. Apologies for having wasted your time. My issue was not the same as the issue of this thread.

**Comment by darrachequesne** [comment]
@creole great, thanks!

To all others who +1'ed, has my comment https://github.com/socketio/socket.io/issues/635#issuecomment-266880918 fixed (or at least explained) your issue?

In any case, maybe a smaller default value for `pingTimeout` would help? Currently in the worst case one must wait 85s (25000 (pingInterval) + 60000 (pingTimeout)) before getting a `disconnect` event. How about a `pingTimeout` of 5s by default?

**Comment by llaakso** [comment]
Changing default setting so much can lead to unexpected behavior in some implementations, but I agree dropping `pingTimeout `to around 30s would be more purposeful.

**Comment by jamilservicos** [comment]
It might be useful
[https://gist.github.com/jamilservicos/e7c09e3701a7ba5ff817096ef8426d94](https://gist.github.com/jamilservicos/e7c09e3701a7ba5ff817096ef8426d94)

**Comment by abitlog** [comment]
Experiencing this problem as well.. Changing ping interval does not seem reliable enough in production

**Comment by abitlog** [comment]
As long as the bug will not be resolved shortly and a final purpose of what we need is to indicate if user has left, we can extend our socket object by using middleware. Basically, we need to extend socket object with a user and a room the user is currently in and after user got disconnected we can use that properly as we need. Full code is available at: https://github.com/abitlog/retube/blob/master/server/utils/socket.js
```
  io.use(checkAuth);

  io.on('connection', function (socket) {
    socket.on('join chatroom', function (data) {
      const { id: room } = data;

      socket.join(room);

      io.to(room).emit('join chatroom', {
        user: socket.user,
        counter: socket.adapter.rooms[room].length
      });

      socket.currentChatroomId = room; // extend an object after user joins a room
    });

    socket.on('leave chatroom', function (data) { // this event will not be fired as long as client-side disconnect does not work
      const { id: room } = data;

      io.to(room).emit('leave chatroom', {
        user: socket.user,
        counter: socket.adapter.rooms[room] ? socket.adapter.rooms[room].length - 1 : null
      });

      socket.leave(room);
    });

    socket.on('disconnect', function () {
      const { currentChatroomId } = socket;

      io.to(currentChatroomId).emit('leave chatroom', { // we use currentChatroomId from our socket object to indicate the room user has left
        user: socket.user,
        counter: socket.adapter.rooms[currentChatroomId] ? socket.adapter.rooms[currentChatroomId].length  : null
      });

    });
  });

  function checkAuth(socket, next) {
    if (!socket.request.session.passport) {
      next(new AuthError(404));
      return;
    }

    socket.user = socket.request.session.passport.user;

    next();
  }
```

**Comment by darrachequesne** [comment]
@abitlog I may be missing something here, but your use case is not related to the current issue, right? 

Please take a look at the [disconnecting](https://github.com/socketio/socket.io/blob/master/docs/API.md#event-disconnecting) event.

**Comment by KamWis** [comment]
@darrachequesne I investigated the issue and it seems all events are working fine. It's just in Chrome for mac (didn't notice this in windows version) taking long time (approx 1 min) to trigger disconnect. I tried of course `timeout` and `connect_error` as attempt to suplement `disconnect` as a sibling event but no luck there.

**Comment by darrachequesne** [comment]
@KamWis which value are you using for `pingTimeout/pingInterval`?

**Comment by brenc** [comment]
This came up in Slack today so I started to look at this myself. Here is a related ticket with lots of good information from another project:

https://github.com/ptaoussanis/sente/issues/259

Testing with Chrome on Windows 10 and Chromium in a Xubuntu 16.04 VM, socket.io 1.7.3, polling and websocket transports enabled. By the time I disconnect the network to test this, my connection is using websockets.

I know pingTimeout and pingInterval get sent to the client in the handshake. I set those to 15000 and 5000 respectively. Then, I reloaded my client and disconnected the network cable and waited. From the time I disconnected the network cable and lose network connectivity, it took about 1 minute 20 seconds before the client fired the `disconnect` event with reason `ping timeout`. This is pretty reproducible - each time it's always around 1:20. This is in line with what the people in the linked ticket are seeing as well.

I would expect that the client would be receiving those values from the server and disconnecting with a ping timeout after 15 seconds, but this is not happening for whatever reason in Chrome (maybe others too, haven't tested that yet). I think the linked ticket has a lot of information that also applies here. 

My quick workaround for this was to implement my own ping system. I emit a ping message every 5 seconds and then set a timeout that waits for a pong. If none is received within 15 seconds, I can then detect that and handle it appropriately. Something like this:

```
function ping () {
  if (disconnectTimer) {
    clearTimeout(disconnectTimer)
  }

  setTimeout(function () {
    debug('sending ping message')
    
    socket.emit('message', {
      name: 'ping'
    })

    disconnectTimer = setTimeout(function () {
      debug('no pong message received, closing connection...')
      // Handle abnormal close here.
      socket.close()
    }, 15000)
  }, 5000)
}
```

I haven't tested this very well, but it seems to be working reliably so far.

I might dig into this a bit more today and see if I can figure out why the client isn't disconnecting with a ping timeout when it should be.

**Comment by brenc** [comment]
I just went through all of my connection settings again and I must have had a typo somewhere. When I set `pingTimeout` and `pingInterval` on the server, the client appears to respect that even in Chrome. If anyone else is having problems and wants to test this, it helps to set `localStorage.debug = 'engine.io-client:socket'` in your browser. This will make ping/pong messages show in the console.

**Comment by darrachequesne** [comment]
I guess the issue can be closed now?

**Comment by brenc** [comment]
Yep, I believe so. Looks like everything is working as expected.

**Comment by Royalone-mobile** [comment]
I can detect disconnect event but it took time at least 8-10 seconds.
would you tell me why it does happen?

**Comment by darrachequesne** [comment]
@Royalone-mobile please update the `pingInterval / pingTimeout` values.

**Comment by liujiusheng** [comment]
I have solved this problem.
it may be a bug of chrome. it‘s still online when we set the network to "`offline`" mode(谷歌浏览器把网络模式设置为offline的时候websocket好像同样可以通信，网络并没有真正断掉，可以换用两个设备用物理上的断网方式你们自己验证一下是不是这个原因).
the right way is use` socket.on('disconnect',function(){})`.
but pingInterval default value is 25000,pingTimeout default value is 60000.it's too long.
so we need to set pingInterval / pingTimeout to a small value.
(其实disconnect事件是可以监听到用户掉线的，只是谷歌浏览器的使用不当埋了第一个坑，然后这个自动掉线检测时间比较长又埋了第二个坑，只需要把pingInterval设置短一点就可以很快检测到用户掉线了)

**Comment by developerKumar** [comment]
Hi guys,

Any luck with this? I am also facing the same issue.

**Comment by irvanherz** [comment]
Got it working smoothly on local server. Socket io fire disconnect event immediately each client disconnected. But dunno why it didn't same on real server

**Comment by pankajgupta1** [comment]
on mobile device working fine, but facing same problem on desktop/laptop.
