### ISSUE TITLE
Listening to 'connection' event with io.on not working

### ISSUE THREAD

**Issue by mabmierau** [socketio/socket.io#713]
Tried to work through the first example in "How to use" using version 0.8.7, and found that it worked if I called `io.of('').on` but not `io.on`. It looks like the 'connection' event was emitted from SocketNamespace, but `io.on` was adding the listener to Manager.

**Comment by gowthamyaal** [comment]
I'm still getting the error even after using 


`io.sockets.on(server,function(sockets){
console.log("check connection"); //console is not printing anything
});`


 my socket version is 2.1.1;

**Comment by shahkrutarth** [comment]
I am facing same issue console is not printing anything. 
Socket version: 2.1.1

**Comment by Marianne00** [comment]
me too :(

**Comment by Juwdohr** [comment]
I am also getting the same thing. I have been looking for the past 2 days. Has anyone found out why?

**Comment by SKPnation** [comment]
I'm also getting the same error

**Comment by aliparsa** [comment]
same here :-/

**Comment by rayyan808** [comment]
Anybody found a fix?

**Comment by darrachequesne** [comment]
@rayyan808 this is a closed issue from 2012. Please open another one, with all necessary details. Thanks!

**Comment by Debasish00** [comment]
Could anyone help with this ?

**Comment by A-K-M-Fozlol-Hoq** [comment]
it worked for me: https://stackoverflow.com/questions/44628363/socket-io-access-control-allow-origin-error
