### ISSUE TITLE
Reconnect on error

### ISSUE THREAD

**Issue by xpepermint** [socketio/socket.io#716]
Soocket.io Client does not try to reconnect on the first page load. 

Steps:
1. Turn off the server.
2. Open your website (browser refresh).

It should try to reconnect itself but it just triggers the Socket.prototype.onError with e="" and the process is finished. In that case a user must manually refresh page to see if the server is already up and running...

**Comment by saisasank-c247** [comment]
attempt to reconnect has failed I am getting like this will you give me any solution

**Comment by darrachequesne** [comment]
@saisasank-c247 could you please open a new issue with all necessary details? This issue is reaaally old.
