### ISSUE TITLE
Server-Sent Events transport

### ISSUE THREAD

**Issue by mscdex** [socketio/socket.io#730]
I recently wrote a transport for using XHR for sending and Server-Sent Events for receiving. In my opinion SSE provides a great alternative to the overhead of websockets (especially if you're mostly receiving data and not sending very often).

Also, there were some recent changes to the SSE editor's draft that show possible upcoming support for cross-origin usage: http://dev.w3.org/html5/eventsource/. Mozilla has already committed changes to utilize this usage based on this draft: https://hg.mozilla.org/mozilla-central/rev/ed783dfd8179. This will make SSE even more handy/useful. I have already taken the initiative to add support for this in the transport as well.

Is there any interest in adding a transport like this?

**Comment by adrai** [comment]
Any opinion or plan to add SSE in v1.x?

**Comment by JohnBaileyN** [comment]
Why was this closed?

**Comment by rauchg** [comment]
SSE doesn't provide any meaningful advantage to us over WS.

**Comment by njh** [comment]
> SSE doesn't provide any meaningful advantage to us over WS.

Any more details on why you think this?

Here are some of the reasons why I think Server Sent Events are worthwhile:

* It is just plain HTTP not a separate protocol
  * falls back to long-polling, if client/server don't have specific support for it
  * works with unmodified HTTP proxies
* It is less generic than Websockets, which means it is possible to build a generic distribution server, that doesn't require application logic
  * it would therefore also be possible to provide a commercial SSE CDN service

**Comment by passcod** [comment]
SSE+HTTP2 means a single connection over a single port, which provides interesting advantages as well.

**Comment by rauchg** [comment]
True. Very close to polling+HTTP2 for the time being.

**Comment by JohnBaileyN** [comment]
@passcod What do you mean by "single"? Do you mean persistent on one instance?

**Comment by passcod** [comment]
As per [section 9.1 of the HTTP/2 spec](https://httpwg.github.io/specs/rfc7540.html#HttpExtra):

> Clients SHOULD NOT open more than one HTTP/2 connection to **a given host and port pair**, where the host is derived from a URI, a selected alternative service [ALT-SVC], or a configured proxy.
>
> A client can create additional connections as **replacements**, either to replace connections that are near to exhausting the available stream identifier space (Section 5.1.1), to refresh the keying material for a TLS connection, or to replace connections that have encountered errors (Section 5.4.1).
>
> A client MAY open multiple connections to the same IP address and TCP port using **different Server Name Indication** [TLS-EXT] values or to provide different TLS client certificates but SHOULD avoid creating multiple connections with the same configuration.
>
> Servers are encouraged to maintain open connections for as long as possible but are permitted to terminate idle connections if necessary.

(All emphasis mine.)

It is my understanding that a browser is a _single_ client. Thus, _all_ requests, SSE streams, Server Push, etc for _all_ tabs of a browser connecting to a single domain/port pair would go through the _same_ multiplexed TCP connection.

**Comment by runvnc** [comment]
Then the conclusion is that socket.io is an outdated library.  I will select an alternative.

**Comment by mkonecny** [comment]
@runvnc did you find any alternatives?

**Comment by runvnc** [comment]
Off the top of my head I don't remember a comprehensive wrapper like socket.to but if you can restrict the browsers at all then you can use plain websockets or HTTP 2 server push.

**Comment by Leo-Mu** [comment]
> Off the top of my head I don't remember a comprehensive wrapper like socket.to but if you can restrict the browsers at all then you can use plain websockets or HTTP 2 server push.

So this is painful right, especially after QUIC and HTTP/3 announced. Today this is already a very necessary feature.

**Comment by qlaffont** [comment]
any update on this ?

**Comment by darrachequesne** [comment]
@qlaffont there are currently no plans to add support for server-sent events, as they do not seem to provide any substantial benefits over WebSocket. I'm open to discussion though.

On a related note, we have added support for [WebTransport](https://developer.mozilla.org/en-US/docs/Web/API/WebTransport) in version [4.7.0](https://socket.io/docs/v4/changelog/4.7.0).
