### ISSUE TITLE
Server-side namespaced disconnect

### ISSUE THREAD

**Issue by DanielBaulig** [socketio/socket.io#795]
As far as I can tell disconnecting from a namespace is only possible from the client side. It does not seem to be possible to disconnect a client from just a namespace from the server side.

Forced disconnection from the server is an essential feature. Multiplexing over a single connection is hampered a lot if a server can only disconnect a client from all namespaces at once. E.g. a module based on socket.io might disconnect a socket if something goes wrong badly. One couldn't pull in that module and use it on a multiplexed connection in it's own namespace without it interfering with other stuff going on on that connection.

The code for dealing with namespaced disconnects essentially is present. The protocol also specifies it. And it is already possible, from the client side. 

What do you guys think?

**Comment by broject** [comment]
> Yep, that's definitely something we need to change =] Thanks for bringing this up

why do not fix this problems "client namespace disconnect". i never call disconnect event normal process. but call disconnect it is very trouble to all developers.!!

**Comment by broject** [comment]
WHY This issue was closed.
WHERE IS SOLUTIONS ?????????????????????????????????

**Comment by laneschmidt** [comment]
this is still happening immediately after connecting.

here's my implementation:

```
// server.js
// version: "socket.io": "^2.3.0",

const express = require('express');
const http = require('http');
const cors = require('cors');
const socketIO = require('socket.io');

import { generateToken } from '../utils/helpers');

const port = 80;
const app = express().use(cors);
const server = http.Server(app);
const io = socketIO(server);

io.on('connection', (socket) => {
  console.log('Socket connected');

  const token = await generateToken();

  socket.on('ping', () => {
    io.emit('ping', 'pong');
  });

  socket.on('disconnect', (reason) => {
    console.log('Socket disconnected. Reason:', reason);
  });
});

server.listen(port, () => {
  console.log(`Server started on port ${port}`);
});
```

```
// AppComponent.tsx
// version: "socket.io-client": "^2.3.0",

import io from 'socket.io-client';

...

const socket = io(socketURL);
socket.emit('ping');
socket.on('ping', (res: any) => console.log('res', res));
```

i have verbose debugging enabled but can't see any errors in the console, so i can see that it connects then immediately disconnects. 

the frontend logs: 
```
browser.js:133 socket.io-client:socket server disconnect (/) +2ms
browser.js:133 socket.io-client:manager disconnect +17ms
engine.io-client:socket socket close with reason: "forced close" +2ms
```

the server logs: `Socket disconnected. Reason: server namespace disconnect`. 

nothing is telling to to disconnect.
