### ISSUE TITLE
When emitting in room, clients in room are sent multiple copies of the same message

### ISSUE THREAD

**Issue by KyleAMathews** [socketio/socket.io#803]
Sometimes even 100s of messages. I can't figure out what might be causing this. Is it possible there's something I'm doing wrong? If not, I'm happy to debug further but some pointers would be very helpful.

**Comment by basickarl** [comment]
Same problem here, ta hah.

**Comment by Chidt12** [comment]
the same =))

**Comment by darrachequesne** [comment]
@Chidt12 could you please open a new issue? Thanks.

**Comment by nikhilcares22** [comment]
I'm having same issue as I'm using proces.emit and on for inter file communication so how can I sort this ?

**Comment by darrachequesne** [comment]
@nikhilcares22 please post your question on StackOverflow with all necessary details. Thanks!
