### ISSUE TITLE
Additional listener on refresh

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io#839]
When I connect socket.io, I can debug values that get passed around fine. The problem occurs when I refresh (any) browser, then I get two values on each submit. If I refresh again, I get three values, and so forth. When I get past 11 I get too much listeners warning from Event Emitter. It appears as listeners don't get removed on refresh of browser.

Server side:

``` javascript
io.sockets.on('connection', function (socket) {         
  socket.on('message', function (data) {
    socket.emit('message', data);
  });
});
```

Client side:

``` javascript
$(document).ready(function() {
  var chat = io.connect('http://localhost.com',{port:3000});
  chat.on('message', function (data) {
    $('.chat').append('<p>' + data.text + '</p>');
  });   
  $('#say').submit(function(e) {
    e.preventDefault();
    chat.emit('message', { text: $('input', this).val() });
    $('input', this).val('');
  });
}); 
```

**Comment by Kalki-CricHeroes** [comment]
What was the solution then?

**Comment by darrachequesne** [comment]
@Kalki-CricHeroes could you please provide a way to reproduce the issue, based on https://github.com/socketio/socket.io-fiddle? Thanks!
