### ISSUE TITLE
CPU 100% with Redis Store

### ISSUE THREAD

**Issue by mindon** [socketio/socket.io#862]
When i use cluster & redis store, the CPU usage is easily reach 100%.

with strace, mass of these found:

```
write(2358, "HTTP/1.1 200 OK\r\nContent-Type: t"..., 179) = 179
write(7, "*3\r\n$7\r\npublish\r\n$9\r\nhandshake\r\n"..., 397) = 397
read(2359, "GET /socket.io/1/?t=133560705283"..., 65536) = 124
```

---

what's wrong? (a few slowlog results found in redis-cli.)

when running in single process without Redis store, everything works fine.

Any recommend configuration of redis, best for socket.io? Thanks.

**Comment by imwillhang** [comment]
has this been fixed yet?

**Comment by kiennguyen07** [comment]
I think we still have this issue at this moment 2021. My server still easy get 100% with 5k connections

**Comment by darrachequesne** [comment]
@kiennguyen07 could you please open a new issue with all necessary details? Thanks!
