### ISSUE TITLE
balancer without sticky sessions and more than 1 process

### ISSUE THREAD

**Issue by kof** [socketio/socket.io#939]
It turns out socket.io has never worked behind balancer without sticky sessions support if you scale to multiple processes. This is the case on heroku.

node 0.6.18
socket.io 0.9.6 (tested both the version from master and npm)

I have modified the chat example to demostrate the issue, it is 100% reproducible.

https://github.com/kof/socket.io/tree/master/examples/chat

```
node cluster
```

use the server on port 3000.

cluster will use proxy and spawn 3 nodejs instances which will listen on different portrs. It will forward every request to a different server.

You will see that .emit callback mostly does not work, same is without a callback, just listening to events on the client. Messages from server does not reach the client.

Thanks.

**Comment by vijayaa** [comment]
can you please provide sample code snippet for this. We are not able to get ipadress behind haproxy
