### ISSUE TITLE
WebSocket network error: OSStatus Error -9812: valid cert chain, untrusted root 

### ISSUE THREAD

**Issue by samccone** [socketio/socket.io#940]
Only in Safari

using a self signed certificate 

I propose in the the arguments you are able to pass a flag to detect if safari and fall back to plain ol WS 

http://blog.marcon.me/post/24874118286/secure-websockets-safari

https://github.com/LearnBoost/socket.io/commit/ffa8994a23f826f71d6c23dd6161dee562fda136

**Comment by wasa4587** [comment]
5 years after still being a frustrating issue

**Comment by leosco** [comment]
It looks like this is happening on Firefox *on Mac only* as well. Works fine on Windows...
