### ISSUE TITLE
Console logs "Booting Client" around 100 times, then crashes.

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io#953]
I have a bug(?) with my node.js. And I think it has something to do with socket.io. So what it does is Logging "Booting Client" around a hundred times, then it crashes with the error:

util.js:35   var str = String(f).replace(formatRegExp, function(x) {                       ^ RangeError: Maximum call stack size exceeded

I am guessing that the stack size is exceeded because Socket.io is doing "booting client" so many times.

**Comment by sivatumma** [comment]
I am kind of not satisfied with this answer. Mine is a similar issue, Help if you can find some answer...
Here is my code
`

var app = require('express')();
var server = require('http').Server(app);
var io = require('socket.io')(server);

io.on('connection', function(socket) {
  console.log("Client connected through 'connect' socket.io ");
  socket.emit('data',{siva:"is thumma"});

  /**********************************************************************************************
   ************   SPECIAL CODE THAT FETCHES DEVICE DATA - DON'T DISTURB UNLESS YOU KNOW - BELOW */
  var server = require('net').createServer(function(deviceSocket) {
    deviceSocket.on('data', function(data) {
      var decodedDeviceData = data.toString('utf8');
      console.log("Data from client", data);
      deviceSocket.emit('data',data);
      deviceSocket.emit('data', decodedDeviceData);

    });
  });


  // server.on('connection', function(c) {    console.log("Connected a device");  });
  // server.on('listening', function() {    console.log("Listening now");  });
  // server.on('data', function(d) {    console.log("Here is d", d);  });
  // server.on('end', function() {    console.log("This client is disconnecting, disconnected");  });

  server.listen(5062, "0.0.0.0");

  /**************************************************************************************
   *******   SPECIAL CODE THAT FETCHES DEVICE DATA - DON'T DISTURB UNLESS YOU KNOW ABOVE */
});

`
